### ISSUE TITLE
PM2 id0 worker online, 0 exited code 8

### ISSUE THREAD

**Issue by btmdave** [Unitech/pm2#1003]
We're using pm2 v0.12.4, since we upgraded when running one of our apps we get the following coming from PM2:

```
PM2: 2015-02-09T20:36:58.730Z : /var/www/site/worker.js - id0 worker online
PM2: 2015-02-09T20:36:58.778Z : Script /var/www/site/worker.js 0 exited code 8
```

This seems to be a conuinous loop that just repeats this (with date updating) over and over again, about 5x a second.

Any ideas what could be causing this?

**Comment by btmdave** [comment]
Just to add, when running from the command line without pm2, there's no exceptions or anything, seems to be only when running via pm2

**Comment by jshkurti** [comment]
Is --watch enabled ?

**Comment by btmdave** [comment]
Sorry for the late reply, no `--watch` is not enabled.

**Comment by jshkurti** [comment]
This is strange, can I take a look at worker.js' code ?

**Comment by btmdave** [comment]
Hm, there's a ton of code.. lots of custom modules being used.  I tried running it on another server and everything is fine, so maybe it's a problem with the server.  Also, I have keymetrics running, but I disabled it and it still is doing it.

**Comment by BannedForLife** [comment]
Any updates. I am having this problem also

**Comment by jshkurti** [comment]
@BannedForLife can you tail some logs from `~/.pm2/pm2.log` at around the time the bug happenned ?
Also do `pm2 desc <id of your process>` to get the path of the err log file and have a look at those logs as well.
