### ISSUE TITLE
Unexpected behaviour with --watch option

### ISSUE THREAD

**Issue by jonathanasquier** [Unitech/PM2#1006]
Hello,
first of all thank you for your work on PM2

I'm monitoring a node rest API in which I make a call to ffmpeg (with the fluent-ffmpeg node module) which creates a child process each time it is called

It works fine,  except with the --watch option, the app is restarting as if changes were made on it.

I'm getting this:
Change detected for app name: <name> - restarting
Process with pid <number> still not killed, retrying...
App closed with code: 143

I'm don't know if it is related to the child process creation/deletion

Have you crossed this issue already?

Thanks a lot,

Jonathan

**Comment by soyuka** [comment]
Depends on what you're watching. 

Watch should only be used as a "development helper". It'll restart your server when a change is made on the file, or directory (recursivly) that you're watching.
Thoses unwanted changes could come from a temp file or a log beeing written in the path you're watching.

**Comment by jonathanasquier** [comment]
I'm watching the whole project folder, as a development helper only of course :)
I'll check on ffmpeg behaviour then.

thx

**Comment by soyuka** [comment]
I think there is a `tmp` file in the `cwd` beeing written by ffmpeg ;).
