### ISSUE TITLE
Log entries about Vizion

### ISSUE THREAD

**Issue by SmallRoomLabs** [Unitech/PM2#1007]
Viewing the logs using PM2 LOGS foobar are getting cluttered by, to me at least, irrelevant messages about Vizion.  Are these messages really meant to be shown by default?

[matseng@Server4 spool]$ pm2 --version
0.12.5
[matseng@Server4 spool]$ node --version
v0.10.30
[matseng@Server4 spool]$ uname -a
Linux name.not.shown.com 3.10.42-52.145.amzn1.x86_64 #1 SMP Tue Jun 10 23:46:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
merchantbalance-0 (out): DEB:terminalId=99999995
merchantbalance-0 (out): DEB:initializeResultObject()
merchantbalance-0 (out): DEB:Balance 49725 THB
merchantbalance-0 (out): INF:Built Reply 87 bytes, 17 bytes data
PM2: 2015-02-12 04:40:11: Vizion is already running for proc id: 7, skipping this round
PM2: 2015-02-12 04:40:11: Vizion is already running for proc id: 13, skipping this round
PM2: 2015-02-12 04:40:11: Vizion is already running for proc id: 23, skipping this round
PM2: 2015-02-12 04:40:41: Vizion is already running for proc id: 7, skipping this round
PM2: 2015-02-12 04:40:41: Vizion is already running for proc id: 13, skipping this round
PM2: 2015-02-12 04:40:41: Vizion is already running for proc id: 23, skipping this round
merchantbalance-0 (out): DEB:terminalId=99999990
```

**Comment by jshkurti** [comment]
You are absolutely right.
Fixed : https://github.com/Unitech/PM2/commit/a1ea26f058c3af8651303828e9b296e83b74befc

Thanks.
