### ISSUE TITLE
PM2 God using 100% on one of the cores in cluster mode

### ISSUE THREAD

**Issue by phahulin** [Unitech/PM2#1008]
Hi,
we have an app that serves a lot of requests, so the problem probably is not in pm2 but I would appreciate any insights.

We have `Ubuntu 14.04.1 LTS` on 8 CPUs server, `node 0.11.14` and `pm2 0.12.2`. We start application in cluster mode via `pm2 start server.js -i max`
![screen shot 2015-02-12 at 16 15 56](https://cloud.githubusercontent.com/assets/2278876/6168194/2437517c-b2d4-11e4-99cc-92b8d7ffe72e.png)
Applications seem to be running fine
![screen shot 2015-02-12 at 16 15 43](https://cloud.githubusercontent.com/assets/2278876/6168203/365af9b2-b2d4-11e4-8f19-1f9ebbeed982.png)
However at the same time in `$ htop` I see that one of the CPUs is utilized up to 100% by `pm2 God daemon` (great name btw) process
![screen shot 2015-02-12 at 16 14 38](https://cloud.githubusercontent.com/assets/2278876/6168211/4bf0b53c-b2d4-11e4-949b-6efb3edcbce9.png)
It will hold this core at 100% for a few seconds and then the usage will drop, but after another second it will be 100% again on another core... and then again on another core... It never reaches 100% CPU on two or more cores. Is this the correct behaviour?

Sometimes 100% will be holding on a single core for a minute or more and we start getting slow responses, below is the response time measured by pingdom.com
![screen shot 2015-02-12 at 16 13 30](https://cloud.githubusercontent.com/assets/2278876/6168302/3bdfbd9a-b2d5-11e4-9210-9c3542c8fe63.png)
We don't see any correlation between response time and the number of incoming requests/sec (as measured by cloudflare).

Should I start the process some other way? From reading the closed issues I see that I should probably try using `fork mode`. I'd like to try it, but didn't quite understand if the load-balancing feature will be abandoned and how can I spawn more than 1 process on server's cores?

Thanks in advance.

**Comment by soyuka** [comment]
I have no correct answer on this issue but I might point you to the right direction concerning clustering.

If you wanted to use the fork mode with multiple instances, pm2 would have to launch 4 applications that aren't listening on the same port (obvious). Then, you'd have to use something like HAProxy tol handle the load balancing. This way, it'll redirect requests on to one of your pm2 app in fork mode.

> It will hold this core at 100% for a few seconds and then the usage will drop, but after another second it will be 100% again on another core... and then again on another core... It never reaches 100% CPU on two or more cores. Is this the correct behaviour?

This is weird. The only thing that would come up to my mind doing things like this would be the "watcher" which you're not using. 
It would be nice having a way to reproduce this without having a whole application and by simulating requests with [wrk](https://github.com/wg/wrk); with and without pm2, to find the origin of the problem.

**Comment by fernandoneto** [comment]
What is the correct version of node? (14.04 as you describe look a little strange :) )
If you run node under version 11 there are problems with cluster mod. 
can you give the content of the logs?

**Comment by phahulin** [comment]
Sorry, it was node v0.11.smth, yesterday we upgraded to v0.12.0 to see if the issue will recur.

**Comment by fernandoneto** [comment]
but the problem persist?

**Comment by phahulin** [comment]
We haven't seen it today, but... today is Friday - the load on the server is below average... should wait for Monday to be sure.

**Comment by jshkurti** [comment]
Dit it happen again ?

**Comment by phahulin** [comment]
No, seems to be working fine now. I'll close the issue.

**Comment by jshkurti** [comment]
Thanks :)

**Comment by codyayers** [comment]
We seem to be having this issue.. Could it have to do with changing the number of cores on the virtualized machine after the initial installation of PM2? Are there files somewhere that store this information that cause PM2 to run multiple processes on a single core? We noticed with a single core you could start in cluster mode with 2 processes and it maxed out the single CPU just like it is now with 2 cores enabled.

**Comment by akashma19** [comment]
same with me...
i am using node and mysql, which is having thousands of rows

**Comment by vmarchaud** [comment]
@akashma19 Be sure that the issue is happening only with pm2 first, and second use latest version of pm2, lot of improvements as been made.

**Comment by akashma19** [comment]
i was facing problem because i was doing lots of data processing...
and node is not made for that...
shiffting everything to python ..
thnkx
