### ISSUE TITLE
running bash script casues 'had too many unstable restarts'

### ISSUE THREAD

**Issue by phishy** [Unitech/PM2#1012]
I'm trying to run:

pm2 start bin/test.sh -i 1 --cron "* * * * *"

test.sh contains "#!/binbash echo HELLO!"

I'm trying to make it run a bash command every minute, and ensure that it has one and only one copy ever running, but I'm getting "had too many unstable restarts"

Am I doing it wrong? ;-)

**Comment by jshkurti** [comment]
Yeah that's a normal behaviour for PM2, when your script ends, PM2 restarts it.
Apparently your script takes less than a second  to excecute so it restarts 15 times in a row and PM2 considers it should stop restarting it.

Have you considered child_process.spawn to launch your bash script ?
(http://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options)

This way it will be even easier to ensure it has only one instance running, you can set a global var flag for that and use cron inside your js code.

**Comment by dhatawesomedude** [comment]
This is an issue I am facing too. @phishy did you solve this?
