### ISSUE TITLE
Watch not working with express

### ISSUE THREAD

**Issue by NiklasMerz** [Unitech/PM2#1016]
If I am posting a duplicate or stupid question delete it.
But I think, I cant use watch with my express app.
The app isnt restarting with the --watch option or with i json with watch options.
can you please gve me a tip. I didnt find somthing on the internet.

**Comment by soyuka** [comment]
[Docs](https://github.com/Unitech/PM2/blob/master/ADVANCED_README.md#watch--restart).

Please give us your: pm2 version, node version, `json declaration`, `tail -n 100 ~/.pm2/pm2.log`.

**Comment by MeisterRoerich** [comment]
![version](https://cloud.githubusercontent.com/assets/3585860/6203314/be99ec96-b51a-11e4-8b59-b2f5279a82ad.png)

´{
  "apps" : [{
    "name"        : "Name",
    "script"      : "bin/www",
    "watch"       : true,
    "log_date_format"  : "DD-MM-YYYY HH:mm ",
    "instances"  : 0,
    "exec_mode"  : "cluster_mode",
    }]
  }

**Comment by Tjatse** [comment]
There is no necessary to enter CWD if you provide the `cwd` config, e.g.:
```JSON
{
  "apps": [{
    "name": "Name",
    "script": "bin/www",
    "cwd": "/path/to",
    "watch": true,
    "log_date_format": "DD-MM-YYYY HH:mm ",
    "instances": 0,
    "exec_mode": "cluster_mode",
  }]
}
```

BTW, your CWD should not contains `node_modules`.

**Comment by MeisterRoerich** [comment]
which path is cwd exactly?

sorry for dumb questions but i cant figure out to get it running

**Comment by soyuka** [comment]
Current working directory
Le dim. 15 févr. 2015 à 16:21, MeisterRoerich <notifications@github.com> a
écrit :

**Comment by zhulongzheng** [comment]
+1

**Comment by zhulongzheng** [comment]
Each time you modify one watched file, like a router file, you need to save the `express/bin/www` to let pm2 restart or reload.
