### ISSUE TITLE
Programmatic API doesn't show process

### ISSUE THREAD

**Issue by davidearlotto** [Unitech/PM2#1018]
Hi All, 
I'm having trouble with the programmatic api:
-I run this test script:
        
        var pm2 = require('pm2');
        pm2.connect(function() {
        pm2.start('test.js', { name: 'test'}, function(err, proc) {
          if (err) throw new Error('err');
       
          // Get all processes running
          pm2.list(function(err, process_list) {
             console.log(process_list);
            })
         });
        });

But the only log I'm getting on the console is:

       [PM2] Spawning PM2 daemon

Probably I'm missing something. At the moment the test.js just logs all the numbers
from 0 to 1000.
Thanks!
Cheers!

**Comment by jshkurti** [comment]
Can you ```pm2 logs``` in another window before launching your script and show us the output ?

**Comment by davidearlotto** [comment]
Thanks. I figured out some modules were missing. Now it starts, but it doesn't retrieve me the list of processes. The log is like this:

        PM2: 2015-02-16 19:41:21: [PM2][WORKER] Started with refreshing interval: 30000
        PM2: 2015-02-16 19:41:21: [[[[ PM2/God daemon launched ]]]]
        PM2: 2015-02-16 19:41:21: BUS system [READY] on port /home/davide/.pm2/pub.sock
        PM2: 2015-02-16 19:41:21: RPC interface [READY] on port /home/davide/.pm2/rpc.sock

And the file is like this:
       
        pm2.connect(function(){
            pm2.start(process.cwd() + '/Documents/Projects/zendesk_app_projects/test-pm2/test.js',
              {instances : 1},
              function(err, data) {
                  proc1 = data[0];           
                  console.log(proc1);
                  process.exit();
          });
        });

Thanks a lot

**Comment by davidearlotto** [comment]
Here is also the debug:

             pm2:constants PM2_ROOT_PATH: /home/davide/.pm2 +0ms
             pm2:satan [PING PM2] Trying to connect to server +74ms
             axon:sock client connect attempt 0.0.0.0:NaN +1ms
             axon:sock client error ECONNREFUSED +2ms
             axon:sock client ignored ECONNREFUSED +0ms
             axon:sock client attempting reconnect +102ms
             axon:sock client closing +1ms
             axon:sock client closing 0 connections +0ms
             pm2:satan Daemon not launched +0ms
             axon:sock client connect attempt 0.0.0.0:NaN +1ms
             [PM2] Spawning PM2 daemon
             pm2:satan Launching daemon +3ms
             pm2:satan env.PM2_HOME: undefined +0ms
             pm2:satan env.HOME: /home/davide +0ms
             pm2:satan env.HOMEPATH: undefined +1ms
             pm2:satan resolved HOME: /home/davide +0ms
             axon:sock client error ECONNREFUSED +8ms
             axon:sock client ignored ECONNREFUSED +1ms
             pm2:satan PM2 daemon launched +180ms { online: true, success: true, pid: 10167,              pm2_version: '0.12.5' }
             pm2:interface:daemon Interaction file does not exists +3ms
             [PM2] Success
             pm2:satan Launching RPC client on port /home/davide/.pm2/rpc.sock undefined +0ms
             axon:sock client connect attempt 0.0.0.0:NaN +0ms
             axon:sock client error ECONNREFUSED +0ms
             axon:sock client ignored ECONNREFUSED +0ms
             axon:sock client attempting reconnect +100ms
             axon:sock client connect attempt 0.0.0.0:NaN +0ms
             axon:sock client error ECONNREFUSED +0ms
             axon:sock client ignored ECONNREFUSED +0ms
  
Thanks!!!

**Comment by jshkurti** [comment]
Which version of pm2 are you using ?

**Comment by davidearlotto** [comment]
0.12.5

**Comment by davidearlotto** [comment]
I solved it installing the 1.0.0.
Sorry for bothering
