### ISSUE TITLE
latest NPM version and latest release on GH out of sync

### ISSUE THREAD

**Issue by askhogan** [Unitech/PM2#1019]
https://github.com/Unitech/PM2/releases

0.12.4

https://www.npmjs.com/package/pm2

0.12.5

**Comment by jshkurti** [comment]
I think it's a hotfix on the npm published version and you have to upgrade your version everytime you want to publish on npm :)
Otherwise :
https://github.com/Unitech/PM2/blob/master/package.json
```
  "version": "0.12.5",
```

Thanks for the feedback, appreciate it :)

**Comment by aaronroberson** [comment]
npm is currently at 0.15.10 but github is at 1.0.0. Please, someone with ownership of the npm package run `npm publish` to publish the updates to npm.
