### ISSUE TITLE
Controll logging of pm2 web

### ISSUE THREAD

**Issue by m-reiniger** [Unitech/PM2#1024]
Hi guys.

Is there a way to turn off the logging feature of pm2 web? Or at least have it log into /dev/null?

I am working on an API stack. I use pm2 web for a monitoring tool that constantly pulls data from the pm2-http-interface. The interface logs every request, which slowly but steadily fills up the disk.

Is there anything I can do to avoid this behaviour?

**Comment by jshkurti** [comment]
Done :)
https://github.com/Unitech/PM2/commit/01efed4b41ba83f3a9c10623ddb638adde199dc6

**Comment by m-reiniger** [comment]
That was quick. :) Thank you.
