### ISSUE TITLE
pm2 stuck in ``Starting execution sequence in -fork mode- for app name``

### ISSUE THREAD

**Issue by koraysels** [Unitech/pm2#1026]
I cannot get my application to start again. and if I do `pm2 logs` i get an infinite loop which looks like this 

indomoapp is an app i start with a json config.. 

```
########### Starting streaming logs for [all] process
PM2: nce in -fork mode- for app name:indomoapp id:0
PM2: 2015-02-18 15:32:06: App name:indomoapp id:0 online
PM2: 2015-02-18 15:32:07: App closed with code: 0
PM2: nce in -fork mode- for app name:indomoapp id:1
PM2: 2015-02-18 15:32:06: App name:indomoapp id:1 online
PM2: 2015-02-18 15:32:07: App closed with code: 0
PM2: nce in -fork mode- for app name:indomoapp id:0
PM2: 2015-02-18 15:32:07: App name:indomoapp id:0 online
PM2: 2015-02-18 15:32:08: App closed with code: 0
PM2: nce in -fork mode- for app name:indomoapp id:0
PM2: 2015-02-18 15:32:07: App name:indomoapp id:0 online
PM2: 2015-02-18 15:32:08: App closed with code: 0
PM2: nce in -fork mode- for app name:indomoapp id:1
PM2: 2015-02-18 15:32:07: App name:indomoapp id:1 online
PM2: 2015-02-18 15:32:08: App closed with code: 0
PM2: nce in -fork mode- for app name:indomoapp id:0
PM2: 2015-02-18 15:32:08: App name:indomoapp id:0 online
PM2: 2015-02-18 15:32:08: Starting execution sequence in -fork mode- for app name:indomoapp id:1
PM2: 2015-02-18 15:32:08: App name:indomoapp id:0 exited
PM2: 2015-02-18 15:32:08: Starting execution sequence in -fork mode- for app name:indomoapp id:0
PM2: 2015-02-18 15:32:08: App name:indomoapp id:0 online
PM2: 2015-02-18 15:32:10: App closed with code: 0
PM2: 2015-02-18 15:32:09: Starting execution sequence in -fork mode- for app name:indomoapp id:0
PM2: 2015-02-18 15:32:09: App name:indomoapp id:0 online
PM2: 2015-02-18 15:32:09: Starting execution sequence in -fork mode- for app name:indomoapp id:1
PM2: 2015-02-18 15:32:10: App name:indomoapp id:0 exited
PM2: 2015-02-18 15:32:10: Starting execution sequence in -fork mode- for app name:indomoapp id:0
PM2: 2015-02-18 15:32:10: App closed with code: 0
PM2: 2015-02-18 15:32:10: App name:indomoapp id:0 exited
PM2: 2015-02-18 15:32:10: Starting execution sequence in -fork mode- for app name:indomoapp id:0
PM2: 2015-02-18 15:32:10: App name:indomoapp id:0 online
PM2: 2015-02-18 15:32:10: Starting execution sequence in -fork mode- for app name:indomoapp id:1
PM2: 2015-02-18 15:32:10: App name:indomoapp id:1 online
PM2: 2015-02-18 15:32:11: App closed with code: 0
PM2: nce in -fork mode- for app name:indomoapp id:0
.....
```

**Comment by jshkurti** [comment]
Can you show us the json config file please ? :)
Does your app work fine if you just ```node app.js``` ?

**Comment by koraysels** [comment]
```{
  "apps": [
    {
      "name": "indomoapp",
      "script": "index.js",
      "args": [
      ],
      "log_date_format": "YYYY-MM-DD HH:mm Z",
      "ignore_watch": [
        "[\\/\\\\]\\./",
        "node_modules"
      ],
      "log_file": "logs/indomo-test.log",
      "watch": false,
      "node_args": "",
      "cwd": "",
      "env": {
        "NODE_ENV": "test",
        "PORT": "1333",
        "API_PORT": "1334"
      }
    }
  ]
}```

**Comment by ivanvoznyakovsky** [comment]
same here, ubuntu 12.04

**Comment by soyuka** [comment]
@ivanvoznyakovsky could you give us nodejs version, pm2 version and the config if you have one?

**Comment by ivanvoznyakovsky** [comment]
actually, I think I found the reason. I had 2 pm2 god daemons running from 2 different users. after killing pm2 daemons of one user this problem does not occur anymore.

**Comment by zackiles** [comment]
Bump. Is this intended by @Unitech ?

Am I not able to run 2 pm2 instances running under 2 different users? I am experiencing the same issue with an infinite loop/kill. Both PM2 daemons are running under non root users,with pm2 installed locally in each users /home. It seems if one of the apps crash that matches the 'app id' of an app in another instance, the other app will think the process has crashed and try to restart. Then what happens is both apps are restarting in an infinite feedback loop, each thinking their app has closed and restarting.

For clarity, im running a 'staging' user and 'production' user, which are essentially mirrors of each other. Both using same node/npm/pm2 versions, but with node app's running on different ports.

**Comment by jshkurti** [comment]
Intresting :)

**Comment by koraysels** [comment]
is there another good nodejs management tool to run it in production ? because I am afraid we cannot rely on pm2 for this in our situation :(

**Comment by gillesdemey** [comment]
I've ran into the very same situation a while back, where one of our developers accidentally started our services under a different user and caused them to be stuck in a never-ending restart loop. 

Killing the pm2 instance for that user solved the problem for us.

**Comment by MasaGon** [comment]
Same issue for me.

**Comment by Unitech** [comment]
It should be good now, please upgrade PM2:

```
$ npm install pm2@latest -g
$ pm2 update
```
