### ISSUE TITLE
app info not working

### ISSUE THREAD

**Issue by danymar24** [Unitech/PM2#1029]
Hello, i have updated node to the version 0.12 and i found that the pm2 info id it kind of doesn't works, the command gives me the info of the app but it also gives me this error:

Revision control metadata
/usr/lib/node_modules/pm2/node_modules/cli-table/lib/index.js:182
      var contents = item.toString().split("\n").reduce(function (memo, l) {
                         ^
TypeError: Cannot read property 'toString' of undefined
    at /usr/lib/node_modules/pm2/node_modules/cli-table/lib/index.js:182:26
    at Array.forEach (native)
    at generateRow (/usr/lib/node_modules/pm2/node_modules/cli-table/lib/index.js:181:11)
    at /usr/lib/node_modules/pm2/node_modules/cli-table/lib/index.js:275:16
    at Table.forEach (native)
    at Table.toString (/usr/lib/node_modules/pm2/node_modules/cli-table/lib/index.js:258:10)
    at Object.UX.describeTable (/usr/lib/node_modules/pm2/lib/CliUx.js:96:24)
    at /usr/lib/node_modules/pm2/lib/CLI.js:1146:12
    at Array.forEach (native)
    at /usr/lib/node_modules/pm2/lib/CLI.js:1145:18

**Comment by jshkurti** [comment]
Hey,
It was fixed, it will be on the next release (which is coming very soon).
Meanwhile, you can ```$ npm install git://github.com/Unitech/pm2#master -g``` and then ```$ pm2 update``` and it will be fine :)

Thanks for the feedback.
