### ISSUE TITLE
AppVeyor CI badge

### ISSUE THREAD

**Issue by jasonwilliams200OK** [Unitech/PM2#1032]
Add AppVeyor CI badge in README to reflect the status on Windows.

AppVeyor for node and io.js: http://www.appveyor.com/docs/lang/nodejs-iojs
AppVeyor.yml reference: http://www.appveyor.com/docs/appveyor-yml

**Comment by jshkurti** [comment]
Ok thanks :)

**Comment by Unitech** [comment]
Unfortunately PM2 contains a lot of bash tests :/
