### ISSUE TITLE
node_arg --harmony not working with coffee

### ISSUE THREAD

**Issue by bublik42** [Unitech/PM2#1033]
I have `"node_args": ["--harmony"]` option specified in ecosystem.json
yield keyword raises error when i'm using coffee. If I precompile file with `coffee -c` everything works fine

I'm using node 0.12.0, coffee 1.9.1 and pm2 0.12.5

In change log I noticed that in version 0.12.3

* Add back automatic coffee interpreter #488 #901 [e9a69fe]

Maybe that somehow caused the error

**Comment by Unitech** [comment]
When you want to launch a coffeescript source with harmony, do you do something like `coffee --harmony my-app.js` to enable harmony support?

**Comment by bublik42** [comment]
When I start coffee manually with harmony flag, everything is fine. But when I add `"node_args": ["--harmony"]` to the ecosystem.json and start coffee app with pm2 - harmony doesn't work. It seems like harmony flag isn't passed to coffee binary.

**Comment by Unitech** [comment]
Use `--next-gen-js` all ES6/ES7 features will be enabled!
