### ISSUE TITLE
pm2 and authbind

### ISSUE THREAD

**Issue by talkingtab** [Unitech/PM2#1038]
I have looked all around for something about running authbind with pm2 so I can replace my forever things. I haven't found much. What I did with forever was something like

authbind forever add blah blah

And that didn't work. Thinking that perhaps the PM2 god daemon had to be started with authbind, I killed every pm2 thing I could find and then started the first pm2 process with authbind
autbind pm2 start foo.

Is this correct?

Could we get something in the Readme about this?

**Comment by Unitech** [comment]
Do authbind would allow PM2 to bind app to the port 80 without permissions?

But yes you have to `pm2 kill` then use authbind to launch pm2, so the daemon will use these features. And everything worked 200 OK that way?

**Comment by talkingtab** [comment]
yes thanks!

**Comment by Unitech** [comment]
Awesome did not know about this utility, feel free to do a PR on the ADVANCED_README (https://github.com/Unitech/PM2/blob/master/ADVANCED_README.md)

Thank you!

**Comment by Unitech** [comment]
:

```
$ authbind --deep pm2 start http.js
```

**Comment by vphantom** [comment]
I wonder how we could make that play nice with pm2's system startup integration though.  I've seen that it can launch as a specific user, but I don't see an obvious way to launch it through authbind in doing so.

**Comment by soyuka** [comment]
You've to edit your startup file and change the command accordingly ;).

**Comment by vphantom** [comment]
Thank you! (I hadn't played with pm2's startup mechanism hands-on yet.)

**Comment by soyuka** [comment]
FIY, scripts are located here: https://github.com/Unitech/pm2/tree/master/lib/scripts
