### ISSUE TITLE
100% CPU usage after pm2 start on Windows

### ISSUE THREAD

**Issue by morkai** [Unitech/PM2#1039]
Hello!

When starting a new process, the CPU usage of the daemon (Satan.js) goes up to 100%, because of an infinite loop of `fs.exists()` calls.

`God.finalizeProcedure()` calls `vision.analyze()` with the full pm2's exec path and then goes down to the root path, where it should stop. The stop condition only checks for `/`, but on Windows the root path is `<disk letter>:\` (e.g. `C:\`) and thus the process never stops (non-stop checks whether `C:\.git`, `C:\.hg` and `C:\.svn` exist). [Check out this output from node-tick-processor.](https://gist.github.com/morkai/03b9a9885c79d1eb3cef)

The [God.js#L440](https://github.com/Unitech/PM2/blob/f7156d10ba1c4f95d98dfb56d90014aaa8e1a3cf/lib/God.js#L440) currently looks like this:
```js
    else if (err && current_path == '/') {
```
and should be something like:
```js
    else if (err && (current_path === '/' || /^[A-Za-z]:\\$/.test(current_path))) {
```

Windows 8.1 64-bit, Node.js v0.10.35, pm2 v0.12.6

**Comment by soyuka** [comment]
@echiu64 thoughts?

#584

**Comment by jshkurti** [comment]
It should be ok now, can you try ?
```$ npm install git://github.com/Unitech/pm2#development -g```

Thanks for the feedback.

**Comment by morkai** [comment]
It's OK now, 0% CPU usage :)

**Comment by jshkurti** [comment]
Glad I could help :)
