### ISSUE TITLE
Can pm2 survive a system reboot?

### ISSUE THREAD

**Issue by iansinnott** [Unitech/PM2#1046]
I recently had a digital ocean VPS crash on me and DO said they had to restart it manually. When I SSHed back in the VPS was running fine, but my node app was no longer running. `pm2 list` no longer displayed the app process at all.

So my question is, is there any way to avoid this? It would be great if pm2 would fire right back up when the server was rebooted.

Thanks for the help.

Versions:

* Node: `0.10.34`
* PM2: `0.12.3`

**Comment by soyuka** [comment]
```
pm2 startup --help
```
[Digital ocean tutorial with pm2 for a nodejs production environment on an ubuntu vps](https://www.digitalocean.com/community/tutorials/how-to-use-pm2-to-setup-a-node-js-production-environment-on-an-ubuntu-vps)
