### ISSUE TITLE
node 0.12 + latest pm2 release

### ISSUE THREAD

**Issue by adrai** [Unitech/PM2#1049]
when starting my processes I get:

PM2: 2015-02-27 09:50:21: ERROR CAUGHT BY DOMAIN:
PM2: AssertionError: false == true
PM2:     at RoundRobinHandle.add (cluster.js:140:3)
PM2:     at queryServer (cluster.js:480:12)
PM2:     at Worker.onmessage (cluster.js:438:7)
PM2:     at ChildProcess.<anonymous> (cluster.js:692:8)
PM2:     at ChildProcess.emit (events.js:129:20)
PM2:     at handleMessage (child_process.js:324:10)
PM2:     at Pipe.channel.onread (child_process.js:352:11)

my process.json file looks something like:

```json
{
  "apps": [
    {
      "name": "registry",
      "script": "./infrastructure/registry/server.js",
      "exec_mode": "fork_mode"
    },
    {
      "name": "authenticator",
      "script": "./authenticator/server.js",
      "instances": "1",
      "exec_mode": "cluster_mode"
    },
...
```

**Comment by Unitech** [comment]
Awesome, this will be fixed for the 0.12.1 so! We are getting to a more and more stable cluster module, this is great,
Closing for now

**Comment by adrai** [comment]
We need to reopen this issue because of: https://github.com/joyent/node/issues/9296#issuecomment-76573830

**Comment by adrai** [comment]
@Unitech any idea how I can get more info?

**Comment by adrai** [comment]
ok, i tested on an other machine... and a can't reproduce it, so we can really close this issue...

**Comment by soyuka** [comment]
https://github.com/joyent/node/issues/9261

**Comment by scopsy** [comment]
having same issue with node 0.12.7

**Comment by BiteBit** [comment]
having same issue with node 0.12.7

**Comment by abhilashsajeev** [comment]
Having same issue with node 0.12.7 and pm2
