### ISSUE TITLE
PM2 stop frequently and stop the app.

### ISSUE THREAD

**Issue by navsaini53** [Unitech/pm2#1051]
PM2 version: 0.12.6
node version :0.10.28
OS : windows
The pm2 monit give 100 % cpu usage

 error info :
PM2: 2015-02-14 17:37:15: [PM2][WORKER] Started with refreshing interval: 30000
PM2: 2015-02-14 17:37:15: [[[[ PM2/God daemon launched ]]]]
PM2: 2015-02-14 17:37:15: BUS system [READY] on port \\.\pipe\pub.sock
PM2: 2015-02-14 17:37:15: RPC interface [READY] on port \\.\pipe\rpc.sock
PM2: 2015-02-27 17:26:58: [PM2][WORKER] Started with refreshing interval: 30000
PM2: 2015-02-27 17:26:58: [[[[ PM2/God daemon launched ]]]]
PM2: 2015-02-27 17:26:58: BUS system [READY] on port \\.\pipe\pub.sock
PM2: 2015-02-27 17:26:58: RPC interface [READY] on port \\.\pipe\rpc.sock
PM2: 2015-02-27 17:27:09: Starting execution sequence in -fork mode- for app name:server id:0
PM2: 2015-02-27 17:27:09: App name:server id:0 online

any suggesstion?

![untitled](https://cloud.githubusercontent.com/assets/7802443/6412747/ff11838c-bead-11e4-9bee-915eb5108a34.png)

![untitled](https://cloud.githubusercontent.com/assets/7802443/6412768/2e833be2-beae-11e4-9ff2-b16658d6720a.png)

**Comment by Unitech** [comment]
When you start a simple app, let's say:

```
setInterval(function() {
  console.log('Hey');
}, 1000);
```

Does this app gives you 100% cpu usage also?

**Comment by navsaini53** [comment]
no it doesnot give me 100% cpu usage .. problem is that app get hang usually say after 1 hours interval sometime 2 hour interval...    i have tested all the suspected routes but everything works fine...

**Comment by vmarchaud** [comment]
Working great for me, must be linked to an old version of pm2.
