### ISSUE TITLE
Using PEM file with automated deployment

### ISSUE THREAD

**Issue by sean-hill** [Unitech/PM2#1053]
Hey there,

I've been given access to our production server using this command on my local machine:

`ssh -v -i /Users/Me/.ssh/production.pem ubuntu@1.2.3.4`

I was wondering if I can use my PEM file instead of an ssh-key for automated deployment using `pm2 deploy`. So basically being able to tell `pm2` which identity file to use for ssh. Thanks.

**Comment by Unitech** [comment]
You can specify the key by adding the "key" attribute with the path of the pem key

**Comment by sean-hill** [comment]
Great thanks!

**Comment by Unitech** [comment]
I updated the doc https://github.com/Unitech/PM2/blob/master/ADVANCED_README.md#using-file-key-for-authenticating

Cheers
