### ISSUE TITLE
Priority of environment variables defined in processes.json vs. those given when starting up pm2

### ISSUE THREAD

**Issue by starsirius** [Unitech/pm2#1056]
Specifying environment variables in the processes.json and starting the app with

```
pm2 start processes.json
```

 is very useful. Sometimes we would like to slightly modify the environment variables without keep creating different json files (that would only be slightly different from each other.) However, specifying those env vars when starting pm2 seems to have lower priority than those in the json file.

```
SOME_VAR=override pm2 start processes.json
```

This won't override the `SOME_VAR` defined in the processes.json. I couldn't find an easy way to do this without creating another json. Any advice would be appreciated. Thanks!

**Comment by Unitech** [comment]
Do declaring different env on your process.json would solve your use case? (#1037)

So you would be able to start different environment via `pm2 start processes.json --env prod`
