### ISSUE TITLE
PM2 V0.12.6 God Daemon consuming excessive CPU?

### ISSUE THREAD

**Issue by rbarkas** [Unitech/PM2#1057]
I've just upgraded to PM2 V0.12.6.
Since the upgrade I've noticed the God Daemon consuming lots of cpu..
In the past it hasn't ever been a problem.
It's interesting that the cpu util showing for the God Daemon is more or less the same as the total utilization of all the tasks that it is managing.

At the moment the God Daemon is using about 60% of a Xeon cpu core.
Has something changed in 0.12.6 that means I need to change my configuration?

I start 26 tasks using a json file.  In the json file there is an entry for each task that looks like:
 {
                "name":"my task name",
                "script":"utils/myTaskExecutable.js",
                "args":"['--config=myTaskConfigFile']",
                "exec_mode":"fork_mode"
        },

**Comment by Unitech** [comment]
What was the previous version?
Can you provide a screenshot of htop / pm2 list?
