### ISSUE TITLE
Centrify issues and fix

### ISSUE THREAD

**Issue by robgrimball** [Unitech/pm2#1061]
PM2 startup script does not work well when using centrify.  This is because apparently the 

```
super() {
    su - $USER -c "PATH=$PATH; $*" 
}
```

will in effect execute a ksh for the su individually and then the part in quotes after exiting from that shell.

What we found works better is to specify the shell explicitly via the --shell option and as long as the path was already set for the user in their environment, it doesn't really need to be explicitly set too.  So the following works for us :

```
super() {
    su - $USER --shell=/bin/bash -c "$*"
}
```

I am not sure if something like this should work it's way into the startup script generally, though I think it would work for most cases anyway (getting the path of bash from which and using that would probably be better than explicitly using it's path like we are), but I thought I would put it here to let you be aware of it and in case any other centrify users are having difficulties with their startup scripts working.

**Comment by Unitech** [comment]
Closing in favor of #2559 

To try the new startup system:

```bash
$ npm install Unitech/pm2#development -g
$ pm2 update
```

```bash
$ pm2 startup     # Then copy / paste the command displayed
$ pm2 unstartup
```
