### ISSUE TITLE
Git submodule with pm2 deploy

### ISSUE THREAD

**Issue by sean-hill** [Unitech/pm2#1064]
Hey there I have a git project with a git submodule. With a hierachy like so:

	- unbill-server
		- unbill-shared (submodule)
		- other
		- folders
		- in
		- project

I'm using `pm2 deploy` to launch my updates. Here's my logs during the deploy

	pm2 deploy ecosystem.json production
	--> Deploying to production environment
	--> on host 54.172.45.78
	  ○ deploying
	  ○ hook pre-deploy
	  ○ fetching updates
	Fetching origin
	From github.com:sweinertjr/unbill-server
	   5218156..c88b9fc  master     -> origin/master
	Fetching submodule unbill-shared
	From github.com:sweinertjr/unbill-shared
	   7f1c831..b807acf  master     -> origin/master
	  ○ resetting HEAD to origin/master
	HEAD is now at c88b9fc Removed git submodule stuff from ecosystem
	  ○ executing post-deploy `npm install && pm2 startOrRestart ecosystem.json --env production`
	npm WARN package.json unbill@0.1.0 No repository field.
	npm WARN package.json semaphore@1.0.1 No repository field.
	[PM2] restartProcessId process id 0

However, my git submodule code did not update as the logs suggest.

Running a post deploy like `npm install && git submodule init && git submodule update --remote && pm2 startOrRestart ecosystem.json --env production` correctly updates my submodule, but I was wondering if `pm2` should be doing this for me.

Thanks!

**Comment by peterchoo** [comment]
I've not found anything to suggest pm2 should be managing your submodules.  In our application we have a post deploy that runs `git submodule update --init --recursive && npm install` before the `startOrRestart` stuff.
