### ISSUE TITLE
start app with http_proxy

### ISSUE THREAD

**Issue by luicfer** [Unitech/PM2#1065]
my server behind the firewall. I  set up http_proxy and https_proxy. and my app can use http request start 
with ``node app.js`` but not with ``pm2 start app.js``.
how to solve the problem

**Comment by jshkurti** [comment]
Can you ```pm2 prettylist | grep http_proxy``` and tell us if grep matched something or not ? :)
If not, do```pm2 update``` and try again please.

**Comment by luicfer** [comment]
grep matched ``http_proxy:"http://10.xx.xx.xx:xxx" 
this app is for exec shell  like ``git`` ``npm install``
