### ISSUE TITLE
PM2 cause coredump.

### ISSUE THREAD

**Issue by JiangJie** [Unitech/pm2#1067]
Any PM2 command will cause coredump. The following is the log.
`PM2 v0.12.7: God Daemon: ../deps/uv/src/unix/linux-core.c:720: read_times: Assertion `num == numcpus' failed.`

More info about my environment:
OS: Linux
Kernel: 2.6.32.57
iojs: 1.4.3
PM2: 0.12.7

**Comment by Unitech** [comment]
We dont do any assertion in our code, it may come from iojs

(https://github.com/Unitech/PM2/search?utf8=%E2%9C%93&q=numcpus)

**Comment by JiangJie** [comment]
Okey. I found the assertion at line 720 of file `deps/uv/src/unix/linux-core.c ` form iojs.
But I would like to know which call or api will cause the assertion failure?

**Comment by Unitech** [comment]
https://github.com/iojs/io.js/blob/v1.x/deps/uv/src/unix/linux-core.c#L720

It seems that this call  http://nodejs.org/api/os.html#os_os_loadavg

Was this pm2 linked with keymetrics.io?

**Comment by JiangJie** [comment]
>Was this pm2 linked with keymetrics.io?

NO.
>Any PM2 command will cause coredump. 

even `pm2 -h`.
