### ISSUE TITLE
what determines console.log's being marked as errors

### ISSUE THREAD

**Issue by GlynnPhillips** [Unitech/PM2#1069]
pm2 version: 0.12.6
nodejs version: 0.10.18
OS: OSX

Hi, firstly thanks for such a great and full featured module. I am in the early stages of using pm2 and trying to use it for now simply to provide a simple start up script for developers local environments and log the processes. However at the moment everything we are logging is being marked as an error and saved in the error log files. I cant quiet figure out what determines an error vs an output. 

Most of these cases are just using console.log.

Can you shed any light on the criteria of an error vs an output? Sorry if this is something I have missed in the docs.

Thanks
Glynn

**Comment by jshkurti** [comment]
@Tjatse any clue ?

**Comment by Tjatse** [comment]
`console.log` goes to `*-error.log` and `console.error` goes to `*-out.log`.  I've never come across the type of problem (what you're describing) before. Any sample code to reproduce it?

**Comment by GlynnPhillips** [comment]
Apologies you can ignore me :-1: 

I have done some digging and I was not aware that out app was using rconsole to log to syslog. This appears to be the root cause and must be switching our logs. 

Thanks for your help and responding quickly, now onto finding out why [rconsole](https://www.npmjs.com/package/rconsole) is messing with logs.

**Comment by Tjatse** [comment]
Okay, feel free to reopen this or file a new one if you feel puzzled about PM2 log system.
