### ISSUE TITLE
Installation Errors

### ISSUE THREAD

**Issue by ar3165** [Unitech/PM2#1073]
Got the following errors when installing:

sudo npm install pm2 -g

npm ERR! git clone http://ikt.pm2.io/ikt.git Cloning into bare repository '/home/users/ar3165/.npm/_git-remotes/http-ikt-pm2-io-ikt-git-58fd7291'...
npm ERR! git clone http://ikt.pm2.io/ikt.git fatal: http://ikt.pm2.io/ikt.git/info/refs not valid: is this a git repository?
npm WARN optional dep failed, continuing ikt@git+http://ikt.pm2.io/ikt.git#master
npm WARN optional dep failed, continuing fsevents@0.3.5

**Comment by Unitech** [comment]
fixed, but ok I understand you got this message, but it blocked the installation?

**Comment by ar3165** [comment]
It seems to work, are those errors harmless?  I tried re-installing and got same errors.
