### ISSUE TITLE
Send Email when an app is down

### ISSUE THREAD

**Issue by mateeyow** [Unitech/PM2#1080]
Any way to implement a sending of email when an app crashes?

**Comment by jorge-d** [comment]
Hi @mateeyow,

There is currently no way to do that out of the box.
However I can only suggest that you give a try to [Keymetrics](http://keymetrics.io) as it has this feature :)

**Comment by soyuka** [comment]
+1 @jorge-d 

Another way would be by using another app that manages pm2 programaticaly by listening to app events.

**Comment by ravi** [comment]
Please see #90.

**Comment by jshkurti** [comment]
```js
var pm2 = require('pm2');

pm2.connect(function() {
  pm2.launchBus(function(err, bus) {
    bus.on('process:event', function(data) {
      if (data.event === "exit") {
	    // Do your stuff here ...                                                                                                                  
      }
    });
  });
});

```

**Comment by ravi** [comment]
That's not bad but it means the user has to write a program to monitor/manage a program that is monitoring/managing other programs. At some point, the mind tires of the indirection. The above however can be one implementation of a standalone program (pm2-notifier?) -- if one doesn't already exist -- to do the email notification, though I think I would still prefer this as a core function.

**Comment by rameshvinfo** [comment]
var pm2 = require('pm2');

pm2.connect(function() {
  pm2.launchBus(function(err, bus) {
    bus.on('process:event', function(data) {
      if (data.event === "exit") {
        // Do your stuff here ...                                                                                                                  
      }
    });
  });
});

above code is not working

**Comment by soyuka** [comment]
@rameshvinfo  take a look [here](https://github.com/soyuka/pm2-notify/blob/master/index.js) and read the [pm2 api docs](http://pm2.keymetrics.io/docs/usage/pm2-api/#programmatic-api)

**Comment by rameshvinfo** [comment]
var getEventType = function(){
var opts = {
			from: appConfigData.mail.from,
			subject:'Exception ',
			mailContent :'Exception In process',
			priority: "high" 
};
	pm2.connect(function() {
		pm2.list(function(err,list) {
		 pm2.launchBus(function(err, bus) {
				if(err) {
					throw err
				}
				bus.on('process:event', function(data) {
                                       #///**does not console any thing--"data"**
					console.log(data);
					if (data.event === "exit") {
                                             opts.subject = 'Exception '+data.event,
						sendMailRequest(opts )                                                                                                                  
					}
				});
			});
			
			
		});
		
	});
		
}

getEventType ()

this is what i am trying...
