### ISSUE TITLE
[Windows issue] PM2 CPU report is wrong

### ISSUE THREAD

**Issue by jorge-d** [Unitech/pm2#1081]
From Unitech/keymetrics.io#43,

On Windows the CPU report keeps rising and even the `pm2 monit` commands seems to do the same.

**Comment by soyuka** [comment]
I think this might comes from https://github.com/soyuka/pidusage#windows, sadly I don't have any windows device to debug this. I've investigate a lot to find something better than `wmic` but there are no tools more portable then this one. There might be an issue with how `wmic` output is handled, but as said, I can't test it :|.

**Comment by men232** [comment]
I confirm the same problem

**Comment by asm911** [comment]
I experience the same issue on Linux, Debian 8.3, pm2 1.0.2, nodejs 4.4.0
