### ISSUE TITLE
pm2 logs --lines bug

### ISSUE THREAD

**Issue by sean-hill** [Unitech/PM2#1084]
Running `pm2 logs --lines 100` still only shows the last 20 lines. It also shows 20 lines of the 3 different log files `(out)`, `(err)`, and `PM2`, I expected these all to be merged together chronologically. 

Thanks!

**Comment by Tjatse** [comment]
thanks, fixed, we're using `tail` to display logs, not `multitail`, so the `lines` option affects each file , i.e. `pm2.log`, `*-out.log` and `*-err.log`.

**Comment by sean-hill** [comment]
@Tjatse thanks! Has this been pushed yet? Just curious when I can update my `pm2` :)

**Comment by jshkurti** [comment]
It has been merged on development branch for the moment, it will be released tomorrow within PM2 0.12.8 ;)

**Comment by sean-hill** [comment]
Woot woot :+1: While we are on the subject of logs...about a month ago there was conversation about being able to tail the logs via the keymetrics dashboard, is this still in the works?

**Comment by jshkurti** [comment]
We're trying to figure out a solution to do it without keeping all the logs on keymetrics servers (it would require Terabytes of disk space :/ ).
It will be avaible someday but I'm afraid not anytime soon :/

**Comment by sean-hill** [comment]
Very understandable, thanks for the quick response!

**Comment by Unitech** [comment]
This is a good idea @sean-hill we are working on a temporary feature (real time on keymetrics dashboard) and a persistent way (storage on keymetrics once we refactored our database infrastructure to make it more scalable)

Cheers!

**Comment by Unitech** [comment]
This is a good idea @sean-hill we are working on a temporary feature (real time on keymetrics dashboard) and a persistent way (storage on keymetrics once we refactored our database infrastructure to make it more scalable)

Cheers!
