### ISSUE TITLE
Docker and Apparmor Specifics (Ubuntu)

### ISSUE THREAD

**Issue by rudijs** [Unitech/pm2#1086]
Hi,

Using pm2 inside docker v1.5 on Ubuntu 14.04 by default I get these system log message every 30 seconds.

```
<5>Mar 12 09:36:50 vbox kernel: [19056.321288] type=1400 audit(1426153010.804:644): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=10241 comm="node" requested_mask="trace" denied_mask="trace" peer="docker-default"
```

I'd like to post my findings into this and would appreciate any feedback.

After some googling around I've round that these two flags on the docker run command are required to "fix" the issue.

```
--cap-add SYS_PTRACE  --security-opt apparmor:unconfined
```

Simiar to Monit inside a docker container I think pm2's controlling and observing individual processes requires capabilities denied by Docker's default Apparmor profile. 

Currently, the only workaround is to add the trace capability and running the container without being fenced by Apparmor.

Not doing so will result in a _vast_ number of log messages polluting your syslog, as pm2 tries to trace the processes every 30 seconds.

Those two flags posted do two things: giving the container the capability of performing traces, and finally disabling apparmor for the docker container, and nothing else.

**Comment by jshkurti** [comment]
30 seconds sounds like the default worker interval of pm2 which basically does some 'git log' commands and parses the output in order to get some metadata about the git/svn/hg repository if there is one.

Worker is here : https://github.com/Unitech/PM2/blob/master/lib/Worker.js#L61-L100
It calls vizion.parse() which is here :
https://github.com/keymetrics/vizion/blob/master/lib/git.js#L7-L111

I don't think there is a ptrace around these lines, at least not directly.

**Comment by rudijs** [comment]
@jshkurti yes, it's an interesting one.

I wouldn't say there's any error on pm2's part or the node application that pm2 is running.

There's no actual application errors or crash, just picked up on those syslog error messages from logstash running inside the container.

It's just a work around that's needed for the current state of apparmor configuration on docker containers.

It goes pretty deep into Docker and apparmor (Ubuntu) and it's tagged in a few github issues/dicsussions.

I wanted to put it into this issue anyways, just for some awareness and discussion plus the keywords should come up in search and save some other developers time.

I'm going to continue using pm2 with my node apps running inside docker containers.

Cheers.

**Comment by jshkurti** [comment]
Thanks for the feedback :)

**Comment by lgelfan** [comment]
Any updates on this?

**Comment by Unitech** [comment]
http://pm2.keymetrics.io/docs/usage/docker-pm2-nodejs/
