### ISSUE TITLE
Is logging asynchronous?

### ISSUE THREAD

**Issue by Jokero** [Unitech/PM2#1087]
From node.js [docs](https://nodejs.org/docs/latest/api/console.html):
> The console functions are synchronous when the destination is a terminal or a file (to avoid lost messages in case of premature exit) and asynchronous when it's a pipe (to avoid blocking for long periods of time).

How does logging in pm2 work?

**Comment by Tjatse** [comment]
Yup, the underlying codes of `console.log`, `console.error` are:
```javascript
process.stdout.write()
process.stderr.write()
```
The `console.log` stuffs are synchronous.

But we're listening on the `data` event, e.g.:
```javascript
process.stderr.on('data', function(data){
 var std = file. createWriteStream([LOG_PATH]);
 std.write([LOG]);
});
```
So the logs will be piped to files, and it's totally asynchronous now.

**Comment by Jokero** [comment]
Thanks! :+1: Update documentation, please

**Comment by florianwalther-private** [comment]
Althought 5 years later, I'm having the same question as @zubair1024.
Could someone clarify this?
