### ISSUE TITLE
why are there 6 daemons and 6 processes for my app?

### ISSUE THREAD

**Issue by neonstalwart** [Unitech/PM2#1088]
this is taken from htop which shows a tree of the processes so you can tell which process created which processes

```
20947 deployer   20   0  690M 58356  6412 S  0.0  1.4  4:45.97 ├─ PM2 v0.12.7: God Daemon
20952 deployer   20   0  690M 58356  6412 S  0.0  1.4  0:03.77 │  ├─ PM2 v0.12.7: God Daemon
20951 deployer   20   0  690M 58356  6412 S  0.0  1.4  0:03.80 │  ├─ PM2 v0.12.7: God Daemon
20950 deployer   20   0  690M 58356  6412 S  0.0  1.4  0:03.82 │  ├─ PM2 v0.12.7: God Daemon
20949 deployer   20   0  690M 58356  6412 S  0.0  1.4  0:03.75 │  ├─ PM2 v0.12.7: God Daemon
20948 deployer   20   0  690M 58356  6412 S  0.0  1.4  0:12.60 │  ├─ PM2 v0.12.7: God Daemon
 6766 deployer   20   0 1139M  231M  8584 S  0.0  5.8  2:59.50 │  └─ app
 6783 deployer   20   0 1139M  231M  8584 S  0.0  5.8  0:00.01 │     ├─ app
 6782 deployer   20   0 1139M  231M  8584 S  0.0  5.8  0:00.00 │     ├─ app
 6781 deployer   20   0 1139M  231M  8584 S  0.0  5.8  0:00.00 │     ├─ app
 6780 deployer   20   0 1139M  231M  8584 S  0.0  5.8  0:00.00 │     ├─ app
 6769 deployer   20   0 1139M  231M  8584 S  0.0  5.8  0:04.46 │     └─ app
```

i'm running in fork mode and here's `pm2 status`

```
┌──────────────┬────┬──────┬──────┬────────┬─────────┬────────┬──────────────┬──────────┐
│ App name     │ id │ mode │ pid  │ status │ restart │ uptime │ memory       │ watching │
├──────────────┼────┼──────┼──────┼────────┼─────────┼────────┼──────────────┼──────────┤
│      API     │ 0  │ fork │ 6766 │ online │ 1       │ 60m    │ 261.395 MB   │ disabled │
└──────────────┴────┴──────┴──────┴────────┴─────────┴────────┴──────────────┴──────────┘
```

any idea what's going on?  let me know if you need any more information.

**Comment by joshperry** [comment]
I'm having this exact same issue. All of my processes are running in fork mode, and a couple of them very specifically can _not_ be load-balanced which is causing a lot of problems... I'd love to know why this is happening.

![](https://www.dropbox.com/s/grhdsbh6p0unxs6/Screenshot%202015-03-17%2014.35.14.png?raw=1)

**Comment by Unitech** [comment]
Internally NodeJS uses a thread pool to handle synchronous operations and HTOP show these threads.

Ref:
http://stackoverflow.com/questions/19891084/node-js-spawns-multiple-processes

@joshperry Happy you still use PM2 :) We now take great care of CHANGELOG and related

**Comment by neonstalwart** [comment]
that's probably what i'm seeing.  i'm going to close this issue and keep an eye on my processes in case it seems to be something other than that.
