### ISSUE TITLE
Instances option allows non number value, starts infinite instances

### ISSUE THREAD

**Issue by janders223** [Unitech/PM2#1091]
```
pm2 --version: 0.12.7
iojs --version: 1.5.1
os: Ubuntu 12.04.4 LTS (GNU/Linux 3.11.0-15-generic x86_64)
os: OS X 10.9.4
```
Launching an application with `pm2 start index.js --name "test" -i 0` performs as expected and launches one instance per core of my machine.
![screen shot 2015-03-13 at 3 16 41 pm](https://cloud.githubusercontent.com/assets/719823/6645572/fe6148c8-c993-11e4-944e-4a02b8de8367.png)

However one missed keystroke `pm2 start index.js --name "test" -i o` continues to launch instances of the application until kernel panic.

![screen shot 2015-03-13 at 3 20 17 pm](https://cloud.githubusercontent.com/assets/719823/6645642/9efba562-c994-11e4-8044-4378dba4173f.png)
![screen shot 2015-03-13 at 3 20 43 pm](https://cloud.githubusercontent.com/assets/719823/6645645/a1ee2786-c994-11e4-9766-4fe15b72edc9.png)

I attempted to run this with debugging on, however calling start with `-i o` seems to just hang the process and does not log anything to stdout or stderr. This is can be reproduced on both my local MacBook Pro and my server.

I will do my best to try to work on this issue. Unfortunately I cannot do anything until I am off of corporate resources.

**Comment by jorge-d** [comment]
Thank you for reporting this, I confirm the fork bomb on my Macbook as well :]

Investigating this right now,
