### ISSUE TITLE
ecosystem.json declaration ignored

### ISSUE THREAD

**Issue by cdaringe** [Unitech/PM2#1093]
Hi all:

I use a ecosystem.json file.  All of processes boot, except this one!  No warning, it's just *not started*. node v0.12.  pm2 0.12.7.  Thanks! 

Chris

```json
        }, {
            "name" : "zedserver",
            "script": "/usr/bin/zedrem",
            "args": "['--interpreter none -x -- --server']",
            "cwd": "/coins",
            "instances" : 1,
            "out_file" : "/coins/log/zedserver.stdout.log",
            "error_file" : "/coins/error_files/zedserver.error",
            "exec_interpreter" : "none",
            "exec_mode" : "fork_mode"
        }
```

**Comment by cdaringe** [comment]
I was causally updating my log dirs, and I just updated ` "error_file" : "/coins/error_files/zedserver.error",` as I noticed `/coins/error_files` didn't exist.  I did a startOrRestart on my ecosystem.json, what do you know, the process spun up!  how peculiar!

**Comment by joshperry** [comment]
Maybe related to #1107?

**Comment by Unitech** [comment]
https://github.com/Unitech/PM2/commit/b0c8f1b7d953eeb2d6cd940fab136184232216e3

**Comment by cdaringe** [comment]
ahhhh yeeaa! :+1:
