### ISSUE TITLE
bus system not emitting process:exception

### ISSUE THREAD

**Issue by fredericosilva** [Unitech/pm2#1098]
Hello,

The bus system is not emitting process:exception. It works fine for "log:err" and "log:out".

```
var pm2 = require('pm2');

pm2.launchBus(function(err, bus) {
  console.log('connected', bus);

  bus.on('process:exception', function(data) {
    console.log(arguments);
  });

  bus.on('reconnect attempt', function() {
    console.log('Bus reconnecting');
  });

  bus.on('close', function() {
    console.log('Bus closed');
  });
});
```

I'm trying to find a way to catch all the exceptions from all node processes, so that I can have a simple reporter that alerts me when something goes wrong.

**Comment by sarus** [comment]
Have the same problem except I'm trying to catch `process:restart`.  I need to be able to run some async cleanup before a process restarts/stops.  Right now it works if I don't use PM2 and just listen for `SIGINT`, run my cleanup code, then exit.  PM2 restart/stop however doesn't seem to trigger the `SIGINT`.  

When testing the bus system the only events I saw emitted where `log:out`.

**Comment by jshkurti** [comment]
@sarus By default, SIGTERM is used to terminate a process.

**Comment by pravee-n** [comment]
I am also facing this issue. I am trying to catch process:restart so that I can send an email whenever PM2 restarts/stops a process. Is there any way I can achieve that?
