### ISSUE TITLE
Deploying with sudo

### ISSUE THREAD

**Issue by webchaz** [Unitech/pm2#1103]
Is there a way when using deploy to have actions executed with sudo? for example using AWS and running `pm2 deploy ecosystem.json5 production setup` locally (for remote server on aws) doesn't work, since aws requires use of sudo.

**Comment by klinquist** [comment]
AWS doesn't require sudo...  The key is running PM2 as a user (such as 'ubuntu').
On a new AWS instance, I do the following:

1) npm config set prefix ~
2) (Add /home/ubuntu/bin to the path in /etc/environment)
3) npm install pm2 -g
3) pm2 startup ubuntu -u ubuntu

Now pm2 should be able to run just fine without sudo.

**Comment by webchaz** [comment]
Thanks, I've tried this, but when I get to `npm install pm2 -g` I get EACCESS errors that I don't get when sudo'ing.  Maybe because pm2 is already installed?

**Comment by kilokeith** [comment]
I'm trying to make an script monitor/dashboard using pm2 programmatically. But my script has to be run as sudo to get access to an HID device on Mac. Would it be possible to make a bash script to do a sudo node ...  and run that with pm2, but still have access to the child node process (for event monitoring)?

**Comment by fernandoneto** [comment]
@webchaz you have 2 options
* you can chown to your user the path `/usr/local` but is not advised.
* do what @klinquist suggest, only create a path in ~
  example 
```bash
mkdir -p ~/node
npm config set prefix ~/node/
```
 PS : check the owner of your aws pem. and if your user is not the owner change it to you.

**Comment by tamaker** [comment]
> I'm trying to make an script monitor/dashboard using pm2 programmatically. But my script has to be run as sudo to get access to an HID device on Mac. Would it be possible to make a bash script to do a sudo node ... and run that with pm2, but still have access to the child node process (for event monitoring)?

@kilokeith - did you ever have any luck doing this?  I am looking to do the same with PM2 programmatically
