### ISSUE TITLE
Windows Error when pm2 start on D: drive

### ISSUE THREAD

**Issue by veacks** [Unitech/PM2#1104]
The error append when trying to start a project on another drive than C: on windows server 2012 R2 

Sorry can't copy past console output from MSRemote Desktop, I can only do Screenshots.

Cf below:

![image](https://cloud.githubusercontent.com/assets/417293/6703487/86054e00-cd90-11e4-9216-bec52bb1410f.png)

Pm2 try to open D:\Users\[username]\.pm2 instead of C:\Users\[username]\.pm2

Is there any way to specify another path for .pm2 file manually by the console?

Thanks.

**Comment by soyuka** [comment]
http://stackoverflow.com/questions/29096135/error-while-installing-pm2-node-js

To specify another `.pm2` directory add an environment variable `PM2_HOME` to the path you want.

**Comment by veacks** [comment]
Thanks! It works well now :)

**Comment by zhaoyou** [comment]
@veacks  It's not work for me. What's your start scripts ?
```
set NODE_ENV=production
set PORT=3001
set PM2_HOME=C:\Users\Administrator\.pm2
pm2 start ./bin/www --watch
```
