### ISSUE TITLE
Question: best practices: logging

### ISSUE THREAD

**Issue by naartjie** [Unitech/PM2#1106]
What are the best practices regarding PM2 and logging? Should my app just log everything to `stdout` a la [12 factor app](http://12factor.net/logs), and PM2 takes care of the rest? i.e. if my app has a `./logs/` directory, and is pumping out files there, I am doing some redundant work, where PM2 can already maintain the logs.

Thanks for a great tool!!

**Comment by jshkurti** [comment]
Yes, just use stdout and stderr and pm2 takes care of the rest.
Do ```pm2 desc <app id>``` to see where PM2 is keeping log files for that particular app.

**Comment by naartjie** [comment]
Thanks :+1:

**Comment by Unitech** [comment]
If you want to do something more custom: https://github.com/Unitech/PM2/blob/master/doc/PROGRAMMATIC.md#bus-system---event-monitoring

Cheers!
