### ISSUE TITLE
Restart failure detection does not work on first boot

### ISSUE THREAD

**Issue by joshperry** [Unitech/pm2#1108]
This seems to happen when PM2 is brought up during a system boot. You can see here the couchmail app is being restarted about 10 times per second.

![](https://www.dropbox.com/s/7v653wvep35252g/Screenshot%202015-03-18%2015.34.07.png?raw=1)

Doing a `pm2 stop 2` and then `pm2 restart 2` and the normal failure detection worked properly after 15 restart attempts.

![](https://www.dropbox.com/s/tf0blu12jr61thu/Screenshot%202015-03-18%2015.38.28.png?raw=1)

**Comment by jshkurti** [comment]
Is there any chance that watch being enabled may cause this ?
