### ISSUE TITLE
Startup script with clustering not working when number of processor changed

### ISSUE THREAD

**Issue by mssio** [Unitech/pm2#1110]
Hello,

I have a problem when I started pm2 in cluster mode maximum (-i 0).
When I created an Ubuntu image with node application (pm2 included) installed and pm2 startup script generated. I run pm2 using pm2 start server.js --name app -i 0. Then I create the image to be loaded by another machine. My image is created in a machine with just 1 core processor, so only 1 process is spawned when I run pm2 start server.js --name app -i 0.

When I run the image in my 8 cores machine, which is if I run manually pm2 start server.js --name app -i 0, it should spawn 8 processes. But when using the startup script from the image only 1 process is spawned instead of 8.

So right now I can't depend on startup script and created my own shell script and run using cron. Please help me to fix this issue so I don't need to use cron and just rely on pm2 startup script.

Thank you very much for creating a great product :+1:

**Comment by jshkurti** [comment]
Hi Mario,
Can you show me the startup script please ?

**Comment by mssio** [comment]
Hi Joni,

The startup script is standard startup script generated when I run this command:
`$ pm2 startup ubuntu`

Here is the generated startup script:
`sudo env PATH=$PATH:/home/dev/.nvm/versions/node/v0.12.0/bin pm2 startup ubuntu -u dev`

**Comment by jshkurti** [comment]
This is a normal behaviour.
Actually the startup script will perform a ```pm2 resurrect``` which basically reads ```~/.pm2/dump.pm2``` and launches all apps it found in it.
Try launching your apps manually on the other machine (with more cpus) so ```-i 0``` would take the right number of cpus and then ```pm2 dump```. It should work.

**Comment by mssio** [comment]
Right now my solution is creating this script and run it on reboot using cron:

````sh
#!/bin/bash

cd /app/api
pm2 stop api
pm2 flush
pm2 delete api
pm2 start server.js --name app
````

I think it will be better if it can be automated using pm2 startup script instead.

**Comment by Unitech** [comment]
make sure you pm2 save once you started more / new applications

https://github.com/Unitech/pm2/issues/2559
