### ISSUE TITLE
pm2: command not found on Ubuntu server 14.04

### ISSUE THREAD

**Issue by michele-prandina** [Unitech/PM2#1112]
Node version installed `v0.10.25`

When installing `npm install pm2 -g` and run `pm2 start server.js ` I get the following issue:

```
No command 'pm2' found, did you mean:
 Command 'pms' from package 'pms' (universe)
 Command 'pmw' from package 'pmw' (universe)
 Command 'wm2' from package 'wm2' (universe)
 Command 'pmk' from package 'pmk' (universe)
 Command 'fpm2' from package 'fpm2' (universe)
 Command 'pmi' from package 'powermanagement-interface' (universe)
 Command 'pom2' from package 'libpod-pom-perl' (universe)
 Command 'pm' from package 'powerman' (universe)
pm2: command not found

```

Any clue why I get this?

PS: I'm working as root.

**Comment by klinquist** [comment]
...because PM2 is not in your path.

type:
npm config get prefix 

Append "/bin" to whatever that result is,
Then add that to your path in /etc/environment

**Comment by vladikoff** [comment]
This can be closed

**Comment by jesobreira** [comment]
@marcusjwhelan run `npm config get prefix`. You will get something similar to:

```
/home/user/.npm-global
```

Take it and add `/bin`:

```
/home/user/.npm-global/bin
```

Run `nano ~/.bashrc` (Ubuntu) and add to the last line:

```
export PATH=$PATH:/home/user/.npm-global/bin
```

Save (<kbd>Ctrl</kbd>) + <kbd>O</kbd>), close (<kbd>Ctrl</kbd> + <kdb>X</kdb>) and run `source ~/.bashrc`.

**Comment by surajpadhy** [comment]
@klinquist thanks, it worked for me.

**Comment by jesussanzdev** [comment]
@jesobreira clean and simple, thank you very much friend!

**Comment by LucasAsafe** [comment]
@jesobreira thanks, dude!

**Comment by klinquist** [comment]
You want clean and simple? I'll give you clean and simple!

```
echo "PATH=\$PATH:`npm config get prefix`/bin" >> ~/.bashrc
source ~/.bashrc
```

**Comment by jesobreira** [comment]
@jesussanzdev @LucasAsafe you are welcome! It's worth to mention that the original answer was posted by @klinquist and my answer was just to add verbosity to his solution. Kudos to him!

**Comment by ifbasit** [comment]
> You want clean and simple? I'll give you clean and simple! Copy/paste:
> 
> ```
> echo "PATH=\$PATH:`npm config get prefix`/bin" >> ~/.bashrc
> source ~/.bashrc
> ```

You saved my life!!!!

**Comment by Samiys** [comment]
> You want clean and simple? I'll give you clean and simple! Copy/paste:
> 
> ```
> echo "PATH=\$PATH:`npm config get prefix`/bin" >> ~/.bashrc
> source ~/.bashrc
> ```

I think it messed it up because now my path looks like 
\[\e]0;\u@\h: \w\a\]\[\033[;94m\]┌──(\[\033[1;31m\]\u💀\h\[\033[;94m\])-[\[\033[0;1m\]\w\[\033[;94m\]]\n\[\033[;94m\]└─\[\033[1;31m\]$\[\033[0m\]
