### ISSUE TITLE
Sourcing environment (~/.zshrc) in post-deploy

### ISSUE THREAD

**Issue by naartjie** [Unitech/pm2#1113]
I am using `nvm` on my server, and I need to source `~/.zshrc` in my `post-deploy`.

Just wondering if there is an easier way to do this:

``` JSON
"post-deploy" : ". \\~/.zshrc\\; npm install && pm2 startOrGracefulReload ecosystem.json --env production"
```

**Comment by naartjie** [comment]
By easier I mean a better (DRY) place in the config file perhaps. Thanks!!

**Comment by neonstalwart** [comment]
have you tried using .zshenv to source nvm and making sure that the user running the pm2 daemon uses the zsh shell?  that's how i make that work.

**Comment by soyuka** [comment]
#1141

**Comment by naartjie** [comment]
Thanks for the suggestion @neonstalwart.

I tried it on the server, and it doesn't seem to work though. It looks like the user's `$HOME/.zshenv` doesn't get sourced at all. I tried with `pm2 deploy` and with a login shell, but `nvm` wasn't there.

I think it's something to do with my particular setup, I'm running Ubuntu 14.04, with a custom oh-my-zsh setup.

This does work on my development machine (OS X), where I am running oh-my-zsh too.

**Comment by spieglio** [comment]
An old issue but I think this can be closed.

This is probably no longer current but in general, the problem most likely comes from pm2 loading a non-interactive shell / bash rather than the one on your Mac.

I fixed this by loading NVM inside the `.zshenv` file  (after trying every other imaginable variation. Now it works.

**Comment by naartjie** [comment]
Yup, it can be closed. It's pretty old and I certainly am no longer using that way, so won't be able to comment. thx.

**Comment by nagman** [comment]
> ```json
> . \\~/.zshrc\\;
> ```

Thank you! I was struggling with deploying through pm2 to my remote server, and nothing worked except this solution.

I've not tried the `.zshenv` method, I don't know how to setup this. I don't even know what a `.zshenv` is.
