### ISSUE TITLE
Wrapping applications

### ISSUE THREAD

**Issue by jksdua** [Unitech/pm2#1114]
Hey guys,

Is it possible to add a wrapper for all NodeJS apps started with PM2?

Use case:

Execute code for error handling or monitoring common across all apps similar to how PM2 handles clustering.

Example code:

``` js
require('pmx').init({
   http: true
});
```

**Comment by jshkurti** [comment]
Whell that depends, if we're talking about just injecting pmx in your app, cluster mode already does that (and fork mode will do as well soon, we're working on it).
If you're talking about more specific configurable wrapping, that is going to be a little tricky :)

**Comment by jksdua** [comment]
For now, its just pmx since I am using PM2 only for dev projects. Running in cluster mode worked like a charm.

However, it would be nice to have a generic version that can be used for prod servers since we use in-house error handling and log servers. Something like:

```js
module.exports = function(done) {
   // run init code here

   done();
}
```

P.S Keymetrics is looking pretty awesome so far too :)
