### ISSUE TITLE
pm2, node 0.10.3x, production - clustersetup: howto

### ISSUE THREAD

**Issue by whyhankee** [Unitech/PM2#1117]
I want to use PM2 to manage multiple processes on my production environment.

Setup:
- Ubuntu 14.04.2 LTS
- Latest stable node 0.10.3x (rationale: http://bit.ly/1FQX9OZ)
- The app is a typical express setup
- pm2@0.12.8

However, I’m confused about the clustering setup, when I want to use multiple processes for an app I have to choose between two modes ‘fork_mode’ and ‘cluster_mode’.

* fork_mode gives me EADDRINUSE on all but the the first process. I imagine because there is no clustering setup so multiple processes don't share the same port

* cluster_mode tells me it should not be used on production and the docs tell me that 0.10 is not supported (0.11 / 0.12 or io.js). However, it seem to work except that pm2 does not seem to release the port when I stop the process (or delete the process). This issue is also mentioned in #74

There must be something i’m missing. What’s the preferred way to get PM2 cluster-setup for my 0.10.3x app in production?

**Comment by balintbako** [comment]
We are using it with 2 process.json files and Apache2 to do the balancing, which is a workaround only but it work.

**Comment by jshkurti** [comment]
'fork_mode', as its name says it's just a fork, there is no clustering, launching an app twice in fork mode is equivalent to ```node app.js; node app.js``` so it's normal to get an EADDRINUSE error :)

On the other hand 'cluster_mode' does spawn multiple workers of the same app which are sharing the same listening port. It should release the port as soon as you stop/kill the process. If it doesn't, it's a bug. In this case I would need some ```~/.pm2/pm2.log``` output to investigate the issue.

I would highly suggest you to use Node.js v0.12.x if possible ;)

**Comment by whyhankee** [comment]
@jshkurti good to hear that 0.10 should still be supported.
Is the cluster mode stable enough to use on production?

I think this is all you need to reproduce the issue:

  wijhenke@ubdev $ node -v
v0.10.36


  wijhenke@ubdev $ telnet localhost 1337
Trying ::1...
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused



* ~/git/pm2test
  wijhenke@ubdev $ pm2 start pm2test.json
[PM2][WARN] You should not use the cluster_mode (-i) in production, it's still a beta feature. A front HTTP load balancer or interaction with NGINX will be developed in the future.
[PM2] Process launched
┌──────────┬────┬─────────┬───────┬────────┬─────────┬────────┬─────────────┬──────────┐
│ App name │ id │ mode    │ pid   │ status │ restart │ uptime │ memory      │ watching │
├──────────┼────┼─────────┼───────┼────────┼─────────┼────────┼─────────────┼──────────┤
│ pm2test  │ 0  │ cluster │ 15284 │ online │ 0       │ 0s     │ 15.773 MB   │ disabled │
│ pm2test  │ 1  │ cluster │ 15290 │ online │ 0       │ 0s     │ 15.777 MB   │ disabled │
└──────────┴────┴─────────┴───────┴────────┴─────────┴────────┴─────────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app



* ~/git/pm2test
  wijhenke@ubdev $ telnet localhost 1337
Trying ::1...
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
^]

telnet> Connection closed.



* ~/git/pm2test
  wijhenke@ubdev $ pm2 stop pm2test.json
[PM2] Stopping pm2test.json
[PM2][WARN] You should not use the cluster_mode (-i) in production, it's still a beta feature. A front HTTP load balancer or interaction with NGINX will be developed in the future.
[PM2] Process 0 restarted
[PM2] Process 1 restarted
┌──────────┬────┬─────────┬─────┬─────────┬─────────┬────────┬────────┬──────────┐
│ App name │ id │ mode    │ pid │ status  │ restart │ uptime │ memory │ watching │
├──────────┼────┼─────────┼─────┼─────────┼─────────┼────────┼────────┼──────────┤
│ pm2test  │ 0  │ cluster │ 0   │ stopped │ 0       │ 0      │ 0 B    │ disabled │
│ pm2test  │ 1  │ cluster │ 0   │ stopped │ 0       │ 0      │ 0 B    │ disabled │
└──────────┴────┴─────────┴─────┴─────────┴─────────┴────────┴────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app



* ~/git/pm2test
  wijhenke@ubdev $ telnet localhost 1337
Trying ::1...
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
^]

telnet> Connection closed.



* ~/git/pm2test
  wijhenke@ubdev $ pm2 kill
[PM2] Stopping PM2...
[PM2] deleteProcessId process id 0
[PM2] deleteProcessId process id 1
[PM2] All processes has been stopped and deleted
[PM2] PM2 stopped



* ~/git/pm2test
  wijhenke@ubdev $ telnet localhost 1337
Trying ::1...
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused


=[pm2test.js]===================================================================
var http = require('http');
http.createServer(function (req, res) {
      res.writeHead(200, {'Content-Type': 'text/plain'});
        res.end('Hello World\n');
}).listen(1337);


=[pm2test.json]=================================================================
{
    "name" : "pm2test",
    "script": "./pm2test.js",
    "exec_mode": "cluster",
    "instances": 2,
    "merge_logs": true
}


=[~/.pm2/pm2.log]===============================================================
2015-03-24 16:03:32: [PM2][WORKER] Started with refreshing interval: 30000
2015-03-24 16:03:32: [[[[ PM2/God daemon launched ]]]]
2015-03-24 16:03:32: BUS system [READY] on port /home/wijhenke/.pm2/pub.sock
2015-03-24 16:03:32: RPC interface [READY] on port /home/wijhenke/.pm2/rpc.sock
2015-03-24 16:03:32: Starting execution sequence in -cluster mode- for app name:pm2test id:0
2015-03-24 16:03:32: App name:pm2test id:0 online
2015-03-24 16:03:32: Starting execution sequence in -cluster mode- for app name:pm2test id:1
2015-03-24 16:03:32: App name:pm2test id:1 online
2015-03-24 16:03:44: Stopping app:pm2test id:0
2015-03-24 16:03:44: App name:pm2test id:0 exited with code 143
2015-03-24 16:03:44: Process with pid 15453 killed
2015-03-24 16:03:44: Stopping app:pm2test id:1
2015-03-24 16:03:44: App name:pm2test id:1 exited with code 143
2015-03-24 16:03:44: Process with pid 15459 killed
2015-03-24 16:03:54: PM2 is being killed via kill method
2015-03-24 16:03:55: RPC socket closed
2015-03-24 16:03:55: PUB socket closed

**Comment by jshkurti** [comment]
Okay, so when your app is 'stopped', the server is still listening...
I'm going to inspect this.
Thanks for the feedback.

**Comment by whyhankee** [comment]
the server is not listening anymore, however, the port is not released :(

still, the other question is: is cluster_mode stable enough for production use?

**Comment by soyuka** [comment]
It's not according to nodejs:

[0.12.1 docs](https://nodejs.org/api/cluster.html#cluster_cluster) Unstable
[0.10.38 docs](https://nodejs.org/docs/v0.10.38/api/cluster.html#cluster_cluster) Experimental

With 0.10 we had many issues while using the cluster, I would not advice to use it in production.

**Comment by jshkurti** [comment]
cluster_mode with latest PM2 + Node v0.12.0 is stable enough for production yeah.
I wouldn't say so for Node 0.10.x, but it can still work I guess :)

**Comment by jshkurti** [comment]
![pm2-port-release](https://cloud.githubusercontent.com/assets/7647602/6806915/dd276ba4-d24b-11e4-91df-ad7cafea01dc.png)

Point is, it's not a PM2 bug, it's a cluster bug which happens with Node 0.10.x.
I tired with 0.11.x and 0.12.x, everything works fine.
You should really consider using 0.12.x in production :+1:

**Comment by whyhankee** [comment]
Alright thanks for checking! Something to think about

**Comment by Xianwei2Free** [comment]
It's not the problem with version of node or pm2 at all !!!
You just need to kill the daemon thread of node.
#netstat -ntlp |grep 3000
then kill it ...
and start again...
