### ISSUE TITLE
Wrong operation of environment variable.

### ISSUE THREAD

**Issue by ww24** [Unitech/PM2#1124]
I think that this commit d5e731e3 is wrong operation of environment variable.

Example: https://github.com/Unitech/PM2/blob/0.12.8/lib/CLI.js#L961
`process.env.PM2_PROGRAMMATIC === true`
It absolutely not true, because environment variable is string.

**Comment by jshkurti** [comment]
Did this bug occured to you or you've been just reading PM2 code for fun ? :)
Anyway, should be fixed : https://github.com/Unitech/PM2/commit/09d6b18c67d525c682eebcd26b3ea1021e55d162

**Comment by ww24** [comment]
I tried to call

```
var pm2 = require("pm2");
/* ~~~ */
var pm2_path = path.resolve(__dirname, "node_modules/.bin/pm2");
child_process.spawn(pm2_path, ["kill"], {stdio: "inherit"});
```

But I could not get stdout, stderr.

I found wrong operation of environment variable.

https://github.com/Unitech/PM2/blob/0.12.8/lib/Common.js#L169
https://github.com/Unitech/PM2/blob/0.12.8/lib/Common.js#L181

Thanks.

**Comment by Unitech** [comment]
Why do you require pm2 without using it? If you want to see the output, and dont use require pm2, just comment it.

If you use require pm2, you should do something like:

```
var pm2 = require("pm2");

pm2.connect(function() {
    pm2.kill(function() {
        pm2.disconnect();
    });
});
```

**Comment by ww24** [comment]
Oh, That's right. I knew that.
But I want to create my command include pm2.

```js
#!/usr/bin/env node
var pm2 = require("pm2");
var child_process = require("child_process");
var path = require("path");

if (process.argv[2] === "pm2") {
    var args = process.argv.slice(3);
    var pm2_path = path.resolve(__dirname, "node_modules/.bin/pm2");
    child_process.spawn(pm2_path, args, {stdio: "inherit"});
}

/* use pm2.connect (ellipsis) */
```

I can call pm2 command from my_command.

Ex: `./my_command pm2 kill`

I can not get output because wrong operation of `process.env.PM2_PROGRAMMATIC`.

**Comment by ww24** [comment]
If my PR accepted, I can call the following code and get outputs!

```
#!/usr/bin/env node
var pm2 = require("pm2");
var child_process = require("child_process");
var path = require("path");

if (process.argv[2] === "pm2") {
    process.env.PM2_PROGRAMMATIC = 'false'; //set false
    var args = process.argv.slice(3);
    var pm2_path = path.resolve(__dirname, "node_modules/.bin/pm2");
    child_process.spawn(pm2_path, args, {stdio: "inherit"});
}

/* use pm2.connect (ellipsis) */
```
