### ISSUE TITLE
PM2 start doesn't work

### ISSUE THREAD

**Issue by tonymx227** [Unitech/PM2#1128]
I don't know what's happen but for some apps `pm2 start path --name name --watch` doesn't work...

When I execute the command `npm start` on my server the app works perfectly but with pm2 it seems not working...

You have to know that the app works on local and on my remote server using `npm start` but not with pm2...

Error : 

    ReferenceError: /var/www/nodejs/adms-architectes.fr.3006/app/views/layout.ejs:6
       4|     <head> 
       5|       <title> 
    >> 6|         <% if(typeof page !== 'undefined') { %> 
       7|           <% if(page.seo_title) { %> 
       8|             <%-page.seo_title%> 
       9|           <% } else { %> 

    options is not defined
       at eval (eval at <anonymous> (/var/www/nodejs/adms-architectes.fr.3006/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:237:14), <anonymous>:29:623)
       at eval (eval at <anonymous> (/var/www/nodejs/adms-architectes.fr.3006/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:237:14), <anonymous>:29:7607)
       at /var/www/nodejs/adms-architectes.fr.3006/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:250:15
       at Object.exports.render (/var/www/nodejs/adms-architectes.fr.3006/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:288:13)
       at Object.exports.renderFile (/var/www/nodejs/adms-architectes.fr.3006/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:318:20)
       at module.exports (/var/www/nodejs/adms-architectes.fr.3006/node_modules/ejs-locals/index.js:85:7)
       at /var/www/nodejs/adms-architectes.fr.3006/node_modules/ejs-locals/index.js:131:7
       at Object.exports.renderFile (/var/www/nodejs/adms-architectes.fr.3006/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:318:3)
       at View.module.exports [as engine] (/var/www/nodejs/adms-architectes.fr.3006/node_modules/ejs-locals/index.js:85:7)
       at View.render (/var/www/nodejs/adms-architectes.fr.3006/node_modules/microscope-web/node_modules/express/lib/view.js:76:8)

Logs : 

    (out): Executing (default): SHOW INDEX FROM `Users`
    (out): database synchronized
    (out): Gestiaweb est lançé avec le port 3006!
    (out): GET / 500 23ms - 1.93kb
    (out): GET / 500 8ms - 1.93kb
    (out): GET / 500 6ms - 1.93kb
    (err):     at View.render (/var/www/nodejs/adms-architectes.fr.3006/node_modules/microscope-web/node_modules/express/lib/view.js:76:8)
    (err): ReferenceError: /var/www/nodejs/adms-architectes.fr.3006/app/views/layout.ejs:6
    (err):     4|     <head>
    (err):     5|       <title>
    (err):  >> 6|         <% if(typeof page !== 'undefined') { %>
    (err):     7|           <% if(page.seo_title) { %>
    (err):     8|             <%-page.seo_title%>
    (err):     9|           <% } else { %>
    (err): options is not defined
    (err):     at eval (eval at <anonymous> (/var/www/nodejs/adms-architectes.fr.3006/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:237:14), <anonymous>:29:623)
    (err):     at eval (eval at <anonymous> (/var/www/nodejs/adms-architectes.fr.3006/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:237:14), <anonymous>:29:7607)
    (err):     at /var/www/nodejs/adms-architectes.fr.3006/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:250:15
    (err):     at Object.exports.render (/var/www/nodejs/adms-architectes.fr.3006/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:288:13)
    (err):     at Object.exports.renderFile (/var/www/nodejs/adms-architectes.fr.3006/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:318:20)
    (err):     at module.exports (/var/www/nodejs/adms-architectes.fr.3006/node_modules/ejs-locals/index.js:85:7)
    (err):     at /var/www/nodejs/adms-architectes.fr.3006/node_modules/ejs-locals/index.js:131:7
    (err):     at Object.exports.renderFile (/var/www/nodejs/adms-architectes.fr.3006/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:318:3)
    (err):     at View.module.exports [as engine] (/var/www/nodejs/adms-architectes.fr.3006/node_modules/ejs-locals/index.js:85:7)
    (err):     at View.render (/var/www/nodejs/adms-architectes.fr.3006/node_modules/microscope-web/node_modules/express/lib/view.js:76:

**Comment by soyuka** [comment]
It's your app that has an issue not pm2.

**Comment by tonymx227** [comment]
When I execute the command `npm start` on my remote server the app works perfectly...

**Comment by rdubrock** [comment]
Heyo, I was having this same problem, and I figured out why. If you are running Express, your npm start script is probably pointing at './bin/www' or something along those lines, not an app.js. You can solve the problem by running pm2 start ./bin/www

**Comment by nbpalomino** [comment]
Thanks @rdubrock THATS THE SOLUTION... NICE...

**Comment by asifmai** [comment]
Thanks @rdubrock, it works.

**Comment by barrard** [comment]
I'm having a similar issue.  The app is in ./bin/www   If i run `node bin/www` it works.  But when i run `pm2 bin/www` I can see from the logs that my `.env` file is missing, because session secret and port number are not getting set.  Any ideas? Thanks!
