### ISSUE TITLE
howto: restart --start a nonexistent service

### ISSUE THREAD

**Issue by whyhankee** [Unitech/PM2#1129]
Hi, 

It would really be useful if there was a #pm2 irc-channel in (for example) Freenode for this kind of questions, but here goes :)

I'm trying to achieve a deployment strategy to servers currently running the processes and servers that are *not* running the processes. The servers *not* running the services are spare-servers that i would like to boot on special moments when we expect excessive traffic.

Note: I boot the spare services with the services stopped to avoid having old software in the load-balancer.

Currently, my deployment expects running services so after uploading the new sources the deployment tools execute `npm restart xxx` to restart the running services.

Now, to get to these situations working I tried the following on the spare servers:
* registered the processes (pm2 start xxx.json) and stopped them (pm2 stop xxx). saved the state (pm2 save) and rebooted the server. When I rebooted the server the services were running (not stopped as i expected) - Not good :(
* changed deployment instructions to `pm2 start pm2_start_xxx.json` . This however adds new processes to the list (even when the name is already used)

Is there a a way to achieve what i want to do? I can imagine  a `pm2 restart xxx.json --start' which would restart a processes mentioned in the json file, or start if it was not started already.

Thanks

(edit: typo's)

**Comment by klinquist** [comment]
Maybe I'm missing something.... If you want services to be stopped when you startup, just don't ever pm2 save and/or  don't run the PM2 startup script.    Use pm2 "startOrRestart" xxx.json  to start a service or restart a service if it's already running (won't spawn another instance).

**Comment by whyhankee** [comment]
I'ts not you that's missing something, it's me. 'startOrRestart' is exactly what I needed and it's working nicely. Thanks very much!
