### ISSUE TITLE
Is that possible to use different app arguments for different environment  when using pm2-deploy?

### ISSUE THREAD

**Issue by idy** [Unitech/PM2#1130]

**Comment by kaven276** [comment]
My app will deploy to different env that start with different argv, too. 

Some app configuration parts can be set in json:deploy:deploy_id section,
so each deployment configuration can have its own setting.

**Comment by kaven276** [comment]
it include out_file, error_file path, args, max_memory_restart ...

**Comment by idy** [comment]
If I have three apps, how to set the args to different apps? json:deploy:deploy_id:app_id£¿thanks.

**Comment by idy** [comment]
Thanks to @kaven276, I got the solution. The trick is in json:deploy:post-deploy, I can run different json file from one ecosystem.json file.
