### ISSUE TITLE
pm2 startup, pre-startup script?

### ISSUE THREAD

**Issue by willyaranda** [Unitech/pm2#1131]
Hi!

We are looking into using PM2 to be integrated on AMIs and autodeploy/scaling on EC2.

My question is… we have a AMI that autostarts our SW at boot time, is it possible to execute a pre-launch script? For example: `git pull -u ; npm install`, so we can have a "old" image, but that can be updated at launch time, without us to build another AMI every time we have a change in our code (as we do a rolling release).

Do you know any way to do this?

Thanks in advance for this such amazing piece of node software

**Comment by klinquist** [comment]
I think this would be easy to script ... in your /etc/init.d/pm2-init.sh

Find where it says:
```
start() {
    echo "Starting $NAME"
    super $PM2 resurrect
}
```

And change it to something like... (note: completely untested):
```
start() {
    find /myNodeScripts -maxdepth 1 -type d -exec cd {} && git pull -u && npm install
    echo "Starting $NAME"
    super $PM2 resurrect
}
```
