### ISSUE TITLE
Monitoring pm2

### ISSUE THREAD

**Issue by masterkorp** [Unitech/PM2#1132]
Hello everyone,

I would like to monitor pm2.

What information do you recommend besides a basic ``pm2 list | grep myapp`` ?

I would like to retrieve detailed stats about the pm2 daemon and its child processes ?

**Comment by klinquist** [comment]
PM2 offers keymetrics.io which is awesome.
We already paid for mmonit so that's what I use.

Here's an example of my monit config for my "timer" app:

CHECK PROCESS TimerApp MATCHING /data/timer/app.js
      start program = "/bin/bash -c 'PM2_HOME=/home/ubuntu/.pm2 /home/ubuntu/bin/pm2 startOrRestart /data/timer/pm2.json' " as uid ubuntu
      stop program =  "/bin/bash -c 'PM2_HOME=/home/ubuntu/.pm2 /home/ubuntu/bin/pm2 stop /data/timer/pm2.json' " as uid ubuntu
      if changed pid then alert

**Comment by michaelBenin** [comment]
You can run:

````
pm2 monit
````

**Comment by jshkurti** [comment]
```pm2 desc <app id>```

**Comment by jshkurti** [comment]
Or, as @klinquist said, you can use https://keymetrics.io ;)
