### ISSUE TITLE
Multiple Servers

### ISSUE THREAD

**Issue by CrackerakiUA** [Unitech/pm2#1134]
Do you have tools to communicate between PM2 instances in different server, if not do you plan to add those? My wondering is for Load Balance between servers.

**Comment by PKuebler** [comment]
I want to use PM2 internally. There is in the system a worker gets the number of jobs that need to be processed in real-time as possible.
If a server does not come from behind, the worker should run on two servers in multiple instances.

My Dream: I send all the jobs on a socket on a port and PM2 shares the request on to instances on all servers.

I think I need a second load balancer in front of it. :(

**Comment by CrackerakiUA** [comment]
PKuebler do you answering my question? if yes i didn't understand it

**Comment by Unitech** [comment]
Would [be a great extension to develop for PM2](https://github.com/pm2-hive). We are currently working on a system module to provide this feature on the PM2 side. Else we are also thinking about making a uniformized communication system between all PM2 linked to the same bucket on [keymetrics.io](https://keymetrics.io)

**Comment by duraki** [comment]
Killer feature. Is this expected for sometimes? It's the only thing I miss in process managers.

**Comment by vmarchaud** [comment]
As said by @Unitech above, we developed a solution that is available at https://keymetrics.io/, closing.
