### ISSUE TITLE
how to use load balancer in node 0.10.*

### ISSUE THREAD

**Issue by simonchan2013** [Unitech/PM2#1135]
Excuse me, it's said that should not use -i in node 0.10.* to start multi instance for load blancer! So what can I do instead, I have no idea about it, could you give me some advices.thanks

**Comment by jorge-d** [comment]
Hi,

There are plenty great resources on the web about how to do load balancing with nodeJS, [this one](http://blog.keithcirkel.co.uk/load-balancing-node-js/) seems to fit your needs !

**Comment by soyuka** [comment]
Cluster on node `0.10` isn't stable! Please use node `0.12`. On pm2 you can use the embed cluster by launching your app with the `-i` flag. 
This question seems to be a global matter that should be posted on stackoverflow instead of here (it not beeing an issue).

Closing.
