### ISSUE TITLE
Git servcies

### ISSUE THREAD

**Issue by dorshaypoob** [Unitech/PM2#1136]
hi

i thought about an idea that might be great to have on you software.
to have a service that configured in the JSON with git url and that every time i push new version to the git the server will update automatically and restart the service.

**Comment by rashthedude** [comment]
Like a deployment script(e.g. capistrano etc..)?

**Comment by dorshaypoob** [comment]
Like how google app engine push to deploy worked until last year.
On way to do it is a git hook that pull the latest commit from github and if its set to auto restart it will.
I dont think its a loot of work and will be happy to help.
In order to do it you should keep in mind to set also username and password for private repos.

**Comment by jorge-d** [comment]
You can use [pm2-deploy](https://keymetrics.io/2014/06/25/ecosystem-json-deploy-and-iterate-faster/) for that, the only thing is that you must type the deploy command :)

**Comment by soyuka** [comment]
Thanks @jorge-d and :+1: indeed.
Closing as a non-issue.

**Comment by alchemytechsolutions** [comment]
Is there a way to deploy a specific git tag?
