### ISSUE TITLE
Make pm2 compatible with logrotate

### ISSUE THREAD

**Issue by abarre** [Unitech/pm2#114]
Do you handle the rotation of the log files? If yes, how do you do that ?

In our server, we use `logrotate` to rotate the log files every day.
The logrotate configuration file looks like this one :

```
~/log/*.log {
    daily
    missingok
    rotate 52
    compress
    delaycompress
    notifempty
    create 644 nodejs nodejs
    postrotate
      kill -USR2 `cat /pidfile.pid`
    endscript
}
```

Every time `logrotate` moves the file, a signal USR2 is sent to the processus and the processus reopen the log file.

I tried the same with pm2 but the process continues to send the data to the old file rather than creating a new file.

Would you accept a pull request that reopen (i.e recreate) the log file when the process receives a signal USR2 ?

**Comment by sgarbesi** [comment]
+1

**Comment by spemmons** [comment]
Is there a recommendation for configuring logrotate using the comment on Apr 14, 2014 mentioning the pm2 reloadlogs command? I'm not strong enough with logrotate to understand how it helps. Thanks!

**Comment by jshkurti** [comment]
You can now install the module pm2-logrotate `pm2 install pm2-logrotate` which will automatically rotate logs for each application running with PM2 including PM2 logs itself.

See https://www.npmjs.com/package/pm2-logrotate#configure for more info.

**Comment by panuhorsmalahti** [comment]
@jshkurti, could you make a GitHub repository for your module? It would allow me to submit an issue for this error:
```
TypeError: Cannot read property 'length' of undefined
    at C:\Users\panu\.pm2\node_modules\pm2-logrotate\app.js:28:32
    at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by jshkurti** [comment]
https://github.com/pm2-hive/pm2-logrotate

**Comment by soyuka** [comment]
@jshkurti I made a pending PR to add a default logrotate configuration, I just need to move things to the `init` method before we could merge it
