### ISSUE TITLE
Startup Script for Debian

### ISSUE THREAD

**Issue by MujiSayed** [Unitech/pm2#1140]
Hello, I was having issues making pm2 start up my scripts on system reboot. I have a bunch of web apps that are supposed to load up automatically with pm2. I didn't recieve any problems or any errors. yet it still does not start up scripts on boot.

Debian wheezy
node version: 0.12.0
pm2 version 0.12.9

this is what i get when i attempt to run the startup script command:

```
$sudo pm2 startup                                      
#[PM2] Generating system init script in /etc/init.d/pm2-init.sh                  
#[PM2] Making script booting at startup...                                       
#[PM2] -linux- Using the command:                                                
 #     su -c "chmod +x /etc/init.d/pm2-init.sh && update-rc.d pm2-init.sh default
#s"                                                                              
#update-rc.d: using dependency based boot sequencing                             
[PM2] Done.   
$sudo pm2 startup linux                                
#[PM2] Generating system init script in /etc/init.d/pm2-init.sh                  
#[PM2] Making script booting at startup...                                       
#[PM2] -linux- Using the command:                                                
#      su -c "chmod +x /etc/init.d/pm2-init.sh && update-rc.d pm2-init.sh default
#s"                                                                              
#update-rc.d: using dependency based boot sequencing                             
#[PM2] Done.                                                 
```

any help would be greatly appreciated

**Comment by muji8u** [comment]
after taking more look at it, it seems that pm2 does not start on boot

**Comment by NoiseEee** [comment]
Um, *what* was your solution exactly? I'm having a similar problem...

**Comment by muji8u** [comment]
@NoiseEee what is ur problem? It not starting on boot?

**Comment by NoiseEee** [comment]
Correct, it was not starting on boot but I solved it.  It seems the init script sets the PM2_HOME to one involving "root", so I just had to edit it to the correct user / where pm2 was installed.

**Comment by jaime-ez** [comment]
Same issue, it seems debian HOME changes to the root home when sudoing -- not in ubuntu that keeps the sudoers home.
To correct it I'm passing the user's PM2_HOME as env variable:
sudo env PATH=$PATH:' + p.dirname(process.execPath) + 'PM2_HOME=' + add user's pm2 home folder here + ' pm2 startup ' + platform + ' -u ' + user

Hope it helps

**Comment by Unitech** [comment]
https://github.com/Unitech/pm2/issues/2559
