### ISSUE TITLE
Is there a way to filter which envs apps should run?

### ISSUE THREAD

**Issue by cusspvz** [Unitech/pm2#1142]
We have the same `ecosystem.json` for different environments, and we need to run `node-inspector` and `weinre` on our `development` environment but not under `production`.

Since we are using somewhere on our `post-deploy` such like `pm2 start ecosystem.json --env $ENV`, is there a way to add a config on `apps` array which envs they should be supported?

**Comment by cusspvz** [comment]
@fernandoneto can you please follow up this issue?

**Comment by cusspvz** [comment]
ping @Unitech

**Comment by jorge-d** [comment]
Any thoughts @jshkurti ?

**Comment by cusspvz** [comment]
Currently the only option that i've seen for multiple environments was **variable environment definition**, but if the feature that i'm asking for isn't available currently, it wouldn't be a bad idea to allow app overrides per **environment**.

**Comment by cusspvz** [comment]
Since currently you're already using `env` and `env_*`, i would suggest a dollar sign for **environment specific configurations**:

```json
{
  "apps": [
    {
      // ...
      node_args: [ '--debug=5800', '--harmony' ],
      "$production": {
        node_args: [ '--harmony' ]
      }
    }
  ]
}
```

That would allow also ENV variables definition as you are currently doing:

```json
{
  "apps": [
    {
      // ...
      env: { TEST: 'abc' },
      "$production": {
        env: { TEST: 'def' }
      }
    }
  ]
}
```
