### ISSUE TITLE
Pass instance id to app as environment variable

### ISSUE THREAD

**Issue by shaharmor** [Unitech/PM2#1143]
When starting pm2 with multiple instances for a specific app, it would really help a lot if the app itself would get an Int representing its id in the series of instances.

For example, given a pm2 configuration that loads 3 instances:

app1 - instance id 0
app2 - instance id 1
app3 - instance id 2

In the node-config module they use the NODE_APP_INSTANCE env variable, but setting it in the pm2.json file itself can also work.

**Comment by jshkurti** [comment]
Hi,
```process.env.pm_id``` does that :)

**Comment by shaharmor** [comment]
Any chance to make it configurable?

**Comment by jshkurti** [comment]
I'm not sure I'm understanding this.
You want to set the id yourself when you launch your app, is that it ?

**Comment by shaharmor** [comment]
Let me explain:
For example, i want to start a 6 instance app that listens on ports starting from 8080 to 8085.
I need to know which instance is currently running within those 6 instances so i will know whether i should bind to 8080, 8081, etc...

I need this ID to get passed to the instance itself (probably through environment variables).
Also, this ID needs to be a zero-indexed (or one-indexed) ID, based on the current number of instances in PM2, and not the pm2-id (which after few starts/restarts can get to a much bigger number).

Does that make sense?

**Comment by soyuka** [comment]
You can set a `port` indication to your processes, I think that it'll then
be available in the pm2 list.

**Comment by shaharmor** [comment]
@soyuka not sure i understand... can you give me an example? Define the port where?
I prefer the port to be configured in my central config file, as obviously its not related to pm2... and i might want to use that instance ID for other things than the port.

**Comment by shaharmor** [comment]
Lets say i have the following `pm2.json` file:
```
{
  "apps": [
    {
      "name": "myapp",
      "script": "./index.js",
      "instances": 6,
      "instance_id_env": "NODE_APP_INSTANCE"
      "exec_mode": "fork",
      "env": {
        "NODE_ENV": "production"
      }
    }
  ]
}
```

I want to be able to do this in my `index.js` file:

```
var instanceId = process.env.NODE_APP_INSTANCE;
var express = require('express');
var app = express();

app.listen(8080 + parseInt(instanceId, 10));
```

and that PM2 will populate the NODE_APP_INSTANCE id by itself. (being one of 0 to 5 for this example)

right now i solve it using a different script to start the instances myself:

```
var instances = 6;
for (var i = 0; i < instances; i++) {
    // start a standard pm2 json file
    pm2.startJson(path.resolve(__dirname, 'pm2.json'), {
        additional_env: {
            NODE_APP_INSTANCE: i
        }
    }, function(err) {
        if (err) {
            throw new Error(err.msg);
        }

        // make sure we only disconnect after all instances were started
        if (++started === instances) {
            pm2.disconnect();
        }
    });
}
```

but that takes the point out of pm2's multi instance feature...

**Comment by jshkurti** [comment]
Ok I got it. we could implement this indeed.
But, why would you want the same app to listen on differents ports ?
Cluster module handles that for you already.
Take a look at this post : https://keymetrics.io/2015/03/26/pm2-clustering-made-easy/

**Comment by soyuka** [comment]
@shaharmor nvm about the `port` it was removed in an earlier release ^^.

@jshkurti Maybe he want's to use something like HAProxy in front of the web app to load-balance to one of his pre-defined ports?

**Comment by shaharmor** [comment]
Actually thats exactly what i want, but i can think of other usages for
that feature such as differentiate instance level logs

**Comment by jshkurti** [comment]
Okay I'm going to implement this feature :)
Would you like to receive via env such as ```process.env.instance_id``` ?

**Comment by shaharmor** [comment]
I think having it configureable in the json file would be best, but if you
ask me i'd go for process.env.NODE_APP_INSTANCE

**Comment by danieljuhl** [comment]
@jshkurti Depending on the setup, you might want to start multiple instances, in a port range, and have your webserver (eg. nginx) handle the distribution - instead of using the cluster mode.

**Comment by jshkurti** [comment]
It's done :)
```process.env.NODE_APP_INSTANCE```
```npm i -g git://github.com/Unitech/PM2#development```
Tell me if it works please.
Thanks!

**Comment by shaharmor** [comment]
Works great!
Thanks a lot for the quick fix.

**Comment by danieljuhl** [comment]
Seems to be working just fine here as well.. thanks.

**Comment by shaharmor** [comment]
@jshkurti now that this feature is done, will it be ready to change the `pm2 restart all` (And `pm2 restart app`) command to restart the instances of the same app one at a time instead of all of them together?

For example, if i have a 6 instance app, instead of doing this:

```
delete instance 1
delete instance 2
...
delete instance 6

start app 1
start app 2
...
start app 6
```
it will do it like this:
```
delete instance 1
start instance 1
delete instance 2
start instance 2
...
delete instance 6
start instance 6
```

this will help in having at most 1 instance down when restarting, instead of all of them (Making the server basically unavailable for a brief moment)

**Comment by XadillaX** [comment]
But there's no `process.env.NODE_APP_INSTANCE` value. Has it been published to NPM? Or just in the branch develop?

**Comment by jshkurti** [comment]
Only works in cluster_mode.
Yes it has been published on npm :)

**Comment by sarthakz9** [comment]
well I would like to use this feature ( process.env.NODE_APP_INSTANCE ) without the cluster mode. Does that make any difference ?

**Comment by smeijer** [comment]
@sarthakz9, isn't there always just a single instance in that case?
