### ISSUE TITLE
Starting pm2 using an upstart script (ghost.conf)

### ISSUE THREAD

**Issue by karan** [Unitech/pm2#1147]
I'm trying to run a ghost blog using an upstart script. This is what my `/etc/init/ghost.conf` file looks like:

``` bash
description "Ghost: Just a blogging platform"

start on (local-filesystems and net-device-up IFACE=eth0)
stop on runlevel [!12345]

# If the process quits unexpectadly trigger a respawn
respawn

setuid ghost
setgid ghost
env NODE_ENV=production
chdir /var/www/ghost

#exec /usr/local/bin/npm start --production
exec /usr/local/bin/pm2 start index.js --run-as-user ghost --name ghost

pre-stop exec /usr/local/bin/npm stop --production
```

If I run `/usr/local/bin/pm2 start index.js --run-as-user ghost --name ghost` from my ghost blog dir, the blog starts up and I can see it in `pm2 ls` list. But if I do `service ghost start` it just won't start up and I can't see it in the result of `pm2 ls`

``` bash
root@goelioblog:/var/www/ghost# service ghost start
start: Job is already running: ghost
root@goelioblog:/var/www/ghost# service ghost restart
ghost stop/waiting
ghost start/running, process 8787
```

**Comment by Fast007** [comment]
I have exactly the same problem. Starting the server without the gost option, though.

**Comment by soyuka** [comment]
We have a lot of ghost resources there: https://github.com/Unitech/PM2/blob/master/ADVANCED_README.md#external-resources-and-articles. 

In the mean time, `--run-as-user` is not part of pm2 anymore, please use `su - $USER` to run pm2 with the correct user. See [this example](https://github.com/Unitech/PM2/blob/master/lib/scripts/pm2-init.sh#L37). Also state node version, pm2 version and OS, thanks.
