### ISSUE TITLE
How to cut the log file?

### ISSUE THREAD

**Issue by davieyeye** [Unitech/PM2#1148]
the log file is very big(about 1.2G, and it is still increasing). How to cut a big log file to multiple small log files? Has pm2 support anyway to cut the log file automatically?

**Comment by Jokero** [comment]
https://github.com/Unitech/PM2/issues/114

**Comment by Unitech** [comment]
nope you need to use logrotate to do this, we may do a module at some point to handle the logrotation https://github.com/pm2-hive/pm2-logrotate

**Comment by jshkurti** [comment]
You can now install the module pm2-logrotate `pm2 install pm2-logrotate` which will automatically rotate logs for each application running with PM2 including PM2 logs itself.

See https://www.npmjs.com/package/pm2-logrotate#configure for more info.
