### ISSUE TITLE
feature request programmatic api should expose a 'start' method which consumes the same json format as command line

### ISSUE THREAD

**Issue by breathe** [Unitech/PM2#1152]
Would be nice if programmatic api exposed a start method which could consume the same format 'application' JSON file as can be passed on command line ...

**Comment by adrian-ludwig** [comment]
but you can do pm2.start('definitions.json', function() {})

**Comment by Unitech** [comment]
You can now do:

```javascript
pm2.start({
  script        : 'path/to/my/script.js',
  instances : 5
}, function(err, ret) {});
```

https://github.com/Unitech/PM2/commit/dd34c7080b8781eb564f15188b528ff17d980b6a
https://github.com/Unitech/PM2/commit/7fe41a8767d4f163b2538e8ba44a3ba18bef82fc

Cheers!
