### ISSUE TITLE
Add support for negative instances count

### ISSUE THREAD

**Issue by shaharmor** [Unitech/PM2#1154]
Hi,

I think it would be nice to have an option for the instances option to be negative  (for example -2), which will then start N-2 instances, N being the cpu count.

So on an 8 core server, i could set instances to "-2", and it will spawn 6 instances, and on a 4 core server it will spawn two.

What do you think?

**Comment by jshkurti** [comment]
Here we go ;)
```npm i -g git://github.com/Unitech/PM2#development```

**Comment by shaharmor** [comment]
Awersome. Thanks a lot.
