### ISSUE TITLE
Don't duplicate processes when start "pm2 start process.json" twice

### ISSUE THREAD

**Issue by SerjoPepper** [Unitech/PM2#1160]
When start "pm2 start process.json" on same file second time its duplicate all running processes.

**Comment by klinquist** [comment]
That's expected.  Use pm2 startOrRestart process.json instead.

**Comment by jorge-d** [comment]
As @klinquist stated you can use `StartOrRestart` or `StartOrReload`, see the [relevant documentation](https://github.com/Unitech/PM2/blob/2587c46835911d31391118c0d7c51ac3b982154d/ADVANCED_README.md#commands).
