### ISSUE TITLE
redirect log to syslog ?

### ISSUE THREAD

**Issue by mderazon** [Unitech/PM2#1163]
I've tried
```
pm2 -l /var/log/syslog start app.js
```

but it won't work for unprivileged  user.

Any other idea ?

**Comment by Unitech** [comment]
Hey,

Try this module: https://github.com/pm2-hive/pm2-syslog

**Comment by mderazon** [comment]
thanks, couldn't get it to work for some reason pm2-hive/pm2-syslog#1

**Comment by Unitech** [comment]
the module has been fixed, but the module used to redirect to syslog, [ain2](https://www.npmjs.com/package/ain2), may be difficult to install under other version, feel free to PR the [pm2-syslog](https://github.com/pm2-hive/pm2-syslog) module

**Comment by nodesocket** [comment]
:+1: but `pm2-syslog` is not working for us. See: https://github.com/pm2-hive/pm2-syslog/issues/3

**Comment by mjmasn** [comment]
@Unitech pm2-syslog doesn't work. Have tried in OSX 10.11.2 and Ubuntu 14.04.2 LTS (including running node as root). Any ideas?

**Comment by adamsea** [comment]
@Unitech I am having the same issue - installed pm2-syslog but no logs are redirected.  Any help you can provide would be greatly appreciated, thanks!

**Comment by celteeka** [comment]
Any update on this?

**Comment by vad1m** [comment]
@Unitech this feature is very needed in distributed environments, could you please have a look? Thanks in advance!

**Comment by celteeka** [comment]
@vad1m I am successfully using pm2-syslog so I suggest you take a look at it.
