### ISSUE TITLE
PM2 seems to run it's own daemon under www-data

### ISSUE THREAD

**Issue by omfgitsasalmon** [Unitech/PM2#1168]
I wrote an app that allows me to manually restart the pm2 instance or pull the logs dynamically from the jlist command.

After updating PM2 today, I lost the ability to check the instance's online / offline status, and during debugging. I realized that jlist returned `[]`

This alerted me and I tried to debug some more. I realized that running pm2 status via php returns an empty table. No instances was shown in PHP.

When I tried to do pm2 status right after rebooting the server, it shows the "Daemonizing PM2" as if it ran it's own version of PM2 under it's own daemon.

Can anyone help me? This update broke my app :(

**Comment by klinquist** [comment]
Are you sure PM2 is being run as the same user as PHP?
sudo ps aux | grep PM2

**Comment by omfgitsasalmon** [comment]
No it was not, but it was working fine before I updated.

It's currently running as my user and no www-data.

**Comment by klinquist** [comment]
Well thats the problem - you need them to both run as the same user.
If the daemon is running as root, you'll need to sudo pm2 status to see the current status.

**Comment by omfgitsasalmon** [comment]
The daemon is running as user (my user account) but I use sudo in my php because it's running as www -data 




How do I decide under which user my pm2 is running?




Best Regards,
Alson.
Caffein8 Creative LABS﻿
www.caffein8.com

**Comment by klinquist** [comment]
If php is running as root then you'll need to run pm2 as root to see the processes. 

When you set PM2 to startup automatically on boot, it should be running as root by default. 
https://github.com/Unitech/PM2/blob/master/ADVANCED_README.md#startup-script

**Comment by omfgitsasalmon** [comment]
Php is not running as root, it's running as www-data. Just that I use
`exec('sudo pm2 jlist');`

Yes, my pm2 is set up to launch at boot, but it still launch as user.

Best Regards,
*Alson.*
(65) 9459 7259
*Caffein8 Creative LABS﻿*
www.caffein8.com

**Comment by jshkurti** [comment]
```Is there anyway to unify PM2 into 1 single daemon regardless of owner?```

No, for security reasons.

Have you tried just removing the 'sudo' in your command this way pm2 and php runs as the same user. It should work.

**Comment by omfgitsasalmon** [comment]
I did, without sudo, it returns null.

Best Regards,
*Alson.*
(65) 9459 7259
*Caffein8 Creative LABS﻿*
www.caffein8.com

**Comment by Unitech** [comment]
You can run multiple PM2 under different users by using PM2_HOME

```
$ PM2_HOME='.pm2-conf-for-user-1' pm2 start app.js

$ PM2_HOME='.pm2-conf-for-user-2' pm2 start app.js
```

This will create two differents deamon accessible for each user.

You can also share the same PM2 for multiple user by setting the right user group to the configuration folder. So if the two users belong to the same group they will be able to interact with the same PM2

```
$ PM2_HOME='/etc/.pm2' pm2 start app.js

$ chgrp group_name /etc/.pm2
```
