### ISSUE TITLE
how Watch parent directory ?

### ISSUE THREAD

**Issue by nvcken** [Unitech/PM2#1169]
Because my structure
```
myapp ( root app folder)
	client
	common
	... lib
	.... ... a.js
	.... ... b.js
	server
	... server.js
```

my start script
```
myapp $ pm2 start server/server.js --watch
```

I edit js file in lib folder, app has not autorestart.
How can I make pm2 watch on root app directory and sub-directory or parent of server.js directory ?

**Comment by soyuka** [comment]
If you use a `json` declaration you could set your cwd to the root directory and start the `server/server.js` app:

```
[{
  "name"          : "server",
  "cwd"             : "./",
  "script"           : "server/server.js",
  "watch"          : true
}]
```

Check the [schema](https://github.com/Unitech/PM2/blob/master/ADVANCED_README.md#schema) to see possible values.
