### ISSUE TITLE
Question: revert deployment

### ISSUE THREAD

**Issue by migg24** [Unitech/PM2#1172]
Hi there,

I have a question regarding the revert of a deployment. When I deploy something that does not work, and I do a `revert 1` which yields a state that works. And then I push some "fix" and deploy this again, and it also does not work, and then I do a `revert 1` again. Will pm2 revert back to the first broken version or the state that works?

More technically speaking does pm2 add the result of the revert to the top of the list of deployments or not?

I hope anyone understands what I am trying to find out.

THX in advance,
Michael

**Comment by jorge-d** [comment]
Hi,

It would revert back to the first broken version,
Technically speaking, the magic happens [around here](https://github.com/Unitech/pm2-deploy/blob/master/deploy#L235-L270), it reads the list of deploys from the [.deploys file](https://github.com/Unitech/pm2-deploy/blob/master/deploy#L200-L202) and takes the n-1 !

**Comment by jorge-d** [comment]
Closing now, if you have another question about this feel free to reopen.

**Comment by migg24** [comment]
Thanks!
