### ISSUE TITLE
R&D

### ISSUE THREAD

**Issue by Unitech** [Unitech/pm2#1174]
- [ ] Let PM2 trigger the GC of applications (Better for real-time [ref](http://www.jayway.com/2015/04/13/600k-concurrent-websocket-connections-on-aws-using-node-js/) [expl](http://sysmagazine.com/posts/123154/))
- [x] Wrap fork_mode processes
- [x] Reduce PM2 memory footprint
- [x] Enhance interactor
- [ ] pm2 install git://repo
- [x] pm2 scale <app_name> <instance_number>
- ~~[ ] pm2 teleport <app_name>~~
- [x] Enhance module system

Any ideas, suggestions are welcome,

Alex

**Comment by jshkurti** [comment]
:+1:

**Comment by soyuka** [comment]
We know that by not requiring `coffee` we could same 1mb (not sure if we
skipped it in a condition).
Le mar. 14 avr. 2015 à 19:56, Joni Shkurti <notifications@github.com> a
écrit :

**Comment by Unitech** [comment]
Here? https://github.com/Unitech/PM2/blob/master/lib/ProcessContainer.js#L84

**Comment by soyuka** [comment]
Indeed, is that enough to not load the 1MB?
Anyway :+1:
