### ISSUE TITLE
Enhancement: option to run a process only once

### ISSUE THREAD

**Issue by onlyforart** [Unitech/PM2#1175]
I want to use PM2 to replace a process manager we've been using in-house for a couple years, that we built on top of nodejs 0.10.x and node-forever.

PM2 has everything I need for this transition except one essential feature: the ability to configure a process to run only once and not restart automatically (ie we'd run it perhaps once a day only). All my other processes, I want to be restarted automatically, well, forever.

To be clear, the use case here would be to allow the process in question to be managed by PM2, but only to be run on demand which we'd script to happen perhaps once a day.

Perhaps I can hack that using *max_restarts=1*, but it would be far neater (and clearer to those who follow me in maintaining this code) to have an explicit *run_once* or a *run_on_demand* flag.

By the way, this could be extended with cron-like features ("run at 8.00am every day") but we don't really need that since we can use cron to do that.

**Comment by jshkurti** [comment]
```pm2 start app.js --no-autorestart``` or ```"autorestart" : false``` in the JSON declaration.

```npm i -g git://github.com/Unitech/PM2#development``` if you want to try right now, otherwise the official release is going to come tomorrow :)

**Comment by onlyforart** [comment]
:) wonderful. Thank you

**Comment by jshkurti** [comment]
It's published now ;)
https://github.com/Unitech/PM2/releases

**Comment by jonathan-kosgei** [comment]
@jshkurti Hey, is it possible to set `'autorestart':'false'` with `watch` and still have the process run when the folder or file it's watching is updated? I'd like to run a shell script with composer install or npm install that watches a package.json or composer.json and runs install if the file is updated.

**Comment by mattiasmohlin-gmail** [comment]
@jshkurti Is this new option also available through the API? I'm trying to use it like this:
pm2.start(pm2ConfigFile, { args: "--no-autorestart"}, (err, proc) => { ...
but PM2 still restarts my application. Perhaps I'm using 'args' incorrectly?

**Comment by vmarchaud** [comment]
yeah, `args` here is the arguments you want to give to your process, you should just use : 
```
pm2.start(pm2ConfigFile, { autorestart: false }, (err, proc) => {
});
```

**Comment by john20xdoe** [comment]
can "autorestart" : false be included in one env only in app delcaration?  for example, 
```
env: {
        NODE_ENV: "development",
        autorestart: false
      },
...
```

**Comment by sam3d** [comment]
Any information on @jonathan-kosgei's question?

**Comment by Monkeyyy11** [comment]
Issue moved to [Unitech/.emacs.d #4](https://github.com/Unitech/.emacs.d/issues/4) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Norfeldt** [comment]
@sam3d @jonathan-kosgei I know it's late but think I found a solution for it.

I got this `.env.local` file that I wish to watch and trigger a rerun of a script on it - if it changes. 

I do it by starting nodemon and let that do the watching instead of pm2.

```js
module.exports = {
  apps: [
    {
      name: 'env-local-types-watcher',
      script: 'yarn nodemon --watch ".env.local" --ignore "![.env.local]**/*" --exec "yarn env:write"',
    }
  ],
}

```
