### ISSUE TITLE
Git call running 100% CPU

### ISSUE THREAD

**Issue by janders223** [Unitech/PM2#1177]
PM2: 0.12.10
IOJS: v.1.5.1
OS: Ubuntu 12.04.4 LTS

I am seeing this with a crashed process that is attempting to restart. It seems to be coming from:
https://github.com/keymetrics/vizion/blob/07638d9e90e969829fee36ad0912e5464667186b/lib/git.js#L27

![1__cloud_u12044ltsba-001_____ssh_](https://cloud.githubusercontent.com/assets/719823/7160064/bbb98622-e354-11e4-971c-e9033df454a9.png)

I honestly don't see what the git log has to do with attempting to restart a crashed process, or why it chews up CPU.

**Comment by jshkurti** [comment]
It comes from the vizion module which grabs metadata about the repository.
Which version of vizion do you have ?

**Comment by jshkurti** [comment]
It does indeed refresh the metadata at each restart.

**Comment by jshkurti** [comment]
Normally, these commands are really fast, they shouldn't stay on htop for long but just in case there is a timeout of 60s by default to cancel them if they did not succeed.

**Comment by janders223** [comment]
The installed vizion version is `0.2.5`, installed on this system yesterday. I understand _what_ it is doing, I don't understand why. Timeout or no, they are still pegging the CPU at 100%+ sometimes with an individual process.

**Comment by Unitech** [comment]
@jshkurti we should reduce the timeout to 5-3secs instead of 60s

**Comment by jshkurti** [comment]
@janders223 we will implement a `--no-vizion``` flag soon so you could completely remove this feature.

**Comment by jshkurti** [comment]
Hi @janders223, check out the new release of PM2 https://github.com/Unitech/PM2/releases
You can now specify ```--no-vizion``` flag when you start an app so it won't do any git commands at all ;)

**Comment by janders223** [comment]
While I appreciate the work, this seems like a band-aid for a larger underlying problem. Have you spent any time at all to investigate the actual issue reported here?

**Comment by jshkurti** [comment]
What happens when you ```git show --quiet --format=%H%n%aD%n%s%n%B HEAD``` manually in the folder of your app ?
Does it take a long time to finish ?

**Comment by jshkurti** [comment]
Hmm actually vizion isn't supposed to execute multiple parallel instances but when a restart occurs we refresh the flag value.
I fixed that: https://github.com/Unitech/PM2/commit/eb5b2fa2085f11d42d0cbfac7fee425e18b5bfa9
Can you give it a try please ? Now it should spawn 15 git commands.
```npm i -g git://github.com/Unitech/PM2#development```

**Comment by janders223** [comment]
That seems to have helped.

**Comment by jshkurti** [comment]
Thanks for the feedback :+1:
