### ISSUE TITLE
Options to disable pmx

### ISSUE THREAD

**Issue by hefangshi** [Unitech/PM2#1181]
In most cases, we don't need pmx to make pm2 works, but pmx will use more memory then application itself.

More worse, although I didn't finger out why, pmx will cause our application memory leak (we used domain, and it seems related).

So I suggest that maybe a option to disable the pmx will be fine.

**Comment by askhogan** [comment]
@hefangshi I got the same result... but I was able to stop the leak by turning http off, which is on by default.  Add this inside your app

```
var pmx = require('pmx').init({
  http          : false
});
```

**Comment by jshkurti** [comment]
Here we go : https://github.com/Unitech/PM2/commit/5faefd2ac8e67f4ca1305b28bcbd35761684efc2

**Comment by hefangshi** [comment]
@jshkurti nice work :+1:
