### ISSUE TITLE
How can I run multiple of the same scripts with different arguements?

### ISSUE THREAD

**Issue by paezao** [Unitech/PM2#1183]
It just says that I already have the script running even though Im using a different name. Any clues?

**Comment by jshkurti** [comment]
It is because it checks the path of your file.
Just add ```-f``` ;)

**Comment by paezao** [comment]
Nice! Thanks!

And how could I pass args like node app.js --username blabla --password blabla on the pm2 start command?

**Comment by jshkurti** [comment]
```pm2 start app.js -- --my-custom-arg --my-custom-arg2```

**Comment by paezao** [comment]
lol nice! so easy! thanks a lot
