### ISSUE TITLE
Monit UI breaks with many process

### ISSUE THREAD

**Issue by rodrigok** [Unitech/PM2#1185]
![captura de tela 2015-04-16 as 16 34 34](https://cloud.githubusercontent.com/assets/234261/7189621/7df80cf2-e456-11e4-8fe0-577d65a01890.png)

**Comment by jshkurti** [comment]
Thanks for the feedback.
Have a look at keymetrics.io :)

**Comment by Unitech** [comment]
Unfortunately we cannot expand your terminal :) but sure, have a look at [keymetrics.io](https://keymetrics.io) we did enhancements for monitoring large micro service apps

**Comment by rodrigok** [comment]
But if we could pass a filter to pm2 monit?

**Comment by Unitech** [comment]
something like pm2 monit <app_name> ?

**Comment by rodrigok** [comment]
How can I see only processes with name "web" in pm2 monit?
