### ISSUE TITLE
PM2 startOrReload config.json does not update env vars

### ISSUE THREAD

**Issue by kodypeterson** [Unitech/pm2#1186]
When using a JSON file for application configuration and changing the value of an env variable then running pm2 startOrReload {{pathToConfig}} the env variables are not updated in the app as expected.

Is this expected?

**Comment by dileepfrog** [comment]
Experiencing this issue as well. Stopping and starting reloads the process config but incurs downtime

**Comment by Unitech** [comment]
fixed
