### ISSUE TITLE
Feature request: PM2 logs raw format

### ISSUE THREAD

**Issue by GDownes** [Unitech/PM2#1189]
The pm2 logs command currently prefixes all log messages with additional information as expected. It would be beneficial to have a flag to prevent additional information being prefixed to the log messages to support additional use cases.

A common use case:
Bunyan is a popular logging framework for the NodeJS stack. The additional prefix logging information prevents bunyan from processing the log messages as it expects raw json. Providing the raw log format through pm2 logs would enable quick and easy access for Bunyan users. pm2 logs | bunyan

Current workaround:
Currently to work around this I use the command "tail -f ~/.pm2/log/my.log | bunyan -o short". This workaround is long, hard to remember, and the name of the log files is required, preventing easy access.

Implementation ideas:
Adding a flag --log-raw-format, much like the current --log-date-format, which prevents the additional information prefixing.

**Comment by jshkurti** [comment]
Okay we will do it on the next release
Thanks for the feedback.

**Comment by jshkurti** [comment]
Here we go https://github.com/Unitech/PM2/pull/1201

Can you give it a try ? `npm i -g git://github.com/Unitech/PM2#raw_logs`

It will be included in the next release ;)
