### ISSUE TITLE
PM2 doesn't load piped json

### ISSUE THREAD

**Issue by rainyday** [Unitech/PM2#1190]
PM2 is supposed to be able to start an application based on json piped from stdout but instead it seems to be trying to open the json as a file name:

```bash
$ cat app.json | pm2 start -
[PM2][ERROR] script not found : /home/user/{
  "name": "myapp",
  "script": "bin/www",
  "cwd": "my/app",
  "watch": true,
  "env": {
    "DB_URL": "my://db"
    "NODE_ENV": "production",
    "DEBUG": "pp:*,sequelize"
  }
}
```
```bash
$ pm2 -v
0.12.11
```

I'm able to do this without issue in v0.12.10

**Comment by Unitech** [comment]
fixed and test added to avoid this kind of regression, will be available on next pm2 release
