### ISSUE TITLE
 exponential backoff

### ISSUE THREAD

**Issue by xkxx** [Unitech/PM2#1191]
Hello there,

I have an use case that could benefit from having exponential backoff in case the app is giving up too fast.

I need to maintain a ssh connection with a remote server, which can sometimes go to maintenance mode, during which connections wouldn't be established no matter how many times it tries.

It would be nice in this case if pm2 wait an exponential delay before retrying (perhaps let us specify a maximum time for the delay).

Do you think this would be a helpful feature for other users as well? Just my two cents.

xkxx

**Comment by jshkurti** [comment]
To be honest, this is way to specific to be implemented on the main pm2 release.
But, you could do such a thing by using pm2 programmatically.
You start your app with ```--no-autorestart``` flag (```autorestart: false``` in json declaration) then you check every x seconds that your app is online, when it's not, do your exponential delay stuff before restarting it ;)
