### ISSUE TITLE
pm2 delete bug

### ISSUE THREAD

**Issue by rochael** [Unitech/PM2#1192]
When i use `pm2 delete id`, the terminal will print out "[PM2] Deleting 12 process".
I need to control + c to return to the terminal.   then i use `pm2 l` to print the process list, but the list is empty.   
`ps -elf | grep node ` found the node process still in the memory.

fewer seconds later the node process will be ended one by one. 

env: Ubuntu 14.04   pm2 0.12.3

**Comment by jshkurti** [comment]
Hi,
You should upgrade your pm2, your version is old.
```npm i -g pm2@latest```
I also suggest using Node.js v0.12.2 as well.
Cheers

**Comment by rochael** [comment]
Hi,
Thanks for your reply. The issue is appears on product environment. So it's difficult to upgrade the node and pm2. I hope that has been fixed in the latest version.

Best regards.
