### ISSUE TITLE
startup script per user

### ISSUE THREAD

**Issue by ashconnell** [Unitech/pm2#1193]
I have a project that run staging and production on a single digital ocean droplet. Staging and production both have their own users. The `pm2 startup` command as one of the users creates a init.d script, and running it as another user just overwrites the first script.

**Comment by PierreGambarotto** [comment]
The PR #1202 can solve this problem by adding the username to the init script name. Hope this helps.

**Comment by Unitech** [comment]
https://github.com/Unitech/pm2/issues/2559
