### ISSUE TITLE
Error restarting from watch setting

### ISSUE THREAD

**Issue by lklepner** [Unitech/PM2#1203]
PM2: 2015-04-23 09:45:36: Change detected for app name: Raven Web - restarting
PM2: 2015-04-23 09:45:36: Stopping app:Raven Web id:9
PM2: 2015-04-23 09:45:36: App name:Raven Web id:9 disconnected
PM2: 2015-04-23 09:45:36: App name:Raven Web id:9 exited with code SIGTERM
PM2: 2015-04-23 09:45:37: Process with pid 66009 killed
PM2: 2015-04-23 09:45:37: Starting execution sequence in -cluster mode- for app name:Raven Web id:9
PM2: 2015-04-23 09:45:37: Trace: { [Error: spawn E2BIG] code: 'E2BIG', errno: 'E2BIG', syscall: 'spawn' }
PM2:     at Object.God.logAndGenerateError (/usr/local/lib/node_modules/pm2/lib/God/Methods.js:30:15)
PM2:     at Object.nodeApp (/usr/local/lib/node_modules/pm2/lib/God/ClusterMode.js:52:11)
PM2:     at Object.executeApp (/usr/local/lib/node_modules/pm2/lib/God.js:145:9)
PM2:     at Object.God.startProcessId (/usr/local/lib/node_modules/pm2/lib/God/ActionMethods.js:210:16)
PM2:     at /usr/local/lib/node_modules/pm2/lib/God/ActionMethods.js:395:20
PM2:     at /usr/local/lib/node_modules/pm2/lib/God/ActionMethods.js:265:18
PM2:     at null.<anonymous> (/usr/local/lib/node_modules/pm2/lib/God/Methods.js:202:16)
PM2:     at wrapper (timers.js:265:14)
PM2:     at Timer.listOnTimeout (timers.js:110:15)

**Comment by jshkurti** [comment]
Hi,
E2BIG means that the argument list is too long.
By running `getconf ARG_MAX` you can check the max argument size (in bytes) of your OS.
On my machine it is 2MB.
Any idea why it would exceed the max authorized value in your case ? :/

**Comment by lklepner** [comment]
I'm developing on Mac 10.10.3. My argument list doesn't seem particularly long -

NODE_ENV=local WORKER_TYPE=web \
pm2 start $APPROOT'/../app.js' -i 1 -n "Raven Web" \
-e $LOGERR -o $LOGOUT \
--watch --ignore-watch="^.*\.log$ \.git logs npm-debug\.log public/* views/* dump/* init/*"

**Comment by MRLuowen** [comment]
met the same problem，on a docker,i run pm2 start app.js -i 0 --no-daemon.the error comes up!

getconf ARG_MAX returns 2097152

anyone solved it?

**Comment by MRLuowen** [comment]
i found why i met this problem, in the docker,there is lot net config params in the env。
in the God.js,when run in cluster mode, clu = cluster.fork({pm2_env: JSON.stringify(env_copy)}),
the env_copy is too big。
but seriousely，what do you really need in  env params. so,now i filter the useless setting.i hope it can solve it in the next version. thanks a lot.

**Comment by tsantanaDH** [comment]
Hi @kaanozcan, sorry for the late response. I "resolved" this issue removing some unused environment variables with `unset` from my docker container on the application startup (the containers have more than 5k env vars). This is by far not the best solution, but since I haven't found anything better, I left the solution like this

**Comment by goodideal** [comment]
Hello @MRLuowen, I got exactly the same issue. Any way to reduce env size for PM2?

**Comment by greenzhang** [comment]
Hey guys! I got the same issue. How can i reduce env params size for solving this issue?

**Comment by lw8008** [comment]
I got the same issue. with 1000+ env added by k8s in container. how can we resolve this?

$ printenv |wc -l
1523

**Comment by geobos23** [comment]
> I got the same issue. with 1000+ env added by k8s in container. how can we resolve this?
> 
> $ printenv |wc -l
> 1523

Same here, upvote!
