### ISSUE TITLE
Not respecting $PATH in .bashrc

### ISSUE THREAD

**Issue by binarykitchen** [Unitech/pm2#1205]
When I do something like

```
pm2 deploy package.json develop
```

where a certain user is logged into the server, that pm2 process is not respecting the `$PATH` in the `.bashrc` for that user.

Probably a bug I think ...

**Comment by joaosa** [comment]
I am experiencing the same issue

**Comment by meteormatt** [comment]
`pm2 updatePM2` maybe help.

**Comment by vmarchaud** [comment]
@meteormatt You need to restart the daemon to pick up `$PATH` change.
