### ISSUE TITLE
stdout/stderr files

### ISSUE THREAD

**Issue by fastid** [Unitech/PM2#1209]
How can disabled the stdout/stderr log files output,Because it is too big

**Comment by jshkurti** [comment]
We will implement a `--no-logs` flag soon enough :)
I will keep you informed.

**Comment by jshkurti** [comment]
`pm2 logs` will no longer work for that particular app if you launch it with `--no-log` flag since pm2 logs fetches the data directly from the files.
Are you ok with it ?

**Comment by fastid** [comment]
{ online: true, success: true, pid: 32340, pm2_version: '0.9.6' }
 error: unknown option `--no-log'

**Comment by igorescobar** [comment]
+1 for `--no-logs` option. 
I've setup something like this: 

```node
module.exports = {
  /**
   * Application configuration section
   * http://pm2.keymetrics.io/docs/usage/application-declaration/
   */
  apps: [
    {
      name: 'worker-streaming',
      script: 'app/workers/streaming.js',
      error_file: '/dev/null',
      out_file: '/dev/null',
      restart_delay: 15000,
      max_restarts: 5000
    },
    {
      name: 'api',
      port: 9000,
      script: 'bin/www',
      error_file: '/dev/null',
      out_file: '/dev/null',
      instances: process.env.NODE_ENV === 'production' ? (process.env.API_INSTANCES || 5) : 2
    }
  ]
};
```

And I'm still receiving logs into: `log/4a12753b1a01-stdouterr.log`.

**Comment by vmarchaud** [comment]
@igorescobar You need the latest pm2 version and it should work (see http://pm2.keymetrics.io/docs/usage/log-management/#disable-logging)

**Comment by igorescobar** [comment]
@vmarchaud I'm using `v2.4.2`. Isn't it enough?

**Comment by igorescobar** [comment]
Also.. worth mentioning that I'm starting the apps like this: `pm2 start -u app_user --no-daemon ecosystem.config.js`. And this `20bdae4e404d-stdouterr.log` file is always appearing. It only stops writting if I remove the file manually.

**Comment by vmarchaud** [comment]
the `-u` option is only used for the startup system, anyway could you try with `merge_logs: false` ? Note that the values are hardcoded [here](https://github.com/Unitech/pm2/blob/master/lib/ProcessContainer.js#L207), so if your daemon is up-to-date it should works (maybe try `pm2 update` ?)

**Comment by igorescobar** [comment]
@vmarchaud tested with what you suggested `merge_logs: false` and still no success. We are running with docker and we always install the newest version during our CI process before ship it to staging/production. so every between every deployment we always kill the old container and setup another one with a fresh setup.

**Comment by igorescobar** [comment]
@vmarchaud the out/err file isn't being written. The file that is being written is the `stdouterr` file which seems to be all the `otdout` that the processes are writting. Maybe we are looking to a different file here.

**Comment by vmarchaud** [comment]
@igorescobar Yes, are you sure that these logs come from your application ?

**Comment by igorescobar** [comment]
@vmarchaud This is what is being sent to this file:
![screen shot 2017-03-27 at 14 38 18](https://cloud.githubusercontent.com/assets/24032/24359056/192ac7da-12fb-11e7-8b35-0ad069b320b1.png)

May application doesn't know the context that it is in... so I strongly believe that this is coming from `pm2`.

**Comment by vmarchaud** [comment]
@igorescobar  Oh yeah, it coming from `pm2-docker` that output `pm2 logs` by [default](https://github.com/Unitech/pm2/blob/master/bin/pm2-docker#L100) into the stdout so its broadcasted to docker. Should we add an option to avoid broadcasting logs to docker ?

**Comment by igorescobar** [comment]
@vmarchaud But I'm not using the `pm2-docker`. or it is being used internally?

**Comment by vmarchaud** [comment]
@igorescobar What is your docker file so ?

**Comment by igorescobar** [comment]
@vmarchaud here it is:
<img width="413" alt="screen shot 2017-03-27 at 15 02 46" src="https://cloud.githubusercontent.com/assets/24032/24360174/77a13206-12fe-11e7-9f24-ec419ee8b339.png">

**Comment by vmarchaud** [comment]
@igorescobar From which image you made yours ?

**Comment by igorescobar** [comment]
@vmarchaud `FROM node:6.9.4`

**Comment by vmarchaud** [comment]
@igorescobar  Could you try something like this [one](https://github.com/keymetrics/pm2-docker-alpine/blob/master/7.4/Dockerfile) : 
```
RUN npm install pm2 -g
CMD ["pm2-docker", "start", "--auto-exit", "ecosystem.config.js"]
```

**Comment by igorescobar** [comment]
@vmarchaud why would you think that using pm2-docker would solve the problem?

**Comment by vmarchaud** [comment]
@igorescobar Just trying to help you, pm2-docker handle pretty much all you need to handle for docker environment.

**Comment by igorescobar** [comment]
@vmarchaud And I appreciate your help :) 

I was just trying to understand why changing the way this would solve the logging problem. I will try.

**Comment by igorescobar** [comment]
@vmarchaud Just tried the `pm2-docker` and the problem still persists... 😞

**Comment by vmarchaud** [comment]
@igorescobar Do you know what ouput this logs, i'm pretty sure that the logs of the docker container

**Comment by igorescobar** [comment]
@vmarchaud I think that if it was the docker container the log will be written in the host machine and not inside of the container, right?

**Comment by vmarchaud** [comment]
@igorescobar Im pretty sure this file hasn't been generated by pm2 from his name

**Comment by shaunwarman** [comment]
Sorry for the late response, but looking to do the same thing.

Take a peek at dockers [default log driver](https://docs.docker.com/engine/admin/logging/json-file/). What I think is happening is that you are still writing to stdout / stderr from your application like expected (no more pm2 to files) but docker log driver will intercept this and write to it's own file. 
Not sure your use case, but the good thing is you can specify a `max-size` of the file and docker will handle rotation itself. So no need for a startup script to start services. (e.g. cron for logrotate)
