### ISSUE TITLE
Detect iojs

### ISSUE THREAD

**Issue by binarykitchen** [Unitech/PM2#1210]
Instead of nodejs I have iojs installed, so, please change this

```
$ pm2 startup ubuntu
[PM2] Spawning PM2 daemon
[PM2] PM2 Successfully daemonized
[PM2] You have to run this command as root. Execute the following command:
      sudo env PATH=$PATH:/usr/bin pm2 startup ubuntu -u nodejs
```

to

```
$ pm2 startup ubuntu
[PM2] Spawning PM2 daemon
[PM2] PM2 Successfully daemonized
[PM2] You have to run this command as root. Execute the following command:
      sudo env PATH=$PATH:/usr/bin pm2 startup ubuntu -u iojs
```

when iojs is detected. Thx

**Comment by jshkurti** [comment]
When you install iojs via nvm, the binary is still called `node`.
If your binary is called iojs you can create an alias or symlink to it called `node`.

**Comment by binarykitchen** [comment]
Yes, I know that. But you are recommending `nodejs`, not `node` ;)

That line

```sudo env PATH=$PATH:/usr/bin pm2 startup ubuntu -u nodejs```

should be

```sudo env PATH=$PATH:/usr/bin pm2 startup ubuntu -u node```

And  make sure that everywhere else in the code `nodejs` is replaced with `node`.

**Comment by soyuka** [comment]
@binarykitchen  talking about https://github.com/Unitech/PM2/blob/master/lib/CLI.js#L418 ? This returns the result of `whoami` nothing to do with the node binary name.

**Comment by binarykitchen** [comment]
Oh, right, fuck me, I have confused that with something else :)

(I have an user called `nodejs` here)

All good now.
