### ISSUE TITLE
Got this error while trying to install - Install fails

### ISSUE THREAD

**Issue by zoiec** [Unitech/pm2#1212]
npm ERR! Error: No compatible version found: isbinaryfile@'^2.0.3'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5","0.1.6","0.1.7","0.1.8","0.1.9","1.0.0","1.0.1","2.0.0","2.0.1","2.0.2","2.0.3"]
npm ERR!     at installTargetsError (/home/zoiec1/lib/node_modules/npm/lib/cache.js:684:10)
npm ERR!     at /home/zoiec1/lib/node_modules/npm/lib/cache.js:606:10
npm ERR!     at saved (/home/zoiec1/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 2.6.32-531.29.2.lve1.3.11.1.el6.x86_64
npm ERR! command "/home/zoiec1/bin/node" "/home/zoiec1/bin/npm" "install" "pm2" "-g"
npm ERR! cwd /home/zoiec1/node_modules
npm ERR! node -v v0.10.1
npm ERR! npm -v 1.2.15

**Comment by jshkurti** [comment]
Hi,
Does it work now ?

**Comment by zoiec** [comment]
No still getting the same error I have tried with and without the -g
