### ISSUE TITLE
Debug application which is run using pm2

### ISSUE THREAD

**Issue by Nawa** [Unitech/PM2#1214]
Application is run by

	pm2 start app.js
or

	pm2 start config.json
I want to debug my application locally using node_inspector. I added debug argument

	pm2 start --node-args="--debug=7000" app.js
It works fine but if I provide config.json instead of script app.js I don't know how to pass arguments about debug. Next piece of config doesn't work

    {
      "apps": [
        {
          "name": "myName",
          "script": "app.js",
          "args": "['--debug=7000']"
          ............
          }
        ]
    }
So How to debug application which is run by pm2 and using config?

**Comment by jshkurti** [comment]
Hi, `node_args` is what you are looking for :)

**Comment by jshkurti** [comment]
https://github.com/Unitech/PM2/blob/master/ADVANCED_README.md#json-app-declaration

**Comment by soyuka** [comment]
http://stackoverflow.com/questions/29900253/debug-application-which-is-run-using-pm2/29900353#29900353
