### ISSUE TITLE
Cluster Mode and Passport

### ISSUE THREAD

**Issue by NiklasMerz** [Unitech/PM2#1216]
I got a problem with passport and my app in cluster mode on more than one instance. Do you know anything that could cause a problem?

see: https://github.com/jaredhanson/passport/issues/347

**Comment by NiklasMerz** [comment]
I didnt look carfully sorry

**Comment by jshkurti** [comment]
What was the problem ? :)

**Comment by NiklasMerz** [comment]
I found another Issue: https://github.com/Unitech/PM2/issues/286.

Unfournately it isnt that simple so i will be using fork mode till a I find a good solution.
