### ISSUE TITLE
pm2 logs and ilogs fails both

### ISSUE THREAD

**Issue by fcioffi** [Unitech/PM2#1218]
I started a process with:

pm2 start file.json

file.json
<code>
{
  "name"        : "name",
  "script"      : "bin/www",
  "watch"       : "/path/",
  "merge_logs"  : true,
  "cwd"         : "/path",
  "instances"   : 0,
  "exec_mode"   : "cluster_mode",
  "env": {
    "NODE_ENV": "production",
    "PORT": "3001"
  }
}
</code>

Then when I run
<code>
pm2 log
</code>
 I obtain:
<pre>
########### Starting streaming logs for [all] process
/opt/node-v0.12.0-linux-x64/lib/node_modules/pm2/lib/CLI.js:1489
    var app_name = (proc.pm2_env.name || p.basename(proc.pm2_env.pm_exec_path)
                        ^
TypeError: Cannot read property 'pm2_env' of undefined
    at printLogs (/opt/node-v0.12.0-linux-x64/lib/node_modules/pm2/lib/CLI.js:1489:25)
    at /opt/node-v0.12.0-linux-x64/lib/node_modules/pm2/lib/CLI.js:1470:9
    at /opt/node-v0.12.0-linux-x64/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/opt/node-v0.12.0-linux-x64/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at Parser.emit (events.js:107:17)
    at Parser._write (/opt/node-v0.12.0-linux-x64/lib/node_modules/pm2/node_modules/pm2-axon/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Parser.Writable.write (_stream_writable.js:217:11)
    at Socket.ondata (_stream_readable.js:540:20)
[Exit 1]
</pre>

And If I run
<code>
pm2 ilogs
</code>

<code>
Waiting for pm2...
</code>

Thanks,
FC

**Comment by nebulade** [comment]
Getting the same after starting two apps with pm2. It was working fine while having only one app running.

**Comment by nebulade** [comment]
The issue seems to be when using merged logs. The call comes from line 1470
```
printLogs(id, lines, undefined, raw);
```
and `id` is `undefined`

**Comment by nebulade** [comment]
I reverted a0e1237897a386e70ea1b45bbf5670dcaa621e95  and it fixes the issue (at least the crash, not sure what the commit does though)

**Comment by Jokero** [comment]
I have same issue.
pm2 - 0.12.12
node - 0.12.2

**Comment by soyuka** [comment]
Ilogs #919

**Comment by jshkurti** [comment]
This is a known issue, it has been fixed on #development, it will be on the 0.12.13 which is being released really soon.

**Comment by jshkurti** [comment]
0.12.13 released :)
`npm i -g pm2`
`ilogs` is deprecated btw

**Comment by fcioffi** [comment]
Great! It Works.

Thanks
