### ISSUE TITLE
If the log directory is unwritable (lacking permissions) pm2 shows process running but it is not

### ISSUE THREAD

**Issue by rbhalla** [Unitech/pm2#1221]
I start my pm2 process using a .json file. At one point the log directory I wanted to write to was not writable to by my logged in user. PM2 didn't throw an error, instead it continued as normal stating that the process was running (an express server if that matters) except it wasn't.

PM2 should throw an error in this situation.

pm2: 0.12.13
node: 0.12.2
os: ubuntu 14.04

**Comment by alexindigo** [comment]
Same happened with me. It was a letdown. Process was shown as "online" but it wasn't operating.

**Comment by alexindigo** [comment]
@Unitech any considerations on this one? Thank you.
