### ISSUE TITLE
PM2 running out of memory

### ISSUE THREAD

**Issue by pravin-mindstix** [Unitech/PM2#1223]
when i start app as  $pm2 start app.js -i 4 then app is not running 

here is logs

PM2: 2015-04-30 08:15:23: App name:app id:1 disconnected
PM2: 2015-04-30 08:15:23: App name:app id:1 exited with code SIGKILL
PM2: 2015-04-30 08:15:23: Starting execution sequence in -cluster mode- for app name:app id:1
PM2: 2015-04-30 08:15:23: App name:app id:1 online
PM2: 2015-04-30 08:15:26: App name:app id:2 disconnected
PM2: 2015-04-30 08:15:26: App name:app id:2 exited with code SIGKILL
PM2: 2015-04-30 08:15:26: Starting execution sequence in -cluster mode- for app name:app id:2
PM2: 2015-04-30 08:15:26: App name:app id:2 online
PM2: 2015-04-30 08:15:28: App name:app id:3 disconnected
PM2: 2015-04-30 08:15:28: App name:app id:3 exited with code SIGKILL
PM2: 2015-04-30 08:15:28: Starting execution sequence in -cluster mode- for app name:app id:3
PM2: 2015-04-30 08:15:29: App name:app id:3 online
app-1 (out): [Error: Module did not self-register.]
app-1 (err): js-bson: Failed to load c++ bson extension, using pure JS version
app-2 (out): [Error: Module did not self-register.]
app-2 (err): js-bson: Failed to load c++ bson extension, using pure JS version
app-3 (out): [Error: Module did not self-register.]
app-3 (err): js-bson: Failed to load c++ bson extension, using pure JS version
PM2: 2015-04-30 08:15:31: App name:app id:4 disconnected
PM2: 2015-04-30 08:15:31: App name:app id:4 exited with code SIGKILL
PM2: 2015-04-30 08:15:31: Starting execution sequence in -cluster mode- for app name:app id:4
PM2: 2015-04-30 08:15:31: App name:app id:4 online
app-4 (out): [Error: Module did not self-register.]
app-4 (err): js-bson: Failed to load c++ bson extension, using pure JS version
PM2: 2015-04-30 08:15:34: App name:app id:1 disconnected
PM2: 2015-04-30 08:15:34: App name:app id:1 exited with code SIGKILL
PM2: 2015-04-30 08:15:34: Starting execution sequence in -cluster mode- for app name:app id:1
PM2: 2015-04-30 08:15:35: App name:app id:1 online
app-1 (out): [Error: Module did not self-register.]
app-1 (err): js-bson: Failed to load c++ bson extension, using pure JS version
PM2: 2015-04-30 08:15:37: App name:app id:2 disconnected
PM2: 2015-04-30 08:15:37: App name:app id:2 exited with code SIGKILL
PM2: 2015-04-30 08:15:37: Starting execution sequence in -cluster mode- for app name:app id:2
PM2: 2015-04-30 08:15:37: App name:app id:2 online
app-2 (out): [Error: Module did not self-register.]
app-2 (err): js-bson: Failed to load c++ bson extension, using pure JS version
PM2: 2015-04-30 08:15:39: App name:app id:3 disconnected
PM2: 2015-04-30 08:15:39: App name:app id:3 exited with code SIGKILL
PM2: 2015-04-30 08:15:39: Starting execution sequence in -cluster mode- for app name:app id:3
PM2: 2015-04-30 08:15:40: App name:app id:3 online
app-3 (out): [Error: Module did not self-register.]
app-3 (err): js-bson: Failed to load c++ bson extension, using pure JS version
.......
.

and server not giving any response.

when I start with $pm2 start app.js   i.e as fork mode then it gives response
but i need to run it in cluster mode

┌──────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────────────┬──────────┐
│ App name │ id │ mode │ pid   │ status │ restart │ uptime │ memory      │ watching │
├──────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────────────┼──────────┤
│ app      │ 1  │ fork │ 19568 │ online │ 0       │ 11m    │ 27.270 MB   │ disabled │
└──────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────────────┴──────────┘

I tried   npm i -g git://github.com/Unitech/PM2#development   as well.

**Comment by jshkurti** [comment]
Hi, what is your Node.js version ?

**Comment by pravin-mindstix** [comment]
node -v
v0.12.0
but earlier PM2 worked. and there is only one core

**Comment by jshkurti** [comment]
Hi,
How did you come to the conclusion that PM2 is running out of memory ?
The only thing I see here is your app crashing everytime and therefore being restarted by PM2.
Can you tell us approximately from which version of PM2 this issue started to happen ?
