### ISSUE TITLE
--interpreter not applied?

### ISSUE THREAD

**Issue by lklepner** [Unitech/PM2#1224]
Running with the --interpreter flag:
    pm2 start app.js --interpreter /home/ds/.nvm/v0.10.38/bin/node

I'm getting the following error: 
    [PM2][WARN] We've notice that you are running the node script, but currently using a /home/ds/.nvm/v0.10.38/bin/node interpreter, may be you need inspect the --interpreter option.

And then the app is started with the system node executable, v0.12.2 in my case. 

Am I misusing the --interpreter flag is it possible its not being applied?

**Comment by Unitech** [comment]
You get this message when you try to use the --interpreter option with the cluster mode. You cannot use other interpreter than node with the cluster mode
