### ISSUE TITLE
pm2 startup hangs in AWS userdata scripts

### ISSUE THREAD

**Issue by velinath** [Unitech/pm2#1225]
node: 0.10.36
pm2: 0.12.13
os: CentOS 7 on AWS instance

The problem:

Running `env PATH=$PATH:/usr/bin pm2 startup centos` in a terminal session works fine, no problems. When I try to add this to a userdata script in AWS to automate installation of pm2, the pm2 process hangs and uses 100% CPU until manually killed.

Logs for this script show that the last output given is as follows:

`localhost cloud-init: [PM2] Spawning PM2 daemon.`

How to reproduce:

Start up an AWS CentOS 7 instance using a userdata script that installs and initializes pm2. An example of a script that would replicate the issue:

``` bash
#!/bin/bash
yum install epel-release -y
yum install nodejs npm -y
npm install pm2 -g
env PATH=$PATH:/usr/bin pm2 startup centos
```

You can verify this works in a terminal session by saving this script as a shell script to the server and running it. You will see that PM2 initializes successfully.

**Comment by edgardksb** [comment]
I have the same problem :(

**Comment by webdevwilson** [comment]
yep, me too. Any solutions?

**Comment by jdrake** [comment]
Oh man, +:100: to this. Also happens with io.js 2.5.0 on ubuntu 14.04.

**Comment by webdevwilson** [comment]
I am on Amazon Linux
Node: 0.10.36
NPM: 1.3.6
pm2: 0.14.6

**Comment by agencia** [comment]
I have a similar problem

pm2 start ~/app/app.js

The file is there but app never starts

**Comment by webdevwilson** [comment]
@agencia I gave up and switched back to forever.

**Comment by hpihkala** [comment]
I am experiencing this as well on AWS and ubuntu 14.04. Any solutions?

**Comment by hpihkala** [comment]
I worked around the problem by manually copying and linking the init script in place instead of executing `pm2 startup` in the userdata script.

```
cp pm2-init.sh /etc/init.d/pm2-init.sh
chmod +x /etc/init.d/pm2-init.sh && update-rc.d pm2-init.sh defaults
ln -s /etc/init.d/pm2-init.sh /etc/rc0.d/K20pm2-init.sh
ln -s /etc/init.d/pm2-init.sh /etc/rc1.d/K20pm2-init.sh
ln -s /etc/init.d/pm2-init.sh /etc/rc6.d/K20pm2-init.sh
ln -s /etc/init.d/pm2-init.sh /etc/rc2.d/S20pm2-init.sh
ln -s /etc/init.d/pm2-init.sh /etc/rc3.d/S20pm2-init.sh
ln -s /etc/init.d/pm2-init.sh /etc/rc4.d/S20pm2-init.sh
ln -s /etc/init.d/pm2-init.sh /etc/rc5.d/S20pm2-init.sh
```

**Comment by bengadbois** [comment]
Happens for me as well on Ubuntu 14.04 (on DigitalOcean)

PM2: 1.0.2
Node: 0.10.25

**Comment by winglian** [comment]
Also happens for me. manually initializing the startup scripts doesn't help as running `pm2 start` from the user data script still fails too

**Comment by winglian** [comment]
I managed to work around this by having ansible use SSH to start PM2 rather than use the local "connection". This may not be a solution for most folks, but we were already using ansible.

**Comment by Unitech** [comment]
https://github.com/Unitech/pm2/issues/2559
