### ISSUE TITLE
js-bson: Failed to load c++ bson extension, using pure JS version

### ISSUE THREAD

**Issue by chelsh** [Unitech/PM2#1228]
root@iZ28zudukwhZ:~# pm2 --version
0.12.7
root@iZ28zudukwhZ:~# node --version
v0.12.0

logs:
PM2: 2015-05-01 18:02:00: App name:Server-Manage-API id:1 online
Server-Manage-API-1 (out): [Error: Module did not self-register.]
Server-Manage-API-1 (err): js-bson: Failed to load c++ bson extension, using pure JS version
Server-Manage-API-1 (err): Error: Module did not self-register.
Server-Manage-API-1 (err):     at Error (native)
Server-Manage-API-1 (err):     at Module.load (module.js:355:32)
Server-Manage-API-1 (err):     at Function.Module._load (module.js:310:12)
Server-Manage-API-1 (err):     at Function.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:59:21)
Server-Manage-API-1 (err):     at Module.require (module.js:365:17)
Server-Manage-API-1 (err):     at require (module.js:384:17)
Server-Manage-API-1 (err):     at bindings (/var/www/Server-Manage-API/source/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
Server-Manage-API-1 (err):     at Object.<anonymous> (/var/www/Server-Manage-API/source/node_modules/bcrypt/bcrypt.js:3:35)
Server-Manage-API-1 (err):     at Module._compile (module.js:460:26)
Server-Manage-API-1 (err):     at Object.Module._extensions..js (module.js:478:10)
PM2: 2015-05-01 18:02:01: App name:Server-Manage-API id:1 exited with code null
PM2: 2015-05-01 18:02:01: Starting execution sequence in -cluster mode- for app name:Server-Manage-API id:1
PM2: 2015-05-01 18:02:01: App name:Server-Manage-API id:1 online

**Comment by soyuka** [comment]
You should build the bson module again:
```
cd node_modules/bson
rm -r node_modules
npm install
```

**Comment by chelsh** [comment]
when i update PM2 to v0.12.13,it is this error:

PM2: 2015-05-01 18:15:23: Script /var/www/Server-Manage-API/source/index.js had too many unstable restarts (15). Stopped. "errored"
Server-Manage-API-3 (out): [Error: Module did not self-register.]
Server-Manage-API-3 (out): [Error: Module did not self-register.]
Server-Manage-API-3 (out): [Error: Module did not self-register.]
Server-Manage-API-3 (out): [Error: Module did not self-register.]
Server-Manage-API-3 (out): [Error: Module did not self-register.]
Server-Manage-API-3 (out): [Error: Module did not self-register.]
Server-Manage-API-3 (out): [Error: Module did not self-register.]
Server-Manage-API-3 (out): [Error: Module did not self-register.]
Server-Manage-API-3 (out): [Error: Module did not self-register.]
Server-Manage-API-3 (out): [Error: Module did not self-register.]
Server-Manage-API-3 (out): [Error: Module did not self-register.]
Server-Manage-API-3 (out): [Error: Module did not self-register.]
Server-Manage-API-3 (out): [Error: Module did not self-register.]
Server-Manage-API-3 (out): [Error: Module did not self-register.]
Server-Manage-API-3 (out): [Error: Module did not self-register.]
Server-Manage-API-3 (out): [Error: Module did not self-register.]
Server-Manage-API-3 (out): [Error: Module did not self-register.]
Server-Manage-API-3 (out): [Error: Module did not self-register.]
Server-Manage-API-3 (out): [Error: Module did not self-register.]
Server-Manage-API-3 (out): [Error: Module did not self-register.]
Server-Manage-API-3 (err):     at bindings (/var/www/Server-Manage-API/source/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
Server-Manage-API-3 (err):     at Object.<anonymous> (/var/www/Server-Manage-API/source/node_modules/bcrypt/bcrypt.js:3:35)
Server-Manage-API-3 (err):     at Module._compile (module.js:460:26)
Server-Manage-API-3 (err):     at Object.Module._extensions..js (module.js:478:10)
Server-Manage-API-3 (err): js-bson: Failed to load c++ bson extension, using pure JS version
Server-Manage-API-3 (err): js-bson: Failed to load c++ bson extension, using pure JS version
Server-Manage-API-3 (err): js-bson: Failed to load c++ bson extension, using pure JS version
Server-Manage-API-3 (err): js-bson: Failed to load c++ bson extension, using pure JS version
Server-Manage-API-3 (err): js-bson: Failed to load c++ bson extension, using pure JS version
Server-Manage-API-3 (err): js-bson: Failed to load c++ bson extension, using pure JS version
Server-Manage-API-3 (err): js-bson: Failed to load c++ bson extension, using pure JS version
Server-Manage-API-3 (err): js-bson: Failed to load c++ bson extension, using pure JS version
Server-Manage-API-3 (err): js-bson: Failed to load c++ bson extension, using pure JS version
Server-Manage-API-3 (err): js-bson: Failed to load c++ bson extension, using pure JS version
Server-Manage-API-3 (err): js-bson: Failed to load c++ bson extension, using pure JS version
Server-Manage-API-3 (err): js-bson: Failed to load c++ bson extension, using pure JS version
Server-Manage-API-3 (err): js-bson: Failed to load c++ bson extension, using pure JS version
Server-Manage-API-3 (err): js-bson: Failed to load c++ bson extension, using pure JS version
Server-Manage-API-3 (err): js-bson: Failed to load c++ bson extension, using pure JS version
Server-Manage-API-3 (err): js-bson: Failed to load c++ bson extension, using pure JS version

**Comment by soyuka** [comment]
This usually happens when node is updated.

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/7429182/8ad3f762-f02f-11e4-91b7-3cb7596d776c.png)




only module mongoose use js-bson

**Comment by soyuka** [comment]
Yes I know, I faced the issue before, please try to rebuild it:

```
cd node_modules/mongoose/node_modules/mongodb/node_modules/bson
rm -r node_modules
npm install
```

Again this has nothing to do with pm2.

**Comment by chelsh** [comment]
OK Thank you：）
