### ISSUE TITLE
Watch + gracefulReload

### ISSUE THREAD

**Issue by glesperance** [Unitech/pm2#1231]
I've looked through the readme but couldn't find a way to have the app use gracefulReload when using the --watch option.

Did I miss something?

Thanks.

**Comment by Unitech** [comment]
Yes for now watch only restart processes https://github.com/Unitech/PM2/blob/master/lib/Watcher.js#L79

**Comment by rbhalla** [comment]
+1

**Comment by jsolis** [comment]
+1

**Comment by privaloops** [comment]
+1

**Comment by vmarchaud** [comment]
See #2629 we group all issue into one.
