### ISSUE TITLE
Programmatic API: restart('all') breaks when called from pm2-managed process

### ISSUE THREAD

**Issue by djphoenix** [Unitech/PM2#1232]
I writing web monitoring service. So, it hosted by same process of PM2 that other hosts. Invoking pm2.restart('all') breaks after monitoring service - all services added after that are not restarted.

![2015-05-02 19 53 01](https://cloud.githubusercontent.com/assets/1833493/7441916/971fb4f8-f105-11e4-881a-2ab29e454679.png)

env:
```
$ node -v
v0.12.2
$ pm2 -v
0.12.12
```

**Comment by Unitech** [comment]
You restart the app that restarts the other processes. This "monitoring app" should not be managed by PM2 or you need to restart all process name but not monit
