### ISSUE TITLE
restartProcessId Error

### ISSUE THREAD

**Issue by zerataul** [Unitech/PM2#1233]
Hello.

using pm2-interface.

https://www.npmjs.com/package/pm2-interface
Example, restartProcessId.

So, My result.
[Error: opts.id not passed to restartProcessId]

I used my server pm_id.
ipm2.rpc.restartProcessId(pm_id, function(err, dt) {
Why show the error??

how to write?? help me, please.

var ipm2 = require('pm2-interface')();
 
ipm2.on('ready', function() {
  console.log('Connected to pm2');
 
  ipm2.bus.on('*', function(event, data){
    console.log(event, data.pm2_env.name);
  });
 
  setTimeout(function() {
    ipm2.rpc.restartProcessId(0, function(err, dt) {
      console.log(dt);
    });
  }, 2000);
 
 
  ipm2.rpc.getMonitorData({}, function(err, dt) {
    console.log(dt);
  });
});

**Comment by Unitech** [comment]
Use pm2

```
var pm2 = require('pm2');

pm2.connect(function() {
  pm2.restart(0, function() {
  });
});
```

**Comment by k3v1nb0t** [comment]
I solve it by passing a object as parameter, instead of a number

ipm2.rpc.restartProcessId({id: pm_id}, function(err, dt) {
