### ISSUE TITLE
Is it possible to require process.send("online") before it goes online?

### ISSUE THREAD

**Issue by owenallenaz** [Unitech/pm2#1234]
From the docs on graceful reload I see there is a way to nofity pm2 for non-http type processes that the process is online via a `process.send('online')`. Would it be possible to have a configuration setting that requires that to be sent in order for a process to be considered booted in all circumstances, and not just in graceful reloads.

This makes it very clear as developer where in the code you are notifying pm2 that your process is operational. In example, right now with graceful reload, pm2 assumes that my process is ready when it starts listening on something, but what if my process needs to listen to multiple things before it's "booted". In addition, when I first start it up I want to tell pm2 when I consider this boot a success. It's sort of an explicit over implicit type issue.

**Comment by adrian-ludwig** [comment]
+1

**Comment by jshkurti** [comment]
I get it. We have to think about it in order to avoid losing usability for the rest of the users. Also there is maybe a workaround : stop the 'listen' event to be fired automatically and fire it manually when your process is ready.

**Comment by michaelBenin** [comment]
+1

**Comment by Unitech** [comment]
```
$ pm2 start app.js --wait-ready --listen-timeout 15000
```

In your code, once your application is ready, do `process.send('ready')`

Available in pm2@next:

```
$ npm install pm2@next -g
$ pm2 update
```
