### ISSUE TITLE
PM2 STARTUP silently fails if no HOME can be resolved

### ISSUE THREAD

**Issue by glesperance** [Unitech/pm2#1235]
If no `HOME` can be resolved,

that is if : 

`typeof (process.env.PM2_HOME || process.env.HOME || process.env.HOMEPATH) == 'undefined'`

(as is it the case when we run `pm2 startup` via `exec` in a puppet manifest)

pm2 silently fails and hangs trying to launch the pm2 daemon.

The CLI should report the error and quit, not hang.

**Comment by jshkurti** [comment]
Ok thanks for reporting this. I'm gonna fix it.

**Comment by redwoodfavorite** [comment]
still an issue...

**Comment by vmarchaud** [comment]
@redwoodfavorite Did you tried using `npm install pm2@next -g` ? I dont see any reference to the code that the issue report in the latest version

**Comment by Unitech** [comment]
fixed on PM2 2.2.x
