### ISSUE TITLE
pm2 not working in fork or cluster mode

### ISSUE THREAD

**Issue by Jessestr** [Unitech/PM2#1240]
Having installed pm2 it doesn't want to start in fork mode.I enabled debugging but it doesn't really show me more than what I get normally.

in fork mode it  _reboots 15 times and then it says "status: errored"_

If I boot it in cluster mode it stays online but then I'm not able to access the page online, assuming it's running on port 3000. Like it does with "npm start app.js"

Anyone having similar issues?

Thanks

**Comment by jshkurti** [comment]
Hi, can you `pm2 desc <your app name>` and look into the corresponding error.log and out.log files to see which error occured ?

**Comment by Jessestr** [comment]
For fork mode I have an error: "too many unstable restarts (15)"
For cluster I don't seem to have any errors.

**Comment by jshkurti** [comment]
`"too many unstable restarts (15)"` this is a PM2 message.
What we really want to know is the error which made your app crash.
Can you do `pm2 logs <your app id>` after the crash and look what happenned ?

**Comment by Jessestr** [comment]
Just solved the problem!
Thought Express was doing node app.js. To get it started I had to do:

    pm2 bin/www

Now it runs wonderful.
