### ISSUE TITLE
`pm2 start app.js -i 0` fails because `Error: ENOENT, no such file or directory` for process.cwd()

### ISSUE THREAD

**Issue by scottyli** [Unitech/PM2#1244]
I am running the PM2 way example here - https://keymetrics.io/2015/03/26/pm2-clustering-made-easy/

```javascript
var http = require('http');

http.createServer(function(req, res) {  
  res.writeHead(200);
  res.end("hello world");
}).listen(8080);
```

```bash
$ pm2 start app.js -i 0
```

However, the process fails 15 times and is then stopped. Here are the logs:
```
PM2: 2015-05-07 15:38:53: Starting execution sequence in -cluster mode- for app name:app id:22
PM2: node.js:720
PM2:     var cwd = process.cwd();
PM2:                       ^
PM2: Error: ENOENT, no such file or directory
PM2:     at Error (native)
PM2:     at Function.startup.resolveArgv0 (node.js:720:23)
PM2:     at startup (node.js:63:13)
PM2:     at node.js:814:3
PM2: 2015-05-07 15:38:53: App name:cluster.pm2 id:22 disconnected
PM2: 2015-05-07 15:38:53: App name:cluster.pm2 id:22 exited with code 1
```

Node ```0.12.2```
PM2 ```0.12.14```
OSX ```10.10.3```

**Comment by jshkurti** [comment]
Open a new terminal and try again.
If still not working, does the command `node` alone work ?

**Comment by jshkurti** [comment]
http://stackoverflow.com/questions/19936850/nodejs-error-node-js810-var-cwd-process-cwd

**Comment by scottyli** [comment]
Yeah, ```node``` and ```pm2 start app.js``` work just fine. Confused why cluster mode doesn't work.

**Comment by jshkurti** [comment]
Your might need to re-install pm2 again i guess.

**Comment by scottyli** [comment]
Yeah I think it's just me. Tried it in another env and it was fine. Thanks for the help though :)

**Comment by Jokero** [comment]
I rarely have same issue. `node app.js` and `pm2 start app.js` works. But `pm2 start -i 0` does not work:
```javascript
PM2: 2015-09-09 17:42:48: Starting execution sequence in -cluster mode- for app name:app id:0
PM2: node.js:720
PM2:     var cwd = process.cwd();
PM2:                       ^
PM2: Error: ENOENT, no such file or directory
PM2:     at Error (native)
PM2:     at Function.startup.resolveArgv0 (node.js:720:23)
PM2:     at startup (node.js:63:13)
PM2:     at node.js:814:3
PM2: 2015-09-09 17:42:48: App name:app id:0 disconnected
PM2: 2015-09-09 17:42:48: App name:app id:0 exited with code 1
```

I can't reproduce it. pm2 reinstalling is very bad because it happened on production

**Comment by soyuka** [comment]
This is not related to pm2, try from another directory or start from a json declaration : http://pm2.keymetrics.io/docs/usage/application-declaration/ by specifying a `cwd`.

**Comment by Jokero** [comment]
I really use `pm2 startOrGracefulReload pm2.json`

pm2.json:
```javascript
{
  "apps": [
    {
      "name":            "api",
      "cwd":             "/apps/api/current",
      "script":          "app.js",
      "exec_mode":       "cluster",
      "instances":       0,

      "out_file":        "/var/log/apps/api/output.log",
      "error_file":      "/var/log/apps/api/error.log",
      "log_date_format": "YYYY-MM-DD HH:mm:ss",
      "merge_logs":      true
    },
    ...
]
```

So result is the same

**Comment by soyuka** [comment]
All I can say is that nodejs does not find `/apps/api/current`

**Comment by Jokero** [comment]
But directory exists :)

**Comment by Jokero** [comment]
And it's very strange that after pm2 reinstalling all is working

**Comment by yinrong** [comment]
same issue, a big headache.

I can't delete pm2 since I have to keep some of the processes running

**Comment by vjpr** [comment]
I ran into the same issue. The problem is when you run pm2 from a symlinked dir. Not exactly sure what is going on yet. I'm thinking that running pm2 start outside of the symlinked dir would fix it.

**Comment by ColinNiu** [comment]
I ran into this issue too.  It finally worked after run "pm2 kill".
In my case, I first ran it in "fork" mode, works fine, and then changed to "cluster" mode, encounted this problem.
tried reinstalling pm2 with no luck;
tried run from the real dir (not the symlinked dir), with noluck.

**Comment by lvdaqian** [comment]
I have met the same issue in our production env.  
I didn't run pm2 from a symlinked dir. But the issue is still there.

**Comment by lvdaqian** [comment]
Sorry for late update, I have found the reason of my issue.
I have added a script to remove the folder when deploy. 
For the first time, it works fine. But for the second time the issue occurs. 
kill and restart pm2, it works again.

So make sure you do not remove the work folder when pm2 is still on daemon. even though you recreate it again, pm2 still could not find the folder.

**Comment by aneeshmg** [comment]
I ran into the same issue, rebooting the machine fixed it for me...

**Comment by sfratini** [comment]
Just a FYI, my issue is that the build machine deleted the folder and pm2 cannot find it after that. A simple "pm2 update" solves it (Caution, it reloads all the current app list)

**Comment by aldee07** [comment]
I ran into the same problem. 

Following @lvdaqian 's answer,  I remembered/realized that I deleted the directory  and clone the project back with the same directory path prior to the `pm2 start /path/to/my-pm2-config.json` command.

So we can conclude that whenever the pm2 is running on daemon, the registry of previously started apps and the reference paths is still in its memory and that even the `pm2 delete myapp` command could not clear the reference path. To resolve, `pm2 update` works for me as suggested by @sfratini 

Thanks

**Comment by sfratini** [comment]
@danoctavian In my experience, this issue is caused by either pm2 being run/installed by root so a normal app cannot run the pm2 executable, or that pm2 daemon was started from a directory that usually gets deleted or cleaned. Example, if you are inside a repo that gets cleaned and checkout by a build machine. After the cleanup, the build machine or script wont be able to find the directory. 

So to me, the final solution was to kill every single daemon for pm2 and started from command line from a directory that I know won't be changed, like /var or /usr/yourUser. Make sure you start the daemon from that directory. After that, following commands run with pm2 should work, even the ones that involve reloading an app that was just installed/updated/checked out. 

If that does not work, then double check the user than wants to run the command and the one that installed pm2. Maybe this is from a script that has less permissions than the one you are using or maybe you are doing "sudo npm i pm2" and then running the pm2 from a ctrontab. That I am guessing will cause problems.

**Comment by keyul-code** [comment]
I added PM2_HOME environment variable on a system level and now it works alright....

**Comment by ubaidillahSriyudi** [comment]
> I ran into this issue too. ** It finally worked after run ** `pm2 kill`
> In my case, I first ran it in "fork" mode, works fine, and then changed to "cluster" mode, encounted this problem.
> tried reinstalling pm2 with no luck;
> tried run from the real dir (not the symlinked dir), with noluck.

thanks it's really work with pm2 kill !

**Comment by limmie** [comment]
Using `sudo` before starting any operation of PM2 worked for me :)
