### ISSUE TITLE
gracefulReload can case pm2 to hang

### ISSUE THREAD

**Issue by btmdave** [Unitech/PM2#1246]
I have a launch script that uses pm2 programmatically which calls `pm2.gracefulReload`.  On occasion, perhaps after a long hang, pm2 just dies.  When doing `pm2 list`, etc. it just hangs there.  Is there a work around when using gracefulReload?  Would it be to just set the timeout for it?  Also, is there a way to bring pm2 back up if it does hang like this, without a reboot?

**Comment by jshkurti** [comment]
I would need some ~/.pm2/pm2.log output at around the time the bug happenned :)
Also, which version of PM2 and Node.js are you on ?
Thanks

**Comment by btmdave** [comment]
I don't see anything in there out of the usual, it was probably unrelated.  I'll close this issue.
