### ISSUE TITLE
Option --force doesn't work for json and programmatic interface

### ISSUE THREAD

**Issue by horpto** [Unitech/pm2#1249]
Hello, 
Console command `pm2 start analyzer.js -i 0 --name "analyzer"` gets me an error: `Script already launched, add -f option to force re-execution`. But almostly the same command `pm2 start analyzer.json` used next json file:

```
{
    name: "analyzer",
    script: "./analyzer.js",
    instances: 0,
    exec_mode: "fork",
    force: false,
}
```

runs a several more instances this the same name.
pm2 --version
0.12.14

nodejs --version
v0.10.29

**Comment by KoltonG** [comment]
@horpto Did you get this figured out?
