### ISSUE TITLE
Dont close socket in cluster mode after delete service

### ISSUE THREAD

**Issue by horpto** [Unitech/PM2#1252]
Hi all, 
pm2 don't close socket after command delete, so manual starting raises EADDRINUSE error, Is it OK?

pm2 --version
0.12.14
nodejs --version
v0.10.29

--------
Instruction
------------

1) create `server.js`:
```javascript
var http = require('http');
http.createServer(function (req, res) {
    res.writeHead(200, {'Content-Type': 'text/plain'});
    res.end('hello world\n');
}).listen(8000, '127.0.0.1');
````
2) start server with pm2:
`pm2 start server.js --name "server" -i 1 `

3) delete server from pm2:
` pm2 delete server `

4) start server manually:
` nodejs server.js`

Output:
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at net.js:1146:9
    at dns.js:72:18
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by jshkurti** [comment]
Yep that's because of Node 0.10.x.
It will work just fine with 0.11.x or 0.12.x :)

(https://github.com/Unitech/PM2/blob/master/README.md#load-balancing--0s-reload-downtime check out the Warning part)

**Comment by horpto** [comment]
Ok,, thanks.
