### ISSUE TITLE
Start with JSON app decl. creates a new app on every start.

### ISSUE THREAD

**Issue by StarpTech** [Unitech/PM2#1255]
Pm2 creates for every start with the JSON app declaration file a new app in my list. Keymetrics tells me then that my app is down. This means that I have to delete the app manually `pm2 delete <id>` to make keymetrics run correctly.

NodeJs: v0.12.2
PM2: 0.12.13
Windows: 8.1

**Comment by klinquist** [comment]
This is by design - try either 'pm2 restart'  or  'pm2 startOrRestart' instead.

**Comment by StarpTech** [comment]
and how can I use the declaration file ? `pm2 restart processes.json` ?

**Comment by klinquist** [comment]
Yes.

**Comment by StarpTech** [comment]
thanks.
