### ISSUE TITLE
Shouldn't default exec_mode be fork?

### ISSUE THREAD

**Issue by DomiR** [Unitech/PM2#1256]
https://github.com/Unitech/PM2/blob/master/lib/Common.js#L117

Default mode should probably be fork_mode: 
```
  if(typeof app.instances == 'undefined'){
    app.instances = 1;
  }

  ...

  /**
   * Here we put the default exec mode
   */
  if (!app.exec_mode && app.instances > 0) {     // check for app.instances > 1 instead
    app.exec_mode = 'cluster_mode';
  } else if (!app.exec_mode) {
    app.exec_mode = 'fork_mode';
  }
```

**Comment by jorge-d** [comment]
The default mode is `fork_mode`, unless you specify the `-i` option that will run the cluster mode. I don't see anything unusual here?

**Comment by DomiR** [comment]
Well I'm not sure if the depicted prepareAppConf is used by pm2, but it is in a third party management tool([pod](https://github.com/yyx990803/pod)). And it seems to me, unless you set instances explicitly to zero the default exec mode would be `cluster_mode`.

**Comment by jorge-d** [comment]
No, the default mode is `fork`:
```shell
$ pm2 start app.js
[PM2] Spawning PM2 daemon
[PM2] PM2 Successfully daemonized
[PM2] Process app.js launched
┌──────────┬────┬──────┬──────┬────────┬─────────┬────────┬─────────────┬──────────┐
│ App name │ id │ mode │ pid  │ status │ restart │ uptime │ memory      │ watching │
├──────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────────────┼──────────┤
│ app      │ 0  │ fork │ 6572 │ online │ 0       │ 0s     │ 17.945 MB   │ disabled │
└──────────┴────┴──────┴──────┴────────┴─────────┴────────┴─────────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app

```

**Comment by DomiR** [comment]
Yes, I know. But the CLI you're showing is not using the Common.prepareAppConf for whatever reason. 

See https://github.com/Unitech/PM2/blob/master/lib/CLI.js#L93.
```
var appConf = {};

  if (!!opts.executeCommand)
    conf.exec_mode = 'fork';
  else if (opts.instances !== undefined)
    conf.exec_mode = 'cluster';
  else
    conf.exec_mode = 'fork';
```
So the problem here is this: The config object used by cli is not beeing validated by the  common.js (Common.prepareAppConf) and there it seems to me the default starting mode is set to cluster_mode.

External libs like "pod" are using this method to parse the settings and therefore it should probably be consistent?

**Comment by jshkurti** [comment]
How exactly is pod using pm2 ? :)

**Comment by DomiR** [comment]
Here you go (comment says to check for errors):
https://github.com/yyx990803/pod/blob/master/lib/api.js#L530
```
    // Get said function 
    pm2prepare = require('pm2/lib/Common.js').prepareAppConf

    // Make config
    var conf = {
        name: appInfo.name,
        script: appInfo.script,
        env: {
            NODE_ENV: appInfo.config.node_env || globalConfig.node_env || 'development',
            PORT: appInfo.config.port
        }
    }

    // invoke pm2's prepare function
    // if the conf has problems it will return an error
    return pm2prepare(conf)
```

**Comment by DomiR** [comment]
To summarize: 
cli is NOT using prepareAppConf from common.js but does instead checking itself, where it uses `fork` as default. 

prepareAppConf from common.js should use the same default values as cli, but sets `cluster` by default. Like depicted in the first comment it sets instances to `1` and checks for `>0` where it should check for `>1`

If this is acceptable I will write a pull request...

**Comment by DomiR** [comment]
https://github.com/Unitech/PM2/pull/1492
