### ISSUE TITLE
PM2 spawn ENOMEM but then Spawn two God Daemon(s)

### ISSUE THREAD

**Issue by ans-4175** [Unitech/PM2#1257]
Well I often faced this issue, but ignore them. Occassionally when our memory reach limit and PM2 spawn something. Then it will spawn another God Daemon, thats odd. I dont know what processes related with this issue. Is it something defect in PM2 ? Kindly please enlighten me. Thanks.
Here I attach my pm2.log ![pm2 log](https://dl.dropboxusercontent.com/u/45227205/cdn/github/pm2-issue-enomem.png)

**Comment by jorge-d** [comment]
Hi, Which version of `pm2` / `node` are you using?

**Comment by ans-4175** [comment]
I use 0.12.8

**Comment by jshkurti** [comment]
Give it a try with PM2 v0.12.14 (latest).

**Comment by jshkurti** [comment]
PM2 v0.12.16 is released. This bug shouldn't happen anymore. At least it won't crash PM2 if ENOMEM occurs.

https://github.com/Unitech/PM2/releases/tag/0.12.16
