### ISSUE TITLE
communicate app status to pm2

### ISSUE THREAD

**Issue by mlmarius** [Unitech/PM2#1259]
is there a way to communicate the status of my application to pm2 ? for example i'd like to control from my app what pm2 list shows in the "status" column. I'd like to make it say "online.reconnecting" for a while and then "online" again once reconnection is complete. Is it possible ?

**Comment by jshkurti** [comment]
There is no such feature for the moment.
But with keymetrics.io you could work something out.

![ports-pm3](https://cloud.githubusercontent.com/assets/7647602/7587581/b05dcd6a-f8b7-11e4-9c59-d3af06b5e828.png)

See the ElasticSearch Status field. This is a real-time indicator that you can update anytime in your code and it appears instantly on the Keymetrics Dashboard.

**Comment by mlmarius** [comment]
thanks !

**Comment by Dameck** [comment]
A process to communicate with PM2 would be great. For e.g. a node app in a cluster could inform PM2 that the app is ready and accessible. Or is there an another way to control the status for the app and set the accessibility in a cluster manually?
