### ISSUE TITLE
env args superseed ecosystem.json args

### ISSUE THREAD

**Issue by thunderace** [Unitech/PM2#1260]
When args is set in starting shell env, ecosystem args is ignored.
Example : 
shell env : 
thunder@debianServer:/media/data/home/thunder$ env
MAIL=/var/mail/thunder
../..
vizion=true
HOME=/home/thunder
SHLVL=5
args=-b,-p,3132,-w,/media/data/home/thunder,-l,0.0.0.0,-a,:
../..

with this domo.json file : 
{
  "apps" : [{
    "name"        : "ArDomo2",
    "script"      : "nodes/domoSerial/domoSerial.js",
    "args"        : "['--node=ArDomo2']",
    "cwd"         : "/home/thunder/repo.git/domo.mqtt",
    "log_date_format"  : "YYYY-MM-DD HH:mm Z",
    "pid_file"   : "/home/thunder/.pm2/pids/ArDomo2.pid",
    "error_file" : "/home/thunder/.pm2/logs/ArDomo2-err.log",
    "out_file"   : "/home/thunder/.pm2/logs/ArDomo2-out.log",
    "merge_logs"  : true
  }]
}
pm2 start domo.json 
domoSerial.js recieve these args : -b,-p,3132,-w,/media/data/home/thunder,-l,0.0.0.0,-a,: and not --node=ArDomo2

**Comment by jshkurti** [comment]
Can you try it with `npm i -g git://github.com/Unitech/PM2#development` ?
I think this might have been fixed.

**Comment by thunderace** [comment]
OK, i will try this this week-end.
Thank you

**Comment by thunderace** [comment]
Fixed, thank you
