### ISSUE TITLE
Watching a symbolic directory

### ISSUE THREAD

**Issue by craigrosborne** [Unitech/PM2#1261]
Hi

Our deployment process releases a new version of the code into a versioned folder e.g. wwwapi_v1.0.60. We then create / update a symbolic link wwwapi that points to the version folder.We start the application from symbolic link wwwapi using the following json file:
[{
  "name"             : "s008.wwwapi",
  "args"             : "['port=10800', 'host=0.0.0.0', 'platformKey=s008']",
  "script"           : "app.js",
  "cwd"              : "/var/www/s008/xxx.yyy.com/wwwapi",
  "log_date_format"  : "YYYY-MM-DD HH:mm Z",
  "error_file"       : "/var/log/www/s008/xxx.yyy.com/wwwapi/stderr.log",
  "out_file"         : "/var/log/www/s008/xxx.yyy.com/wwwapi/stdout.log",
  "min_uptime"       : "1000s",
  "max_restarts"     : 15,
  "watch"            : true,
  "ignoreWatch"      : ["[\\/\\\\]\\./", "node_modules" ],
  "merge_logs"       : true,
  "exec_interpreter" : "node",
  "exec_mode"        : "fork",
  "env": {
    "NODE_ENV": "s008"
  }
}]

When we switch the symbolic link it fails to auto restart the application. This worked on version 12.4 (node v0.10.30 and Centos 6.5) but upgrading to version 12.14  (node v0.10.30 and Centos 6.5) has broken the auto restart process. 

Touching a file inside the symbolic directory caused the restart process if the symbolic link hasn't been updated. If the symbolic link updates, touching a file won't cause the restart.

Is there a new flag to make it work this way, or is this an issue that needs fixing?

Thanks

Craig

**Comment by soyuka** [comment]
https://github.com/Unitech/PM2/issues/870

[Watch & restart docs](https://github.com/Unitech/PM2/blob/master/ADVANCED_README.md#watch--restart)

Add this:
```
"watch_options": {
    "followSymlinks": true
}
```

**Comment by craigrosborne** [comment]
I will try now, but the documentation says the default value is true.

**Comment by craigrosborne** [comment]
That doesn't fix the issue. As soon as the symbolic link is changed the watch process stops working

**Comment by soyuka** [comment]
You're right about `followSymlinks: true` it's the default options.

I ran [this test](https://gist.github.com/soyuka/5dc2857c5ba12f431688) on my os x 10.10 and it worked just fine.

Can you paste the last 150 lines from `~/.pm2/pm2.log`?

**Comment by craigrosborne** [comment]
Hi

This is all I have in the log

[root@web-01-iom .pm2]# cat pm2.log
2015-05-12 19:16:19: [Watch] Stop watching 16
2015-05-12 19:16:19: Stopping app:s008.wwwapi id:16
2015-05-12 19:16:19: Process with pid 5171 still not killed, retrying...
2015-05-12 19:16:19: App name:s008.wwwapi id:16 exited with code 143
2015-05-12 19:16:19: Process with pid 5171 killed
2015-05-12 19:16:47: [Watch] Stop watching 0
2015-05-12 19:16:47: Stopping app:s009.wwwapi id:0
2015-05-12 19:16:47: App name:s009.wwwapi id:0 exited with code 143
2015-05-12 19:16:47: Process with pid 5154 killed
2015-05-12 19:17:03: Starting execution sequence in -fork mode- for app name:s009.wwwapi id:17
2015-05-12 19:17:03: App name:s009.wwwapi id:17 online
2015-05-12 19:17:15: Change detected for app name: s009.wwwapi - restarting
2015-05-12 19:17:15: Stopping app:s009.wwwapi id:17
2015-05-12 19:17:16: Process with pid 5304 still not killed, retrying...
2015-05-12 19:17:16: App name:s009.wwwapi id:17 exited with code 143
2015-05-12 19:17:16: Process with pid 5304 killed
2015-05-12 19:17:16: Starting execution sequence in -fork mode- for app name:s009.wwwapi id:17
2015-05-12 19:17:16: App name:s009.wwwapi id:17 online

Regards

Craig

**Comment by craigrosborne** [comment]
Is there a mechanism to enable more logging so you can diagnose the issue?

**Comment by soyuka** [comment]
`export DEBUG="pm2:*"` in `--no-daemon` mode coupled with `tail -F ~/.pm2.log`

**Comment by if-meaton** [comment]
Hey, I'm having the same issue, enabling the extra logging / debug options don't seem to help or provide more information. I'm using pm2 0.14.5.. any further advice?

**Comment by soyuka** [comment]
Setup? 
Nfs? Watch options? OS? Node version?

**Comment by if-meaton** [comment]
Hey, sorry, same set up! I work for the same company - I'm currently looking into this issue

**Comment by soyuka** [comment]
Maybe that when the symlink is changed, the path can't be founded and chokidar just fails. You might try watching the previous directory for changes.

**Comment by if-meaton** [comment]
Can I tell it to watch a certain directory, or will it always use the cwd?

**Comment by soyuka** [comment]
[RTFM](https://github.com/Unitech/PM2/blob/master/ADVANCED_README.md#watch--restart)

**Comment by if-meaton** [comment]
haha, thanks! It's been a while since I was told to do that :)

**Comment by if-meaton** [comment]
Still doesn't seem to work, here is my current config:

[{
  "name"             : "t009.cmsapi",
  "args"             : "['port=10921', 'host=0.0.0.0', 'platformKey=t009', 'debugOutput=false']",
  "script"           : "main.js",
  "cwd"              : "/var/www/t009/casino.iforium.com/cmsapi",
  "log_date_format"  : "YYYY-MM-DD HH:mm Z",
  "error_file"       : "/var/log/www/t009/casino.iforium.com/cmsapi/stderr.log",
  "out_file"         : "/var/log/www/t009/casino.iforium.com/cmsapi/stdout.log",
  "min_uptime"       : "1000s",
  "max_restarts"     : 15,
  "watch"            : "/var/www/t009/casino.iforium.com",
  "ignoreWatch"      : ["[\\/\\\\]\\./", "node_modules", "assets", "temp_uploads"  ],
  "merge_logs"       : true,
  "exec_interpreter" : "node",
  "exec_mode"        : "fork",
  "env": {
    "NODE_ENV": "t009"
  }
}]

I've changed 'watch' to be "/var/www/t009/casino.iforium.com" and "/var/www/t009/casino.iforium.com/cmsapi" neither trigger a restart.. pm2.log doesn't show anything nor does watching it in no --no-daemon mode.. any other ideas?

**Comment by soyuka** [comment]
Which of those is your symlink? What's your operating system? Are you using NFS?

Could you give me more details about the directory structure? What is supposed to change?

Does this test works: https://gist.github.com/soyuka/5dc2857c5ba12f431688 ?

**Comment by if-meaton** [comment]
/var/www/t009/xxx.xxx.com/cmsapi links to /var/www/t009/xxx.xxx.com/cmsap_1.0.xx-xx (whatever is the current version) - centos 6.5 final not using NFS.

During deployment the cmsapi symlink is changed to the latest version that was just deployed..

Can't seem to get the test to work - not sure if I'm missing a step...

**Comment by if-meaton** [comment]
As for the test in ~/ I have:
testwatch.json
testw.js
testwatch/
testsym -> ./testwatch

Contents of testwatch.json:

[{
  "name"      : "testwatch",
  "script"    : "./testw.js",
  "watch"     : ["./testsym"]
}]

Contents of testw.js:

setInterval(function() {
  console.log('hi');
}, 2000)


pm2 start testwatch.json starts the process, with watch enabled - touching anything in './testwatch' doesn't restart the process nor does touching anything 'testsym'

**Comment by if-meaton** [comment]
Even now, I'm sitting inside the cmsapi directory and touching test files and it isn't restarting the process.. current config:

[{
  "name"             : "t009.cmsapi",
  "args"             : "['port=10921', 'host=0.0.0.0', 'platformKey=t009', 'debugOutput=false']",
  "script"           : "main.js",
  "cwd"              : "/var/www/t009/www.xxx.com/cmsapi",
  "log_date_format"  : "YYYY-MM-DD HH:mm Z",
  "error_file"       : "/var/log/www/t009/www.xxx.com/cmsapi/stderr.log",
  "out_file"         : "/var/log/www/t009/www.xxx.com/cmsapi/stdout.log",
  "min_uptime"       : "1000s",
  "max_restarts"     : 15,
  "watch"            : "./",
  "ignoreWatch"      : ["[\\/\\\\]\\./", "node_modules", "assets", "temp_uploads"  ],
  "merge_logs"       : true,
  "exec_interpreter" : "node",
  "exec_mode"        : "fork",
  "env": {
    "NODE_ENV": "t009"
  }
}]

**Comment by soyuka** [comment]
See screenshots: 

![capture du 2015-08-03 14 33 43](https://cloud.githubusercontent.com/assets/1321971/9037566/c81b1aa4-39ec-11e5-97fd-95af125398ea.png)
![capture du 2015-08-03 14 34 05](https://cloud.githubusercontent.com/assets/1321971/9037565/c81a25ea-39ec-11e5-8186-52cc24ef1523.png)

Everything is perfectly working to me:
1. changing the link (`ln -sfn newtarget/ link`)
2. writing something in the link

In red you can see the pm2 debug messages about watch to see if options are the one you want or that he reloads.

**Comment by if-meaton** [comment]
Ok.. What are you using on the right hand side? I use --no-daemon but I don't see anything in red at all..

**Comment by soyuka** [comment]
`DEBUG="pm2:*" pm2 start --no-daemon server.json`

**Comment by if-meaton** [comment]
I don't seem to get all those messages like you, running the above command and restarting the app I get the following in the log:

14:20:27 PM2 Stopping app:t009.cmsapi id:12
14:20:27 PM2 App name:t009.cmsapi id:12 exited with code 143
14:20:27 PM2 Process with pid 30411 killed
14:20:27 PM2 Starting execution sequence in -fork mode- for app name:t009.cmsapi id:12
14:20:27 PM2 App name:t009.cmsapi id:12 online
14:20:28 t009.cmsapi-12 Server Running on 0.0.0.0:10921


nothing about watching anything.. am I missing something?

**Comment by soyuka** [comment]
Do you use the env variable `DEBUG="pm2:*"`? Did you `pm2 kill` to clear memory before testing on a clean env?

**Comment by if-meaton** [comment]
Managed to get it working - I think the 'followSymlinks' watch option helped. Thanks for all your help :)
