### ISSUE TITLE
pm2 + iojs 2.0.0 docker image: Error: spawn /opt/wwwapp/node_modules/pm2/node_modules/babel/bin/babel-node ENOENT

### ISSUE THREAD

**Issue by jbmusso** [Unitech/PM2#1262]
Hi there,

I'm using pm2 v0.12.14 with io.js 2.0.0 using the official Dockerfile from https://github.com/iojs/docker-iojs

The following command will fail in the docker container (application doesn't start, `status: errored`):

```
$ pm2 start proxy.js --no-daemon --next-gen-js --node-args="--stage 1"
```
Gives the following logs and error:
```
web_1   | 2015-05-12 18:09:51: [PM2][WORKER] Started with refreshing interval: 30000
web_1   | 2015-05-12 18:09:51: [[[[ PM2/God daemon launched ]]]]
web_1   | 2015-05-12 18:09:51: BUS system [READY] on port /root/.pm2/pub.sock
web_1   | 2015-05-12 18:09:51: RPC interface [READY] on port /root/.pm2/rpc.sock
web_1   | 2015-05-12 18:09:51: [PM2] Overridding next-gen-js interpreter
web_1   | 2015-05-12 18:09:51: [PM2] Next gen JS enabled
web_1   | 2015-05-12 18:09:51: Starting execution sequence in -fork mode- for app name:proxy id:0
web_1   | 2015-05-12 18:09:51: App name:proxy id:0 online
web_1   | 2015-05-12 18:09:51: Error: spawn /opt/wwwapp/node_modules/pm2/node_modules/babel/bin/babel-node ENOENT
web_1   |     at exports._errnoException (util.js:843:11)
web_1   |     at Process.ChildProcess._handle.onexit (child_process.js:987:32)
web_1   |     at onErrorNT (child_process.js:1138:16)
web_1   |     at doNTCallback2 (node.js:437:9)
web_1   |     at process._tickDomainCallback (node.js:392:17)
web_1   | 2015-05-12 18:09:51: [PM2] Process proxy.js launched
```

Note that the above command works fine with pm2 v0.12.14 under Mac OS X v10.9.5 (application runs fine `status: online`).

I will happily give more information if needed. I'm unsure if this is more an issue related to the Dockerfile or if this is more related to pm2.

Thanks.

**Comment by jshkurti** [comment]
Maybe you should `npm i -g babel`
https://babeljs.io/docs/usage/cli/

**Comment by jbmusso** [comment]
Added a `RUN npm i -g babel`, unfortunately I'm still getting the issue.

**Comment by jbmusso** [comment]
Found (and resolved) the issue.

I had `"babel": "^5.x"` set as a dependency within `package.json`, which caused npm not to add babel within the `wwwapp/node_modules/pm2/node_modules/` folder (hence the ENOENT error).

Removing babel as a direct dependency of my application and doing a fresh `npm install` solved the issue.

**Comment by jshkurti** [comment]
Thanks for letting us know :)
