### ISSUE TITLE
pm2-dev watcher doesn't follow links

### ISSUE THREAD

**Issue by petemill** [Unitech/PM2#1263]
pm2-dev does not reload the app when a file in an 'npm link'ed module changes. This is a common pattern for node app development when you are also developing a module shared by multiple apps.

thanks!

**Comment by soyuka** [comment]
Related #1261 

Could you show your pm2 configuration? What is your pm2 version ? node version ? An output of `~/.pm2/pm2.log` after trying to watch would be nice too.

Thanks.

**Comment by petemill** [comment]
This is still an issue. It isn't just with running pm2 processes, this is with ```pm2-dev``` which, according to the documentation is *always* meant to restart on changes to files. It just doesn't seem to be looking at linked files. This happens on a fresh install.

Steps to reproduce:

 - ```mkdir TestModule```
 - ```cd TestModule```
 - ```npm init```
 - create a basic js file at index.js
 - ```npm link```
 -  ```cd ..```
 - ```mkdir TestApp```
 - ```cd TestApp```
 - ```npm link TestModule```
 - create a basic js file at app.js which has the lines: ```require('TestApp');setTimeout(function(){},100000)```
 - ```pm2-dev app.js```
 - Edit ../TestModule/index.js

Expected: the app restarts

Observed: the app does not restart

```pm2 -V```
Output: ```0.14.1```

```pm2-dev -V```
Output: ```0.14.1```

```iojs --version```
Output: ```v2.3.0```

OS X 10.10
