### ISSUE TITLE
how to config the ecosystem.json the ssh login with different port

### ISSUE THREAD

**Issue by ChitaGideon** [Unitech/pm2#1264]
my remote server use different port ,like 222 for ssh login

how could I config that in deploy ecosystem.json

**Comment by ottersoftware** [comment]
I've not yet tested it myself (I just came across these two tickets whilst looking for a solution to this myself) but this might help: https://github.com/Unitech/PM2/issues/880

**Comment by lino-silva** [comment]
Hey,
This is what I've been using, and works well:
`    production: {
      user: 'REDACTED',
      host: [{
        host: 'REDACTED',
        port: 'REDACTED'
      }],
`
Additional notes: note that host is not an object, but an array of objects. Note as well that port is a string, as it didn't work with a numeric value.
