### ISSUE TITLE
can׳t find pmx module.

### ISSUE THREAD

**Issue by roysG** [Unitech/pm2#1269]
Error: Cannot find module 'pmx'

**Comment by jshkurti** [comment]
More details please :)
When does this occur ?

**Comment by roysG** [comment]
i inject it in the app.js as explained in the keymetrics.

but this is the error i get:

module.js:340
    throw err;
          ^
Error: Cannot find module 'pmx'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/Admin/www/picktags.com/public_html/server/app.js:27:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

Process finished with exit code 8

**Comment by jshkurti** [comment]
Well, perhaps you need to install it first.
`npm i pmx` or `npm i -g pmx` to install it globally.

**Comment by pyramation** [comment]
Still occurs. 

Happens on fresh installs

- [x] Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-48-generic x86_64)
- [x] OSX Yosemite

Is this a pmx or pm2 issue?

It's super easy to reproduce. All I need to run is

```
$ pm2 web
$ pm2 list
┌────────────────────┬────┬──────┬─────┬─────────┬─────────┬────────┬────────┬──────────┐
│ App name           │ id │ mode │ pid │ status  │ restart │ uptime │ memory │ watching │
├────────────────────┼────┼──────┼─────┼─────────┼─────────┼────────┼────────┼──────────┤
│ pm2-http-interface │ 0  │ fork │ 0   │ errored │ 15      │ 0      │ 0 B    │ disabled │
└────────────────────┴────┴──────┴─────┴─────────┴─────────┴────────┴────────┴──────────┘
```

Then when I look at the logs it shows cannot find `pmx`:

```
pm2-http-interface-0 (err): Error: Cannot find module 'pmx'
pm2-http-interface-0 (err):     at Function.Module._resolveFilename (module.js:336:15)
pm2-http-interface-0 (err):     at Function.Module._load (module.js:278:25)
pm2-http-interface-0 (err):     at Module.require (module.js:365:17)
pm2-http-interface-0 (err):     at require (module.js:384:17)
pm2-http-interface-0 (err):     at Object.<anonymous> (/Users/brandcast/.nvm/versions/v0.12.6/lib/node_modules/pm2/lib/ProcessContainerFork.js:2:1)
pm2-http-interface-0 (err):     at Module._compile (module.js:460:26)
pm2-http-interface-0 (err):     at Object.Module._extensions..js (module.js:478:10)
pm2-http-interface-0 (err):     at Module.load (module.js:355:32)
pm2-http-interface-0 (err):     at Function.Module._load (module.js:310:12)
pm2-http-interface-0 (err):     at Function.Module.runMain (module.js:501:10)
```

**Comment by pyramation** [comment]
So `npm install -g pmx` worked, but shouldn't this be explicit in the install of this package?

**Comment by imsky** [comment]
This happens for me as well with a fresh nvm install of Node in 2 different VMs. `npm install -g pmx` **does not** fix it.

**Comment by imsky** [comment]
This bug seems to be introduced in 0.14.3. 0.14.2 is the last version where I do not see this error.

**Comment by soyuka** [comment]
Do you have `pmx` installed in your package? Pm2 has it as a dependency : https://github.com/Unitech/PM2/blob/master/package.json#L162.

**Comment by imsky** [comment]
@soyuka Why would a package need a pm2 dependency? This error still happens even when `pmx` is installed globally.

**Comment by soyuka** [comment]
> Why would a package need a pm2 dependency?

If you want to use `pmx` in your app.

Are you using it in your app? Or is it pm2 that fails to require it?

When using `require('package')` it can fail to require a global package [see this so question](http://stackoverflow.com/questions/15636367/nodejs-require-a-global-module-package). 

If pm2 has this dependency I won't see why it'd fail to require it.

**Comment by imsky** [comment]
> Are you using it in your app? Or is it pm2 that fails to require it?

I'm not using it in my app. The basic Express "hello world" fails with this.

**Comment by jshkurti** [comment]
Can you try `npm i -g Unitech/PM2#pmx_path` then `pm2 start app.js` then `pm2 logs`.
It will display a list of paths in which pm2 will look up for the pmx module.

**Comment by jshkurti** [comment]
Mine shows : 
```
child-0 (out): [ '/home/joni/.nvm/versions/node/v0.12.7/lib/node_modules/pm2/lib/node_modules',
child-0 (out):   '/home/joni/.nvm/versions/node/v0.12.7/lib/node_modules/pm2/node_modules',
child-0 (out):   '/home/joni/.nvm/versions/node/v0.12.7/lib/node_modules',
child-0 (out):   '/home/joni/.nvm/versions/node/v0.12.7/node_modules',
child-0 (out):   '/home/joni/.nvm/versions/node/node_modules',
child-0 (out):   '/home/joni/.nvm/versions/node_modules',
child-0 (out):   '/home/joni/.nvm/node_modules',
child-0 (out):   '/home/joni/node_modules',
child-0 (out):   '/home/node_modules',
child-0 (out):   '/node_modules' ]
```

**Comment by jshkurti** [comment]
Since pmx is a dependecy of pm2, it should be somewhere in these folders.

**Comment by imsky** [comment]
```
hello-0 (out): [ '/usr/local/lib/node_modules/pm2/lib/node_modules',
hello-0 (out):   '/usr/local/lib/node_modules/pm2/node_modules',
hello-0 (out):   '/usr/local/lib/node_modules',
hello-0 (out):   '/usr/local/node_modules',
hello-0 (out):   '/usr/node_modules',
hello-0 (out):   '/node_modules' ]
```
node v0.10.25, npm v1.3.10

**Comment by jshkurti** [comment]
@pyramation @roysG are you also on Node 0.10.x ?

**Comment by proreact-mj** [comment]
Installing it locally "npm install pmx --save" worked for me. Not sure if this is bad practice?

**Comment by Unitech** [comment]
Yes you need to add pmx as a dependency in the package.json or do `npm install pmx --save`

**Comment by yunnysunny** [comment]
I uninstall pm2-logrotate `pm2 uninstall pm2-logrotate`,and reinstall it `pm2 install pm2-logrotate`, and the pm2-logrotate works ok now.

**Comment by AlekEagleYT** [comment]
when i use `npm install pmx --save` i get `npm ERR! Error: EPERM: operation not permitted, symlink '../semver/bin/semver' -> '/media/pi/ALEKEAGLE/Discord Bot/node_modules/.bin/semver'
npm ERR!  { Error: EPERM: operation not permitted, symlink '../semver/bin/semver' -> '/media/pi/ALEKEAGLE/Discord Bot/node_modules/.bin/semver'
npm ERR!   cause: 
npm ERR!    { Error: EPERM: operation not permitted, symlink '../semver/bin/semver' -> '/media/pi/ALEKEAGLE/Discord Bot/node_modules/.bin/semver'
npm ERR!      errno: -1,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'symlink',
npm ERR!      path: '../semver/bin/semver',
npm ERR!      dest: '/media/pi/ALEKEAGLE/Discord Bot/node_modules/.bin/semver' },
npm ERR!   stack: 'Error: EPERM: operation not permitted, symlink \'../semver/bin/semver\' -> \'/media/pi/ALEKEAGLE/Discord Bot/node_modules/.bin/semver\'',
npm ERR!   errno: -1,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../semver/bin/semver',
npm ERR!   dest: '/media/pi/ALEKEAGLE/Discord Bot/node_modules/.bin/semver',
npm ERR!   parent: 'alekaagleyts_bot' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-06-09T23_15_26_756Z-debug.log`
and same thing with `sudo npm install pmx --save`
