### ISSUE TITLE
PM2 cluster allocates memory incorrectly

### ISSUE THREAD

**Issue by icaliman** [Unitech/PM2#1272]
When I start a cluster, each instance has allocated ~80MB of RAM:

![image](https://cloud.githubusercontent.com/assets/4498933/7628884/ce3ae758-fa30-11e4-9aa1-fd8a49e1e625.png)

After running `pm2 update` each instance gets ~900MB:

![image](https://cloud.githubusercontent.com/assets/4498933/7628915/0a84dde0-fa31-11e4-9aef-14be8094207e.png)

After restarting instances with `pm2 restart`, each restarted instance gets 80MB again.

Is it possible to allocate 900MB on starting/restarting?

Thank you.

**Comment by icaliman** [comment]
some updates on this?

**Comment by jshkurti** [comment]
I'm going to look at this at some point. Sorry for the lateness.

**Comment by jshkurti** [comment]
I tired with this sample code :
```js
var http = require('http');

http.createServer(function(req, res) {
  res.writeHead(200);
  res.end('hey');
}).listen(8000);

process.on('message', function(msg) {
  if (msg == 'shutdown') {
    console.log('Closing all connections...');
    setTimeout(function() {
      console.log('Finished closing connections');
      process.exit(0);
    }, 500);
  }
});
```
I started the app `pm2 start child.js -i 0` :
![slow7](https://cloud.githubusercontent.com/assets/7647602/8111602/0ce7d310-1063-11e5-9f63-ce36c4000435.png)

I did several `pm2 update`, then :

![slow8](https://cloud.githubusercontent.com/assets/7647602/8111618/1b6b42f0-1063-11e5-8e59-fead1f9a2b45.png)

Not much of a difference here.

**Comment by jshkurti** [comment]
I notice one thing on your screenshots.
In the first one, all your cpu usages are at 0%.
In the second screenshot they are at around ~20% which means your server is serving some requests, in which case it is perfectly normal to use a bit more memory.

**Comment by soyuka** [comment]
What I understand here is that you don't really see the reality on `pm2 monit`.

In fact, a nodejs process has :
```
Currently, by default v8 has a memory limit of 512mb on 32-bit systems, and 1gb on 64-bit systems. The limit can be raised by setting --max_old_space_size to a maximum of ~1024 (~1 GiB) (32-bit) and ~1741 (~1.7GiB) (64-bit), but it is recommended that you split your single process into several workers if you are hitting memory limits.
```

> 
[source](https://github.com/joyent/node/wiki/FAQ#what-is-the-memory-limit-on-a-node-process)

The cluster is forking your main process (basically), so they'd have an "allocated" memory of the max memory limit for a process. 
On `pm2 monit` memory is based on "ratios": https://github.com/Unitech/PM2/blob/24f1bd77a1053448d02580e4d4ccdccf0ee28e46/lib/Monit.js#L13.
So, this is a normal behavior.

**Comment by icaliman** [comment]
When I did the first screenshot, after `pm2 start`, the web page was infinitely loading, the server was not responding (??). But after `pm2 update` web page was loading quickly.

Maybe it's because I scaled the server to more instances than the number of CPUs?

**Comment by jshkurti** [comment]
No. it must be a bug. You can scale the server to a unlimited number of instances.
Are you using an old version of PM2 ?
Does this bug happen everytime ?
Can you reproduce ?

**Comment by icaliman** [comment]
I updated to the latest version some days ago. I will try to reproduce.

**Comment by Unitech** [comment]
Please feel free to reopen the issue if the problem persists
