### ISSUE TITLE
pm2 start more than two daemon

### ISSUE THREAD

**Issue by no7dw** [Unitech/PM2#1276]
in some production machine , I found pm2 start more than two daemon

    klg@gentoo:~$ ps -ef | grep PM2
    klg       1978     1  0 May13 ?        00:03:57 PM2 v0.12.14: God Daemon                                     
    klg       3832     1  0 May13 ?        00:14:16 PM2 v0.12.14: God Daemon                                     
    klg      10945     1  0 12:31 ?        00:00:00 PM2 v0.12.14: God Daemon                                     
    klg      20148 20042  0 12:53 pts/0    00:00:00 grep PM2

here is logs related:

    klg@gentoo:~/.pm2$ cat pm2.pid
    10945klg@gentoo:~/.pm2$ date
    Fri May 15 12:57:58 CST 2015
    klg@gentoo:~/.pm2$ less pm2.log 
    klg@gentoo:~/.pm2$ tail -f pm2.log
    2015-05-13 17:08:45: App name:koala-9001 id:0 online    
    2015-05-13 17:11:24: Stopping app:koala-9001 id:0
    2015-05-13 17:11:24: App name:koala-9001 id:0 exited with code 0
    2015-05-13 17:11:24: Process with pid 22407 killed
    2015-05-13 17:11:24: Starting execution sequence in -fork mode- for app name:koala-9001 id:0
    2015-05-13 17:11:24: App name:koala-9001 id:0 online
    2015-05-15 12:31:30: [PM2][WORKER] Started with refreshing interval: 30000
    2015-05-15 12:31:30: [[[[ PM2/God daemon launched ]]]]
    2015-05-15 12:31:31: BUS system [READY] on port /home/klg/.pm2/pub.sock
    2015-05-15 12:31:31: RPC interface [READY] on port /home/klg/.pm2/rpc.sock

seems like has nothing to do with start up json, because last command which start another daemon is :

    pm2  -v

    klg@gentoo:~/.pm2$ pm2 -v
    [PM2] Spawning PM2 daemon
    [PM2] PM2 Successfully daemonized
    0.12.14

I have tried to update to latest version , but without luck.

**Comment by franciskim** [comment]
I have a similar issue where I have 2 daemons running.

**Comment by KTachyon** [comment]
Same problem here. For some reason, pm2 starts a new daemon and we lose control over the older daemon's processes. In order to regain control, we need to kill the older daemon and start everything on the new one.

**Comment by odnarb** [comment]
+1

```sh
localuser@DEVSERVER:/opt/myapp$ ps aux | grep PM2
localus+ 11695  0.0  0.0  11744   916 pts/0    S+   16:05   0:00 grep --color=auto PM2
localuser@DEVSERVER:/opt/myapp$ sudo pm2 -v
[PM2] Spawning PM2 daemon
[PM2] PM2 Successfully daemonized
0.12.15
localuser@DEVSERVER:/opt/myapp$ ps aux | grep PM2
root     11707  1.9  0.5 661272 22860 ?        Ssl  16:06   0:00 PM2 v0.12.15: God Daemon
localus+ 11713  0.0  0.0  11744   916 pts/0    S+   16:06   0:00 grep --color=auto PM2
localuser@DEVSERVER:/opt/myapp$ node -v
v0.10.38

```

**Comment by jshkurti** [comment]
@odnarb I only see one daemon in your sample.

**Comment by KTachyon** [comment]
Happened to me again:

```
projectime@ubuntu-server:~$ pm2 list
[PM2] Spawning PM2 daemon
[PM2] PM2 Successfully daemonized
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬────────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ memory │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
projectime@ubuntu-server:~$ ps aux | grep PM2
project+  1381  0.0  1.0 711020 62732 ?        Ssl  May27   0:55 PM2 v0.12.15: God Daemon                               
project+  6717  0.7  0.5 673564 30756 ?        Ssl  10:46   0:00 PM2 v0.12.15: God Daemon                               
project+  6728  0.0  0.0  12004  2128 pts/3    S+   10:47   0:00 grep --color=auto PM2
projectime@ubuntu-server:~$ node -v
v0.12.3
projectime@ubuntu-server:~$ pm2 -v
0.12.15
````

I have 4 instances running in cluster that I cannot list because they are controlled by the previous daemon (PID 1381). I can only "see" instances running on the newer daemon, but I can still watch the logs from the older daemon's instances via pm2 logs.

**Comment by odnarb** [comment]
Okay, I think I found a work around. Or maybe it was an env issue for me. I had installed pm2 and then used with sudo before... so basically I tried to clean out EVERYTHING:
```sh
npm remove -g pm2
cd /root
rm -rf .pm2
cd /home/myuser
rm -rf .pm2
npm install -g pm2
pm2 startup ubuntu
[then run the command with the PATH that's echoed by pm2 in the console]
```

So what might have happened is the pm2 daemons were spawned as a result of using different users (sudo/root and non-sudo) in addition to different installation paths for node/npm. That's another problem but quite possibly related so I'll jot down some details.

Installation of node.js on Ubuntu had been a pain for me. The apt repo's were way behind (0.10.38 vs 0.12.x) the current release of node. I needed the latest stable release for node.js. So I think I installed via some different ways and didn't remove everything that embedded itself in my /usr/ folders and elsewhere: apt, nvm, some home-made script, finally came to homebrew for linux.

I probably could have found a way to install for my non-root user but I am not that interested in learning more about linux (or my environment) than I really need to know. I needed a fast solution  at work to get crap done.

I also used the setcap approach for allowing non-root to run my app on ports less than <1024.

I haven't written this off completely as an issue and I'll keep looking. Hope this helps someone.

**Comment by Unitech** [comment]
Yes it the case when you run pm2 under different user (w/o sudo)

**Comment by valp124** [comment]
The same thing happens to me, all these years later, and this is not a sudo issue at all. Look:

![image](https://user-images.githubusercontent.com/7969539/189387406-c1173df3-026d-4316-8da8-0bf13e71bf35.png)

In the meantime, all the processes that the first daemon had started are still there but I have not way to control them through pm2. I'd have to kill both daemons and restart everything, which is ok one time, but it happens again and again...
