### ISSUE TITLE
max_memory_restart and gracefulReload

### ISSUE THREAD

**Issue by iclems** [Unitech/PM2#1279]
It seems to me that if in cluster mode, max_memory_restart should trigger a gracefulReload. For instance, I'm using it with an API and I wish it could reload it gracefully if it ever leaks.

**Comment by jshkurti** [comment]
I agree, I will change that

**Comment by jshkurti** [comment]
It's done :)
`npm i -g git://github.com/Unitech/PM2#development`
Otherwise it will be included in PM2 v0.12.15 which is coming soon ;)

**Comment by iclems** [comment]
Thanks, perfect! What's the expected release date for 12.15?

**Comment by jshkurti** [comment]
It's been released ;)

**Comment by scriby** [comment]
Late to the party, but thanks for this change. It was exactly what I needed!
