### ISSUE TITLE
script not found when using capistrano-like directory structure

### ISSUE THREAD

**Issue by marbemac** [Unitech/pm2#128]
I'm deploying my app using the following directory structure:

releases ->
  1 -> code
  2 -> code
  3 -> code
current -> symbolic link -> releases/3

Basically on deploy it creates a new releases folder, and then creates a symbolic link called current that points to the active release (capistrano). I start pm2 in the current directory, and on deploy would like to reload all from the current directory, however I get this error:

PM2 [ERROR] script not found : /var/www/releases/20131023191028/all

This is presumably because pm2 doesn't work with the symbolic directory, so it's still running the app in the old release folder. Any thoughts on how to manage a deploy process like this with pm2?

**Comment by rishabhmhjn** [comment]
I had the same issue in my `capistrano`+`pm2` based release.
This error resulted in this error: https://github.com/Unitech/pm2/issues/659

**Comment by samiruppaluru** [comment]
@rishabhmhjn and anyone else who finds themselves here dealing with this, pm2 has a page in their docs that takes you through how to solve this problem: 

http://pm2.keymetrics.io/docs/tutorials/capistrano-like-deployments

**Comment by rishabhmhjn** [comment]
@samiruppaluru Awesome! I need to fix that deployment process. Thank you so much.
I will update here if it worked.

**Comment by rishabhmhjn** [comment]
it did work. Thanks @samiruppaluru 

referring https://github.com/winstonjs/winston/issues/798 as I thought it was a winston issue but it is not

**Comment by mruba** [comment]
thank you @samiruppaluru this save me a lot of time
