### ISSUE TITLE
pm2-dev doesn't use the watch flag in config

### ISSUE THREAD

**Issue by adrianolaru** [Unitech/PM2#1284]
I'm running `pm2-dev run some.config.json` and some of the apps there have `"watch": false` but that does nothing.

**Comment by adrianolaru** [comment]
Or maybe it does work but it doesn't update the watching column in `pm2 ls`?

**Comment by Unitech** [comment]
It forces the watch option https://github.com/Unitech/PM2/blob/master/bin/pm2-dev#L33
