### ISSUE TITLE
Graceful shutdown

### ISSUE THREAD

**Issue by iliakan** [Unitech/pm2#1286]
What is the recommended way of doing a "graceful shutdown"?
I mean: send `shutdown` to all processes and kill them after timeout if they still exist.

Any command for that?

Essentially the same as `gracefulReload`, but do not reload ;)

**Comment by jshkurti** [comment]
That is a good point !
I'm going to implement that :)

**Comment by jshkurti** [comment]
It should be named `gracefulStop` or perhaps `shutdown` is sexier ?
`pm2 shutdown <name | id | all | json>`

**Comment by iliakan** [comment]
`gracefulShutdown` would be sexier, but you have `pm2 stop` already, so `pm2 gracefulStop` is more logical.

**Comment by DenisGorbachev** [comment]
Desperately need this :) +100, +1000, +1000000 :)

**Comment by shaharmor** [comment]
+100

**Comment by hypesystem** [comment]
:+1:

what is status on this?

**Comment by lklepner** [comment]
I'm also curious about this

**Comment by jhansen-tt** [comment]
+1

**Comment by geekyme** [comment]
I'm interested on this too. Would like a way to safely terminate processes so that I can perform upgrades on Node.js on my servers one by one (load balancers will direct traffic to other node.js servers while one is under maintenance)

**Comment by Unitech** [comment]
Now in PM2 there is a given order of signales sent to your processes (SIGINT then SIGKILL) with configurable timing so you can clean whichever things on your code before your process get restarted/stopped

Link to doc: http://pm2.keymetrics.io/docs/usage/signals-clean-restart/
