### ISSUE TITLE
Silent failure when output dir does not exist

### ISSUE THREAD

**Issue by KidkArolis** [Unitech/PM2#1289]
I have the following config for my app

```
[
  {
    "name": "enporium",
    "script": "/data/app/apps/enporium/current",
    "cwd": "/data/app/apps/enporium/current",
    "merge_logs": true,
    "out_file": "/data/app/logs/enporium-out.log",
    "error_file": "/data/app/logs/enporium-error.log",
    "min_uptime": 5000,
    "max_restarts": 10,
    "exec_interpreter": "/home/app/.nvm/versions/node/v0.12.0/bin/node",
    "node_args": [
      "--harmony"
    ]
  }
]
```

Directory `/data/app/logs` did not exist (only `/data/app`) and so `pm2 start config.json` would just say "Launching process" but nothing was happening. The process didn't start, did not appear in the list, there was no error shown.

I know this is not super major, but would be nice if at the very least it would show a warning (or create the target directory for `out_file` and `error_file`.

**Comment by Tjatse** [comment]
Confirmed!

**Comment by Unitech** [comment]
Fixed
