### ISSUE TITLE
PM2 list do not work with large set of workings processes

### ISSUE THREAD

**Issue by adrian-ludwig** [Unitech/PM2#1290]
pm2 version v0.12.15
node v0.12.3
CENTOS

with $pm2 list
I get

│ App name     │ id │ mode    │ pid   │ status │ restart │ uptime │ memory       │ watching │
├──────────────┼────┼─────────┼───────┼────────┼─────────┼────────┼──────────────┼──────────┤
│ graph        │ 1  │ cluster │ 20850 │ online │ 4       │ 3h     │ 332.328 MB   │ disabled │
│ restfs       │ 2  │ cluster │ 20849 │ online │ 3       │ 3h     │ 176.699 MB   │ disabled │
│ restfs       │ 3  │ cluster │ 3044  │ online │ 1       │ 4h     │ 187.473 MB   │ disabled │
│ restfs       │ 4  │ cluster │ 3045  │ online │ 1       │ 4h     │ 182.727 MB   │ disabled │
│ restfs       │ 5  │ cluster │ 3050  │ online │ 1       │ 4h     │ 188.512 MB   │ disabled │
│ restfs       │ 6  │ cluster │ 3062  │ online │ 1       │ 4h     │ 183.773 MB   │ disabled │
│ queue        │ 10 │ cluster │ 20511 │ online │ 24      │ 7s     │ 139.734 MB   │ disabled │
│ queue        │ 11 │ cluster │ 4304  │ online │ 23      │ 4m     │ 139.980 MB   │ disabled │
│ queue        │ 12 │ cluster │ 4317  │ online │ 23      │ 4m     │ 139.047 MB   │ disabled │
│ queue        │ 13 │ cluster │ 4361  │ online │ 23      │ 4m     │ 147.355 MB   │ disabled │
│ queue        │ 14 │ cluster │ 20260 │ online │ 23      │ 39s    │ 142.688 MB   │ disabled │
│ queue        │ 15 │ cluster │ 7601  │ online │ 23      │ 4m     │ 140.336 MB   │ disabled │
│ queue        │ 16 │ cluster │ 20252 │ online │ 23      │ 39s    │ 143.258 MB   │ disabled │

And i have like ~60 processes running

The same is with pm2 jlist. Output is sliced at some point.

**Comment by jshkurti** [comment]
Hmm that's strange. It might be a CentOS specific issue because it works just fine on my Ubuntu.

**Comment by soyuka** [comment]
#1077 duplicate ?

**Comment by adrian-ludwig** [comment]
Yes, It is duplicate I belive.

**Comment by Tjatse** [comment]
I can not find a better way to solve this, just pipe pm2 [action] through less, e.g.: pm2 ls | less, pm2 -h | less... (q quits the session).
