### ISSUE TITLE
pm2 deploy doesn't set up git repo to track a different branch correctly

### ISSUE THREAD

**Issue by naartjie** [Unitech/pm2#1291]
I am using `pm2 deploy` to deploy a different branch, not `master` and when I go to my `project-name/current` dir on the server, the files are all correct, but `git status` thinks it's on `master`: 

``` sh
On branch master
Your branch and 'origin/master' have diverged
```

Anyone else experience this?

**Comment by jorge-d** [comment]
Hi,

Well [pm2-deploy](https://github.com/Unitech/pm2-deploy) does a `git reset --hard origin/you_branch` at [this line](https://github.com/Unitech/pm2-deploy/blob/master/deploy#L192).

We could change this do be a `git checkout` instead maybe?

**Comment by naartjie** [comment]
How about both `git checkout` and then `git reset --hard origin/branch_name`, to be sure?

**Comment by itomas** [comment]
+

any news?

**Comment by Tak-MK** [comment]
+1...

**Comment by ldarren** [comment]
@Unitech still facing this problem on pm2 3.0, any fix?
