### ISSUE TITLE
pm2 deploy: causes UFW ban

### ISSUE THREAD

**Issue by naartjie** [Unitech/PM2#1292]
Sometimes `pm2 deploy` will fail to connect intermittently, and eventually causes me to get blocked by Ubuntu's UFW, with a `[UFW LIMIT BLOCK]` in the log files.

I am normally connected to the server where I am deploying to, (in another terminal session, but via mosh). I'm not sure if this causes any conflicts, but it doesn't seem like pm2 is reusing that connection as it takes a while to connect every time.

Has anyone else experienced this?

**Comment by Unitech** [comment]
Please post this issue [here](https://github.com/Unitech/pm2-deploy)

**Comment by naartjie** [comment]
Thanks, done Unitech/pm2-deploy#57
