### ISSUE TITLE
cwd option no longer works on 0.12.15

### ISSUE THREAD

**Issue by masterkorp** [Unitech/PM2#1293]
Hello, on pm2 ``0.12.15`` the ``cwd`` parameter does not work

```json
{
  "name": "name-app",
  "script": "index.js",
  "exec_mode": "cluster",
  "run_as_user": "my-user",
  "cwd": "/path/to/my/code/current",
  "env": {
    "NODE_ENV": "staging",
    "DEBUG": "*"
  }
}
```
The error that apears on the application logs is:
```
PM2: 2015-05-21 22:42:00: App name:name-app id:12 exited with code 1
PM2: 2015-05-21 22:42:00: Starting execution sequence in -cluster mode- for app name:name-app id:12
PM2: 2015-05-21 22:42:00: App name:name-app id:12 online
PM2: path.js:411
PM2:     var path = (i >= 0) ? arguments[i] : process.cwd();
PM2:                                                  ^
PM2: Error: ENOENT: no such file or directory, uv_cwd
PM2:     at Error (native)
```

This error does not happen on pm2 version ``0.12.12``, I did not confirmed any more versions, just downgraded to this one, because it was the one we tested before the upgrade.

This feature is a must have if you have automated deploys (capistrano style with a symlink).
**pm2 version:** 0.12.15
**io.js version:** v1.7.1

**Comment by jshkurti** [comment]
I tried to reproduce the bug but no luck.
![probe9](https://cloud.githubusercontent.com/assets/7647602/7772761/7b38fb46-00a0-11e5-81fb-e314dc737717.png)

**Comment by DaAwesomeP** [comment]
Is there a way to set the CWD when running from the command line?

**Comment by DaAwesomeP** [comment]
I guess not.

**Comment by iam4x** [comment]
I'm having this issue too. Can't find the source.

**Comment by raeesaacapita** [comment]
Even I am facing similar issue.

**Comment by raeesaa** [comment]
Even I am facing similar issue.

**Comment by jacobbubu** [comment]
Why close this issue? It's still happened in 1.1.3.

**Comment by banny310** [comment]
Still happens on 2.6.1. Why this is closed?
