### ISSUE TITLE
Configure amount of data in pm2 web?

### ISSUE THREAD

**Issue by solitud** [Unitech/pm2#1294]
I am using `pm2 web` to programmatically monitor the health of a nodejs server. Basically I am only interested to get info if the server is still running.

The problem with `pm2 web` is that the function is giving way too much info about the server to the public, even the email address of the git user, etc.

Is there a way to simply configure `pm2 web` to output just basic info?

**Comment by markthethomas** [comment]
I completely agree; I was thinking of using this as a simple health check in a service but there was way too much info exposed. I'd be happy to help with a feature along these lines if other people indicate a similar desire/need and it's something the maintainers feel would help pm2.

**Comment by aroach** [comment]
+1
