### ISSUE TITLE
executing arbitrary command instead of script file

### ISSUE THREAD

**Issue by kilianc** [Unitech/pm2#1297]
I have tried to play with it a little but with no luck

```
{
  "name": "rtail-server",
  "script": "rtail-server --web-port 9999 --udp-port 9090 --udp-host 0.0.0.0",
  "exec_interpreter": "bash",
  "exec_mode": "fork_mode"
}
```
I am using a `.json` file to declare the job and I always get 

```
[PM2][ERROR] script not found : ...
```

**Comment by jshkurti** [comment]
That's because `script` should be a path to your executable file.
https://github.com/Unitech/PM2/blob/master/ADVANCED_README.md#list-of-all-json-declaration-fields-avaibles

**Comment by kilianc** [comment]
@jshkurti yes I figured and I think I may have found a way:

```
{
  "name": "rtail-server",
  "script": "/bin/bash",
  "args": [
    "-c",
    "-o",
    "pipefail",
    "rtail-server --web-port 9999 --udp-port 9090 --udp-host 0.0.0.0"
  ],
  "env": {
    "DEBUG": "rtail:*"
  }
}
```

**Comment by jshkurti** [comment]
Gosh, that's ugly ^^
But smart :)

**Comment by kilianc** [comment]
I really hope it's not the only way :+1:

**Comment by ravi** [comment]
I had at some point submitted a PR for `exec_interpreter = none`. That doesn't help you in this case?

**Comment by jshkurti** [comment]
Well, why wouldn't you just use a .sh file ?

**Comment by kilianc** [comment]
Don't you think that a file for a oneliner is kinda overkill? Considering I have like 6 processes to run, it's 6 pm2 block + 6 files. SUPER UGLY.

**Comment by meteormanaged** [comment]
Any luck with this? Trying to get it in my environment.

**Comment by jsEveryDay** [comment]
@jshkurti You're the man!
I been looking for a solution for so long, didn't stumble upon this until I was searching for rTail
Tired of writing single liner bash scripts.
Je njish

Wondering if this will work with cron and cwd... will test it out.

**Comment by Unitech** [comment]
Documented here: http://pm2.keymetrics.io/docs/usage/process-management/#start-any-process-type

Closing as this issue has been fixed

**Comment by DrecDroid** [comment]
For those that stumbled upon this problem, and looking that is not well documented, you just need to set the `interpreter` option as `none`. For example:

```
module.exports = [{
    name: 'ngrok', // The name the process will have
    script: 'ngrok', //  The command you'll call
    interpreter: 'none', // This makes the magic
    args: [ // The command args
      'http',
      '--subdomain=my-subdomain',
      `--authtoken=${token}`,
      config.get('port').toString(),
    ]
  }]
```
