### ISSUE TITLE
Confusing docs about merge_logs option

### ISSUE THREAD

**Issue by kilianc** [Unitech/PM2#1299]
https://github.com/Unitech/PM2/blob/master/ADVANCED_README.md#raw-examples

> defaults to false. if true, it will merge stdout and stderr logs into the same file

>--merge-logs merge logs from different instances but keep error and out separated

**Comment by jshkurti** [comment]
You're absolutely right. Fixing this right away.

**Comment by jshkurti** [comment]
https://github.com/Unitech/PM2/commit/a15fa4457f0819db22e7c6188f725dfe38cea735
