### ISSUE TITLE
Can't supply command line arguments to script

### ISSUE THREAD

**Issue by Morriz** [Unitech/pm2#13]
Try:

pm2 start 'script.js -d 1'

and it crashes, showing a module not found error:

Error: Cannot find module '......./device-simulation.js -d 1'

**Comment by xieranmaya** [comment]
NOTICE that the arguments you supply will persist until you **delete** and restart the app:

`pm2 start app.js -- aa bb cc`
`pm2 restart app.js -- 11 22 33`

This will not work, you should do the following:

`pm2 delete app.js`
`pm2 start app.js -- 11 22 33`

**Comment by govo** [comment]
@xieranmaya Thank you!

**Comment by Unitech** [comment]
Now with PM2 > 1.1.x

this:

```
$ pm2 start app.js -- aa bb cc
$ pm2 restart app.js -- 11 22 33
```

works, but doing

```bash
$ pm2 restart app.js
```

Will still keep the latest arguments (11, 22, 33)

**Comment by xieranmaya** [comment]
@Unitech Great improve!

**Comment by martinjuhasz** [comment]
Am i missing something or is it not possible to run two processes with different arguments but the same script with this configuration?

**Comment by SonicReal** [comment]
> Now with PM2 > 1.1.x
> 
> this:
> 
> $ pm2 start app.js -- aa bb cc
> $ pm2 restart app.js -- 11 22 33
> works, but doing
> 
> $ pm2 restart app.js
> Will still keep the latest arguments (11, 22, 33)

Hello. I dont need to keep latest arguments. How can i "nullify" them?

**Comment by anoop-ananthan** [comment]
What is the way to run 
`pm2 start --env production --node-args  "DB_HOST=some.host.xyz DB_NAME=mybase DB_USER=heman DB_PASSWORD=Morning@r00t90"`
