### ISSUE TITLE
Round Robin Clustering Appears to Not Round Robin Under Certain Conditions

### ISSUE THREAD

**Issue by askhogan** [Unitech/pm2#1300]
This may be better posted in the native cluster module, however, I have not had time to look at the clustering layer code to see if it may be with PM2.  I have a 16 cluster on 0.12.3 that is not doing round robin correctly.  

![screen shot 2015-05-23 at 1 38 13 am](https://cloud.githubusercontent.com/assets/635449/7782741/7b99d622-00ec-11e5-83c7-aec8b19da610.png)

You may say, but how do you know?  There is a memory leak.  These boxes are such that they are stateless and doing same work.  The leak is 4x worse on some of the workers, and those workers are processing 4x the volume.  With round robin that shouldn't happen right?

**Comment by askhogan** [comment]
BTW if you haven't checked out Keymetrics yet, you should.  Their Dashboard is awesome!

**Comment by jshkurti** [comment]
I get these results with a basic http server and `-i 8`.
I used `ab -c 100 -n 10000`.

![round-robin](https://cloud.githubusercontent.com/assets/7647602/7797192/05663b86-02e9-11e5-81d8-e590c005114e.png)

**Comment by askhogan** [comment]
I agree it is a strange issue and may not be with pm2.  However, I would like to note a few differences in our comparisons.  

1) Your app was online for a few seconds, my app was online for 2 days.  
2) Your app is using 8 workers, my app was using 16.  

Once I restarted the app round robined correctly.  The post here is to ask why something like this would happen.

**Comment by jshkurti** [comment]
`The post here is to ask why something like this would happen.`
I appreciate the initiative :)
I happen to be kinda the curious type myself for things like this.
What I understand about cluster module load-balancing :
The load-balancing operates at a "request level".
It means that if you have 4 instances of a very simple tcp server listening on port 8080 and you manage to perform a `cat /dev/urandom | nc localhost 8080` there will be no load-balancing. Only your first instance will take all the load.

But, if you spam your server with hundreds of quick requests, then these requests will be load-balanced between the workers.

So, if you have 16 workers but 1 request any 10seconds for about 2 weeks (for example) chances are that only your first worker will treat those requests.

**Comment by jshkurti** [comment]
Here's another example, one of Keymetrics nodes running for 11 hours : 
![buckets](https://cloud.githubusercontent.com/assets/7647602/7800610/4ce78f58-0318-11e5-896c-a82a9e4e271a.png)

**Comment by askhogan** [comment]
Ah.  Interesting!  Ok that is what I was looking for.  So your worker 1 and 3 are serving more requests after 11 hours.  Where does this decision get made?  Just curious, because I saw a node core post where they said in .12 they changed to round-robin distribution.

**Comment by Unitech** [comment]
fixed in newer Node.js version (+4.0)
