### ISSUE TITLE
Notifying PM2 of process shutdown through Node's Domain error handling?

### ISSUE THREAD

**Issue by canebat** [Unitech/PM2#1303]
From the [Node docs](https://nodejs.org/api/domain.html), the domain that is being shutdown will notify the cluster master that it's shutting down with:

    var d = domain.create();
    d.on('error', function(er) {

        // ....

        // stop taking new requests.
        server.close();

        // Let the master know we're dead.  This will trigger a
        // 'disconnect' in the cluster master, and then it will fork
        // a new worker.
        cluster.worker.disconnect();
   
        // ....

    });

The cluster master then opens a new process now that the old one has shut down.

If I'm replacing Node's official cluster module in my code with **PM2**, how do I notify PM2 that a cluster worker is being shutdown by my domain?

**Comment by jshkurti** [comment]
Just use `process.exit()`, PM2 will receive both 'disconnect' and 'exit' events for that worker and will restart it :)

**Comment by michaelBenin** [comment]
I don't think just calling process.exit() suffices for a more robust application's needs.

Many people are using node processes with open connections that need to gracefully disconnect. 

That's great the pm2 will just restart it, but during a gracefulShutdown it would be more ideal for pm2 to send work to a process that is are not actively shutting down. 

I believe there is an api for process.send('online') within pm2, it would be great to let pm2 know a process is in the middle of shutting down as well. 

Can we reopen this issue? 

Thank you.
