### ISSUE TITLE
ecosystem.json/json5 inconsistency

### ISSUE THREAD

**Issue by metalim** [Unitech/pm2#1304]
`pm2 ecosystem` generates *ecosystem.json5*. But `pm2 deploy dev` is looking by default for *ecosystem.json*. IMO defaults should not be different across commands.
Patching CLI.js [here](https://github.com/Unitech/PM2/blob/master/lib/CLI.js#L211) to *.json5* solved the issue for me. Until next update.

**Comment by Unitech** [comment]
Feel free to send us a small PR :muscle: 

Thanks

**Comment by Unitech** [comment]
pm2 ecosystem now generates config.js file and pm2-deploy check for 'ecosystem.json', 'ecosystem.json5', 'ecosystem.config.js'
