### ISSUE TITLE
How can I stop link with Keymetrics

### ISSUE THREAD

**Issue by jaydenlin** [Unitech/PM2#1305]
Is there any command to stop link with Keymetrics?
Thank you.

**Comment by jshkurti** [comment]
Sure, `pm2 interact stop` will stop the sync with Keymetrics until next pm2 reboot or until you perform a `pm2 interact start`.
`pm2 interact delete` will completely remove the interaction by deleting the file `~/.pm2/agent.json`.
In this case if you want to connect again you will have to specify the public and private key again.

**Comment by jkiss** [comment]
cool

**Comment by soichih** [comment]
Thanks @jshkurti

**Comment by deju** [comment]
or use `pm2 link delete`
