### ISSUE TITLE
delay before auto restart

### ISSUE THREAD

**Issue by rbarkas** [Unitech/PM2#1307]
Enhancement request:

Add an option to the JSON app declarations that specifies a delay (in seconds) before a restart attempt is invoked.

Use case:
A task fails because of some external reason.  The ability to specify a restart delay would allow the external cause to be remedied before the task restarts.

Without this ability, a task may be restarted without success a number of times before the external cause is remedied

**Comment by jorge-d** [comment]
Closing in favor of #498

**Comment by jshkurti** [comment]
Here we go.
`pm2 start app.js --restart-delay 4000` (delay is in milliseconds)
or in JSON declaration:
```json
  "restart_delay" : "4000"
```

Avaible on #development for now, soon to be published :)

https://github.com/Unitech/PM2/commit/12261c6b4ae17e69bc0721c9a68167731b26ba4b

**Comment by michahell** [comment]
is the restart delay feature on stable branch / released already?

**Comment by soyuka** [comment]
Yup.
