### ISSUE TITLE
Remote log aggregation?

### ISSUE THREAD

**Issue by tkambler** [Unitech/PM2#1308]
I'm just curious as to whether you've given any thought to implementing remote log aggregation within PM2? The tool currently provides support for remotely accessing system / process information via the `pm2-http-interface` application that is launched by the `web` command. This seems like it could be a natural extension of that for people that don't want to devote separate tooling for that (winston, etc...).

**Comment by Unitech** [comment]
You can get all logs from application runned by PM2 with the [bus system](https://github.com/Unitech/PM2/blob/master/doc/PROGRAMMATIC.md#bus-system---event-monitoring)

**Comment by jshkurti** [comment]
```js
var pm2 = require('pm2');                                                                                                   
                                                                                                                            
pm2.launchBus(function(err, bus) {                                                                                          
  bus.on('log:*', function(type, data) {                                                                                    
    console.log(data);                                                                                                      
  });                                                                                                                       
}); 
```
