### ISSUE TITLE
[URGENT] HUGH 30GB pm2.log file

### ISSUE THREAD

**Issue by MrBokeh** [Unitech/PM2#1309]
30GB pm2.log file, what happen to the pm2 log file? The server was only up for a week and the log file is almost 30GB big and my server crashes. How can I disable the log file complete to avoid this problem occur again?

**Comment by jorge-d** [comment]
Have you tried #866?

**Comment by hugcoday** [comment]
I think should be to split log, one day  one file,
It can be deleted by shell command.

**Comment by Unitech** [comment]
```
pm2 flush
```

**Comment by MrBokeh** [comment]
I have to delete it through FTP because I cannot do anything on the VPS server via command line. The flush was not working if the disk is run out of space. I don't want to open a 30Gb log file either so I have just deleted it. I wonder if there's a way to just disable the pm2 logging mechanism completely since I don't really need it in some cases, imagine if the production server have this problem, you will lose all the customers... I was using -i 0 cluster mode but now swapped back to fork mode and keep my fingers crossed it won't happen again. I suspect it's the cluster cannot find the matching port and keep generating the errors to the log file. Because on the second day after I deleted the log file I  have seen this errors many times:
Error: bind EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at cb (net.js:1195:33)
    at rr (cluster.js:592:14)
    at Worker.<anonymous> (cluster.js:563:9)
    at process.<anonymous> (cluster.js:692:8)
    at process.emit (events.js:129:20)
    at handleMessage (child_process.js:324:10)
    at Pipe.channel.onread (child_process.js:352:11)

**Comment by jshkurti** [comment]
You can now install the module pm2-logrotate `pm2 install pm2-logrotate` which will automatically rotate logs for each application running with PM2 including PM2 logs itself.

See https://www.npmjs.com/package/pm2-logrotate#configure for more info.
