### ISSUE TITLE
logs diplayed twice for merged stderr and stdout logs

### ISSUE THREAD

**Issue by nebulade** [Unitech/pm2#1310]
As noted in https://github.com/Unitech/PM2/blob/master/ADVANCED_README.md#json--programmatic I want to have stderr and stdout logs in the same file. This works just fine, however `pm2 logs` would always display the same logs twice for (out) and again for (err).

I could not find a commandline flag to suppress either one of them, or possibly if the two `error_file` and `out_file` correspond to the same file, pm2 logs could be smart enough to only display once?

**Comment by gramakri** [comment]
+1

**Comment by vmarchaud** [comment]
By default we will stay like this, since pm2 logs is mainly used in development mode, we think that by default it should be differentiated.
