### ISSUE TITLE
PM2 not Starting?

### ISSUE THREAD

**Issue by jonrichings** [Unitech/pm2#1316]
Probably just a noob mistake but I've followed these instructions (http://nodered.org/docs/getting-started/running.html#starting-node-red-on-boot) to the letter on a Raspberry Pi 2  but PM2 just doesn't start up, and then obviously neither does node-red.  Also, if I manually start PM2, the node-red still doesn't start.  Yes, I've done the pm2 save, pm2 startup, all according to the instructions.  Strangely when I did all this on an RPi 1 it all worked like a charm.  Any ideas?

**Comment by GlennGeenen** [comment]
Did every step succeed? You need permissions for startup so you should run `sudo pm2 startup`.

**Comment by jonrichings** [comment]
Yep, tried everything with and without sudo.  No errors reported.  dump.pm2 is there and references node-red (can't tell if the whole of dump.pm2 is correct though).  Weird huh?

**Comment by jonrichings** [comment]
Still trying to figure this out.  I've installed on clean setups a couple of dozen times with various simple variations, all get the same result: PM2 does not auto-start.  Manually starting PM2 is fine but does not start the app that was saved.  PM2 appears to be working in every other way.  Would uploading my dump.pm2 and pm2-init.sh help anybody help me?

**Comment by Unitech** [comment]
Have you tried with `pm2 startup systemd` ?

**Comment by jonrichings** [comment]
Finally got around to trying it.  Got this:

*pi@raspberrypi ~ $ pm2 startup systemd*
*[PM2] You have to run this command as root. Execute the following command:*
*      sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u pi*
*pi@raspberrypi ~ $ sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u pi*
*[PM2] Spawning PM2 daemon*
*[PM2] PM2 Successfully daemonized*
*[PM2] Generating system init script in /etc/systemd/system/pm2.service*
*[PM2] Making script booting at startup...*
*[PM2] -systemd- Using the command:*
*      su -c "pm2 dump && pm2 kill && systemctl daemon-reload && systemctl
enable                     pm2 && systemctl start pm2"*
*Command failed: [PM2][WARN] No process found*
*bash: systemctl: command not found*

*----- Are you sure you use the right platform command line option ? centos
/ red                    hat, amazon, ubuntu, gentoo, systemd or darwin?*
*pi@raspberrypi ~ $*

On the node-red site though a clever chap suggesting editing pm2-init.sh to
say:

export PM2_HOME="/root/pi/.pm2"
instead of
export PM2_HOME="/root/.pm2"

And that seems to do the trick.

Jon Richings | Original Design & Development | 801-704-9166 | *www.anoddco.com
<http://www.anoddco.com>*

This email and it's attachments may be confidential and are intended solely
for the use of the individual to whom it it addressed.   If you are not the
intended recipient of this email and it's attachments, you must take no
action based upon them, nor must you copy or show them to anyone.



Please contact the sender if you believe you have received this email in
error.

**Comment by elmedico27** [comment]
Heh, I ran into the same issue and it looks like the original node-red instructions you linked to were updated with the following, which worked for me:


*Temporary Note:* There's an [open issue](https://github.com/Unitech/PM2/issues/1321) on PM2 on GitHub which highlights an issue that has been introduced recently. Linux users need to manually edit the generated `/etc/init.d/pm2-init.sh` file and replace
```
export PM2_HOME="/root/.pm2"
```
to point at the correct directory, which would be like:
```
export PM2_HOME="/home/{youruser}/.pm2"
```

**Comment by NoiseEee** [comment]
The solution by GlennGeenen worked for me; sudo everything.  Takes less than a minute after server reboot, and all my node scripts are up and running.

**Comment by mastix** [comment]
Hey guys,

autostart does not work here... I've tried (almost) everything...

Machine: Raspberry 2 (Raspbian Jessie)

This is what I've ended up with:

Installed pm2
```$ npm install -g pm2```

Ran install script as pi user
```
$ sudo pm2 startup raspberry -u pi
[PM2] Generating system init script in /etc/init.d/pm2-init.sh
[PM2] Making script booting at startup...
[PM2] -raspberry- Using the command:
  su -c "chmod +x /etc/init.d/pm2-init.sh && update-rc.d pm2-init.sh defaults"
[PM2] Done.
```
As you've mentioned, the script refers to the wrong .pm2 folder (looks in the root folder, not the user's folder), so I changed that
```$ sudo vi /etc/init.d/pm2-init.sh```
Changed ```export PM2_HOME="/root/.pm2"``` to ```export PM2_HOME="/home/pi/.pm2"```

Went into my project's folder
```$ cd /opt/mycoolnodeproject```

Started my node project with pm2
```$ pm2 start server.js -x --name "cool-node-project"```

Saved active processes for restart
```$ pm2 save```

So now the server is up and running and works fine... until I reboot! I thought that pm2 would autostart my node application, but for some reason it doesn't... :( No chance...

Any idea what the problem might be?

Btw: I've also tried to call the startup cmd like this ```sudo env PATH=$PATH:/usr/local/bin pm2 startup raspberry -u pi```, but that didn't work either.

Regards,

Sascha

**Comment by jefftimesten** [comment]
I'm also having this problem, even after the fix in /etc/init.d/pm2-init.sh 
I'm on raspberry pi.

**Comment by elmedico27** [comment]
I was just about to post my whole pm2-init.sh here -- glad you all got it figured out.  And thanks for alerting me to Raspbian Jessie, I hadn't realized there was a new version!

**Comment by rictorres** [comment]
I had the problems mentioned here where PM2 was running as `root` and `deploy` users.

The fix from @elmedico27 worked fine :)

Thanks!

**Comment by faizalpribadi** [comment]
Thanks @elmedico27 , i think this issues has solved , yay :+1:

**Comment by tacoben** [comment]
im not sure which fix worked for me - but we tried teh fix from @elmedico27 and a fix in another bug report that set the .pm2/dump.pm2 to immutable:

chattr +i /home/<user>/.pm2/dump.pm2

it seems that we need to do both for pm2 to survive a restart.  yeah for the internet!

**Comment by Unitech** [comment]
Will be fixed on the next PM2 release #1035

**Comment by rictorres** [comment]
:+1:

**Comment by MikhaelGerbet** [comment]
In my case, for this issue when i want start a script whith PM2 as `deploy` user : 

As root 

```npm uninstall pm2```

As deploy (`su deploy`)

```sudo npm i -g pm2```

End now, deploy can use PM2.
 
Enjoy :)

**Comment by sandyfox** [comment]
I had this issue when the disk was 100% full. Had to clear the logs to start the pm2 as non root user and worked for me.
