### ISSUE TITLE
Support bunyan JSON log format

### ISSUE THREAD

**Issue by andrewrothman** [Unitech/PM2#1318]
Allow for pretty printing of all JSON logs (and use conventions in the bunyan format to make log output even better). This should be optional.

An example of this is that pm2 currently outputs:

    my_app-1 (out): {"cool_number": 42, "other_information": "I'm bad at writing examples."}

supporting JSON message pretty printing would allow for something like this:

    my_app-1 (out):
        * cool_number: 42
        * other_information: I'm bad at writing examples.

Supporting the bunyan format would take a message like this...

    my_app-1 (out): {"name":"my_app","hostname":"foobar","pid":12345,"level":30,"component":"http","msg":"Hello, world!","time":"2015-05-28T22:14:18.453Z", "custom_field": "hi there"}

and turn it into this much more readable string:

    my_app-1/http @ 5/28/2015 (out): Hello, world!
        * custom_field: "hi there"

There's some redundant information in there that we can get rid of when pretty printing. Fields like "name" (if it's different than the name PM2 has registered), "pid", and "hostname". I think level is also probably unnecessary when pretty printing.

**Comment by neeharv** [comment]
+1

**Comment by neeharv** [comment]
I'd like to help on this particular feature, since it's very useful to our setup. Could anyone give me some pointers as to where to start for this?

**Comment by gpit2286** [comment]
So here's a thought.  I think that as opposed to building the bunyan processor into the porject, we should just make it parse the log file properly so that the bunyan CLI can read it.  Something like this? 

    pm2 logs api | perl -pi -e 's/.*(?={)//'

**Comment by gpit2286** [comment]
Hey @andrewrothman and @neeharv.  I was looking at the source code for this and I found that logs supports a --raw tag that will output just the JSON which you can pipe to bunyan.  Do we really need anything beyond that? 

`pm2 logs --raw | bunyan`

**Comment by soyuka** [comment]
Indeed, see #1201 #1189 #709

`pm2 logs --raw | bunyan` should do the work :)

**Comment by neeharv** [comment]
Aha! That does the trick. Thank you so much @gpit2286 :beers:
