### ISSUE TITLE
Problems with `pm2 startup` on ubuntu 15.04

### ISSUE THREAD

**Issue by michielbdejong** [Unitech/pm2#1319]
Looks like on Ubuntu 15.04 (first Ubuntu version running systemd instead of upstart by default), you have to do `pm2 startup systemd` explicitly.

In my case, just `pm2 startup` did not seem to make my processes start at startup.

**Comment by michielbdejong** [comment]
Ref: https://wiki.ubuntu.com/VividVervet/ReleaseNotes/#Boot_and_service_management

**Comment by Unitech** [comment]
Closing in favor of #2559 

To try the new startup system:

```bash
$ npm install Unitech/pm2#development -g
$ pm2 update
```

```bash
$ pm2 startup     # Then copy / paste the command displayed
$ pm2 unstartup
```
