### ISSUE TITLE
Log separate from date

### ISSUE THREAD

**Issue by hugcoday** [Unitech/PM2#1322]
Can you separate log to many files,not in one file. 

It can be one day one file. Like tomcat logs

Always, Can it limit log file size，It can be config, like 50M . 

The time is long, the log file is very big

**Comment by jshkurti** [comment]
You can now install the module pm2-logrotate `pm2 install pm2-logrotate` which will automatically rotate logs for each application running with PM2 including PM2 logs itself.

See https://www.npmjs.com/package/pm2-logrotate#configure for more info.
