### ISSUE TITLE
Path relative when providing environment fails on ecosystem.json

### ISSUE THREAD

**Issue by deathlord87** [Unitech/PM2#1323]
The ~ folder doesn't get resolved and just adds that to the directory path
```
    "apps": [
        {
            "name": "API",
            "script": "server.js",
            "merge_logs" : true,
            "cwd": ".",
            "exec_interpreter" : "node",
            "env": {
                "APP_HOME": "~/Env/folders"
            },
            "env_production": {
                "NODE_ENV": "production"
            },
            "watch" : false,
            "exec_mode"  : "fork_mode"
        }
    ],
```

It works if I give 
``` APP_HOME=~/Env/folders/ iojs server.js ```
But doesn't work if I provide the ecosystem.json and start the app using the below command
``` pm2 startOrRestart ecosystem.json --env production ```

**Comment by jshkurti** [comment]
Because your terminal is smart, it automatically converts it to an absolute path.

![meter1](https://cloud.githubusercontent.com/assets/7647602/7914472/7e9a1476-0877-11e5-80ca-eba1cc02ccf0.png)

**Comment by deathlord87** [comment]
Why can the same thing work with pm2's ecosystem.json it can internally do the same thing right ?
