### ISSUE TITLE
it meet error,Some processes do not update code after changing the code

### ISSUE THREAD

**Issue by qqqzhch** [Unitech/PM2#1324]
i have use pm2 delete ***
                  pm2 kill 
                  pm2 start *******
but 
Some processes do not update code after changing the code
the page  is  diff  in pc and mobile 
This page is not the same, especially the paging code. 
  http://www.unknownerror.org/opensource  
what can id do?

**Comment by jshkurti** [comment]
Are you talking about the `--watch` feature ?
If you start an app like this `pm2 start app.js --watch` it will restart it every time a change is detected on folders and sub-folders starting from the app cwd.

**Comment by Unitech** [comment]
For sure the code is updated on every `pm2 restart <app>`, maybe it an issue with your browser of http server, feel free to re open the issue if you encounter any problem
