### ISSUE TITLE
PM2 gets 'stuck' sometimes

### ISSUE THREAD

**Issue by btmdave** [Unitech/PM2#1326]
We have a few express apps monitored by pm2 and one of them seems to get 'hung' fairly often.  Meaning, it's still listed in PM2, everything appears to be fine, no errors in the apps logs or in `~/.pm2/pm2.log`, but it just stops becoming available via port 80.   

It's just a simple script that basically is running an ffmpeg flv stream to the response, so route request times can be long, this is the only variance from other apps running on pm2 just fine.

Any ideas why it would just 'hang' and the only thing that seems to fix it is doing `/etc/init.d/pm2-init.sh restart`

**Comment by jshkurti** [comment]
Is the cpu usage high ?
Are you sure the issue comes from PM2 ?

**Comment by btmdave** [comment]
The CPU usage does get high.  But we also have other processes on the same server being managed by PM2 and those are still working.

**Comment by Unitech** [comment]
Bug reproduced - inspecting

**Comment by Unitech** [comment]
You should upgrade to the latest version of PM2, tell us if it reduced the memory usage,

Thanks

**Comment by btmdave** [comment]
Great, updated to `0.14.0`, will keep an eye on it.

**Comment by Unitech** [comment]
Feel free to install the module to monitor PM2: 

```
$ pm2 install pm2-probe
```

**Comment by btmdave** [comment]
I've installed this.  It looks like this will write to an error and out log? (`pm2 logs pm2-probe`)  Nothing available yet.

**Comment by Unitech** [comment]
Fixed starting 0.14

**Comment by guypaskar** [comment]
I'm having the same issue here. Using version 1.1.3 and node v5.6.0.
I have 4 processes in cluster mode where sometimes one of them is going to 100% cpu and is stuck there. 
Interestingly when I do pm2 logs [stuck_id] I see logs from recent time they are not continuous but if I exit and enter the log again I see that something happened. However, the app does not really work (if I stop all other processes I will not be able to use my web app at all)

Any clue?
