### ISSUE TITLE
PM2 v0.12.9: Go

### ISSUE THREAD

**Issue by struCoder** [Unitech/PM2#1327]
Recently, i found that in my ubuntu vps pm2 has a process name `PM2 v0.12.9: Go`, it taked up `15% mem` what's that, i searched it in google, but i have not found.
![qq 20150603093540](https://cloud.githubusercontent.com/assets/6498477/7950941/f4946106-09d3-11e5-9c57-84dac441382c.png)

**Comment by jshkurti** [comment]
It's the PM2 daemon.

**Comment by struCoder** [comment]
okay ：)
