### ISSUE TITLE
pm2 pullAndRestart

### ISSUE THREAD

**Issue by codydaig** [Unitech/PM2#1328]
No matter where or in how many places I put:
"post_update": ["npm install"]

It never runs. Any ideas to what might be going wrong?

I've put that in the app.json file that the application launches form as well as in the package.json file. I'm using the Pull from keymetrics which executes a "pullAndRestart"

**Comment by jorge-d** [comment]
Did you manage to make it work?

**Comment by codydaig** [comment]
Yup. Apparently if you start an app from "somename.json" it doesn't look in that file for the post update scripts. You have to have those scripts in the package.json, process.json, or ecosystem.json.
