### ISSUE TITLE
pm2 -h is having troubles

### ISSUE THREAD

**Issue by orykami** [Unitech/PM2#1329]
Hi !
I'vo got troubles with pm -h with non-root user, which having Error : connect EACCES.
You can find some screens below.
![capture d ecran 2015-06-03 a 14 53 47](https://cloud.githubusercontent.com/assets/3338393/7960370/6280ac7a-0a00-11e5-819c-d7d3efe49238.png)

**Comment by Unitech** [comment]
It means that you launched PM2 with root and your are trying to act on it with another user.
Start and use PM2 with the same user

Or set the right on unix domain files:

```bash
$ sudo chown $MY_USER /root/.pm2/*.sock 
```
