### ISSUE TITLE
Feature request: Renaming Apps

### ISSUE THREAD

**Issue by spruce** [Unitech/pm2#133]
Hey,
I think it would be pretty neat to have a action to renaming processes by there ID to something else

**Comment by t3chguy** [comment]
Maybe have default App name be the name of the folder if the file being run is app.js rather than "app" or offer a built-in method of renaming entries without losing the data related to the old name of the application.

**Comment by taneltm** [comment]
I'm using pm2 to manage my development environment and I also wish for this feature...
Example:
```
cd project1
pm2 http-server -- -c-1 build/www
pm2 proxy -n "backend-proxy"

(a few days later, different project with similar setup)
pm2 rename http-server -n project1-http-server
pm2 rename backend-proxy -n project1-backend-proxy

cd project2
pm2 http-server -n project2-http-proxy -- -c-1 build/www
pm2 proxy -n "project2-backend-proxy"
```

Right now, instead of `pm2 rename ,,,`, I would have delete the existing processes and re-create them, which takes more time.

**Comment by krokofant** [comment]
This would be nice to have. Deleting the app and starting it again removes the restart stats and creates a new id.

**Comment by Weyland** [comment]
I agree. Just ran into the same problem. I would like to have it remain the same process id.

**Comment by feychenie** [comment]
Same here

**Comment by estliberitas** [comment]
@Unitech wrote:
> you can do pm2 delete myoldappname ; pm2 start app.js --name newname

Talking about 0-downtime it would mean not 0-downtime. :-) From the other point, renaming apps on production is not something we do everyday, right (we do not name apps by day name, for example :smile: )? So I think this feature is not something super-important.

Other important feature would be taking into account changed JSON declaration during reload / gracefulReload

**Comment by Unitech** [comment]
On next release 1.0.3: 

```
$ pm2 restart app --name "new-name"
```

**Comment by Unitech** [comment]
Update available (PM2@1.1.1 - latest stable):

```
$ npm install pm2@latest -g
$ pm2 update
```

Please re-open this issue if you notice any problem,

**Comment by peteroid** [comment]
The "restart" command above doesn't work on my pm2(ver 2.2.3). I have to rename the app with this command.
```
pm2 restart app --name "new-name" --update-env
```

**Comment by geeksamu** [comment]
`pm2 restart id --name newName`
It's the same as the above answers.
You can use the ID of the app to rename it
