### ISSUE TITLE
PM2 killed my process

### ISSUE THREAD

**Issue by alexzhang2015** [Unitech/PM2#1330]
$ pm2 logs
[PM2] Starting streaming logs for [all] process
PM2: 2015-06-03 06:49:38: Starting execution sequence in -fork mode- for app name:server id:0
PM2: 2015-06-03 06:49:38: App name:server id:0 online
PM2: 2015-06-03 10:49:58: Change detected for app name: server - restarting
PM2: 2015-06-03 10:49:58: Stopping app:server id:0
PM2: 2015-06-03 10:49:58: App name:server id:0 exited with code SIGTERM
PM2: 2015-06-03 10:49:58: Process with pid 32035 killed
PM2: 2015-06-03 10:49:58: Starting execution sequence in -fork mode- for app name:server id:0
PM2: 2015-06-03 10:49:58: App name:server id:0 online
PM2: 2015-06-03 13:11:53: Change detected for app name: server - restarting
PM2: 2015-06-03 13:11:53: Stopping app:server id:0
PM2: 2015-06-03 13:11:53: App name:server id:0 exited with code SIGTERM
PM2: 2015-06-03 13:11:53: Process with pid 28243 killed
PM2: 2015-06-03 13:11:53: Starting execution sequence in -fork mode- for app name:server id:0
PM2: 2015-06-03 13:11:53: App name:server id:0 online
PM2: 2015-06-03 13:20:31: Change detected for app name: server - restarting
PM2: 2015-06-03 13:20:31: Stopping app:server id:0
PM2: 2015-06-03 13:20:31: App name:server id:0 exited with code SIGTERM
PM2: 2015-06-03 13:20:31: Process with pid 12797 killed
PM2: 2015-06-03 13:20:31: Starting execution sequence in -fork mode- for app name:server id:0
PM2: 2015-06-03 13:20:31: App name:server id:0 online

i can't find any error can up with my node.js application, PM2 just restart it many time a day, what happened?

Thanks

**Comment by jshkurti** [comment]
Do you have `--watch` enabled ?

**Comment by alexzhang2015** [comment]
i find the issue, because the --watch and local access.log.
access.log would trigger the restart.

Thanks
