### ISSUE TITLE
restart instead of start

### ISSUE THREAD

**Issue by btmdave** [Unitech/PM2#1333]
Is there anyway natively in pm2 to perform a `restart` or `start` if the app is not currently running?

**Comment by jshkurti** [comment]
What do you mean ?

**Comment by btmdave** [comment]
For example, doing `pm2 restart app.js --name app` if this isn't running then you get `Process app.js not found`.  Would there be a way in that case, to fallback to `start`? Then in future attempts, it would restart, since it's found.

**Comment by Unitech** [comment]
would be nice to auto detect stopped processes when using the start command:

```
$ pm2 start app.js --name "app"
$ pm2 stop app
$ pm2 start app   # detect that the app is stopped, so restart it
```

**Comment by shamasis** [comment]
Curious, why will `pm2 startOrRestart` not work for this case @Unitech?

**Comment by btmdave** [comment]
`startOrRestart` only works when using the JSON config, i.e., `pm2 startOrRestart app.js` doesn't work.

**Comment by shamasis** [comment]
Then this could perhaps become a feature request. ;-)

`pm2 restart` starting a not-started app could break existing use-cases where failure to restart is used as any form of check. Also, one valid requirement could be to only restart and not start (the present behaviour)?

**Comment by btmdave** [comment]
The command could probably be the same as for the JSON config `startOrRestart`, as oppose to adding the functionality to `restart`.

**Comment by Unitech** [comment]
Will be available in the next release!

**Comment by btmdave** [comment]
Awesome! Thank you

**Comment by btmdave** [comment]
@jshkurti Should `pm2 startOrRestart app.js` work now? I tried with `0.14.3` but get:

```
/usr/lib/node_modules/pm2/lib/CLI.js:2300
    return vm.runInNewContext(code, sandbox, filename);
              ^
SyntaxError: Unexpected token var
```

**Comment by jshkurti** [comment]
It's normal, `startOrRestart` is only for .json files.
What changed here is the following :
`pm2 start app.js --name "API"`
`pm2 start API` <- now restarts API instead of throwing an error

**Comment by btmdave** [comment]
Ah, so there's no way to do startOrRestart for non-json files?  The use case is when deploying with git using post-receive hooks, you have to issue `pm2 kill` before doing `pm2 start`, so you lose the restart functionality.
