### ISSUE TITLE
Error: connect EACCES - Brand new ubuntu install - Non-root user

### ISSUE THREAD

**Issue by noducks** [Unitech/PM2#1336]
Am getting this issue on a brand new server install. Created a new user, and installed everything including pm2 with that user. npm install works ok, but then it breaks. Any suggestions?

     ➜  test git:(develop) pm2 deploy production 
     --> Deploying to production environment
     --> on host xx.xx.xx.xx -p xxxx
       ○ deploying
       ○ hook pre-deploy
       ○ fetching updates
     Fetching origin
     From xxxxxx
        06c8208..eff846c  develop    -> origin/develop
       ○ resetting HEAD to origin/develop
     HEAD is now at eff846c test
       ○ executing post-deploy `npm install && pm2 startOrRestart ecosystem.json --env production`
     
     events.js:72
             throw er; // Unhandled 'error' event
                   ^
     Error: connect EACCES
         at errnoException (net.js:901:11)
         at Object.afterConnect [as oncomplete] (net.js:892:19)
     
       post-deploy hook failed
     
     Deploy failed

Running this command with sudo works when logged directly into the server, but not if I add sudo to the ecosystem.json script.

`sudo pm2 startOrRestart ecosystem.json --env production`

**Comment by Unitech** [comment]
Do not run PM2 with the root user, if you really want to bind port 0-1024 please use [authbind](https://github.com/Unitech/PM2/blob/master/ADVANCED_README.md#allow-pm2-to-bind-applications-on-ports-80443-without-root)

**Comment by noducks** [comment]
Thanks for the response. I didn't use the root user. I had created a new non-root user, and installed node, pm2, etc with that user using sudo.
