### ISSUE TITLE
pm2 0.12.16 does not connect to keymetrics

### ISSUE THREAD

**Issue by grrava** [Unitech/PM2#1337]
Hello,

The keymetrics website indicated my pm2 processes as offline and that it had an outdated version of pm2 (0.12.15) so I updated to 0.12.16 succesfully, did the pm2 updatePM2 but but I can't link these processes to the website anymore. Underneath is the output, but nothing changes on the website.

The same process worked fine for 0.12.15

Many thanks for any help.

~$ pm2 updatePM2
Be sure to have the latest version by doing `npm install pm2@latest -g` before doing this procedure.
[PM2] Stopping PM2...
[PM2] deleteProcessId process id 0
[PM2] deleteProcessId process id 1
[PM2] All processes have been stopped and deleted
[PM2] PM2 stopped
[Keymetrics.io] Using (Public key: xxxx) (Private key: xxxx)
[Keymetrics.io] [Agent updated] Agent ACTIVE - Web Access: https://app.keymetrics.io/
Process /var/node/dev/api/server.js launched
Process /var/node/staging/api/server.js launched
>>>>>>>>>> PM2 updated
● Agent online - public key: g6t208lvp41nx73 - machine name: api-staging - Web access: https://app.keymetrics.io/
┌──────────┬────┬──────┬──────┬────────┬─────────┬────────┬─────────────┬──────────┐
│ App name │ id │ mode │ pid  │ status │ restart │ uptime │ memory      │ watching │
├──────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────────────┼──────────┤
│ dev      │ 0  │ fork │ 8069 │ online │ 0       │ 0s     │ 11.074 MB   │ disabled │
│ staging  │ 1  │ fork │ 8071 │ online │ 0       │ 0s     │ 8.098 MB    │ disabled │
└──────────┴────┴──────┴──────┴────────┴─────────┴────────┴─────────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app

Regards,
Alex

**Comment by jshkurti** [comment]
Hmm, try again `pm2 kill` `pm2 start` `pm2 link stop` `pm2 link start`.
If it still doesn't work tell me the name of your bucket I'm going to have a look at it.

**Comment by jshkurti** [comment]
And congrats for the issue number 1337 :P

**Comment by Unitech** [comment]
yes it works now, we were in maintenance mode, sorry for that, closing

**Comment by grrava** [comment]
Allright, it works now indeed, glad it was only that. I really love the tool, I'll probably become a paying customer since I want it for all my apps. Keep up the good work!

**Comment by Unitech** [comment]
thanks! we are working hard to provide the best monitoring tool for nodejs!
