### ISSUE TITLE
Symlink change not detected

### ISSUE THREAD

**Issue by pfazzino** [Unitech/PM2#1340]
Clean ubuntu 14.04 vagrant machine,  node v0.12.4, pm2 0.12.15

PM2 json setup as follows -

```javascript
{
    "apps": [
        {
            "name"           : "pm2-test",
            "script"         : "pm2-test.js",
            "watch"          : "/home/nodejsuser/pm2-test",
            "watch_options"  : {
                "followSymlinks": true
            },
            "cwd"            : "/home/nodejsuser/pm2-test",
        }
    ]
}
```

pm2-test is a symlink to pm2-test1 or pm2-test2 with a basic node script in each. Running the above with the symlink intiially pointing to pm2-test1, if I then move the symlink to pm2-test2 the watch reload never triggers. If I then touch pm2-test1/pm2-test.js the reload kicks in and I see the version from pm2-test2. Swinging the symlink back to pm2-test1, again nothing happens, I still have to touch pm2-test1/pm2-test.js to trigger the reload.

Editing either pm2-test.js file directly works fine but this is no good in a deployment environment where code is pushed to versioned deployment locations and then the production symlink is re-directed to the new release so this feels like a pretty standard scenario.

**followSymlinks** has no effect on this behaviour.

**Comment by soyuka** [comment]
Did you try `followSymlinks: false`? 

The chokidar README states:

>followSymlinks (default: true). When false, only the symlinks themselves will be watched for changes instead of following the link references and bubbling events through the link's path.

https://github.com/paulmillr/chokidar

I'll test this tonight (GMT+1), could you please give me your `bash` procedure to test this? Something like :

```
ln -s target mylink1
touch mylink1/file
pm2 start --watch mylink1/file.js
#etc.
```

Thanks!

**Comment by pfazzino** [comment]
Yes, followSymlinks has no effect. That would be fine if the symlink pointed to the js file directly but in this case the symlink points to the parent folder.

To test:

create pm2-test1 & pm2-test2 folders with a basic script, e.g.

```javascript
var http = require('http');

var server = http.createServer(function (request, response) {
    response.writeHead(200, {"Content-Type": "text/plain"});
    response.end("Test 1\n");
});

server.listen(3000);
```
with a different variation in both folders.

ln -nfs pm2-test1/ pm2-test
pm2 start pm2.json (see example above)

ln -nfs pm2-test2/ pm2-test

# no restart detected
touch pm2-test1/pm2-test.js
#restart detected

ln -nfs pm2-test1/ pm2-test

# no restart detected
touch pm2-test1/pm2-test.js
#restart detected

HTH

Paul

**Comment by soyuka** [comment]
Ok, so if I understand you want it to restart when a link changes?

It's working just fine here, this is my configuration to test:

```
{
    "apps": [
        {
            "name"           : "pm2-test",
            "script"         : "./linktobewatched/server.js", //relative to cwd
            "watch"          : ["./"],
            "watch_options"  : {
                "followSymlinks": false
            },
            "cwd"            : "/home/user/sites/forks/testwatchsym" //absolute path to cwd
        }
    ]
}
```

Then I have:
```

❯ ls -l
total 12
drwxr-xr-x 2 user user 4096 juin  10 12:24 test2
drwxr-xr-x 2 user user 4096 juin  10 12:21 test1
-rw-r--r-- 1 user user  349 juin  10 12:24 pm2.json
lrwxrwxrwx 1 user user    6 juin  10 12:24 linktobewatched -> test2/
```

A file `server.js` is in both directories.

When I change the link (ie `ln -nfs test2/ linktobewatched`) pm2 gets restarted. When I touch a file in a directory it's also restarting.

I'm watching live changes on pm2 with the command `DEBUG="pm2:*" pm2 start pm2.json --no-daemon` (Ctrl-C to quit).

**Comment by pfazzino** [comment]
Thanks Antoine

That does indeed work for me. My production setup is slightly more complex with cluster mode enabled and slightly different paths. I can still repro the problem there even though your above example works fine for me. Let me do some more digging and see if I can understand why my other setup fails to restart when I switch symlinks.

Regards

Paul

**Comment by pfazzino** [comment]
I've dug into why my production setup fails to detect the symlink changes and it's due to another symlink level underneath the first so my first example was overly simplistic. For example, given the setup below

```
mkdir pm2-test
mkdir test1
mkdir test2
ln -nfs pm2-test/ pm2-link
ln -nfs test1/ pm2-test/test
```

So ./pm2-link is a symlink with an additional ./pm2-link/test symlink underneath. Copy the test script into folders test1 & test2. Using pm2 setup as follows

```
{
    "apps": [
        {
            "name"           : "pm2-test",
            "script"         : "./pm2-link/test/pm2-test.js",
            "watch"          : "./pm2-link",
            "watch_options"  : {
                "followSymlinks": true
            },
            "cwd"            : "/home/nodejsuser",
        }
    ]
}
```

The above fails if I cd pm2-link && ln -nfs ../test2/ test. If I change the watch entry to be simply './' this works however it's not good for my setup as that would include a huge amount of files in the watch and exceed the default filesystem watch notification limits (sure I could adjust these but I'm now sure why the above doesn't work by default.

Any thoughts?

**Comment by pfazzino** [comment]
I've got this working now after enabling DEBUG. The top level symlink I needed to watch has a lot of files and I was exceeding the fs max_user_watches limit which was causing the watch to fail. Thanks for your help with this.

**Comment by gansbrest** [comment]
Is there a way to watch parent folder symlink only, to avoid wasting resources on watching files that never change in prod. 

Our setup is like this:

*build-1
*build-2
* current ----> (symlink) build-1

And our deploy script just switches symlink between different build folders. Typical capistrano style setup? I see no point monitoring files inside the build, only symlink. Please help.

**Comment by aequasi** [comment]
I also have the same setup as @gansbrest. Were you able to find anything?

**Comment by gansbrest** [comment]
@aequasi Yes, so we ended up doing it this way. Every time we deploy new code we basically cd outside build dir and run pm2 like this `HOME=/root HOSTNAME=`hostname` /usr/local/bin/pm2 reload   /current/pm2/pm2.json5` ( those two variable are optional, but HOME is important if you not sure if pm2 was started properly and we always use just reload, since our servers always changing).

Then here is snipped from pm2 config, located in the project (note, everything is relative to the main app dir):

````
     "name": "app-name",
      "cwd": "./current",
      "script": "./current/node_modules/.bin/runfaster",
      "instances": "0",
      "exec_mode": "cluster_mode",
      "max_memory_restart": "500M",
      "min_uptime": 1000,
      "watch": false,
      "merge_logs": true,

````

When we run pm2 this way, it works as expected. No problems with deleted folders any more ( because we never delete project folder, only clean up builds ). Let me know if you have other questions.
