### ISSUE TITLE
Module ideas

### ISSUE THREAD

**Issue by Unitech** [Unitech/PM2#1342]
The upcoming module system for PM2 will be released in stable mode for PM2 1.0. 
The goal is to be able to install NPM packages that can act as standalone software via command like:

```bash
$ pm2 install module-name
$ pm2 uninstall module-name
```
 
# Proposals

## Load balancer

- [Sundry](https://github.com/PaperElectron/Sundry)
- [Hipache](https://github.com/hipache/hipache)

## Others

- [Private NPM: Sinopia](https://github.com/rlidwka/sinopia)
- [SMTP server: Haraka](https://github.com/baudehlo/Haraka)

**Comment by jshkurti** [comment]
You can add to that [pm2-logrotate](https://www.npmjs.com/package/pm2-logrotate) :+1:

**Comment by Unitech** [comment]
Here is an article about the module system & pm2-webshell module

https://keymetrics.io/2015/06/10/pm2-ssh-expose-a-fully-capable-terminal-within-your-browser/

**Comment by jorge-d** [comment]
Some modules providing stats within browser & sending data to keymetrics:
```
pm2-redis
pm2-elasticsearch
pm2-mongo
& so on...
```

:smile:

**Comment by Unitech** [comment]
implemented
