### ISSUE TITLE
warning for incompatible dependency

### ISSUE THREAD

**Issue by mihai-chiorean** [Unitech/PM2#1343]
npm WARN engine promise-spawner@0.0.3: wanted: {"node":">=0.10.3 <0.12"} (current: {"node":"0.12.4","npm":"2.10.1"})

**Comment by soyuka** [comment]
It's only used in a deprecated test and it's a dev dependency. I think those can be removed.

https://github.com/Unitech/PM2/search?utf8=%E2%9C%93&q=promise-spawner
