### ISSUE TITLE
Setting up Pm2 clusters on Digital Ocean

### ISSUE THREAD

**Issue by shashanklp** [Unitech/PM2#1348]
I've hosted my application on Digital ocean with 1GB Memory & 1 Core Processor.

I dont have complete understanding of what cluster actually does. 
When I made 2 or 3 clusters of the app,  the image upload speed slows down and  even to a noticable extent. 

What should be the reason ? Should I use cluster in 1 Core processor ?

And yeah I'm planning to migrate to 2 Gb memory and 2 core processors . Any suggestions for clusters on that too will also be helpful
There is not much traffic on the app yet but its kinda photo sharing where photos are stored at S3 using a express middleware to process image into versions.

**Comment by Unitech** [comment]
Do not use more instances in cluster mode than the number of CPUs available in your server

**Comment by jontelm** [comment]
So the ideal numbers of workers is the amount of CPU:s? What is the reason?
