### ISSUE TITLE
Feature Request: Startup Script for smartOS

### ISSUE THREAD

**Issue by mbejda** [Unitech/pm2#1352]
Feature Request: Startup Script for smartOS.
I noticed that PM2 offers a startup script for Amazon Linux, why note SmartOS?

**Comment by Unitech** [comment]
Would love to get a PR to handle startup for SmartOS!

**Comment by djensen47** [comment]
I have a gist with a SmartOS SMF manifest to start, stop, refresh pm2

https://gist.github.com/djensen47/55ec31c993746989b308

Currently the path and user is hardcoded. Also, in order to activate this manifest, you need to run `svccfg import pm2-service-manifest.xml`

**Comment by Unitech** [comment]
SmartOS embed the launchd init system?

**Comment by Unitech** [comment]
Closing in favor of #2559 

To try the new startup system:

```bash
$ npm install Unitech/pm2#development -g
$ pm2 update
```

```bash
$ pm2 startup     # Then copy / paste the command displayed
$ pm2 unstartup
```
