### ISSUE TITLE
memory usage rising?

### ISSUE THREAD

**Issue by sandro-pasquali** [Unitech/PM2#1353]
Starting the following Node 0.12.4 server on Centos 6.5:
```
// tester.js
var http=require('http');
http.createServer(function(req, res) {
  res.writeHead(200);
  res.end('bye');
}).listen(2122);
```
>pm2 start tester.js
>pm2 list
![screen shot 2015-06-13 at 10 14 36 pm](https://cloud.githubusercontent.com/assets/657552/8146774/c5f9295a-1219-11e5-9dac-a751146bfc32.png)

Now I hit the server (s.om.e.ip:2122), and see "bye"

> pm2 list
![screen shot 2015-06-13 at 10 14 50 pm](https://cloud.githubusercontent.com/assets/657552/8146778/e725a414-1219-11e5-9bd9-cd9fd4b451e2.png)

Now I reload the "page".

> pm2 list
![screen shot 2015-06-13 at 10 15 06 pm](https://cloud.githubusercontent.com/assets/657552/8146781/fd634952-1219-11e5-9575-61ba63633fad.png)

So I'm a little confused by what seems to be a massive memory leak on the simplest HTTP request. Am I missing something? pm2 @0.12.15

Thanks

**Comment by jshkurti** [comment]
No, it's not a leak. Memory usage eventually rises when you start handling requests but it will stabilize at some point.
How to know ? Try sending huge amounts of requests with a tool like `ab` or `wrk`.

**Comment by sandro-pasquali** [comment]
Ok, I'll do some testing.

I'm wondering if you can provide some information on why requests would increase memory? I'm interested in how things are working internally w/ PM2.

**Comment by jshkurti** [comment]
It's not PM2, it's Node.js itself :)
```js
var http = require('http');

http.createServer(function(req, res) {
  res.end('hi');
}).listen(8080);

setInterval(function() {
  console.log(parseInt(process.memoryUsage().rss / (1024*1024)) + ' MB');
}, 333);
```

![pm3-desc](https://cloud.githubusercontent.com/assets/7647602/8161370/c50172ec-1376-11e5-9e37-a93ad996765c.png)


The memory usage starts rising when I do `ab -c 100 -n 10000 http://localhost:8080/`

**Comment by sergeche** [comment]
I have similar issue. For comparison, I’ve started two instances of my web-server app on a fresh VPS (Ubuntu 14.04 x64), one by running script directly and one via PM2. I left these processes for 7 hours and ensured that *no HTTP requests made to either of these servers*.

After 7 hours, memory of “direct” process raised by 0.5KB and PM2 process raised by 15MB. What can cause memory increase for idle process?

**Comment by komorebi-san** [comment]
@sergeche  How did you resolve the leakage?
