### ISSUE TITLE
TypeError on localhost

### ISSUE THREAD

**Issue by DQvsRA** [Unitech/pm2#1355]
When i try to start pm2 on local machine, even when i call "pm2 list" i have this error

![trable](https://cloud.githubusercontent.com/assets/442111/8148129/02fe3780-129e-11e5-9f58-747b69c15d60.png)

i use node 0.10.3 on windows

What to do?

**Comment by vmarchaud** [comment]
Should be working with new version of `pidusage` in `pm2@next`
