### ISSUE TITLE
Process lost on localhost

### ISSUE THREAD

**Issue by DQvsRA** [Unitech/PM2#1356]
I don't know what happen but after i start process and list them with "pm2 list" it's lost from observation but still run on localhost:3000
see this

![trable2](https://cloud.githubusercontent.com/assets/442111/8148165/d7d2b322-129f-11e5-80c0-ed6491f1ba71.jpg)

?

**Comment by soyuka** [comment]
https://github.com/Unitech/PM2/issues/1424
