### ISSUE TITLE
Ecosystem Error

### ISSUE THREAD

**Issue by DQvsRA** [Unitech/pm2#1357]
This is error from latest

![trable3](https://cloud.githubusercontent.com/assets/442111/8148603/d3fdb2f4-12b5-11e5-8611-1f4152bada61.jpg)

windows 7, node 2.3.0

?

**Comment by DQvsRA** [comment]
I suppose it's only windows problem because i run same things on Ubuntu and have it work fine

**Comment by vmarchaud** [comment]
Should be fixed now with recent version of pm2

**Comment by vmarchaud** [comment]
Fix on branch `windowsfix` should be merged soon on `development`.

**Comment by Unitech** [comment]
@vmarchaud https://github.com/Unitech/pm2/commit/c4916d53116f114a08433e42c48794e53c812cf4 LGTM

**Comment by Unitech** [comment]
published pm2@next
