### ISSUE TITLE
How to manage remote process?

### ISSUE THREAD

**Issue by dbuarque** [Unitech/PM2#1358]
Hey guys, 

How can I manage and monitoring remote processes?

**Comment by jshkurti** [comment]
Hi, can you be a bit more specific please ? :)

**Comment by Unitech** [comment]
You can use https://keymetrics.io/

**Comment by dbuarque** [comment]
I love keymetrics.io and I really would like to use it, however as a self-funded startup we don't have a budget to pay for 100 hosts. Every day we run some heavy node jobs that run in up to 100 hosts, each host has two or more processes and we need be able to stop, start, restart, monitoring  remotely.

PM2 is awesome and we really wanna use it for our project.

**Comment by DQvsRA** [comment]
I agree that the cost of keymetrics is too much, aws ec2 micro instance for 3 year cost just 179$ and it worth it.
 Try to look at this as an alternative https://github.com/Tjatse/pm2-gui

**Comment by soyuka** [comment]
By using pm2 programmatically? 
```
var pm2 = require('pm2')
pm2.launchBus(function(err, bus) {
    bus.on('process:event', function(e) {
        //do something with your process e
    })
})
```

**Comment by dbuarque** [comment]
@DQvsRA the problem with pm2-gui is it doesn't support remote management, only local. https://github.com/Tjatse/pm2-gui/issues/19

**Comment by dbuarque** [comment]
@soyuka this is the only way that I think possible with pm2. However, I will have to write a lot of code to manage a bunch of processes. I was looking for something ready to go. :(

**Comment by Tjatse** [comment]
@dbuarque It's just **"local deployment"* - deploying `pm2-gui` on your remote server, then enable the web port, you can manage processes anywhere..

My suggestion:
- 1. Some deployment module like @DQvsRA said.
- 2. Using programmatically API, you can reference to [this](https://github.com/Tjatse/pm2-gui/blob/master/lib/pm.js#L15-L214).
