### ISSUE TITLE
pm2 logs crash

### ISSUE THREAD

**Issue by shaharmor** [Unitech/PM2#1360]
fatal error after `pm2 logs` command:

```
#
# Fatal error in ../deps/v8/src/handles.h, line 48
# CHECK(location_ != NULL) failed
#

==== C stack trace ===============================

 1: V8_Fatal
 2: v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::String::NewStringType, int)
 3: node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding)
 4: node::Buffer::Utf8Slice(v8::FunctionCallbackInfo<v8::Value> const&)
 5: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 6: ??
 7: ??
Illegal instruction (core dumped)
```

**Comment by jshkurti** [comment]
Hmm, what about the Node.js error ?

**Comment by shaharmor** [comment]
there is nothing else... the lines above it were the logs themselves. it happened after like 2 seconds of streaming the logs

**Comment by jshkurti** [comment]
That is strange, let me know if it happens again.

**Comment by jshkurti** [comment]
http://stackoverflow.com/questions/26726711/fatal-error-in-deps-v8-src-handles-h-checklocation-null-failed-fatal

**Comment by jshkurti** [comment]
It doesn't look like it comes from PM2 :/

**Comment by cendrizzi** [comment]
I get this too since upgrading to 0.14. I went back to 0.12.6 and logs work again. Using node 0.12.4 on Ubuntu server.

**Comment by jshkurti** [comment]
`npm i -g Unitech/PM2#development`
Should be fixed.

**Comment by StarpTech** [comment]
I had the same issue. Update fixed the issue.
