### ISSUE TITLE
often restart why?--------PM2: 2015-06-16 23:56:01: App name:Server-API id:0 exited with code 0

### ISSUE THREAD

**Issue by chelsh** [Unitech/pm2#1361]
PM2: 2015-06-16 21:14:20: App name:Server-API id:1 disconnected
PM2: 2015-06-16 21:14:20: App name:Server-API id:1 exited with code 0
PM2: 2015-06-16 21:14:20: Starting execution sequence in -cluster mode- for app name:Server-API id:1
PM2: 2015-06-16 21:14:21: App name:Server-API id:1 online
PM2: 2015-06-16 23:16:16: App name:Server-API id:1 disconnected
PM2: 2015-06-16 23:16:16: App name:Server-API id:1 exited with code 0
PM2: 2015-06-16 23:16:16: Starting execution sequence in -cluster mode- for app name:Server-API id:1
PM2: 2015-06-16 23:16:16: App name:Server-API id:1 online
PM2: 2015-06-16 23:18:47: App name:Server-API id:0 disconnected
PM2: 2015-06-16 23:18:47: App name:Server-API id:0 exited with code 0
PM2: 2015-06-16 23:18:47: Starting execution sequence in -cluster mode- for app name:Server-API id:0
PM2: 2015-06-16 23:18:47: App name:Server-API id:0 online
PM2: 2015-06-16 23:54:32: App name:Server-API id:1 disconnected
PM2: 2015-06-16 23:54:32: App name:Server-API id:1 exited with code 0
PM2: 2015-06-16 23:54:32: Starting execution sequence in -cluster mode- for app name:Server-API id:1
PM2: 2015-06-16 23:54:32: App name:Server-API id:1 online
PM2: 2015-06-16 23:56:01: App name:Server-API id:0 disconnected
PM2: 2015-06-16 23:56:01: App name:Server-API id:0 exited with code 0
PM2: 2015-06-16 23:56:01: Starting execution sequence in -cluster mode- for app name:Server-API id:0
PM2: 2015-06-16 23:56:01: App name:Server-API id:0 online

------ pm2 ,node version:
$ pm2 -v
0.14.0
$ node -v
v0.12.0
----i start my app by this: pm2 startOrReload ecosystem.json
ecosystem.json is :
  apps : [
    {
      name      : "Server-API",
      script    : "index.js",
      instances : '2',
      exec_mode : 'cluster',
      log_date_format: "YYYY-MM-DD HH:mm Z",
      error_file: "../logs/node-err.log",
      out_file: "../logs/node-out.log",
      env: {
        COMMON_VARIABLE: "true"
      },
      env_production : {
        NODE_ENV: "production"
      }
    },
  ]
----my ubuntu server is: 2G memory , 4 cpus

**Comment by chelsh** [comment]
PM2: 2015-06-18 23:03:42: App name:Server-API id:0 disconnected
PM2: 2015-06-18 23:03:42: App name:Server-API id:0 exited with code 0
PM2: 2015-06-18 23:03:42: Starting execution sequence in -cluster mode- for app name:Server-API id:0
PM2: 2015-06-18 23:03:42: App name:Server-API id:0 online
PM2: 2015-06-18 23:05:03: App name:Server-API id:1 disconnected
PM2: 2015-06-18 23:05:03: App name:Server-API id:1 exited with code 0
PM2: 2015-06-18 23:05:03: Starting execution sequence in -cluster mode- for app name:Server-API id:1
PM2: 2015-06-18 23:05:03: App name:Server-API id:1 online
PM2: 2015-06-18 23:20:31: App name:Server-API id:1 disconnected
PM2: 2015-06-18 23:20:31: App name:Server-API id:1 exited with code 0
PM2: 2015-06-18 23:20:31: Starting execution sequence in -cluster mode- for app name:Server-API id:1
PM2: 2015-06-18 23:20:31: App name:Server-API id:1 online
PM2: 2015-06-18 23:23:27: App name:Server-API id:1 disconnected
PM2: 2015-06-18 23:23:27: App name:Server-API id:1 exited with code 0
PM2: 2015-06-18 23:23:27: Starting execution sequence in -cluster mode- for app name:Server-API id:1
PM2: 2015-06-18 23:23:27: App name:Server-API id:1 online
PM2: 2015-06-19 07:50:50: App name:Server-API id:0 disconnected
PM2: 2015-06-19 07:50:50: App name:Server-API id:0 exited with code 0
PM2: 2015-06-19 07:50:50: Starting execution sequence in -cluster mode- for app name:Server-API id:0
PM2: 2015-06-19 07:50:50: App name:Server-API id:0 online

**Comment by chelsh** [comment]
why :)

**Comment by chelsh** [comment]
often restart :(

![image](https://cloud.githubusercontent.com/assets/10752360/8251489/8fe89784-16af-11e5-862b-36d5b968c33b.png)

**Comment by Tjatse** [comment]
Node will normally exit with a 0 status code when no more async operations are pending.

**Comment by jshkurti** [comment]
Can you have a look at these files : 
```
error_file: "../logs/node-err.log",
out_file: "../logs/node-out.log"
```

Maybe there's an error in here :)

**Comment by chelsh** [comment]
PM2: 2015-07-16 00:05:54: App name:Server-API id:1 disconnected
PM2: 2015-07-16 00:05:54: App name:Server-API id:1 exited with code 0
PM2: 2015-07-16 00:05:54: Starting execution sequence in -cluster mode- for app name:Server-API id:1
PM2: 2015-07-16 00:05:54: App name:Server-API id:1 online
PM2: 2015-07-16 01:29:35: App name:Server-API id:0 disconnected
PM2: 2015-07-16 01:29:35: App name:Server-API id:0 exited with code 0
PM2: 2015-07-16 01:29:35: Starting execution sequence in -cluster mode- for app name:Server-API id:0
PM2: 2015-07-16 01:29:35: App name:Server-API id:0 online
PM2: 2015-07-16 02:44:04: App name:Server-API id:0 disconnected
PM2: 2015-07-16 02:44:04: App name:Server-API id:0 exited with code 0
PM2: 2015-07-16 02:44:04: Starting execution sequence in -cluster mode- for app name:Server-API id:0
PM2: 2015-07-16 02:44:04: App name:Server-API id:0 online
PM2: 2015-07-16 07:54:36: App name:Server-API id:1 disconnected
PM2: 2015-07-16 07:54:36: App name:Server-API id:1 exited with code 0
PM2: 2015-07-16 07:54:36: Starting execution sequence in -cluster mode- for app name:Server-API id:1
PM2: 2015-07-16 07:54:36: App name:Server-API id:1 online
PM2: 2015-07-16 08:36:44: App name:Server-API id:0 disconnected
PM2: 2015-07-16 08:36:44: App name:Server-API id:0 exited with code 0
PM2: 2015-07-16 08:36:44: Starting execution sequence in -cluster mode- for app name:Server-API id:0
PM2: 2015-07-16 08:36:44: App name:Server-API id:0 online

**Comment by hassansin** [comment]
Same happens to me when I run the apps/args.json example. node: v0.12.6 PM2: 0.14.5

**Comment by hassansin** [comment]
Continuously restarts on cluster_mode. But works fine on fork_mode. But then again cron_restart doesn't work on fork_mode :(

**Comment by mmoulton** [comment]
I'm experiencing this as well using latest PM2 in cluster mode on iojs 2.x running in a docker container. No problems when in fork mode.

**Comment by jshkurti** [comment]
`exited with code 0` means your app exited without PM2 killing it.
The only way a clustered app would exit with 0 status is if cron_restart is specified.

`console.log(process.env.cron_restart);` inside your app should display `undefined`

**Comment by nikakoy131** [comment]
I have same problem in cluster mode. 
node 4.4.1
npm 2.14.20
pm2 1.1.3
`console.log(process.env.cron_restart); //undefined`
I start my app by this
`pm2 start server.js --name lookfor --watch "server.js parsers"`
But  I don't use Docker.

**Comment by SidFeng** [comment]
same problem!
![image](https://cloud.githubusercontent.com/assets/6702354/16403061/078fe8d2-3d24-11e6-88db-3bfeda0f36cd.png)

**Comment by avnunn** [comment]
We are seeing this issue after migrating to AWS.
(the exit code of 1 was from adding an event handler on `SIGINT` to log additional debug information and `process.exit(1)`)
```
2019-03-28 18:14:14: App name:api id:1 disconnected
2019-03-28 18:14:14: App [api] with id [1] and pid [25093], exited with code [1] via signal [SIGINT]
2019-03-28 18:14:14: Starting execution sequence in -cluster mode- for app name:api id:1
2019-03-28 18:14:14: App name:api id:1 online
2019-03-28 18:19:24: App name:api id:2 disconnected
2019-03-28 18:19:24: App [api] with id [2] and pid [25098], exited with code [1] via signal [SIGINT]
2019-03-28 18:19:24: Starting execution sequence in -cluster mode- for app name:api id:2
2019-03-28 18:19:24: App name:api id:2 online
2019-03-28 18:24:15: App name:api id:1 disconnected
2019-03-28 18:24:15: App [api] with id [1] and pid [27521], exited with code [1] via signal [SIGINT]
2019-03-28 18:24:15: Starting execution sequence in -cluster mode- for app name:api id:1
2019-03-28 18:24:16: App name:api id:1 online
2019-03-28 19:14:33: App name:api id:1 disconnected
2019-03-28 19:14:33: App [api] with id [1] and pid [29254], exited with code [1] via signal [SIGINT]
2019-03-28 19:14:33: Starting execution sequence in -cluster mode- for app name:api id:1
2019-03-28 19:14:33: App name:api id:1 online
2019-03-28 19:35:53: App [api] with id [2] and pid [28417], exited with code [1] via signal [SIGINT]
2019-03-28 19:35:53: Starting execution sequence in -cluster mode- for app name:api id:2
2019-03-28 19:35:53: App name:api id:2 online
```

```
┌──────────┬────┬─────────┬──────┬────────┬─────────┬────────┬─────┬────────────┬──────────┐
│ App name │ id │ mode    │ pid  │ status │ restart │ uptime │ cpu │ mem        │ watching │
├──────────┼────┼─────────┼──────┼────────┼─────────┼────────┼─────┼────────────┼──────────┤
│ api      │ 1  │ cluster │ 5162 │ online │ 75      │ 23m    │ 0%  │ 550.9 MB   │ disabled │
│ api      │ 2  │ cluster │ 8645 │ online │ 54      │ 115s   │ 0%  │ 391.4 MB   │ disabled │
└──────────┴────┴─────────┴──────┴────────┴─────────┴────────┴─────┴────────────┴──────────┘
```
