### ISSUE TITLE
require('pmx').init();

### ISSUE THREAD

**Issue by alexzhang2015** [Unitech/PM2#1362]
It's strange after clone new code in the different folder, then pm2 start the server.js 
The HTTP requests count missing. But origin is ok.
![keymetrics___app](https://cloud.githubusercontent.com/assets/859624/8200755/151fdb0c-14fc-11e5-9e09-d5bf706c7b33.jpg)

Does anything need reconfigure?

PS: I just update to the 0.14.0

**Comment by jorge-d** [comment]
Hi,

We had a small issue with the probe not being updated correctly, you might need to run `npm install -g pm2@latest; pm2 update` in order to update `pmx` to its latest version

**Comment by alexzhang2015** [comment]
Thanks ,

I just run npm install pmx@latest fix this issue.
