### ISSUE TITLE
Can pm2 logs only display error logs?

### ISSUE THREAD

**Issue by Enyu** [Unitech/PM2#1363]
I found when I use pm2 logs, the console window will display all the logs include error & out. It's very cool actually, but after I added health check for my application, the out logs seems like very restless for me...

My question: is there any way to change pm2 logs only display error logs?

**Comment by Enyu** [comment]
actually, I try to use ```pm2 logs -e <error log path>``` to display error logs. after error logs displayed still will show out log in console window. - -!

**Comment by soyuka** [comment]
There is no such option atm (see `pm2 logs --help`).

@jshkurti what about adding an option to choose err/out or both?

**Comment by jshkurti** [comment]
Done.
`npm i -g Unitech/PM2#development`

`pm2 logs [ all | OUT | ERR | app_name | app_id] [--lines <n>] [--raw] [--timestamp [format]]`.

**Comment by jshkurti** [comment]
Only works for live streamed logs. It will still show out and err for the last lines tailed.
So in your case you have to do something like this :
`pm2 logs ERR --lines 0`

**Comment by jshkurti** [comment]
This is not a good implementation though, I will update it before the officiel release to something like `pm2 logs [app_name | app_id] [--err | --out]` so you could filter by app **and** by stderr or stdout.

**Comment by Enyu** [comment]
@jshkurti @soyuka thanks.

**Comment by zhupengfeivip** [comment]
you can use pm2 log 12 | grep ERROR

**Comment by denven** [comment]
To see the last 100 lines of error logs:
`pm2 logs appName --err --lines=100`

**Comment by amir-khann** [comment]
how i can fix the following error
/home/ubuntu/.pm2/logs/server-error.log last 15 lines:
/home/ubuntu/.pm2/logs/server-out.log last 15 lines:

**Comment by tahirakbar1** [comment]
pm2 logs 'App ID' --err --lines 1000
