### ISSUE TITLE
lsof  shows too many open files for pm2

### ISSUE THREAD

**Issue by vijaybarnwal** [Unitech/PM2#1364]
Hi,

I am afraid of too many open files. 
When I run 
lsof | wc -l gives 80000 count and when I run lsof | grep pm2 | wc -l it shows me 60000 count alone.

I am running my pm2 apps in cluster mode in two different ports like:
NODE_PORT=8080 pm2 start index.js --name index1
and
NODE_PORT=8081 pm2 start index.js --name index2 -f

Both the apps are running in cluster mode. But due to lsof it gives memory leaks and high cpu usage.

But after restart/reload pm2 lsof goes to stable state and also cpu and memory is goes down as normal state.

Can anybody  help me to debug this and resolve this issue? 

Thanks,
Vijay Barnwal

**Comment by Tjatse** [comment]
Whats your PM2 and node.js / io.js version? And could you provide a simple demo to reproduce this if possible?

**Comment by vijaybarnwal** [comment]
PM2 version : 0.9.6
Node version: 0.10.33

 lsof | wc -l
157071
lsof | grep pm2 | wc -l
130298

Thanks,

**Comment by Tjatse** [comment]
Uh, your PM2 seems too old, and this is a confirmed bug of `<PM2@0.11`, why don't u update PM2 to latest (0.12.x), it's more stabler and powerful. x.-

**Comment by vijaybarnwal** [comment]
I tried to update pm2 previously but it gives error in ubuntu 14.04 aws instance. 

In log I saw channel is closed error from node js.

Can I update node version also?

Thanks for support Tjaste.

**Comment by Tjatse** [comment]
You'd better do that, node 0.11+ will utmost develop cluster efficiency.

**Comment by vijaybarnwal** [comment]
But in ubuntu 14.04 aws instance when I ran apt-get install nodejs it doesnt upgrade it to latest version it shows me 0.10.33 I think there is no any issue with node.

And I read somewhere that PM2 0.11.x version deprecated its cluster behaviour.
If its true then how can I run my app in two ports as cluster just example given in my first post?

Thanks,

**Comment by Tjatse** [comment]
Apparently, all you need to do is just update your PM2, I'm not familiar with AWS, it is blocked in China, maybe @soyuka can help you out.

**Comment by vijaybarnwal** [comment]
But in my local ubuntu 14.04 machine I also got error after updating PM2. 

Can you please tell me how can I run app script in cluster mode in 0.11.x version like posted in first post?

Thanks,

**Comment by Tjatse** [comment]
[exec_mode](https://github.com/Unitech/PM2/blob/master/ADVANCED_README.md#list-of-all-json-declaration-fields-avaibles)

**Comment by vijaybarnwal** [comment]
Hi Tjatse,

I got following error while trying to install pm2@0.11.x

npm ERR! pm2@0.11.1 preinstall: `bash ./scripts/preinstall.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pm2@0.11.1 preinstall script.
npm ERR! This is most likely a problem with the pm2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bash ./scripts/preinstall.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls pm2
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "pm2@0.11"
npm ERR! cwd /home/manusis
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0


Please tell me whats the issue.

**Comment by Tjatse** [comment]
@jshkurti

**Comment by jshkurti** [comment]
`npm i -g pm2@latest` ?

**Comment by vijaybarnwal** [comment]
Hi Shkurti,

pm2@latest installs latest version of pm2 which is 0.14.x not 0.11.1. But I
want to install pm2@0.11.1.

Thanks,

*-----------*

*Vijay Barnwal | StoreHippo*

*mobile*: +91 750 329 8247

*email* : vijay.barnwal@hippoinnovations.com <vijay.barnwal@manusis.com>,
vijay.barnwal@manusis.com

*website*:* http://www.storehippo.com <http://www.storehippo.com/>*

* <http://www.storehippo.com/>*

**Comment by jshkurti** [comment]
Just use v0.14.0.
Don't try `pm2 update`.
Instead do `npm i -g pm2@latest; pm2 dump; pm2 kill; pm2 resurrect`.
PM2 v0.14.0 works just fine, it's just the `pm2 update` which fails when trying to update from a really old version of PM2.

**Comment by vijaybarnwal** [comment]
Thanks for reply Shkruti, I have another issue when I see lsof | grep pm2 |
wc -l it shows 80% open files of total files which consumes system cpu and
memory.

Can you please tell me whats the reason behind this? My apps are running in
cluster mode.

Thanks,

*-----------*

*Vijay Barnwal | StoreHippo*

*mobile*: +91 750 329 8247

*email* : vijay.barnwal@hippoinnovations.com <vijay.barnwal@manusis.com>,
vijay.barnwal@manusis.com

*website*:* http://www.storehippo.com <http://www.storehippo.com/>*

* <http://www.storehippo.com/>*

**Comment by jshkurti** [comment]
Can you try a fresh start. Kill evertyhing `pkill -9 node; pkill -9 PM2` until `lsof | grep PM2` shows nothing.
Then start your apps and paste a screenshot of your `lsof | grep PM2`

**Comment by vijaybarnwal** [comment]
Hi Shkruti,

I upgraded nodejs to 0.12.4 and pm2 to 0.14.0. Can you please tell me how
can I run app in cluster mode with these configuration becoz when i simply
run these apps it run in fork mode?

Thanks,

*-----------*

*Vijay Barnwal | StoreHippo*

*mobile*: +91 750 329 8247

*email* : vijay.barnwal@hippoinnovations.com <vijay.barnwal@manusis.com>,
vijay.barnwal@manusis.com

*website*:* http://www.storehippo.com <http://www.storehippo.com/>*

* <http://www.storehippo.com/>*

**Comment by jshkurti** [comment]
`pm2 start app.js -i 4` => runs app.js in cluster mode with 4 instances
or if you're using json configuration file :
```json
{
  "exec_mode" : "cluster",
  "instances"    : 4
}
```
