### ISSUE TITLE
start app only with fork mode when trying cluster

### ISSUE THREAD

**Issue by OriTheMan** [Unitech/PM2#1365]
Hi,
i try to run sailsjs app in cluster mode.
i run the command 
```
pm2 start app.js -i max -x -- --prod
```

and the result is
![pm2](https://cloud.githubusercontent.com/assets/2189993/8209309/f8d70420-1514-11e5-8fbc-1ee810109bc3.jpg)

the app cant run because the other fork task listen to the specific port

**Comment by jshkurti** [comment]
`-x` is for fork_mode. Just remove the `-x`.

**Comment by OriTheMan** [comment]
but i need to pass this parameter to use production mode in sails js-i took this command from sailsjs documentation

**Comment by jshkurti** [comment]
`pm2 start app.js -i max -- --prod` ?

**Comment by OriTheMan** [comment]
works, thanks! i will recommend to salsas fix the command

**Comment by jshkurti** [comment]
Did you read in sails doc about PM2 ? Where ?

**Comment by OriTheMan** [comment]
http://sailsjs.org/#!/documentation/concepts/Deployment
