### ISSUE TITLE
Reset environment variables on reload/restart 

### ISSUE THREAD

**Issue by rkmax** [Unitech/pm2#1366]
I test this only with the cluster_mode.

I have some env variables defined on my json file, if I changed the value and reload using the command

```
$ pm2 reload config.json
```

The env vars does not change on my instances, I have to restart, :( this on production is not good

**Comment by soyuka** [comment]
@jshkurti I have a similar issue, my `pm2.json` is looking like this:

```
{
"apps": [{
    "script": "./lib/WatchSQL.js",
    "name": "WatchSQL",
    "exec_mode": "fork",
    "cwd": "./some/path",
    "env": {
      "GTS_ENV": "development",
      "DEBUG": "some:*"
    },
    "env_development": {
      "GTS_ENV": "developmentb",
      "DEBUG": "some:*"
    },
    "env_production": {
      "GTS_ENV": "production",
      "DEBUG": ""
    },
    "env_integration": {
      "GTS_ENV": "integration",
      "DEBUG": "some:*"
    },
    "vizion": false,
    "error_file": "/usr/share/nginx/www/some/logs/watchsql.err.log",
    "out_file": "/usr/share/nginx/www/some/logs/watchsql.out.log"
  }]
}
```

If a process is initially started with no env, `DEBUG="some:*"` in my example, doing `pm2 restart 0 --env production` won't reload my env variable.
I remember that you fixed an issue that might be related to this recently but I just tried with pm2 `0.14.1` and it didn't work.
May you confirm this? I'll give a complete way to reproduce as soon as I can ;).

**Comment by soyuka** [comment]
Test case here : https://github.com/soyuka/pm2envtest

**Comment by jshkurti** [comment]
Which kind of behavior do you want :

On restart/reload :
- env is refreshed completely (json env + current shell env)
or
- only json env is refreshed ?

**Comment by soyuka** [comment]
I think that the best is that json environnement variable should override my shell env. Also, they should be updated according to the json values and the `--env` argument value. 

As current shell env is already reloading (not tested), I think that we should add a json refresh on top of it.

**Comment by rkmax** [comment]
I agree with @soyuka, JSON should replace shell env then reload/restart

**Comment by lukesneeringer** [comment]
What is the status on this? PM2's loss of environment variables declared in a JSON configuration seems like a bug, but the roadmap issue makes me wonder whether this issue has been abandoned?

**Comment by pmcnr-hx** [comment]
+1. I had a look at the code a while back and this shouldn't be too difficult to implement. It is a blocker for 100% rolling restarts.

**Comment by alexpts** [comment]
+1

**Comment by Unitech** [comment]
PR welcome, this feature is not going to be implemented by ourselves

**Comment by Unitech** [comment]
Moving to #2002
