### ISSUE TITLE
pm2 restart problem

### ISSUE THREAD

**Issue by haozxuan** [Unitech/PM2#1367]
when i use pm2@0.12.1 release,i find something worong eg:
![image](https://cloud.githubusercontent.com/assets/8748015/8222751/cb449580-15a1-11e5-868b-44c82e672bdb.png)
but i find this : https://github.com/Unitech/PM2/issues/891, so i update my pm2 -> 0.12.16,but no lucky,
i found err logs too.
![image](https://cloud.githubusercontent.com/assets/8748015/8222719/9a9fd804-15a1-11e5-801f-e174abb51931.png)
this is my err log, i search all way,but not find anything to help me.so hope you answer.

**Comment by Tjatse** [comment]
Did you do `pm2 updatePM2` after updated.

**Comment by haozxuan** [comment]
@Tjatse  yeah, i did npm install pm2@latest -g ; pm2 updatePM2  and pm2 -v is 0.12.4

**Comment by Tjatse** [comment]
It seems some thing wrong with your script(full/half width symbols), could you provide the demo codes if possible?
BTW, which version of node.js are you using?

**Comment by haozxuan** [comment]
this is my start json :
![image](https://cloud.githubusercontent.com/assets/8748015/8223126/c3147f56-15a6-11e5-9b95-b85df4105441.png)

full/half width symbols,i don't think so,because when pm2@0.12.1 still work well.
demo is simple http server.and node@0.10.26

**Comment by Tjatse** [comment]
can not reproduce that, my test case:

app.js
```js
var http = require('http');
var port = process.argv.slice(process.argv.length - 1)[0];
if (isNaN(port)) {
  port = parseInt(Math.random() * 1000) + 8000;
}

http.createServer(function(req, res, next) {
  res.writeHead(200, {
    contentType: 'application/json'
  });
  res.write({
    say: 'welcome aboard: ' + process.id
  });
  res.end();
}).listen(port);

console.log('Web site is listening on %s with node@%s', port, process.versions.node);
```

startup json:
```JSON
{
  "apps": [{
    "name": "server1",
    "script": "./app.js",
    "args": [8000],
    "log_date_format": "YYYY-MM-DD HH:mm:ss",
    "exec_mode": "fork_mode"
  }, {
    "name": "server2",
    "script": "./app.js",
    "args": [8001],
    "log_date_format": "YYYY-MM-DD HH:mm:ss",
    "exec_mode": "fork_mode"
  }, {
    "name": "server3",
    "script": "./app.js",
    "args": [8002],
    "log_date_format": "YYYY-MM-DD HH:mm:ss",
    "exec_mode": "fork_mode"
  }]
}
```

`pm2 logs`:

```
server1-0 (out): 2015-06-18 12:28:10: Web site is listening on 8000 with node@0.10.26
server2-1 (out): 2015-06-18 12:28:10: Web site is listening on 8001 with node@0.10.26
server3-2 (out): 2015-06-18 12:28:10: Web site is listening on 8002 with node@0.10.26
```

`pm2 -v`:

`0.12.16`

**Comment by haozxuan** [comment]
i run 1W , it works well :cry: 
i check pm2.log file, stop reason is 143. i have any idea.

**Comment by jshkurti** [comment]
Can you try a fresh start. Kill everything. `npm install -g pm2@latest` (which is 0.14.0).
Then `pm2 start your.json`.

**Comment by haozxuan** [comment]
i add this want to catch uncaughtException.  hope find error.
process.on('uncaughtException', function(exception) {
    //handle or ignore error
    console.log('exception is ', exception);
});
