### ISSUE TITLE
pm2-dev on 0.14, console output doesn't seem to work

### ISSUE THREAD

**Issue by gerotakke** [Unitech/PM2#1369]
When starting an app with pm2-dev run <script.js>, all that is displayed on the console is "undefined".
Very simple test case:
cat "console.log('test');" > app.js
pm2-dev run app.js
Output:
app: undefined
Tested on several machines, all running OSX 10.10.3. Downgrade to 0.12.16 (and running updatePM2) helped.

**Comment by jshkurti** [comment]
It will be fixed on v0.14.1.
You can already test : `npm i -g Unitech/PM2#development`
