### ISSUE TITLE
Add support for autocomplete to pm2 command line

### ISSUE THREAD

**Issue by shaharmor** [Unitech/PM2#1370]
Hi,

Can you please add autocomplete to pm2 command line?

For example, 
lets say i have the following apps currently running with pm2:
very-long-app-name
short-app
another-app
another-app-2

if i write `pm2 restart v` and then press the TAB button, it will autocomplete to `pm2 restart very-long-app-name`.

Another possible feature of this, is to TAB-toggle between apps prefixed with the prefix i wrote.

For example, with the same app from above, if i write `pm2 restart a`and then click TAB, it will autocomplete to `pm2 restart another-app`, but if i TAB again it will change to `pm2 restart another-app-2`.

This can also be used to autocomplete the pm2 commands like reset, restart, start, stop, delete etc..

**Comment by haozxuan** [comment]
@shaharmor  i usual use id,not name

**Comment by Unitech** [comment]
Does someone have any recommendation about the autocomplete system?

**Comment by shaharmor** [comment]
https://www.npmjs.com/package/tabtab

**Comment by Unitech** [comment]
Any contribution is warmly welcome, we could use `pm2 jlist` or the PM2 API to retrieve current running processes name and do the completion (https://github.com/Unitech/PM2/blob/master/doc/PROGRAMMATIC.md#rpc-system---remote-control)

**Comment by Unitech** [comment]
Done!

Thanks to @alavit-d!

https://github.com/Unitech/PM2/blob/master/ADVANCED_README.md#tab-completion

**Comment by hos7ein** [comment]
https://futurestud.io/blog/pm2-command-line-autocompletion
