### ISSUE TITLE
Delete all to reset pm2 ids

### ISSUE THREAD

**Issue by shaharmor** [Unitech/PM2#1371]
Hi,

When using `pm2 delete all`, is it possible to also reset the pm2 ids? so if i have an app running with id 0, if i `pm2 delete all` and then start another app it will also use id 0.

**Comment by jshkurti** [comment]
https://github.com/Unitech/PM2/commit/2552dee3fe82b2c5643f424740bdbf35bf0ef8c2

Done :)

**Comment by jshkurti** [comment]
It will be avaiable on v0.14.1

**Comment by shaharmor** [comment]
Thanks!

**Comment by adityamertia** [comment]
This doesn't work on pm2V2.9.3. Has this been released yet?
`pm2 delete all` doesn't reset the application ids. The ids start from incremental numbers.
@jshkurti
