### ISSUE TITLE
pm2@0.14.0  logs no colors?

### ISSUE THREAD

**Issue by haozxuan** [Unitech/PM2#1372]
when start many services, i hope different colors ,but 0.14.0 all of is green.
like this:
![image](https://cloud.githubusercontent.com/assets/8748015/8231175/45b6da92-15f9-11e5-97a4-2fcc3089e033.png)
i like this:
![image](https://cloud.githubusercontent.com/assets/8748015/8231167/2a51d284-15f9-11e5-8044-2e4eb2712fa4.png)

**Comment by jshkurti** [comment]
Indeed, will implement this someday :)

**Comment by haozxuan** [comment]
after 0.14 only have one color?

**Comment by jshkurti** [comment]
yes green = stdout, red = stderr, blue = PM2 logs

**Comment by haozxuan** [comment]
I need some time to adjust :|

**Comment by MichielDeMey** [comment]
You can get color if you're using an alternative logger (e.g. Bunyan) and log everything using the `--raw` flag.

`pm2 logs --raw | bunyan`

**Comment by pvcon13** [comment]
How can we reset it, like previously, to have an array of colors(per processor)? Routinely added a few more colors when I loaded a new version. Its useful on a 4 or 8 threaded app to see the affinity/distribution

**Comment by pvcon13** [comment]
whats the last version I can rollback to (least bugs/issues) that has the color logs?

**Comment by MZeora** [comment]
This color bug also seems to ruin with other libraries (such as Marak/colors) both on serverside and clientside use with telnet. Making pm2 or colors useless together.

colors v1.1.2, pm2 v0.14.3, Ubuntu 15.04, node v0.12.0.

**Comment by pvcon13** [comment]
I just reverted to npm install pm2@0.12.16 –g and added at cd /usr/local/lib/node_modules/pm2/lib
in Logs.js
Log.colors = ['black', 'yellow', 'magenta', 'cyan', 'red', 'yellow', 'white', 'green', 'blue', 'cyan'];
Looks great  with superputty terninals

node v0.12.7, Rhel 7.1

**Comment by MZeora** [comment]
Sounds great. Thanks. I'll look into it.

**Comment by pvcon13** [comment]
will be trying node 5.0.0 soon.... is pm2@0.12.16 still compatible  OR  is there a way to get color logs now with the latest version?
