### ISSUE TITLE
Watch: Ignore exceptions?

### ISSUE THREAD

**Issue by tkambler** [Unitech/PM2#1373]
My application is setup with a `node_modules/app` folder that contains various application-specific bits of logic, etc..., that don't yet deserve their own modules. All of my app-specific code lives within this folder.

Is it possible to instruct PM2's `watch` command to ignore everything within `node_modules` - *except* `node_modules/app`?

**Comment by soyuka** [comment]
Something like this should work: 

```ignoreWatch: ['node_modules', '!node_modules/app']```

**Comment by tkambler** [comment]
Does not appear to work, no. And the docs discuss `ignore_watch` ?

**Comment by soyuka** [comment]
Indeed it's `ignore_watch` for the configuration. Use a regex if this does not work but according to the [chokidar behavior](https://github.com/paulmillr/chokidar#path-filtering) this should work.

**Comment by tkambler** [comment]
FYI... I see references to both `ignoreWatch` and `ignore_watch` both within the docs and within test fixtures, etc...

**Comment by soyuka** [comment]
Yes that's why I made the mistake ([those files are wrong](https://github.com/Unitech/PM2/search?utf8=%E2%9C%93&q=ignoreWatch)). 
`ignore_watch` is correct, [here is the code](https://github.com/Unitech/PM2/blob/dfd33cb29f1972a2c47def59fc4013f46b6fa3e1/lib/Watcher.js#L28).
