### ISSUE TITLE
Logs crash with "Allocation failed"

### ISSUE THREAD

**Issue by MichielDeMey** [Unitech/PM2#1374]
I'm trying to stream the logs a a certain process but I'm getting the following error:

```
FATAL ERROR: CALL_AND_RETRY_0 Allocation failed - process out of memory
[1]    26844 abort (core dumped)  pm2 logs 9
```

Server has 16GbB of memory and is only using 2GB - 4GB at most.

Running PM2 v0.14.0, Node v0.10.37, Ubuntu 14.04

EDIT: The same error occurs when I try to limit the number of lines using
```
pm2 logs 9 --lines 50
```

**Comment by jshkurti** [comment]
`npm i -g Unitech/PM2#development` and tell me if it works now :)

The problem here was that PM2 tried to read and bufferise the entire file and the file was probably too big.
Now it reads only the necessary part.

**Comment by MichielDeMey** [comment]
Seems to work now, thanks!

**Comment by jshkurti** [comment]
great news :)

**Comment by scaryguy** [comment]
I'm having the exact same problem with both 0.14.0 and 0.14.1. So, if you have a patch for that are you going to release it soon? What should I do now? I have an application in production.

**Comment by jshkurti** [comment]
`npm i -g Unitech/PM2#development` should work for now.
The 0.14.2 release is coming really soon.
