### ISSUE TITLE
Optional external dependency: ikt

### ISSUE THREAD

**Issue by v12** [Unitech/PM2#1376]
Hi,

There is an optional dependency that is located not in npm but at `http://ikt.pm2.io/ikt.git`

After fetching it manually, I found that there is only one file `index.js`, which doesn't do anything useful:
```javascript
console.log('hello');
```

Also, no any additional information about the package in `package.json`

I'm wondering what's the use of this module and why it is required by PM2 as a dependency (though optional). The only thing that comes to my mind – it allows you to collect package installation statistics, but, if I'm right, why isn't it mentioned anywhere? :smiley: 

So, would you mind to tell what's the purpose of having this dependency?

Thanks! :+1:

**Comment by jshkurti** [comment]
Exactly, it allows us to collect statistics.
Check your emails ;)
