### ISSUE TITLE
PM2 cluster mode instance stuck on launching status

### ISSUE THREAD

**Issue by flaviolivolsi** [Unitech/PM2#1378]
Hello,
after updating node.js version from 0.10 to 0.12.4, PM2 started to give me the issue described above.
If I launch an app with the cluster mode, the first cluster will remain stuck on the launching status and it won't work.

![image](https://cloud.githubusercontent.com/assets/5151628/8267451/b7df4ba8-1762-11e5-9a8d-f4de805d95ef.png)

**Comment by jshkurti** [comment]
Hmm can you kill everything `pkill -9 PM2; pkill -9 node;`, install PM2 v0.14.1 (latest) and try again ? :)

**Comment by flaviolivolsi** [comment]
Thank you @jshkurti :) solved! I've got 0.14.0 version, once updated it worked!

**Comment by grrava** [comment]
I have the same issue with pm2 1.0.0...

**Comment by IPRIT** [comment]
I have the same issue on PM2 version 1.1.3

**Comment by IPRIT** [comment]
I've tried to kill all PM2 & node processes and still not working.

**Comment by yogithesymbian** [comment]
any other solution ?

**Comment by danish7778** [comment]
Hi, I have this issue in production. the process is stuck in launching until I kill the pm2 daemon.

node version: v12.22.12
pm2 version:  5.2.2

any idea how to troubleshoot?

**Comment by tomihq** [comment]
> Hmm can you kill everything `pkill -9 PM2; pkill -9 node;`, install PM2 v0.14.1 (latest) and try again ? :)

life saver! thanks
