### ISSUE TITLE
watch option doesn't work + ignore_watch crashes on empty value

### ISSUE THREAD

**Issue by srcspider** [Unitech/PM2#1379]
**Test case**

```sh
mkdir testserv
cd testserv
mkdir -p src/node_modules
echo "{}" > package.json
npm i -S cluster express
edit src/node_modules/main.js
```

```javascript
var cluster = require('cluster');
var express = require('express');

module.exports = function (syspath, conf) {

	var http = express();

	http.get('/', function (req, res) {
		res.send('code version: 1.0.0');
	});

	http.use(function(req, res, next) {
		res.status(404).send('404 - Not Found');
	});

	if (cluster.isMaster) {
		console.log('Listening on Port', conf.server.port);
		var cpuCores = require('os').cpus().length;
		console.log('Detected', cpuCores, 'CPU cores');

		for (var i = 0; i < cpuCores; i += 1) {
			cluster.fork();
		}

		cluster.on('exit', function (worker, code, signal) {
			console.log('worker %d died (%s). resurecting...',
				worker.process.pid, signal || code);
			cluster.fork();
		});
	}
	else { // worker process
		http.listen(conf.server.port);
		console.log('Worker Process #' + cluster.worker.id, 'ready');
	}

};
```
```sh
mkdir public
edit public/www.js
```
```js
var path = require('path');

var wwwpath = __dirname;
var syspath = path.join(wwwpath, '..');

var conf = {
	server: {
		port: 3030,
		wwwpath: wwwpath
	}
};

var main = require(path.join(syspath, 'src/node_modules/main'));
main(syspath, conf);
```
```sh
edit .pm2.json
```
```json
{
	"apps": [
		{
			"name"   : "testapp",
			"script" : "public/www.js",
			"watch"  : [ "src" ],
			"ignore_watch" : [ "file_does_not_exist_anywhere" ]
		}
	]
}
```
*The key `ignore_watch` seems to crash if array is empty; hence the random value.*

Okey so now in another console window I open up `pm2 logs`, and load in the app via `pm2 start .pm2.json`. Everything okey so far I the server is live on `3030` and starts all its workers. But if I go to change the version in the `/` route neither do I get a restart of the server in logs, nor does the change reflect if I access `localhost:3030`.

I've confirmed with `pm2 list`, the application `testapp` is identified as `online` and `watching`.

**Comment by soyuka** [comment]
Watch options are directly handled by chokidar. If you need to debug your arguments, I'd recommend the use of `DEBUG="pm2:*" pm2 --no-daemon`. I don't know why it wouldn't work. Take a look at other watch issues, maybe some things I said there might help your case.

I'll test the empty `ignore_watch` and 'll fix the issue as soon as I can.  Thanks for reporting.

**Comment by soyuka** [comment]
There is an issue when `ignore_watch` is empty, reopening

**Comment by Unitech** [comment]
ops ok
