### ISSUE TITLE
Segfaults on Ubuntu 14.04

### ISSUE THREAD

**Issue by suprMax** [Unitech/PM2#1380]
Hi!

We used to use upstart to run our Node apps and decided to try to move to pm2 instead. Unfortunately on our production machine it crashes at least once a day.

kern.log:
`Jun 22 15:06:02 Ubuntu-1404-trusty-64-minimal kernel: [569531.959543] PM2 v0.14.1: Go[19539]: segfault at 3fffffffa0 ip 0000000000902e38 sp 00007fff99f29290 error 4 in nodejs[400000+b60000]`

We tried to add upstart to call `pm2 resurrect` in case pm2 dies, but apparently that doesn't work too. Couldn't really check that one though.

We have node v0.12.4. 

Is anyone else experiencing the same issue? It's really a shame, I loved keymetrics interface, but I can't use it without pm2 on the server.

**Comment by jshkurti** [comment]
The only thing I found : https://github.com/joyent/node/issues/2376

**Comment by jshkurti** [comment]
This may happen while using PM2 but I honestly think it has nothing to do with PM2 :)

**Comment by jshkurti** [comment]
Give it a try with `npm i -g Unitech/PM2#development` though.

**Comment by suprMax** [comment]
Different symptoms, currently it just crashes all node apps, and it does say `PM2 v0.14.1`

**Comment by suprMax** [comment]
`Unitech/PM2#development` seems to be stable. Any chance to get it published to the NPM soon?

**Comment by jshkurti** [comment]
Published @0.14.2 ;)

**Comment by NikitaKrasavtsev** [comment]
Hello.
We are experiencing similar issue on Ubuntu v14.04.2, pm2 v0.14.3 & node v0.12.3
Jul  6 12:51:41 kernel: [8099284.062085] traps: PM2 v0.14.3: Go[3068] general protection ip:902e38 sp:7fff13dab650 error:0 in nodejs[400000+b60000]

**Comment by membrive** [comment]
Hello. I have the same problem in two different machines with Ubuntu 14.04.2:

kernel: [27469.014499] PM2 v0.14.3: Go[1159]: segfault at ffffffffffffffa0 ip 00000000009036f8 sp 00007ffcaf7b07f0 error 5 in nodejs[400000+b61000]

and

kernel: traps: PM2 v0.14.3: Go[3491] general protection ip:99e0d8 sp:7fffc3fbae00 error:0 in node[400000+fca000]

**Comment by jhansen-tt** [comment]
I am also seeing this issue on Ubuntu 14.04 w/nodejs 0.12.6 and PM2 0.14.3, and it is not due to the hung-task kernel issue that has been referenced previously.  This is the only thing that shows up in our kernel log:

[ 8023.396041] PM2 v0.14.3: Go[29558]: segfault at 8090000404c ip 00000000009037f8 sp 00007fff7e3d9a80 error 4 in nodejs[400000+b61000]

I have to do '/etc/init.d/pm2-init.sh start' to get things running again.

If this is a nodejs bug, I am happy to file a bug with them, I just want to help fix the issue however I can.  If PM2 doesn't have any native code then it is definitely a nodejs bug.

**Comment by suprMax** [comment]
```

**Comment by jshkurti** [comment]
Is there any error in `~/.pm2/pm2.log` so we could at least know when that happens in the JS code ?

**Comment by membrive** [comment]
I don't see any errors on ~/.pm2/pm2.log, it seems normal.

Yesterday I reinstalled node.js from the source code (`./configure`, `make` and `make install`), and pm2 so far hasn't been crashed! I'm waiting...

Did anyone with this problem try with node.js installed from the source code?

**Comment by jhansen-tt** [comment]
There is nothing in my pm2.log at the time of the segfault.  Anything else I can look at?  What is the best way to start pm2 with gdb?

**Comment by suprMax** [comment]
````

**Comment by soyuka** [comment]
Lot of restarts there ^^.

This isn't good: `RangeError: Maximum call stack size exceeded`. Do others have this kind of error too?

**Comment by jshkurti** [comment]
@suprMax According to the first post, the segfault happenned `Jun 22 15:06:02`. Your pm2.log shows `2015-07-08`.

**Comment by soyuka** [comment]
@jhansen-tt Last time I had to debug a segfault I used https://github.com/ddopson/node-segfault-handler. I don't know if it's possible with gdb.

@jshkurti indeed.

**Comment by jhansen-tt** [comment]
I don't get the RangeError, or anything in my pm2.log when it happens.  Just the segfault notification in the kernel log.  Right now I have to use crontab to see if the PID in ~/.pm2/pm2.pid is still running, and if not, then I run /etc/init.d/pm2 restart...

**Comment by jshkurti** [comment]
Any chance newer versions of Node could fix this ? (perhaps Node v0.12.6)

**Comment by jhansen-tt** [comment]
@jshkurti I am already on 0.12.6 and I see it.

**Comment by soyuka** [comment]
@jhansen-tt would be nice to have a way to reproduce or a better stack trace :/. I'm using node 0.12.3 with pm2 0.14.1 with a 20D+ uptime (debian 7). +1 @jshkurti or try to go back to node 0.12.3 to see if this still happens.

**Comment by jhansen-tt** [comment]
@soyuka I am just running an express server and a couple of python scripts with PM2... Nothing fancy.

**Comment by soyuka** [comment]
Same here @jhansen-tt but with fancy things and I've absolutely no issue. On another server I've pm2 `0.14.3` with node `0.12.5` 1 ghost blog and another express app with no segfault (debian 8). 
I'll try to give ubuntu a try tonight and let you know.

**Comment by suprMax** [comment]
@jshkurti I got log only for today cos It happened today too at ~12:35:55. Nothing in the log around that time though.

@wrekah FYI

**Comment by parisholley** [comment]
i ran into a segfault today, but I can't get my processes to launch now...

**Comment by parisholley** [comment]
running 
```
pm2 startOrGracefulReload ecosystem.json --env production
```
produced no output in logs and just hangs

when I called 

```
pm2 start ecosystem.json --env production
```

I got the following in ~/.pm2/pm2.log

```
2015-07-09 00:32:21: Starting execution sequence in -cluster mode- for app name:crawl-pull id:12
2015-07-09 00:32:21: [PM2] Error caught by domain:
AssertionError: false == true
    at SharedHandle.add (cluster.js:97:3)
    at queryServer (cluster.js:480:12)
    at Worker.onmessage (cluster.js:438:7)
    at ChildProcess.<anonymous> (cluster.js:692:8)
    at ChildProcess.emit (events.js:129:20)
    at handleMessage (child_process.js:324:10)
    at Pipe.channel.onread (child_process.js:352:11)
```

**Comment by parisholley** [comment]
looks like my issue is related to #1204 , bah...

**Comment by jhansen-tt** [comment]
I think this issue needs to be broken out into two:
* Obviously node.js is segfaulting, so that is probably node.js's issue, and not necessarily a PM2 bug.  I've updated to node.js 0.12.7, and I'm trying to reproduce this again.
* When PM2 crashes in this way, the dump.pm2 file get emptied (to an empty object "{}"), and "pm2 resurrect" doesn't re-initialize my saved tasks the next time I start pm2.  As a work-around, I've made dump.pm2 owned by root, but PM2 should be fixed so that a crash does not cause the dump.pm2 file to get saved as an empty object.  This can easily be reproduced by simply kill -9'ing the pm2 process.

**Comment by chelsh** [comment]
PM2 stop frequently and stop the app #1433 
----pm2 v0.14.3 have resolved this problem?

**Comment by membrive** [comment]
No, the problem is not solved in v0.14.3.

**Comment by jorge-d** [comment]
Can you try using the development branch ?

**Comment by membrive** [comment]
@jorge-d I will try when I have a little free time.

**Comment by soyuka** [comment]
@jorge-d @membrive Could you try to remove those two lines from [Satan](https://github.com/Unitech/PM2/blob/master/lib/Satan.js#L359):

```
  node_args.push('--expose-gc'); // Allows manual GC in the code
  node_args.push('--gc-global'); // Does full GC (smaller memory footprint)
```

And see if the segfault still occurs?

**Comment by membrive** [comment]
In the first 24 hours with the development PM2 (with the changes made by @jorge-d) I have not seen segafults, but I am trying in a virtual machine without traffic, so I think that we need more testing.

Should I try with the development PM2 (@jorge-d changes) or with @soyuka changes? Or both?

**Comment by klinquist** [comment]
I'm waiting with bated breath too - this is causing me a lot of headaches.

**Comment by membrive** [comment]
After 2 days, no crashes with the development branch...

**Comment by klinquist** [comment]
I updated several servers that had segfaults on fri night, I can also report no crashes yet..

**Comment by soyuka** [comment]
@klinquist @membrive Still working? We'll publish it soon, we just need some more confirmations!

**Comment by klinquist** [comment]
Yes still working! Not a single segfault on the 4 servers I updated.

**Comment by Unitech** [comment]
AWESOME :) merging to master and publishing

**Comment by membrive** [comment]
I'm not running the development PM2 in production (with load), but I'm running it in four virtual machines (without load), and there is no segfaults in 4 days! I think that this feedback is not decisive but just for your information.

**Comment by Unitech** [comment]
PM2 0.14.4 with GC force removed published!

Please upgrade via (it keep your current process list):
 
```
$ npm install pm2 -g
$ pm2 update
```

**Comment by fernandoneto** [comment]
im getting the same problem.
kern.log
```
kernel: [677735.752265] PM2 v0.14.2: Go[1315]: segfault at 4ffffffa0 ip 000000000099e0d8 sp 00007fff5e747af0 error 4 in node[400000+fca000]
```
pm2.log
```
2015-07-28 17:05:47: Stopping app:example2 id:_old_0

(null):0
(null)

RangeError: Maximum call stack size exceeded
2015-07-28 17:05:47: Process with pid 29318 still not killed, retrying...
2015-07-28 17:05:47: Process with pid 29318 killed
2015-07-28 17:05:47: Starting execution sequence in -cluster mode- for app name:example id:1
2015-07-28 17:05:47: App name:example id:1 online
2015-07-28 17:05:50: Stopping app:example id:_old_1
2015-07-28 17:05:50: Process with pid 29343 killed
2015-07-28 17:05:50: Starting execution sequence in -cluster mode- for app name:example id:2
2015-07-28 17:05:50: App name:example id:2 online
2015-07-28 17:05:53: Stopping app:example id:_old_2
2015-07-28 17:05:53: Process with pid 29368 killed
2015-07-30 09:25:58: [PM2][WORKER] Started with refreshing interval: 30000
2015-07-30 09:25:58: [[[[ PM2/God daemon launched ]]]]
2015-07-30 09:25:58: BUS system [READY] on port /home/user/.pm2/pub.sock
2015-07-30 09:25:58: RPC interface [READY] on port /home/user/.pm2/rpc.sock
2015-07-30 09:30:08: Starting execution sequence in -cluster mode- for app name:example2 id:0
2015-07-30 09:30:08: App name:example2 id:0 online
2015-07-30 09:30:08: Starting execution sequence in -cluster mode- for app name:example id:1
2015-07-30 09:30:08: App name:example id:1 online
2015-07-30 09:30:08: Starting execution sequence in -cluster mode- for app name:example id:2
2015-07-30 09:30:08: App name:example id:2 online
```

**Comment by jshkurti** [comment]
That's because you're using PM2 v0.14.2.
Please upgrade to 0.14.5 :)

**Comment by fernandoneto** [comment]
@jshkurti already updated thanks
