### ISSUE TITLE
deploy: same app-name though different envs

### ISSUE THREAD

**Issue by ericberberich** [Unitech/PM2#1381]
I follow the strategy of [the advanced README](https://github.com/Unitech/PM2/blob/master/ADVANCED_README.md#deployment) having a production and test environment on the same server.

Starting 
    `pm2 deploy test`
works fine, and results in 
   `API             │ 13 │ fork │ 11278 │ online │         0 │ 0s     │  1.340 MB   │  enabled`
but when I then call
    `pm2 deploy production`
it deletes the 'test' API and starts the production API as 'API'. That is, as they have the same name, pm2 thinks they are the same, but they run with different NODE_ENV and thus with different port numbers on the same server.

Solution: prefix or postfix the 'name' with 'env'.

**Comment by Unitech** [comment]
Hello,

Please post this issue to: https://github.com/Unitech/pm2-deploy

Thanks

**Comment by emilsedgh** [comment]
As I mentioned on https://github.com/Unitech/pm2-deploy/issues/59#issuecomment-151353381 I think this is a problem with pm2, not pm2-deploy.
