### ISSUE TITLE
default save logs...

### ISSUE THREAD

**Issue by Ohen** [Unitech/PM2#1387]
pm2 logs save $HOME./pm2/logs...

this is so many charging to disk.. how to do turn off save logs ??

**Comment by soyuka** [comment]
Redirect output to `/dev/null` ?
```
pm2 start app.js -o /dev/null
```

**Comment by Unitech** [comment]
Use https://github.com/pm2-hive/pm2-logrotate or call `pm2 flush` via a cron task to flush all logs file
