### ISSUE TITLE
Remote Actions - permissions redux.

### ISSUE THREAD

**Issue by stefan1968** [Unitech/PM2#1389]
The remote actions permissions work, i.e users can't trigger remote actions, but developers and admin can, this is great, however I'd like to be able for users to see some remote actions. My scenerio is like this - i want some users to be able to trigger remote actions to get information back from the server, but don't want them to be able to trigger remote actions that accept a parameter (i.e can modify values in the server) a read-only mode if you like. Is this possible?

**Comment by Unitech** [comment]
Interesting, please repost this issue https://github.com/Unitech/keymetrics.io

Thanks!
