### ISSUE TITLE
PM2 open cmd every 5 seconds

### ISSUE THREAD

**Issue by StarpTech** [Unitech/PM2#1390]
Hi when I start my application with `pm2 start <file>` PM2 open a cmd window every ~5 seconds without any content and It is closed immediately.

Version: 0.14.2
Node: 0.12.2
Windows 8

**Comment by soyuka** [comment]
https://github.com/Unitech/PM2/issues/584#issuecomment-68558128

**Comment by morkai** [comment]
This issue can be resolved by spawning the `taskkill.exe` process through something like [`hideexec`](http://code.kliu.org/misc/hideexec/).

In the `lib/TreeKill.js` file replace [line 16](https://github.com/Unitech/pm2/blob/9ad8d3876deec52f27dbff2c72410788df3b5f43/lib/TreeKill.js#L16):
```js
exec('taskkill /pid ' + pid + ' /T /F');
```
with:
```js
spawn(__dirname + '/../bin/hideexec.exe', ['taskkill.exe', '/T', '/F', '/PID', pid]);
```
The `hideexec.exe` would need to be bundled with pm2.

**Comment by XMalatji** [comment]
This fix is still not working
