### ISSUE TITLE
PM2 authbind .bashrc alias not working

### ISSUE THREAD

**Issue by lgomez** [Unitech/PM2#1393]
Hi,

I was just setting up PM2 to handle deployments and have run into a problem that I narrowed down to be coming from the `alias pm2='authbind --deep pm2'` suggested [here](https://github.com/Unitech/PM2/blob/master/ADVANCED_README.md#allow-pm2-to-bind-applications-on-ports-80443-without-root) not being expanded in the session started by the pm2 deploy command's non-interactive shell.

I tried manually starting my script (testing with a simple expressjs server trying to run on port 80) on the remote host and it works. It only fails through the deploy command.

I prepended `type pm2` to the post-deploy command (`"post-deploy" : "type pm2 && npm i && pm2 startOrRestart ecosystem.json --env production"`) to see what it'd output and it showed `pm2 is /usr/bin/pm2` which confirms the alias is not being expanded.

Any ideas on how to solve this?

**Comment by Unitech** [comment]
Add a source ˜/.bashrc athe beginning of the `post-deploy` command and make sure you did pm2 update in your server

**Comment by lgomez** [comment]
@Unitech Thank you! That seems to have solved it.
