### ISSUE TITLE
feature request: pm2 ensure_running application.json

### ISSUE THREAD

**Issue by breathe** [Unitech/PM2#1397]
An 'ensure_running' command that accepted an application.json file and made sure all processes listed were running with correct arguments would be pretty cool -- the behavior I'm imagining:

```
for each process in application.json
- if process with <name> is not running, start it 
- if process with <name> is running and arguments have changed, stop process with <name>, start process <name> with new configuration
- otherwise -- process is already running with the correct arguments, nothing to do
```

Would make it simple to manage process lifespan through simple mutations of the json file.

**Comment by soyuka** [comment]
Try using pm2 programatically, this seems to be a lot overload.

**Comment by adrian-ludwig** [comment]
+1
This would be nice for deployments

**Comment by sholladay** [comment]
+1, I would use this.

**Comment by Unitech** [comment]
`pm2 startOrRestart application.json`
