### ISSUE TITLE
Running on OSX - Connection Refused

### ISSUE THREAD

**Issue by chromag9** [Unitech/PM2#1398]
When running PM2 in cluster or fork mode I can't connect to the app at all. I suspect I'm doing something stupid but it's just not working for me. I removed everything and start clean with only the following:

-   nvm 0.25.4
-   iojs 2.3.1
-   express 4.12.4
-   express-generator
-   PM2 0.14.2

That's it. I create a basic new express app and I've tried the following:
pm2 start app.js
pm2 start app.js -i 4

When I open my browser and go to the default URL (http://localhost:3000) I get connection refused. If I kill pm2 with a "pm2 kill" command and start up my app with "npm start" it works just fine.

I've checked $HOME/.pm2/pm2.log and the logs directory. Everything looks fine. If I check with a "pm2 monit" or "pm2 list" it says the apps are online.

I'm running OSX Yosemite.

**Comment by Unitech** [comment]
Can you paste the command under script -> start in your package.json?
