### ISSUE TITLE
Security: Reverse interaction protocol

### ISSUE THREAD

**Issue by masumsoft** [Unitech/PM2#1399]
How does pm2 make sure that the reverse interaction port is only accessible by keymetrics and not any other random attacker on the internet? If I want to allow only keymetrics to access the port using iptables, then i need to have the ip(s) of the reverse interaction server, but I didn't find any doc referring to this. 

Could anyone please shed some light on it?

**Comment by masumsoft** [comment]
@Unitech  Any thoughts regarding this?

**Comment by Unitech** [comment]
When doing a *remote action*, the data sent to your PM2 must be ciphered in AES256 with the public and private key you set at the `pm2 link` phase. Else the interaction agent just drop the packet.
