### ISSUE TITLE
Can ecosystem.js be a commonjs module (ecosystem.js)?

### ISSUE THREAD

**Issue by lgomez** [Unitech/PM2#1400]
Hi,

Is it possible to provide the acosystem file as a js module that returns json or do I need to move to doing things programmatically through the API?

Thank you,

**Comment by Unitech** [comment]
Yes it can be a JS file,

Cheers

**Comment by whitecolor** [comment]
I tried with `deploy` - it doesn't work
"pm2 deploy some/path/ecosystem.js production update"

expected?
