### ISSUE TITLE
pm2 crashe

### ISSUE THREAD

**Issue by wormen** [Unitech/PM2#1401]
welcome
pm2 updated to the latest version, and then see the following message

```
>>>> In-memory PM2 is out-of-date, do:
>>>> $ pm2 updatePM2
In memory PM2 version: 0.12.3
Local PM2 version: 0.14.2
```

**Comment by soyuka** [comment]
Normal behavior, update your in-memory pm2:
```
pm2 updatePM2
```

**Comment by wormen** [comment]
Yes, and I updated, after which this message is displayed

**Comment by soyuka** [comment]
Run `pm2 updatePM2`...
