### ISSUE TITLE
Will not start app in cluster mode on Windows Server 2008

### ISSUE THREAD

**Issue by pfatcat** [Unitech/pm2#1408]
Hello,
I am trying to use PM2 in cluster mode on a Windows Server 2008 R2 Standard 64-bit machine.
node v0.12.5  pm2 v0.14.2

pm2 start test.js starts the app successfully.

pm2 start test.js -i 2  or pm2 start test.js -i 0  does not.

I tried this fix with no success
https://github.com/Unitech/PM2/issues/868

![pm2](https://cloud.githubusercontent.com/assets/3833246/8457517/74f81a68-1fd7-11e5-81ef-406551ee16bf.PNG)

Thanks for your help with this issue.

**Comment by samc3322** [comment]
We have been digging into this issue. What we have been running into is an error thrown down in node (v0.12.5) on a app that tried to spin up a mssql connection on a named instance. While not certain the our best lead is that mssql connections use udp to negotiate a port. Apparently there is still a bug in node cluster.js where udp connections don't close.

If anyone has insight or can confirm this issue it may save someone a lot of heartache.

**Comment by samc3322** [comment]
P.S - Use PM2 with --no-daemon to get information piped to the console.

**Comment by andriecool** [comment]
I have the same issue running PM2 on Windows 7 machine. Any help would be appreciated

![screen shot 2015-07-13 at 4 01 31 am](https://cloud.githubusercontent.com/assets/192841/8640036/fc44f3e8-2913-11e5-94d0-075368a2e3c9.png)

**Comment by samc3322** [comment]
The issue we’ve experienced seem to be related to our app trying to connect to a mssql named instance. Basically there is still a issue inside one of node’s core features with cluster.js where udp connections do not get closed properly. Connecting to a named instance used udp to request connection information. In our case the app would start up and appear to be working from the PM2 console but almost immediately.

Currently we are running the in fork mode in the environments where we use a named instance for mssql. Other environments which we use a instance running on 1433 seem to work fine in cluster_mode.

I hope this helps. I lost about 2 days tracking down this issue.

Regards,
Sam

**Comment by gmahomarf** [comment]
See https://github.com/joyent/node/issues/9261
