### ISSUE TITLE
user count with pmx

### ISSUE THREAD

**Issue by zerataul** [Unitech/PM2#1410]
hi

we are develop monitoring service.
we are testing many user connections.
our purpose about 7,000 user.

so, there is the bug.

some process not show user count, forever.
we are use with pmx.

why not show??
somebody help me, please.

under image link.
![_2015_07_02_11_19_36_25](https://cloud.githubusercontent.com/assets/681056/8468900/4561cc28-20ad-11e5-8bfa-7bb638bea5e9.png)

**Comment by zerataul** [comment]
and this process mode is cluster.

**Comment by Unitech** [comment]
Can you do a `pm2 prettylist` and send us the result
