### ISSUE TITLE
getaddrinfo ENOTFOUND - pm2 1.14.3

### ISSUE THREAD

**Issue by seeden** [Unitech/PM2#1411]
Hi I can see this error with latest version 1.14.3, node 0.12.5, debian

www-user@vps:~/.pm2$ pm2 link xxxx yyyy
[Keymetrics.io] Using (Public key: xxxx ) (Private key: yyyy)
[Keymetrics.io][ERROR] Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
[Keymetrics.io] Contact support contact@keymetrics.io and send us the error message

**Comment by Unitech** [comment]
Try to do a ping www.google.com if it works we will continue to inspect,

**Comment by Unitech** [comment]
Feel free to re open the issue if you still have this problem
