### ISSUE TITLE
Deploy from within deployment environment (pull and forward?)

### ISSUE THREAD

**Issue by lgomez** [Unitech/pm2#1412]
Hi all,

I'm trying to create a github webhook handler within the same app being deployed. Basically, have the app listen for github pushes, check wether the push passes certain tests (like ensuring the branch is master, etc) and then execute the necessary PM2 commands to "self-deploy".

Deployments from my local dev environment work fine but I'm not sure what commands I would run on the server itself to mimic the same effect. I thought it'd be `pm2 pull <app> <commit>` followed by `pm2 forward <app>` but that does not seem to be working.

Any ideas?

**Comment by lgomez** [comment]
Oh... also, I don't just want to deploy a single app... I'd like to deploy all of them. But that's secondary. I could parse the ecosystem file and run that for every app in the worst case scenario.

**Comment by jshkurti** [comment]
Just `pm2 pull <app_name>` should do the trick.
