### ISSUE TITLE
PM2 startup with nvm

### ISSUE THREAD

**Issue by zettam** [Unitech/pm2#1413]
I've installed nvm and iojs.
I've installed npm on top of it. Default alias is set to use iojs.

Now I want to make pm2 autostart and use the "default" alias. when I type the command

```
pm2 startup
```

I get the error

```
You have to run this command as root. Execute the following command:
sudo env PATH=$PATH:/home/nodeuser/.nvm/versions/io.js/v2.3.2/bin pm2 startup linux -u nodeuser
```

and I get it, but the issue is that this is setting pm2 to use the specific version of node through nvm. Is there any way to make pm2 use the default version that's set in nvm?

**Comment by muji8u** [comment]
i've had a ton of issues with nvm. i know this isn't really a solution but i just removed node and installed the correct version of node i needed

**Comment by zettam** [comment]
I have to use nvm though, it's a part of my workflow

**Comment by Unitech** [comment]
Is there any default NVM path (to get the current selected node.js version with NVM)? Never found it

**Comment by htolic** [comment]
sudo env PATH=$PATH:`dirname $(nvm which default)` pm2 startup linux -u nodeuser

**Comment by soyuka** [comment]
@Unitech : 
```
(master ✗)❯ echo $NVM_PATH
/home/soyuka/.nvm/versions/node/v0.12.2/lib/node

(master ✗)❯ echo $NVM_BIN
/home/soyuka/.nvm/versions/node/v0.12.2/bin
```

**Comment by Oliboy50** [comment]
UP

**Comment by Unitech** [comment]
Closing in favor of #2559 

To try the new startup system:

```bash
$ npm install Unitech/pm2#development -g
$ pm2 update
```

```bash
$ pm2 startup     # Then copy / paste the command displayed
$ pm2 unstartup
```

**Comment by adrienjoly** [comment]
I got `spawn node ENOENT` and `TypeError: One of the pids provided is invalid` errors when trying to (re)start my app, after removing an old version of Node.js using `nvm uninstall vX.XX.XX`.

I fixed it by adding `--interpreter=$(nvm which default)` to `$ pm2 start app.js`. 🎉

Thank you @htolic and @axi (https://github.com/Unitech/pm2/issues/3648#issuecomment-1381662195) for the hints! 🙌
