### ISSUE TITLE
pm2 deploy ecosystem.json5 production setup －－－－ stop at this code,why?

### ISSUE THREAD

**Issue by chelsh** [Unitech/PM2#1414]
stop at:"Cloning into ....."

**Comment by chelsh** [comment]
![1](https://cloud.githubusercontent.com/assets/10752360/8506250/77f72872-223d-11e5-9a2a-1e4838fd5f9f.jpg)

**Comment by chelsh** [comment]
when i run the command：git clone ＊.git    in the target machine,it is ok

**Comment by Unitech** [comment]
Have you solved this issue?

Closing it here as it's related to pm2-deploy, feel free to repost the issue

https://github.com/Unitech/pm2-deploy
