### ISSUE TITLE
Logrotate integration

### ISSUE THREAD

**Issue by scaryguy** [Unitech/PM2#1415]
Hi there,

Recently I've experienced an edge case with PM2 log files. My server's storage was full because of my application's PM2 log file -which was 25GB in size :fearful: As a result, the application stopped working. I think this is something serious that should be considered when setting up default behavior with collecting log files.

I guess integration with logrotate can be an option. Just like nginx. As you probably know, nginx -by default- uses logrotate to compress and remove old log files. IMHO PM2 should have something similar which would prevent edge cases like I experienced. 

Thanks!

**Comment by jshkurti** [comment]
https://github.com/pm2-hive/pm2-logrotate

**Comment by scaryguy** [comment]
Actually I was talking about something like this: https://www.digitalocean.com/community/tutorials/how-to-manage-log-files-with-logrotate-on-ubuntu-12-10

**Comment by soyuka** [comment]
What keeps you of adding a logrotate yourself? You can change log paths or
use the default one `~/.pm2/logs`. You can also disable them if you're
handling them in your app. To do this redirect out and err logs to
`/dev/null`.

**Comment by carnesen** [comment]
+1. I'm relying on pm2 for most of my log handling needs, and it'd be swell
if log rotation and archiving also "just worked" by default. That
pm2-logrotate project isn't a production-quality solution IMO. Basically it
just does a synchronous read, write, truncate, which I'd expect would lead
to data loss. The real-deal logrotate does some pretty fancy stuff to make
sure the cutover is seamless. Perhaps the feature here could be a command
that installs an OS-appropriate logrotate configuration, similar to "pm2
startup" but "pm2 logrotate". Of course nothing prevents anyone from doing
this themselves. It'd just be slick to have it integrated into pm2 since it
already does so much stuff around logs.

**Comment by soyuka** [comment]
`startup`-like commands are hard to maintain because they depend on the OS behind. On debian, logrotate just takes one configuration file to `/etc/logrotate.d/pm2`:

```
/home/myuser/.pm2/logs/*.log {
        weekly
        missingok
        copytruncate
        rotate 12
        compress
        notifempty
}
```

Are you really too lazy for that?

**Comment by carnesen** [comment]
Wanting my process management software to make my life easier doesn't make
me lazy. That's actually it's only job. There are like a dozen different
pieces of information behind what you wrote (the fact that logrotate is a
program that ships with most linux distros, where its config files go, what
their format is, where the pm2 log files are ...). Everything is easy once
you know the answer.

**Comment by soyuka** [comment]
I'd add that pm2 could never have logrotate options that fit everyone needs. 

@Unitech any thoughts on this?

**Comment by carnesen** [comment]
Sure, like Nginx it would just use some reasonable defaults that work fine
for most.

**Comment by scaryguy** [comment]
I'm totally agree with @carnesen .

@soyuka , it's not about "me" dude, it's about PM2. Do you want every PM2 user to be having the same concern or spending time for setting this themselves?  I do think that, PM2 has to have logrotate integration. Because it's very likely for any developer to face disk capacity issues and/or unexpected service interruptions because of this "missing feature" in PM2.

**Comment by Tjatse** [comment]
Why're you guys using txt logs in production env, my advise: 
- bucker (UDP logstash client, non-blocking)
- logstash (collect, parse and transform logs)
- ElasticSearch (big data, DB)
- Kibana (UI, DA, data mining, search logs)

And you can totally abandon PM2 logs.

![1](https://cloud.githubusercontent.com/assets/1418444/8610134/dd59c7f4-26e0-11e5-8264-1ada4f00aa58.png)
![2](https://cloud.githubusercontent.com/assets/1418444/8610135/dd840a0a-26e0-11e5-82bb-9ec0767319ce.png)

**Comment by soyuka** [comment]
Can someone test the logrotate command?

`npm i -g Unitech/PM2#logrotate`

**Comment by scaryguy** [comment]
Thanks for adding the feature @soyuka ! I run logrotate command and configuration template was copied to my ubuntu box's `/etc/logrotate.d/` directory successfully. 

Maybe an addition could be done to this feature: current logrotate configuration imports ALL `.log` files inside the `.pm2/logs` directory. This means the logs for all applications run on the same machine are imported all together. A separate conf file for each application would be nice which makes each applications logs separate. Just an idea!

Thanks again!

**Comment by soyuka** [comment]
> Maybe an addition could be done to this feature: current logrotate configuration imports ALL .log files inside the .pm2/logs directory. This means the logs for all applications run on the same machine are imported all together.

I haven't understand. Are you saying that logs are concatenated together? To me it seems that the configuration is applied to each file independently.

I'll set the logrotate configuration when pm2 init itself instead of adding a command.

**Comment by scaryguy** [comment]
Uhmm.. Maybe you are right. I'm not sure about what I guess.

init'ing is a great idea!
