### ISSUE TITLE
Segfault on different machines with Ubuntu Server 14.04

### ISSUE THREAD

**Issue by membrive** [Unitech/PM2#1417]
PM2 0.14.3 crashes in two different machines with Ubuntu 14.04.2 (with different kernels versions), Node.js 0.12.4 and also Node.js 0.12.6, with the following syslogs:

- kernel version 3.10.23-xxxx-std-ipv6-64-vps:

kernel: [52527.982907] show_signal_msg: 51 callbacks suppressed
kernel: [52527.982910] PM2 v0.14.3: Go[1192]: segfault at 16ffffffa0 ip 00000000009036f8 sp 00007ffc57e9b550 error 4 in nodejs (deleted)[400000+b61000]

- kernel version 3.13.0-57-generic:

kernel: traps: PM2 v0.14.3: Go[3491] general protection ip:99e0d8 sp:7fffc3fbae00 error:0 in node[400000+fca000]

It's the same issue than https://github.com/Unitech/PM2/issues/1380, but it is now closed. Any clue to solve this issue? I will try different things and I will reply if I have results.

**Comment by jshkurti** [comment]
https://github.com/Unitech/PM2/issues/1380 Duplicate

**Comment by jshkurti** [comment]
Sorry, but this bug isn't directly related to PM2.

https://github.com/joyent/node/issues/2376
