### ISSUE TITLE
startup command kill all running processes and not restart them

### ISSUE THREAD

**Issue by huiyiqun** [Unitech/pm2#1418]
Platform:

```
pm2 --version: 0.14.3
node --version: v0.10.36
system: CentOS 7
```

I'm trying to deploy our distributed system with `ansible` and `pm2`, I start process(of course using `ansible`):

```
pm2 start main.coffee
```

and ensure it startup on boot:

```
pm2 startup systemd
```

But, as I can see, the running process is killed and never restarted.

According to the output, I infer that pm2 do following:

```
pm2 dump && pm2 kill && systemctl daemon-reload && systemctl enable pm2 && systemctl start pm2
```

But the problem is `pm2.service` has been started from last running. so that `systemctl start` do nothing.

I have not gotten a graceful solution, but I think there may be.

**Comment by Unitech** [comment]
Closing in favor of #2559 

To try the new startup system:

```bash
$ npm install Unitech/pm2#development -g
$ pm2 update
```

```bash
$ pm2 startup     # Then copy / paste the command displayed
$ pm2 unstartup
```
