### ISSUE TITLE
Installation Failed on Windows 8 

### ISSUE THREAD

**Issue by ZeroHackeR** [Unitech/PM2#1420]
C:\>npm install pm2 -g
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "pm2" "-g"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Cannot read property 'trim' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "pm2" "-g"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Uncaught, unspecified "error" event.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log

**Comment by ZeroHackeR** [comment]
I just fixed it:

- Go to your node installation folder (eg: C:\Program Files\nodejs)
- Right Click on "node.exe" 
- Choose "Compatibility" tab
- Run this program as an administrator 

Then in cmd execute:
```npm cache clean```

Then, execute 
```npm install pm2 -g```

**Comment by ZeroHackeR** [comment]
Not fixed!!! 

I don't know what went wrong 

```
D:\Dropbox\Projects\API>pm2 start app.js
fs.js:747
  return binding.mkdir(pathModule._makeLong(path),
                 ^
Error: ENOENT, no such file or directory 'D:\Users\xxx\.pm2'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:747:18)
    at Object.CLI.pm2Init (C:\Users\xxx\AppData\Roaming\npm\node_modules\
pm2\lib\CLI.js:39:8)
    at Object.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\
pm2\bin\pm2:21:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
``

**Comment by marklagendijk** [comment]
Currently pm2 fails when executing from a drive other than `C:`. See [this issue](https://github.com/Unitech/PM2/issues/1251#issuecomment-121086243).
