### ISSUE TITLE
pm2 stop / pm2 kill stucks, [PM2][ERROR] Process 2 not found

### ISSUE THREAD

**Issue by PavelPolyakov** [Unitech/PM2#1421]
Hi,

I did something with my pm2 instance, so when I call these:
```
pm2 stop
```

or 
```
pm2 kill
```

it doesn't work, just stucks.
The pm2 process were finished not in the normal way.

When I try to launch a copy of the application:
![image](https://cloud.githubusercontent.com/assets/839290/8569962/233aa2a8-257d-11e5-9dde-e265275e0d94.png)

I see:
[PM2][ERROR] Process 2 not found

How can I solve the issue without restarting the server? Which pm2 commands should I use? How can I restart only the pm2 instance?

Regards,

**Comment by jshkurti** [comment]
Which version of PM2 and Node have you been using ?

`pm2 dump; pm2 kill; npm i -g pm2; pm2 resurrect` should do the trick.

**Comment by PavelPolyakov** [comment]
I had 0.12 , currently updated and restarted the whole server at the end.
Another interesting thing was, that pm2 had problems for one user, but for the rest it worked fine.
