### ISSUE TITLE
PM2 node scripts restarting without being able to read environment variables

### ISSUE THREAD

**Issue by klinquist** [Unitech/PM2#1427]
On many of my servers since upgrading to the latest PM2, my scripts may restart and not be able to read the environment variables in /etc/environment.

I run pm2 as user 'ubuntu'  (pm2 startup ubuntu -u ubuntu).

I notice that in ~/.pm2,   pm2.pid, pub.sock, and rpc.sock are owned by ubuntu:root  instead of ubuntu:ubuntu, I don't know if this is the cause.

**Comment by klinquist** [comment]
I may have found one possible issue, it looks like pm2-init.sh is setting PM2_HOME to /root/.pm2.   I am expecting it to be /home/ubuntu/.pm2.

**Comment by vikrantlabde** [comment]
the pm2-init.sh is not generated even after startup command. any pm2 command is not showing any error or output. Stange. 

![screen shot 2015-07-10 at 8 55 16 pm](https://cloud.githubusercontent.com/assets/433298/8621939/062555a8-2746-11e5-8ed7-1a537f0ed7d0.png)

**Comment by vikrantlabde** [comment]
Its havent even generated folder ~/.pm2

**Comment by Unitech** [comment]
@klinquist there is permission problems, please do `pm2 kill`,  delete your ~/.pm2 and start pm2 again under ubuntu user

@vikrantlabde can you execute these command by adding DEBUG="*" front of each commands and paste the output here?

**Comment by klinquist** [comment]
The source of this was actually https://github.com/Unitech/PM2/issues/1380
