### ISSUE TITLE
PM2, express, memory issue

### ISSUE THREAD

**Issue by pvlbzn** [Unitech/PM2#1428]
Dear all,

I run into problem with memory. My application grows in memory as hell after requests.

<code> $ pm2 start app.js </code>

![initial](https://cloud.githubusercontent.com/assets/9218794/8626487/bcb7ed10-274d-11e5-8468-63a970a84469.jpg)

First request from browser:

![first_req](https://cloud.githubusercontent.com/assets/9218794/8626631/55c6152c-274e-11e5-9499-d87589260964.jpg)

Well,
<code> wrk -c 100 -d 100 http://127.0.0.1:8080 </code>

![after_test](https://cloud.githubusercontent.com/assets/9218794/8626702/b749fb6a-274e-11e5-8590-58b7adf4b151.jpg)

And in one small application...

![memo](https://cloud.githubusercontent.com/assets/9218794/8626715/ca8db0ae-274e-11e5-9d45-415c35bb0c9d.jpg)

I have noticed that memory rises not linear. It dramatically rises on like 50mb in a seconds, after that it hangs on one value, and repeat. And actually it isn't garbage collected after a while. Now memory just freezes on 195mb.

Am I doing something very bad or wrong (Im novice, but app created by express and isn't much changed in backend)? Or this is kind of normal behavior.. ?

Thanks in advance! Cheers!

**Comment by airs0urce** [comment]
Did you try to run same test without pm2? 
I tried with Apache Bench and thought that express.js has memory leak. 
But later I run node with --expose-gc flag and call garbadge collector manually in code:
global.gc(); 

And I saw that this is not memory leak but the way how node manage memory.
So, I think your case is normal behavior.

**Comment by pvlbzn** [comment]
airs0urce, thanks for your reply.

A did additional tests. Before tests pm2 was deleted and server was rebooted.

Starting just Node:
<code>$ node app.js</code>
<code>app listening at :8080</code>

Memory was checked by:
<code>$ ps au</code>
Where initial state was
<code>user    1086  0.2  9.8 648832 49524 pts/0    Sl+  03:00   0:01 node app.js</code>
Where is 4th value goes for % of memory. My server has ~500mb.

<code>$ free -m</code>
<code>total 490  |  used 181  |   free 308</code>

Run the same test on the same app, without PM2
<code>$ wrk -c 100 -d 100 http://127.0.0.1:8080</code>

Behavior of memory was 'clean'. It just jump to a value and stick with it to the end of the test:
<code>$ ps au</code>
<code>user    1086 15.8 27.2 716712 136772 pts/0   Rl+  03:00   1:36 node app.js</code>
simplyfied: <code> $ ps au  // - 27.2% </code>

<code>$ free -m</code>
<code>total 490  |  used 279  |   free 210</code>

<b>Result:</b>
PM2:
Actually I can clearly say numbers because memory just grows all the time in a bit weird way. After the wrk test my server left with 30mb free memory out of ~490, and memory continued to grow.

Without PM2:
<code>initial state, running node:  9.8%   ||  48.02mb</code>
<code>running test on the node:  27.2%  ||  122.28mb</code>

Second test was run without any changes in memory.

Call and test with --expose-gc flag won to my server 1%

Thanks!

**Comment by Unitech** [comment]
Node.js version?
PM2 version?

You did `$ pm2 start app.js` but relating your screenshot it started in cluster mode but should be in fork mode

**Comment by jshkurti** [comment]
@airs0urce said everything. I noticed this behaviour some times ago. This is not a leak, it's normal.
PM2 may actually some overhead since it monitors the http requests & stuff but still not a memory leak :)
