### ISSUE TITLE
PM2 Segfault

### ISSUE THREAD

**Issue by klinquist** [Unitech/PM2#1429]
AWS, Ubuntu 14.04.02 LTS with the latest updates.
Problem experienced with
Node 0.12.2, 0.12.5, 0.12.7,
PM2 0.14.1, 0.14.3

Problem experienced  on multiple servers.  Almost randomly  every few days, my node scripts seem to restart "internally" (pm2 does not report a restart) and can't read env variables when they do so, so they don't connect to our database.

/var/log/syslog shows this:

kernel: [48101.205004] PM2 v0.14.3: Go[1125]: segfault at ffffffffffffffa0 ip 000000000099f6c8 sp 00007ffe1770b350 error 5 in node[400000+fcc000]

**Comment by klinquist** [comment]
Nevermind, looks like a duplicate/already reported issue.

**Comment by soyuka** [comment]
#1380
