### ISSUE TITLE
post_update doesn't execute

### ISSUE THREAD

**Issue by overlookmotel** [Unitech/PM2#1431]
`"post_update": ["./build.sh"]` in a `.json` file doesn't execute the script.

I've got a file called `pm2.json` in the root of my repo. That file includes the line `"post_update": ["./build.sh"]`. I start the app with `pm2 start pm2.json`.

But when I pull from Keymetrics, the `build.sh` script doesn't run.

I also tried putting it in `package.json` as advised in https://github.com/Unitech/PM2/issues/1328, but that doesn't seem to work either.

In any case, being able to put the `post_update` attribute in the JSON file that is passed to pm2 would be better, and as described in the docs.

I'm having this problem on Debian v7.7, pm2 v0.14.3

If this feature worked, it would make Keymetrics a total winner for me - one-click build and deploy!

**Comment by jshkurti** [comment]
Adding simply the post_update field in your package.json doesn't do the trick.
You have to add at least these fields : 

```
  "apps" :
  [
    {
      "name"               : "your_app_name",
      "post_update"        : ["./build.sh"],
    }
  ]
```

**name** must match with your running app

**Comment by jshkurti** [comment]
https://github.com/Unitech/PM2/blob/master/doc/PULL.md

**Comment by jshkurti** [comment]
Any updates on this issue ? @overlookmotel

**Comment by wmertens** [comment]
@jshkurti also not happening for me, I have this in package.json:

```
  "apps": [{
    "name": "www",
    "script": "lib/server-production.js",
    "autorestart": true,
    "post_update": ["npm run build"]
  }],
```

and I started the app with `pm2 start package.json`.

`pm2 pull www` just pulls and restarts.

**Comment by overlookmotel** [comment]
Just to say that this now works for me with the solution given above.

Thanks for your help.

**Comment by bbnnt** [comment]
@jshkurti, I this a normal behaviour nor having @wmertens' post_update to work ?

**Comment by zcutner** [comment]
Hello, I believe I am experiencing this same issue. The solution by @jshkurti works for me however, I do not want to include the PM2 configuration in my package.json.

When starting PM2 from a process.json file, the `post_update` commands only appear to be executed if the process.json file is in the project root. When it is outside (as I would like it to be) the `post_update` commands are not executed, even when using the `cwd` property.

I would be grateful if the issue could be reopened as I am still experiencing this same bug. Thanks.
