### ISSUE TITLE
PM2 stop frequently and stop the app

### ISSUE THREAD

**Issue by chelsh** [Unitech/PM2#1433]
PM2: 2015-07-13 14:13:22: [PM2][WORKER] Started with refreshing interval: 30000

PM2: 2015-07-13 14:13:22: [[[[ PM2/God daemon launched ]]]]

PM2: 2015-07-13 14:13:22: BUS system [READY] on port /home/ubuntu/.pm2/pub.sock

PM2: 2015-07-13 14:13:22: RPC interface [READY] on port /home/ubuntu/.pm2/rpc.sock

**Comment by chelsh** [comment]
pm2 version:0.14.0
node version:v0.12.0

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/8643843/a3a84e26-296b-11e5-849d-5b319c8d2153.png)

**Comment by chelsh** [comment]
often automatically all services shutdowned in production server.

**Comment by chelsh** [comment]
$ uname -a
Linux  3.13.0-55-generic #92-Ubuntu SMP Sun Jun 14 18:32:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by soyuka** [comment]
#1424 #1380 please read those and provide the same logs there

**Comment by chelsh** [comment]
pm2 v0.14.3 have resolved this problem?
