### ISSUE TITLE
Using restart or --watch leads to looping error: EADDRINUSE

### ISSUE THREAD

**Issue by ucabzh0** [Unitech/PM2#1438]
When use ```pm2 start .\server.js```, everything works cool.

But when use ```pm2 restart 0``` to restart the server, the server begin to looping restart with error: EADDRINUSE (found in the log).

Same case happened if I use ```pm2 start .\server.js --watch``` to start the server.

It looks when restart the server, the port is still in use. 
I also try to set PM2_KILL_TIMEOUT to larger value, but nothing happened:(

Versions: 
pm2@0.14.3
node@0.12.7

Does any one have idea on the issue?

**Comment by lmf** [comment]
I have the same problem, I think pm2 start all workers in a port.  it can be control in code

**Comment by marciovicente** [comment]
I catch the same error when use: `pm2 start server.js --name "app" --interpreter ./node_modules/.bin/babel-node --watch` :(

**Comment by soyuka** [comment]
OS ?

**Comment by marciovicente** [comment]
@soyuka, OS X. I check that some files (e.g. Node modules) was with wrong timestamp. So I used `touch` to  fix tem, and now it's works fine.

**Comment by soyuka** [comment]
Closing this. Please see https://github.com/Unitech/PM2/issues/1062 if there is a solution for further issues.

**Comment by MilknCookie** [comment]
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at EventEmitter.app.listen (D:\htdocs\dev\nodejsserver\lib\node_modules\express\lib\application.js:595:24)
    at Object.<anonymous> (D:\htdocs\dev\nodejsserver\server.js:47:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
events.js:85
      throw er; // Unhandled 'error' event


var pm2 = require('pm2');

pm2.connect(function() {
  pm2.start({
        script    : 'D:\\htdocs\\dev\\nodejsserver\\server.js',
	    node_args : "--harmony",
        env: {
            "NODE_ENV": "development",
        },
        watch:['D:\\htdocs\\dev\\nodejsserver','D:\\htdocs\\gagal06\\','D:\\htdocs\\lacfr05\\'],
        ignore_watch : ["node_modules", "public","cell.json","test",".hg"],
        min_uptime:"15s"
    },function(err, apps) {
        pm2.disconnect();
    });
});

when there is a lot of change going and pm2 keep restarting eventualy he goes on a loop of already used and he is not able to kill the server process.

**Comment by ZeroHackeR** [comment]
+1 on windows server
