### ISSUE TITLE
is there any option to set the restart interval?

### ISSUE THREAD

**Issue by rangercyh** [Unitech/PM2#1439]
I want let my process not to restart inmediately, is there any option or solution in pm2 to let me do this?
I know about min_uptime and max_restart options's meaning. can you help me? @jshkurti

**Comment by carnesen** [comment]
This feature has been requested but not yet implemented. https://github.com/Unitech/PM2/issues/498

**Comment by soyuka** [comment]
Thx @carnesen closing this as duplicate.

**Comment by jshkurti** [comment]
Here we go.
`pm2 start app.js --restart-delay 4000` (delay is in milliseconds)
or in JSON declaration:
```json
  "restart_delay" : "4000"
```

Avaible on #development for now, soon to be published :)

https://github.com/Unitech/PM2/commit/12261c6b4ae17e69bc0721c9a68167731b26ba4b

**Comment by rangercyh** [comment]
thx:D
