### ISSUE TITLE
How to integrate PM2 analysis in a custom website?

### ISSUE THREAD

**Issue by vabatta** [Unitech/PM2#1442]
Hi all,

I would like to know if there is someway to integrate the PM2 analysis of my node app in order to add it to  some basic information (like CPU / RAM / HDD info) in my custom admin dashboard without be forced to give admins another access to an external site (like [keymetrics.io](https://keymetrics.io/)).

I gave a quick look in the documentation but I didn't found nothing.

Thanks!

**Comment by soyuka** [comment]
https://github.com/Unitech/PM2/blob/master/doc/PROGRAMMATIC.md ?

**Comment by vabatta** [comment]
Yes, saw that but I don't understand if there is any method to get accurate info directly in node, or if with RPC I should send ```log``` commands and parse them...

**Comment by soyuka** [comment]
You can watch the `process:event` event for example and retreive anything you want from the process.

```javascript
pm2.launchBus(function(err, bus) {
  bus.on('process:event', function(e) {
    //do something with the event
  })
})
```

The object you retreive will look like this:

```
{ event: 'exit',
  manually: false,
  process:
   { name: 'throw',
     vizion: true,
     autorestart: true,
     exec_mode: 'fork_mode',
     exec_interpreter: 'node',
     pm_exec_path: '/usr/share/nginx/www/pm2-notify/throw.js',
     pm_cwd: '/usr/share/nginx/www/pm2-notify',
     instances: 1,
     node_args: [],
     pm_out_log_path: '/home/abluchet/.pm2/logs/throw-out-0.log',
     pm_err_log_path: '/home/abluchet/.pm2/logs/throw-error-0.log',
     pm_pid_path: '/home/abluchet/.pm2/pids/throw-0.pid',
     NODE_APP_INSTANCE: 0,
     NODE_ENV: 'production',

     ... //your env variables here

     status: 'stopped',
     pm_uptime: 1434096604224,
     axm_actions: [],
     axm_monitor: {},
     axm_options: {},
     axm_dynamic: {},
     vizion_running: false,
     created_at: 1434096545628,
     pm_id: 0,
     restart_time: 19,
     unstable_restarts: 0,
     started_inside: false,
     command:
      { locked: false,
        metadata: {},
        started_at: null,
        finished_at: null,
        error: null },
     versioning: null,
     exit_code: 1 },
  at: 1434096607294 }
```

You can also take a look at @Tjatse  pm2-gui module : https://github.com/Tjatse/pm2-gui.

**Comment by vabatta** [comment]
Okay thanks! I will look at @Tjatse pm2-gui module, and pull out what I need.

Anyway @soyuka, some more documentations about the data of events would be great, no?

**Comment by soyuka** [comment]
@vabatta not really needed, pm2 programmatically is simply using CLI.js, just read the code there if you need docs ^^. I think that @Tjatse is using the pm2 bus with `axon` and `axon-rpc` to talk and retreive informations from pm2.

**Comment by sholladay** [comment]
I am sad about the lack of docs for this stuff. Can you imagine having to read the code every time you wanted to learn an API?

**Comment by balboliu** [comment]
@soyuka  why the "manually"  is false when I run `pm2 stop name` ? when the "manually" will be true?

**Comment by soyuka** [comment]
@balboliu I really don't know it should be manually if you ran that through cli imo
