### ISSUE TITLE
Not working with babel-node

### ISSUE THREAD

**Issue by LeiZeng** [Unitech/PM2#1444]
Hi guys,

I try to use PM2 on my project which is in ES6, met a lot of trouble and please help me get some anwser: 
1. Why we have to use babel-node under iojs? It's not a dependency of babel.
2. When PM2 start a script, it forks a worker but find the source of the soft link, here is a e.g.:
  I have start a script like this(under iojs):
  ```bash
  pm2 start app.js --next-gen-js
  ```
  I will get two process:
  ```bash
  node /path/to/babe-node/cli app.js
  /path/to/iojs/cli /path/to/node_modules/babel-node/lib/_babel-node app.js
  ```
  In this case, when the process restart, the 'port in use' error alway throw.

**Comment by leozdgao** [comment]
I met the relevant issue. I use `pm2 start app.js --next-gen-js` too, and it always show `errored` without any error messages, but I use `babel-node app.js` directly, it works. I'm confusing.

**Comment by soyuka** [comment]
From what I understand you can either:
- run an ES6 script with babel-node, using nodejs in `fork_mode`
- run an ES6 script in cluster mode only with iojs

Note that on cluster mode we call the [register hook](
 https://github.com/Unitech/PM2/blob/e26aa9df8cf3b6e6214085a91e0281ffce5d4e41/lib/ProcessContainer.js#L101).

@Unitech am I missing something here?

**Comment by CD1212** [comment]
I'm also having issues (as of today) using babel-node through PM2. From my PM2 logs, the relevant issue appears to be:

```
Starting execution sequence in -fork mode- for app name:server id:0
PM2: 2015-07-22 06:07:14: App name:server id:0 online
PM2: 2015-07-22 06:07:14: Error: spawn /usr/local/lib/node_modules/pm2/node_modules/babel/bin/babel-node ENOENT
```

The file `/usr/local/lib/node_modules/pm2/node_modules/babel/bin/babel-node.js` definitely exists. Almost as though PM2 isn't correctly detecting the .js extension.

I don't know if this is related to OP's issue, or if anyone has any help to offer. If not sorry to hijack this issue.

**Comment by Unitech** [comment]
Thanks!

https://github.com/Unitech/PM2/blob/master/constants.js#L29

**Comment by soyuka** [comment]
@CD1212 may you try the development branch to see if it fixes the ENOENT issue?

**Comment by CD1212** [comment]
Perfect, that has fixed the issue for me. Thanks @soyuka and @Unitech
