### ISSUE TITLE
pm2 startup on darwin doesn't make sure LaunchAgents directory exists

### ISSUE THREAD

**Issue by hideov** [Unitech/PM2#1450]
When calling `pm2 startup` from osx, pm2 tries to create `/Users/<user>/Library/LaunchAgents/io.keymetrics.PM2.plist`.
If LaunchAgents was not created before, pm2 emits an exception 
>Error: ENOENT: no such file or directory, open '/Users/administrator/Library/LaunchAgents/io.keymetrics.PM2.plist'
>    at Error (native)
>    at Object.fs.openSync (fs.js:549:18)
>    at Object.fs.writeFileSync (fs.js:1155:15)
>    at Object.CLI.startup (/usr/local/lib/node_modules/pm2/lib/CLI.js:594:8)
>    at Command.<anonymous> (/usr/local/lib/node_modules/pm2/bin/pm2:476:9)
>    at Command.listener (/usr/local/lib/node_modules/pm2/node_modules/commander/index.js:301:8)
>    at emitTwo (events.js:87:13)
>    at Command.emit (events.js:172:7)
>    at Command.parseArgs (/usr/local/lib/node_modules/pm2/node_modules/commander/index.js:610:12)
>    at Command.parse (/usr/local/lib/node_modules/pm2/node_modules/commander/index.js:458:21)

The solution is to `mkdir ~/Library/LaunchAgents`.

**Comment by soyuka** [comment]
Thanks for the report.
