### ISSUE TITLE
pm2 stop does not stop process that ignores SIGINT

### ISSUE THREAD

**Issue by alpacagh** [Unitech/PM2#1451]
pm2 can not stop process that ignores SIGINT signal.
Moreover, it shows that process is actually stopped (!) while it is still running.

Example script:

``` js
// sauron.js
"use strict";
var ignore = function() { console.log('Got SIGINT, ignoring') };
process.on('SIGINT', ignore);
setInterval( function() { console.log('tick') }, 1000 );
```

``` bash
$ pm2 start sauron.js # started
$ pm2 stop 1 # seems stopped, but..
$ ps axfu | grep sauron # shows that process is running and
$ pm2 logs 1 # is showing us live logs of this process
```

This behavior is explicitly described in lib/God/ActionMethods.js:263 God.stopProcessId :: kill_anyway = function(proc)
looks like "nah, it will die anyway sometime.."

**Comment by soyuka** [comment]
We kill the process [here](https://github.com/Unitech/PM2/blob/master/lib/God/Methods.js#L224) and we're sending a `SIGINT` signal. So yes, if you're ignoring the signal it won't stop but pm2 will think it has. 

What would be your expected behavior here? Do you want pm2 to warn that the process can't be killed by keeping it available?

**Comment by alpacagh** [comment]
First of all, do not mark it as stopped. 
Easiest is to leave it in 'running' state with error message in pm2 log, more complex is to mark its status as 'can not stop', so I could see it within interface.

Other (configurable in json, eg `kill_timeout`?) behavior is to send a SIGKILL after some timeout (and if sigkill did not kill that process, do not mark it as stopped).

**Comment by jshkurti** [comment]
Good point @alpacagh 
I will work on this soon.

**Comment by jshkurti** [comment]
Here we go :)

https://github.com/Unitech/PM2/commit/c6353eaee82c038b9698ddd8ce9876a036a2b72c

**Comment by jshkurti** [comment]
Now PM2 sends SIGKILL after KILL_TIMEOUT milliseconds if SIGINT wasn't effective.
If SIGKILL doesn't work either, the status will be ERRORED and PM2 logs are pretty verbose about it

**Comment by fabienvauchelles** [comment]
Could it be added to the .json5 ?
Thanks
