### ISSUE TITLE
PM2 restarting my app regularly

### ISSUE THREAD

**Issue by klinquist** [Unitech/pm2#1461]
I do NOT have watch enabled, I do not have any memory limits enabled... but I am seeing this constantly:

PM2 Stopping app:my-app id:7
PM2 App name:my-app id:7 exited with code SIGTERM
PM2 Process with pid 28954 killed
PM2 Starting execution sequence in -fork mode- for app name:my-app id:7
PM2 App name:my-app id:7 online

Any ideas how to debug why PM2 is restarting it?  PM2 is running several other scripts on the same instance with the same settings and they're running just fine.

**Comment by klinquist** [comment]
This is a very little app using almost no resources, PM2 monit shows this:
```
 ● my-app                         [                              ] 0 %
[7] [fork_mode]                        [||||||||                      ] 44.242 MB  
```

**Comment by soyuka** [comment]
Everything fine in your app logs?

FIY pm2 sends a `SIGINT` signal to kill apps. I doesn't see why it'd send a `SIGTERM` :/.

**Comment by klinquist** [comment]
Nothing is showing up in my logs, only the message from express "listening on *:7000"  every time it restarts.

When I run it without PM2 it runs forever.

I'm starting it via a simple json declaration file:
{ "apps": { 
              "name":   "my-app",
              "script": "./server.js",
              "cwd":    "/data/myapp",
              "watch":  false
}

**Comment by klinquist** [comment]
Actually... that might not be correct.  Grep'd through the whole folder and found


node_modules/babel/node_modules/babel-core/node_modules/source-map-support/test.js:    'process.on("uncaughtException", function (e) { console.log("SRC:" + sms.getErrorSource(e)); });',

node_modules/babel/node_modules/babel-core/node_modules/source-map-support/source-map-support.js:      process.on('uncaughtException', handleUncaughtExceptions);


Will continue to troubleshoot on my side.

**Comment by klinquist** [comment]
I did a process.removeAllListeners('uncaughtException')  as the last line and it's still restarting :(.    Odd that it only happens under PM2.

**Comment by soyuka** [comment]
Are you running on ubuntu? PM2 version? 
This seems related to the recent issues #1380 or #1424

**Comment by klinquist** [comment]
Ubuntu 14.04.2  PM2 0.14.5, I was experiencing #1380/#1424 with other scripts (which was solved with the latest PM2), this seems to be not related - not getting a SEGFAULT or anything in my syslog/kernel log.

**Comment by soyuka** [comment]
Could you run:

```
DEBUG="pm2:*" pm2 start yourapp.json --no-daemon
``` 

to see if you get more informations about the SIGTERM cause?

**Comment by klinquist** [comment]
Not a whole log of info...

```
% DEBUG="pm2:*" pm2 start pm2.json --no-daemon
  pm2:constants PM2_ROOT_PATH: /home/ubuntu/.pm2 +0ms
  pm2:monit Getting interaction info +71ms
  pm2:interface:daemon [PING INTERACTOR] Trying to connect to Interactor daemon +1ms
pm2 launched in no-daemon mode (you can add DEBUG="*" env variable to get more messages)
  pm2:satan [PING PM2] Trying to connect to server +5ms
  pm2:satan Daemon alive +3ms
undefined
  pm2:satan [PING PM2] Trying to connect to server +2ms
  pm2:satan Daemon alive +1ms
  pm2:satan Launching RPC client on port /home/ubuntu/.pm2/rpc.sock undefined +0ms
  pm2:satan Connected to Daemon +1ms
  pm2:cli Got message from Satan as succesfully connected to PM2, now parsing arguments +4ms
  pm2:satan Calling daemon method pm2:getVersion +1ms
  pm2:monit Before processing +29ms { name: 'my-app',
  script: './server.js',
  cwd: '/data/myapp',
  watch: false,
  exec_mode: 'fork_mode',
  exec_interpreter: 'node' }
  pm2:monit After processing +4ms { errors: [],
  config: 
   { script: './server.js',
     name: 'my-app',
     cwd: '/data/myapp',
     watch: false,
     exec_mode: 'fork_mode',
     exec_interpreter: 'node' } }
  pm2:satan Calling daemon method pm2:getMonitorData +0ms
  pm2:satan Calling daemon method pm2:getMonitorData +17ms
  pm2:satan Calling daemon method pm2:restartProcessId +17ms
  pm2:satan Calling daemon method pm2:notifyByProcessId +14ms
[PM2] restartProcessId process id 4
  pm2:satan Calling daemon method pm2:notifyByProcessId +0ms
  pm2:satan Calling daemon method pm2:getMonitorData +1ms
  pm2:satan God notified +9ms
  pm2:satan God notified +0ms
  pm2:interface:daemon Interactor Daemon not launched +2ms
┌─────────────────────┬────┬──────┬──────┬────────┬─────────┬────────┬──────────────┬──────────┐
│ App name            │ id │ mode │ pid  │ status │ restart │ uptime │ memory       │ watching │
├─────────────────────┼────┼──────┼──────┼────────┼─────────┼────────┼──────────────┼──────────┤
│ my-app              │ 4  │ fork │ 4664 │ online │ 4       │ 0s     │ 6.477 MB     │ disabled │
└─────────────────────┴────┴──────┴──────┴────────┴─────────┴────────┴──────────────┴──────────┘
 
 Use `pm2 show <id|name>` to get more details about an app
--no-daemon option enabled = do not exit pm2 CLI
PM2 daemon PID = 2517
  pm2:satan Calling daemon method pm2:getMonitorData +16ms
[PM2] Streaming realtime logs for [all] processes 

08:27:59 my-app-4 listening on *:7000

08:28:30 PM2 Stopping app:my-app id:4
08:28:30 PM2 App name:my-app id:4 exited with code SIGTERM
08:28:30 PM2 Process with pid 4664 killed
08:28:30 PM2 Starting execution sequence in -fork mode- for app name:my-app id:4
08:28:30 PM2 App name:my-app id:4 online
08:28:31 my-app-4 listening on *:7000
```

**Comment by soyuka** [comment]
Then it keeps saying stopping/starting? This is really weird, especially that we never send SIGTERM to any process.

**Comment by klinquist** [comment]
Yep- every few minutes it seems.   Ok, will continue to troubleshoot.

**Comment by jshkurti** [comment]
Any news on this ? @klinquist

**Comment by klinquist** [comment]
Nope - it's still happening, but only for a single app.  No idea what's going on.  I added a process.on('SIGTERM', function(err){
console.log(err)
});  

and I'm just getting 'undefined'....

**Comment by soyuka** [comment]
Following up in #2005
