### ISSUE TITLE
Why used memory much higher than using pure cluster module?

### ISSUE THREAD

**Issue by ndaidong** [Unitech/PM2#1465]
Hi there,

This may be not an issue, I'm just curious about the monitoring information. 

Here are my two apps, running under PM2's fork mode. They were started with cluster module by Node.js itself.

![Cluster module](http://i.imgur.com/p4UiGdX.png)

And here, when I run them with PM2 cluster mode:

![PM2 cluster mode](http://i.imgur.com/cdOGZeV.png)

It looks like in the first case, PM2 just shows the amount of memory used by 1 process? Is that right?

Thanks.

**Comment by jshkurti** [comment]
Yes, it shows metrics for each process, if your app creates workers (== child_processes), those workers will have different **pid**s thus PM2 will monitor only the master process.

**Comment by ndaidong** [comment]
Thank you for your explaining, @jshkurti . It means the numbers PM2 shows are actual values.
