### ISSUE TITLE
next_gen_js with node 0.12

### ISSUE THREAD

**Issue by soncodi** [Unitech/PM2#1468]
Can the iojs-only restriction be lifted, with node 0.12?

##### https://github.com/Unitech/PM2/blob/master/lib/Common.js#L40-L42
```js
if (!iojs) {
  return new Error('To run next generation Javascript you need to run PM2 with io.js');
}
```

**Comment by jshkurti** [comment]
`npm i -g Unitech/PM2#development` for now otherwise it will be in the next release :)

**Comment by soncodi** [comment]
Great, thanks!

**Comment by vbalas6** [comment]
NODE_ENV=development pm2 start --next-gen-js dist/lib/server/index.js --name pulse-api --watch "../"

[PM2][ERROR] script not found : /var/lib/jenkins/jobs/pulse-api/io.js

**Comment by Unitech** [comment]
next-gen-js flag has been deprecated
