### ISSUE TITLE
pm2 reloadLogs is not working

### ISSUE THREAD

**Issue by binarykitchen** [Unitech/PM2#1469]
I have this logrotation config for videomail.io but somehow the `pm2 reloadLogs` doesn't perform the logrotation:

```
/var/log/xxx/videomail/production/error.log
/var/log/xxx/videomail/production/out.log {
        sharedscripts
        rotate 6

        notifempty
        mailfirst
        mail aaa@bbb.com

        weekly

        create 644 nodejs nodejs

        dateext
        dateformat %Y-%m-%d
          
        postrotate
            [ -s /run/nginx.pid ] && kill -USR1 `cat /run/nginx.pid`
            pm2 reloadLogs
        endscript
}
```

Am I doing something wrong here?

**Comment by binarykitchen** [comment]
Ping?

**Comment by Tjatse** [comment]
I just test it on my servers and everything goes fine.
PM2 v0.14.5
Centos 6, 7

Could you force the rotation by executing `logrotate -f /etc/logrotate.d/[your config name]`  and paste the logs here?

**Comment by binarykitchen** [comment]
```
# michael.heuberger at binarykitchen.com in /etc/logrotate.d on git:master x [9:21:51]
$ cat nodejs_logs_with_email                                                                                                                                                                               
/var/log/nodejs/videomail/production/error.log
/var/log/nodejs/videomail/production/out.log {
        sharedscripts
        create 644 nodejs nodejs
        rotate 4

        notifempty
        mailfirst
        mail michael.heuberger@binarykitchen.com

        weekly

        postrotate
            [ -s /run/nginx.pid ] && kill -USR1 `cat /run/nginx.pid`
            pm2 reloadLogs
        endscript
}

# michael.heuberger at binarykitchen.com in /etc/logrotate.d on git:master x [9:26:16]
$ sudo logrotate -f /etc/logrotate.d/nodejs_logs_with_email                                                                                                                                                
[sudo] password for michael.heuberger: 
[PM2] Spawning PM2 daemon
[PM2] PM2 Successfully daemonized
Reloading all logs...
All logs reloaded
```

**Comment by Tjatse** [comment]
Wait, why
```
[PM2] Spawning PM2 daemon
[PM2] PM2 Successfully daemonized
```

It seems that your PM2 did not startup before logrotation.

**Comment by binarykitchen** [comment]
I already have installed the startup script a long time ago. So, must be something else. Maybe a bug?

**Comment by Tjatse** [comment]
IDK
My suggestion:
1. Run `pm2 ls` to make sure that your processes are running.
2. Go to `/var/log/xxx/videomail/production/` directory to make sure that your logs are stable (Over 1KB?).
3. Test your logrotation by `sudo logrotate -f /etc/logrotate.d/nodejs_logs_with_email`.
4. Check out your rotated logs in `/var/log/xxx/videomail/production/`, it should be `error.log0` or `error.log20140807`...

**Comment by binarykitchen** [comment]
Wait, I think I found the cause. I am running the node processes under another user called `nodejs` but logrotate is running under `root`, firing the `pm2 reloadLogs` command as root.

Maybe I should change to `sudo -H -u nodejs bash -c 'pm2 reloadLogs'` instead??

Can you confirm?

**Comment by Tjatse** [comment]
Okay, I will test it on my server, and I am running PM2 by root (user) root (group), and my logrotation config is:
```
create 0644 root root
```

**Comment by binarykitchen** [comment]
Please test this with another user, not root. This to make sure we both have the same test conditions.

**Comment by Tjatse** [comment]
**logrotation config1:**
```
/var/log/nodejs/out-1.log {
        sharedscripts
        create 644 nodejs nodejs
        rotate 4

        weekly

        postrotate
            pm2 reloadLogs
        endscript
}
```

My test script (test.js):
```javascript
setInterval(function(){
  console.log(Date.now());
}, 2000);
```

Pure CentOS 7, terminal of `root:root`:
```bash
# node -v
v0.12.7
# pm2 -v
0.14.6
# groupadd nodejs
# useradd -s /bin/sh -g nodejs nodejs
# passwd nodejs
***
# chown -R nodejs:nodejs /usr/nodejs
# chown -R nodejs:nodejs /var/log/nodejs
```

Terminal of `nodejs:nodejs`:
```bash
$ pm2 start test.js -o /var/log/nodejs/out.log -e /var/log/nodejs/error.log
$ [PM2] Starting test.js in fork_mode (1 instance)
$ [PM2] Done.
┌──────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────────────┬──────────┐
│ App name │ id │ mode │ pid   │ status │ restart │ uptime │ memory      │ watching │
├──────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────────────┼──────────┤
│ test     │ 1  │ fork │ 21283 │ online │ 0       │ 0s     │ 12.473 MB   │ disabled │
└──────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────────────┴──────────┘
$ tail -n 10 /var/log/nodejs/out-1.log 
1438917696673
1438917699692
1438917702697
1438917705698
1438917708698
1438917711699
1438917714700
$ ls /var/log/nodejs/
error-1.log  out-1.log
```

Now terminal of `root:root`:
```bash
# logrotate -f /etc/logrotate.d/pm2 
Reloading all logs...
All logs reloaded
```

Terminal of `nodejs:nodejs`:
```bash
$ ls /var/log/nodejs/
error-1.log  out-1.log  out-1.log.1 
$ tail -n 10 /var/log/nodejs/out-1.log 
```
`out-1.log.1` means log was rotated, but there are no more logs in `/var/log/nodejs/out-1.log` now (the problem).

**logrotation config2**:
```
/var/log/nodejs/out-1.log {
        sharedscripts
        create 644 nodejs nodejs
        rotate 4

        weekly

        postrotate
            su - nodejs -c "pm2 reloadLogs"
        endscript
}
```
Just like what you said, everything goes fine now, cheers!!

**Comment by binarykitchen** [comment]
Wonderful, very good examination. Many thanks!

Maybe we should document or better, add a warning for the `pm2 reloadLogs` saying that it must be run under the same user who started pm2!

**Comment by jshkurti** [comment]
+1

**Comment by binarykitchen** [comment]
@Tjatse I am still having issues and the out file still does not get logrotated. Here is my config:

```
$ cat nodejs_logs_with_email                                                                                                                                                                               
/var/log/nodejs/xxx/production/error.log
/var/log/nodejs/xxx/production/out.log {
        sharedscripts
        create 644 nodejs nodejs
        rotate 4

        notifempty
        mailfirst
        mail a@b.com

        weekly

        postrotate
            [ -s /run/nginx.pid ] && kill -USR1 `cat /run/nginx.pid`
            sudo -H -u nodejs bash -c 'pm2 reloadLogs'
        endscript
}
```

Do you see any mistakes?

And should I change `sudo -H -u nodejs bash -c 'pm2 reloadLogs'` to `su - nodejs -c "pm2 reloadLogs"`?

**Comment by Tjatse** [comment]
@binarykitchen Hi, Michael, I'll test it tonight and let you known the result, it's afternoon now(@China)

**Comment by Tjatse** [comment]
Everything goes fine on my machine.
Could you try out by:
1. Remove the following mail settings and force rotation by `logrotate -f /etc/logrotate.d/nodejs_logs_with_email` to get rid of mail problems.
```
notifempty
mailfirst
mail a@b.com
```

2. try to change `sudo -H -u nodejs bash -c 'pm2 reloadLogs'` to `su - nodejs -c "pm2 reloadLogs"`.

**Comment by binarykitchen** [comment]
will try, thanks! but i won't remove the mail config lines as i need them.

**Comment by binarykitchen** [comment]
still no luck @Tjatse :( it does not logrotate the out.log (but the error.log is rotated fine):

```
$ cat nodejs_logs_with_email.weekly                                                                                                                                                                        
/var/log/nodejs/xxx/production/error.log
/var/log/nodejs/xxx/production/out.log {
        sharedscripts
        create 644 nodejs nodejs
        rotate 4

        notifempty
        mailfirst
        mail aaa@bbb.com

        weekly

        postrotate
            [ -s /run/nginx.pid ] && kill -USR1 `cat /run/nginx.pid`
            su - nodejs -c "pm2 reloadLogs"
        endscript
}
```

anything wrong here?

**Comment by Unitech** [comment]
Have you tried the [pm2-logrotate](https://github.com/pm2-hive/pm2-logrotate) module?

```
$ pm2 install pm2-logrotate
```

**Comment by binarykitchen** [comment]
@Unitech really, should i? then why does the `pm2` package already comes with the `reloadLogs` command?

**Comment by Unitech** [comment]
Do your applications runs in cluster or in fork mode?

**Comment by binarykitchen** [comment]
@Unitech fork mode

```
$ pm2 ls                                                                                                                                                                                          master 
┌────────────────────────────────┬────┬──────┬───────┬────────┬─────────┬────────┬──────────────┬──────────┐
│ App name                       │ id │ mode │ pid   │ status │ restart │ uptime │ memory       │ watching │
├────────────────────────────────┼────┼──────┼───────┼────────┼─────────┼────────┼──────────────┼──────────┤
│ www.videomail.io               │ 3  │ fork │ 10533 │ online │ 0       │ 2D     │ 241.867 MB   │ disabled 
```

**Comment by Unitech** [comment]
Reload logs works, I started an app, delete the log files, then called pm2 reloadLogs, and the log files went back again with right data inserted

**Comment by binarykitchen** [comment]
@Unitech I think you should test this together with logrotate.d - that's where it fails for me.

And can you explain me the difference between the `pm2-logrotate` npm module and the `pm2 reloadLogs` command? Are both the same?

**Comment by Unitech** [comment]
pm2-logrotate is slightly different: https://github.com/pm2-hive/pm2-logrotate/blob/master/app.js

I will try to inspect this with logrotate

**Comment by binarykitchen** [comment]
thanks @Unitech, please do that

**Comment by sominlee74** [comment]
Hi, 

I am not sure if this issue has already been solved, or not. However, I had similar problem, and solved it with getting some idea from this issue. Hopefully, my configuration could be helpful.

(something like user account is changed, but others is same as original)

### Environment and situation
* OS: Ubuntu 14.04.X (LTS) on Amazon Web Services(AWS)
* PM2 version: 1.0.0
* Application: Node.JS application
* Node.JS App: Run my node.js app under an account `simonlee74`, with this `run.sh` script
```
pm2 start app.js --name "myauthserver" --log-date-format "YYYY-MM-DD HH:mm:ss" --merge-logs
```
* pm2 logs are located `/home/simonlee74/.pm2/logs`

### config file: `/etc/logrotate.d/pm2-myauthserver`
```
/home/simonlee74/.pm2/pm2.log /home/simonlee74/.pm2/logs/*.log {
       su simonlee74 simonlee74
       rotate 8
       daily
       missingok
       notifempty
       dateext
       compress
       delaycompress
       create 0640 simonlee74 simonlee74
       sharedscripts
       postrotate
          su -c "pm2 reloadLogs" - simonlee74
       endscript
}
```

### Conclusion

* `su simonlee74 simonlee74` directive is required. Without this, 'insecure permission' error might happen (Please test `sudo logrotate -vf /etc/logrotate.d/pm2-myauthserver` with/without `su` directive)
* `su -c "pm2 reloadLogs" - simonlee74` (after `postrotate`) is required. : I run `myauthserver` under `simonlee74`. As you know, `logrotate` is launched under `root` account. So, without this `su -c ~ - simonlee74`, something goes wrong. For one example, another PM2 process is launched under "root" account.

**Comment by clayzermk1** [comment]
@sominlee74 thank you for this! Your suggestions got me going.

**Comment by ik9999** [comment]
For those who have V8 error when running `pm2 reloadLogs` in logrotate environment:

Make sure you have 
[Service]
MemoryDenyWriteExecute=false

In your logrotate.service definition.
