### ISSUE TITLE
How to point pm2.log to /var/log/

### ISSUE THREAD

**Issue by binarykitchen** [Unitech/PM2#1470]
... instead of having it in my home folder?

How can this be reconfigured?

**Comment by soyuka** [comment]
[This line](https://github.com/Unitech/PM2/blob/24f1bd77a1053448d02580e4d4ccdccf0ee28e46/lib/samples/sample-conf.js#L17) can be modified in `~/.pm2/conf.js`. For example:

```
    PM2_LOG_FILE_PATH        : '/var/log/pm2.log',
```

**Comment by binarykitchen** [comment]
Thanks. But I have multiple pm2 users and the `conf.js` file is in each of their home directories. I want all of them to point to a  single `/var/log/pm2.log` and configure this with logrotate.

How can I do this best? Do not want to set the same log path at five places. Isn't there some kind of central pm2 configuration for the whole server?
