### ISSUE TITLE
Calling logs results in error

### ISSUE THREAD

**Issue by sune26** [Unitech/PM2#1471]
Whenever I call logs I receive this message 

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: EINVAL, read
    at Error (native)

Anyone know what's wrong and how to fix this?
I am running windows 7 and have tried reinstalling pm2.

**Comment by PredokMiF** [comment]
Same problem! Windows 7 x32

**Comment by MarcusSjolin** [comment]
I see this at work too on Win 7, haven't got a fix yet unfortunately

**Comment by harriha** [comment]
Managed to reproduce this, and seems to me that https://github.com/Unitech/PM2/commit/419f6c819408425acaddeda3f89ce43e36ada04f fixes this at least in my case. One way to prevent this might be to ensure the log files have enough content - not very practical obviously, but a workaround.

**Comment by Unitech** [comment]
PM2 0.15.x published
