### ISSUE TITLE
Exiting child process causes a restart of main app

### ISSUE THREAD

**Issue by rdev** [Unitech/pm2#1472]
I have an app, spawning phantomjs processes. When phantom finishes and exits, PM2 restarts my main app. How can I prevent that from happening?

**Comment by soyuka** [comment]
`pm2 start app.js --no-autorestart`

>true by default. if false, PM2 will not restart your app if it crashes or ends peacefully

[Source](https://github.com/Unitech/PM2/blob/master/ADVANCED_README.md#list-of-all-json-declaration-fields-avaibles)

**Comment by Altair-Z** [comment]
Thanks, but I actually want to restart my main app if it exits. Just not when it's child process exits.

**Comment by fivepointseven** [comment]
Thanks, but I actually want to restart my main app when it exits. Just not when it's child process exits.

**Comment by soyuka** [comment]
Oh sorry misunderstood. Pm2 doesn't handle your child processes so it would be your app job to handle this.

**Comment by fivepointseven** [comment]
My app has a callback to perform an action when child processes finish, but it can't do anything, because PM2 restarts the whole app >_<

**Comment by jshkurti** [comment]
Is `--watch` enabled ?
PM2 doesn't restart an app without a reason.
See `~/.pm2/pm2.log` to find out what happened.
