### ISSUE TITLE
Arguments not getting passed to app

### ISSUE THREAD

**Issue by dbeckwith** [Unitech/PM2#1473]
Both when using a JSON config file and with the `--` syntax, my app isn't getting passed any arguments.

Here is my JSON config file:
```json
{
  "apps": [
    {
      "name": "website-server",
      "script": "bin/website-server.js",
      "args": "--port 80",
      "max_memory_restart": "256M",
      "env": {
        "NODE_ENV": "production"
      }
    }
  ]
}
```

Here is my app logging `process.argv` as it starts:
```
website-server-0 (out): [ 'node',
website-server-0 (out):   '/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js' ]
```
I get the same if I do `pm2 start bin/website-server.js -- --port 80`.
Any help?

**Comment by jshkurti** [comment]
Just tried it with latest PM2 and Node 0.12. It worked fine.
Which versions of PM2 and Node have you been using ?

**Comment by dbeckwith** [comment]
PM2 v0.14.5, NodeJS v0.12.7

**Comment by jshkurti** [comment]
![htop4](https://cloud.githubusercontent.com/assets/7647602/8931617/dfc5c30c-3537-11e5-900c-50b7411ade11.png)

**Comment by dbeckwith** [comment]
Seems to be working now, I'm not sure why... Do you have to reload the config JSON every time it changes or something?

**Comment by jshkurti** [comment]
Of course, the JSON is loaded once when you start your app :)

**Comment by dbeckwith** [comment]
Does the JSON get reloaded when I do `pm2 restart`?

**Comment by jshkurti** [comment]
Nope.

**Comment by dbeckwith** [comment]
Ah, I see. Thanks for the help!
