### ISSUE TITLE
Error when clustering with IcedCoffeeScript

### ISSUE THREAD

**Issue by prvcy** [Unitech/PM2#1478]
I see other people have had this issue previously (#488) that doesn't seem to have been resolved, however it works in fork mode but not with cluster mode.

I am executing the command: 

`pm2 start server.iced --interpreter iced -i 0 --name "api"`

which results in:

`SyntaxError: Unexpected string
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at /usr/lib/node_modules/pm2/lib/ProcessContainer.js:207:23
    at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:49:16
    at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:1165:30
    at WriteStream.<anonymous> (/usr/lib/node_modules/pm2/lib/Utility.js:110:13)
    at WriteStream.emit (events.js:95:17)
`

Everything works fine when I execute: 
`pm2 start server.iced --interpreter iced -x --name "api"` and `iced server.iced`

I am using node version v0.10.40, any idea what the issue could be? I also tried it with the latest version of node (v0.12.7) and got the same results

**Comment by Unitech** [comment]
Interpreter option does not work in cluster mode (only work for Node and CoffeeScript), we may add the library in the future.

For now you can compile from icedcoffescript to raw javascript then run this in cluster mode,

Closing for now,
