### ISSUE TITLE
Change polling interval

### ISSUE THREAD

**Issue by TheCrazyDigitalPainter** [Unitech/PM2#1480]
Hello,
i'm using PM2 with docker with nfs, and i would like to know how to change the default interval between polling.

**Comment by soyuka** [comment]
Are you talking about the watch feature?

You can change every chokidar option in the `watch_options` declaration, for example:

```
{
  "watch": ["server", "client"],
  "ignore_watch" : ["node_modules", "client/img"],
  "watch_options": {
    "followSymlinks": false,
    "usePolling": true,
    "interval": 400
  }
}
```

**Comment by TheCrazyDigitalPainter** [comment]
Great Thanks I'll try now

**Comment by TheCrazyDigitalPainter** [comment]
It doesn't seem to work in docker :(

here is my conf
{
  "apps" : [{
    "name"        : "worker-app",
    "script"      : "index.js",
    "args"        : ["--toto=heya coco", "-d", "1"],
    "watch"       : true,
    "watch_options": {
      "usePolling": true,
      "interval": 100
    },
    "node_args"   : "--harmony",
    "merge_logs"  : true,
    "cwd"         : "/server",
    "exec_mode"  : "cluster_mode",
    "env": {
        "NODE_ENV": "dev"
    }
  }]
}

Any idea how to verify the polling interval in the container ?

**Comment by soyuka** [comment]
Default interval is already `100` see [chokidar docs](https://github.com/paulmillr/chokidar/tree/e8c770af092752ea6fef69b94d673026d0e6625b#performance). 
I don't think you'll be able to check this without adding a line of code in chokidar.

Closing as non-pm2 issue.
