### ISSUE TITLE
Running npm test freezes on "Should get an empty process list from system data"

### ISSUE THREAD

**Issue by ejbaker** [Unitech/PM2#1486]
OS: Ubuntu 14.04.2 LTS (on AWS)
Node version: 0.12.7
PM2 version: 0.14.5
Command: npm test

Relevant code:

    [PM2] Spawning PM2 daemon
    [PM2] PM2 Successfully daemonized
        ✓ should start Satan interaction (475ms)
    Client ready
        ✓ should auto instancy itself, fire event and kill daemon
        ✓ should have right properties
        DAEMON
          - should have the right exposed methods via RPC
          ✓ should get an empty process list
          1) should get an empty process list from system data

The last is red, and then the process hangs.

**Important**: When I ran the test for the first time, it stopped much later on. I followed the suggestion to make sure I had build-essential installed, node-gyp, etc., but on every subsequent try I get this message. (I have tried to purge the PM2 processes as per the documentation in the hopes that that is what this meant, to no avail.)

**Also important**: PM2 *works*, when used on my own project... it's just this test that's failing.

**Comment by jshkurti** [comment]
https://travis-ci.org/Unitech/PM2/builds

**Comment by ejbaker** [comment]
I assumed this response meant it had been patched and went through the steps to update. Still having the error.

**Comment by jshkurti** [comment]
I merged #development into #master.
So #master is now stable but it hasnt been published to npm yet.
It will be soon enough.
Thanks for reporting this :)

**Comment by randallard** [comment]
I'm getting this far in the tests then it seems like they freeze:

  Satan
{ msg: 'script not found : /root/.pm2/node_modules/ms/index' }
    ✓ should start Satan interaction (1652ms)
Client ready
    ✓ should auto instancy itself, fire event and kill daemon
    ✓ should have right properties
    DAEMON
      - should have the right exposed methods via RPC
      1) should get an empty process list

seems like the same issue mentioned in this thread but not sure how to implement the fix as the link is not finding anything
