### ISSUE TITLE
pm2  and uncaughtException 

### ISSUE THREAD

**Issue by wf744** [Unitech/PM2#1488]
I use node to make a game server,and use pm2 to manager all the game servers,when the server come out a uncaughtException, pm2 restart the server  than is a terrible thing, because it will case all the online player lose their data.

What i want to do is i must save all the online player's data to db, then disconnect all the online player, at last, invoke process.exit to close the server

I also try PM2 Programmatic usage, used pm2 Bus system, listen to  process:exception event, but it still unwork, while using pm2 to start the server;
    So how to solve the problem ?

thx

**Comment by soyuka** [comment]
In your app listen to `uncaughtException`:

```
process.on('uncaughtException', function(e) {
    console.error(e.stack)
    dosomegamesavingasync(function() {
        process.nextTick(function() { process.exit(1) })
    })
})
```

Something like this should work.

**Comment by wf744** [comment]
```
var fs = require("fs");

setInterval(function(){
	var oppPvpOlInfo = 50;
	var a = oppPvpOlInfo["abc"];
	oppPvpOlInfo["abc"]["eff"] = 3;
	}, 3000);

process.on('uncaughtException', function (err) {
	console.error(err.stack);
	fs.writeFile('abc.txt', 'Hello Node', function (err) {
	  if (err) throw err;
	  console.log('It\'s saved!');
	  process.nextTick(function() { process.exit(1) })
	});
});
```

The code before unwork ~~

**Comment by jshkurti** [comment]
Is your app running in cluster mode ?

**Comment by jshkurti** [comment]
Nevermind, it is running in fork mode. Bug confirmed. I'm working on this :)

**Comment by jshkurti** [comment]
Fixed : https://github.com/keymetrics/pmx/commit/1e02b202bf9922dac8a3afb419f821a272af70fd

You just have to update pmx (dependecy), to do so : `npm i -g pm2`.
Normally you will see **pmx@0.3.26** and it should be ok :)

I close this now, feel free to re-open if the error persists.
Cheers

**Comment by wf744** [comment]
@jshkurti
thx, it fixed and work!
