### ISSUE TITLE
pm2-dev run with --next-gen-js does not kill process properly

### ISSUE THREAD

**Issue by tlvenn** [Unitech/pm2#1494]
Hi,

When I use pm2-dev run with --next-gen-js I notice that when PM2 detect a change and restart the app, the old app is actually still running. After 10 changes, you ends up with 11 instances of your app serving different code versions :)

Any idea what is going on ?

Using latest PM2 with latest iojs on OS X

Thanks

**Comment by Tlvenn** [comment]
My issue might be related to https://github.com/Unitech/PM2/issues/1444

**Comment by Tlvenn** [comment]
For information:

```
$ pm2-dev run server.js --next-gen-js
[PM2] Streaming realtime logs for [all] processes

server-0 Server (dev) started at localhost:8070
server-0 get called:
server-0 auth called!
server-0 false
^C
PM2 [Watch] Stop watching 0
PM2 Stopping app:server id:0
PM2 App name:server id:0 exited with code SIGTERM
PM2 Process with pid 49653 killed

$ ps -ef | grep server.js
  501 49670     1   0  1:39AM ??         0:01.11 /.../.nvm/versions/io.js/v2.5.0/bin/iojs /usr/local/lib/node_modules/pm2/node_modules/babel/lib/_babel-node /.../server.js
```

With PM2 0.14.5 and IOJS 2.5

**Comment by jshkurti** [comment]
Does your app use child processes ?

**Comment by Tlvenn** [comment]
As far as I know no and I dont think any dependencies do but I might be wrong about that...

**Comment by peeter-tomberg** [comment]
Seems to be a pm2 issue. A simple HapiJS demo application is kept alive after changes are detected.

https://gist.github.com/peeter-tomberg/0755046480c21ff80557

If I change the port the app is started and the old instance is kept up.

**Comment by soyuka** [comment]
`--next-gen-js` is not supported anymore, just use the require hook
