### ISSUE TITLE
Can you add max_auto_restarts ? my server restart 5000 times one night

### ISSUE THREAD

**Issue by roytan883** [Unitech/PM2#1496]
I know that max_restarts only watch those crash in 1 sec, and limit it to default 15 times.
I meet a problem on autorestart = true. In special condition my app will not crash in 1 sec, it's about 2~5 sec. Then my app restart more then 5000 times one night......

Can you add a config options that limit autorestart times? Means we need autorestart, but not infinite.

**Comment by Tjatse** [comment]
How about the following config, it means only allowing 100 restarts in the first 24 hours, and restart your server at `00:01:00` every day, so the `min_uptime` and `max_restarts` behavior works again.
```
{
  "min_uptime": "24h",
  "max_restarts": 100,
  "cron_restart": "01 0 * * *"
}
```

**Comment by roytan883** [comment]
First two options look great, solve my problem.
But can cron_restart only work with the App already stopped? Because i dont' want my running app restart.

That means only allow 15 restart one day, and will restart it at next day 00:01:00 if the app already stopped.
{
  "min_uptime": "24h",
  "max_restarts": 15,
  "cron_restart_stopped": "01 0 * * *"
}

**Comment by Tjatse** [comment]
Sorry, can not do that.

As far as I'm concerned, I do not think restarting your server at `00:01:00` is a bad idea, scheduled reboot is always helpful, e.g.: GC, release connection... and the request traffics are scarce in middle night.

**Comment by jshkurti** [comment]
Progammatic PM2 always comes handy :)

```js
var pm2 = require('pm2');

pm2.connect(function() {

  setInterval(function() {
    pm2.list(function(err, list) {
      var app = list.filter(function(e) {return e.pm_id === 'MY_APPS_ID'})[0];
      if (app.pm2_env.restart_time > MY_LIMIT) {
        pm2.stop(MY_APPS_ID, function() { console.log("App stopped !") });
      }
    });
  }, 3000);
});

**Comment by jshkurti** [comment]
Closing this for now, max_auto_restarts will probably be a thing someday in the future ;)
