### ISSUE TITLE
Feature request: Get "pm2 list" output in JSON format

### ISSUE THREAD

**Issue by klinquist** [Unitech/PM2#1498]
Would make it much easier to parse with jq for use in build/deploy scripts.
pm2 list --output-json  perhaps?

**Comment by klinquist** [comment]
In the meantime, this worked well :)

```
pm2 l --no-color | grep \"{{ appname.stdout }}\" | awk -F │ '{gsub(/^[ \t]+|[ \t]+$)/, \"\", $3); system(\"pm2 reset \" $3 ) }'
```

**Comment by klinquist** [comment]
Sorry about this - just found 'pm2 jlist'.

**Comment by soyuka** [comment]
Indeed :)

Get status by name:
```
pm2 jlist|jq '.[]|select(. | contains({name: "myName"})).pm2_env.status' 
```

**Comment by klinquist** [comment]
You rock :).

**Comment by jshkurti** [comment]
What kind of informations would do you like have when doing `pm2 list --json` ?
Because you can actually access all of the data with `pm2 jlist` or `pm2 prettylist`.
