### ISSUE TITLE
shouldn't close the old_worker when new_worker start listening

### ISSUE THREAD

**Issue by elvis-macak** [Unitech/PM2#1499]
There is a procedure when gracefulReload in function `softReload` in `lib/God/Reload.js`, as below
It adds `a timer to stop the old_worker` or `a event listener of new_worker's listening`. But sometimes I want to wait for the old_worker's conversation to finish.

eg or a demo:
I want to upload a really large file(a sample of long-time job), and then `gracefulReload` the app, the current logic is stop the old_worker when started the new_worker, this will interrupt my uploading operation. 
So I doubt whether I can comment the line: `new_worker.once('listening', onListen);`.
I think a better logic is to add a event listener for the old_worker's disconnect and then stop the old_worker. 
 
<pre>
  God.executeApp(new_env, function(err, new_worker) {
    if (err) return cb(err);

    var timer = null;

    var onListen = function () {
      clearTimeout(timer);
      softCleanDeleteProcess();
      console.log('-softReload2- New worker listening');
    };  

    // Bind to know when the new process is up
    new_worker.once('listening', onListen);   // XXXXXXXXXXX I think it's not a good logic here

    timer = setTimeout(function() {
      new_worker.removeListener('listening', onListen);
      softCleanDeleteProcess();
    }, cst.GRACEFUL_LISTEN_TIMEOUT);

    // Remove old worker properly
    var softCleanDeleteProcess = function () {
     ...
     // other codes, replace the old_worker with the new_worker in the db
     ...
    }
</pre>

**Comment by jshkurti** [comment]
The behaviour you described is what hardReload (`pm2 reload`) does (kill old_worker as soon as new_worker has spawned).
softReload (`pm2 gracefulReload`) will send a **shutdown** message to the old_worker and then wait till this one exits by himself. If it doesn't, it kills it anyway after PM2_GRACEFUL_TIMEOUT milliseconds.

What you need to do is set a higher PM2_GRACEFUL_TIMEOUT.

See https://github.com/Unitech/PM2/issues/1394 for more details

**Comment by elvis-macak** [comment]
thx for your reply

yeah, i get your idea, and it's really a good design.  I have to close my old_workder and set a larger PM2_GRACEFUL_TIMEOUT.
