### ISSUE TITLE
Massive memory leaks

### ISSUE THREAD

**Issue by novacrazy** [Unitech/PM2#1500]
Earlier today I reinstalled my project dependencies and upgraded everything the latest versions, and now I'm getting gigabytes of memory used on the PM2 God Daemon and the KeyMetrics.io Agent processes. It uses up about 30MB per minute, sometimes as much as 2MB per second. After about two hours my server crashes because it's out of memory. So that's a pretty big problem.

I know for a fact it is not my code, because I have a page on my application that monitors all memory and CPU aspects of each running process. Plus I can view it in htop. Only the PM2 God Daemon and Keymetrics.io Agent are leaking tons of memory.

For now I'm going to try reverting back to an older version of PM2 to see if that helps.

**Comment by novacrazy** [comment]
After fifteen minutes running PM2 version 0.14.3, the Keymetrics.io Agent and the God Daemon are each taking up about 10-13% of my server's RAM. That is, doing absolutely nothing, each one is using over 200MB. That is insane.

The only thing I have changed in my application in the last week is a couple Redis connections that are actually less intensive that they were previously.

Any ideas? Otherwise I might have to switch back to forever or roll my own solution, which won't be pleasant.

**Comment by novacrazy** [comment]
Upon further research, this actually seems tied to me upgrading to io.js 3.0.0

On io.js 2.4.0 and 2.5.0 memory usage for PM2 processes stays relatively low. Hovering at around 2% for the last five minutes with no signs of leaking.

Interesting.

**Comment by light24bulbs** [comment]
Can confirm, same thing on io.js 3

**Comment by pragmadash** [comment]
Also confirm this issue. I have memory leaks since updated to 0.14.4 version. I'm using iojs 1.8.4. 

I've found this changelog line in 0.14.4 release:

> Fix: Remove forced GC

Can be that a reason?

**Comment by soyuka** [comment]
#1453 #1380

**Comment by jshkurti** [comment]
@pragmadash Yes, upgrade to the latest version of PM2 please.
