### ISSUE TITLE
Critical EMFILE issue

### ISSUE THREAD

**Issue by kanongil** [Unitech/PM2#1501]
PM2 died on one of my servers with an `EMFILE` error. This error happens on file access when all file descriptors are occupied, by PM2 or other user processes.

While this issue can be caused by other processes, I am confident that it is a PM2 issue after a quick `lsof`, which shows that the same log files are opened several hundred times.

It seems that PM2 never closes log files, and reopens them whenever a process is restarted.

**Comment by jshkurti** [comment]
`lsof -c PM2 | wc -l` ?

**Comment by jshkurti** [comment]
Which version of PM2 have you been using ?
