### ISSUE TITLE
'pm2 updatePM2' should return apps to previous state (started/stopped)

### ISSUE THREAD

**Issue by klinquist** [Unitech/pm2#1503]
It has always bugged me that after running pm2 updatePM2, all of my apps are restarted even if they were previously in a stopped state.

**Comment by Tjatse** [comment]
Indeed.

**Comment by klinquist** [comment]
Perhaps it's a bug in the resurrect function -  It seems that even on reboot, stopped services should stay stopped.  I see the "status" key in the dump file reflects "online" or "stopped"....

**Comment by Unitech** [comment]
dup https://github.com/Unitech/pm2/issues/2654
