### ISSUE TITLE
Logs are being written in bad file

### ISSUE THREAD

**Issue by adrian-ludwig** [Unitech/pm2#1504]
I have architecture like this:
Forker - microservice that spawns other microservices using pm2 api on demand from our web ui.
X1,X2 - other microservices

Forker writes logs to : logs/forker.log, logs/out-forker.log, logs/error-forker.log
Same for X1,X2 etc. just change name in log.

After few weeks i get forker.log out- and error- being files with 5GB of data.
And inside there are logs from every microservice that forker have spawned using programistic pm2 api.

Node 0.12.3
pm2 0.14.3

Small edit:
I am spawning microservices by json definitions.

**Comment by adrian-ludwig** [comment]
anything?

**Comment by jshkurti** [comment]
@Tjatse
