### ISSUE TITLE
problems in windows.

### ISSUE THREAD

**Issue by YoungsoonLee** [Unitech/pm2#1514]
hi. I love pm2.
when I use pm2  on linux , It's all okay.
But I use pm2 on Windows , I have some problems. 
  1) when I log off in live windows server , pm2 is not running.
  2) when windows server reboot , pm2 is not restarted

I searched all issue such as #1079 , #1165 , and used this module (https://github.com/marklagendijk/node-pm2-windows-startup)
But  I failed all above solution.

Is there another solution.

FYI , i use pm2-deveopment version.

**Comment by jshkurti** [comment]
We do no longer do Windows support, sorry :(

**Comment by jshkurti** [comment]
I re-open this for visibilty purposes in case someone can help you :)

**Comment by harriha** [comment]
@jshkurti Hi, could you please elaborate your comment above about Windows support - does that mean that PM2 is not (anymore) officially supported on Windows? If so, please make it clear in the README/project website to avoid people starting to rely on the tool on this OS and hitting a wall later on.

**Comment by Unitech** [comment]
Hello,

Would love to make PM2 being able to run on Windows, but I really need some help to do that...
PM2 0.10.x, 0.11.x was working well on Windows,

If I understand well by looking at the issues the main problems under Windows are:
- PM2 does not daemonize well
- Startups scripts does not work 
- Logs does not work (? Oo) #1471 

And [others](https://github.com/Unitech/PM2/issues?q=is%3Aopen+is%3Aissue+label%3Awindows)

Do someone knows if there is something similar to Travis to test PM2 under Windows? Is it possible to run bash scripts on Windows?

**Comment by harriha** [comment]
Hi @Unitech, 

Thanks for the info. I do understand the pain, can imagine Windows being a bit...painful platform to build this kind of stuff on - but all of us who build stuff on/for Windows appreciate a lot your efforts on providing this utility for that OS :+1:.

The lack of CI for Windows is obviously a fairly big shortcoming - have you checked http://www.appveyor.com/, would that work? (disclaimer: I've got no practical experience on that myself)

From what I can tell, bash scripts work quite fine in [Git bash](https://git-for-windows.github.io/) at least.

And that log file related issue #1471 is most probably fixed already in master, ended up investigating that some days ago as you might've noticed from the comments of that issue.

**Comment by soyuka** [comment]
For appveyor we'd need to move tests from bash to javascript :/.

I tried appveyor with [pidusage](https://github.com/soyuka/pidusage) and I could set it up.

**Comment by Unitech** [comment]
appveyor tests [added](https://github.com/Unitech/PM2/blob/development/appveyor.yml)

https://ci.appveyor.com/project/Unitech/pm2-2r9vk

Only Mocha tests are runned, but it's a good start,

If any one could try PM2 development in Windows and report me some bugs, it would be helpful:

```
$ npm install Unitech/PM2#development -g
$ pm2 update
```

**Comment by Unitech** [comment]
Would someone do a pull request to add support for Windows startup script?

@YoungsoonLee I like the suggestion of https://github.com/marklagendijk/node-pm2-windows-startup

**Comment by YoungsoonLee** [comment]
Sorry... I'm late...
I will test your opinion and report again.
Thanks ~!

**Comment by YoungsoonLee** [comment]
@Unitech 
 First , I run the command that 

   $ npm install Unitech/PM2#development -g
   $ pm2 update

and reinstall https://github.com/marklagendijk/node-pm2-windows-startup

and run pm2 installl.....but got the error like below...

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   './server/app.js',
1 verbose cli   '--prefix',
1 verbose cli   'D:\\Users\\youngsoonl\\.pm2' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose install initial load of D:\Users\youngsoonl\.pm2\package.json
5 verbose readDependencies loading dependencies from D:\Users\youngsoonl\.pm2\package.json
6 silly cache add args [ './server/app.js', null ]
7 verbose cache add spec ./server/app.js
8 silly cache add parsed spec { raw: './server/app.js',
8 silly cache add   scope: null,
8 silly cache add   name: null,
8 silly cache add   rawSpec: './server/app.js',
8 silly cache add   spec: 'D:\\work\\work\\server\\app.js',
8 silly cache add   type: 'local' }
9 silly addLocalTarball shasum (computed) 74a541d6e7c04b974cc0169c24821d2fc1936469
10 verbose addTmpTarball D:\work\work\server\app.js not in flight; adding
11 verbose addTmpTarball validating metadata from D:\inflogames\www.inflogames.com\server\app.js
12 verbose tar unpack D:\inflogames\www.inflogames.com\server\app.js
13 verbose tar unpacking to C:\Users\YOUNGS~1\AppData\Local\Temp\2\npm-4264-e7639335\unpack-0a6f7475a58c
14 silly gentlyRm C:\Users\YOUNGS~1\AppData\Local\Temp\2\npm-4264-e7639335\unpack-0a6f7475a58c is being purged
15 verbose gentlyRm don't care about contents; nuking C:\Users\YOUNGS~1\AppData\Local\Temp\2\npm-4264-e7639335\unpack-0a6f7475a58c
16 silly gunzTarPerm modes [ '777', '666' ]
17 error not a package D:\inflogames\www.inflogames.com\server\app.js
18 error addLocal Could not install D:\inflogames\www.inflogames.com\server\app.js
19 verbose stack Error: ENOENT, open 'C:\Users\YOUNGS~1\AppData\Local\Temp\2\npm-4264-e7639335\unpack-0a6f7475a58c\package.json'
19 verbose stack     at Error (native)
20 verbose cwd D:\inflogames\www.inflogames.com
21 error Windows_NT 6.1.7601
22 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "./server/app.js" "--prefix" "D:\\Users\\youngsoonl\\.pm2"
23 error node v0.12.7
24 error npm  v2.11.3
25 error path C:\Users\YOUNGS~1\AppData\Local\Temp\2\npm-4264-e7639335\unpack-0a6f7475a58c\package.json
26 error code ENOENT
27 error errno -4058
28 error enoent ENOENT, open 'C:\Users\YOUNGS~1\AppData\Local\Temp\2\npm-4264-e7639335\unpack-0a6f7475a58c\package.json'
28 error enoent This is most likely not a problem with npm itself
28 error enoent and is related to npm not being able to find a file.
29 verbose exit [ -4058, true ]

**Comment by kimown** [comment]
i am using win10,does pm2 support window10

**Comment by Unitech** [comment]
Please use https://github.com/jon-hall/pm2-windows-service
