### ISSUE TITLE
Cleanup command between restarts?

### ISSUE THREAD

**Issue by ravi** [Unitech/PM2#1515]
Apologies if this is already discussed: it would be useful to provide a hook to run (synchronously!) a cleanup operation between restarts (perhaps even restart based on the exit code of the cleanup). Feature bloat or as in my case a valuable addition?

**Comment by jshkurti** [comment]
You can do this with a watchdog by using pm2 programmatically.
See `restart_delay` `autorestart: false`, `launchBus`.

**Comment by ravi** [comment]
@jshkurti maybe I am not fully understanding your suggestion, but what you mention seems to be a very limited solution for what I suspect is a fairly common need. It would be nicer if PM2 supported an option, say 'prescript' and 'postscript', to run commands (waiting for them to exit) between restarts.
