### ISSUE TITLE
how to install specific version？  npm install pm2@0.14.0 -g ？

### ISSUE THREAD

**Issue by chelsh** [Unitech/PM2#1519]

**Comment by Tjatse** [comment]
Yes! Or
`npm install https://github.com/Unitech/PM2/archive/0.14.0.tar.gz -g`
`npm install https://github.com/Unitech/PM2/archive/0.14.3.tar.gz -g`

**Comment by chelsh** [comment]
it is ok now ,just now it maybe the network is slow :P

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/9218603/551794bc-4106-11e5-9816-d385aad3bd8e.png)

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/9218630/915663a4-4106-11e5-81cc-ecf4cd5de3ce.png)

**Comment by chelsh** [comment]
i install pm2@0.14.0,and pm2 update,but pm2 -v  also 0.12.7

**Comment by chelsh** [comment]
reboot the host , it is ok now,pm2 -v show 0.14.0
