### ISSUE TITLE
pm2 does not restart app when Centos server reboot

### ISSUE THREAD

**Issue by thanhthang20** [Unitech/pm2#1521]
![screen shot 2015-08-12 at 10 52 53 pm](https://cloud.githubusercontent.com/assets/5382700/9228927/efb97646-4144-11e5-974f-75cf389b3a70.png)

**Comment by jwhitmarsh** [comment]
:+1: same here

**Comment by jshkurti** [comment]
@soyuka @Tjatse

**Comment by IvanGaravito** [comment]
Using *Ubuntu 14.04.1* got similar behaviour for `# sudo env PATH=$PATH:/usr/bin pm2 startup -u safeuser`. Inspecting boot log I've found the following:

```
Starting pm2
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: connect EACCES
    at exports._errnoException (util.js:746:11)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
```

Using `# sudo env PATH=$PATH:/usr/bin pm2 startup` and adding the app with `# sudo pm2 start app.json` works perfectly after reboot, but it's not secure run pm2 as **root**.

A note of worth is that reading https://www.digitalocean.com/community/tutorials/how-to-use-pm2-to-setup-a-node-js-production-environment-on-an-ubuntu-vps it points to use `libcap2-bin` library to allow use restricted ports, but remains the same behaviour as not executing `# sudo setcap cap_net_bind_service=+ep /usr/bin/node`.

**Comment by ungana** [comment]
I'm running into the same thing.

I did come across [this article](http://www.buildsucceeded.com/2015/solved-pm2-startup-at-boot-time-centos-7-red-hat-linux/), but it didn't really seem to help much. I did however get it to startup once on reboot but not since.

* CentOS Linux release 7.1.1503 (Core)

**Comment by dibari** [comment]
I ran into this issue, and found a solution that works for me.  Let's assume I've created a user named 'node' to run pm2.  All of the commands below should be run by the node user, in the node user's home directory (/home/node)

1. Clear any pm2 dump files, and then start the appropriate services
    `% pm2 delete all`
    `% pm2 dump`
    `% pm2 start app.js --watch`

2. Save the current config to start on reboot
    `% pm2 save`
    `% sudo pm2 startup centos -u node`

3. Edit the `PM2_HOME` path in the pm2-init script to match the home directory of the user:
    `% sudo vi /etc/init.d/pm2-init.sh`
    `export PM2_HOME="/home/node/.pm2"`

I found the issue was, the user was being set appropriately in the pm2-init.sh file, but the PM2_HOME directory was set to `/root/.pm2` by default

**Comment by mikalai-silivonik** [comment]
@dibari thank you! it worked out for me too!

**Comment by yizhiheng** [comment]
@dibari 
I have been stuck here for 3 days....Thank you very much for your solution!!! It also worked for me!!!

**Comment by kennethisom** [comment]
Observing the same problem on Centos 7.  pm2 is starting on boot but as @mikalai-silivonik  mentioned dump.pm2 is "empty" (contains only: []).  I've verified that dump.pm2 does contain the environment dump before reboot but not after through several reboots.

**Comment by crystoll** [comment]
Same problem here. To me it seems like dumpfile gets emptied on resurrect, when it is run in pm2-init.sh init script on reboot. If I run resurrect manually as proper user, it all works. I'm using pm2-generated init file, with non-root user who has all node tools and pm2 installed under his account.
This is somewhat suprising issue to have.

**Comment by ghartsho** [comment]
@mikalai-silivonik thanks should go to you here, on CentOS7

`chattr +i [USER_HOME_DIR]/.pm2/dump.pm2` did the trick for me after the `pm2 save`

**Comment by julianxhokaxhiu** [comment]
@ghartsho your `chattr` command saved my life, thanks!

**Comment by meteormatt** [comment]
@thanhthang20 I try success by this step
```bash
pm2 start start.js
pm2 save
pm2 startup centos
```

**Comment by ubiko** [comment]
@meteormatt 
I get this error trying to do `pm2 startup centos`

```
[PM2] Writing startup script in /etc/init.d/pm2-init.sh
[PM2] Making script booting at startup...
[PM2] /var/lock/subsys/pm2-init.sh lockfile has been added
[PM2] -centos- Using the command:
      su -c "chmod +x /etc/init.d/pm2-init.sh; chkconfig --add pm2-init.sh"
internal/child_process.js:313
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at exports._errnoException (util.js:1036:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:380:9)
    at Object.exports.execFile (child_process.js:143:15)
    at exports.exec (child_process.js:103:18)
    at CLI.startup (/usr/local/lib/node_modules/pm2/lib/API/Startup.js:175:5)
    at Command.<anonymous> (/usr/local/lib/node_modules/pm2/bin/pm2:548:9)
    at Command.listener (/usr/local/lib/node_modules/pm2/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
```

Any ideas?

**Comment by meteormatt** [comment]
@ubiko Maybe no enough memory?

**Comment by ubiko** [comment]
@meteormatt that must be it! 

I'm on a VPS with no control over the swap.
Thanks, I'll change my setup!

**Comment by Unitech** [comment]
Closing in favor of #2559 

To try the new startup system:

```bash
$ npm install Unitech/pm2#development -g
$ pm2 update
```

```bash
$ pm2 startup     # Then copy / paste the command displayed
$ pm2 unstartup
```
