### ISSUE TITLE
pm2 stop and SIGKILL  signal

### ISSUE THREAD

**Issue by wf744** [Unitech/PM2#1522]
I use pm2(0.14.6, CentOS6.5 64bit, node v0.10.36) to manager game servers, my app listen to the "SIGTERM" signal, when i use "pm2 stop all" to stop my apps, pm2 send the "SIGTERM" signal to my app, then my app save all the online game player data to database and do some other clear up things，it take about 5 minutes,but pm2 send the SIGKILL signal to my app after 1.6s,and my app was killed, all the unsaved player data lost...

I try to listen the "SIGKILL" signal, but fail, node not allow to listen this signal.

So how to solve this problem ?

pm2 log:
```
PM2: 2015-08-13 05:40:54: Process with pid 26210 still not killed, retrying...
PM2: 2015-08-13 05:40:54: Process with pid 26210 still not killed, retrying...
PM2: 2015-08-13 05:40:54: Process with pid 26210 still not killed, retrying...
PM2: 2015-08-13 05:40:54: Process with pid 26210 still not killed, retrying...
PM2: 2015-08-13 05:40:55: Process with pid 26210 still not killed, retrying...
PM2: 2015-08-13 05:40:55: Process with pid 26210 still not killed, retrying...
PM2: 2015-08-13 05:40:55: Process with pid 26210 still not killed, retrying...
PM2: 2015-08-13 05:40:55: Process with pid 26210 still not killed, retrying...
PM2: 2015-08-13 05:40:55: Process with pid 26210 still not killed, retrying...
PM2: 2015-08-13 05:40:55: Process with pid 26210 still not killed, retrying...
PM2: 2015-08-13 05:40:55: Process with pid 26210 still not killed, retrying...
PM2: 2015-08-13 05:40:55: Process with pid 26210 still not killed, retrying...
PM2: 2015-08-13 05:40:55: Process with pid 26210 still not killed, retrying...
PM2: 2015-08-13 05:40:55: Process with pid 26210 still alive after 1600ms, sending it SIGKILL now...
PM2: 2015-08-13 05:40:55: App name:11_control id:1 exited with code SIGKILL
PM2: 2015-08-13 05:40:56: Process with pid 26210 killed
PM2: 2015-08-13 06:30:55: Starting execution sequence in -fork mode- for app name:2_control id:0
PM2: 2015-08-13 06:30:55: App name:2_control id:0 online
PM2: 2015-08-13 06:30:55: Starting execution sequence in -fork mode- for app name:11_control id:1
PM2: 2015-08-13 06:30:55: App name:11_control id:1 online
```

PS.I know i can use "pm2 sendSignal SIGUSR2 my-app" to send a "SIGTERM" signal to my app, my app will work fine, saving all the online player data and then exit, but after exit, pm2 restart my app automatically what is not i expect(what i need is app save all the data to db and then stop, so i can do other upgrade things and backup pm2 logs ). but at the same time, i also need the auto restart mechanism, when my app throw a uncaught exception, i need to save the data and then auto restart my app.

thanks!

**Comment by jshkurti** [comment]
This was implemented after this issue https://github.com/Unitech/PM2/issues/1451

You can fix your problem by setting PM2_KILL_TIMEOUT manually.
It defaults to 1600ms.
You have to set it the first time you launch PM2 daemon like this 
`PM2_KILL_TIMEOUT=60000 pm2 start app.js` (60sec)
