### ISSUE TITLE
start app.js in cluster, instance:3, how to export the log  into one file：node-out.log。

### ISSUE THREAD

**Issue by chelsh** [Unitech/PM2#1532]

**Comment by chelsh** [comment]
start app.js in cluster, instance:3, how to export the log  into one file：node-out.log。 Do not export the log into separate file:node-out1.log,node-out2.log,node-out3.log

**Comment by Tjatse** [comment]
[merge-logs](https://github.com/Unitech/PM2/blob/master/ADVANCED_README.md#configuring-logs)

**Comment by chelsh** [comment]
Thank you：）

**Comment by Tjatse** [comment]
you're welcome, feel free to file a new one if you have any confusion.

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/9299183/ff6b2684-44eb-11e5-9bb7-062f71c00387.png)




![image](https://cloud.githubusercontent.com/assets/10752360/9299183/ff6b2684-44eb-11e5-9bb7-062f71c00387.png)

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/9299190/139d5c44-44ec-11e5-9ee9-43830e3a36c8.png)

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/9299200/28942f2e-44ec-11e5-913d-855bedc3cb56.png)

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/9299231/5e1db282-44ec-11e5-821a-c4f4aaafcf7e.png)

**Comment by Tjatse** [comment]
`--merge-logs` in you `.json5` file, i.e.:
```
{
  "name":"Server-API",
  "merge_logs": true,
  ...
}
```

**Comment by chelsh** [comment]
Thank you:), my cluster are running, and the i change the .json5 file by adding "merge_logs": true, then i run the command:pm2 startOrReload ecosystem.json5  --env production --no-daemon,then logs are also node-out1.log,node-out2.log,node-out3.log.

**Comment by chelsh** [comment]
i must "pm2 delete all", and then  "pm2 startOrReload ecosystem.json5  --env production --no-daemon", it will ok

**Comment by chelsh** [comment]
i change the .json5 file, how can i let it become effective Immediately:)

**Comment by Tjatse** [comment]
```bash
pm2 delete ecosystem.json5
pm2 start ecosystem.json5 --env production
```

**Comment by chelsh** [comment]
pm2 delete ecosystem.json5---- it is the same as "pm2  delete all", it will stop all cluster,it will effect the users of my app

**Comment by chelsh** [comment]
![Uploading image.png…]()
