### ISSUE TITLE
Tell when an app is "ready" or at least listening.

### ISSUE THREAD

**Issue by sholladay** [Unitech/PM2#1537]
I have a web server built with [Hapi](https://github.com/hapijs/hapi). It starts up asynchronously, since it needs to load plugins and then listen on a port. In most cases this doesn't matter because I don't really care precisely when the app considers itself "ready" / fully initialized, the fact that PM2 launched and is managing it is good enough.

However, I ran into a case where I want to launch my app with PM2's programmatic API and be able to tell when my app is fully initialized so that I can take actions that depend upon that. What is a good way to go about that?

I have thought about writing some kind of ready file and tailing it. But ideally this would not involve any disk I/O. I am new to PM2's programmatic API, but it seems like I might be able to get a reference to something I could use for messaging through `pm2.list()`. The documentation isn't very clear on what exactly this is passing to its callback, but assuming I am right, would it make sense to use this as an interface or is there some better / more idiomatic way?

**Comment by jshkurti** [comment]
```js
var pm2 = require('pm2');

pm2.connect();

pm2.launchBus(function(err, bus) {
    bus.on('process:msg', function(msg) {
        if (msg === 'ready') {
            // Do stuff                                                                        
        }
    });
});
```

Then in your app : 
```js
process.send('ready');
```
