### ISSUE TITLE
pm2 crashes with SEGFAULT - pm2 monitors my process - what monitors pm2?

### ISSUE THREAD

**Issue by askhogan** [Unitech/pm2#1540]
I recently had a SEGFAULT with pm2 where pm2 crashed.  This created an outage.  I SSH'd and restarted pm2.  This was problematic, because I look to pm2 to be the glue that keeps my node process up.  

What do you recommend to keep pm2 up, monit?

**Comment by jshkurti** [comment]
Which version ?

**Comment by askhogan** [comment]
14.2

**Comment by jshkurti** [comment]
https://github.com/Unitech/PM2/issues/1424

It has been fixed. It's a Node.js issue, it came from node flags `--gc-global` and `--expose-gc`. We removed those and haven't heard of a segfault issue ever since :)

Upgrade PM2 to its latest version please :)

**Comment by askhogan** [comment]
Overall though the question is, PM2 is built on Node.  Node has bugs and
can fail.  PM2 spawns a bunch of stuff, so using upstart respawn is
difficult.  What process monitors PM2 to ensure that my last command stays
up?

When this segfaulted, and I logged into my box, my process is down.

I have a start on boot, but nothing else.  So for now, I can use CloudWatch
to monitor the port and reboot, but that is all.  Do you have any upstart
or systemd respawn examples?

**Comment by askhogan** [comment]
my last command = my last service / config on PM2

**Comment by askhogan** [comment]
@jshkurti hey man can you assist here, bigger issue is how do I keep a process up?  PM2 just did the same thing on 14.7

**Comment by jshkurti** [comment]
If you are linked to Keymetrics, the Keymetrics Agent has a watchdog which executes `pm2 resurrect` if PM2 got killed by a signal other than SIGINT or SIGTERM, in this case SIGSEGV (segfault signal).

**Comment by jshkurti** [comment]
But your point is valid. We should implement an external watchdog for PM2 nonrelated to Keymetrics Agent.

**Comment by jshkurti** [comment]
Does this line `pm2 has been killed by signal, dumping process list before exit...` figure somewhere in your `~/.pm2/pm2.log` ?

**Comment by carnesen** [comment]
Can you use the OS's init process to supervise the pm2 master daemon and
restart it when it crashes? I know upstart and systemd have that
capability. I figured that was part of the purpose of the "pm2 startup"
command, though I've never actually tried it.
