### ISSUE TITLE
How to force pm2 to exit?

### ISSUE THREAD

**Issue by alekbarszczewski** [Unitech/pm2#1541]
I have node.js app with following code:

```
process.on 'SIGTERM', ->
  process.exit(0)

process.on 'SIGINT', ->
  process.exit(0)

...
```

And I am starting it like this:

```
pm2 --no-daemon start server.coffee
```

Now when I, for example, hit `Ctrl+c` then pm2 show this:

```
C2015-08-19 18:24:22: pm2 has been killed by signal, dumping process list before exit...
2015-08-19 18:24:22: Stopping app:server id:0
18:24:22 PM2 pm2 has been killed by signal, dumping process list before exit...
18:24:22 PM2 Stopping app:server id:0
2015-08-19 18:24:22: App name:server id:0 exited with code 0
18:24:22 PM2 App name:server id:0 exited with code 0
2015-08-19 18:24:22: Process with pid 18004 killed
2015-08-19 18:24:22: [PM2] Exited peacefully
```

But pm2 process does not exit - console just "hangs" forever untill I hit `Ctrl-c` again.

The problem is that I am running this app in Docker and when I try to `docker stop ...` then app does not exits (as I explained above) and command hangs for 10 seconds (this is Docker default time before killing app) and then kills app.

How I can force pm2 process to exit after program that has been started with pm2 exits?

**Comment by jshkurti** [comment]
Which version of PM2 ?

**Comment by alekbarszczewski** [comment]
"pm2": "^0.14.7"

2015-08-20 18:09 GMT+02:00 Joni Shkurti <notifications@github.com>:

**Comment by jshkurti** [comment]
![pm2-exit](https://cloud.githubusercontent.com/assets/7647602/9442827/27177d08-4a7e-11e5-95d5-67c8c33bc819.jpeg)

**Comment by Unitech** [comment]
#1916
