### ISSUE TITLE
watch feature not working for folders outside script location

### ISSUE THREAD

**Issue by simoami** [Unitech/pm2#1542]
Using Mac 10.10.4, PM2 v0.14.7, Node 0.12.7.

Folder structure:

```
project dir
|-- pm2-dev.json
|-- server/
|   |-- server.js
|   |-- test.js
|-- common/
|   |-- models/
|       |-- model.js
```

JSON file: pm2-dev.json

``` json
{
  "name" : "server",
  "script" : "server/server.js",
  "cwd": ".",
  "watch": [
    "common",
    "server"
  ]
}
```

pm2 executed as:

```
pm2-dev start pm2-dev.json
```

Changes to test.js are picked up. but changes to model.js are not detected. I tried a combination of values for the cwd and watch paths without success.

**Comment by jshkurti** [comment]
@soyuka

**Comment by soyuka** [comment]
![](http://www.zupmage.eu/i/3lYlnYrT6q.png)

On top pm2 + debug (`DEBUG="pm2:watch" pm2 start server-watch.json --no-daemon`)
Left `echo` and `touch`
Right-top `ls -lR` (file structure)
Right-bottom configuration:

```json
[{
  "name"      : "server-watch",
  "script"    : "./server/server.js",
  "watch"     : ["**"],
  "cwd"       : "/home/abluchet/testwatcher"
}]
```

Use an absolute `cwd`. When using paths in the `watch` option, use relative ones to the cwd, this also accept glob patterns. Here I'm taking everything (recursively `**`) but another working option could be:

```json
{watch: ['server/*.js', 'common/**']}
```

**Comment by jshkurti** [comment]
@soyuka thanks !

**Comment by simoami** [comment]
Hello, I prefer not to set an absolute path in cmd specific to an individual machine, forcing all developers to modify the path to their system. This isn't common practice. Is there any workaround?

**Comment by soyuka** [comment]
`cwd` will be set to the path you launch `pm2 start`. It's not required.

**Comment by simoami** [comment]
is there a resolution for this yet? I've used the following config based on @soyuka 's recommendation, but didn't specify `cwd` hoping that it picks up the current directory. but it doesn't help. 

```
{
  "name" : "searchedgejs",
  "script" : "./server/server.js",
  "watch": ["**"]
}
```

Folders under server/ are properly watched but nothing outside of it. Also, it shouldn't be expected for a project to have `cwd` hardcoded to a specific machine path. e.g. `/home/soyuka/nodetest`

**Comment by soyuka** [comment]
And what is your `process.cwd()`?

`pm2 desc` => `exec cwd`.

Did you try watching specific directories ? 

```
{"watch": ["server/*.js", "common/**"]}
```
