### ISSUE TITLE
PM2 Deploy/JSON App Declaration Cluster Mode Not Working On Random Port

### ISSUE THREAD

**Issue by KoltonG** [Unitech/pm2#1545]
I am having issues when updating my code using `pm2 deploy HOST-1 update` where when it reloads for some reason either the api on port A or port B does not work anymore and in `pm2 list` it shows that it is online. I thought it was an issue with HAProxy but when I `sudo rm -rf current shared/ source/` and completely uninstall pm2 and reinstall it, it then works?

Any idea what could be causing this, if you need more information I can gladly give more. Thanks!

Here is my ecosystem.json file

```
"apps" : [{
      "name"              : "API",
      "script"            : "api.js",
      "watch"             : true,
      "exec_mode"         : "cluster",
      "instances"         : 2,
      "merge_logs"        : true,
      "error_file"        : "/home/ubuntu/shared/logs/API.log",
      "out_file"          : "/home/ubuntu/shared/logs/API.log",
      "max_restarts"      : 15,
      "max_memory_restart": "300M",
      "restart_delay"     : 5000,
      "env_production"    : {
        "NODE_ENV": "production",
      }    
    }],
  "deploy" : {
    "Host-1" : {
      "user" : "<USER>",
      "host" : "<IP>",
      "key"  : "<KEY>",
      "ref"  : "<MASTER>",
      "repo" : "<GIT>",
      "path" : "<PATH>",
      "post-deploy" : "sudo npm install --production && pm2 startOrReload ecosystem.json --env production && sudo pm2 logrotate -u ubuntu && sudo pm2 startup -u ubuntu && sudo pm2 save -u ubuntu"
    }
  }
}
```

And the ports in the api.js files are determined like this
`var port               = 900 + process.env.NODE_APP_INSTANCE;`

**Comment by jshkurti** [comment]
Can you print the value of process.env.NODE_APP_INSTANCE before and after the `pm2 deploy update` for both of your instances running ? :)

**Comment by KoltonG** [comment]
Ill make an dummy app on another host to try this, I had to change my ecosystem.json to have two apps that are the same in the meantime to make it work.
