### ISSUE TITLE
[Feature Request]Reset restart count

### ISSUE THREAD

**Issue by benhk2005** [Unitech/PM2#1546]
Sometimes I would forgot whether the restart is done by me or the node itself error cause to restart.
It would be great if I can reset the restart count by using the command line without removing the job and add back again.

**Comment by ftortega** [comment]
$ pm2 reset <process>    # Reset meta data (restarted time...)

**Comment by nilaeus** [comment]
The link didn't work, this one does: https://github.com/Unitech/PM2/blob/master/ADVANCED_README.md

**Comment by ProCylon** [comment]
pm2 reset <process>    
# Reset meta data (restarted time...)
# <process> = App name

**Comment by antonytrupe** [comment]
neither of the links work anymore :(

**Comment by orgads** [comment]
https://pm2.keymetrics.io/docs/usage/pm2-doc-single-page/#cheatsheet

**Comment by Unitech** [comment]
https://pm2.keymetrics.io/docs/usage/process-management/#reset-restart-count

**Comment by EwertonDutra** [comment]
> https://pm2.keymetrics.io/docs/usage/process-management/#reset-restart-count

Reset all 😁
Best option!
