### ISSUE TITLE
on SIGINT

### ISSUE THREAD

**Issue by btmdave** [Unitech/PM2#1548]
I want to get notified when pm2 has restarted/stopped/crashed/exited.

`process.on('SIGINT')` is what seems to be called, I added a listener and this is the result:

```
index-0 SIGINT (console.log)
PM2 Process with pid 14152 still not killed, retrying...
PM2 Process with pid 14152 still not killed, retrying...
PM2 Process with pid 14152 still not killed, retrying...
PM2 Process with pid 14152 still not killed, retrying...
PM2 Process with pid 14152 still not killed, retrying...
PM2 Process with pid 14152 still not killed, retrying...
PM2 Process with pid 14152 still not killed, retrying...
PM2 Process with pid 14152 still not killed, retrying...
PM2 Process with pid 14152 still not killed, retrying...
PM2 Process with pid 14152 still not killed, retrying...
PM2 Process with pid 14152 still not killed, retrying...
PM2 Process with pid 14152 still not killed, retrying...
PM2 Process with pid 14152 still not killed, retrying...
PM2 Process with pid 14152 still not killed, retrying...
PM2 Process with pid 14152 still not killed, retrying...
PM2 Process with pid 14152 still alive after 1600ms, sending it SIGKILL now...
```

Is this the best way to do this or is there a better/built-in method to listen for exit?

**Comment by jshkurti** [comment]
SIGINT is sent only when PM2 tries to stop/restart the process.
If your process crashes by himself there is no SIGINT, you have to listen for 'uncaughtException' in this case.

**Comment by btmdave** [comment]
Ok so that's fine, so handling both of these cases should cover all grounds? are there any issues with listening to SIGINT?

**Comment by jshkurti** [comment]
No, there aren't, just don't forget to process.exit() when you are finished and be careful of SIGKILL which is going to be sent after PM2_KILL_TIMEOUT milliseconds.
You might need to set PM2_KILL_TIMEOUT higher if your tasks take some time to execute.
