### ISSUE TITLE
pm2 logs throws 'EINVAL, read' error on an empty log file

### ISSUE THREAD

**Issue by withinsea** [Unitech/PM2#1551]
Built an empty project or call 'pm2 flush' to remove all logs, then call `pm2 logs` before anything was writen to log files, it shows:
```
C:\proj>pm2 logs
[PM2] Tailing last 20 lines for [all] processes

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: EINVAL, read
    at Error (native)
```

Checked the source and found this throwed while creating a ReadStream in `lib/Log.js`:
```javascript
  var getLastLines = function (filename, lines, callback) {
    var chunk = '';
    var size = fs.statSync(filename).size - (lines * 200);

    var fd = fs.createReadStream(filename, {start : size});
    fd.on('data', function(data) { chunk += data.toString(); });
    fd.on('end', function() {
      chunk = chunk.split('\n').slice(-(lines+1));
      chunk.pop();
      callback(chunk);
    });
  };
```

Look at the option `start:size` in the `fs.createReadStream` line, the value of `size` is subtract size of 200 lines from the size of log file.
Reading an empty log file means the size of file is 0, thus making `size` a negative number, causing the error.

Giving `size` a minimum value solved my problem:
```javascript
    var size = fs.statSync(filename).size - (lines * 200);
    size = Math.max(0, size);
    var fd = fs.createReadStream(filename, {start : size});
```

I don't know whether other peoples have met the same problem...
I'm using Windows, maybe nodejs for linux supports a negative start?

**Comment by jshkurti** [comment]
Never had this error on unix indeed. We don't really support Windows anymore, sorry :(

**Comment by kayz1** [comment]
Same problem here v0.14.7
