### ISSUE TITLE
delete all cluster instances by name

### ISSUE THREAD

**Issue by nodesocket** [Unitech/PM2#1552]
When using cluster mode and 4 instance, pm2 created 4 processes just fine. The problem is how to delete all 4. Right now I have to manually run:

     pm2 delete {{id-of-1}}
     pm2 delete {{id-of-2}}
     pm2 delete {{id-of-3}}
     pm2 delete {{id-of-4}}

Is there a way instead to say delete all instances in the cluster by name?

**Comment by adrian-ludwig** [comment]
Almost everywhere you can use id|name|all|json
