### ISSUE TITLE
PM2 SH Bad Substitution on deploy

### ISSUE THREAD

**Issue by herghost** [Unitech/PM2#1553]
Hi all, can anyone point out what script could result in this error? My app deploys fine however I use stash for deployment and this is reporting the build has failed

    pm2 deploy ecosystem.json production
    --> Deploying to production environment
    --> on host 192.168.0.195
      ○ deploying
      ○ hook pre-deploy
      ○ fetching updates
    Fetching origin
      ○ resetting HEAD to origin/master
    HEAD is now at 78297ee Merge pull request #6 in AA/ppm---stores from dev to master
      ○ executing post-deploy `pm2 startOrRestart ecosystem.json —env production`
    [PM2] restartProcessId process id 0
    [PM2] restartProcessId process id 1
    ┌─────────────────┬────┬──────┬───────┬────────┬─────────┬─────   ───┬─────────────┬──────────┐
│ App name        │ id │ mode │ pid   │ status │ restart │ uptime │ memory      │ watching │
├─────────────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────────────┼──────────┤
│ PPM Stores Test │ 0  │ fork │ 28151 │ online │ 8       │ 0s     │ 15.770 MB   │ disabled │
│ PPM Stores Live │ 1  │ fork │ 28163 │ online │ 8       │ 0s     │ 5.395 MB    │ disabled │
└─────────────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────────────┴──────────┘
    Use `pm2 show <id|name>` to get more details about an app
    sh: 1: Bad substitution

      post-deploy hook failed

     Deploy failed

if I run pm2 startOrRestart ecosystem.json —env production from command then it builds without this error.

This is on Ubuntu 14.04.1

**Comment by jpdesigndev** [comment]
Same problem here.. Not sure what to make of it.

**Comment by jpdesigndev** [comment]
@Unitech I've seen hints that this could be related to the fact that Ubuntu uses dash instead of bash. Does this seem like the likely culprit?

**Comment by herghost** [comment]
@jpdesigndev - Based on your comment I gave my pm2 group permission for bash and this has done the trick.

**Comment by soyuka** [comment]
See also #1456 if you have thoughts/ideas

**Comment by jpdesigndev** [comment]
@herghost Sorry, linux skills are lacking. How might I do this?

**Comment by herghost** [comment]
@jpdesigndev I am using webmin on my server so I did it through that, however I believe the followig commands should do it
chsh (From the user you want to add)
//Enter your password, then
/bin/bash

**Comment by jpdesigndev** [comment]
Ah, thanks... Looks like my user couldn't do this, so I had to do it this way,

```
sudo chsh -s /bin/bash web
```

**Comment by herghost** [comment]
Hope it helped :-)

**Comment by jpdesigndev** [comment]
@herghost Yep, pm2 deployment successful! Thank you.

**Comment by Finkes** [comment]
had the same issue. Changing the shell to /bin/bash fixed it. thanks!
