### ISSUE TITLE
Deploying a private repository?

### ISSUE THREAD

**Issue by StevenLangbroek** [Unitech/pm2#1556]
We're using Ruby + Capistrano for most of our infrastructure, which uses local user's keys to access private repositories. How does this work in PM2? Can't find much documentation about it...

**Comment by StevenLangbroek** [comment]
So I found the `forward-agent` config option, should this be documented somewhere?

**Comment by randomsync** [comment]
@StevenLangbroek how did you use the `forward-agent` option? I had the same issue but was able to get around by adding the `ForwardAgent yes` to my ssh config file.
