### ISSUE TITLE
Daemon should support non-background mode

### ISSUE THREAD

**Issue by wmertens** [Unitech/pm2#1562]
For process monitoring services like launchd, systemd and monit, it would be best if you could run the PM2 daemon without it going to the background.

Then all the OS tools can be used to set resource limits, do monitoring etc.

**Comment by soyuka** [comment]
`--no-daemon` would suffice?

**Comment by wmertens** [comment]
Oh, I didn't find that. In that case, shouldn't the startup scripts for
systemd and launchd use that option?

On Fri, Aug 28, 2015 at 2:00 PM Antoine Bluchet <notifications@github.com>
wrote:

> --no-daemon would suffice?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Unitech/PM2/issues/1562#issuecomment-135749703>.
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by soyuka** [comment]
I won't see why they should but I'm all ears if you have pros arguments.

**Comment by wmertens** [comment]
Well the main argument is that launchd will know that PM2 is running and it
will show like that when running `launchctl list`.
Systemd can work around the forking but non-forking is preferred and
recommended.

On Fri, Aug 28, 2015 at 7:06 PM Antoine Bluchet <notifications@github.com>
wrote:

> I won't see why they should but I'm all ears if you have pros arguments.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Unitech/PM2/issues/1562#issuecomment-135833699>.
>
-- 

Wout.
(typed on mobile, excuse terseness)
