### ISSUE TITLE
pm2 pull - "No versioning system found for process..."

### ISSUE THREAD

**Issue by ericterpstra** [Unitech/PM2#1563]
I'm having trouble getting PM2 to recognize the .git folder in my application.  My folder structure is like this (on Windows Server 2012 R2)

```
D:\wwwroot\myapp\.git
D:\wwwroot\myapp\myapp-pm2.json
D:\wwwroot\myapp\someotherfiles.foo
D:\wwwroot\myapp\bundle\main.js  <= node app entry point
```

Below is my .json config for PM2.  I'm using `pm2 start myapp-pm2.json` which seems to be working fine.

```json
{
  "apps" : [{
    "name"        : "myapp",
    "script"      : "bundle\\main.js",
    "cwd"         : "D:\\wwwroot\\myapp",
    "env": {
      "NODE_ENV": "production",
      "PORT" : 3000
    }
  }]
}
```

However, when I do `pm2 pull myapp`, I get the error:

```
[PM2] Updating repository for process name myapp
[PM2] No versioning system found for process myapp
```

Is this something I'm doing wrong, or does `pm2 pull` not work with Windows?

**Comment by zalym** [comment]
i have the same issue.  pm2 version is 0.14.6

**Comment by Unitech** [comment]
Not sure that these commands work on Windows: https://github.com/keymetrics/vizion/blob/master/lib/git.js#L183

If any one could make suggestion to make this work on windows, drop an issue or pr on vizion package

**Comment by zalym** [comment]
@Unitech I am having this issue in Linux.

**Comment by jinceon** [comment]
@zalym  maybe your git version is too old.

http://stackoverflow.com/questions/36497380/version-control-metadata-sometimes-missing-when-i-use-pm2

after I updated my git, the problem was resolved.

**Comment by Olegt0rr** [comment]
It's not git problem!

/home/app/app.py
/home/start_app.json


pm2 can see .git if I start app directly from /home/app/app.py
But if I start app by /home/start_app.json - pm2 can't sell .git and return error No versioning system found for process...

Please fix it

**Comment by mattehicks** [comment]
Same problem here, I'm using Linux and starting apps using  "pm2 start npm --name"
Keymetrics is telling me "no .git found in the project"

**Comment by levon-gevorgyan** [comment]
@Unitech The issue still exists when I start the app through npm ("pm2 start npm --name"). (on Linux too)

**Comment by Kovaelin** [comment]
@Unitech Is this sill an issue?
