### ISSUE TITLE
treekill option has inconsistent behaviour when pm2 is used via json configuration (application declaration)

### ISSUE THREAD

**Issue by paulovieira** [Unitech/pm2#1564]
Suppose I give the options to pm2 directly in the command line:

``` bash
pm2 start index.js --name "my-app"
```

Then the treekill feature will be used (that is, when i call `pm2 stop my-app`, pm2 will kill all the children). This is the expected behaviour, in my opinion.

However if I use pm2 via json configuration, using the same options from the command line, pm2 won't kill the child processes. That is, if I have a `pm2-conf.json` like this:

``` js
{
  "name": "my-app",
  "script": "index.js",
}
```

and if I execute 

``` bash
pm2 start pm2-conf.json
pm2 stop my-app
```

then the child processes will remain alive. To make sure they are killed the json must have the "treekill" property, which isn't even [documented in the docs](http://pm2.keymetrics.io/docs/usage/application-declaration/) (I found it in `lib/schema.json`)

``` js
{
  "name": "my-app",
  "script": "index.js",
  "treekill": true
}
```

So I suggest that the "treekill" option should be true by default when pm2 is used via application configuration, as that's the default behaviour when the options are given directly in the command line.

**Comment by ninja-** [comment]
@Unitech the `treekill` option in json doesn't seem to work. I set it to false.
I start my app via $ pm2 start myapp.json [fork mode]
then $ pm2 restart myapp kills it along with childs.
It works fine if I do pm2 --no-treekill restart myapp though. Why?

**Comment by kripplek** [comment]
I can confirm the json value is entirely ignored. The cli option does work for stop gap. Any updates on this @Unitech ?

**Comment by ninja-** [comment]
@kripplek this is fixed on master after I complained. It's not released to npm yet :/

**Comment by kripplek** [comment]
@ninja- Thanks for the heads up. When can we get the npm release updated?
