### ISSUE TITLE
like memory leak on cluster mode

### ISSUE THREAD

**Issue by smallnewer** [Unitech/pm2#1567]
sorry for my english.

I use pm2 in production env. memory will grow up until app crashed.

config file:

```
{
    "apps": [{
        "name"             : "xxx",
        "cwd"              : "/xxx",
        "args"             : [ 'xxx=xxx' ],
        "script"           : "app.js",
        "node_args"        : [],
        "log_date_format"  : "YYYY-MM-DD HH:mm Z",
        "error_file"       : "xxx.err.log",
        "out_file"         : "xxx.out.log",
        "pid_file"         : "xxx.pid",
        "instances"        : 1,
        "merge_logs"       : true,
        "exec_interpreter" : "node",
        "exec_mode"        : "cluster",
        "env": {
            "NODE_ENV": "production"
        }
    }]
}
```

iojs 1.8.2 
pm2 0.12.15 and 0.14.7
centos 6.5 64

But, I use fork mode ,It's okay.
And, I use node cluster module to run app.js, it's okay.
Only use pm2 and cluster mode, memory will grow up and can not stop.

**Comment by crobinson42** [comment]
[https://github.com/lovell/sharp/issues/1803 ](https://github.com/lovell/sharp/issues/1803)

```
This issue only issue on pm2 cluster mode.
pm2 fork mode able to load libjemalloc correctly but cluster.

Some how the pm2 cluster mode unable to load libjemalloc correctly.
```

**Comment by crobinson42** [comment]
@Unitech @vmarchaud I was preparing to open a new issue and I found this open from 2015 - I posted a comment above ☝️ on how I've come to this conclusion that pm2 does not release memory back to the OS. 

The issue is only experienced in cluster mode and appears to be related to cluster mode not loading `libjemalloc`. 

Any help or direction?
