### ISSUE TITLE
Providing app name doesn't rename the process 

### ISSUE THREAD

**Issue by demisx** [Unitech/pm2#1568]
I am trying to start a process with a specific name:

``` bash
$ pm2 start app.js --name "api"
```

However, the process is still running as `app`:

![screen shot 2015-08-30 at 9 51 32 am](https://cloud.githubusercontent.com/assets/4452412/9568387/c004ce3a-4efc-11e5-9daf-1020349271c0.png)

**Comment by jonkafton** [comment]
Just delete it first

    pm2 delete app

**Comment by Unitech** [comment]
Updating application name via `pm2 restart app --name "new-name"` will be available in PM2 1.0.3

**Comment by Unitech** [comment]
Update available (PM2@1.1.1 - latest stable):

```
$ npm install pm2@latest -g
$ pm2 update
```

Please re-open this issue if you notice any problem,

**Comment by indrasantosa** [comment]
I still have this issue. I still not able to rename my process @Unitech

**Comment by vmarchaud** [comment]
@indrasantosa Are you sure that you have updated the PM2 Daemon ? Do a `pm2 update` to be sure.

**Comment by indrasantosa** [comment]
Hi @vmarchaud, Yes, I use pm2 2.1.5

**Comment by Nocturnal316** [comment]
same here doesn't work. on version 2 .1.6

**Comment by haozxuan** [comment]
same here doesn't work. on version 2.2.2

**Comment by Unitech** [comment]
`pm2 restart app --name "new-name" --update-env`
