### ISSUE TITLE
"This account is currently not available" Error

### ISSUE THREAD

**Issue by demisx** [Unitech/PM2#1569]
Running startup command on Ubuntu 14.04 LTS server results  in the following account not available error:

```bash
app@ws:~$ pm2 startup ubuntu -u app
[PM2] You have to run this command as root. Execute the following command:
      sudo su -c "env PATH=$PATH:/usr/bin pm2 startup ubuntu -u app"
app@ws:~$ sudo su -c "env PATH=$PATH:/usr/bin pm2 startup ubuntu -u app"
[sudo] password for app: 
This account is currently not available.
```

**Comment by Unitech** [comment]
This is not linked to pm2, have you tried this: https://geekpeek.net/this-account-is-currently-not-available-login-problems/

**Comment by demisx** [comment]
Yes, our root not having a valid shell was causing the error. However, we do not give root a valid shell for security purposes. If we already run the command as root, is there a reason to `su -c`?
