### ISSUE TITLE
Cluster with UNIX Socket

### ISSUE THREAD

**Issue by DaAwesomeP** [Unitech/pm2#1570]
Instead of a port, my app listens on a UNIX socket. Will clustering work with this? I can't quite get it to work. I get all sorts of errors.

**Comment by Unitech** [comment]
Which node.js version are you using? Btw the Node.js cluster module handle UNIX socket

**Comment by DaAwesomeP** [comment]
I'm using io.js v1.8.4 (I need to upgrade to 2.x, but I haven't gotten around to it). I am simply telling both clustered apps to listen on the same socket path.

**Comment by Synchro** [comment]
I have a similar problem - I can't figure out how to make pm2 start a single app in cluster mode in a way that allows the app to create its sockets somewhere it has permission (e.g. /var/run is not writable to unprivileged apps) and that it is predictable so I can point an nginx rev proxy at it. I created [a serverfault Q](http://serverfault.com/questions/734441/pm2-sockets-and-permissions) about it. It's easy to do with upstart, but I can't figure out how to do it at all with pm2.

**Comment by manico** [comment]
Same here. I get error:

```
PM2        | 2016-10-27 09:01:45: Process 0 in a stopped status, starting it
PM2        | 2016-10-27 09:01:45: Starting execution sequence in -cluster mode- for app name:gravity id:0
PM2        | 2016-10-27 09:01:45: App name:gravity id:0 online
PM2        | 2016-10-27 09:01:46: Error: write ENOTSUP
PM2        |     at exports._errnoException (util.js:1026:11)
PM2        |     at ChildProcess.target._send (internal/child_process.js:654:20)
PM2        |     at ChildProcess.target.send (internal/child_process.js:538:19)
PM2        |     at sendHelper (cluster.js:751:15)
PM2        |     at send (cluster.js:534:12)
PM2        |     at cluster.js:509:7
PM2        |     at SharedHandle.add (cluster.js:99:3)
PM2        |     at queryServer (cluster.js:501:12)
PM2        |     at Worker.onmessage (cluster.js:450:7)
PM2        |     at ChildProcess.<anonymous> (cluster.js:765:8)
PM2        | 2016-10-27 09:01:46: App name:gravity id:0 disconnected
PM2        | 2016-10-27 09:01:46: App [gravity] with id [0] and pid [9768], exited with code [0] via signal [SIGTERM]
```

Code works without PM2.

Sample:

```javascript
// Import libs
const os = require('os');
const net = require('net');

// Export socket server
module.exports = {
    start: function () {
        // Create socket depending on platform
        // NOTE: Unix sockets will be saved to sock directory, windows will create named pipe
        let socket = os.platform() === 'win32' ? '\\\\.\\pipe\\gravity.sock' : gravity.path + '/sock/bridge.sock';

        // Create server
        const server = net.createServer((connection) => {
            connection.on('data', (data) => {
                data = data.toString();
                console.log(data);
            });
        });

        // Start server only in one worker
        if (!server.address()) {
            server.listen(socket);
        }
        
        // Close server before exit
        process.on('exit', () => {
            server.close();
        });

        // Call exit explicitly
        process.on('SIGINT', () => {
            process.exit();
        });
    }
};
```

**Comment by soyuka** [comment]
IMO it's the `Start server only in one worker` condition that is failing. @manico I assume this code works with the fork mode?

**Comment by manico** [comment]
I just tried that condition.
It is the same without that if statement.

Yes, it works in pm2 fork mode.

**Comment by soyuka** [comment]
Yes but your should have a condition there because you can't listen twice on the same socket. I'm looking for a condition that would work, maybe print out env variable to see if one can be used. @Unitech any idea on how we could differentiate master from child here?

**Comment by manico** [comment]
I understand that and I can place some condition or create name like 'gravity' + process.pid + '.sock'.
I have tried this and no success.
Even if I run pm2 in cluster mode with **one instance** same error is thrown.
