### ISSUE TITLE
Premature exit for cluster mode processes

### ISSUE THREAD

**Issue by kanongil** [Unitech/pm2#1571]
When a cluster mode process is stopped, `console.log` usage after it has been disconnected can cause the process to exit immediately with a non-zero exit code.

Example **server.js**:

``` js
var http = require('http');
var server = http.createServer();
server.listen(0);

process.on('SIGTERM', function () {
  console.log('SIGTERM');
  process.exit(0);
});
```

Now run:

``` sh
pm2 start server.js -i 2
pm2 stop server
```

The following is reported in the pm2 log:

```
PM2 Stopping app:server id:0
PM2 App name:server id:0 disconnected
PM2 App name:server id:0 exited with code 7
PM2 Process with pid 17542 killed
PM2 Stopping app:server id:1
PM2 App name:server id:1 disconnected
PM2 App name:server id:1 exited with code 7
PM2 Process with pid 17543 killed
```

If I remove the `console.log()`, it will exit with code `0`, as expected.

It will also work (albeit without the log message) if I comment out [these lines](https://github.com/Unitech/PM2/blob/04c72a75833891ab85f2093779eb8bb886e742d4/lib/ProcessContainer.js#L42-L43) in ProcessContainer.js.

**Comment by kanongil** [comment]
Great. No response to a flaw in the very fundamentals of what you do...

Anyway, I give up. You are on your own.

**Comment by wanming** [comment]
+1
