### ISSUE TITLE
setting DEFAULT log timestamp format

### ISSUE THREAD

**Issue by pacmac** [Unitech/PM2#1573]
I have googled and searched and cannot find an answer, that indicates what file name to set the default logging behavior in.

I can find references to .js and .json files, but nothing that actually specifies the file name that needs to be edited.

I tried this, but it does not appear to work:

conf.js
==
    {
      "config": {             // Default configuration value
        "log_date_format"  : "YYYY-MM-DD HH:mm Z"
     }
    }

module.conf.json
==
    {
      "config": {             // Default configuration value
        "log_date_format"  : "YYYY-MM-DD HH:mm Z"
     }
    }

But after restarting the services (pm2 restart all) I still don't get any timestamps ?

What am I doing wrong ?

**Comment by Unitech** [comment]
You need to define it in your [application declaration](http://pm2.keymetrics.io/docs/usage/application-declaration/), more info here: http://pm2.keymetrics.io/docs/usage/log-management/

**Comment by diginfo** [comment]
Yes, but nowhere in the text does it say what the filename of these "json/js" is !

"Declaration via JS, JSON or JSON5 file
You can define parameters for your apps in a JS/JSON file:"

**Comment by Unitech** [comment]
it can be any name. For example if you do your app declaration in process.json, after you do pm2 [start|restart|reload] process.json
