### ISSUE TITLE
post_update doesn't execute when package.json not in repo root

### ISSUE THREAD

**Issue by wmertens** [Unitech/pm2#1574]
Hi,

I have this in my package.json:

```
  "apps": [{
    "name": "www",
    "script": "lib/server-production.js",
    "autorestart": true,
    "env": {
      "NODE_ENV": "production",
      "PORT": 8080
    },
    "post_update": ["npm run build"]
  }],
```

I started the server with `$ ./node_modules/.bin/pm2 start package.json`. It runs fine, but when I pull it doesn't run the `post_update` commands.

```
$ ./node_modules/.bin/pm2 pull www
[PM2] Updating repository for process name www
[PM2] Process successfully updated www
[PM2] Current commit 856b6b5889e66d09188fc355a48e6ace2b8a8234
[PM2] Reloading process by name www
[PM2][WARN] www app can't be reloaded - restarting it
[PM2] restartProcessId process id 0
[PM2] All processes reloaded
```

Any pointers on troubleshooting this?

**Comment by wmertens** [comment]
I found out why: My package.json is not in the git root. I think this is a bug.

**Comment by rparaschak** [comment]
I have similar problem. I use gulp where I do pm2.start('./ecosystem.json'). I use the following ecosystem.json file:

{
  "apps": [
    {
      "name": "frontend",
      "script": "app.js",
      "instances": 4,
      "exec_mode": "cluster_mode",
      "max_memory_restart": "100M",
      "out_file": "logs/pm2logs/frontend/log.log",
      "autorestart": true,
      "post_update": [
        "echo App has been updated, running npm install...",
        "npm install",
        "echo Running bower install",
        "bower install",
        "echo Running gulp build --mode production",
        "gulp build --mode production",
        "echo App is being restarted now"]
    }
  ]
}

Same config i've put int package.json file. It just doesn't execute post_update lines after 'pm2 pull frontend'.

Can someone assist with this issue?

**Comment by rparaschak** [comment]
I've found the issue,

i was expecting to see commands output in console, but there was nothing. All the commands were executed.
