### ISSUE TITLE
interpreter ignored when using cluster mode

### ISSUE THREAD

**Issue by creynders** [Unitech/PM2#1575]
This works as expected:

- `pm2 start app -i 2`
- `pm2 start app --interpreter=/usr/local/n/versions/node/0.12.0/bin/node`

But when combined the interpreter argument is ignored:

- `pm2 start app -i 2 --interpreter=/usr/local/n/versions/node/0.12.0/bin/node`

The same applies when declared in a json file

**Comment by Unitech** [comment]
Hello,

Yes in fork mode you can defined the interpreter but in cluster mode it's not possible as we rely on the current Node.js version that runs PM2 to use the cluster module (https://github.com/Unitech/PM2/blob/master/lib/God/ClusterMode.js#L50)

**Comment by creynders** [comment]
Hmm, yes of course, that makes sense. A real pity though.

**Comment by tangxinfa** [comment]
Suggest documention it(in npm --help output or some where else), i waste many time to investigate the same problem:(

**Comment by jippi** [comment]
I stumbled on this as well

@Unitech I would like to be able to overwrite the `interpreter`, since i depend on envconsul ( github.com/hashicorp/envconsul/ ) to inject the relevant ENV variables to my node script

Basically i want to prefix whatever `interpreter` is in `cluster` mode with a command to enrich the environment :) 

Any way to achieve this?

**Comment by vmarchaud** [comment]
PM2 has a hardcoded binary name (which is 'node') for start in cluster mode since we are using the cluster mode of nodejs. By the way you can inject custom env values into your app using PM2 (cf. http://pm2.keymetrics.io/docs/usage/application-declaration/)

**Comment by jippi** [comment]
@vmarchaud sure, but being able to wrap that binary would be wildly useful, as my example above shows, that it would be my own responsibility to pass the what-ever i put in `interpreter` to `node` (eventually) 

Having the environment variables in a static file is not an optimal requirement/pattern for docker and highly flexible environments where these things change quite rapidly and can come from multiple sources.

**Comment by vmarchaud** [comment]
@jippi Understood but other people might try to use another interpreter in cluster mode and since its wont work, tell us that its our responsibility to verify that the interpreter is node, so yeah, not an easy choice here.

**Comment by jippi** [comment]
@vmarchaud would it make sense to have a new config key for this ? e.g. `node_bin` or something, where i can provide my own path to whatever should be considered a node binary ? 

Would also allow me to mix nodejs versions easily under the same pm2 instance :)

**Comment by soyuka** [comment]
I think you can already do this by using `NODE_PATH`. It's evaluated before `PATH` in pm2.

**Comment by tayden** [comment]
My working workaround is to do:

`PATH=/usr/local/n/versions/node/0.12.0/bin:$PATH pm2 start app -i 2`
