### ISSUE TITLE
pm2 API with watch string or array crash on windows + workaround

### ISSUE THREAD

**Issue by amelon** [Unitech/PM2#1578]
I've found an error and a workaround when using pm2 API.

Problem is on watcher (line 47).
It appears that process.env.PWD is ``undefined`` on windows.

Find below the code I'm using and the fix by assigning ``process.env.PWD`` with ``process.cwd()`` value.

````
var gulp         = require('gulp');
var pm2 = require('pm2');

gulp.task('pm2', function(done) {
  var conf = require('./config/pm2/base.json');

  // bug on pm2 (watcher - 47) which expects process.env.PWD to exist
  process.env.PWD = process.cwd();

  pm2.connect(true, function() {
    pm2.start(conf, function(err /*, apps*/) {
      if (err) throw err;
      console.log('pm2 started');
      pm2.streamLogs('all', 0);
      done();
      // pm2.disconnect();
    });
  });
});

````

Problem identified is in file ``lib/Watcher.js`` on the following line

````
...
      watch = [].concat(pm2_env.watch).map(function(dir) {
          return p.resolve(process.env.PWD, dir);
      });
...
````

**Comment by soyuka** [comment]
We had an issue when pm2 and the process didn't had the same `cwd`. So, we used `PWD` instead of `process.cwd()`: https://github.com/Unitech/PM2/commit/6a5712814ed807b6d9d97af15d8159b05fdd7141

What could be the alternative on windows?

Could you try using `pm2_env.pm_exec_path` instead of `process.env.PWD`?

**Comment by amelon** [comment]
``pm2_env.pm_exec_path`` is not a directory but the script file to be executed by pm2, thus ``path.resolve`` will fail :(.

But ``pm2_env.pm_exec_path`` is resolved with ``pm2_env.pm_cwd``

Common.js
````
...
app.env.pm_cwd = cwd;
app.pm_cwd = cwd; 
app.script = p.resolve(cwd, app.script);
...
````

``pm2_env.pm_cwd`` should be the right param.

Everything is ok with following lines in Watcher.js
````
...
      watch = [].concat(pm2_env.watch).map(function(dir) {
          return p.resolve(pm2_env.pm_cwd, dir);
      });
...
````

**Comment by soyuka** [comment]
@amelon Thanks! Agreed about `pm_exec_path`, I'll patch this!

**Comment by amelon** [comment]
@soyuka quick answer & fix. merci :)
