### ISSUE TITLE
PM2 on Heroku Hobby instance.

### ISSUE THREAD

**Issue by AlejandroJL** [Unitech/pm2#1582]
Hello!

I am trying to start pm2 in Heroku following the explanation that there is *http://pm2.keymetrics.io/docs/usage/use-pm2-with-cloud-providers/*. But I can not run it well. 

any ideas?

A greeting and thank you!

**Comment by Unitech** [comment]
*You can not run it well*... Well I cannot help you if you do no give me any clues of what's going on

**Comment by Unitech** [comment]
You can checkout the integration with amazon elastic beanstalk: http://pm2.keymetrics.io/docs/tutorials/use-pm2-with-aws-elastic-beanstalk/
