### ISSUE TITLE
When ES6 extension is used, two processes are started instead of one

### ISSUE THREAD

**Issue by stepankouba** [Unitech/pm2#1583]
Just take this code and save it once as server.js and once as server.s6.

	var express = require('express');
	var app = express();

	app.get('/', function (req, res) {
  		res.send('Hello World!');
	});

	var server = app.listen(3000, function () {
		var host = server.address().address;
		var port = server.address().port;

		console.log('Example app listening at http://%s:%s', host, port);
	});

When pm2 start server.js is performed, just one node process is started.

When pm2 start server.s6 is performed, two processes are started

using pm2 0.14.7

**Comment by stepankouba** [comment]
detail of two started processes in case of using ES6 extension:
node /usr/local/lib/node_modules/pm2/node_modules/babel/lib/_babel-node PATH_TO_SERVER.ES6
/usr/local/lib/node_modules/pm2/node_modules/babel/bin/babel-node.js PATH_TO_SERVER.ES6

**Comment by stepankouba** [comment]
Closing since it's probably problem with babel-node. Similar issue solved by forever: https://github.com/foreverjs/forever/issues/687

in order to avoid the problem, create starting file with following content:
require('babel-core/register');
require('./server.es6');

**Comment by soyuka** [comment]
Is it preventing your script from working? 

`babel/register` code reference: https://github.com/Unitech/PM2/blob/bc30bda25a23cb39a1dda6dc848cc8c98e867779/lib/ProcessContainer.js#L103

**Comment by stepankouba** [comment]
The problem is with stoping the server (pm2 stop server or pm2 delete all). One of the two processes is there still running. EADDRINUSE error is in such case thrown

**Comment by soyuka** [comment]
Ok this needs investigations,

**Comment by soyuka** [comment]
Following up in #2005
