### ISSUE TITLE
After `pm2 stop app` port is still in use on CentOS

### ISSUE THREAD

**Issue by calebmer** [Unitech/pm2#1588]
The restart feature of pm2 does not work because whenever the process is stopped the process does not actually stop. The port is still in use and when trying to access the app from its url, the stopped app shows up and is still running.

This is a crucial feature of pm2, is there a fix? Maybe a hook to call `killall node` on every stop command?

Environment:
- CentOS
- node: v0.12.7
- pm2: v0.14.7

**Comment by Unitech** [comment]
Looks like you're doing something atypical in your application, are you catching system calls?

**Comment by calebmer** [comment]
I don't believe so. I'm using Hapijs, how would you recommend doing this?
