### ISSUE TITLE
Is it normal for PM2 to run on port 6666 and 6667?

### ISSUE THREAD

**Issue by DPerkunas** [Unitech/PM2#1590]
When I look at my ports in use, it says PM2 is running on port 6666 and 6667, is this normal? My node.js app is running on port 8080, Apache on 80. I'm unsure if this is a vulnerability on my end (due to my setup). If i do a telnet site.com 6666 or 6667 it blocks the request though.

**Comment by soyuka** [comment]
You might be running an old version, to me pm2 runs with sockets by default (see [here](https://github.com/Unitech/PM2/blob/24f1bd77a1053448d02580e4d4ccdccf0ee28e46/lib/samples/sample-conf.js#L24)). This `configuration` file can be found in `~/.pm2/conf.js` or in your `$PM2_PATH` to modify values.

**Comment by DPerkunas** [comment]
I have updated to 0.14.7 yesterday using npm install and then update. I was running something like 0.7.2 before. Perhaps some of the old files remained? I guess I'll uninstall and reinstall. Advise if this isn't the best solution for me and should look into something else. Thank you.

**Comment by soyuka** [comment]
Would it be possible that you have more than 1 pm2 version running?

Try to `pm2 kill` and `pm2 start xx` to proper update the memory, or `pm2 updatePM2`

**Comment by Unitech** [comment]
Yes you have a very old PM2 version, when CLI and Daemon was communicating via TCP instead of current Sockets

```bash
$ pm2 save
$ npm install pm2@latest -g
$ pkill -f pm2
$ pm2 resurrect
```
