### ISSUE TITLE
Code duplication in ecosystem.json and processes.json?

### ISSUE THREAD

**Issue by Telemakhos** [Unitech/pm2#1591]
PM2 newbie here. 

I'm setting up a group of microservices with PM2 and after following [this tutorial](http://pm2.keymetrics.io/docs/usage/application-declaration/) for managing several processes ```(processes.json```) and [this other](http://pm2.keymetrics.io/docs/usage/deployment/) for deployment (```ecosystem.json```) I'm seeing a lot of duplication in both files. Seems like the "apps" section should be the same in both (specially the ENV vars). 

Is this necessary? I don't think it's a very DRY solution to keep and maintain both files when the content is almost the same (plus the deploying info), but maybe I'm wrong and they shouldn't have the same content. 

Ideally I'd like to use just one file. Is this possible?

**Comment by Unitech** [comment]
This the same file, just with different names. It has been updated to avoid confusion
