### ISSUE TITLE
Pid 0 issue

### ISSUE THREAD

**Issue by 3674823674252** [Unitech/PM2#1600]
I was playing with PM2 (here is the testing app i was using: https://github.com/3674823674252/pm2-example) and i got this problem after watching this program working for about a minute:

current pids: 4577,4459,4578,4417 master pid: 3452
app: err: Error: random kill at: 4459
current pids: 4577,4615,4578,4417 master pid: 3452
current pids: 4577,4615,4578,4417 master pid: 3452
app: err: Error: random kill at: 4417
current pids: 4577,4615,4578,4640 master pid: 3452
app: err: Error: random kill at: 4615
current pids: 4577,0,4578,4640 master pid: 3452
app: err: Error: random kill at: 4577
current pids: 4664,0,4578,4640 master pid: 3452
app: err: Error: random kill at: 4640
current pids: 4664,0,4578,4674 master pid: 3452
app: err: Error: random kill at: 4578
current pids: 4664,0,4578,4674 master pid: 3452
app: err: Error: random kill at: 4664
current pids: 4664,0,0,4674 master pid: 3452
app: err: Error: random kill at: 4674
current pids: 4709,0,0,4714 master pid: 3452
current pids: 4709,0,0,4714 master pid: 3452
current pids: 4709,0,0,4714 master pid: 3452
app: err: Error: random kill at: 4709
app: err: Error: random kill at: 4714
current pids: 4749,0,0,4750 master pid: 3452
current pids: 4749,0,0,4750 master pid: 3452
current pids: 4749,0,0,4750 master pid: 3452
app: err: Error: random kill at: 4750
current pids: 4749,0,0,4789 master pid: 3452
current pids: 4749,0,0,4789 master pid: 3452
current pids: 4749,0,0,4789 master pid: 3452
app: err: Error: random kill at: 4789
current pids: 4749,0,0,0 master pid: 3452
app: err: Error: random kill at: 4749
current pids: 4813,0,0,0 master pid: 3452
current pids: 4813,0,0,0 master pid: 3452
current pids: 4813,0,0,0 master pid: 3452
app: err: Error: random kill at: 4813
current pids: 0,0,0,0 master pid: 3452
current pids: 0,0,0,0 master pid: 3452
current pids: 0,0,0,0 master pid: 3452
current pids: 0,0,0,0 master pid: 3452
current pids: 0,0,0,0 master pid: 3452
current pids: 0,0,0,0 master pid: 3452
current pids: 0,0,0,0 master pid: 3452
current pids: 0,0,0,0 master pid: 3452
current pids: 0,0,0,0 master pid: 3452
current pids: 0,0,0,0 master pid: 3452
current pids: 0,0,0,0 master pid: 3452
current pids: 0,0,0,0 master pid: 3452
current pids: 0,0,0,0 master pid: 3452
current pids: 0,0,0,0 master pid: 3452
current pids: 0,0,0,0 master pid: 3452
current pids: 0,0,0,0 master pid: 3452
current pids: 0,0,0,0 master pid: 3452
current pids: 0,0,0,0 master pid: 3452
current pids: 0,0,0,0 master pid: 3452
current pids: 0,0,0,0 master pid: 3452
current pids: 0,0,0,0 master pid: 3452
current pids: 0,0,0,0 master pid: 3452
current pids: 0,0,0,0 master pid: 3452
current pids: 0,0,0,0 master pid: 3452
current pids: 0,0,0,0 master pid: 3452
current pids: 0,0,0,0 master pid: 3452

What this program does is it starts pm2 programmatically, pm2 in turn starts several workers (in cluster mode) each of those is running an http server. To get things more complicated (I was testing if PM2 was really restarting worker processes when one has failed) each of the workers can randomly crash. And the problem I saw in logs is that after several crashes PM2 stops reloading workers.

If this is not a bug please tell me what I am doing wrong.

**Comment by soyuka** [comment]
Yes, pm2 stops when there are too many unstable restarts. You can tweak this behaviour with your configuration, for example:

> min_uptime	number	1000	min uptime of the app to be considered started (i.e. if the app crashes in this time frame, the app will only be restarted the number set in max_restarts (default 15), after that it's errored)
max_restarts	number	10	number of consecutive unstable restarts (less than 1sec interval or custom time via min_uptime) before your app is considered errored and stop being

From http://pm2.keymetrics.io/docs/usage/application-declaration/

**Comment by 3674823674252** [comment]
I see, the situation is clear for me, thank you for the quick response, this issue may be closed.
