### ISSUE TITLE
Stopped apps start when I modify a file and watching = true

### ISSUE THREAD

**Issue by Telemakhos** [Unitech/PM2#1601]
If I stop any of the apps in my ```processes.json``` (they have watch: true) and I continue working in the code, when I save the file a change is detected and the app starts... Shouldn't PM2 know if a process is stopped so it doesn't have to "watch" and fire a restart?

**Comment by soyuka** [comment]
To do so you need to toggle watch while stopping:

```
pm2 start --watch someapp.js --name someapp
pm2 stop someapp
pm2 list #see it's still watching
pm2 stop --watch someapp
pm2 list #not watching anymore
```

You can find this behavior at the beginning of those docs : http://pm2.keymetrics.io/docs/usage/watch-and-restart/

**Comment by Telemakhos** [comment]
Oh! I missed that part of the docs... thanks!
