### ISSUE TITLE
axm monitor

### ISSUE THREAD

**Issue by zdychacek** [Unitech/PM2#1605]
Hi,

I want to ask if there exist any other axm monitor options working out of the box and are visible from `pm2-http-interface`.

Just now I see only 'Loop delay' information:

```
"axm_monitor": {
  "Loop delay": {
     "value": "0.58ms",
     "agg_type": "avg",
     "alert": {}
  }
}
```

My question is, if there are any other information like average http latency, average request count, etc. available.

I am using latest version of PM2, and running my app from CLI with JSON config file.

Thanks for your reply,

O.

**Comment by alavit-d** [comment]
Hi,

You can check [pmx](https://github.com/keymetrics/pmx) which allow you to create those probes. However they are mostly designed to work with the [Keymetrics](https://keymetrics.io/) solution.

**Comment by zdychacek** [comment]
Very useful answer. Thanks.
