### ISSUE TITLE
PM2 configuration under /etc/pm2 structured like Nginx

### ISSUE THREAD

**Issue by allantatter** [Unitech/PM2#1608]
http://stackoverflow.com/questions/32527809/pm2-how-to-store-configuration-files-under-etc-pm2-like-nginxs

Thanks,
Allan

**Comment by Unitech** [comment]
Answered via stackoverflow

http://pm2.keymetrics.io/docs/usage/specifics/#multiple-pm2-on-the-same-server

```bash
$ export PM2_HOME='/etc/pm2'
$ pm2 list
```
