### ISSUE TITLE
pm2 generated startup scripts doesn't do not match LSB

### ISSUE THREAD

**Issue by tantra35** [Unitech/pm2#1612]
for example serial launch of pm2-init.sh start will launch more and more workers, thats wrong. First launch must start dumped workers, the second start of pm2-init.sh start must return 0, and doesn't do anything. For example(expected behavior): 

pm2-init.sh start -> launch resurrected
pm2-init.sh start -> do nothing
pm2-init.sh start -> do nothing

and so on

pm2-init.sh status also work unproperly. It doesn't must launch anything it just must check the status, and if pm2 master process died it must return 3

**Comment by Unitech** [comment]
https://github.com/Unitech/pm2/issues/2559
