### ISSUE TITLE
Executable name "node" hardcoded several places.

### ISSUE THREAD

**Issue by lcrocker** [Unitech/pm2#1614]
Running PM2 0.14.7 on Ubuntu 14.04, NodeJS 0.10.25.

PM2 looks for the executable "node" in several places, including the shebang line on PM2 itself. Others cause "execvp(): No such file or directory" errors in the log when starting an app.

Since I'm not using the "node" package (some packet radio thing), this was easily solved by making a symlink from /usr/bin/nodejs to /usr/bin/node. Might want to make your installer a little more Ubuntu-aware and do something like this, or have it search.

**Comment by Unitech** [comment]
we should declare a new Node constant for PM2: https://github.com/Unitech/PM2/blob/master/constants.js#L74

And use it instead of "node"

**Comment by JMoli** [comment]
Ran into this issue. Common on DO droplets. Instead of reworking the constant, why not just handle the exception and create the symlink or even prompt.
