### ISSUE TITLE
BUG: Unexpected illegal  Token in pm2 lib utility.js

### ISSUE THREAD

**Issue by frank-dspeed** [Unitech/PM2#1618]
dscms-3 (err): SyntaxError: Unexpected token ILLEGAL
dscms-3 (err):     at exports.runInThisContext (vm.js:73:16)
dscms-3 (err):     at Module._compile (module.js:443:25)
dscms-3 (err):     at Object.Module._extensions..js (module.js:478:10)
dscms-3 (err):     at Module.load (module.js:355:32)
dscms-3 (err):     at Function.Module._load (module.js:310:12)
dscms-3 (err):     at Function.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
dscms-3 (err):     at /usr/lib/node_modules/pm2/lib/ProcessContainer.js:210:23
dscms-3 (err):     at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:52:16
dscms-3 (err):     at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:1166:30
dscms-3 (err):     at WriteStream.<anonymous> (/usr/lib/node_modules/pm2/lib/Utility.js:124:13)

dscms-4 (err):     at Function.Module._load (module.js:310:12)
dscms-4 (err):     at Function.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
dscms-4 (err):     at /usr/lib/node_modules/pm2/lib/ProcessContainer.js:210:23
dscms-4 (err):     at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:52:16
dscms-4 (err):     at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:1166:30
dscms-4 (err):     at WriteStream.<anonymous> (/usr/lib/node_modules/pm2/lib/Utility.js:124:13)
dscms-4 (err): /usr/bin/nodejs:1
dscms-4 (err): (function (exports, require, module, __filename, __dirname) { ELF

**Comment by Unitech** [comment]
The error is more precise now with the PM2 development version

```
$ npm install Unitech/pm2#development -g
$ pm2 update
```

**Comment by HarasimowiczKamil** [comment]
I have this same problem with run binary app. Developer version works the same way.

```
/project/games/csgo_ds/srcds_run:2
#
^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at /usr/lib/node_modules/pm2/lib/ProcessContainer.js:202:23
    at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:52:16
    at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:1166:30
    at WriteStream.<anonymous> (/usr/lib/node_modules/pm2/lib/Utility.js:124:13)
```

config.json 

```
...
        "exec_interpreter" : "none",
        "watch"            : true,
        "merge_logs"       : true,
        "mode"             : "cluster",
        "instances"        : 1,
        "autorestart"      : true,
...
```

**Comment by Unitech** [comment]
Can I have a look of your entire json file please?

**Comment by HarasimowiczKamil** [comment]
```json
{
    "apps" : [{
        "name"             : "game-server-server1",
        "script"           : "srcds_run",
        "args"             : [
            "-game csgo"
        ],
        "exec_interpreter" : "none",
        "watch"            : true,
        "merge_logs"       : true,
        "cwd"              : "/project/games/csgo_ds/",
        "log_date_format"  : "YYYY-MM-DD HH:mm:ss Z",
        "mode"             : "cluster",
        "instances"        : 1,
        "autorestart"      : true,
        "error_file"       : "/project/var/log/csgo-game-logs-server1.err.log",
        "out_file"         : "/project/var/log/csgo-game-logs-server1.out.log"
    }]
}
```

**Comment by frank-dspeed** [comment]
problem solved for me in latest dev version

**Comment by TemaSM** [comment]
Hey, some updates? I have the same issue as @HarasimowiczKamil and dev version of PM2 can't help me.
Here is my .json for PM2:
```Json
{
  "apps" : [
  {
    "name"        : "Server",
    "script"      : "srcds.exe",
    "args"        : [
      "-nocrashdialog",
      "-port 27015",
      "-game cstrike",
      "-insecure",
      "+map de_dust2",
      "-tickrate 100",
      "+fps_max 0",
      "+maxplayers 32",
      "+sv_lan 0",
      "+exec server.cfg"
    ],
    "cwd"              : "F:/Server/",
    "exec_interpreter" : "none",
    "exec_mode"        : "fork",
    "merge_logs"  : true
  }
 ]
}
```

**Comment by Nulsen** [comment]
I'm still having the same problem when i'm trying to run the elasticsearch server with pm2.
