### ISSUE TITLE
Future: drop out lib pmx (aka keymetrics support into own modul)

### ISSUE THREAD

**Issue by frank-dspeed** [Unitech/PM2#1619]
You Should strip of this keymetrics bindings they are error pawn!!!!!!!
and users that whant to use that will install that all others run own redis servers to optain data :dancers:

**Comment by Unitech** [comment]
PMX is very well tested + benchmarked and memory tested.

By the way if you want to not activate PMX:

```
$ pm2 start app.js --no-pmx
```
