### ISSUE TITLE
Ability to flush logs for a specific app

### ISSUE THREAD

**Issue by will123195** [Unitech/pm2#1621]
This clears all the logs:

```
pm2 flush
```

But it would be great to clear the log for only a specific app like this:

```
pm2 flush my-app
```

**Comment by Unitech** [comment]
Not a critical issue but feel free to contribute to add this feature:

pm2 call to CLI: https://github.com/Unitech/PM2/blob/master/bin/pm2#L600
CLI method: https://github.com/Unitech/PM2/blob/master/lib/CLI.js#L1499

Thanks!

(PR on development branch)

**Comment by Unitech** [comment]
Still waiting for a PR and to add you as a PM2 contributor :+1: :)

**Comment by will123195** [comment]
Thanks for pointing me in the right direction, I will certainly open a PR for this when I have time!

**Comment by Almya** [comment]
+1

**Comment by cope** [comment]
+1

**Comment by Unitech** [comment]
with the latest pm2 version (3.1.2) you can flush a specific app via `pm2 flush [app]`
