### ISSUE TITLE
BUG: Restarting does not seem to respect declaration file

### ISSUE THREAD

**Issue by creynders** [Unitech/pm2#1627]
Some context: I have a single user `dpac` which runs two separate instances of the same code. They're fully separated, i.e. I have a directory `tool` and a directory `demo`, each with the same code (they're not always fully synced, which is why I'm using two different directories)
I have these declaration files:

``` js
//file: process.staging.json
{
  "apps": [
    {
      "name": "staging",
      "script": "app/server.js",
      "env": {
        "NODE_ENV": "staging"
      }
    }
  ]
}
```

``` js
//file: process.demo.json
{
  "apps": [
    {
      "name": "demo",
      "script": "app/server.js",
      "env": {
        "NODE_ENV": "demo"
      }
    }
  ]
}
```

The default `NODE_ENV` is "staging".

Starting the applications works perfectly. And `pm2 restart staging` too.
But if I do `pm2 restart demo`, suddenly the application declaration file is disregarded (or at least part of it) since it uses "staging" as a `NODE_ENV` instead of "demo" as declared.

**Comment by creynders** [comment]
When doing `pm2 stop demo` and `pm2 start demo` the problem remains.
I have to `pm2 delete demo` and `pm2 start process.demo.json` before it works again.

**Comment by birdbyrd** [comment]
I have the same issue. pm2: 1.1.3, nvm: 2.7.4, node: 0.12.2

@creynders workaround: you can perform `pm2 restart process.demo.json` This works for me.

**Comment by birdbyrd** [comment]
Typo: I ment npm: 2.7.4

**Comment by jaimeagudo** [comment]
This bug is still unfixed at `v2.2.3`
