### ISSUE TITLE
log issue on centos 6.6

### ISSUE THREAD

**Issue by szucsi8** [Unitech/PM2#1630]
I have a question regarding the log locations:
"[root@www5 httpd]# pm2 start /var/www/frontend/bin/www -o /var/log/httpd/node -e /var/log/httpd/error_node
[PM2] restartProcessId process id 0
[PM2] Process successfully started
┌──────────┬────┬──────┬───────┬────────┬─────────┬────────┬────────────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ memory │ watching │
├──────────┼────┼──────┼───────┼────────┼─────────┼────────┼────────────┼──────────┤
│ www │ 0 │ fork │ 53242 │ online │ 0 │ 0s │ 4.492 MB │ disabled │
└──────────┴────┴──────┴───────┴────────┴─────────┴────────┴────────────┴──────────┘
Use `pm2 show <id|name>` to get more details about an app
[root@www5 httpd]# pm2 desc www
Describing process with id 0 - name www
┌───────────────────┬─────────────────────────────────┐
│ status │ online │
│ name │ www │
│ id │ 0 │
│ path │ /var/www/frontend/bin/www │
│ args │ │
│ exec cwd │ /var/www/frontend │
│ error log path │ /root/.pm2/logs/www-error-0.log │
│ out log path │ /root/.pm2/logs/www-out-0.log │
│ pid path │ /root/.pm2/pids/www-0.pid │
│ mode │ fork_mode │
│ node v8 arguments │ │
│ watch & reload │ ✘ │
│ interpreter │ node │
│ restarts │ 0 │
│ unstable restarts │ 0 │
│ uptime │ 15s │
│ created at │ 2015-09-21T11:57:33.503Z │
└───────────────────┴─────────────────────────────────┘
Probes value
┌────────────┬────────┐
│ Loop delay │ 1.01ms │
└────────────┴────────┘"
I am not able to set a log path for pm2 logs, it logs in the default root folder.
I use centos 6.6 and I tried other combinations like '--log/-l/--output/--error..' from 
 http://pm2.keymetrics.io/docs/usage/log-management/
pm2 CS suggested to post my issue here

**Comment by Unitech** [comment]
Hello,

After inspecting the PM2 output it says:

```
[PM2] restartProcessId process id 0
```

Please delete the process via pm2 delete 0

Then run your command again with the options to change log path,
