### ISSUE TITLE
PM2 shows different CPU % from Windows Task Manager

### ISSUE THREAD

**Issue by toddgeist** [Unitech/PM2#1631]
I am running a node app on Windows 2012 R2, Node 0.12.7, PM2 14.7, 4 cores 8GB RAM.

If I use pm2 monit or keymetrics.io I often see the CPU usage go to 100% after a few hours.  Yet the CPU usage on the Task manager shows 0% cpu usage. ( see the Image )  

Shouldn't these be reasonably close to one another? 
![image](https://cloud.githubusercontent.com/assets/316792/10010139/70f642dc-609b-11e5-9ac6-7f83f1196617.png)

**Comment by toddgeist** [comment]
possibly similar to #1622. But that one is on a mac. It does also claim that pm2 monit shows a different result then activity monitor.

**Comment by haozxuan** [comment]
oh， actually pm2 monit cpu is not true， memory is true. so Do not be too concerned about ：）

**Comment by soyuka** [comment]
#1081 duplicate

If you have thoughts on how to improve this I'm all ears :).
