### ISSUE TITLE
question: see apps of other users? ( like root )

### ISSUE THREAD

**Issue by buechling** [Unitech/PM2#1632]
Hallo, sorry for writing here.. you seem to have no forum..

i have a problem: i run severals node apps on the same linux computer, but as different users. how can i see all apps in one list ( pm2 list , pm2 logs etc.. )? i only see the apps of the specific user ... i could run all apps as root and start pm2 as root.. but this can't be the only way?

thank you!

**Comment by soyuka** [comment]
You can't. 

Similar issues, questions : #789 #367 #268
