### ISSUE TITLE
Inconsistent output when used programmatically

### ISSUE THREAD

**Issue by pycbouh** [Unitech/pm2#1633]
When using PM2 from code there's an inconsistency with how logs are printed out. When daemon is spawned, there is output, because `console.log` is used in `Satan`.

However, other actions, like starting app or killing the daemon, use `printOut`/`printError` methods from `Common`, which checks for `PM2_PROGRAMMATIC` being `'true'` and thus prevents any output.

It seems to me, that the appropriate fix would've been to hide `Satan`'s output as well. However, I would've prefered a settings to control how output is handled. If `PM2_PROGRAMMATIC` is such a setting and must be used, then it is not named properly, as the current name suggests any variety of changes dependent on it.

**Comment by Unitech** [comment]
fixed in dev, will be published in 0.15.7 (tomorrow)

**Comment by pycbouh** [comment]
Thanks! So, how should I go about actually allowing this output when used programmatically?
