### ISSUE TITLE
different project watches the same file

### ISSUE THREAD

**Issue by MaxLi1994** [Unitech/pm2#1635]
pm2 version 0.14.7
nodejs version iojs-v2.1
operating system OS X 10.10.5

I have two projects with the same config,  
and here is the project structure:
- project1
  - conf
  - dist
  - server.json
- project2
  - conf
  - dist
  - server.json

project1/server.json

```
{
    "name": "template",
    "script": "dist/framework/server/server.js",
    "watch": ["dist", "conf"],
    "env": {
        "NODE_ENV": ""
    }
}
```

project2/server.json

```
{
    "name": "xnl-hefan-admin",
    "script": "./dist/framework/server/server.js",
    "watch": ["dist", "conf"],
    "env": {
        "NODE_ENV": ""
    }
}
```

and I start project2 fisrt, then start project1

``` base
cd project2 && pm2 start server.json
cd ../project1 && pm2 start server.json
```

here is the pm2 list
![2015-09-23 15 12 14](https://cloud.githubusercontent.com/assets/5857749/10039497/34ae385a-6205-11e5-9545-d57f75134b06.png)

and here comes the strange thing!  
When I change files in project1, project1 could not detect the change, pm2 would not restart the app.   but when I change files in project2, both projects detected the change and restart.
![2015-09-23 15 15 03](https://cloud.githubusercontent.com/assets/5857749/10039540/9b268682-6205-11e5-830b-ba4fbe90f9c9.png)

then I delete both projects and only start project1. It still ignore my changes in project1, but react to changes in project2.

**Comment by MaxLee1994** [comment]
Kill the pm2 god daemon process and restart pm2 fix this. but still, is there someone who can explain this? am I doing something wrong?
