### ISSUE TITLE
Breaking change - Remove --next-gen-js option and babel

### ISSUE THREAD

**Issue by Unitech** [Unitech/pm2#1639]
BabelJS dependencies are too heavy and the --next-gen-js feature has not been adopted enough to justify the dependency.

**Comment by agonbina** [comment]
Yep, and for development you can achieve the same thing by using ```babel-node``` as the ```exec_interpreter```, and then setting ```watch:true```

**Comment by soyuka** [comment]
@agonbina using the `babel-node` exec interpreter will only work with the fork mode.

More informations about using babel with the cluster mode:  #1643
