### ISSUE TITLE
Facing SIGSEGV issue

### ISSUE THREAD

**Issue by selvakumark** [Unitech/pm2#1641]
I'm using pm2 version 0.14.7. I used pm2 start up script to start my application. 

pm2.connect(function() {
  pm2.start({
    "script" : "bin/startup.js",
    "name" : myAppName,
    "exec_mode" : "cluster",
    "instances" : 4,
    "max_memory_restart" : "500M"
  }, function(err, apps) {
    pm2.disconnect();
  });
});

cluster process is getting restarted often with "exited with code SIGSEGV".

I face outage because of this issue. How can i resolve this issue?

**Comment by Unitech** [comment]
Can you show me the content of bin/startup.js? What does this application do? 

```
"name" : myAppName, -> "name" : "myAppName"
```

**Comment by selvakumark** [comment]
I can't show startup.js due to restriction. In this application, We have lots of REST services. Mobile platform uses (iOS/Android) these  REST services. 

We have around 10k active users everyday.  We have multiple data sources. We created REST services using these data sources.
