### ISSUE TITLE
PM2 0.15.6 pm2 delete

### ISSUE THREAD

**Issue by md2k** [Unitech/pm2#1644]
Hi, just updated one of my servers to latest PM2 (0.15.6) and realise that `pm2 delete <JSON>| ecosystem.json` wont delete application from pm2 process list as it was in previous versions.
Not sure that this is bug, maybe it is feature :)  but...
if i do `pm2 delete <ID> | <App Name>` application removed from process overview properly

**Comment by Unitech** [comment]
fixed in dev, will be published in 0.15.7 (tomorrow)
