### ISSUE TITLE
pm2 weird output

### ISSUE THREAD

**Issue by kkprince1998** [Unitech/pm2#1647]
After running `pm2 status`, it prints a series of chars that are abnormal, and modifies my terminal by changing the color of the prompt to grey, and I have to `reset` it to fix it.

**Comment by Unitech** [comment]
terminal? operating system? node version?

Screenshot is welcome,
Thanks

**Comment by kkprince1998** [comment]
It apears to work fine now, ub14.04, repo version of node.

**Comment by renzosunico** [comment]
I have the same issue. It does it intermittently.

![pm2](https://user-images.githubusercontent.com/13325504/46202057-5cfdd200-c348-11e8-94fa-3ff7345d838e.png)
