### ISSUE TITLE
Typo in Satan.js (SIGILL instead of SIGKILL)

### ISSUE THREAD

**Issue by DavidDurman** [Unitech/pm2#1651]
The following line contains a typo: https://github.com/Unitech/pm2/blob/master/lib/Satan.js#L103. It should be `'SIGKILL'` instead of `SIGILL`.

**Comment by Unitech** [comment]
https://github.com/Unitech/PM2/blob/master/test/benchmarks/monit-daemon.sh#L8

SIGILL is a signal used in unix system
