### ISSUE TITLE
Cron expression with wrong format?

### ISSUE THREAD

**Issue by guilhermemmb** [Unitech/pm2#1655]
Hello guys,

Im trying to use cron expression to execute my tasks in pm2, but im facing a problem: pm2 don't execute in time as expected.

I have some 5 fields patterns crons(as documentation shows) to use:

"*/5 * * * *" -> every 5 minutes
"*/10 * * * *", -> every 10 minutes
"0 * * * *", -> every hour
"0 */12 * * *", -> every 12 hours
"0 0 * * *", -> every day
"0 0 */7 * *", -> every week

Any idea why pm2 wont follows that patterns?

Thanks.

**Comment by Unitech** [comment]
Here is the cron system: https://github.com/Unitech/pm2/blob/master/lib/ProcessContainer.js#L78

Cron module: https://www.npmjs.com/package/cron

**Comment by guilhermemmb** [comment]
Hey,

Thanks for reference. i found which module pm2 uses to evaluate crons after created my issue.

My program wont exit with right way. Because of it, pm2 can't execute it again.

I'll do a pr adding that cron module link in pm2 documentation.

Anyways, thanks for help.
