### ISSUE TITLE
Get the full revision hash from pm2 deploy current

### ISSUE THREAD

**Issue by florrain** [Unitech/pm2#1657]
Hello,

Is there a way to have `pm2 deploy ecosystem.json production current` return the full git hash instead of the short version?

Thanks.

**Comment by Unitech** [comment]
Hello,

Feel free to PR the bash script: https://github.com/Unitech/pm2-deploy/blob/master/deploy

I'm closing this issue because it's not related to the pm2 code but the pm2-deploy module,
