### ISSUE TITLE
Keymetrics advert in logs? How to disable.

### ISSUE THREAD

**Issue by bgSosh** [Unitech/pm2#1658]
Since upgrading pm2 I was dismayed to find some kind of advert for keymetrics.io strewn all over the logs.  This is ridiculous.  Imagine if all software did this.

How do I disable this please?

**Comment by Unitech** [comment]
Hello,

The Keymetrics banner just appears one time, when a file is missing: https://github.com/Unitech/pm2/blob/master/lib/CLI.js#L63

**Comment by bgSosh** [comment]
Ok that's not as bad then, but just for the sake of feedback, I don't like this practice at all.  I don't know about others, but it doesn't make me want to use the keymetrics service - in fact it makes me feel less inclined to trust a service that would abuse system functions for commercial purposes.

**Comment by Unitech** [comment]
I've always been very respectful to all PM2 users, I've never did any kind of hidden actions on their behalf, never (you can check on the code by yourself). This is only a simple text banner that supports our commercial product, the only way to make us continue to support PM2. 

Maybe I should put it on the installation procedure instead of popping up it like that

**Comment by bgSosh** [comment]
I believe you.  PM2 is a great piece of software, and you sound very sincere.  I also sympathise with the need to montise free stuff (I'm also wrestling with the same challenge).  I overreacted a bit with the initial post, sorry about that, but maybe others will flip out a bit too (or maybe I'm just too stressed at the moment!).  Anyway I respect the fact that you are treating it constructively.

I think it would help if it was clearer that it was a one time message.  Maybe you could add a 'This message will be displayed only once' type message at the end?

**Comment by Unitech** [comment]
No worries :) I expected someone to tell me something about this banner,

Yes I will add this information,

Have a good day!
Alex

**Comment by paullryan** [comment]
@Unitech it shows up every time I load my gulp file, which has an option to programmatically run pm2, on my CI system as the container is new each time. Makes reading the logs a little annoying. 

Anyway to tell the programmatic API to keep quite? 

Thanks for the great tool.

**Comment by bcldvd** [comment]
@Unitech same remark as @paullryan , is there a way to disable it ?

**Comment by davemackintosh** [comment]
Agreed, this is annoying in my logs. Any flag to disable?

**Comment by turbohz** [comment]
+1
