### ISSUE TITLE
Mismatch of Bars and Actual usage in Monit

### ISSUE THREAD

**Issue by nviror** [Unitech/pm2#1660]
![pm2](https://cloud.githubusercontent.com/assets/1423756/10224582/53fecf80-687c-11e5-8b5e-b66a6cff957e.png)

Red bar for lower memory consuming app "api2" should be smaller in length compared to "app".

**Comment by soyuka** [comment]
Maybe a related comment : https://github.com/Unitech/pm2/issues/1272#issuecomment-111200714

**Comment by nviror** [comment]
Issue gone, updated to latest version.
