### ISSUE TITLE
node V4.1.1 install pm2 failed

### ISSUE THREAD

**Issue by nichliu** [Unitech/pm2#1662]
Ubuntu 14.04 + node V4.1.1+ NPM V2.14.4

sudo npm install -g pm2

Install pm2 failed,  Message 
npm WARN optional dep failed, continuing fsevents@1.0.1

Then stay there forever.

**Comment by Unitech** [comment]
just tried it, it works, any update on this?

**Comment by nichliu** [comment]
Should my network problem, move to another machine works good. Thx
