### ISSUE TITLE
pm2 start in a symbolic linked directory should not follow symlink

### ISSUE THREAD

**Issue by derEremit** [Unitech/pm2#1663]
starting an app in a symblic linked directory 
pm2 info reports path as the resolved link

that breaks workflows where deployment changes the target of the symlink.
As pm2 restart uses the "old" target

**Comment by imsky** [comment]
:+1: have the same issue

**Comment by Unitech** [comment]
I tried different way of linking and relinking folders, I cannot reproduce this issue,
Could you give me a scenario to reproduce this,
Thank you

**Comment by derEremit** [comment]
on linux / ubuntu

suppose binary in daemondir
```
ln -s daemondir linkdeamon
cd linkdaemon
pm2 start app.js
```

pm2 info shows
path: daemondir/app.js

and not as expected
linkdaemon/app.js

**Comment by Unitech** [comment]
Thanks, why not starting your app like that:

```
$ pm2 start linkdeamon/app.js
```
So the folder does not get resolved

**Comment by derEremit** [comment]
Your're right, like this it works.

Why I do it the way I do it?

I think because usually with node you are inside a directory while developing
doing stuff with npm install, grunt gulp, etc, so it felt like the normal way to do, and I think more people will therefore experience this issue. 

with my deployment script I actually have done npm install an build tasks before and made an archive.
but after deploying ( extracting ) i still do something like
```
pushd $linkeddaemondir
npm rebuild
pm2 restart
popd
```

**Comment by imsky** [comment]
@Unitech `pm2 restart app-name` after switching symlinks where `app-name` is located is the problem case

**Comment by derEremit** [comment]
i can't descibe why, but for me I have to start my processes in the correct directory. So the workaround above doesn't work.

**Comment by khoerling** [comment]
+1 -- doesn't work when "npm start/stop/restart" are used to kick-off pm2 in the new working directory after a deploy

**Comment by tnolet** [comment]
Having the same issue, for example with a service like deploybot where releases are kept on disk and a `current` symlink changes the actual version.

**Comment by gansbrest** [comment]
Yep, we just hit same problem. We do deploys by switching symlinks to diff folders for fast rollbacks (capistrano style), but our symlink location is resolved on pm2 start and nothing ever gets updated. Please advice!

**Comment by tnolet** [comment]
For everyone reading this. I managed to solve it by actually adding some extra symlinks. Here's our `app.json` for PM2:

```json
{
  "apps": [
    {
      "name": "my-app",
      "script": "index.js",
      "args": [],
      "watch": true,
      "node_args": "",
      "merge_logs": true,
      "cwd": "/usr/local/share/my-app/current",
      "env": {
        "NODE_ENV": "development"
      }
    }
  ]
}
```

where the `/usr/local/share/my-app/current` is:

```
[ec2-user@ip-172-31-27-68 ~]$ ls -ltra /usr/local/share/flow-api/
total 20
drwxr-xr-x 9 root     root     4096 Dec 10 09:24 ..
drwxrwxr-x 2 ec2-user ec2-user 4096 Dec 10 09:58 shared
drwxrwxr-x 6 ec2-user ec2-user 4096 Jan  4 13:25 deploy-cache
lrwxrwxrwx 1 ec2-user ec2-user   45 Jan  4 13:26 current -> /usr/local/share/my-app/releases/1451913926
drwxr-xr-x 5 ec2-user ec2-user 4096 Jan  4 13:26 .
drwxrwxr-x 5 ec2-user ec2-user 4096 Jan  4 13:26 releases
```

**Comment by hguillermo** [comment]
@tnolet Something is wrong in your explanation? Are you sure you pasted the correct paths?

**Comment by tnolet** [comment]
@hguillermo: where it says 'flow-api' is should read 'flow-api'. This is due to my sad and failed attempt ot cover up our app name :smile:

**Comment by hguillermo** [comment]
It didn't work for us. At the end our issue is related to this: https://github.com/Unitech/pm2/issues/1623

Hopefully that gets fixed soon.

**Comment by xpiwo** [comment]
+1.
can't pm2 use process.env.PWD instead of process.cwd()?

**Comment by teu** [comment]
Having a similar problem with pm2 1.1.1.

When switching the version underneath pm2 and using startOrGracefulReload, pm2 processes are erroring (which renders the process quite usless) due to the lack of CWD. Anyone knows how this can be  combated?

**Comment by hguillermo** [comment]
@teu: @gansbrest suggested before that starting PM2 with upstart or similar will help. I am sure he can explain the logic behind it.

**Comment by gansbrest** [comment]
@teu Basically you need to make sure you run pm2 outside of your build dir. So if you have structure like this:

current --> build-1
build-1
build-2
build-3

You need to cd outside of the build directory and run pm2 from there. That way your directory will never be deleted. Hope that helps.

**Comment by teu** [comment]
Thanks @gansbrest already figured it out by trial and (a lot of) error. Good catch, should go in the pm2 docs.

**Comment by soyuka** [comment]
I wrote about symlinks [here](http://pm2.keymetrics.io/docs/tutorials/capistrano-like-deployments)

**Comment by teu** [comment]
@soyuka True, missed it, great resource, thanks!

**Comment by zhangkaiyulw** [comment]
@gansbrest it works Thanks!

**Comment by misterikkit** [comment]
Hello, something about the way I am doing this is simply not working. Each time I reboot my server, the CWD and absolute path to the script are replaced with the target of the symlink I was using at some point in the past.

I read through the [instructions][1] and I can't tell what I am doing incorrectly. Can someone point me in the right direction? Thanks!

```
$ ls -l
total 132
lrwxrwxrwx 1 misterikkit misterikkit     15 Dec 23 20:07 catfood -> catfood-72d1d3c
drwxr-xr-x 4 misterikkit misterikkit   4096 Dec 23 07:04 catfood-0853a10
drwxr-xr-x 4 misterikkit misterikkit   4096 Dec 23 08:06 catfood-30b614e
drwxr-xr-x 4 misterikkit misterikkit   4096 Dec 23 19:50 catfood-461515d
drwxr-xr-x 4 misterikkit misterikkit   4096 Dec 23 19:47 catfood-5199879-dirty
drwxr-xr-x 4 misterikkit misterikkit   4096 Dec 23 20:07 catfood-72d1d3c
drwxr-xr-x 4 misterikkit misterikkit   4096 Dec 23 08:53 catfood-7d48e66
-rw-r--r-- 1 misterikkit misterikkit 100110 Dec 23 20:21 catfood.log

$ pm2 start catfood/run.sh --name catfood-backend --log $HOME/catfood.log

$ pm2 info catfood-backend
 Describing process with id 0 - name catfood-backend 
┌───────────────────┬───────────────────────────────────────────────────────┐
│ status            │ online                                                │
│ name              │ catfood-backend                                       │
│ namespace         │ default                                               │
│ version           │ 1.0.0                                                 │
│ restarts          │ 0                                                     │
│ uptime            │ 9s                                                    │
│ entire log path   │ /home/misterikkit/catfood.log                         │
│ script path       │ /home/misterikkit/catfood/run.sh                      │
│ script args       │ N/A                                                   │
│ error log path    │ /home/misterikkit/.pm2/logs/catfood-backend-error.log │
│ out log path      │ /home/misterikkit/.pm2/logs/catfood-backend-out.log   │
│ pid path          │ /home/misterikkit/.pm2/pids/catfood-backend-0.pid     │
│ interpreter       │ bash                                                  │
│ interpreter args  │ N/A                                                   │
│ script id         │ 0                                                     │
│ exec cwd          │ /home/misterikkit                                     │
│ exec mode         │ fork_mode                                             │
│ node.js version   │ N/A                                                   │
│ node env          │ N/A                                                   │
│ watch & reload    │ ✘                                                     │
│ unstable restarts │ 0                                                     │
│ created at        │ 2020-12-23T20:23:11.634Z                              │
└───────────────────┴───────────────────────────────────────────────────────┘

# After reboot it becomes...

$ pm2 info catfood-backend
 Describing process with id 0 - name catfood-backend 
┌───────────────────┬───────────────────────────────────────────────────────┐
│ status            │ online                                                │
│ name              │ catfood-backend                                       │
│ namespace         │ default                                               │
│ version           │ 1.0.0                                                 │
│ restarts          │ 0                                                     │
│ uptime            │ 12s                                                   │
│ script path       │ /home/misterikkit/catfood-0853a10/index.js            │
│ script args       │ N/A                                                   │
│ error log path    │ /home/misterikkit/.pm2/logs/catfood-backend-error.log │
│ out log path      │ /home/misterikkit/.pm2/logs/catfood-backend-out.log   │
│ pid path          │ /home/misterikkit/.pm2/pids/catfood-backend-0.pid     │
│ interpreter       │ node                                                  │
│ interpreter args  │ N/A                                                   │
│ script id         │ 0                                                     │
│ exec cwd          │ /home/misterikkit/catfood-0853a10                     │
│ exec mode         │ fork_mode                                             │
│ node.js version   │ 15.5.0                                                │
│ node env          │ N/A                                                   │
│ watch & reload    │ ✔                                                     │
│ unstable restarts │ 0                                                     │
│ created at        │ 2020-12-23T07:33:20.840Z                              │
└───────────────────┴───────────────────────────────────────────────────────┘
```

[1]: https://pm2.keymetrics.io/docs/tutorials/capistrano-like-deployments
