### ISSUE TITLE
Feature Request?

### ISSUE THREAD

**Issue by md2k** [Unitech/pm2#1665]
Checked all issues/docs and so on. PM2 awesome product and it is nice that it have keymetrics.io Dashboard, but what about StatsD support or directly to graphite, InfluxDB metrics exposition?
It is possible to have in nearest future support of external metrics, except Keymetrics dashboard?

Thank you in advance.

**Comment by Unitech** [comment]
we will provide soon commercial connectors to support graphite and so on
