### ISSUE TITLE
pm2.start does not pass args

### ISSUE THREAD

**Issue by arasmussen** [Unitech/pm2#1669]
```javascript
// start.js
pm2.start({
  script: 'script.js',
  rawArgs: ['--', 'foo'],
  name      : 'bar',
}, function() {
});

// script.js
var argv = require('yargs').argv;
console.log(process.argv); // no foo
console.log(argv); // no foo
```

**Comment by Unitech** [comment]
The json passed into .start method is the same than the classic json application declaration: http://pm2.keymetrics.io/docs/usage/application-declaration/#application-declaration-file

```javascript
// start.js
pm2.start({
  script: 'script.js',
  args: ['foo'],
  name      : 'bar',
}, function() {
});

// script.js
var argv = require('yargs').argv;
console.log(process.argv); // no foo
console.log(argv); // no foo
```

**Comment by arasmussen** [comment]
@Unitech When I use `args: ['foo']` then the following lines log the following:

>> console.log(process.argv);
[ '/usr/local/bin/iojs',
  '/path/to/my/project/node_modules/pm2/lib/ProcessContainer.js' ]
>> console.log(yargs.argv);
{ _: [], '$0': '../node_modules/pm2/lib/ProcessContainer.js' }

**Comment by arasmussen** [comment]
Running pm2 kill and then re-running my script worked. A bit odd that I had to do this though. I feel like if I kill the programmatic pm2 script then starting it should re-create the processes from scratch, no?

**Comment by vision1v1** [comment]
I have encountered the same problem, how to solve it?

**Comment by vision1v1** [comment]
I found a solution,
Use "start(script: string, options: StartOptions, errback: ErrProcCallback)" to be careful
The examples that can be run are as follows

`var config = {
    name            : 'app',
    script          : './server.js',
    args            : ['54321']
};

pm2.start(config,function(err, apps){
    pm2.disconnect(); // Disconnects from PM2
    if (err) {
        console.log(err);
    }
})

console.log(process.argv);

var port = process.argv.splice(2);
console.log("------------------>" + port);
port = parseInt(port);
`
