### ISSUE TITLE
pm2 does not obey num instances

### ISSUE THREAD

**Issue by arasmussen** [Unitech/pm2#1670]
```javascript
pm2.start({
  script: 'script.js',
  name: 'foo',
  exec_mode: 'cluster', // fork here does the same
  instances: 1,
}, function() {...});

// script.js
console.log('foo');
```

"foo" prints 3 times even though I specified a single instance.

**Comment by Unitech** [comment]
Just tried it locally everything works fine, kill all you apps and try again. How do you start the programmatic call to pm2?

**Comment by arasmussen** [comment]
@Unitech simply doing `node pm2script.js`..

Basically doing this: https://gist.github.com/Unitech/4c8ea564aa8bf0a389c5

**Comment by arasmussen** [comment]
Running pm2 kill and then re-running my script worked. A bit odd that I had to do this though. I feel like if I kill the programmatic pm2 script then starting it should re-create the processes from scratch, no?

**Comment by Unitech** [comment]
Nope, when you start your pm2 script programmatically, it will spawn a pm2 instance if it's not present and then start your script. If you exit the script, the application will continue to run
