### ISSUE TITLE
max_restarts does not detect restarts properly

### ISSUE THREAD

**Issue by vladikoff** [Unitech/pm2#1676]
In my json config I have a shell script that I run:

```
    {
      "name": "server PORT 5000",
      "script": "../_scripts/server.sh",
      "cwd": "server",
      "max_restarts": "1"
    }
```

Even though I have "max_restarts" set, I still get over 90000 restarts on the server:

![image](https://cloud.githubusercontent.com/assets/128755/10311973/166b1c0c-6c17-11e5-9b30-a089710c73c9.png)

Any ideas what I'm doing wrong? did I not set the options correctly?

**Comment by if-meaton** [comment]
You could try setting the min_uptime option?

See here: http://pm2.keymetrics.io/docs/usage/application-declaration/#options

Description:

min uptime of the app to be considered started (i.e. if the app crashes in this time frame, the app will only be restarted the number set in max_restarts (default 15), after that it's errored)

**Comment by vladikoff** [comment]
Thanks! I guess the default is 1000 ms for a crashed process, but servers take longer to start so it does not stop restarting. Thanks for showing me that option!
