### ISSUE TITLE
PM2:Watch - Using GlusterFS - Only restarting on one server

### ISSUE THREAD

**Issue by if-meaton** [Unitech/pm2#1677]
Here is my setup:

I have two servers (Web-01 and Web-02) which are load balanced. I have watch enabled and I am using GlusterFS to mirror the files between the two servers. So /var/www/l008/ is the GlusterFS Volume Mount point and is the same on both servers

If I touch a file on Web-01 then the process is restarted on Web-01 but not Web-02 and vice-versa on Web-02. My question is, is this a GlusterFS issue not raising the event on both servers or is this PM2 not seeing a change if it didn't originate on that server?

I have been using DEBUG="pm2:watch" and no events are raised on the 'other' server but are on the server that the touch was done from.

Let me know if you need anything else.

Thanks!

**Comment by soyuka** [comment]
Internally pm2 uses https://github.com/paulmillr/chokidar. I think that they'll have a better clue about this than I. May you open an issue there? I know that there are issues with NFS but I'm not familiar with GlusterFS.

**Comment by if-meaton** [comment]
Yeah, I realised after posting. I'm just setting up a test case. sorry for bothering you :)

**Comment by if-meaton** [comment]
Hey, just an fyi, issue replicated using just chokidar in isolation. :)

https://github.com/paulmillr/chokidar/issues/364

**Comment by soyuka** [comment]
https://github.com/Unitech/pm2/issues/931#issuecomment-72047654 
Glad `usePolling` fixed it.

**Comment by if-meaton** [comment]
Just in case anyone comes across this issue, GlusterFS is considered a Network File System I guess so usePolling:true fixes the issue.
