### ISSUE TITLE
Module activated, why?

### ISSUE THREAD

**Issue by anthonycluse** [Unitech/pm2#1682]
Hello,

When I do `pm2 list` I see a new tab "Module activated" but I don't understand because I didn't launch any modules...

![sans titre](https://cloud.githubusercontent.com/assets/1122304/10394252/3594fe00-6e96-11e5-8209-163915749f0a.png)

Regards,

**Comment by Unitech** [comment]
Hello, what is your npm version?

**Comment by anthonycluse** [comment]
1.3.10

**Comment by Unitech** [comment]
weird, please delete the module folder

```
$ rm ~/.pm2/node_modules
```

**Comment by anthonycluse** [comment]
That's all need?

**Comment by Unitech** [comment]
then 

```
$ pm2 update
```

**Comment by anthonycluse** [comment]
Thank you it works !
