### ISSUE TITLE
App restarts randomly when using pm2 after update, works fine without it

### ISSUE THREAD

**Issue by bastienvans** [Unitech/pm2#1684]
Hello,

We've been using pm2 for a few months without have many issues. We updated to the newest version of pm2 a week ago and it seems to have broken quite a few of our apps. Some apps started restarting themselves about twice a minute. If the app is ran using command line node app.js it will not restart/crash. There are no errors. The app just restarts itself. We've tried uninstalling pm2 and reinstalling, flushing logs, but it hasn't fixed anything.

Thanks

**Comment by Unitech** [comment]
hello, any new clues on this? did you downgraded pm2 and worked as normal?

**Comment by santillaner** [comment]
Found similar issue. Discovered at pm2.log that it was a max memory restart but I had not configured it. It is a pitty that max memory is not included in pm2 monit or pm2 list or pm2 show. Is there a way to know this setting's value?
