### ISSUE TITLE
[question] How to handle external services (mongodb, mysql, etc) using multi-process

### ISSUE THREAD

**Issue by lucaswxp** [Unitech/pm2#1685]
Hey guys

I'm writing a data-processing script and I would like to make use o pm2 capability of starting my program able to use multi-cores, like so:

```bash
pm2 start app.js -i0
```

I just don't know how should I design my app.js, since my problem consists of querying the database for some data, processing it, setting a flag and to repeat the process. How do I make my processes not to run into a race condition? Here is my problem:

```javascript
doJob();
function doJob(){
  Product
    .find({status: 'waiting'})
    .limit(100)
    .exec(function(err, movies){
      if(err) console.log(err)
      else {
        movies.forEach(function(p){ processProduct(p); })
        doJob(); // repeat the process
      }
    });
}

function processProduct(p){
  p.status = 'processed';
  p.save();
}
```
I know the code is not correct, I omitted intentionally the async part for better readability. The problem is, if I start multiple processes for this script, they will always find the same "waiting" products, because they all start at the same time and have no coordination.

How would I go about solving this? I haven't found a elegant solution yet.

**Comment by Unitech** [comment]
multiple processes are going to access to the same data at the same time, this is about software design it's not about pm2 (you should ask on stackoverflow). the cluster mode is useful for socketed application,

**Comment by lucaswxp** [comment]
Ok, that's what I thought.

I was just wondering if pm2 would have capability for one process to communicate with another (like sending messages), but I didn't find anything in the docs.

That way I could have a "master" process serving the data and the others being fed with it.

**Comment by soyuka** [comment]
@lucaswxp you can fork a `cluster` to handle master and childs yourself ;).

**Comment by lucaswxp** [comment]
@soyuka If I understood correctly, I would have one "master" like so:

```sh
pm2 start master.js
```
And this master, using node cluster module, would fork my workers? Is there any way to control these children with pm2? So them show up in `pm2 list`, for instance.

Thanks for the answer :)
