### ISSUE TITLE
startup.json - restart using updated json variables

### ISSUE THREAD

**Issue by pacmac** [Unitech/pm2#1686]
First of all, a big thanks for developing this, it is really great and such a leap forward from forever !

I have a pm2.startup.json file that contains a list of apps and their env settings etc, this works great.

But the problem is I may modify this file and would want to restart one of the apps with the new settings, but currently have to kill pm2 and restart every service in order for any changes that were made to the file to be applied.

So 2 questions:

1) If I add a new app to the pm2.startup.json file, how can I start just this app without restarting all of the apps and / or killing and restarting PM2 ?

2) if I change a config setting for one of the apps, it does not appear to get updated when I restart the app ?

An alternative to having a single pm2.startup.json file, would be to have 1 file for each app, and somehow get pm2 to read all of the json files in a folder or a wildcard to get it's startup info  

ie. pm2 start /usr/share/nodejs/*.pm2.json

**Comment by mnewmedia** [comment]
I'm also new with pm2 i found out, that the configs, gets updated when you do `pm2 remove all` and then add them again.

**Comment by Unitech** [comment]
Hello, the JSON configuration reload feature is available on the development, feel free to try and give me any feedback:

```bash
$ npm install Unitech/pm2#development -g
```

**Comment by Unitech** [comment]
feature landed in PM2 > 0.15.8
