### ISSUE TITLE
How to read pm2 logs with other programs

### ISSUE THREAD

**Issue by larzuk91** [Unitech/pm2#1687]
I've been using PM2 for a while and recently I wanted to check my old logs file. The problem is when I open those logs with other programs like "pico, nano, etc" I get lines like this:

**2015-10-09 16:57 -05:00: ^[[0mGET /zone ^[[36m304 ^[[0m2.342 ms - -^[[0m**

As you see it, it's very dificult to read and I would like to open them like pm2 does.

The problem is pm2 just stream logs in real time and I just can't find a way to achieve it.

thanks in advance.

**Comment by ruandao** [comment]
the `^[[0m` and others was used to color the output on terminal

you can simple delete it use `sed -e 's/xxxx//g logfile`

**Comment by larzuk91** [comment]
Nice, it worked as a charm. Thank you very much
