### ISSUE TITLE
Disable stdout and stderr logs if --log is provided

### ISSUE THREAD

**Issue by CGavrila** [Unitech/pm2#1689]
Doing something like:
```
pm2 start whatever.js --log /path/to/.pm2/logs/application-name.log
```
still creates different files called `application-name-out-X.log` and `application-name-error-X.log`, even though the merged version is supposed to be in the `.log` file provided.

1. Is there any way to disable the creation of those files except for maybe `-o /dev/null -e /dev/null`?
2. Why is the log file named `application-name-X.log` if I specifically asked for it to be named `application-name.log`? Is there any way to stop this?

**Comment by soyuka** [comment]
`--merge-logs`?

**Comment by CGavrila** [comment]
Oops, saw the option, but it was not clear that this is what it does. Will close this one for the moment and reopen if appropriate. 

Thanks, @soyuka!
