### ISSUE TITLE
All dependencies of pm2 module activated as individual modules

### ISSUE THREAD

**Issue by erikverheij** [Unitech/pm2#1692]
When I install a pm2 module all dependencies are loaded as modules.  

After running ```pm2 install pm2-logrotate```  the folder ```/home/username/.pm2/node_modules``` is filled with pm2-logrotate and its dependencies. Somehow the dependencies are not nested. All dependencies are just installed in the root folder. The folder ```/home/username/.pm2/node_modules/pm2-logrotate``` has no folder ```node_modules```.

All these dependencies are loaded as pm2 modules on the next startup. 

* I'm using version 0.15.7.  
* The problem also arises for other pm2 modules (tested with pm2-webshell).
* I'm on a AWS Linux AMI (based on CentOS/RHEL)
* node v0.12.7
* npm v3.3.6

![image](https://cloud.githubusercontent.com/assets/3001961/10489369/1a152924-729d-11e5-8adc-af4da1476857.png)

![image](https://cloud.githubusercontent.com/assets/3001961/10489379/2628c6b2-729d-11e5-9c24-76818e9d4f4f.png)

**Comment by Unitech** [comment]
How did you installed node.js?
Right now please delete the folder ~/.pm2/node_modules

**Comment by Unitech** [comment]
#1674 duplicate

**Comment by erikverheij** [comment]
I installed node with;

```
# Install with yum (outdated version)
yum install nodejs npm --enablerepo=epel
# Install node version manager
npm install -g n
# Install desired version
n v0.12
# Remove the outdated version
yum remove nodejs
# Remove packages of the outdated version 
rm /usr/lib/node_modules
# Check version
node -v
```

Some more debug info..; these warnings show up after ```pm2 install pm2-logrotate```

![image](https://cloud.githubusercontent.com/assets/3001961/10490089/7dd4aeba-729f-11e5-87a7-f3bb5ab64fca.png)

**Comment by Unitech** [comment]
PM2 0.15.8 including this fix is published
