### ISSUE TITLE
pm2 daemon crash - segfault

### ISSUE THREAD

**Issue by nuBHblx** [Unitech/pm2#1699]
Greetings,
Few times a day pm2 suddenly crash with errors like :

Oct 17 17:06:22 Tychus kernel: [18577217.260761] PM2 v0.15.7: Go[32076]: segfault at 0 ip 0000000000d950b0 sp 00007fff1d835030 error 4 in nodejs[400000+dc9000]
Oct 17 11:56:09 Tychus kernel: [18558590.533129] PM2 v0.15.7: Go[24801]: segfault at 0 ip 0000000000d950b0 sp 00007fffd00d1360 error 4 in nodejs[400000+dc9000]

Reproduced on 2 different machine with 

Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty

with same app launched in cluster mode with node.js v4.1.1. 
what can cause this problem?
thanks.

**Comment by nuBHblx** [comment]
checked with PM2 v0.15.5 - the same behavior

**Comment by ricardohbin** [comment]
Do you upgraded to node 4 after installing the npm modules?

**Comment by Unitech** [comment]
seems to be a very rare case, mostly linked to Node.js

**Comment by soyuka** [comment]
When I usually have this issue, it's after a node upgrade and all you have to do to fix it is `npm rebuild`.
