### ISSUE TITLE
pm2 does not produce any output at all

### ISSUE THREAD

**Issue by mpeshev** [Unitech/pm2#1700]
I've installed pm2 as described in the readme:

    npm install pm2 -g

The manager seems to be installed:

    root@dxtools:/var/www/gsearch# which pm2
    /usr/local/bin/pm2

However, there is no output at all whenever I try to start an application, call `pm2 list`, `--version` or anything else. There are no processes running. 

It's installed as a global package by root (and running with root) on a Digital Ocean droplet with Ubuntu 14.04.

**Comment by manon-henrioux-cko** [comment]
Same problem for me

**Comment by macecchi** [comment]
+1 here. I've tried reinstalling a few times, with or without root, but there is no output.

**Comment by HAZARDU5** [comment]
+1 for me too. Shows up with `which pm2` as `/usr/local/bin/pm2` on Ubuntu 14.04 Bitnami Nginx 64-bit AMI on AWS but when running it there is no output or process running.

**Comment by macecchi** [comment]
It started working after I upgraded Node.js to 5.0.0. I believe I was running 0.12.x before.

**Comment by HAZARDU5** [comment]
Some of the guys at the office suggested using `n` to install Node `4.2.1`. We also had to remove the `node` (Amateur Packet Radio Node) Ubuntu package as it looked like some weirdness was happening with `pm2` trying to use `node` instead of `nodejs` when running `pm2`.

`n` installed the new version of node in the correct place and everything looked good.

Here's what we ran to get it working:

```
sudo apt-get update
sudo apt-get remove node
sudo apt-get install nodejs npm build-essential
sudo npm install n -g
sudo n 4.2.1
```

**Comment by Unitech** [comment]
@mpeshev did you solve this issue?

**Comment by mpeshev** [comment]
Yes - installing through `n` (which I stumble upon for the first time) fix it for me - thanks everyone

**Comment by sandyfox** [comment]
I had this issue when the disk space is 100% full. Cleared the unwanted logs and ran pm2 and everything back to normal.

**Comment by Bringer-of-Light** [comment]
"sudo apt remove node" solve this problem.

nodejs should be used instead of node.
looks like pm2 can only work with "nodejs", not "node"
