### ISSUE TITLE
run app as root (-u root) failure

### ISSUE THREAD

**Issue by ruandao** [Unitech/pm2#1709]
thank you  
I run a email server use `Haraka (a nodejs framework)` which require `root` permission

when i run it directly, it was success: `sudo haraka -c xxxx`

but when i run it through pm2 it was failure

    pm2 start $(which haraka) -u root --no-daemon -- -c xxxxx

**Comment by Unitech** [comment]
The -u option is for startup scripts, to run haraka with root permission, you need to start PM2 with the root user, so the process will inherit these permissions
