### ISSUE TITLE
when running 2 apps of the same name you get Error: listen EADDRINUSE

### ISSUE THREAD

**Issue by BrandonCopley** [Unitech/pm2#1710]
When I run 2 apps of the same name:

ex:

```
{apps:[{name:"myApp",},{name:"myApp"}]}
```

I get this error on pm2 deploy 

```
Error: listen EADDRINUSE
```

It appears the stop message isn't going to myApp-1

**Comment by BrandonCopley** [comment]
I don't have enough details, but 2 apps same name, different ports specified. it appears it uses the name to identify the app, even if there are multiple apps of the same name. so it tries to start the first app twice, rather than the 2nd app if they share the same name.

**Comment by soyuka** [comment]
Indeed, I don't think that you can have 2 apps with the same name.
