### ISSUE TITLE
HTTP status code 400 with v4.2.1

### ISSUE THREAD

**Issue by yarekc** [Unitech/pm2#1712]
Hello,
"Warning: If you want to use the embedded load balancer (cluster mode), we recommend the use of node#0.12.0+ or node#0.11.16+. We do not support node#0.10.*'s cluster module anymore"

What about versions 4.2.1 ?

I try:  pm2 start server.js -i0

and got many errors: 
XMLHttpRequest cannot load /socket.io/?EIO=3&transport=polling&t=1445592575230-24&sid=eoHF5xtTw8w3rw-DAAAG. Response for preflight has invalid HTTP status code 400

whereas
 node server.js

 works good

Does PM2 works with the latest version of node ? because it looks lt does not !

**Comment by soyuka** [comment]
#389
Le ven. 23 oct. 2015 à 11:33, chmielewski <notifications@github.com> a
écrit :
