### ISSUE TITLE
EADDRINUSE error on restart

### ISSUE THREAD

**Issue by calebmer** [Unitech/pm2#1715]
Whenever I run pm2 restart, it seems to not kill my node app as it keeps spitting out `EADDRINUSE` errors. Here is my setup:

In `processes.json`:
```js
[
  {
    "name": "node",
    "cwd": ".",
    "script": "scripts/start-node.sh",
    "exec_interpreter": "bash",
    "exec_mode": (process.env.ENV === 'development' ? 'fork' : 'cluster'),
    "watch": (process.env.ENV === 'development'),
    "ignore_watch": ["node_modules"]
  }
]
```

In `scripts/start-node.sh`:
```sh
#!/bin/bash

node_modules/.bin/babel-node --stage 0 index.js
```

And in `index.js`:
```js
if (!module.parent) {
  Http.createServer(…).listen(PORT, () => console.log(`Server listening on ${PORT}`))
}
```

**Comment by calebmer** [comment]
Ok, did some digging, it appears like pm2 is not properly tree killing my process. (1) How do I get `pm2_env.treekill` to be true [here](https://github.com/Unitech/pm2/blob/master/lib/God/Methods.js#L239)? (2) Am I looking in the right place?

**Comment by calebmer** [comment]
I can‘t use pm2 in production if the process will always fail to restart. Any updates on this?

**Comment by soyuka** [comment]
Hi,

`treekill` default is `true`. 
If you want to use babel, please refer to http://pm2.keymetrics.io/docs/usage/specifics/#babeljs. I had issues while using `babel-node` and `child_process.fork` together ([small blog article on the subject](http://soyuka.me/an-unpleasant-babeljs-experiment/)). 

Setting `exec_interpreter` to `bash` will **not** work with the **cluster**. Cluster **has** to work with `node`, and there are no workarounds. This may be why your process is failing.

**Comment by calebmer** [comment]
Yep, changing the `exec_interpreter` was the trick.
