### ISSUE TITLE
ES6 Support Not Working

### ISSUE THREAD

**Issue by sabrehagen** [Unitech/pm2#1716]
When using `pm2 start server.es` where `server.es` contains ES6 code, any ES6 functions will not be recognized. This is on pm2 version 0.15.7. Also, as per https://keymetrics.io/2015/06/02/embrace-next-generation-javascript-today/ using `--next-gen-js` produces `error: unknown option '--next-gen-js'`.

**Comment by kkc** [comment]
+1, want to know how to integrate ES6 code with latest pm2 version.

**Comment by soyuka** [comment]
We recently removed babeljs from pm2, please see this related issue: https://github.com/Unitech/pm2/issues/1602. I'm also explaining there some ways to still use babeljs or simply use node 4.x that embeds most of the interesting ES6 features.

**Comment by sabrehagen** [comment]
So if you have removed babeljs from pm2, does this mean your explanation where you modify `~/.pm2/conf.js` doesn't work anymore? Is `BABEL_EXEC_PATH` still referenced in the latest pm2? For those of us who depend on this functionality for production apps, what can be done to restore the functionality? I don't see a "`NODE_EXEC_PATH`" option. Can we supply an alternative node path that actually points to `babel-node`?

**Comment by soyuka** [comment]
You can either change the `exec_interpreter` in your `ecosystem.json` ([doc](http://pm2.keymetrics.io/docs/usage/pm2-doc-single-page/#json-configuration)) or use the [require hook](https://github.com/Unitech/pm2/issues/1643#issuecomment-144087967).

https://github.com/Unitech/pm2/issues/1643#issuecomment-144087967

**Comment by sabrehagen** [comment]
thanks
