### ISSUE TITLE
chalk doesn't work in pm2 logs

### ISSUE THREAD

**Issue by FoghostCn** [Unitech/pm2#1719]
I use chalk to styling my console, but with pm2 it doesn't work
my code is like this:
```
  console.log(chalk.green('this is a chalk color string'));
```
run it with node or pm2 command,in pm2 chalk doesn't take any effection

![](https://cloud.githubusercontent.com/assets/5020327/10752649/188a4ef8-7cc6-11e5-846d-9bc29ac4fd59.png)
![](https://cloud.githubusercontent.com/assets/5020327/10752624/e8b7d092-7cc5-11e5-89cb-a02c2b6b50fa.png)

**Comment by Tjatse** [comment]
Just try:
```json
{
  "apps": [
    {
      "[SOME]":"[CONFIGS]",
      "args": [
        "--color"
      ]
    }
  ]
}
```

or

```bash
$ pm2 start myapp.js -- --color
```

**Comment by FoghostCn** [comment]
@Tjatse Thank you

**Comment by chickenwing** [comment]
Where is this "--color" option coming from? Is this a nodejs thing? Its not a pm2 option, is it?

**Comment by soyuka** [comment]
Nope it's a chalk thing: see [supports-color](https://github.com/chalk/supports-color/blob/master/index.js#L18), a dependency of [Chalk](https://github.com/chalk/chalk/blob/master/index.js#L10), where the dependency [has-flag](https://www.npmjs.com/package/has-flag) checks whether `process.argv` has `--no-color`.

**Comment by volodalexey** [comment]
This didn't work for me:
```
$ pm2 start myapp.js -- --color
```
This [supportsColor](https://www.npmjs.com/package/chalk#chalksupportscolor) worked:
```
$ FORCE_COLOR=1 pm2 start myapp.js
```

**Comment by chase-moskal** [comment]
i'm trying every possible combination i can imagine, and nothing works.

```sh
$ FORCE_COLOR=3 pm2 start "node --env-file=.env.prod x/signaller/server.js" --name app -- --color
```

so upsetting, i put so much effort into making beautiful colorful logs, and to have it all permanently stripped away beyond my control is a bummer :disappointed:

**Comment by DereC4** [comment]
> Just try:
> 
> {
>   "apps": [
>     {
>       "[SOME]":"[CONFIGS]",
>       "args": [
>         "--color"
>       ]
>     }
>   ]
> }
> or
> 
> $ pm2 start myapp.js -- --color

thank you
