### ISSUE TITLE
Question on PM2's loading of files with Cluster approach

### ISSUE THREAD

**Issue by jsmartfo** [Unitech/pm2#1722]
I have a question not sure if this is the correct place to ask or not but I am facing the following issue, I have a requirement to update webpage copy and such on the page from property files, below is an approach we have followed but we are facing an issue with PM2. (the requirement of hot reload cannot be changed).

1. Start PM2 in cluster mode
2. Adjust property files on the OS
3. Clear out application cache
4. Reloading files from the OS 
5. Updating the cache with what should be new property files

The issue we face is the files always appear the same as when the application started, does PM2 hold its own internal cache of all application files when the app started?

I know I can use watch and restart but that doesn't from what I can tell support graceful reload, its just a tear down. 

Any light anyone can shed would be great.

**Comment by soyuka** [comment]
pm2 does not uses an internal cache. Could you try to reproduce this is a gist?

**Comment by jsmartfo** [comment]
Thanks for the reply, let me double check the logic on our end just to make sure we haven't missed anything. If it persists I will setup a gist.

**Comment by danday74** [comment]
I experienced very severe file caching issues with pm2 on cluster mode. I was "restarting" processes with pm2 delete ecosystem.config.js and then pm2 start ecosystem.config.js - this caused major file caching issues. pm2 was serving long gone changes quite randomly. It had me running in circles for ages. Have switched my "restart" to pm2 restart in hope of a better experience.
