### ISSUE TITLE
pm2 memory display

### ISSUE THREAD

**Issue by haozxuan** [Unitech/pm2#1724]
hi:
    I am very pleased to be able to talk to you， now i found command “pm2 m “list memory is rss not used memory,  i want show process used memory because rss not accurate. like this 

![image](https://cloud.githubusercontent.com/assets/8748015/10819969/03f62db0-7e86-11e5-8fcd-25b59d1834da.png)

so, where can i find code in pm2 module?

pm2 ： 0.16.7
node： 4.2.1
mac OS
head -n 50 ~/.pm2/pm2.log output null

**Comment by soyuka** [comment]
pm2 rss is computed in the [pidusage module](https://github.com/soyuka/pidusage) : https://github.com/soyuka/pidusage/blob/master/lib/stats.js#L84. Then it's displayed in `monit` [here](https://github.com/Unitech/pm2/blob/0eb9e8e7791b3377a79c9f09f8cfb4501ccba095/lib/God/ActionMethods.js#L64).

**Comment by haozxuan** [comment]
oh, thank you.  i have a question, why not use node module(process.memoryUsage())?

**Comment by soyuka** [comment]
Because we want your process memory, not pm2's. If we wanted to execute `process.memoryUsage` it should be done in your app, not the master that forks it. Here, we just have a `pid` and we guess the memory usage per process.

**Comment by haozxuan** [comment]
e...but 'pm2 m' list memory is rss. After node releasing the memory, this memory is not accurate.  so ,can i some way to get real time memory beside in my process add ```process.memoryUsage```
