### ISSUE TITLE
startup apps only start when user logs in (OS X)

### ISSUE THREAD

**Issue by overlookmotel** [Unitech/pm2#1725]
I am trying to set a group of apps to be started up automatically on server start.

I started the apps in `pm2` from a `json` file (which all works fine) and then did...

``` sh
$ sudo pm2 startup -u overlook
$ pm2 save
```

On reboot, the apps are restarted as expected BUT only when the user logs in through the GUI. This is on OS X Yosemite and generally I want to have the screen locked so someone wandering past the machine can't interfere with it, but at present the only solution is to set the machine to auto-login the user to kick `pm2` into action. I don't know whether an SSH remote login has a similar effect - haven't been able to test that yet.

Is this a bug, or am I doing something wrong with the `-u` switch?

Any help would be much appreciated...

System details:
OS X Yosemite 10.10.5
Node 0.12.7
pm2 0.15.7

**Comment by soyuka** [comment]
I'm not really familiar with darwin LaunchAgents and there might be an option to do what you want. I'm not sure though, and it might be an Apple restriction to launch scripts on login. 

The script template: https://github.com/Unitech/pm2/blob/master/lib/scripts/io.keymetrics.PM2.plist
You can find the `.plist` in `Library/LaunchAgents/io.keymetrics.PM2.plist`, try do edit it according to the Apple docs on the subject.

**Comment by jaredadobe** [comment]
It is because it is set up as a launchagent (only starts up when a user logins). I have my service running as a launchdeamon its a pretty similar process, same file just different location remove the one that is in your $HOME/Library/LaunchAgents/io.keymetrics.PM2.plist and put it into /Library/LaunchDaemons/o.keymetrics.PM2.plist @soyuka who would i be asking for permission to make this a permanent change (it makes it behave more like other systems)

**Comment by soyuka** [comment]
+1 about the change @jaredadobe

**Comment by overlookmotel** [comment]
@soyuka Are you saying that launching PM2 on system launch (as opposed to user login) is the desired behaviour? (I assume so, but just wanted to check).

If, so would you accept a PR to make this change?

**Comment by overlookmotel** [comment]
@jaredadobe Thanks loads for proposing this solution. I haven't tried it yet, but will do when I get a chance.

**Comment by jaredadobe** [comment]
@overlookmotel it sounded like he was a-ok with it doing it on startup rather than launch. I can open a PR for this.

**Comment by Unitech** [comment]
launchd init script fixed: https://github.com/Unitech/pm2/issues/2559
