### ISSUE TITLE
0.15.8 breaks watch & restart / chokidar integration / customization.

### ISSUE THREAD

**Issue by lukesneeringer** [Unitech/pm2#1729]
The update to pm2 0.15.8 broke something in the way watching and chokidar works if you are using a JSON configuration file.

Given a configuration file such as:

```json
{
  "apps": [
    {
      "autorestart": true,
      "cwd": "/var/company_name/app_name/",
      "error_file": "/var/log/app_name/pm2.error.log",
      "exec_interpreter": "node",
      "ignore_watch": [
        ".git",
        ".vagrant",
        "node_modules"
      ],
      "name": "bodoni-server",
      "node_args": [
        "--debug=5858"
      ],
      "out_file": "/var/log/app_name/pm2.out.log",
      "script": "app.js",
      "watch": true,
      "watch_options": {
        "followSymlinks": false,
        "usePolling": true
      }
    }
  ]
}
```

The `watch_options` are no longer passed to chokidar at all, and the `ignore_watch` is passed incorrectly.

By starting PM2 with `DEBUG="*"` I was able to get the watch logs:

```
  pm2:watch Initial watch  +5ms true
  pm2:watch Watching /var/company_name/app_name +0ms
  pm2:watch Watch opts +0ms { ignored: '[".git",".vagrant","node_modules"]',
  persistent: true,
  ignoreInitial: true,
  cwd: '/var/company_name/app_name' }
```

Note that:

  * The `ignored` key is _a string that looks like an array_, rather than an actual array. This causes the `ignored` value to essentially no-op as nothing will ever match that, so your ignores do not work.
  * The `usePolling` and `followSymlinks` options are missing; they _should_ be in "Watch opts" since I set them in the configuration file.

Using my l33t hacking skills (also known as: being on a virtual machine and being willing to edit PM2 code on the fly to add log messages), I determined that not only is `pm2_env.ignore_watch` a string (in the context of [`lib/Watcher.js`](https://github.com/Unitech/pm2/blob/master/lib/Watcher.js) on line 35), but `pm2_env.watch_options` is also. This means that `util._extend` no-ops on line 42 and therefore `watch_options` are effectively ignored.

I also confirmed that in PM2 0.5.7, `pm2_env.ignore_watch` is properly an `Array` and `pm2_env.watch_options` is properly an `Object`. Something changed in 0.5.8 to stringify them.

Here's hoping this can be fixed. Watch & restart effectively does not work in pm2 0.5.8, sadly.

I was not able to figure out where the env is made to submit a patch, so I took the lazy way out, gave you a bug report, and downgraded to 0.5.7.

Thanks for a great piece of software!

**Comment by soyuka** [comment]
Thanks for the details!

I see [this commit](https://github.com/Unitech/pm2/issues/1668) that could interfere

Could you try this fix: https://github.com/soyuka/pm2/tree/watch-restart-0.15.8 ?

**Comment by lukesneeringer** [comment]
Dumb question: How do I npm install from that source?

**Comment by lukesneeringer** [comment]
Still broken:

```  pm2:watch Watch opts +0ms { ignored: '[".git",".vagrant","node_modules"]',
  persistent: true,
  ignoreInitial: true,
  cwd: '/var/may/bodoni' }```

(I stopped caring about redacting my actual project directory.)

**Comment by soyuka** [comment]
Found that https://github.com/Unitech/pm2/commit/32262267d5b6b74690ce52746883a12d99291a15#diff-4ce9aea92d36e9c98f1eae56904b4a3eR14 is the issue.

Working on it ;).

**Comment by soyuka** [comment]
Should be better:
```
Fri, 30 Oct 2015 23:54:45 GMT pm2:watch Watch opts { ignored: [ '*.log' ],
  persistent: true,
  ignoreInitial: true,
  cwd: '/Users/soyuka/forks/PM2/test/fixtures/watcher',
  followSymlinks: true }
```

**Comment by Unitech** [comment]
@lukesneeringer thanks for such a clear bug report!

The fix is now available on master, feel free to have a try:

```
$ npm install Unitech/pm2#master -g
$ pm2 update
```

**Comment by michahell** [comment]
I think this is in 0.15.7 is well, since i'm experiencing the same issue (related comments by me in https://github.com/Unitech/pm2/issues/1307 and https://github.com/Unitech/pm2/issues/498).

**Comment by soyuka** [comment]
@michahell please update to 0.15.9.

**Comment by michahell** [comment]
@soyuka yes will do, just wanted to let you guys know :)
