### ISSUE TITLE
Listen socket

### ISSUE THREAD

**Issue by yamifr07** [Unitech/pm2#1733]
In my nodejs config I don't use a port, instead I have:
      "listen": "server.sock",
I don't know exactly the problem but when I run pm2 reload app.js the server does not work anymore and if I remove the file server.sock and run the command again, it works again.
Any idea?

**Comment by animedbz16** [comment]
This is likely due to the socket file permissions and that yoyr webserver
doenst have access to write to it. We had a similar issue which we needed
to chgrp/chmod the socket file so nginx had group write access.

**Comment by yamifr07** [comment]
Perfect! I ran chmod and now I can reload the app without any problem. This file is created automatically. Do you know how could I force it for being created with write permission?

**Comment by soyuka** [comment]
Not related to pm2.
