### ISSUE TITLE
can a module define custom cli functions?

### ISSUE THREAD

**Issue by thewilli** [Unitech/pm2#1734]
I want to trigger actions on a module externally, and would therefore like to define custom cli actions (e.g. something like `pm2 my_action arg1 arg2`). 

Is there currently any way to extend pm2 by custom actions?

**Comment by soyuka** [comment]
There is none actually. You could try using pm2 programmatically:  http://pm2.keymetrics.io/docs/usage/pm2-doc-single-page/#programmatic

**Comment by thewilli** [comment]
thanks, I'll try to go this way. But you should really consider allowing modules to extend the cli functionality.

**Comment by soyuka** [comment]
What is your use case?

**Comment by thewilli** [comment]
I'm currently evaluating ways for deployments and maintenance of distributed, Docker-based web backends.
My idea was to include a module which could handle setup, configuration and scaling of linked services like database containers. In addition it could allow deployment scenarios other than the currently offered one (which is only SSH-based, as far as I understand). Such a container would be managed from inside using a configuration management system like [chef](https://www.chef.io). 

Without the possibility to trigger custom actions using the pm2 executable, my management module would have to listen on e.g. a unix socket, so the management service is able to trigger an action like a deployment of a certain git tag, which leads to increased complexity.
