### ISSUE TITLE
documentation for vizion missing?

### ISSUE THREAD

**Issue by thewilli** [Unitech/pm2#1735]
the [documentation](http://pm2.keymetrics.io/docs/usage/pm2-doc-single-page/) says that there is an option `--no-vizion` to disable vizion, which has something to do with version control metadata, but I haven't found any description of how vizion works, how it integrates with pm2 and how the retrieved metadata can be used in a pm2 workflow.

Is there any information I maybe just haven't found?

**Comment by soyuka** [comment]
https://github.com/keymetrics/vizion

When doing `pm2 desc` you might get repository data if your project is a git directory. Then it is also used to change your repository current state, for example `pm2 pull myapp` or `pm2 forward myapp`. 

Some users didn't had `git` and `vizion` was then an issue. This flag disables everything related to the git repository.

[CLI.js](https://github.com/Unitech/pm2/blob/9eea08f7e06dc8d8514d074518a40ee55b0720d2/lib/CLI.js#L2090-L2147) / [bin](https://github.com/Unitech/pm2/blob/9eea08f7e06dc8d8514d074518a40ee55b0720d2/bin/pm2#L688-L717)
