### ISSUE TITLE
not install in nodejs 5.0.0 ???

### ISSUE THREAD

**Issue by c941010623** [Unitech/pm2#1737]
my os is aws ec2 ubuntu 14.x

and use node.js 5.0.0

npm install pm2 -g   is not work .....

error info 

npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (/opt/nodejs/node-v5.0.0-linux-x64/lib/node_modules/npm/node_modules/which/which.js:73:28)
npm WARN addRemoteGit     at E (/opt/nodejs/node-v5.0.0-linux-x64/lib/node_modules/npm/node_modules/which/which.js:76:29)
npm WARN addRemoteGit     at /opt/nodejs/node-v5.0.0-linux-x64/lib/node_modules/npm/node_modules/which/which.js:84:16
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN addRemoteGit  git+http://ikt.pm2.io/ikt.git#master resetting remote /root/.npm/_git-remotes/git-http-ikt-pm2-io-ikt-git-master-098735ff3c4481296d11bc2fc98a470a because of error: { [Error: not found: git] code: 'ENOGIT' }
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror http://ikt.pm2.io/ikt.git /root/.npm/_git-remotes/git-http-ikt-pm2-io-ikt-git-master-098735ff3c4481296d11bc2fc98a470a: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror http://ikt.pm2.io/ikt.git /root/.npm/_git-remotes/git-http-ikt-pm2-io-ikt-git-master-098735ff3c4481296d11bc2fc98a470a: undefined
npm WARN install Couldn't install optional dependency: not found: git
npm WARN install Couldn't install optional dependency: Unsupported
/opt/nodejs/node-v5.0.0-linux-x64/bin/pm2 -> /opt/nodejs/node-v5.0.0-linux-x64/lib/node_modules/pm2/bin/pm2
/opt/nodejs/node-v5.0.0-linux-x64/bin/pm2-dev -> /opt/nodejs/node-v5.0.0-linux-x64/lib/node_modules/pm2/bin/pm2-dev
/opt/nodejs/node-v5.0.0-linux-x64/lib
└── pm2@0.15.8

**Comment by soyuka** [comment]
It worked. try `pm2 -v`.

Seems there is not `git` on your server, anyway `ikt` is an [optional dep](https://github.com/Unitech/pm2/blob/master/package.json#L185).

**Comment by c941010623** [comment]
any npm install (ex.. mysql and other ) is ok but my aws ec2 use npm install pm2 -g  is error .....
why ?
