### ISSUE TITLE
Apps Errored on Startup if I run as root /  pm2 wont startup at all  while using a normal user. and breaks after logout

### ISSUE THREAD

**Issue by HERRKIN** [Unitech/pm2#1740]
I found no way to make pm2 start on startup with my sudo user so I uninstalled and istalled again using only root, it seemed to work, I rebooted the machine and when I typed pm2 list as root it listed the processes as errored, if I type pm2 restart all they start normally but I am surprised there is no error log I could see. Please help me debug this one. 

I am using ubuntu 14.04 
iojs-v2.5
pm2 0.15.9

**Comment by soyuka** [comment]
Could you give the output of `tail -n 100 ~/.pm2/pm2.log`? 
Is there data in your `~/.pm2/dump.pm2`?

**Comment by HERRKIN** [comment]
I would like to review instead the other aproach, so that the user can start it up, no need for root. I reinstalled pm2 again deleting .pm2 folders both on root and home/user before installing again. 

When I log into the system I type pm2 list, pm2 starts in this moment, so it didnt start on boot. no list is loaded I have to manually type pm2 resurrect. but the most weird thing is that if I exit the session pm2 kill itself. 

what did I do? 
pm2 start theapp.js --name app
pm2 save
sudo env PATH=$PATH:/usr/local/bin pm2 startup -u $USER  

this is my pm2.log
http://termbin.com/5enz

I have 4 apps running.

**Comment by HERRKIN** [comment]
also I think its worth it to put the out put of grep -r pm2 /var/log/

/var/log/auth.log:Nov  4 10:04:02 saecosms sudo: saecosoft : TTY=pts/0 ; PWD=/home/saecosoft/code/casinterface ; USER=root ; COMMAND=/usr/bin/env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/bin pm2 startup -u saecosoft
/var/log/auth.log:Nov  4 10:44:50 saecosms sudo: saecosoft : TTY=pts/0 ; PWD=/home/saecosoft ; USER=root ; COMMAND=/bin/grep pm2 /var/log/
/var/log/auth.log:Nov  4 10:44:55 saecosms sudo: saecosoft : TTY=pts/0 ; PWD=/home/saecosoft ; USER=root ; COMMAND=/bin/grep -r pm2 /var/log/
/var/log/auth.log:Nov  4 10:46:16 saecosms sudo: saecosoft : TTY=pts/1 ; PWD=/home/saecosoft ; USER=root ; COMMAND=/bin/grep -r pm2 /var/log
/var/log/boot.log:Starting pm2
/var/log/boot.log:Error: connect EACCES /home/saecosoft/.pm2/rpc.sock

**Comment by HERRKIN** [comment]
it seems its trying to use the root user anyway, no matter that the pm2-init says user=saecosoft

**Comment by HERRKIN** [comment]
@soyuka @Unitech why havent I received any answer of this? I am really stuck on this and it should be something taken for granted. I cant make the machine start the processes on boot up. PLEASE HELP!

**Comment by soyuka** [comment]
Did you use `pm2 startup` to set up the init script?
Did you check the file `/etc/init.d/pm2-init.sh` to see that it fits your needs?
Are your processes in the `~/.pm2/dump.pm2` file? I assume yes because `pm2 resurrect` works.

I didn't see the notification mail about this, apologizes.

**Comment by HERRKIN** [comment]
I even sent you a direct email via gmail about this. the pm2-init.sh has these config: 
```
NAME=pm2
PM2=/usr/lib/node_modules/pm2/bin/pm2
USER=saecosoft

export PATH=/usr/bin:$PATH
export PM2_HOME="/home/saecosoft/.pm2"

```

also note this
```
/var/log/boot.log:Starting pm2
/var/log/boot.log:Error: connect EACCES /home/saecosoft/.pm2/rpc.sock
grep: /var/log/btmp: Permiso denegado

```

**Comment by soyuka** [comment]
I don't answer to mails regarding pm2 in my personal mail box.

Does the user `saecosoft` has execute rights on `/usr/lib/node_modules/pm2/bin/pm2`? You should rather use `nvm` to set one `node` executable per user. And then install pm2 globally from that user `npm install pm2 -g`. This way there'll be no such issues as `EACCES`, which is definitly related to user/binary permissions.

**Comment by HERRKIN** [comment]
how do I set a node executable for a user on nvm?

**Comment by HERRKIN** [comment]
I uninstalled node completely and pm2. installed nvm, iojs-v2, when I try npm i -g pm2 it wont let me it says I have to run the command as sudo

**Comment by HERRKIN** [comment]
pm2 is driving me crazy. if I install pm2 using iojs via nvm it works while on the same session, if I restart I lose pm2, like if it wasnt installed, I try to install it again and it throws an error looking for /usr/local/bin/pm2. I guessed well lets just copy pm2 binary to that folder and see what happens. pm2 runs after reinstall but it behaves identically like before, it says EACCESS. I dont really know what to do. PLEASE HELP!

**Comment by HERRKIN** [comment]
there was no way to make it, I have tried several tutorials with your ideas, nothing has worked for me. @soyuka @Unitech please help, I am stuck with it and this is extremely important for my project.

**Comment by soyuka** [comment]
Just install everything as a non root user, for example using [nvm](https://github.com/creationix/nvm):

```
nvm install 4.1
nvm alias default 4.1
npm install pm2 -g
pm2 start app.js
```

**Comment by HERRKIN** [comment]
but the thing is that pm2 requires root permissions, if I dont install it with sudo it will break. I have been talking to ubuntu comunity via irc, they say it is caused by home folder being encrypted. as soon as I leave the session this folder gets unmounted so anything under my name gets killed

**Comment by soyuka** [comment]
Yes because nodejs, npm and pm2 are installed as root. Either install everything as the user, or run your app with root (everything installed as root).

**Comment by HERRKIN** [comment]
yes it semms I also have to move the code out of the home folder  too. because it is encrypted. 
that should work

**Comment by sami-sweng** [comment]
I had the same issue with the same version of Ubuntu and pm2 1.0.1

I echoed the `$PATH` that the auto-generated /etc/init.d/pm2-init.sh script uses. I don't know if it's because of the runlevel at which the script runs or if it's because that variable is not the same for root (you generate the path outside of the `su` command) but that revealed to be the problem for me.

The path was `/usr/bin:/sbin:/usr/sbin:/bin:/usr/bin` which does not match my usual path `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`. 

So the solution for me was to hardcode my usual path at the beginning of the script but I suppose there must be more elegant solutions.

**Comment by Unitech** [comment]
upstart init files fixed https://github.com/Unitech/pm2/issues/2559
