### ISSUE TITLE
Reloading WITH a new environment

### ISSUE THREAD

**Issue by ZerbitX** [Unitech/pm2#1743]
Apologies if this is in the documentation and I missed it...

Is there a way with pmx to, fristly force a reload FROM the app, and secondly to do so with a new set of environment variables? Basically, something like...

    var _ = require('lodash');
    pmx.reload('appName', _.extend(process.env, someOverrideStuff));

to effectively be akin to 

    var _ = require('lodash');
    
    // When a worker is killed, restart with a new environment    
    cluster.on('exit', function(worker) {
        if (worker.suicide === true) {
            cluster.fork(process.env); 
        }
    });
    
    // ... sometime later
    _.extend(process.env, someOverrideStuff);
    cluster.worker.kill();
    
In general something like the example...
    
    pmx.action('debug:on', function(reply) {
        DEBUG='*';
        reply({DEBUG:DEBUG});
    });
    
...would work fine, but I'm interested in changing the middleware stack of an app, and to avoid mucking with koa or express internals, that requires the app to be restarted and the app to call "use" on the middleware pieces in order.

**Comment by Unitech** [comment]
landing in next release (1.0.3)

**Comment by Unitech** [comment]
Update available (PM2@1.1.1 - latest stable):

```
$ npm install pm2@latest -g
$ pm2 update
```

Please re-open this issue if you notice any problem,
