### ISSUE TITLE
Help me create a restart script

### ISSUE THREAD

**Issue by Pinkkk** [Unitech/pm2#1744]
Hi, so recently I just got pm2 and I was wanting to restart my scripts 2 hours or so.

Here is what I have --

var pm2 = require('pm2');

pm2.connect(function(err) {
if (err) return console.error(err.stack || err);
setInterval(function() {
pm2.restart('all');
}, 120 * 60 * 1000);
});

---

I added this but it came back as error, any suggestions?

**Comment by Pinkkk** [comment]
Anyone?

**Comment by soyuka** [comment]
Can't you use the `cron_restart` option? 

http://pm2.keymetrics.io/docs/usage/application-declaration/#options

**Comment by Unitech** [comment]
You need to pass a callback to restart for pm2 to recognize programmatic calls

```
var pm2 = require('pm2');

pm2.connect(function(err) {
  if (err) return console.error(err.stack || err);
  setInterval(function() {
    pm2.restart('all', function() {
      console.log('Application restarted');
    });
  }, 1000);
});
```
