### ISSUE TITLE
cluster mode opens new shell for each fork

### ISSUE THREAD

**Issue by dwelle** [Unitech/pm2#1749]
```
pm2 start server.js -i 4
```

starts 4 new node shell windows, which then of course reopen every time you save a file (if you watch for changes).

Doesn't matter if started via CLI or config.

Only solution is to use `--no-daemon` switch, but then you have to open another shell for monitoring.

pm2 version `0.15.9`, Node `4.2.1`, Windows 7.

**Comment by pauloavelar** [comment]
Any update on this issue? I'm using fork mode for now, but in Prod I will need many instances in parallel. Still happening in pm2 v1.0.0, Node v5.5.0.

**Comment by muratsu** [comment]
+1

**Comment by keymsg** [comment]
+1

**Comment by Kitanotori** [comment]
Still no fix?

**Comment by mmojica53** [comment]
I have the same issue! any updates?

**Comment by vlapo** [comment]
+1

**Comment by Unitech** [comment]
With @vmarchaud we are having a hard time to find a solution to this issue. Node.js on Windows seems to behave like that when you create a new detached process.

If someone have a clue about that, please let us know.

**Comment by vmarchaud** [comment]
close this one in favor of #2182
