### ISSUE TITLE
pm2 install not working on windows

### ISSUE THREAD

**Issue by angelosc** [Unitech/pm2#1750]
on windows run:
c:\> pm2 install pm2-logrotate

throws the following error:
[PM2][Module] Installing module pm2-logrotate
[PM2][Module] Processing...
The system cannot find the path specified.
[PM2][Module][ERROR] Unknown module

Tested on windows 7x64 and windows 2012R2x64

**Comment by JamesBewley** [comment]
Same issue on windows 2012 R2

**Comment by javahas** [comment]
I have the same issue, did you find a solution?

**Comment by angelosc** [comment]
no, this is still not fixed

**Comment by Mohinesh27** [comment]
I am also facing same issue. Please help me to out of it

**Comment by jianbingfang** [comment]
+1
