### ISSUE TITLE
pm2 startup - multiple users

### ISSUE THREAD

**Issue by PavelPolyakov** [Unitech/pm2#1753]
Hi,

On one server I have one `pm2` installation, which is run by several users.
I want to execute `pm2 startup`, how ever, as I see it generates the the `/etc/init.d/pm2-init.sh` file, with the next content:

```
NAME=pm2
PM2=/usr/lib/node_modules/pm2/bin/pm2
USER=username
```

So, as I assume, on startup `pm2` would start the applications only for the `username`.

Is there an option to configure startup for all the users?

Regards,

**Comment by soyuka** [comment]
Implement 1 startup script per user if there is one pm2 per user it'll work just fine ;).

**Comment by PavelPolyakov** [comment]
@soyuka 
you mean by copying?

yes, good idea, I just thought that it is somehow done by pm2.

I think, then, it worth updating the ```pm2 startup``` scheme, so the file created would not be named ```pm2-init.sh```, but ```pm2-init-username.sh``` , should be easy and useful change.

Regards,

**Comment by soyuka** [comment]
Thing is that pm2 is built to run per user. This means that you'll have one pm2 daemon per user, user-daemons don't speak together. So, the daemon is not aware that they could be more daemons on the same server. 

Either by copying or by looping on an array of users and starting each pm2 instance.

**Comment by PavelPolyakov** [comment]
Yes, I completely understand.

I just said, that if ```pm2 startup``` would generate username-based "daemon" file, then it would be easier to integrate startups for each username-pm2 combination.

**Comment by soyuka** [comment]
Ofc but the standard use is to only use one pm2 instance. We could change startup scripts to implement a user-basis script. @Unitech  thoughts?

**Comment by Unitech** [comment]
This is an interesting idea, it may require some change in CLI.startup command (CLI.js)

**Comment by Unitech** [comment]
Closing in favor of #2559 

To try the new startup system:

```bash
$ npm install Unitech/pm2#development -g
$ pm2 update
```

```bash
$ pm2 startup     # Then copy / paste the command displayed
$ pm2 unstartup
```

**Comment by PavelPolyakov** [comment]
Thanks
