### ISSUE TITLE
Pm2 + socket.io

### ISSUE THREAD

**Issue by andreabianco** [Unitech/pm2#1754]
Hi,  I'm trying to start my node.js application in cluster mode. 

The application is generated with the angular full stack generator and I use socket. 
If I use pm2 with default mode,  it's fine and powerful but I want to use the load balancing functionality. But when I start the application a lot of errors appears in console,  also in the browser. This functionality is supported? I have to insert something in my code in order to enable it? 
Thanks!

**Comment by soyuka** [comment]
#389
