### ISSUE TITLE
PM2 restart loop - possible to show what caused "change" to trigger?

### ISSUE THREAD

**Issue by ruandao** [Unitech/pm2#1755]
the same problem as [#1547](https://github.com/Unitech/PM2/issues/1547)

if I disable `--watch` option it work well, but I don't know which file change, and change for what

May be it will be more nice to add some option to tell about which file change

**Comment by soyuka** [comment]
Hi, I just added a line that logs the path that triggers the restart : https://github.com/Unitech/pm2/commit/c0ced46be82805c725c9626c093d3d2d854aba67

Logs are written in `~/.pm2/pm2.log`.
