### ISSUE TITLE
optional dep failed, continuing ikt@git+http://ikt.pm2.io/ikt.git#master

### ISSUE THREAD

**Issue by rasekar2000** [Unitech/pm2#1758]
In the standard ubuntu 0.14.
myuser@c7511b58315b:~$ npm install pm2
npm WARN package.json ubuntu-node@0.0.1 No repository field.
npm WARN package.json ubuntu-node@0.0.1 No README data
npm WARN package.json ubuntu-node@0.0.1 No license field.
npm ERR! git clone --template=/home/sourab/.npm/_git-remotes/_templates --mirror http://ikt.pm2.io/ikt.git /home/sourab/.npm/_git-remotes/http-ikt-pm2-io-ikt-git-4d23bf0d: undefined
npm ERR! git clone --template=/home/sourab/.npm/_git-remotes/_templates --mirror http://ikt.pm2.io/ikt.git /home/sourab/.npm/_git-remotes/http-ikt-pm2-io-ikt-git-4d23bf0d: undefined
npm WARN optional dep failed, continuing ikt@git+http://ikt.pm2.io/ikt.git#master
npm WARN optional dep failed, continuing fsevents@1.0.5
npm WARN prefer global pm2@0.15.10 should be installed with -g

root@c7511b58315b:/etc# cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.3 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

myuser@c7511b58315b:~$ npm version
{ 'ubuntu-node': '0.0.1',
  npm: '2.11.3',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.7',
  openssl: '1.0.1p',
  uv: '1.6.1',
  v8: '3.28.71.19',
  zlib: '1.2.8' }
myuser@c7511b58315b:~$ 

Can this warning , pls be fixed?

Tnanks Regards,
Raj

**Comment by Unitech** [comment]
It does not impact the installation of PM2, if you really want to skip this step:

```
$ npm install pm2 -g  --no-optional 
```

**Comment by rasekar2000** [comment]
Thanks ..

**Comment by mariojunior** [comment]
Hi... I've checked this file is just a console.log('hello'), why do we need this? Maybe for statistics (hitting the server and counting how many downloads you got?)

**Comment by vmarchaud** [comment]
@mariojunior Exactly, npm download aren't really accurate.
