### ISSUE TITLE
pm2 restarts my process when it writes to a file

### ISSUE THREAD

**Issue by natcl** [Unitech/pm2#1759]
I use pm2 to manage a node-red instance.  Whenever I write to a file in node-red, pm2 restarts node-red with this message:
```
PM2 Change detected on path logs/coact_test.log for app node-red - restarting
PM2 Stopping app:node-red id:0
```

This happened after I did an npm update, any ideas why this is happening ?

**Comment by soyuka** [comment]
When doing `pm2 list` is "Watching" enabled?

**Comment by natcl** [comment]
Yes that's with watching enabled (I assume that pm2 restarts when the app crashes, not when a file changes ?)

**Comment by soyuka** [comment]
hmm nope, watch is to watch for files change. Pm2 restart the app when it crashes by default.

**Comment by natcl** [comment]
Oh I see, that's strange because watching was enabled before also but it did not crash.
Is there a way to disable the watchdog also ?

**Comment by natcl** [comment]
ah just found it thanks, it's --no-autorestart

**Comment by soyuka** [comment]
```
autorestart: false
```

Or with cli `pm2 start --no-autorestart`. Documented : http://pm2.keymetrics.io/docs/usage/application-declaration/

**Comment by Ankur008** [comment]
I am trying to upload the image on the aws server,
It works when I run pm2 like that

pm2 start bin/www --log-date-format "YYYY-MM-DD HH:mm"  autorestart: false

but if watch enabled, app crashes.  
So I can't use the watch when autorestart sets to false??

**Comment by CH4V3Z** [comment]
if you need watch changes, you can use next conf

`"ignore_watch"	: [
				"./log", "./node_modules","./.git",
				"./sessions","./sessions/*", "./private/files/**/*",
				"./private/imgs/**/*"
			],`

**Comment by FarvaTech** [comment]
CH4V3Z - You saved me!   Thanks for the intel.  You rock!

**Comment by brettz9** [comment]
Isn't this still a bug if logging causes pm2 to write to the log file which triggers a restart? Shouldn't pm2 automatically ignore its own log files?

**Comment by brettz9** [comment]
`--ignore-watch="logs/**"` does the trick at least...
