### ISSUE TITLE
startup script should honour the home directory of the given user

### ISSUE THREAD

**Issue by binarykitchen** [Unitech/pm2#1762]
I initialize the startup script with the custom user `nodejs` who has no sudo rights

```
sudo su -c "env PATH=$PATH:/usr/bin pm2 startup ubuntu -u nodejs"
```

but when I open the startup script I see a bad home directory

```
NAME=pm2
PM2=/usr/lib/node_modules/pm2/bin/pm2
USER=nodejs

export PATH=/usr/bin:$PATH
export PM2_HOME="/root/.pm2"
...
```

PM2_HOME should be the home directory of the nodejs user, shouldn't it?

**Comment by Unitech** [comment]
Hey,

It is fixed via the new --hp option: 419b748#diff-4ce9aea92d36e9c98f1eae56904b4a3eR634
419b748#diff-4ce9aea92d36e9c98f1eae56904b4a3eR602

**Comment by binarykitchen** [comment]
great, thanks. can you inform on this ticket when this change is out on npm?

**Comment by estliberitas** [comment]
+1 to @binarykitchen 

@Unitech

**Comment by Unitech** [comment]
issue fixed long time ago, closin'
