### ISSUE TITLE
cron_restart and autorestart

### ISSUE THREAD

**Issue by debovitch** [Unitech/pm2#1767]
I have a script that I don't want to restart after crash but I want to launch it at fixed time, for instance every day.
So I set my options this way : 
<pre>
       pm2.start({
                apps: [
                    {   
                        name: "myscript",
                        script: "./bin/myscript",
                        exec_mode: "cluster",
                        args: importArgs,
                        cron_restart: "0 0 * * *",
                        autorestart: false
                    }
                ]
            }, ...
</pre>
Cron never starts with this code, and if I remove autorestart option, cron does work.

Did I miss something or is it a bug ?

**Comment by Unitech** [comment]
That's normal that it does not work as the Cron feature is handled by your application itself. So it must be online for the cron feature to work

**Comment by Unitech** [comment]
Closing for now, but in the future it would be interesting to have the Cron feature handled by PM2 instead

**Comment by debovitch** [comment]
Got it, thanks for your reply.

**Comment by shsu** [comment]
I'm currently using the `cron_restart` to kick off an hourly script and it looks like setting `autorestart` to false is preventing my app from starting `restarting`.

Is there a workaround other than `restart_delay`?
