### ISSUE TITLE
Problem with pmx using babel

### ISSUE THREAD

**Issue by jonathanbeber** [Unitech/pm2#1772]
Hi, 

I'm trying to use babel to run my app. I can start it with `pm2 start "./node_modules/babel/bin/babel-node.js" --name "myApp" --watch -- bin/www`. 

The problem is when I try collect HTTP informations with `pmx` module to KeyMetrics. My software is written in ECS6 and I've tried to put the `pmx` init code in the babel module (`./node_modules/babel/bin/babel-node.js`) but it doesn't work too. 

I tried put this in `bin/www` file: 

```js
import pmx from 'pmx';
let probe = pmx.probe();
pmx.init({ http: true });
```

Can someone help me?

**Comment by soyuka** [comment]
https://github.com/Unitech/pm2/issues/1643 related

May you try to use the babeljs require hook instead? See http://pm2.keymetrics.io/docs/usage/specifics/#babeljs

**Comment by jonathanbeber** [comment]
It works perfectly. Thanks, @soyuka.
