### ISSUE TITLE
pm2 crashes with ENFILE error, bringing down all apps it is running

### ISSUE THREAD

**Issue by catdad** [Unitech/pm2#1773]
If the filesystem reaches its limit of open files for some period of time (several milliseconds), PM2 will crash. It usually crashes silently, but I was able to see this error when using `pm2 status` while running my tests. I am putting together a code example, but I currently only have access to a Windows machine (where this issue does not seem to happen). I should have some code tomorrow.

PM2 version 0.15.10
Node version 0.12.7
Mac OS (tested)

This happens under cluster mode, as a single Node instance will hit the EMFILE limit (open files per process) before the ENFILE limit (open files for the entire filesystem).

**Comment by catdad** [comment]
Here is a simplified case that will reproduce this issue:

```javascript
var fs = require('fs');
var argv = process.argv;
var command = argv[2];

var enfileReached = 0;
var emfileReached = 0;
var openStreams = [];

if (command === 'init') {
  // set up some files
  // we need to be opening different files, we can't open the same file over and over
  fs.mkdirSync('./files');
  for (var i = 0; i < 10000; i++) {
    fs.writeFileSync('./files/test' + i + '.txt', 'this is just a test file');
  }
} else if (command === 'delete') {
  // delete the files, because we are nice people
  var files = fs.readdirSync('./files');
  files.forEach(function(file) {
    fs.unlinkSync('./files/' + file);
  });
  fs.rmdirSync('./files');
} else {
  // crash the darn thing
  var files = fs.readdirSync('./files');
  console.log('reading %s files', files.length);

  while (!enfileReached && files.length) {
    var file = files.shift();
    var stream = fs.createReadStream('./files/' + file);

    stream.on('error', function(err) {
      if (err.code === 'ENFILE') {
        enfileReached++;
      } else if (err.code === 'EMFILE') {
        emfileReached++;
      }
    });

    openStreams.push(stream);
  }

  setTimeout(function() {
    console.log('files left', files.length);
    console.log('emfileReached', emfileReached);
    console.log('enfileReached', enfileReached);
  }, 1000);

  // just to keep the process running longer
  setInterval(function(){}, Math.POSITIVE_INFINITY);
}
```

To use this, place the content in a file called `index.js`, and then run:

`node index.js init`

After that, start the index file in PM2, as such:

`pm2 start index.js -i 4`

This will crash PM2 immediately. In most cases, PM2 does not even output all of the start info to the console. You may want to add a small delay in executing that last `else`, so that it will fully start the cluster and crash afterwards.

**Comment by zhaoyueer** [comment]
How to solve it, encountered a similar problem
