### ISSUE TITLE
PM2 startup script only works for a single user

### ISSUE THREAD

**Issue by tschuy** [Unitech/pm2#1775]
Hi all!

I'm trying to run PM2 with two apps running under two users, but if I try to use PM2's built-in startup script generator to start PM2 on server reboot, it of course overwrites the first user with the second.

Would it be possible to support an arbitrary number of startups by username? I'd prefer not to run all of my apps under one user account.

**Comment by soyuka** [comment]
Discussed here https://github.com/Unitech/pm2/issues/1753

**Comment by tschuy** [comment]
Ah, apologies for not reading that. Closing for duplication.
