### ISSUE TITLE
Using PM2 to manage all processes

### ISSUE THREAD

**Issue by calebmer** [Unitech/pm2#1776]
I want to use PM2 to manage all of my processes, even non node ones. I have some processes written in Haskell and Go (which are compiled) and run in a bash environment. Does PM2 accommodate this use case?

**Comment by ravi** [comment]
Yes, you can use PM2 in fork mode with exec interpreter set to none.

**Comment by calebmer** [comment]
@ravi With exec_interpreter set to bash, the restart and stop commands fail, is this to be expected?

**Comment by ravi** [comment]
Are you running a bash script? Try setting it to `none`, I think.

**Comment by calebmer** [comment]
Yep. That works.

**Comment by dgreene1** [comment]
Is there an example of this somewhere?

**Comment by atrauzzi** [comment]
Yeah, wondering if there's any documentation that could be added for non-node executables.

**Comment by soyuka** [comment]
Sure http://pm2.keymetrics.io/docs/usage/process-management/#start-any-process-type

**Comment by vmarchaud** [comment]
@barbalex you should use `pm2 start ./postgrest -- postgrest.conf`, `--` is needed to tell PM2 that you want to define arguments for the process and not for PM2 itself

**Comment by barbalex** [comment]
@vmarchaud Thanks a lot. For your answer and most of all for helping build this great tool.

Somehow I missed that important detail in the documentation. It probably is there but as someone not much into this matter I guess I just did not know how to search correctly.

Maybe this is a general way to do this sort of thing in node and that is why it is not mentioned in the pm2 docs? If so I would plead to add this example for all the poor frontend folks like me ;-)

**Comment by vmarchaud** [comment]
@barbalex It's documented [there](http://pm2.keymetrics.io/docs/usage/quick-start/#42-starts) (second line), but it's common for unix tools to use `--` as a indicator to stop parsing arguments.
For example, if you want to `ls` on a file called `-a`, you can't run `ls -a` because thats an option, you need to use `ls -- -a` :)

**Comment by barbalex** [comment]
@vmarchaud thanks a lot for clarifying that. So it's true that this is a catch for noobs like me who think this may be a node thing when it really is unix ;-)

Any way I offered clarifying this in the postgrest repository (https://github.com/begriffs/postgrest-docs/issues/105) where it would have been most helpful for me.

**Comment by vmarchaud** [comment]
@barbalex If you want our docs is hosted [here](https://github.com/pm2-hive/pm2-hive.github.io/tree/master/docs/features), feel free to make a PR if you want to
