### ISSUE TITLE
No way to run code before stop/kill

### ISSUE THREAD

**Issue by Stackoverload** [Unitech/pm2#1777]
Hello, as far as I'm aware there's no way to run code before pm2 kill or pm2 stop.
I've tried using
```javascripts
process.on('exit', function(code) { });
```
and
```javascript
process.on('SIGINT', function() { });
```
but neither get called when I run pm2 kll/stop

**Comment by Unitech** [comment]
For your process to get alerted of a restart you can use [gracefulReload](http://pm2.keymetrics.io/docs/usage/cluster-mode/#graceful-reload)

**Comment by Unitech** [comment]
You can execute some stuff with this handler: `process.once('SIGTERM', function() { });`
