### ISSUE TITLE
pm2.connect() callback never returns when system boots

### ISSUE THREAD

**Issue by wkopen** [Unitech/pm2#1782]
Hi all, I've been searching for pm2.connect() issues but seems there is very few. Please mark as duplicate if already exists.

I'm using beaglebone black runnign debian v7.8, Node version v0.10.38, and PM2 v0.15.10.

I embedded PM2 code in my JS code called `boot.js`, and I added a startup script `myStart` to `/etc/init.d/` so that the system can automatically run it when system boots. And I had `boot.js` log its console.log to a local file `out.log`. Then I did `pm2 kill` to make sure no pm2 process is running and pm2 daemon is killed, then I rebooted the beaglebone.

After reboot, I checked `pm2 list`, there was no process running. So I checked `out.log`. I saw all the console log outputs until and including 'before PM2 connects', but not 'pm2 failed to connect' or 'pm2 connected'. I checked if boot.js was still running but it was not.

So I manually started my program by running `/etc/init.d/myStart start`, this time, however, I could see 'pm2 connected' and all following console logs. And pm2 successfully started the `fileName`.

I tried adding `setTimeout` to this whole `pm2.connect` process to manually delay the function call by 30 seconds just in case pm2 is waiting on some boot-strapping. But still, same situation.

Any idea? Thanks in advance!

Here's the code in `boot.js`

``` javascript
...
console.log('before PM2 connects');
pm2.connect(function(err) {
                    if (err) {
                        console.log('pm2 failed to connect');
                        console.err(err);
                        return;
                    }

                    console.log('pm2 connected');
                    pm2.start(path.join(__dirname, fileName), {
                        out_file: outPath,
                        error_file: errPath
                    }, function(err, app) {
                        if (err) {
                            console.error('pm2 failed to start ' + fileName);
                            console.error(err);
                            pm2.disconnect();
                        }
                        else {
                            pm2.disconnect();
                            console.log('pm2 started ' + fileName);
                        }
                    });
});
...
```

**Comment by Unitech** [comment]
https://github.com/Unitech/pm2/issues/2559
