### ISSUE TITLE
child_process.exec() in Windows pops up a window

### ISSUE THREAD

**Issue by georgehdd** [Unitech/pm2#1784]
When calling child_process.exec() in Windows it pops up a command prompt window and doesn't do it in the background like expected.

Run the following in Windows with PM2 to demonstrate the issue:
```javascript
require('child_process').exec(['ping 127.0.0.1 -n 6 > nul']);
```
PM2 version 0.15.10
Node version v4.2.1

**Comment by Unitech** [comment]
#1749 related?

**Comment by georgehdd** [comment]
Duplicate #1749
