### ISSUE TITLE
[SyntaxError: Unexpected token .]

### ISSUE THREAD

**Issue by ronag** [Unitech/pm2#1785]
I'm getting this error when running one of my configurations. Everything seems to be ok but I'm not sure where this error originates...? It's not from our application.

```
pm2 logs --err script
script-4 (err): [SyntaxError: Unexpected token .]
script-4 (err): Error while parsing configuration in environment (script)``

**Comment by ronag** [comment]
It's seems using `script` as name in an application json configuration is not supported.

**Comment by Unitech** [comment]
reproduced

**Comment by Unitech** [comment]
it does not affects your application, it's just do basic checks before starting your application and your script named "script" interfere with some environment variables for this check. Please ignore this error (we will skip this warning message)
