### ISSUE TITLE
pm2 start config.json --name [application-name] start all aplications

### ISSUE THREAD

**Issue by rkmax** [Unitech/pm2#1788]
I have a .json file with two applications (app-api y app-worker) I try to run the command

```
$ pm2 start applications.json --name app-worker
```

but all applications are restarted. I understood that only the application's matching name must be started

**Comment by kos984** [comment]
hi, I think you should use 
--only <application-name>            with json declaration, allow to only act on one application
```bash
pm2 start applications.json --only app-worker
```
