### ISSUE TITLE
max_memory_restart

### ISSUE THREAD

**Issue by cssivision** [Unitech/pm2#1796]
when you set max_memory_restart to 300M, and your instance now take up 299M memory, how to solve this problem when this instance has to handle something, and the memory is over 300M? crash this process right now and restart or restart after finish the thing you are handling?

**Comment by Unitech** [comment]
That's an edge case, if your process does not behave well you need to fix it!

You can catch the SIGINT signal and process some stuff (10seconds) before the process receive a final SIGTERM signal.

Or you can catch both signals to not allow PM2 to kill your process, let your process finish your stuff then `process.exit(0)` it
