### ISSUE TITLE
Cluster Mode Errors for node 5.* ES6 Reserved Words

### ISSUE THREAD

**Issue by jzumbrun** [Unitech/pm2#1799]
Ubuntu 14.04.3 LTS
```
pm2 -v
0.14.7
node -v
v5.0.0
```

If I add the following to my config file:
```
"exec_mode"   : "cluster_mode",
"instances"   : 2,
```
Node will not run with the latest node 5.* ES6 syntax.

So in 5.* we can use the `class` architecture and `const` assignments WITHOUT using babel or harmony, whoop! Those new ES6 elements are now just native in 5.*.
pm2 WILL however run correctly in a single fork mode. But as soon as one tries to set the `exec_mode` to `cluster_mode`  I get `SyntaxError: Use of const in strict mode.` 

If I do add the `--harmony` `node_args` flag the `const` error goes away but I get the `class Index {
^^^^^
SyntaxError: Unexpected reserved word
`
error.

I should be able to use the const and class architecture without babel or harmony in cluster_mode I would think.

**Comment by Unitech** [comment]
Thanks for reporting this issue, can you do `pm2 update` and try again your app in cluster mode without the --harmony flag?

**Comment by jzumbrun** [comment]
Well that was an easy fix. Thanks @Unitech!
Im not exactly sure what `pm2 update` did, since the version number is still the same, but it made
the ES6 syntax work.

```
 pm2 update
Be sure to have the latest version by doing `npm install pm2@latest -g` before doing this procedure.
[PM2] Stopping PM2...
[PM2] deleteProcessId process id 0
[PM2] All processes have been stopped and deleted
[PM2] PM2 stopped
Process /home/jon/Projects/contestfarm.dev/api launched
>>>>>>>>>> PM2 updated

pm2 list
┌─────────────┬────┬─────────┬───────┬────────┬─────────┬────────┬─────────────┬──────────┐
│ App name    │ id │ mode    │ pid   │ status │ restart │ uptime │ memory      │ watching │
├─────────────┼────┼─────────┼───────┼────────┼─────────┼────────┼─────────────┼──────────┤
│ contestfarm │ 0  │ cluster │ 18714 │ online │ 0       │ 16s    │ 73.848 MB   │  enabled │
│ contestfarm │ 1  │ cluster │ 18719 │ online │ 0       │ 16s    │ 71.457 MB   │  enabled │
└─────────────┴────┴─────────┴───────┴────────┴─────────┴────────┴─────────────┴──────────┘

```

**Comment by Unitech** [comment]
It was because you started the PM2 daemon with a Node.js version that was not supporting ES6, then you upgraded Node.js but the PM2 daemon was still using the old Node.js version. Applications running in cluster mode use the same Node.js version than the one who was used to start PM2.

Cheers!
