### ISSUE TITLE
pm2 graceful crash

### ISSUE THREAD

**Issue by sradu** [Unitech/pm2#1801]
I have a very particular situation where there's a spawned process being run from inside node that takes a long time to finish. This should have been isolated in a jobber, but it wasn't, and it just takes a while to finish.

Sometimes, rarely, we get an API crash and when it happens the spawned process gets killed.

I was was wondering if there's a concept of a graceful crash. On onUncaughtError we catch the event, tell pm2 to decouple this node and start a new one (just like a graceful reload), and then die when the process is done.

Is something like this possible?

**Comment by Unitech** [comment]
You may want to use: http://pm2.keymetrics.io/docs/usage/signals-clean-restart/
