### ISSUE TITLE
Problems when starts app from PM2

### ISSUE THREAD

**Issue by marcioamr** [Unitech/pm2#1803]
I having some problems when trying to start app from PM2.

When I start manualy its ok.

```
NODE_ENV=production node /usr/local/photoka/photokaApp.js
```

When starting from PM2 the app going down after some seconds.

```
NODE_ENV=production pm2 start /usr/local/photoka/photokaApp.js
```

Erro log:

```
2015-11-29-10:25:02 photokaApp-0 Error: ENOENT, open 'log/filelog-log.log.29-11-2015'
2015-11-29-10:25:02 photokaApp-0     at Error (native)
```

PM2 version:

```
0.15.10
```

Anybody can help me?

**Comment by marcioamr** [comment]
Works when remove NODE_ENV=production from command line. Then you need to set NODE_ENV outside the PM2 command.

**Comment by rogr** [comment]
You can use a configuration file to set your ENV variables: http://pm2.keymetrics.io/docs/usage/application-declaration/

**Comment by Unitech** [comment]
Please set the rights on ~/.pm2 via `chown -R user:user ~/.pm2`
