### ISSUE TITLE
pm2 deploy ecosystem.json must add to project git repo?

### ISSUE THREAD

**Issue by perzy** [Unitech/pm2#1804]
I use pm2 deploy ecosystem.json production to deploy ours project auto.

But I don't want add ecosystem.json to project git repo. Because I will set some "appkey/appsecret ..." env variable in ecosystem.json file and this variable is secret , only team master can set , the other team member can not to see.

So how can I do that?  Place ecosystem.json to my computer but still can use pm2 deploy ecosystem.json to deploy ours project ?

Thank you for you help!

**Comment by PavelPolyakov** [comment]
@perzy 

You need to have ```ecosystem.json``` to run the app, right?
Like this:
```
"post-deploy" : "npm install ; pm2 startOrRestart ecosystem.json --env production"
```

Which means, that you need to have it only when you try to run the app.

You can do something like this, then:
```
"post-deploy" : "npm install ; cp /secretFolderOnProduction/ecosystem.json ./ecosystem.json ; pm2 startOrRestart ecosystem.json --env production"
```

Regards,

**Comment by perzy** [comment]
@PavelPolyakov
You answer resolve my problem really。

Thank you very much!
