### ISSUE TITLE
How can I send custom message to all clusters in my code and I can use process.on('message') listen the event?

### ISSUE THREAD

**Issue by cage1618** [Unitech/pm2#1805]
How can I send custom message to all clusters in my code and I can use process.on('message') listen the event?

process.on('message', function(data) {
// the data is my custom data send by the other code
})

**Comment by Unitech** [comment]
For now inter-process communication is not implemented, you can use redis pub/sub to do this,

Best

**Comment by cage1618** [comment]
Can give me an example? I want to use sailsjs and sailsjs-redis, How can I use pub/sub in this?Thanks!

**Comment by Unitech** [comment]
#1826
