### ISSUE TITLE
Install modules globally

### ISSUE THREAD

**Issue by bragma** [Unitech/pm2#1807]
I have pm2 installed globally and I'd also like to install pm2-logrotate globally. Is there a way to do so?

**Comment by Unitech** [comment]
When you use pm2 install, modules are installed globally (~/.pm2/node_modules)

**Comment by bragma** [comment]
Exactly, it is installed in "~/.pm2/" which is not exactly what I mean with "globally". As per documentation, pm2 is installed with "npm install pm2 -g". This (on my system) installs in "/usr/lib/node_modules/pm2/". All users can then execute pm2, but not all users will have the same "~/.pm2/" and modules, I suppose...
Correct?
Thanks!
