### ISSUE TITLE
Add config property for setting pm2 kill timeout

### ISSUE THREAD

**Issue by shaharmor** [Unitech/pm2#1810]
Right now the way it works is you need to set the environment variable PM2_KILL_TIMEOUT, but it would be much better if this could be added to the pm2 json config per applicaction

**Comment by shaharmor** [comment]
Any chance this will be implemented anytime soon?

**Comment by soyuka** [comment]
Can you be more specific about your needs?

There are many ways to achieve such things: 
- [graceful reload](http://pm2.keymetrics.io/docs/usage/pm2-doc-single-page/#graceful-reload)
- You can also change this in your constants file, see `~/.pm2/conf.js`. 
- There is also [`restart_delay`](http://pm2.keymetrics.io/docs/usage/application-declaration/) to set the delay between restarts.

**Comment by shaharmor** [comment]
When i shutdown my application, i want to have enough time to get rid of ongoing tasks within the app, like saving the state of it in the database for example.

This "saving" takes more time than the `PM2_KILL_TIMEOUT` allows for my app to run after being shutdown, so it kills it.

I want to increase this timeout, but on a per application basis by setting it in the process.json file, and not globally in the entire server.

**Comment by soyuka** [comment]
Yes so `timeout` is not safe/clean. You should use graceful stop and exit when you're done processing leftovers.

**Comment by shaharmor** [comment]
Its not possible to do that because the shutdown is coming from an automated service that shuts down the server and not by manually running a command.

What do you mean by not safe/clean? If i will be able to increase (Or disable) this timeout i will just manually process.exit when i'm done

**Comment by soyuka** [comment]
>  i want to have enough time to get rid of ongoing tasks within the app, like saving the state of it in the database for example

If you want to be 100% sure, that the asynchronous "saving" or the processing of some leftovers tasks is done, increasing the timeout will always leave an uncertainty. 
On the other hand, by using a graceful exit, you'll be able to control when the process can exit.

I don't understand the link between "shutting a server down" and "pm2" and the "timeout". Will the "shutdown" wait that "pm2" has kill every process before shutting the server down?

**Comment by shaharmor** [comment]
In linux servers, when you `shutdown` the server, its sending a `SIGTERM` to all the processes that are running, including nodejs & pm2.

I catch that signal on the application level and handle it accordingly, but pm2 starts to terminate the process too, eventually killing it.

If its not possible to move that timeout to the process.json (Maybe even being able to disable it completely), then i will just set it globally high enough so i will have enough time to do what i need.

**Comment by Unitech** [comment]
@shaharmor following http://pm2.keymetrics.io/docs/usage/signals-clean-restart/ you will soon be able to overidde the [(PM2_)KILL_TIMEOUT](https://github.com/Unitech/pm2/blob/master/lib/God/Methods.js#L236) via the CLI and via JSON with the option `--kill-timeout`

**Comment by shaharmor** [comment]
@Unitech great! looking forward to it

**Comment by Unitech** [comment]
Landed in dev, this will be published tomorrow with PM2 1.0
