### ISSUE TITLE
Adding process.json support for linking KeyMetrics?

### ISSUE THREAD

**Issue by remlabm** [Unitech/pm2#1813]
Hello,

Is it possible to add linking command to the processes.json manifest? I like the idea of running one simple `pm2 start processes.json` that not only starts my workers, but connects my keymetrics account.

Another alternative would be the ability to add pm2 linking support in my actual code base.. but i was unable to find any working examples on how do this.

Thanks!
-m

**Comment by Unitech** [comment]
Moving to #1829
