### ISSUE TITLE
Error: EACCES: permission denied, mkdir

### ISSUE THREAD

**Issue by smolleyes** [Unitech/pm2#1815]
hi

i run my app thru pm2, no problems to start andrun the app BUT

i have to write and read files froms one dir wich has specific permissions (on linux)

my pm2 run as user "webuser" so i added this user to the same group of my dir where i have to write files...

i still have Error: EACCES: permission denied on mkdir or fs.readdir ...

even if i change the dir permissions to 0777 i  still have this error !!! :/ 

an idear ? 

thanks

**Comment by smolleyes** [comment]
edit

tried by starting my app without pm2 = no problems
tried thru nodemon = no problems

problem come with pm2 

thanks

**Comment by smolleyes** [comment]
edit:

have this problem only in cluster mode

no problems if i only have 1 pm2 process

**Comment by Unitech** [comment]
Please fix rights problem on ~/.pm2 with `chown` command

**Comment by smolleyes** [comment]
hello

i don t see what it has  To do with my issue
.. Oo 

my  pm2 rights are good 

please read user s issues before closing them

thanks

Envoyé par TypeMail



Sur 7 déc. 2015 16:33, à 16:33, Alexandre Strzelewicz <notifications@github.com> a écrit:

**Comment by piniu** [comment]
Having the exact same issue here, a script ran with node and pm2 by the same user fails to access a folder that is accessible to that user. The problem happens only when running the script under pm2. 
`ps -aux` shows the node fork started by pm2 running under the correct user, but still I get `EACCES` errors.
@israelidanny

**Comment by israelidanny** [comment]
Our problem ended up the fact that permissions have changed after the `pm2` daemon has been launched. The user that `pm2` was forking processes under was not listed in the new group it has been added to for the current instance of the daemon.

What solved the issue was running `pm2 kill`, and relaunching all the processes monitored by `pm2` (and thereby the daemon itself).

That way the newly added group membership of the operating system user and all of its' consequences regarding permissions were applied.

**Comment by mylastore** [comment]
I am getting this errors for a new application, but older apps they run fine with PM2 so What could be wrong? 

Error: EACCES: permission denied, mkdir '/root/.pm2/logs'
Error: EACCES: permission denied, mkdir '/root/.pm2/pids'
Error: EACCES: permission denied, mkdir '/root/.pm2/modules'

**Comment by mylastore** [comment]
I desperately need help please.... looks like lots of us having similar issues. I try everything by now, remove pm2, re install, update npm packages etc here is the complete error.

```bash
Error: EACCES: permission denied, mkdir '/root/.pm2/logs'
    at Object.mkdirSync (fs.js:1009:3)
    at mkdirpNativeSync (/usr/lib/node_modules/pm2/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
    at Function.mkdirpSync [as sync] (/usr/lib/node_modules/pm2/node_modules/mkdirp/index.js:21:7)
    at module.exports.Client.initFileStructure (/usr/lib/node_modules/pm2/lib/Client.js:133:25)
    at new module.exports (/usr/lib/node_modules/pm2/lib/Client.js:38:8)
    at new API (/usr/lib/node_modules/pm2/lib/API.js:108:19)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/binaries/CLI.js:22:11)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
Error: EACCES: permission denied, mkdir '/root/.pm2/pids'
    at Object.mkdirSync (fs.js:1009:3)
    at mkdirpNativeSync (/usr/lib/node_modules/pm2/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
    at Function.mkdirpSync [as sync] (/usr/lib/node_modules/pm2/node_modules/mkdirp/index.js:21:7)
    at module.exports.Client.initFileStructure (/usr/lib/node_modules/pm2/lib/Client.js:141:25)
    at new module.exports (/usr/lib/node_modules/pm2/lib/Client.js:38:8)
    at new API (/usr/lib/node_modules/pm2/lib/API.js:108:19)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/binaries/CLI.js:22:11)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
Error: EACCES: permission denied, open '/root/.pm2/module_conf.json'
    at Object.openSync (fs.js:498:3)
    at Object.writeFileSync (fs.js:1524:35)
    at module.exports.Client.initFileStructure (/usr/lib/node_modules/pm2/lib/Client.js:149:10)
    at new module.exports (/usr/lib/node_modules/pm2/lib/Client.js:38:8)
    at new API (/usr/lib/node_modules/pm2/lib/API.js:108:19)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/binaries/CLI.js:22:11)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
Error: EACCES: permission denied, mkdir '/root/.pm2/modules'
    at Object.mkdirSync (fs.js:1009:3)
    at mkdirpNativeSync (/usr/lib/node_modules/pm2/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
    at Function.mkdirpSync [as sync] (/usr/lib/node_modules/pm2/node_modules/mkdirp/index.js:21:7)
    at module.exports.Client.initFileStructure (/usr/lib/node_modules/pm2/lib/Client.js:157:25)
    at new module.exports (/usr/lib/node_modules/pm2/lib/Client.js:38:8)
    at new API (/usr/lib/node_modules/pm2/lib/API.js:108:19)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/binaries/CLI.js:22:11)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)

                        -------------

__/\\\\\\\\\\\\\____/\\\\____________/\\\\____/\\\\\\\\\_____
 _\/\\\/////////\\\_\/\\\\\\________/\\\\\\__/\\\///////\\\___
  _\/\\\_______\/\\\_\/\\\//\\\____/\\\//\\\_\///______\//\\\__
   _\/\\\\\\\\\\\\\/__\/\\\\///\\\/\\\/_\/\\\___________/\\\/___
    _\/\\\/////////____\/\\\__\///\\\/___\/\\\________/\\\//_____
     _\/\\\_____________\/\\\____\///_____\/\\\_____/\\\//________
      _\/\\\_____________\/\\\_____________\/\\\___/\\\/___________
       _\/\\\_____________\/\\\_____________\/\\\__/\\\\\\\\\\\\\\\_
        _\///______________\///______________\///__\///////////////__


                          Runtime Edition

        PM2 is a Production Process Manager for Node.js applications
                     with a built-in Load Balancer.

                Start and Daemonize any application:
                $ pm2 start app.js

                Load Balance 4 instances of api.js:
                $ pm2 start api.js -i 4

                Monitor in production:
                $ pm2 monitor

                Make pm2 auto-boot at server restart:
                $ pm2 startup

                To go further checkout:
                http://pm2.io/


                        -------------

Error: EACCES: permission denied, open '/root/.pm2/module_conf.json'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at Object.Configuration.getAllSync (/usr/lib/node_modules/pm2/lib/Configuration.js:299:26)
    at Object.Configuration.getSync (/usr/lib/node_modules/pm2/lib/Configuration.js:270:30)
    at new API (/usr/lib/node_modules/pm2/lib/API.js:117:44)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/binaries/CLI.js:22:11)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
/usr/lib/node_modules/pm2/node_modules/@pm2/agent/src/InteractorClient.js:58
          if (stats.uid === 0) {
                    ^

TypeError: Cannot read property 'uid' of undefined
    at /usr/lib/node_modules/pm2/node_modules/@pm2/agent/src/InteractorClient.js:58:21
    at FSReqCallback.oncomplete (fs.js:192:21)
```

**Comment by Robypelle** [comment]
> 
> 
> I desperately need help please.... looks like lots of us having similar issues. I try everything by now, remove pm2, re install, update npm packages etc here is the complete error.
> 
> ```shell
> Error: EACCES: permission denied, mkdir '/root/.pm2/logs'
>     at Object.mkdirSync (fs.js:1009:3)
>     at mkdirpNativeSync (/usr/lib/node_modules/pm2/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
>     at Function.mkdirpSync [as sync] (/usr/lib/node_modules/pm2/node_modules/mkdirp/index.js:21:7)
>     at module.exports.Client.initFileStructure (/usr/lib/node_modules/pm2/lib/Client.js:133:25)
>     at new module.exports (/usr/lib/node_modules/pm2/lib/Client.js:38:8)
>     at new API (/usr/lib/node_modules/pm2/lib/API.js:108:19)
>     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/binaries/CLI.js:22:11)
>     at Module._compile (internal/modules/cjs/loader.js:1068:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
>     at Module.load (internal/modules/cjs/loader.js:933:32)
> Error: EACCES: permission denied, mkdir '/root/.pm2/pids'
>     at Object.mkdirSync (fs.js:1009:3)
>     at mkdirpNativeSync (/usr/lib/node_modules/pm2/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
>     at Function.mkdirpSync [as sync] (/usr/lib/node_modules/pm2/node_modules/mkdirp/index.js:21:7)
>     at module.exports.Client.initFileStructure (/usr/lib/node_modules/pm2/lib/Client.js:141:25)
>     at new module.exports (/usr/lib/node_modules/pm2/lib/Client.js:38:8)
>     at new API (/usr/lib/node_modules/pm2/lib/API.js:108:19)
>     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/binaries/CLI.js:22:11)
>     at Module._compile (internal/modules/cjs/loader.js:1068:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
>     at Module.load (internal/modules/cjs/loader.js:933:32)
> Error: EACCES: permission denied, open '/root/.pm2/module_conf.json'
>     at Object.openSync (fs.js:498:3)
>     at Object.writeFileSync (fs.js:1524:35)
>     at module.exports.Client.initFileStructure (/usr/lib/node_modules/pm2/lib/Client.js:149:10)
>     at new module.exports (/usr/lib/node_modules/pm2/lib/Client.js:38:8)
>     at new API (/usr/lib/node_modules/pm2/lib/API.js:108:19)
>     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/binaries/CLI.js:22:11)
>     at Module._compile (internal/modules/cjs/loader.js:1068:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
>     at Module.load (internal/modules/cjs/loader.js:933:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:774:14)
> Error: EACCES: permission denied, mkdir '/root/.pm2/modules'
>     at Object.mkdirSync (fs.js:1009:3)
>     at mkdirpNativeSync (/usr/lib/node_modules/pm2/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
>     at Function.mkdirpSync [as sync] (/usr/lib/node_modules/pm2/node_modules/mkdirp/index.js:21:7)
>     at module.exports.Client.initFileStructure (/usr/lib/node_modules/pm2/lib/Client.js:157:25)
>     at new module.exports (/usr/lib/node_modules/pm2/lib/Client.js:38:8)
>     at new API (/usr/lib/node_modules/pm2/lib/API.js:108:19)
>     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/binaries/CLI.js:22:11)
>     at Module._compile (internal/modules/cjs/loader.js:1068:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
>     at Module.load (internal/modules/cjs/loader.js:933:32)
> 
>                         -------------
> 
> __/\\\\\\\\\\\\\____/\\\\____________/\\\\____/\\\\\\\\\_____
>  _\/\\\/////////\\\_\/\\\\\\________/\\\\\\__/\\\///////\\\___
>   _\/\\\_______\/\\\_\/\\\//\\\____/\\\//\\\_\///______\//\\\__
>    _\/\\\\\\\\\\\\\/__\/\\\\///\\\/\\\/_\/\\\___________/\\\/___
>     _\/\\\/////////____\/\\\__\///\\\/___\/\\\________/\\\//_____
>      _\/\\\_____________\/\\\____\///_____\/\\\_____/\\\//________
>       _\/\\\_____________\/\\\_____________\/\\\___/\\\/___________
>        _\/\\\_____________\/\\\_____________\/\\\__/\\\\\\\\\\\\\\\_
>         _\///______________\///______________\///__\///////////////__
> 
> 
>                           Runtime Edition
> 
>         PM2 is a Production Process Manager for Node.js applications
>                      with a built-in Load Balancer.
> 
>                 Start and Daemonize any application:
>                 $ pm2 start app.js
> 
>                 Load Balance 4 instances of api.js:
>                 $ pm2 start api.js -i 4
> 
>                 Monitor in production:
>                 $ pm2 monitor
> 
>                 Make pm2 auto-boot at server restart:
>                 $ pm2 startup
> 
>                 To go further checkout:
>                 http://pm2.io/
> 
> 
>                         -------------
> 
> Error: EACCES: permission denied, open '/root/.pm2/module_conf.json'
>     at Object.openSync (fs.js:498:3)
>     at Object.readFileSync (fs.js:394:35)
>     at Object.Configuration.getAllSync (/usr/lib/node_modules/pm2/lib/Configuration.js:299:26)
>     at Object.Configuration.getSync (/usr/lib/node_modules/pm2/lib/Configuration.js:270:30)
>     at new API (/usr/lib/node_modules/pm2/lib/API.js:117:44)
>     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/binaries/CLI.js:22:11)
>     at Module._compile (internal/modules/cjs/loader.js:1068:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
>     at Module.load (internal/modules/cjs/loader.js:933:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:774:14)
> /usr/lib/node_modules/pm2/node_modules/@pm2/agent/src/InteractorClient.js:58
>           if (stats.uid === 0) {
>                     ^
> 
> TypeError: Cannot read property 'uid' of undefined
>     at /usr/lib/node_modules/pm2/node_modules/@pm2/agent/src/InteractorClient.js:58:21
>     at FSReqCallback.oncomplete (fs.js:192:21)
> ```

same issue, i have a jailed user, and that happens if he uses any pm2 command, if on my account i do su -jaileduser and use the same pm2 command it works fine

**Comment by mateuszmazurek** [comment]
@mylastore @Robypelle how do you execute pm2 command? Directly from terminal or using `npm run`? If `npm run` - is it in version 7? If so - try v6 and check if problem still occurs.

**Comment by linonetwo** [comment]
Exactly same here in 2022, maybe reopen this?

**Comment by vetan2** [comment]
> I desperately need help please.... looks like lots of us having similar issues. I try everything by now, remove pm2, re install, update npm packages etc here is the complete error.
> 
> ```shell
> Error: EACCES: permission denied, mkdir '/root/.pm2/logs'
>     at Object.mkdirSync (fs.js:1009:3)
>     at mkdirpNativeSync (/usr/lib/node_modules/pm2/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
>     at Function.mkdirpSync [as sync] (/usr/lib/node_modules/pm2/node_modules/mkdirp/index.js:21:7)
>     at module.exports.Client.initFileStructure (/usr/lib/node_modules/pm2/lib/Client.js:133:25)
>     at new module.exports (/usr/lib/node_modules/pm2/lib/Client.js:38:8)
>     at new API (/usr/lib/node_modules/pm2/lib/API.js:108:19)
>     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/binaries/CLI.js:22:11)
>     at Module._compile (internal/modules/cjs/loader.js:1068:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
>     at Module.load (internal/modules/cjs/loader.js:933:32)
> Error: EACCES: permission denied, mkdir '/root/.pm2/pids'
>     at Object.mkdirSync (fs.js:1009:3)
>     at mkdirpNativeSync (/usr/lib/node_modules/pm2/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
>     at Function.mkdirpSync [as sync] (/usr/lib/node_modules/pm2/node_modules/mkdirp/index.js:21:7)
>     at module.exports.Client.initFileStructure (/usr/lib/node_modules/pm2/lib/Client.js:141:25)
>     at new module.exports (/usr/lib/node_modules/pm2/lib/Client.js:38:8)
>     at new API (/usr/lib/node_modules/pm2/lib/API.js:108:19)
>     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/binaries/CLI.js:22:11)
>     at Module._compile (internal/modules/cjs/loader.js:1068:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
>     at Module.load (internal/modules/cjs/loader.js:933:32)
> Error: EACCES: permission denied, open '/root/.pm2/module_conf.json'
>     at Object.openSync (fs.js:498:3)
>     at Object.writeFileSync (fs.js:1524:35)
>     at module.exports.Client.initFileStructure (/usr/lib/node_modules/pm2/lib/Client.js:149:10)
>     at new module.exports (/usr/lib/node_modules/pm2/lib/Client.js:38:8)
>     at new API (/usr/lib/node_modules/pm2/lib/API.js:108:19)
>     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/binaries/CLI.js:22:11)
>     at Module._compile (internal/modules/cjs/loader.js:1068:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
>     at Module.load (internal/modules/cjs/loader.js:933:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:774:14)
> Error: EACCES: permission denied, mkdir '/root/.pm2/modules'
>     at Object.mkdirSync (fs.js:1009:3)
>     at mkdirpNativeSync (/usr/lib/node_modules/pm2/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
>     at Function.mkdirpSync [as sync] (/usr/lib/node_modules/pm2/node_modules/mkdirp/index.js:21:7)
>     at module.exports.Client.initFileStructure (/usr/lib/node_modules/pm2/lib/Client.js:157:25)
>     at new module.exports (/usr/lib/node_modules/pm2/lib/Client.js:38:8)
>     at new API (/usr/lib/node_modules/pm2/lib/API.js:108:19)
>     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/binaries/CLI.js:22:11)
>     at Module._compile (internal/modules/cjs/loader.js:1068:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
>     at Module.load (internal/modules/cjs/loader.js:933:32)
> 
>                         -------------
> 
> __/\\\\\\\\\\\\\____/\\\\____________/\\\\____/\\\\\\\\\_____
>  _\/\\\/////////\\\_\/\\\\\\________/\\\\\\__/\\\///////\\\___
>   _\/\\\_______\/\\\_\/\\\//\\\____/\\\//\\\_\///______\//\\\__
>    _\/\\\\\\\\\\\\\/__\/\\\\///\\\/\\\/_\/\\\___________/\\\/___
>     _\/\\\/////////____\/\\\__\///\\\/___\/\\\________/\\\//_____
>      _\/\\\_____________\/\\\____\///_____\/\\\_____/\\\//________
>       _\/\\\_____________\/\\\_____________\/\\\___/\\\/___________
>        _\/\\\_____________\/\\\_____________\/\\\__/\\\\\\\\\\\\\\\_
>         _\///______________\///______________\///__\///////////////__
> 
> 
>                           Runtime Edition
> 
>         PM2 is a Production Process Manager for Node.js applications
>                      with a built-in Load Balancer.
> 
>                 Start and Daemonize any application:
>                 $ pm2 start app.js
> 
>                 Load Balance 4 instances of api.js:
>                 $ pm2 start api.js -i 4
> 
>                 Monitor in production:
>                 $ pm2 monitor
> 
>                 Make pm2 auto-boot at server restart:
>                 $ pm2 startup
> 
>                 To go further checkout:
>                 http://pm2.io/
> 
> 
>                         -------------
> 
> Error: EACCES: permission denied, open '/root/.pm2/module_conf.json'
>     at Object.openSync (fs.js:498:3)
>     at Object.readFileSync (fs.js:394:35)
>     at Object.Configuration.getAllSync (/usr/lib/node_modules/pm2/lib/Configuration.js:299:26)
>     at Object.Configuration.getSync (/usr/lib/node_modules/pm2/lib/Configuration.js:270:30)
>     at new API (/usr/lib/node_modules/pm2/lib/API.js:117:44)
>     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/binaries/CLI.js:22:11)
>     at Module._compile (internal/modules/cjs/loader.js:1068:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
>     at Module.load (internal/modules/cjs/loader.js:933:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:774:14)
> /usr/lib/node_modules/pm2/node_modules/@pm2/agent/src/InteractorClient.js:58
>           if (stats.uid === 0) {
>                     ^
> 
> TypeError: Cannot read property 'uid' of undefined
>     at /usr/lib/node_modules/pm2/node_modules/@pm2/agent/src/InteractorClient.js:58:21
>     at FSReqCallback.oncomplete (fs.js:192:21)
> ```

I solved this by not using sudo. If you are using sudo prefix, try to take out it.
