### ISSUE TITLE
Communicating between two clusters on separate ports

### ISSUE THREAD

**Issue by vigneshshanmugam** [Unitech/pm2#1816]
I am running apps using pm2 using the below config

```sh
pm2 start config.json
```
## config.json
```json
{
    "apps" : [
        {
            "name": "app1",
            "script": "./index.js",
            "exec_mode" : "cluster",
            "instances": -1,
        },
        {
            "name": "app2",
            "script": "./metrics.js",
            "exec_mode": "fork_mode",
        }
    ]
}
```

**index.js** - runs a server on port 8080

**metrics** - runs another server on different port. 

I need to communicate between these two apps, Is it possible using pm2?. If yes, how do you do that?

**Comment by Unitech** [comment]
How do you want to communicate? Sending messages in pub/sub style?

**Comment by Unitech** [comment]
A basic inter process communication system will be available soon.
It will consists of installing a PM2 module (something like `pm2 install pm2-intercom`) then you will be able to send message to all processes via 

Emitter app:

```javascript
process.send({
  type       : 'intercom',
  strategy : 'broadcast',  // or round robin
  data       : {
      some : 'data'
  }
});
```

Receiver app:

```javascript
process.on('message', function(packet) {
   if (packet.type == 'intercom') {
     // Access to my data
     console.log(packet.data);
   }
});
```

**Comment by Unitech** [comment]
Moving to #1826

**Comment by vigneshshanmugam** [comment]
yeah, more like pub/sub. 

Since pm2 follows round robin to each cluster, exposing /metric from clusters will get me the metrics of the present cluster alone. 

I want to expose /metric from master and aggregate the metrics from all other worker clusters.
