### ISSUE TITLE
pm2 cluster not working on centos7 nodejs5.0

### ISSUE THREAD

**Issue by qizisheng** [Unitech/pm2#1817]
Operating System: CentOS Linux 7 (Core)
  Kernel: Linux 3.10.0-123.9.3.el7.x86_64
node -v   v5.0.0
npm -v 3.3.6
4core CPU

// app.js
var http = require('http');
var os = require('os');
http.createServer(function(req, res) {
  res.writeHead(200);
  res.end("hello world and cpu is : "+os.cpus().length);
}).listen(5000);

then when i do 
pm2 start app.js -i 2 --watch

i got this from  pm2 logs

PM2 Starting execution sequence in -cluster mode- for app name:app id:0
PM2 Error: spawn ENOENT
PM2     at errnoException (child_process.js:1011:11)
PM2     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
PM2 App name:app id:0 disconnected    

help plz

**Comment by qizisheng** [comment]
now i use cluster.js to start as cluster mode, then use pm2 start cluster.js as failover.
this seems work fine.

//cluster.js
var cluster = require('cluster');
var http = require('http');
var numCPUs = require('os').cpus().length;

if (cluster.isMaster) {
  for (var i = 0; i < numCPUs; i++) {
    cluster.fork();
  }

  cluster.on('exit', function(worker, code, signal) {
    console.log('worker ' + worker.process.pid + ' died');
    cluster.fork();
  });
} else {
  http.createServer(function(req, res) {
    res.writeHead(200);
    res.end("hello world\n");
  }).listen(4000);
}

**Comment by Unitech** [comment]
Seems like some environment variables are not set ($PWD, $HOME)
