### ISSUE TITLE
pm2 doesn't reload remote url when the ecosystem file changes

### ISSUE THREAD

**Issue by dpereira411** [Unitech/pm2#1820]
Is this expected behaviour? How to change the remote git repository after deploy setup?

**Comment by Unitech** [comment]
The PM2 deployment system is not that flexible, if you would like to keep track of this possible feature (change branch / repo url easily) please open an issue [here](https://github.com/Unitech/pm2-deploy) and feel free to send a first draft of PR so we can discuss further on this
