### ISSUE TITLE
Use --raw option with start command and --no-deamon

### ISSUE THREAD

**Issue by ThibautGery** [Unitech/pm2#1821]
I'm using pm2 in docker and I'm using `CMD pm2 start myApp.json --no-deamon`.
I'm also using JSON logging from bunyan and I wish to delete any additional data from pm2. The `--raw` option exists but is only usable with the `logs` command.

I wish to be able to run `CMD pm2 start myApp.json --no-deamon --raw`.

Can you add this option to the start method ?

Thank you

**Comment by Unitech** [comment]
You can do

```
CMD pm2 start myApp.json
CMD pm2 logs --raw
```

**Comment by ThibautGery** [comment]
According to me it's not a good solution: 
First of all, you can only have one CMD but it could be `pm2 start myApp.json && pm2 logs --raw`
Yet I would be breaking one concept: One container = One process.

 * If for some reason my log process crash, My container would crash but the application would still be running
 * If some reason my application crash, my log would continue to follow the log file but my application would be down.

Am I wrong ?
