### ISSUE TITLE
Correct way to update deployment args

### ISSUE THREAD

**Issue by BruceBGordon** [Unitech/pm2#1823]
I have an ecosystem with an apps and a deploy section. When I update the apps "args" json, what is the proper pm2 sequence of commands to get the new args deployed to the hosts? 

I've found that `pm2 deploy ecosystem-worker.json dev update` does not update the args. So far I've had to delete the source dir on the host, and do a `pm2 setup` followed by a `pm2 deploy`

Thanks, -Bruce

**Comment by Unitech** [comment]
What are your PM2 versions?

**Comment by BruceBGordon** [comment]
0.15.9 on all machines.

**Comment by BruceBGordon** [comment]
osx 10.10.5
node v5.0.0

**Comment by BruceBGordon** [comment]
any update? Thanks, -bruce

**Comment by BruceBGordon** [comment]
?

**Comment by Unitech** [comment]
it gets updated automatically now
