### ISSUE TITLE
pm2  node-schedule, why code  repeat executed  in every process?

### ISSUE THREAD

**Issue by Mainintowhile** [Unitech/pm2#1828]
code like this with express:
var rule = new schedule.RecurrenceRule();
rule.minute = 12//excute per hour
schedule.scheduleJob(rule, request(url…));
…
router.get(’…’)
…
and then the request execute multiple times，why？and how to solve
//node:v4.2.1 pm2:0.15.10

**Comment by Mainintowhile** [comment]
如何解决pm2部署nodejs项目时node-schedule这类模块重复执行？

**Comment by bodyno** [comment]
Of couse it will execute multiple times

**Comment by bodyno** [comment]
Use this http://stackoverflow.com/questions/34446969/how-can-we-configure-master-process-when-using-pm2

**Comment by deepred5** [comment]
https://stackoverflow.com/questions/40422589/how-to-use-node-schedule-to-run-a-cron-only-on-one-instance
