### ISSUE TITLE
pm2 doesn't start on CentOS 6.7

### ISSUE THREAD

**Issue by http91** [Unitech/pm2#1832]
I installed it like below.

sudo npm install pm2@latest -g

Here's the output.

```
npm WARN optional dep failed, continuing fsevents@1.0.6
/usr/bin/pm2 -> /usr/lib/node_modules/pm2/bin/pm2
/usr/bin/pm2-dev -> /usr/lib/node_modules/pm2/bin/pm2-dev
pm2@0.15.10 /usr/lib/node_modules/pm2
├── ikt@0.0.0
├── isbinaryfile@2.0.4
├── eventemitter2@0.4.14
├── pidusage@0.1.1
├── safe-clone-deep@1.0.5
├── semver@5.0.3
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── debug@2.2.0 (ms@0.7.1)
├── async@1.5.0
├── pm2-multimeter@0.1.2 (charm@0.1.2)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── pm2-deploy@0.2.1 (async@1.4.2, tv4@1.0.18)
├── pm2-axon@2.0.9 (amp-message@0.1.2, escape-regexp@0.0.1, amp@0.3.1, configurable@0.0.1)
├── shelljs@0.5.3
├── mkdirp@0.5.1 (minimist@0.0.8)
├── pm2-axon-rpc@0.3.6 (json-stringify-safe@5.0.1, commander@1.0.5)
├── cli-table@0.3.1 (colors@1.0.3)
├── vizion@0.2.12 (async@0.9.0)
├── nssocket@0.5.3 (lazy@1.0.11)
├── coffee-script@1.9.3
├── pmx@0.5.8 (json-stringify-safe@5.0.1)
├── cron@1.0.9 (moment-timezone@0.3.1)
├── moment@2.10.6
└── chokidar@1.2.0 (arrify@1.0.1, path-is-absolute@1.0.0, glob-parent@2.0.0, async-each@0.1.6, is-binary-path@1.0.1, is-glob@2.0.1, lodash.flatten@3.0.2, readdirp@2.0.0, anymatch@1.3.0)
```

Versions

```
Node.js version : 4.2.3
NPM version : 3.5.2
pm2 version : 0.15.10
```

Node.js' port is 80, it works without an issue when I run it via "npm start", but "pm2 start app.js" doesn't do anything, so I can't access my app. What could be the problem?

$HOME resolves to /root and $PWD resolved to /root/site (site is the folder where my app lives)

**Comment by SkamDart** [comment]
I'm running into the same issue. All ports `0-1024` are reserved for `root`. Thus, a couple solutions would be: use the package `authbind` as described by [here\(http://pm2.keymetrics.io/docs/usage/specifics/) by them, or run the command with `sudo` to host below 1024.

**Comment by soyuka** [comment]
You can run pm2 as root. 

I usually use nginx on front with an upstream to my pm2 apps. This allows me to ease lot of things regarding installation/deployments/maintenance.
