### ISSUE TITLE
pm2 startup script - user option does not work

### ISSUE THREAD

**Issue by focused** [Unitech/pm2#1835]
http://pm2.keymetrics.io/docs/usage/startup/ says:

"Let's say you want the startup script to be executed under another user. Just use the -u <username> option !"

```
developer@vds1085:~$ pm2 startup ubuntu -u www
[PM2] Spawning PM2 daemon
[PM2] PM2 Successfully daemonized
[PM2] You have to run this command as root. Execute the following command:
      sudo su -c "env PATH=$PATH:/usr/local/nvm/versions/node/v5.2.0/bin pm2 startup ubuntu -u developer --hp /home/developer"
```

Generated command uses "developer" as username, not "www". Is it a bug?
The pm2 version is `pm2@0.15.10`

**Comment by Unitech** [comment]
Just the log message that is not correct, but the option works
