### ISSUE TITLE
Different clustering algorithm

### ISSUE THREAD

**Issue by bputt** [Unitech/pm2#1837]
Just a feature request:

Allow different load balancing algorithms...While NodeJS requests are supposed to be as fast as possible, some times there are requests that take a little longer than others which can hold up the next incoming request even when a thread is available. 

I'd assume least connections would be sufficient as a connection is dropped after NodeJS processes the request?

**Comment by soyuka** [comment]
pm2 is using the embed [cluster](https://nodejs.org/api/cluster.html).

**Comment by Unitech** [comment]
Currently we embbed the cluster module for ease of use, for more advanced load balancing techniques please use something like nginx or haproxy
