### ISSUE TITLE
Exited with code SIGKILL

### ISSUE THREAD

**Issue by tvq** [Unitech/pm2#1839]
Whenever my node application consume more then 100MB Ive got **Exited with code SIGKILL** error.
When I add `--max-old-space-size=2048` error states same. 
When I use `DEBUG=pm2:* PM2_DEBUG=true` there is no more information.

Scenario: 
1) app make request to remote server for product list (json array - 63MB)
2) app is consuming body of response and when usage of memory is bigger then 100MB Ive got `PM2 App name:core id:0 exited with code SIGKILL` and pm2 restarts app

pm2 version: 0.15.10
node version: 5.2.0
os: Ubuntu 14.04.3 LTS

Any thoughts?
Thanks

**Comment by Unitech** [comment]
Have you used the option --max-memory-restart before? http://pm2.keymetrics.io/docs/usage/process-management/#max-memory-restart

**Comment by tvq** [comment]
Just tired it now: `DEBUG=pm2:* PM2_DEBUG=true pm2 start app.js --max-memory-restart 300M`
After ~105MB app restarted again.

```
app-0 REQUEST response end http://remote.server.com { 'cache-control': 'no-cache',
app-0   pragma: 'no-cache',
app-0   'content-length': '63106796',
app-0   'content-type': 'application/json; charset=utf-8',
app-0   expires: '-1',
app-0   server: 'Microsoft-IIS/8.0',
app-0   'x-aspnet-version': '4.0.30319',
app-0   'x-powered-by': 'ASP.NET',
app-0   date: 'Tue, 15 Dec 2015 16:55:23 GMT',
app-0   connection: 'close' }
app-0 REQUEST end event http://remote.server.com
app-0 REQUEST has body http://remote.server.com 63106796
PM2 App name:app id:0 exited with code SIGKILL
PM2 Starting execution sequence in -fork mode- for app name:app id:0
PM2 App name:app id:0 online
```

**Comment by tvq** [comment]
Ok, I have no idea why but Ive started to see more detailed error :confused: 
Now I have `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory` and `exited with code SIGABRT`

**Comment by Unitech** [comment]
process out of memory

**Comment by alokm2w** [comment]
First Stop & Delete your current running PM2 App.

pm2 stop <app name>

pm2 delete <app name>

Then execute the below commands:

pm2 kill

rm -rf ~/.pm2

Now start your app again and see the logs.

pm2 start <app name>

pm2 logs
