### ISSUE TITLE
PM2 watch: catch event

### ISSUE THREAD

**Issue by ggarret** [Unitech/pm2#1841]
Hello, 
i want to catch event when pm2 restart with watch argument.
The goal is to clean  entries into redis serveur.

I try to catch SIGINT and SIGKILL into my node app, but nothing works.. :( 

Thank you for help !

**Comment by Unitech** [comment]
To handle signals (SIGINT) please upgrade to the latest PM2 

```
$ npm install Unitech/pm2#development -g
```
