### ISSUE TITLE
PM2-init.sh - load defaults from /etc/default/pm2

### ISSUE THREAD

**Issue by shaharmor** [Unitech/pm2#1844]
The pm2-init.sh script should load a script from /etc/default/pm2 that will be used to override its defaults (That way you don't have to modify pm2-init.sh manually.

**Comment by shaharmor** [comment]
http://superuser.com/questions/354944/what-is-the-purpose-of-etc-default

**Comment by shaharmor** [comment]
Here is an example from the elasticsearch init.d script: https://github.com/elastic/elasticsearch/blob/master/distribution/deb/src/main/packaging/init.d/elasticsearch

Points to look at:
1) default the default path: https://github.com/elastic/elasticsearch/blob/master/distribution/deb/src/main/packaging/init.d/elasticsearch#L25
2) define overrideable variables: https://github.com/elastic/elasticsearch/blob/master/distribution/deb/src/main/packaging/init.d/elasticsearch#L40
3) load the config script from /etc/default: https://github.com/elastic/elasticsearch/blob/master/distribution/deb/src/main/packaging/init.d/elasticsearch#L88
4) use variables if they are configured: https://github.com/elastic/elasticsearch/blob/master/distribution/deb/src/main/packaging/init.d/elasticsearch#L156

**Note**: configuring ulimit like this is super critical as when using pm2 after a reboot the default ulimit is used unless setting it up in the init.d script manually.
This should be added so its possible to override the ulimit with pm2 without modifying the startup script itself, but the configuration script instead.

**Comment by Unitech** [comment]
That sounds really usefull, would you feel comfortable to do this new init.d script?

**Comment by shaharmor** [comment]
Sure I'll make a PR tomorrow
