### ISSUE TITLE
Download PDF problem

### ISSUE THREAD

**Issue by Daaru00** [Unitech/pm2#1847]
I have a problem to download pdf when the process I launched with pm.
I have nginx configured as proxy to my nodejs application, if I launch my application simply with ```nodejs app.js``` the pdf is downloaded correctly otherwise if I use pm2 the response header have the correct content-type (application/pdf) but I can't open the file because I reach an error
"document type (text/plain) is not supported" and I can't open it both in the browser and with any other application.

What's the problem? is pm2 using any kind of proxy?

**Comment by soyuka** [comment]
Pm2 could not interfere with the Content-Type in which it does not touch your web server (ie no proxy or anything like this).

**Comment by Daaru00** [comment]
I check the file created before it was downloaded and the problem is there. I used [html-pdf](https://www.npmjs.com/package/html-pdf) with function ```pdf.create().toFile()``` to render the file when I execute it in pm2 "enviroment" the file content is wrong.

**Comment by Daaru00** [comment]
sorry, was only a memory fault

**Comment by harisaikaja** [comment]
how did u able to resolve this?
