### ISSUE TITLE
Doesn't resurrect properly from /etc/init.d/pm2-init restart (or start)

### ISSUE THREAD

**Issue by jvanalst** [Unitech/pm2#1849]
So PM2 after dumping doesn't resurrect any of the processes. In fact, it's wiping out the dump.pm2 in the ~/.pm2 folder so that the processes can never be resurrected. I could not tell you why.

Script was generated using ```sudo su -c "env PATH=$PATH:/usr/bin pm2 startup ubuntu -u nodejs```

Looking at the the /etc/init.d/pm2-init script it appears to be referencing a ```/root/.pm2``` folder but the dump files are initially saved to ```/home/nodejs/.pm2```. Why it's blanking the dump file in the second folder after a restart (say instead of ignoring it entirely), I couldn't tell you.

Is this something I'm doing wrong?

**Comment by artursudnik** [comment]
https://github.com/Unitech/pm2/issues/1035

**Comment by jvanalst** [comment]
That does look like it could be the same issue. It's hard to tell at this point.

**Comment by Unitech** [comment]
#1035
