### ISSUE TITLE
Max-memory is graceful?

### ISSUE THREAD

**Issue by behrad** [Unitech/pm2#1857]
How pm2 handles max-memory option? Does it kill the process or it stops it gracefully? 
I want to be sure if app's `shutdown` hook will be called then, so that we can stop gracefully.

If not, using a `graceful nightly restart cronjob` would be a better option!

**Comment by Unitech** [comment]
Under the hood, [PM2 do a graceful reload](https://github.com/Unitech/pm2/blob/master/lib/Worker.js#L31) when your process is exceeding the specified memory threshold

Cheers

**Comment by mugli** [comment]
@Unitech It'd be great if the info is in doc too, unless I've missed it. :)

**Comment by vmarchaud** [comment]
@mugli [Done](http://pm2.keymetrics.io/docs/usage/process-management/#max-memory-restart)

**Comment by mugli** [comment]
Awesome!
