### ISSUE TITLE
Memory climbing in CentOS but not OSX

### ISSUE THREAD

**Issue by Kav91** [Unitech/pm2#1858]
![image](https://cloud.githubusercontent.com/assets/13043208/12008273/a1ced1f0-ac84-11e5-9efe-db60dd68f5ff.png)

So running identical API i'm testing, and this is making 0 calls to it. 
Its literally just running and doing nothing.

Bottom is CentOS 7
Top is my local OS X machine 10.11.2

Both are on;
node v4.2.2
pm2 0.5.10

Not sure if this is PM2 not liking centos or centos not playing nice.

**Comment by Unitech** [comment]
You are using the fork mode, it cannot come from PM2 at all,

Have you noticed something new since you posted this issue?

**Comment by Unitech** [comment]
Closing for now please re open if you still notice this issue
