### ISSUE TITLE
Node 5.3.0 - API failure

### ISSUE THREAD

**Issue by bluejamesbond** [Unitech/pm2#1859]
The following API functions do not work as intended - process not found error
- Restart by appName
- Reload by appName

**Comment by Unitech** [comment]
[All tests are passing on Travis with Node 5.3.0](https://travis-ci.org/Unitech/pm2/jobs/98353745), I've also tested this locally, no bugs.

Could you please do:

```bash
$ pm2 update
```

**Comment by Unitech** [comment]
Feel free to reopen the issue if the issue still exists
