### ISSUE TITLE
Inconsistency between CLI and Programmatic behavior for cluster mode

### ISSUE THREAD

**Issue by gera2ld** [Unitech/pm2#1861]
``` js
pm2.start({
  name: 'app',
  script: 'app.js',
  instances: 0,
}, function (err) {
  console.log(err);
});
```

If I pass `0` to `instances`, the maximum processes will be started but in **fork** mode, which makes all processes fail in the end but one.
Only if I pass a number other than `0` to `instances`, **cluster** mode will be entered.
Also tried the string `'0'` but didn't work either.

Environment:
Node v4.2.1

**Comment by Unitech** [comment]
Thanks for reporting this inconsistency between CLI and Programmatic.

I will check this, until this is fixed please specify the exec_mode:

```
pm2.connect(function() {
  pm2.start({
    name: 'app',
    script: 'app.js',
    instances: 0,
    exec_mode : 'cluster'
  }, function (err) {
    console.log(err);
  });
})
```
