### ISSUE TITLE
'pm2 monit' causes higher CPU usage of 'WMI Provider Host' process on Windows 10

### ISSUE THREAD

**Issue by knight00931** [Unitech/pm2#1862]
My environment: Windows 10 x64 professional (10586.36), Node.js 5.3.0, npm 3.5.2, pm2 0.15.10

Steps to reproduce:
1. create a js file called test.js (even there is nothing in it)
2. pm2 start test.js -i 0 (looks fine)
3. pm2 monit

And then you'll see there's process called 'WMI Provider Host' using 2~30% CPU (depends on how many instance you have in the same time) while monit function is running. As soon as you exit monit by pressing ctrl-C, that problem disappears.

It happens on another PC which is using Windows Server 2008 as well.

**Comment by Unitech** [comment]
It may be a process to allow monitoring processes under Windows.

We have updated some monitoring features on the last PM2, could you try it:

```
$ npm install Unitech/pm2#development -g
```

**Comment by knight00931** [comment]
It still happens, plus, there were some cmd.exe windows popped up after launching 'pm2 monit'...

**Comment by soyuka** [comment]
https://github.com/soyuka/pidusage/commit/2c8d47d2365590684e5998be33d9ce05af5ab8f3

This was a recent change, see also https://github.com/soyuka/pidusage/pull/16. 

For the `cmd.exe` I'll set `detached: true`. You may know a better command to get process usage statistics on windows?

**Comment by knight00931** [comment]
Hi @soyuka, I think I didn't describe correctly.
Normally, there are 4 windows named "Node.js" with green icon popped up after I typed 'pm2 start blah.json', that's OK, because I have 4 instances running in cluster mode.

With pm2 stable version, no additional cmd.exe will pop up after launching 'pm2 monit'.
But with pm2 development version, there are some cmd.exe keep popping up and then closes itself repeatedly.

Back to the CPU usage issue, unfortunately, I don't know any better ways to gather process usage statistics on windows, I just observed that in task manager, its obvious.

Hope this would be helpful.

**Comment by soyuka** [comment]
Yes it's because pm2 development version we updated pidusage with this new command which should be more precise. It does not run in a detached mode hence the cmd.exe that pop's out.

Maybe that monit launches too many wmic instances without waiting for an answer. Let me check those and get back to you.

**Comment by soyuka** [comment]
I've updated the dependency, could you `npm install Unitech/pm2#development -g` to see if cmd.exe still pops out?
About the cpu usage we may increase the [refresh timeout](https://github.com/Unitech/pm2/blob/f57c6c1c89c23368419e0cb123b8338be3aba3b4/lib/CLI.js#L1644) but I don't think that it would improve cpu usage.

**Comment by knight00931** [comment]
Thank you for your reply, @soyuka. It's late here, I'm gonna test it tomorrow and see how it goes.

**Comment by knight00931** [comment]
Hi, I just tested it. Seems these cmd.exe were no longer popped up!

And the cpu usage seems a bit lower, it's between 15%~20% now.

**Comment by Unitech** [comment]
Awesome thanks @soyuka for the fix and @knight00931 for the bug report ! :)

**Comment by knight00931** [comment]
Uh, in fact I don't think this cpu issue is addressed...

**Comment by soyuka** [comment]
@knight00931 if it's WMI that does take ~20% cpu usage there is not much we can do except to improve the base command:

```
wmic path Win32_PerfFormattedData_PerfProc_Process WHERE IDProcess=PID get PercentProcessorTime, WorkingSet
```

It was proposed by @crystaldust as an alternative to the previous command:

```
wmic PROCESS PID get workingsetsize,usermodetime,kernelmodetime
```

to have more accurate results. If you know how we can improve this, feel free to share!

ref https://github.com/soyuka/pidusage/pull/14

**Comment by knight00931** [comment]
OK, thank for the reply.

**Comment by crystaldust** [comment]
I'm sorry I can't test it for now without a Windows environment, I'll give it try later, and maybe we can dig things from Win32_PerfRawData_PerfProc_Process which seems to be faster( since there is no data formatting), I'll make a test

**Comment by crystaldust** [comment]
Sorry for the latency guys, just returned from a journey. I tried with the Win32_PerfRawData_PerfProc_Process instance, which is implemented by calculating the time consuming occupation. Which is faster but I'm not sure if the result is more accurate. According to MSDN,  [Win32_PerfRawData_PerfProc_Process](https://msdn.microsoft.com/en-us/library/aa394277(v=vs.85).aspx)'s PercentProcessorTime property has a Counter Type ["PERF_100NSEC_TIMER"](https://msdn.microsoft.com/en-us/library/ms803979.aspx), which should be calculated in the forum:

```javascript

var percent = deltaProcessTime / deltaTimestamp * 100

```

It is mentioned in a very old [thread](https://msdn.microsoft.com/en-us/library/ms974615.aspx)(the year 2003 when Microsoft is on top of the world!), this should be the  same way @soyuka worked before. The result seems to be a little bit weird, the percent is either a value or just 0, here is the code and you guys can have a try, I'll dig more into it:
``` javascript
var exec  = require( 'child_process' ).exec;

function showCPUUsage( pid, cb ) {
	getRawPerfInfo( pid, function( err, baseInfo ) {
		if( err ) {
			return cb( err );
		}

		process.nextTick( function() {
			getRawPerfInfo( pid, function( err, currentInfo ) {
				if( err ) {
					return cb( err );
				}

				var basePercent 	= baseInfo.percent;
				var baseTimestamp 	= baseInfo.timestamp;

				var currentPercent 		= currentInfo.percent;
				var currentTimestamp 	= currentInfo.timestamp;

				var percent  = 100 * ( currentPercent - basePercent ) / ( currentTimestamp - baseTimestamp );

				return cb( null, percent );
			} );

		}, 1000 );


	} );
}

function getRawPerfInfo( pid, cb ) {
	var cmd = exec( 'wmic path Win32_PerfRawData_PerfProc_Process WHERE IDProcess=' + pid + ' get PercentProcessorTime, Timestamp_Sys100NS', function( error, stdout, stderr ) {
		if( error ) {
			return cb( error, null );
		}

		// Tested under Windows 7 Ultimate SP1, 64 bits
		// The new line in this Windows version is \r\r\n
		var lines 	= stdout.split( '\r\r\n' );
		var titles 	= lines[0];
		var values 	= lines[1].trim().split(/ +/)

		var percent 	= parseFloat( values[0] );
		var timestamp 	= parseFloat( values[1] );
		return cb( null, { percent: percent, timestamp: timestamp } );
	} );
}

// Testing:
setInterval( function() {
	var start = Date.now();
	showCPUUsage( THE_PID, function( err, percent ) {
		console.log( percent.toFixed(2), Date.now() - start, 'ms' );
	} );
}, 1000 );

```

**Comment by tonytranupc** [comment]
> My environment: Windows 10 x64 professional (10586.36), Node.js 5.3.0, npm 3.5.2, pm2 0.15.10
> 
> Steps to reproduce:
> 
>     create a js file called test.js (even there is nothing in it)
>     pm2 start test.js -i 0 (looks fine)
>     pm2 monit
> 
> And then you'll see there's process called '[WMI Provider Host](https://usefulpcguide.com/18548/wmiprvse-exe-wmi-provider-host-high-cpu-issue/)' using 2~30% CPU (depends on how many instance you have in the same time) while monit function is running. As soon as you exit monit by pressing ctrl-C, that problem disappears.
> 
> It happens on another PC which is using Windows Server 2008 as well.

In most cases, just restarted the Windows Management Instrumentation service and it will back to normal.

**Comment by soyuka** [comment]
Yeah, anyway I think pidusage is now as optimised as it can get, this matter (if it still exists) should be resolved by microsoft...

**Comment by pabloruan0710** [comment]
I have this problem in Windows 10, Anybody solved?

**Comment by Unitech** [comment]
@pabloruan0710 you're having this issue only when using `pm2 monit`?
