### ISSUE TITLE
How to remove a link to keymetrics ?

### ISSUE THREAD

**Issue by EduardJS** [Unitech/pm2#1864]
I removed the bucket, and i am trying to `unlink` that `keymetrics.io` bucket from `pm2`. How to accomplish that ?

**Comment by Unitech** [comment]
`pm2 link delete`

**Comment by sudeepdk** [comment]
thanks alot , I was trying "pm2 interact stop"  but you command works fine

**Comment by deju** [comment]
cool

**Comment by michelem09** [comment]
I tried with `pm2 interact delete` and `pm2 link delete` but server is still in the https://app.keymetrics.io dashboard.
Should I force something? How?

**Comment by vmarchaud** [comment]
@michelem09 You can try `ps aux | grep KM` and killing the pid that you see, or just `pkill KM`.
If it still show of the dashboard, that might be another server pushing with the same name
