### ISSUE TITLE
Pm2 God Daemon always running

### ISSUE THREAD

**Issue by fcukinyahoo** [Unitech/pm2#1866]
After stopping all node applications that pm2 controlling, i still see that Pm2 God Daemon still running and consuming ~27M memory. Was is supposed to be that way? If not, should I simply kill it with kill -9 or is there a command line command such as 'pm2 kill all' to stop that Daemon?

**Comment by bhaveshgohel** [comment]
Kill daemon pm2 :
```    
$ pm2 kill
```

Check Help command: 
```
$ pm2 --help
```

**Comment by fcukinyahoo** [comment]
Thanks, Was Pm2 God Daemon meant to be always running?

**Comment by bhaveshgohel** [comment]
@fcukinyahoo  : AFAIK, if its not running(or killed) and you start any new script with pm2 the demon will be activated(wake-up) automatically. So yeah its necessary if scripts are running, else you can kill pm2.

**Comment by fcukinyahoo** [comment]
@bhaveshgohel there was a node project running via pm2. I stop the project but still see the God Daemon. Before stopping the project, I see 2 processes running, actual project via pm2 and pm2 God Daemon. After stoping the project successfully, I still see the God Daemon.

**Comment by bhaveshgohel** [comment]
@fcukinyahoo : The pm2 God Daemon will be running unless you kill it. (Killing pm2 Daemon also kills your script run by pm2.) It's safe to kill daemon if there are no active script run by pm2. :+1:

**Comment by Unitech** [comment]
@bhaveshgohel gave you the answer!
