### ISSUE TITLE
How to get startup scripts working with pm2, NVM and Rasberry Pi

### ISSUE THREAD

**Issue by bchr02** [Unitech/pm2#1868]
I thought I would share how I was able to get pm2 startup scripts working with my Rasberry Pi 2 board, which has RASPBIAN JESSIE and NVM installed on it. Hopefully this saves others some time.

First, Install NVM, Node and pm2. I won't list those steps as they are relatively easy to find. Next, type `whereis pm2` and use the outputted directory to replace within the below steps wherever it reads `/home/pi/.nvm/v0.10.41/bin` 

**Here are the steps:**
- `sudo su -c "env PATH=$PATH:/home/pi/.nvm/v0.10.41/bin pm2 startup linux -u pi --hp /home/pi"`
- Add each script that you want to load, in the following format (where `/home/pi/my\ testing/index.js` is the path to your script): `sudo su -c "env PATH=$PATH:/home/pi/.nvm/v0.10.41/bin pm2 start /home/pi/my\ testing/index.js"`
- save the changes: `sudo su -c "env PATH=$PATH:/home/pi/.nvm/v0.10.41/bin pm2 save"`
- restart the computer to test that they load: `sudo shutdown -r now`

**Comment by zettam** [comment]
I came across this, I have asimilar problem (where things are not loading when raspberry is shut down properly).

This is not a very convenient solution, but the problem is still there. This needs a fix.

**Comment by Unitech** [comment]
refactored since that http://pm2.keymetrics.io/docs/usage/startup/
