### ISSUE TITLE
Can't figure out if processes can be started from various linux users?

### ISSUE THREAD

**Issue by virtuman** [Unitech/pm2#1872]
I see multiple tickets and resolutions about similar question, but seems like they may still be a little bit different from what i'm trying to achieve:

Is it possible to specify what linux user account to use for a specific process that is managed by pm2?
ie: option similar to _user=_ in supervisord:
http://supervisord.org/configuration.html#program-x-section-settings

i can't seem to be able to figure out how this configuration can be achieved.

Thank you.

**Comment by ruquay** [comment]
I might be wrong about how PM2 works, but it seems to me that a separate PM2 "god" process starts for any individual linux user that starts it. So you would just start it as the when you're that user.

That's what I do: start PM2-based apps as the user I want to run them as. If you're root, you could use `su -c 'pm2 start ...' linuxuser` to start it.

**Comment by Unitech** [comment]
Feature added in upcoming PM2. To try it:

(Make sure pm2 is run as root to manipulate uid and gid)

```bash
$ pm2 save
$ pm2 kill
$ npm install Unitech/pm2#development -g
$ sudo pm2 resurrect
$ sudo pm2 start app --uid <uid>
# Now pm2 ls display the user running the script
$ pm2 ls
```

Feedback is welcome
