### ISSUE TITLE
Automated unattended startup - autoscale use case

### ISSUE THREAD

**Issue by gansbrest** [Unitech/pm2#1873]
Hi,

I would like to understand how pm2 would work with unattended startups. 

Our app contains 3 separate node processes (parts): client ---> queue ---> workers
At the moment we have 3 upstart scripts for each part. When new box is started  / restarted - upstart will start those processes and monitor those. In case of node process crash upstart will respawn processes again.

Now we are considering switch to pm2.

First step for us is to install pm2 process manager globally. Question - what will start / monitor this pm2 process, since it becomes single point of failure for all other node processes on the server? What happens after server reboot ( or stop and reszing, adding more cpus )? What happens after process crash even if upstart could potentially restart it, how will it know which processes to run?

We cant just save state (processes) on one box and reuse it for others, because every box could be different, it can have different number of CPUs, different number and locations on node projects?

Is there some kind of global configuration based setup, where we can provide configs with projects locations that pm2 would check to understand which projects it needs to run and run those on boot? We don't want to do any manual steps after new servers are provisioned.

Please advice.

**Comment by michaelBenin** [comment]
On the same note, what tool is used to monitor pm2 itself?

**Comment by Unitech** [comment]
> Question - what will start / monitor this pm2 process, since it becomes single point of failure for all other node processes on the server? 

By using [Keymetrics](https://keymetrics.io/) the agent will also acts as a Watchdog for PM2. So in case of unreachable PM2, the agent wil respawn PM2 with the previous process list.

> What happens after server reboot (or stop and reszing, adding more cpus )?

You can use [the automatic startup script generation](http://pm2.keymetrics.io/docs/usage/startup/) to respawn PM2 on server boot (with the same process launched before)

For the resizing, if you use the [cluster mode](http://pm2.keymetrics.io/docs/usage/cluster-mode/), you can use the `pm2 scale` command to scale up/down the number of processes

> What happens after process crash even if upstart could potentially restart it, how will it know which processes to run?

PM2 keeps the list of processes you started and will monitor each of them and restart them in case of failure.

> We cant just save state (processes) on one box and reuse it for others, because every box could be different, it can have different number of CPUs, different number and locations on node projects?

[PM2 application declaration](http://pm2.keymetrics.io/docs/usage/application-declaration/) file is interpreted as a Javascript file, so you can add environment variables or any other Javascript code to make you configuration dynamic.

[The deployment system](http://pm2.keymetrics.io/docs/usage/deployment/) can be also useful.

**Comment by Unitech** [comment]
> On the same note, what tool is used to monitor pm2 itself?

```
$ pm2 install pm2-probe
```

pm2-probe allows you to monitor PM2 cpu and memory usage and if PM2 is linked to keymetrics you will be able to monitor these vital signs over time

**Comment by gansbrest** [comment]
@Unitech thanks a lot for your response.

Just to clarify pm2-probe package will install the agent which is monitored by regular process supervisors (upstart, systemd, runit) and then this **probe** deamon will monitor main **pm2** process and restart it in case of unresponsiveness?

Another thining - you mentioned probe stats. Is there a way to periodically access those stats and send to our statsd?

**Comment by michaelBenin** [comment]
Is it possible to put a readme or link to the github repo for https://www.npmjs.com/package/pm2-probe?

Is pm2 web still functional in 1.0?

**Comment by gansbrest** [comment]
> You can use the automatic startup script generation to respawn PM2 on server boot (with the same process launched before)

Would be also nice if you provide example for fresh / first time boot, where there is no "before" state.

**Comment by listepo** [comment]
statsd +1
