### ISSUE TITLE
Can i use pmx with a https website ?

### ISSUE THREAD

**Issue by kevincaradant** [Unitech/pm2#1874]
Hi 

I wish follow the network requests but my website is in https . I tried to put : 

require('pmx').init({
  https : true
});

But this doesnot work , any idea , how can i try that . 

Thank you in advance ;)

NB : in http avg , i get this : Great! Not any routes are taking more than 200ms! and i haven't any graph to show all requests :/ but i'm sure that i have requests which do more thatn 200ms

**Comment by Unitech** [comment]
Sure PMX handles http/https. Maybe you are on the Keymetrics free tier (no route logging and processing)

**Comment by kevincaradant** [comment]
Ah yes ... my account it's free , sorry i didn't see that it's available only for the premium account :/

Thank you @Unitech

**Comment by kevincaradant** [comment]
Just to know ,is it possible to have the grpah without pay or not ?
