### ISSUE TITLE
kill parallel

### ISSUE THREAD

**Issue by shaharmor** [Unitech/pm2#1878]
Hi,

Today when pm2 is killing its child processes its waiting for each of them to die before moving to the next one, which makes the "wait" time increase when having many processes.

It should be possible (Probably by a config) to tell pm2 that it should kill all processes at the same time

**Comment by soyuka** [comment]
It's already https://github.com/Unitech/pm2/blob/ba95a803877de19d56d54116d00db46aef532b7f/lib/God/ActionMethods.js#L470

See the `CONCURRENT_ACTIONS` constant.
