### ISSUE TITLE
Using Pm2 to run npm codes

### ISSUE THREAD

**Issue by ponty96** [Unitech/pm2#1880]
I have my app setup and my package.json,i got it setup that I start my app using<code>npm start</code>. My app server is a <code>nginx server proxing</code> to a nodejs server running on <code>port 5000</code>. I also have pm2 installed on my system and its working fine for other node apps on my system. Is there a way to use pm2 to run the <code>npm start</code> or to run this 
<code>node ./node_modules/better-npm-run start-prod</code>?

**Comment by jcollum** [comment]
I use it: 

` pm2 start npm --name=$packageName -- start`

However it seems that it won't restart your app if it hits an error.

**Comment by Unitech** [comment]
now it restarts your app please see #2176
