### ISSUE TITLE
pm2 can't start my app on windows server2008

### ISSUE THREAD

**Issue by knight00931** [Unitech/pm2#1881]
My environment: node js 5.4.0, pm2 1.0.0 on Windows server 2008 (not R2)

While I can still run my app using "node main.js" and "nodemon main.js" without any issue, pm2 can't even start it.
Although it can run on my Windows 10 (with the same version of node js and pm2). I am not sure why.

Here are some error messages:

┌─────────────────────────┬────┬─────────┬──────┬────────┬──
───────┬────────┬────────┬──────────┐
│ App name                │ id │ mode    │ pid  │ status │ restart │ uptime │ memory │ watching │
├─────────────────────────┼────┼─────────┼──────┼────────┼──
───────┼────────┼────────┼──────────┤
│ main.js in cluster mode │ 0  │ cluster │ 4220 │ online │ 0       │ 0s     │ 0 B    │  enabled │
│ main.js in cluster mode │ 1  │ cluster │ 4300 │ online │ 0       │ 0s     │ 0 B    │  enabled │
│ main.js in cluster mode │ 2  │ cluster │ 6052 │ online │ 0       │ 0s     │ 0 B    │  enabled │
│ main.js in cluster mode │ 3  │ cluster │ 2416 │ online │ 0       │ 0s     │ 0 B    │  enabled │
└─────────────────────────┴────┴─────────┴──────┴────────┴──

```
[PM2] Streaming realtime logs for [all] processes

PM2 ERROR:
PM2 Code = 0x800007d0
PM2 Description = Facility = (null)
PM2 ERROR:
PM2 Code = 0x800007d0
PM2 Description = Facility = (null)
PM2 ERROR:
PM2 Code = 0x800007d0
PM2 Description = Facility = (null)
PM2 ERROR:
PM2 Code = 0x800007d0
PM2 Description = Facility = (null)
PM2 [PM2][WORKER] Process 0 restarted because it uses 0 memory and has ONLINE status
PM2 Stopping app:main.js in cluster mode id:0
PM2 App name:main.js in cluster mode id:0 disconnected
PM2 Process with pid 4220 still not killed, retrying...
PM2 App [main.js in cluster mode] with id [0] and pid [4220], exited with code [1] via signal [SIGINT]
PM2 Starting execution sequence in -cluster mode- for app name:main.js in cluster mode id:0
PM2 App name:main.js in cluster mode id:0 online
PM2 [PM2][WORKER] Process 1 restarted because it uses 0 memory and has ONLINE status
PM2 Stopping app:main.js in cluster mode id:1
PM2 App name:main.js in cluster mode id:1 disconnected
PM2 Starting execution sequence in -cluster mode- for app name:main.js in cluster mode id:1
PM2 App [main.js in cluster mode] with id [1] and pid [0], exited with code [1] via signal [SIGINT]
PM2 Starting execution sequence in -cluster mode- for app name:main.js in cluster mode id:1
PM2 App name:main.js in cluster mode id:1 online
PM2 [PM2][WORKER] Process 2 restarted because it uses 0 memory and has ONLINE status
PM2 Stopping app:main.js in cluster mode id:2
PM2 App name:main.js in cluster mode id:1 online
PM2 App name:main.js in cluster mode id:2 disconnected
PM2 App [main.js in cluster mode] with id [2] and pid [6052], exited with code [1] via signal [SIGINT]
PM2 Starting execution sequence in -cluster mode- for app name:main.js in cluster mode id:2
PM2 App name:main.js in cluster mode id:2 online
PM2 [PM2][WORKER] Process 3 restarted because it uses 0 memory and has ONLINE status
PM2 Stopping app:main.js in cluster mode id:3
PM2 App name:main.js in cluster mode id:3 disconnected
PM2 App [main.js in cluster mode] with id [3] and pid [2416], exited with code [1] via signal [SIGINT]
PM2 Starting execution sequence in -cluster mode- for app name:main.js in cluster mode id:3
PM2 App name:main.js in cluster mode id:3 online
```

**Comment by knight00931** [comment]
FYI, node js 5.4.0 with pm2 0.15.0 works fine on server 2008!

**Comment by PierreAnctil** [comment]
Same here.
node js 5.6.0 with pm2 1.0.1 on Windows 10
The same configuration works fine in Debian.
Happens starting from 1.0.0.
I downgraded to 0.15.10 as a workaround.

**Comment by soyuka** [comment]
Can you tell me if the following command results in an error on your windows versions?

```
wmic path Win32_PerfFormattedData_PerfProc_Process WHERE IDProcess=$PID get PercentProcessorTime, WorkingSet
```

Where $PID has to be set to your process id.

Thanks!

**Comment by knight00931** [comment]
`ERROR:
Code = 0xc0000bbf
Description = Facility = (null)` on server 2008

**Comment by knight00931** [comment]
I set pid of a cluster then got:
```

ERROR:
Code = 0xc0000bbf
Description = Facility = (null)

```

**Comment by soyuka** [comment]
As this works on pm2 < 1.0.0 I assume that it's the wmic change that triggers this error and that the previous command works ([commit](https://github.com/soyuka/pidusage/commit/f7186f218b8f56f33ee2a80a3717995b8f9a39db)).

May you check https://github.com/soyuka/pidusage/pull/16#issuecomment-164969098? 

@crystaldust maybe you've thoughts on this?

**Comment by crystaldust** [comment]
It seems that the WMIC service is broken on knight00931 's machine. I've got the issue on my own computer and... well, just failed to repair it after googling everything I can. And after I reinstalled the OS wmic works fine. As we discussed in the previous [issue](https://github.com/Unitech/pm2/issues/1862#issuecomment-168650611) , maybe we can get the data from Win32PerfRawData and compute the pid usage after a CPU interval. The result might to be that accurate, but it seems less likely to bring errors.

Anyway, @knight00931 , can you try this command on your machine:

`https://github.com/Unitech/pm2/issues/1862#issuecomment-168650611`

**Comment by knight00931** [comment]
Hi, on my win 10 machine (which runs latest pm2 and works fine)
```
PercentProcessorTime  Timestamp_Sys100NS
4687500               131014685979356663
```

but on my win server 2008 (mentioned in OP) I got:
```
Invalid GET Expression.
```

Thank you for your help!

**Comment by soyuka** [comment]
Windows really can't do anything simple... I made an attempt to use VBS so that it'd be (theoretically) more portable than `wmic`, but then some function calls had to be internationalized (yeah, on french computer's the command had to be written with french arguments; wtf). You can find this work on some rejected PR's: https://github.com/soyuka/pidusage/pulls?q=is%3Apr+is%3Aclosed

@crystaldust do you think I should add a condition on windows server 2008 OS recognition to spawn a different command? Or maybe if the `wmic` command fail, try to get data another way (but this would be very slow). It doesn't feel right, but if there are no other solutions it'd have to do the trick :|.
I'm also looking in the `C#` approach, or any other language that would get this data on every windows versions . This would mean having a binary that simply gets the process usage of a PID that would work on every windows versions. I don't know if this would work in term of portability or what language would be more appropriate. 

If anyone has an idea, please speak up and I'll implement it asap :).

**Comment by crystaldust** [comment]
Omg, very surprised to here that the French version would require a different behavior on arguments(⊙o⊙) Anyway, I guess the C# approach would call a system provided DLL which links to the underlying WMIC service(not very sure but that should be the way).

@knight00931 That's weird, I ran the command on my Windows Server 2008 r2( running in VirtualBox), it returns the correct data:
```
PercentProcessorTime    Timestamp_Sys100NS
312500                  131026611105128498
```

**Comment by knight00931** [comment]
Thanks guys, I just decided upgrading to newer windows version because of this and some other issues. I don't think it's worth to deal with a old system like server 2008 (not even R2).
