### ISSUE TITLE
PM2 leaking memory

### ISSUE THREAD

**Issue by herkyl** [Unitech/pm2#1882]
In order to find why my production servers are not releasing memory I have tracked down that it is caused by PM2.

I have tested my apps running as normal node apps and then running them with pm2. I am printing GC events and see that the normal way all memory get's cleaned up after all Websocket clients disconnect. Using PM2 however the memory is not released.

I am on:
* pm2 1.0.0
* node 5.1.1
* OSX (but this also happens on Ubuntu)
* I am not in cluster mode

Has anyone else experienced this with WS?

**Comment by zeluis9** [comment]
@herkyl please update your nodejs version and try again then. I think in the newer versions the team had corrected some socket-related bugs. See here https://github.com/nodejs/node/blob/v5.4.0/CHANGELOG.md and give your feedback!

**Comment by herkyl** [comment]
@zeluis9 thanks, I will check it out and get back!

**Comment by herkyl** [comment]
Tested and it didn't help.

I don't know much about PM2 internals but why is it doing anything with the socket connections anyway? When I test my app with normal node.js I can see that GC runs right after a bunch of sockets disconnect pretty much always keeping the memory low. With PM2 I rarely see any drop in used memory and even then it is much less then it gains.

Right now I am creating 1000 connections to the server and then closing them. After closing about 50%-100% of the memory used by the connections is not released. (100% is released when running normal node).

**Comment by zeluis9** [comment]
That's strange. I'm using pm2 on a daily basis and didn't noticed any memory leak. This happens only with WS?

**Comment by soyuka** [comment]
see #1453 and related sailsjs discusssion about sockets and sessions.

You should also know that default sessions (of most frameworks) (eg express-sessions), which are memory storages by default, might leak! Especially when doing lots of requests (for example with wrk/siege/ab benchmarks).

**Comment by zeluis9** [comment]
@soyuka - @herkyl didn't mentioned sails.js here. But you're right. Memory sessions can leak.

**Comment by soyuka** [comment]
I mention sails.js because we had a long and interesting discussion when #1453 was opened. Actually the memleak came from sessions. 

I also compared (briefly) different frameworks and their memory usage (with and without pm2) to show that there is no memory leak in pm2: https://github.com/soyuka/nodejs-http-memtest. I could run those again against pm2@1.0.0 if needed ;).

**Comment by herkyl** [comment]
So weird, I did not get notifications from Github. I am using WS (https://github.com/websockets/ws). Some of the production servers are now using Upstart instead of PM2, let's see if that get's rid of the leak.

**Comment by herkyl** [comment]
I'm closing this issue for now since it seems that the leak still happens with Upstart.
