### ISSUE TITLE
babel6 and watch doesn't work

### ISSUE THREAD

**Issue by lookfirst** [Unitech/pm2#1890]
1. I got things started just fine with `babel-node` technique, but [it isn't recommended in production](https://babeljs.io/docs/usage/cli/#babel-node).
2. I got things started just fine with the `require('babel-register')` [technique](https://babeljs.io/docs/usage/require/).
3. watching is true, I change a source file (or any other file in the same directory as my app) and nothing restarts.

OSX 10.11.2 Beta (15C48a)
Node 5.4.0
pm2 1.0.0

**Comment by lookfirst** [comment]
Running things with `nodemon index.js` works just fine.

**Comment by MarufSarker** [comment]
I was just starting with pm2, and tried below configurations, and seems like working and restarts after changes, you can give it a try.

server.js
```javascript

import express from 'express';

const PORT = 3000;

let app = express();

app.get('/', (req, res) => {
  res.send('Hello World! Using pm2 :)')
});

app.listen(PORT, (err) => {
  console.log(`App running on ${PORT}`)
})
```

index.js
```javascript
require('babel-register');
require('./server.js')
```

.babelrc
```javascript
{
  "presets": ["es2015", "stage-0"]
}
```

ecosystem.json
```javascript
{
  "apps": [{
    "name": "App1",
    "script": "index.js",
    "watch": true,
  }]
}

```

packages
```javascript
"babel-preset-es2015": "^6.3.13",
"babel-preset-stage-0": "^6.3.13",
"babel-register": "^6.4.3",
"express": "^4.13.3"
```

one thing about ```.babelrc``` is that, without ```.babelrc``` the ```pm2``` starts the ```App1``` but the ```pid``` keeps changing, and nothing is served into the browser, rather the ```http://localhost:3000/``` stays ```offline```, and ```.beblrc``` solves that issue.


Additional infos:
```
node --version
v5.3.0

babel --version
6.4.0 (babel-core 6.4.0)

babel-node --version
6.4.0

pm2 --version
1.0.0

OS
Windows 10
```

**Comment by lookfirst** [comment]
I suspect that since you're on Windows, that is the big difference.

**Comment by timnew** [comment]
I met similar issue:

I looks like `babel-register` require hook doesn't work at all.

```
tickets-server-0 /home/suoper/node/tickets/source/apps/startApp.js:18
tickets-server-0   const port = parseInt(val, 10);
tickets-server-0
tickets-server-0
tickets-server-0 ^
tickets-server-0 ^
tickets-server-0 ^
tickets-server-0 ^
tickets-server-0 ^
tickets-server-0 SyntaxError: Use of const in strict mode.
tickets-server-0     at Module._compile (module.js:439:25)
tickets-server-0     at loader (/home/suoper/node/tickets/source/node_modules/babel-register/lib/node.js:126:5)
tickets-server-0     at Object.require.extensions.(anonymous function) [as .js] (/home/suoper/node/tickets/source/node_modules/babel-register/lib/node.js:136:7)
tickets-server-0     at Module.load (module.js:356:32)
tickets-server-0     at Function.Module._load (module.js:312:12)
tickets-server-0     at Function._load (/usr/local/node-v5.7.1-linux-x64/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
tickets-server-0     at Module.require (module.js:364:17)
tickets-server-0     at require (module.js:380:17)
tickets-server-0     at Object.<anonymous> (/home/suoper/node/tickets/source/bin/server:5:1)
tickets-server-0     at Module._compile (module.js:456:26)
tickets-server-0     at Object.Module._extensions..js (module.js:474:10)
tickets-server-0     at Module.load (module.js:356:32)
tickets-server-0     at Function.Module._load (module.js:312:12)
tickets-server-0     at Function._load (/usr/local/node-v5.7.1-linux-x64/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
tickets-server-0     at Object.<anonymous> (/usr/local/node-v5.7.1-linux-x64/lib/node_modules/pm2/lib/ProcessContainerFork.js:41:21)
tickets-server-0     at Module._compile (module.js:456:26)
tickets-server-0     at Object.Module._extensions..js (module.js:474:10)
tickets-server-0     at Module.load (module.js:356:32)
tickets-server-0     at Function.Module._load (module.js:312:12)
tickets-server-0     at Function.Module.runMain (module.js:497:10)
tickets-server-0     at startup (node.js:119:16)
tickets-server-0     at node.js:935:3
```

I'm sure that I have executed `require('babel-register')` before previous code got executed.

And I also ensure that babel works. I added `DEBUG=*` to pm2 env, and I did see babel compilation process. But require hook failed due to some unknown issue.

**Comment by timnew** [comment]
Issue got fixed after I downgrade PM2 to `0.15.10`

**Comment by soyuka** [comment]
Sure you've the strict mode enabled? I don't see any issues on my hand.

**Comment by soyuka** [comment]
Following up in #2005

**Comment by lookfirst** [comment]
@soyuka Why was this closed? This issue revolves around pm2 not watching files for changes, not around making babel-require work.

**Comment by soyuka** [comment]
@lookfirst because this has to be babel-related, if watching works without babel no ?

Anyway, babel won't interfere with how the watch process works and restarts, or maybe processes are not killed properly because of babel.

I'll try again tonight using babel+pm2+`--watch` on my osx. Could you provide a script that reproduces the issue? 

Thanks.

**Comment by lookfirst** [comment]
Sure, something with the combination of babel might be causing watching to fail, but that is a separate issue from what the other people commenting here are talking about. Thanks for re-opening.

I'll try to work on an example project for you, but it may take some time. Slammed with work right now. =(

**Comment by soyuka** [comment]
@lookfirst ok, so what doesn't work for you is pm2 + babel + watch right? I'm doing a test-case asap.

**Comment by lookfirst** [comment]
Yup!

**Comment by vmarchaud** [comment]
See #2629 we group all issue into one.
