### ISSUE TITLE
PM2 SIGINT

### ISSUE THREAD

**Issue by misha-plus** [Unitech/pm2#1894]
PM2 don't send `SIGINT` on `pm2 stop` for me, only `SIGKILL`.

**Comment by misha-plus** [comment]
It seems that this happens in v1.0.0, in 0.15.9 everything was fine.

**Comment by Unitech** [comment]
Everything work as expected on 1.0.0

Please double check the documentation about signals: http://pm2.keymetrics.io/docs/usage/signals-clean-restart/

Test #1: https://github.com/Unitech/pm2/blob/ba95a803877de19d56d54116d00db46aef532b7f/test/programmatic/signals.js

Test #2: https://github.com/Unitech/pm2/blob/master/test/bash/signal.sh
