### ISSUE TITLE
question/feature: get the app id of an app by name from command line

### ISSUE THREAD

**Issue by jcollum** [Unitech/pm2#1895]
Say I have an app named "fizzbuzz". I start it with `pm2 start index.js --name="fizzbuzz" --watch`. For automation purposes I'd like to just get the id of the app. I can grep it I guess but it seems like something that PM2 would have out of the box. I can't find it in the docs. For instance, I'd like to do this: 

    $ pm2 id --name="fizzbuzz"
    3

Will I have to use grep and string manipulation in bash to accomplish this? 

Also on [SO](http://stackoverflow.com/questions/34829550/how-do-i-get-just-the-app-id-with-pm2) if anyone has an answer.

**Comment by soyuka** [comment]
With `jq` for example:

```
pm2 jlist | jq '.[] | select(.name == "server").pm_id'
```

Le sam. 16 janv. 2016 à 21:01, Justin Collum <notifications@github.com> a
écrit :

**Comment by jcollum** [comment]
What is `jq`?

**Comment by soyuka** [comment]
This nice thing : https://stedolan.github.io/jq/

Actually it can easily be implemented in pm2

Le sam. 16 janv. 2016 à 22:40, Justin Collum <notifications@github.com> a
écrit :

**Comment by jcollum** [comment]
Looks like you can do this with just grep and mini-list: 

I solved this with node and grep. I am using the app name from package.json when I start the apps up. If I am in the root dir of the app, I can get that from package.json: 

    packageName=`node -e "console.log((require('./package.json')).name)"`

The I use pm2's mini-list feature, which outputs: 

    +--- alpha-beta-gamma 
    pid : 4327
    pm2 id : 2
    status : online 

Then I can grep it: 
    
    pm2 -m ls | grep "\-\- $packageName" -A 3 | grep "pm2 id" | grep -oP '\d+$'

Which returns: 

    2 

A feature for this would be nifty though.

**Comment by soyuka** [comment]
Done on the development branch

**Comment by jcollum** [comment]
Wow, thanks @soyuka

**Comment by soyuka** [comment]
You can use it by installing the development branch directly.
