### ISSUE TITLE
jxcore support ?

### ISSUE THREAD

**Issue by giulianoz** [Unitech/pm2#1899]
Hi,
I'm trying to use pm2 to run a jx compiled application. Is this supported ? I have found nothing around...
thanks

g

**Comment by soyuka** [comment]
Hi it should be compatible, at least with fork mode. You might have to change the exec_interpreter or try to run pm2 from jx to make the cluster work.

**Comment by giulianoz** [comment]
Thanks, setting the exec_interpreter  to /usr/local/bin/jx worked like a charm :)
