### ISSUE TITLE
pm2 startup add support for Debian

### ISSUE THREAD

**Issue by pensierinmusica** [Unitech/pm2#1905]
Hi,

Can you please add support for Debian to the `pm2 startup` script?

Thanks!

   Alex

**Comment by soyuka** [comment]
It's already available: http://pm2.keymetrics.io/docs/usage/startup/

use `ubuntu` if you use updaterc.d

**Comment by pensierinmusica** [comment]
If I understand correctly, you're saying that `pm2 startup ubuntu` will work perfectly fine under Debian. If this is right, could we add this piece of information to the docs? Thanks! Cheers
