### ISSUE TITLE
how to integrate pm2 with monitoring tool like nagios?

### ISSUE THREAD

**Issue by PLEEROCK** [Unitech/pm2#1913]
I would like to monitor my multiple servers not via cli, but via separate monitoring tool, like nagios. Is there a way to do it?

**Comment by soyuka** [comment]
You can develop plugins for nagios which uses the pm2 programmatic api or by parsing pm2 json output ([like this](https://github.com/poymode/pm2_nagios)).

**Comment by PLEEROCK** [comment]
is there a docs related to what pm2 outputs in json and how to access this data?

**Comment by soyuka** [comment]
http://pm2.keymetrics.io/docs/usage/pm2-api/

**Comment by hobbyquaker** [comment]
I made a trivially simple Nagios/Icinga Plugin for this purpose: https://github.com/hobbyquaker/check_pm2
