### ISSUE TITLE
Any way to read log files as they come?

### ISSUE THREAD

**Issue by McFarts** [Unitech/pm2#1914]
For example, I set my conf.json file to output the error_file and out_file to my main directory.

I see that the log files get filled up, but is there another module related to pm2 where I can have running to see the log files as they come in? This way, I don't have to keep re-opening the files :P

**Comment by soyuka** [comment]
`pm2 logs`

**Comment by McFarts** [comment]
Wow, I'm a idiot

Thanks @soyuka
