### ISSUE TITLE
PM2 Crash allocation failure

### ISSUE THREAD

**Issue by mauron85** [Unitech/pm2#1915]
After very long and reliable duty (almost year), today pm2 crashed itself twice.

pm2 1.0.0
node v4.2.4
free -h reports that server has 1GB of free memory. 

from pm2.log
```
FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory

<--- Last few GCs --->

11077620 ms: Scavenge 17.8 (54.9) -> 16.8 (54.9) MB, 5.8 / 0 ms [allocation failure].
11107284 ms: Scavenge 17.8 (54.9) -> 17.0 (54.9) MB, 1.1 / 0 ms [allocation failure].
11137818 ms: Scavenge 17.9 (54.9) -> 17.0 (54.9) MB, 13.0 / 0 ms [allocation failure].
11197344 ms: Scavenge 17.9 (54.9) -> 17.0 (54.9) MB, 602.4 / 2 ms [allocation failure].
11360431 ms: Scavenge 18.0 (54.9) -> 17.1 (54.9) MB, 1218.8 / 0 ms [allocation failure].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2aa6137b4629 <JS Object>
    1: safeDeepClone(aka safeDeepClone) [/usr/lib/node_modules/pm2/lib/tools/safeclonedeep.js:53] [pc=0x1697ae06b47] (this=0x2aa6137041b9 <undefined>,circularValue=0x2aa6137041b9 <undefined>,refs=0x103f0c0b81f1 <JS Array[2]>,obj=0x3cccfce76c09 <a ChildProcess with map 0x3440658a0d59>)
    2: safeDeepClone(aka safeDeepClone) [/usr/lib/node_modules/pm2/lib/tools/safeclonedeep.js:53] [pc=0x1697ae0..
```

**Comment by estliberitas** [comment]
Maybe more log available? Full JS Stack trace is most interesting thing.

**Comment by mauron85** [comment]
Thats' all from pm2.log. Nothing more

**Comment by estliberitas** [comment]
@mauron85 Well, there are many places where `safedeepclone.js` is used.

/cc @Unitech @soyuka

**Comment by soyuka** [comment]
indeed and a lot of aliases too

**Comment by estliberitas** [comment]
@mauron85 Any data like graphs of memory usage by certain processes (PM2 or all on the host) through the year?

**Comment by mauron85** [comment]
@estliberitas I'am ashamed but none :-). That's our dev server. I though I've found lead, but it turned out to be false positive. I've configured (by mistake) pm2 to store pids into /var/run/somedir dir, which worked until restart. Then pm2 start filling logs about unable to put pids to that dir and then crashed. I've reconfigured pm2 to store pids into it's own dir, but after couple of hours it crashed again with same error. So it was not related.

**Comment by mauron85** [comment]
It crashed once again. The crash dump is trimmed. Maybe I can raise limit by ulimit -c, but I'm not sure how to use it.

Anyway I also installed pm2-server-monit and start logging into keymetrics. I'm curious.

**Comment by estliberitas** [comment]
@mauron85 Uhm, interesting. Isn't it somehow connected with cluster mode? What is Node.js version?

**Comment by mauron85** [comment]
@estliberitas All apps are in fork mode (this is just dev server). And node is v4.2.6. But the more I think about it, the more I think that it's not probably pm2 related thing.

But even it's server related, the strange thing is that pm2 completely forget it's configuration and I have to configure it with pm2 start pm2.json

**Comment by estliberitas** [comment]
> the strange thing is that pm2 completely forget it's configuration and I have to configure it with pm2 start pm2.json

@mauron85 more details plz

**Comment by mauron85** [comment]
after crash when I exec pm2 list. The list of apps is empty. So I have to start them all again with pm2 start

**Comment by estliberitas** [comment]
@mauron85 Even after `pm2 dump`?

**Comment by estliberitas** [comment]
Typical case would be:

1. `$ pm2 start ...`
2. `$ pm2 dump`
3. PM2 dies
4. `$ pm2 resurrect`

**Comment by mauron85** [comment]
Will try next time it crashes. But what is the actual diferrence? I mean it doesn't matter if I have to pm2 resurrect or pm2 start. My conf is already in json, that I created manually.

**Comment by estliberitas** [comment]
You're correct. The only difference is once it dies you can call one command and that's all. Also, when you do `pm2 list` if I'm correct PM2 is just spawned (if not already) without `resurrect` action. Btw would be cool to auto-resurrect.

Let guys correct me if I'm wrong:
/cc @Unitech @soyuka

**Comment by mauron85** [comment]
+1 for auto-resurrect. It would make a difference. ;-)

**Comment by mauron85** [comment]
@estliberitas It just happened again . However I don't have access to logs in free acount. Do you?
https://app.keymetrics.io/#/bucket/56a3eda17340c1a186aa5f9a/dashboard

```
016-03-01 23:39:58: App name:pm2-server-monit id:0 online

<--- Last few GCs --->

1164486245 ms: Scavenge 12.7 (52.9) -> 11.9 (52.9) MB, 1036.2 / 1 ms [allocation failure].
1164495996 ms: Scavenge 12.8 (52.9) -> 12.0 (52.9) MB, 405.3 / 0 ms [allocation failure].
1164508584 ms: Scavenge 12.8 (52.9) -> 12.0 (52.9) MB, 1820.5 / 0 ms [allocation failure].
1164525690 ms: Scavenge 12.9 (52.9) -> 12.1 (52.9) MB, 18.0 / 0 ms [allocation failure].
1164594147 ms: Scavenge 13.3 (52.9) -> 12.4 (52.9) MB, 2436.6 / 394 ms (+ 6348.9 ms in 11 steps since last GC) [allocation failure].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x214942db4629 <JS Object>
    1: safeDeepClone(aka safeDeepClone) [/usr/lib/node_modules/pm2/lib/tools/safeclonedeep.js:48] [pc=0x266254f80336] (this=0x214942d041b9 <undefined>,circularValue=0x214942d041b9 <undefined>,refs=0x2757610d02c1 <JS Array[3]>,obj=0xd513ade60c1 <a Socket with map 0x226d2c5a6711>)
    2: safeDeepClone(aka safeDeepClone) [/usr/lib/node_modules/pm2/lib/tools/safeclonedeep.js:53] [pc=0x266254f80578]...
FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory
```

**Comment by mauron85** [comment]
It crashed again. This time systat confirmed that pm2 crashes due out of memory. Here is correlation of pm2.log crash log entry and ```sar -u``` output.

The ***interesting*** thing here is that memory consumption start to rise exactly at midnight, which is time when pm2 is scheduled to restart services (option cron_restart": "1 0 * * *")

pm2.log
```
2016-03-05 01:50:43: App name:pm2-server-monit id:0 online

<--- Last few GCs --->

98837666 ms: Scavenge 15.5 (51.9) -> 14.6 (51.9) MB, 41.3 / 0 ms [allocation failure].
98839131 ms: Scavenge 15.4 (51.9) -> 14.6 (51.9) MB, 207.3 / 0 ms [allocation failure].
98843277 ms: Scavenge 15.5 (51.9) -> 14.6 (51.9) MB, 5.5 / 0 ms [allocation failure].
98845923 ms: Scavenge 15.5 (51.9) -> 14.7 (51.9) MB, 1.9 / 0 ms [allocation failure].
98857939 ms: Scavenge 15.6 (51.9) -> 14.7 (51.9) MB, 1600.0 / 7 ms [allocation failure].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3736a16b4629 <JS Object>
    2: safeDeepClone(aka safeDeepClone) [/usr/lib/node_modules/pm2/lib/tools/safeclonedeep.js:53] [pc=0x2440e580c67] (this=0x3736a16041b9 <undefined>,circularValue=0x3736a16041b9 <undefined>,refs=0x2c69700dbb41 <JS Array[4]>,obj=0x35def99d4559 <an Object with map 0x6e0207b30d9>)
    3: safeDeepClone(aka safeDeepClone) [/usr/lib/node_modules/pm2/lib/tools/safeclonedeep.js:53] [pc=0x2440e580c58] ...
FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory
```


sar -r
```
12:00:01 AM kbmemfree kbmemused  %memused kbbuffers  kbcached  kbcommit   %commit  kbactive   kbinact   kbdirty
11:55:01 PM   1049100    667692     38.89     96356    306776    427312     24.89    404476    142652         8
11:59:01 PM   1047492    669300     38.99     96376    306804    424980     24.75    405888    142652         8
12:00:01 AM   1048812    667980     38.91     96376    306808    426724     24.86    404660    142652         8
12:05:02 AM    316412   1400380     81.57    111112    600172   1245716     72.56   1029184    210044        24
12:15:01 AM    222972   1493820     87.01    111112    600332   1318968     76.83   1122684    210044        20
12:25:01 AM    161864   1554928     90.57    111112    600480   1403392     81.75   1183632    210044        32
12:35:01 AM    114560   1602232     93.33    110768    563236   1473716     85.84   1169672    271260        16
12:45:01 AM    146716   1570076     91.45    108344    423920   1578836     91.96   1144232    265648        20
12:55:01 AM    101500   1615292     94.09     84156    403772   1688544     98.35   1225116    230120        12
01:05:01 AM    129432   1587360     92.46     40552    296292   1756992    102.34   1263124    167956        56
01:15:01 AM    116580   1600212     93.21     34504    255644   1867204    108.76   1306024    139236        72
01:25:01 AM    123952   1592840     92.78     22276    135596   1967508    114.60   1373384     77876        48
01:35:01 AM    114312   1602480     93.34      8760     79964   2066776    120.39   1434340     42304        60
01:45:01 AM    100724   1616068     94.13      1048     62868   2161336    125.89   1483480     24932        52
01:56:04 AM     90688   1626104     94.72       172      9100   2139948    124.65   1516096      4796         4
02:05:02 AM   1400552    316240     18.42      5312     77632    422240     24.59    170784     50772        68
```

**Comment by balboliu** [comment]
I have same problem.

**Comment by barakedry** [comment]
I also have the same problem

**Comment by Dreanmer** [comment]
same problem here

```
PM2: 2016-06-14 03:39:00: [PM2][WORKER] Error caught by domain:
PM2: Error: spawn ENOMEM
PM2:     at exports._errnoException (util.js:1007:11)
PM2:     at ChildProcess.spawn (internal/child_process.js:302:11)
PM2:     at exports.spawn (child_process.js:383:9)
PM2:     at Object.exports.execFile (child_process.js:139:15)
PM2:     at exports.exec (child_process.js:99:18)
PM2:     at getUrl (/usr/lib/node_modules/pm2/node_modules/vizion/lib/git.js:18:5)
PM2:     at fn (/usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:641:34)
PM2:     at Immediate._onImmediate (/usr/lib/node_modules/pm2/node_modules/vizion/node_modules/async/lib/async.js:557:34)
PM2:     at tryOnImmediate (timers.js:543:15)
PM2:     at processImmediate [as _immediateCallback] (timers.js:523:5)
PM2: 
PM2: <--- Last few GCs --->
PM2: 
PM2: 50319371 ms: Scavenge 16.4 (54.0) -> 15.6 (54.0) MB, 1.0 / 0 ms [allocation failure].
PM2: 50349379 ms: Scavenge 16.5 (54.0) -> 15.8 (55.0) MB, 1.0 / 0 ms [allocation failure].
PM2: 50379922 ms: Scavenge 16.6 (55.0) -> 15.9 (55.0) MB, 0.9 / 0 ms [allocation failure].
PM2: 50434611 ms: Scavenge 16.8 (55.0) -> 16.0 (55.0) MB, 0.9 / 0 ms [allocation failure].
PM2: 50469520 ms: Scavenge 16.9 (55.0) -> 16.2 (55.0) MB, 38.9 / 0 ms [allocation failure].
PM2: 
PM2: 
PM2: <--- JS stacktrace --->
PM2: 
PM2: ==== JS stack trace =========================================
PM2: 
PM2: Security context: 0x406e9cc9e59 <JS Object>
PM2:     1: safeDeepClone(aka safeDeepClone) [/usr/lib/node_modules/pm2/lib/tools/safeclonedeep.js:48] [pc=0x3e4eca69e272] (this=0x406e9c04189 <undefined>,circularValue=0x406e9c04189 <undefined>,refs=0xc84310dde71 <JS Array[5]>,obj=0x1e7ed14efd89 <a Domain with map 0x2bf30f23f301>)
PM2:     2: safeDeepClone(aka safeDeepClone) [/usr/lib/node_modules/pm2/lib/tools/safeclonedeep.js:52] [pc=0x3e4eca69e467] (t...
PM2: FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory
```

**Comment by Dreanmer** [comment]
i think my problem was => express session + file drive + static files + aws health check + chmod 750 on sessions folder

**Comment by gustavobello** [comment]
Same problem here. Any progress on this issue?

**Comment by Unitech** [comment]
PM2 cannot add RAM to your server.

At least you can install that PM2 (v2.0) to reduce PM2 memory usage:

```
$ npm install Unitech/pm2#development -g
$ pm2 update
```

**Comment by gustavobello** [comment]
@Unitech if you close this issue. You should updated the product description:
**"...It allows you to keep applications alive forever..."** unless it runs out of memory and crash.

**Comment by soyuka** [comment]
@gustavobello please follow https://github.com/Unitech/pm2/issues/1314 

You'll see that we're working hard to try to reproduce any memory leak issue that has been reported. Thing is, we need ways to reproduce the reported memory leak. If you have any way to reproduce your issue, please let us know how to reproduce it by using pm2 and we'll do our best to fix it. Giving things like "...It allows you to keep applications alive forever... unless it runs out of memory and crash." does not help in any way ;).

**Comment by gustavobello** [comment]
@soyuka Thank you for the answer, but I don't think #1314 is related to this issue. Either way, I will give version 2.0 a try. My last, and not so helpful, comment is related only to the act of closing a issue when it is not fixed.

**Comment by soyuka** [comment]
The  referenced `safedeepclone.js` mentioned above has been refactored in v2 and does help with memory and cpu issues we've seen in all of your issues. If any of you still have an issue by trying with pm2@v2, please let us know and this will be reopened.

**Comment by josser** [comment]
Hi! I've got same error with pm2 2.2.3
Here is what I have in pm2.log: https://gist.github.com/josser/dcf886f25568ce913751ffd1056a27e7

Maybe this can help
Thank you!

**Comment by soyuka** [comment]
What is `/data/home/ccccccc/src/cppt/task_worker.js`?

**Comment by josser** [comment]
@soyuka this is part of our code and here I'm not sure why we see it in ~/.pm2/pm2.log
I thought pm2.log is log for pm2 and application logs should be somewhere in logs folder.

**Comment by vmarchaud** [comment]
@josser PM2 tried to spawn the application and failed cause it ran out of memory, so that's normal this crash is inside the pm2 logs.

**Comment by josser** [comment]
@vmarchaud but why pm2 itself died?

**Comment by soyuka** [comment]
@josser Because there was no memory left IMHO

**Comment by juliocanares** [comment]
same problem here

this is in my pm2.log

```
2017-02-22 15:51:06: Starting execution sequence in -cluster mode- for app name:riqra-app id:38
2017-02-22 15:51:06: App name:riqra-app id:38 online
2017-02-22 15:51:06: Starting execution sequence in -cluster mode- for app name:riqra-app id:39
2017-02-22 15:51:06: App name:riqra-app id:39 online

<--- Last few GCs --->

3130008328 ms: Scavenge 17.2 (53.9) -> 16.3 (53.9) MB, 3.7 / 0 ms [allocation failure].
3130010372 ms: Scavenge 17.3 (53.9) -> 16.3 (53.9) MB, 4.5 / 0 ms [allocation failure].
3130012475 ms: Scavenge 17.3 (53.9) -> 16.3 (53.9) MB, 7.5 / 0 ms [allocation failure].
3130015909 ms: Scavenge 17.3 (53.9) -> 16.3 (53.9) MB, 11.1 / 0 ms [allocation failure].
3130017772 ms: Scavenge 17.3 (53.9) -> 16.4 (53.9) MB, 10.4 / 0 ms [allocation failure].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0xde2130b4629 <JS Object>
    1: safeDeepClone(aka safeDeepClone) [/usr/lib/node_modules/pm2/lib/tools/safeclonedeep.js:52] [pc=0x36f839bdd992] (this=0xde2130041b9 <undefined>,circularValue=0xde2130041b9 <undefined>,refs=0x3ae0c60f7031 <JS Array[3]>,obj=0x5cdb346af21 <a Socket with map 0x235db75a1dd9>)
    2: safeDeepClone(aka safeDeepClone) [/usr/lib/node_modules/pm2/lib/tools/safeclonedeep.js:52] [pc=0x36f839bdd983] (t...
FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory

2017-02-22 15:53:27: [PM2][WORKER] Started with refreshing interval: 30000
2017-02-22 15:53:27: [[[[ PM2/God daemon launched ]]]]
2017-02-22 15:53:28: BUS system [READY] on port /home/deploy/.pm2/pub.sock
2017-02-22 15:53:28: RPC interface [READY] on port /home/deploy/.pm2/rpc.sock
2017-02-22 15:53:30: Starting execution sequence in -fork mode- for app name:riqra-mailer id:0
2017-02-22 15:53:30: App name:riqra-mailer id:0 online
2017-02-22 15:57:15: Starting execution sequence in -cluster mode- for app name:riqra-app id:1
2017-02-22 15:57:15: App name:riqra-app id:1 online
2017-02-22 15:57:15: Starting execution sequence in -cluster mode- for app name:riqra-app id:2
2017-02-22 15:57:15: App name:riqra-app id:2 online
```

**Comment by malipraful** [comment]
Same problem here 

/root/.pm2/logs/index-error-0.log last 10 lines:
0|index    |     at createBuffer (buffer.js:68:17)
0|index    |     at allocate (buffer.js:216:12)
0|index    |     at Function.Buffer.allocUnsafe (buffer.js:176:10)
0|index    |     at new Buffer (buffer.js:110:19)
0|index    |     at Object.<anonymous> 
0|index    |     at Module._compile (module.js:541:32)
0|index    |     at Object.Module._extensions..js (module.js:550:10)
0|index    |     at Module.load (module.js:456:32)
0|index    |     at tryModuleLoad (module.js:415:12)
0|index    | FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory

**Comment by malipraful** [comment]
How to solve this problem

**Comment by Unitech** [comment]
Buy ram or use keymetrics with pm2-server-monit to know when there is not enough memory remaining on your server

**Comment by praful-lallabi** [comment]
Still Now this problem is there.
.pm2/logs/index-error-0.log last 15 lines:
0|index    |     at Module._compile (module.js:541:32)
0|index    |     at Object.Module._extensions..js (module.js:550:10)
0|index    |     at Module.load (module.js:456:32)
0|index    |     at tryModuleLoad (module.js:415:12)
0|index    | RangeError: Array buffer allocation failed
0|index    |     at new Uint8Array (native)
0|index    |     at createBuffer (buffer.js:68:17)
0|index    |     at allocate (buffer.js:216:12)
0|index    |     at Function.Buffer.allocUnsafe (buffer.js:176:10)
0|index    |     at new Buffer (buffer.js:110:19)
0|index    |     at Object.<anonymous> 
0|index    |     at Module._compile (module.js:541:32)
0|index    |     at Object.Module._extensions..js (module.js:550:10)
0|index    |     at Module.load (module.js:456:32)
0|index    |     at tryModuleLoad (module.js:415:12)

/root/.pm2/logs/index-out-0.log last 15 lines:
0|index    |      785 ms: Scavenge 13.9 (47.9) -> 12.3 (48.9) MB, 5.5 / 0 ms [allocation failure].
0|index    |      882 ms: Scavenge 16.5 (49.9) -> 15.3 (50.9) MB, 6.0 / 0 ms [allocation failure].
0|index    |
0|index    |
0|index    | <--- JS stacktrace --->
0|index    |
0|index    | ==== JS stack trace =========================================
0|index    |
0|index    | Security context: 0xcbacdac0dc1 <JS Object>
0|index    |     2: /* anonymous */(aka /* anonymous */) [vm.js:53] [pc=0x3cc4b604eb91] (this=0xcbacda04189 <undefined>,code=0x180eb7285051 <Very long string[20740]>,options=0x180eb7285079 <an Object with map 0x5ac08a10021>)
0|index    |     3: _compile [module.js:511] [pc=0x3cc4b604e351] (this=0x180eb727eeb1 <a Module with map 0x252937422ef9>,content=0x180eb727ff49 <Very long string[20674]>,filename=0x180eb727ee79 <Stri...

**Comment by mikiyasET** [comment]
Is anyone else having this issue in 2024 I'm facing the same thing, once the users using my app exceed 700 it crashes and clears the log too.

Pm2  version 5.3.0
