### ISSUE TITLE
Exit in --no-daemon mode when all apps are stopped/errored/removed

### ISSUE THREAD

**Issue by aPoCoMiLogin** [Unitech/pm2#1916]
When PM2 is used in docker container, to easy clustering app, would be more docker way, when PM2 simple exit with non zero code, when all apps are stopped/errored/removed. Now if I login to the container, and even remove all apps, PM2 is still working. This is bad behavior, because only logs can tell you if something went wrong.

**Comment by bobelev** [comment]
+1

**Comment by gajus** [comment]
Is there any workaround?

**Comment by aPoCoMiLogin** [comment]
My workaround was just to not use PM2 for docker containers anymore. You still need any kind of proxy if you are scaling your app horizontally. So instead of PM2, how you can easily cluster your app with docker ? In most of my applications im using https://github.com/docker/dockercloud-haproxy which  is easy to use. With latest changes to docker swarm, they did use linux kernel ipvs built in load balancer, which I didn't tested yet, but I'm very exited about that one.

**Comment by Unitech** [comment]
feature will be added to pm2 v2 via pm2-docker command https://github.com/Unitech/pm2/blob/development/bin/pm2-docker

**Comment by gajus** [comment]
Interesting. Is there any release timeline? Is there a beta release?

**Comment by Unitech** [comment]
[Feature added](https://github.com/Unitech/pm2/commit/db976cc67fb15ae284a2878808440675bf8423fa) on new pm2-docker command

@gajus yes you can try it like that:

```bash
$ npm install Unitech/pm2#development -g
$ pm2-docker start <app|json> --auto-exit
```

**Comment by gajus** [comment]
Reading the code, it appears that this will exit `pm2-docker` program only if 0 apps are running. How to handle a case when either of the programs have reached maximum restart limit?

**Comment by Unitech** [comment]
Nope, it exits if 0 application is managed or if 0 application is online or
launching

Once max restart is reached, it will stop the app

On Saturday, July 2, 2016, Gajus Kuizinas <notifications@github.com> wrote:

> Reading the code, it appears that this will exit pm2-docker program only
> if 0 apps are running. How to handle a case when either of the programs
> have reached maximum restart limit?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Unitech/pm2/issues/1916#issuecomment-230099919>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAuP8xRtFox8KrhvglW1QOJC5Y1VWlc7ks5qRlxUgaJpZM4HK6d7>
> .
>


-- 
Alexandre Strzelewicz
(+33) 7.83.88.11.43
