### ISSUE TITLE
PM2 not Logging binary executable file in Raspberry Pi!

### ISSUE THREAD

**Issue by bhaveshgohel** [Unitech/pm2#1919]
Hello,
I'm facing weird issue with PM2, when i run my c binary executable via pm2. It's some times logs it's output and some times dont. :/

Here is my josn file: 

``` javscript
{
  "apps" : [{
  "name"             : "main",
  "cwd"              : "/release/hardware",
  "script"           : "/release/hardware/main",
  "log_date_format"  : "DD-MM-YYYY HH:mm:ss.SSS",
  "error_file"       : "/release/logs/main-err.log",
  "out_file"         : "/release/logs/main-out.log",
  "pid_file"         : "/release/logs/main-pid.log",
  "instances"        : 1,
  "max_restarts"     : 30,
  "exec_mode"        : "fork",
  "exec_interpreter" : "none"
}]
}
```

PM2 : 1.0.0
Nodejs: v4.2.4
OS: DietPi v105
Hardware: Raspberry Pi 1 B+ 512MB

Same thing working fine for my nodejs file. Please Help.

Thanks.
-Bhavesh Gohel

**Comment by estliberitas** [comment]
@bhaveshgohel Are you sure it's pm2 issue? What are the results, if you run your binary using forever / nodemon or maybe supervisord?

Does user which runs excutable (=pm2) has rights to write to specified directory and log file?

**Comment by bhaveshgohel** [comment]
@estliberitas : Yes PM2 has rights to write to specified directory and log file. 
I have tried running with forever but i guess it may have issue running this kind of binary file, i'm waiting for a reply from them [https://github.com/foreverjs/forever/issues/800]. but forever still able log process failed log on the same directory.

In my case PM2 just have issue with logging, It can run the process smoothly.

**Comment by estliberitas** [comment]
@bhaveshgohel, "process failed log" === `stderr` or any kind of logs?

On Wed, Jan 27, 2016, 09:19 Bhavesh Gohel <notifications@github.com> wrote:

> @estliberitas <https://github.com/estliberitas> : Yes PM2 has rights to
> write to specified directory and log file.
> I have tried running with forever but i guess it may have issue running
> this kind of binary file, i'm waiting for a reply from them [
> foreverjs/forever#800 <https://github.com/foreverjs/forever/issues/800>].
> but forever still able log process failed log on the same directory.
>
> In my case PM2 just have issue with logging, It can run the process
> smoothly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Unitech/pm2/issues/1919#issuecomment-175424440>.
>
-- 
Sincerely,
Alexander Makarenko

**Comment by bhaveshgohel** [comment]
After Running process with forever, it was restarting constantly as it can not start, so stderr of my process was logging in err.log . 

Just to clarify again, in PM2 the process was able to start and log both stout and stderr of process, but logging is flaky, it logs sometime and some time don't. mostly don't log.
One more thing. I tested a dummy c code on my windows machine to re-evaluate:
Test C code:
```c
int main(int argc, char const *argv[])
{
    printf("Hello World\n");
    return 0;
}
```
And compiled with gcc and run it with PM2. it was logging output in windows!!
But, the above same test code was not logging on Raspberry Pi!!?

**Comment by estliberitas** [comment]
Maybe that's some kind of race between exit of child process and detaching
of it's streams...

/cc @soyuka @Unitech

On Wed, Jan 27, 2016, 14:57 Bhavesh Gohel <notifications@github.com> wrote:

> After Running process with forever, it was restarting constantly as it can
> not start, so stderr of my process was logging in err.log .
>
> Just to clarify again, in PM2 the process was able to start and log both
> stout and stderr of process, but logging is flaky, it logs sometime and
> some time don't. mostly don't log.
> One more thing. I tested a dummy c code on my windows machine to
> re-evaluate:
> Test C code:
>
> int main(int argc, char const *argv[])
> {
>     printf("Hello World\n");
>     return 0;
> }
>
> And compiled with gcc and run it with PM2. it was logging output in
> windows!!
> But, the above same test code was not logging on Raspberry Pi!!?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Unitech/pm2/issues/1919#issuecomment-175582476>.
>
-- 
Sincerely,
Alexander Makarenko

**Comment by soyuka** [comment]
Works fine on debian:

```

14:05:09 PM2 App name:myprogram id:0 online
14:05:09 PM2 App [myprogram] with id [0] and pid [3451], exited with code [0] via signal [null]
14:05:09 myprogram-0 Hello World
2016-01-27 14:05:09: Starting execution sequence in -fork mode- for app name:myprogram id:0
14:05:09 PM2 Starting execution sequence in -fork mode- for app name:myprogram id:0
2016-01-27 14:05:09: App name:myprogram id:0 online
2016-01-27 14:05:09: App [myprogram] with id [0] and pid [3452], exited with code [0] via signal [null]
14:05:09 PM2 App name:myprogram id:0 online
14:05:09 PM2 App [myprogram] with id [0] and pid [3452], exited with code [0] via signal [null]
2016-01-27 14:05:09: Starting execution sequence in -fork mode- for app name:myprogram id:0
14:05:09 myprogram-0 Hello World
14:05:09 PM2 Starting execution sequence in -fork mode- for app name:myprogram id:0
2016-01-27 14:05:09: App name:myprogram id:0 online
2016-01-27 14:05:09: App [myprogram] with id [0] and pid [3453], exited with code [0] via signal [null]
14:05:09 PM2 App name:myprogram id:0 online
14:05:09 PM2 App [myprogram] with id [0] and pid [3453], exited with code [0] via signal [null]
2016-01-27 14:05:09: Starting execution sequence in -fork mode- for app name:myprogram id:0
14:05:09 myprogram-0 Hello World
14:05:09 PM2 Starting execution sequence in -fork mode- for app name:myprogram id:0
2016-01-27 14:05:09: App name:myprogram id:0 online
2016-01-27 14:05:09: App [myprogram] with id [0] and pid [3454], exited with code [0] via signal [null]
14:05:09 PM2 App name:myprogram id:0 online
14:05:09 PM2 App [myprogram] with id [0] and pid [3454], exited with code [0] via signal [null]
2016-01-27 14:05:09: Starting execution sequence in -fork mode- for app name:myprogram id:0
14:05:09 myprogram-0 Hello World
14:05:09 PM2 Starting execution sequence in -fork mode- for app name:myprogram id:0
2016-01-27 14:05:09: App name:myprogram id:0 online
2016-01-27 14:05:09: App [myprogram] with id [0] and pid [3455], exited with code [0] via signal [null]
14:05:09 PM2 App name:myprogram id:0 online
14:05:09 PM2 App [myprogram] with id [0] and pid [3455], exited with code [0] via signal [null]
2016-01-27 14:05:09: Starting execution sequence in -fork mode- for app name:myprogram id:0
14:05:09 myprogram-0 Hello World
14:05:09 PM2 Starting execution sequence in -fork mode- for app name:myprogram id:0
2016-01-27 14:05:09: App name:myprogram id:0 online
2016-01-27 14:05:09: App [myprogram] with id [0] and pid [3456], exited with code [0] via signal [null]
2016-01-27 14:05:09: Script /home/abluchet/myprogram had too many unstable restarts (15). Stopped. "errored"
14:05:09 PM2 App name:myprogram id:0 online
14:05:09 PM2 App [myprogram] with id [0] and pid [3456], exited with code [0] via signal [null]
14:05:09 PM2 Script /home/abluchet/myprogram had too many unstable restarts (15). Stopped. "errored"
14:05:09 myprogram-0 Hello World
```

**Comment by bhaveshgohel** [comment]
@estliberitas : Yeah, that will be obvious if you consider test code. as it was not running continuous. But in case of my main Project Code it is running continuous.

@soyuka : Is it Debian Wizzy or Debian Jessie? , I'm using Debian Jessie on Raspberry Pi.

just for reference here is the pm2.log:
```
PM2: 2016-01-27 19:17:36: [PM2][WORKER] Started with refreshing interval: 30000
PM2: 2016-01-27 19:17:36: [[[[ PM2/God daemon launched ]]]]
PM2: 2016-01-27 19:17:36: BUS system [READY] on port /root/.pm2/pub.sock
PM2: 2016-01-27 19:17:36: RPC interface [READY] on port /root/.pm2/rpc.sock
PM2: 2016-01-27 19:17:37: Starting execution sequence in -fork mode- for app name:server id:0
PM2: 2016-01-27 19:17:37: App name:server id:0 online
PM2: 2016-01-27 19:17:38: Starting execution sequence in -fork mode- for app name:main id:1
PM2: 2016-01-27 19:17:38: App name:main id:1 online
```

What are the possible case PM2 will be unable to log? I can test that. :)

Today also i will be doing some test with older version of PM2, Since it was working sometime before update to 1.0.0.

Thanks.

**Comment by soyuka** [comment]
Jessie. The app will log to it's log file not necessarily `pm2.log`. I paste the output of the `pm2 logs` command.

**Comment by bhaveshgohel** [comment]
Hello @soyuka and @estliberitas ,

I've  tested below c code with Different OSs and pm2 versions:
```c
int main(int argc, char const *argv[])
{
    long long c;
    printf("Hello World\n");

    while(1){
        //wait for sometime.
        for(c=0;c<99999999;c++){

        }
        printf("Hello World\n");
    }
    return 0;
}
```
I have compiled above code with gcc and run it with pm2:
```bash
$ gcc -o test test.c
$ pm2 start ./test
$ pm2 logs
```
![pm2-issue](https://cloud.githubusercontent.com/assets/5253753/12679014/c70a433e-c6c7-11e5-9dbe-4e49e7f359b0.png)

Results:

1. Test 1 [**Faild to log**]
OS: Raspbian Jessie Lite (Rel. Date: 2015-11-21)
Hardware: Raspberry Pi 1 B+ 512MB
Node.js: v4.2.6
PM2: v0.15.0 & v1.0.0

2. Test 2 [**Faild to log**]
OS: DietPi v105 [Debian Jessie]
Hardware: Raspberry Pi 1 B+ 512MB
Node.js: v4.2.3
PM2: v0.15.0 & v1.0.0

3. Test 3 [**Faild to log**]
OS: DietPi v107 [Debian Wizzy]
Hardware: Raspberry Pi 1 B+ 512MB
Node.js: v4.2.6
PM2: v0.15.0 & v1.0.0

4. Test 4 [**Able to log**]
OS: Windows 7 64Bit
Hardware: Intel Core i5
Node.js: v4.2.3 & v4.2.6 
PM2: v0.15.0 & v1.0.0

5. Test 5 [**Able to log**]
OS: ubuntu 15.10 64Bit
Hardware: Intel Core i5
Node.js: v0.12.0 & v4.2.6 
PM2: v0.15.0 & v1.0.0

Note:
1. By saying "Faild to log" mean its able to Run but there were no log(stdout/stderr) recorded on it's log file.
2. All the Process were run by root user and was having all the right to edit the log directory.

--
Seems like it only having issue with Raspberry Pi. How can we tackle it?

**Comment by estliberitas** [comment]
@bhaveshgohel Plz, create simple Node app which logs something to stdout and stderr every N seconds and run it. And tell us if there logs.

It matters. It's either some problem with paths, or other thing which I do not get at all now

**Comment by bhaveshgohel** [comment]
@estliberitas It has no issue with Node App it is working smoothly from beginning, i'm only having issue with c executable.

**Comment by bhaveshgohel** [comment]
@estliberitas @soyuka :  is there anyway we can resolve this issue? :)

**Comment by adamglowacki** [comment]
And how did it end? How did you resolve this issue? When I try to run a binary executable under PM2 (Ubuntu Server), I get nothing in logs (i.e. `pm2 logs`). Then I run `pm2 restart XXX` and the missing lines appear in the log file. On another machine I can see the log files eventually fill with entries. So maybe it has something to do with logs flushing to files? Is it possible the log entries reside in PM2's local memory too long and are saved into the filesystem only after hours/days?

**Comment by bhaveshgohel** [comment]
@adamglowacki : i make another process(tcp/udp logger with javascript) just for loging the binary executable and print whichever log i want from my main binary file to that process via tcp/udp socket communication.

Cons:
- we have to manage both the process now.
- It wont log everything like when the main executable fails or in some uncaught error condition.

But all an all this is the dirty workaround i implemented.

I hope they resolve this issue since its around 1 year now. :confused:

**Comment by vmarchaud** [comment]
@bhaveshgohel I think you should give pm2 v2 a try and tell us if the issue is still here : `npm install -g pm2 && pm2 update`

**Comment by bhaveshgohel** [comment]
@vmarchaud: Sure Thanks, but I don't have device at the moment. I check and update about it soon. :smiley:

**Comment by bhaveshgohel** [comment]
@vmarchaud Sorry still not get chance to test, but I will get back to this very soon. :smiley:

**Comment by bhaveshgohel** [comment]
Sorry didn't get time to check yet. :confused: 
Closing the issue for now.

**Comment by checor** [comment]
Hello everyone, I have the same problem in Windows 10. Can't log binaries data.

My test program (Qt). A simple program that logs to stdout every 2 seconds. Works without problem running on console.
```
#include <QCoreApplication>
#include <QTimer>
#include <QDebug>

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);

    QTimer timer;
    QObject::connect(&timer, &QTimer::timeout, [](){
        qDebug() << "Hello world!\n";
    });
    timer.start(2000);
    return a.exec();
}
```

I remember that another project also had a problem with binaries logging, in a way like this one. I will check and report what I found.

Works fine on console.
