### ISSUE TITLE
pm2 keeps restarting for php script

### ISSUE THREAD

**Issue by teliov** [Unitech/pm2#1920]
I am using pm2 to manage a php script. It was working but all of a sudden the script won't stay up. It restarts almost every other second. And it is not an unstable restart. I am running an ubuntu gnome and the same setup is running on a debian and it works fine there.

**Comment by soyuka** [comment]
Logs (~/.pm2/pm2.log) ? Versions ?

**Comment by teliov** [comment]
Versions, thanks !. The ubuntu was on 0.14.x while the debian was on 0.15.x. An upgrade did the trick. Thanks!
