### ISSUE TITLE
Application declaration with JavaScript

### ISSUE THREAD

**Issue by raine** [Unitech/pm2#1925]
Documentation talks about [injecting Javascript into the configuration](http://pm2.keymetrics.io/docs/usage/application-declaration/#using-javascript-in-the-declaration). Personally I find it quite confusing that a file ends with `.json`, suggesting it would be a valid JSON file, yet it's actually JavaScript. This also screws up syntax highlighting in editor.

I think a more elegant and easier to understand solution would be to simply allow PM2 read JS files that export an object. Something like:

```js
module.exports = {
  apps: ['com', 'fi', 'br'].map((x, i) => {
    return {
      args: [x],
      name: `looper-${i}`,
      script: 'looper',
      exec_interpreter: 'bash'
    }
  })
}
```

Thoughts?

**Comment by Unitech** [comment]
If this is a conf file with a `.js` extension, PM2 would interpret that script as an application
