### ISSUE TITLE
Is there a way to detach a running process from pm2?

### ISSUE THREAD

**Issue by shaifd** [Unitech/pm2#1928]
We have a process that we want to implement graceful reload - but we can not use PM2's graceful reload because we use our own clustering code. We still want to be able to tell this process, which is started using pm2, to shutdown gracefully - and do not want it to be restarted automatically by PM2 when we do that. Is there a way to detach the process from PM2's watch so when it closes itself after a graceful logout - it is not restarted?
The only options we found are pm2 stop / delete and none answers our need to release this process from pm2 and keep it running.

Thanks!

**Comment by Unitech** [comment]
Stop / Delete should be enough, I don't really get the problem

**Comment by shaifd** [comment]
Stop/Delete cannot be used in our scenario: We want the process to continue (as it has information in the memory) but we need to detach it from pm2 completely. Using stop or delete will stop the process and the data in memory will be lost.
