### ISSUE TITLE
pm2-autopull installation

### ISSUE THREAD

**Issue by kheremos** [Unitech/pm2#1933]
pm2-autopull should be listed in the README as pm2-auto-pull.

Because "pm2 install pm2-autopull" will fail with "[PM2][Module][ERROR] Unknown module"

Easy to figure out, but may cause unnecessary confusion.

Thanks!

**Comment by Sigura** [comment]
Got same error

```bash
# pm2 -v
1.1.3
# pm2 install pm2-slack
[PM2][Module] Installing module pm2-slack
[PM2][Module] Module already installed. Updating.
[PM2][Module] Processing...
.........../root/.pm2
`-- pm2-slack@0.3.0

[PM2][Module][ERROR] Unknown module
```

**Comment by Sigura** [comment]
issue gone when I downgrade pm2 to version 1.1.2
