### ISSUE TITLE
pm2 cannot detect failed startup in conjunction with npm scripts

### ISSUE THREAD

**Issue by zivester** [Unitech/pm2#1934]
I'm trying to run an application using `package.json`'s `scripts` (Reference: https://github.com/Unitech/pm2/issues/1317#issuecomment-143448386), but pm2 does not detect a failure of the application to start when run with `npm`.

`test.js`

```js
require('this-file-does-not-exist');
```

As expected, pm2 run directly eventually fails:
```bash
$ pm2 --silent start test.js && sleep 1 && pm2 -m status | grep -E 'status|restarted'
[PM2] Starting test.js in fork_mode (1 instance)
[PM2] Done.
status : errored
restarted : 14
```

But, when we have a `package.json`:
```json
{
    "scripts": {
        "start": "./test.js"
    }
}
```

And attempt to run it through npm:
```bash
$ pm2 --silent start npm -- run start && sleep 1 && pm2 -m status | grep -E 'status|restarted'
[PM2] Starting npm in fork_mode (1 instance)
[PM2] Done.
status : online
restarted : 0
```

pm2 is capturing the logs spat out by the bogus require, but it is not attempting to rerun the `npm start` command when it fails.

**Comment by Unitech** [comment]
I do not manage to intercept the 'exit' signal from npm when a script exits (https://github.com/npm/npm/blob/e73b56407d95a723d0ebf5434a67d9bc6bce70e9/lib/utils/error-handler.js#L96)

For now please do:

`$ pm2 start npm --no-automation -- run start`

**Comment by Unitech** [comment]
Yep I do not manage to override the `_exit` npm configuration variable:

https://github.com/npm/npm/blob/e73b56407d95a723d0ebf5434a67d9bc6bce70e9/lib/utils/error-handler.js#L45

And any configuration name starting with a `_` apparently cannot be overriden

**Comment by zivester** [comment]
Thanks for the workaround @Unitech, seems to work well.

**Comment by gabmontes** [comment]
@Unitech how can I configure my `ecosystem.json` to execute `npm` with the `--no-automation` flag? I dealing with `pm2` to run my program's `npm start` script and properly capture errors.

**Comment by jcollum** [comment]
I agree @zivester, it works well. I am curious what the no-automation flag is doing though. I can't find anything in the docs that explains it.

**Comment by ufik** [comment]
@Unitech Same here as @gabmontes, I am trying to use this flag inside json configuration of app, but it's not working as an argument. Any advice how to do that?
