### ISSUE TITLE
Seems to be processing multiple requests at once

### ISSUE THREAD

**Issue by nidhhoggr** [Unitech/pm2#1936]
Here is a snippet on my pm2 logs

```
2016-02-08T07:06:22.249Z debug caching image begins of 9 at Logger.log (/var/www/vhosts/advertising-api/node_modules/le_node/lib/node_modules/logger.js:366:53)
    Mon, 08 Feb 2016 07:07:19 GMT: Request tracking middleware triggered on / at tracker         (/var/www/vhosts/advertising-api/server/middleware/tracker.js:6:13)
    The request processing time is 3.7102239999999997 ms. at ServerResponse.<anonymous>     (/var/www/vhosts/advertising-api/server/middleware/tracker.js:11:15)
    GET / 200 6ms { lbHttpMethod: 'GET',
      lbUrl: '/',
      lbStatusCode: 200,
      lbResponseTime: 6 }
2016-02-08T07:07:59.812Z debug caching image complete at Logger.log (/var/www/vhosts/advertising-api/node_modules/le_node/lib/node_modules/logger.js:366:53)
```

Notice that the indented text is  a separate requests in between a request logging image caching process. Also notice that the time it continued processing the images before it was interrupted was nearly a 50 second difference even through the interrupting request only took about 6 ms to complete. If I was reading the readme correctly it stated that each load balancing process should process one request at a time. if that is the case how is this possible? I have 2 separate processes running for that application for which I am using the following command:

> runuser -l git -c 'NODE_ENV=prod pm2 start /var/www/vhosts/advertising-api/server/server.js --name advertising-api -i 2'

The output that this logging was found on an process log. Also It's highly unlikely there was any issue with the cache considering that it's a redis cluster and all other server connected to the cluster had no issues connecting to the server at the time.

**Comment by zmijevik** [comment]
It turns out that there may have indeed been an issue with a redis cluster at the time however this still does not answer my question about there seemingly being a request processed between that process.
