### ISSUE TITLE
bug where App name is a number

### ISSUE THREAD

**Issue by keithics** [Unitech/pm2#1937]
you can start the app when the name is a number but you cannot delete or restart it.

![screen shot 2016-02-08 at 4 01 52 pm](https://cloud.githubusercontent.com/assets/229427/12880602/506a89e2-ce7d-11e5-99c2-c097de452193.png)

**Comment by soyuka** [comment]
Indeed, number is bound to the id

**Comment by keithics** [comment]
yep.. you can restart or delete it by id instead. not by app name.

**Comment by Unitech** [comment]
fixed (+tests) on dev branch, feel free to try it:

`npm install Unitech/pm2#development -g`
