### ISSUE TITLE
app keeps restarting although killed

### ISSUE THREAD

**Issue by geoeki** [Unitech/pm2#1939]
(this is my very first attempt using something like pm2, so bare with me). I got an app based on node.js from a colleague and I wanted to run it as a service via pm2 (latest version) on a Windows Server 2008 . It didn't work (starting meteor from a bash script) and always restarted without success (although calling the bash directly from gitbash did start meteor). I thought maybe the restart timer is too short as it takes a couple of seconds to initiate meteor, so I delayed the restart with --restart-delay 10000. Didn't help either, but the app keeps infinitely restarting now. I killed the app, deleted it out of pm2 several times, but every couple seconds it still restarts and shows up in pm2 again.

Here the error log:

```
PM2 Starting execution sequence in -fork mode- for app name:temp

id:0 PM2 App name:temp id:0 online temp-0 temp-0

child_process.js:553 temp-0 p.open(fd); temp-0 ^

temp-0 Error: EINVAL, invalid argument temp-0 at

Object.exports._forkChild (child_process.js:553:5) temp-0 at

Function.startup.processChannel (node.js:838:10) temp-0 at

startup (node.js:56:13) temp-0 at node.js:935:3 PM2 App

[temp] with id [0] and pid [7056], exited with code [8] via signal

[null]
```

This is really a problem with a console popping up every few seconds.

**Comment by vmarchaud** [comment]
Released in pm2 `2.4.1` via #2724
