### ISSUE TITLE
WHAT ON EARTH?? pm2.json won't start if env has attribute "NODE_UNIQUE_ID" 

### ISSUE THREAD

**Issue by artofspeed** [Unitech/pm2#1940]
This is an extremely weird bug. In `pm2.json`, when "env" has "NODE_UNIQUE_ID" field, the node app won't start. You can test it on any app. Just add NODE_UNIQUE_ID field to env.

```
"apps" : [
    {
      "script": "app.js",
      "env": {
        "PORT": "3000",
        "NODE_UNIQUE_ID": "0"
      }
    }
  ]
```

Then go to `localhost:3000` on your browser, you'll see server won't even start.

BUT remove NODE_UNIQUE_ID in `pm2.json`, server would start perfectly. What on earth???

**Comment by estliberitas** [comment]
@artofspeed https://nodejs.org/api/cluster.html#cluster_cluster_ismaster

**Comment by artofspeed** [comment]
I see, thanks!

**Comment by Unitech** [comment]
thanks @estliberitas !
