### ISSUE TITLE
Files requested by index returning 404 over network

### ISSUE THREAD

**Issue by suederade** [Unitech/pm2#1942]
Server started with the `node` command works fine, but once it is started with pm2 the files on the index.html all return 404.

Newest version of pm2 on Raspbian Jessie and Node v4.2.6.

No errors in debug mode.

**Comment by kakridge** [comment]
I am seeing a similiar issue with 404 for all routes in my node app.  Does not matter if I sudo or not.  pm2 was working without issue until I recently rebooted.   Can run node and forever without issue, but cannot get pm2 to run without the app generating 404's.

**Comment by nibblesnbits** [comment]
I'm having the same issue.  Has anyone looked into this yet?

**Comment by nibblesnbits** [comment]
Ok, so @kakridge and I figured out that, at least in our case, this was caused by my code dynamically loading some modules incorrectly.  I'm not sure if @stevenmwade is still having the issue, but I don't think this is an issue with pm2 anymore.
