### ISSUE TITLE
 cannot find module pm2/lib/ProcessContainerFork.js

### ISSUE THREAD

**Issue by evalenzuela** [Unitech/pm2#1943]
Good evening,

I am using webfaction, and just found PM2 module. But I am getting probably a beginner issue.

I have 2 apps running on webfaction. I run npm install pm2 -g while being on app2 folder. If I run pm2 start --name="app2" --watch, all goes well. But then If I go to app1. and run pm2 start --name="app1" --watch. It appears an error: " cannot find module pm2/lib/ProcessContainerFork.js".

What I have noticed is that that file exists on app2 folder structure but no on app1. I guess I need to define a home dir or something?

Thanks in advance for your help

**Comment by Unitech** [comment]
Normally if you install PM2 with the -g option, the module should be global.

Could you install on the root folder instead? It may helps

Also have a look at the `cwd` option: http://pm2.keymetrics.io/docs/usage/application-declaration/#options

**Comment by caojs** [comment]
I have the same issue. After some research, I followed a solution what I found this [stackoverflow](http://stackoverflow.com/questions/36690442/error-cannot-find-module-users-wyb-nvm-versions-io-js-v3-0-0-lib-node-modulerl).
Using `rm -rf ~/.pm2` and it worked.

**Comment by wojtek-krysiak** [comment]
In my case `pm2 update` solved the case

**Comment by redhat-raptor** [comment]
I just had to mkdir -p ~/.pm2/node_modules/

**Comment by Deniernal354** [comment]
Hello I have the same error and I ran all the above commands but they where no use.
Here is my full error.

```
1|app      | Error: Cannot find module '/root/.nvm/versions/node/v11.5.0/lib/node_modules/pm2/lib/ProcessContainerFork.js'
1|app      |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
1|app      |     at Function.Module._load (internal/modules/cjs/loader.js:529:25)
1|app      |     at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
1|app      |     at executeUserCode (internal/bootstrap/node.js:342:17)
1|app      |     at startExecution (internal/bootstrap/node.js:276:5)
1|app      |     at startup (internal/bootstrap/node.js:227:5)
1|app      |     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

**Comment by khelkun** [comment]
> I just had to `mkdir -p ~/.pm2/node_modules/`

Same for me under Windows 10. If I don't create this folder manually then `pm2 start` `failed from my exprressjs node app directory where the `ecosystem.config.js lives.
For me removing `~/.pm2/` does not fix the problem at all

**Comment by khelkun** [comment]
I have the same issue on Windows 10 with a pm2 global isntallation through npm. If I run `pm2 start` from the root folder of my nodejs expressjs application where lives the `ecosystem.config.json`:
```
0|ftl-node | Error: Cannot find module 'G:\my-expressjs-node-app\node_modules\pm2\lib\ProcessContainerFork.js'
0|ftl-node |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:15)
0|ftl-node |     at Function.Module._load (internal/modules/cjs/loader.js:835:27)
0|ftl-node |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
0|ftl-node |     at internal/main/run_main_module.js:17:47 {
0|ftl-node |   code: 'MODULE_NOT_FOUND',
0|ftl-node |   requireStack: []
0|ftl-node | }
```
If pm2 is installed as a local package of my nodejs application, then the issue does not occur...

**Comment by DaggieBlanqx** [comment]
> I have the same issue. After some research, I followed a solution what I found on this [stackoverflow](http://stackoverflow.com/questions/36690442/error-cannot-find-module-users-wyb-nvm-versions-io-js-v3-0-0-lib-node-modulerl).
> 
> Using `rm -rf ~/.pm2` and it worked.

It is 2021! and this answer worked for me! Thanks!

**Comment by tewedaj** [comment]
`pm2 start npm --name projectName -- run develop`
this worked for me

**Comment by yangxiaolin** [comment]
> I have the same issue. After some research, I followed a solution what I found on this [stackoverflow](http://stackoverflow.com/questions/36690442/error-cannot-find-module-users-wyb-nvm-versions-io-js-v3-0-0-lib-node-modulerl).
> 
> Using `rm -rf ~/.pm2` and it worked.

it's 2021-08. answer still work for me. cool

**Comment by tamurtaj85** [comment]
I had 2 versions of node 16.x and 17.x and i installed pm2 globally two times by interchanging the node versions but it still didn't work for me. Then i check the status of pm2 by deleting all the processes. And used the command "pm2 startup" to make it run at server startup. They will give a command just copy and paste the command and hit enter. After that run pm2 instance and you will be good to go.

**Comment by crazyoptimist** [comment]
Thanks @maxinmos ❤️❤️ 
`rm -rf .pm2` worked for me.

**Comment by notflip** [comment]
`cd && rm -rf .pm2` works for me as well. I used to have PM2 installed globally, switching to a local install now for testing, and removing the .pm2 folder is the trick, if someone can explain why, feel free to do so!

**Comment by qiulang** [comment]
It is 2023-12-15. The answer `rm -rf .pm2` still work for me (for pm2 5.3.0). WHY??

**Comment by MonishKrishna2009** [comment]
> I have the same issue. After some research, I followed a solution what I found on this [stackoverflow](http://stackoverflow.com/questions/36690442/error-cannot-find-module-users-wyb-nvm-versions-io-js-v3-0-0-lib-node-modulerl).
> 
> Using `rm -rf ~/.pm2` and it worked.

its 2024 -03 and solved the issue

Thank you btw.

**Comment by Gkiokan** [comment]
> > I have the same issue. After some research, I followed a solution what I found on this [stackoverflow](http://stackoverflow.com/questions/36690442/error-cannot-find-module-users-wyb-nvm-versions-io-js-v3-0-0-lib-node-modulerl).
> > Using `rm -rf ~/.pm2` and it worked.
> 
> it's 2021-08. answer still work for me. cool

2024-06 still works.  

I think this is an issue with pm2 when it has some old instances that can't even be cleared with `pm2 kill`.  
However `rm -rf ~/.pm2` fixes the issue and you can start over.

**Comment by terwer** [comment]
> I have the same issue. After some research, I followed a solution what I found on this [stackoverflow](http://stackoverflow.com/questions/36690442/error-cannot-find-module-users-wyb-nvm-versions-io-js-v3-0-0-lib-node-modulerl).
> 
> Using `rm -rf ~/.pm2` and it worked.

it's 2024-11. answer still work for me. cool

**Comment by banphlet** [comment]
> I have the same issue. After some research, I followed a solution what I found on this [stackoverflow](http://stackoverflow.com/questions/36690442/error-cannot-find-module-users-wyb-nvm-versions-io-js-v3-0-0-lib-node-modulerl).
Using rm -rf ~/.pm2 and it worked.

Yep this still works

**Comment by chengluyu** [comment]
It's 16th January 2026. `rm -rf ~/.pm2` still works.

**Comment by jim-king-2000** [comment]
It's 28th Jan 2026. `rm -rf ~/.pm2` still works. It's a bug. Nobody fix it?
