### ISSUE TITLE
post_update commands don't work when package.json contains javascript

### ISSUE THREAD

**Issue by oowl** [Unitech/pm2#1945]
I read in [manual](http://pm2.keymetrics.io/docs/usage/application-declaration/#using-javascript-in-the-declaration) that _ecosystem.json_ can contain javascript:

> You may have noticed that you can put comments, remove double quotes in JSON declaration file. It's because PM2 process the JSON file as a Javascript file meaning that you can inject Javascript into this file.

But [the code which finds commands for executing](https://github.com/Unitech/pm2/blob/6a774df4ed7f2419978f286b0edba387fce493ef/lib/tools/VersionManagement.js#L314) after update tries to parse _ecosystem.json_ as valid json file. As a result if file contains invalid JSON, no command will be executed.

**Comment by Unitech** [comment]
Alright! Thanks @oowl for reporting the issue and thx @Arkotek for fix landed in development version:

`$ npm install Unitech/pm2#development -g`
