### ISSUE TITLE
Only watch certain directories/files

### ISSUE THREAD

**Issue by cmckni3** [Unitech/pm2#1947]
Is there a way to whitelist directories/files to watch?

I don't find `ignore_watch` to be super useful for `pm2-dev` because of the large amount of things I have to ignore.

I would find it more useful to specify a handful of files and directories to watch.

**Comment by soyuka** [comment]
Maybe this is useful:
http://stackoverflow.com/questions/35142465/how-do-you-make-ignore-watch-regex-work-in-pm2/35165720#35165720
Le lun. 15 févr. 2016 à 23:09, Chris McKnight <notifications@github.com> a
écrit :

**Comment by cmckni3** [comment]
That helps but I couldn't find anything in the documentation about using an array with watch. I saw the schema allows for a an array.

```json
{
  "watch": [
    "app",
    "index.js"
  ]
}
```

Isn't working correctly on 1.0.1. If I update `.gitignore`, says it detected the change and restarts.

**Comment by tangxinfa** [comment]
I tested 1.01, it looks like --watch is a boolean now, can not specify a directory to watch, and there is no way to --ignore-watch multiple directories on command line, force us to put configurations in a json file.

**Comment by TrejGun** [comment]
+1 
i don't want to use json config

**Comment by soyuka** [comment]
13b1e0cae71fe57a949986335f27002f2fda30e4 enables:
```
pm2 start --watch lib --watch test
```
