### ISSUE TITLE
CPU and memory usage monitoring not working

### ISSUE THREAD

**Issue by greenc** [Unitech/pm2#1948]
Node: v0.12.5 (OSX dev env) /v0.10.42 (Ubuntu prod env)
PM2: v1.0.1

I'm fairly new to PM2 and I can't find any other reference to this specific issue anywhere else, so I'm hoping I've just missed something obvious.

I have a fairly simple node app that scrapes an API. It employs clustering within the app (not handled by PM2).

When I `pm2 monit` my app on either my development or production environments, my CPU usage is always 0% and memory usage is more or less constant at around 62MB (although does vary slightly), despite the real usage being around 60% CPU and 100-200MB memory consumed.

**Incorrect:**
![image](https://cloud.githubusercontent.com/assets/2804699/13066064/8d136232-d45a-11e5-8523-7b055849e23b.png)

**Correct:**
![image](https://cloud.githubusercontent.com/assets/2804699/13066080/aaaf6dfe-d45a-11e5-92a7-77b9cf5598e9.png)

Any ideas?

Also, of a lesser priority, is there any particular reason why my CLI interface looks pretty basic compared to the examples listed in the README (see below)?

![image](https://cloud.githubusercontent.com/assets/2804699/13066222/b4f66262-d45b-11e5-8030-4dba53134cbc.png)

**Comment by jozan** [comment]
I'm having the same issue on node v5.10.1 and latest version pm2. CPU usage stays at 0% all the time but when doing `pm2 reload all`. My app is offloading most of the work to child processes not handled by pm2. Is this an issue in my application or in pm2 itself?

The app is running on Ubuntu 14.04.

**Comment by soyuka** [comment]
child process usages are not computed, this might be the issue. 

As process usage has to be computed over time, it's also possible that the process usage isn't as accurate as the other?

> Also, of a lesser priority, is there any particular reason why my CLI interface looks pretty basic compared to the examples listed in the README (see below)?

IMO, it's a color scheme issue.

**Comment by greenc** [comment]
I managed to solve the missing CPU usage issue by letting PM2 handle clustering and removing all master/child worker clustering code from my app. When I redeployed it this way, PM2 CPU and RAM usage stats started working correctly.

**Comment by cdmcnamara** [comment]
I'm experiencing the same issue but to my knowledge my app isn't spinning off child processes. I'm using the API to call npm run start on a sub module.

Is there a way I can determine if the node process is actually a child of the pm2 process?

**Comment by soyuka** [comment]
We have things to compute a process tree but they're heavy in resources. Closing this in relation with my explanations in https://github.com/Unitech/pm2/issues/3319 . Current discussion: https://github.com/Unitech/pm2/issues/3422#issuecomment-360437744
