### ISSUE TITLE
Failed to install pm2 on my Ubuntu server

### ISSUE THREAD

**Issue by itleo31** [Unitech/pm2#1951]
Hi team, thank you for you great work. I'm trying to install pm2 to my ubuntu server but got this error. Please help me.

Environment: Ubuntu 14.04
Node: v5.6.0
Npm: 3.6.0

Error:
/opt/node/bin/pm2 -> /opt/node/lib/node_modules/pm2/bin/pm2
/opt/node/bin/pm2-dev -> /opt/node/lib/node_modules/pm2/bin/pm2-dev
/opt/node/lib
└─┬ pm2@1.0.1 
  └── ikt@0.0.0  (git+http://ikt.pm2.io/ikt.git#3325a3e39a502418dc2e2e4bf21529cbbde96228)

npm WARN optional Skipping failed optional dependency /pm2/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7

**Comment by harr999y** [comment]
Same problem,

Environment:
CentOS 7
npm 3.7.2

Thanks.

**Comment by renarsvilnis** [comment]
Having same issue on:
- Ubuntu 14.04
- Node v5.6.0
- Npm 3.7.3

```bash
npm i -g pm2
/home/ubuntu/.nvm/versions/node/v5.6.0/bin/pm2 -> /home/ubuntu/.nvm/versions/node/v5.6.0/lib/node_modules/pm2/bin/pm2
/home/ubuntu/.nvm/versions/node/v5.6.0/bin/pm2-dev -> /home/ubuntu/.nvm/versions/node/v5.6.0/lib/node_modules/pm2/bin/pm2-dev
/home/ubuntu/.nvm/versions/node/v5.6.0/lib
└─┬ pm2@1.0.1
  └── ikt@0.0.0  (git+http://ikt.pm2.io/ikt.git#3325a3e39a502418dc2e2e4bf21529cbbde96228)

npm WARN optional Skipping failed optional dependency /pm2/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
```

**Comment by soyuka** [comment]
I don't see any errors everything is fine with those messages.

**Comment by Marindrew** [comment]
I have the same issue

```
ubuntu@____:~$ sudo npm install pm2 -g
/usr/bin/pm2 -> /usr/lib/node_modules/pm2/bin/pm2
/usr/bin/pm2-dev -> /usr/lib/node_modules/pm2/bin/pm2-dev
/usr/lib
└─┬ pm2@1.0.1 
  └── ikt@0.0.0  (git+http://ikt.pm2.io/ikt.git#3325a3e39a502418dc2e2e4bf21529cbbde96228)

npm WARN optional Skipping failed optional dependency /pm2/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
```

**Comment by soyuka** [comment]
No errors there only warnings.

**Comment by mcrawshaw** [comment]
It's perfectly fine, `fsevents` is used by developers to watch the file system for new builds.  It is only compatible with Mac OSX, safe to ignore this warning.

**Comment by Unitech** [comment]
no error, closing issue

**Comment by LucianOppa** [comment]
no error but still not working any help?

**Comment by renarsvilnis** [comment]
As @mcrawshaw told, this is not really an issue, just an warning for an optional dependency.

> It's perfectly fine, fsevents is used by developers to watch the file system for new builds. It is only compatible with Mac OSX, safe to ignore this warning.

**Comment by heticor915** [comment]
@mcrawshaw  I was dealing with this today in a couple of Ubuntu servers meanwhile I was testing pm2,nodemon, forever.., It's just me or do I really need to use this only in a Mac OS enviroment ?

**Comment by soyuka** [comment]
No worry it's just a warning and pm2 will work fine (probably even better)
on Ubuntu ;).

**Comment by heticor915** [comment]
After checking this I solve  the problem, We need to add an explanation on this, after checking in xenial I was able to install using npm in this way: 

`npm install --no-optional pm2` or
`npm install -g --no-optional pm2`
I've seen many issues with the same problem including this. 
Regards.

**Comment by agilob** [comment]
>It's perfectly fine, fsevents is used by developers to watch the file system for new builds. It is only compatible with Mac OSX, safe to ignore this warning.

For me this is not a warning but error and breaks build of docker image:
```
npm WARN optional Skipping failed optional dependency /pm2/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
/bin/sh: 1: systemctl: not found
The command '/bin/sh -c ... && apt-get install -y nodejs npm build-essential php php7.0-fpm php7.0-sqlite php7.0-curl php7.0-mbstring sqlite3 git &&  npm install -g pm2 &&  ....  returned a non-zero code: 127
```

**Comment by vmarchaud** [comment]
@agilob It isnt the warning that make your build crash, but `/bin/sh: 1: systemctl: not found`

**Comment by agilob** [comment]
@vmarchaud adding `--no-optional` to `npm install -g pm2` passed the build, for sure it's not apt-get and git clone that is crashing the build.
