### ISSUE TITLE
Start in stopped mode

### ISSUE THREAD

**Issue by zontafil** [Unitech/pm2#1956]
Hello, I'm trying to build a dev environment with pm2.
Basically I'm planning to install needed deps with pm2 deploy, but I need to add my services to pm2 list without starting them, as I need to start them later manually.
Is it possible, or am I thinking about the problem the wrong way?

thanks.

**Comment by sholladay** [comment]
> I need to start them later manually
They will just start _then_. Why would you need to add them to the process database in advance?

**Comment by SunSatION** [comment]
+1

I would like to have the same functionality. I only need to start the load balancer process on deployment and let it start the other processes when needed, otherwise, the server will be overloaded on deployment.
