### ISSUE TITLE
PM2 with NGNIX strange behaviour

### ISSUE THREAD

**Issue by himgarg** [Unitech/pm2#1960]
I see when I start PM2 after a while there are many more instance running with sh and node.
I am running sudo pm2 start myfile.js -i 8 (on 8 core machine) it runs fine and within few minutes I see strange behavior.

when I run sudo lsof -i -P | grep -i listen to check I see there are more than 8 instances running, many of them are running under as sh.

**Comment by himgarg** [comment]
sh          2813          root   15u  IPv4  22607      0t0  TCP *:5002 (LISTEN)
node      2814          root   15u  IPv4  22607      0t0  TCP *:5002 (LISTEN)
sh          2822          root   15u  IPv4  22607      0t0  TCP *:5002 (LISTEN)
node      2823          root   15u  IPv4  22607      0t0  TCP *:5002 (LISTEN)
sh          2831          root   15u  IPv4  22607      0t0  TCP *:5002 (LISTEN)
node      2832          root   15u  IPv4  22607      0t0  TCP *:5002 (LISTEN)
sh          2840          root   15u  IPv4  22607      0t0  TCP *:5002 (LISTEN)
node      2841          root   15u  IPv4  22607      0t0  TCP *:5002 (LISTEN)

**Comment by QianJin2013** [comment]
Hi, i found PM2 dynamically change current process's command line by following TRICK:
```
process.title = 'node ' + pm2_env.pm_exec_path;
```

It's really. The result of ps of lsof or /proc/<pid>/cmdline will be changed.

So do not trust what you see.

I do not know whether this trick always works.

**Comment by Unitech** [comment]
https://nodejs.org/api/process.html#process_process_title
