### ISSUE TITLE
Clustering not working !!

### ISSUE THREAD

**Issue by metwally** [Unitech/pm2#1963]
I've tried to run my app in cluster mode but not working.
I've tried with node 0.10.36 and 5.6.0.
each time it open only one process 
I've tried -i 0, -i 2, -i 4 and -i max with no hope.
# lscpu

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    2
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Stepping:              4
CPU MHz:               2793.332
BogoMIPS:              5586.66
Hypervisor vendor:     Xen
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
NUMA node0 CPU(s):     0-3
# pm2 start sqs.js -i 0

[PM2] restartProcessId process id 1
[PM2] Process successfully started

┌──────────┬────┬──────┬───────┬─────────┬─────────┬────────┬────────────┬──────────┐
│ App name │ id │ mode │ pid   │ status  │ restart │ uptime │ memory     │ watching │
├──────────┼────┼──────┼───────┼─────────┼─────────┼────────┼────────────┼──────────┤
│ sqs      │ 1  │ fork │ 31366 │ online  │ 0       │ 0s     │ 8.430 MB   │ disabled │
└──────────┴────┴──────┴───────┴─────────┴─────────┴────────┴────────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
# node --version

v5.6.0

**Comment by spicydonuts** [comment]
Same problem.  Also tried to set using a config file. (`pm2 start ecosystem.json` with `instances: 0` and `exec_mode: "cluster"`)

**Comment by whyhankee** [comment]
Just noticed that in a .json file `instances: 0` does not seem to work.

Does *not* work:
`"instances": 0,`

Does work:
`"instances": "max",`

Maybe it helps!

$ pm2 --version = 0.15.10

$ node --version = v4.4.0

**Comment by metwally** [comment]
It works with Node.js version v0.12.10 !!
