### ISSUE TITLE
PM2 startup with non-root by default

### ISSUE THREAD

**Issue by inf3rno** [Unitech/pm2#1965]
I understand there are many questions in this topic. I read some of them. According to them currently PM2 can be started by non-root, but individual applications cannot be started by different users. I can live with that.

Databases usually add a Linux user with the proper settings. Why isn't PM2 installed the same way with a dedicated pm2 user who has the proper privileges to make running nodejs applications more secure? I think we could avoid many confusions and security issues with that.

**Comment by Unitech** [comment]
We use the root user only to setup the init scripts for launchd, systemd, upstart or rc.d
You can use whatever user you like to start PM2

https://github.com/Unitech/pm2/issues/2559
