### ISSUE TITLE
'pm2 stop all' does not work if process is in delayed restart state

### ISSUE THREAD

**Issue by santillaner** [Unitech/pm2#1966]
If you issue a 'pm2 stop all' command while some processes are in stopped state because of "restart_delay" param, those temporarily stopped processes are relaunched when the delay finishes. 
However, if those processes are running while the 'pm2 stop all' command is launched, they are correctly stopped and not relaunched anymore.

**Comment by efolio** [comment]
+1 this is really annoying…
The only thing currently available to stop the processes is `pm2 kill`…

**Comment by m1ch4ls** [comment]
:+1:

**Comment by soyuka** [comment]
@efolio maybe `pm2 delete all`?
ping @Unitech

**Comment by vmarchaud** [comment]
Released in pm2 `2.4.1` via #2724
