### ISSUE TITLE
My pm2 dosen't work

### ISSUE THREAD

**Issue by kevinsu1989** [Unitech/pm2#1970]
PM2: 2016-02-25 16:02:07: [PM2][WORKER] Started with refreshing interval: 30000
PM2: 2016-02-25 16:02:07: [[[[ PM2/God daemon launched ]]]]
PM2: 2016-02-25 16:02:07: BUS system [READY] on port /root/.pm2/pub.sock
PM2: 2016-02-25 16:02:07: RPC interface [READY] on port /root/.pm2/rpc.sock
PM2: 2016-02-25 16:02:07: Starting execution sequence in -fork mode- for app name:app id:0
PM2: 2016-02-25 16:02:07: App name:app id:0 online
PM2: 2016-02-25 16:02:07: Error: spawn coffee ENOENT
PM2:     at exports._errnoException (util.js:870:11)
PM2:     at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
PM2:     at onErrorNT (internal/child_process.js:344:16)
PM2:     at nextTickCallbackWith2Args (node.js:437:9)
PM2:     at process._tickDomainCallback (node.js:392:17)

**Comment by yasaricli** [comment]
run command 

    pm2 kill 

?
