### ISSUE TITLE
PM2 hangs after "PM2 daemonized" and "Process launched"

### ISSUE THREAD

**Issue by xsy233** [Unitech/pm2#1971]
when I run pm2 as 
`$ pm2 start www/production.js --no-daemon`

it works as expected

however, with

```
$ pm2 start pm2.json
[PM2] Spawning PM2 daemon
[PM2] PM2 Successfully daemonized
[PM2] Process launched

```

then pm2 just hangs forever
but child processes have started yet

In another terminal, running all pm2 commands will get stuck
function like child process auto-restart works just fine

debug info:

```
$ DEBUG="*" pm2 list 
pm2:constants PM2 folder (logs, pids, configuration): /home/work/.pm2 +0ms
  pm2:monit Getting interaction info +251ms
  pm2:interface:daemon [PING INTERACTOR] Trying to connect to Interactor daemon +2ms
  axon:sock connect attempt null:/home/work/.pm2/interactor.sock +2ms
  pm2:satan [PING PM2] Trying to connect to server +6ms
  axon:sock connect attempt null:/home/work/.pm2/rpc.sock +1ms
  axon:sock error ENOENT +4ms
  axon:sock ignored ENOENT +0ms
  axon:sock connect +1ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +1ms
  axon:sock closing +0ms
  axon:sock closing 1 connections +0ms
  pm2:satan Daemon alive +0ms
  axon:sock remove socket 0 +1ms
  pm2:satan Launching RPC client on socket file /home/work/.pm2/rpc.sock +1ms
  axon:sock connect attempt null:/home/work/.pm2/rpc.sock +0ms
  axon:sock connect +1ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +0ms
  pm2:satan Connected to Daemon +0ms
  pm2:cli Got message from Satan as successfully connected to PM2, now parsing arguments +5ms
  pm2:satan Calling daemon method pm2:getVersion +0ms
  pm2:satan Calling daemon method pm2:getMonitorData +3ms
  axon:sock attempting reconnect +92ms
  axon:sock closing +0ms
  axon:sock closing 0 connections +0ms
  pm2:interface:daemon Interactor Daemon not launched +0ms
  axon:sock connect attempt null:/home/work/.pm2/interactor.sock +0ms
  axon:sock error ENOENT +1ms
  axon:sock ignored ENOENT +0ms
```

my pm2.json is

```
{
  "apps": [
    {
      "name": "xxx",
      "script": "www/production.js",
      "exec_mode": "cluster",
      "instances": 4,
      "max_memory_restart": "1G",
      "autorestart": true,
      "node_args": [],
      "args": [],
      "env": {},
      "error_file": "/data/logs/web/xxx.err.log",
      "out_file": "/data/logs/web/xxx.out.log",
      "merge_logs": true,
      "pid_file": "/data/run/xxx.pid"
    }
  ]
}
```

**Comment by nicholasdickey** [comment]
I have the same issue

**Comment by gpetrov** [comment]
this happens also to me - any idea hot to debug/resolve?

**Comment by jdbranham** [comment]
Same for me.

OS Redhat 7
node v6.9.1
pm2 v1.0.1

**Comment by jdbranham** [comment]
looks like mine is hanging at a socket connection -

`[me@mine lrs-dev]$ DEBUG="*" pm2 start server.js
  pm2:constants PM2 folder (logs, pids, configuration): /home/me/.pm2 +0ms
  pm2:monit Getting interaction info +248ms
  pm2:interface:daemon [PING INTERACTOR] Trying to connect to Interactor daemon +4ms
  axon:sock connect attempt null:/home/me/.pm2/interactor.sock +2ms
  pm2:satan [PING PM2] Trying to connect to server +7ms
  axon:sock connect attempt null:/home/me/.pm2/rpc.sock +0ms
  axon:sock error ENOENT +6ms
  axon:sock ignored ENOENT +0ms
  axon:sock connect +1ms
  axon:sock add socket 0 +1ms
  axon:queue flush 0 messages +1ms
  axon:sock closing +1ms
  axon:sock closing 1 connections +0ms
  pm2:satan Daemon alive +0ms
  axon:sock remove socket 0 +2ms
  pm2:satan Launching RPC client on socket file /home/me/.pm2/rpc.sock +0ms
  axon:sock connect attempt null:/home/me/.pm2/rpc.sock +0ms
  axon:sock connect +1ms
  axon:sock add socket 0 +1ms
  axon:queue flush 0 messages +0ms
  pm2:satan Connected to Daemon +0ms
  pm2:cli Got message from Satan as successfully connected to PM2, now parsing arguments +5ms
  pm2:satan Calling daemon method pm2:getVersion +1ms
  pm2:monit Before processing +10ms { script: 'server.js',
  node_args: undefined,
  max_memory_restart: undefined,
  restart_delay: undefined,
  instances: undefined,
  kill_timeout: undefined,
  port: undefined,
  log_file: undefined,
  error_file: undefined,
  out_file: undefined,
  pid_file: undefined,
  cron_restart: undefined,
  cwd: undefined,
  merge_logs: undefined,
  vizion: true,
  pmx: true,
  automation: true,
  autorestart: true,
  treekill: true,
  watch: undefined,
  ignore_watch: undefined,
  watch_options: undefined,
  env: undefined,
  log_date_format: undefined,
  min_uptime: undefined,
  max_restarts: undefined,
  exec_mode: 'fork_mode',
  exec_interpreter: undefined,
  write: undefined,
  force: undefined,
  post_update: undefined,
  name: 'server' }
  pm2:monit After processing +7ms { errors: [],
  config:
   { script: 'server.js',
     name: 'server',
     vizion: true,
     pmx: true,
     automation: true,
     autorestart: true,
     treekill: true,
     exec_mode: 'fork_mode' } }
  pm2:satan Calling daemon method pm2:findByFullPath +11ms
[PM2] Starting server.js in fork_mode (1 instance)
  pm2:satan Calling daemon method pm2:prepare +5ms
  axon:sock attempting reconnect +60ms
  axon:sock closing +0ms
  axon:sock closing 0 connections +0ms
  pm2:interface:daemon Interactor Daemon not launched +0ms
  axon:sock connect attempt null:/home/me/.pm2/interactor.sock +1ms
  axon:sock error ENOENT +0ms
  axon:sock ignored ENOENT +1ms
  axon:sock remove socket 0 +906ms
  axon:sock attempting reconnect +100ms
  axon:sock connect attempt null:/home/me/.pm2/rpc.sock +1ms
  axon:sock error ECONNREFUSED +0ms
  axon:sock ignored ECONNREFUSED +0ms
  axon:sock attempting reconnect +151ms
  axon:sock connect attempt null:/home/me/.pm2/rpc.sock +0ms
  axon:sock error ECONNREFUSED +0ms
  axon:sock ignored ECONNREFUSED +0ms
  axon:sock attempting reconnect +226ms
`

**Comment by jdbranham** [comment]
After starting the app in non-daemon mode, I noticed there was a reference to an older global pm2 binary. 
After removing the old installation files from the path, the server is working fine again.
