### ISSUE TITLE
Process cannot be killed kill ESRCH (PM2 1.0.1) in cluster mode

### ISSUE THREAD

**Issue by airs0urce** [Unitech/pm2#1974]
I have problem on Fedora 22 (node 5.7.0, PM2 1.0.1). My server.js starts server .js (HTTP and Websocket server) in cluster mode, 6 instances and two apps in fork mode. On SIGINT in server.js I clear something and exit:

`
process.on('SIGINT', function() {
    // clear, stop HTTP server, stop websocket server
    process.exit(0);
});
`

This is my app.json: [app.json](https://github.com/Unitech/pm2/files/147811/app.txt)

I delete all processes (pm2 delete), but PM2 doesn't kill some processes of clustered app.
(Sometimes those zombie processes start eating CPU)

<img width="819" alt="commands" src="https://cloud.githubusercontent.com/assets/109203/13345759/ff77fd60-dc93-11e5-88cd-29b53af1cbec.png">
(btw, why it says "restarted" if I run "pm2 delete" command?)
So, it shows that there is no processes when I run "pm2 list", but I can see with "ps aux | grep node" that processes still running.

This is PM2 log:

> PM2 Stopping app:nearby id:0
PM2 Process with pid 22126 still not killed, retrying...
PM2 Process with pid 22126 still not killed, retrying...
PM2 Process with pid 22126 still not killed, retrying...
PM2 Process with pid 22126 still not killed, retrying...
PM2 Process with pid 22126 still not killed, retrying...
PM2 Process with pid 22126 still not killed, retrying...
PM2 Process with pid 22126 still not killed, retrying...
PM2 Process with pid 22126 still not killed, retrying...
PM2 Process with pid 22126 still not killed, retrying...
PM2 Process with pid 22126 still not killed, retrying...
PM2 Process with pid 22126 still not killed, retrying...
PM2 Process with pid 22126 still not killed, retrying...
PM2 Process with pid 22126 still not killed, retrying...
PM2 Process with pid 22126 still not killed, retrying...
PM2 Process with pid 22126 still not killed, retrying...
PM2 Process with pid 22126 still alive after 1600ms, sending it SIGKILL now...
PM2 Process cannot be killed kill ESRCH
PM2 Process with pid 22126 still not killed, retrying...
PM2 Process with pid 22126 still not killed, retrying...
PM2 Process with pid 22126 still not killed, retrying...
PM2 Process with pid 22126 still not killed, retrying...
PM2 Process with pid 22126 still not killed, retrying...
PM2 Process with pid 22126 still not killed, retrying...
PM2 Process with pid 22126 still not killed, retrying...
PM2 Process with pid 22126 still not killed, retrying...
PM2 Process with pid 22126 still not killed, retrying...
PM2 Process with pid 22126 still not killed, retrying...
PM2 Process with pid 22126 still not killed, retrying...
PM2 Process with pid 22126 still not killed, retrying...
PM2 Process with pid 22126 still not killed, retrying...
PM2 Process with pid 22126 still not killed, retrying...
PM2 Process with pid 22126 still not killed, retrying...
PM2 Process with pid 22126 could not be killed
PM2 Stopping app:nearby id:1
PM2 Process with pid 22131 still not killed, retrying...
PM2 Process with pid 22131 still not killed, retrying...
PM2 Process with pid 22131 still not killed, retrying...
PM2 Process with pid 22131 still not killed, retrying...
PM2 Process with pid 22131 still not killed, retrying...
PM2 Process with pid 22131 still not killed, retrying...
PM2 Process with pid 22131 still not killed, retrying...
PM2 Process with pid 22131 still not killed, retrying...
PM2 Process with pid 22131 still not killed, retrying...
PM2 Process with pid 22131 still not killed, retrying...
PM2 Process with pid 22131 still not killed, retrying...
PM2 Process with pid 22131 still not killed, retrying...
PM2 Process with pid 22131 still not killed, retrying...
PM2 Process with pid 22131 still not killed, retrying...
PM2 Process with pid 22131 still not killed, retrying...
PM2 Process with pid 22131 still alive after 1600ms, sending it SIGKILL now...
PM2 Process cannot be killed kill ESRCH
PM2 Process with pid 22131 still not killed, retrying...
PM2 Process with pid 22131 still not killed, retrying...
PM2 Process with pid 22131 still not killed, retrying...
PM2 Process with pid 22131 still not killed, retrying...
PM2 Process with pid 22131 still not killed, retrying...
PM2 Process with pid 22131 still not killed, retrying...
PM2 Process with pid 22131 still not killed, retrying...
PM2 Process with pid 22131 still not killed, retrying...
PM2 Process with pid 22131 still not killed, retrying...
PM2 Process with pid 22131 still not killed, retrying...
PM2 Process with pid 22131 still not killed, retrying...
PM2 Process with pid 22131 still not killed, retrying...
PM2 Process with pid 22131 still not killed, retrying...
PM2 Process with pid 22131 still not killed, retrying...
PM2 Process with pid 22131 still not killed, retrying...
PM2 Process with pid 22131 could not be killed
PM2 Stopping app:nearby id:2
PM2 Process with pid 22152 still not killed, retrying...
PM2 Process with pid 22152 still not killed, retrying...
PM2 Process with pid 22152 still not killed, retrying...
PM2 Process with pid 22152 still not killed, retrying...
PM2 Process with pid 22152 still not killed, retrying...
PM2 Process with pid 22152 still not killed, retrying...
PM2 Process with pid 22152 still not killed, retrying...
PM2 Process with pid 22152 still not killed, retrying...
PM2 Process with pid 22152 still not killed, retrying...
PM2 Process with pid 22152 still not killed, retrying...
PM2 Process with pid 22152 still not killed, retrying...
PM2 Process with pid 22152 still not killed, retrying...
PM2 Process with pid 22152 still not killed, retrying...
PM2 Process with pid 22152 still not killed, retrying...
PM2 Process with pid 22152 still not killed, retrying...
PM2 Process with pid 22152 still alive after 1600ms, sending it SIGKILL now...
PM2 Process cannot be killed kill ESRCH
PM2 Process with pid 22152 still not killed, retrying...
PM2 Process with pid 22152 still not killed, retrying...
PM2 Process with pid 22152 still not killed, retrying...
PM2 Process with pid 22152 still not killed, retrying...
PM2 Process with pid 22152 still not killed, retrying...
PM2 Process with pid 22152 still not killed, retrying...
PM2 Process with pid 22152 still not killed, retrying...
PM2 Process with pid 22152 still not killed, retrying...
PM2 Process with pid 22152 still not killed, retrying...
PM2 Process with pid 22152 still not killed, retrying...
PM2 Process with pid 22152 still not killed, retrying...
PM2 Process with pid 22152 still not killed, retrying...
PM2 Process with pid 22152 still not killed, retrying...
PM2 Process with pid 22152 still not killed, retrying...
PM2 Process with pid 22152 still not killed, retrying...
PM2 Process with pid 22152 could not be killed
PM2 Stopping app:nearby id:3
PM2 App name:nearby id:3 disconnected
PM2 App [nearby] with id [3] and pid [22177], exited with code [0] via signal [SIGINT]
PM2 Stopping app:nearby id:4
PM2 Process with pid 22203 still not killed, retrying...
PM2 Process with pid 22203 still not killed, retrying...
PM2 Process with pid 22203 still not killed, retrying...
PM2 Process with pid 22203 still not killed, retrying...
PM2 Process with pid 22203 still not killed, retrying...
PM2 Process with pid 22203 still not killed, retrying...
PM2 Process with pid 22203 still not killed, retrying...
PM2 Process with pid 22203 still not killed, retrying...
PM2 Process with pid 22203 still not killed, retrying...
PM2 Process with pid 22203 still not killed, retrying...
PM2 Process with pid 22203 still not killed, retrying...
PM2 Process with pid 22203 still not killed, retrying...
PM2 Process with pid 22203 still not killed, retrying...
PM2 Process with pid 22203 still not killed, retrying...
PM2 Process with pid 22203 still not killed, retrying...
PM2 Process with pid 22203 still alive after 1600ms, sending it SIGKILL now...
PM2 Process cannot be killed kill ESRCH
PM2 App name:nearby id:4 disconnected
PM2 App [nearby] with id [4] and pid [22203], exited with code [0] via signal [SIGINT]
PM2 Stopping app:nearby id:5
PM2 Process with pid 22234 still not killed, retrying...
PM2 Process with pid 22234 still not killed, retrying...
PM2 Process with pid 22234 still not killed, retrying...
PM2 Process with pid 22234 still not killed, retrying...
PM2 Process with pid 22234 still not killed, retrying...
PM2 Process with pid 22234 still not killed, retrying...
PM2 Process with pid 22234 still not killed, retrying...
PM2 Process with pid 22234 still not killed, retrying...
PM2 Process with pid 22234 still not killed, retrying...
PM2 Process with pid 22234 still not killed, retrying...
PM2 Process with pid 22234 still not killed, retrying...
PM2 Process with pid 22234 still not killed, retrying...
PM2 Process with pid 22234 still not killed, retrying...
PM2 Process with pid 22234 still not killed, retrying...
PM2 Process with pid 22234 still not killed, retrying...
PM2 Process with pid 22234 still alive after 1600ms, sending it SIGKILL now...
PM2 Process cannot be killed kill ESRCH
PM2 Process with pid 22234 still not killed, retrying...
PM2 Process with pid 22234 still not killed, retrying...
PM2 Process with pid 22234 still not killed, retrying...
PM2 Process with pid 22234 still not killed, retrying...
PM2 Process with pid 22234 still not killed, retrying...
PM2 Process with pid 22234 still not killed, retrying...
PM2 Process with pid 22234 still not killed, retrying...
PM2 Process with pid 22234 still not killed, retrying...
PM2 Process with pid 22234 still not killed, retrying...
PM2 Process with pid 22234 still not killed, retrying...
PM2 Process with pid 22234 still not killed, retrying...
PM2 Process with pid 22234 still not killed, retrying...
PM2 Process with pid 22234 still not killed, retrying...
PM2 Process with pid 22234 still not killed, retrying...
PM2 Process with pid 22234 still not killed, retrying...
PM2 Process with pid 22234 could not be killed
PM2 Stopping app:nearby-workers id:6
PM2 Process with pid 22259 still not killed, retrying...
PM2 Process with pid 22259 still not killed, retrying...
PM2 Process with pid 22259 still not killed, retrying...
PM2 Process with pid 22259 still not killed, retrying...
PM2 Process with pid 22259 still not killed, retrying...
PM2 Process with pid 22259 still not killed, retrying...
PM2 Process with pid 22259 still not killed, retrying...
PM2 Process with pid 22259 still not killed, retrying...
PM2 Process with pid 22259 still not killed, retrying...
PM2 Process with pid 22259 still not killed, retrying...
PM2 Process with pid 22259 still not killed, retrying...
PM2 Process with pid 22259 still not killed, retrying...
PM2 Process with pid 22259 still not killed, retrying...
PM2 Process with pid 22259 still not killed, retrying...
PM2 Process with pid 22259 still not killed, retrying...
PM2 Process with pid 22259 still alive after 1600ms, sending it SIGKILL now...
PM2 App [nearby-workers] with id [6] and pid [22259], exited with code [0] via signal [SIGKILL]
PM2 Stopping app:nearby-bot id:7
PM2 Process with pid 22271 still not killed, retrying...
PM2 Process with pid 22271 still not killed, retrying...
PM2 Process with pid 22271 still not killed, retrying...
PM2 Process with pid 22271 still not killed, retrying...
PM2 Process with pid 22271 still not killed, retrying...
PM2 Process with pid 22271 still not killed, retrying...
PM2 Process with pid 22271 still not killed, retrying...
PM2 Process with pid 22271 still not killed, retrying...
PM2 Process with pid 22271 still not killed, retrying...
PM2 Process with pid 22271 still not killed, retrying...
PM2 Process with pid 22271 still not killed, retrying...
PM2 Process with pid 22271 still not killed, retrying...
PM2 Process with pid 22271 still not killed, retrying...
PM2 Process with pid 22271 still not killed, retrying...
PM2 Process with pid 22271 still not killed, retrying...
PM2 Process with pid 22271 still alive after 1600ms, sending it SIGKILL now...
PM2 App [nearby-bot] with id [7] and pid [22271], exited with code [0] via signal [SIGKILL]

Apps "nearby-workers" and "nearby-bot" running in fork mode, so not problems with them.

Processes where it shows "Process cannot be killed kill ESRCH" stay running.
Now I added workaround "pkill node" after "pm2 delete" to get rid of those zombie processes.

I have development server which running on same software (OS version, node version etc.).
And on that server it works ok, but there is no users connected. Also once "pm2 delete" worked good on production too, but again because there were no users connected. 
Also I had problem above on OSX, so I don't think this is only happens on Fedora 22, something wrong with killing processes, I'll try to test it more on OSX.

I can add any debug information to code and run "pm2 delete" again if it will help to get reason of this behavior.

**Comment by airs0urce** [comment]
Just reproduced it on local machine (OSX).
"Process cannot be killed kill ESRCH" happens only when there is connected client to Websocket server (I use https://www.npmjs.com/package/ws library).
Will try to write separate script to show how to reproduce the issue.

**Comment by airs0urce** [comment]
Previous pm2 version I used was 0.12.16. And it happened there too, but error was different:
"Process disconnected from parent" instead of "Process cannot be killed kill ESRCH"

**Comment by Unitech** [comment]
Could you please try with a simple node.js app that catch the SIGINT message without exiting, and try to see if with your setup the app get killed after 1.6s?

**Comment by airs0urce** [comment]
Yes, In simple app it works. I just got what happens. When I have at least two websocket connections my SIGINT handler makes the problem. It starts loading CPU 100% and I can't kill app even when press Ctrl+C in terminal. So, I'm checking with profiler now what's wrong and trying to debug it. This is issue on my side. 

But anyway, may be my case will be useful to improve pm2. I just tried this:

process.on('SIGINT', function() {
	while (true){}
});

And in this case pm2 will never kill app and programmer will not know why about it until he run something like:
$ ps aux | grep node 
And after each restart user will get more and more processes. 
May be there is way to kill buggy apps?

**Comment by liukun** [comment]
I got the same log but in my case, it is not PM2's fault but mine. My old problematic was like:

    server = net.createServer(...)
    server.listen(...)
    process.on("SIGINT", function() {
        server.close(function() {
            process.exit()
        })
    })

When there was existing connected sockets, PM2 restart will error and not work. The reason is `server.close` will not run callback function if there are existing connections (nodejs/api/net.html#net_server_close_callback). To fix, just stop all left connections manually:

    sockets = {} // just demo
    server = net.createServer(...) // remember existing sockets
    server.listen(...)
    process.on("SIGINT", function() {
        server.close(function() {
            process.exit()
        })
        // go through all sockets here, finish jobs and then call socket.destroy()
        _.forEach(sockets, function(socket) {
            socket.destroy() // just demo, should finish jobs first in real case
        })
    })

Then PM2 restart works correctly.

**Comment by airs0urce** [comment]
In my case this is my fault too. Only thing I suggest now - handle cases like this:

process.on('SIGINT', function() {
while (true){}
});

and show some message right in output of "pm2 restart", "pm2 stop" and other commands that stop processes to let developer see problem in code before he start getting zombie processes.

**Comment by Unitech** [comment]
closing in favor of #2061
