### ISSUE TITLE
Changing app config with environment

### ISSUE THREAD

**Issue by Tomino2112** [Unitech/pm2#1975]
Hi,

I couldn't find anywhere if this is possible. 

I have different environments I have to "deploy" my app to and I would like each running with a bit different config.

So what I am trying to do is:

```
{
  "apps":[{
    "name": "api2",
    "script": "app.js",
    "watch": true,
    "ignore_watch": ["./**/*.ts","./**/*.map",".git",".idea"],
    "env_development": {
      "NODE_ENV": "development",
      "autorestart": false
    },    
    "env_production": {
      "NODE_ENV": "production",
      "exec_mode": "cluster_mode",
      "instances": 4,
      "cron_restart": "0 1 * * *",
      "autorestart": true
    }
  }]
}
```

This is not working and as I understand it, in environments you can only set the environment variables that are accessible in app.

Is there other way of doing this? I know there is "deploy" option, but we dont need it to be deploying with git etc, we have other stuff in place for that.

Thank you

**Comment by deathlord87** [comment]
seperate out the apps and deploy into two jsons it would help deploying to different environments

**Comment by bluejamesbond** [comment]
Perhaps the [BrancOff PM2 module](https://github.com/bluejamesbond/BranchOff.js)?

**Comment by bluejamesbond** [comment]
Have you taken a look at this? http://pm2.keymetrics.io/docs/usage/pm2-doc-single-page/

```json5
// Default environment variables that will be injected in any environment and at any start
  "env": {
    "NODE_ENV": "production",
    "AWESOME_SERVICE_API_TOKEN": "xxx"
  }
  "env_*" : {
    "SPECIFIC_ENV" : true
  }
```

**Comment by Tomino2112** [comment]
@bluejamesbond Thats exactly what I described above.... Try what you suggesting with my config above and you will see that it doesnt work

**Comment by bluejamesbond** [comment]
```json
{
  "apps":[{
    "name": "app",
    "script": "test.js",
    "env_development": {
      "NODE_ENV": "development"
    },    
    "env_development_config": {
      "exec_mode": "cluster_mode",
      "instances": 2
    },    
    "env_production": {
      "NODE_ENV": "production"
    },
    "env_production_config": {
      "exec_mode": "cluster_mode",
      "instances": 4
    },    
  }]
}
```

**WARNING**: Temporary solution. `npm install git://github.com/bluejamesbond/BranchOff.js.git -g`. To restart the app, you have to `stop` and then `start`.

Please delete this comment as needed.

**Comment by Tomino2112** [comment]
@bluejamesbond Tahnks for taking the time, it would be better if you create pull request to pm2, dont really want to install pm2 from custom repo

**Comment by Unitech** [comment]
```
# Will use environment variables under env_production
$ pm2 start application.json --env production
# Will use env var under env_development
$ pm2 start application.json --env development
```
