### ISSUE TITLE
with only one app you get "[PM2][ERROR] No script path - aborting"

### ISSUE THREAD

**Issue by toddgeist** [Unitech/pm2#1976]
It seems like this should be a valid json config,
```json
{
  "apps:" : [
    {
      "name" : "dropbox",
      "script" : "server.js",
    }
  ]
}
```
But it will throw `[PM2][ERROR] No script path - aborting`. Instead you need to get rid of the "apps" key.  This works.

```json
{
   "name" : "dropbox",
   "script" : "server.js",
 }
```
I did not see this anywhere in the docs so I thought I'd post it. I'd be happy to work on a PR if somebody can point me to the file.

Todd

**Comment by bluejamesbond** [comment]
@toddgeist I think that the `ecosystem.json` file allows you have to multiple apps which are potentially in different locations; so a `cwd` is required. However, with a single app then you don't need to specify that.

**Comment by Unitech** [comment]
It's apps not apps:

```"apps:"```

**Comment by toddgeist** [comment]
uggghhhhh can't believe I fell for that :-(

**Comment by yogithesymbian** [comment]
whats wrong with me 
```
module.exports = {
  apps : [{
    name: "API-NODE",
    script: "/var/www/api/api-nodejs/server.js",
    env: {
      NODE_ENV: "development",
    },
    env_production: {
      NODE_ENV: "production",
    },
    watch: '.'
  }, {

  }],

  deploy : {
    production : {
      user : 'root',
      host : '101.xx.x.xxx',
      ref  : 'origin/master',
      repo : 'https://github.com/yogithesymbian/xxxx.git',
      path : '/var/www/api/api-nodejs/',
      'pre-deploy-local': '',
      'post-deploy' : 'npm install && pm2 reload ecosystem.config.js --env production',
      'pre-setup': ''
    }
  }
};


```

**Comment by yogithesymbian** [comment]
> whats wrong with me i have same issue @toddgeist
> 
> ```
> pm2 ecosystem
> ```
> 
> ```
> module.exports = {
>   apps : [{
>     name: "API-NODE",
>     script: "/var/www/api/api-nodejs/server.js",
>     env: {
>       NODE_ENV: "development",
>     },
>     env_production: {
>       NODE_ENV: "production",
>     },
>     watch: '.'
>   }, {
> 
>   }],
> 
>   deploy : {
>     production : {
>       user : 'root',
>       host : '101.xx.x.xxx',
>       ref  : 'origin/master',
>       repo : 'https://github.com/yogithesymbian/xxxx.git',
>       path : '/var/www/api/api-nodejs/',
>       'pre-deploy-local': '',
>       'post-deploy' : 'npm install && pm2 reload ecosystem.config.js --env production',
>       'pre-setup': ''
>     }
>   }
> };
> ```
> 
> ```
> pm2 restart ecosystem.config.js --env production
> ```

pm2 restart ecosystem.config.js --env production --ignore-watch

  error: option `--ignore-watch <folders|files>' argument missing

**Comment by ink-stone** [comment]
try "script" replace "exec" 
There may be a version problem

**Comment by yogithesymbian** [comment]
> apps : [{
>     name: "API-NODE",
>     script: "/var/www/api/api-nodejs/server.js",
>     env: {
>       NODE_ENV: "development",
>     },
>     env_production: {
>       NODE_ENV: "production",
>     },
>     watch: '.'
>   }, {
> 
>   }],

solved by

**before**
```
  apps : [{
    name: "API-NODE",
    script: "/var/www/api/api-nodejs/server.js",
    env: {
      NODE_ENV: "development",
    },
    env_production: {
      NODE_ENV: "production",
    },
    watch: '.'
  }, {
 // remove empty { }
  }], 
```

**after**
```
  apps : [{
    name: "API-NODE",
    script: "/var/www/api/api-nodejs/server.js",
    env: {
      NODE_ENV: "development",
    },
    env_production: {
      NODE_ENV: "production",
    },
    watch: '.'
  }],
```

**Comment by NickCarducci** [comment]
I fixed this error [[digital ocean droplet](https://github.com/NickCarducci/mastercard-backbank-digital-ocean/blob/maintenance/ReadMe.md)] by following the [pm2.keymatic instruction](https://pm2.keymetrics.io/docs/tutorials/using-transpilers-with-pm2). I assume "*all you have to do* is start the script, `pm2 start server.js`," fits all purposes (emphasis, mine!) ... for the single app. Seriously, forget `pm2 start ecosystem.config.cjs` and [babel-register](https://github.com/Unitech/pm2/issues/1643) transpiler will not say the following error:

>[PM2] Spawning PM2 daemon with pm2_home=/home/honcho/.pm2 [PM2] PM2 Successfully daemonized
> [PM2][WARN] Applications  not running, starting... [PM2][ERROR] Error: No script path - aborting.

````
{
  "main": "ecosystem.config.cjs",
  "scripts": {
    "start": ""
  },
  "dependencies": {
    "@babel/core": "^7.19.3",
    "@babel/preset-env": "^7.19.3",
    "babel-register": "^6.26.0",
    "express": "^4.18.1",
    "mastercard-locations": "^1.0.3",
    "pm2": "^5.2.0"
  }
}
````
no `ecosystem.config.js`, `pm2app.json`, nor even `package.json\main` the matter & I assume express working is not a fluke for this *on-the-fly development integration register*.

**Comment by boda-sh** [comment]
I have `type: module` in `package.json` with bun as interpreter. Writing my solution for anyone who find this:

- keep `module.exports` in the ecosystem file
- rename ecosystem to `cjs` extension
- use full path for script file, like so: `/home/user/app/index.ts`
