### ISSUE TITLE
Logs are useless without timestamps

### ISSUE THREAD

**Issue by brandonros** [Unitech/pm2#1977]
pm2 logs --timestamp doesn't _add_ timestamps to the previous logs.

What is the expected course of action when a user wants reference their past logs from pm2 processes? Without timestamps, it's difficult to decipher what matters and what doesn't.

**Comment by roccomuso** [comment]
+1

**Comment by developius** [comment]
It also breaks the specification for which log you specified:

```
$ pm2 logs 3
[TAILING] Tailing last 15 lines for [3] process (change the value with --lines option)
$ pm2 logs --timestamp 3
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
```

Note the `[all]`

**Comment by vmarchaud** [comment]
PM2 don't store at which time old logs has been logged, they are stored in the filesystem inside `~/.pm2/logs/` directory, you need to enable either [json logging](http://pm2.keymetrics.io/docs/usage/log-management/#directly-output-json-logs) (starting pm2 v2.4) or add the `log_date_format` [option](http://pm2.keymetrics.io/docs/usage/application-declaration/#log-files) to your application before you start them.
