### ISSUE TITLE
Tests (npm test) stops (OSX 10.11.3)

### ISSUE THREAD

**Issue by airs0urce** [Unitech/pm2#1978]
<img width="701" alt="screen shot 2016-02-28 at 3 59 24 pm" src="https://cloud.githubusercontent.com/assets/109203/13378293/6132de66-de34-11e5-85a9-c1e325e5756d.png">

Stops on "3) should trigger failure action". And it doesn't output anything for 10 min already

**Comment by Unitech** [comment]
Do you have any app listening on port 4322? Because this test spawn a "mock server" on that port

**Comment by airs0urce** [comment]
No, I don't have 
<img width="1232" alt="screen shot 2016-03-11 at 11 50 37 am" src="https://cloud.githubusercontent.com/assets/109203/13693630/8f4a7abc-e77f-11e5-9bd4-dbfb501b5747.png">

**Comment by Unitech** [comment]
It would be interesting to see what's buggy on Mac in that file https://github.com/Unitech/pm2/blob/master/test/interface/custom-actions.mocha.js
