### ISSUE TITLE
PM2 module system issues

### ISSUE THREAD

**Issue by bluejamesbond** [Unitech/pm2#1979]
While writing [BranchOff](https://github.com/bluejamesbond/BranchOff.js), I noticed some problems with the PM2/X module system. Upon @Unitech request, I am listing them here.

1. Imagine a pm2 module with a broken package.json (i.e. bad dependency version) but pm2 install <module_name> shows no error output
2. Better PM2 API error outputs. I have had several cases where pm2.start just splits out `{success: false}` without any error. However the app would run fine if just invoke it with the CLI i.e. `pm2 start app_name`
3. PM2 designated cache folder for temporary storage exposed as a conf variable perhaps i.e. conf.storageDir.
4. PM2 breaks arbitrarily and the uninstall/install process does not work because of missing/corrupted package.json in the `./pm2/node_modules`
5. PM2 restart loop is very challenging to break out off. Perhaps consider increasing in the default `min_uptime`
6. Is there a way to not strip out ansi-colors in pm2 logs? 
7. Sometimes pm2 publish does not commit and just freezes (happened once or twice at most)

**Comment by Unitech** [comment]
Some progress have been made for the PM2 module system, please check #2176 and let me know if it's better

**Comment by Unitech** [comment]
almost all features request has been implemented into pm2@next (rc)

```
$ npm install pm2@next -g
$ pm2 update
```

Thanks for this enhancement list,
