### ISSUE TITLE
how can i use iron-node with pm2?

### ISSUE THREAD

**Issue by giladv** [Unitech/pm2#1981]
hi!

i"m working with pm2 on development as well, the problem is that i want to use the iron-node debugger but i can seem to make it work here is what i tried
```
{

	"name": "backoffice",
	"exec_interpreter": "iron-node",
	"exec_mode": "fork",
	"script": "backoffice/bin/www",
	"node_args": "--debug",
	"watch": true,
	"ignore_watch": ["node_modules"],
	"autorestart": false,
	"env": {
		"NODE_ENV": "development"
	}
}
```

the app loads but without the iron-node debugger..

**Comment by Unitech** [comment]
Put the full path of iron-node in `exec_interpreter`

**Comment by giladv** [comment]
i tried that e.g "exec_interpreter": "/usr/local/bin/iron-node"
but iron-node does not seem to launch (it should open an inspector window)

thanks!

**Comment by Unitech** [comment]
You should better use iron-node just for debug (i do not see the point to use iron-node in a json declaration file)

**Comment by giladv** [comment]
i use pm2 for development as well so i can have the same setup for my dev env + reload capabilities.
i need a debugger in all times while developing.
how should i otherwise tackle that?
