### ISSUE TITLE
pm2 startup -u home directory should be the user specified with -u? 

### ISSUE THREAD

**Issue by pwang2** [Unitech/pm2#1984]
When running pm2 startup with -u USER, PM2_HOME is the user before sudo privilege escalation.   In most cases, we want the home directory to be the run user.  

```bash
sudo pm2 startup -u nodejs

## in /etc/init.d/pm2-init.sh
export PATH=/usr/bin:$PATH
export PM2_HOME="/home/myname/.pm2" #nodejs is expected here
```

**Comment by Unitech** [comment]
Could you just type `pm2 startup` and follow the indications? The resulted command add the option `--hp` that fix PM2_HOME

**Comment by pwang2** [comment]
Yes, it seems we need to pass the `--hp` explicitly always to fixed the home path. Making this as default seems make more sense.. 

Also, as below, the instruction will always refer current user's home even we pass `--hp` with `pm2 startup`.  If we cat the pm2-init.sh file, the home path is correct though. 
```
**[[vagrant@localhost ~]$** pm2 startup centos -u nodejs --hp /home/nodejs
[PM2] You have to run this command as root. Execute the following command:
      sudo su -c "env PATH=$PATH:/usr/bin pm2 startup centos -u nodejs --hp /home/vagrant"
**[vagrant@localhost ~]$** sudo !!
sudo pm2 startup centos -u nodejs --hp /home/nodejs
```

```
export PATH=/usr/bin:$PATH
export PM2_HOME="/home/nodejs/.pm2"
```

**Comment by estliberitas** [comment]
@pwang2 I was working on this - #1911 (this addition makes `pm2 startup` determine home directory of user specified via `-u` option). @Unitech reverted it, because there are some problems there AFAIK. I will have time to fix those bugs soon.

**Comment by pwang2** [comment]
Good to know. Thanks for the update.

**Comment by Cyclonecode** [comment]
Specifying a custom home path via `--hp` does not work at all. To make this work I instead set the path using the environment variable `export PM2_HOME=/path` which works fine.

**Comment by agopu** [comment]
> Specifying a custom home path via `--hp` does not work at all. To make this work I instead set the path using the environment variable `export PM2_HOME=/path` which works fine.

Same.

**Comment by vanitharc12** [comment]
PM2_HOME=/foldername/.pm2
Only pm2 save command creates a dump in .pm2 folder
 pm2 startup systemd -u name --hp /dirname, does not works for me for RHEL linux server. It shows the home directory of me
