### ISSUE TITLE
pm2 doesn't respect gid (group id)

### ISSUE THREAD

**Issue by akotlar** [Unitech/pm2#1989]
It looks like pm2 tries to set the group id to be the same as the user id. This is terribly inconvenient.

Running app using nodemon, node:

```
username proper_primary_group_name   43 Feb 29 11:57 file_name
```

pm2:

```
username    1001   43 Mar  1 13:46 file_name
```

where 1001 was once the user's group id (whose name was also username).

```
id username
#uid=1001(username) gid=1270(groupname_of_same_name)
```

Am I doing anything incorrectly?

**Comment by Unitech** [comment]
we do not override the gid anywhere: https://github.com/Unitech/pm2/search?utf8=%E2%9C%93&q=gid

**Comment by Nicholi** [comment]
Looks like the gid is overwritten here on line 719
https://github.com/Unitech/pm2/blob/358e98f664e5ce7b3183036219a7bf53642293af/lib/Common.js

If you use --uid it effectively removes --gid making it useless. It also overwrites with the user's primary group, meaning you can never use a secondary group the user is a member of.
