### ISSUE TITLE
any way to do stuffs upon receiving SIGKILL?

### ISSUE THREAD

**Issue by artofspeed** [Unitech/pm2#1992]
SIGKILL means immediate termination. In my knowledge we're not able to attach listener to it. However it would be helpful to do some cleanup upon receiving that signal. Is there a way in pm2 to trigger some other process or function upon receiving SIGKILL? Thanks!

**Comment by Unitech** [comment]
Please refer to the documentation: http://pm2.keymetrics.io/docs/usage/signals-clean-restart/
If you find any issue please report
