### ISSUE TITLE
Watch option array is not work

### ISSUE THREAD

**Issue by fyddaben** [Unitech/pm2#1993]
```
"watch": [ "app.js"],
```
when i touch `.gitignore`, it detected a file .gitignore changed

But i declear just watch app.js

**Comment by soyuka** [comment]
If you want to watch only app.js you can easily just give a string instead of an array. 
Did you properly stop and restart the whole process to get this change to work? I tried on my side and this works fine.

**Comment by fyddaben** [comment]
@soyuka  I  see. Its my wrong.
When i `pm2 stop all` and `pm2 start app.js`。The process not changed , it use the old ecosystem.json
And I must `pm2 delete all` and `pm2 start app.js`。the process can update by ecosystem.json
