### ISSUE TITLE
pm2 Application Declaration node_args does not work 

### ISSUE THREAD

**Issue by rongwj** [Unitech/pm2#1995]
my  JSON configuration file have "node-args": ["--nouse-idle-notification", "--expose-gc"], but when  i running the app,i get a error “global.gc is not a function”

**Comment by soyuka** [comment]
"node_args" in the json configuration https://github.com/Unitech/pm2/blob/0afe40a2d6968b2651ea6e17439d0030c3e73e37/lib/schema.json#L12
