### ISSUE TITLE
Unified out + error logs

### ISSUE THREAD

**Issue by bragma** [Unitech/pm2#1996]
Is it possible to configure pm2 for logging output and errors on the same file?

**Comment by soyuka** [comment]
Use the same file for both arguments?

**Comment by bragma** [comment]
@soyuka ouch, seems so easy I've never tried (blush)... :)

If you try, does it work as expected? We'll have 2 writers accessing the same file. May it happen that lines will overlap or it's impossible due to node's single thread nature. Moreover, will lines be flushed correctly preserving the temporal sequence of events?
Thanks!

**Comment by soyuka** [comment]
It get's easier:
```
    -l --log [path]                      specify entire log file (error and out are both included)
    -o --output <path>                   specify out log file
    -e --error <path>                    specify error log file
 ```

**Comment by soyuka** [comment]
ref https://github.com/pm2-hive/pm2-hive.github.io/pull/16

**Comment by ulrichb** [comment]
Hmm, .. neither `pm2 start someapp --log xxx.log` nor `pm2 start someapp -o xxx.log -e xxx.log` has an effect on my system. I always get `someapp-out.log` (+ the error log)

Using pm2 4.1.2 on Windows and use `pm2-logrotate`.

Any ideas?
