### ISSUE TITLE
Correct way to get process uptime from API

### ISSUE THREAD

**Issue by raine** [Unitech/pm2#1997]
`pm2.list()` returns list with objects that have keys `pm2_env.pm_uptime` and `pm2_env.created_at` and the values seem very similar if you restart a process. What's the difference and which one should be used?

**Comment by soyuka** [comment]
Main difference is:
- `pm_uptime` is initied every time there is a process restart. 
- `created_at` when the process get's in memory the first time

So, if you want the process uptime, you should use `pm_uptime`.

**Comment by IonutSanda** [comment]
apparently, the pm2_env.pm_uptime is the uptime of the pm2 process itself, and not the items in the pm2. Is there a way to get the uptime of each individual services in pm2?

**Comment by smor777** [comment]
> apparently, the pm2_env.pm_uptime is the uptime of the pm2 process itself, and not the items in the pm2. Is there a way to get the uptime of each individual services in pm2?

This is my question as well - @Unitech
