### ISSUE TITLE
node_args not passed in cluster mode

### ISSUE THREAD

**Issue by gergelykovacs** [Unitech/pm2#2000]
Hi,

node_args options are not applied hence e.g., GC stat cannot be made in cluster mode just in fork mode.

Please fix this bug to have the ability to test apps in cluster mode, as well.

Thank you!

**Comment by soyuka** [comment]
https://github.com/Unitech/pm2/issues/1995
Proof : https://github.com/Unitech/pm2/blob/431e4c4691d1371ddc55b46be10fd99644788fdc/lib/God/ClusterMode.js#L40

**Comment by gergelykovacs** [comment]
Hi @soyuka ,

please note that code segment referred by the link (previously I also checked) is not a proof, because if e.g.,
```
...
"exec_mode": "cluster",
"instances": process.env.NODE_PROXY_INSTANCES || 0,
...
```
section is present in `ecosystem.json` then e.g., `"node_args": "--trace_gc"` is omitted but when those 2 lines are removed to fall back to fork mode then GC trace data is immediately shown, so please investigate because node args are not passed.

Thanks in advance!

**Comment by Unitech** [comment]
Do you mean that the node_args option is not applied on ecosystem.json updates?

**Comment by Unitech** [comment]
```
$ npm install Unitech/pm2#development -g
$ pm2 update
```

**Comment by hkmarques** [comment]
Still seems like an issue today. I also tried the suggested version of pm2 to no avail.
When using cluster mode, the --debug option in node_args is rendered useless and I am unable to connect to the debug port. Simply changing to fork mode enables debugging again.

**Comment by hubermat** [comment]
Same for me. Just updated to the newest version 1.1.3 and it ignores the arguments in
pm2 start server.js --node-args="--trace_gc --max_old_space_size=512" -i max
