### ISSUE TITLE
4 threads

### ISSUE THREAD

**Issue by komarevtsevdn** [Unitech/pm2#2001]
Hi, i am using pm2 for my app. my app are divided for 4 mini app. for (ex app1.js app2.js app3.js app4.js 
My web server have 4 core. When i write pm2 start  app1.js app2.js app3.js app4.js, this will place 4 core of CPU or 1 core?

**Comment by Unitech** [comment]
The system will handle itself the process balancing between the 4 cores. But if you have one application (let's say api.js) that exposes HTTP/TCP/UDP routes you can use the cluster mode so you are sure that this application can use the 4 cores instead of one
