### ISSUE TITLE
How to run NPM script upon start/ restart?

### ISSUE THREAD

**Issue by gajus** [Unitech/pm2#2003]
I need to run NPM build script when file change is detected (which is equal to restart).

I have tried:

``` json
{
    "apps": [
        {
            "name": "ad-app",
            "script": "npm run build; ./devServer.js",
            "watch": [
                "./devServer.js",
                "./webpack.config.common.js",
                "./webpack.config.development.js"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "autorestart": false,
            "restart_delay": 1000
        }
    ]
}
```

but that did not work. I am getting:

```
[PM2][ERROR] script not found : /Users/gajus/Documents/dev/applaudience/showtime-ad-app/npm run build; ./devServer.js
script not found : /Users/gajus/Documents/dev/applaudience/showtime-ad-app/npm run build; ./devServer.js
```

**Comment by gajus** [comment]
My example is missing `node` before `./devServer.js`.

**Comment by tnrich** [comment]
I'm getting a similar error: 
```
[PM2][ERROR] script not found : /opt/bitnami/apps/EST/npm run buildAndRunProduction
script not found : /opt/bitnami/apps/EST/npm run buildAndRunProduction
```

for my config: 
```
{
  "apps" :
  [
    {
      "exec_interpreter"   : "node",
      "exec_mode"          : "cluster_mode",
      "instances"          : "1",
      "name"               : "EST",
      "script"             : "npm run buildAndRunProduction",
      "post_update"        : ["echo App has been updated, running npm install...",
                              "npm install",
                              "echo App is being restarted now"],
      "exec_timeout"       : 30000
    }
  ]
}
```

@gajus, why did adding `node` in front of `./devServer.js` help ?

**Comment by gajus** [comment]
Wrongly closed issue. I still have it.

**Comment by Unitech** [comment]
The `script` attribute is only to specify the main entry point of your application.
Then the `args` attribute allows to pass arguments.

For example to can call npm start:

```
{
    "apps": [
        {
            "name": "ad-app",
            "script": "npm",
            "args" : "start",
            "autorestart": false,
            "restart_delay": 1000
        }
    ]
}
```

http://pm2.keymetrics.io/docs/usage/application-declaration/

**Comment by centigrade-thomas-becker** [comment]
@gajus Did this work for you?

I tried to start my module with `"script": "npm"` and `"args": "start"`, but the process failed to start. I have the following error in my log files: 

```
2016-10-11 12:07:58: SyntaxError: Unexpected token :
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function._load (C:\Users\username\AppData\Roaming\npm\node_modules\pm2\node_modules\pmx\lib\transaction.js:62:21)
    at Object.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\pm2\lib\ProcessContainerFork.js:46:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```

**Comment by Jeff-Tian** [comment]
@centigrade-thomas-becker  I met your same issue on windows, and tried @gajus 's solution in ubuntu again, it works like a charm!

**Comment by virajvg** [comment]
@Unitech like @centigrade-thomas-becker mentioned i am facing the exact same issue on windows, is there any resolution for this ?

**Comment by juliocesardemoraes** [comment]
guys I'm a bit late for the discussion but here's my solution for nested apps. Just a little improvement from the other suggestions, I use on this one the cwd for specifying the path, and the args to choose my script. My script pm2start is a command for building and after that running the application.

`module.exports = {
  apps: [
    {
      name: "api-customer.blackz.pro/v1",
      script: "npm",
      cwd: "/api-customer.blackz.pro/v1/",
      args: "run pm2start",
      autorestart: false,
      restart_delay: 1000,
    },
    {
      name: "api-editor.blackz.pro/v1",
      script: "npm",
      cwd: "/api-editor.blackz.pro/v1/",
      args: "run pm2start",
      autorestart: false,
      restart_delay: 1000,
    },
  ],
};
`

and on my pm2start script for both my projects I run the build for my app and the start
`
    "pm2start": "tsc --project tsconfig.json && tscpaths -p tsconfig.json -s ./src -o ./dist && node ./dist/server.js --env=production",
`

Works like a charm!
