### ISSUE TITLE
Specify dependency order in config file?

### ISSUE THREAD

**Issue by geuis** [Unitech/pm2#2010]
Getting up and running with pm2 today. I'm running 2 applications, a web server and an api server. The web server can't get started until the api server is ready.

I've been through the pm2 docs but I don't see a way to specify the order in which groups of applications should be started. Is there a way?

**Comment by Unitech** [comment]
I don't see any way how PM2 could help you do this, if you have any idea to configure that via JSON application declaration i'm listening. Anyway it may be better to handle this programmatically (the api server sends a message to the webserver).

**Comment by Unitech** [comment]
feel free to re-open if any idea

**Comment by geuis** [comment]
I'll take another look at this later and see if I can recommend anything.
