### ISSUE TITLE
node.js's process.stderr.write or process.stdout.write behavier changed by pm2

### ISSUE THREAD

**Issue by tangxinfa** [Unitech/pm2#2011]
node.js's define:

    bool write(chunk[, encoding][, callback])

see [node.js doc](https://nodejs.org/api/stream.html#stream_writable_write_chunk_encoding_callback)

overwrite by pm2 with:

    void write(chunk[, encoding][, fd])             // fd is unused.

see [pm2 source code](https://github.com/Unitech/pm2/blob/master/lib/ProcessContainer.js#L148)

there is no return value to indicate writed data buffered internally, and the callback never called:(

**Comment by Unitech** [comment]
PR welcome :)
