### ISSUE TITLE
Enter command inside node.js script running (and view the console) via pm2

### ISSUE THREAD

**Issue by Ogarunite** [Unitech/pm2#2014]
Hi, when I start a node.js server via pm2 start server.js I can't actually see the output from the server.js, and I can't either type any commands in via pm2 to the server.js from the console. 
How can i view the output from server.js and type commands into server.js when running it via pm2?

**Comment by Unitech** [comment]
To view the output of server.js, just check the logs via `pm2 logs server`.

You cannot attach the standard input of your application to the current terminal.

**Comment by Ogarunite** [comment]
Okay thanks, that worked! So i cannot enter commands into it somehow? Only view the logs?

**Comment by roblav96** [comment]
Ye, I'd like to use `process.stdin` while viewing logs from `pm2 logs`.

Example:
```javascript
process.stdin.resume()
process.stdin.setEncoding( "ascii" )
process.stdin.on( "data", function ( input ) {
	console.info( 'input >' )
	inspect( input )
	let argz = input.split( ' ' )
	argz[ argz.length - 1 ] = argz[ argz.length - 1 ].replace( /\n/g, '' )
	let fn = argz.splice( 0, 1 )
	if ( _.isFunction( coms[ fn ] ) ) {
		coms[ fn ]( argz )
	} else {
		console.log( 'INVALID COMMAND\n' )
	}
} )
```
