### ISSUE TITLE
Cant use an application name "*push*"

### ISSUE THREAD

**Issue by daraghking** [Unitech/pm2#2018]
Not allowed "push", "my_push", etc....

from [issue 1764](https://github.com/Unitech/pm2/issues/1764) it seems you can't call your application "push" but there is no reason given to block every other application name containing the letters "push".

I will do a PR to change this if there is a chance it will be merged.

**Comment by estliberitas** [comment]
@daraghking Well, I thought I already fixed this by #1910 .

/cc @Unitech @soyuka

**Comment by Unitech** [comment]
I would prefer to keep the legacy cli-table module, now I will just restrict the "push" name instead of "*push*"
