### ISSUE TITLE
blank spaces issue

### ISSUE THREAD

**Issue by roccomuso** [Unitech/pm2#2022]
I've noticed a weird behaviour using the JSON configuration file.

Let me show you an example:

- I have a node.js app accepting CLI parameters.
ex. <code>my_app -s /dev/ttyUSB0</code>

Now, if I do something like that:

<code>pm2 start my_app -- -s /dev/ttyUSB0</code>

Everything works great.

But If I use a JSON configuration file, with an <code>args</code> array:

    {
        "name": "my_app",
        "script": "my_app",
        "args": ["-s /dev/ttyUSB0"]
    }

The arguments is not well parsed.
I'll have " /dev/ttyUSB0" instead of "/dev/ttyUSB0". Just notice the blank space.

We get this behaviour when using a JSON configuration file.

**Comment by Unitech** [comment]
Can you remove the brackets around the args value

**Comment by roccomuso** [comment]
I've seen the brackets in the example, are they wrong? Should examples be updated?

**Comment by roccomuso** [comment]
This bug makes the **yargs** module not working properly if using the ''number'' type, because yargs won't parse " 80" as number but instead gives ***NaN***.

      .option('port', {
        alias: 'p',
        demand: false,
        describe: 'HTTP Server Port.',
        type: 'number'
       })

**Comment by Unitech** [comment]
"args": ["-s", "/dev/ttyUSB0"]
