### ISSUE TITLE
PM2 on jessie not dumping processes on reboot.

### ISSUE THREAD

**Issue by zettam** [Unitech/pm2#2023]
When I do a manual dump as "pm2 dump" and restart the system, it works perfectly. But anything that's not manually dumped is not autostarting.

I've installed pm2 startup scipt by typing
sudo pm2 startup -u pi

(raspbery pi 3)

**Comment by zettam** [comment]
update:
When the machine is reloaded via sudo reboot apps do not load into pm2. However when the machine is turned off without any commands(direct power off) everything loads perfectly. How is this possible?

**Comment by zettam** [comment]
Any comments, ideas, updates would be appreciated!

**Comment by Unitech** [comment]
Yes you need to do a pm2 dump once you have the list of processes you want to keep across restart

https://github.com/Unitech/pm2/issues/2559
