### ISSUE TITLE
Strange request distribution under load using cluster mode

### ISSUE THREAD

**Issue by nodesocket** [Unitech/pm2#2027]
**Running PM2 v0.15.10.**

Looking at `htop` when our web app was under load, the load seems to be exclusive on a single node process instead of balancing out across all the node processes in cluster mode.

<img width="942" alt="screen shot 2016-03-16 at 11 07 50 pm" src="https://cloud.githubusercontent.com/assets/523312/13837817/2ce84a38-ebcc-11e5-9721-cbef574e2b6a.png">

Might need to post a video to show, but the load was consistently on this single process, did not switch to others.

Is this expected behavior? I would have expected to see the load swapping back between all the node processes in the cluster.

**Comment by nodesocket** [comment]
Here is a another screenshot notice the process CPU times.

12:09.16 *(this process was heavily favorited)*
4:42.04
9:02.79
3:04.68
2:01.54

<img width="811" alt="screen shot 2016-03-16 at 11 13 34 pm" src="https://cloud.githubusercontent.com/assets/523312/13837905/fcba6980-ebcc-11e5-9422-2ac52a21e966.png">

**Comment by nodesocket** [comment]
Updated pm2 to **1.0.2** and the load seems be much more evenly distributed.

**Comment by soyuka** [comment]
@nodesocket Know that pm2 is using the [nodejs cluster module](https://nodejs.org/api/cluster.html). This means that load distribution is not handled by pm2 but rather by the [nodejs RoundRobin algorithm](https://github.com/nodejs/node/blob/66f4586dd031435984ed77837512531dfc4fe893/lib/cluster.js#L102).

If you want an alternative, or a better way to handle load distribution you'll have to check other load-balancers, which can be easily integrated with pm2 ;).

**Comment by nodesocket** [comment]
Just wanted to update that load seems to be much more even distributed now (running 8 workers on an 8 cpu instance). Perhaps updating to 1.0.2 helped, but not exactly sure.

![screen shot 2016-03-28 at 11 30 36 am](https://cloud.githubusercontent.com/assets/523312/14086216/d4dc52f6-f4d8-11e5-9f9c-97d2efd88d00.png)
