### ISSUE TITLE
_old_0 or similar process id in the cluster mode

### ISSUE THREAD

**Issue by bhanuV** [Unitech/pm2#2028]
Hello I am using pm2 api to perform start, stop, delete, list and other pm2 operations
pm2 1.0.2
node 4.2.1
Ubuntu 14.04

In this case, pm2 stop and  delete api are called after one another, the start api call does not work. Because of a pm2 process which has process id such as  **_old_0**, **_old_1** or **_old_2** so on. 
So I tried killing them if any before the start api is called, but the another process pops up within the time gap of killing any process having process id _old_0 or similar and start of the pm2 api making the start api not able to start.

I am using pm2 in cluster mode

The screenshot of the pm2 list
![pm2_old_0](https://cloud.githubusercontent.com/assets/3939149/13841362/8a9feb5e-ec4e-11e5-8303-949c189a05e0.png)

Can you please tell me why these processes are created? and how to get rid of them.

Thanks.

**Comment by sharmaankush8993** [comment]
Can u pls mention the steps that can help me to reproduce the above scenario on my local system?

**Comment by bhanuV** [comment]
I had created a JavaScript file with pm2 api where every function was accessible from the command line mode and takes input for start, stop, delete of pm2. Later used the same file for automatic start and stop of the process if there was a git update in the project.
Unfortunately it didn't work due to the error caused as stated above.

**Comment by vmarchaud** [comment]
Note that you should not have them listed with newer version of PM2 (they are temporary process pm2 use when restarting one)

**Comment by extensionsapp** [comment]
@vmarchaud Hello.
My log PM2. Every second "Unknown id _old_1"

![e5a5a4c59ff754bd8516979e77318126](https://user-images.githubusercontent.com/8192379/30703622-e689e0f6-9ef8-11e7-88a6-1cc92724f041.gif)

My process.json

```
{
  "apps" : [{
    "name" : "example.com",
    "script" : "/home/example.com/app.js",
    "instances" : "max",
    "exec_mode" : "cluster",
    "cwd" : "/home/example.com",
    "error_file" : "/home/example.com/log/err.log",
    "out_file" : "/home/example.com/log/out.log",
    "node_args" : "--max-old-space-size=768",
    "max_memory_restart" : "768M",
    "watch" : true,
    "ignore_watch" : [
      "process.json"
    ],
    "watch_options" : {
      "followSymlinks": false
    },
    "vizion" : false
  }]
}
```

**Comment by rambo-panda** [comment]
@extensionsapp me too

**Comment by imjeffparedes** [comment]
Does it mean that we cant use reload because of this?

**Comment by jesusvera-tabled** [comment]
This just happened to me. A `pm2 restart` solves the problem, but this affects the purpose of using `reload` for zero downtime.
