### ISSUE TITLE
"save" not working on system reboot

### ISSUE THREAD

**Issue by zettam** [Unitech/pm2#2032]
So I've installed nvm and installed node 5.9.0.
Then globally instlaled pm2.

created my startup script

pm2 starts on system boot but it does not fire any apps.

Then I checked it, if it's saving or not, by manually doing "pm2 save"
At this point when I restart the system it boots the saved apps!

the problem is that, if I don't do the save manually it just forgets the final state of everything running every time the system is booted. Is this normal? Is the behavior changed?

**Comment by tacoben** [comment]
as far as i can tell this is how the npm version currently works.  The save function creates a file of some sort under .pm2 directory in the user/install directory... this file can be set to be immutable and  then you can survive a restart...

sudo chattr +i /home/$USER/.pm2/dump.pm2

**Comment by zettam** [comment]
Hm this does not make sense,

So currently, when we start scripts, isn't it auto saved for restarts? Do we have to run the save command on every platform?

**Comment by mkozjak** [comment]
chattr didn't help. i did pm2 startup && pm2 save after running processes manually. pm2 is not starting on boot.

**Comment by Unitech** [comment]
https://github.com/Unitech/pm2/issues/2559

**Comment by RicardoZap** [comment]
Una disculpa por comentar en español en un foro en Inglés pero encontré la solución al problema.
Ami me funcionó ejecutando el siguiente método:

1.- pm2 start "ejemplo.js"
2.- pm2 save
3.- pm2 startup
4.- sudo env PATH=$PATH:/usr/bin /usr/local/lib/node_modules/pm2/bin/pm2 startup systemd -u pi --hp /home/pi

Después de ejecutar lo anterior hacer un "sudo reboot" y con eso el problema queda resuelto. Saludos.

**Comment by azaelvaldo** [comment]
> Una disculpa por comentar en español en un foro en Inglés pero encontré la solución al problema.
> Ami me funcionó ejecutando el siguiente método:
> 
> 1.- pm2 start "ejemplo.js"
> 2.- pm2 save
> 3.- pm2 startup
> 4.- sudo env PATH=$PATH:/usr/bin /usr/local/lib/node_modules/pm2/bin/pm2 startup systemd -u pi --hp /home/pi
> 
> Después de ejecutar lo anterior hacer un "sudo reboot" y con eso el problema queda resuelto. Saludos.

This helped me a lot, only i did evertything except step 4 and it worked after reboot.
