### ISSUE TITLE
Question: Cluster mode: processes communication

### ISSUE THREAD

**Issue by StyleT** [Unitech/pm2#2044]
How I can register/unregister application which is running in cluster mode in load balancer? I need to detect somehow master process and do this action only once for the whole cluster. And remove app from LB when the last cluster minion is ready to exit. 

I'm using json environment configuration for PM2.

**Comment by akaNightmare** [comment]
up

**Comment by richcem** [comment]
the same question!

**Comment by soyuka** [comment]
Maybe this example can help: https://github.com/Unitech/pm2/blob/aab0221f7f0c60f45a93e0fc1b3fd6555fce947c/examples/udp-cluster.js

**Comment by EddieOne** [comment]
pm2 is a wrapper for [node cluster](https://nodejs.org/api/cluster.html).  Sounds like you want to write the master process instead of using pm2 as the controller. It's surprisingly easy to do in node. There will usually be some gotchas like, how to know if a child needs to be restarted.
