### ISSUE TITLE
Question: how to not suppress windows created by pm2 daemon process?

### ISSUE THREAD

**Issue by malcoriel** [Unitech/pm2#2047]
After upgrading my pm2 to 1.0.2 I found that it wonderfully hides all annoying console windows that were popping up before (in v0.x) when launching apps. However, this improvement added unexpected annoyance - now my chrome windows (pm2 -> selenium -> chromedriver -> chrome) also do not pop up! I launch my selenium server via pm2, and now that makes my tests harder to debug since I cannot see what's going on.

How can I configure old behavior or do some workarounds for a specific app managed by pm2?

Info:
pm2 --version 1.0.2
node --version v5.7.0
OS Win10 Professional x64

Selenium app config I use: 

```
{
  "apps": [
    {
      "name": "selenium-server",
      "script": "./node_modules/selenium-server/bin/selenium",
      "args": ["-Dwebdriver.chrome.driver=./node_modules/chromedriver/lib/chromedriver/chromedriver.exe"]
    }
  ]
}

```

**Comment by Amzul** [comment]
we have similar issue on version 0.14.7
on windows server 2012 (aws instance) 

every CMD application is killed 👎

**Comment by malcoriel** [comment]
@Amzul They are not killed, but hidden. In fact, this is desired behavior - but in some cases we need to override it.
