### ISSUE TITLE
linux core error

### ISSUE THREAD

**Issue by fastid** [Unitech/pm2#2051]
Mar 13 10:17:30 localhost kernel: node /var/www/s: page allocation failure. order:2, mode:0x20
Mar 13 10:17:30 localhost kernel: Pid: 45224, comm: node /var/www/s Not tainted 2.6.32-358.el6.x86_64 #1
Mar 13 10:17:30 localhost kernel: Call Trace:
Mar 13 10:17:30 localhost kernel: [<ffffffff8112c127>] ? __alloc_pages_nodemask+0x757/0x8d0
Mar 13 10:17:30 localhost kernel: [<ffffffff811669d2>] ? kmem_getpages+0x62/0x170
Mar 13 10:17:30 localhost kernel: [<ffffffff811675ea>] ? fallback_alloc+0x1ba/0x270
Mar 13 10:17:30 localhost kernel: [<ffffffff8116703f>] ? cache_grow+0x2cf/0x320
Mar 13 10:17:30 localhost kernel: [<ffffffff81167369>] ? ____cache_alloc_node+0x99/0x160
Mar 13 10:17:30 localhost kernel: [<ffffffff81168530>] ? kmem_cache_alloc_node_trace+0x90/0x200
Mar 13 10:17:30 localhost kernel: [<ffffffff8116874d>] ? __kmalloc_node+0x4d/0x60
Mar 13 10:17:30 localhost kernel: [<ffffffff8143d6ad>] ? __alloc_skb+0x6d/0x190
Mar 13 10:17:30 localhost kernel: [<ffffffff8143e7c6>] ? skb_copy+0x36/0xa0
Mar 13 10:17:30 localhost kernel: [<ffffffffa01186cc>] ? tg3_start_xmit+0xa8c/0xd50 [tg3]
Mar 13 10:17:30 localhost kernel: [<ffffffff81448ca8>] ? dev_hard_start_xmit+0x308/0x530
Mar 13 10:17:30 localhost kernel: [<ffffffff81466fca>] ? sch_direct_xmit+0x15a/0x1c0
Mar 13 10:17:30 localhost kernel: [<ffffffff8144c9b0>] ? dev_queue_xmit+0x3b0/0x550
Mar 13 10:17:30 localhost kernel: [<ffffffffa01c7ed7>] ? bond_dev_queue_xmit+0x67/0x200 [bonding]
Mar 13 10:17:30 localhost kernel: [<ffffffffa01cefd9>] ? bond_3ad_xmit_xor+0x1c9/0x220 [bonding]
Mar 13 10:17:30 localhost kernel: [<ffffffffa01c812b>] ? bond_start_xmit+0xbb/0x5d0 [bonding]
Mar 13 10:17:30 localhost kernel: [<ffffffff81448ca8>] ? dev_hard_start_xmit+0x308/0x530
Mar 13 10:17:30 localhost kernel: [<ffffffff81474609>] ? nf_iterate+0x69/0xb0
Mar 13 10:17:30 localhost kernel: [<ffffffff8144c805>] ? dev_queue_xmit+0x205/0x550
Mar 13 10:17:30 localhost kernel: [<ffffffff81484f40>] ? ip_finish_output+0x0/0x310
Mar 13 10:17:30 localhost kernel: [<ffffffff8148507c>] ? ip_finish_output+0x13c/0x310
Mar 13 10:17:30 localhost kernel: [<ffffffff81485308>] ? ip_output+0xb8/0xc0
Mar 13 10:17:30 localhost kernel: [<ffffffff814845cf>] ? __ip_local_out+0x9f/0xb0
Mar 13 10:17:30 localhost kernel: [<ffffffff81484605>] ? ip_local_out+0x25/0x30
Mar 13 10:17:30 localhost kernel: [<ffffffff81484ae0>] ? ip_queue_xmit+0x190/0x420
Mar 13 10:17:30 localhost kernel: [<ffffffff814997ce>] ? tcp_transmit_skb+0x3fe/0x7b0
Mar 13 10:17:30 localhost kernel: [<ffffffff8149bb8b>] ? tcp_write_xmit+0x1fb/0xa20
Mar 13 10:17:30 localhost kernel: [<ffffffff8149c540>] ? __tcp_push_pending_frames+0x30/0xe0
Mar 13 10:17:30 localhost kernel: [<ffffffff8148bdbe>] ? tcp_push+0x6e/0x90
Mar 13 10:17:30 localhost kernel: [<ffffffff8148cdbc>] ? tcp_sendmsg+0x64c/0xa20
Mar 13 10:17:30 localhost kernel: [<ffffffff81437b9b>] ? sock_aio_write+0x19b/0x1c0

Mar 25 13:31:56 localhost kernel: Pid: 3665, comm: node /var/www/s Not tainted 2.6.32-358.el6.x86_64 #1
Mar 25 13:31:56 localhost kernel: <IRQ>  [<ffffffff8112c127>] ? __alloc_pages_nodemask+0x757/0x8d0
Mar 25 13:31:56 localhost kernel: [<ffffffff81167369>] ? ____cache_alloc_node+0x99/0x160
Mar 25 13:31:56 localhost kernel: [<ffffffff81168530>] ? kmem_cache_alloc_node_trace+0x90/0x200
Mar 25 13:31:56 localhost kernel: [<ffffffff8116874d>] ? __kmalloc_node+0x4d/0x60
Mar 27 01:46:19 localhost kernel: PM2 v0.14.3: Go[9839] general protection ip:99f6c8 sp:7ffffb636ae0 error:0 in node[400000+fcc000]
Mar 27 01:46:19 localhost abrt[36035]: Saved core dump of pid 9839 (/usr/local/bin/node) to /var/spool/abrt/ccpp-2016-03-27-01:46:19-9839 (114114560 bytes)
Mar 27 01:46:21 localhost abrtd: Executable '/usr/local/bin/node' doesn't belong to any package

node: v0.12.7
pm2:  v0.14.3

**Comment by Unitech** [comment]
Upgrade PM2 to latest, this issue has been fixed long time ago
