### ISSUE TITLE
pm2-init.sh "Comman not found" error

### ISSUE THREAD

**Issue by dberansky** [Unitech/pm2#2055]
installed pm2-init.sh with the following command:

`sudo pm2 startup ubuntu -u sa`

modified the script to fix the PM2_HOME directory to point to the right location

when I run `sudo service pm-init.sh status` I get the following error:

> ~$ sudo service pm2-init.sh status
> Status for pm2:
> PATH=/usr/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/share/anaconda/bin: Command not found.
> PM2_HOME=/usr2/sa/.pm2: Command not found.

I get this error for any `service` command really: `start`, `stop`, etc.

Ubuntu: v14.04
pm2: v1.0.2

**Comment by iongion** [comment]
I get the same

```pm2 --no-color startup ubuntu -u $USR_NAME --hp $USR_HOME```

I see that the `/etc/init.d/pm2-init.sh` file is empty on Ubuntu 12.04, 14.04, 16.04
I solve it by copying my own template file there ... ugly!

**Comment by vmarchaud** [comment]
We are currently refactoring the system, see #2559

**Comment by Unitech** [comment]
There is no more pm2-init.sh (renamed as pm2 on /etc/init.d/pm2) on the new PM2 version, see #2559
