### ISSUE TITLE
numerous "/usr/bin/pm2 logs" orphan processes

### ISSUE THREAD

**Issue by diginfo** [Unitech/pm2#2056]
I was just figuring out where all my memory had gone and noticed that I had around 30 "/usr/bin/pm2 logs" processes running all consuming roughly 1% of memory each.

I was the only user logged in and was not viewing the logs, so the only thing I can think of is that pm2 logs continues to run when a either a shell gets disconnected or the services are restarted while the logs were running.

How can I prevent this ?

**Comment by Unitech** [comment]
were you using pm2 logs and got disconnected from SSH?
