### ISSUE TITLE
pm2-init fails on fish shell

### ISSUE THREAD

**Issue by mooyoul** [Unitech/pm2#2058]
<img width="1594" alt="2016-04-01 5 45 33" src="https://cloud.githubusercontent.com/assets/2101743/14198192/4a370d98-f812-11e5-98f4-0a406872669e.png">

PM2 Startup script (pm2-init.sh) fails on system startup if system default shell is [fish shell](http://fishshell.com/).

Due to [this issue](https://github.com/fish-shell/fish-shell/issues/438), fish shell recommends using `env` command when set inline envrionment variables.

Like this:

``` bash
env PM2_HOME=/foo/bar node foo.js
```

So, My suggestion is:
Adding `env` command before set inline environment variables for compatibility.

**Comment by Unitech** [comment]
https://github.com/Unitech/pm2/issues/2559
