### ISSUE TITLE
Error: unsupported git service

### ISSUE THREAD

**Issue by zyg-github** [Unitech/pm2#2059]
http://ikt.pm2.io/ikt.git 
Error: unsupported git service

**Comment by Unitech** [comment]
git ikt dependency replaced with gkt tgz dependency

https://github.com/Unitech/pm2/commit/adcfa078b1061e126d68a919ee02461f53d38f7d

Available in PM2 V2:

```bash
$ npm install Unitech/pm2#development -g
$ pm2 update
```
If there is still a problem, please reopen issue
