### ISSUE TITLE
startOrRestart differ from start

### ISSUE THREAD

**Issue by wesleycoder** [Unitech/pm2#2062]
I'm trying to daemonize a [chokidar](https://github.com/capaj/chokidar-socket-emitter) server, but pm2 complains if I use `startOrRestart`.

#### Steps to reproduce:

1. `npm i chokidar-socket-emitter`
2. `pm2 start ./node_modules/chokidar-socket-emitter/cli.js`
this goes ok

3. `pm2 startOrRestart ./node_modules/chokidar-socket-emitter/cli.js`
this throws an error due a shebang in the cli.js:
```
evalmachine.<anonymous>:1
(#!/usr/bin/env node
 ^

SyntaxError: Unexpected token ILLEGAL
    at Object.exports.runInThisContext (vm.js:53:16)
...
```

**Comment by alexindigo** [comment]
`pm2 startOrRestart` – expects pm2 config json file.

**Comment by wesleycoder** [comment]
Oh, thanks! I didn't realize this.
