### ISSUE TITLE
'pm2 list' output nothing after pm2 start ./bin/www

### ISSUE THREAD

**Issue by beysion** [Unitech/pm2#2063]
'pm2 list' output nothing after pm2 start ./bin/www
why no response, who knows it, thanks

windows

**Comment by WindWen** [comment]
+1

**Comment by vmarchaud** [comment]
@beysion Can you give your node/pm2/windows version ?

**Comment by vmarchaud** [comment]
No update, working great with `pm2@next` and working in node from 0.10 to 6.x, re-open if you still have the issue.

**Comment by sanpupi** [comment]
+1
