### ISSUE TITLE
Provide way to change daemon configs without kill

### ISSUE THREAD

**Issue by kevinmstephens** [Unitech/pm2#2065]
As far as I can tell, the daemon loads configs from `constants.js` at daemon launch time and never again. 

If there is a need to change a settings, for example `GRACEFUL_TIMEOUT`, I have to kill the daemon and restart it with the new settings which takes down my application. 

I suggest a way to allow updating deamon configs in a way that will not stop the applications it runs.

**Comment by Unitech** [comment]
http://pm2.keymetrics.io/docs/usage/signals-clean-restart/#customize-exit-delay

Cheers

**Comment by francescozanoni** [comment]
Hi,
I've tried, but the `#customize-exit-delay` section is not available on the page.
Where could it be?
Thanks,

Francesco
