### ISSUE TITLE
multiple instances of same process running on diff ports not working

### ISSUE THREAD

**Issue by siddo420** [Unitech/pm2#2067]
I already have an external load balancer that distributes load on multiple instances on different ports. However, the app script file is always the same with env vars used to distinguish.

For example, here is how I used to start multiple instances using nodemon:
```
LEVEL=debug NODE_ENV=production PORT=3001 nodemon app.js
LEVEL=debug NODE_ENV=production PORT=3000 nodemon app.js
```
But, this does not seem to work although I tried using different names:
```
LEVEL=debug NODE_ENV=production PORT=3001 TZ=UTC pm2 start app.js --name="app-3001" --watch
```
The above works but as soon as I try the following I get an error:
```
LEVEL=debug NODE_ENV=production PORT=3000 TZ=UTC pm2 start app.js --name="app-3000" --watch
[PM2][ERROR] Script already launched, add -f option to force re-execution
```
Should I add -f? Or, use symlinks? 

How do I go about doing this using .json files?

**Comment by knight00931** [comment]
Saw this somewhere else, `var port = 3000 + Number(process.env.NODE_APP_INSTANCE);`
and then declare your instance number in json file, the first instance will run on port 3000, then 3001, 3002, etc.

**Comment by siddo420** [comment]
Thanks.

I'll try and let you know.

**Comment by siddo420** [comment]
seems to work ... closing
