### ISSUE TITLE
Node processes still running but not listed in pm2

### ISSUE THREAD

**Issue by PaddyMann** [Unitech/pm2#2068]
I've fired up pm2 running 4 node processes, and at various times have called `pm2 delete all` and `pm2 kill`.

I've managed to get to a position whereby `pm2 list` no longer lists any processes, but 4 node processes are still running. If I kill the node processes directly then they are auto-restarted, but I can't control this outside of pm2. Furthermore, I can't kick up new processes in pm2 as the IP+port conflicts.

Is this a bug, or something I've missed? How can I kill the node processes and give control back to pm2?

**Comment by Unitech** [comment]
pm2 version?

**Comment by PaddyMann** [comment]
1.0.2

Have updated to 1.1.1 and it now appears fixed - thanks :)
