### ISSUE TITLE
Deprecate gracefulReload

### ISSUE THREAD

**Issue by Unitech** [Unitech/pm2#2069]
Deprecate gracefulReload commands from CLI/Daemon.

> When a process is stopped/restarted by PM2, some system signals are sent to your process in a given order.
First a SIGINT a signal is sent to your processes, signal you can catch to know that your process is going to be stopped. If your application does not exit by itself before 1.6s (customizable) it will receive a SIGKILL signal to force the process exit.

http://pm2.keymetrics.io/docs/usage/signals-clean-restart/

It's a much better way to handle connection problem on reload etc. It's also usable in both fork and cluster mode.

http://pm2.keymetrics.io/docs/usage/cluster-mode/

**Comment by jamiemcconnell** [comment]
I assume that the better way is just to use `pm2 reload`? and handle it in my app?

**Comment by Unitech** [comment]
Yes via SIGINT

http://pm2.keymetrics.io/docs/usage/signals-clean-restart/
