### ISSUE TITLE
Can't install any version of pm2

### ISSUE THREAD

**Issue by shaikatzir** [Unitech/pm2#2072]
All my attempts of installing pm2 encountered the following error:
npm ERR! registry error parsing json
npm ERR! SyntaxError: Unexpected token

Every time on a different package.
I tried the following versions:
1.0.2
0.15.8
0.14.7

**Comment by florianbeer** [comment]
Same here, is npm currently broken?

**Comment by shaikatzir** [comment]
I think there is some problem with async@1.4.2

**Comment by florianbeer** [comment]
I guess it's related to a node version that's too old to deal with gzip'ed responses, which the npm folks tried to test: https://github.com/npm/npm/issues/12196#issuecomment-205855393

**Comment by shaikatzir** [comment]
I guess so
