### ISSUE TITLE
1.1.1: PID in status doesn't match actual PID 

### ISSUE THREAD

**Issue by jcollum** [Unitech/pm2#2074]
```
$ pm2 --version
1.1.1

$ ps ax | grep node
...
17268 ?        Sl     0:01 node --max-old-space-size=4096 ./node_modules/dafds/dist/start.js config.yaml # this is the process running with pm2

$ pm2 ls 
┌─────────────────────────────┬────┬──────┬───────┬─────────┬─────────┬────────┬─────────────┬──────────┐
│ App name                    │ id │ mode │ pid   │ status  │ restart │ uptime │ memory      │ watching │
├─────────────────────────────┼────┼──────┼───────┼─────────┼─────────┼────────┼─────────────┼──────────┤
│ job-processor               │ 5  │ fork │ 17224 │ online  │ 0       │ 2m     │ 33.906 MB   │ disabled │

```

Why does the PID reported by PM2 not match the PID reported by `ps ax`? This causes issues because the RabbitMQ library I use tracks connections according to their PID. But the PID that PM2 is reporting is always off by a little bit.

**Comment by soyuka** [comment]
Hmm, my pid's matches my node processes. Are you sure this isn't a child process of your own process?

**Comment by jcollum** [comment]
Could using npm start have something to do with it?

**Comment by jcollum** [comment]
OK it appears that when you use `npm start`  (e.g. `pm2 start npm --no-automation --name=$packageName -- start`) the PID that PM2 shows will be off by a few digits from the process ID of your actual node process. Should this be in the README next to `--no-automation`?

**Comment by soyuka** [comment]
Are you trying to tell pm2 to start your app using `npm start`? Seems weird to me, because `npm start`, will just end up doing `node someapp.js` which is the same as running `pm2 someapp.js`.

**Comment by jcollum** [comment]
The point of doing `npm start` instead of `pm2 app.js` is that I can keep
configuration of how to start the app in source control (package.json) and
have a consistent way to start the app across environments -- I don't use
pm2 to start the app when I'm developing.

**Comment by soyuka** [comment]
I see, about the PID it does make sense to me because pm2 starts npm who starts node. So, pm2 think that your app pid is the one from `npm`. Now, I don't get how this could work and won't advise it, might be error-prone and also isn't really supported by pm2 (read not tested :p).
 
Can't you alternatively run what `npm start` runs for you in a `npm run pm2` task that ends up doing `pm2 startOrRestart myapp.js`?

**Comment by jcollum** [comment]
It seems to work well enough. Been doing it on a few machines for a month
or two.

I could pull the npm start script out via `node -e "[script to read
package.json]"` or something and then pass that to the pm2 start. That
would keep the PIDs accurate. I'm not worried enough about it to actually
do that. Having the PIDs mismatched was a bit of a surprise but I get it
now.
