### ISSUE TITLE
Feature request: Auto save

### ISSUE THREAD

**Issue by domarmstrong** [Unitech/pm2#2078]
Hi,

Couldn't see if this had been bought up, and couldn't find anything in the docs.

It would be great to be able to enable auto-save of apps. We have a slightly manual deploy process currently and its very easy for people to forget to call `pm2 save`. It seems like it would be a useful feature to be able to enable.

**Comment by michAtEl** [comment]
+1

**Comment by harlentan** [comment]
+1

**Comment by Unitech** [comment]
This feature make sense we will have to do some changes on startup scripts:

*Drop pm2 delete all* here:
- https://github.com/Unitech/pm2/blob/master/lib/templates/init-scripts/openrc.tpl#L35
- https://github.com/Unitech/pm2/blob/master/lib/templates/init-scripts/pm2-init-amazon.sh#L45
- https://github.com/Unitech/pm2/blob/master/lib/templates/init-scripts/rcd.tpl#L42

Also some questions will come up, like how should we handle previous init scripts that call pm2 delete all?

**Comment by bisubus** [comment]
I hope this will be opt-in feature, because current behaviour is the reason why `pm2 save` exists.

**Comment by dkbhadeshiya** [comment]
Is there anything going on for this feature? Because I am excited for this.

**Comment by Unitech** [comment]
`pm2 save pm2:autodump true`

**Comment by markhaehnel** [comment]
> `pm2 save pm2:autodump true`

Little correction. It's `pm2 set pm2:autodump true`
