### ISSUE TITLE
Custom pm2 cluster strategy on process `exit`

### ISSUE THREAD

**Issue by shaunwarman** [Unitech/pm2#2081]
Just looking into the API for the first time in depth.

Is there a way to create a custom strategy on `exit` of worker process using `cluster` mode?

What I'd like to do is pass a message to nginx and provide my own restart handler for worker processes. Is something like this obvious?

**Comment by soyuka** [comment]
Maybe [this](http://pm2.keymetrics.io/docs/usage/signals-clean-restart/) is want you want?

**Comment by shaunwarman** [comment]
Thanks @soyuka, I may need to dive a bit deeper, but this may be the closest option.
