### ISSUE TITLE
[PM2][ERROR] script not found : /apps/wms/frontend/www  -p 8080

### ISSUE THREAD

**Issue by emazzu** [Unitech/pm2#2084]
Hi

One question:

/apps/wms/node_modules/pm2/bin/pm2 start http-server "/apps/wms/frontend/www  -p 8080" --name frontend

The service started good !!!, but when script finished, it shows the red message.

I have to do something or not ??

![image](https://cloud.githubusercontent.com/assets/6100546/14430502/3833de1e-ffd8-11e5-897e-ebeab20afb8e.png)

Regards
Eduardo

**Comment by soyuka** [comment]
I'm not sure to understand what you're trying to start, `pm2 start` accepts:

```
    start [options] <file|json|stdin|app_name|pm_id...>                  start and daemonize an app
```

If you want to add arguments, check [the `--args` option](http://pm2.keymetrics.io/docs/usage/application-declaration/#attributes-available).

**Comment by emazzu** [comment]
I am doing this !!!

this is OK !!! load perfect.
#Backend
cd /apps/wms/backend
/apps/wms/node_modules/pm2/bin/pm2 delete backend
/apps/wms/node_modules/pm2/bin/pm2 start "/apps/wms/backend/server/server.js" --name backend

this is OK !!! load perfect, but the line start shows script not found !!!

#Frontend
cd /apps/wms/frontend/www
/apps/wms/node_modules/pm2/bin/pm2 delete frontend
/apps/wms/node_modules/pm2/bin/pm2 start http-server "/apps/wms/frontend/www  -p 8080" --name  frontend

#Monitor PM2
#/apps/wms/node_modules/pm2-gui/pm2-gui start

**Comment by soyuka** [comment]
`/apps/wms/frontend/www -p 8080` is not a valid path. Also, `-p` is used to specify a pid file (see `pm2 --help`).
