### ISSUE TITLE
When I want to view pm2-gui, on port 8088, it need password ??

### ISSUE THREAD

**Issue by emazzu** [Unitech/pm2#2085]
Hi

When I want to view pm2-gui, on port 8088, redirect to http://localhost:8088, it does a redirect to http://localhost:8088/auth.

Somebody Can tell me why ??

![image](https://cloud.githubusercontent.com/assets/6100546/14430926/c7016156-ffd9-11e5-9ca2-2813d7759df6.png)

Regards
Eduardo

**Comment by soyuka** [comment]
pm2-gui is not linked to pm2
