### ISSUE TITLE
Programmatic API documentation please

### ISSUE THREAD

**Issue by fresheneesz** [Unitech/pm2#2089]
[This](http://pm2.keymetrics.io/docs/usage/pm2-api/) isn't documentation. Those are examples. There is simply no substitute for exhaustive documentation that lists all options, parameters, and methods intended for public availability. I would offer my help, but I don't understand pm2's programatic because ... drum roll ... there's no docs. If someone that does understand the interface could please write some docs that list available functions, ALL the parameters those functions have, and their behavior, it would be much appreciated by your thousands of fans.

I see that under "Programmatic API" there is a list of methods, but they're woefully incomplete. They're also incredibly difficult to read. Some love there would be great.

**Comment by soyuka** [comment]
Yes, we definitely need to put some time to improve this. The "programmatic api" is giving you access to every method of the [`CLI.js`](https://github.com/Unitech/pm2/blob/master/lib/CLI.js) file. It's complex, I won't deny that but @Unitech did a great work [separating concerns](https://github.com/Unitech/pm2/tree/master/lib/CLI) recently.
Every `options` parameters is defined in the [options schema](https://github.com/Unitech/pm2/blob/master/lib/CLI/schema.json), on which cli and json usage are based on.

To help further, you can take a look at a bunch of [examples](https://github.com/Unitech/pm2/tree/master/examples) but also [unit tests](https://github.com/Unitech/pm2/tree/master/test/programmatic) that rely on programmatic usage. I've also published an example that uses the programmatic api to notify by email when some events occurs. You can find it [here](https://github.com/soyuka/pm2-notify). Indeed, you'd have to dig a bit in the code...

As you must know there are a lot of options and possibilities with pm2. I've done some tutorials recently (https://github.com/pm2-hive/pm2-hive.github.io/pull/19, https://github.com/pm2-hive/pm2-hive.github.io/pull/15, https://github.com/pm2-hive/pm2-hive.github.io/pull/14), and will do my best to try  to improve this if no one else can help! 

Thanks for your interest in improving pm2 :).

**Comment by fresheneesz** [comment]
I added some docs to the readme: https://github.com/Unitech/pm2/pull/2091

**Comment by fresheneesz** [comment]
FYI I added a pull request here: https://github.com/pm2-hive/pm2-hive.github.io/pull/25

**Comment by soyuka** [comment]
Closing this one in favor of https://github.com/pm2-hive/pm2-hive.github.io/pull/25

Note that it'll be merged soon, just waiting for @Unitech aproval.
