### ISSUE TITLE
Weird optional dependency `ikt`

### ISSUE THREAD

**Issue by kompot** [Unitech/pm2#2092]
In `package.json` I see the following

```
"optionalDependencies": {
  "ikt": "git+http://ikt.pm2.io/ikt.git#master"
},
```

I've checked out that repo and there's literally nothing but a single `console.log`.

I've found that by using `npm`'s `shrinkwrap` that requires exact hashes (not `master` branch) to be set and it fails under certain circumstances.

Can that be dropped completely from `package.json`?

**Comment by n-johnson** [comment]
> I've found that by using npm's shrinkwrap that requires exact hashes (not master branch) to be set and it fails under certain circumstances.

I have run into issues with this a number of times as well.

If you're adamant about collecting usage statistics in this manner and won't merge this PR, can you at least please update it to refer to the commit hash instead of branch?

```
"optionalDependencies": {
  "ikt": "git+http://ikt.pm2.io/ikt.git#3325a3e39a502418dc2e2e4bf21529cbbde96228"
},
```

Thanks!

**Comment by animedbz16** [comment]
Installing modules like this (outside of NPM) cause issues when behind
corporate firewalls.

We run a internal NPM caching server and when an NPM client attempts to
install modules such as this they fail.

NPM has published a blog post that relates specifically about this:
http://blog.npmjs.org/post/145724408060/dealing-with-problematic-dependencies-in-a

**Comment by Unitech** [comment]
git ikt dependency replaced with gkt tgz dependency

https://github.com/Unitech/pm2/commit/adcfa078b1061e126d68a919ee02461f53d38f7d

Available in PM2 V2:

```bash
$ npm install Unitech/pm2#development -g
$ pm2 update
```
If there is still a problem, please reopen issue
