### ISSUE TITLE
.deploys not found

### ISSUE THREAD

**Issue by ChBernat** [Unitech/pm2#2100]
Hey!
 I have a problem with pm2 and here it comes:
- First step of deployment (setup) went smoothly, repository was cloned and all directories were created.
- Second step... Well, it went good all the way up to appending a deploy log, it suddenly crashed and throws an error like so:

```
bash: myProject/.deploys: No such file or directory

  deploy log append failed

Deploy failed
```

I've tried to create this file by myself, but it didn't work. I'm using an admin user for that for I though that would have been a problem.

Thanks in advance, 
 Chris

**Comment by gpasq** [comment]
Same issue here, version 1.1.3

**Comment by naugtur** [comment]
Use absolute path for now, see: https://github.com/Unitech/pm2-deploy/issues/86

**Comment by kichooo** [comment]
Same issue here, 1.1.3. Where exactly the absolute path should be used?

**Comment by naugtur** [comment]
Path field in your environment section for deployment needs to be absolute

**Comment by kichooo** [comment]
Thanks
