### ISSUE TITLE
generating none json file

### ISSUE THREAD

**Issue by calidion** [Unitech/pm2#2101]
with <code>pm2 ecosystem</code> we can get a file named ecosystem.json
as from its extension we may guess it is a json file, 
but it is not. it is more of a javascript file. And it leads to syntax errors on some text editors.

So it would be better keep file content and extension matched.
thanks.

**Comment by tacomanator** [comment]
Having same issue. The [example on the website](http://pm2.keymetrics.io/docs/usage/deployment/#deployment-options) is valid JSON but the file generated by `pm2 ecosystem` does not have quotes around most of the property keys.

**Comment by Unitech** [comment]
with the new support of legacy [javascript conf files](https://github.com/Unitech/pm2/blob/9f88b486de6434c72eb8a9b635ba918da6542e2d/examples/process-file/process.config.js), `pm2 ecosystem` now generates a javascript file
