### ISSUE TITLE
xxx app can't be reloaded - restarting it

### ISSUE THREAD

**Issue by diginfo** [Unitech/pm2#2102]
I seem to be unable to reload or gracefulRelaod any app that is running with PM2.

Every process gets restarted instead of reloaded:

      > pm2 gracefulReload all
      > [PM2][WARN] proxy app can't be reloaded - restarting it
      > [PM2] restartProcessId process id 0

All processes are running as "exec_mode": "fork"

**Comment by soyuka** [comment]
reload only works in cluster mode (`"exec_mode": "cluster"`)
