### ISSUE TITLE
Resurrection problem

### ISSUE THREAD

**Issue by kirilkalchev** [Unitech/pm2#2103]
Hi,

I have e pretty strange problem when I am trying to resurrect some apps after restarting pm2 daemon. Max restart property is not respected. In case of problems my app is just restarting endlessly after restarting pm2 daemon. I am using pm2 version 1.1.2 on official ubuntu docker container.

I narrowed down the issue to a pretty strange behaviour connected somehow with created_at property in dump file. I prepared a pretty simple test app and pm2 json file.
### pm2.json

> {
>   "apps" : [{
>     "script"      : "start.js",
>     "name"      : "test-app",
>     "max_restarts": 5,
>     "min_uptime": 10000,
>     "instances": 1,
>   }]
> }
### start.js

> "use strict";
> const app     = require('lib/mssing');

You can just paste them some directory. In my case this is `/var/www/uiapp/test_app`.

After starting the app and saving pm2, the following dump file will be generated:
### dump.pm2.not.working

> [
>   {
>     "name": "test-app",
>     "vizion": true,
>     "pmx": true,
>     "automation": true,
>     "autorestart": true,
>     "treekill": true,
>     "min_uptime": 10000,
>     "max_restarts": 5,
>     "exec_mode": "cluster_mode",
>     "node_args": [],
>     "pm_exec_path": "/var/www/uiapp/test_app/start.js",
>     "env": {
>       "PM2_JSON_PROCESSING": "true",
>       "OLDPWD": "/var/www/uiapp",
>       "_": "/usr/bin/pm2",
>       "LESSCLOSE": "/usr/bin/lesspipe %s %s",
>       "LESSOPEN": "| /usr/bin/lesspipe %s",
>       "SSH_CONNECTION": "172.16.0.2 52420 172.16.20.3 22",
>       "LOGNAME": "root",
>       "HOME": "/root",
>       "SHLVL": "1",
>       "NODE_PATH": "/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript",
>       "LANG": "en_US.UTF-8",
>       "PWD": "/var/www/uiapp/test_app",
>       "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
>       "MAIL": "/var/mail/root",
>       "SSH_AUTH_SOCK": "/tmp/ssh-v1hkOKNylf/agent.30381",
>       "LS_COLORS": "rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:_.tar=01;31:_.tgz=01;31:_.arj=01;31:_.taz=01;31:_.lzh=01;31:_.lzma=01;31:_.tlz=01;31:_.txz=01;31:_.zip=01;31:_.z=01;31:_.Z=01;31:_.dz=01;31:_.gz=01;31:_.lz=01;31:_.xz=01;31:_.bz2=01;31:_.bz=01;31:_.tbz=01;31:_.tbz2=01;31:_.tz=01;31:_.deb=01;31:_.rpm=01;31:_.jar=01;31:_.war=01;31:_.ear=01;31:_.sar=01;31:_.rar=01;31:_.ace=01;31:_.zoo=01;31:_.cpio=01;31:_.7z=01;31:_.rz=01;31:_.jpg=01;35:_.jpeg=01;35:_.gif=01;35:_.bmp=01;35:_.pbm=01;35:_.pgm=01;35:_.ppm=01;35:_.tga=01;35:_.xbm=01;35:_.xpm=01;35:_.tif=01;35:_.tiff=01;35:_.png=01;35:_.svg=01;35:_.svgz=01;35:_.mng=01;35:_.pcx=01;35:_.mov=01;35:_.mpg=01;35:_.mpeg=01;35:_.m2v=01;35:_.mkv=01;35:_.webm=01;35:_.ogm=01;35:_.mp4=01;35:_.m4v=01;35:_.mp4v=01;35:_.vob=01;35:_.qt=01;35:_.nuv=01;35:_.wmv=01;35:_.asf=01;35:_.rm=01;35:_.rmvb=01;35:_.flc=01;35:_.avi=01;35:_.fli=01;35:_.flv=01;35:_.gl=01;35:_.dl=01;35:_.xcf=01;35:_.xwd=01;35:_.yuv=01;35:_.cgm=01;35:_.emf=01;35:_.axv=01;35:_.anx=01;35:_.ogv=01;35:_.ogx=01;35:_.aac=00;36:_.au=00;36:_.flac=00;36:_.mid=00;36:_.midi=00;36:_.mka=00;36:_.mp3=00;36:_.mpc=00;36:_.ogg=00;36:_.ra=00;36:_.wav=00;36:_.axa=00;36:_.oga=00;36:_.spx=00;36:_.xspf=00;36:",
>       "USER": "root",
>       "LC_ALL": "C.UTF-8",
>       "SSH_TTY": "/dev/pts/0",
>       "SSH_CLIENT": "172.16.0.2 52420 22",
>       "SHELL": "/bin/bash",
>       "TERM": "xterm-256color",
>       "pm_cwd": "/var/www/uiapp/test_app",
>       "test-app": "{}",
>       "name": "test-app",
>       "instances": 1,
>       "vizion": true,
>       "pmx": true,
>       "automation": true,
>       "autorestart": true,
>       "treekill": true,
>       "min_uptime": 10000,
>       "max_restarts": 5,
>       "exec_mode": "cluster_mode",
>       "node_args": [],
>       "pm_exec_path": "/var/www/uiapp/test_app/start.js",
>       "exec_interpreter": "node",
>       "pm_out_log_path": "/root/.pm2/logs/test-app-out.log",
>       "pm_err_log_path": "/root/.pm2/logs/test-app-error.log",
>       "pm_pid_path": "/root/.pm2/pids/test-app.pid"
>     },
>     "pm_cwd": "/var/www/uiapp/test_app",
>     "exec_interpreter": "node",
>     "pm_out_log_path": "/root/.pm2/logs/test-app-out.log",
>     "pm_err_log_path": "/root/.pm2/logs/test-app-error.log",
>     "pm_pid_path": "/root/.pm2/pids/test-app.pid",
>     "NODE_APP_INSTANCE": 0,
>     "vizion_running": false,
>     "PM2_JSON_PROCESSING": "true",
>     "OLDPWD": "/var/www/uiapp",
>     "_": "/usr/bin/pm2",
>     "LESSCLOSE": "/usr/bin/lesspipe %s %s",
>     "LESSOPEN": "| /usr/bin/lesspipe %s",
>     "SSH_CONNECTION": "172.16.0.2 52420 172.16.20.3 22",
>     "LOGNAME": "root",
>     "HOME": "/root",
>     "SHLVL": "1",
>     "NODE_PATH": "/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript",
>     "LANG": "en_US.UTF-8",
>     "PWD": "/var/www/uiapp/test_app",
>     "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
>     "MAIL": "/var/mail/root",
>     "SSH_AUTH_SOCK": "/tmp/ssh-v1hkOKNylf/agent.30381",
>     "LS_COLORS": "rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:_.tar=01;31:_.tgz=01;31:_.arj=01;31:_.taz=01;31:_.lzh=01;31:_.lzma=01;31:_.tlz=01;31:_.txz=01;31:_.zip=01;31:_.z=01;31:_.Z=01;31:_.dz=01;31:_.gz=01;31:_.lz=01;31:_.xz=01;31:_.bz2=01;31:_.bz=01;31:_.tbz=01;31:_.tbz2=01;31:_.tz=01;31:_.deb=01;31:_.rpm=01;31:_.jar=01;31:_.war=01;31:_.ear=01;31:_.sar=01;31:_.rar=01;31:_.ace=01;31:_.zoo=01;31:_.cpio=01;31:_.7z=01;31:_.rz=01;31:_.jpg=01;35:_.jpeg=01;35:_.gif=01;35:_.bmp=01;35:_.pbm=01;35:_.pgm=01;35:_.ppm=01;35:_.tga=01;35:_.xbm=01;35:_.xpm=01;35:_.tif=01;35:_.tiff=01;35:_.png=01;35:_.svg=01;35:_.svgz=01;35:_.mng=01;35:_.pcx=01;35:_.mov=01;35:_.mpg=01;35:_.mpeg=01;35:_.m2v=01;35:_.mkv=01;35:_.webm=01;35:_.ogm=01;35:_.mp4=01;35:_.m4v=01;35:_.mp4v=01;35:_.vob=01;35:_.qt=01;35:_.nuv=01;35:_.wmv=01;35:_.asf=01;35:_.rm=01;35:_.rmvb=01;35:_.flc=01;35:_.avi=01;35:_.fli=01;35:_.flv=01;35:_.gl=01;35:_.dl=01;35:_.xcf=01;35:_.xwd=01;35:_.yuv=01;35:_.cgm=01;35:_.emf=01;35:_.axv=01;35:_.anx=01;35:_.ogv=01;35:_.ogx=01;35:_.aac=00;36:_.au=00;36:_.flac=00;36:_.mid=00;36:_.midi=00;36:_.mka=00;36:_.mp3=00;36:_.mpc=00;36:_.ogg=00;36:_.ra=00;36:_.wav=00;36:_.axa=00;36:_.oga=00;36:_.spx=00;36:_.xspf=00;36:",
>     "USER": "root",
>     "LC_ALL": "C.UTF-8",
>     "SSH_TTY": "/dev/pts/0",
>     "SSH_CLIENT": "172.16.0.2 52420 22",
>     "SHELL": "/bin/bash",
>     "TERM": "xterm-256color",
>     "test-app": "{}",
>     "status": "errored",
>     "pm_uptime": 1461332684907,
>     "axm_actions": [],
>     "axm_monitor": {},
>     "axm_options": {
>       "http": false,
>       "http_latency": 200,
>       "http_code": 500,
>       "ignore_routes": [],
>       "profiling": true,
>       "errors": true,
>       "alert_enabled": true,
>       "custom_probes": true,
>       "network": false,
>       "ports": false,
>       "module_conf": {},
>       "module_name": "test-app",
>       "module_version": "1.1.2",
>       "pmx_version": "0.6.1",
>       "error": true
>     },
>     "axm_dynamic": {},
>     "created_at": 1,
>     "restart_time": 4,
>     "unstable_restarts": 0,
>     "_pm2_version": "1.1.2",
>     "versioning": null,
>     "node_version": "4.4.3",
>     "exit_code": 0
>   }
> ]

Now when I restart pm2 deamon my application is just restarting forever.
After some testing and looking around I narrowed it down to created_at field. If I edit the dump file and set the property to null everything works fine and app is restarted only 5 times.
### dump.pm2.working

> [
>   {
>     "name": "test-app",
>     "vizion": true,
>     "pmx": true,
>     "automation": true,
>     "autorestart": true,
>     "treekill": true,
>     "min_uptime": 10000,
>     "max_restarts": 5,
>     "exec_mode": "cluster_mode",
>     "node_args": [],
>     "pm_exec_path": "/var/www/uiapp/test_app/start.js",
>     "env": {
>       "PM2_JSON_PROCESSING": "true",
>       "OLDPWD": "/var/www/uiapp",
>       "_": "/usr/bin/pm2",
>       "LESSCLOSE": "/usr/bin/lesspipe %s %s",
>       "LESSOPEN": "| /usr/bin/lesspipe %s",
>       "SSH_CONNECTION": "172.16.0.2 52420 172.16.20.3 22",
>       "LOGNAME": "root",
>       "HOME": "/root",
>       "SHLVL": "1",
>       "NODE_PATH": "/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript",
>       "LANG": "en_US.UTF-8",
>       "PWD": "/var/www/uiapp/test_app",
>       "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
>       "MAIL": "/var/mail/root",
>       "SSH_AUTH_SOCK": "/tmp/ssh-v1hkOKNylf/agent.30381",
>       "LS_COLORS": "rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:_.tar=01;31:_.tgz=01;31:_.arj=01;31:_.taz=01;31:_.lzh=01;31:_.lzma=01;31:_.tlz=01;31:_.txz=01;31:_.zip=01;31:_.z=01;31:_.Z=01;31:_.dz=01;31:_.gz=01;31:_.lz=01;31:_.xz=01;31:_.bz2=01;31:_.bz=01;31:_.tbz=01;31:_.tbz2=01;31:_.tz=01;31:_.deb=01;31:_.rpm=01;31:_.jar=01;31:_.war=01;31:_.ear=01;31:_.sar=01;31:_.rar=01;31:_.ace=01;31:_.zoo=01;31:_.cpio=01;31:_.7z=01;31:_.rz=01;31:_.jpg=01;35:_.jpeg=01;35:_.gif=01;35:_.bmp=01;35:_.pbm=01;35:_.pgm=01;35:_.ppm=01;35:_.tga=01;35:_.xbm=01;35:_.xpm=01;35:_.tif=01;35:_.tiff=01;35:_.png=01;35:_.svg=01;35:_.svgz=01;35:_.mng=01;35:_.pcx=01;35:_.mov=01;35:_.mpg=01;35:_.mpeg=01;35:_.m2v=01;35:_.mkv=01;35:_.webm=01;35:_.ogm=01;35:_.mp4=01;35:_.m4v=01;35:_.mp4v=01;35:_.vob=01;35:_.qt=01;35:_.nuv=01;35:_.wmv=01;35:_.asf=01;35:_.rm=01;35:_.rmvb=01;35:_.flc=01;35:_.avi=01;35:_.fli=01;35:_.flv=01;35:_.gl=01;35:_.dl=01;35:_.xcf=01;35:_.xwd=01;35:_.yuv=01;35:_.cgm=01;35:_.emf=01;35:_.axv=01;35:_.anx=01;35:_.ogv=01;35:_.ogx=01;35:_.aac=00;36:_.au=00;36:_.flac=00;36:_.mid=00;36:_.midi=00;36:_.mka=00;36:_.mp3=00;36:_.mpc=00;36:_.ogg=00;36:_.ra=00;36:_.wav=00;36:_.axa=00;36:_.oga=00;36:_.spx=00;36:_.xspf=00;36:",
>       "USER": "root",
>       "LC_ALL": "C.UTF-8",
>       "SSH_TTY": "/dev/pts/0",
>       "SSH_CLIENT": "172.16.0.2 52420 22",
>       "SHELL": "/bin/bash",
>       "TERM": "xterm-256color",
>       "pm_cwd": "/var/www/uiapp/test_app",
>       "test-app": "{}",
>       "name": "test-app",
>       "instances": 1,
>       "vizion": true,
>       "pmx": true,
>       "automation": true,
>       "autorestart": true,
>       "treekill": true,
>       "min_uptime": 10000,
>       "max_restarts": 5,
>       "exec_mode": "cluster_mode",
>       "node_args": [],
>       "pm_exec_path": "/var/www/uiapp/test_app/start.js",
>       "exec_interpreter": "node",
>       "pm_out_log_path": "/root/.pm2/logs/test-app-out.log",
>       "pm_err_log_path": "/root/.pm2/logs/test-app-error.log",
>       "pm_pid_path": "/root/.pm2/pids/test-app.pid"
>     },
>     "pm_cwd": "/var/www/uiapp/test_app",
>     "exec_interpreter": "node",
>     "pm_out_log_path": "/root/.pm2/logs/test-app-out.log",
>     "pm_err_log_path": "/root/.pm2/logs/test-app-error.log",
>     "pm_pid_path": "/root/.pm2/pids/test-app.pid",
>     "NODE_APP_INSTANCE": 0,
>     "vizion_running": false,
>     "PM2_JSON_PROCESSING": "true",
>     "OLDPWD": "/var/www/uiapp",
>     "_": "/usr/bin/pm2",
>     "LESSCLOSE": "/usr/bin/lesspipe %s %s",
>     "LESSOPEN": "| /usr/bin/lesspipe %s",
>     "SSH_CONNECTION": "172.16.0.2 52420 172.16.20.3 22",
>     "LOGNAME": "root",
>     "HOME": "/root",
>     "SHLVL": "1",
>     "NODE_PATH": "/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript",
>     "LANG": "en_US.UTF-8",
>     "PWD": "/var/www/uiapp/test_app",
>     "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
>     "MAIL": "/var/mail/root",
>     "SSH_AUTH_SOCK": "/tmp/ssh-v1hkOKNylf/agent.30381",
>     "LS_COLORS": "rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:_.tar=01;31:_.tgz=01;31:_.arj=01;31:_.taz=01;31:_.lzh=01;31:_.lzma=01;31:_.tlz=01;31:_.txz=01;31:_.zip=01;31:_.z=01;31:_.Z=01;31:_.dz=01;31:_.gz=01;31:_.lz=01;31:_.xz=01;31:_.bz2=01;31:_.bz=01;31:_.tbz=01;31:_.tbz2=01;31:_.tz=01;31:_.deb=01;31:_.rpm=01;31:_.jar=01;31:_.war=01;31:_.ear=01;31:_.sar=01;31:_.rar=01;31:_.ace=01;31:_.zoo=01;31:_.cpio=01;31:_.7z=01;31:_.rz=01;31:_.jpg=01;35:_.jpeg=01;35:_.gif=01;35:_.bmp=01;35:_.pbm=01;35:_.pgm=01;35:_.ppm=01;35:_.tga=01;35:_.xbm=01;35:_.xpm=01;35:_.tif=01;35:_.tiff=01;35:_.png=01;35:_.svg=01;35:_.svgz=01;35:_.mng=01;35:_.pcx=01;35:_.mov=01;35:_.mpg=01;35:_.mpeg=01;35:_.m2v=01;35:_.mkv=01;35:_.webm=01;35:_.ogm=01;35:_.mp4=01;35:_.m4v=01;35:_.mp4v=01;35:_.vob=01;35:_.qt=01;35:_.nuv=01;35:_.wmv=01;35:_.asf=01;35:_.rm=01;35:_.rmvb=01;35:_.flc=01;35:_.avi=01;35:_.fli=01;35:_.flv=01;35:_.gl=01;35:_.dl=01;35:_.xcf=01;35:_.xwd=01;35:_.yuv=01;35:_.cgm=01;35:_.emf=01;35:_.axv=01;35:_.anx=01;35:_.ogv=01;35:_.ogx=01;35:_.aac=00;36:_.au=00;36:_.flac=00;36:_.mid=00;36:_.midi=00;36:_.mka=00;36:_.mp3=00;36:_.mpc=00;36:_.ogg=00;36:_.ra=00;36:_.wav=00;36:_.axa=00;36:_.oga=00;36:_.spx=00;36:_.xspf=00;36:",
>     "USER": "root",
>     "LC_ALL": "C.UTF-8",
>     "SSH_TTY": "/dev/pts/0",
>     "SSH_CLIENT": "172.16.0.2 52420 22",
>     "SHELL": "/bin/bash",
>     "TERM": "xterm-256color",
>     "test-app": "{}",
>     "status": "errored",
>     "pm_uptime": 1461332684907,
>     "axm_actions": [],
>     "axm_monitor": {},
>     "axm_options": {
>       "http": false,
>       "http_latency": 200,
>       "http_code": 500,
>       "ignore_routes": [],
>       "profiling": true,
>       "errors": true,
>       "alert_enabled": true,
>       "custom_probes": true,
>       "network": false,
>       "ports": false,
>       "module_conf": {},
>       "module_name": "test-app",
>       "module_version": "1.1.2",
>       "pmx_version": "0.6.1",
>       "error": true
>     },
>     "axm_dynamic": {},
>     "created_at": null,
>     "restart_time": 4,
>     "unstable_restarts": 0,
>     "_pm2_version": "1.1.2",
>     "versioning": null,
>     "node_version": "4.4.3",
>     "exit_code": 0
>   }
> ]

If I find some more time I will try to look into the issue myself, but I am not sure when this will be.

Thank you!

**Comment by vmarchaud** [comment]
Should work using pm2 v2
