### ISSUE TITLE
executing "pm2 log" isn't a command but it doesn't fail

### ISSUE THREAD

**Issue by laurenskling** [Unitech/pm2#2105]
Okay, so i was a dummy. I've been executing `pm2 log` and nothing happened. Now i realised it was `pm2 logs` i needed. 
But why does it allow me to give the `log` command if it doesn`t exist?

**Comment by Unitech** [comment]
fixed ;)
Also the pm2 log command has been refined with love :) :

$ pm2 logs
![pm2-logs](https://cloud.githubusercontent.com/assets/757747/17459847/089adcc8-5c00-11e6-8530-bb5ef5662bdf.png)

$ pm2 logs --json
![pm2-logs-json](https://cloud.githubusercontent.com/assets/757747/17459843/f1d33d78-5bff-11e6-9e09-3f72a9e4d342.png)

$ pm2 logs --format
![pm2-log-format](https://cloud.githubusercontent.com/assets/757747/17459845/fef31ec4-5bff-11e6-8ffe-19d67204dd6e.png)

Available in development branch!
