### ISSUE TITLE
each process on different core?

### ISSUE THREAD

**Issue by Xeroner** [Unitech/pm2#2106]
It is possible to get something like this?

Process 1 - Core 1
Process 2 - Core 2
Process 3 - Core 3 
etc.. ?
EDIT : Or meaby there is an option for running 1 process on 8 cores but with one instance?

Becouse i have really high CPU usage on 2 nodejs scripts, sometimes it is 100% :( .

**Comment by Xeroner** [comment]
EDIT: My scripts cannot run on cluster mode :)

**Comment by adrian-ludwig** [comment]
Node.js is Single Threaded.
You can utlize multi processes with queue systems or something like that.
Cluster module will do too, but for masive http load.

**Comment by Xeroner** [comment]
So there is no option to ascribe each process to an explicit core?

**Comment by adrian-ludwig** [comment]
This is system level task.

**Comment by soyuka** [comment]
Nope there is not. Also, the cluster mode will spawn multiple processes, which doesn't mean that two processes will use the same core. 

If you want to change the number of processes with cluster, specify the `-i` option. For example `pm2 start -i 8 app.js` will start the server 8 times.

**Comment by Xeroner** [comment]
Omfg did you read my issue?
EDIT : Or meaby there is an option for running 1 process on 8 cores but with one instance?
I cannot run 8 instances of my script.....

**Comment by soyuka** [comment]
Did you read my answer? Either I didn't understood, either you want something that is not possible because nodejs is single-thread. Jxcore has multi-thread abilities, you might want to look into that.

**Comment by Xeroner** [comment]
That wat i was looking for :)) Thanks
