### ISSUE TITLE
pm2 start not working

### ISSUE THREAD

**Issue by DilshadPt** [Unitech/pm2#2107]
pm2 start not working. 
when i do 'pm2 start server.js'.., the output will be 
'[PM2] Starting server.js in fork_mode (1 instance)
[PM2] Done.' .
But server will not come in the list. All other processes will stay.

When I try to stop, delete and restart an exsisting process, it also fails. We can't start a new process.

I can get it to working by deleting all the processes from list and restarting one after one.
But after some time, above issue will come again. 

This PM2 was installed months ago and was working fine till yesterday. I dont know what happened.

pm2 --version --> 1.0.0
node --version --> 5.4.1

**Comment by soyuka** [comment]
May you upgrade pm2 to the latest? Thanks.

**Comment by DilshadPt** [comment]
It was working seamlessly for last many months. It stopped suddenly.

**Comment by vmarchaud** [comment]
If its still hapenning, try updating to pm2 v2 : `npm install -g pm2 && pm2 update`

**Comment by DilshadPt** [comment]
this issue got fixed after updating PM2 package
thank you
