### ISSUE TITLE
--watch in cli commands not working

### ISSUE THREAD

**Issue by Yu1989** [Unitech/pm2#2108]
PM2 version: 1.1.3

So I have **ecosystem.json5** with multiple apps declared. 
- Add `watch: true` to app declarations in **ecosystem.json5** and run `pm2 start ecosystem.json5`, watching works.
- Run `pm2 start ecosystem.json5 --watch`, watching does not work. `pm2 list` shows watching is disabled.

I doubt this is the intended behaviour. Assuming it's not intended, I believe the cause is the conditions with this line: https://github.com/Unitech/pm2/blob/master/lib/Satan.js#L541

Thank you (:

**Comment by stimmins** [comment]
More specifically I believe it was introduced in: https://github.com/Unitech/pm2/commit/cb4aecbe0d13826f7204397694480cc046a7c4eb#diff-97bd991fe20771d0b1957f1e86056658

If `env.env.watch` is not an array then `env_watch` is always false

**Comment by vmarchaud** [comment]
See #2629 we group all issue into one.
