### ISSUE TITLE
post_update script says failed but executes correctly

### ISSUE THREAD

**Issue by jonaswindey** [Unitech/pm2#2112]
I have the following in my package.json

```
  "apps" :
  [
    {
      "name"               : "carrefour-it-web",
      "post_update"        : ["export TENANT=it && npm run dist"]
    }
  ]
```

if I run pm2 pull (or pm2 pullAndRestart via keymetrics) I get the following result:

```
Action pullAndRestart received
Executing: pm2 pullAndRestart carrefour-it-web

{error}
{
    "msg": "cd '/home/trinit/apps/carrefour-it/web/';LC_ALL=en_US.UTF-8 git reset --hard a1378d98c69fcbe585ab75a00c329ce38310ecc7\nHEAD is now at a1378d9 Test\n\nexport TENANT=it && npm run dist\n\n> Carrefour@0.0.1 dist /home/trinit/apps/carrefour-it/web\n> npm run clean && NODE_ENV=production webpack --config webpack.config.production.js\n\n\n> Carrefour@0.0.1 clean /home/trinit/apps/carrefour-it/web\n> rimraf dist\n\n\n`export TENANT=it && npm run dist` failed"
}
{/error}
```

However, the script seems to have executed correctly (dist folder is created)

Any idea what could cause this error? The npm-debug.log.50497065 file it created is empty.

**Comment by jonaswindey** [comment]
The error seems to be related to webpack. If I remove that part, it works.

Maybe it expects a different return value?

**Comment by jonaswindey** [comment]
It would be good if https://github.com/Unitech/pm2/blob/79ba743723131436bd049cc952e2b1f1158bc84c/lib/tools/VersionManagement.js#L294 printed the error code for debugging purposes.

**Comment by soyuka** [comment]
+1 would you mind sending a Pull request?
