### ISSUE TITLE
wrong timezone in cluster mode

### ISSUE THREAD

**Issue by hankfrinkel** [Unitech/pm2#2118]
Hello 

pm2 gives a wrong timezone when I start the script in cluster mode. 
For example...

This is my test.js file:

```
process.env.TZ = 'Europe/Berlin';
console.log(new Date());
```

If the script start with the follow command

```
$ pm2 start test.js
```

The script print out a correct datetime

```
$ time-0 (out): Fri Apr 29 2016 15:15:22 GMT+0200 (CEST)
```

But when I start the same script in cluster mode.

```
$ pm2 start test.js -i 0
```

The script print out a wrong datetime 

```
$ time-0 (out): Fri Apr 29 2016 13:16:57 GMT+0000 (CEST)
$ time-1 (out): Fri Apr 29 2016 13:16:57 GMT+0000 (CEST)
```

What I'am doing wrong?
Thanks

Edit: my versions

```
pm2 v.1.1.3
node v4.2.6
```

**Comment by SamDuvall** [comment]
@elstonie Did you ever find a resolution?

I have a clustered config where I set the TZ environment variable and that doesn't work either

```
{
    "name": "api",
    "script": "server/api.js",
    "instances": 2,
    "watch": ["common", "config", "server"],
    "env": {
      "TZ": "GMT"
    }
}
```

**Comment by elstonie** [comment]
@SamDuvall 

Hi, yes! I've changed my global server time zone to 'Euro/Berlin' and it will works in cluster mode.

```
$ sudo dpkg-reconfigure tzdata
```
