### ISSUE TITLE
Environment variable or API to discover cluster size

### ISSUE THREAD

**Issue by vphantom** [Unitech/pm2#2120]
This is a followup on #2035 where @mangix elects one process to do special tasks, more or less an equivalent of `cluster.isMaster` with:

``` js
if (typeof process.env.pm_id !== 'undefined') {
  // We're under PM2
  if (process.env.pm_id % os.cpus().length === 0) {
    // We're the chosen process
  }
}
```

Is there a means to discover during run-time how many nodes are _currently_ in our cluster from PM2 itself?  The above assumes that pm2 was launched with `-i 0` and that its size wasn't modified since.  I'm developing a strategy to dispatch a lot of distinct work between my cluster's nodes (a queue would incur too much IPC I/O) and I would rather not assume/hard-code anything about my cluster.

Thanks for any suggestions you may have!

**Comment by ValueBerry** [comment]
I would also love to know the answer to this.  I have a process that needs to be run periodically, but I need it run by only a single process, not all of them.

**Comment by OmgImAlexis** [comment]
Bad bot.
