### ISSUE TITLE
Can't pass args to process

### ISSUE THREAD

**Issue by ZackMattor** [Unitech/pm2#2121]
I can't seem to pass args to the process using the API `pm2.start('index.js', {...})`

* pm2: 1.1.3
* nodejs: v6.0.0
* OS: osx

http://pm2.keymetrics.io/docs/usage/pm2-api/#programmatic-api

```javascript
var opts = {
  name: 'tis-server-' + id,
  force: true,
  args: ['--port', '8090']
};

pm2.start('../server/index.js', opts, (err) => {
  if(err) {
    console.log('ERROR');
    console.log(err);
  }
});
```

File output (`../server/index.js`)
```javascript
console.log(process.argv);

// outputs
// [ '/Users/zmattor/.nvm/versions/node/v5.2.0/bin/node',
// '/Users/zmattor/work/arksaw/game/tis-server-manager/node_modules/pm2/lib/ProcessContainerFork.js' ]

// Missing --port 8090
```

**Comment by ZackMattor** [comment]
Looks like the docs are wrong!! Can someone point me to where the doc repo is (if there is one?)

it needs to be `scriptArgs: ['foo', 'bar']` and now `args: ['foo', 'bar']`

`opts.args` gets explicitly deleted... https://github.com/Unitech/pm2/blob/master/lib/CLI.js#L141

**Comment by soyuka** [comment]
Here's the repo: https://github.com/pm2-hive/pm2-hive.github.io. Thanks!

**Comment by Unitech** [comment]
```
var opts = {
  script : '../server/index.js', 
  name: 'tis-server-' + id,
  force: true,
  args: ['--port', '8090']
};

pm2.start(opts, (err) => {
  if(err) {
    console.log('ERROR');
    console.log(err);
  }
});
```
