### ISSUE TITLE
PM2 Leaves "sudo" spawned sub-process running after stopping processes

### ISSUE THREAD

**Issue by taylorotwell** [Unitech/pm2#2125]
If I use PM2 to start a Bash script which contains the following:

```
sudo node proxy.js
```

I have `node proxy.js` in my sudoers.d so that it can be run without prompting for a password. PM2 runs the Bash script fine; however, if I then run `pm2 stop all` it stops but if I check `ps aux | grep node` I can still see the proxy.js process hanging out there.

Why is this child process not being killed when the parent bash script being monitored by PM2 is stopped using `stop all`?

**Comment by vmarchaud** [comment]
Shouldn't happen on pm2 v2 : `npm install -g pm2 && pm2 update`
