### ISSUE TITLE
PM2 keeps using PORT after removing the process

### ISSUE THREAD

**Issue by kauegimenes** [Unitech/pm2#2126]
After trying to restart a process i got this error:
`uncaughtException: listen EADDRINUSE`
Using the command `netstat -tulpn` i was able to verify that PM2 was using the application port.

The solution was to execute pm2 update

The process was running in cluster, and was not answering to any HTTP requests. I tried multiple pm restart <ID> to fix it, but didnt worked.

This happend after i executed a pm2 startup + pm2 save

**Comment by vmarchaud** [comment]
Shouldn't be a problem with pm2 v2 : `npm install -g pm2 && pm2 update`
