### ISSUE TITLE
Not waiting for changes before restarting app

### ISSUE THREAD

**Issue by alex-cory** [Unitech/pm2#2127]
I think this is the problem, but I'm not 100%. It may not be though because everything works great on my local environment, but on the server not so much.

I have a cron job running that pulls data and overwrites a local json file with fresh data.  The app is then supposed to restart, which it does, but "I think" it's restarting before the write is done updating the file with fresh data, because after the 1st cron job runs, the app crashes due to there being no data in the json file.

I tried putting a `--restart-delay 10000` to see if that would help, but no luck.  Do you think this is an issue with pm2 or?

**Comment by alex-cory** [comment]
Wait.. I might've figured it out.

**Comment by alex-cory** [comment]
Wait.. I might've figured it out.

**Comment by alex-cory** [comment]
Wait.. I might've figured it out.

**Comment by alex-cory** [comment]
It runs perfectly fine when locally with pm2 and on the server when I don't use pm2.  For some reason it's not executing what's inside the cronjob properly.

**Comment by soyuka** [comment]
Are you watching the file for changes? I think that chokidar triggers the change when the file is modified, and doesn't wait until it has been fully written. Try adding a fail-safe when parsing the json, or don't watch in production and try another, safer way.

**Comment by alex-cory** [comment]
I found this under the [Performance](https://github.com/paulmillr/chokidar#performance) section of the chokidar repo.
![alt text](http://new.tinygrab.com/99382f8371895d4a984a5eeed5acfd1fe25be5ae45.png "Title")

**Comment by alex-cory** [comment]
I just basically turned off the watch feature and whenever I had to make an update to a file, I invoked `process.exit(1)` and then pm2 will automatically restart the app.

**Comment by gulakov** [comment]
fs.writeFileSync() to block process untill file is written, or you can also use promises:
https://www.npmjs.com/package/fs-promise
