### ISSUE TITLE
Spawing child process throws 'Error: spawn pm2 ENOENT'

### ISSUE THREAD

**Issue by MtDalPizzol** [Unitech/pm2#2128]
I took a look at similar issues but I got nowhere. If this is a replicate, please, ignore me and close this issue. 

I'm writing a CLI tool to lift 2 or 3 apps with a single command in the terminal and I have a fresh install with these configs:

Linux Mint 17.3
Node 4.4.3
PM2 1.1.3

I have installed Node via the package manager, like described in [here](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) and fixed NPM permissions following exactly the [option 2 on the tutorial at the NPM site](https://docs.npmjs.com/getting-started/fixing-npm-permissions), which have changed my global modules default path. Now,  when I start things manually on a terminal, like ```pm2 start server.js```, everything works fine. But when I try to spawn child processes with PM2, I get this error: 

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn pm2 ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3

```

Here is the code throwing it:

```javascript
  #!/usr/bin/env node

  const spawn = require('child_process').spawn;
  // ...
  const appSpawn = spawn('pm2', app.spawn.args, {
    cwd: path.join(process.cwd(), 'api')
  });
```

The same code works fine with Node 4.2.6, PM2 1.0.0 and the default global modules path.

**Comment by soyuka** [comment]
You can use [pm2 programmatically](http://pm2.keymetrics.io/docs/usage/pm2-api/), you don't and should not use spawn here.

**Comment by MtDalPizzol** [comment]
Well... that is not exactly how I wanted my tool to handle things but, with a simple conditional for handling pm2 this way, it worked. Thanks!
