### ISSUE TITLE
Pm2 does not run on configured port

### ISSUE THREAD

**Issue by inspirebin** [Unitech/pm2#2131]
I have an  express.js application that runs on nodemon on the development machine and in the production server uses pm2.The application runs on the specified port using nodemon without any problem in the production server. However when i use pm2 the app runs on some strange port. Is there any mechanism to find which port is used by the app.

**Comment by Unitech** [comment]
you can use pmx: http://docs.keymetrics.io/docs/pages/custom-metrics/#builtin-custom-metrics and set the port option to true

then `pm2 show <MY-APP>`
