### ISSUE TITLE
Linking with keymetrics completely destroys your Windows host

### ISSUE THREAD

**Issue by oliversalzburg** [Unitech/pm2#2134]
As soon as I linked my workstation with keymetrics.io, I got a myriad of `wmic` processes (`wmic path Win32_PerfFormattedData_PerfProc_Process WHERE IDProcess=32168 get PercentProcessorTime, WorkingSet`) running. I guess those are used to determine CPU and RAM usage.

I don't know if it was trying to run those for processes that had already exited, but my running Node instances stopped behaving correctly, pm2 started way more instances of my application than it should have (even though `autorestart` is set to `false`) and, generally, my system became almost unusable.

**Comment by vmarchaud** [comment]
Shouldn't be a problem with pm2 v2 : `npm install -g pm2 && pm2 update`, we've made a number of fixes on windows this summer.
