### ISSUE TITLE
pm2 can for tcp server?

### ISSUE THREAD

**Issue by tianyayouxiaer** [Unitech/pm2#2141]
I use pm2 for tcp server(in mqtt project),and use "pm2 start index_tcp.js -i 4--name="TCP" --watch
",but I found it always printf
PM2 App name:TCP id:0 disconnected
PM2 App [TCP] with id [0] and pid [9394], exited with code [0] via signal [SIGINT]
PM2 Starting execution sequence in -cluster mode- for app name:TCP id:0

so,does pm2  not suppot tcp server?

**Comment by Unitech** [comment]
do you have a sample code so I can try to reproduce?

**Comment by vmarchaud** [comment]
No answer, we consider that your problem is solved, plus it there are no reason why this should not work, we have several tests with http server that works great.

**Comment by okonsemi** [comment]
Confirm, the problem exists. 
Indeed one can start http server on a cluster and make pm2 shared the port for it. It's not so for tcp. pm2 can't share a binding port of tcp server. 
For example:
```
"use strict";

const zmq = require('zeromq');
const publisher = zmq.socket('pub');

const PORT = process.env.PORT || 5557;
const SERVER = process.env.SERVER || '127.0.0.1';
const d = new Date();

function publish() {
  publisher.send('XXX '+d.getTime());
  console.log('XXX '+d.getTime());
  setTimeout(publish, 1500);
}

publisher.bind('tcp://'+SERVER+':'+PORT, function(err) {
  if (err){
    console.log('Can not bring up server');
    console.log(err);
    process.exit(1);
  } else {
    console.log(SERVER+' publishing on '+PORT);
    setTimeout(publish, 1500);
  }
});
```
Start the server via pm2:
`node_modules/pm2/bin/pm2 start pub-server-example.js --name test  -i 3`   
then see what we got:
`node_modules/pm2/bin/pm2 list` 
only one instance will be alive, others errored after 15 restart attempts

pm2 -v 
2.10.4
