### ISSUE TITLE
cluster gracefulReload : Add an option to listen for an event to start next instance

### ISSUE THREAD

**Issue by Benew** [Unitech/pm2#2143]
I can't find an issue about this.

My app starts slow because all instances start at (approximately) the same time and I can't control it.

**Comment by Unitech** [comment]
gracefulReload will be deprecated soon, please use instead: http://pm2.keymetrics.io/docs/usage/signals-clean-restart/

**Comment by Benew** [comment]
Thx but will gracefulReload be replaced with some other command?

**Comment by Unitech** [comment]
Any command (restart, stop, reload) with be able to graceful Stop & start/reload with [this](http://pm2.keymetrics.io/docs/usage/signals-clean-restart/)
