### ISSUE TITLE
User permission

### ISSUE THREAD

**Issue by belldandu** [Unitech/pm2#2144]
Atm i had to set the directory "/home/minecraft" to chmod 777

However it would be nice if pm2 ACTUALLY let me start a process for an application as root so i can drop is for a different process after without getting retarded EPERM when spawning :|

see https://github.com/nodejs/node/issues/6676 for code that was used and the errors.

Atm idc that setting 777 is a security risk however this needs to be fixed.

A proposed fix would be to check for sudo if it exists (to get around the currently discussed issues where people say not every system has sudo) and saying to install sudo (or a derivative)

**Comment by vmarchaud** [comment]
We removed the setguid && setuid support so its not possible anymore.

**Comment by Unitech** [comment]
Feature added in upcoming PM2. To try it:

(Make sure pm2 is run as root to manipulate uid and gid)

```bash
$ pm2 save
$ pm2 kill
$ npm install Unitech/pm2#development -g
$ sudo pm2 resurrect
$ sudo pm2 start app --uid <uid>
# Now pm2 ls display the user running the script
$ pm2 ls
```

Feedback is welcome

**Comment by nasredin** [comment]
hello,

yes pm2 show user but "ps u" on pid keeps show root for me :(
