### ISSUE TITLE
pm2 hangs on start, can't update to latest version of pm2

### ISSUE THREAD

**Issue by Dualio** [Unitech/pm2#2145]
been using pm2 for months on our server, has worked great up until today, running a vps server, just increase the servers ram from 2048mb to 2560mb, this required a restart of the vps.  Afterwords when i try to run  > pm2 start server.js the process might show 1 or 2 of its startup lines but it then hangs and i have to ctrl-c to do anything else.  This is with version 1.0.3 and node 6.0.0 (worked fine two day ago)

So seeing i dont have the latest version of pm2 I am trying to install the latest version 1.1.3? and am getting errors, here is my log:

npm install pm2 -g
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:63:19)
npm WARN addRemoteGit     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:72:29)
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/which.js:81:16
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:117:15)
npm WARN addRemoteGit  git+http://ikt.pm2.io/ikt.git#master resetting remote /root/.npm/_git-remotes/git-http-ikt-pm2-io-ikt-git-master-d352a2a2 because of error: { Error: not found: git
npm WARN addRemoteGit     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:63:19)
npm WARN addRemoteGit     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:72:29)
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/which.js:81:16
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:117:15) code: 'ENOGIT' }
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror http://ikt.pm2.io/ikt.git /root/.npm/_git-remotes/git-http-ikt-pm2-io-ikt-git-master-d352a2a2: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror http://ikt.pm2.io/ikt.git /root/.npm/_git-remotes/git-http-ikt-pm2-io-ikt-git-master-d352a2a2: undefined
/usr/bin/pm2 -> /usr/lib/node_modules/pm2/bin/pm2
/usr/bin/pm2-dev -> /usr/lib/node_modules/pm2/bin/pm2-dev
/usr/lib
`-- pm2@1.1.3

npm WARN optional Skipping failed optional dependency /pm2/ikt:
npm WARN not found: git
npm WARN optional Skipping failed optional dependency /pm2/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
>

**Comment by doctori** [comment]
Hi,  
clearly you'll need to install git on your VPS,
to resolve at least : `Error: not found: git`

**Comment by Unitech** [comment]
git ikt dependency replaced with gkt tgz dependency

https://github.com/Unitech/pm2/commit/adcfa078b1061e126d68a919ee02461f53d38f7d

Available in PM2 V2:

```bash
$ npm install Unitech/pm2#development -g
$ pm2 update
```
If there is still a problem, please reopen issue
