### ISSUE TITLE
App [app] with id [2] and pid [26519], exited with code [0] via signal [SIGINT]

### ISSUE THREAD

**Issue by whw1988** [Unitech/pm2#2147]
PM2: 2016-05-10 20:38:47: App name:app id:1 disconnected
PM2: 2016-05-10 20:38:47: App [app] with id [1] and pid [26530], exited with code [0] via signal [SIGINT]
PM2: 2016-05-10 20:38:47: Starting execution sequence in -cluster mode- for app name:app id:1
PM2: 2016-05-10 20:38:47: App name:app id:1 online
PM2: 2016-05-10 20:41:43: App name:app id:2 disconnected
PM2: 2016-05-10 20:41:43: App [app] with id [2] and pid [26519], exited with code [0] via signal [SIGINT]
PM2: 2016-05-10 20:41:43: Starting execution sequence in -cluster mode- for app name:app id:2
PM2: 2016-05-10 20:41:43: App name:app id:2 online
PM2: 2016-05-11 10:22:31: App name:app id:1 disconnected
PM2: 2016-05-11 10:22:31: App [app] with id [1] and pid [26541], exited with code [0] via signal [SIGINT]
PM2: 2016-05-11 10:22:31: Starting execution sequence in -cluster mode- for app name:app id:1
PM2: 2016-05-11 10:22:31: App name:app id:1 online
PM2: 2016-05-11 11:13:44: App name:app id:1 disconnected
PM2: 2016-05-11 11:13:44: App [app] with id [1] and pid [9447], exited with code [0] via signal [SIGINT]
PM2: 2016-05-11 11:13:44: Starting execution sequence in -cluster mode- for app name:app id:1
PM2: 2016-05-11 11:13:44: App name:app id:1 online
PM2: 2016-05-11 11:13:46: App name:app id:3 disconnected
PM2: 2016-05-11 11:13:46: App [app] with id [3] and pid [26446], exited with code [0] via signal [SIGINT]
PM2: 2016-05-11 11:13:46: Starting execution sequence in -cluster mode- for app name:app id:3
PM2: 2016-05-11 11:13:46: App name:app id:3 online

ps:node version and pm2 version

~~~

app@9Z:~$ node --version
v5.1.1
app@9Z:~$ pm2 --version
1.0.0

~~~

**Comment by Unitech** [comment]
Need more data, closing

**Comment by chelsh** [comment]
$ cat pm2.json
{
  "apps": [
    {
      "name": "app",
      "script": "app.js",
      "error_file": "../log/error.log",
      "out_file": "../log/access.log",
      "merge_logs": true,
      "cwd": "./",
      "instances": 0,
      "exec_mode"  : "cluster_mode",
      "env": {
        "NODE_ENV": "production"
      }
    }
  ]
}

**Comment by AndyRoyal** [comment]
how to fix it ?

**Comment by AndyRoyal** [comment]
![image](https://user-images.githubusercontent.com/2374989/155087544-fb9e17dc-fd03-45c0-aa28-2642c6a8f3bf.png)
一直在重启
