### ISSUE TITLE
Default logs are still created if you use `logFile` option

### ISSUE THREAD

**Issue by fresheneesz** [Unitech/pm2#2148]
Is the `logFile` option something that we should even have? You can just specify the same file for `error` and `output` to put both stdout and stderr into the same file.

**Comment by mlovrovich** [comment]
+1

**Comment by vmarchaud** [comment]
See `-l <path>` options [documented here](http://pm2.keymetrics.io/docs/usage/log-management/#cli).

**Comment by fresheneesz** [comment]
@vmarchaud This ticket isn't about documentation. This ticket is suggesting a behavior change or feature removal. Please reopen this.

**Comment by vmarchaud** [comment]
Please details more so, i don't get what you are suggesting.

**Comment by fresheneesz** [comment]
I'm recomending that either:
A. we remove the logFile option entirely (since you can specify the `error` and `output` options already), or
B. that if we keep the `logFile` option, it should *not* still log to default log locations.

**Comment by vmarchaud** [comment]
I understand your suggestion but at the same time people may want all three options to be available at the same time, we can't just change this. 
However, in your configuration you can just redirect `error_log` & `out_file` into `/dev/null` and you are good.

**Comment by fresheneesz** [comment]
@vmarchaud Ok, in that case, the default behavior should be changed so that if you *only* include a the `logFile`, it *only* logs to that specified file and not the default locations.
