### ISSUE TITLE
pm2 will core dump when using in docker

### ISSUE THREAD

**Issue by dynastysea** [Unitech/pm2#2150]
when use pm2 command, it will assert failed! 

`node: ../deps/uv/src/unix/linux-core.c:746: read_times: Assertion 'num == numcpus' failed.
./pm.sh: line 4: 30365 Aborted                 (core dumped) pm2 start ../server/index.js --no-daemon`

i have readed the sourse code, num is get from "cat /proc/cpuinfo", numcpus is get from "sysconf(_SC_NPROCESSORS_CONF)", but _SC_NPROCESSORS_CONF might be possible for the operating system to disable individual processors。 so num may by not equal numcpus。 

i want to know how to fix it~

Thanks all~

**Comment by dynastysea** [comment]
i can provide any information when needed

**Comment by soyuka** [comment]
https://github.com/nodejs/node/issues/6252 ?

**Comment by Unitech** [comment]
Official Docker image released that includes:

- Alpine Linux
- Node.js 4 prebuilt
- PM2 v2 with pm2-docker command
- dumb-init to handle signals in a clean way
- Optional Keymetrics integration

Here is the link to the Docker hub: https://hub.docker.com/r/keymetrics/pm2-docker-alpine/
Github repository: https://github.com/keymetrics/pm2-docker-alpine
