### ISSUE TITLE
Ignore watch PM2 parameter not working ecsystem.json for parse server

### ISSUE THREAD

**Issue by tanzeelrana** [Unitech/pm2#2152]
Hey Guys,

I have setup pm2 to run my parse-server according to the following tutorial 

> https://www.digitalocean.com/community/tutorials/how-to-migrate-a-parse-app-to-parse-server-on-ubuntu-14-04

Now the problem is the I have a logs folder and I it contains 2 types of logs 
- error logs 
- info logs 

Now I want to keep watching the error logs and restart my server just in case but in the info logs I do not want to watch 

my ecosystem.json file looks something like this : 

![eclipse_ _parse_pacecourier____ _ssh_root_159_203_35_195_ _179x25](https://cloud.githubusercontent.com/assets/2520028/15227011/4225316e-1853-11e6-8099-70fa1325c59c.png)

but this does not seem to work. Everytime I have a change in my info log file pm2 restarts my application 

![documents_ _parse_pacecourier___root_ _ssh_root_159_203_35_195_ _179x47](https://cloud.githubusercontent.com/assets/2520028/15223068/8ab85c84-1840-11e6-9786-cc37c2660422.png)

My logs folder looks like this 

![documents_ _parse_pacecourier____logs_ _ssh_root_159_203_35_195_ _179x47](https://cloud.githubusercontent.com/assets/2520028/15222949/fd377386-183f-11e6-9d6a-a592ba0f0d7f.png)

Does any one know how I can make pm2 ignore my info file and not ignore error log files

**Comment by soyuka** [comment]
Can't you just watch the file you need? `watch: 'myerrlog.log'

**Comment by sjmn** [comment]
@tanzeelrana Did you find a solution?  I'm having the precise problem you describe here.

**Comment by tanzeelrana** [comment]
@sjmn no

**Comment by tanzeelrana** [comment]
@sjmn  

I added the logs folder into my ecosystem.json file. I was unable to specifically state a file name pattern to ignore 

`{
    "name"        : "pace app",
    "script"      : "parse-server",
    "ignore_watch": ["logs"],
    "watch"       : true,
    "merge_logs"  : true,
`

**Comment by vmarchaud** [comment]
See #2629 we group all issue into one.
