### ISSUE TITLE
Cannot read property pm2_env of undefined

### ISSUE THREAD

**Issue by lukesneeringer** [Unitech/pm2#2154]
Running pm2 (primarily from Ansible) is now giving this error on 1.1.3:

```
[PM2][WARN] Applications webpack not running, starting...
/usr/lib/node_modules/pm2/lib/CLI.js:461
        Common.printOut(cst.PREFIX_MSG + 'App [%s] launched (%d instances)', data[0].pm2_env.name, data.length);
                                                                                    ^

TypeError: Cannot read property 'pm2_env' of undefined
    at /usr/lib/node_modules/pm2/lib/CLI.js:461:85
    at /usr/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Parser._write (/usr/lib/node_modules/pm2/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:300:12)
    at writeOrBuffer (_stream_writable.js:286:5)
    at Parser.Writable.write (_stream_writable.js:214:11)
    at Socket.ondata (_stream_readable.js:536:20)
```

It turns out that `data` is an empty array.

**Comment by lukesneeringer** [comment]
Here is the full debug output:

```
  pm2:constants PM2 folder (logs, pids, configuration): /home/vagrant/.pm2 +0ms
  pm2:interface:daemon Getting interaction info +152ms
  pm2:interface:daemon [PING INTERACTOR] Trying to connect to Interactor daemon +2ms
  pm2:satan [PING PM2] Trying to connect to server +6ms
  pm2:satan Daemon alive +6ms
  pm2:satan Launching RPC client on socket file /home/vagrant/.pm2/rpc.sock +1ms
  pm2:satan Connected to Daemon +2ms
  pm2:cli Got message from Satan as successfully connected to PM2, now parsing arguments +4ms
  pm2:satan Calling daemon method pm2:getVersion +1ms
  pm2:monit Before processing +10ms { cwd: '/var/may/core/',
  env: { WEBPACK_MODE: 'dev' },
  error_file: '/var/log/may/webpack.error.log',
  exec_interpreter: 'none',
  name: 'webpack',
  out_file: '/var/log/may/webpack.out.log',
  script: 'node_modules/.bin/webpack-dev-server',
  exec_mode: 'fork_mode' }
  pm2:monit After processing +17ms { errors: [],
  config:
   { script: 'node_modules/.bin/webpack-dev-server',
     name: 'webpack',
     error_file: '/var/log/may/webpack.error.log',
     out_file: '/var/log/may/webpack.out.log',
     cwd: '/var/may/core/',
     vizion: true,
     pmx: true,
     automation: true,
     autorestart: true,
     treekill: true,
     env: { WEBPACK_MODE: 'dev' },
     exec_mode: 'fork_mode',
     exec_interpreter: 'none' } }
  pm2:satan Calling daemon method pm2:getMonitorData +3ms
[PM2][WARN] Applications webpack not running, starting...
  pm2:satan Calling daemon method pm2:prepare +8ms
/usr/lib/node_modules/pm2/lib/CLI.js:461
        Common.printOut(cst.PREFIX_MSG + 'App [%s] launched (%d instances)', data[0].pm2_env.name, data.length);
                                                                                    ^

TypeError: Cannot read property 'pm2_env' of undefined
    at /usr/lib/node_modules/pm2/lib/CLI.js:461:85
    at /usr/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Parser._write (/usr/lib/node_modules/pm2/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:300:12)
    at writeOrBuffer (_stream_writable.js:286:5)
    at Parser.Writable.write (_stream_writable.js:214:11)
    at Socket.ondata (_stream_readable.js:536:20)
```

**Comment by vjpr** [comment]
I'm getting the same error. Running 1.1.3 too.

**Comment by cnjsstong** [comment]
Same error.

**Comment by cnjsstong** [comment]
Fix it by making sure pm2 has the privilege to write to the log folder.

**Comment by Unitech** [comment]
Please make sure that you did `pm2 update`  after installing the latest PM2 version

**Comment by rarutu** [comment]
spot on @cnjsstong :+1: :)

**Comment by centigrade-thomas-becker** [comment]
> Please make sure that you did pm2 update after installing the latest PM2 version

This was the fix to my problem. I included this as a post install step in the package.json to prevent this from happening again.

However, now I want to move my pm2 integration from shell scripts to a gulp tasks, and there is no command "update" in the [PM2-API](http://pm2.keymetrics.io/docs/usage/pm2-api/). What is the api equivalent to calling `pm2 update` from the console?

**Comment by vmarchaud** [comment]
You should can do a `pm2.update` since its defined in the API [here](https://github.com/Unitech/pm2/blob/master/lib/API.js#L352), the documentation isnt currently up-to-date, refer to the API object for accurate methods.

**Comment by jchappell82** [comment]
I'm failing to grasp how `pm2 update` is the solution here.  I'm getting the exact same error, and this is a _fresh_ pm2 installation. There has never been any previous version of pm2 on the server.  My understanding from the docs is that `pm2 update` forces the currently running pm2 god process to be replaced by an updated version, which makes sense in the case of an actual upgrade.  It does not at all seem to describe that it affects any configuration.   Can you help me understand what I'm missing in what it's doing here?

**Comment by vmarchaud** [comment]
@jchappell82 Cause it isnt the solution. We do write a lot to execute an `pm2 update` cause a lot of people do the update but dont reload the pm2 daemon.

The solution here has been wrote by @cnjsstong : 
`Fix it by making sure pm2 has the privilege to write to the log folder.`

**Comment by centigrade-thomas-becker** [comment]
@vmarchaud It was the solution to my problem. The error occured only on a windows system, and folder permissions were not an issue there. Using `pm2 update` seemed to fix it.

**Comment by jchappell82** [comment]
@vmarchaud - Turns out you're right. Thanks! The actual issue it was having in my case was due to pm2 being run as a user who had just been added to the group that would have granted write permissions to the log folder, but had not created a new session due to the way my configuration management software (Ansible in this case) was processing commands.

**Comment by nkostic** [comment]
Can not get to work it on Windows and I tried all the answers. Any Ideas ? Here is my Dockerfile:
`FROM keymetrics/pm2:latest

# Bundle APP files
COPY . opt/mighty/
COPY package.json .
COPY pm2.json .

# Install app dependencies
ENV NPM_CONFIG_LOGLEVEL warn
RUN npm install --production

# Show current folder structure in logs
RUN ls -al -R

CMD [ "pm2-docker", "start", "pm2.json" ]`

**Comment by yogithesymbian** [comment]
> pm2 kill

how to do that ? can you comment with sytnx cli.
i have run pm2 update and its working 
but when i tried to re run `pm2 restart ecosystem.config.js --env production -i -1 --parallel 1 --wait-ready` just work once , the next run / restart its happen again and again.
