### ISSUE TITLE
Strange behavior related to `minUptime`

### ISSUE THREAD

**Issue by fresheneesz** [Unitech/pm2#2155]
The `minUptime` parameter doesn't seem to be working right for me. I have the following files:

pmErrTest.js:

``` javascript
var pm2 = require('pm2');

pm2.connect(function(err) {
  if (err) {
    console.error(err)
    process.exit(2)
  }

  pm2.start({
    script: 'errTest.js',
    output: 'errOutput.txt', error: 'errOutput.txt',
    minUptime: 1, maxRestarts: 10
  }, function(err, apps) {
    if(err) console.log(err)
    pm2.disconnect()
  })
})
```

errTest.js:

``` javascript
setTimeout(function() {
  console.log('test')
},1500)
```

I would have expected instead for it to "successfully" start, and then see logs in `~/.pm2/pm2.log` every 3 seconds or so. 

Instead, when I run `node pmErrTest`, I get the following result on the console: `{ success: false }`. Doing a pm2 list returns an empty array. Also strangely, no `errOutput.txt` file is created. I do get the following single line in `~/.pm2/pm2.log`: 

`2016-05-12 18:16:11: [PM2][WORKER] Started with refreshing interval: 30000`

What does that refreshing interval message mean anyway?

Furthermore, if I change `minUptime` to 1000, it exists silently (presumably successfully). But while  `errOutput.txt` _is_ created, it only gets one line "test", which never repeats - indicating to me that the process isn't being restarted. Doing a pm2 list at this point returns one result with a bunch of info about the process I started. The list of info includes `status: 'online'` when its clearly impossible that the script is "online" if its not putting output in `errOutput.txt`. In this case, `~/.pm2/pm2.log` doesn't receive any additional lines (and isn't created if its not already there). 

If I remove the `minUptime` and `maxRestarts` parameters entirely, much the same thing happens except that `~/.pm2/pm2.log` _is_ created and gets the following logs:

```
2016-05-12 18:23:43: [PM2][WORKER] Started with refreshing interval: 30000
2016-05-12 18:23:44: Starting execution sequence in -fork mode- for app name:errTest id:0
2016-05-12 18:23:44: App name:errTest id:0 online
```

In this case as well, a pm2 list command shows that the script's status is "online" regardless of the fact that no output is being created.  

I'm using version 1.1.1 on node v5.1.0

**Comment by Unitech** [comment]
Could you try min_uptime instead?

Basically the object you pass as the first parameter of pm2 is the same object than in a json application declaration

Here is the schema: https://github.com/Unitech/pm2/blob/master/lib/CLI/schema.json#L130

**Comment by fresheneesz** [comment]
@Unitech `minUptime` clearly has an effect because changing it changes behavior. I just tried with `min_uptime` instead, and its all the exact same behavior.
