### ISSUE TITLE
pm2 logs won't show "debug" module colors.

### ISSUE THREAD

**Issue by sulliwane** [Unitech/pm2#2156]
Hello,

I require [debug](https://www.npmjs.com/package/debug) module to control log output of my app, it looks like this:
![screenshot from 2016-05-13 10 41 46](https://cloud.githubusercontent.com/assets/1733686/15236854/7d2c429a-18fb-11e6-8367-2910f3ca750d.png)

Now that I moved to **pm2**, logs look like this:
![screenshot from 2016-05-13 10 40 43](https://cloud.githubusercontent.com/assets/1733686/15236894/cbb4e0c0-18fb-11e6-8119-633e7dd66daa.png)

I lost the colors and the time in ms taken by each request. Is there away to preserve **debug** style in **pm2** logs?

Thank you !

**Comment by kevhuang** [comment]
@sulliwane You can set the `DEBUG_COLORS` env to "true" and then run `pm2 logs --raw`

**Comment by sulliwane** [comment]
thanks @kevhuang for your answer, but adding ```DEBUG_COLORS=true``` to my env, and  ```pm2 logs --raw``` doesn't help. No colors now:
![screenshot from 2016-05-16 09 33 31](https://cloud.githubusercontent.com/assets/1733686/15278290/4851cafe-1b49-11e6-9769-dca930c9739b.png)

**Comment by sulliwane** [comment]
Sorry my bad, it is actually working. The colors just appeared! i'm not sure why though.

And the date that was added by pm2 doesn't show up anymore, with or without ```-- raw``` option. It will surely make sense after a system restart and some later investigations.

Anyway, many thanks !

**Comment by Unitech** [comment]
https://github.com/Unitech/pm2/blob/master/lib/CLI/Log.js#L51
