### ISSUE TITLE
pm2 ssh connection with parameters 

### ISSUE THREAD

**Issue by tbouchnafa** [Unitech/pm2#2157]
Hi, 

when i want to deploy for the first time on a server from another using pm2 i need to add the ssh key to the known hosts of the server 
in my case: from jenkins --> app server
in this case i need a user interaction: 
```
Are you sure you want to continue connecting (yes/no)? yes
```
however connecting to the server with ssh using the `StrictHostKeyChecking` option overdo this interaction
```
ssh -o StrictHostKeyChecking=no username@hostname.com
```
Is there a way to overgive pm2 options for the ssh connection? 

Thanks in advance

**Comment by Unitech** [comment]
```
$ ssh-keyscan -H <HOST> >> /home/`process.env.USER`/.ssh/known_hosts
```
