### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined after upgrade from 0.8.13

### ISSUE THREAD

**Issue by tdaugaard** [Unitech/pm2#2159]
We've had some really old PM2 instances running and I recently upgraded them to the latest PM2 v1.1.3 but that caused some of them to throw a TypeError exception when I ran `pm2 desc <id>`.

The complete error and stack trace is here:

```
/usr/local/lib/node_modules/pm2/lib/CLI/CliUx.js:99
            { 'interpreter args' : pm2_env.node_args.length != 0 ? pm2_env.nod
                                                    ^
TypeError: Cannot read property 'length' of undefined
    at Object.UX.describeTable (/usr/local/lib/node_modules/pm2/lib/CLI/CliUx.js:99:53)
    at /usr/local/lib/node_modules/pm2/lib/CLI.js:1450:12
    at Array.forEach (native)
    at /usr/local/lib/node_modules/pm2/lib/CLI.js:1449:18
    at /usr/local/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at Parser.EventEmitter.emit (events.js:95:17)
    at Parser._write (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:223:10)
    at writeOrBuffer (_stream_writable.js:213:5)
```

Google was no help, so I solved it simply by editing `CliUx.js` manually, changing line 99 from:
```
{ 'interpreter args' : pm2_env.node_args.length != 0 ? pm2_env.node_args : null },
```
to
```
{ 'interpreter args' : pm2_env.node_args ? pm2_env.node_args.length != 0 ? pm2_env.node_args : null : null },
```
(preceeding white-space omitted)

I thought I'd create an issue here since I have been unable to find this error in conjuction with an upgrade and as such, it would be good to have it fixed.

**Comment by Unitech** [comment]
The communication interface has been refactored since old PM2 version (from NET to UNIX socket),

There were strategies earlier to detect old interface for a seamless upgrade, but it has been deprecated since the 1.X

In case someone else find this issue again, make sure you save your process (pm2 save) then kill pm2 (pm2 kill), install the latest PM2 (npm install pm2 -g) and do a a pm2 resurrect
