### ISSUE TITLE
socket hang up during connection

### ISSUE THREAD

**Issue by shiroganee** [Unitech/pm2#2162]
Hello,

I wanted to give Keymetrics and Pm2 a try but whenever I use pm2 link i get xxx xxx a problem with socket hang up

![image](https://cloud.githubusercontent.com/assets/9503398/15247946/a19f158c-1917-11e6-85e5-c3da1bdeb11e.png)

What might be the reason of that? I'm running on Node 5.10.0

**Comment by Jossbly** [comment]
Same problem here

**Comment by soyuka** [comment]
https://twitter.com/keymetrics_io/status/731106845557960704 ?

**Comment by Unitech** [comment]
issue fixed since Friday
