### ISSUE TITLE
pm2 kills my program with "Did you forgot to call pm2.connect(function() { }) before interacting with PM2 ?"

### ISSUE THREAD

**Issue by fresheneesz** [Unitech/pm2#2163]
This one is really bad form. Instead of getting an exception with a stack-trace, it just prints this to the console and EXITS YOUR PROGRAM. A module like this should NEVER do that. It prevents graceful failure and other error handling. Please fix this

I'd also recommend doing an audit of your code to see where there might be other places where the CLI is assumed when the API might be being used.

**Comment by Unitech** [comment]
fixed  in dev branch

The API really needs a deep refactor

**Comment by fresheneesz** [comment]
Thanks!
