### ISSUE TITLE
programmatic tests vs. bash scripts - spec shell command

### ISSUE THREAD

**Issue by ORESoftware** [Unitech/pm2#2165]
I am wondering what the spec command is in your bash scripts

for example:

```
bash ./test/bash/cli-actions-1.sh
spec "CLI basic test"
```

or

```
mocha ./test/programmatic/god.mocha.js
spec "God test"
```

**Comment by Unitech** [comment]
it's raw bash tests, the command "spec" is here: https://github.com/Unitech/pm2/blob/master/test/bash/include.sh#L27

**Comment by ORESoftware** [comment]
ah thanks
