### ISSUE TITLE
Improvement: Automatically manage connection and disconnection

### ISSUE THREAD

**Issue by fresheneesz** [Unitech/pm2#2167]
I propose that all the api methods automatically connect and disconnect from pm2. I would imagine most if not all uses of pm2 wouldn't be significantly slowed down if pm2 was connected to and then disconnected from on *every* method call. It is running on the local machine after all. 

If there are legitimate cases where pm2 might being called thousands of times a second, you could switch into a different mode that allows more explicit control over disconnection (explicit control over connection isn't needed even in this case tho).

I recently ran into issues related to disconnection, that I wrote another issue for here: https://github.com/Unitech/pm2/issues/2166 . If connection and disconnection were automatically managed, it would solve that problem too.

**Comment by fresheneesz** [comment]
This is still a problem in Unitech/pm2#v2

**Comment by Unitech** [comment]
this feature will be for next versions

**Comment by Unitech** [comment]
feature implemented you can now do:

```javascript
var pm2 = require('pm2');

pm2.start('myscript.js', (err, procs) => {
});

// Or via custom PM2 instance

var ipm = new pm2.custom();

ipm.start('script.js', (err, procs) => {});
```

**Comment by Unitech** [comment]
auto exit implemented by calling [socket.unref](https://nodejs.org/api/net.html#net_server_unref) on RPC connection
