### ISSUE TITLE
pm_id question

### ISSUE THREAD

**Issue by crh3675** [Unitech/pm2#2169]
We run about 10 instances and use PM2 to monitor.
- 4 applications forked
- 2 applications clustered (2 instances and 4 instances)

For the clustered instances, I want to fire a certain set of functionality but only for one of the clustered instances.  We do have an older version, 0.15.7.  The original idea was to use **pm_id** but we soon realized that it increments for all instances.

We essentially need to know which instance for which application and we are not sure how to determine that. Examples, application X is clustered with 4 instances, we might query something like **process.env.APP_INSTANCE_ID** which would only pertain to that one application and be incremented based on the other applications. So, app X that runs 4 instances should have APP_INSTANCE_IDs 1,2,3,4.  As well, app Y that runs 2 instances should have APP_INSTANCE_IDs 1 and 2.

**Comment by crh3675** [comment]
Is there a response to this?  Help is appreciated.

**Comment by soyuka** [comment]
Can you check the env variable `NODE_APP_INSTANCE`?

**Comment by crh3675** [comment]
I don't think that variable exists in our 0.15.7 version

**Comment by crh3675** [comment]
It looks like https://github.com/Unitech/pm2/blob/v0.15.x/lib/God.js doesn't copy that variable in so it is not available

**Comment by soyuka** [comment]
Can't you update pm2?

**Comment by crh3675** [comment]
Why is this closed?

**Comment by vmarchaud** [comment]
No update here since soyuka tell you to upgrade so i guess it the upgrade fixed the problem, if not tell me.

**Comment by crh3675** [comment]
Ok thanks.  Still haven't upgraded though.  I will get that upgrade completed.

**Comment by Besatnias** [comment]
@crh3675 do you remember whether this update solved your problem?
