### ISSUE TITLE
Always use Error objects

### ISSUE THREAD

**Issue by fresheneesz** [Unitech/pm2#2172]
I'm catching some errors from pm2 that are objects like `{success:false, msg: "some error message"}`. This is unexpected and against standards. Printing out something like this gives you the incredibly unhelpful "[Object object]" string, and expecting all errors to have a 'message' property makes the 'msg' property incredibly error prone.

Please audit the code and replace stuff like this with *actual* error objects.

**Comment by fresheneesz** [comment]
I'm trying very hard to control my rage here. On PRODUCTION, after everything was working fine, it all quit overnight and now when I'm trying to restart things, all I get back is an "error" object (not an Error object) that contains `{success:false}`. NO message, NOTHING. What am I supposed to do with this bullshit? I have no idea why its failing!

My app log isn't created, indicating that the app wasn't event started. And there's NO pm2.log in `~./pm2/`. WTF?

**Comment by fresheneesz** [comment]
Ok, in my particular case, I was passing in an object as the script path. Its pretty confusing to me why I didn't get an error message like "script not found", because I have seen that error in the past..

**Comment by fresheneesz** [comment]
FYI, I haven't seen pm2 crash since that one time. 24 days uptime on my longest running stuff at this point.

**Comment by fresheneesz** [comment]
Now (on Unitech/pm2#v2) instead of `{success:false}` I'm seeing `[Error: Expect "script" to be a typeof [object String], but now is [object Object]]`. So I'm marking this good! Thanks

**Comment by fresheneesz** [comment]
@Unitech Please reopen this, I'm still seeing non-Error objects being returned in Unitech/pm2#v2. Here's the case:

`
var pm2 = new require('pm2')()

pm2.connect(function(err) {
  if (err) {
    console.error(err)
    process.exit(2)
  }

  pm2.start({
    script: 'errTest.js',
    output: 'errOutput.txt', error: 'errOutput.txt',
    min_uptime: 1000, maxRestarts: 10
  }, function(err, apps) {
    if(err) console.log(err)
    pm2.disconnect()
  })
})
`

My output is:
`
[PM2] Spawning PM2 daemon with pm2_home=/home/vagrant/.pm2
{ msg: 'secret key is not defined' }
[PM2] PM2 Successfully daemonized
`

The other problem there is obviously the "[PM2]" print statements that shouldn't be happening when the api is being used (as opposed to the CLI).

**Comment by Unitech** [comment]
Fixed in #v2
