### ISSUE TITLE
Cannot install pm2

### ISSUE THREAD

**Issue by anubhav7495** [Unitech/pm2#2173]
```
-bash: /usr/local/bin/pm2: No such file or directory
```

This is the error i get after installing pm2 and trying to run it.

**Comment by fresheneesz** [comment]
pm2 is a node.js script - you can't run it with bash. Simply doing `./pm2 list` etc is all you need to do. You can also do `node .../bin/pm2 list` but you can use it as if it was a binary program.

**Comment by anubhav7495** [comment]
I think you misunderstood. The steps i took are:

```
$ sudo npm install -g pm2

// After it is successfully installed.

$ pm2

// throws the error i mentioned in previous comment.
```

**Comment by Pumych** [comment]
The same issue, solved by:
$ sudo pm2

**Comment by Pumych** [comment]
The same issue, solved by:
$ sudo pm2

**Comment by Pumych** [comment]
The same issue, solved by:
$ sudo pm2

**Comment by Pumych** [comment]
The same issue, solved by:
$ sudo pm2

**Comment by Pumych** [comment]
The same issue, solved by:
$ sudo pm2

**Comment by Pumych** [comment]
The same issue, solved by:
$ sudo pm2

**Comment by Pumych** [comment]
The same issue, solved by:
$ sudo pm2
