### ISSUE TITLE
Daemonized processes are killed if the PM2 process dies

### ISSUE THREAD

**Issue by fresheneesz** [Unitech/pm2#2174]
In testing, if I use `kill` to kill the PM2 God process, all its daemonized processes are also killed. This is problematic if PM2 crashes for whatever reason - which has already happened to me in one day of use (https://github.com/Unitech/pm2/issues/1809). Wouldn't it be far better if PM2 could completely die without also killing its entire application tree? Yes, it would be best if PM2 never crashes, but that's not a feasible approach.

**Comment by Unitech** [comment]
PM2 has a lot of strategies to always stay alive, and this strategy is reinforced when PM2 is linked to Keymetrics (external Watchdog),

Processes managed are tightly linked to PM2 to offer more advanced features like cluster, monitoring
