### ISSUE TITLE
support Q => what ascii table generator is used

### ISSUE THREAD

**Issue by ORESoftware** [Unitech/pm2#2178]
Hi all - simple question here - would you mind divulging which library you use to generate the ascii tables for your lib? Quite nice stuff, I looked through your codebase and I couldn't find the answer - please let me know thanks!

**Comment by Unitech** [comment]
https://github.com/Unitech/pm2/blob/master/package.json#L155 ;)

**Comment by ORESoftware** [comment]
thanks, I grepped for table in the repo and came up with nothing, weird

**Comment by soyuka** [comment]
Be careful with the library, there is a weird bug https://github.com/Automattic/cli-table/pull/83

**Comment by ORESoftware** [comment]
thanks for the warning, is the bug overwhelming?
