### ISSUE TITLE
Install failed on Ubuntu 15.10, Node 6.0.0, npm 3.8.9

### ISSUE THREAD

**Issue by marckris** [Unitech/pm2#2179]
npm install pm2@latest -g

/usr/local/bin/pm2 -> /usr/local/lib/node_modules/pm2/bin/pm2
/usr/local/bin/pm2-dev -> /usr/local/lib/node_modules/pm2/bin/pm2-dev
/usr/local/lib
└─┬ pm2@1.1.3 
  └── ikt@0.0.0  (git+http://ikt.pm2.io/ikt.git#3325a3e39a502418dc2e2e4bf21529cbbde96228)

npm WARN optional Skipping failed optional dependency /pm2/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12

**Comment by soyuka** [comment]
Everything went fine, those are just warnings
