### ISSUE TITLE
Not restarting when directory specified in 'watch' changes

### ISSUE THREAD

**Issue by geuis** [Unitech/pm2#2180]
I need pm2 to restart when any files in a series of specified directories changes. In this particular case, those directories are "node_modules" in a series of projects in child directories that all have their own node_modules. Currently, I'm making changes in a test directory manually but pm2 isn't responding.

I'm using the following pm2 config:

```
{
  "apps": [{
    "name": "module-link",
    "script": "module-link",
    "watch": ["sub-proj1/node_modules"],
    "cwd": "/usr/local/apps/pm2-test-restart",
    "merge_logs": true
  }]
}
```
I've tried variations of the 'watch' property like './sub-proj1' and '../sub-proj1', etc.

**Comment by soyuka** [comment]
You can see what arguments are given to chokidar by activating the debug flag (DEBUG="pm2:*" pm2 start yourapp.json --no-daemon"), check also `~/.pm2/pm2.log` and please paste `head -n 50 ~/.pm2/pm2.log`

**Comment by benishak** [comment]
i have the same problem I run my app with `--watch` but when error happens, pm2 doesn't restart the app

**Comment by geuis** [comment]
@soyuka I've modified the config to the basics to confirm that 

1. changes to any other directory trigger a restart
2. node_modules is specifically being ignored

```
{
  "apps": [{
    "name": "module-link",
    "script": "module-link",
    "watch": ".",
    "cwd": "/usr/local/apps/pm2-test-restart",
    "merge_logs": true
  }]
}
```

These are the relevant DEBUG logs. Notice that node_modules is specifically being ignored.

```  config: 
   { script: 'module-link',
     name: 'module-link',
     cwd: '/usr/local/apps/mop-reference',
     merge_logs: true,
     vizion: true,
     pmx: true,
     automation: true,
     autorestart: true,
     treekill: true,
     watch: '.',
     exec_mode: 'fork_mode' } }
  pm2:satan Calling daemon method pm2:getMonitorData +0ms
  pm2:satan Calling daemon method pm2:prepare +7ms
  pm2:watch Initial watch  +4ms .
  pm2:watch Watching . +0ms
  pm2:watch Watch opts +0ms { ignored: /[\/\\]\.|node_modules/,
  persistent: true,
  ignoreInitial: true,
  cwd: '/usr/local/apps/mop-reference' }
```

In looking through pm2's source, notice line 40 https://github.com/Unitech/pm2/blob/79ba743723131436bd049cc952e2b1f1158bc84c/lib/Watcher.js#L40

```
    var watch_options = {
      ignored       : pm2_env.ignore_watch || /[\/\\]\.|node_modules/,
      persistent    : true,
      ignoreInitial : true,
      cwd: pm2_env.pm_cwd
    };
```

**Comment by soyuka** [comment]
Note in your case the path is `/usr/local/apps/pm2-test-restart`, this does work to me:

https://asciinema.org/a/6fn63wo2mfqvnare0x4bubzxs

**Comment by geuis** [comment]
@soyuka I don't know what point you're trying to get across. The problem I'm describing is that I can't find a way to get pm2 to detect changes inside a node_modules directory. It seems to be written specifically to ignore the directory with no option to enable it.

**Comment by soyuka** [comment]
Just ignore nothing, yes `node_modules` are ignored by default, so change it by `ignore_watch: []`.

**Comment by benishak** [comment]
@soyuka can I ignore verbose and info logs?

**Comment by soyuka** [comment]
@benishak I'm sorry I didn't understood. You can ignore what you want: `ignore_watch: ['logs', '.git']`.

**Comment by benishak** [comment]
info logs in this way
`logger.info()` or `logger.verbose()` lead pm2 to restart the process ... 
Check this issue #2152
https://github.com/Unitech/pm2/issues/2152
