### ISSUE TITLE
Question mark before application/file name

### ISSUE THREAD

**Issue by m-menon** [Unitech/pm2#2183]
I have installed pm2 and it all went on fine. But I see a few question (?) marks when I run pm2 monit which I don't really understand what it means. I have set up the monitoring server too, as specified in https://app.keymetrics.io console.

```
? PM2 monitoring (To go further check out https://app.keymetrics.io)

? pm2-server-monit                    [                              ] 0 %
[0] [fork_mode]                        [|||||                         ] 31.375 MB

? index                               [                              ] 0 %
[1] [cluster_mode]                     [||||||||                      ] 47.734 MB

? index                               [                              ] 0 %
[2] [cluster_mode]                     [||||||||                      ] 47.398 MB

? index                               [                              ] 0 %
[3] [cluster_mode]                     [||||||||                      ] 46.418 MB
```

The question marks that I am referring to are the ones in front of "index" e.g "**? index**"
I can see from some of the other screenshots on the web that it is supposed to be either a green or red circle. I have no idea as to what those circles are. Anyone can help me understand?

Thanks,
M.M

**Comment by soyuka** [comment]
Utf8 issue.

**Comment by m-menon** [comment]
I did a 

> localectl status

 and I got the following result

```
# localectl status
   System Locale: LANG=en_US.UTF-8
       VC Keymap: us
      X11 Layout: us
```

Any suggestion on where I should be looking at to fix this? Thanks

**Comment by soyuka** [comment]
Hmm, I'd look on the terminal emulator side. For example, I use rxvt-unicode and have no format issues.
