### ISSUE TITLE
How do you restart pm from a dump?

### ISSUE THREAD

**Issue by fresheneesz** [Unitech/pm2#2184]
I see that the `dump` method records all the relevant pm2 state into a file in `~/.pm2/dump.pm3`. If I want to use that to start pm2, what do I do?

**Comment by fresheneesz** [comment]
Ok, there's a `resurrect` command on the CLI. Is that also available in API form?

**Comment by soyuka** [comment]
Yes

**Comment by fresheneesz** [comment]
Could someone add it to the docs please? https://github.com/pm2-hive/pm2-hive.github.io/blob/master/docs/features/pm2-api.md
