### ISSUE TITLE
pm2 1.1.3: suffix pids when start with merge_logs true

### ISSUE THREAD

**Issue by alexzyp** [Unitech/pm2#2186]
Here's my process.json file:

``` javascript
{
  "name"     : "www",
  "script"   : "bin/www",
  "instances": 0,
  "merge_logs": true,
  "exec_mode": "cluster",
  "env": {
    "NODE_ENV": "development",
  },
  "env_production" : {
    "NODE_ENV": "production"
  }
}
```

after `pm2 start process.json`, there're four pid files.
`www-0.pid  www-1.pid  www-2.pid  www-3.pid`
then `pm2 reload www`, the new four processes had pid path: www.pid.

**Comment by kocuroglu** [comment]
Same here when killing the process with `kill <pid>`

This breaks my monit configuration.
