### ISSUE TITLE
Any way to flush logs automatically?

### ISSUE THREAD

**Issue by kylezengTR** [Unitech/pm2#2187]
Hi, is there any way to clean up all of the logs file under {home}/.pm2/logs automatically with given period?
Every 5 days or less, the log files will be full of my disk space.
I think log-rotate will only splits the logs, is that correct?

**Comment by AntJanus** [comment]
I had the same issue. Use cron to do it, that'd be my best bet.

**Comment by soyuka** [comment]
logrotate will remove files after `12` rotations according to [our configuration](https://github.com/Unitech/pm2/blob/master/lib/scripts/logrotate.d/pm2#L2). It can be too much, so adjust the parameter ;). I put a high number by default on purpose.

Lot of informations available there too: http://stackoverflow.com/questions/14858752/logrotate-to-clean-up-date-stamped-files
