### ISSUE TITLE
How to enable SSL on pm2 server application

### ISSUE THREAD

**Issue by matt212** [Unitech/pm2#2189]
Hi, 

How to enable ssl on pm2 served application

**Comment by soyuka** [comment]
The same you'd do without pm2: https://nodejs.org/api/https.html

**Comment by matt212** [comment]
Hi soyuka , 
Would this will work on aws envirnoment ? just curious

**Comment by soyuka** [comment]
Why wouldn't it?

**Comment by matt212** [comment]
Will try and get back to you !.another note github should have chat !

**Comment by unknownterritory** [comment]
While, as @soyuka pointed out, Node.js is perfectly capable of serving an app over https, there's [good reasons](https://medium.com/intrinsic/why-should-i-use-a-reverse-proxy-if-node-js-is-production-ready-5a079408b2ca) to use a reverse proxy instead. As a former leader of the Node.js project put it:

> If #nginx isn’t sitting in front of your node server, you’re probably doing it wrong. [Bryan Hughes](https://twitter.com/nebrius/status/505543249969176576?ref_src=twsrc%5Etfw).

PM2 has a [documentation page on it](https://pm2.keymetrics.io/docs/tutorials/pm2-nginx-production-setup) as well.
