### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by positlabs** [Unitech/pm2#2192]
I'm using `child_process.exec` to call `pm2 restart {process}`, and it's failing with `TypeError`.

<img width="914" alt="screen shot 2016-05-27 at 11 44 30 am" src="https://cloud.githubusercontent.com/assets/1918844/15620495/5dbfca70-240f-11e6-8c16-cf935c23fb39.png">

Calling `pm2 restart {process}` from the command line works just fine, so I'm confused about why it's failing when I use `child_process.exec`

Here's the config file...

```javascript
{
	"apps" : [{
		"name": 		"git-hooks",
		"script": 		"./server.js",
		"env": {
			"NODE_ENV": "development",
			"PORT": 	3333
		},
	}]
}
```

**Comment by Unitech** [comment]
Avoid passing environments variable while it's being inspected for fix on next release:

```javascript
child_process.exec(`pm2 reload test_pm2_main`, { env : {
    PATH : process.env.PATH,
    HOME : process.env.HOME
}}, function(err, stderr, stdout) {
    console.log(err, stderr, stdout);
});
```

#2176

**Comment by KronKraken** [comment]
I'm having the same issue on Node v4.5.0, Debian.
