### ISSUE TITLE
pm2 not reacting to any command

### ISSUE THREAD

**Issue by AFakeman** [Unitech/pm2#2200]
I am new to this, basically I just downloaded nodejs, npm and pm2 on my Ubuntu AWS Instance, and tried launching something with pm2 start smth.py. Got no output on this command, and got suspicious. Any command like pm2 asdadadasdas will produce no error nor any other output.

**Comment by raine** [comment]
Check `pm2 logs` for a clue.

**Comment by Unitech** [comment]
tail -f ~/.pm2/pm2.log

**Comment by kiranvm** [comment]
Hi I am facing the same issue .
OS version : Ubuntu 14.04

Steps performed.
1. $ sudo su -
2. $ npm install pm2 -g (Successfully installed)
3. $ pm2 startup ubuntu (no response)
4. $ pm2 list (no response)
5. $ which pm2 
        /usr/local/bin/pm2

There is no hidden folder .pm2 created in home path.
Please share in case of any suggestions.
Thank you.

**Comment by Unitech** [comment]
upgrade to latest pm2
