### ISSUE TITLE
Logging: PM2 is still writing an out-file by using only -l and -e options

### ISSUE THREAD

**Issue by Dameck** [Unitech/pm2#2205]
Hi folks,

I'm starting PM2 with -l and -e option to log only err-logs and all-logs (err+out) and I noticed, that PM2 is still writing an out-file in ~/.pm2/log/. I don't see an option in PM2 to prevent that. Could you set the -o option optional if someone needs the out-logs?

**Comment by mlovrovich** [comment]
+1

**Comment by vmarchaud** [comment]
Shouldn't be a problem with pm2 v2 : `npm install -g pm2 && pm2 update`
