### ISSUE TITLE
i think pm2.gracefulReload fails with address already in use

### ISSUE THREAD

**Issue by wowzaaa** [Unitech/pm2#2207]
Hi

My code looks like this

``` javascript
pm2.connect((err) => {
    if (err) {
        throw err;
        process.exit(2);
        return;
    }
    pm2.gracefulReload(app, (err, _) => {
        pm2.disconnect();
        if (err) {
            process.chdir(path);
            throw err;
            return;
        }
        process.chdir(path);
        res.status(200).json({ message : 'success' });
    });
});
```

my pb is that i keep getting address already in use :(

**Comment by rarutu** [comment]
maybe it is useful to mention that this script is starting while a demo is already in place .. what it needs to do is attach itself to the existing demo and reload a specific app

**Comment by vmarchaud** [comment]
Try updating to latest pm2 version : `npm install -g pm2 && pm2 update`
