### ISSUE TITLE
[PM2][WORKER] Started with refreshing interval: 30000

### ISSUE THREAD

**Issue by Malkiat-Singh** [Unitech/pm2#2208]
Pm2 stops after 2-3 days and logs have 
[PM2][WORKER] Started with refreshing interval: 30000
Any idea guys?

**Comment by Unitech** [comment]
if you can provide us more info that would be helpful ;)

**Comment by Malkiat-Singh** [comment]
Ubuntu OS kill process

**Comment by vmarchaud** [comment]
Please provide a way to reproduce the issue and more information about the versions that you run (node/pm2/ubuntu).
