### ISSUE TITLE
Lost process

### ISSUE THREAD

**Issue by danielmetta** [Unitech/pm2#2211]
I have a problem in the PM2 will that ever happened to anyone .

I give start in some applications and they usually appear in the list when I run pm2 list . But after a few days the applications disappear from the list pm2 . They continue working anymore can only find them when I run ps aux | grep node , as the image below.

http://i.stack.imgur.com/CfoyC.jpg

Already uninstalled the PM2 reinstalled the worst that happens with more than one server . Does anyone have any ideas?

**Comment by Unitech** [comment]
There is a second instance running under the root user,

Do:
```
$ PM2_HOME='/root/' pm2 kill
```

To install pm2-server-monit:

```
$ pm2 install pm2-server-monit
```
