### ISSUE TITLE
EADDRINUSE when running express app via pm2

### ISSUE THREAD

**Issue by randeepbhatia** [Unitech/pm2#2212]
Hi
I have both websocket & webserver running in same app. But when I try to launch the app using 
pm2 start server.js -i max, the app server comes up fine, but it raises exception when starting websocket server.

**Comment by Unitech** [comment]
Are you using primus? socket.io?

Btw you should handle real time connections in a different process

**Comment by vmarchaud** [comment]
Shouldn't be a problem with pm2 v2 : `npm install -g pm2 && pm2 update`
