### ISSUE TITLE
reload/restart a single app from the json config file

### ISSUE THREAD

**Issue by e-wiese** [Unitech/pm2#2214]
Hi, I have about 20 apps like the following defined in my json config file:

```
"apps" : [{
     "name"         : "BNC-PPP-3",
     "script"       : "bin/bnc-ppp",
     "args"         : ["--conf", "./etc/ppp_3.bnc", "--nw"],
     "exec_interpreter": "none",
     "cwd"          : "/home/rtmon/ppptest",
},...]
```

The apps configured here are all _binaries_ in _fork-mode_. 
Now I want to change the configuration for only one app. How can I reload and restart this app without resarting all configured apps in this json file? That means something like `pm2 reload myconf.json app3` would be handy. And it's really crucial  that only that one gets restarted. 
#1650 is closed but didn't work for this constellation. (/cc @tomwang1013) PM2 still restarts all jobs without reloading my changes in the json-file. So I still have to delete and start again what is quite cumbersome.

Otherwise it's a great tool, many thanks.
I'm using **pm2 v1.1.3** with **Node.js v4.4.5** on **CentOS 6.8**

**Comment by Unitech** [comment]
Could you try:

```bash
$ pm2 reload app.json --only app3
```

**Comment by e-wiese** [comment]
That command restarts only app3, but without considering my changes in app.json. (I changed the "script").

**Comment by vmarchaud** [comment]
You can't change `script` without restart the process file.

**Comment by ali1366** [comment]
@e-wiese  use --watch or  add "watch" : "true" to config file
