### ISSUE TITLE
PM2 start auto restarting

### ISSUE THREAD

**Issue by kishor-bhatt** [Unitech/pm2#2216]
Hi,

I have a admin server started from PM2
AdminServer    │ 63 │ fork │ 7242  │ online │ 1       │ 0s     │ 34.637 MB | disabled

Now I am using pm2 module to start and stop other servers,like - 
testServer         │ 29 │ fork │ 20223 │ online  │ 0       │ 24h    │ 19.473 MB   │ disabled

It works fine in local setup.But on AWS instance, on stopping and then starting again testServer, AdminServer is only getting restarted.
I tried with passing both **id** and **App name** of testServer which comes fine in logs but pm2 is automatically taking **id** and *\* name*\* of AdminServer (printed in logs).
So,this error comes continuously - 

WARNING: NODE_APP_INSTANCE value of '0' did not match any instance config file names.
AdminServer-63 WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
AdminServer-63 2016-06-08 18:11:29 - info: [Admin] AdminDB URL:mongodb://172.31.0.25:27017/AdminNowConferDB
AdminServer-63 In db connect state.db null and options {"replSet":{}}
AdminServer-63 Error: listen EADDRINUSE :::4310
AdminServer-63     at Object.exports._errnoException (util.js:860:11)
AdminServer-63     at exports._exceptionWithHostPort (util.js:883:20)
AdminServer-63     at Server._listen2 (net.js:1234:14)
AdminServer-63     at listen (net.js:1270:10)
AdminServer-63     at Server.listen (net.js:1366:5)
AdminServer-63     at ApiServer.listen (/home/nowconfer/NowConfer-1.0.1.0/node_modules/apiserver/lib/apiserver.js:80:15)
AdminServer-63     at Object.<anonymous> (/home/nowconfer/NowConfer-1.0.1.0/src/admin/server_admin.js:198:11)
AdminServer-63     at Module._compile (module.js:425:26)
AdminServer-63     at Object.Module._extensions..js (module.js:432:10)
AdminServer-63     at Module.load (module.js:356:32)
AdminServer-63 2016-06-08 18:11:29 - info: [Admin] Redis is ready

Please tell if something need to be changed,Stopping is working properly with *\* id and name both*\* as checked with 
netstat -anlp|grep port_no.

Thanks.

**Comment by vmarchaud** [comment]
`Error: listen EADDRINUSE :::4310` the problem come from the fact that the port you bind isn't available, not related to PM2
