### ISSUE TITLE
PM2 cannot start a Ruby Server Process ?

### ISSUE THREAD

**Issue by diogopublio** [Unitech/pm2#2217]
I have been using pm2 for many ruby scripts, they great! : )
However I can't find a way to use it with the "rails server" command.

The app starts only with "rails server -p 3002" running from the app directory.

Tried sending server as argument: 
pm2 start rails server  -- -p 3002
pm2 start "rails server"  -- -p 3002
pm2 start rails  -- server -p 3002

Tried direct path:
pm2 start bin/rails server  -- -p 3002
pm2 start /absolute_path/bin/rails server  -- -p 3002

Tried setting the script in a json file:
{
        "name": "server_processos",
        "scripts": {
                "start": "/home/rails/processos/bin rails server -p 3002"
        }
}

tried it with full path:
 "start": "rails server -p 3002"

None of them seems to work. Would you have any suggestion I could try ?

**Comment by smoothdvd** [comment]
You show start rails app like following:

pm2 start rails --interpreter bash --name "xxx" -- server

**Comment by 1Luc1** [comment]
as of now, this is how i did it with en `ecosystem.config.js` file:

```js
module.exports = {
    apps: [
   { 
        name: "projectXYZ",
        script: "rails server -p 3005 -e production",
        cwd: "/var/www/html/projectxyz/",
        watch: false,
    }
] }
```
