### ISSUE TITLE
pm2 showing cannot find module error.

### ISSUE THREAD

**Issue by monera23** [Unitech/pm2#2220]
I am using this module https://github.com/Pakhee/Cross-platform-AES-encryption/tree/master/Node
The module works fine on my local system I have checked it. But when I am using it on digitial ocean using pm2. The site shows 502 bad gateway nginx. And when I do pm2 logs, It shows an error that cannot find module 'cryptlib' 

Something like this - 
 Error: Cannot find module 'cryptlib'
     at Function.Module._resolveFilename (module.js:440:15)
     at Function.Module._load (module.js:388:25)
     at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/dexter/node-dextra/otp/otp_utils.js:5:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
     at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
     at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
     at Object.<anonymous> (/home/dexter/node-dextra/otp/otp.js:2:17)

Why is this error being shown ?

**Comment by davidbeijinho** [comment]
+1

**Comment by davidbeijinho** [comment]
root@XXXXX [~]# pm2 install pm2-server-monit
[PM2][Module] Installing module pm2-server-monit
[PM2][Module] Processing...
..[PM2][Module][ERROR] Unknown module

**Comment by Unitech** [comment]
npm version please

**Comment by monera23** [comment]
2.14.12

**Comment by monera23** [comment]
I also tried installing the node-gcm module and it gave the same error, Can't find module node-gcm. Need help on it.

**Comment by Unitech** [comment]
@davidbeijinho it's a different issue please tell me your npm version,

@monera23 could you please show me the command you use with pm2 (pm2 start app.js ....)

**Comment by monera23** [comment]
I just reload the process on each update - pm2 reload <name>

**Comment by davidbeijinho** [comment]
root@server2 [~]# pm2 install pm2-server-monit
[PM2][Module] Installing module pm2-server-monit
[PM2][Module] Processing...
.....[PM2][Module][ERROR] Unknown module
● Agent online - public key: r0lfsr13gmkf6sd - machine name: try.novudermskin.com - Web access: https://app.keymetrics.io/
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬────────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ memory │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
root@server2 [~]# npm - -v
2.15.5
root@server2 [~]# node -v
v4.4.5

**Comment by davidbeijinho** [comment]
@Unitech i just notice that after i start a app ex : https://github.com/keymetrics/app-playground.git , i can install the module

**Comment by psabharwal3** [comment]
getting same error, doesn't work even after i start an app -
Action install received
Executing: pm2 install pm2-server-monit

{error}
{
    "msg": "Unknown module"
}
{/error}

npm ver - 3.10.6
platform - windows 10

**Comment by vmarchaud** [comment]
You can git clone the module and do a `npm install && pm2 install .` inside.
