### ISSUE TITLE
PM2 and package.json watch

### ISSUE THREAD

**Issue by roccomuso** [Unitech/pm2#2222]
Hi,

What is the best way to let PM2 watch a package.json file and do a "npm install" when new dependencies were added?

**Comment by soyuka** [comment]
You'd have a service, started with `pm2 --watch` + `autorestart: false` that runs `npm install`.

IMO not using pm2 for this is easier, for example by using [chokidar-cli](https://www.npmjs.com/package/chokidar-cli) : `watch package.json -c npm install`

**Comment by vmarchaud** [comment]
See #2629 we group all issue into one.
