### ISSUE TITLE
pm2 install on Windows (fix suggestion)

### ISSUE THREAD

**Issue by cbernstein** [Unitech/pm2#2223]
As you know, module installation has been broken on Windows.  Here's a simple fix:

In file Modularizer.js, 
- Add a require for 'os' 
- At 'ugly hack', change the shelljs.exe line to:
```
  var no_errs = os.platform()==='win32'? ' 2> nul:' : ' 2> /dev/null';
  shelljs.exec('npm install ' + module_name + ' --prefix ' + cst.PM2_ROOT_PATH + no_errs, function(code) {
```

**Comment by cbernstein** [comment]
OK, looks like you already have this fixed in master as of yesterday but not yet in a release.  Any idea _when_ the next release will be?

**Comment by serganus** [comment]
![issue](https://cloud.githubusercontent.com/assets/12946435/16555164/d5863da0-4205-11e6-8500-63d79ae5fbf1.PNG)

I am facing the same issue, any fixes?

**Comment by Unitech** [comment]
@serganus pm2-monit module does not exists
 Try `$ pm2 install pm2-server-monit`

Else you can try PM2 v2:
```
$ npm install Unitech/pm2#development -g
$ pm2 update
$ pm2 install pm2-server-monit
```

**Comment by serganus** [comment]
@Unitech Tried but doesn't work

Check the output for ```pm2 install pm2-server-monit```:
![issue2](https://cloud.githubusercontent.com/assets/12946435/16555809/15376b6a-4209-11e6-8def-2854298c23b9.PNG)

After dev ver 2.0.0-rc3 :
![issue3](https://cloud.githubusercontent.com/assets/12946435/16556070/782348ec-420a-11e6-9f13-ba2497c26307.PNG)

**Comment by Unitech** [comment]
NPM version? Node.js version? PM2 version?

Have you tried with the PM2 on the development branch?

**Comment by serganus** [comment]
@Unitech Yes i tried the development branch.

![issue5](https://cloud.githubusercontent.com/assets/12946435/16556399/628a83d6-420c-11e6-9b2e-9f2c36a21907.PNG)

**Comment by Unitech** [comment]
What is you NPM version?

**Comment by serganus** [comment]
2.15.8

**Comment by Unitech** [comment]
Could you upgrade your npm?

```
$ npm install npm -g
```

**Comment by serganus** [comment]
Upgraded to 3.10.3 but same error

![issue](https://cloud.githubusercontent.com/assets/12946435/16556558/52768ae8-420d-11e6-8b5f-58bfac037627.PNG)

**Comment by vmarchaud** [comment]
I got this error resolved by launching the npm install into a shell in Modularizer.js#L111 :

```javascript
install_instance = spawn('npm', [
      'install', module_name, '--prefix', cst.PM2_ROOT_PATH, '--loglevel=error'
    ],{
      stdio : 'inherit',
      async : true,
	  shell: true
    });
```

Maybe a windows specific behavior ?

**Comment by serganus** [comment]
@vmarchaud  What do you mean by launching the npm install into a shell in Modularizer.js#L111?

**Comment by Unitech** [comment]
Windows fix from @vmarchaud has been merge to development branch,

```
$ npm install Unitech/pm2#development -g
$ pm2 update
$ pm2 install pm2-server-monit
```

Waiting for feedbacks

**Comment by serganus** [comment]
<img width="507" alt="screen shot 2016-07-06 at 7 46 03 pm" src="https://cloud.githubusercontent.com/assets/12946435/16616838/795ec778-43b2-11e6-95b7-2ad129bc783e.png">
<img width="513" alt="screen shot 2016-07-06 at 7 46 24 pm" src="https://cloud.githubusercontent.com/assets/12946435/16616839/7963d0ce-43b2-11e6-84a3-4b0a2e245054.png">
<img width="509" alt="screen shot 2016-07-06 at 7 46 39 pm" src="https://cloud.githubusercontent.com/assets/12946435/16616840/7969e57c-43b2-11e6-90d6-fdbb457bf29b.png">

I tried to follow the steps and here is the output as screenshots. still not fixed :-(

**Comment by vmarchaud** [comment]
Can you give us your npm/node/pm2/windows exact version ?
Its seems that you dont have the lastest dev version because we dont have any git dependency since this morning and your first error seems to say that we do.

**Comment by serganus** [comment]
- pm2 version is 2.0.0-rc3
- npm version is 3.1.0
- node version is 4.4.7

I did the following but still same error.

```
pm2 kill
npm remove pm2 -g
npm cache clean
npm install Unitech/pm2#development -g
pm2 update
pm2 install pm2-server-monit
```

**Comment by vmarchaud** [comment]
Working on node v6.X.X. If you want you can update to use it correctly while i'm debuging with node v4.X.X

**Comment by vmarchaud** [comment]
@serganus Merged on development branch, tested and working on my workstation, its good for you ?
