### ISSUE TITLE
Intercept uncaught exceptions in cluster mode

### ISSUE THREAD

**Issue by acarstoiu** [Unitech/pm2#2226]
I've noticed in #1488 and #721 that you seem to allow PM2 users to intercept uncaught exceptions only in forked mode. What about the cluster mode? Setting an `uncaughtException` listener in this case has **no effect** and I do not see a reason for that.

If it matters, my particular interest is to enrich the standard error output (and then exit, of course).

**Comment by YanivSa** [comment]
+ 1

**Comment by acarstoiu** [comment]
For interested people, the fix is to use `EventEmitter.prependListener()` when placing your own `uncaughtException` listener.

**Comment by YanivSa** [comment]
@acarstoiu , listener on what? `process.on` doesn't catch.

**Comment by acarstoiu** [comment]
`process.prependListener('uncaughtException', function(error) {...});`

**Comment by YanivSa** [comment]
FYI, my issue was running nodeJS with `--abort-on-uncaught-exception` :)

**Comment by vmarchaud** [comment]
Because pmx remove all of them [here](https://github.com/keymetrics/pmx/blob/9e76bd731855f20c8068ccfeb50bd958b0ec2762/lib/notify.js#L76) to avoid problem with runtime dependency since pmx absolutly need to send it to pm2.

**Comment by cheapsteak** [comment]
`process.prependListener` does not seem to be working for me
Are there any other workarounds?
