### ISSUE TITLE
pm2 does not response to duplicated arguments (patchCommanderArg is not correct)

### ISSUE THREAD

**Issue by oxyflour** [Unitech/pm2#2230]
With the latest 1.1.3, the following command is OK and pm2 will start ssh normally
```pm2 start ssh -- localhost -v```
But this one is not (pm2 does nothing)
```pm2 start ssh -- localhost -v -v```
It seems that [patchCommanderArg](https://github.com/Unitech/pm2/blob/master/bin/pm2#L214 ) will try to remove arguments after '--' from the action commands, but it does not work as expected when there are duplicated arguments : (

**Comment by nfantone** [comment]
The argument parsing in **pm2** is completely broken ATM.

https://github.com/Unitech/pm2/issues/2198

I'm considering sending a PR to fix some of these, but I'm afraid it'll just get queued along all 20+ already present.

**Comment by Unitech** [comment]
inspecting

**Comment by Unitech** [comment]
closing in favor of #2272
