### ISSUE TITLE
deploy option 'needs_tty' fails with "Pseudo-terminal will not be allocated because stdin is not a terminal."

### ISSUE THREAD

**Issue by mozeryansky** [Unitech/pm2#2231]
What I'm attempting to do is run su in a post-deploy. To do this, I know I need a tty which is achieved with -t. I found in the source of deploy that if I include needs_tty then a -t will be used on the ssh commands for deploy. However, when I do this, all the ssh commands output "Pseudo-terminal will not be allocated because stdin is not a terminal."

I believe this is because the deploy command is passed the config string by piping in the string, instead of passing it as an argument.
### Environment info

Operating System: OS X 10.11.5
Pm2 version: 1.1.3
Node version: 5.3.0
Shell: bash
### Steps to reproduce
1. In the ecosystem.json file include in the deploy section: "needs_tty": "yes". I don't think this was documented but I found in the source that it will add -t when doing ssh commands, which I need.
2. Run deploy: pm2 deploy production
### Logs

The pm2 log doesn't apply here, so this is from '/tmp/pm2-deploy.log'. From the logs, it looks like everything is operating correctly.

ssh -t username@website.com "cd /home/bob/source && git fetch --all"
ssh -t username@website.com "cd /home/bob/source && git reset --hard origin/master"
ssh -t username@website.com "ln -sfn /home/bob/source /home/bob/current"
ssh -t username@website.com "cd /home/bob/source &&       echo `git rev-parse --short HEAD`       >> /home/bob/.deploys"
ssh -t username@website.com "cd /home/bob/current;       SHARED="/home/bob/shared"       su bob pm2 startOrRestart ecosystem.json --env production 2>&1 | tee -a /tmp/pm2-deploy.log;       exit ${PIPESTATUS[0]}"

**Comment by mozeryansky** [comment]
If I change deploy.js to send the hostJSON as the first param, then in the deploy bash script replace 'read conf' with 'conf=$1; shift'. This will not open ssh with stdin and the commands will work.

**Comment by soyuka** [comment]
ping @Unitech I'm a bit lost on this one :|

**Comment by vmarchaud** [comment]
Actually you can't use TTY with pm2 deploy since the binary is spawn by a shellscript, so you can't allocate TTY.

**Comment by mozeryansky** [comment]
@vmarchaud I was able to get it to work with the fix I mentioned.

I do agree that I shouldn't be using `su` and I'm doing something else to accomplish what I wanted, but the current mode that pre/post deploy runs in is not what I would expect.

**Comment by vmarchaud** [comment]
I'm writing a new version of the deploying system ([here](https://github.com/vmarchaud/deployerjs)) and i'll be happy if you provide me what you exactly expect from the pre/post hooks ?

**Comment by mozeryansky** [comment]
Thanks for following up. I would expect that whatever I put in the string of a hook can be executed as if I put that same string in the shell. I haven't modified my deployment, but when I was writing it, I was able to do everything except what I mentioned in my original comment. I'm very glad you're adding more hooks, it was confusing what ran where before.

**Comment by vmarchaud** [comment]
@mozeryansky Actually i'm not just adding hooks, i'm rewriting it from scratch with a pure javascript solution without relying on a shellscript or spawning the ssh binary. I'm interested for feedback on it btw

**Comment by mozeryansky** [comment]
@vmarchaud I do see all the additional features, the limited number of hooks was a pain point in the current deployment. Personally, and on any project, if I'm using a tool (pm2) and that tool provides other related tools (pm2-deploy) I will almost always use that tool without looking for another (even if others have a million more features).

**Comment by vmarchaud** [comment]
@mozeryansky Yeah totally (same for me), but deployerjs will replace pm2-deploy as some point, thats the aim of deployerjs since the start.

**Comment by mozeryansky** [comment]
Ok great!
