### ISSUE TITLE
my app logs print twice

### ISSUE THREAD

**Issue by shuperry** [Unitech/pm2#2233]
when I use `node` or `nodemon`, my app logs print normally, when I turned to pm2, I saw all my app logs print twice, these are my package scripts field:

```
"prod": "cross-env DEBUG=tip NODE_ENV=production pm2 start bin/index.js --name kingnoshop-api",
"prod1": "cross-env DEBUG=tip NODE_ENV=production node bin/index.js --name kingnoshop-api | bunyan"
```

when I run `npm run prod1`, the logs print normally, then I run `npm run prod`, and run `pm2 logs --raw --name kingnoshop-api| bunyan` see my app logs, all logs are print twice, please explain.

**Comment by soyuka** [comment]
How many instances of the script are running ? Are you using cluster mode ? pm2 version ? Please provide more data.

**Comment by shuperry** [comment]
only one instance, I run `pm2 list` command, only show one app is running, not use cluster yet.

**Comment by shuperry** [comment]
@soyuka I know the reason now, I start an instance, then I modified sth, and after that I delete the instance and start another, the log is increasing not clean and create a new log file, so I run `pm2 logs --raw --name kingnoshop-api| bunyan`, this command shows the total logs not only new instance, I have been tested.

**Comment by shuperry** [comment]
@soyuka Can we start a new instance with new log file?

**Comment by soyuka** [comment]
You can restart instead of deleting/restarting. you can use `flush` to flush logs.

**Comment by shuperry** [comment]
@soyuka I tried, `restart` command can not flush logs, `flush` command only worked when app is running, can we join an option to start app with new log files?

**Comment by vmarchaud** [comment]
Could you try with PM2 v2 : `npm install -g pm2 && pm2 update` ? I close but re-open if you still got the problem.
