### ISSUE TITLE
pm2 caused server crash

### ISSUE THREAD

**Issue by mozeryansky** [Unitech/pm2#2235]
I was load testing my server with siege and then my system crashed. I don't think the crash log gives much. Is there anything else I can provide or test?
Here's the crash log:

> ProblemType: Crash
> Architecture: amd64
> Date: Mon Jun 20 22:39:13 2016
> DistroRelease: Ubuntu 14.04
> ExecutablePath: /usr/bin/nodejs
> ExecutableTimestamp: 1464913344
> ProcCmdline: node /usr/lib/node_modules/pm2/lib/ProcessContainerFork.js
> ProcCwd: /home/me/.pm2/node_modules/pm2-server-monit
> ProcEnviron:
>  XDG_RUNTIME_DIR=<set>
>  LANG=en_US.UTF-8
>  PATH=(custom, no user)
>  SHELL=/bin/bash
> ProcMaps:
>  00400000-01996000 r-xp 00000000 fd:01 917779                             /usr/bin/nodejs
>  01b95000-01b96000 r--p 01595000 fd:01 917779                             /usr/bin/nodejs
>  01b96000-01baf000 rw-p 01596000 fd:01 917779                             /usr/bin/nodejs
>  01baf000-01bc2000 rw-p 00000000 00:00 0 
>  02f62000-0310a000 rw-p 00000000 00:00 0                                  [heap]
>  e9f7287f000-e9f728bf000 rw-p 00000000 00:00 0 
>  e9f728bf000-e9f72c7f000 ---p 00000000 00:00 0 
>  10769e2b2000-10769e2c0000 ---p 00000000 00:00 0 
>  10769e2c0000-10769e2e0000 rw-p 00000000 00:00 0 
>  10769e2e0000-10769e312000 ---p 00000000 00:00 0 
>  10d019300000-10d019400000 rw-p 00000000 00:00 0 
>  1749c922b000-1749c9300000 ---p 00000000 00:00 0 
>  1749c9300000-1749c9305000 rw-p 00000000 00:00 0 
>  1749c9305000-1749c9306000 ---p 00000000 00:00 0 
>  1749c9306000-1749c9307000 rwxp 00000000 00:00 0 
>  1749c9307000-1749c9400000 ---p 00000000 00:00 0 
>  1749c9400000-1749c9405000 rw-p 00000000 00:00 0 
>  1749c9405000-1749c9406000 ---p 00000000 00:00 0 
>  1749c9406000-1749c9407000 rwxp 00000000 00:00 0 
>  1749c9407000-1749c9500000 ---p 00000000 00:00 0 
>  1749c9500000-1749c9505000 rw-p 00000000 00:00 0 
>  1749c9505000-1749c9506000 ---p 00000000 00:00 0 
>  1749c9506000-1749c9507000 rwxp 00000000 00:00 0 
>  1749c9507000-1749c9600000 ---p 00000000 00:00 0 
>  1749c9600000-1749c9605000 rw-p 00000000 00:00 0 
>  1749c9605000-1749c9606000 ---p 00000000 00:00 0 
>  1749c9606000-1749c9647000 rwxp 00000000 00:00 0 
>  1749c9647000-1749c9700000 ---p 00000000 00:00 0 
>  1749c9700000-1749c9705000 rw-p 00000000 00:00 0 
>  1749c9705000-1749c9706000 ---p 00000000 00:00 0 
>  1749c9706000-1749c97ff000 rwxp 00000000 00:00 0 
>  1749c97ff000-1749e922b000 ---p 00000000 00:00 0 
>  1aefcaf00000-1aefcafec000 rw-p 00000000 00:00 0 
>  24f5f6400000-24f5f6500000 rw-p 00000000 00:00 0 
>  2a5b2c000000-2a5b2c200000 rw-p 00000000 00:00 0 
>  2a5b2c200000-2a5b2d000000 ---p 00000000 00:00 0 
>  2a5b2d000000-2a5b2d200000 rw-p 00000000 00:00 0 
>  2a5b2d200000-2a5b2e000000 ---p 00000000 00:00 0 
>  2ba040700000-2ba040713000 rw-p 00000000 00:00 0 
>  37875a000000-37875a100000 rw-p 00000000 00:00 0 
>  7fbc18000000-7fbc18023000 rw-p 00000000 00:00 0 
>  7fbc18023000-7fbc1c000000 ---p 00000000 00:00 0 
>  7fbc20000000-7fbc20033000 rw-p 00000000 00:00 0 
>  7fbc20033000-7fbc24000000 ---p 00000000 00:00 0 
>  7fbc24000000-7fbc24023000 rw-p 00000000 00:00 0 
>  7fbc24023000-7fbc28000000 ---p 00000000 00:00 0 
>  7fbc28000000-7fbc28058000 rw-p 00000000 00:00 0 
>  7fbc28058000-7fbc2c000000 ---p 00000000 00:00 0 
>  7fbc2ef43000-7fbc2ef44000 ---p 00000000 00:00 0 
>  7fbc2ef44000-7fbc2f744000 rw-p 00000000 00:00 0                          [stack:7511]
>  7fbc2f744000-7fbc2f745000 ---p 00000000 00:00 0 
>  7fbc2f745000-7fbc2ff45000 rw-p 00000000 00:00 0                          [stack:7510]
>  7fbc2ff45000-7fbc2ff46000 ---p 00000000 00:00 0 
>  7fbc2ff46000-7fbc30746000 rw-p 00000000 00:00 0                          [stack:7509]
>  7fbc30746000-7fbc30747000 ---p 00000000 00:00 0 
>  7fbc30747000-7fbc30f47000 rw-p 00000000 00:00 0                          [stack:7508]
>  7fbc30f47000-7fbc31101000 r-xp 00000000 fd:01 403248                     /lib/x86_64-linux-gnu/libc-2.19.so
>  7fbc31101000-7fbc31301000 ---p 001ba000 fd:01 403248                     /lib/x86_64-linux-gnu/libc-2.19.so
>  7fbc31301000-7fbc31305000 r--p 001ba000 fd:01 403248                     /lib/x86_64-linux-gnu/libc-2.19.so
>  7fbc31305000-7fbc31307000 rw-p 001be000 fd:01 403248                     /lib/x86_64-linux-gnu/libc-2.19.so
>  7fbc31307000-7fbc3130c000 rw-p 00000000 00:00 0 
>  7fbc3130c000-7fbc31325000 r-xp 00000000 fd:01 403240                     /lib/x86_64-linux-gnu/libpthread-2.19.so
>  7fbc31325000-7fbc31524000 ---p 00019000 fd:01 403240                     /lib/x86_64-linux-gnu/libpthread-2.19.so
>  7fbc31524000-7fbc31525000 r--p 00018000 fd:01 403240                     /lib/x86_64-linux-gnu/libpthread-2.19.so
>  7fbc31525000-7fbc31526000 rw-p 00019000 fd:01 403240                     /lib/x86_64-linux-gnu/libpthread-2.19.so
>  7fbc31526000-7fbc3152a000 rw-p 00000000 00:00 0 
>  7fbc3152a000-7fbc31540000 r-xp 00000000 fd:01 393221                     /lib/x86_64-linux-gnu/libgcc_s.so.1
>  7fbc31540000-7fbc3173f000 ---p 00016000 fd:01 393221                     /lib/x86_64-linux-gnu/libgcc_s.so.1
>  7fbc3173f000-7fbc31740000 rw-p 00015000 fd:01 393221                     /lib/x86_64-linux-gnu/libgcc_s.so.1
>  7fbc31740000-7fbc31845000 r-xp 00000000 fd:01 403233                     /lib/x86_64-linux-gnu/libm-2.19.so
>  7fbc31845000-7fbc31a44000 ---p 00105000 fd:01 403233                     /lib/x86_64-linux-gnu/libm-2.19.so
>  7fbc31a44000-7fbc31a45000 r--p 00104000 fd:01 403233                     /lib/x86_64-linux-gnu/libm-2.19.so
>  7fbc31a45000-7fbc31a46000 rw-p 00105000 fd:01 403233                     /lib/x86_64-linux-gnu/libm-2.19.so
>  7fbc31a46000-7fbc31b2c000 r-xp 00000000 fd:01 917531                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19
>  7fbc31b2c000-7fbc31d2b000 ---p 000e6000 fd:01 917531                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19
>  7fbc31d2b000-7fbc31d33000 r--p 000e5000 fd:01 917531                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19
>  7fbc31d33000-7fbc31d35000 rw-p 000ed000 fd:01 917531                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19
>  7fbc31d35000-7fbc31d4a000 rw-p 00000000 00:00 0 
>  7fbc31d4a000-7fbc31d51000 r-xp 00000000 fd:01 403247                     /lib/x86_64-linux-gnu/librt-2.19.so
>  7fbc31d51000-7fbc31f50000 ---p 00007000 fd:01 403247                     /lib/x86_64-linux-gnu/librt-2.19.so
>  7fbc31f50000-7fbc31f51000 r--p 00006000 fd:01 403247                     /lib/x86_64-linux-gnu/librt-2.19.so
>  7fbc31f51000-7fbc31f52000 rw-p 00007000 fd:01 403247                     /lib/x86_64-linux-gnu/librt-2.19.so
>  7fbc31f52000-7fbc31f55000 r-xp 00000000 fd:01 403235                     /lib/x86_64-linux-gnu/libdl-2.19.so
>  7fbc31f55000-7fbc32154000 ---p 00003000 fd:01 403235                     /lib/x86_64-linux-gnu/libdl-2.19.so
>  7fbc32154000-7fbc32155000 r--p 00002000 fd:01 403235                     /lib/x86_64-linux-gnu/libdl-2.19.so
>  7fbc32155000-7fbc32156000 rw-p 00003000 fd:01 403235                     /lib/x86_64-linux-gnu/libdl-2.19.so
>  7fbc32156000-7fbc32179000 r-xp 00000000 fd:01 403241                     /lib/x86_64-linux-gnu/ld-2.19.so
>  7fbc32367000-7fbc3236e000 rw-p 00000000 00:00 0 
>  7fbc32372000-7fbc32373000 ---p 00000000 00:00 0 
>  7fbc32373000-7fbc32378000 rw-p 00000000 00:00 0                          [stack:7507]
>  7fbc32378000-7fbc32379000 r--p 00022000 fd:01 403241                     /lib/x86_64-linux-gnu/ld-2.19.so
>  7fbc32379000-7fbc3237a000 rw-p 00023000 fd:01 403241                     /lib/x86_64-linux-gnu/ld-2.19.so
>  7fbc3237a000-7fbc3237b000 rw-p 00000000 00:00 0 
>  7fffeaf3c000-7fffeaf5d000 rw-p 00000000 00:00 0                          [stack]
>  7fffeaf66000-7fffeaf68000 r-xp 00000000 00:00 0                          [vdso]
>  ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
>

**Comment by mozeryansky** [comment]
Also I found this in pm2-server-monit's error log:

> Error: spawn ENOMEM
>     at exports._errnoException (util.js:1007:11)
>     at ChildProcess.spawn (internal/child_process.js:302:11)
>     at exports.spawn (child_process.js:383:9)
>     at Object.execute (/home/jumpsell/.pm2/node_modules/pm2-server-monit/lib/process.js:33:17)
>     at Netstat.module.exports.Netstat.start (/home/jumpsell/.pm2/node_modules/pm2-server-monit/lib/network.js:60:27)
>     at Timeout._onTimeout (/home/jumpsell/.pm2/node_modules/pm2-server-monit/lib/network.js:67:21)
>     at tryOnTimeout (timers.js:224:11)
>     at Timer.listOnTimeout (timers.js:198:5)

**Comment by vmarchaud** [comment]
`ENOMEM` means that your server run out of memory, pm2 can't recover itself when running out of memory for obvious reason. But new pm2 version have massive memory improvements : `npm install -g pm2 && pm2 update`.
