### ISSUE TITLE
running 4 fork instances of pm2 causing a function to be executed four times.

### ISSUE THREAD

**Issue by gurpreetRosie** [Unitech/pm2#2238]
Hi There
I have the following code
var PM2 = function () {
    pm2.connect(function () {
        pm2.start({
            script: 'app.js',
            instances: 4,
            max_memory_restart: '3G',
            exec_mode: 'fork',
            error_file: "/var/log/rfm6001.err",
            out_file: "/var/log/rfm6001.log",
        }, function (err, apps) {
               
            pm2.disconnect(function () {
                //process.exit(0);
            });

        });
    });
}();

I want to execute a function once only. But that function is getting executed four times. Is there any way I can stop this? Node version is v0.10.25 and pm2 version is 1.0.1 and ubuntu version is Ubuntu 14.04

Regards
Gurpreet

**Comment by Unitech** [comment]
API fixed in V2:

package.json:
```
[...]
"dependencies" : {
  "pm2" : "Unitech/pm2#development"
},
[...]
```

**Comment by gurpreetRosie** [comment]
Hi There,
I would like some more information on how to use this API if I want to execute a function only once. Any help will be appreciated.

Regrads

**Comment by soyuka** [comment]
@gurpreetRosie  What do you mean by "only once"?

**Comment by gurpreetRosie** [comment]
Hi, 

Thanks for reply. Now we have four instances of app running. And I want to execute a function every 5 seconds. But because of four instances running, that function is getting executed four times every 5 seconds. I want to execute that function only once every 5 seconds. Any help will be appreciated.

Regards

**Comment by soyuka** [comment]
You need to run the app with only one instance, or check if `cluster.isMaster` to launch your function only from master.
