### ISSUE TITLE
some processes in pm2 stopped because of lack of pid

### ISSUE THREAD

**Issue by kylezengTR** [Unitech/pm2#2242]
Hi, some of my services in PM2 stopped, link this:
![image](https://cloud.githubusercontent.com/assets/9773049/16312226/bd5d6324-3941-11e6-9171-8cce8f5f6522.png)
![image](https://cloud.githubusercontent.com/assets/9773049/16312252/dd7d0ea2-3941-11e6-9a1a-f95a0ff9d4fc.png)
And I have checked the ~/.pm2/pids  folder, there is no such pid file related to that process.
And Pm2 logs shows following information:
![image](https://cloud.githubusercontent.com/assets/9773049/16312314/1a71acf0-3942-11e6-8d1d-4ddabe7e01dd.png)

I know that  running 

> pm2 update

will solve this problem, I just want to know is there any possible reason that causes this error?

Thank you very much!

**Comment by soyuka** [comment]
Your process was out of memory and stopped. It's normal to have no pid file when the process is stopped.

**Comment by kylezengTR** [comment]
@soyuka 
You are correct,PM2 process cost 15GB of memory:
![pasted image at 2016_06_24 05_19 pm](https://cloud.githubusercontent.com/assets/9773049/16351048/c4c2d10e-3a30-11e6-8280-18010ca7f804.png)

Should I reinstall pm2 or just run "pm2 update" or "pm2 reboot"?

BTW, is there any explanation regarding  to this unusual situation?

thank you very much!

**Comment by vmarchaud** [comment]
Try to upgrade to the latest pm2 version : `npm install -g Unitech/pm2#development`
