### ISSUE TITLE
sort process-listing

### ISSUE THREAD

**Issue by e-wiese** [Unitech/pm2#2243]
Hi, just a little something:
`pm2 list` sorts by **id**. That's no problem if you have only a few apps configured, but if you have some 30 apps running you don't get a clear process listing without a proper sorting. And the process listing is my most used command.
I would propose to sort by default by "App name" or to give the list-command a sort-option. 

Thanks, Erwin

**Comment by Unitech** [comment]
available in development branch
thanks for the suggestion

**Comment by iCodeBIT** [comment]
is there a way to switch back to sorting by id?
