### ISSUE TITLE
How to work with commander.js

### ISSUE THREAD

**Issue by WindWen** [Unitech/pm2#2250]
```
node --harmony ./bin/www -e product
```
i can use
```
pm2 start ./bin/www --node-args="--harmony"
```
but how to use "-e" ? this arg achieved through the commander.js

**Comment by Unitech** [comment]
Use -- <argument list> to pass arguments to your app:

`pm2 start ./bin/www --node-args="--harmony" -- -e product`

**Comment by WindWen** [comment]
@Unitech Thank you so much~
