### ISSUE TITLE
mysql requests

### ISSUE THREAD

**Issue by ciumexan** [Unitech/pm2#2253]
If reporting a bug, please use the following template.
#### Expected behaviour

i have hapijs service with mysql backend
pm2 is --watch 

i was expecting when i make a change over database to see the changes immediately
#### Actual behaviour

i need to make a modif in js file in order for changes to take effect.
#### Steps to reproduce

...
#### Software versions used

```
OS         : 3.11.0-15-generic #25~precise1-Ubuntu SMP Thu Jan 30 17:39:31 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux 
node.js    : 5.8.0
PM2        : 1.1.3
```
#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

no log related to this behaviour... 

cf CONTRIBUTING.md for more informations

**Comment by vmarchaud** [comment]
`watch` listen for file system change, not database.
