### ISSUE TITLE
Question/Suggestion: Use setgroups to allow the process to run with multiple groups

### ISSUE THREAD

**Issue by carlosduclos** [Unitech/pm2#2254]
Currently pm2 allows only setting one group when running a command. This is ok, but there are plenty situations when one needs to be able to set secondary groups when running the process.

A common example is to have some files that are only accessible for a given group, but need to be part of a different group to be able to interact with a service or use a resource.

Node (child_process that is), already supports this by calling the POSIX setgroups(2) system call.

Changing PM2 to support this should not be a major issue, but I'd like to know if this has been considered before or if there is a reason for why this should not be supported.

**Comment by soyuka** [comment]
It's historical, due to lots of misuse, or related issues we dropped the support of `setuid` and `setgid`. Nevertheless, we never looked into the `process.setgroups(groups)` method and I think it might be worth it. 
However, this will force you to run pm2 as root, which is not recommended. Running pm2 as root isn't that bad, but if you can avoid it you should.

@Unitech thoughts on this?

**Comment by carlosduclos** [comment]
You don't necessarily need to run pm2 as root, you just need to add the proper process capability (CAP_SETGID). 

It should be safe to assume that people wanting this kind of advanced functionality will know how to set up the process capabilities, IMHO.

**Comment by soyuka** [comment]
> It should be safe to assume that people wanting this kind of advanced functionality will know how to set up the process capabilities, IMHO.

If only this was true ;).

> You don't necessarily need to run pm2 as root, you just need to add the proper process capability (CAP_SETGID).

Indeed. I'll think about an approach for this, it would be a nice feature.

**Comment by carlosduclos** [comment]
I've been thinking about the implementation of this. It is more or less straight forward when in ForkMode, it gets more complicated in ClusterMode.

In ForkMode it should be as easy as passing the groups in the "env" variable and then adding it to the options given to child_process.spawn.

In ClusterMode it is not as straight forward, or at least I'm not confident that I understand ClusterMode good enough to attempt the implementation. One question that come to mind is should both master and workers be spawn with groups?

**Comment by soyuka** [comment]
We should be able to call `process.setGroups` in the [cluster process container](https://github.com/Unitech/pm2/blob/master/lib/ProcessContainer.js#L215) and in the [fork process container](https://github.com/Unitech/pm2/blob/master/lib/ProcessContainerFork.js).

> One question that come to mind is should both master and workers be spawn with groups?

Good question, I think it should be enough on master, as workers are only sub-processes, so should behave with the same rules as set in master. To be tested though.

**Comment by carlosduclos** [comment]
Probably right, but on the other hand it is mostly the workers who need the extra groups since it is them who do _real_work_ and need the extra permissions.

**Comment by carlosduclos** [comment]
I've tried to follow what you say regarding calling process.setgroups, but that would require that we use child_process.fork and then call exec ourselves. Currently we are using child_process.spawn which will internally call exec (thus not allowing us to change the secondary groups).
Could you elaborate a little bit more on what you mentioned?

**Comment by soyuka** [comment]
`spawn` also has the `gid <Number> Sets the group identity of the process. (See setgid(2).)` option.

But IMO it'd be better to run `process.setGroups` directly inside the process, which is what `ProcessContainer` is for. Basically you just call `process.setGroups` [here](https://github.com/Unitech/pm2/blob/master/lib/ProcessContainerFork.js#L43) and it'll work as expected.
