### ISSUE TITLE
IBM AIX7.1 OS

### ISSUE THREAD

**Issue by cchgood12** [Unitech/pm2#2258]
In IBM AIX 7.1 operating system daemon pm2 occupies more than 20% CPU utilization . Is there a way to lower the CPU utilization ?

**Comment by Unitech** [comment]
Pm2 v2 has much lower CPU usage, to install:

$ npm install Unitech/pm2#development -g
$ pm2 update

Keep me updated about changes

On Saturday, July 2, 2016, cchgood12 <notifications@github.com> wrote:

> In IBM AIX 7.1 operating system daemon pm2 occupies more than 20% CPU
> utilization . Is there a way to lower the CPU utilization ?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Unitech/pm2/issues/2258>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAuP88HlzBgK8rqVwFEvnnuHzT6PSZRFks5qRnYPgaJpZM4JDr22>
> .
>


-- 
Alexandre Strzelewicz
(+33) 7.83.88.11.43

**Comment by Unitech** [comment]
@cchgood12 any updates?
