### ISSUE TITLE
Is there a way to delay “online” event from cluster processes under pm2?

### ISSUE THREAD

**Issue by Rogach** [Unitech/pm2#2260]
My nodejs app takes a while before it is able to accept requests (resources are compiled, etc). When I run it under pm2 in cluster mode and trigger reload, pm2 starts reloading instances one-by-one - but it does not wait until application is actually able to accept requests, and goes on to restart other instances - which results in all instances being down for some time.

Is there a way to configure events to signal that this instance has finished startup and pm2 can go on to restart next one?

I prepared a basic test case:

```js
var http = require("http");

setTimeout(() => {
  var server = http.createServer((req, res) => {
    res.statusCode = 200;
    res.setHeader("Content-Type", "text/plain");
    res.end("hello\n");
  });

  server.listen(7000, "127.0.0.1", () => {
    console.log("server ready");
  });
}, 10000);
```

Start with `pm2 start app -i 2`, then try reloading with `pm2 reload app`. On my machine, there is about 4s window when app does not respond to requests at all:

```
curl: (7) Failed to connect to localhost port 7000: Connection refused
```

**Comment by Unitech** [comment]
looks like the event 'listening' is not triggered on successful port binding

**Comment by Rogach** [comment]
I suspect it is triggered, but after GRACEFUL_LISTEN_TIMEOUT is over (it is only 3 seconds). Is there a way to configure it externally?

**Comment by Rogach** [comment]
Awesome, that works! Will this setting survive restarts (after `pm2 save`)?

**Comment by Unitech** [comment]
echo "PM2_GRACEFUL_TIMEOUT=15000" >> /etc/environment

**Comment by Rogach** [comment]
Ok. Should I close the issue? (it is marked as "feature")

**Comment by Unitech** [comment]
#2261 for the new flag feature, closing
