### ISSUE TITLE
Server crashed, got satan.js errors

### ISSUE THREAD

**Issue by jsantana90** [Unitech/pm2#2262]
Hi there

I am trying to figure out what happen to my ubuntu server.

Now I'm not really sure but I can assume pm2 crashed.

But when I tried to input commands like cd + write + tab to autocomplete in the terminal, these errors popped up:

![screenshot from 2016-07-01 20 43 33](https://cloud.githubusercontent.com/assets/9933887/16570873/3f1643a2-421d-11e6-9f93-65c7bddd8512.png)

also, it happen when I tried using any commands of `pm2`, I had to restart the server completely in order for it to come back to normal.

Could someone guide or explain me what really happen here?

**Comment by vmarchaud** [comment]
Can you please give us your node/npm/pm2 version ?
