### ISSUE TITLE
Can't install PM2 - failed NPM dependency

### ISSUE THREAD

**Issue by jasonmacdonald** [Unitech/pm2#2265]
I'm getting the following NPM error when trying to install PM2.

`Error: Execution of '/bin/npm install --global pm2' returned 1: npm ERR! fetch failed https://registry.npmjs.org/escape-regexp/-/escape-regexp-0.0.1.tgz`

It seems the dependency escape-regexp is not loading. trying to load https://registry.npmjs.org/escape-regexp/-/escape-regexp-0.0.1.tgz gives **502 Bad Gateway**

**Comment by vmarchaud** [comment]
@jasonmacdonald We got our CI builds failing with the same issue, you should check with NPM or your CI service if you have one for this issue.

**Comment by jasonmacdonald** [comment]
Yeah I just saw NPM is having a major outage. http://status.npmjs.org/ I'll close this as it seems it has nothing to do with PM2.
