### ISSUE TITLE
Restart and tail logs (feature request)

### ISSUE THREAD

**Issue by johntron** [Unitech/pm2#2266]
It would be nice if `pm2 restart {process}` had a flag to follow logs (i.e. `pm2 logs {process}`) immediately after restarting. It's easy enough to run the second command, but in my experience this is a very common sequence of commands, so it would be nice to have something like `pm2 restart {process} --logs`.

**Comment by vmarchaud** [comment]
see https://github.com/Unitech/pm2/issues/2304

**Comment by johntron** [comment]
👍

**Comment by vmarchaud** [comment]
Released in pm2 `2.4.1`
