### ISSUE TITLE
How do you NOT watch in production?

### ISSUE THREAD

**Issue by astanciu** [Unitech/pm2#2268]
I'm using an ecosystem file and in my app declaration I have `watch` defined. This works fine when I run it in dev mode. When I deploy to a production environment which automatically starts with pm2, I'd like it to not watch. Can't find any docs on how to achieve this.

**Comment by mpartipilo** [comment]
I'm having this issue in pm2 2.0.2. Watchinig is always enabled regardless of the value of `watch` in the process.json.

**Comment by mpartipilo** [comment]
I did pm2 stop --watch ID and then pm2 start and the watching flag was disabled.

**Comment by Unitech** [comment]
Fix is available:

```bash
$ npm install pm2@next -g
$ pm2 update
```

**Comment by Unitech** [comment]
closing in favor of #2471
