### ISSUE TITLE
gracefullExit doesn't wait for processes to unlink in Keymetrics

### ISSUE THREAD

**Issue by ATGardner** [Unitech/pm2#2271]
If reporting a bug, please use the following template.
#### Expected behaviour

After stopping pm2, see empty host in Keymetrics.
Preferably, I'd rather see the processes visible, only "stopped", but that's a different story.
...
#### Actual behaviour

Processes are still visible and apear "running' in Keymetrics, even after the entire node process is stopped.
...
#### Steps to reproduce
- Launch pm2 using js (pm2.connect(no-deamon), pm2.start, pm2.install(pm2-logrotate), pm2.interact, pm2.launchBus)
- See the process and module in Keymetrics dashboard
- Stop the node process using ctrl+c
- See the console logs of "Deleting process...", "Stopping...", "App [...] with id [...] and pid [...], exited with code [0] via signal [SIGINT]", etc.
- See the "[PM2] Exited peacefull"
- Both the process and the module still appear Keymetrics. Sometimes one of them is in the "stopping" state, while the other is still in the "running' state. It appears to be some sort of a race, until the final exit is being called.
  ...

I added a 1000ms timeout before the final call to "process.exit(cst.SUCCESS_EXIT);" at the end of gracefullExit, and I got the expected result. Maybe there is a better way to perform this?
#### Software versions used

```
OS         : Windows 10 x64
node.js    : 6.3 x64
PM2        : 1.2 (commit 8e1906febbe8b038d56671918f688ac991aa418f)
```
#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`
2016-07-11 09:40:14: pm2 has been killed by signal, dumping process list before exit...
2016-07-11 09:40:14: Deleting process 1
2016-07-11 09:40:14: Stopping app:endpoints id:1
2016-07-11 09:40:14: Process with pid 24 still not killed, retrying...
2016-07-11 09:40:14: App [endpoints] with id [1] and pid [24], exited with code [0] via signal [SIGINT]
2016-07-11 09:40:14: Deleting process 2
2016-07-11 09:40:14: Stopping app:pm2-logrotate id:2
2016-07-11 09:40:14: App [pm2-logrotate] with id [2] and pid [45], exited with code [0] via signal [SIGINT]
2016-07-11 09:40:15: [PM2] Exited peacefully

```
...
```

cf CONTRIBUTING.md for more informations

**Comment by vmarchaud** [comment]
@ATGardner  Could you try with the dev branch of pm2 and tell me if the issue is still here : 
```npm install Unitech/pm2#development -g
&& pm2 update```

**Comment by ATGardner** [comment]
After figuring out how to run in non-daemon mode, I got the same problem. Adding the 1000ms timeout in the Daemon.js gracefullExit temporarily fixed it for me.

**Comment by Unitech** [comment]
Right, currently there are no signals to tell Keymetrics that PM2 has been manually stopped/killed
We add this in the Keymetrics backlog (it may be implemented on PM2 side also as a quick fix)

BTW @ATGardner you should try [PM2 v2](https://github.com/Unitech/pm2/blob/development/CHANGELOG.md#200---quantica-ultimatum), it has a much cleaner API and better error reporting.

On you package.json just do:

```
[...]
  "dependencies" : {
    "pm2" : "next",
[...]
```

New API:
```javascript
var PM2 = require('pm2');

// Or instanciate a custom PM2 instance

var pm2 = new PM2.custom({
  pm2_home :    // Default is the legacy $USER/.pm2. Now you can override this value
  cwd      :    // Move to CWD,
  daemon_mode : // Should the process stay attached to this application,
  independant : // Create new random instance available for current session
  secret_key  : // Keymetrics secret key
  public_key  : // Keymetrics public key
  machine_name: // Keymetrics instance name
});

// Start an app
pm2.start('myapp.js');

// Start an app with options
pm2.start({
  script   : 'api.js',
  instances: 4
}, function(err, processes) {
});

// Stop all apps
pm2.stop('all');

// Bus system to detect events
pm2.launchBus((err, bus) => {
  bus.on('log:out', (message) => {
    console.log(message);
  });

  bus.on('log:err', (message) => {
    console.log(message);
  });
});

// Connect to different keymetrics bucket
pm2.interact(opts, cb)

// PM2 auto closes connection if no processing is done but manually:

pm2.disconnect(cb) // Close connection with current pm2 instance
pm2.destroy(cb)    // Close and delete all pm2 related files of this session
```
