### ISSUE TITLE
CLI argument parsing issues

### ISSUE THREAD

**Issue by Unitech** [Unitech/pm2#2272]
- [#2230] pm2 does not response to duplicated arguments (patchCommanderArg is not correct) 
- [#2198] Start process breaks when params are too long
- [https://github.com/tj/commander.js/issues/553]
- [https://github.com/tj/commander.js/issues/475]

**Comment by nfantone** [comment]
@Unitech Any idea where to start looking for #2198? Or a pointer? Willing to send you guys a PR.

**Comment by Unitech** [comment]
Thanks help appreciated! I just fixed the issue, it was the patchCommanderArg that was failing.
At the root it comes from the [commander.js module](https://github.com/tj/commander.js/issues/475) if you wanna patch that module!

I've added a test suit for arguments parsing: 
https://github.com/Unitech/pm2/blob/development/test/bash/args.sh

Now waiting for test suit to pass on [Travis](https://travis-ci.org/Unitech/pm2)

If you wanna try this fix:

```
$ npm install Unitech/pm2#development -g
$ pm2 update
``` 

Cheers

**Comment by nfantone** [comment]
Works wonders. Thank you very much for your time!

Any chance we could see this in a not-so-distant release? Would you recommend installing 2.0.0-rc3?

**Comment by Unitech** [comment]
Great! I'm checking some last things and PM2 2.0 will be released, sometime next week,

Yes you can install it with confidence, I deployed it everywhere at Keymetrics and it works great so far
