### ISSUE TITLE
Log messages prefixed with `PM2`

### ISSUE THREAD

**Issue by zdychacek** [Unitech/pm2#2273]
Hi,

is there any way to have messages coming from PM2 itself logged into file (those prefixed with "PM2")?

Now, we have "out" and "error" log files and I think it would be useful if we have PM2 messages logged as well (processes restarts info, ...).

Thank you for your response.

O.

**Comment by vmarchaud** [comment]
There are logged into the pm2 folder under the name of pm2.log, you should have them too.
