### ISSUE TITLE
How to run script with no stdout?

### ISSUE THREAD

**Issue by jsEveryDay** [Unitech/pm2#2278]
How can I possibly run a bash script that does nothing for pm2?
In order to avoid running it on crontab as @reboot ...etc...etc

```
[user]$ ./start.sh
[user]$
```

It simply starts a process for me but no log or console results are emitted.
Tried every possible method from documentation, the app simply restarts indefinitely.

Used this new method I learned today with pipefail but no success.

```
   {
      "name": "Test",
      "script": "/bin/sh",
      "cwd" : "/home/user/folder",
      "args": [
        "-c",
        "-o",
        "pipefail",
        "./start.sh"
      ]
    }
```

Its a bash that starts a jar file with log4k arguments.

Can pm2 accept a start script and a stop script? so it could act as a deamon?
How about reading the log from a log file?

```
OS         : CentOS 6.8
node.js    : 6.3.0
PM2        : 1.1.3
```
#### PM2 Log output

```
...2016-07-13 11:40:44: App name:Test id:3 online
2016-07-13 11:40:44: App [Test] with id [3] and pid [9065], exited with code [0] via signal [SIGINT]
2016-07-13 11:40:44: Script /bin/sh had too many unstable restarts (16). Stopped. "errored"
```

**Comment by soyuka** [comment]
Your bash script should keep running or you could disable the autorestart feature. 

For example, I use a script named `sleep.sh`:

```bash
sleep 10
```

```
pm2 start sleep.sh
```

Will restart every 10 seconds, because the bash script will end after the sleep, and so will `exit with code [0]`. Then pm2 will simply restart the script.

**Comment by vmarchaud** [comment]
``` 
 {
      "name": "Test",
      "script": "/bin/sh",
      "cwd" : "/home/user/folder",
      "args": [
        "./start.sh"
      ],
      "error_file": '/dev/null',
      "out_file": '/dev/null'
    }
```
