### ISSUE TITLE
--no-daemon gets parsed by pm2 even when passed as argument to started script

### ISSUE THREAD

**Issue by rainyday** [Unitech/pm2#2285]
When running, for example the following command:

     pm2 start loader.js -- --no-silent --no-daemon --production

#### Expected behavior

Arguments after `--` are passed to loader.js rather than used by pm2

#### Actual behavior

`--no-daemon` is used as both an argument to loader.js **and** an argument to pm2 resulting pm2 being run with `--no-daemon` which is not the desired behavior

#### Steps to reproduce

Run a script that takes --no-daemon as an argument.

#### Software versions used

```
OS         : Ubuntu Server 16.04
node.js    : v6.3.0
PM2        : 1.1.3
```

#### PM2 Log output

```
 Use `pm2 show <id|name>` to get more details about an app
--no-daemon option enabled = do not exit pm2 CLI
PM2 daemon PID = 3744
[PM2] Streaming realtime logs for [all] processes
...
```

**Comment by soyuka** [comment]
Indeed, this line should only test in process.argv preceding `--`:

https://github.com/Unitech/pm2/blob/30239e142928ae04fa19733e186df4c9288f3949/bin/pm2#L149

**Comment by Unitech** [comment]
fixed, available in dev branch
