### ISSUE TITLE
 process.exit(1) makes pm2 enter restart loop

### ISSUE THREAD

**Issue by sulliwane** [Unitech/pm2#2286]
#### Expected behaviour
After running once my app.js with ```pm2 start```, the program should exit, because it calls ```process.exit(1);```.
...

#### Actual behaviour
when using  ```pm2 start```, my app enter an infinite restart loop.
...

#### Steps to reproduce
Here is the code:
```javascript
    const stream = await mongo.find(query).sort(sort).stream();
    stream.pipe(through2({ objectMode: true },
      (chunk, enc, callback) => {
        debug(chunk);
        callback();
      }, 
      (callback) => {
        debug('NO MORE DATA');
        process.exit(1);
        callback();
      }
    ))
    .on('finish', () => {debug('finish of stream');})
    .on('end', () => {debug('end of stream');});
```
If I remove ```process.exit(1);``` then pm2 won't enter infinite restart loop.
...

#### Software versions used

```
OS         : Ubuntu 16.04
node.js    : 6.2
PM2        : 1.1.3
```

#### PM2 Log output

```
 pm2:fork_mode stds: {"out":"/home/me/.pm2/logs/project-out-6.log","err":"/home/me/.pm2/logs/project-error-6.log"} +2s
2016-07-18 18:32:18: App name:project id:6 online
  pm2:god Error vizion::analyze() for given folder: /home/me/Documents/project/src/ +6ms
2016-07-18 18:32:20: App [project] with id [6] and pid [25578], exited with code [1] via signal [SIGINT]
2016-07-18 18:32:20: Starting execution sequence in -fork mode- for app name:project id:6
```

No difference if ```--watch``` is enabled or not. It's clrearly the use of ```process.exit(1);``` that trigger the restart. But no infinite restart loop when start my program with ```node app.js```.

 Any idea ?  Many Thanks.

**Comment by soyuka** [comment]
You need to use `--no-autorestart` if you want the app to stop after the first exit.

Also, if your script ended correctly, please use `process.exit(0)`, where `1` is generally used when the script errored.

**Comment by sulliwane** [comment]
I guess pm2 is just not supposed to be used to run an app that can exit by itself...

**Comment by sulliwane** [comment]
@soyuka Thanks a lot for your answer. I appreciate :)

**Comment by aiavci** [comment]
This isn't working when I use `--no-autorestart` either

**Comment by FerLuisxd** [comment]
Still happening to me

**Comment by tsulatsitamim** [comment]
my workaround:
pass app_name to args, and call exec(`pm2 stop ${process.argv[xxx]}`) to stop the app
