### ISSUE TITLE
eaccess after pm2 startup

### ISSUE THREAD

**Issue by NikosEfthias** [Unitech/pm2#2287]
i read some bugs in earlier versions of pm2 about the same problem but none of them solve the problem . when i run sudo startup ubuntu -u <uname>
#### Expected behaviour

register pm2 for startup and let me use pm2 as it was
...
#### Actual behaviour

.pm2 is owned by root and i cannot use pm2 even if i change the ownership of the folder on nex boot it again fails
...
#### Steps to reproduce

type sudo  pm2 startup -u <uname>
...
#### Software versions used

```
OS         :ubuntu 16.4
node.js    :6x
PM2        :1.1.3
```
#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

``` bash
2016-07-20 12:15:01: [PM2][WORKER] Started with refreshing interval: 30000
2016-07-20 12:15:01: [[[[ PM2/God daemon launched ]]]]
2016-07-20 12:15:01: BUS system [READY] on port /home/nikos/.pm2/pub.sock
2016-07-20 12:15:01: RPC interface [READY] on port /home/nikos/.pm2/rpc.sock
```

```
...
```

cf CONTRIBUTING.md for more informations

**Comment by vmarchaud** [comment]
Can you try using the latest pm2 version : `npm install -g Unitech/pm2#development` ?

**Comment by Unitech** [comment]
```
$ npm install pm2@latest -g
$ pm2 startup  # Do not pass any argument to pm2 startup
```
