### ISSUE TITLE
Process is being started automatically

### ISSUE THREAD

**Issue by goforgold** [Unitech/pm2#2288]
If reporting a bug, please use the following template.
#### Expected behaviour

Projects starts
#### Actual behaviour

Gives error that port is already in use
#### Steps to reproduce
- Find process ID by port number `netstat -nltp | grep 9191`
- Kill the process. `kill -9 PID` It is immediately starting the project automatically when I've already removed it from PM2 using `pm2 delete PID` and it doesn't appear in `pm2 list`.
- Try re-adding the process `pm2 start app.js --name="a-name"`. And it is saying that port is already in use. I checked in browser, and find out the project is already running which is really weird.
#### Software versions used

```
OS         : CentOS 6.7
node.js    : 5.0.0 (sorry can't upgrade)
PM2        : 1.1.3
```
#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
Really needed ?
```

Also, check this for complete explanation.
http://serverfault.com/questions/790874/

**Comment by vmarchaud** [comment]
Could you try using latest pm2 version : `npm install pm2 -g && pm2 update` ? Maybe that you have two pm2 instance running ?

**Comment by vmarchaud** [comment]
No update, closing.
