### ISSUE TITLE
Should share cache when running in cluster mode

### ISSUE THREAD

**Issue by ravisoni6262** [Unitech/pm2#2291]
I'm using https://github.com/ptarjan/node-cache for creating app cache and I also tried to run my app using pm2 in cluster mode but the problem is that each  cluster process is creating it own instance of cache module instead of sharing cache among all cluster processes.

#### Expected behaviour
cache should be shared between all cluster process. 
...

#### Actual behaviour
Cache is not shared.
...

#### Steps to reproduce

Install memory-cache module and start app using pm2 in cluster mode
...

#### Software versions used

```
OS         : OS X EI CAPITAN version 10.11.5
node.js  : v4.4.7
PM2       : latest
```

**Comment by vmarchaud** [comment]
Cluster worker doesnt share memory so thats pretty logic that you can't use this kind of cache.
Our cluster mode use the node implementation of cluster [documented here](https://nodejs.org/api/cluster.html#cluster_how_it_works).
