### ISSUE TITLE
Cannot read ssh key on Windows

### ISSUE THREAD

**Issue by 4ants** [Unitech/pm2#2292]
When trying to set ecosystem deploy from Windows I get error when pm2 tries to read ssh key file. Here is my configuration:
`
"user": "root",
"key": "C:\\Users\\jadranko.dragoje\\.ssh\\id-rsa",
"host": "REMOTE-URL",
"ref": "origin/staging",
"repo": "GIT-REPO",
"path": "/home/api/v1",
"post-deploy": "npm install && pm2 startOrRestart ecosystem.json --env staging"
`

When I run:
pm2 deploy ecosystem.json staging setup

I get error:
Identity file C:Usersjadranko.dragoje.sshid-rsa not accessible: No such file or directory.

It is like it strips backslashes.

#### Expected behaviour
Deploy setup should be successful.

#### Actual behaviour
Error is thrown when reading key file.

#### Steps to reproduce
Try to run deploy on Windows with ssh key absolute path.

#### Software versions used
```
OS         : Window 10
node.js    : 4.4.7
PM2        : 1.1.3
```

**Comment by vmarchaud** [comment]
Could you try with the path set to `C:/Users/jadranko.dragoje/.ssh/id-rsa` or `~/.ssh/id-rsa` ?

**Comment by 4ants** [comment]
This path works: `C:/Users/jadranko.dragoje/.ssh/id-rs.pem`.
This does not: `~/.ssh/id-rsa`

Thanks.
