### ISSUE TITLE
Local config that is merged with config

### ISSUE THREAD

**Issue by pdufour** [Unitech/pm2#2293]
Hi I just wanted to check if there was way to have a local config be merged with a pm2 config? So for instance we have a development.json, but it'd be nice if you could have a local.json that would get merged with development.json so you could have your own changes.

**Comment by Unitech** [comment]
Seems interesting, could you please provide an example of `local.json` and a `development.json` to see the use case, thank you

**Comment by vmarchaud** [comment]
You can define javascript inside json process file or directly use `ecosystem.config.js` so you can easily define a variable that will be retrieved from enviromment : 
```
{
  "apps": [
    {
      "name": "test",
      "script": "server.js",
      "autorestart": process.env.NODE_ENV === "production" ? true : false,
      "env": {
        "MYSQL_USER: process.env.MYSQL_USER || 'default user'
      }
    }
  ]
}
```
