### ISSUE TITLE
Specify an IP Address for the API to bind on

### ISSUE THREAD

**Issue by bragatto** [Unitech/pm2#2294]
As of now, the API (pm2 web) always binds on 0.0.0.0, possibly exposing the API to public IP addresses if they are present on the server.

I'd like to be able to  specify only a private IP for the API to bind on, so I don't need to rely on a firewall to make sure nothing from the outside world can reach it.

This seems to be fairly simple, I've made the modifications on pm2 and will submit a PR for the 
development branch, please consider this.

EDIT: PR #2295

Kind regards

**Comment by Unitech** [comment]
Great thanks for the PR, will be available on the next PM2 release (v2)

Cheers!
