### ISSUE TITLE
cmd pops up when watch mode triggers app restart

### ISSUE THREAD

**Issue by httpdigest** [Unitech/pm2#2297]
On Windows when an application is started in watch mode via `pm2 start app.js --watch` and a watched file is changed, pm2 opens a new cmd window with empty content which is closed immediately afterwards. The application is restarted successfully, but the quick popping up of a new cmd window is irritating, especially when you are working in a text editor/IDE and you are losing the keyboard focus because of the opened cmd.

#### Expected behaviour
- pm2 restarts the watched application without opening a new cmd window

#### Actual behaviour
- pm2 restarts the watched application _with_ a briefly showing new cmd window

#### Steps to reproduce
- on Windows, start a simple application in `--watch` mode
- change a watched file
- observe that a new cmd window is opened and closed quickly in succession

#### Software versions used

```
OS         : Windows 7 x64
node.js    : 6.3.1
PM2        : 1.1.3
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`
No log output

**Comment by Unitech** [comment]
Thanks for reporting,

Can you try again with pm2 v2:

```
$ npm install pm2@next -g
$ pm2 update
$ pm2 start app.js --watch
```

**Comment by httpdigest** [comment]
Thanks for the quick reply!
Indeed, installing the pm2@next version resolved this issue. And it also resolved calling `pm2 close all`, which also quickly opened a new cmd.
This issue can then be closed.

**Comment by AbhiGoku** [comment]
i too am getting the same error 
But even after doing the suggest ans i am getting the same annoying terminals.
Please help me in this

**Comment by TomerconDevelopers** [comment]
im getting same error

**Comment by weihsth** [comment]
I have the same popping cmd windows.

pm2 version: 5.3.0
cluster-mode-config:
```
module.exports = {
    apps: [
        {
            name: "api",
            script: "./bin/www",
            args: "",
            exec_mode: "cluster",
            instances: 4,
            kill_timeout: 4000,
            wait_ready: true,
            autorestart: true,
            watch: true,
            max_memory_restart: "1G",
            log_date_format: "YYYY-MM-DD HH:mm Z",
            env: {
                NODE_ENV: "development",
                PORT: 1337
            },
            env_production: {
                NODE_ENV: "production",
                PORT: 3000,
                watch: false
            }
        }
    ]
};
```
