### ISSUE TITLE
log/out/error_file ignored on some OS

### ISSUE THREAD

**Issue by ssilve1989** [Unitech/pm2#2303]
Given the following config:

```
{
	"apps": [
		{
			"name"      : "app-name",
			"script"    : "./server.js",
			"watch"     : false,
			"log_file"  : "./server.log",
			"out_file"  : "./server.out",
			"error_file": "./server.err",
			"env"       : {
				"NODE_ENV": "production"
			},
			"node_args" : "--harmony"
		}
	]
}

```
On Mac OS 10.10.5 it seems like the log props are completely ignored. However on an Ubuntu system they work fine.

Is this a bug?

**Comment by vmarchaud** [comment]
We dont make any difference between MacOS and Linux, maybe a problem of path resolving, have you a way to reproduce the issue ? (And please join your PM2/NodeJS versions).

**Comment by vmarchaud** [comment]
Closing in favor of #2474
