### ISSUE TITLE
Attach stdin to running process (pm2 attach?) 

### ISSUE THREAD

**Issue by roblav96** [Unitech/pm2#2304]
I start my server like so:

``` shell
pm2 kill && pm2 start server.json && pm2 logs
```

and the viewing the logs is fantastic! 😄 

Although with `nodemon` after starting my server and viewing logs, I can type into the terminal and receive commands into my node app using `process.stdin`.
### Example:

``` javascript
process.stdin.resume()
process.stdin.setEncoding( "ascii" )
process.stdin.on( "data", function ( input ) {
    console.info( 'input >', input )
    let argz = input.split( ' ' )
    argz[ argz.length - 1 ] = argz[ argz.length - 1 ].replace( /\n/g, '' )
    let fn = argz.splice( 0, 1 )
    if ( _.isFunction( coms[ fn ] ) ) {
        coms[ fn ]( argz )
    } else {
        console.log( 'INVALID COMMAND\n' )
    }
} )
```

Is this possible to do after executing `pm2 logs`?

**Comment by Unitech** [comment]
Nope currently there is no way to attach to the process stdin as the process is put in background.

It may be interesting to implement some sort of `pm2 attach <process_id>` in the future

**Comment by roblav96** [comment]
Thanks man! Sounds good.

**Comment by Unitech** [comment]
Reattaching to a stdin is more complicated than expected. If anyone has ideas on that please share

**Comment by Unitech** [comment]
closing in favor of https://github.com/Unitech/pm2/issues/2968
