### ISSUE TITLE
how to use monit with pm2 

### ISSUE THREAD

**Issue by lonso** [Unitech/pm2#2305]
i want to run monit with pm2 
my script like this:
````
check process node_test matching /xxx/test/test.js
start program = "/usr/local/bin/pm2 start /xxx/test/test.js"
stop program = "/usr/local/bin/pm2 stop /xxx/test/test.js"
````

but ,still start faild.

**Comment by Unitech** [comment]
You may want to monitor PM2 via his pid (~/.pm2/pm2.pid)

**Comment by lonso** [comment]
@Unitech 
yes.i can monitor PM2 via his pid or monitor matching files.
but, the error is  start program not execute success.

do you hava some suggestion to monitor pm2 process. if process crash and pm2 not restart it.

**Comment by Unitech** [comment]
Concerning:

```
start program = "/usr/local/bin/pm2 start /xxx/test/test.js"
stop program = "/usr/local/bin/pm2 stop /xxx/test/test.js"
```

It looks good to me.

Could you please show me the ~/.pm2/pm2.log when monit try to restart pm2?
Also the monit logs could be interesting.

Something else make sure you installed pm2@next `npm install pm2@next -g`

Thanks

**Comment by lonso** [comment]
@Unitech 
unfortunately, the ~/.pm2/pm2.log  is empty, no log in that file.
do you know why?

monit logs like this:

```
[CST Jul 26 11:53:44] info     : 'node_test' trying to restart
[CST Jul 26 11:53:44] info     : 'node_test' start: /usr/local/bin/pm2
[CST Jul 26 11:54:15] error    : 'node_test' failed to start
[CST Jul 26 11:54:20] error    : 'node_test' process is not running
[CST Jul 26 11:54:20] info     : 'node_test' trying to restart
[CST Jul 26 11:54:20] info     : 'node_test' start: /usr/local/bin/pm2
[CST Jul 26 11:54:50] error    : 'node_test' failed to start
[CST Jul 26 11:54:55] error    : 'node_test' process is not running
[CST Jul 26 11:54:55] info     : 'node_test' trying to restart
[CST Jul 26 11:54:55] info     : 'node_test' start: /usr/local/bin/pm2

```

**Comment by Unitech** [comment]
Alright some environment variables are not set, make sure you pass PM2_HOME with the right value:

```
start program = "PM2_HOME='/home/username/.pm2' /usr/local/bin/pm2 start /xxx/test/test.js"
stop program = "PM2_HOME='/home/username/.pm2' /usr/local/bin/pm2 stop /xxx/test/test.js"
```

**Comment by lonso** [comment]
@Unitech  
thanks.

it's works. it's my environment reason,
The error is 
```
/usr/bin/env: node: No such file or directory

so we can do like this:

sudo ln -s /usr/bin/nodejs /usr/bin/node

```
But the import things is to use faq docs.
[https://mmonit.com/wiki/Monit/FAQ#execution](https://mmonit.com/wiki/Monit/FAQ#execution)
That faq tell me how to debug monit.
