### ISSUE TITLE
Can you remove the '.sh',and add an extra option to specify the file extention?

### ISSUE THREAD

**Issue by xzycn** [Unitech/pm2#2306]
Hi,
Generally speaking,we put the startup script in /etc/init.d without an extension,it's convenient(e.g. type less),but the cmd "pm2 startup" generate it,and the code :

> var scriptFile = '/etc/init.d/pm2-init.sh',

in lib/CLI.js  .
So,should we remove it and add an extra option to specify the file extention?
:)

**Comment by Unitech** [comment]
Yes that's true that the `.sh` extension could be dropped, I'm just a bit worried about backward compatibility if someone regenerate a startup script

**Comment by xzycn** [comment]
That's great,I'm looking forward to it :)

**Comment by lewellyn** [comment]
TBH, I think the "expected" behavior would be to simply leave the file named `pm2`, not `pm2-init` or `pm2-init.sh` (I scratched my head over that actually).

While it's a breaking change, I can't imagine that it's one which would actually upset too many people. After all, it's a change to bring things in line with expectations and it will reduce typing. `service pm2-init.sh start` seems a bit strange as a command. ;)

It might be worthwhile to detect if there's an existing `pm2-init.sh`, move it to `~`, then remind the person invoking `pm2 startup` at the end that the name has changed and that their existing script was saved in case they want to keep it for some reason.

**Comment by Unitech** [comment]
Closing in favor of #2559 

To try the new startup system:

```bash
$ npm install Unitech/pm2#development -g
$ pm2 update
```

```bash
$ pm2 startup     # Then copy / paste the command displayed
$ pm2 unstartup
```
