### ISSUE TITLE
post-deploy / using environments variable defined in apps

### ISSUE THREAD

**Issue by bbnnt** [Unitech/pm2#2308]
If reporting a bug, please use the following template.

#### Expected behaviour

Getting environment variables defined in an app to be available when `post-deploy` occurs

#### Actual behaviour

Not getting anything

#### Steps to reproduce

```
apps: [{
    name: "www",
    ...
    env: {
        NODE_ENV: "production"
    }
}],
deploy: {
    production: {
        ...
        `"post-deploy" : "echo $NODE_ENV && npm install && npm run build && pm2 startOrRestart ecosystem.json --env production"`
        ...
    }
}
```

`NODE_ENV` won't return anything

#### Software versions used

```
OS         : all
node.js    : all
PM2        : all
```

**Comment by jackblackjack** [comment]
I have same error. Do you fix it?)
