### ISSUE TITLE
webpack // need to have apps' specific  behaviours

### ISSUE THREAD

**Issue by bbnnt** [Unitech/pm2#2309]
#### Expected behaviour

a successfull `npm run build` defined in a `post_update` key within an app definition in some standard `ecosystem.json` file, having the following in package.json :

```
...
webpack --config ./conf/webpack/prod.js
...
```
#### Actual behaviour

nothing happens
#### Steps to reproduce

deploying with some `post_update` array of commands within a specific app containing, having one command being `npm run build`

Trigerring specific commands from within an app definition is quite opaque; I expected it to be more obvious. Sorry if it is simple for advanced user; glad to get some help

**Comment by vmarchaud** [comment]
@bbnnt Can you provide us a example to reproduce the issue and your pm2/nodejs version ? Thanks
