### ISSUE TITLE
Ignore watch not working on windows

### ISSUE THREAD

**Issue by MilknCookie** [Unitech/pm2#2314]
I have been having this problem for a very long time and i was always hopping for a fix.
#### Expected behaviour

Should not watch directory in the ignore watch.
#### Actual behaviour

Watch directory even if present in ignore watch resulting in high CPU usage.
#### Steps to reproduce

Install nodeJs pm2.
Run it with process.json
{
    "apps": [{
        "name": "server-app",
        "script": "D:\htdocs\dev\nodejsserver\server.js",
        "watch": ["D:\htdocs\dev\nodejsserver",],
    "ignore_watch":["node_modules", "nodeCellInfo", "public", "test",".hg", "formulaireds"],
    "watch_options"  : {
            "followSymlinks": false
         },
    "exec_mode" : "clustered",
        "node_args": "--harmony",
        "merge_logs": true,
        "env": {
          "NODE_ENV": "development"
        },
        "autorestart":false
    }]
}
#### Software versions used

```
OS         : Windows server 2008
node.js    : 6.3.1
PM2        :  1.1.3
```
#### PM2 Log output

Changed detected in D:\htdocs\dev\...\node_modules.

There is a way to fix it. I have been remplacing the watcher.js inside lib with the file from the following link : 
https://raw.githubusercontent.com/Unitech/pm2/f6847bae3b7711ba573e6e210e378c4fcd7ad05f/lib/Watcher.js

But every time i update pm2. It gets overwrite and there will come a day where this wont work anymore because of an update.

**Comment by vmarchaud** [comment]
Will look into this and see if we can fix this.

**Comment by vmarchaud** [comment]
Working great on my Win7, thought we cant test on a Windows 2k8 server, i recommand you testing with `pm2@next`, see if its fix the problem or not.

**Comment by MilknCookie** [comment]
My next try will be with : "env": { "args": ["--ignore-watch=\.hg|node_modules"] }

I can precise that everything was working great before this commit :  

https://github.com/Unitech/pm2/commit/506c7146e4a422a6de1d4c47b5d17d763ece65cb

**Comment by amelon** [comment]
may be related to issue #2366

**Comment by vmarchaud** [comment]
We updated chokidar dependency, can you re-test using the latest version : `npm install -g pm2@next && pm2 update` ?

**Comment by mindonline** [comment]
@vmarchaud 
Same issue on pm2 v2.1.3, windows 10.
Config:
`{
  "apps" : [
    {
      "name"      : "www",
      "script"    : "web.js",
      "watch"     : [
        "../"
      ],
      "ignore_watch" : [
        "../public",
        "../.gitignore",
        "../README.MD",
        "../package.json",
        "../node_modules",
        "../.git",
        "../.idea",
        "../*.log"
      ],
      "watch_options": {
        "followSymlinks": false,
        "usePolling": true
      },
      "env": {
        "COMMON_VARIABLE": "true"
      },
      "env_production" : {
        "NODE_ENV": "production"
      }
    }
  ]
}
`

Watch working on all files , and ignores "ignore_watch" property. I tried absolute path with no success..

**Comment by MilknCookie** [comment]
@vmarchaud Going to retry soon !

**Comment by MilknCookie** [comment]
![image](https://cloud.githubusercontent.com/assets/8702639/20193351/8f5ed0c4-a75b-11e6-9f51-1f85792bf8a5.png)
Still taking above 1 full cpu juste to watch files

**Comment by vmarchaud** [comment]
See #2629 we group all issue into one.
