### ISSUE TITLE
Stop command that doesn't throw exceptions if it doesn't exist

### ISSUE THREAD

**Issue by joshunger** [Unitech/pm2#2318]
I think a lot of people have deploy code that tries to stop and then start a pm2 process.  When deploying a new application with pm2, the process doesn't exist.  It would be helpful if there was a stop command that included a flag that wouldn't throw an exception if it is not found.  The stop command would still throw any other exceptions.  How are people handling this?

**Comment by Unitech** [comment]
You can check the return code of `pm2 stop` by using `$?`
if $? == 0 the app has been stopped
if $? == 1 the app does not exists and cannot be stopped
