### ISSUE TITLE
pm2 doesnt start python when instances is specified

### ISSUE THREAD

**Issue by motherhubbard** [Unitech/pm2#2323]
#### Expected behaviour
The python program should start

#### Actual behaviour
The application does not start and the following error is seen:
crawl_service-0 (err): SyntaxError: Unexpected token import
crawl_service-0 (err):     at Object.exports.runInThisContext (vm.js:76:16)
crawl_service-0 (err):     at Module._compile (module.js:513:28)
crawl_service-0 (err):     at Object.Module._extensions..js (module.js:550:10)
crawl_service-0 (err):     at Module.load (module.js:458:32)
crawl_service-0 (err):     at tryModuleLoad (module.js:417:12)
crawl_service-0 (err):     at Function.Module._load (module.js:409:3)
crawl_service-0 (err):     at Function._load (/apps/libs/node-v6.3.1/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
crawl_service-0 (err):     at /apps/libs/node-v6.3.1/lib/node_modules/pm2/lib/ProcessContainer.js:217:23
crawl_service-0 (err):     at /apps/libs/node-v6.3.1/lib/node_modules/pm2/node_modules/async/lib/async.js:52:16
crawl_service-0 (err):     at /apps/libs/node-v6.3.1/lib/node_modules/pm2/node_modules/async/lib/async.js:1209:30

#### Steps to reproduce

Create a simple pm2 json file and python application, eg:
{
    "script": "my_service.py",
    "error_file": "/data0/logs/python/myerr.log",
    "out_file": "/data0/logs/python/myout.log",
    "pid_file": "/data0/logs/python/mypid.log",
    "watch" : false,
    "interpreter": "python"
}

Confirm the application above runs:
pm2 start my-pm2.json

Kill pm2 and then add "instances":4 to the pm2.json file and restart the application

Confirm the errors are seen as above

Are instances only supported for node apps?

...

#### Software versions used

```
OS         : CentOS 7
python    : 2.7.8 
PM2        : 1.1.3
```

#### PM2 Log output

Nothing in this file other than "too many unstable restarts"

**Comment by vmarchaud** [comment]
@motherhubbard  Could you try using `npm install -g pm2@next` ?

**Comment by motherhubbard** [comment]
@vmarchaud thanks for getting back to me. Ive run the command as requested (and updated to pm2 v2.0.4) but the results are the same.

**Comment by Unitech** [comment]
When passing `instances` to a non-node.js script, it automatically switch the execution mode to cluster_mode.

Just force the "exec_mode" to "fork":

```
{
 "script": "my_service.py",
 "interpreter": "python",
 "instances" : 4,
 "exec_mode" : "fork"
}
```

**Comment by motherhubbard** [comment]
Awesome thanks!

**Comment by denny0223** [comment]
@Unitech will you plain to add some warning message when pass `instances` to a non-node.js script?

I encounter the same problem, but I have no idea to fix it until I google it and find this issue.

By the way, there's no option to set `exec_mode` when start without json file, right?
