### ISSUE TITLE
pm2 maximum retries

### ISSUE THREAD

**Issue by joshunger** [Unitech/pm2#2325]
Does pm2 allows a configuration setting to define the maximum number of retries?

**Comment by vmarchaud** [comment]
From the [documentation](http://pm2.keymetrics.io/docs/usage/application-declaration/) of pm2 under `Control Flow`  :

> max_restarts | type: number	| default : 10 | number of consecutive unstable restarts (less than 1sec interval or custom time via min_uptime) before your app is considered errored and stop being restarted

**Comment by joshunger** [comment]
Thanks @vmarchaud, that was hidden.
