### ISSUE TITLE
pm2 startOrRestart with --only

### ISSUE THREAD

**Issue by sean-hill** [Unitech/pm2#2330]
If reporting a bug, please use the following template.

#### Expected behaviour

For the `--only` option to work with `startOrRestart` command.

#### Actual behaviour

	$ pm2 startOrRestart ecosystem.json --only myapp --env production

		error: unknown option `--only'

#### Software versions used

```
OS         : Linux
node.js    : v4.3.2
PM2        : v0.12.3
```

**Comment by Unitech** [comment]
You must upgrade PM2

```
$ npm install pm2 -g
# or rc 
$ npm install pm2@next -g
```
