### ISSUE TITLE
PM2 Capistrano style deploy issues

### ISSUE THREAD

**Issue by saponifi3d** [Unitech/pm2#2332]
https://github.com/Unitech/pm2/blob/development/lib/Client.js#L228

This means the configuration in the document doesn't work. Can we simply update that to be:
```js
cwd: that.conf.cwd || process.cwd(),
```

Currently, a no-daemon mode can't override the cwd to work with capistrano style depoyments.

pm2 version: 2.0.7

**Comment by Unitech** [comment]
Nice catch! Fixed in development branch
