### ISSUE TITLE
Pass host ids as environment variable

### ISSUE THREAD

**Issue by nitoo7** [Unitech/pm2#2334]
When deploying with pm2, i need to set an array of host id's to where the app is to be deployed. I am thinking of doing so by means of environment variable. How could i do so?

**Comment by Unitech** [comment]
You could pass process.env.HOSTS to your process.json file:

```
{
  "apps" : [{
    "name"      : "api",
    "script"    : "./app1/api.js",
    "instances" : "4"
  },{
    "name"      : "dev-api",
    "script"    : "./app2/child.js",
    "instances" : "1"
  }],
  "deploy" : {
    "production" : {
      "user" : "node",
      "host" : process.env.HOSTS,
      "ref"  : "origin/master",
      "repo" : "git@github.com:Unitech/eip-vitrine.git",
      "path" : "/var/www/test-deploy"
    }
  }
```

http://pm2.keymetrics.io/docs/usage/deployment/

**Comment by nitoo7** [comment]
i am currently calling pm2 deploy commands from jenkins. Would you please how could i set environment variables in there.
