### ISSUE TITLE
Pm2 doesn't log anymore (no log output) when "disconnect" worker from cluster

### ISSUE THREAD

**Issue by markmenox** [Unitech/pm2#2335]
If reporting a bug, please use the following template.

#### Expected behaviour
if in code i disconnect a worker when in cluster mode like the following:
var worker = require('cluster').worker;
          if (worker) {
            worker.disconnect();
          }

from that point on i see that no log is captured/displayed by pm2 when using for example console.log
...

#### Actual behaviour

...

#### Steps to reproduce

...

#### Software versions used

```
OS         : ubuntu 11
node.js    : 5.12.0
PM2        : 1.1.3
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
...
```

cf CONTRIBUTING.md for more informations

**Comment by Unitech** [comment]
#2333
