### ISSUE TITLE
pm2 start process.json --interpreter $(nvm which 0.10) doesn't use correct node version

### ISSUE THREAD

**Issue by joshunger** [Unitech/pm2#2336]
I can't get `pm2 start process.json --interpreter $(nvm which 0.10)` to use the correct node version.

process.json
```
{
  apps : [{
    args: "version",
    name       : "",
    script: "npm"
  }]
}
```

```
nvm use 6
pm2 start process.json --interpreter $(nvm which 0.10)
pm2 logs
```

0|npm      | { 'my-project': '1.0.0',
0|npm      |   npm: '3.9.5',
0|npm      |   ares: '1.10.1-DEV',
0|npm      |   http_parser: '2.7.0',
0|npm      |   icu: '57.1',
0|npm      |   modules: '48',
0|npm      |   node: '6.2.2',
0|npm      |   openssl: '1.0.2h',
0|npm      |   uv: '1.9.1',
0|npm      |   v8: '5.0.71.52',
0|npm      |   zlib: '1.2.8' }

If reporting a bug, please use the following template.

#### Expected behaviour
pm2 should use 0.10 node

#### Actual behaviour
pm2 is using 6.2 

#### Steps to reproduce

...

#### Software versions used

```
OS         : OSX
node.js    : 6.2.2 and 0.10
PM2        : 2.0.7
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
tail: illegal option -- -
usage: tail [-F | -f | -r] [-q] [-b # | -c # | -n #] [file ...]
```

cf CONTRIBUTING.md for more informations

**Comment by Unitech** [comment]
The --interpreter is not available when starting a JSON file, you must declare the interpreter option in the JSON file instead

**Comment by joshunger** [comment]
@Unitech how are you supposed to override options?  Are any available?

**Comment by Unitech** [comment]
By changing the file, we currently does not support overriding options via CLI when using a process file.

The only switch you can do is by using the `--env [env name]` when managing a process.json file
