### ISSUE TITLE
node 6 is not working

### ISSUE THREAD

**Issue by benishak** [Unitech/pm2#2340]
when using node 6 I get the following error when i try to run `pm2 restart all`

```
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at prepareAppName (/usr/lib/node_modules/pm2/lib/CLI.js:2372:19)
    at verifyConfs (/usr/lib/node_modules/pm2/lib/CLI.js:2295:5)
    at Object.CLI._handleAttributeUpdate (/usr/lib/node_modules/pm2/lib/CLI.js:1186:17)
    at Object.CLI._operate (/usr/lib/node_modules/pm2/lib/CLI.js:1016:16)
    at Object.CLI._restart (/usr/lib/node_modules/pm2/lib/CLI.js:1204:7)
    at Object.CLI.restart (/usr/lib/node_modules/pm2/lib/CLI.js:1168:9)
    at /usr/lib/node_modules/pm2/bin/pm2:298:11
    at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:181:20

```

**Comment by Unitech** [comment]
6.4?

What is your PM2 version?

**Comment by benishak** [comment]
thanks a lot

**Comment by Unitech** [comment]
I guess a PM2 update solved that issue! Cheers

**Comment by 2Marks** [comment]
hello @Unitech. i get this error path must be a string received when trying to run **"pm2 ecosystem"** from my dir. attahced is an error image. any help would be appreciated thanks for giving us pm2 .
![capture](https://cloud.githubusercontent.com/assets/12138334/18349366/ff0f9256-75c8-11e6-9dd3-27890275862f.PNG)

**Comment by 2Marks** [comment]
hi @Unitech . i had the issue resolved with @arieljannai comment on it.

   fs.writeFileSync(path.join(process.env.PWD || process.cwd(), f_name), dt);
  Common.printOut('File %s generated', path.join(process.env.PWD || process.cwd(), f_name));

i had to add " || process.cwd()" to the two lines above in cli.js before it worked. i think it should be merged into the module.

**Comment by yagman** [comment]
Help! I am trying to update pm2 using`pm2 update` and I get this same error because pm2 tries to shutdown the running processes before it updates.

**Comment by yagman** [comment]
how do you delete the whole pm2 module?

**Comment by soyuka** [comment]
@yagman something like:

```
pm2 kill
npm rm -g pm2
```

**Comment by 2Marks** [comment]
@yagman

npm uninstall -g pm2
