### ISSUE TITLE
pm2 start process.json --name doesn't work

### ISSUE THREAD

**Issue by joshunger** [Unitech/pm2#2342]
#### Expected behaviour
Setting the name with a process.json should work.
...

#### Actual behaviour
Name is not set.
...

#### Software versions used

```
OS         : OSX 10.11.1
node.js    : 6
PM2        : 2.0.7
```

**Comment by Unitech** [comment]
You can have multiple applications in your process file, you have to declare this attribute in that file

**Comment by joshunger** [comment]
@Unitech this isn't possible at large scales; would it be possible to provide a fix?

**Comment by Unitech** [comment]
In a process.json file you can have multiple applications, it is not possible to override each name with a single name, I dont see the point

**Comment by joshunger** [comment]
@Unitech My biggest concern is that using npm start names every application as "npm".  I can switch to process.json but how do I execute a `require`?  There are multiple ways to solve this.  Thanks for the help.
