### ISSUE TITLE
Pm2 does not restarting processes when finished - only on cluster mode

### ISSUE THREAD

**Issue by adambisek** [Unitech/pm2#2344]
If reporting a bug, please use the following template.

#### Expected behaviour
┌──────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────────────┬──────────┐
│ App name │ id │ mode │ pid   │ status │ restart │ uptime │ memory      │ watching │
├──────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────────────┼──────────┤
│ seznam   │ 0  │ cluster │ 57337 │ online │ 2       │ 59s     │ 84.699 MB   │ disabled │
└──────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────────────┴──────────┘
Restart count should keep groving

#### Actual behaviour
┌──────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────────────┬──────────┐
│ App name │ id │ mode │ pid   │ status │ restart │ uptime │ memory      │ watching │
├──────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────────────┼──────────┤
│ seznam   │ 0  │ cluster │ 57337 │ online │ 0       │ 59s     │ 84.699 MB   │ disabled │
└──────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────────────┴──────────┘
...

#### Steps to reproduce
Run process in cluster mode, it does not keep process restarting when it finish.

I've tried even config in json like this, with same result:
```
{
  "apps" : [{
    "name": "spider",
    "script": "index.js",
    "instances": 5,
    "max_memory_restart": "200M",
    "exec_mode": "cluster",
    "autorestart": true
  }]
}
```
...

#### Software versions used

```
OS         : OSX 10.11.6
node.js    : v6.2.2
PM2        : 1.1.3
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
...
```

cf CONTRIBUTING.md for more informations

**Comment by Unitech** [comment]
That is the behavior of the cluster mode. If you only run one application, the fork mode is the way to go
