### ISSUE TITLE
Calls to CLI.list() never finish

### ISSUE THREAD

**Issue by kay-is** [Unitech/pm2#2345]
I use the programmatic API to mange some background processes and some calls to `CLI.list()` never finish. 

#### Expected behaviour

I get an error or a result.

#### Actual behaviour

The callback never gets called, neither with error nor result

#### Steps to reproduce

I don't know really. If I got a process list that didn't change since the last `CLI.connect()` everything works. Then I start a process with pm2 (which is finished in a few milliseconds), after that I call `CLI.list()` and wait.

#### Software versions used

```
OS         : Ubuntu 14.04
node.js    : 4.2.3
PM2        : 1.1.3
```

#### PM2 Log output

All processes ended with the exit code 0, nothing special.

**Comment by Unitech** [comment]
Please use pm2@next for better API

```
$ npm install pm2@next --save
```

**Comment by kay-is** [comment]
Ah, is this stable?

**Comment by Unitech** [comment]
Yes it is! We are just waiting some more days to officially release the V2!

I'm closing the issue as the upgrade seems to have fixed your problem,
