### ISSUE TITLE
Can I use pm2 api in pm2?

### ISSUE THREAD

**Issue by zhengnz** [Unitech/pm2#2346]
I write a website to manage pm2, use node to start it is correct, but when it use pm2 to start it I will get some error.
Does it mean I can't use pm2 api in pm2?

**Comment by vmarchaud** [comment]
you need to have a pm2 instance started to use pm2 since the api just communicate with the daemon.

**Comment by vmarchaud** [comment]
Do you have a example on what you want to do ? Which version of pm2 are you using too ?

**Comment by zhengnz** [comment]
npm install -g lgp-monitor
lgp-monitor -p your_port
view http://127.0.0.1:your_port
This is my project, If I use pm2 to start it, I can't use pm2 api.

**Comment by zhengnz** [comment]
The project can list all pm2 app, and can reload or restart.
重载 = reload
重启 = restart

**Comment by vmarchaud** [comment]
Looked at your code, could you try using pm2.connect() everytime to want to do an action ?
And by the way you should use `npm install pm2@next` since it got a improved API.

**Comment by zhengnz** [comment]
I install use **npm install pm2@next** and rewrite my code as pm2 module, then it run correct!
Thank for your help.
