### ISSUE TITLE
pm2-dev API

### ISSUE THREAD

**Issue by Ferixz** [Unitech/pm2#2349]
Hey there, 

I'm setting up my development environment using `pm2-dev`.
There are multiple services that need to be forked at the same time so that all of the services are available on developer's local machine. I could of course set up the environment using an ecosystem file. The problem is that some environment variables need to loaded from a config file which is shared across the process, and the ecosystem file does not allow importing modules.

I managed to write an script to augment the process file with the configuration variables and kick off the process using `pm2` API, but I really prefer handling it via `pm2-dev`.

Of course, one solution would be to regenerate an static config file and then invoke `pm2-dev`, but it would be a pain to watch for changes in those file and do the signaling and stuff. 

I couldn't find anything on how to use `pm2-dev` programmatically, and after skimming through source codes my initial take is that it is not possible at the moment. If that is correct, then I have two suggestions:

1. Expose `pm2-dev` API. 
2. Improve `pm2` to treat a JS file as ecosystem generator (if the appropriate flag is set). The generator script is run under node environment and exports the ecosystem object.

**Comment by Unitech** [comment]
About pm2-dev, you can have a look at how PM2 is being used by that command here: [https://github.com/Unitech/pm2/blob/development/lib/DevCli.js](https://github.com/Unitech/pm2/blob/development/lib/DevCli.js)


In your ecosystem file you can declare different environment variables for each application for each environment: http://pm2.keymetrics.io/docs/usage/application-declaration/#switching-environments

Then you can use pm2-dev to start your application the desired environment type:

```
$ pm2-dev start ecosystem.json --env development
```

https://github.com/Unitech/pm2/blob/development/lib/DevCli.js#L128

**Comment by vmarchaud** [comment]
API has been improved in `pm2@2.0.x`, plus since you didnt answered we consider that the response was what you was looking for. Re-open if you need more information.
