### ISSUE TITLE
No way of adding a worker to a cluster in code

### ISSUE THREAD

**Issue by markmenox** [Unitech/pm2#2351]
If reporting a bug, please use the following template.

#### Expected behaviour
It would be useful if there would be a way of adding/spawning a new worker (when in cluster mode) from inside the code (we already have this feature when using pm2 from the command line with: pm2 reload). This is really useful when in our application code we use nodejs "Domains" to handle unhandled exceptions/errors, and we gracefully exit the process. At the moment all i can do is just exit the process without having a new worker ready to handle incoming requests....this is not so good in production. 
...

#### Actual behaviour

...

#### Steps to reproduce

...

#### Software versions used

```
OS         :
node.js    :
PM2        :
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
...
```

cf CONTRIBUTING.md for more informations

**Comment by Unitech** [comment]
First, make sure you use `npm install pm2@next -g` to use PM2 inside applications managed by PM2.

Then, to spawn more workers, you may want to use the `scale` command:

CLI:
```bash
$ pm2 scale <app_name> <instance_number>
```

Programmatic:
```javascript
var pm2 = require('pm2');

pm2.scale('app-name', 2, (err, processes) => {
  console.log('Success');
});
```

**Comment by markmenox** [comment]
Is this functionality available in the latest stable release?

**Comment by vmarchaud** [comment]
@markmenox If by stable release you mean the old one, yeah [it is](https://github.com/Unitech/pm2/blob/aab0221f7f0c60f45a93e0fc1b3fd6555fce947c/test/programmatic/cluster.js#L143) but you really should use the v2 RC version, the pm2 API has been ameliorated and the overall performance are better.

**Comment by markmenox** [comment]
I think i will switch to the current release when it will be stable cause i
use pm2 in production to manage website and rabbitmq consumer clusters. So
it is great news that this functionality is already available. I will test
it. I think also  that this functionality is not in the docs right?
Le 23 août 2016 9:00 PM, "vmarchaud" <notifications@github.com> a écrit :

@markmenox <https://github.com/markmenox> If by stable release you mean the
old one, yeah it is
<https://github.com/Unitech/pm2/blob/aab0221f7f0c60f45a93e0fc1b3fd6555fce947c/test/programmatic/cluster.js#L143>
but you really should use the v2 RC version, the pm2 API has been
ameliorated and the overall performance are better.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Unitech/pm2/issues/2351#issuecomment-241840573>, or mute
the thread

**Comment by vmarchaud** [comment]
@markkevans Yes it isnt currently in the official documentation, we certainly will rewrite it when we gonna release PM2 v2.

**Comment by markmenox** [comment]
Great i cant wait for the new version thank you

**Comment by markmenox** [comment]
I am testing this and i see a little problem.
Example: 
Cluster of two instances with ids : 1 and 2

My nodejs domain catch the unhandled execption and i have my shutdown code that is executed.
Firstable i would like to start a new worker (inside code with pm2 scale command as you said) because the current process is going to cut the http server (so it will no more be available for the application), and i would like to always have my cluster with two available processes (actually we now have our cluster with three processes but one process is no more available because we cutted the http server).
At the end my shutdown logic will kill the current process/worker.
The problem is that, knowing that the new worker has a new id, pm2 will restart the current process i killed inside code because ids are different. 
But i would like to have the same behaviour as the pm2 reload command where the new worker has the same id of the worker that is going to kill and i think that this is the reason why pm2 with its pm21 reload command will not relaunch the process once killed

**Comment by markmenox** [comment]
no answer?

**Comment by markmenox** [comment]
I still don't know how to do this with pm2

**Comment by vmarchaud** [comment]
For the cluster mode to work correctly, all workers need to be the same, if they are different the logic of the cluster isn't applicable (see https://12factor.net)
Secondly, if a error shutdown a worker inside the cluster, all request will be routed to the other process. In the meantime PM2 will restart another worker with the same state (env) than the old one and when it will be started it will receive request.
I don't understand why you want to implement what PM2 do by default on your own.

**Comment by markmenox** [comment]
Maybe i didn't expalin well my code/situation.
I use node.js domains to catch unhandled errors in my application. Inside of this handler i use a setTimeout function with a timing of 30 seconds. When code of setTimeout callback is called i call process.exit(1). The problem is that for 30 seconds that process doesn't accept http requests anymore and i would like to have another one spawned.

  domain.on('error', function(domainErr) {

  var worker = require('cluster').worker;
// disconnect from the cluster
          if (worker) {
            worker.disconnect();
          }

          // failsafe shutdown
          // make sure we close down within 30 seconds
          var killtimer = setTimeout(function() {
            logger.info(
              'Process: ' + worker.id +
              ', is going to exit'
            );

              // Everything is done: Exit process now!
              process.exit(1);
            });
          }, 30000);

});

**Comment by vmarchaud** [comment]
Since your worker aren't identical you have no way to do this with `pm2 scale`, you'll need to use the PM2 API to spawn a process with the same environment as the one that died. But i advised you to make all worker identical.

**Comment by markmenox** [comment]
I dodn't understand. What do you mean by "make all worker identical" ? What do i have to do exactly? thank you

**Comment by vmarchaud** [comment]
Each worker should have strictly the same behavior (all should be used to respond to http request) to work at their best (see https://12factor.net/processes), there are no other solution to refactor your codebase to respect it.
You can still make it work without but we will not maintain your special use-case.

**Comment by markmenox** [comment]
I still can't understand. I mean, the only thing i would like is a way to do the same thing that pm2 reload does, but within the logic of my app.js when i catch an uncaught exception with node domains

**Comment by soyuka** [comment]
@markmenox your needs are too specific. In your case, I'd use my own cluster implementation (nodejs/cluster) and start it from pm2 in fork mode. That way, you'll have full control over your workers. You'll lose the reload feature, but you should be able to implement some kind of reload on your own based on the signals received by the master process.

**Comment by vmarchaud** [comment]
What i was trying to explain is that its better for you to implement the cluster mode of [nodejs](https://nodejs.org/dist/latest-v6.x/docs/api/cluster.html#cluster_how_it_works) yourself.
