### ISSUE TITLE
2 process after reboot rather than 1

### ISSUE THREAD

**Issue by aydarcreatiestripe** [Unitech/pm2#2352]
#### Steps to reproduce

pm2 start server.js
pm2 startup
pm2 save
pm2 list
...1 process
sudo reboot

#### Expected behaviour

1 process

#### Actual behaviour

2 processes

Why there are 2 processes, i tried different ways and killed second but after reboot pm2 starts 2 processes...

**Comment by tjsail33** [comment]
What type of startup script are you using? I've seen this behavior recently using Systemd/PM2/Puppet

**Comment by aydarcreatiestripe** [comment]
what you mean by startup script ?
i already choice forever service, it works perfect
