### ISSUE TITLE
Schedule...

### ISSUE THREAD

**Issue by lagden** [Unitech/pm2#2355]
I propose a new feature for **pm2**...

The `Schedule`

Sometimes I need setup some application to self destroy or self start!
Well, my scripts solves the problem, but I'd wish one command to make that, something like this: `pm2 --schedule <date> <cmd>`

Example: `pm2 --schedule "2016-09-01 12:00:15"  "stop myApp"`

🍻

**Comment by Unitech** [comment]
Thanks for the suggestion, you may want to have a look at the *cron* feature (*cron_restart* http://pm2.keymetrics.io/docs/usage/application-declaration/#control-flow)

**Comment by lagden** [comment]
I was taking a look...

The `kill_timeout` will kill all apps?
It's possible setup this option in the`ecosystem.json` file?

**Comment by vmarchaud** [comment]
like wrote, `kill_timeout` is the timeout between a SIGINT (asking for a shutdown to the process) and a SIGKILL (this one will kill directly the process), its interesting only if your app is taking a long time to shutdown. And all options in the `application-declaration` documentation need to be put into a `ecosystem.json` file, thats the aim of this section.

**Comment by lagden** [comment]
Tks!
