### ISSUE TITLE
Question: cluster mode and healthcheck for zero downtime during deployment

### ISSUE THREAD

**Issue by ruXlab** [Unitech/pm2#2357]
pm2 cluster mode is extremely powerful feature but it doesn't allow to set any specific health check.

The problem with ```pm2 restart all``` is pm2 detects that app has been started but app isn't ready to work yet. Database connection might be not established yet, cache hasn't prepared, etc..

Right now I've got this solution: run few app instances in **fork_mode** binding them to different ports and then restart one by one, checking that healhcheck endpoint says that app is ready.

What are known workaround for this?

**Comment by vmarchaud** [comment]
@ruXlab You've got issue #2353 that explain how to do this, currently working only on fork mode but will try to make it available in cluster mode in the next days.
