### ISSUE TITLE
Stopped get expanded error that show me the specific line that the error occoure.

### ISSUE THREAD

**Issue by roysG** [Unitech/pm2#2361]
**I am getting error:** 

MongoError: Cannot apply $addToSet to a non-array field. Field named 'action' has a non-array type String in the document _id: ObjectId('56eeafd55b25afc24f705b65')
    at Function.MongoError.create (/var/www/xx/public_html/server/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/var/www/xx/public_html/server/node_modules/mongodb/lib/utils.js:114:22)
    at /var/www/xx/public_html/server/node_modules/mongodb/lib/collection.js:1042:67
    at /var/www/xx/public_html/server/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:430:18
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback (node.js:390:13)
Exception MD5 identifier : feb8ac78c74b6e11279dad8599079afc

The problem is that if you will see, i did not get specific line and file that the error was.
For example in the past i also was the line:

(/var/www/xx/public_html/server/node_modules/chat.js:31:11) -  this line was show me where the bug is.
Now i do not have it.
I do not know if if connect to your plugin, but it will be appricate if someone will tell me why the important line has gone?!

node: 4.4.4
mongoDB: 2.2.8
pm2: last version
pmx: last verion

**Comment by vmarchaud** [comment]
PM2 just write the standard output and error stream directly into the logs file in `~/.pm2/logs/`, your problem doesnt not come from PM2.
