### ISSUE TITLE
How to not run a script forever

### ISSUE THREAD

**Issue by jonathan-kosgei** [Unitech/pm2#2362]
Use case:
Have pm2 monitor a package.json or composer.json or requirements.txt .

If there're any changes to the files, then restart my app; where my app is a shell script with a single command, either `npm install` , `composer install` or `pip install -r requirements.txt`.

Catch:
On actually trying this I find that, the bash script is restarted continuously 15 times then the restarts stop, upon adding sleep 1 the command is run over and over again. Upon adding autorestart: false to the app's config the script runs only once and doesn't respond to changes to the files.

I need for pm2 to watch a file and only if there're changes to the file run the app and exit, in this case the app is a bash script.

**Comment by vmarchaud** [comment]
Refer to [our documentation](http://pm2.keymetrics.io/docs/usage/application-declaration/#control-flow) specially `autorestart` options and [watch options](http://pm2.keymetrics.io/docs/usage/watch-and-restart/#auto-restart-apps-on-file-change). You should be able to do that pretty easily with a little configuration.
