### ISSUE TITLE
Fork mode and script not running

### ISSUE THREAD

**Issue by zelin** [Unitech/pm2#2363]
I am trying to run a node script using 
pm2 start city.js 
It used to work fine until i installed forever. Even then it was working fine, but today its giving an error
#### Expected behaviour

The script should start running
...
#### Actual behaviour

App is stuck at 

pm2 start city.js
[PM2] Starting city.js in fork_mode (1 instance)
...
#### Steps to reproduce

Just trying to start a script
...
#### Software versions used

```
OS         :
node.js    : v6.4.0
PM2        :  pm2 -v
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
2.0.7
```
#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
...
```

cf CONTRIBUTING.md for more informations

**Comment by vmarchaud** [comment]
@zelin Could you try updating pm2/node to latest version and check your log in `/root/.pm2/logs/` dir and `/root/pm2.log` file ? Thanks.

**Comment by vmarchaud** [comment]
No update, closing.

**Comment by tamitutor** [comment]
Ping...I'm having this same problem.  Just upgraded my Ubuntu to 16.04 Xenial

**Comment by vmarchaud** [comment]
Please check the logs of your app and PM2 (under `~/.pm2/` folder) and report it there.
