### ISSUE TITLE
Unable to start the service of pm2 in nodejs@4.5.0

### ISSUE THREAD

**Issue by Chandler0415** [Unitech/pm2#2368]
If reporting a bug, please use the following template.

#### Expected behaviour

...

#### Actual behaviour

...

#### Steps to reproduce

...

#### Software versions used

```
OS         :
node.js    :
PM2        :
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
...
```

cf CONTRIBUTING.md for more informations

**Comment by Unitech** [comment]
I do not get it, could you please tell me the step to reproduce the issue,

Closing for now
