### ISSUE TITLE
I can't install logrotate

### ISSUE THREAD

**Issue by zhengnz** [Unitech/pm2#2369]
If reporting a bug, please use the following template.

#### Expected behaviour

...

#### Actual behaviour
```
Error: Cannot find module '/root/.pm2/node_modules/pm2-logrotate/package.json'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at startModule (/usr/local/lib/node_modules/pm2/lib/API/Modules/Modularizer.js:32:22)
    at /usr/local/lib/node_modules/pm2/lib/API/Modules/Modularizer.js:146:9
    at /usr/local/lib/node_modules/pm2/lib/Configuration.js:108:14
    at FSReqWrap.oncomplete (fs.js:82:15)
```

#### Steps to reproduce

pm2 install pm2-logrotate

#### Software versions used

```
OS         : CentOS Linux release 7.2.1511 (Core)
node.js    : 4.4.5
PM2        : 2.0.7
```

**Comment by Unitech** [comment]
Could you install the latest NPM and tell me if that works?

```
$ npm install npm -g
```

**Comment by vmarchaud** [comment]
No update since, we assume this is working now, please tell us if it isnt the case

**Comment by MonkeyDo** [comment]
With the latest version of NPM installed, this is still failing for me on a 64-bit windows 10 machine.
This is the output after running `pm2 install pm2-logrotate`

```[PM2][Module] Installing module pm2-logrotate
[PM2][Module] Calling [NPM] registry...
Error: EEXIST: file already exists, mkdir 'C:\Users\Flow'
    at Error (native)

[PM2][Module] Module downloaded
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\Flow Marine\.pm2\node_modules\pm2-logrotate\package.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at startModule (C:\Users\Flow Marine\AppData\Roaming\npm\node_modules\pm2\lib\API\Modules\Modularizer.js:32:22)
    at C:\Users\Flow Marine\AppData\Roaming\npm\node_modules\pm2\lib\API\Modules\Modularizer.js:146:9
    at C:\Users\Flow Marine\AppData\Roaming\npm\node_modules\pm2\lib\Configuration.js:108:14
    at FSReqWrap.oncomplete (fs.js:123:15)
```


```
node version: 6.9.1
npm version: 4.0.3
pm2 version: 2.1.6
```

Would you kindly reopen the issue?

**Comment by MonkeyDo** [comment]
There is a space in the user name/path. Could that be the source of the issue?

**Comment by vmarchaud** [comment]
@MonkeyDo Please nuke your pm2 installation : `rm -rf ~/.pm2/` and retry. I don't have any issue on windows with the exact same version.

**Comment by MonkeyDo** [comment]
Well, no `rm` on windows, but I did nuke the {User}/.pm2/ folder, rebooted, reinstalled pm2 and tried to install pm2-logrotate.
Same error message.

I tried the install process above on another machine running the same OS image with no problem.
One clear difference between the two is the user name. On the failing machine the user name has a space in it.

I get this error message at the beginning of the module install process:
```
Error: EEXIST: file already exists, mkdir 'C:\Users\Flow'
    at Error (native)
```
Flow is not the user name, but rather Flow Marine, with a space.
I don't see any reason why you would want to create the Users/Flow/ directory, and conclude the space in the user name is throwing a spanner in the works…

**Comment by MonkeyDo** [comment]
Installing in development mode, directly from a directory works:

`c:\Users\Flow Marine\node_modules\pm2-logrotate>pm2 install .`

Installed the module correctly, in development mode.

**Comment by vmarchaud** [comment]
Sadly can't help you much here, we spawn a process [here](https://github.com/Unitech/pm2/blob/master/lib/API/Modules/Modularizer.js#L111) with the path in parameters, i guess since we spawn the process in a shell (due to compatibility problem with Windows) the space is parsed as a different arguments. We don't handle this part so for now you'll need to install the module like this.

**Comment by MonkeyDo** [comment]
Thanks, you put me on the right track !

On Windows, to get a safe path without spaces, you can use `dir /X` in a prompt.

I then used said path to change my PM2_HOME env variable from `C:\Users\Flow Marine\.pm2` like such:
`set PM2_HOME=C:\Users\FLOWMA~1\.pm2``

Installation of module works as expected now.

I don't remember setting that PM2_HOME variable myself; perhaps there is a way to get such a safe path when it is originally set by PM2?

**Comment by vmarchaud** [comment]
`PM2_HOME` is by default `~/.pm2/` so it depend on which user spawn the daemon the first time.
