### ISSUE TITLE
PM2 deployable to self hosting VM?

### ISSUE THREAD

**Issue by scheung38** [Unitech/pm2#2373]
If reporting a bug, please use the following template.

#### Expected behaviour

...

#### Actual behaviour

...

#### Steps to reproduce

...

#### Software versions used

```
OS         :
node.js    :
PM2        :
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
...
```

cf CONTRIBUTING.md for more informations

**Comment by Unitech** [comment]
Sure you can do `pm2 deploy` and deploy anywhere you want.

Check this: http://pm2.keymetrics.io/docs/usage/deployment/
