### ISSUE TITLE
debug module incorrectly initialized in cluster mode

### ISSUE THREAD

**Issue by eloquence** [Unitech/pm2#2374]
#### Expected behaviour

I'd like to add debug messages to my error log in development mode, using the widely used `debug` module, which pm2 itself also uses.

#### Actual behaviour

In cluster mode, the debug module is initialized prior to my app loading it. My app retains a reference to it in a state where all namespaces are disabled, regardless of the DEBUG environment variable.

I can work around this by invalidating the require cache for the debug module before I use it, but that behavior seems like a bug to me, unless the error is on my part. What's noticeable is that if I switch from cluster to fork mode, the module functions as expected.

#### Steps to reproduce

Set your DEBUG environment variable, e.g., via export DEBUG=*

Run an app that depends on the debug module in pm2's cluster mode.

Examine the .skips and .names properties of the object exported by the debug module -- they are empty arrays, when names should be set to `[ /^.*?$/ ]` after initialization (or another regex depending on the value of DEBUG).

#### Software versions used

```
OS         : Ubuntu 16.04
node.js    : 4.5.0
PM2        : 1.1.3
```

My app is fully open; the process.json I'm using is here:
https://github.com/eloquence/lib.reviews/blob/master/process.json

**Comment by vmarchaud** [comment]
Can you try using the latest version of pm2 ? `npm install pm2@next -g`

**Comment by eloquence** [comment]
I can confirm that this is no longer an issue with pm2@next (2.0.7 as of this writing).

**Comment by vmarchaud** [comment]
Closing so, pm2 v2 will be release in the following weeks.
