### ISSUE TITLE
Keymetrics: Multiple servers under same IP not displaying well

### ISSUE THREAD

**Issue by Tomino2112** [Unitech/pm2#2376]
In our setup we have autoscaling group of identical servers, all set to report to keymetrics. All works great, only in keymetrics all servers appear as one and "flick" between each other.

At the top of dashboard you can see:

```
Server #1 - ip-172-32-16-15 (ip: ::ffff:52.49.247.9) (hostname: ip-172-32-17-176)
```

All servers will have IP same, but you can see the hostname and firther stats about each server changing.

Would be great if you can work around this and we could see list of all servers.

Bucket id: 577a812fd08ea4b43bce4097

**Comment by Tomino2112** [comment]
PS: ignore number of server errors etc, we are testing failover scenarios

**Comment by vmarchaud** [comment]
@Tomino2112 Please use the keymetrics zendesk to report this kind of problem (we will answer you over there). If you dont see it, try disabling adblocker/ghostery.
