### ISSUE TITLE
`pm2 startup` does not work on RHEL 7

### ISSUE THREAD

**Issue by lewellyn** [Unitech/pm2#2377]
#### Expected behaviour

`pm2 startup` should generate a working systemd service on RHEL 7, without further arguments.
#### Actual behaviour

On Red Hat Enterprise Linux 7.2, it seems that without any arguments to `pm2 startup`, it thinks the OS is Debian-esque:

```
# pm2 startup

                        -------------

   Looking for a complete monitoring and management tool for PM2?
    _                             _        _            _
   | | _____ _   _ _ __ ___   ___| |_ _ __(_) ___ ___  (_) ___
   | |/ / _ \ | | | '_ ` _ \ / _ \ __| '__| |/ __/ __| | |/ _ \
   |   <  __/ |_| | | | | | |  __/ |_| |  | | (__\__ \_| | (_) |
   |_|\_\___|\__, |_| |_| |_|\___|\__|_|  |_|\___|___(_)_|\___/
             |___/

                          Features

                   - Real Time Dashboard
                   - CPU/Memory monitoring
                   - HTTP monitoring
                   - Event notification
                   - Custom value monitoring
                   - Real Time log display

                          Checkout

                   https://keymetrics.io/

                        -------------

[PM2] Spawning PM2 daemon
[PM2] PM2 Successfully daemonized
[PM2] Generating system init script in /etc/init.d/pm2-init.sh
[PM2] Making script booting at startup...
[PM2] -linux- Using the command:
      su -c "chmod +x /etc/init.d/pm2-init.sh && update-rc.d pm2-init.sh defaults"
Command failed: su -c "chmod +x /etc/init.d/pm2-init.sh && update-rc.d pm2-init.sh defaults"
bash: update-rc.d: command not found


----- Are you sure you use the right platform command line option ? centos / redhat, amazon, ubuntu, gentoo, systemd or darwin?
```

If one attempts to run `pm2 startup systemd` (as RHEL 7 uses systemd), this appears to work, though the service is left running while the `pm2 startup systemd` output indicates it should be stopped. So, I don't even really consider this a working state. 

```
# pm2 startup systemd
[PM2] Generating system init script in /etc/systemd/system/pm2.service
[PM2] Making script booting at startup...
[PM2] -systemd- Using the command:
      su root -c "pm2 dump && pm2 kill" && su root -c "systemctl daemon-reload && systemctl enable pm2 && systemctl start pm2"
[PM2][WARN] No process found
Created symlink from /etc/systemd/system/multi-user.target.wants/pm2.service to /etc/systemd/system/pm2.service.
[PM2] Saving current process list...
[PM2] Successfully saved in /root/.pm2/dump.pm2
[PM2] Stopping PM2...
[PM2] All processes have been stopped and deleted
[PM2] PM2 stopped
[PM2] Done.
# systemctl status pm2
● pm2.service - PM2 next gen process manager for Node.js
   Loaded: loaded (/etc/systemd/system/pm2.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2016-09-08 16:13:56 PDT; 4min 11s ago
  Process: 130852 ExecStart=/usr/lib/node_modules/pm2/bin/pm2 resurrect (code=exited, status=0/SUCCESS)
 Main PID: 130858 (PM2 v1.1.3: God)
   CGroup: /system.slice/pm2.service
           └─130858 PM2 v1.1.3: God Daemon

Sep 08 16:13:55 HOSTNAME systemd[1]: Starting PM2 next gen process ....
Sep 08 16:13:55 HOSTNAME pm2[130852]: [PM2] Spawning PM2 daemon
Sep 08 16:13:56 HOSTNAME pm2[130852]: [PM2] PM2 Successfully daemonized
Sep 08 16:13:56 HOSTNAME pm2[130852]: [PM2] Resurrecting
Sep 08 16:13:56 HOSTNAME pm2[130852]: [PM2] Restoring processes loc...2
Sep 08 16:13:56 HOSTNAME pm2[130852]: ┌──────────┬────┬──────┬─────…──┐
Sep 08 16:13:56 HOSTNAME pm2[130852]: │ App name │ id │ mode │ pid …g │
Sep 08 16:13:56 HOSTNAME pm2[130852]: └──────────┴────┴──────┴─────…──┘
Sep 08 16:13:56 HOSTNAME pm2[130852]: Use `pm2 show <id|name>` to g...p
Sep 08 16:13:56 HOSTNAME systemd[1]: Started PM2 next gen process m....
Hint: Some lines were ellipsized, use -l to show in full.
```
#### Steps to reproduce

`# pm2 startup`
#### Software versions used

```
OS         : Red Hat Enterprise Linux 7.2
node.js    : 6.4.0
PM2        : 1.1.3
```
#### PM2 Log output

```
2016-09-08 16:08:03: [PM2][WORKER] Started with refreshing interval: 30000
2016-09-08 16:08:03: [[[[ PM2/God daemon launched ]]]]
2016-09-08 16:08:03: BUS system [READY] on port /root/.pm2/pub.sock
2016-09-08 16:08:03: RPC interface [READY] on port /root/.pm2/rpc.sock
2016-09-08 16:13:55: PM2 is being killed via kill method
2016-09-08 16:13:55: RPC socket closed
2016-09-08 16:13:55: PUB socket closed
2016-09-08 16:13:56: [PM2][WORKER] Started with refreshing interval: 30000
2016-09-08 16:13:56: [[[[ PM2/God daemon launched ]]]]
2016-09-08 16:13:56: BUS system [READY] on port /root/.pm2/pub.sock
2016-09-08 16:13:56: RPC interface [READY] on port /root/.pm2/rpc.sock
```

**Comment by Unitech** [comment]
Systemd startup mode:

1/ create the script `/etc/systemd/system/pm2.service` with [this content](https://github.com/Unitech/pm2/blob/development/lib/templates/pm2.service)
2/ Run

```
$ pm2 dump
$ pm2 kill 
$ systemctl daemon-reload
$ systemctl enable pm2
$ systemctl start pm2
``` 

https://github.com/Unitech/pm2/blob/development/lib/API/Startup.js

Do you see anything wrong in the command flow?

**Comment by lewellyn** [comment]
The problem I see is the disconnect between what it does and what is printed to the console: The console shows the stopping, but no mention that it's being started. This violates the principle of least surprise. The least surprising outcome would be that the startup script's running state matches what's most recently printed to the console.

Additionally, why is a Debian-style init script the default especially since it seems practically everyone has jumped on the systemd bandwagon by now?

**Comment by Unitech** [comment]
Closing in favor of #2559 

To try the new startup system:

```bash
$ npm install Unitech/pm2#development -g
$ pm2 update
```

```bash
$ pm2 startup     # Then copy / paste the command displayed
$ pm2 unstartup
```

**Comment by multithreadke** [comment]
![v7](https://user-images.githubusercontent.com/16612658/29812112-3d3c6d5e-8cae-11e7-8e16-54813fb9dc8d.PNG)

![v6](https://user-images.githubusercontent.com/16612658/29812097-386e2114-8cae-11e7-819e-26f8f7ae9fe9.PNG)
Generate startup script and modify the script User as root : Make sure you enable startup by running systemctl enable pm2-**YOURHOSTNAME**
![rrr](https://user-images.githubusercontent.com/16612658/29811995-eb73e8da-8cad-11e7-80a8-f395907563a2.PNG)

Also the set soft limit and hard limit and make sure the script does not exceed the set limits
![v3](https://user-images.githubusercontent.com/16612658/29812081-2d0a6634-8cae-11e7-9ee5-de6da1af1a6e.PNG)

**Comment by multithreadke** [comment]
1. I'm running centos 
![v1](https://user-images.githubusercontent.com/16612658/29812202-813486f4-8cae-11e7-9dff-8d1e9bda8a95.PNG)

2. Set system wide limit resources [/etc/security/limits.conf]
![v3](https://user-images.githubusercontent.com/16612658/29812297-c2fcb282-8cae-11e7-9724-28baa91ca199.PNG)

3. Log in as root and generate script for start up $pm2 startup systemd

4. Modify script ~ Since the script is set to use infinity resources which will exceed the system wide resources [500, 000]
 Before modifying script
![v6](https://user-images.githubusercontent.com/16612658/29812456-4a036ffa-8caf-11e7-8b6e-5ebb051d778f.PNG)

After Modifying
![v7](https://user-images.githubusercontent.com/16612658/29812480-5d924a5a-8caf-11e7-8cff-fa0ffb32b874.PNG)

6.If you get an error like 
![vvv](https://user-images.githubusercontent.com/16612658/29812535-99793272-8caf-11e7-93c1-696c119b4be2.PNG) Go to step 7

7.Modify the user in the script to User = root and run command systemctl enable pm2-SCRIPTNAME
![rrr](https://user-images.githubusercontent.com/16612658/29812588-c62d7f1c-8caf-11e7-9adf-148cd416b638.PNG)
