### ISSUE TITLE
startup does not work with an encrypted home folder

### ISSUE THREAD

**Issue by Booom3** [Unitech/pm2#2378]
If reporting a bug, please use the following template.

#### Expected behaviour
Running "sudo pm2 startup" makes the PM2 process start during system boot and runs your process.
...

#### Actual behaviour
If you choose to install Ubuntu Server 16.04 with encrypted home directory, PM2 will error out during computer boot with "Error: EACCES: permission denied, mkdir ('/home/(user)/.pm2')"
...

#### Steps to reproduce
Install Ubuntu Server 16.04 with encrypted home directory enabled
Install PM2
Run "sudo pm2 startup"
Restart server
Server boot log should now contain "Error: EACCES: permission denied, mkdir" and the PM2 process is not started
...

#### Software versions used

```
OS         : Ubuntu Server 16.04
node.js    : 6.5.0
PM2        : 1.1.3
```

#### PM2 Log output

PM2 does not log this in its own log file from what I could see.

cf CONTRIBUTING.md for more informations

**Comment by Unitech** [comment]
Should we add something in the init script on the [Required Start directive](https://github.com/Unitech/pm2/blob/development/lib/templates/pm2-init.sh#L9)?

**Comment by Booom3** [comment]
I have no idea to be honest with you, it wasn't a crucial feature for us so I just reinstalled the server without the home folder encryption enabled and it started working just fine. I don't know how to fix it.

**Comment by Unitech** [comment]
alright,

for anyone having this issue in the future, please add some suggestions to it or else check this http://askubuntu.com/questions/604361/delay-mounts-after-encrypted-home-folder-is-ready

closing for now

**Comment by ctmackay** [comment]
I have this issue. PM2 works great if the home folder is not encrypted. If the home folder is encrypted, pm2 daemon does not launch, and processes dont start at boot. 

Help?
