### ISSUE TITLE
Status: errored on launch

### ISSUE THREAD

**Issue by troffaholic** [Unitech/pm2#2380]
Hello,

I recently switched from nodemon to pm2, but everytime I try to launch my program(s) 
(or bot in this case), they crash with `uptime: 0` and `status: errored`.

So I ran `pm2 logs` and this is the full output:
http://pastebin.com/hPembawq

Thanks in advance.

**Comment by vmarchaud** [comment]
You should check in `~/.pm2/logs/` for the complete error log.

**Comment by vmarchaud** [comment]
No answer, i presume you have found the issue in your logs so i'll close, re-open if not the case.
