### ISSUE TITLE
app version column

### ISSUE THREAD

**Issue by jcferrer** [Unitech/pm2#2382]
It would be nice to have the option to display the actual app version as defined in the package.json, as a column in the process list output table.

**Comment by MichaelIT** [comment]
+1. It will be nice ,if config file pm2.json support following setting:
```
{
  "name"            : "${name}-${version}",
  "script"          : "./bin/www"
}
```

`${name}`and`${version}` are variables in package.json file

**Comment by Unitech** [comment]
Closing in favor of #2937
