### ISSUE TITLE
Coffee-Script support is broken

### ISSUE THREAD

**Issue by nshtg** [Unitech/pm2#2384]
https://github.com/Unitech/pm2/commit/117eec1062e7d38eca77b934b6265e0b37082729

broke support for coffee-script by removing it from dependencies.

Since there is no tutorial or comment (not even in your changelog) on how to re-enable coffee-script support I suppose this is non-intentional?

To renable it you have to go into the installation folder of pm2 and install coffee-script **manually**.

If it **is** intentional, please add a note to your changelog under "Breaking Changes", because this is a breaking change!

**Comment by Unitech** [comment]
With PM2 v2 you have to now this command:

```
$ pm2 install coffeescript
```

We talked about it on this blog post: https://keymetrics.io/2016/08/24/pm2-v2-released/#pm2installtranspiler

**Comment by nshtg** [comment]
Thank you. Consider adding it in your changelog under "Breaking changes" though please. ;)
