### ISSUE TITLE
--abort-on-uncaught-exception does not produce core file when specified with node_args

### ISSUE THREAD

**Issue by restarian** [Unitech/pm2#2386]
If reporting a bug, please use the following template.

#### Expected behaviour
The node flag ----abort-on-uncaught-exception should produce a core dump in the working directory of the process which called node (or pm2), was ran.   
...

#### Actual behaviour
There is no core dump file generated anywhere.

**Comment by vmarchaud** [comment]
Are you sure that the problem doesnt come from NodeJs itself ? Did you checked in every folder for weird working directory (pm2 can change cwd sometimes) ?

**Comment by restarian** [comment]
Ya, I did a find / -iname 'core' and it returned nothing. It is fairly
important guys. Maybe I can diagnose the problem if it is recognized as a
bug here.

**Comment by vmarchaud** [comment]
@restarian Would accelerate a potential fix if you could provide us a way that reproduce (with all needed files), so we could find out exactly the way to fix it.

**Comment by Unitech** [comment]
When you use the raw node binary to start your application with the --abort-on-uncaught-exception, does it works?

Looks like this option need some OS configuration to make it works

**Comment by restarian** [comment]
Ok, there's egg on my face. ..chalk it up to unfamiliarity with your platform and/or haste, but now I am getting a core file produced where it should be. I guess this is my waste of time, sorry. 
Oh and, good work guys. I shall try this one out in production myself and we will see if it proves valuable.
