### ISSUE TITLE
JSON-schema for process config files

### ISSUE THREAD

**Issue by epoberezkin** [Unitech/pm2#2387]
As part of it, validation based on the [non-standard schema](https://github.com/Unitech/pm2/blob/master/lib/API/schema.json) could be switched to JSON-schema

**Comment by vmarchaud** [comment]
Our current schema is simply working fine and its not really needed to adopt a standart schema validation, so currently thats not planned.

**Comment by ulrichb** [comment]
Having a "standard" schema (available at http://schemastore.org/json/) would enable IDE completion in ecosystem.json files in IDEs like [WebStorm](https://www.jetbrains.com/help/webstorm/json.html#ws_json_using_schemas)  or [VS Code](https://code.visualstudio.com/docs/languages/json#_json-schemas-and-settings).

This would be really helpful. So +1.

**Comment by NickBolles** [comment]
@vmarchaud I'm not sure you understood this issue. It's a request for a [JSON Schema](https://json-schema.org/) defintion for the pm2.json file to assist with auto completion.

It involves creating a "$schema" key in your json and pointing it to the schema for the json - https://json-schema.org/understanding-json-schema/reference/schema.html

+1

**Comment by keyiis** [comment]
I really need this feature!

**Comment by vaaski** [comment]
[edosssa/pm2-config](https://github.com/edosssa/pm2-config) works great for vscode
