### ISSUE TITLE
[idea/feature] Provide watch_folders option for processes.json

### ISSUE THREAD

**Issue by lteacher** [Unitech/pm2#2389]
Hello,

I have recently started working with a project which introduced me to PM2. The thing is that there are about 5+ apps in the process json, and all the watch folder paths were incorrect so some people didn't use it because _'watching didn't work'_. Of course I fixed the watches but the thing is that there are specific folders to watch and some to ignore so just setting watch to `true` is no good. Then with all of the apps watching on given folder paths pm2 will often crash due to memory issues etc.

Well I would just like to ask if it would be nice to have an additional `watch_folders` option which can be used in conjunction with watch true/false. This is quite helpful to allow configuring the processes to all be watch false for a given set of folders and then enabled with `pm2 restart <process-name> --watch` and then the watch will hit the folders specified in the config. I have this change in a fork and it is quite beneficial. To add to the reasoning for the folders, note that the apps are actually sharing some common code as well which is outside of the 'current' folder of the started app so the watch folder paths are essential.

I hope my question / description was relatively clear. [Here is the option I am referring to](https://github.com/lteacher/pm2/blob/30393a59c6085df5163f3e397e0f172642c5113b/lib/Watcher.js#L37)

**Comment by soyuka** [comment]
You can just give the "folders" or directories you want to `watch` and it'll work exactly the same.

For example:

`watch: ['dir/one', 'dir/two']`

**Comment by lteacher** [comment]
Yeah its true, but it does enable the watch then you need to disable for all and enable each so with this you can set them all false on startup but know that enable will set true then sub in the req folders

**Comment by soyuka** [comment]
Sorry I didn't understood your comment, can you provide an illustrated use case as example? (with fake commands/fake json files so that I can understand your need). Thx!

**Comment by lteacher** [comment]
Sure,

So there is some project which has a structure like:

```
api
-- app1 // is node app here
---- lib
---- src
---- test
---- index.js
-- app2 // and again here
---- lib
---- ... // Assume same as above
ui-client
-- app3 // again apps here
-- app4
common
-- shared // some shared modules used in some apps
scripts
-- app5 // etc....
```

Then given the following `processes.json` (though not fully complete just for example):
```json
{
  "apps": [{
    "name": "app1",
    "cwd": "./api/app1",
    "script": "index.js",
    "instances": 1,
    "exec_mode": "fork",
    "merge_logs": true,
    "watch": ["lib", "src", "../../common"],
    "max_restarts": 10000,
    "env": {
      "PORT": 3001
    }
  }, {
    "name": "app2",
    "cwd": "./api/app2",
    "script": "index.js",
    "instances": 1,
    "exec_mode": "fork",
    "merge_logs": true,
    "watch": ["lib", "src", "../../common"],
    "max_restarts": 10000,
    "env": {
      "PORT": 3002
    }
  }, {
    "name": "app03",
    "cwd": "./ui-client/app3",
    "script": "index.js",
    "instances": 1,
    "exec_mode": "fork",
    "merge_logs": true,
    "watch": true,
    "max_restarts": 10000,
    "env": {
      "PORT": 3003
    }
  }]
}
```

Then just running as `pm2 start processes.json`

What happens with this scenario is that actually all the apps have watch folders setup, at least as many as the `app1` and `app2` examples so then if started like this pm2 will eventually crash due to some gc memory issue I assume due to the excessive watching going on. 

Its possible to stop the watch per app with `pm2 stop app2 --watch 0` then restart it or even stop them all with `pm2 stop all --watch 0` but it would seem that on start, they will have the watches all enabled again even though now we don't specify any watch e.g. `pm2 start all` . I assume this is because its reinitialized from the config json.

So here, a way to get around this is that they can all be run as false with an additional optional folders / directories or whatever setting to allow disabling the watch and enabling it on the fly, something like 
```json
{
  "apps": [{
    "name": "app1",
    "cwd": "./api/app1",
    "script": "index.js",
    "instances": 1,
    "exec_mode": "fork",
    "merge_logs": true,
    "watch": false,
    "watch_folders": ["lib", "src", "../../common"],
    "max_restarts": 10000,
    "env": {
      "PORT": 3001
    }
  }, {
    "name": "app2",
    "cwd": "./api/app2",
    "script": "index.js",
    "instances": 1,
    "exec_mode": "fork",
    "merge_logs": true,
    "watch": false,
    "watch_folders": ["lib", "src", "../../common"],
    "max_restarts": 10000,
    "env": {
      "PORT": 3002
    }
  }, {
    "name": "app03",
    "cwd": "./ui-client/app3",
    "script": "index.js",
    "instances": 1,
    "exec_mode": "fork",
    "merge_logs": true,
    "watch": false,
    "max_restarts": 10000,
    "env": {
      "PORT": 3003
    }
  }]
}
```
Actually I just thought the additional option was the least intrusive. A neater way to do watching and unwatching for configured processes would be even nicer but i felt like the dual purpose boolean | array of directories threw a bit of a spanner into that when i was looking into the code.

**Comment by soyuka** [comment]
Yeah it is thanks.

So you want to be able to control the watching state and the watched paths from the configuration (or command line). I'll take a look at this!

**Comment by vmarchaud** [comment]
See #2629 we group all issue into one.
