### ISSUE TITLE
modify max_memory_restart checking interval

### ISSUE THREAD

**Issue by artofspeed** [Unitech/pm2#2391]
For now, I think the `max_memory_restart` gets checked every 30 seconds, is there a way to decrease that so PM2 can check memory more often?

Because sometimes the nodejs process increases memory so fast that the operating system will kill pm2 entirely for "out of memory", and then there's no way to restart the process without manually respawning PM2 again. So if PM2 can check it more often it would solve this issue.

Thanks for responding!

**Comment by Unitech** [comment]
```
$ PM2_WORKER_INTERVAL=1000 pm2 update
```

This will decrease the worker interval [to 1000ms](https://github.com/Unitech/pm2/blob/master/constants.js#L83)

**Comment by artofspeed** [comment]
Thanks, is it possible to specify this option in the pm2.json config file?
