### ISSUE TITLE
pm2 with cron_restart restarts process while the process is still running

### ISSUE THREAD

**Issue by rachel-benh** [Unitech/pm2#2395]
If reporting a bug, please use the following template.

#### Expected behaviour
I need to prevent restarting script if the former didn't terminate

#### Actual behaviour

The script restarts

#### Steps to reproduce

...

#### Software versions used

```
OS         :
node.js    : 4.4.0
PM2        : latest
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

PM2 App [temp] with id [1] and pid [43887], exited with code [0] via signal [SIGINT]
PM2 Starting execution sequence in -fork mode- for app name:temp id:1
PM2 App name:temp id:1 online
PM2 Starting execution sequence in -fork

I tried listening to process.on('SIGINT', function() {..}
to prevent exit if the script wan't done but it doesn't seem to enter the function.
Same for process.on('message', function(msg)

Thanks!

**Comment by Unitech** [comment]
Could you please double check that it does not enters in the SIGINT function.

Something else, increase [kill_timeout](http://pm2.keymetrics.io/docs/usage/signals-clean-restart/#customize-exit-delay)

**Comment by rachel-benh** [comment]
Hi,
thanks.
I created 
process.on('SIGINT', function() {
    process.stdout.write('received SIGINT');
...
}
And there weren't any log prints.
I already tried setting "kill_timeout": 3000

**Comment by rachel-benh** [comment]
we tried to listen to exit and that worked...
Is there a configuration to prevent pm2 from stopping running scripts?

**Comment by Yontih** [comment]
+1
Same for me, cron restarts the process while the process is still running.

**Comment by vmarchaud** [comment]
Cause the cron is running `process.exit(1)` from [inside the process](https://github.com/Unitech/pm2/blob/79ba743723131436bd049cc952e2b1f1158bc84c/lib/ProcessContainerFork.js#L25), the process itself do not receive the SIGINT. 
Feel free to make a PR to fix that.

**Comment by Yontih** [comment]
@vmarchaud it is looks like the cron is running process.exit with status code 0 not 1 ProcessContainerFork.js line 25

**Comment by vmarchaud** [comment]
@Yontih Mybad, but it doesnt change anything.

**Comment by Unitech** [comment]
Thanks for the PR @Yontih, just made some change to harden the cron workflow (restart instead of raw kill) + some tests

You can try it:

```bash
$ npm install Unitech/pm2#development -g
$ pm2 update
```

**Comment by Yontih** [comment]
@Unitech 
What if god will manage the crons (start/restart child_process) instead of every child_process to run is own cron?
For example: I have a script that I want to run everyday at 00:00, I wont be able to kill my script process because the cron will die as well and my script will never run again.

**Comment by Unitech** [comment]
Landed in latest PM2 stable

```bash
$ npm install pm2@latest -g
```

**Comment by Unitech** [comment]
@Yontih sounds interesting, PR welcome

**Comment by zackees** [comment]
Also hitting this with using cron. All python processes spawned with ProcessPoolExecutor remain alive after job completion.
