### ISSUE TITLE
Unexpected end of input - when trying to uninstall pm2-logrotate

### ISSUE THREAD

**Issue by damianof** [Unitech/pm2#2399]
If reporting a bug, please use the following template.

#### Expected behaviour
Should uninstall successfully

#### Actual behaviour
Getting error
sudo pm2 uninstall pm2-logrotate
[PM2][Module] Uninstalling module pm2-logrotate
undefined:1

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Object.Configuration.unsetSync (/usr/lib/node_modules/pm2/lib/Configuration.js:216:24)
    at uninstallModule (/usr/lib/node_modules/pm2/lib/API/Modules/Modularizer.js:165:17)
    at Object.Modularizer.uninstall (/usr/lib/node_modules/pm2/lib/API/Modules/Modularizer.js:356:3)
    at CLI.uninstall (/usr/lib/node_modules/pm2/lib/API/Modules/Modules.js:96:17)
    at Command.<anonymous> (/usr/lib/node_modules/pm2/bin/pm2:459:9)
    at Command.listener (/usr/lib/node_modules/pm2/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (/usr/lib/node_modules/pm2/node_modules/commander/index.js:615:12)

#### Steps to reproduce
sudo pm2 uninstall pm2-logrotate
...

#### Software versions used
latest
```
OS         : ubunt 14.04
node.js    : latest
PM2        : latest
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`
empty
```
...
```

cf CONTRIBUTING.md for more informations

**Comment by Unitech** [comment]
Could you show me the content of `~/.pm2/module_conf.json`

Thanks

**Comment by damianof** [comment]
The file is there, but it's blank. This machine had run out of disk space when I checked this morning because I guess the "retain" option had not set correctly and therefore too many log files were kept. I 
then deleted all the logs files under "/root/.pm2/logs/", and was able to deploy my latest app, and see the logs resume working correctly. However, when I try to either run one of these commands:
- pm2 set pm2-logrotate max_size 1MB
- pm2 set pm2-logrotate retain 3

I get the same "Unexpected end of input" error.
That is why I was trying to uninstall pm2-logrotate and re-install. I already uninstall pm2 and reinstalled. How can I manually force it to delete pm2-logrotate and reinstall it? Maybe the problem will go away if I find a way to do that.

**Comment by damianof** [comment]
One more thing, when i do pm2 list, I only see information regarding pm2 and no longer pm2-logrotate now.

**Comment by damianof** [comment]
I added a copule of console.log just before the line that throws the error (/usr/lib/node_modules/pm2/lib/Configuration.js:219):

console.log('cst.PM2_MODULE_CONF_FILE', cst.PM2_MODULE_CONF_FILE);
console.log('data', data);
  var json_conf = JSON.parse(data);
   ....

And the output is:
cst.PM2_MODULE_CONF_FILE /root/.pm2/module_conf.json
data <Buffer >

So I guess the fact that module_conf.json is blank is causing it to throw the error.

So I got the content of that file from another machine where everything is working well, and pasted into this other machine into /root/.pm2/module_conf.json and saved.
I did uninstall, and this time it worked. Here is the output:

cst.PM2_MODULE_CONF_FILE /root/.pm2/module_conf.json
data <Buffer 7b 0a 20 20 20 20 22 6d 6f 64 75 6c 65 2d 64 62 22 3a 20 7b 0a 20 20 20 20 20 20 20 20 22 70 6d 32 2d 6c 6f 67 72 6f 74 61 74 65 22 3a 20 22 74 72 75 ... >
┌─────────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────┬───────────┬──────────┐
│ App name    │ id │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem       │ watching │
├─────────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼──────────┤
│ DDScheduler │ 0  │ fork │ 11713 │ online │ 3       │ 4h     │ 0%  │ 77.2 MB   │ disabled │
└─────────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────┴───────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app


Then i did install again and seemed to have worked:

root@PROD-DDScheduler-nyc3-01:/opt/web/DDScheduler# pm2 install pm2-logrotate
[PM2][Module] Installing module pm2-logrotate
[PM2][Module] Calling [NPM] registry...
pm2-logrotate@2.0.0 ../../../root/.pm2/node_modules/pm2-logrotate
├── pmx@0.6.5 (json-stringify-safe@5.0.1, debug@2.2.0)
├── node-schedule@1.1.1 (long-timeout@0.0.2, cron-parser@1.1.0)
├── moment-timezone@0.5.5 (moment@2.15.1)
└── pm2@2.0.15 (gkt@1.0.0, filename-regex@2.0.0, set-immediate-shim@1.0.1, amp-message@0.1.2, brace-expansion@1.1.6, buffer-shims@1.0.0, array-unique@0.2.1, arr-flatten@1.0.1, arrify@1.0.1, is-primitive@2.0.0, isobject@2.1.0, escape-string-regexp@1.0.5, for-own@0.1.4, for-in@0.1.6, has-ansi@2.0.0, is-dotfile@1.0.2, is-binary-path@1.0.1, is-extglob@1.0.0, is-extendable@0.1.1, number-is-nan@1.0.0, repeat-element@1.1.2, strip-ansi@3.0.1, normalize-path@2.0.1, is-number@2.1.0, is-glob@2.0.1, is-posix-bracket@0.1.1, ansi-regex@2.0.0, anymatch@1.3.0, arr-diff@2.0.0, expand-range@1.8.2, expand-brackets@0.1.5, binary-extensions@1.6.0, kind-of@3.0.4, code-point-at@1.0.0, inflight@1.0.5, chalk@1.1.3, braces@1.8.5, fill-range@2.2.3, extglob@0.3.2, glob-base@0.3.0, is-equal-shallow@0.1.3, once@1.4.0, path-is-absolute@1.0.0, string-width@1.0.2, supports-color@2.0.0, wrappy@1.0.2, is-fullwidth-code-point@1.0.0, object.omit@2.0.0, parse-glob@3.0.4, randomatic@1.1.5, regex-cache@0.4.3, repeat-string@1.5.4, ansi-styles@2.2.1, minimatch@3.0.3, string_decoder@0.10.31, balanced-match@0.4.2, async-each@1.0.1, inherits@2.0.3, amdefine@1.0.0, fs.realpath@1.0.0, interpret@1.0.1, commander@2.9.0, escape-regexp@0.0.1, graceful-readlink@1.0.1, ms@0.7.1, process-nextick-args@1.0.7, util-deprecate@1.0.2, amp@0.3.1, core-util-is@1.0.2, eventemitter2@1.0.5, glob-parent@2.0.0, concat-map@0.0.1, is-buffer@1.1.4, graceful-fs@4.1.6, glob@7.0.6, semver@5.3.0, isarray@1.0.0, micromatch@2.3.11, pm2-deploy@0.3.1, async@1.5.2, json-stringify-safe@5.0.1, preserve@0.2.0, rechoir@0.6.2, chokidar@1.6.0, debug@2.2.0, pm2-multimeter@0.1.2, charm@0.1.2, tv4@1.2.7, cron@1.1.0, fclone@1.0.9, minimist@0.0.8, pidusage@1.0.7, sprintf-js@1.0.3, colors@1.1.2, readable-stream@2.1.5, vizion@0.2.13, readdirp@2.1.0, mkdirp@0.5.1, lazy@1.0.11, source-map-support@0.4.2, cli-table2@0.2.0, argparse@1.0.7, pm2-axon@3.0.2, source-map@0.1.32, nssocket@0.6.0, moment-timezone@0.3.1, shelljs@0.7.3, pm2-axon-rpc@0.4.5, yamljs@0.2.8, resolve@1.1.7, moment@2.15.0, lodash@3.10.1)
[PM2][Module] Module downloaded
[PM2][WARN] Applications pm2-logrotate not running, starting...
[PM2] App [pm2-logrotate] launched (1 instances)
[PM2][Module] Module successfully installed and launched
[PM2][Module] : To configure module do
[PM2][Module] : $ pm2 conf <key> <value>
┌─────────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────┬───────────┬──────────┐
│ App name    │ id │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem       │ watching │
├─────────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼──────────┤
│ DDScheduler │ 0  │ fork │ 11713 │ online │ 3       │ 4h     │ 0%  │ 77.2 MB   │ disabled │
└─────────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────┴───────────┴──────────┘
 Module activated
┌───────────────┬─────────┬────────────┬────────┬─────────┬─────┬────────────┐
│ Module        │ version │ target PID │ status │ restart │ cpu │ memory     │
├───────────────┼─────────┼────────────┼────────┼─────────┼─────┼────────────┤
│ pm2-logrotate │ N/A     │ 13296      │ online │ 0       │ 20% │ 8.891 MB   │
└───────────────┴─────────┴────────────┴────────┴─────────┴─────┴────────────┘

I guess ultimately the question is: Why the file ~/.pm2/module_conf.json got blanked out?

**Comment by vmarchaud** [comment]
first thing to do would be to try using `pm2 set pm2-logrotate:max_size 1MB` in place of `pm2 set pm2-logrotate max_size 1MB` like explained in the [readme of logrotate](https://github.com/pm2-hive/pm2-logrotate#how-to-set-these-values-). 
I think that your setting a weird configuration and that pm2 cant remove the config because of the broken json stuff like that.

**Comment by damianof** [comment]
vmarchaud thank you for catching that. I'll make sure that is the command I run.
