### ISSUE TITLE
command prompt created by pm2 

### ISSUE THREAD

**Issue by yuqinlear** [Unitech/pm2#2402]
#### Expected behaviour
suppress/hide windows created by pm2
...

#### Actual behaviour
pm2 creates the same number of windows as the processes
Based on what I read "After upgrading my pm2 to 1.0.2 I found that it wonderfully hides all annoying console windows that were popping up before (in v0.x) when launching apps"  from https://github.com/Unitech/pm2/issues/2047, it seems it was fixed. However I still have such issue.
...

#### Steps to reproduce
I tested based on the sample code from http://pm2.keymetrics.io/docs/usage/pm2-api/
...

#### Software versions used

```
OS         : windows server 2012 & windows 7
node.js    : 4.4.4
PM2        : 2.0.15
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
...
```

cf CONTRIBUTING.md for more informations

**Comment by vmarchaud** [comment]
Refer to #2182 all information are in this issue
