### ISSUE TITLE
TypeError: this.ipm2.rpc.getMonitorData is not a function

### ISSUE THREAD

**Issue by FranciscoG** [Unitech/pm2#2403]
node v4.0.0
pm2 v2.0.15

trying to link pm2 to keymetrics and i's not working

pm2 link info outputs this

```
[Keymetrics.io] Getting agent information...
Interactor is offline
```

~/.pm2/agent.log shows this everytime I try to restart it

```
[Keymetrics.io] Launching agent
2016-09-24 13:59:50: Launching Interactor exposure
2016-09-24 13:59:50: Connected to PM2
2016-09-24 13:59:51: [WATCHDOG] Launching
2016-09-24 13:59:51: [PUSH] Connecting epsilon.keymetrics.io:80
2016-09-24 13:59:51: [REV] Connecting to epsilon.keymetrics.io:43554
2016-09-24 13:59:51: [PUSH] Connected
2016-09-24 13:59:51: [REV] Connected to epsilon.keymetrics.io:43554
/usr/local/lib/node_modules/pm2/lib/Interactor/PushInteractor.js:229
    this.ipm2.rpc.getMonitorData({}, function(err, processes) {
                  ^

TypeError: this.ipm2.rpc.getMonitorData is not a function
    at Object.module.exports.preparePacket (/usr/local/lib/node_modules/pm2/lib/Interactor/PushInteractor.js:229:19)
    at Object.module.exports.sendData (/usr/local/lib/node_modules/pm2/lib/Interactor/PushInteractor.js:275:10)
    at null._repeat (/usr/local/lib/node_modules/pm2/lib/Interactor/PushInteractor.js:126:22)
    at wrapper [as _onTimeout] (timers.js:270:19)
    at Timer.listOnTimeout (timers.js:89:15)
```

**Comment by FranciscoG** [comment]
more info:

I'm running it on a Pi
```
Linux  4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l GNU/Linux

PRETTY_NAME="Raspbian GNU/Linux 7 (wheezy)"
NAME="Raspbian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=raspbian
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

```

**Comment by Unitech** [comment]
I do not manage to reproduce the error.
Tried `pm2 link <secret> <public>`, also `pm2 link info`, I haven't got this exception.

Have you upgraded recently from PM2 v1 to PM2 v2? Have you run `pm2 update`?

**Comment by Unitech** [comment]
Need more info or I close this issue

**Comment by FranciscoG** [comment]
When  I do `pm2 -v` I get `2.0.15`

I did a `pm2 update` and I still get the same version number.  I've only recently installed pm2

I've looked through [troubleshooting](http://docs.keymetrics.io/docs/pages/faq-troubleshooting/#troubleshooting-for-keymetrics-pm2) docs

> Make sure that the ports 80 (TCP outbound), 443 (HTTPS) and 43554 (TCP inbound/outbound) are open.

I made sure these ports are open

> You have concurrent PM2 sending data to the same bucket with an identical server name. Make sure you have only one PM2 instance launched ps -ax | grep PM2

There's only one process running

Do I need to do some port forwarding from my router?  The Pi has access to the internet but I can only ssh into on the local network

**Comment by Unitech** [comment]
Is is still happening on PM2 2.1.X?

**Comment by FranciscoG** [comment]
I haven't actually tried it again and I've completely abandoned that server I was having issues with and now I'm just using a Digital Ocean droplet and everything works fine now (CentOS).   Maybe it was an issue of it being on a Pi.. maybe it was an internal network issue... who knows.

**Comment by vmarchaud** [comment]
We have ourselves a raspi with pm2 running on it without problem so yeah, weird.
Closing so.
