### ISSUE TITLE
node execute shell commands: pm2 reload app-name,Parameter does not work

### ISSUE THREAD

**Issue by 8473874** [Unitech/pm2#2404]
The preferred run npm test.
the package script:
export NODE_ENV = test && pm2 start app.js --name = 'app-name'
normal work.

github commit code, webhook call api interfaces
With node execute shell commands
shell command:
pm2 reload app-name
But export NODE_ENV = test will not work.

Modify shell command:
pm2 reload process.json
normal work.

#### Software versions used

```
OS         :  CentOS Linux release 7.2.1511 (Core)
node.js    : v6.4.0
PM2        : 2.0.15
```

**Comment by vmarchaud** [comment]
Correct me if i'm wrong but what i understand here is that your old env isnt re-set when you reload your app, and thats actually a normal behavior.
If you give pm2 a json process file, it will load the env from the file, but if you only give him the name, it will get the current env and pass it to the application. It will never get the old env.

**Comment by 8473874** [comment]
Executive pm2 reload app-name in the centos.
export NODE_ENV = test is work.

**Comment by vmarchaud** [comment]
@8473874 Sorry i don't understand what you are trying to explain

**Comment by Unitech** [comment]
@8473874 if you can provide a set of commands to better understand this issue, it's welcome
