### ISSUE TITLE
pm2 v2 is crashing the app inside a try ... catch clause with async/await

### ISSUE THREAD

**Issue by magalhas** [Unitech/pm2#2406]
#### Expected behaviour

```
try {
    await asyncFunction();
  } catch (error) {
    logger.debug(error);
  }
```

This code expects that if an error is thrown inside `asyncFunction` then it's caught and logged on the `catch` clause. Starting on pm2@2 the catch clause is not executed.

#### Actual behaviour

The application logs the error in stderr and quits.

#### Steps to reproduce

Not sure if the above example is true in any scenario, did not take the time to test it out, but reverting to pm2@1 fixed the behaviour.

#### Software versions used

```
OS         : Ubuntu (Docker)
node.js    : v6.6.0
PM2        : v2.0.15
```

Also babel@6 is being used to transpile the code (async/await usage) on build time.

**Comment by Unitech** [comment]
This may be linked to the new listener "unhandledRejection"?
https://github.com/Unitech/pm2/blob/master/lib/ProcessContainer.js#L239
@soyuka

**Comment by Unitech** [comment]
pm2@2.0.17 with fix published

```bash
$ npm install pm2@latest -g
```
