### ISSUE TITLE
pm2-docker doesn't allow to pass arguments to app

### ISSUE THREAD

**Issue by targos** [Unitech/pm2#2408]
#### Expected behaviour

It should be possible to pass args using `-- -a 42` syntax.

#### Actual behaviour

The arguments are ignored.

#### Steps to reproduce

run `pm2-docker start app.js -- -a 42` with an app that accepts CLI arguments

**Comment by Unitech** [comment]
You must declare any option into a [process file](http://pm2.keymetrics.io/docs/usage/application-declaration/)

**Comment by brankol** [comment]
@Unitech If `pm2-docker` doesn't allow arguments, how would you tell it to start a particular app with `--only`?

**Comment by Unitech** [comment]
@brankol good idea, implemented
