### ISSUE TITLE
PM2 v2: Creating a rejected promise anywhere crashes worker

### ISSUE THREAD

**Issue by randomsock** [Unitech/pm2#2413]
May be related to #2406.

Just creating a rejected Promise causes the process to crash in PM2 v2.  Same code works fine directly in Node and in PM2 v1.

In this case, Node is v4.5.0.

To reproduce:

**weird.js**

	#!/usr/bin/env node

	Promise.reject(new Error('Blah'));

In PM2 v2.0.15, trace is dumped to stderr and process exits with code 1:

	random:~/dev/foo$ pm2 start --no-autorestart weird.js && pm2 logs --lines 20
	[PM2] Spawning PM2 daemon with pm2_home=/home/random/.pm2
	[PM2] PM2 Successfully daemonized
	[PM2] Starting /home/random/dev/foo/weird.js in fork_mode (1 instance)
	[PM2] Done.
	+---------------------------------------------------------------------------------------+
	¦ App name ¦ id ¦ mode ¦ pid   ¦ status ¦ restart ¦ uptime ¦ cpu ¦ mem       ¦ watching ¦
	+----------+----+------+-------+--------+---------+--------+-----+-----------+----------¦
	¦ weird    ¦ 0  ¦ fork ¦ 22212 ¦ online ¦ 0       ¦ 0s     ¦ 8%  ¦ 13.3 MB   ¦ disabled ¦
	+---------------------------------------------------------------------------------------+
	 Use `pm2 show <id|name>` to get more details about an app
	[TAILING] Tailing last 20 lines for [all] processes (change the value with --lines option)
	/home/random/.pm2/pm2.log last 20 lines:
	PM2        | 2016-09-28 22:53:17: ===============================================================================
	PM2        | 2016-09-28 22:53:17: --- New PM2 Daemon started ----------------------------------------------------
	PM2        | 2016-09-28 22:53:17: Time                 : Wed Sep 28 2016 22:53:17 GMT+0200 (CEST)
	PM2        | 2016-09-28 22:53:17: PM2 version          : 2.0.15
	PM2        | 2016-09-28 22:53:17: Node.js version      : 4.5.0
	PM2        | 2016-09-28 22:53:17: Current arch         : x64
	PM2        | 2016-09-28 22:53:17: PM2 home             : /home/random/.pm2
	PM2        | 2016-09-28 22:53:17: PM2 PID file         : /home/random/.pm2/pm2.pid
	PM2        | 2016-09-28 22:53:17: RPC socket file      : /home/random/.pm2/rpc.sock
	PM2        | 2016-09-28 22:53:17: BUS socket file      : /home/random/.pm2/pub.sock
	PM2        | 2016-09-28 22:53:17: Application log path : /home/random/.pm2/logs
	PM2        | 2016-09-28 22:53:17: Process dump file    : /home/random/.pm2/dump.pm2
	PM2        | 2016-09-28 22:53:17: Concurrent actions   : 4
	PM2        | 2016-09-28 22:53:17: SIGTERM timeout      : 1600
	PM2        | 2016-09-28 22:53:17: ===============================================================================
	PM2        | 2016-09-28 22:53:17: Starting execution sequence in -fork mode- for app name:weird id:0
	PM2        | 2016-09-28 22:53:17: App name:weird id:0 online
	PM2        | 2016-09-28 22:53:18: App [weird] with id [0] and pid [22212], exited with code [1] via signal [SIGINT]

	/home/random/.pm2/logs/weird-out-0.log last 20 lines:
	/home/random/.pm2/logs/weird-error-0.log last 20 lines:
	0|weird    | Error: Blah
	0|weird    |     at Object.<anonymous> (/home/random/dev/foo/weird.js:3:16)
	0|weird    |     at Module._compile (module.js:409:26)
	0|weird    |     at Object.Module._extensions..js (module.js:416:10)
	0|weird    |     at Module.load (module.js:343:32)
	0|weird    |     at Function.Module._load (module.js:300:12)
	0|weird    |     at Function._load (/home/random/.nvm/versions/node/v4.5.0/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
	0|weird    |     at Object.<anonymous> (/home/random/.nvm/versions/node/v4.5.0/lib/node_modules/pm2/lib/ProcessContainerFork.js:46:21)
	0|weird    |     at Module._compile (module.js:409:26)
	0|weird    |     at Object.Module._extensions..js (module.js:416:10)
	0|weird    |     at Module.load (module.js:343:32)

In PM2 v1.1.3, it does nothing as expected and exits cleanly:

	random:~/dev/foo$ pm2 start --no-autorestart weird.js && pm2 logs --lines 20
	[PM2] Spawning PM2 daemon
	[PM2] PM2 Successfully daemonized
	[PM2] Starting weird.js in fork_mode (1 instance)
	[PM2] Done.
	+-----------------------------------------------------------------------------------+
	¦ App name ¦ id ¦ mode ¦ pid   ¦ status ¦ restart ¦ uptime ¦ memory      ¦ watching ¦
	+----------+----+------+-------+--------+---------+--------+-------------+----------¦
	¦ weird    ¦ 0  ¦ fork ¦ 22524 ¦ online ¦ 0       ¦ 0s     ¦ 14.102 MB   ¦ disabled ¦
	+-----------------------------------------------------------------------------------+
	 Use `pm2 show <id|name>` to get more details about an app
	[PM2] Tailing last 20 lines for [all] processes

	PM2: 2016-09-28 22:55:27: [PM2][WORKER] Started with refreshing interval: 30000
	PM2: 2016-09-28 22:55:27: [[[[ PM2/God daemon launched ]]]]
	PM2: 2016-09-28 22:55:27: BUS system [READY] on port /home/random/.pm2/pub.sock
	PM2: 2016-09-28 22:55:27: RPC interface [READY] on port /home/random/.pm2/rpc.sock
	PM2: 2016-09-28 22:55:27: Starting execution sequence in -fork mode- for app name:weird id:0
	PM2: 2016-09-28 22:55:27: App name:weird id:0 online
	PM2: 2016-09-28 22:55:27: App [weird] with id [0] and pid [22524], exited with code [0] via signal [SIGINT]

**Comment by vmarchaud** [comment]
Could you please retry using pm2 `2.0.16` : `npm install -g pm2@next && pm2 update` ?

**Comment by randomsock** [comment]
@vmarchaud SOLVED - thanks!

	random:~/dev/foo$ pm2 --version
	[PM2] Spawning PM2 daemon with pm2_home=/home/random/.pm2
	[PM2] PM2 Successfully daemonized
	2.0.16
	random:~/dev/foo$ pm2 start --no-autorestart weird.js && pm2 logs --lines 20
	[PM2] Starting /home/random/dev/foo/weird.js in fork_mode (1 instance)
	[PM2] Done.
	+---------------------------------------------------------------------------------------+
	¦ App name ¦ id ¦ mode ¦ pid   ¦ status ¦ restart ¦ uptime ¦ cpu ¦ mem       ¦ watching ¦
	+----------+----+------+-------+--------+---------+--------+-----+-----------+----------¦
	¦ weird    ¦ 0  ¦ fork ¦ 27295 ¦ online ¦ 0       ¦ 0s     ¦ 7%  ¦ 12.5 MB   ¦ disabled ¦
	+---------------------------------------------------------------------------------------+
	 Use `pm2 show <id|name>` to get more details about an app
	[TAILING] Tailing last 20 lines for [all] processes (change the value with --lines option)
	/home/random/.pm2/pm2.log last 20 lines:
	PM2        | 2016-09-28 23:32:17: ===============================================================================
	PM2        | 2016-09-28 23:32:17: --- New PM2 Daemon started ----------------------------------------------------
	PM2        | 2016-09-28 23:32:17: Time                 : Wed Sep 28 2016 23:32:17 GMT+0200 (CEST)
	PM2        | 2016-09-28 23:32:17: PM2 version          : 2.0.16
	PM2        | 2016-09-28 23:32:17: Node.js version      : 4.5.0
	PM2        | 2016-09-28 23:32:17: Current arch         : x64
	PM2        | 2016-09-28 23:32:17: PM2 home             : /home/random/.pm2
	PM2        | 2016-09-28 23:32:17: PM2 PID file         : /home/random/.pm2/pm2.pid
	PM2        | 2016-09-28 23:32:17: RPC socket file      : /home/random/.pm2/rpc.sock
	PM2        | 2016-09-28 23:32:17: BUS socket file      : /home/random/.pm2/pub.sock
	PM2        | 2016-09-28 23:32:17: Application log path : /home/random/.pm2/logs
	PM2        | 2016-09-28 23:32:17: Process dump file    : /home/random/.pm2/dump.pm2
	PM2        | 2016-09-28 23:32:17: Concurrent actions   : 4
	PM2        | 2016-09-28 23:32:17: SIGTERM timeout      : 1600
	PM2        | 2016-09-28 23:32:17: ===============================================================================
	PM2        | 2016-09-28 23:32:30: Starting execution sequence in -fork mode- for app name:weird id:0
	PM2        | 2016-09-28 23:32:30: App name:weird id:0 online
	PM2        | 2016-09-28 23:32:30: App [weird] with id [0] and pid [27295], exited with code [0] via signal [SIGINT]

**Comment by soyuka** [comment]
Because you need to `catch` promises, or this reaches the `unhandledRejection` event.

**Comment by Unitech** [comment]
pm2@2.0.17 with fix published

```bash
$ npm install pm2@latest -g
```
