### ISSUE TITLE
call pm2.start in a for loop

### ISSUE THREAD

**Issue by yuqinlear** [Unitech/pm2#2417]
#### Expected behaviour
Because I need pass different arguments to different processes, I made a for loop to call pm2.start.
The problem is that I can not always create the expected number of processes.

```
'use strict';
var pm2 = require('pm2');
var NUMBER_OF_WORKERS = 10;
var PORT_START = 13001;

pm2.connect(function(err) {
  if (err) {
    console.error(err);
    process.exit(2);
  }

  for(let i = 0; i < NUMBER_OF_WORKERS; i++) {
    let proxyPort = PORT_START + i;
    pm2.start(
      {
        name: 'worker-' + proxyPort,
        script : 'src/foo.js',
        exec_mode : 'fork',
        force: true,
        instances : 1,
        args: [ proxyPort ]
      },
      function(err, apps) {
        console.error('the error handler is called ----------------');
        pm2.disconnect();
        if (err) {
          throw err;
        }
      });
  }
});
```

...

#### Actual behaviour
the number of started processes is less than defined NUMBER_OF_WORKERS.
"the error handler is called ----------------" will be printed out several times inconsistently.

#### Steps to reproduce
test code at foo.js: 
setInterval(function() {
  console.log(process.argv[2]);
}, 1000);

...

#### Software versions used

```
OS       windows server 2012 & windows 7  :
node.js  4.5.0  :
PM2    2.0.15 :
```

#### PM2 Log output

```

sometimes I can get the error log below, and no process will be created:

===============================================================================
--- PM2 global error caught ---------------------------------------------------
Time                 : Fri Sep 30 2016 02:12:35 GMT+0800 (China Standard Time)
This socket is closed.
Error: This socket is closed.
    at Socket._writeGeneric (net.js:648:19)
    at Socket._write (net.js:700:8)
    at doWrite (_stream_writable.js:300:12)
    at clearBuffer (_stream_writable.js:407:7)
    at onwrite (_stream_writable.js:339:7)
    at Socket.WritableState.onwrite (_stream_writable.js:89:5)
    at WriteWrap.afterWrite (net.js:781:12)
===============================================================================

```

**Comment by Unitech** [comment]
You have three solutions here. You can use async or a recursive function to call pm2.start iteratively or the third option is to generate an array of json and pass it to pm2.start

**Comment by yuqinlear** [comment]
@Unitech what is the callback function once pm2.start succeeds? just want to make sure because errback(err,proc) sounds like an error call back.

**Comment by Unitech** [comment]
Yes, this is the classical function signature
