### ISSUE TITLE
Incorrect log path handling

### ISSUE THREAD

**Issue by fayf** [Unitech/pm2#2418]
On [this page](http://pm2.keymetrics.io/docs/usage/log-management/#combine-out-and-err-logs):
> Note that relatives logs paths will usually be written in the PM2_HOME (~/.pm2/logs).

This has not been the case for me.
1. Specifying relative paths just appends the path to the cwd. 
2. If i specify `~/.pm2/logs/err.log` as the path, the logs appear in `c_w_d/~/.pm2/logs/err.log`

This applies to error, output and entire logs.

#### Expected behaviour

If a relative path is defined, it should append the defined path to PM2_HOME.

#### Actual behaviour

If a relative path is defined, it appends the defined path to the cwd.

#### Steps to reproduce

`pm2 start app.js -l all.log`
or
`pm2 start app.js -l ~/.pm2/logs/all.log`

#### Software versions used

Tried on
```
OS         : OS X El Capitan 10.11.6 (15G1004)
node.js    : 6.6.0
PM2        : 2.0.15
```
and
```
OS         : Ubuntu 14.04.3 LTS
node.js    : 4.6.0
PM2        : 2.0.15
```

**Comment by vmarchaud** [comment]
Closing in favor of #2474
