### ISSUE TITLE
PM2 restart app didn't work but pm2 delete app and then pm2 start app worked

### ISSUE THREAD

**Issue by ktkaushik** [Unitech/pm2#2421]
#### Expected behaviour
Pull the latest code from git, run `pm2 restart production` and the new application process would reflect the changes.
...

#### Actual behaviour
2 days ago, we pulled the using git and restarted our application but didn't see the new changes in our application.
...

#### Steps to reproduce
In this case, we didn't see the changes reflected with cron (using [node-cron](https://github.com/ncb000gt/node-cron)). We were initially running a single cron but after the changes we were running 2 crons. We have tested this behaviour before and it worked flawlessly. However, in this case, it didn't.

Sample code would be - 
```
var cron = new CronJob('00 00,15,30,45 * * * *', yourFunction(), null, true, 'Asia/Kolkata');    
var cron2 = new CronJob('00 00,15,30,45 * * * *', yourFunctionForAnotherAction(), null, true, 'Asia/Kolkata');    
```
...

#### Software versions used

```
OS           : **Debian 8.3**
node.js    : **Node v5.1**
PM2         : **v1.1.3**
```

#### History of comamnds

Last few commands - 

```
pm2 list
pm2 delete cron.production
NODE_ENV=production PORT=<PORT> pm2 start bin/www-cron --name cron.production --log-date-format="YYYY-MM-DD HH:mm Z" && pm2 logs cron.production
```

Please let me know if you would need more information.

Thanks.

**Comment by ktkaushik** [comment]
@shubham1208

**Comment by vmarchaud** [comment]
Please update to latest pm2 version : `npm install -g pm2 && pm2 update` and tell me if its still happening ?

**Comment by Unitech** [comment]
Fix available on pm2@next

```bash
$ npm install pm2@next -g
$ pm2 update
```
