### ISSUE TITLE
TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by fresheneesz** [Unitech/pm2#2428]
When using the node API to attempt to *stop* the daemon (using `stopDaemon`), I get a strange error about `this.Client` being undefined in `lib/API.js`. I inserted some console log debugging and found that when `this.Client` is set in API.js (with the `new` operator), it seems correctly defined as an object. But when it gets into `API.prototype.connect`, `this.Client` is at that point undefined. What could cause this?

#### Expected behaviour

No error or some readable/understandable error.

#### Actual behaviour

TypeError: Cannot read property 'start' of undefined
 at API.connect (/root/temporaryPackageFolder/node_modules/pm2/lib/API.js:135:14)

#### Steps to reproduce

...

#### Software versions used

```
OS          : Centos 6
node.js    : 5.1.0
PM2        : 2.0.18
```

#### PM2 Log output

N/A - no relevant logs from the day.

**Comment by vmarchaud** [comment]
Could you please share with us how you are using the API ?

**Comment by fresheneesz** [comment]
Unfortunately, my script is pretty complex, so no. But I'm going to debug through it today. I'll add more info with what I find.

**Comment by fresheneesz** [comment]
Ok, looks like I updated my pm2 and a change was made where the context (bound  `this`) started mattering. I changed my code to fix the issue.
