### ISSUE TITLE
Sourcemaps in production?

### ISSUE THREAD

**Issue by Anomen** [Unitech/pm2#2430]
Hi Team!

I was wondering what is the impact of enabling the sourcemaps in production? Any significant overhead? 
What are your advice on it?

Thanks
Kevin

**Comment by soyuka** [comment]
Do you need source maps in production ? Are you talking about source maps on the server side ?

**Comment by Anomen** [comment]
Yes, say I transpile my code (ES6 for instance, with babel) to run with nodejs on the server side. If I get error logs in production, I would like to be able to read what's wrong with the actual original source files, so they makes sense for debugging.

**Comment by soyuka** [comment]
yeah this makes sense. Do you have a prototype working with sourcemaps yet? I won't think it's much overhead (especially if embed). Still, I'm not sure how nodejs interpret those.

**Comment by Unitech** [comment]
Sourcemap are enabled by default when you start a node app with PM2. I do not think there is any overhead at all, as the source map equivalence is done when exception arise.

You can use `--disable-source-map` to disable source maps

Documentation: http://pm2.keymetrics.io/docs/usage/source-map-support/
Source map module used: https://github.com/Unitech/pm2/blob/master/package.json#L174
Tests: https://github.com/Unitech/pm2/blob/master/test/bash/source_map.sh

**Comment by soyuka** [comment]
Wow great, wasn't aware of that! Thanks @Unitech!
