### ISSUE TITLE
Starting pm2 via runit?

### ISSUE THREAD

**Issue by jsumners** [Unitech/pm2#2431]
I am attempting to launch pm2 via [runit](http://smarden.org/runit). In the simplest case, the startup script is:

```bash
#!/bin/bash
exec pm2 --no-daemon
```

However, that doesn't work. The process keeps getting respawned over and over, and nothing is written to my log file (via runit's `svlogd`). Further, if I simply run `pm2 --no-daemon` I see that `~/.pm2/pm2.pid` is not created. So I can't add extra scripts to tell runit the process is okay by checking for the pid file and pid.

So, how do I get pm2 (v2.0.18) running via runit?

**Comment by vmarchaud** [comment]
That's because if you run with `--no-daemon`, pm2 will not spawn process so that's pretty logic that no pid file is created and the only log will be outputed in `stdout `& `stderr`.

**Comment by jsumners** [comment]
Uh, what? pm2 *is* the process. And yes, the log is captured from `stdout`. But when the process continually doesn't run then there isn't anything being written to `stdout`.

**Comment by jsumners** [comment]
Additionally, https://github.com/Unitech/pm2/blob/master/lib/Client.js#L71 indicates that it *should* be writing a pid file when launched with `--no-daemon`.

**Comment by soyuka** [comment]
This should work, I think we're doing the same with Docker (`--no-daemon`). Nothing written in `~/.pm2/pm2.log` either? Can you try `exec node pm2`? Is the `runit` user the same as the user who runs the script?

**Comment by jsumners** [comment]
Okay, here we go. `pm2` is crashing under the `runit` service. And `pm2` is writing crashes to `stderr`, so `stdout` wasn't getting them. So, modifying the service script a little:

```bash
#!/bin/bash
exec 2>&1
exec pm2 --no-daemon
```

Yields:

```
[PM2][Initialization] Environment variable HOME (Linux) or HOMEPATH (Windows) are not set!
[PM2][Initialization] Defaulting to /etc/.pm2
/usr/local/lib/node_modules/pm2/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/etc/.pm2'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at sync (/usr/local/lib/node_modules/pm2/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/usr/local/lib/node_modules/pm2/node_modules/mkdirp/index.js:77:24)
    at Client.initFileStructure (/usr/local/lib/node_modules/pm2/lib/Client.js:127:10)
    at new module.exports (/usr/local/lib/node_modules/pm2/lib/Client.js:37:8)
    at new module.exports (/usr/local/lib/node_modules/pm2/lib/API.js:96:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/pm2/bin/pm2:19:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

Which tells me to modify my service script again:

```bash
#!/bin/bash
export HOME=/home/theuser
exec 2>&1
exec pm2 --no-daemon
```

Voila! `pm2` actually runs and `~/.pm2/pm2.pid` is created.

**Comment by soyuka** [comment]
:) nice, you may also customize `PM2_HOME` instead of `HOME` if needed.
