### ISSUE TITLE
Unable to install pm2

### ISSUE THREAD

**Issue by uthaman** [Unitech/pm2#2432]
If reporting a bug, please use the following template.

#### Expected behaviour
Install pm2
...

#### Actual behaviour
Not able to install pm2
...

#### Steps to reproduce
npm install pm2 -g
...

#### Software versions used

```
OS         : Windows 7 64 bit
node.js    : v4.3.0
PM2        : latest
```

#### PM2 Log output
npm ERR! fetch failed http://tgz.pm2.io/gkt-1.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with statu
s code 401
Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
...
```

cf CONTRIBUTING.md for more informations

**Comment by vmarchaud** [comment]
Please refer to answer on #2410 : `npm i pm2@latest --no-optional -g --no-shrinkwrap`.
