### ISSUE TITLE
pm2 watch doesn't work with interpreter.

### ISSUE THREAD

**Issue by Sraw** [Unitech/pm2#2434]
I was using babel-node to launch my app, so I config my pm2 with the following json:
```
{
  "apps" : [{
    "name"        : "xxxxxxx",
    "script"      : "./index.js",
    "watch"       : true,
    "exec_interpreter" : "babel-node",
    "exec_mode"        : "fork",
  }]
}
```

#### Expected behaviour

When I change the index.js, the app could restart automatically so I can see the changes in the browser.

#### Actual behaviour

Nothing happened.

#### Software versions used

OS         : Ubuntu 16.04
node.js    : v4.5.0
PM2        : 2.0.18
npm        : 2.15.9
babel      : 6.14.0
```
Use the command: `pm2 start pm2 pm2_config.json 
```

**Comment by soyuka** [comment]
This does work to me.

**Comment by vmarchaud** [comment]
Maybe that that come from the fact that your command isnt right ? Try with `pm2 start pm2_config.json`.

**Comment by Sraw** [comment]
@vmarchaud There are some problems with my system. So I hope I could confirm whether it works or not as soon as possible. Anyway thanks a lot.

**Comment by Sraw** [comment]
@vmarchaud It seems work! But another problem occurs.
No matter how I change the listening port, the pm2 gives me an error:
```
Error: listen EADDRINUSE :::3001
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at Server._listen2 (net.js:1250:14)
    at listen (net.js:1286:10)
    at Server.listen (net.js:1382:5)
    at EventEmitter.listen (/x/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/x/index.js:37:5)
    at Module._compile (module.js:409:26)
    at loader (/x/node_modules/babel-cli/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) (/x/node_modules/babel-cli/node_modules/babel-register/lib/node.js:154:7)
events.js:141
      throw er; // Unhandled 'error' event
      ^
```
It seems that the port has been used, but I can promise it hasn't. When I just use `babel-node index.js` to run the application, everything is perfect.

**Comment by vmarchaud** [comment]
Can't help you much here, check that pm2 has started only one application maybe ?

**Comment by Sraw** [comment]
@vmarchaud Oops, finally I found the problem is caused by that pm2 was watching the log directory. So pm2 always tries to restart the application. 
Now it works perfectly, `pm2 start pm2_config.json` really solves the problem. Thank you very much.
btw, maybe #2427 is also caused by the similar reasons.

**Comment by vmarchaud** [comment]
@Sraw No problem ;)
