### ISSUE TITLE
pm2 deploy doesn't get recent updates

### ISSUE THREAD

**Issue by benishak** [Unitech/pm2#2436]
PM2 @ 2.0.18

when I deploy new changes, pm2/git doesn't get the recent changes I need to login to the server and pull the changes manually issuing `git pull origin mybranch`

On bitbucket I can see the my last commit
To fix this problem I had to remvoe the folder and run `pm2 deploy .... setup` again, but when I do some changes and need to deploy them, it stucks in same commit which was at the time pm2 cloned the git repo

Is it pm2 or git issue?
if it is issue with git, why when I login to server and go to the directory where my project located and type `git pull ...` it gets the recents updates but when I type `pm2 deploy env` on my local machine, pm2/git doesn't pull the new commits

**Comment by benishak** [comment]
I fixed this issue by updating git to latest version on the remote server. I don't know why this happened before this never happened before even using the same version of git. but updating git fixed the issue .... I'm using CentOS and had to install IUS Packages to get `git 2.10.x`. CentOS only come with old release and latest was version 1.8.x

**Comment by benishak** [comment]
i leave this issue open for feedback

**Comment by Soulwest** [comment]
I have same problem with git 1.8.x on Centos 7. Installing from sources git 2.0.5 helped me.

**Comment by vmarchaud** [comment]
Might come from the fact that we spawn git command [here](https://github.com/keymetrics/vizion/blob/master/lib/git.js#L153) and it might doest work with older version. Sadly i dont think we will support it one day.

**Comment by Unitech** [comment]
closing in favor of #2533
