### ISSUE TITLE
pm2 fail to install from a private registry

### ISSUE THREAD

**Issue by yinrong** [Unitech/pm2#2437]
pm2 fail to install from a private registry (installing host can NOT connect to npmjs.org).

#### Expected behaviour
pm2 is only package not working among all npm packages. please standardlize pm2 install procedure which mean do not try to connect any website.

#### Actual behaviour

...

#### Steps to reproduce
```
npm set registry http://any.com
npm i pm2
# pm2 will still try to connect to registry.npmjs.org
...

#### npm log

```
$ npm i -g pm2 --verbose
npm info it worked if it ends with ok
npm verb cli [ '/home/admin/.local/4.5/bin/node',
npm verb cli   '/home/admin/.local/4.5/bin/npm',
npm verb cli   'i',
npm verb cli   '-g',
npm verb cli   'pm2',
npm verb cli   '--verbose' ]
npm info using npm@3.2.2
npm info using node@v4.5.0
npm verb request uri http://npm.jd.com/pm2
npm verb request no auth needed
npm info attempt registry request try #1 at 3:44:58 PM
npm verb request id 1da5af1336590c26
npm verb etag "5d017d8b7509dae27c84985dec6e2dd4"
npm http request GET http://npm.jd.com/pm2
npm http 304 http://npm.jd.com/pm2
npm verb etag http://npm.jd.com/pm2 from cache
npm verb get saving pm2 to /home/admin/.npm/npm.jd.com/pm2/.cache.json
npm verb cache add spec pm2
npm verb addNamed "*" is a valid semver range for pm2
npm verb addNameRange registry:http://npm.jd.com/pm2 not in flight; fetching
npm verb get http://npm.jd.com/pm2 not expired, no request
npm verb addNamed "2.0.18" is a plain semver version for pm2
npm verb afterAdd /home/admin/.npm/pm2/2.0.18/package/package.json not in flight; writing
npm verb afterAdd /home/admin/.npm/pm2/2.0.18/package/package.json written
npm verb cache add spec amp@https://registry.npmjs.org/amp/-/amp-0.3.1.tgz
npm verb cache add spec amp-message@https://registry.npmjs.org/amp-message/-/amp-message-0.1.2.tgz
npm verb cache add spec ansi-regex@https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.0.0.tgz
npm verb cache add spec ansi-styles@https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz
npm verb cache add spec anymatch@https://registry.npmjs.org/anymatch/-/anymatch-1.3.0.tgz
npm verb cache add spec argparse@https://registry.npmjs.org/argparse/-/argparse-1.0.7.tgz
npm verb cache add spec arr-diff@https://registry.npmjs.org/arr-diff/-/arr-diff-2.0.0.tgz
npm verb cache add spec arr-flatten@https://registry.npmjs.org/arr-flatten/-/arr-flatten-1.0.1.tgz
...
(many many lines)
...
npm http fetch GET https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz
npm info retry fetch attempt 1 at 3:44:59 PM
npm info attempt registry request try #1 at 3:44:59 PM
npm http fetch GET https://registry.npmjs.org/vizion/-/vizion-0.2.13.tgz
npm info retry fetch attempt 1 at 3:44:59 PM
npm info attempt registry request try #1 at 3:44:59 PM
npm http fetch GET https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz
npm info retry fetch attempt 1 at 3:44:59 PM
npm info attempt registry request try #1 at 3:44:59 PM
npm http fetch GET https://registry.npmjs.org/yamljs/-/yamljs-0.2.8.tgz
npm info retry fetch attempt 1 at 3:44:59 PM
npm info attempt registry request try #1 at 3:44:59 PM
npm http fetch GET https://registry.npmjs.org/is-dotfile/-/is-dotfile-1.0.2.tgz
npm info retry fetch attempt 1 at 3:44:59 PM
npm info attempt registry request try #1 at 3:44:59 PM
npm http fetch GET https://registry.npmjs.org/is-equal-shallow/-/is-equal-shallow-0.1.3.tgz
npm info retry will retry, error on last attempt: Error: connect ETIMEDOUT 212.83.163.168:80
npm info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.88.162:443
npm info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.88.162:443
npm info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.88.162:443
npm info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.88.162:443
npm info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.88.162:443
npm info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.88.162:443
npm info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.88.162:443
npm info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.88.162:443
npm info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.88.162:443
npm info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.88.162:443
npm info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.88.162:443
npm info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.88.162:443
npm info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.88.162:443
npm info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.88.162:443
npm info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.88.162:443
npm info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.88.162:443
npm info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.88.162:443
npm info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.88.162:443
npm info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.88.162:443
npm info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.88.162:443
```

cf CONTRIBUTING.md for more informations

**Comment by vmarchaud** [comment]
We use npm shrinkwrap to lock our dependency, please install using `npm i pm2 --no-optional -g --no-shrinkwrap`.
