### ISSUE TITLE
Daemonize all pm2 start calls

### ISSUE THREAD

**Issue by ioanlucut** [Unitech/pm2#2440]
It is possible to set the `pm2` to daemonize every call to `pm2 start`? The documentation says the following: 

> By deafult, pm2 stays alive after your script exits. If pm2 is already running, your script will attach to the existing daemon but will also die when your process exits. 

What I want to achieve is the following: we port every app bootstrap logic into unix services, so instead of having a single `pm2` instance, we want a daemon per `app`, therefore per unix `service`. Currently the unix services are timing out due to fact that only the first call to `pm2 start` daemonizes.

**Comment by vmarchaud** [comment]
Are you sure that you want to use pm2 since its a daemon and that basically a unix service **is** a daemon ? You will achieve easily using the default linux tools.

**Comment by ioanlucut** [comment]
Thank you for response. Well, yes, pretty much, otherwise we need to rewrite in unix services pretty much everything that pm2 offers. Would you advise against using pm2 in this configuration?

**Comment by vmarchaud** [comment]
No, of course not, i advise you to doesn't use unix service and only use pm2. What i advise is to either use pm2 or unix service, they both implement the same concept : a process manager.
What was the argument to make a unix service per app in the first place ?

**Comment by ioanlucut** [comment]
Currently our infrastructure uses yadt (http://www.yadt-project.org/) for managing our apps which integrates them as unix services. Having this configuration and the apps separated makes easily to manage a particular app. Not all of them are node based apps. 

By using pm2 as a process manager would mean to simply have a single daemon (pm2) which we manage, therefore losing the granularity.

I suppose we actually try to integrate a process manager inside another one, which doesn't really make sense.. and it is clearer now.

**Comment by vmarchaud** [comment]
@ioanlucut You can actually start other apps type using `exec_interpreter` ([docs here](http://pm2.keymetrics.io/docs/usage/application-declaration/#general)). But yeah you got my point saying that managing a process manager using a process manager isn't really a good idea.

**Comment by ioanlucut** [comment]
Thank you for the explanation and your time!
