### ISSUE TITLE
Pm2 started to serve static files very slowly

### ISSUE THREAD

**Issue by archasek** [Unitech/pm2#2443]
#### Expected behaviour
Faster serving static files for development purposes (I know that on production NodeJS should not serve static files because it's slow). I need it only for local dev env.

#### Actual behaviour
When I refresh the website, very frequently it get stuck and it takes a few/dozen seconds to render.
In logs, there is also no information about successful requests (I don't know why it disappeared), I cannot see what static files are served with status 200. There are only missing files listed.

#### Steps to reproduce
I run `pm2-dev start pm2.json`.

pm2.json:
```
{
    "apps": [
        {
            "name": "DST",
            "script": "bin/www",
            "ignore_watch": ["frontend/", ".*"],
            "log_date_format" : "YYYY-MM-DD HH:mm",
            "env": {
                "NODE_ENV": "development"
            },
            "env_production": {
              "NODE_ENV": "production"
            }
        }
    ]
}
```

#### Software versions used

```
OS         : Windows 7
node.js    : 4.4.5
PM2        : 2.0.18
```

#### PM2 Log output

```
DST-0      | GET /img/favicon.ico - - ms - -
DST-0      | GET /img/logo.png - - ms - -
DST-0      | GET /img/favicon.ico - - ms - -
DST-0      | GET /img/logo.png - - ms - -
DST-0      | GET /browser-sync/socket.io.min.1.5.0.js.map - - ms - -
DST-0      | GET /browser-sync/socket.io.min.1.5.0.js.map - - ms - -
DST-0      | GET /browser-sync/socket.io.min.1.5.0.js.map - - ms - -
DST-0      | GET /browser-sync/socket.io.min.1.5.0.js.map - - ms - -
DST-0      | GET /img/favicon.ico - - ms - -
DST-0      | GET /img/logo.png - - ms - -
DST-0      | GET /browser-sync/socket.io.min.1.5.0.js.map - - ms - -
DST-0      | GET /browser-sync/socket.io.min.1.5.0.js.map - - ms - -
DST-0      | GET /img/logo.png - - ms - -
DST-0      | GET /img/favicon.ico - - ms - -
DST-0      | GET /browser-sync/socket.io.min.1.5.0.js.map - - ms - -
DST-0      | GET /img/favicon.ico - - ms - -
DST-0      | GET /img/logo.png - - ms - -
DST-0      | GET /browser-sync/socket.io.min.1.5.0.js.map - - ms - -
DST-0      | GET /browser-sync/socket.io.min.1.5.0.js.map - - ms - -
DST-0      | GET /browser-sync/socket.io.min.1.5.0.js.map - - ms - -
DST-0      | GET /browser-sync/socket.io.min.1.5.0.js.map - - ms - -
DST-0      | GET /img/favicon.ico - - ms - -
DST-0      | GET /img/logo.png - - ms - -
DST-0      | GET /browser-sync/socket.io.min.1.5.0.js.map - - ms - -
DST-0      | GET /browser-sync/socket.io.min.1.5.0.js.map - - ms - -
DST-0      | GET /browser-sync/socket.io.min.1.5.0.js.map - - ms - -
```

**Comment by vmarchaud** [comment]
You should profile the application using Chrome ([tutorial](https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27#.t3aqzjml7)) and see what's going on, pm2 just spawn your application inside a child-process, it should not impact performance that bad.

Are you sure that come from pm2 ? Have you tried using another process manager or just vanilla nodejs for example ? Check your RAM/CPU usage for anormal behavior ?

**Comment by archasek** [comment]
Sorry, you are right that it's not really connected with pm2... When I use vanilla node to run my app, the behavior is the same.

**Comment by vmarchaud** [comment]
Closing so ;)
