### ISSUE TITLE
pm2 restart not working on typescript app

### ISSUE THREAD

**Issue by radarsu** [Unitech/pm2#2444]
#### Expected behaviour
```
pm2 list
myApp ... online
pm2 restart
myApp  ... online
```

#### Actual behaviour
```
pm2 list
myApp  ... online
pm2 restart
myApp  ... stopped
```

#### Steps to reproduce
Create launch script json (myApp.json) for TypeScript application:
```
{
    "apps": [{
        "name": "myApp",
        "script": "/path/app.ts",
        "env": {
            "NODE_ENV": "development"
        },
        "args": ""
    }]
}
```
Run:
```
pm2 start myApp.json
myApp  ... online
pm2 restart myApp
myApp  ... stopped
```

#### Software versions used

```
OS         : Ubuntu 16.04
node.js    : 6.5.0
PM2        : 2.0.18
```

**Comment by vmarchaud** [comment]
Have you run a `pm2 install typescript` before ?

**Comment by radarsu** [comment]
Yes, of course. Application is working and running smoothly. I can start it with `pm2 start myApp.ts` and watch pm2 logs too. The problem is only with restart - restart stops it instead of restarting.

As a workaround I have to do:
`pm2 delete myApp`
`pm2 start myApp.ts`

**Comment by radarsu** [comment]
I reinstalled pm2, typescript and ts-node and it works now.

I guess the problem was I was using latest typescript 2.1.0-dev.
