### ISSUE TITLE
Advanced_Readme: Folder Structure link broken

### ISSUE THREAD

**Issue by batjko** [Unitech/pm2#2445]
If reporting a bug, please use the following template.

#### Expected behaviour

Link leads to existing Section of the current document:
https://github.com/Unitech/pm2/blob/master/ADVANCED_README.md#pm2-folder-structure

#### Actual behaviour

Nothn'

#### Steps to reproduce

On the Advanced_Readme.md file, click the "Folder Structure" link.
Observe nothing.

**Comment by Unitech** [comment]
minor, this file will be dropped in the future

please refer to the official doc instead: http://pm2.keymetrics.io/
