### ISSUE TITLE
pm2 partly ignores sudo

### ISSUE THREAD

**Issue by flashspys** [Unitech/pm2#2446]
If using pm2 behind an ssh session it wont work correct with `sudo -s`. pm2 will only show the true list if you open your ssh session with the user pm2 runs in. It's not possible to use pm2 from another user via su or, in my case, sudo. Is this expected behavior?

#### Expected behaviour

```
Felixs MacBook Pro:~ Felix$ ssh felix@example.org
felix@example:~$ sudo pm2 l
[sudo] password for felix: 
< a **not** empty list >
```

#### Actual behaviour

```
Felixs MacBook Pro:~ Felix$ ssh felix@example.org
felix@example:~$ sudo pm2 l
[sudo] password for felix: 
< empty list >
felix@example:~$ sudo -s
root@example:~# whoami
root
root@example:~# pm2 l
< empty list >
root@example:~# exit
exit
felix@example:~$ exit
logout

Felixs MacBook Pro:~ Felix$ ssh root@example.org
root@example:~# pm2 l
< a **not** empty list >
```

#### Software versions used

```
OS         : latest Ubuntu
node.js    : v4.2.6
PM2        : 1.1.3
```

**Comment by vmarchaud** [comment]
That's because the pm2 CLI connect to the daemon via socket that are stored in `~/.pm2/` (so relative of the user). So yeah normal behavior, you should check to set `PM2_HOME` env variable to the `~/.pm2/` of the user that has spawned the daemon.

**Comment by flashspys** [comment]
Okay thank you. I now use `su - root` to login into root. Here is pm2 l outputting the information I expected
