### ISSUE TITLE
no log in cluster mode

### ISSUE THREAD

**Issue by eshengsky** [Unitech/pm2#2447]
I used PM2 in Windows 10, node.js v4.4.3, my run script is: 
`pm2 start bin/www -i max`
`pm2 list` shows as following:
┌──────────┬────┬─────────┬───────┬────────┬────────
──┬─────┬───────────┬──────────┐
│ App name │ id │ mode    │ pid   │ status │ restart │ uptime │ cpu │ mem       │ watching │
├──────────┼────┼─────────┼───────┼────────┼────────
──┼─────┼───────────┼──────────┤
│ www      │ 0  │ cluster │ 9164  │ online │ 0       │ 2s     │ 0%  │ 57.4 MB   │ disabled │
│ www      │ 1  │ cluster │ 260   │ online │ 0       │ 1s     │ 0%  │ 57.6 MB   │ disabled │
│ www      │ 2  │ cluster │ 14404 │ online │ 0       │ 1s     │ 0%  │ 57.3 MB   │ disabled │
│ www      │ 3  │ cluster │ 9212  │ online │ 0       │ 1s     │ 0%  │ 57.7 MB   │ disabled │
└──────────┴────┴─────────┴───────┴────────┴────────
──┴─────┴───────────┴──────────┘
I have many log in my code, such as 
`console.log('test!');`
while `pm2 logs` does not show the log, and there is no log in .pm2\logs\xxx.log file.

If I not use cluster mode, that is:
`pm2 start bin/www`
everything is fine, log is perfect.

any help?

**Comment by vmarchaud** [comment]
Can you please provide an example file to reproduce this issue ?

**Comment by eshengsky** [comment]
I have found it's the compatibility problem between pm2 & log4js-node.  
Closed. thanks.

**Comment by webFunc** [comment]
@eshengsky so... how do you solve this problem at last? Would you provide some infomation?

**Comment by eshengsky** [comment]
@webFunc I removed `type: "clustered"` from my log4js config file.
