### ISSUE TITLE
Problem install dependencies: npm not use private registry

### ISSUE THREAD

**Issue by lebretr** [Unitech/pm2#2448]
#### Expected behaviour
when install pm2, pm2's depencies must be dowloaded from the registry set in npm config
...

#### Actual behaviour
I am behind a corp proxy and I have a private registry
On my server(centos 7) and my PC (linux Mint 18), npm config registry is my private registry server

Actually, the pm2's depencies are download directly from npmjs and not from my private registry

With pm2@1.x.x, I haven't the problem. the registry used is my private registry
...

#### Steps to reproduce
npm config set registry="http://my.private.regystry.com"
npm install -g pm2 
...

#### Software versions used

```
OS         : Centos 7 | Linux Mint 18
node.js    : node 6.2.2 | node 6.3.1
PM2        : 2.0.18
```

**Comment by vmarchaud** [comment]
See #2438 : 

> Sadly that's because we use npm shrinkwrap that doesnt make difference between optional and required dependency, that's an issue in npm here.
We are discussing a solution for this one, but you can use `npm i pm2@latest --no-optional -g --no-shrinkwrap` to install it, this should work.

**Comment by lebretr** [comment]
That's works.

Thank you and sorry for double post.
