### ISSUE TITLE
Question on the pm2 list

### ISSUE THREAD

**Issue by ChennyBaBy** [Unitech/pm2#2449]
Got a really quick and dumb question about the restart column from pm2 list, I guess these should be   pretty self explanatory, but I'm not too clear what the restart column means. So I have 20 as the value in my screen shot, does it represent the maxium time it will restart? or how many times it has restarted ? I cant really find anything that explains it in the docs.

![pi_applepi_____ssh_](https://cloud.githubusercontent.com/assets/1523107/19393571/208eac20-922d-11e6-8457-bcf63d3966b3.png)

Thanks in advance.

**Comment by vmarchaud** [comment]
It's how many times the application has been restarted by pm2, it reset when you restart by the CLI (since the restart is made by you).
