### ISSUE TITLE
Pm2 to start an app with sudo command

### ISSUE THREAD

**Issue by vijay122** [Unitech/pm2#2452]
If reporting a bug, please use the following template.

#### Expected behaviour
Greetings to pm2 team, for creating such a unique tool.
I am trying to start my app with pm2 in Ubuntu server in production. The users can upload pics to the app, it creates folder dynamically on server, and puts the pictures inside those folder. Since I am doing file operation, I used to run the app in sudo mode, means as the root user. Is there a way I can tell pm2 to run my app with root user. I tried sudo pm2 start my_app_file.js . But it did nt work. However when i run without pm2, sudo node my_app_file.js it works perfectly. Please let me know what I am missing.
#### Actual behaviour

it will be nice to have a provision to specify to run the app in root user.

#### Steps to reproduce

...

#### Software versions used

```
OS         :ubuntu
node.js    :6
PM2        :latest
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
...
```

cf CONTRIBUTING.md for more informations

**Comment by vmarchaud** [comment]
PM2 is a daemon so its running on the user that are started the application, if you sudo to run pm2, the daemon will run as root and you will not be able to `pm2 list` from your user.
Plus you never should run anything under root, i'll personally allow your user to write in the folder you want so it doesnt need root.

**Comment by asdat3** [comment]
> PM2 is a daemon so its running on the user that are started the application, if you sudo to run pm2, the daemon will run as root and you will not be able to `pm2 list` from your user.
> Plus you never should run anything under root, i'll personally allow your user to write in the folder you want so it doesnt need root.

for a python Flask webserver you need root rights, soooooo I need to start the .py with root!
