### ISSUE TITLE
PM2 command not found

### ISSUE THREAD

**Issue by jy2008** [Unitech/pm2#2453]
I am installing PM2 for hubot rocket.chat adapter. so i did the following:
I firstly added a <pm2.json> file to hubot adapter folder, then 
`sudo npm install pm2 -g`
`cd <hubot directory>`
`pm2 start <pm2.json>`

The i got error saying this:
```
No command 'pm2' found, did you mean:
 Command 'wm2' from package 'wm2' (universe)
 Command 'pms' from package 'pms' (universe)
 Command 'pmk' from package 'pmk' (universe)
 Command 'pmw' from package 'pmw' (universe)
 Command 'fpm2' from package 'fpm2' (universe)
 Command 'pom2' from package 'libpod-pom-perl' (universe)
 Command 'pmi' from package 'powermanagement-interface' (universe)
 Command 'pm' from package 'powerman' (universe)
pm2: command not found
```
Then I tried to add the path by doing: 
`sudo env PATH=$PATH:/home/jy/.npm-global/bin pm2 startup -u safeuser`
and
`export PATH=$PATH:/home/jy/.npm-global/bin`
and restarted PuTTY,

still get the same error.

when I went to where PM2 is at, which is /home/jy/.npm-global/bin, and do `pm2 start <pm2.json>` command, still get the same error.

Is there anything i did wrong? or there might be other reasons?

**Comment by vmarchaud** [comment]
Take care that pm2 is in the path of both user, it must come from your system for sure.
Closing since it's not related to pm2, feel free to ask more questions (in this issue) anyway.
