### ISSUE TITLE
Could you please add time into log files by default?

### ISSUE THREAD

**Issue by xzycn** [Unitech/pm2#2454]
When I start a script using  "pm2 start" every time,must append "--log_date_format" opinion to the command.This is a bit weird to me,maybe many others.Shouldn't we put a time into log in almost all situations?
So,could you enhance this feature?

**Comment by vmarchaud** [comment]
Because we are streaming the `stdout` and `stderr` of the application, some people already use a logger that log handle this. So it will stay an option for now.
