### ISSUE TITLE
--node-args cli argument create the error "node: bad option: --dir-path=myPath"

### ISSUE THREAD

**Issue by sulliwane** [Unitech/pm2#2455]
#### Expected behaviour
take node cli argument

#### Actual behaviour
```node: bad option: --dir-path=myPath```

#### Steps to reproduce
just start the program with ```--node-args``` like this:
```DEBUG=*,-babel pm2 start src/index.js --no-autorestart --name myProgram --node-args="--dir-path=myPath"```

#### Software versions used

```
OS         : ubuntu 16.04
node.js    : 6.7.0
PM2        : 2.0.18
```

**Comment by soyuka** [comment]
http://stackoverflow.com/a/34618054/1145578

`pm2 start app.js -- --dir-path=myPath`

**Comment by sowjanya-kr** [comment]
node: bad option: -version
