### ISSUE TITLE
pm2 --help missing trailing newline(s)

### ISSUE THREAD

**Issue by maxtruxa** [Unitech/pm2#2457]
Somewhat trivial but annoying behavior for anyone who's using `pm2 --help`.

![pm2 --help output](http://i.imgur.com/LEL1rIc.png)

#### Expected behaviour

PS1 (terminal prompt) appears in the line *after* the help message. Might even be separated by one or two empty lines.

#### Actual behaviour

PS1 appears in the same line as the last line of pm2's help message.

#### Steps to reproduce

```bash
pm2 --help
```

#### Software versions used

```
OS         : Debian GNU/Linux 7.11 (wheezy)
node.js    : v4.6.0
PM2        : 2.0.18
```

#### PM2 Log output

\-

**Comment by vmarchaud** [comment]
The help message is actually way bigger (with examples and options), your terminal might cut the other parts.
