### ISSUE TITLE
pm2 start app not working 

### ISSUE THREAD

**Issue by Jasmine2010** [Unitech/pm2#2458]
I installed hubot rocket chat adapter. it works well. I want to use pm2 to start it forever. so i created a `pm2.json` file under my hubot directory `myhubot` as the following:
```
{
  "apps": [{
		"name": "myhubot",
		"max_memory_restart": "1024M",
		"log_date_format": "YYYY-MM-DD HH:mm:ss SSS",
		"script": "bin/hubot", 
		"exec_interpreter": "bash",
		"args": "--name myhubot --adapter rocketchat",
		"watch": ["package.json", "external-scripts.json", "scripts/", "hubot-scripts.json", "HUBOT_GITHUB_EVENT_NOTIFIER_TYPES=issues,pull_request,push bin/hubot"],
		"out_file": "/var/log/hubot/app.log",
		"error_file": "/var/log/hubot/err.log",
		"port": "8079",
		"env": {
			"ROCKETCHAT_URL": "my website domain",
			"ROCKETCHAT_USER": "bot",
			"ROCKETCHAT_ROOM": "",
			"ROCKETCHAT_PASSWORD": "bot",
			"PORT": "8079",
			"HUBOT_GITHUB_EVENT_NOTIFIER_TYPES": "issues,pull_request,push"
		}
	}]
}
```
I installed pm2 and pm2 works well. then i did `sudo pm2 start pm2.json`. pm2 does started an app named `myhubot` based on command line. But when i went to rocket.chat, hubot is not logged in. Is there anything wrong? Is port 8079 right? can the port be any number from 3001-8080?

**Comment by Unitech** [comment]
Any progress on that? You should not run pm2 as sudo, if you need to access to the 1024 port range use [authbind](http://pm2.keymetrics.io/docs/usage/specifics/#listening-on-port-80-w-o-root)
