### ISSUE TITLE
reload/restart changes error and out log path

### ISSUE THREAD

**Issue by shah-mcc** [Unitech/pm2#2459]
#### Expected behaviour
when reloading or restarting using a config file the error and out log paths should not change.

#### Actual behaviour
when reloading or restarting using a config file the error and out log paths change to paths without process id suffixes.

#### Steps to reproduce
config.json
```
{
  "apps": [
    {
      "name": "index",
      "script": "index.js",
      "exec_mode": "cluster",
      "instances": 0,
      "log_date_format": "[[]YYYY-MM-DD HH:mm:ss.SSS[]]"
    }
  ]
}

```
```
pm2 delete all
pm2 save
pm2 start config.json
```
at this point the out and error log paths are correct with process id suffixes
```
/home/<user>/.pm2/logs/index-err-0.log
/home/<user>/.pm2/logs/index-err-1.log

/home/<user>/.pm2/logs/index-out-0.log
/home/<user>/.pm2/logs/index-out-1.log
...
```
now if you reload or restart or even stop and start
```
pm2 reload config.json
```
the log paths are
```
/home/<user>/.pm2/logs/index-err.log
/home/<user>/.pm2/logs/index-out.log
```
the only way to get the proper log paths back is with delete and start

#### Software versions used

```
OS         : Ubuntu 14.04.5 LTS
node.js    : 6.9.0
PM2        : 2.0.18
```

**Comment by tantra35** [comment]
This is the same as #2227

**Comment by vmarchaud** [comment]
Closing since duplicate.
