### ISSUE TITLE
Cannot unlink/remove/restart pm2

### ISSUE THREAD

**Issue by ayxos** [Unitech/pm2#2460]
Instead of that i get this 

´´´
➜  interpretaMe git:(master) ✗ pm2 link delete
[PM2] Spawning PM2 daemon
[Keymetrics.io] Using (Public key: xxxxxxxx) (Private key: xxxxxx)
[Keymetrics.io] [Agent updated] Agent ACTIVE - Web Access: https://app.keymetrics.io/
[PM2] PM2 Successfully daemonized
[PM2][Module] Starting module pm2-server-monit
[PM2][WARN] Applications pm2-server-monit not running, starting...
´´´

**Comment by vmarchaud** [comment]
Please follow the issue template.
