### ISSUE TITLE
always say >>>> In-memory PM2 is out-of-date, do: >>>> $ pm2 update

### ISSUE THREAD

**Issue by Messilimeng** [Unitech/pm2#2462]
If reporting a bug, please use the following template.

#### Expected behaviour

...

#### Actual behaviour
I delete all of the pm2 file and npm install pm2 -g
...

#### Steps to reproduce
pm2 list
Be sure to have the latest version by doing `npm install pm2@latest -g` before doing this procedure.
According to the prompt I npm install pm2@latest -g
but it cant work at all;
...

#### Software versions used

```
OS      windows service 2008 r2   :
node.js    :
PM2        :
```

#### PM2 Log output
![image](https://cloud.githubusercontent.com/assets/12272166/19590635/7a8c3de6-97a5-11e6-9950-2ad787f99a87.png)

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
...
```

cf CONTRIBUTING.md for more informations

**Comment by soyuka** [comment]
just run `pm2 update`

**Comment by Messilimeng** [comment]
@soyuka 
![image](https://cloud.githubusercontent.com/assets/12272166/19590923/026fb02a-97a7-11e6-96a7-9268ac8736f8.png)

**Comment by Messilimeng** [comment]
Than I kill the node.exe  process , it seem run ok, but i start the app  , I will wait so long time ?why
![image](https://cloud.githubusercontent.com/assets/12272166/19591475/df266da4-97a9-11e6-89d5-4a45f26a4af2.png)

**Comment by vmarchaud** [comment]
PM2 on Windows isn't recommended for production environments, specially in that old windows version.

**Comment by Messilimeng** [comment]
@vmarchaud 
so my production environments is windows service 2012 
Is it batter than 2008 R2?

**Comment by soyuka** [comment]
I know a company using windows 2012 and 2008 R2 without issues with pm2 ;). (they just migrated to 2012 though)

**Comment by Messilimeng** [comment]
开始的时候我们用windows 以后 会用Linux 
At begining we will use windows service   later we will use Linux

thinks @soyuka @vmarchaud

**Comment by vmarchaud** [comment]
All my tests was under windows 7 so should be working under windows 2012.

**Comment by Unitech** [comment]
Any progress on that issue @Messilimeng, looks like your bin path is messy

**Comment by mdrijwan** [comment]
every time i update pm2, the moment i restart the terminal it tells me to update again shows me this:

```In-memory PM2 is out-of-date, do:
>>>> $ pm2 update
In memory PM2 version: 2.1.6
Local PM2 version: 2.4.0```

what's the solution?

**Comment by AlbinCauderlier** [comment]
Same problem

**Comment by vmarchaud** [comment]
Run `pm2 update`

**Comment by AlbinCauderlier** [comment]
Already done... without success.
< pm2 status> give me the same answer :
<
>>>> In-memory PM2 is out-of-date, do:
>>>> $ pm2 update
In memory PM2 version: 2.3.0
Local PM2 version: 2.4.6
>

**Comment by AlbinCauderlier** [comment]
`pm2 kill -all`
`npm remove pm2 -g`
`npm install pm2 -g`
`pm2 update`
`pm2 --update-env`

`pm2 status` ...

**Comment by vmarchaud** [comment]
Kill all the daemons : `ps aux | grep PM2`

**Comment by AlbinCauderlier** [comment]
ps aux => `[PATH]/.nvm/versions/node/v6.9.4/lib/node_modules/pm2/bin/pm2 resurrect --no-daemon`

**Comment by AlbinCauderlier** [comment]
I quit... No way to kill this...

**Comment by Dzenly** [comment]
Just met the same problem, killing all daemons did not help. But computer reboot helped.

**Comment by evollu** [comment]
I used `pm2 unstartup` to prevent pm2 to restart itself then `pm2 update` seemed to work

**Comment by myyellowshoe** [comment]
Tried all the above. Still now luck at updating. The script still keeps restarting it self in the background, and I keeps the in memory process going. Restarted, removed/reinstalled pm2 and no dice.

When running the command from 'pm2 unstartup' i get the following error:


```
main@Moonlite:~$ pm2 unstartup
[PM2] Init System found: systemd
[PM2] You have to run this command as root. Execute the following command:
sudo env PATH=$PATH:/home/main/.nvm/versions/node/v8.1.0/bin /home/main/.nvm/versions/node/v8.1.0/lib/node_modules/pm2/bin/pm2 unstartup systemd -u main --hp /home/main
main@Moonlite:~$ sudo env PATH=$PATH:/home/main/.nvm/versions/node/v8.1.0/bin /home/main/.nvm/versions/node/v8.1.0/lib/node_modules/pm2/bin/pm2 unstartup systemd -u main --hp /home/main
[PM2] Init System found: systemd
Failed to stop pm2-main.service: Unit pm2-main.service not loaded.

Failed to stop pm2-main.service: Unit pm2-main.service not loaded.

undefinedReturn code : 5
```
What is up here?

**Comment by mattiasmak** [comment]
pm2 updatePM2

**Comment by bradennapier** [comment]
Ok so my issue was that it "APPEARED" to be caused by server but it was apparently on the client.  Server was updated and showing.  Also had to use `npx` since i have it as a local dependency and i dont generally use the global since  i execute things in scripts.  

So running `npx pm2 update` is probably a good idea for those having issues

**Comment by Steveb-p** [comment]
I've had issues as described steming from conflicting installation from ubuntu package manager (`apt`) having installed `pm2` globally as a package (which took priority over anything being installed via `npm`).

Discovered this by checking `which pm2` and `whereis pm2` and discovering it was not the binary that `npm` installed.

**Comment by dawadam** [comment]
I'm just doing that, inspired by reponse on stackoverflow.
https://stackoverflow.com/questions/51860234/how-to-resolve-in-memory-pm2-is-out-of-date

```
pm2 unstartup systemd
pm2 update
pm2 startup
```

And it work.

**Comment by inspiraller** [comment]
I followed the above but noted I had to be logged in as the same user that installed pm2 in the first place. ie root user.

**Comment by zhengxin-wang** [comment]
Guys, I can't say 100%, but it shouldn't be your globally installed pm2 version issue. Instead, it's due to the pm2 processes that's running.

- In my case, I run a node.js program with pm2, inside that package.json the pm2 dependency is v3.0.3
- While in my globally installed pm2, it's v4.5.6. And it just identified the node.js is running with pm2 v3.0.3

**Comment by Nononoelle** [comment]
This problem makes me exhausted. I tried everything I could but all failed. It's weird that I use pm2 update; it works well. Once I type pm2 list, it shows error. the version of nodejs and that of linux is the same

**Comment by nadeem977** [comment]
i have an face this error any one can help me to solve this  

<img width="744" alt="image" src="https://github.com/Unitech/pm2/assets/117159455/3fa3969f-a577-4c85-a137-b0c2cb6cf68b">
