### ISSUE TITLE
max_old_space_size argument is not working

### ISSUE THREAD

**Issue by v29neil** [Unitech/pm2#2465]
Hi, 
I created the script for starting my server with the option max_old_space_size 
Process.json script:
```
{
  "apps": [
    {
      "name": "Server",
      "script": "./server.js",
      "node_args": "--max_old_space_size=500",
      "cwd": "/test/path/to/script/",
      "watch": true,
      "error_file"      : "/server-err.log",
      "out_file"        : "/server-out.log",
      "merge_logs"      : true,
      "log_date_format" : "YYYY-MM-DD HH:mm:ss Z",
      "env": {
        "NODE_ENV": "development"
      },
      "env_production": {
        "NODE_ENV": "production"
      }
    }
  ]
}
```
Then , i start the script using 
`pm2 start process.json`

So to make sure server is working with`max_old_space_size=500`  .
I checked the process details using  `ps -fp <PID>` 

But it is not showing under `CMD `. 
When i try to run manually by running  `node --max_old_space_size=500 script.js`
It shows max_old_space_size command under CMD .   
Anyone seems to have this issue ? or i am doing something wrong ?

**Comment by Unitech** [comment]
Yes this is normal, we rename the process with process.title
