### ISSUE TITLE
Deprecation warning message

### ISSUE THREAD

**Issue by Unitech** [Unitech/pm2#2468]
Deprecation warning about worker.suicide

https://gist.github.com/Unitech/784ad1a6a85146a0330323bc108df581

**Comment by soyuka** [comment]
Use `worker.exitedAfterDisconnect` instead https://nodejs.org/api/cluster.html#cluster_worker_exitedafterdisconnect

**Comment by Unitech** [comment]
landed in development

**Comment by yanzhihong23** [comment]
Still get this error on PM2 version 2.4.2
` (node:6246) DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.       `

**Comment by damianobarbati** [comment]
@Unitech is the 27-Oct-2016 commit going to fix the boring warning PM2 always throws when starting?
`PM2        | 2017-10-04 10:30:49: (node:3757) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
```

**Comment by vmarchaud** [comment]
As said on the nodejs issue : 
```
The log spam was a result of a module used by PM2 that walks an object's members mutating functions. Since it has to check for each member's functionness, it was calling typeof obj[key] and triggering this deprecation message.

So, removing this flag will not break PM2. They don't use it for anything.
```
