### ISSUE TITLE
launching pm2 from crontab, script defunct

### ISSUE THREAD

**Issue by naartjie** [Unitech/pm2#247]
I am using crontab's `@restart` to launch pm2 on my hosted server (webfaction, which is using CloudLinux Server 6.5).

I noticed that afterwards my `start_pm2.sh` bash script appears as `[defunct]` in `ps -eaf`. I can "fix" it if I do something like this:

`@reboot start_pm2.sh &> pm2.log &`

But then I don't get `stderr` emailed to me if anything goes wrong (using crontab's `MAILTO=`).

I was hoping to get some insight on this? Am I going about it the wrong way? I don't have root access, should I be using the `startup` command with user option?

Thanks!!

**Comment by juliousglori** [comment]
The command above doesn't worked in my app. When run pm2 commands (like start, resurrect) from crontab, my app doesn't  start properly. But when i manually run the command it starts well..

Here is the error i got:

maintenance-script-9 (err): 2015-09-28 05:55 +00:00: /home/ubuntu/src/maintenance-script/server/node_modules/co-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:83
maintenance-script-9 (err):         throw e
maintenance-script-9 (err):               ^
maintenance-script-9 (err): Error: Module version mismatch. Expected 14, got 44.
maintenance-script-9 (err):     at Error (native)
maintenance-script-9 (err):     at Module.load (module.js:349:32)
maintenance-script-9 (err):     at Function.Module._load (module.js:305:12)
maintenance-script-9 (err):     at Module.require (module.js:357:17)
maintenance-script-9 (err):     at require (module.js:373:17)
maintenance-script-9 (err):     at bindings (/home/ubuntu/src/maintenance-script/server/node_modules/co-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)
maintenance-script-9 (err):     at Object.<anonymous> (/home/ubuntu/src/maintenance-script/server/node_modules/co-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
maintenance-script-9 (err):     at Module._compile (module.js:449:26)
maintenance-script-9 (err):     at Object.Module._extensions..js (module.js:467:10)
maintenance-script-9 (err):     at Module.load (module.js:349:32)
maintenance-script-9 (err):     at Function.Module._load (module.js:305:12)
maintenance-script-9 (err):     at Module.require (module.js:357:17)
maintenance-script-9 (err):     at require (module.js:373:17)
maintenance-script-9 (err):     at Object.<anonymous> (/home/ubuntu/src/maintenance-script/server/node_modules/co-bcrypt/index.js:1:76)
maintenance-script-9 (err):     at Module._compile (module.js:449:26)
maintenance-script-9 (err):     at Object.Module._extensions..js (module.js:467:10)

On top of the it says: The app restarted 15 times so it is stopped (errored)

**Comment by fourq** [comment]
Was there ever a resolution to this @juliousglori ?

**Comment by labidiaymen** [comment]
up

**Comment by MiguelSavignano** [comment]
@Unitech that works form me, thaks!!,
