### ISSUE TITLE
ecosystem.json is created as invalid json

### ISSUE THREAD

**Issue by ElegantSudo** [Unitech/pm2#2473]
#### Expected behaviour
`pm2 ecosystem` should create `ecosystem.json` as valid json.

#### Actual behaviour
It creates it as invalid json, where properties and fields are lacking quotes surrounding them.

#### Steps to reproduce
Type `pm2 ecosystem` in terminal

#### Software versions used
```
OS         : macOS Sierra 10.12.1
node.js    : v4.6.0
PM2        : 2.0.18
```

No errors are displayed.

**Comment by Unitech** [comment]
Install this pm2:

```
$ npm install Unitech/pm2#development -g
$ pm2 update
$ pm2 ecosystem
```
