### ISSUE TITLE
PM2 cluster load balancing not working for remote clients

### ISSUE THREAD

**Issue by mocotrah** [Unitech/pm2#2476]
Hi, 
I have a Node.js server app running in PM2 cluster mode.
I have it installed on Windows 7, but also made tests on a RedHat.
(Node 5.1.1, PM2 2.0.18)
Here's what I have tested:
My client fires 500 calls in parallel to REST API in my Node.js server.
1) if I run my client on the same machine where PM2/Node.js server is running, the load is distributed on almost all processes.
![capturelocalhost](https://cloud.githubusercontent.com/assets/15890374/19771215/6a35579a-9c62-11e6-932e-23a74f02e0b4.PNG)

2) if I run the client on 1-4 machine(s) in the network, all clients reach the server but only one process is doing the work (and goes up to 100% CPU time).
![capturefromremote](https://cloud.githubusercontent.com/assets/15890374/19771197/5bb40ce8-9c62-11e6-8a9b-aef4c8188628.PNG)

It's like the load balancing mechanism it's not working for clients coming from a remote machine.
Do you have any thoughts on that's wrong here?

**Comment by soyuka** [comment]
This is related to how the nodejs cluster round robin works nothing we can do about it. However, I may suggest that you update nodejs.

**Comment by vmarchaud** [comment]
I advise you to read the [documentation of cluster](https://nodejs.org/dist/latest-v6.x/docs/api/cluster.html#cluster_how_it_works) and you'll see that by default under windows, it isnt round-robin and would suffer from the other strategy in this case.

> Loads have been observed where over 70% of all connections ended up in just two processes, out of a total of eight.

Closing since we can't do much about it apart from re-implementing the cluster system.

**Comment by jandosse** [comment]
please don something about it

**Comment by a1003584293** [comment]
I have same question;but However, the native cluster module can set cluster.schedulingPolicy = cluster.SCHED_RR; It can be implemented load-balancing on windows; Or set NODE_CLUSTER_SCHED_POLICY=rr；But neither method works on windows
