### ISSUE TITLE
pm2-axon folder was delete after run pm2 start command

### ISSUE THREAD

**Issue by lerit** [Unitech/pm2#2480]
If reporting a bug, please use the following template.

#### Expected behaviour
except start pm2 each time
...

#### Actual behaviour
first pm2 start is fine,but then pm2-axon folder was delete.i  run such as pm2 list ,error throw "Cannot find module 'pm2-axon'",i must copy this folder each time before run pm2 command.
...

#### Steps to reproduce

...

#### Software versions used

```
OS         :win10 x64
node.js    :v6.9.1(same error v4.5)
PM2        :v1.1.3
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
...
```

cf CONTRIBUTING.md for more informations

**Comment by vmarchaud** [comment]
Can you update to latest pm2 version : `npm install pm2@next -g && pm2 update` and test if the issue is still here ?

**Comment by lerit** [comment]
thanks!update to v2.0 resolve my problem
