### ISSUE TITLE
pm2 --watch option is conflicting with websocket connections

### ISSUE THREAD

**Issue by papmodern** [Unitech/pm2#2482]
#### Expected behaviour

Consistent socket connection between client and server after using pm2 --watch option.
#### Actual behaviour

Socket connection breaks sometimes with 502 (Bad Gateway) errors (Only with using pm2 --watch)
#### Steps to reproduce

Create an expressjs application, consuming socket.io package for managing socket connections.
Start nginx server and create a virtual host to redirect requests to local running application (which is running by pm2 and with --watch option on port 3000)
Now try to calling some functions on server or vice versa.
#### Software versions used

pm2 1.1.3
node 6.5.0
npm 3.10.3
express 4.14.0
socket.io 1.4.8
nginx 1.10.1
centos 7

As I'm not sure the problem is in pm2 , I will add this issue on socket.io project too!

**Comment by vmarchaud** [comment]
Please try with latest pm2 version : `npm install -g pm2@next && pm2 update`

**Comment by Unitech** [comment]
@papmodern any news? The @next version will fix this issue

**Comment by papmodern** [comment]
I'll test it tomorrow with latest version and let you know the result. @Unitech 
When the next version will release?

**Comment by Unitech** [comment]
Great thanks.
@next version will be published some time this week or early next week

**Comment by papmodern** [comment]
@Unitech Unfortunately the problem persist on version 2.0.19

**Comment by Unitech** [comment]
I guess the restart counter increase over time when you use the --watch option?

**Comment by papmodern** [comment]
Is that solved?

**Comment by vmarchaud** [comment]
Watch doesn't reload the apps (only hard restart) so it's normal that some connections are dropped. I advise you to just don't use watch in production (since its mainly for dev mode)

**Comment by papmodern** [comment]
My reason for using watch in production mode was about updating the scripts. Because for updating I had to delete exist process and restart them with pm2. 
And because of that process ids always increased. 
Now I'm using -n option for naming process. But the overhead of typing delete and start commands is not so nice!

**Comment by vmarchaud** [comment]
@papmodern I advise you to make a process file (generate one with `pm2 ecosystem`) and configure all apps you want in it, it will be easier to manage.
