### ISSUE TITLE
pm2-docker starting `pm2 web` health inspector

### ISSUE THREAD

**Issue by wisko** [Unitech/pm2#2486]
I have moved my application into docker, and started using the binary `pm2-docker` to make all processes run correctly.

However, I previously used `pm2 web` when running pm2 on its own, and it would be nice if it was possible to send it in as an argument to `pm2-docker`, so that it can run alongside my application inside the container.

**Comment by Unitech** [comment]
Interesting idea, would you mind doing a PR on pm2-docker? ([[1](https://github.com/Unitech/pm2/blob/master/bin/pm2#L518)][[2](https://github.com/Unitech/pm2/blob/master/bin/pm2-docker)])

**Comment by Unitech** [comment]
Web interface on pm2-docker implemented & landed in development branch, this feature will be available on next release.

```bash
$ pm2-docker process.json --web [port||9615]
```
