### ISSUE TITLE
Possible to change PM2_WORKER_INTERVAL in pm2.json config file?

### ISSUE THREAD

**Issue by artofspeed** [Unitech/pm2#2489]
By default `max_memory_restart` gets checked every 30 secs, is there a way to change `PM2_WORKER_INTERVAL` in **pm2.json** like this to check more often?
```
"apps" : [
    {
      "env": {
        "PM2_WORKER_INTERVAL" : "5000" 
      },
      "max_memory_restart" : "300M" 
    },
]
```

**Comment by Unitech** [comment]
You can set PM2_WORKER_INTERVAL environment variable in /etc/environment
