### ISSUE TITLE
how to disable logs?

### ISSUE THREAD

**Issue by txiaocao** [Unitech/pm2#2490]
If reporting a bug, please use the following template.

#### Expected behaviour

...

#### Actual behaviour

...

#### Steps to reproduce

...

#### Software versions used

```
OS         :
node.js    :
PM2        :
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
...
```

cf CONTRIBUTING.md for more informations

**Comment by vmarchaud** [comment]
A little bit of research and you would have found : https://github.com/Unitech/pm2/issues/866

**Comment by wtchangdm** [comment]
@vmarchaud Hi, does it work on Windows? I tried "NUL" like the stackoverflow post said. However, it created a file called NUL...

**Comment by vmarchaud** [comment]
@wtchangdm http://stackoverflow.com/questions/313111/dev-null-in-windows

**Comment by wtchangdm** [comment]
@vmarchaud Thank you for your reply, I did write something like:
`"log": "NUL" //which created a file named NUL` 
`"log": "C:\\something\\NUL //which still created a file named NUL"`
Is there anything I misunderstand? Because a simple `echo 1 > c:\nul` doesn't create any file at all

**Comment by wtchangdm** [comment]
Sorry, I really don't want to bring this up again, but is there anything wrong with my setting? Or I just can't simply combine the NUL trick with PM2? Thanks in advance.

**Comment by nodkrot** [comment]
Whats the answer here?
