### ISSUE TITLE
Socket files (pub and rpc) needed?

### ISSUE THREAD

**Issue by markusdanek** [Unitech/pm2#2491]
Hello,

are the socket files in the root home directory needed for pm2? We have a strict policy at operations unfortunately.

Those files are meant:
./.pm2/**rpc.sock** 
./.pm2/**pub.sock**

Is it possible to remove them or "disable" them via configuration?

Thanks!

**Comment by vmarchaud** [comment]
For people who want more informations about this, the socket are used by the CLI and PM2 API to connect to the daemon running in the background, they are installed in `$PM2_HOME` which by default is the `~/.pm2` of the user who launched the daemon for the first time. PM2 communicate via RPC server which is exposed via the socket files.

**Comment by SnowyJaguar1034** [comment]
> For people who want more informations about this, the socket are used by the CLI and PM2 API to connect to the daemon running in the background, they are installed in `$PM2_HOME` which by default is the `~/.pm2` of the user who launched the daemon for the first time. PM2 communicate via RPC server which is exposed via the socket files.

Hi, Just a question about this. If I wanted to manage my PM2 instance (that is running on the host locally) from within a docker container, then could I pass these socket files into the container as bind mount environment variables? or would there be a different file(s) or directory(s) I would need to pass in?
