### ISSUE TITLE
process.env.npm_package_config_port undefined when start  by pm2_windows_service

### ISSUE THREAD

**Issue by lerit** [Unitech/pm2#2494]
If reporting a bug, please use the following template.

#### Expected behaviour
read process.env.npm_package_config_port when start pm2 by pm2_windows_service
...

#### Actual behaviour
i  run pm2 by "pm2 start" in windows,it works fine.but when i start pm2  by pm2_windows_service(reboot my computer),i can see node process is runing ,but pm2 error logs say: process.env.npm_package_config_port undefined,and "pm2 list" can see it restart again and again.

before,i read port config by require('package.json'),it work fine(start by pm2_windows_service is fine too),but when i use process.env.npm_package_config_port to read it,it fail.is it mean i can not read it when start as service?

#### Steps to reproduce

...

#### Software versions used

```
OS         :win2012 x64
node.js    :v6.9.1
PM2        :latest
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
...
```

cf CONTRIBUTING.md for more informations

**Comment by vmarchaud** [comment]
I suggest you to see with the guy who wrote `pm2-windows-service` the problem don't come from PM2 itself.
