### ISSUE TITLE
How print to the console

### ISSUE THREAD

**Issue by robsonbittencourt** [Unitech/pm2#2497]
I use pm2 in a CLI and must inform the user of an error.

I searched but did not find a way not to drive console.log to the log file.

How can I do to display a text in the terminal and continue logging other errors?

**Comment by soyuka** [comment]
pm2 logs? Check also the logs at `~/.pm2/logs`

**Comment by robsonbittencourt** [comment]
@soyuka i need show a message to user in terminal not in logs.

**Comment by vmarchaud** [comment]
PM2 is a daemon, you can't show something on user terminal since its the daemon that start the process.

**Comment by robsonbittencourt** [comment]
I ended up doing a workaround. I'm going to register here in case someone has the same need.

I found this module that displays a dialog:
https://github.com/tomas/dialog

And I wrote the code below to display the error for the user:

```javascript
const pm2 = require('pm2');
const dialog = require('dialog');

something()
  .then(sucess)
  .catch ((err) => {
    dialog.err (err, 'Error', () => {
    pm2.stop ('myApp', () => pm2.disconnect ());
  });
});
