### ISSUE TITLE
Issue with setting up a native logrotate

### ISSUE THREAD

**Issue by AndySoHotRightNow** [Unitech/pm2#2498]
I noticed logs are not being rotated when setting up a native logrotate as described [here](http://pm2.keymetrics.io/docs/usage/log-management/).

#### Expected behaviour

Rotate logs as describe in the configuration file created by doing

`$ sudo pm2 logrotate -u user`

...

#### Actual behaviour

Logs are not rotated.

To investigate the problem I did

`logrotate -d pm2-user`

And the output I observe is

```
considering log /home/ubuntu/.pm2/logs/*.log
log /home/ubuntu/.pm2/logs/*.log does not exist -- skipping
```

Issue lies in the fact that there is a mismatch between the name of the log file created by PM2 (**without** .log extension and the ones expected by the logrotate utility **with** .log extension).

May I suggest to edit the default config file to read:

```
/home/user/.pm2/pm2.log /home/user/.pm2/logs/* {
        rotate 12
        weekly
        missingok
        notifempty
        compress
        delaycompress
        create 0640 user user
}
```

Rather than

```
/home/user/.pm2/pm2.log /home/user/.pm2/logs/*.log {
        rotate 12
        weekly
        missingok
        notifempty
        compress
        delaycompress
        create 0640 user user
}
```

...

#### Steps to reproduce

Start a process with PM2 and then set up a native log rotate with

`$ sudo pm2 logrotate -u user`

And notice that nothing happens

...

#### Software versions used

```
OS         :   Ubuntu 16.04 Xerial
node.js    :  6.4.0
PM2        : 1.1.3
```

**Comment by vmarchaud** [comment]
Please try with the latest pm2 version : `npm install -g pm2 && pm2 update`

**Comment by AndySoHotRightNow** [comment]
Done and still seeing the same problem.

The issue is with the pm2 template stored at

`/usr/local/lib/node_modules/pm2/lib/templates/logrotate.d/pm2`

I believe this line (the first line):

`/home/user/.pm2/pm2.log /home/user/.pm2/logs/*.log {`

Should be changed to this line

`/home/user/.pm2/pm2.log /home/user/.pm2/logs/*`

PM2 logs do not have the **.log** extension and that's what is causing the mismatch when the default template is loaded.

On a side note, I would also consider introducing

`copytruncate`

as part of the logrotate template as @pedrofranceschi mentioned in this [issue](https://github.com/Unitech/pm2/issues/114).

**Comment by Unitech** [comment]
PR merged feel free to try the patched native logrotate:

```
$ npm install Unitech/pm2#development -g
$ sudo pm2 logrotate -u user
```

**Comment by AndySoHotRightNow** [comment]
Exactly what I had in mind :)

**Comment by Unitech** [comment]
published on pm2@2.1.5

**Comment by luislobo** [comment]
@Unitech This actually breaks pm2 behavior.

I just created a very simple app `index.js`:
```js
setInterval(function(){ console.log(new Date().toISOString(),"This is a log that grows forever"); }, 50);
```

Started with `pm2 start index.js`

The logs are being saved as `index-out-0.log` and `index-error-0.log`.

If you just leave `/home/user/.pm2/pm2.log /home/user/.pm2/logs/*`, the first time logrotate runs, it generates `index-out-0.log.1`. The second time it runs it generates `index-out-0.log.1.1`, and it continues creating files for each file found, since you are including **all** files.
It should be reverted back to `*.log` or `*log`

**Comment by AndySoHotRightNow** [comment]
You are right, apologies, I made a mistake. It should be reverted back to `*.log` while still keeping the `copytruncate` option.

For some reason my log files did not have the `.log` extension and they were not being rotated correctly.
