### ISSUE TITLE
pm2 start hangs at [PM2] Spawning PM2 daemon 

### ISSUE THREAD

**Issue by changev** [Unitech/pm2#2503]
#### Expected behaviour
when
```
pm2 logs > some.log &
pm2 start some-comfig.yml
```

for ```pm2 logs```
......
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2 
[PM2] PM2 Successfully daemonized
.......

for ```pm2 start```
.............
just start the process because  PM2 daemon has been setup
..............

#### Actual behaviour
```pm2 logs``` start successfully

but ```pm2 start``` Hangs at 
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2

#### Steps to reproduce

Occurs occasionally, probability is about 30%.
just run 
```
#!/bin/bash
while true; do
  pm2 logs > some.log &
  pm2 start some-config.yml
done
```

#### Software versions used

OS runs in vagrant box.
vagrant up -> vagrant ssh xxx -c 'pm2 start ...' 

OS         :  ubuntu 14.04 in vagrant box
node.js    : v4.6.1
PM2        : 2.0.19

#### Possible root cause
There's no mutex lock on **check existence of Daemon process** when run each PM2 cmds.
#So a mutex lock can be added on "check daemon" or when hangs at spawning daemon just skip.

This issue make all cases like this not available.
```
pm2 some cmds &
pm2 some cmd
```
@Unitech

**Comment by vmarchaud** [comment]
We are spawning the process at this moment ([here](https://github.com/Unitech/pm2/blob/51edbc55bbf71d59ceb9a8a222c6cb55bf4e7b63/lib/Client.js#L214)) so i guess that vagrant got some problem with that maybe ?
Anyway i don't see any way to fix this problem since we rely on nodejs standart lib to handle spawning the process.

**Comment by changev** [comment]
@vmarchaud The information of this issue has been updated, I'm quite this is a issue and I think the root cause has been found. 
Thanks。

**Comment by vmarchaud** [comment]
What do you mean by a lock the daemon, the way pm2 works is that the CLI connect to the RPC server of the daemon via a socket file, if the CLI cant connect, it will spawn de process, how a 'lock' will change things for you exactly ?

**Comment by changev** [comment]
@vmarchaud I mean lock on **check existence of Daemon process**, only one cmd can check the  existence of Daemon process at one time.

**Comment by Hobbit44** [comment]
I'm having this issue as well, though I'm running in a docker container.
I think its related to having a non standard home directory.
I'm on a ubuntu:16.04 based image

steps to reproduce: 
```
[as root]
pm2 list
```
(runs fine)
```
useradd -U -d /app -s /bin/bash node 
su - node
pm2 list
``` 
(hangs)
```
useradd -U -m -s /bin/bash node2
su - node2
pm2 list
```
(runs fine)

**Comment by Unitech** [comment]
you should use the upcoming `pm2-runtime` inside containers

**Comment by dev-garcia** [comment]
Tentei muitas coisas, a solução foi remover o node que instalei com `snap` e instalar o node com o tutorial: https://nodejs.org/en/download/package-manager

Passo a passo do link, nele lista os seguintes comandos:

installs nvm (Node Version Manager)
`curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash`

download and install Node.js (you may need to restart the terminal)
`nvm install 20`

verifies the right Node.js version is in the environment
`node -v `

verifies the right NPM version is in the environment
`npm -v`

Após esses passos o comando `pm2` já começou a funcionar sem erros!
