### ISSUE TITLE
pm2 save without starting first

### ISSUE THREAD

**Issue by shaharmor** [Unitech/pm2#2504]
Hi,

We want to be able to `pm2 save` a state without first being in that state.

So if we have a file `processes.json`, we want to start all the processes listed there but only after a reboot.
Today we do:
```
pm2 start processes.json
pm2 save
```

but that causes the processes to run before we have time to reboot the server.

Any chance to do something like
`pm2 save processes.json` which will save the "future" state of those processes? or just start them after the reboot?

**Comment by vmarchaud** [comment]
You should be able to start the `processes.json` and do a `pm2 save` only once, should be good enough no ?

**Comment by shaharmor** [comment]
But I don't want the processes to start now, I want to to start after a reboot

**Comment by xtramath** [comment]
+1

**Comment by sa-0001** [comment]
This is something I also have been trying to do.  A suggestion: `pm2 create` which would have the same arguments as `pm2 start` but not actually start the process.

**Comment by lspiehler** [comment]
+1

**Comment by mz8i** [comment]
+1

**Comment by bitflut** [comment]
+1

**Comment by Unitech** [comment]
Feature landed

Update PM2 to 5.4.0

```bash
$ npm install pm2@5.4.0 -g
$ pm2 update
```
