### ISSUE TITLE
pm2 install with  --no-optional --no-shrinkwrap

### ISSUE THREAD

**Issue by lebretr** [Unitech/pm2#2507]
Hi,

I wand install pm2-logrotate but I am behind a proxy corp and I use a private registry.

I have installed pm2 with `--no-shrinkwrap --no-optional` options but I don't know how use this options with `pm2 install pm2-logrotate`

I test `pm2 install pm2-logrotate --no-optional --no-shrinkwrap` but i have an error  `error: unknown option `--no-optional'`

**Comment by vmarchaud** [comment]
PM2 install a module by spawning the `npm` executable. The solution is to do `git clone https://github.com/pm2-hive/pm2-logrotate && cd pm2-logrotate && pm2 install .`
