### ISSUE TITLE
Make pm2 generate actually helpful. 

### ISSUE THREAD

**Issue by Phara0h** [Unitech/pm2#2512]
Since there is no way to 'pm2 resurrect' pointing to any dump you saved off from another server, 'pm2 generate' should generate you a app.js based off your current running processes and configuration. 

#### Expected behaviour

'pm2 generate' should take your current running processes/configuration and generate you an app.js file with that information.

...

#### Actual behaviour
'pm2 generate' generates a generic sample file which is quite useless since you can get that from the documentation 
...

#### Steps to reproduce

type 'pm2 generate' and be disappointed with the results. 

...

#### Software versions used

```
OS         :
node.js    :
PM2        :
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
...
```

cf CONTRIBUTING.md for more informations

**Comment by vmarchaud** [comment]
You are asking for the command `pm2 save`, `pm2 generate` as been used in the past when there was not that much documentation.

**Comment by Phara0h** [comment]
It used to generate you a useful file and now it does not?

**Comment by vmarchaud** [comment]
It have been since the generated file [hasn't change](https://github.com/Unitech/pm2/blame/master/lib/templates/ecosystem.tpl) so i guess its not the case.
