### ISSUE TITLE
NPM in PM2 Configuration File?

### ISSUE THREAD

**Issue by therynamo** [Unitech/pm2#2514]
I've looked all over and can't seem to find answer on npm and the pm2 configuration file.

What I'm looking for:

```js
{
  apps : [{
    name        : "worker",

// Doing something like this
    script      : "npm start",

    watch       : true,
    env: {
      "NODE_ENV": "development",
    },
    env_production : {
       "NODE_ENV": "production"
    }
  }]
}
```

is this possible or no?

**Comment by vmarchaud** [comment]
We don't have this, `script ` conf entry is used to specify the path of the entry file (for example an `index.js`).

**Comment by therynamo** [comment]
Right, that much makes sense. I was just hoping that since pm2 has npm support via the CLI, there would be a way to do it in the configuration file. 

More or less I could see how it could be considered unnecessary since you could just run the command you start up with `npm start` in the `script: ` value. However, say my `npm start` does something in a "testing deployed" environment that enables different commands with npm start than our "prod" environment. It'd be easier to say `script: npm start` (it doesn't have to be a part of the `script` key/value, but something), than to make two different pm2 configuration files in order to run different scripts based upon environments. 

I'm just curious if it was in the books for you guys? If not, would it be something you'd like a PR for? Or does this seem like something you guys wouldn't like having?

**Comment by vmarchaud** [comment]
Actually we don't support directly `npm`, we support `.json` file declaration and retrieve apps definition in it, so you can put them in a `package.json` without problem.
We don't have really a roadmap yet, so its more likely via PR that this feature will be implemented.

Come over our slack [pm2.slack.io](pm2.slack.io) to discuss on how implementation details if you want.

**Comment by therynamo** [comment]
You'll have to forgive me, I was unable to follow the slack link, it seems to point to a non-existent github page. Maybe you have a direct invite link? 

I'd be up for discussing this further if it is something you and your team would find useful.

**Comment by vmarchaud** [comment]
@therynamo Edited with the correct link sorry

**Comment by Unitech** [comment]
To run npm start inside a process file:

```javascript
{
  apps : [{
    name        : "worker",
    script         : "npm",
    args          : "start",
    watch       : true,
    env: {
      "NODE_ENV": "development",
    },
    env_production : {
       "NODE_ENV": "production"
    }
  }]
}
```
