### ISSUE TITLE
Read shebang from executable as last resort

### ISSUE THREAD

**Issue by shubhamchaudhary** [Unitech/pm2#2517]
#### Expected behaviour
A file without (known) extension and having it's first line contain shebang (e.g. `#!/usr/bin/bash`), must start with bash

#### Actual behaviour
Throws js error (likely opening as node app)

#### Steps to reproduce
1. Remove extension from a shell script with shebang as first line
2. Run in cli, works fine
3. Run with pm2 - throws error

#### Software versions used
```
OS         :  Linux
PM2        : latest
```

**Comment by vmarchaud** [comment]
By default we are considering that the executable you want to run is a node project, if it isn't the case, refer to [the documentation](http://pm2.keymetrics.io/docs/usage/application-declaration/#general) to change interpreter (try using interpreter `none`).
