### ISSUE TITLE
pm2 delete won't stop the process

### ISSUE THREAD

**Issue by papmodern** [Unitech/pm2#2520]
I'm running a node server on port 3000. After deleting this process from pm2 and restarting it from the file,  the port 3000 is in use with a process ( if I kill that process its started again with another pid ). It seems pm2 is not deleted that process

**Comment by vmarchaud** [comment]
You might have another PM2 daemon running somewhere else on your computer. Check with `ps aux | grep PM2`.

**Comment by Unitech** [comment]
We also need your Node.js version, PM2 version

**Comment by papmodern** [comment]
The problem was the multiple pm2 process. I killed another one and my problem solved. Tnks.

**Comment by yinrong** [comment]
+1 encounter the problem.  but my server is used by many people, they sometimes run 'pm2' command on other users. What should I do other than write a 'monitor app' to kill pm2 instances from other users?

**Comment by laurencefass** [comment]
subscribing. pm2 doesnt kill processes and it would be great to have a delete+kill command.

**Comment by laurencefass** [comment]
subscribing. pm2 doesnt kill processes but startup procedures are aribtratily complex - often multiple processes are spawned from a single command for delete + kill to work pm2 would need access to a list of spawned processes from "start".
