### ISSUE TITLE
PM2 not deploying after git pull.

### ISSUE THREAD

**Issue by the-yadu** [Unitech/pm2#2521]
If reporting a bug, please use the following template.

#### Expected behaviour

It should do git pull in server and execute post deploy commands.

#### Actual behaviour

pm2 stucks after git pull and you cant ssh into server for more than 15 mins.

#### Steps to reproduce

...

#### Software versions used

```
OS         : from mac to linux
node.js    : v0.10.29
PM2        : 2.1.4
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
pm2 deploy ecosystem-production.json production
[PM2] Spawning PM2 daemon with pm2_home=/Users/narayan/.pm2
[PM2] PM2 Successfully daemonized
--> Deploying to production environment
--> on host preprod.ykone.com
  ○ deploying origin/master
  ○ executing pre-deploy-local
  ○ hook pre-deploy
  ○ fetching updates
Fetching origin
  ○ resetting HEAD to origin/master
HEAD is now at a613b66 Merged in staging (pull request #169)
  ○ executing post-deploy `grunt concat; grunt stylus; npm install;bower install;pm2 startOrRestart ecosystem-production.json --env production`
```

cf CONTRIBUTING.md for more informations

**Comment by vmarchaud** [comment]
Retry using debug mode : `pm2 kill && DEBUG=* pm2 ls`, reproduce the bug and paste the content of `~/.pm2/pm2.log` somewhere we can look at it.

**Comment by the-yadu** [comment]
I retied and got this output mate.

>  pm2:paths pm2 home resolved to /home/preprod/.pm2 +0ms /home/preprod
  pm2:conf Using 1 parallelism (CONCURRENT_ACTIONS) +7ms
  pm2:client Using RPC file /home/preprod/.pm2/rpc.sock +147ms
  pm2:client Using PUB file /home/preprod/.pm2/pub.sock +0ms
  pm2:interface:daemon Getting interaction info +0ms
  pm2:interface:daemon [PING INTERACTOR] Trying to connect to Interactor daemon +1ms
  axon:sock connect attempt null:/home/preprod/.pm2/interactor.sock +1ms
  pm2:client [PING PM2] Trying to connect to server +2ms
  axon:sock connect attempt null:/home/preprod/.pm2/rpc.sock +0ms
  axon:sock error ENOENT +3ms
  axon:sock ignored ENOENT +0ms
  axon:sock error ENOENT +0ms
  axon:sock ignored ENOENT +0ms
  axon:sock attempting reconnect +101ms
  axon:sock closing +0ms
  axon:sock closing 0 connections +0ms
  pm2:client Daemon not launched +1ms
  axon:sock connect attempt null:/home/preprod/.pm2/rpc.sock +0ms
  axon:sock attempting reconnect +0ms
  axon:sock closing +0ms
  axon:sock closing 0 connections +0ms
  pm2:interface:daemon Interactor Daemon not launched +0ms
  axon:sock connect attempt null:/home/preprod/.pm2/interactor.sock +1ms
[PM2] Spawning PM2 daemon with pm2_home=/home/preprod/.pm2
  axon:sock error ENOENT +5ms
  axon:sock ignored ENOENT +0ms
  axon:sock error ENOENT +0ms
  axon:sock ignored ENOENT +1ms
  pm2:client PM2 daemon launched with return message:  +247ms { online: true, success: true, pid: 29914, pm2_version: '2.1.4' }
  pm2:interface:daemon Interaction file does not exists +4ms
[PM2] PM2 Successfully daemonized
  pm2:client Launching RPC client on socket file /home/preprod/.pm2/rpc.sock +1ms
  axon:sock connect attempt null:/home/preprod/.pm2/rpc.sock +0ms
  axon:sock connect +0ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +2ms
  pm2:client RPC Connected to Daemon +0ms
  pm2:cli Now connected to daemon +11ms
  pm2:client Calling daemon method pm2:getVersion on rpc socket:/home/preprod/.pm2/rpc.sock +1ms
  pm2:client Calling daemon method pm2:getMonitorData on rpc socket:/home/preprod/.pm2/rpc.sock +3ms
  pm2:client Calling daemon method pm2:getMonitorData on rpc socket:/home/preprod/.pm2/rpc.sock +5ms
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
  axon:sock closing +5ms
  axon:sock closing 1 connections +0ms
  axon:sock remove socket 0 +1ms
  pm2:client PM2 RPC cleanly closed +0ms
  pm2:cli This command took 0.392s to execute +0ms

**Comment by vmarchaud** [comment]
I need to you to reproduce the bug with `DEBUG=*` set on the daemon, you just need to reproduce now and send me last lines of `~/.pm2/pm2.log`

**Comment by the-yadu** [comment]
This is what my local log says after trying the process with debug=*.

> 2016-11-14 16:04:27: ===============================================================================
2016-11-14 16:04:27: --- Stopping PM2 --------------------------------------------------------------
2016-11-14 16:04:27: Time                 : Mon Nov 14 2016 16:04:27 GMT+0530 (IST)
2016-11-14 16:04:27: ===============================================================================
Mon, 14 Nov 2016 10:34:27 GMT axon:sock closing
Mon, 14 Nov 2016 10:34:27 GMT axon:sock closing 2 connections
Mon, 14 Nov 2016 10:34:27 GMT axon:sock closing server
2016-11-14 16:04:27: RPC closed
Mon, 14 Nov 2016 10:34:27 GMT axon:sock closing
Mon, 14 Nov 2016 10:34:27 GMT axon:sock closing 0 connections
Mon, 14 Nov 2016 10:34:27 GMT axon:sock closing server
2016-11-14 16:04:27: PUB closed
2016-11-14 16:04:27: PM2 successfully stopped
Mon, 14 Nov 2016 10:34:27 GMT axon:sock disconnect /Users/narayan/.pm2/rpc.sock
Mon, 14 Nov 2016 10:34:27 GMT axon:sock remove socket 1
Mon, 14 Nov 2016 10:34:27 GMT axon:sock disconnect /Users/narayan/.pm2/rpc.sock
Mon, 14 Nov 2016 10:34:27 GMT axon:sock remove socket 0
Mon, 14 Nov 2016 10:34:28 GMT pm2:paths pm2 home resolved to /Users/narayan/.pm2 /Users/narayan
Mon, 14 Nov 2016 10:34:28 GMT pm2:conf Using 2 parallelism (CONCURRENT_ACTIONS)
Mon, 14 Nov 2016 10:34:28 GMT axon:sock bind null:/Users/narayan/.pm2/pub.sock
Mon, 14 Nov 2016 10:34:28 GMT axon:sock bind null:/Users/narayan/.pm2/rpc.sock
2016-11-14 16:04:28: ===============================================================================
2016-11-14 16:04:28: --- New PM2 Daemon started ----------------------------------------------------
2016-11-14 16:04:28: Time                 : Mon Nov 14 2016 16:04:28 GMT+0530 (IST)
2016-11-14 16:04:28: PM2 version          : 2.1.4
2016-11-14 16:04:28: Node.js version      : 4.1.1
2016-11-14 16:04:28: Current arch         : x64
2016-11-14 16:04:28: PM2 home             : /Users/narayan/.pm2
2016-11-14 16:04:28: PM2 PID file         : /Users/narayan/.pm2/pm2.pid
2016-11-14 16:04:28: RPC socket file      : /Users/narayan/.pm2/rpc.sock
2016-11-14 16:04:28: BUS socket file      : /Users/narayan/.pm2/pub.sock
2016-11-14 16:04:28: Application log path : /Users/narayan/.pm2/logs
2016-11-14 16:04:28: Process dump file    : /Users/narayan/.pm2/dump.pm2
2016-11-14 16:04:28: Concurrent actions   : 2
2016-11-14 16:04:28: SIGTERM timeout      : 1600
2016-11-14 16:04:28: ===============================================================================
Mon, 14 Nov 2016 10:34:28 GMT axon:sock accept /Users/narayan/.pm2/rpc.sock
Mon, 14 Nov 2016 10:34:28 GMT axon:sock add socket 0
Mon, 14 Nov 2016 10:34:28 GMT axon:sock disconnect /Users/narayan/.pm2/rpc.sock
Mon, 14 Nov 2016 10:34:28 GMT axon:sock remove socket 0
Mon, 14 Nov 2016 10:34:28 GMT axon:sock accept /Users/narayan/.pm2/rpc.sock
Mon, 14 Nov 2016 10:34:28 GMT axon:sock add socket 0

**Comment by vmarchaud** [comment]
I don't see any logs that state that you tried to pull something ?

**Comment by the-yadu** [comment]
I am running this command 
`pm2 deploy ecosystem-production.json production`
and then I copy pasted the log file from local machine. 

Could you please help me to produce logs. I am super new to pm2.

**Comment by vmarchaud** [comment]
I'll need pm2 logs on the remote server so

**Comment by the-yadu** [comment]
This is pm2 logs in sever.

> 2016-11-14 11:33:05: Stopping app:campaygn-v3-production id:1
2016-11-14 11:33:05: App [campaygn-v3-production] with id [1] and pid [31122], exited with code [0] via signal [SIGINT]
2016-11-14 11:33:05: pid=31122 msg=process killed
2016-11-14 11:33:05: Starting execution sequence in -fork mode- for app name:campaygn-v3-production id:1
Mon, 14 Nov 2016 10:33:05 GMT pm2:fork_mode stds: {"out":"/home/preprod/campaygn_v3/production/source/campaygn-v3-production-out-1.log","err":"/home/preprod/campaygn_v3/production/source/campaygn-v3-production-error-1.log"}
2016-11-14 11:33:05: App name:campaygn-v3-production id:1 online
2016-11-14 11:33:05: Stopping app:campaygn-v3-workers-production id:2
2016-11-14 11:33:05: App [campaygn-v3-workers-production] with id [2] and pid [31126], exited with code [0] via signal [SIGINT]
2016-11-14 11:33:06: pid=31126 msg=process killed
2016-11-14 11:33:06: Starting execution sequence in -fork mode- for app name:campaygn-v3-workers-production id:2
Mon, 14 Nov 2016 10:33:06 GMT pm2:fork_mode stds: {"out":"/home/preprod/campaygn_v3/production/source/campaygn-v3-workers-production-out-2.log","err":"/home/preprod/campaygn_v3/production/source/campaygn-v3-workers-production-error-2.log"}
2016-11-14 11:33:06: App name:campaygn-v3-workers-production id:2 online
Mon, 14 Nov 2016 10:33:06 GMT axon:sock disconnect /home/preprod/.pm2/rpc.sock
Mon, 14 Nov 2016 10:33:06 GMT axon:sock remove socket 0

**Comment by vmarchaud** [comment]
No error again, please try to reproduce the issue with a basic example so i can reproduce it on my side.
