### ISSUE TITLE
Unknown Request /client

### ISSUE THREAD

**Issue by sateesh2020** [Unitech/pm2#2525]
Hi Team, After starting the node application with pm2, there is a hit to /client continuously for every second, but none of my client are requesting for this URL. Is this due to some configuration issues.
In my server.js i am using an express middle ware 
```sh
app.use(express.static('client'))
```
Is this a reason for that call, cause i am not facing this issue if i use forever or nodemon

#### Software versions used

```
OS         : Windows 
node.js    : 4.4.4
PM2        : 1.0.0
```

#### PM2 Log output

{"level":"info","message":"Logged In User undefined","timestamp":"2016-11-01T21:32:18.664Z"}
{"level":"info","message":"HEAD /client 404 20 - 0.268 ms\n","timestamp":"2016-11-01T21:32:18.665Z"}
{"level":"info","message":"Logged In User undefined","timestamp":"2016-11-01T21:32:23.673Z"}
{"level":"info","message":"HEAD /client 404 20 - 0.305 ms\n","timestamp":"2016-11-01T21:32:23.674Z"}
{"level":"info","message":"Logged In User undefined","timestamp":"2016-11-01T21:32:28.689Z"}
{"level":"info","message":"HEAD /client 404 20 - 0.410 ms\n","timestamp":"2016-11-01T21:32:28.690Z"}
{"level":"info","message":"Logged In User undefined","timestamp":"2016-11-01T21:32:33.698Z"}
{"level":"info","message":"HEAD /client 404 20 - 0.301 ms\n","timestamp":"2016-11-01T21:32:33.699Z"}
{"level":"info","message":"Logged In User undefined","timestamp":"2016-11-01T21:32:38.707Z"}
{"level":"info","message":"HEAD /client 404 20 - 0.286 ms\n","timestamp":"2016-11-01T21:32:38.708Z"}

**Comment by vmarchaud** [comment]
Can you try with latest pm2 version ? `npm install -g pm2 && pm2 update`

**Comment by vmarchaud** [comment]
Closing cause no update, reopen if you have more informations.
