### ISSUE TITLE
PM2 Deploy cant ready from remote repository

### ISSUE THREAD

**Issue by Nerfair** [Unitech/pm2#2527]
I try to deploy my pm2 server to production with 

    pm2 deploy server.json production setup

but getting this:

    --> Deploying to production environment
    --> on host chat.lt
        ○ hook pre-setup
        ○ running setup
        ○ cloning ssh://git@host.lt:7999/ch/socket.git
        Cloning into '/srv/www/socket/source'...
        ssh: connect to host host.lt port 7999: Connection timed out
        fatal: Could not read from remote repository.
    
    Please make sure you have the correct access rights
    and the repository exists.
    
    failed to clone
    
    Deploy failed

my server.json is

    {
      "apps": [
        {
          "name": "server",
          "script": "nodejs_server.js",
          "instances": 8,
          "exec_mode": "cluster",
          "max_memory_restart": "2G",
          "merge_logs": true,
          "log_date_format": "MM-DD HH:mm:ss"
        }
      ],
      "deploy" : {
        "production" : {
          "user" : "root",
          "host" : "chat.lt",
          "ref" : "origin/master",
          "repo" : "ssh://git@host.lt:7999/ch/socket.git",
          "path" : "/srv/www/socket",
          "post-deploy" : "pm2 startOrRestart server.json --env production"
        }
      }
    }

and the main problem is what i have ssh key on machine from which i run pm2 deploy, and i can use it perfectly with host.lt repository (git clone, git push, and so on works fine), the only problem is pm2 deploy

**Comment by vmarchaud** [comment]
Connectivity problem with your distant git repo, pm2 deploy just spawn the git binary to pull it. Try cloning directly on your remote server.

**Comment by Nerfair** [comment]
Ah, so it's connecting to remote chat.lt with user root, and then tries to clone? If so case solved, because on remote chat.lt it is true what i can't use git. Thank you.
