### ISSUE TITLE
for express, should pm2 start app.js or bin/www?

### ISSUE THREAD

**Issue by jiajianrong** [Unitech/pm2#2528]
I failed with the former but succeed with latter. I see the bin/www has content like below:

```
var app = require('../app');
var debug = require('debug')('trace_jinrong_58:server');
var http = require('http');

var port = normalizePort(process.env.PORT || '3000');
app.set('port', port);

var server = http.createServer(app);

server.listen(port);
server.on('error', onError);
server.on('listening', onListening);
```

Seems it creates http server in bin/www. 
When using 'pm2 start app.js', the process indeed started but I don't know the port.
How should I do to current use 'pm2 start app.js'? Thanks

**Comment by jiajianrong** [comment]
Seems this is a desired change from express 3 to express 4 - creating http server is moved from app.js to bin/www.  But the pm2 releted document hasn't updated accordingly.
I suppose I should either  1) use  'pm2 start bin/www'   or   2)   append 

```
app.set('port', process.env.PORT || 3000);
var server = app.listen(app.get('port'), function() {
  debug('Express server listening on port ' + server.address().port);
});
```

**Comment by vmarchaud** [comment]
PM2 examples aren't focused on express, we just make a generic name. You should use pm2 start with the entry point of your application, in your case `bin/www`
