### ISSUE TITLE
pm2 is unable to resolve correctly "~" while deploying with an ecosystem.json

### ISSUE THREAD

**Issue by AndoniMartin** [Unitech/pm2#2534]
If reporting a bug, please use the following template.

#### Expected behaviour

With the pm2 version 1.0.1 our path for the deploy was set like:

"path": "~/opt/name/app/develop"

the path was resolved correctly to the home of the remote server and the application was successfully deployed.

#### Actual behaviour

The path is instead resolved as:

 "/home/user/Projects/name/~/opt/name/app/testing/source" being  "/home/user/Projects/name/" the current path where the application is being launched from.

#### Steps to reproduce

Set a relative path using the "~" symbol in a currently working deploy in the ecosystem.json "path" section for a concise deploy, e.g.:
 
```
"testing": {
            "user": "user",
            "host": process.env.HOSTS ? JSON.parse(process.env.HOSTS) : [],
            "ref": "origin/testing",
            "repo": "ssh://valid-ssh",
            **"path": "~/opt/name/app/testing",**
            "post-deploy": "bash ./deploy.sh testing",
            "env": {
                "ENV": "testing",
                "LOGLEVEL": "debug"
            }
        }
```

#### Software versions used

```
OS         :  (Origin OS) Linux 4.8.0-1-amd64 Debian 4.8.5-1 x86_64
                 Linux, Mac and Windows 10 as remote machines.
node.js    : v5.6.0 (also tested with newer versions, 6.9.0 and the latest 7 version)
PM2        :  2.1.5
```

#### PM2 Log output
(Command:  pm2 deploy ecosystem.json testing setup --force)

--> Deploying to testing environment
--> on host 192.168.13.12
  ○ hook pre-setup
  ○ running setup
  ○ cloning ssh://valid-ssh
Enter passphrase for key '/home/user/.ssh/id_rsa': 
Cloning into '/home/user/Projects/name/~/opt/name/app/testing/source'...

**Comment by vmarchaud** [comment]
Can you come over our slack (http//slack.pm2.io) to test something please ?
Thanks

**Comment by AndoniMartin** [comment]
Hello @vmarchaud, for sure, I've just requested an invite. Thank you!

**Comment by Unitech** [comment]
@vmarchaud we may want to use the  ~ resolving method (https://github.com/Unitech/pm2/commit/c1b083c5923b2b6b6783f6f7feb25b8e3c3e39d7) for this path attribute

**Comment by vmarchaud** [comment]
should work since we merged [this commit](https://github.com/Unitech/pm2-deploy/commit/295fa35dd40a143f91255e72173f0972b3ddd0fd)
