### ISSUE TITLE
Argument parsing fails on certain characters

### ISSUE THREAD

**Issue by nfantone** [Unitech/pm2#2535]
Setting some values as command line arguments for an app (after `--`), makes them disappear entirely.

#### Expected behaviour
Starting an application like this:

```sh
NODE_ENV=live pm2 start -f app.js --hostname=0.0.0.0 --jwt.options.secret=>wsAMQEK77tbh2r^
```

Should show an `info` output such as:

```sh                        │
│ script args       │ --hostname=0.0.0.0 --jwt.options.secret=>wsAMQEK77tbh2r^ │
```

#### Actual behaviour

`--hostname` gets set correctly. But, the value for `--jwt.options.secret` just gets swallowed as if no value would have been set after `=`.

```sh
│ script args       │ --hostname=0.0.0.0 --jwt.options.secret= |
```

Incidentally, wrapping the value around with `"` (double quotes) works as expected and it actually _strips_ the `"` characters.

#### Software versions used

```
OS         :  macOS Sierra `10.12.1` (16B2555)
node.js    : `6.9.1`
PM2        : `2.1.5`
```

**Comment by vmarchaud** [comment]
We are using the `commander` module to handle CLI parsing so i think it should be more appropriate in [their repo ](https://github.com/tj/commander.js).

**Comment by Unitech** [comment]
There is a special caracter in the arguments you are passing "<"

Do this instead:

```
NODE_ENV=live pm2 start -f app.js -- --hostname=0.0.0.0 --jwt.options.secret=">wsAMQEK77tbh2r^"
```

**Comment by nfantone** [comment]
@Unitech I am certainly aware of that. It's on the issue description:

> Incidentally, wrapping the value around with " (double quotes) works as expected and it actually strips the " characters.

But that's not a solution. It's a workaround for a non deterministic behaviour. It gets worse if params are dynamic and are built using some kind of logic.

@vmarchaud I know that. But it was worth trying out this repo first as it may be related to some display logic on the `info` command or something else. Thanks for the tip, anyway. I'll go ahead and open a new issue over here.

**Comment by vmarchaud** [comment]
Are you sure your shell isn't interpreting this `>` by redirecting the stdout to a file ?

**Comment by nfantone** [comment]
@vmarchaud No, sorry, I'm not. It could very well be the case.
