### ISSUE TITLE
installing pm2 on ubuntu 14.04

### ISSUE THREAD

**Issue by kamil7732** [Unitech/pm2#2536]
http://stackoverflow.com/questions/40799533/bash-pm2-command-not-found/

just letting you know

**Comment by soyuka** [comment]
The origin path was not in your `PATH` variable then?

**Comment by kamil7732** [comment]
you know, it was under linux. also I just name npm install pm2 -g or how it was...so it should run smoothly but it didn't

**Comment by soyuka** [comment]
This is an issue with nodejs not linking the correct path then no? All we do here is setting `bin` in the [package.json](https://github.com/Unitech/pm2/blob/master/package.json#L9). I don't see why it won't work seamlessly except if it's a matter of how nodejs was installed
