### ISSUE TITLE
npm start script support via API

### ISSUE THREAD

**Issue by nite** [Unitech/pm2#2542]
Related to this issue (closed) 
https://github.com/Unitech/pm2/issues/1317
we'd like to be able to run npm script via the pm2 api
eg. 
` pm2.start({ script    : 'npm start' ...} `
This results in an error: 
`Error: script not found : /path/to/cwd/npm start`

**Comment by soyuka** [comment]
I think that you have to use `{script: 'npm',  scriptArgs: ['start']}`

**Comment by nite** [comment]
`script: 'npm',  args: [ 'start' ] ` works - thanks!
