### ISSUE TITLE
process started with pm2 api inherit wrong exit_code env value

### ISSUE THREAD

**Issue by beniboy87** [Unitech/pm2#2545]
If reporting a bug, please use the following template.

#### Expected behaviour
If I start a process with the PM2 API from another process, that was started with PM2 also, then if the first fails and restarts, the newly started processes should not inherit the exit_code environment value. 
...

#### Actual behaviour
I am using a scheduler process to start worker processes. I am running this scheduler with PM2, and if I restart this scheduler with pm2 restart scheduler or it gives a process.exit(2) for example (and it autorestarts), then when I'm starting a new worker process, it will inherit the process.exit code from the crash, or from the restart (pm2 restart kills with code 1). If I get the pm2 list, the exit_code is there in the process object.
...

#### Fix that worked for me
I was able to fix this in PM2 code - putting exit_code into the keysToIgnore array in Common.js solved it,  like the autorestart in this commit: https://github.com/Unitech/pm2/commit/0f7a10e1e0aa9bf1137a60a042b9250bd62affb7

I think the exit_code should be there as well.
...

#### Software versions used

```
OS         : Ubuntu LTS, Windows 10, Mac OS X El Capitan
node.js    : 6.9.1 and 4.x branch latest
PM2        : 2.1.5
```

**Comment by Unitech** [comment]
Published

```bash
$ npm install pm2@next -g
$ pm2 update
```
