### ISSUE TITLE
how to setup pm2 to restart automatically upon server restart and start the node process ?

### ISSUE THREAD

**Issue by jpca999** [Unitech/pm2#2546]
I have my code located at /home/ubuntu/properties-Docker-capi
I usually use gulp prod to start the server which takes care of minification stuff. 
How do i get the $gulp prod command run by pm2 ?

$ which node
/usr/bin/node

**Comment by vmarchaud** [comment]
Please read documentation before making an issue : http://pm2.keymetrics.io/docs/usage/startup/
