### ISSUE TITLE
use jmeter do pressure test,node.js cpu is very high,can you helpe me?

### ISSUE THREAD

**Issue by chelsh** [Unitech/pm2#2549]
host: cpu:16 core, ram:16G

https://dn-cnode.qbox.me/Fr2OH0MQjxlZCuB9N8QKIk0rhjlc

**Comment by vmarchaud** [comment]
Can you please explain what is the problem with pm2 exactly  ?

**Comment by vmarchaud** [comment]
Re-open if you got detailed problem.
