### ISSUE TITLE
pm2 programmatic api appends cwd even for absolute path

### ISSUE THREAD

**Issue by aniketdd** [Unitech/pm2#2550]
pm2.start('D:\process.json', 
    function(errStart, apps) {
      if (errStart) {
        console.log(errStart);
        throw errStart;
      }
      console.log('app started on pm2');
    });

gives error as : 
Error: ENOENT: no such file or directory, open 'C:\Users\Admin\projects\D:\process.json'

Works fine in v1.1.3.

**Comment by vmarchaud** [comment]
You should use a json object and define `cwd` to avoid this problem.
