### ISSUE TITLE
PMX with nodejs-cluster module [feature request][bug]

### ISSUE THREAD

**Issue by benishak** [Unitech/pm2#2552]
#### Expected behaviour

PMX and Keymetrics should be able to monitor worker processes

#### Actual behaviour

when using nodejs-cluster module, node creates 1 master process but 2 workers, workers handle everything, but PMX and Keymetrics track only the master process which actually does nothing.
PMX and Keymetrics show only information from the master process (CPU, Memory Usage, HTTP ...etc) HTTP is always 0ms, because the master doesn't handle any requests.

#### Steps to reproduce

require cluster and fork some workers based on your CPU counts and check the values from PMX or check Keymetrics dashboard

#### Software versions used

```
OS         : CentOS 7
node.js    : 6.9.1
PM2        : 2.1.6
```

#### why not use pm2 cluster mode ?
Some part of our app is unfortunately not stateless, we have some cronjobs that are stored in the memory, sometime things get executed twice ... We use node cluster module and try to execute these from the master process.

**Comment by vmarchaud** [comment]
Are you sure that you required pmx on worker too ?

**Comment by benishak** [comment]
I require pmx at the top of my `server.js` file

```
var pmx = require('pmx').init({
  http          : true,
  ignore_routes : [],
  errors        : true, // Exceptions loggin (default: true)
  custom_probes : true, // Auto expose JS Loop Latency and HTTP req/s as custom metrics
  network       : true, // Network monitoring at the application level
  ports         : true  // Shows which ports your app is listening on (default: false)
});
var express = require('express');
app = express();

// initialize app ....

// ... other variable
if (cluster.isMaster) {
       // fork workers here
} else {
      app.listen();
}
```

should I move the pmx deceleration inside the `if (cluster.isMaster) { ... }` ?

But beside the PMX thing, PM2 seems to only monitor the master as in CPU the CPU is around 0-1% and memory usage is not changing but I can see in `htop`  something like this
```
------------------------------------------------ MEM
- node server.js ( master)                                75M
|--- node server.js (worker)                             350M
|--- node server.js (worker)                             350M
```

MEM and CPU of workers are always changing, I can only see that in `htop` but not in `pm2`

**Comment by vmarchaud** [comment]
I advise run your process under `pm2 cluster` and trigger your cron using customs actions and triggering them using `pm2 trigger` inside a crontab.
You should have your data reported on all workers since the pmx.require is always required anyway so i guess it will stay a weird issue.
