### ISSUE TITLE
`exec` returns invalid environment variable

### ISSUE THREAD

**Issue by xpepermint** [Unitech/pm2#2554]
This commands

```
./node_modules/.bin/pm2 deploy production exec 'echo $PATH'
./node_modules/.bin/pm2 deploy ecosystem.json production run "echo $PATH"
```

print a value of the $PATH environment variable of my *local* machine. It should return a value of the $PATH variable on the remote server.

`pm2 v2.1.6, osx -> linux`

**Comment by vmarchaud** [comment]
Please open an issue over https://github.com/Unitech/pm2-deploy

**Comment by xpepermint** [comment]
ok
