### ISSUE TITLE
pm2 starts node app correctly , but I am not able to access the app in browser

### ISSUE THREAD

**Issue by Bhushan001** [Unitech/pm2#2555]
I have installed pm2 using `npm install -g pm2` on my windows 10 x64.

I have a node app which I run using command `npm start`.

I wanted to profile that app , so I ran `pm2 start app.js`.

I can see in the console that pm2 starts process correctly. Now When I open the browser and type address as `http://localhost:3000` , my node app is not found.

I have checked & app runs fine when I run my app using `npm start`.

any inputs?

**Comment by vmarchaud** [comment]
Check logs of your app in `/.pm2/logs/` and pm2 log in `~/.pm2/pm2.log`

**Comment by Unitech** [comment]
To run npm start with pm2:

```
$ pm2 start npm -- start
```
