### ISSUE TITLE
Starting pm2 with npm start parameter

### ISSUE THREAD

**Issue by aneeven** [Unitech/pm2#2557]
Hey,

I ran into an issue starting pm2 via an npm script using a ecosystem.json.

I use shipit for my deployments and according to the documentation on capistrano like deployments ([here](http://pm2.keymetrics.io/docs/tutorials/capistrano-like-deployments)) I should start pm2 from the project root and point to `current/ecosystem.json` so it doesn't get confused by following symlinks.

So far so good, but I need to run `npm start`. 
How would I do that, if I don’t have a specific js file to start from in my script?

```
# ecosystem.json
{
  "apps": [{
    "name": "app",
    "script": "?",
    "cwd": "/var/www/html/site/current",
    "error_file": "./logs/app.err.log",
    "out_file": "./logs/app.out.log", 
    "exec_mode": "fork_mode"
  }]
}
```

Any ideas? I can't seem to figure it out.

Thanks!

**Comment by vmarchaud** [comment]
Just put `{script: 'npm', scriptArgs: ['start']}` and it shoud works.
