### ISSUE TITLE
how to delete all apps and let next app id start with 0 or 1

### ISSUE THREAD

**Issue by shuperry** [Unitech/pm2#2560]
I install a pm2 module `pm2-logrotate`, then when i run `pm2 delete all`, when i start next app, id is still increasing, not starts with 0 or 1

**Comment by vmarchaud** [comment]
You just use the name to make action on application at runtime, ID are volatile and never the same.
If you want you can set a custom log path to be sure that it always the same (if you want all the logs of your application to be in the same file.
