### ISSUE TITLE
PM2 doesn't inherit admin permission to child process which created fork mode.

### ISSUE THREAD

**Issue by greenfrog82** [Unitech/pm2#2561]
I'm developing web service using node.js on windows 10. I have a requirement which open port entered by user to default windows firewall. So I have written code and test successfully. 

Finally, I have executed my code on PM2. But My code doesn't work well this time. I have found reason why PM2 doesn't inherit admin permission to child process which created fork mode. When my code work well, I run my code on CMD which is running as administrator permission. But When my code doesn't work well, I run my code on PM2 on CMD which is running as administrator permission.

So, I guess ... PM2 doesn't inherit admin permission to child process which created fork mode.

I have rewrite my code to test efficiently to you. This code will write 'pm2_test_permission.log' file to c:\ which need admin permission to write file. Please see the follow link ...

[permission-problem](https://github.com/greenfrog82/study/tree/master/node.js/PM2/permission-problem)

#### Expected behaviour

It must have written 'pm2_test_permission.log' to c:\pm2_test_permission.log.
...

#### Actual behaviour

It can't have written 'pm2_test_permission.log' to c:\pm2_test_permission.log.
...

#### Steps to reproduce

Execute 'run-with-pm2-a.cmd file on [permission-problem](https://github.com/greenfrog82/study/tree/master/node.js/PM2/permission-problem)

...

#### Software versions used

```
OS         : Windows 10
node.js    : v6.9.1
PM2        :  2.1.6
```

#### PM2 Log output

```
Error: EPERM: operation not permitted, open 'c:\pm2_test_permission.log'
    at Error (native)
Error: EPERM: operation not permitted, open 'c:\pm2_test_permission.log'
    at Error (native)
Error: EPERM: operation not permitted, open 'c:\pm2_test_permission.log'
    at Error (native)
Error: EPERM: operation not permitted, open 'c:\pm2_test_permission.log'
    at Error (native)
Error: EPERM: operation not permitted, open 'c:\pm2_test_permission.log'
    at Error (native)
Error: EPERM: operation not permitted, open 'c:\pm2_test_permission.log'
    at Error (native)
Error: EPERM: operation not permitted, open 'c:\pm2_test_permission.log'
    at Error (native)
Error: EPERM: operation not permitted, open 'c:\pm2_test_permission.log'
    at Error (native)
Error: EPERM: operation not permitted, open 'c:\pm2_test_permission.log'
    at Error (native)
Error: EPERM: operation not permitted, open 'c:\pm2_test_permission.log'
    at Error (native)
Error: EPERM: operation not permitted, open 'c:\pm2_test_permission.log'
    at Error (native)
Error: EPERM: operation not permitted, open 'c:\pm2_test_permission.log'
    at Error (native)
Error: EPERM: operation not permitted, open 'c:\pm2_test_permission.log'
    at Error (native)
Error: EPERM: operation not permitted, open 'c:\pm2_test_permission.log'
    at Error (native)
Error: EPERM: operation not permitted, open 'c:\pm2_test_permission.log'
    at Error (native)
Error: EPERM: operation not permitted, open 'c:\pm2_test_permission.log'
    at Error (native)

```

cf CONTRIBUTING.md for more informations

**Comment by vmarchaud** [comment]
Must come from Windows itself since we are spawning a child process, i guess it should give the admin right to the child process too ?

**Comment by greenfrog82** [comment]
Yes, When I execute PM2 as admin permission, Child process spawned by PM2 must have admin permission.

**Comment by vmarchaud** [comment]
What i was trying to point is that maybe the child process doesn't inherit permission even if the master process has permission and thats behavior come from the windows kernel ?

**Comment by greenfrog82** [comment]
I have been windows programmer for 9 years.  Inheriting admin permission to child process is responsibility of windows kernel. But this behavior is set by programmer using option of WIN32 API. Could you handle WIN32 API?

**Comment by vmarchaud** [comment]
I'll check in the NodeJs API docs but from memory its nodejs that handle win32 API calls.

**Comment by greenfrog82** [comment]
Let me know code which fork child process on PM2 and I'll check API. If it is possible, I will modify this code to inherit admin permission to child process.

**Comment by vmarchaud** [comment]
Fork mode is [here](https://github.com/Unitech/pm2/blob/master/lib/God/ForkMode.js#L94) and there is the nodejs api [docs](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options)

**Comment by vmarchaud** [comment]
From what i saw its impossible, sorry.
