### ISSUE TITLE
start using npm

### ISSUE THREAD

**Issue by TrejGun** [Unitech/pm2#2562]
#### Steps to reproduce

Here is my ecosystem.json

```json
{
  "apps": [
    {
      "name": "App",
      "script": "app.js",
      "exec_mode": "fork",
      "exec_interpreter": "node_modules/.bin/babel-node",
      "env": {
        "NODE_ENV": "development"
      }
    }
  ]
}
```

when I run it with 
```bash
node_modules/.bin/pm2 start ecosystem.json
```
it works just fine
and creates a log file `Main-error-0.log` starting from upper case `M`

but when I run it with npm

package.json
```json
    "start": "node_modules/.bin/pm2 start ecosystem.json"
```

```bash
npm start
```

it can't find `babel-node`
and creates a log file `main-error-0.log` starting from lower case `m`

#### Actual behaviour
crashes
```
~/app.js:1
(function (exports, require, module, __filename, __dirname) { import xxx from "xxx";
                                                              ^^^^^^
SyntaxError: Unexpected token import
```

#### Expected behaviour
should start my app

#### Software versions used

```
OS          : mac os
node.js     : 7.0.0
npm         : 4.0.1
PM2         : 2.1.6
```

#### PM2 Log output
```
...
2016-12-07 11:13:44: Starting execution sequence in -fork mode- for app name:app id:0
2016-12-07 11:13:44: App name:app id:0 online
2016-12-07 11:13:44: App [app] with id [0] and pid [6340], exited with code [1] via signal [SIGINT]
...
2016-12-07 11:13:44: Script ~/app.js had too many unstable restarts (16). Stopped. "errored"
```

I have tried to use full path at `exec_interpreter`, `cwd` and `interpreter_args`, but it still looses context somehow

Can you help me to debug? how can I check what arguments pm2 uses when spawning processes?

**Comment by vmarchaud** [comment]
Please search before next time, see #2557 #2542

**Comment by TrejGun** [comment]
@vmarchaud 
Thanks for you reply 

You are telling me how to run `npm start` from ecosystem.json
so if I have more then one app I will end up with

package.json
```
"scripts": {
    "start:app1": "..."
    "start:app2": "..."
}
```

and ecosystem.json
```js
{
  "apps": [
    {
      "script": "npm",
      "args": [ "start:app1" ]
    }, {
      "script": "npm",
      "args": [ "start:app2" ]
    }
  ]
}
```
and then
```
pm2 start ecosystem.json
```

I don't wont this, I want to run `npm start` and run all apps listed in ecosystem.json

**Comment by vmarchaud** [comment]
I don't get your point, why aren't you using the PM2 CLI to start the applications ?

**Comment by TrejGun** [comment]
@vmarchaud
I want to have pm2 as a local npm so it is in devDependencies
Now if I want to use it I have to type
```bash
node_modules/.bin/pm2 start ecosystem.json
```
which is too long
so I want to configure `npm start` to run my `ecosystem.json`
```
"start": "node_modules/.bin/pm2 start ecosystem.json"
```
but as I said in the first message `exec_interpreter` can't find `babel-node`

**Comment by vmarchaud** [comment]
You may need to put `cwd` in the configuration file.

**Comment by TrejGun** [comment]
thanks :)
