### ISSUE TITLE
Install PM2 from sources

### ISSUE THREAD

**Issue by xarrdastop** [Unitech/pm2#2565]
Hello! How can I install PM2 from source code (downloaded from github) on Linux Mint 18?
I've limited network connection, so I can't install this from network by npm.
What's steps I must do to install it? 
Thanks. Best regards.

**Comment by soyuka** [comment]
You just need its dependecies:

```
git clone https://github.com/Unitech/pm2 --depth=1
cd pm2
npm install --production
cd ..
tar -cvzf pm2-2.1.6.tar.gz pm2
```

To use it, add `./bin/pm2` to your `$PATH`.

[pm2-2.1.6.tar.gz](https://github.com/Unitech/pm2/files/639617/pm2-2.1.6.tar.gz)

**Comment by vmarchaud** [comment]
You can ask npm to add it to its repo by running `npm link` in the npm folder.
