### ISSUE TITLE
 ''pm2' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by DevinThePancake** [Unitech/pm2#2566]
i was already installed pm2 in my system using npm,But whenever iam trying to run pm2 commands it is showing error like ''pm2' is not recognized as an internal or external command,
operable program or batch file.Please give me the solution for this

#### Software versions used

```
OS         : win 10
node.js    : latest
PM2        : latest
```

**Comment by vmarchaud** [comment]
Verify that npm repo is in your PATH, if not just add it and it should works.

**Comment by DevinThePancake** [comment]
Ok and there is not a specific file in pm2 I'm putting in path right? Just the folder pm2?

**Comment by vmarchaud** [comment]
The `bin` folder of pm2

**Comment by DevinThePancake** [comment]
Ok I did it but I still get the same error for some reason :/

**Comment by DevinThePancake** [comment]
It's in path and everything but it's still unrecognizable:/

**Comment by DevinThePancake** [comment]
Ok I've tried many things, I've tried moving the file somewhere else, I've tried installing the zip, tried to put it in another folder but it still won't recognize pm2.

**Comment by vmarchaud** [comment]
Try `git clone https://github.com/Unitech/pm2 && cd pm2 && npm link`, if its still not working it comes from your environment.

**Comment by Yoruba** [comment]
Had the same problem. See my answere on [Stackoverflow](https://stackoverflow.com/questions/41872620/no-able-to-run-pm2-on-windows-server-2012/53884599#53884599)

**Comment by dkduyanh** [comment]
Same problem on windows server 2019 with administrative account. Normal user account works fine!

**Comment by juloko** [comment]
@Eugenio161288, when you come to Brazil, I'll pay u a beer. 

`npm install pm2 -g` works for me.

For you, you have to put at `PATH` in enviromental variables this path `C:\Program Files\nodejs\`.
WIN + PAUSE BREAK> Advanced Configurations of System>Enviromental Variables>NEW> add above
...

**Comment by radhika0811** [comment]
@julioflima Thanks, that worked for me as well.

**Comment by xinthose** [comment]
After I ran `npm i pm2 -g`, I had to close my Node.js command prompt and re-open it, then `pm2 ls` worked.

**Comment by 0826240270** [comment]
If u using yarn u need to add --prefix ...path like docs https://classic.yarnpkg.com/en/docs/cli/global to direct global environment variable. U can use npm install -g pm2 will automatically add for u

**Comment by chiavj** [comment]
> `npm install pm2 -g`

this actually works, man. thank you.
