### ISSUE TITLE
PM2 version warning in each operation

### ISSUE THREAD

**Issue by mustafamamun** [Unitech/pm2#2572]
I have installed the latest version of PM2(2.1.6). Then I had to downgrade the version to 1.1.3. Now for every operation I am getting this error with the real data.

>>>> In-memory PM2 is out-of-date, do:
>>>> $ pm2 update
In memory PM2 version: 2.1.6
Local PM2 version: 1.1.3

Is there any way to get only the real data and avoid the warning.

**Comment by vmarchaud** [comment]
The problem come from the fact that the CLI version and the daemon version are different, you just need to downgrade the CLI version using npm : `npm install -g pm2@1.1.3`
