### ISSUE TITLE
How to update config without doing pm2 kill

### ISSUE THREAD

**Issue by dytsai** [Unitech/pm2#2576]
After changing my config file and running

pm2 reload process.json --only myProject

I expect env will be changed but not.

The only way to update my env config is to do pm2 kill and pm2 start again and then do pm2 save so config will be reloaded when rebooting machine. Is there a better way to update my config?

**Comment by Unitech** [comment]
Do you change the "env" field and these values does not get updated?

**Comment by dytsai** [comment]
No, and after running pm2 save, the old value is saved to .pm2/dump.pm2. I'm using pm2 version 2.2.1

**Comment by Unitech** [comment]
Could you please give me a way to reproduce this issue

**Comment by dytsai** [comment]
Oops, I just found something. If value is updated, it will be saved to dump.pm2. If the field is completed omitted, it will still be saved to dump.pm2.

**Comment by Unitech** [comment]
I see, this is an edge case. We may support this feature in the following month

**Comment by vmarchaud** [comment]
This has been fixed with pm2 `2.4` published last week :)
