### ISSUE TITLE
PM2 startup script generation fails on CentOS 6.x

### ISSUE THREAD

**Issue by psparago** [Unitech/pm2#2579]
If reporting a bug, please use the following template.

#### Expected behaviour

Running the following command should produce a startup script:
sudo su -c "env PATH=$PATH:/usr/bin pm2 startup centos ecosystem.json -u nodeadmin --hp /home/nodeadmin"

#### Actual behaviour

The command fails as follows:

[PM2] Writing init configuration in /etc/systemd/system/pm2.service
[PM2][ERROR] Failure when trying to write startup script
#### Steps to reproduce

Run the command below on CentOS 6.x
sudo su -c "env PATH=$PATH:/usr/bin pm2 startup centos ecosystem.json -u nodeadmin --hp /home/nodeadmin"

#### Software versions used

```
OS         : CentOS 6 (I'm not sure of the minor release (6.8 I think) but can get it if necessary)
node.js    : 6.9.2
PM2        : @latest (2.2.1)
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

(Unavailable at the moment)
...
```

cf CONTRIBUTING.md for more informations

**Comment by vmarchaud** [comment]
Centos 6 use SystemV, it should work using `pm2 startup systemv`.

**Comment by psparago** [comment]
To clarify, the documentation pointed to by the Release 2.2.1 notes says 

SystemD: Ubuntu >= 16, CentOS, Arch, Debian >= 7

Could you verify that we should 'systemv' please?

I don't have access to the server and have to instruct others, so I can't test for myself.

**Comment by vmarchaud** [comment]
Just run `pm2 startup` if you dont know which platform to use.
