### ISSUE TITLE
max_restarts in process.json doesn't work.

### ISSUE THREAD

**Issue by roccomuso** [Unitech/pm2#2584]
#### Expected behaviour

> max_restarts | type: number | default : 10 | number of consecutive unstable restarts (less than 1sec interval or custom time via min_uptime) before your app is considered errored and stop being restarted

#### Actual behaviour

I expect to have a max number of consecutive restarts of 10, but the script keeps getting restarted over and over again. I had like 40000 restarts. What am i doing wrong?

#### Steps to reproduce

```json
    {
      "name" : "wol-server",
      "script" : "./wake-on-lan/index.js",
      "args" : "-m f8:32:e4:a3:5a:7z -p 8002",
      "max_restarts"  : 10
    }
```

#### Software versions used

```
OS         : Raspbain
node.js    : 6.9.1
PM2        : latest
```

**Comment by vmarchaud** [comment]
Like documented, its the number of unstable restart, so if your application is online for more than one second, it will be counted in this counter.

**Comment by roccomuso** [comment]
@vmarchaud what does it means? my app crash on start and it takes less than a second i guess.
how can I increase this thime?

**Comment by vmarchaud** [comment]
Documented right [there](http://pm2.keymetrics.io/docs/usage/application-declaration/#control-flow), its the `min_start` option

**Comment by roccomuso** [comment]
@vmarchaud You mean <code>min_uptime</code>, cannot see a <code>min_start</code> option in the doc.

**Comment by vmarchaud** [comment]
Yeah i meant `min_uptime`
