### ISSUE TITLE
watch doesn't work after git pull

### ISSUE THREAD

**Issue by Sraw** [Unitech/pm2#2585]
I'm sure that "git pull" has been executed, but pm2 didn't automatically restart the app even though the files has changed.

```
OS         : Ubuntu 16.04
node.js    : 4.4.7
PM2        : lastest
```

**Comment by vmarchaud** [comment]
Please provide your configuration to replicate the issue

**Comment by Marchie** [comment]
Hello,

I think I am seeing a similar issue with an ExpressJS based node application:

System:
```
OS: Ubuntu 16.04
Node: 4.6.2
PM2: 2.2.1
```

PM2 application config:
```
module.exports = {
  "apps": [
    {
      "name"            : "foo",
      "script"          : "bin/www",
      "node_args"       : "--harmony",
      "merge_logs"      : true,
      "watch"           : ["bin", "config", "lib", "server", "routes", "views", "package.json", "app.js"],
      "cwd"             : "/var/www/foo",
      "log_date_format" : "YYYY-MM-DDTHH:mm:ss.sssZ",
      "max_restarts"    : 10,
      "env": {
        "NODE_ENV": "production",
        "PORT": 3000
      }
    }
  ]
};
```

What I would expect to see here is if I make a change to any file under the `bin`, `config`, `lib`, `server`, `routes` or `views` directories, or a change to the `package.json` or `app.js` files, then PM2 should restart the application.

However, the application does not restart when changes are made.  The files will normally be changed using a GIT post-receive hook, but I've also tried manually editing the package.json file on the server - the application is not restarted in either case.

I am new to PM2 though, so if I've misunderstood or made an error, any help will be gratefully received!

Thanks for your work on this.

**Comment by Sraw** [comment]
@vmarchaud 
`pm2_config.json:`
```
{
  "apps" : [{
    "name"        : "xxx",
    "script"      : "./index.js",
    "watch"       : true,
    "env": {
      "NODE_ENV": "development",
    },
    "env_production" : {
      "NODE_ENV": "production"
    },
    "ignore_watch" : ["node_modules", "public", "logs" , "logHelper","views"],
    "exec_interpreter" : "babel-node",
    "exec_mode"        : "fork",
  }]
}
```

**Comment by vmarchaud** [comment]
See #2629 we group all issue into one.
