### ISSUE TITLE
How Cluster Mode works?

### ISSUE THREAD

**Issue by brlebtag** [Unitech/pm2#2586]
I'd like to know more about the cluster mode solution that PM2 implements. what happens behind the curtains?

it is not explained on http://pm2.keymetrics.io/docs/usage/cluster-mode/.

can I combine it with node cluster (https://nodejs.org/api/cluster.html)?

I see it uses a custom load balancer. but how does it instantiate many instances without 'rebind the same port' problem?

**Comment by vmarchaud** [comment]
Our cluster mode is just a wrapper around the implementation of nodejs, we use it to abstract the cluster logic for your application. Since we just use the nodejs implementation, there isnt any custom load balancing.

**Comment by brlebtag** [comment]
just for curiosity, could you give me a high-level idea how the wrapper works? I don't like to use something that works like a 'black box' or 'magic tool', 'miraclely' solving a problem.  It can help me and of course, someone else when designing systems. I'm reading the pm2 codes but it can take a while before I have a good idea of what it is going on.

I'm sorry for any inconvenience and thank you a lot.

**Comment by vmarchaud** [comment]
We don't have any written explaination on how it works, so the only way for you would be to start from the entry point (pm2 start) and dive in our codebase to understand how it works, see [here](https://github.com/Unitech/pm2/blob/master/lib/God/ClusterMode.js#L52), [here](https://github.com/Unitech/pm2/blob/master/lib/ProcessContainer.js) and [here](https://github.com/Unitech/pm2/blob/master/lib/God.js#L156)

**Comment by brlebtag** [comment]
thanks. it is a good start point.

**Comment by soyuka** [comment]
http://stackoverflow.com/questions/34682035/cluster-and-fork-mode-difference-in-pm2 Ref
