### ISSUE TITLE
Is where anyway to specify app script with environment variable

### ISSUE THREAD

**Issue by ruoqianfengshao** [Unitech/pm2#2588]
If reporting a bug, please use the following template.

#### Expected behaviour
I want to start app with a global node runtime,  and I specify app script with shell command, but it's not work;
If I specify with absolute path, like `/Users/ruoqian/.nvm/versions/node/v7.2.0/bin/herd`, it works fine;
...

#### Actual behaviour
![image](https://cloud.githubusercontent.com/assets/2928664/21344175/601d00c6-c6d5-11e6-94d8-9e64939125b1.png)

...

#### Steps to reproduce
![image](https://cloud.githubusercontent.com/assets/2928664/21344212/8d159b2e-c6d5-11e6-8faa-13fa80f168ae.png)

...

#### Software versions used

```
OS         : macOS Sierra
node.js    :  7.2.0
PM2        :  2.1.6
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
...
```

cf CONTRIBUTING.md for more informations

**Comment by Unitech** [comment]
`$(which herd)` does not get replaced automatically. If nvm is rightly loaded when you do `pm2 start ecosystem.json`, you can replace `$(which herd)` by `herd`

**Comment by ruoqianfengshao** [comment]
@Unitech thx, i will study if it's possible
