### ISSUE TITLE
Running in not daemon mode

### ISSUE THREAD

**Issue by alexbeletsky** [Unitech/pm2#259]
I know it may sound a bit silly, but can I run pm2 in not daemon mode?

Let me explain why. I'm working on [pm2 plugin](https://github.com/likeastore/dokku-pm2) for dokku, with dokku each process is started in [docker](http://www.docker.io/) container. 

The problem is then I run, `pm2 start processes.json` it immediately quits, so docker assumes that it's done and stops.

Is that possible to have option like, `pm2 start --no-daemon processes.json`, so pm2 continues to run?

**Comment by aikomastboom** [comment]
How do I tell pm2 to also send stdout/stderr of its managed processes to the console?

currently when I start `pm2 --no-deamon`, only the pm2.log seems to be shown, not the logs of the process I just started.

**Comment by Unitech** [comment]
you can do

```
$ pm2 start app.js
$ pm2 logs
```

We just fixed the --no-daemon command to also display processes output https://github.com/Unitech/PM2/commit/f4569cbebf9b56dba5c4edf9893261cd613f6fec

**Comment by aikomastboom** [comment]
excellent, thank you.

**Comment by lexoyo** [comment]
Hello
It seems that when I start pm2 with `--no-daemon` it does not send data to keymetrics anymore... Am I right?

**Comment by lexoyo** [comment]
False alarm sorry about that, no problem

**Comment by Fenchurchh** [comment]
Just incase somebody googles this therad: as of 2017 `pm2-docker` runs in --no-daemon mode instead of `pm2`

http://pm2.keymetrics.io/docs/usage/docker-pm2-nodejs/

**Comment by aaronbrink** [comment]
`pm2-docker` was renamed to `pm2-runtime` but should still work as `pm2-docker` for now

https://pm2.io/doc/en/runtime/integration/docker/
