### ISSUE TITLE
passing multiple environment variable to pm2

### ISSUE THREAD

**Issue by SudeepParajuli** [Unitech/pm2#2594]
I was looking a way to pass multiple environment variables during pm2 startup . Though I found a way to pass a single environment variable but not sure how to pass multiple environment variable during pm2 startup .

**Comment by vmarchaud** [comment]
You must modify the pm2 service file, his location depend of platform ([you can find them in this switch](https://github.com/Unitech/pm2/blob/master/lib/API/Startup.js#L86)) and add necessary configuration, exmple [here with systemd](https://github.com/Unitech/pm2/blob/master/lib/templates/init-scripts/systemd.tpl#L12).
