### ISSUE TITLE
On ubuntu, pm2 is using /var/lock/subsys/pm2

### ISSUE THREAD

**Issue by dmitry-mukhin** [Unitech/pm2#2598]
Startup script is using `/var/lock/subsys/` for lock file. As this is not part of [file system hierarchy](http://manpages.ubuntu.com/manpages/xenial/en/man7/hier.7.html), on most hosts the dir is absent and file is not created.

#### Software versions used

```
OS         : ubuntu 14.04
node.js    : 6.9.2 
PM2        : 2.2.2
```

**Comment by Unitech** [comment]
pm2@2.2.3 published
