### ISSUE TITLE
How to save crash dump on aws linux instance

### ISSUE THREAD

**Issue by tesjhri16** [Unitech/pm2#2609]
If reporting a bug, please use the following template.

#### Expected behaviour

...

#### Actual behaviour

...

#### Steps to reproduce

...

#### Software versions used

```
OS         :
node.js    :
PM2        :
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
...
```

cf CONTRIBUTING.md for more informations

**Comment by vmarchaud** [comment]
Use `pm2 save` and retrieve the file stored under `~/.pm2/dump.pm2`

**Comment by tesjhri16** [comment]
I have linux instance and I think pm2 package is available only for ubuntu.

**Comment by vmarchaud** [comment]
pm2 is running with nodejs so with all platform

**Comment by tesjhri16** [comment]
check this
 yum install pm2
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
rhui-REGION-client-config-server-7                                                                 | 2.9 kB  00:00:00
rhui-REGION-rhel-server-releases                                                                   | 3.5 kB  00:00:00
rhui-REGION-rhel-server-rh-common                                                                  | 3.8 kB  00:00:00
No package pm2 available.
Error: Nothing to do

**Comment by vmarchaud** [comment]
Yeah, we only publish deb file for ubuntu/debian based linux, you need to install it using npm.
