### ISSUE TITLE
Caclulate memory usage by all child processes tree in fork mode.

### ISSUE THREAD

**Issue by fuson** [Unitech/pm2#261]
When pm2 look at memory usage it calulate it only for runned process, but not for all childs tree.

**Comment by rickysahu** [comment]
Its easy to get the child process of a pid, and therefore, just add up all the ram and cpu usage.
`pgrep -P 1819`

**Comment by yinrong** [comment]
+1 need cpu/mem for child processes

**Comment by soyuka** [comment]
https://github.com/simonepri/pidtree does it, feel free to propose a patch?
