### ISSUE TITLE
PM2 using much RAM

### ISSUE THREAD

**Issue by tuktun** [Unitech/pm2#2615]
I have closed source app. It is an express+socket.io+mongodb app.
When i am launching this with `pm2` (fork mode, without keymetrics) In a few hours it is using >1 GB RAM and then crash on 1.5 GB. When i am launching this with `forever` all goods even after a few days.

OS: `Debian 7 x64`
Node: `4.4.7`
PM2 Version: `1.1.3` and `2.2.1` (tested on both versions, same result)

What can be a reason for this? How to fix?

**Comment by vmarchaud** [comment]
The only way to check why is to take heapdump and see which object is in the memory, pm2 only had a couple of lines to your application (in this case the `lib/ProcessContainerFork.js` file), so its really weird that you have memory leak only with pm2.
Try lauching your application with the `"intepreterArgs":  ["--inspect"]` and debug it through chrome dev tools (see [this](https://blog.hospodarets.com/nodejs-debugging-in-chrome-devtools)), take heapdump and see the problem.
If you want some help you can pm me on our slack (http://slack.pm2.io) and share the heapdump with me in private
