### ISSUE TITLE
pm2 can't startup in osx

### ISSUE THREAD

**Issue by kimown** [Unitech/pm2#2617]
I want to run pm2 when osx startup, so I follow this [doc](http://pm2.keymetrics.io/docs/usage/startup/).

#### Steps to reproduce
```
pm2 startup
PM2] Init System found: launchd
[PM2] You have to run this command as root. Execute the following command:
sudo env PATH=$PATH:/Users/google/.tnvm/versions/alinode/v2.0.5/bin /Users/google/.tnvm/versions/alinode/v2.0.5/lib/node_modules/pm2/bin/pm2 startup launchd -u google --hp /Users/google
```
then I run the command, but error occurs, here is log:
```
PM2] Init System found: launchd
Platform launchd
Template
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
	  <key>Label</key>
	  <string>com.PM2</string>
	  <key>UserName</key>
	  <string>google</string>
    <key>KeepAlive</key>
    <true/>
	  <key>ProgramArguments</key>
	  <array>
		  <string>/bin/sh</string>
		  <string>-c</string>
		  <string>/Users/google/.tnvm/versions/alinode/v2.0.5/lib/node_modules/pm2/bin/pm2 resurrect</string>
	  </array>
	  <key>RunAtLoad</key>
	  <true/>
	  <key>OnDemand</key>
	  <false/>
	  <key>LaunchOnlyOnce</key>
	  <true/>
	  <key>EnvironmentVariables</key>
    <dict>
      <key>PATH</key>
      <string>/Users/google/.tnvm/versions/alinode/v2.0.5/bin</string>
      <key>PM2_HOME</key>
      <string>/Users/google/.pm2</string>
    </dict>
	  <key>StandardErrorPath</key>
	  <string>/tmp/com.PM2.err</string>
	  <key>StandardOutPath</key>
	  <string>/tmp/com.PM2.out</string>
  </dict>
</plist>

Target path
/Users/google/Library/LaunchAgents/PM2.plist
Command list
[ 'chmod +x /Users/google/Library/LaunchAgents/PM2.plist',
  'launchctl load /Users/google/Library/LaunchAgents/PM2.plist',
  'launchctl start /Users/google/Library/LaunchAgents/PM2.plist',
  'launchctl list' ]
[PM2] Writing init configuration in /Users/google/Library/LaunchAgents/PM2.plist
[PM2] Making script booting at startup...
>>> Executing chmod +x /Users/google/Library/LaunchAgents/PM2.plist
[DONE] 
>>> Executing launchctl load /Users/google/Library/LaunchAgents/PM2.plist
[DONE] 
>>> Executing launchctl start /Users/google/Library/LaunchAgents/PM2.plist
[ERROR] Exit code : 3
[PM2][ERROR] launchctl start /Users/google/Library/LaunchAgents/PM2.plist failed, see error above.
```

#### Software versions used

```
OS         :10.11.6
node.js    :v6.9.2
PM2        :2.2.3
```

**Comment by vmarchaud** [comment]
We came to the fact that `OSX v10.10` alias ElCapitan embed `launchctl v3.x` however `macOS v10.11` alias Sierra embed `launchctl v4.x`, we tried to track down the problem deeper without success, if anyone can investigate it would be awesome (commands run by pm2 are [here](https://github.com/Unitech/pm2/blob/master/lib/API/Startup.js#L238) and template is just [here](https://github.com/Unitech/pm2/blob/master/lib/templates/init-scripts/launchd.tpl))

**Comment by arctelix** [comment]
I can confirm the same error with the following versions:
OS         :10.11.6
node.js  :v7.4.0
PM2       :2.3.0

**Comment by PierrickMartos** [comment]
Same here:
OS : 10.11.6
Node.js : v6.9.4
PM2 : 2.3.0

**Comment by soyuka** [comment]
@arctelix @PierrickMartos 

Could any one of you try the following commands:

```
launchctl load -w ~/Library/LaunchAgents/PM2.plist
launchctl start ~/Library/LaunchAgents/PM2.plist
```

Are there any errors?

Would you be able to send us a file (`.plist`) from either one of these directories:

```
~/Library/LaunchAgents/
/Library/LaunchAgents/
```

so that we have an example of what the differences could be? I didn't find any changelog for launchctl :|.

**Comment by PierrickMartos** [comment]
Yes of course, no error with 2 commands you gave:

![image](https://cloud.githubusercontent.com/assets/1785711/22377537/a61f3cec-e4b2-11e6-8f14-a3ee5ce979bb.png)

Here is ~/Library/LaunchAgents/com.google.keystone.agent.plist
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>com.google.keystone.user.agent</string>
	<key>LimitLoadToSessionType</key>
	<string>Aqua</string>
	<key>ProgramArguments</key>
	<array>
	  <string>/Users/username/Library/Google/GoogleSoftwareUpdate/GoogleSoftwareUpdate.bundle/Contents/Resources/GoogleSoftwareUpdateAgent.app/Contents/MacOS/GoogleSoftwareUpdateAgent</string>
	  <string>-runMode</string>
	  <string>ifneeded</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>StartInterval</key>
	<integer>3623</integer>
	<key>StandardErrorPath</key>
	<string>/dev/null</string>
	<key>StandardOutPath</key>
	<string>/dev/null</string>
</dict>
</plist>
```

And one another from /Library/LaunchAgents/com.teamviewer.teamviewer.plist : 
````
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Disabled</key>
	<false/>
	<key>KeepAlive</key>
	<true/>
	<key>Label</key>
	<string>com.teamviewer.teamviewer</string>
	<key>LimitLoadToSessionType</key>
	<array>
		<string>Aqua</string>
	</array>
	<key>ProgramArguments</key>
	<array>
		<string>/Applications/TeamViewer.app/Contents/MacOS/TeamViewer</string>
		<string>-RunAsAgent</string>
		<string>YES</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>WorkingDirectory</key>
	<string>/Applications/TeamViewer.app/Contents/MacOS</string>
</dict>
</plist>
```

**Comment by arctelix** [comment]
No errors running those commands either..  
The only .plist files i have are the same as @PierrickMartos.  Just in case here is the PM2.plist that is generated:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
	  <key>Label</key>
	  <string>com.PM2</string>
	  <key>UserName</key>
	  <string>NYPortal</string>
    <key>KeepAlive</key>
    <true/>
	  <key>ProgramArguments</key>
	  <array>
		  <string>/bin/sh</string>
		  <string>-c</string>
		  <string>/usr/local/lib/node_modules/pm2/bin/pm2 resurrect</string>
	  </array>
	  <key>RunAtLoad</key>
	  <true/>
	  <key>OnDemand</key>
	  <false/>
	  <key>LaunchOnlyOnce</key>
	  <true/>
	  <key>EnvironmentVariables</key>
    <dict>
      <key>PATH</key>
      <string>/usr/local/Cellar/node/7.4.0/bin</string>
      <key>PM2_HOME</key>
      <string>/Users/channel1/.pm2</string>
    </dict>
	  <key>StandardErrorPath</key>
	  <string>/tmp/com.PM2.err</string>
	  <key>StandardOutPath</key>
	  <string>/tmp/com.PM2.out</string>
  </dict>
</plist>
```

**Comment by soyuka** [comment]
Hmm, this seems wrong, but may still be correct:

```
	  <key>ProgramArguments</key>
	  <array>
		  <string>/bin/sh</string>
		  <string>-c</string>
		  <string>/usr/local/lib/node_modules/pm2/bin/pm2 resurrect</string>
	  </array>
```

Did you install nodejs with brew? Does the binary `/usr/local/lib/node_modules/pm2/bin/pm2` exists?

After running the `launchctl start ~/Library/LaunchAgents/PM2.plist` command, is there anything in `/tmp/com.PM2.err` or `/tmp/com.PM2.out`?

Thanks!

**Comment by arctelix** [comment]
I installed node with brew & pm2 with npm.

The following file exists:

 /usr/local/lib/node_modules/pm2/bin/pm2

Contents /tmp/com.PM2.err:

[PM2][ERROR] No processes saved; DUMP file doesn't exist

Contents /tmp/com.PM2.err (portals is my app):

[PM2] Resurrecting
[PM2] Restoring processes located in /Users/channel1/.pm2/dump.pm2
┌──────────┬────┬──────┬──────┬────────┬─────────┬────────┬─────┬───────────┬──────────┐
│ App name │ id │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem       │ watching │
├──────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────┼───────────┼──────────┤
│ portals  │ 0  │ fork │ 4647 │ online │ 0       │ 25h    │ 0%  │ 47.7 MB   │ enabled  │
└──────────┴────┴──────┴──────┴────────┴─────────┴────────┴─────┴───────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app






On Jan 27, 2017, at 12:42 PM, Antoine Bluchet <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmm, this seems wrong, but may still be correct:

          <key>ProgramArguments</key>
          <array>
                  <string>/bin/sh</string>
                  <string>-c</string>
                  <string>/usr/local/lib/node_modules/pm2/bin/pm2 resurrect</string>
          </array>


Did you install nodejs with brew? Does the binary /usr/local/lib/node_modules/pm2/bin/pm2 exists?

After running the launchctl start ~/Library/LaunchAgents/PM2.plist command, is there anything in /tmp/com.PM2.err or /tmp/com.PM2.out?

Thanks!

**Comment by soyuka** [comment]
So it did find the dump file after all?

Can you do this :

```
launchctl start ~/Library/LaunchAgents/PM2.plist
echo $?
```

What exit code did you get?

In fact the exit code `3` means:

```
❯ launchctl error 3
3: No such process
```

Anyway, as long as it's loaded with the `launchctl load` command I don't think that we need to start it and it should be there on reboot anyway. Does pm2 get started when you reboot your computer?

Thanks for those debugging informations @PierrickMartos  and @arctelix

**Comment by arctelix** [comment]
launchctl start ~/Library/LaunchAgents/PM2.plist
echo $?

echoed "3"

And the good news:

YES pm2 did start on reboot and relaunched my configured node app after all!

Its very strange indeed that the files do exist and launchctl is complaining that they don't.
Theres got to be something in the plist that it's not too fond of.  In the mean time, looks like a superficial error.

**Comment by soyuka** [comment]
It's the same with most my launchctl files there, I think that `launchctl start` was misused:

```
     start label
              Start the specified job by label. The expected use of this subcommand is for debugging and
              testing so that one can manually kick-start an on-demand server.
```

It's not needed here because pm2 is already started anyway.

**Comment by soyuka** [comment]
Will land in next release!

Don't worry though if you have this issue pm2 will still be started on boot!

**Comment by vmarchaud** [comment]
@arctelix Could you try ? `npm install -g Unitech/pm2#development && pm2 update` thanks !

**Comment by arctelix** [comment]
I installed the provided branch clean (no prior pm2 install)

npm install -g Unitech/pm2#development

Then ran:  `pm2 startup`

 Then copied and paste the sudo commend:  Success, no errors as expected.

**Comment by arctelix** [comment]
here is the output:

Command list
[ 'launchctl load -w /Users/justin/Library/LaunchAgents/PM2.plist' ]
[PM2] Writing init configuration in /Users/justin/Library/LaunchAgents/PM2.plist
[PM2] Making script booting at startup...
>>> Executing launchctl load -w /Users/justin/Library/LaunchAgents/PM2.plist
[DONE]
+---------------------------------------+
[PM2] Freeze a process list on reboot via:
$ pm2 save

[PM2] Remove init script via:
$ pm2 unstartup launchd

**Comment by soyuka** [comment]
Thanks @arctelix !
