### ISSUE TITLE
pm2 'cluster' mode fail to load LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by wilbur1991** [Unitech/pm2#2618]
**Hi all, i'm installing a npm package '_ccap_' to generate CAPTCHA. Because it's a c++ add on and requires _gcc 4.8 +_,i met some problems while installing it.
I compiled _gcc 4.9.4_ and installed ccap successfully on my development machine.
However ,i met this wield problem when i try to start my application (without pm2).**

```
Error: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/jwb/ccapDemo/node_modules/ccap/build/Release/hcaptha.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function._load (/home/jwb/ccapDemo/node_modules/pmx/lib/transaction.js:47:40)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/jwb/ccapDemo/node_modules/ccap/lib/hcap.js:4:13)
    at Module._compile (module.js:570:32)
```

**I googled a lot and got it fixed by setting  following linux enviroment variable in _.bash_profile._**

```
export LD_LIBRARY_PATH=/home/jwb/gcc-4.9.4/lib64:$LD_LIBRARY_PATH
```

**Now it seems like working ,but when i try to start my demo in _PM2 cluster mode_,the same problem  occured.**
**I also tried pm2 fork mode,and it worked just fine.**
**So i figured maybe _LD_LIBRARY_PATH_ can not be found in _PM2 cluster mode_.Then i printed _process.env_ and found _LD_LIBRARY_PATH_.**

**So i think this problem is somehow related to _PM2 cluster mode_ ,but i don't know how to fix it. 
I do not have root authority and  can not just update _/usr/lib64/libstdc++.so.6_ to a higher version. Have someone met same problem ?How should i solve it?***

#### Software versions used

```
OS         : Red Hat 6
gcc        : 4.9.4 (default gcc version is 4.4.7)
node.js    : 6.9.1
PM2        : 2.0.19
```

**Comment by vmarchaud** [comment]
PM2 use [nodejs cluster](https://nodejs.org/dist/latest-v6.x/docs/api/cluster.html) so it should't have any problem, could you try with the [cluster of nodejs](https://nodejs.org/dist/latest-v6.x/docs/api/cluster.html#cluster_cluster) directly (and started using `node` binary) ?

**Comment by wilbur1991** [comment]
Hi vmarchaud , i've tried to start my demo with nodejs cluster module and it works just fine.So i guess it's still a pm2 problem. Here's my code.
```
const cluster = require('cluster');
const http = require('http');
const numCPUs = require('os').cpus().length;

var ccap = require('ccap')();//Instantiated ccap class
if (cluster.isMaster) {
    // Fork workers.
    for (var i = 0; i < numCPUs; i++) {
        cluster.fork();
    }
    cluster.on('exit', (worker, code, signal) => {
        console.log(`worker ${worker.process.pid} died`);
    });
} else {
    // Workers can share any TCP connection
    // In this case it is an HTTP server
    http.createServer(function (request, response) {
        if(request.url == '/favicon.ico')return response.end('');//Intercept request favicon.ico
        var ary = ccap.get();
        var txt = ary[0];
        var buf = ary[1];
        response.end(buf);
        console.log(txt);
    }).listen(8124);
}
```

**Comment by vmarchaud** [comment]
Can you try requiring `ccap` inside the worker ?

**Comment by wilbur1991** [comment]
@vmarchaud ,I tried your suggestion.Nothing happened.It still works.
Here is my code.

```
const cluster = require('cluster');
const http = require('http');
const numCPUs = require('os').cpus().length;
if (cluster.isMaster) {
    // Fork workers.
    for (var i = 0; i < numCPUs; i++) {
        cluster.fork();
    }

    cluster.on('exit', (worker, code, signal) => {
        console.log(`worker ${worker.process.pid} died`);
    });
} else {
    // Workers can share any TCP connection
    // In this case it is an HTTP server

    var ccap = require('ccap')();//Instantiated ccap class

    http.createServer(function (request, response) {
        if(request.url == '/favicon.ico')return response.end('');//Intercept request favicon.ico
        var ary = ccap.get();
        var txt = ary[0];
        var buf = ary[1];
        response.end(buf);
        console.log(txt);
    }).listen(8124);
}
```

**Comment by vmarchaud** [comment]
Weird cause thats exactly how its working inside pm2, could you try using a [process file](http://pm2.keymetrics.io/docs/usage/application-declaration/) to declare your app (specially `env` & `cwd` configs).

**Comment by wilbur1991** [comment]
@vmarchaud  ,i update my pm2 version from _**2.1.6**_ to **_2.2.3_** accidentally a few minutes ago. And the problem is gone. I guess it's some known issue and already got fixed. I think this issue can be closed now, thx a lot.

**Comment by jleed** [comment]
3.0.4 same problem...

**Comment by Davetwo** [comment]
One solution in https://unix.stackexchange.com/a/548126/378457

**Comment by sakesun** [comment]
Why this issue is closed ?
I have same problem even with latest 4.2.3.
I have to do the clustering in my code and configure pm2 ecosystem file in fork mode.

I think we should re-open this issue.
