### ISSUE TITLE
Request for non-realtime log output

### ISSUE THREAD

**Issue by Nogbit** [Unitech/pm2#2620]
Right now log output is realtime which makes it difficult to do other things with the output.   Hopefully I haven't missed a feature that exists to simply send the last x lines of log to stdout.

**Suggestion**

    pm2 logs --lines 10 --nostream  [id|name]

**Comment by soyuka** [comment]
tail -n 100 ~/.pm2/logs/XX.log ?

**Comment by Nogbit** [comment]
I would like to infer the log file config in my process.json vs sleuthing around to determine which file to run tail on.

-----Original Message-----

**Comment by vmarchaud** [comment]
Landed on pm2 `2.3.0`
