### ISSUE TITLE
(version 2.2.3) --no-daemon is not working on windows 

### ISSUE THREAD

**Issue by lovelyelfpop** [Unitech/pm2#2621]
If reporting a bug, please use the following template.

#### Expected behaviour
--no-daemon should be working

#### Actual behaviour
still have black cmd popups even I use '--no-daemon'

#### Steps to reproduce
`pm2 start ./bin/www -i 1 -n xxxxx --no-daemon`

#### Software versions used

```
OS         : Windows 7 x64
node.js    : 6.9.4
PM2        :  2.2.3
```

**Comment by vmarchaud** [comment]
Because PM2 spawn shell command to retrieve some data (git status for example), so its possible that popups still spawn using `--no-daemon`. I advise you to run on fork mode (less popups) since you have only one process anyway.
But your issue name isn't valid, `--no-daemon` is working on windows.
