### ISSUE TITLE
Pm2 cron can restart a stopped shell script ?

### ISSUE THREAD

**Issue by astrung** [Unitech/pm2#2622]
I have a script to crawl data from website : `crawl.sh`.
I want to cron this script everyday at 0 a.m , so i use this command to run this script on pm2 :
 
`pm2 start crawl.sh --name testpython  --no-autorestart --cron '0 0 * * *'`

After running , this process go to `stopped` status . So can it restart at 0 a.m at next day . From what i read, pm2 expects cron process is still running before restart .

**Comment by vmarchaud** [comment]
At this moment you need to have a javascript process to use `--cron` (cause its embded inside the process). If you want to do this, i suggest you to make a crontab that restart the script using `pm2 restart testpython` and to manually start it the first time.

**Comment by astrung** [comment]
@vmarchaud Now pm2 `--cron` only suggests for javascript process (by start `.js` file) ??

**Comment by vmarchaud** [comment]
It has always be the case, see this [file](https://github.com/Unitech/pm2/blob/master/lib/ProcessContainerFork.js#L19) that is spawn for each javascript process, the cron is handled inside.
