### ISSUE TITLE
QUESTION: Auto-revert on failed deploy?

### ISSUE THREAD

**Issue by Aldlevine** [Unitech/pm2#2628]
Is there any way to have pm2 automatically revert to the previous deploy in the case of deploying a build that crashes on start?

**Comment by vmarchaud** [comment]
I advise you to create a [module](http://pm2.keymetrics.io/docs/advanced/pm2-module-system/) to do this, pm2 can't make this kind of decision for you.

**Comment by Aldlevine** [comment]
Thanks! I thought as much, but I wanted to make sure there wasn't a solution for this before rolling my own.
