### ISSUE TITLE
Refactor Watch System

### ISSUE THREAD

**Issue by vmarchaud** [Unitech/pm2#2629]
- Support gracefull reload when watching file
- Make a clear system
- Make it work
- Add post_watch hook to make shell action when change has been detected
- Avoid multiples changes to restart multiples times the process
- https://github.com/rlidwka/node-hotswap ?
- https://github.com/fgnass/node-dev ?

**Comment by vmarchaud** [comment]
Be able to run a command each time a file is updated #2685

**Comment by peacemakr** [comment]
whats the status of this work log?

**Comment by vmarchaud** [comment]
Its in the backlog, that means we aim to do this as soon as we can.

**Comment by luchillo17** [comment]
Seems that currently it works as good as you ignore a folder or a file, but globs don't.

**Comment by vmarchaud** [comment]
Restarting reset the `watch` option with ecosystem file #2920

**Comment by manico** [comment]
Any info on this?
We have a need to run eslint each time change with watch is detected, before reload.

**Comment by robcmills** [comment]
@vmarchaud ☝️ Is this work still in the "backlog"? An update would be appreciated, thanks.

**Comment by Saishy** [comment]
Having the watch not working on restart and if my app status is "errored" it also stops watching.

**Comment by AamuLumi** [comment]
Hi ! Is there some news about this issue ? `ignore_watch` is still unusable (because completly buggued) and it's a major problem for all developers with at least 2 servers.

**Comment by soyuka** [comment]
@AamuLumi I don't get how ignore_watch is "unusable" and "completly bugged". Some examples that may help you setting it correctly: https://github.com/Unitech/pm2/search?utf8=%E2%9C%93&q=ignore_watch&type=

**Comment by AamuLumi** [comment]
I tested all possible patterns accepted by [anymatch](https://github.com/micromatch/anymatch) (as mentioned in the documentation of [chokidar](https://github.com/paulmillr/chokidar#path-filtering) mentioned in the documentation of pm2). When I spend 2 hours of time to test all possible paths and nothing works, sorry, but this is "completly bugged". Perhaps the lack of real documentation is the true issue, yeah.

Here's some tests I've done : 
```
"src/modules/**/app"
"src\/modules\/.*\/app"
"src\/modules\/[a-zA-Z]*\/app"
"src/modules"
"src\/modules"
```
All these cases cannot ignore the file `src/modules/data/app/something/aFile.ts`.

Got the same problem with : 
```
".cache-loader"
".cache-loader/*"
".cache-loader/*.json"
".cache-loader\/.*"
```
Nothing ignore the file `.cache-loader/xxx.json`.

**Comment by doowb** [comment]
@AamuLumi, I'm a maintainer on `micromatch`, which is used in `anymatch`. If you're trying to ignore anything in the `src/modules/**/app` folder(s), then you could try:

```js
'src/modules/**/app/**'
// or
'src/modules/**/app/**/*'
```

Also, for the second pattern (and the first if there are any "dot" files), use the `watch_options` property [specified here](https://pm2.io/doc/en/runtime/guide/development-tools/#watch-options) to ensure files and folders that start with a dot `.` are also captured in the glob:

```js
watch_options: {
  dot: true
}
```

I hope this helps. I don't have anything available to test with right now, so I'm showing what I think should work.

**Comment by AamuLumi** [comment]
You're a genius dude ! Thanks a lot !

Note : for the second pattern, `dot` option isn't needed. I think there was a bug in my infrastructure : it seems Docker stopped refreshing my configuration files when I was working on `ignore_watch`. All works perfectly now.

My bad, and sorry for blaming too fast `ignore_files`. :/

**Comment by dbos** [comment]
When I attempt to use the watch mode, I get extra processes that are still running and blocking my ports. I have tried moving the chokidar watching into my script, disabling it in pm2, and triggering a process.exit when files change, but that doesn't work either.

I end up having to use "pm2 delete ecosystem.json" followed by "kill -9 $PROCESS_IDS" and "pm2 start ecosystem.json". It's very tedious and really defeats much of the purpose of using pm2 during development. If there's any update or suggestion to make the development flow more convenient, that would be greatly appreciated.

**Comment by komocode** [comment]
Ignore Watch is bugged. I'm currently using Realm. My ignore watch is:

> "ignore_watch" : [".sailsrc", ".tmp", "views", "assets", "node_modules", ".git", ".DS_Store", "realm-object-server"],

Only files in views and realm-object-server folders change. PM2 seems to continuously restart the server.

**Comment by diegofontana** [comment]
i cant get this fu*** ignore to work, how could this be so hard!???
i am using escosystem file named "ecosystem.dev.config.js" on Windows10 with this rule
ignore_watch: ["*.json"]
i have tried with many many other patterns....

**Comment by komocode** [comment]
FYI - I did notice my app was crashing which was causing pm2 to restart it. I fixed the crash, but ignore watch is still bugging out. Everyone that is experiencing auto restarts, please check by running your app via node first to see if it runs fine.

**Comment by M-erb** [comment]
I seem to be having the same problem. I want to ignore all and any updates that are in the "clients" directory. Here some patterns I have tried:

['./client/*', './node_modules/*']
['/client/*', '/node_modules/*']
['client/', 'node_modules/']
['client', 'node_modules']

In testing I have "pm2 monit" up in my terminal and I see in the logs that it is detecting a change in client/components/ and so on to the file located there. Spent about 2 hours on this so far and it still does not ignore the client directory.

**Comment by catchmareck** [comment]
I'm encountering a similar problem. When I add the `node_modules` directory to the ignore-watch it still detects changes

**Comment by chrisdemetriad** [comment]
Same here, is there a fix for this?

**Comment by arkabase** [comment]
Still there !
Is anyone working on this bug ?

**Comment by Unitech** [comment]
PM2 v4.0 will fix that
Could you please try the development version and let me know if that issue has been fixed:

```
npm install Unitech/pm2#development -g
pm2 update
```

**Comment by r2g** [comment]
> PM2 v4.0 will fix that
> Could you please try the development version and let me know if that issue has been fixed:
> 
> ```
> npm install Unitech/pm2#development -g
> pm2 update
> ```

This did not work.. pm2 is still restarting when some ignored folders content changes

**Comment by HiroshiHorie** [comment]
glad to know i'm not the only one annoyed with this 😅

**Comment by FreeDevStan** [comment]
I also have this issue. Windows 10 pro, Node v10.15.3, PM2 3.5.1 (also tried 
4.0.0-beta-7). I'm starting pm2 without a watch, everything works fine until app reaches max memory limit, then app restarts and I get an error: "address already in use". If you try pm2 stop, then it stops and starts again. An only possible way to kill app is to make pm2 delete id and then kill the process manually.

**Comment by AdnanRashied** [comment]
Yea, I'm currently trying to deploy on Heroku and keep running into


>  "Something is already running on port 47607."


 I can't tell if its because im using windows or not. I changed mine to development node and now I'm getting this. 
`PM2 log: App [PrO:7] exited with code [0] via signal [SIGINT]
`

**Comment by objNameGit** [comment]
I have the same problem. What am I doing wrong?
i have ecosystem.config.js:
```
module.exports = {
  apps : [{
    name: 'bot',
    script: 'index.js',
    log_date_format: 'YYYY-MM-DD HH:mm Z',
   // error_file: '$HOME/.pm2/logs/XXXerr.log',
   // out_file: '$HOME/.pm2/logs/XXXout.log',
    // Options reference: https://pm2.io/doc/en/runtime/reference/ecosystem-file/
    args: 'one two',
    instances: 1,
    autorestart: true,
    watch: true,
    ignore_watch: ['node_modules'],
    max_restarts: 10,
    max_memory_restart: '500M',
    env: {
      NODE_ENV: 'development'
    },
    env_production: {
      NODE_ENV: 'production'
    }
  }],
}
```
` pm2 start ecosystem.config.js`

```
┌────┬─────────────────────────┬─────────┬─────────┬──────────┬────────┬──────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name                    │ version │ mode    │ pid      │ uptime │ ↺    │ status   │ cpu      │ mem      │ user     │ watching │
├────┼─────────────────────────┼─────────┼─────────┼──────────┼────────┼──────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ 0  │ bot                     │ 0.3.0   │ cluster │ 5747     │ 0s     │ 67   │ online   │ 0%       │ 30.8mb   │ joker    │ enabled  │
└────┴─────────────────────────┴─────────┴─────────┴──────────┴────────┴──────┴──────────┴──────────┴──────────┴──────────┴──────────┘
```
i change file **index.js**, but  server not restarted

**Comment by jlsjonas** [comment]
@Unitech we are still experiencing "address already in use"-related errors due to an unclean/too-fast restart when there's changes detected; so this issue definitey does not appear to be solved.
running pm2 4.5.0 (last release)
