### ISSUE TITLE
python processes are not stopped

### ISSUE THREAD

**Issue by gregoryb** [Unitech/pm2#263]
Hello,

I use pm2 to run a python app (with the interpreter arg) and when i use "stop all" or "delete all" command. The processes are not stopped. (ps aux).

is it normal ?

thanks you!

**Comment by jdrake** [comment]
Why was this issue closed? I just ran into it using pm2 0.14.6, OSX Yosemite 10.10.4, Python 2.7.8.

Part of my apps declaration file:
```json
"exec_interpreter": "vendor/python/bin/python",
"script": "src/my_app/app.py",
```
