### ISSUE TITLE
Unable to delete all app's logs without restart

### ISSUE THREAD

**Issue by Kitanotori** [Unitech/pm2#2633]
#### Expected behaviour

All the logs of a particular app should be possible to delete without having to restart the app.

#### Actual behaviour

`pm2 flush` does not allow to delete all app logs nor logs of a particular app, only the active ones of all apps. `rm *.log` or similar on the other hand allows removing all the logs of a particular app but the app stops logging because it seems to be unable to automatically recreate the active log file in case it gets deleted.

#### Steps to reproduce

`pm2 flush`
`rm *.log`

#### Software versions used

pm2: 2.2.3

**Comment by vmarchaud** [comment]
I suggest you to use [pm2-logrotate](https://github.com/pm2-hive/pm2-logrotate) to manage your old logs, PM2 only manage `live` stream logs.

**Comment by Kitanotori** [comment]
How exactly do I delete logs on-demand using pm2-logrotate? It seems to have configuration parameters such as max_sive and retain, but those are for automated, not on-demand log deletion.

Is it not possible to make pm2 recreate live stream log if it gets deleted?
