### ISSUE TITLE
pm2 start app.js -i max -  run only 2 instances of application

### ISSUE THREAD

**Issue by lyudad** [Unitech/pm2#2634]
pm2 start app.js -i max  - run only 2 instances of application
if I write instead of "max" any number - it work right. But why "max" not work

**Comment by vmarchaud** [comment]
`max` is setting the instance to the number of CPU core if you have available, see [here](https://github.com/Unitech/pm2/blob/master/lib/God.js#L19), so that's a normal behavior.
