### ISSUE TITLE
pm2-docker Memory Leak are there.

### ISSUE THREAD

**Issue by rahulkulmi** [Unitech/pm2#2636]
I am using pm2-docker for node express app.

node = v6.9.2
pm2 = 2.2.3

command i am using to start node server: 
pm2-docker process.yml

Here is my process.yml fine data:
```
apps:
  - script   : 'app.js'
    name     : 'APP'
    exec_mode: 'cluster'
    instances: 4
    max_memory_restart: '120M'
```

Can you please tell me how to fix memory issue because after 2-3 days my server will not give HTTP response but it log inside the log file.

**Comment by vmarchaud** [comment]
Linked to https://github.com/Unitech/pm2/issues/1484 not to `pm2-docker`.

**Comment by vmarchaud** [comment]
Do have you have nginx in front of your container ?

**Comment by rahulkulmi** [comment]
No i am not using nginx for my container.

Is it required nginx for pm2 docker .

**Comment by vmarchaud** [comment]
No of course not, but people of issue #1484 had the same problem than you, connection aren't handled, checkout this one too : https://github.com/Unitech/pm2/issues/2300

**Comment by rahulkulmi** [comment]
I am also using pmx can i remove it.

Also can i add _timeout for every request which is mention in #2300

**Comment by vmarchaud** [comment]
You just need to add `--no-pmx` in CLI or put `pmx: false` in your process file.

**Comment by rahulkulmi** [comment]
@vmarchaud I thing it is not the pmx issue because when i am facing this issue then i will add pmx for keymetrics dashboard. But i will set pmx: false inside my process file and check my server and will let you know.

**Comment by Unitech** [comment]
Are you sure it is about a memory leak of pm2-docker? Could you please provide more informations

**Comment by rahulkulmi** [comment]
I am not 100% sure about that memory leak of pm2-docker may be there is some another reason also. But as i read about node v8 profiler that will remove the Garbage collection but may be pm2-docker will not remove Garbage collection properly. Because in keymetrics it is showing that no memory leak but when i go to server and check that (free -m) then it will increase so there is memory leak but pm2 will not detect.

**Comment by rahulkulmi** [comment]
Is there any option so will call Garbage collection in pm2-docker also like using process.yml file.

If i am set (node-args: '--expose-gc') inside the process.yml file so pm2 will call garbage collection.

**Comment by GiankOtarola** [comment]
@rahulkulmi Do you have any update about your issue?
