### ISSUE TITLE
-i 0 flag not working on windows

### ISSUE THREAD

**Issue by psabharwal3** [Unitech/pm2#2637]
If reporting a bug, please use the following template.

#### Expected behaviour
pm2 start src/server/index.js -i 0 should start app in cluster mode with maximum processes
...

#### Actual behaviour
You are starting 0 processes in fork_mode without load balancing. To enable it remove -x option.

...

#### Steps to reproduce
create index.js under src/server
pm2 start src/server/index.js -i 0
...

#### Software versions used

```
OS         : windows
node.js    : v6.5.0
PM2        :2.2.3
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
...
```

cf CONTRIBUTING.md for more informations

**Comment by vmarchaud** [comment]
Which version of Windows are you running ?

**Comment by psabharwal3** [comment]
sorry forgot to type that - 10

**Comment by Steinweber** [comment]
`$ pm2 start ./bin/www -i 10 --watch`

this starts 1 process in fork

`$ pm2 scale www +3
[PM2][ERROR] Application www is not in cluster mode`

delete process and restart will work
`$ pm2 delete "appname"
$ pm2 start ./bin/www -i 10 --watch --name appname`

**Comment by psabharwal123** [comment]
It did not work. Also issue is on windows 10

**Comment by vmarchaud** [comment]
Just tested with a clean version of windows 10 (just installed `nvm` and `git`), node `6.5.0` and it works perfectly. Debian 8 also working in multiple of our setups.
Can you using a [ecosystemfile](http://pm2.keymetrics.io/docs/usage/application-declaration/) ?

**Comment by psabharwal3** [comment]
i ll switch to using json file, thanks
