### ISSUE TITLE
PM2-deploy failed with Jenkins : ecosystem.config.js environment is not defined in package.json file

### ISSUE THREAD

**Issue by Choko256** [Unitech/pm2#2638]
I was expecting to deploy a NodeJS API on a remote server.
Everything was fine until I tried to use the pm2-deploy with my Jenkins CI.

The command line I used is:

`$ pm2 deploy ecosystem.config.js $ENV tags/$VERSION`

Where `$ENV` is the environement to be deployed, and `$VERSION` the name of the tag I want to deploy.

There is only one log line produced by the Jenkins job :

`ecosystem.config.js environment is not defined in package.json file`

This error is not produced and the app is successfully deployed when I run the same command line into a direct SSH shell on the Jenkins server.

```
OS           :  RHEL 6
node.js    :  6.9.4
PM2        :  2.2.3
```

My collegues and me searched for hours for information about this problem. None found.
Please help !!

Thanks.

**Comment by vmarchaud** [comment]
Can't help you without your configuration, can you paste it here ?

**Comment by Choko256** [comment]
Here is the `ecosystem.config.js` which perfectly works on my local machine but does not work in Jenkins :

```javascript
module.exports = {
    /**
     * Application configuration section
     * http://pm2.keymetrics.io/docs/usage/application-declaration/
     */
    apps : [

        // First application
        {
            name : "Private Repo",
            script : "index.js",
            env_production : {
                NODE_ENV : "production"
            }
        }
    ],

    /**
     * Deployment section
     * http://pm2.keymetrics.io/docs/usage/deployment/
     */
    deploy : {
        qat_com : {
            key : "~/.ssh/secret-key.pem",
            user : "user",
            host : "1.2.3.4",
            repo : "git@bitbucket.org:user/private-repo.git",
            path : "/euronews/mercury",
            ref : null,
            "post-deploy" : "yarn && pm2 startOrRestart ecosystem.config.js --env qat_com",
            env : {
                NODE_ENV : "qat_com"
            }
        }
    }
}

```

**Comment by Choko256** [comment]
I was looking into the source code, and it seems that the `Utility.whichFileExists` function cannot find `ecosystem.config.js` in the Jenkins job context, but it can find the `package.json`

**Comment by Choko256** [comment]
Ok My bad.
The pm2 version Jenkins was using was 1.0.0.
Updating it inside the Jenkins context fixed the problem.

**Comment by koistya** [comment]
If the file is named `ecosystem.config.cjs` pm2 also unable to find it.
