### ISSUE TITLE
Database migrations

### ISSUE THREAD

**Issue by DataTables** [Unitech/pm2#2639]
This possibly isn't the correct place to ask a support question such as this, if not, please accept my apologies! I couldn't see any indication of where I should ask, and since this isn't a yes / no question it would probably be closed on SO.

I'm working on an app that I'd like to be able to deploy with zero downtime and PM2 looks awesome for this. The app will be database backed which of course might be updated from time to time. I'm using postgres with a schema per tenant.

The database migration process will normally be fast, but inevitably there will be the cases where the schema has been updated for some tenants and not others, and thus they would need to be directed to different processes (i.e. the old forks which are now being killed off, or the new forks for the new and updated schema).

Are there any recommendations for how to do this, or has it been done in practice? I'd wondering about having some kind of communication between the child processes and the parent to say "the connecting user's schema has been updated and needs to use one of these child processes" or "the connecting user's schema has not been updated and needs to use one of these processes", until everyone has be updated. But it sounds messy :-).

**Comment by vmarchaud** [comment]
PM2 use [node cluster implementation](https://nodejs.org/dist/latest-v6.x/docs/api/cluster.html#cluster_how_it_works) and you can't implement custom load balancing strategy so you'll not be able to do what you are saying.

What you could do (but i don't think thats actually a good idea) is to add a schema versioning then add a required schema version in your application configuration, so you can wait for the database (maybe a query that check a special table for current schema version) to be at your required version to start the application (using [--wait-ready](http://pm2.keymetrics.io/docs/usage/signals-clean-restart/#graceful-start)).
Like this new worker will have new schema and old one will still be there while waiting for the database.

**Comment by DataTables** [comment]
Thanks for the feedback - much appreciated!

I did [ask it on SO](https://stackoverflow.com/questions/41706616/database-migrations-in-zero-downtime-node-js) but perhaps unsurprisingly it got a down vote and no replies.

**Comment by soyuka** [comment]
> The database migration process will normally be fast, but inevitably there will be the cases where the schema has been updated for some tenants and not others, and thus they would need to be directed to different processes (i.e. the old forks which are now being killed off, or the new forks for the new and updated schema).

Yes it'll be inevitable especially it you don't want any downtimes.  

IMO the best is to have a proper error management system that just fails if the query doesn't work (ie columns has changed) and ask the user to retry. The next request will probably have the good schema in memory. Also, I think that a database upgrade is probably worth a downtime, just to be safe :).
