### ISSUE TITLE
PM2-Deploy w/ --depth=1 optimization

### ISSUE THREAD

**Issue by phra** [Unitech/pm2#2640]
#### Feature request

hi. it would be nice if the deploy via pm2 will take advange of `--depth=1` when cloning/fetching the repository.
what do you think guys? eventually i can craft a PR with this change.

**Comment by vmarchaud** [comment]
I think its a good idea, at least we should have an opt-in option to use `--depth=1`, but pm2 is using another module to do this :
- Currently the deploy part is hosted in [this repository](https://github.com/Unitech/pm2-deploy) so if you want to make a PR it should be over there.
- I started to re-implement the whole deploy system in plain javascript (no call to binary) [over there](https://github.com/vmarchaud/deployerjs) if you want to contribute too.

**Comment by phra** [comment]
i've gave a quick look to the source code and it seems to me that this [changes](https://github.com/Unitech/pm2-deploy/pull/118) can be enough *but i have still to test it due to lack of time*.
if someone can test the change i'll be grateful.

**Comment by vmarchaud** [comment]
Landed in pm2 `2.3.0`
