### ISSUE TITLE
Question: Using PM2 inside a docker container?

### ISSUE THREAD

**Issue by danprince** [Unitech/pm2#2641]
Trying to get a node app running under PM2 inside a Docker container and have been [having some trouble][1].

I threw together a [minimal example][2], and this seems to work just fine, but it leaves me wondering—if PM2 has involved Docker integrations (like [keymetrics/pm2-docker-alpine][4] and [`pm2-docker`][3]), why aren't there more examples of using them?

My colleague pointed me towards the Docker best practice of only using [one process per container][5], but this advice seems to be contradicted by Docker's own guide on [using Supervisor][6].

From [Nodesource's Docker article][7]:
> In the event an application's process crashes, a mechanism is needed to restart it. Docker introduces a paradigm shift with its best practices: one process per container. Unfortunately tools like `pm2` or `forever` require being inside the container, breaking this rule.
It is recommended that the process is restarted at the container level, rather than from within the container. This has the advantage of requiring a single tool for all containers, regardless of what's running inside. This can be leveraged by an agnostic tool like `systemd` or `upstart`.

This only gets more complicated when other threads about supervising node apps, suggest instead using the `restart: always` option for Docker Compose. 

Here's the rough gist of what I'd like to achieve:

* In __development__ I'd like to mount a local volume and restart the _node process_ when a file changes.
* In __production__ I'd like the process to restart upon failure and expose a health check endpoint.

Is PM2 the right tool for the job?

[1]: http://stackoverflow.com/questions/41715838/pm2-wont-start-inside-docker
[2]: https://github.com/danprince/docker-pm2-example
[3]: http://pm2.keymetrics.io/docs/usage/docker-pm2-nodejs/#pm2-docker-inside-a-dockerfile
[4]: https://hub.docker.com/r/keymetrics/pm2-docker-alpine/
[5]: https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/run-only-one-process-per-container
[6]: https://docs.docker.com/engine/admin/using_supervisord/
[7]: https://nodesource.com/blog/8-protips-to-start-killing-it-when-dockerizing-node-js/

**Comment by Unitech** [comment]
Yes it is,

For development, use pm2-dev in your Dockerfile to restart your app on file change within the Docker container.
For production, use pm2-docker in your Dockerfile to restart your app in case of crash.
To expose a health check endpoint you can use the option `--web` ([doc here](http://pm2.keymetrics.io/docs/usage/docker-pm2-nodejs/#expose-health-endpoint))

**Comment by danprince** [comment]
Thanks @Unitech. Just want to follow up quickly to ask about how this would work in production.

Would you rebuild the container from a new image each time the code changes? Not sure how to keep the reloads at zero-downtime that way (no load balancers involved).

Or would you deploy the code to a mounted volume (outside of the container), then signal for pm2 to restart (something like `docker exec "npm install && pm2 reload all"`)?

**Comment by jimmylin212** [comment]
+1, I am also wondering what is the correct or best way to deploy a new patch to pm2 container. Is there any online document or guide that could follow?

**Comment by beeplin** [comment]
@danprince after two years of this discussion... what's your current way to deploy new code via docker & pm2? I am just trying to figure it out.

**Comment by danprince** [comment]
@beeplin Here's the rough take:

1. Using standard `node` docker image
2. Install pm2 as dependency
3. Start docker image with following shell script:

```sh
#!/bin/sh
set -e

npm=$PWD/node_modules/.bin

if [ "$ENV" == "production" ]
  then $npm/pm2-docker $PWD/process.prod.yml
  else $npm/pm2-dev start $PWD/process.dev.yml
fi
```

Been deploying code with AWS ECS which handles the container rotation/restarts for you. Not even totally sure that I need `pm2` running inside the container, because I'm pretty sure it restarts itself if the main process goes down.

**Comment by danprince** [comment]
In development I'm using mounting the source directory as a volume so pm2 can watch for changes inside the container.

Before deploying, I build a new docker image that's ready to run, by copying the app source over and running `yarn install`. Then I push the new image to the container registry and point the running containers to the new image tag.

**Comment by beeplin** [comment]
Yeah that makes sense. Thank you~~!!
