### ISSUE TITLE
pm2 cluster communication question

### ISSUE THREAD

**Issue by MDSLKTR** [Unitech/pm2#2644]
Hello, i have a question concerning the pm2 implementation of the node cluster module.
I basicly run this code if i am on a dev environement without pm2:

```
if (process.env.NODE_ENV === 'development') {
    let cpus = os.cpus().length;
    if (cluster.isMaster) {
        for (let i = 0; i < cpus; i++) {
            cluster.fork();
        }
    } else {
        launchInstance(process.pid);
    }
}
```

It launches a simple http server. And so far so good. I know pm2 will spawn its own cluster forks so this code only needs to be on the local machines.

The problem begins though if i try to use my cache module (node-cache module for memory caching) which tries to make the cache available on all instances depending on the worker that is processing the request.

So basicly the constructor looks like this:

```
const NodeCache = require('node-cache'),
    cluster = require('cluster');

class Cache {
    constructor(cluster) {
        if (!Cache.instance) {
            this.mCache = new NodeCache();
            this.resolver = {};
            Cache.instance = this;
        }

        if (cluster.isMaster) {
            cluster.on('online', (worker) => {
                worker.on('message', this.executeTask.bind(null, worker));
            });
        }

        process.on('message', (msg) => {
            if (this.resolver[msg.sig]) {
                this.resolver[msg.sig](msg.body);
                delete this.resolver[msg.sig];
            }
        });

        return Cache.instance;
    }
}
```

So the first problem i guess would that is no `cluster.isMaster` in pm2 i suspect as all instances return false on console.log. But also the cluster listener will never fire the online event and i presume you would need to use the pm2 api for this somehow, but honestly i have no clue where to start.
Any help would be highly appreciated.

**Comment by Unitech** [comment]
Instead of node-cache you can use a database like redis to share data between processes

**Comment by MDSLKTR** [comment]
Surely also an option. How would you connect the redis client to all clusters when using pm2?

**Comment by vmarchaud** [comment]
Just use multiples redis client, worker should be considered standalone, not depending on any in-memory information sharing.
I advise you to read about [12factor application](https://12factor.net/), it help a lot designing web applications.
