### ISSUE TITLE
pm2 startup doesn't correctly detect platform on ubuntu 14.04

### ISSUE THREAD

**Issue by notgiorgi** [Unitech/pm2#2645]
#### Expected behaviour
On ubuntu 14.04 `pm2 startup ubuntu` should use `upstart` on ubuntu 14.04 to setup startup script

#### Actual behaviour
`pm2 startup ubuntu` uses `systemd` for startup script generation on ubuntu 14.04

At the end it says
```bash
/bin/sh: 1: systemctl: not found
[error] exit code: 127
[pm2][error] systemctl enable pm2 failed, see error above.
```

and after that when I restarted the system it didn't boot up, I had to manually fix startup scripts.

my solution was to manually run
```bash
pm2 unstartup
pm2 startup upstart
```

#### Software versions used

```
OS         : Ubuntu 14.04
node.js    : 6.9.x
PM2        : latest
```

**Comment by Unitech** [comment]
Have you run the command `pm2 startup` or `pm2 startup ubuntu`?

How could it detect systemctl automatically if it's not present on the system? https://github.com/Unitech/pm2/blob/master/lib/API/Startup.js#L48

**Comment by notgiorgi** [comment]
Correct, I checked the command history and it was definitely `pm2 startup ubuntu`, I'll update the issue description

**Comment by vmarchaud** [comment]
Because the new LTS version of ubuntu is `16.04` so by default, ubuntu is referring to the version `16.04`.
See code source [here](https://github.com/Unitech/pm2/blob/master/lib/API/Startup.js#L191), you will understand that you should use either `pm2 startup` or `pm2 startup ubuntu14` or `pm2 startup upstart`
We added a check in pm2 v2.3 (will be released next week) with message to say that you didn't specify the right init-system.

**Comment by notgiorgi** [comment]
Thanks, it should be on docs page though.

**Comment by vmarchaud** [comment]
It is on the docs [there](http://pm2.keymetrics.io/docs/usage/startup/#command), i guess it's not clear for you, how would you write that ? (repo is over [here ](https://github.com/pm2-hive/pm2-hive.github.io/blob/master/docs/features/startup.md)if you want to make a PR)

**Comment by notgiorgi** [comment]
Thanks, was looking for that repo, I think It'd be convenient if docs listed all available platforms
