### ISSUE TITLE
Make the 90 seconds server offline alert configurable

### ISSUE THREAD

**Issue by binarykitchen** [Unitech/pm2#2649]
In your online Keymetrics app you have an useful server offline email alert.

It's just that the 90 seconds are too short. When I restart server manually for whatever reasons, it can take longer than that. About 2 mins, depending on my init.d setup.

Can we have these 90 seconds configurable? That would be great.

**Comment by vmarchaud** [comment]
I added it to the keymetrics backlog however i'll close the issue since we try to keep keymetrics and pm2 backlog split.
