### ISSUE TITLE
--log-date-format -i first time will be wrong

### ISSUE THREAD

**Issue by rambo-panda** [Unitech/pm2#2652]
#### Expected behaviour
There is an empty error msg for the first time

#### Actual behaviour
The first boot should not have error

#### Steps to reproduce
this is my script:
```bash
NODE_ENV=test pm2 start app.js --log-date-format 'YYYY-MM-DD_HH:mm:ss' -i 2 -o /dev/null
```
When I use both `--log-date-format` and `-i` for the first time, it will be error （the error msg is empty and only time）:
![image](https://cloud.githubusercontent.com/assets/2776050/22212821/09cd8872-e1cd-11e6-9ccc-3023fef54ee9.png)

When I delete the `--log-date-format` or `-i`  it will be ok;

...

#### Software versions used
```
OS         :  10.12.2
node.js    :  6.9.4
PM2        :  2.23
```

**Comment by vmarchaud** [comment]
I don't get the problem here, you must have a `console.error('')` in your code somewhere, thats it.

**Comment by rambo-panda** [comment]
I'm sure there's no `console.error` because I have tried to set the `console.error` method to `function(){}`

anyway, I found the reason:
```javascript
require('child_process').execSync(command);  // it will be error

require('child_process').execSync(command, {stdio:[0, 1, 2]});  // it is fine
```

thanks very much

**Comment by vmarchaud** [comment]
Closing so
