### ISSUE TITLE
PM2 doesn't respect status flag upon resurrect

### ISSUE THREAD

**Issue by natcl** [Unitech/pm2#2654]
If reporting a bug, please use the following template.

#### Expected behaviour

If I stop some processes and dump/save I expect those processes to be stopped when I restart the computer.

#### Actual behaviour

If I stop some processes then run pm2 dump and restart the computer, the stopped processed will be in online mode upon restart even though the status is still at stopped in the dump file.

#### Steps to reproduce
1. Add some processes
2. Stop some processes
3. Dump/Save
4. Restart computer
5. All processes are online

#### Software versions used

```
OS         : Windows 10
node.js    : 4.7.0
PM2        : 2.3.0
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
...
```

cf CONTRIBUTING.md for more informations

**Comment by BarryCarlyon** [comment]
I just discovered this bug and it's frankly annoying.

Hopefully fixed soon?

**Comment by vmarchaud** [comment]
We don't plan to fix this one before March so feel free to make a PR for it ([link](https://github.com/Unitech/pm2/blob/88f6d0212fe4a2d23e7ededda9a6a01fd46aca06/lib/API/Startup.js#L384) to [relevant](https://github.com/Unitech/pm2/blob/master/lib/God.js#L353) [code](https://github.com/Unitech/pm2/blob/master/lib/God.js#L70) )

**Comment by shubs** [comment]
+1

**Comment by Unitech** [comment]
landing on 4.x
