### ISSUE TITLE
pm2 cluster mode, 2 node going down together on error

### ISSUE THREAD

**Issue by singhmaheshk** [Unitech/pm2#2655]
![image](https://cloud.githubusercontent.com/assets/25312933/22231018/8574fdba-e1a6-11e6-9da4-a80e1430dff1.png)

#### Expected behaviour

I am running a nodejs service on my local with pm2 cluster with 4 instances, I was testing, on error how the instance going down and comes online, I forced service to process.exit(1) on a error and I was expecting only one instance will go down but from the logs its showing two instances are going down together. check the attached image

#### Actual behaviour

two instance are going down together whenever there is node server going down on error. check the attached image

#### Steps to reproduce

Raised a error on a service method and on error event used process.exit(1) to shutdown the service instance.

#### Software versions used

```
OS         : OX X EI
node.js    : V6.4.0
PM2        : 2.3.0
```

**Comment by vmarchaud** [comment]
Can't reproduce with the setup you provided, are you sure that the second process isn't shutting down the same way to first one do ?

**Comment by singhmaheshk** [comment]
Please find the more details. 
First  started my service with pm2 in cluster mode with 4 instance, you can see in below screen, then I made few successful call for service, then I made a call to throw error, which is suppose to stop one instance, but its stopping two instance, you can see in screen shot.

in the below screen shot you can see two instance showing as restarted
![image](https://cloud.githubusercontent.com/assets/25312933/22276367/b197f42e-e278-11e6-9d67-2be2b417e67d.png)

Here is screen shot of log file which is showing instance 0 and 1 went got disconnected and then become online again.

![image](https://cloud.githubusercontent.com/assets/25312933/22276434/1de4b5ea-e279-11e6-8858-aab1b943b1ef.png)

I was expecting only one instance to go offline on an error.

**Comment by singhmaheshk** [comment]
One additional info I would like to add here is, if I just ONLY call the method which throws error (No other method called since service has started) then it just take one instance down. But when I use any other service method and then call method which throws error then it start taking two instance down together.

**Comment by EmmEm** [comment]
Are you using a browser to call the API? Because I've noticed that chrome might try the same path twice if it failed the first time..

**Comment by singhmaheshk** [comment]
I am using Postman to call the service API. If Postman or Chrome is trying same path twice then it should always take 2 instance down, but the strange behavior is  when i just call the API which throws error then it just take one instance down, and when I call any other API which return data and then call the API which throws error then from that point onwards it start taking two instances down.

**Comment by vmarchaud** [comment]
So its obvious that the problem come from your code, otherwise the problem should have been consistent.

**Comment by singhmaheshk** [comment]
I will do some more analysis and share the findings if this is causing by our code or something with pm2.

**Comment by vmarchaud** [comment]
Re-open if you have more information about this bug
