### ISSUE TITLE
Porcess title modification leads to data truncation on long file paths

### ISSUE THREAD

**Issue by gireeshpunathil** [Unitech/pm2#2656]
If reporting a bug, please use the following template.

There are 5 places where PM2 changes the title of the running process, 2 of them can potentially cause information loss and reliability issue. For example, [this](https://github.com/Unitech/pm2/blob/bfacdbf7688b30be37ffce6ceb71fd888709c7cb/lib/ProcessContainerFork.js#L41) and [this](https://github.com/Unitech/pm2/blob/bfacdbf7688b30be37ffce6ceb71fd888709c7cb/lib/ProcessContainer.js#L22) pick up the script file under execution and augments the title with the absolute path of the file. Depending on the length of the file, in conjunction with the OS limitation of changing the command-line argument (as documented in [node.js documentation](https://nodejs.org/dist/latest-v7.x/docs/api/process.html#process_process_title)) this can truncate the data.

#### Expected behaviour

The process title as seen in the ps output shows the complete script path

#### Actual behaviour

The process title as seen in the ps output is truncated at the end, for long files.

#### Steps to reproduce

Issue can be easily reproduced by running a script under PM2, where the script is placed in a file system whose absolute path is long enough (say around 50 chars)

The limitation is easily demonstrated by the below code, when run and check the ps output in another terminal:

`
process.title='ABCDEFGHIHKLMNOPQRSTUVWXYZABCDEFGHIHKLMNOPQRSTUVWXYZABCDEFGHIHKLMNOPQRSTUVWXYZ'
setTimeout(function() {
  console.log('done');
},50000);

`
#### Software versions used

```
OS         : Linux
node.js    : 7.0.*
PM2        : 2.2.3
```

#### PM2 Log output
NA

#### Proposals

1. Control the process title modification under a configuration option, and set the option off by default.

2. Same as 1, but option is on by default, but publish the option so that users can turn it off if necessary.

3. To use the title augmentation and still it useful, provide an option to control the truncation. For example, if the length is more than the OS can manage, the imminent truncation follows - but is controlled by user as to where the truncation can occur, depending on which side (of the title) he thinks is important - the head or the tail.

**Comment by vmarchaud** [comment]
Published PM2 `2.4.0`

**Comment by gireeshpunathil** [comment]
thanks!
