### ISSUE TITLE
PM2 + Nodemon

### ISSUE THREAD

**Issue by anacicconi** [Unitech/pm2#2657]
Hi, I'm new to NodeJs and some developers told me to use PM2 in production and Nodemon in development. However, I just saw that PM2 has a watch option so isn't it better to use only PM2 in production and development? Why are developers still combining both? Thanks ;)

**Comment by vmarchaud** [comment]
Maybe cause of the simplicity to run nodemon in development mode, PM2 will eventually need some configuration see [here](http://pm2.keymetrics.io/docs/usage/application-declaration/) but if done nicely (with dev/prod env definition) you can easily use PM2 in both case.

**Comment by anacicconi** [comment]
Ok, thank you @vmarchaud. I was wondering if there was a reason other than just simplicity but if not I'll go for PM2.

**Comment by eudaimos** [comment]
@vmarchaud unfortunately as I look thru using pm2 for development, there is no option to trigger other checks on restarts like the nodemon which has hooks for the restart event, e.g. I can't run eslint on each restart from a file change.

Unless, do you know of a way to do this with pm2?

**Comment by vmarchaud** [comment]
Its planned via https://github.com/Unitech/pm2/issues/2629 but not yet implemented.
