### ISSUE TITLE
does pm2 ignore node_modules by default with --watch?

### ISSUE THREAD

**Issue by am1stad** [Unitech/pm2#2660]
I'm using latest pm2 2.x and --watch flag. It appears to ignore node_modules by default...as I installed a new module and the app didn't restart.

package.json excerpt:

```
    "start:production": "pm2 start --node-args='--harmony-async-await' index.js -i max --watch --name='api'"

```

**Comment by vmarchaud** [comment]
Yes, [it does by default](https://github.com/Unitech/pm2/blob/master/lib/Watcher.js#L40).
