### ISSUE TITLE
Docker & PM2: String based CMD with environment variables

### ISSUE THREAD

**Issue by ktk** [Unitech/pm2#2661]
Note I was asking this on [Stackoverflow](http://stackoverflow.com/questions/41803392/docker-pm2-string-based-cmd-with-environment-variables) but did not get any answers. If I can resolve the issue I will post the answer there as well. I could not find any other pointers in the documentation about where questions can be asked so I hope this is the right place.

I'm currently using the [shell](https://docs.docker.com/engine/reference/builder/#cmd)-form of `CMD` in Docker for launching my node app:

    CMD /usr/src/app/node_modules/.bin/trifid --config $TRIFID_CONFIG

The env-var `TRIFID_CONFIG`is set to a default in the `Dockerfile`:

    ENV TRIFID_CONFIG config.customer.json

This makes it easy to pass another config file for dev-environments for example.

Now I try to switch this to [PM2](http://pm2.keymetrics.io/docs/usage/docker-pm2-nodejs/) for production. However it looks like all PM2 samples are using the "exec" form which from what I understood does not evaluate ENV-vars. I tried the shell-form with PM2:

    CMD pm2-docker /usr/src/app/node_modules/trifid/server.js --config $TRIFID_CONFIG

But it looks like the variable is not evaluated like this, it fails back to default on execution.

What would be the proper way to handle this with PM2 inside a Docker image?

**Comment by vmarchaud** [comment]
There is a documentation [here](http://pm2.keymetrics.io/docs/usage/docker-pm2-nodejs/), you should find what you are looking for.

**Comment by ktk** [comment]
Note that I did link to this documentation in the issue. Unfortunately this is all the "exec" form of Docker which does have the problem that env-vars are not evaluated. So it doesn't answer my question.

**Comment by vmarchaud** [comment]
My bad i didn't understand the problem, maybe using `CMD pm2-docker $TRIFID_CONFIG` ?

**Comment by ktk** [comment]
@vmarchaud I would miss the executable then?

**Comment by vmarchaud** [comment]
You can define the application inside the ecosystem file (see [this](http://pm2.keymetrics.io/docs/usage/docker-pm2-nodejs/#starting-a-configuration-file))

**Comment by ktk** [comment]
I see what you mean but I again fail to see on this link how env-vars from Docker could be used in this example.

**Comment by vmarchaud** [comment]
Because as you can see [here](https://github.com/Unitech/pm2/blob/master/bin/pm2-docker#L17), there is no option `--config` so you must directly pass the ecosystem at the place of the server : `CMD pm2-docker $TRIFID_CONFIG`

**Comment by ktk** [comment]
So via [Stackoverflow](http://stackoverflow.com/questions/28980307/how-to-pass-arguments-to-app-using-pm2) I probably found the [right issue](https://github.com/Unitech/pm2/issues/13). I think I got it working, will test and then update & close the issue if it works.

**Comment by ktk** [comment]
Ok seems to work:

    CMD pm2-docker /usr/src/app/node_modules/.bin/trifid -- --config $TRIFID_CONFIG

So the trick is to use `--` after the command and the rest will be passed as argument. If I use the shell form env-vars do seem to get evaluated properly.
