### ISSUE TITLE
PM2 logging configuration for JSON format

### ISSUE THREAD

**Issue by nidhhoggr** [Unitech/pm2#2663]
With the latest version of PM2 there is the ability to output all logs in JSON with the following command:

`pm2 logs --json`

PM2 already writes all the log in the `~/.pm2/logs` folder respectively. The issue is, the format
of these logs are not in JSON and it seems there is no option in the configuration to force the
format of the output to be JSON instead.

Is there something in the documentation I am missing?

A work around is writing a deamon to spawn individual processes and redirect all STDOUT of `pm2 logs [app_name] --json` to `~/.pm2/logs/[app_name]-[process_id]-[type].log` I am hoping that something is built in PM2 to care on this instead.

**Comment by vmarchaud** [comment]
Published PM2 `2.4.0`

**Comment by seven-deuce** [comment]
It is not in the documentation, but as far as I could read the source code in new version, this is possible by adding this to the ecosystem config file:

`log_type : 'json'`

**Comment by sebRomeo** [comment]
> It is not in the documentation, but as far as I could read the source code in new version, this is possible by adding this to the ecosystem config file:
> 
> `log_type : 'json'`

I have spent an hour on that :rofl: would someone put in in the doc please :pray:
