### ISSUE TITLE
Send custom signals (e.g. SIGUSR1, SIGHUP) to node processes

### ISSUE THREAD

**Issue by rightaway** [Unitech/pm2#2667]
I'd like to request a feature to be able to send custom signals (e.g. SIGUSR1, SIGHUP) to node processes using pm2. I'm new to pm2 and haven't seen a way to do this, unless I've missed it somewhere.

**Comment by Unitech** [comment]
```bash
$ pm2 sendSignal SIGUSR2 app-name
```
