### ISSUE TITLE
[Feature Request]  Passive Stop and/or Stop Trigger

### ISSUE THREAD

**Issue by jdthorpe** [Unitech/pm2#2668]
Given that (1) Windows lacks good signaling making graceful exits difficult and (B) there is often more than than one way to stop a process gracefully, it would be great to have an option such as (A) `pm2 stop my-process --eventually` whereby pm2 would simply not restart a process when it stops (allowing users to separately send a trigger telling the process [how] to stop ), or (B) `pm2 stop my-process --trigger "custom-stop-trigger"`  whereby pm2 would send a trigger instead of the SIGINT (which in windows simply kills the process).

This would allow windows users to stop gracefully, and allow everyone to implement multiple stop scenarios.  I'd prefer option B, which would allow PM2 to kill the process after `kill_timeout` has elapsed...

**Comment by vmarchaud** [comment]
Actually there is still the old system ([example here](https://github.com/Unitech/pm2/blob/3f5641a67d13b746b861dd2a491206df2eb50cca/test/fixtures/graceful-exit.js)) where you can listen for `shutdown` event via IPC.
I added the documentation right [there ](http://pm2.keymetrics.io/docs/usage/signals-clean-restart/#windows-gracefull-stop)

**Comment by jdthorpe** [comment]
The issue with the example is that when the processes quits, PM2 dutifully spins up another instance of the script, and the resources which were gracefully closed are now open again...

The best I've come up with is  this: 

	pmx.action("stop",(my_name,reply) => {
		graceful_shutdown().then{ () => {
			reply({success:true });
			fs.execSync("pm2 stop " +my_name);
		}).catch(() => reply({success:false}))
	})

combined with 

    > pm2 trigger MyScript stop "MyScript"

but having a process call pm2 to stop itself is a bit cludgy...

**Comment by jdthorpe** [comment]
Also, for what it's worth, this little script suggests that no messages are sent when calling `pm2 stop my_script` or `pm2 gracefulRestart my_script`:, so the linked 'graceful shutdown in windows' method in the docs doesn't seem to be working.

	var process = require('process');
	var winston = require('winston');
	var moment = require('moment');
	require('winston-log-and-exit');

	// add a file transport to winston's default logger
	winston.add(winston.transports.File, 
		{ filename: moment().format("[Hello World]YYYY-MM-DD HH-MM-SS[.log]" )});

	setInterval(()=>{ winston.info("Hello World") },1000)

	process.on('message', function(msg) {
		winston.log_and_exit(/* log level */ "info" ,
							 /* log text  */ "Got message: "+ msg ,
							 /* exit code */ 0 )
	});
