### ISSUE TITLE
pm2 startup -u <user>

### ISSUE THREAD

**Issue by cebor** [Unitech/pm2#2672]
#### Expected behaviour
pm2 creates a startscript for user specifed with `-u` with its default home path.

#### Actual behaviour
pm2 creates a startscript for user specifed with `-u`, but with the home path of the user executing the command

With the `--hp` it works, but shouldn't pm2 pick the default path of the user defined with `-u`

#### Steps to reproduce
```bash
sudo su - root
pm2 startup -u node
# root home path is defined in service
cat /etc/systemd/system/pm2.service
```

#### Software versions used

```
OS         : ubuntu 16.04
node.js    : 7.4.0
PM2        : 2.3.0
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
...
```

cf CONTRIBUTING.md for more informations

**Comment by Unitech** [comment]
Run `pm2 startup` with the current user you want the init script to be generated for, without getting root

**Comment by cebor** [comment]
Works this, if the targeted user has no `sudo`?

Also i think, it worked in a previous version of pm2.

**Comment by vmarchaud** [comment]
After thinking about this, we will not use the default path for the user passed with `-u` because we can't perfectly guess where the home of the user is, its far better to let the user set it.
And you can run `pm2 startup -u node --hp /home/node/.pm2` under root without problem too.
