### ISSUE TITLE
Non-root port binding does not work with pm2

### ISSUE THREAD

**Issue by nodesocket** [Unitech/pm2#2673]
Using [Ghost](https://github.com/TryGhost/Ghost) and binding on `0.0.0.0:80` with a non-root user.

When I start with vanilla node `NODE_ENV=production node index.js` it is able to bind successfully on port 80 as a non-root user using the trick

````bash
setcap cap_net_bind_service=+ep `which node`
````

When I try running the same script *(index.js)* using pm2, I am getting:

````bash
ERROR: (Code: EACCES)
````

This is on **Ubuntu 16.04** running **Node.js v6.9.4** and **PM2 2.3.0**.

**Comment by vmarchaud** [comment]
Can you running this (working for me): http://pastebin.com/fva2hgy6 ?
(cant paste it directly to github since formatting suck with ` inside command)

**Comment by nodesocket** [comment]
Got it. Just needed to run 'pm2 update'.
