### ISSUE TITLE
using pm2 with gps issue on startup

### ISSUE THREAD

**Issue by kaushik-hemant** [Unitech/pm2#2677]
#### Expected behaviour

i connected a gps receiver to pi and create a node application which using gps module as gps gets data there is  a event generated in gps 'on data' function everything working fine like i am using console to see the data. 

#### Actual behaviour
but when i reboot device it run the appliction perfectly but no gps on data function event generated.

**Comment by vmarchaud** [comment]
If your application is correctly restarted that mean that the problem come from your application.

**Comment by kaushik-hemant** [comment]
no actually inner code should also restart with node process as well as i assume or pm2 does something else

**Comment by vmarchaud** [comment]
PM2 just spawn a process with exactly the same option as saved in `dump.pm2` which is generated with `pm2 save`.

**Comment by Unitech** [comment]
> but when i reboot device it run the appliction perfectly but no gps on data function event generated.

You may want to set a small delay before starting the gps module, the initialization of pm2 may be too early for the gps device to be ready to transmit data

anyway this is not linked to an inner pm2 issue

**Comment by kaushik-hemant** [comment]
i solved at my own thanks for reply
