### ISSUE TITLE
`pm2 pull` should perform `npm install`

### ISSUE THREAD

**Issue by GingerPlusPlus** [Unitech/pm2#2678]
As in topic, I think `pm2 pull` should perform `npm install` before restarting the app.

Currently, when dependencies get updated and you run `pm2 pull`, app crashes or misbehaves because of unmet dependency, which is not very nice.

I have to run `npm install` and `pm2 restart` manually, after figuring out the reason.

Is there a reason for not running `npm install`?

**Comment by vmarchaud** [comment]
Because its technology agnostic, but you can use `post_update` option in process file ([docs ](http://pm2.keymetrics.io/docs/usage/application-declaration/#control-flow)here)
