### ISSUE TITLE
log:err event not captured with launchBus

### ISSUE THREAD

**Issue by balasivagnanam** [Unitech/pm2#2679]
#### Expected behaviour
I am trying to do something when there is an error in my express server script.
so based on my code below, things gets logged in error.log and output.log.
so whenever there is an error log printed in error.log there should be "logged error" printed in output.log as well.
```
var pm2 = require('pm2');

pm2.launchBus(function(err, bus) {
  console.log('connected', bus);

  bus.on('process:exception', function(data) {
    console.log(arguments);
  });

  bus.on('log:err', function(data) {
    console.log('logged error',arguments);
  });

  bus.on('reconnect attempt', function() {
    console.log('Bus reconnecting');
  });

  bus.on('close', function() {
    console.log('Bus closed');
  });
});

```

...

#### Actual behaviour
There is an error in error.log which is 

**Error.log:**
> 2017-02-02 20:27 +08:00: (node:8308) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
> 2017-02-02 20:27 +08:00: Invalid or unsupported zip format. No END header found

but Output.log shows only the connection success message and another error message but not the error related to "Invalid or unsupported zip format. No END header found"
Output.log

> 2017-02-02 20:27 +08:00: Listening on port 3001...
> 2017-02-02 20:27 +08:00: connected SubEmitterSocket {
>   sock: 
>    SubSocket {
>      opts: {},
>      server: null,
>      socks: [ [Object] ],
>      settings: 
>       { hwm: Infinity,
>         identity: '8308',
>         'retry timeout': 100,
>         'retry max timeout': 5000 },
>      subscriptions: [],
>      onmessage: [Function: bound ],
>      type: 'client',
>      _events: {},
>      _eventsCount: 0,
>      connected: true,
>      retry: 100 },
>   bind: [Function: bound ],
>   connect: [Function: bound ],
>   close: [Function: bound ],
>   listeners: [] }
> 2017-02-02 20:27 +08:00: logged error { '0': 
>    { data: '(node:8308) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.\n',
>      at: 1486038472973,
>      process: { rev: null, name: 'server', pm_id: 0 } } }
> 2017-02-02 20:27 +08:00: apicalled
> 2017-02-02 20:27 +08:00: { projectname: 'test',
>   projectincharge: 'test',
>   projectemail: 'xxx' }
> {"file":{"fieldName":"file","originalFilename":"PASSES.zip","path":"C:\\Users\\balas\\AppData\\Local\\Temp\\gmmaMaiBQXPDtO9mULuP0ij-.zip","headers":{"content-disposition":"form-data; name=\"file\"; filename=\"PASSES.zip\"","content-type":"application/x-zip-compressed"},"size":245289,"name":"PASSES.zip","type":"application/x-zip-compressed"}}
> C:\Users\balas\AppData\Local\Temp\gmmaMaiBQXPDtO9mULuP0ij-.zip
> 2017-02-02 20:27 +08:00: C:\Codes\momtest0.5-cdn\project-files\test
> 2017-02-02 20:27 +08:00: pow!
> 2017-02-02 20:27 +08:00: all dropped
> 2017-02-02 20:27 +08:00: return executing
> 2017-02-02 20:27 +08:00: null
> 2017-02-02 20:27 +08:00: PASSES.zipupload complete for user:
> 2017-02-02 20:27 +08:00: compliance api called
> PASSES.zip
> 2017-02-02 20:27 +08:00: Listening on port 3001...

**Comment by vmarchaud** [comment]
Because `log:err` channel is used by all applications to broadcast their error output so it may come from another application. Which PM2/Node version ? Can you give us the ecosystem used to launch these application ?

**Comment by balasivagnanam** [comment]
pm2 - 2.3.0
node - 7.2.1

using windows cmd to launch the application

my json config
```
{
  "script"          : "server.js",
  "error_file"      : "error.log",
  "out_file"        : "output.log",
  "merge_logs"      : true,
  "log_date_format" : "YYYY-MM-DD HH:mm Z"
}
```

**Comment by vmarchaud** [comment]
Can't reproduce, i believe our code is pretty strong for the logging in fork mode since we use the nodejs api (see [here](https://github.com/Unitech/pm2/blob/master/lib/God/ForkMode.js#L109)). Have you a way to reproduce the problem with a simple file ?

**Comment by vmarchaud** [comment]
We use it for the new `pm2 monit` [here](https://github.com/Unitech/pm2/blob/master/lib/API/Extra.js#L383) without any problem, re-open if you can provide a example that you believe can be easily reproduced on our side.
