### ISSUE TITLE
pm2 build script

### ISSUE THREAD

**Issue by peacemakr** [Unitech/pm2#2685]
I've been using PM2 for some time and very happy with it. Thanks.

However, I wanted to achieve the following and wanted to know how it can be done through PM2.

PM2 watches a few files in my repo and restarts the app as soon as they're updated. Now, I want to run a script (eg. build script) before the app is reloaded. Is it possible? I used to do it through npm's build option.

**Comment by vmarchaud** [comment]
Currently not possible, i added it into the issue #2629 that list all things to be done with the watch system (closing this one).
