### ISSUE TITLE
Check if there is new PM2 version 

### ISSUE THREAD

**Issue by Unitech** [Unitech/pm2#2686]
Notify user if there is a new PM2 version available

https://github.com/yeoman/update-notifier

**Comment by vad1m** [comment]
I would advice to not add this as default behavior (just add this as additional CLI command, if you need it). App shouldn't "call home" bypassing package management systems.

**Comment by vmarchaud** [comment]
For some people indeed its useless but considering that some people doesn't check if their dependencies are up-to-date, we discussed that it was a good idea to hint our users that we published an update.
For example `oh-my-zsh` do this every two weeks, we could do something alike, that ping the latest version for update and then print it on the CLI every few days as a friendly reminder.
