### ISSUE TITLE
Define parallel reload / restart via --parallel <int>

### ISSUE THREAD

**Issue by Unitech** [Unitech/pm2#2690]

**Comment by jontelm** [comment]
I running 4 copies in fork, when I run "reload all" every instance take some time to start because of node and this makes some request to the server to fail for a second or two. Will this solve that kind of problems?

**Comment by vmarchaud** [comment]
@jontelm No, i advise you read about graceful restart here : http://pm2.keymetrics.io/docs/usage/signals-clean-restart/

**Comment by jontelm** [comment]
Thanks you can remove this comment.

**Comment by Unitech** [comment]
Published on PM2 2.6.0:

```bash
$ npm install pm2@latest -g
$ pm2 update
```

**Comment by shaharmor** [comment]
@Unitech can this be defined in the JSON configuration?
