### ISSUE TITLE
pm2 restarts app multiple time during save when watch enabled.

### ISSUE THREAD

**Issue by ffallah** [Unitech/pm2#2691]
I am using a remote editor to work on my code through sshfs.
My latency to server is about 120ms.
When I save my changes on remote editor, pm2 restarts the app several time during save period.

#### Expected behaviour
It should only restart after save is finished.

#### Actual behaviour
Restarts app multiple times during save period.

#### Steps to reproduce
Save file through sshfs with a high latency with watch enabled.

#### Software versions used

OS         : Debian 8.0
PM2        : 2.3.0

#### Suggested solution

Add a timer which would delay the restart for x milliseconds after change is detected.
Or somehow detect when the save is finished and then restart.

**Comment by vmarchaud** [comment]
Its because FS over network is specific, as [advised](https://github.com/paulmillr/chokidar#performance) in `chokidar` : you should add the option : `usePolling: true` and in your case `awaitWriteFinish: true`. ([docs explain it too](http://pm2.keymetrics.io/docs/usage/watch-and-restart/))
