### ISSUE TITLE
how to get the process info by ps -fC(under linux)?

### ISSUE THREAD

**Issue by tomleader** [Unitech/pm2#2692]
when u need to start a node app(linux env, centos),

**situation 1(pure node app):**

```js
node app.js
```
then u can check the process name by 

```
ps -fC node
```

usually u can get results like:

```
UID        PID  PPID  C STIME TTY          TIME CMD
root     10256     1  0  2016 ?        00:00:21 node app.js
```

**situation 2(use pm2):**

```js
pm2 start app.js --name 'testapp'
```
then u also check the process name by 
```
ps -fC node
```
or check the app name:

```
ps -fC testapp
```
the result is null,like:
```
UID        PID  PPID  C STIME TTY          TIME CMD
```

so the question is 
when I use pm2 start a process, how can I get the process info by ps -fC ?

**Comment by vmarchaud** [comment]
Two solution : 
- Pids file are in `~/.pm2/pids/` so just cat the pid of your application to use `ps`
- Wait for pm2 `2.4.0` to be published, use env var `PROCESS_TITLE` to set the process title and then `ps -fC processTitle` (see https://github.com/Unitech/pm2/issues/2656)
