### ISSUE TITLE
Change the ip and port for the httpinterface.

### ISSUE THREAD

**Issue by garprogram** [Unitech/pm2#2693]
I have read the documentation and should change the env variables PM2_API_IPADDR and PM2_API_PORT.
 I am trying to do it using the ecosystem.json file but I can not start the httpinterface with json.

How can I change the ip and port for the httpinterface?
Is it possible to start the web interface with a json file?

Thanks

**Comment by vmarchaud** [comment]
`PM2_API_IPADDR=127.0.0.1 PM2_API_PORT=8080 pm2 web`
You can launch the web interface via CLI, or you just get [the file](https://github.com/Unitech/pm2/blob/master/lib/HttpInterface.js) and run it with an ecosystem file
