### ISSUE TITLE
PM2 monit old interface

### ISSUE THREAD

**Issue by kirkins** [Unitech/pm2#2699]
How do I switch between these two visual modes on pm2?

![screenshot_2017-02-07_21-44-28](https://cloud.githubusercontent.com/assets/9503662/22713071/df9e51c2-ed7e-11e6-99e5-5fde7c859b51.png)

![screenshot_2017-02-07_21-44-41](https://cloud.githubusercontent.com/assets/9503662/22713073/e287d02a-ed7e-11e6-98ba-f663345fda20.png)

**Comment by vmarchaud** [comment]
We totally removed the old mode since it was broken, so there is only the bottom one.

**Comment by kirkins** [comment]
What was broken about it? If the bug is fixed will it be brought back in a future update?

**Comment by vmarchaud** [comment]
No, the new one has more features (and show the cpu/mem too) so there is no point brought it back.

**Comment by Unitech** [comment]
We may add back this *interface*, reopening

**Comment by grit96** [comment]
The new interface has very high CPU usage and freezes after being open for some time.

**Comment by vmarchaud** [comment]
@grit96 I just pushed a commit to fix high CPU usage, could you retry : `npm install -g Unitech/pm2#development` ?

**Comment by grit96** [comment]
I will leave `pm2 monit` running and see how it performs leaving it for a while.

**Comment by kirkins** [comment]
Thanks my co-worker agrees we loved the old it was perfect for picking up on memory leaks and other potential problems!

**Comment by grit96** [comment]
I left it running overnight and now it is using 100% CPU and is completely frozen

**Comment by soyuka** [comment]
Made https://github.com/soyuka/pm2-cli-monit for a temporary solution.

**Comment by vmarchaud** [comment]
It will be re-added in `2.4.1` before the end of the week

**Comment by vmarchaud** [comment]
It will be aliased as `pm2 oldmonit`

**Comment by cuteboi** [comment]
This is perfect, I came here for the same reason. Mine freezes within an hour of usage, as there is a lot of log output on my application.  That old interface lets me visualize everything, and I had my terminator window perfectly set up like the new "dash" looks

**Comment by cuteboi** [comment]
![image](https://cloud.githubusercontent.com/assets/3236512/23136471/7afcd30e-f762-11e6-8b37-776208e29f0b.png)

Can't wait for 2.4.1

**Comment by Unitech** [comment]
You can already use 2.4.1:

```bash
$ npm install Unitech/development -g
```

**Comment by vmarchaud** [comment]
Released in pm2 `2.4.1` : use `pm2 imonit` to get the old interface back
