### ISSUE TITLE
Deploying doesn't work with js configuration file

### ISSUE THREAD

**Issue by bitbreakr** [Unitech/pm2#2708]
If reporting a bug, please use the following template.

#### Expected behavior

"post-deploy" : "npm install && pm2 startOrRestart ecosystem.config.js --env production"

#### Actual behaviour

When creating an ecosystem file for deployment, it creates a file named "ecosystem.config.js"
but "post-deploy" expects this file named "ecosystem.json"
#### Steps to reproduce

Typing command : pm2 ecosystem
...

#### Software versions used

```
OS         : Mac OS Sierra
node.js    :6.9.1
PM2        : 2.1.6
```

#### PM2 Log output

Doesnt help

cf CONTRIBUTING.md for more informations

Yan Philippe

**Comment by nicodinh** [comment]
http://pm2.keymetrics.io/docs/usage/application-declaration/

You can use a JSON (ecosystem.json) or Javascript (ecosystem.config.js) configuration file.

**Comment by vmarchaud** [comment]
You just need to edit the line of `post-deploy` to use `ecosystem.config.js`
