### ISSUE TITLE
PM2 not showing complete info on command line 

### ISSUE THREAD

**Issue by hamza610** [Unitech/pm2#2711]
**pm2 list** command should yield this result:
![pm2issue2](https://cloud.githubusercontent.com/assets/25743285/22884123/11047a58-f215-11e6-95f6-262259086b90.png)

However it's yielding the following result missing out on important info like pid, number of restarts, uptime etc.

![pm2issue](https://cloud.githubusercontent.com/assets/25743285/22884112/03c14b28-f215-11e6-94a7-3b55b14126ea.png)

Everything was working fine untill I updated PM2 to the latest version

OS         : Windows Server 2003
node.js    : 5.8.0
PM2        : 2.4.0

**Comment by vmarchaud** [comment]
Normal behavior, we modified the table to show less data because it was buggy before, you just need to increase your terminal size, we show the normal list above 90 columns.
