### ISSUE TITLE
selectively start or exclude certain apps in my multi app ecosystem.config.js 

### ISSUE THREAD

**Issue by tomdavidson** [Unitech/pm2#2721]
Usage guidance.

I would like to selectively start or exclude certain apps in my multi app ecosystem.config.js . It is js so I suppose I can do anything, but is there a PM2 convention for only starting a particularly app if dev (dev by node_env, cli flag, npm_lifecycle_event, anything)?

**Comment by vmarchaud** [comment]
Like explained in #2717 (my bad on this one) you can just create multiple ecosystem file, they just need to end with `.config.js`.
In the case of thisissue, you can use the flag `--only appName` to make an action on one application, but you can't make conditional use of it.

**Comment by tomdavidson** [comment]
Thanks @vmarchaud. In prod I want to start apps A, B, C but in dev I want to start apps A, B, C, and D. '--only' doesn't quite cover the use case, but I could just have two seperate config.js files repeating the app declarations.
