### ISSUE TITLE
[PM2][WARN] Applications API not running and ..502 Bad Gateway nginx/1.4.6 (Ubuntu)

### ISSUE THREAD

**Issue by MilanMahata** [Unitech/pm2#2723]
[PM2][WARN] Applications API not running and ..502 Bad Gateway nginx/1.4.6 (Ubuntu)
node.js 502 Bad Gateway nginx/1.4.6 (Ubuntu) already restart reboot but unable to fix the problem i face the problem after reboot before that all was working fine

**Comment by MilanMahata** [comment]
please help me its very urgent

**Comment by vmarchaud** [comment]
Please re-open and complete the issue template, can help you without any information.

**Comment by MilanMahata** [comment]
[PM2] Spawning PM2 daemon with pm2_home=/home/ubuntu/.pm2
[PM2] PM2 Successfully daemonized
[PM2][WARN] Applications API not running, starting...


this is the problem after reboot and still getting  500 Internal Server Error
nginx/1.4.6 (Ubuntu)

**Comment by MilanMahata** [comment]
than vmarchaud  for your  reply  please help me

**Comment by vmarchaud** [comment]
There isn't any error/problem with what you reported.

**Comment by MilanMahata** [comment]
[PM2][WARN] Applications API not running, starting...

**Comment by vmarchaud** [comment]
Still not an error

**Comment by MilanMahata** [comment]
i am not geeting  like 
[PM2] Applying action restartProcessId on app [API](ids: 0)
[PM2] [API](0) ✓
its work fine after the reboot i unable to start and show  502 Bad Gateway
nginx/1.4.6 (Ubuntu)

**Comment by vmarchaud** [comment]
Checkout the [documentation](http://pm2.keymetrics.io/docs/usage/startup/)
