### ISSUE TITLE
salt exec "pm2 status" is not result

### ISSUE THREAD

**Issue by zhaochenglan** [Unitech/pm2#2727]
1、[root@deploy ~]# salt '*.*.*.*' cmd.run " /data/dist/node6.9/bin/pm2 status"
*.*.*.*:
    [PM2][Initialization] Environment variable HOME (Linux) or HOMEPATH (Windows) are not set!
    [PM2][Initialization] Defaulting to /etc/.pm2
    ┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────────┐
    │ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ watching │
    └──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────────┘
     Use `pm2 show <id|name>` to get more details about an app

2、[root@deploy ~]# /data/dist/node6.9/bin/pm2 status
┌────────────┬────┬──────┬──────┬────────┬─────────┬────────┬─────┬───────────┬──────────┐
│ App name   │ id │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem       │ watching │
├────────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────┼───────────┼──────────┤
│ nuxt-start │ 0  │ fork │ 1262 │ online │ 0       │ 3D     │ 0%  │ 63.6 MB   │ disabled │
└────────────┴────┴──────┴──────┴────────┴─────────┴────────┴─────┴───────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app

**Comment by vmarchaud** [comment]
You need to run `pm2 status` as the same user that has started the daemon,

**Comment by zhaochenglan** [comment]
Run pm2 with the same user
[root@deploy sandaman]# ps aux|grep pm2
root      1327  0.0  0.0 893860 19156 ?        Ssl  Feb17   0:02 PM2 v2.4.0: God Daemon (/etc/.pm2)                                                   
root      7705  0.0  0.0 893860 19848 ?        Ssl  Feb17   0:03 PM2 v2.4.0: God Daemon (/etc/.pm2)                                                   
root      7848  0.0  0.0 895268 20232 ?        Ssl  Feb17   0:03 PM2 v2.4.0: God Daemon (/etc/.pm2)                                                   
root     10523  0.0  0.0 103268   856 pts/11   S+   09:22   0:00 grep pm2
root     13943  0.1  0.0 1225004 25024 ?       Ssl  Feb17   8:03 PM2 v2.4.0: God Daemon (/root/.pm2)                                                  
root     14917  0.0  0.0 895372 22564 ?        Ssl  Feb16   0:03 PM2 v2.2.3: God Daemon (/etc/.pm2)                                                   
root     17385  0.0  0.0 934052 26140 ?        Sl   Feb16   0:00 node /gaodun/dist/node6.9/bin/pm2 logs
root     23325  0.0  0.0 893608 24260 ?        Sl   Feb16   0:00 node /gaodun/dist/node6.9/bin/pm2 --update-env

**Comment by vmarchaud** [comment]
`root 14917 0.0 0.0 895372 22564 ? Ssl Feb16 0:03 PM2 v2.2.3: God Daemon (/etc/.pm2)`
`root 7848 0.0 0.0 895268 20232 ? Ssl Feb17 0:03 PM2 v2.4.0: God Daemon (/etc/.pm2)`
You have two different daemon running, kill them all with `pkill PM2` and restart your processes.

**Comment by zhaochenglan** [comment]
How to definition path  for /etc/.pm2

**Comment by vmarchaud** [comment]
Export environment var `PM2_HOME` to `/etc/.pm2`

**Comment by zhaochenglan** [comment]
Thank you very much.

**Comment by sakib412** [comment]
> Export environment var `PM2_HOME` to `/etc/.pm2`

Thanks. It works for me.
