### ISSUE TITLE
pm2 monit - freeze after being open for some time

### ISSUE THREAD

**Issue by a8775** [Unitech/pm2#2728]
I'm experiencing the issue mentioned in the https://github.com/Unitech/pm2/issues/2699 by @grit96

"The new interface has very high CPU usage and ***freezes after being open for some time***. It's not very suitable for continuous monitoring like the old one was."

```
OS         : Debian 8.6
node.js    : 7.4.0
PM2        : 2.4.0
```

**Comment by vmarchaud** [comment]
Closing in favor of #2699
