### ISSUE TITLE
Pm2 list this does not do anything

### ISSUE THREAD

**Issue by emazzu** [Unitech/pm2#2731]
If reporting a bug, please use the following template.

#### Expected behaviour
I hope the command shows the start process
...

#### Actual behaviour
nothing
...

#### Steps to reproduce
pm2 list
...

#### Software versions used
```
OS         : linux
node.js    : 5.2.0
PM2        : 0.15.10
```

#### PM2 Log output
nothing back screen

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

```
...
```

cf CONTRIBUTING.md for more informations

**Comment by vmarchaud** [comment]
Update pm2.
