### ISSUE TITLE
How to run a node application as sudo on startup

### ISSUE THREAD

**Issue by mohamed-elsabagh** [Unitech/pm2#2733]
I have a nodejs application which won't work unless it run as sudo.
I run it as sudo like that ```sudo pm2 start process.js``` and this force it to run as sudo, the problem is when I restart the machine the pm2 start the node application but not as sudo, so it doesn't work, how can I run a node application as sudo on startup by default

**Comment by vmarchaud** [comment]
You just need to spawn a PM2 daemon as root and run `pm2 startup` as root too.

**Comment by mohamed-elsabagh** [comment]
I already did I am running it on pi here are the steps

```sudo pm2 startup systemd -u pi```

go to ```/etc/systemd/system/pm2.service``` and changed ```Environment=PM2_HOME=/root/.pm2``` to ```Environment=PM2_HOME=/home/pi/.pm2```

```sudo env PATH=$PATH:/usr/local/node-v6.9.5-linux-armv6l/bin /usr/local/node-v6.9.5-linux-armv6l/lib/node_modules/pm2/bin/pm2 startup systemd -u pi --hp /home/pi}```

```
sudo pm2 start script.js
sudo pm2 save```

now this run now as sudo, if I restart the device and do ```pm2 list``` I can find node app is running but not as sudo
