### ISSUE TITLE
Cluster Mode same request processed twice

### ISSUE THREAD

**Issue by swapnil001** [Unitech/pm2#2734]
I have my instance running in cluster mode (2 CPU). Is it possible that same request is processed by 2 different CPU? I made one request to my backend and the same request was processed by both CPU at the same time.

How is this possible? And if yes, then how can I stop it from happening?

**Comment by vmarchaud** [comment]
No it isnt possible, each request is balanced to only one CPU, see implementation detail [here](https://nodejs.org/dist/latest-v6.x/docs/api/cluster.html#cluster_how_it_works)
