### ISSUE TITLE
Pm2 restart when the role does not work, need to kill the process to restart？

### ISSUE THREAD

**Issue by chenzezhang** [Unitech/pm2#2735]
## In the use of pm2, encountered a more headaches, restart pm2 application has not been updated, need to kill pm2 process or node process, restart, the problem can be resolved, do not know why?

**Comment by Unitech** [comment]
You look like having typing issues too, not sure it comes from the github text editor though

**Comment by vmarchaud** [comment]
Update PM2 to the latest version and next time open a issue by completing the issue template.
