### ISSUE TITLE
pm2 launching...

### ISSUE THREAD

**Issue by Maxim-Chugaev** [Unitech/pm2#2737]
pm2 2.0.18
node v7.4.0

```
[Keymetrics.io] [Agent updated] Agent ACTIVE - Web Access: https://app.keymetrics.io/
[PM2] PM2 Successfully daemonized
[PM2][WARN] Applications app not running, starting...
```
Application status launching, very long time!!
My app already started, but pm2 show uptime 0.
pm2 broken, why?
reboot can not help me!

**Comment by vmarchaud** [comment]
Please provide pm2 logs or somethings that can help reproduce the issue.
