### ISSUE TITLE
pm2 startup does not generate pm2-init.sh

### ISSUE THREAD

**Issue by martirius** [Unitech/pm2#2744]
Hello,
i'm having a problem with pm2. When i launch the command pm2 startup it does not generate the pm2-init.sh file in /etc/init.d/ and pm2 does not start on boot... Some suggestion?
I'm working on a Raspberry Pi 3 with Raspbian jessie

**Comment by vmarchaud** [comment]
Because the startup system has been refactored, you should find your service unit file under `/etc/systemd/sytemd/`

**Comment by martirius** [comment]
Thanks for fast reply! 
However, it does not start on boot, because properly saved processes are not resurrected at system boot.
How to fix this?

**Comment by vmarchaud** [comment]
You need to run `pm2 save` while running the process you want to be started, like this pm2 will take a snapshot of the process.

**Comment by martirius** [comment]
I think i didn't explain correctly my situation.
I run pm2 start *myProcess* and then pm2 save. Then i run pm2 startup. But if i reboot the system, *myProcess* is not resurrected. Instead, if i run pm2 resurrect after reboot, pm2 starts as a daemon( it should have to start at boot,right?) and resurrects *myProcess*.
