### ISSUE TITLE
pm2 docker and python

### ISSUE THREAD

**Issue by quanvuong** [Unitech/pm2#2746]
Does anyone have an example Dockerfile that uses pm2-docker and python ? I have been unable to make them work well together : (

**Comment by smolinari** [comment]
What are you trying to accomplish? 

You do know, pm2 is for specifically built for Node applications, right?

Scott

**Comment by soyuka** [comment]
Python works fine :) You just have to specify `fork` mode.

@quanvuong can you please share configuration files? We need more informations to help you.

**Comment by quanvuong** [comment]
I think it might have something to do with the Overlay File System.

If I build and run the Dockerfile below, my script executive normally 

```
FROM python:3.5

COPY requirements.txt ./server/requirements.txt

WORKDIR ./server

RUN pip install -r requirements.txt

COPY ./server/ ./

CMD [ "python", "./server.py"]

```

But if I have the following, the I get the error `script not found : /server.py`

```
FROM python:3.5

COPY requirements.txt ./server/requirements.txt

WORKDIR ./server

RUN pip install -r requirements.txt

COPY ./server/ ./

FROM node:6.10

RUN npm install pm2 -g

CMD [ "pm2-docker", "./server.py" ]
```

I tried using the image `keymetrics/pm2-docker-alpine:6`, but there seems to be a few missing npm packages (`commander`), but running from `node:6.10` seems to suffice,

**Comment by vmarchaud** [comment]
Anything in the docker logs ? Checkout `/root/.pm2/pm2.log` too

**Comment by quanvuong** [comment]
Since my container doesn't run after the error, I can't ssh in to retrieve the logs. Do you have any suggestion on how I might go about doing that @vmarchaud ? Thanks!

**Comment by smolinari** [comment]
Um, @quanvuong. I think your problem is the second FROM. Two FROMs do not merge images. 

Start with the node image, install Python, then do the rest. 

Scott

**Comment by quanvuong** [comment]
@smolinari do you know how I can install python inside an image ? I tried:

```
RUN apt-get update
RUN apt-get install python3
``` 

But then I got `After this operation, 18.8 MB of additional disk space will be used.
Do you want to continue? [Y/n] Abort.`

**Comment by smolinari** [comment]
You can use the `-y` option. 

RUN apt-get update && \
        apt-get -y install python3

It is also good practice to combine `RUN` commands, in order to reduce the number of layers in your image. 

Scott

**Comment by quanvuong** [comment]
yeah that did the trick. Thanks!
