### ISSUE TITLE
Allow to register pm2 service in userspace

### ISSUE THREAD

**Issue by vmarchaud** [Unitech/pm2#2750]
See https://github.com/Unitech/pm2/issues/2749

**Comment by crazyyi** [comment]
Any progress on this one? I am watching a tutorial on Youtube and I found I still need to run pm2 startup centos then register a new user to get the privilege.

**Comment by vmarchaud** [comment]
Not sure i get you but you can already register a pm2 service for a specific user using the `--user` options, you just need root privileges to do this, the aim of this issue is to register the service in userspace without having to go root.
Anyway feel free to make a PR if you want this implemented, we don't have much time to give to pm2 currently.

**Comment by prupert** [comment]
Any update on this? There is no need to require root privileges to manage a user-specific systemd service (provided you enable session lingering). This way the service inherits all limits imposed on user it's running under. It also auto-starts and works all the same.

**Comment by Grafikart** [comment]
Hi, this issue is flagged as complete but I can't find on the documentation how to do a startup to create a userspace service (a service registered with systemctl --user that does not require sudo access).
