### ISSUE TITLE
commit or stash your changes before deploying

### ISSUE THREAD

**Issue by quinn** [Unitech/pm2#2758]
Why? This seems like unnecessary hand-holding. All it needs to do is pull from the remote on the server, what is local doesn't matter

**Comment by vmarchaud** [comment]
You can use `--force` to bypass this restriction, this has been put in place because people complained sometime that the change weren't deployed but the problem came from them cause they didnt commit.

**Comment by kgrosvenor** [comment]
@vmarchaud i don't understand, i'm using continuous deployment, the changes are always the latest each time i run deploy?
