### ISSUE TITLE
PM2 crashes and unable to restore process afterwards

### ISSUE THREAD

**Issue by nkt217** [Unitech/pm2#2760]
PM2 crashed on one of our server and was unable to restore the processes in the dump.pm2 file. 

PM2 version: 1.1.3
The logs in the pm2.log were like this: 
<img width="398" alt="screen shot 2017-03-10 at 15 33 16" src="https://cloud.githubusercontent.com/assets/11870018/23791980/28e6feb2-05ab-11e7-98a7-3a376176ab88.png">

We have checked the dump.pm2 file and it has all the required process list which has to be respawned.

**Comment by vmarchaud** [comment]
Its seems to come from the nodejs implementation of cluster, what is your node version ?

**Comment by imdzeeshan** [comment]
`pm2 resurrect` is the command if anyone got here searching for 'load processes from dump.pm2.'
