### ISSUE TITLE
pm2 run app in Development mode

### ISSUE THREAD

**Issue by kodekrendel** [Unitech/pm2#2762]
I am setting up https://github.com/nuxt/express app on my AWS VPS. 
When I run app standalone `npm start` everything works as expected in Production environment. 
But when I try to daemonize this script, pm2 run it in Development (I can say it because FOUC appers, so nuxt doesn't include CSS in Development).
How can I fix it and what can cause the issue?

**Comment by kodekrendel** [comment]
https://github.com/nuxt/express/issues/13

**Comment by kodekrendel** [comment]
My ecosystem.conf.js:

```
module.exports = {
  apps : [{
    name: "test",
    script: "server.prod.js",
    env: {
      "NODE_ENV": "development"
    },
    env_production: {
      "NODE_ENV": "production"
    }
  }]
}
```

**Comment by kodekrendel** [comment]
`NODE_ENV=production pm2 start server.prod.js` - doesn't work

**Comment by yunnysunny** [comment]
```	
pm2 start server.prod.js --env production
```

**Comment by vmarchaud** [comment]
@yunnysunny is right, its documented here : http://pm2.keymetrics.io/docs/usage/application-declaration/#environement-definition

**Comment by kodekrendel** [comment]
No, he is not right. I tried that in the first place. Application still runs in DEVELOPMENT. I still have no answer how to run this app in PRODUCTION (without pm2 it run in PROD ok).

**Comment by vmarchaud** [comment]
Its tested [here](https://github.com/Unitech/pm2/blob/88f6d0212fe4a2d23e7ededda9a6a01fd46aca06/test/programmatic/env_switching.js#L70) with the API and [here](https://github.com/Unitech/pm2/blob/51edbc55bbf71d59ceb9a8a222c6cb55bf4e7b63/test/bash/env-refresh.sh#L74) with the CLI so the problem definitly come from you.
