### ISSUE TITLE
monit dashboard "Global Logs" window make it for each process if highlighted

### ISSUE THREAD

**Issue by pantchox** [Unitech/pm2#2764]
I think it is also logical to be able to switch to a specific process output rather then have "Global" output of all of them.

Thanks!

**Comment by G-Rath** [comment]
I'm in favor of this too - When I started using PM2 for basic management of some experimental node apps I was pretty impressed, but discovering that the log window is global made it a lot more unwieldy to use.

**Comment by Tory73** [comment]
I fully agree with that. I love monit, but these global logs for all processes making me nuts.

**Comment by Unitech** [comment]
alright will be shipped on 3.4.2
