### ISSUE TITLE
How to print uncaughtexception log with date prefix in pm2

### ISSUE THREAD

**Issue by yunnysunny** [Unitech/pm2#2767]
I come across an troubling problem, when the process started with pm2 broke down, but its uncaughtException's log will be wirtten via pm2 without date format. In other words, it make me have no idea when the process broke down.

To description the problem simply, I will give a two lines js file:

```
console.log(xxx);
console.log('over');
```

**The code of err.js**  

Then I start err.js with pm2:  

```
pm2 start err.js --log-date-format "YYYY-MM-DD HH:mm"
```

Unfortunately,the error log is printed without date format:

    ReferenceError: xxx is not defined
        at Object.<anonymous> (F:\temp\sodu_build\err.js:1:75)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Function._load (d:\Users\sunny\AppData\Roaming\nvm\v6.9.2\node_modules\pm2\node_modules\.0.6.8@pmx\lib\transaction.js:62:21)
        at Object.<anonymous> (d:\Users\sunny\AppData\Roaming\nvm\v6.9.2\node_modules\pm2\lib\ProcessContainerFork.js:52:21)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)

**The output of error log**

This issue can be reproduced easily. And the error log is very important for developers , we have to known when the app broke down. I have no idea why not the pm2 maintainer add the support of the date format of error log.

> I use the latest version of 2.4.2.

**Comment by vmarchaud** [comment]
Can't reproduce with `console.error(new Error())` and the command you provided, what is your node version ? Can you provide a sample file to reproduce the issue ?

**Comment by yunnysunny** [comment]
`console.error(new Error())` can not make the process break down, use `console.log(xxx)`  instead. Since the variable `xxx` is undefined, the node process will trigger an uncaughtexception and then pm2 will print the error log.
So the [demo file](https://gist.github.com/yunnysunny/13757ee442a4674f761fb04ebf6d5fa3) could be only one line:
```
console.log(xxx);
```
> My environment:
pm2 : 2.4.2
os : win 10
node : 6.9.2

**Comment by vmarchaud** [comment]
Can't reproduce with node `7.4.0`, pm2 `2.4.2` and Ubuntu `16.04` : 
![image](https://cloud.githubusercontent.com/assets/2820968/23943647/6877f054-0970-11e7-8203-47bed0b21fa2.png)

**Comment by yunnysunny** [comment]
I restart my pc , and it works ok now. I think the problem may cased by old version (2.2.x). I update the pm2 from 2.2 to 2.4, and the old version already existed in memory before I restarted.
