### ISSUE TITLE
enable startup for openwrt

### ISSUE THREAD

**Issue by yangpu** [Unitech/pm2#2768]
pm2 startup [ubuntu | ubuntu14 | ubuntu12 | centos | centos6 | arch | oracle | amazon | macos | darwin | freesd | systemd | systemv | upstart | launchd | rcd]

How to make it work for openwrt?

**Comment by vmarchaud** [comment]
Just make a PR to add the support for the platform : https://github.com/Unitech/pm2/blob/master/lib/API/Startup.js

**Comment by vmarchaud** [comment]
Could you try to see if `openrc` template works with `openwrt` ? `pm2 startup openrc`

**Comment by HobaiRiku** [comment]
> Could you try to see if `openrc` template works with `openwrt` ? `pm2 startup openrc`
rc-update is not found in my  openwrt router
```bash
Target path
/etc/init.d/pm2
Command list
[ 'chmod +x /etc/init.d/pm2', 'rc-update add pm2 default' ]
[PM2] Writing init configuration in /etc/init.d/pm2
[PM2] Making script booting at startup...
[PM2] [-] Executing: chmod +x /etc/init.d/pm2...
[PM2] [v] Command successfully executed.
[PM2] [-] Executing: rc-update add pm2 default...
/bin/sh: rc-update: not found
[ERROR] Exit code : 127
[PM2][ERROR] rc-update add pm2 default failed, see error above.
```

but, in `/etc/rc.local`
```bash
export PM2_HOME=/root/.pm2 && pm2 resurrect
```
works.
