### ISSUE TITLE
Question:  Can PM2 send notifications or launch an arbitrary script when a process dies?

### ISSUE THREAD

**Issue by mrcybermac** [Unitech/pm2#2772]
Hi,  I've been googling around, looking through pm2 docs, and looking through github issues but can't seem to find an answer to this question:

Is there a way for pm2 to launch an arbitrary script when a process that it is monitoring crashes?  I understand that pm2 can automatically restart the process, but can it also launch a script?  

The purpose is for notifications.  When a process dies in production, what is the best practice way of sending alerts or notifications using pm2?

Thanks for any advice!

**Comment by vmarchaud** [comment]
Two solutions : 
- use https://keymetrics.io
- or make a [module](http://pm2.keymetrics.io/docs/advanced/pm2-module-system/) that listen event from the [bus](http://pm2.keymetrics.io/docs/usage/pm2-api/#programmatic-api) and then do whatever you want.

**Comment by psifertex** [comment]
Just to clarify, it appears the free tier of keymetrics does not support any notifications, so it requires a minimum of $360/yr to use keymetrics to add notifications.
