### ISSUE TITLE
ARM fsevents WARN

### ISSUE THREAD

**Issue by DQvsRA** [Unitech/pm2#2774]
Hi
I'm installed PM2 on My Orangi PI Zero but have an WARN

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/pm2/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

Could you please take a look on it?

**Comment by papakai** [comment]
I've reported a similar issue in grunt-nodemon here: https://github.com/ChrisWren/grunt-nodemon/issues/73

The chokidar module dependency triggers this warning.
So, @ pm2 team, if you open a git issue at chokidar, you may link in also the above issue. I haven't got any response set from the grunt-nodemon devs on that.

**Comment by vmarchaud** [comment]
They are plenty of issues already openned for this  (chokidar's dev already anwsered multiple times): https://github.com/paulmillr/chokidar/issues?utf8=%E2%9C%93&q=is%3Aissue%20warning
There are warning because you can ignore them.
