### ISSUE TITLE
Debugging from pm2-docker

### ISSUE THREAD

**Issue by danprince** [Unitech/pm2#2776]
Normally, I'd just run `node app.js --inspect` to use the chrome dev tools to debug my node apps, but on my current project, the node process is being run inside a container with `pm2-docker`.

Is there already a standard/accepted workflow for debugging/profiling a node process inside of a Docker container?

Alternatively, is there a good way to ask pm2 to conditionally pass `NODE_ARGS=--inspect` if an environment variable like `NODE_DEBUG=true`?

**Comment by vmarchaud** [comment]
Since PM2 start your process file inside the container, you can just add `nodeArgs: '--inspect'` in it, then you'll just need to allow networking on the debug port to be able to access it from the host.

**Comment by danprince** [comment]
Thanks @vmarchaud, does this mean that the only sensible option is to always run the process with `nodeargs: '--inspect'`?

Ideally, I'd be able to enable/disable that from outside the container.

**Comment by vmarchaud** [comment]
You should be able to use `SIGUSR1` signals (docs [here](https://nodejs.org/api/process.html#process_signal_events)) to start the debugger, pm2 can send it for you (check [here](https://github.com/Unitech/pm2/blob/master/bin/pm2#L416)) but you will need to run the command inside the container.
You can't really enable/disable outside of the container cause you would need to have an API exposed, and PM2 doesnt provide any.

**Comment by danprince** [comment]
Thanks, this is all helpful.

I already have an API for running commands inside the container from outside, but I think SIGUSR1 is going to put node into the traditional debugger (`node --debug`) rather than the debugging mode using Chrome devtools as a frontend (`node --inspect`)?

**Comment by vmarchaud** [comment]
I have no idea about the working of the debugging protocol sorry.

**Comment by danprince** [comment]
No worries, thanks for your time all the same!

**Comment by mmahalwy** [comment]
@danprince figured this out?

**Comment by danprince** [comment]
@mmahalwy Afraid not. Just taken to running outside of docker when I need step debugging.

**Comment by shyam-habarakada** [comment]
I'm running into this same issue. we are running with `process.yaml` and I have args specified like,

```yaml
      node_args:
        - "--expose-gc"
        - "--inspect:9929"
```

And y docker-compose configuration is exposing the port over to the host machine as `"9929:9929"`, but chrome dev tools does not appear to find it.

Any input would be much appreciated.

**Comment by shyam-habarakada** [comment]
@danprince @mmahalwy have you made any progress on this or have newer information?

I managed to get chrome dev-tools to detect and attach to a node app running inside a container, but not when the node app is run/managed via pm2-docker. Everything else is the same in the two tests except one is running `node --inspect start.js` vs the other running `pm2-docker` with a process.yml file. The correct node args are specified in `process.yml` and in both cases the port bindings are setup the same way between the host and containers.

**Comment by osmarpixuri** [comment]
Hey @shyam-habarakada, I've reached here through google. The problem you're (were) facing is because by default the node inspector accepts only local connections, so inside a container you need to use: `node_args: "--expose-gc --inspect:9929"`
Remeber to include EXPOSE 9229 and on docker compose use the port as "127.0.0.1:9229:9229" so that you only expose the port to your host and not to the outside world.
