### ISSUE TITLE
Webshell Error

### ISSUE THREAD

**Issue by DQvsRA** [Unitech/pm2#2779]
Im running PM2 on armbian and it's works fine except webshell module
Here is a log of error: 

Starting execution sequence in -fork mode- for app name:pm2-webshell id:2
PM2        | App name:pm2-webshell id:2 online
2|pm2-webs | TypeError: Cannot read property 'prototype' of undefined
2|pm2-webs |     at Object.<anonymous> (/root/.pm2/node_modules/socket.io/lib/store.js:35:41)
2|pm2-webs |     at Module._compile (module.js:571:32)
2|pm2-webs |     at Object.Module._extensions..js (module.js:580:10)
2|pm2-webs |     at Module.load (module.js:488:32)
2|pm2-webs |     at tryModuleLoad (module.js:447:12)
2|pm2-webs |     at Function.Module._load (module.js:439:3)
2|pm2-webs |     at Module.require (module.js:498:17)
2|pm2-webs |     at require (internal/module.js:20:19)
2|pm2-webs |     at Object.<anonymous> (/root/.pm2/node_modules/socket.io/lib/manager.js:16:13)
2|pm2-webs |     at Module._compile (module.js:571:32)
PM2        | App [pm2-webshell] with id [2] and pid [3696], exited with code [1] via signal [SIGINT]

**Comment by vmarchaud** [comment]
Please open an issue over https://github.com/pm2-hive/pm2-webshell
