### ISSUE TITLE
pm2 Multiple God Daemons Spawning

### ISSUE THREAD

**Issue by LewisTehMinerz** [Unitech/pm2#2784]
#### Expected behaviour

Only one God Daemon should spawn using `pm2 start`

#### Actual behaviour

More than one God Daemon spawns.

#### Steps to reproduce

Unsure if reproduce-able, but I'll give you what I did.
(Application name is Akane)

Simply running the command `pm2 start Akane` spawns multiple processes, and multiple instances of the application. This is running in `fork` mode. Also occurs with any `pm2` command.

#### Software versions used

```
OS         : Ubuntu 14.04 LTS
node.js    : v7.7.3
PM2        : 2.4.2
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`
```
2017-03-21 10:10:25: ===============================================================================
2017-03-21 10:10:25: --- New PM2 Daemon started ----------------------------------------------------
2017-03-21 10:10:25: Time                 : Tue Mar 21 2017 10:10:25 GMT-0400 (EDT)
2017-03-21 10:10:25: PM2 version          : 2.4.2
2017-03-21 10:10:25: Node.js version      : 7.7.3
2017-03-21 10:10:25: Current arch         : x64
2017-03-21 10:10:25: PM2 home             : /root/.pm2
2017-03-21 10:10:25: PM2 PID file         : /root/.pm2/pm2.pid
2017-03-21 10:10:25: RPC socket file      : /root/.pm2/rpc.sock
2017-03-21 10:10:25: BUS socket file      : /root/.pm2/pub.sock
2017-03-21 10:10:25: Application log path : /root/.pm2/logs
2017-03-21 10:10:25: Process dump file    : /root/.pm2/dump.pm2
2017-03-21 10:10:25: Concurrent actions   : 2
2017-03-21 10:10:25: SIGTERM timeout      : 1600
2017-03-21 10:10:25: ===============================================================================
2017-03-21 10:10:25: Starting execution sequence in -fork mode- for app name:Akane id:0
2017-03-21 10:10:25: App name:Akane id:0 online
```

I am unsure on why this is happening, as I should only see 1 God Daemon and 5 node.js processes (using the library cluster, so 1 master and 4 slaves)

**Comment by vmarchaud** [comment]
Need a way to reproduce and be sure to run all command with the same user (since the PM2 home directory is `~/.pm2` it depend on which user launch the command)

**Comment by LewisTehMinerz** [comment]
It is running on the same user, and that's all I have been running to get it to do that.

**Comment by vmarchaud** [comment]
Please paste the result of `ps aux | grep PM2`

**Comment by LewisTehMinerz** [comment]
```
root     11990  7.5  2.5 938292 26848 ?        Ssl  10:36   0:00 PM2 v2.4.2: God Daemon (/root/.pm2)
root     12268  0.0  0.0  11184   820 pts/1    R+   10:36   0:00 grep --color=auto PM2
```

In a program such as `top` or `htop`, this shows as 10 processes.

**Comment by vmarchaud** [comment]
htop/top depending on the platform show processes threads by default, see https://peteris.rocks/blog/htop/#process-tree
In this case, nodejs have 10 threads for the PM2 daemon, not 10 processes.

**Comment by sterina** [comment]
I am facing the same issue, below is output for ps aux | grep pm2
appuser    912  0.0  1.1 574952 43824 ?        Sl   08:40   0:00 node /opt/node/bin/pm2 start /opt/pm2-config/scheduler.json
appuser    944  0.0  1.0 574412 42904 ?        Sl   08:40   0:00 node /opt/node/bin/pm2 start /opt/pm2-config/push.json
appuser    948  0.0  1.1 575052 44068 ?        Sl   08:40   0:00 node /opt/node/bin/pm2 start /opt/pm2-config/api-ui.json
appuser    964  0.0  1.0 574924 43124 ?        Sl   08:40   0:00 node /opt/node/bin/pm2 start /opt/pm2-config/ui.json
appuser    973  0.0  1.0 574452 42896 ?        Sl   08:40   0:00 node /opt/node/bin/pm2 start /opt/pm2-config/meter.json
appuser   1017  0.0  1.0 575152 43320 ?        Sl   08:40   0:00 node /opt/node/bin/pm2 start /opt/pm2-config/dj.json
appuser   1902  0.0  1.0 573132 41424 ?        Ssl  08:41   0:00 PM2 v4.2.3: God Daemon (/naught-home/.pm2)
appuser   1903  0.0  1.0 573644 41076 ?        Ssl  08:41   0:00 PM2 v4.2.3: God Daemon (/naught-home/.pm2)
appuser   1904  0.0  1.0 573136 41504 ?        Ssl  08:41   0:00 PM2 v4.2.3: God Daemon (/naught-home/.pm2)
appuser   1905  0.0  1.0 573140 41772 ?        Ssl  08:41   0:00 PM2 v4.2.3: God Daemon (/naught-home/.pm2)
appuser   1906  0.3  1.2 618972 49264 ?        Ssl  08:41   0:18 PM2 v4.2.3: God Daemon (/naught-home/.pm2)
appuser   1911  0.0  1.0 573136 41192 ?        Ssl  08:41   0:00 PM2 v4.2.3: God Daemon (/naught-home/.pm2)
appuser   1926  0.0  1.0 573128 40984 ?        Ssl  08:41   0:00 PM2 v4.2.3: God Daemon (/naught-home/.pm2)
ubuntu    9058  0.0  0.0  13132  1056 pts/0    S+   10:12   0:00 grep --color=auto pm2

**Comment by sterina** [comment]
> It is running on the same user, and that's all I have been running to get it to do that. Also, it spawns 10 God Daemons.

@LewisTehMinerz  Were you able to fix the issue?Please share your progress

**Comment by sterina** [comment]
> Please paste the result of `ps aux | grep PM2`

@vmarchaud Could you please help me understand and resolve my issue? I have pasted above output of ps aux command
