### ISSUE TITLE
Passing arguments to app does not work

### ISSUE THREAD

**Issue by c0dr** [Unitech/pm2#2786]
#### Expected behaviour

Arguments should be passed to the started application.

#### Actual behaviour

Arguments are not passed.

#### Steps to reproduce

Start a script with arguments

e.g.
`pm2 start test.js -- -a 34`

With test.js for example containing

`console.log(process.argv)`

#### Software versions used

```
OS         : Windows 7
node.js    : 7.5.0
PM2        : 2.4.2
````

**Comment by vmarchaud** [comment]
![image](https://cloud.githubusercontent.com/assets/2820968/24210996/0bb73788-0f2b-11e7-886a-2c13a68721b5.png)
Working for me (Ubuntu 16.04, node 7.4 and pm2 2.4.2)

**Comment by c0dr** [comment]
Yeah, I can confirm that it works on OS X with 7.6 and pm2 2.4.2 as well.

I will investigate what might cause that.

**Comment by c0dr** [comment]
It works in cmd, so I guess it's a PowerShell-Bug. Closing
