### ISSUE TITLE
What is the clock (⏱) Emoji (in the process list) for?

### ISSUE THREAD

**Issue by gopeter** [Unitech/pm2#2787]
My process list shows a clock Emoji next to my `server-flights` app and I didn't found any documentation about this. 

I'm using `pmx` and I don't receive any `http` information in the Keymetrics dashboard for this app, so I wonder wether this is related. `server-import` works fine and I'm receiving `http` metrics for this app.

It would be great if someone could explain where the clock comes from 😄  I'm using PM 2.4.2.

![image](https://cloud.githubusercontent.com/assets/1242960/24208955/3b7ba8b0-0f25-11e7-9671-9eacb48a54de.png)

**Comment by vmarchaud** [comment]
Its a new feature that is in development, the pm2 part is working so you are able to enable but it doesnt do anything on keymetrics side.
I'm guessing that you enabled it with the `pmx.init` method, so you just need to remove `transactions: true` from it.

**Comment by gopeter** [comment]
Thank you very much! `http` metrics are working fine now :)
