### ISSUE TITLE
No-color option not working?

### ISSUE THREAD

**Issue by joeauty** [Unitech/pm2#2790]
If reporting a bug, please use the following template.

#### Expected behaviour

Expecting a command like:

`pm2 restart ecosystem.json --env dev --no-color`

to remove all color from logs

...

#### Actual behaviour

Seeing color in logs, which is causing problems in streaming to AWS Cloudwatch in seeing entries like this:

`[0mGET / [32m200 [0m4.319 ms - 55[0m`

This should instead read:

`GET / 200 4.319 ms - 55`

...

#### Steps to reproduce

Run above command, look at `pm2 logs`

...

#### Software versions used

```
OS         :  OS X, Linux
node.js    :  6.9.1
PM2        :  2.4.2
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

Nothing unusual

**Comment by vmarchaud** [comment]
ping @soyuka : I saw that you made some commits ([ref](https://github.com/Unitech/pm2/search?q=no-color&type=Commits&utf8=%E2%9C%93)) about this, but i dont see how they work, do you have any info for us ?

**Comment by soyuka** [comment]
@joeauty I'm not sure that this colored log comes from pm2. What are you using to output logs from you API?

Maybe you also need to pass `--no-color` to your script on top of the pm2 flag `--no-color`?

**Comment by joeauty** [comment]
Sorry for my slow response here. I was trying to use the awslogs service to stream the logs to Cloudwatch. Shouldn't pm2 have stripped the color out prior to streaming though, with this option set?

**Comment by soyuka** [comment]
This option is only disabling the PM2 logs colored outputs (internally we use `chalk`, and this flag disables the `chalk` color output). It won't stripped colors that may come from your app logger.

**Comment by joeauty** [comment]
I see, thanks! Sorry, I was a little confused here. Would it be possible for pm2 to search/replace the color characters so that this color disabling is absolute and framework/logger agnostic?

**Comment by soyuka** [comment]
@joeauty This would be hard to do and might alter application logs in an undesired way. I don't think it can be safely implemented as it's out of pm2 scope.

Though, your framework should give you the ability to turn off coloring output. May I ask what you're using?

**Comment by joeauty** [comment]
A combination of Restify and Loopback.
