### ISSUE TITLE
Execute node script using pm2

### ISSUE THREAD

**Issue by phoenixvk** [Unitech/pm2#2791]
I'm using command sudo pm2 start app.js which works fine :+1: 
But I'm using node script in pm2 which is sudo npm run dev. 
In which dev is declared in package.json. So how should command would be analogical to
**npm run dev** I tried **pm2 run dev**. It didn't worked please help.
Thank you.

**Comment by vmarchaud** [comment]
See documentation to switch environment right there : http://pm2.keymetrics.io/docs/usage/application-declaration/#environement-definition
