### ISSUE TITLE
Processes file doesn't accept Window absolute paths

### ISSUE THREAD

**Issue by willmcenaney** [Unitech/pm2#2796]
If reporting a bug, please use the following template.

#### Expected behaviour
\<drive letter\>:\location\script.config.js
Working

#### Actual behaviour
[PM2][ERROR] \<drive_letter\>:\location\script.config.js File not found.

**Comment by vmarchaud** [comment]
You need to put a drive identifier for nodejs to find your file, should be `C:\location\script.config.js` or something like that.

**Comment by willmcenaney** [comment]
I've found the issue in the code - its looking for '/' at position 0.  I'm doing a pull req for it now.

**Comment by vmarchaud** [comment]
@willmcenaney Will merge if tests are good

**Comment by willmcenaney** [comment]
Looks like there may be a bug in the tests.  The first pass fell over on     ✓ should trigger message with params by name, but after resubmission it passed.

**Comment by vmarchaud** [comment]
@willmcenaney I'll trigger re-build manually myself if tests fail :)

**Comment by willmcenaney** [comment]
All successful this time 👍

**Comment by willmcenaney** [comment]
@vmarchaud Apologies for trying to push, but I have a live environment waiting for this, is there a chance you could push it through for me?

**Comment by vmarchaud** [comment]
@willmcenaney We will not push it right now, maybe later today (with another release that we worked on)

**Comment by vmarchaud** [comment]
Published under pm2 `2.4.3` !
