### ISSUE TITLE
Basic load balancing not working

### ISSUE THREAD

**Issue by ryan65** [Unitech/pm2#2800]
Hi 
I might be doing something wrong but I wrote a basic server 
and I start is with pm2 start appTest.js -i 4 .
However when running multiple clients , they all seem to connect to the same process and there is no load balancing.
I tried both socket.io connections and http connections with browser. I print the process id and I seem to get the same process Id . 

Below is my server code and client code

SERVER 
```
 var app = require('http').createServer(handler);
var io = require('socket.io')(app);
var fs = require('fs');

var port = 6661;
app.listen(port);


console.log('Starting server: port %d , pid %d' ,port, process.pid);
function handler (req, res) {
   console.log('received http request');
   res.writeHead(200);
   res.end('Connected to: ' + process.pid);
}

var count = 0;
io.on('connection', function (socket) {
   socket.myId = count++;
   console.log('PID: %s . Connnection created:%s', process.pid, socket.myId);
   socket.emit('news', "You are connected to server: " + process.pid);
   socket.on('my other event', function (data) {
      console.log('recived:" data from socket ' + socket.myId);
   });
   socket.on('disconnect', function(){
      console.log('Disconnected socket ' + socket.myId);
   });
   socket.on('error', function(){
      console.log('Error socket ' + socket.myId);
   });
});
```
CLIENT 
```
var io = require('socket.io-client');
var socket = io.connect('http://localhost:6661');
socket.on('news', function (data) {
   console.log(data);
   socket.emit('my other event', {my: 'data'});
});
```

**Comment by vmarchaud** [comment]
Cluster mode isn't statefull so you can't use websocket with it, see https://github.com/Unitech/pm2/issues/389
Please read the [doc](https://nodejs.org/dist/latest-v6.x/docs/api/cluster.html#cluster_how_it_works) of the cluster implementation too, it will explain to you the different strategy that are implemented by nodejs.
