### ISSUE TITLE
exiting "pm2 logs" kills the processes.

### ISSUE THREAD

**Issue by shaheenmasood** [Unitech/pm2#2803]
## I'm opening this issue because:

  - [ ] pm2 isn't behaving like it should do.
  - [ ] pm2 is doing something I don't understand.
  - [x] pm2 is crashing.
  - [ ] Other (_see at the end for feature requests_):

## General Informations:

 `pm2 -v` prints: 
 ``` 
 ```

`node -v` prints: 
``` 
```

`uname -a` output for unix OR Windows version: 
```
 ```

`tail --lines 50 ~/.pm2/pm2.log` prints: 

``` 
```

**Comment by shaheenmasood** [comment]
I started my node.js application using pm2 start process.json (with cluster mode and 2 instances). Everything worked fine. Then I wanted to see the logs using "pm2 logs" and I could see the logs. But when I exited the log using ctrl-C, the processes got killed. What would be the correct way to exit out of "pm2 logs" and demonize the processes back?

**Comment by vmarchaud** [comment]
Could you please fill the general information (specially all the versions) ?
Anyway pm2 logs can't kill process, it only attach to the pm2 bus and print logs in realtime.

**Comment by shaheenmasood** [comment]
I misunderstood. On Windows cmd line, when I do ctrl-C, it asks if I want
to terminate the job, I said "Y" and then the processes got killed. I
reponded with "N" next time and the processes were fine.

Thanks for the clarification.

**Comment by calao** [comment]
I had the same issue on Windows 10 **## I resolved this by running the pm2 start as administrator**... Really strange behaviour...
