### ISSUE TITLE
pm2 jlist outputs more than json

### ISSUE THREAD

**Issue by aikomastboom** [Unitech/pm2#281]
When running pm2 for the first time:

vagrant@precise64:~$ rm -rf .pm2/
vagrant@precise64:~$ pm2 jlist -s
Initializing folder for pm2 on /home/vagrant/.pm2
Creating PM2 configuration file in /home/vagrant/.pm2/custom_options.sh
[]

It would be nice if the "Initializing .. options.sh" part would be suppressed as:
- the output is not json anymore and breaks a json parser
- -s is supposed to make it silent but doesn't make it silent enough.

vagrant@precise64:~$ rm -rf .pm2/
vagrant@precise64:~$ pm2 jlist -s | json_pp
malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "Initializing folder ...") at /usr/bin/json_pp line 44

**Comment by Unitech** [comment]
available in upcoming release
