### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by billwing** [Unitech/pm2#2813]
**What's going wrong?**

    pm2 deploy deploy.json sit

This make errors:

    Warning: Permanently added '[*.*.*.*]:9536' (ECDSA) to the list of known hosts.
    Permission denied (publickey).

But `git clone ` is worked.

## Supporting information

```
PM2 version: 2.4.2
Node version: v6.9.5
Linux
```

**Comment by vmarchaud** [comment]
You just cannot connect to your server, simple as that.
