### ISSUE TITLE
cron_restart starts job on server startup

### ISSUE THREAD

**Issue by TrejGun** [Unitech/pm2#2817]
**What's going wrong?**
cron job starts immediately after server starts up
```bash
pm2 start ecosystem.json
```
but it should not

**How could we reproduce this issue?**
ecosystem.json
```json
{
  "apps": [
    {
      "name": "CRON",
      "script": "test.js",
      "cron_restart": "0 11 * * *",
      "exec_mode": "cluster"
    }
  ]
}
```

test.js
```js
console.log(new Date());
```

## Supporting information

```
PM2 version: `pm2 -v` 2.4.4 / dev
Node version: `node -v` 6.10.0
Windows? Mac? Linux? Mac
```

**Comment by vmarchaud** [comment]
Currently the cron is launched the process so you need to start it to make the cron work, see https://github.com/Unitech/pm2/issues/2487

**Comment by TrejGun** [comment]
@vmarchaud how can I help to fix?

**Comment by vmarchaud** [comment]
You'll need to implement the whole cron mechanism inside https://github.com/Unitech/pm2/blob/master/lib/Worker.js
