### ISSUE TITLE
cron_restart not updated after restart

### ISSUE THREAD

**Issue by Almya** [Unitech/pm2#2820]
Hi there, I use cron_restart in my ecosystem config file.

When I change the cron_restart attribute in my config file, it's not updated with a restart or a reload.

I have to kill my apps then reload it.

```
PM2 version: `2.4.2`
Node version: `6.9.4`
Centos 7
```

**Comment by vmarchaud** [comment]
You want to use `--update-env` to tell PM2 to update configuration when restarting process (however if you use an ecosystem file to restart you shouldn't have to)

**Comment by Almya** [comment]
@vmarchaud thanks
