### ISSUE TITLE
Add ability to choose to start now an app with cron_restart option

### ISSUE THREAD

**Issue by Almya** [Unitech/pm2#2821]
Hi there, I'm using cron_restart in my ecosystem config file.

The issue is that when I start/restart an app which contains the cron_restart option, the app is started at the moment.

I think it should be great to add an option (for example "start_now") to determine if the app should be started now or only when the cron_restart option matches.

```
PM2 version: `2.4.2`
Node version: `6.9.4`
Centos 7
```

**Comment by vmarchaud** [comment]
Its because the cron is launched inside the process, see https://github.com/Unitech/pm2/issues/2487
