### ISSUE TITLE
log file is in incorrect location

### ISSUE THREAD

**Issue by psabharwal3** [Unitech/pm2#2823]
using the following config.js

```
module.exports = {
    apps: [{
        name: 'app',
        script: './server/src',
        instances: 0,
        exec_mode: 'cluster',
        max_memory_restart: '1G',
        error_file: 'app.log',
        out_file: 'app.log',
        updateEnv: true,
        merge_logs: true,
        log_date_format: 'YYYY-MM-DD HH:mm Z'
    }]
};
```

app.log is generated in same directory as repo; however the documentation says "Note that relatives logs paths will usually be written in the PM2_HOME (~/.pm2/logs)" on  http://pm2.keymetrics.io/docs/usage/log-management/

## Supporting information

```
PM2 version: 2.4.4
Node version: v6.10.2
Windows and Linux
```

**Comment by vmarchaud** [comment]
I don't know why the doc state this cause the behavior is that it resolve the path relative of the [cwd](https://github.com/Unitech/pm2/blob/master/lib/Common.js#L199), i'm editing the documentation.
Thanks for the report.
