### ISSUE TITLE
log to new file after restart of the app

### ISSUE THREAD

**Issue by hemirt** [Unitech/pm2#2826]
Is there a way to create a new logfile for each new restart of the app?
(I checked [logs management](http://pm2.keymetrics.io/docs/usage/log-management/) and [logrotate module](https://github.com/pm2-hive/pm2-logrotate) but they don't offer any of this.)

```
PM2 version: 2.1.5
Node version: v4.7.2
Linux (debian)
```

**Comment by vmarchaud** [comment]
PM2 doesn't offer this feature, the logs depend on the `process id` but it doesn't get incremented for each restart.
