### ISSUE TITLE
Docker-compose + pm2-dev = TypeError: Cannot create property 'watch' on string '.'

### ISSUE THREAD

**Issue by joeauty** [Unitech/pm2#2828]
**What's going wrong?**

pm2-dev inside Docker container not working

**How could we reproduce this issue?**

In my Docker-compose file I have the following override:

`command: pm2-dev run .`

(My Dockerfile's normal CMD is pm2-docker). When this command is executed I see the following:

```
/usr/local/lib/node_modules/pm2/lib/DevCli.js:58
opts.watch = true;

TypeError: Cannot create property 'watch' on string '.'
```

## Supporting information

```
PM2 version: `pm2 -v`
```
2.4.4

```
Node version: `node -v`
```

6.9.1

```
Windows? Mac? Linux?
```

Linux

**Comment by RichAyotte** [comment]
I'm seeing this error outside of Docker.

```sh
$ pm2-dev run app.js 
/usr/lib/node_modules/pm2/lib/DevCli.js:58
  opts.watch = true;
             ^

TypeError: Cannot create property 'watch' on string 'app.js'
    at run (/usr/lib/node_modules/pm2/lib/DevCli.js:58:14)
    at Command.<anonymous> (/usr/lib/node_modules/pm2/lib/DevCli.js:125:5)
    at Command.listener (/usr/lib/node_modules/pm2/node_modules/commander/index.js:301:8)
    at emitOne (events.js:96:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/usr/lib/node_modules/pm2/node_modules/commander/index.js:617:12)
    at Command.parse (/usr/lib/node_modules/pm2/node_modules/commander/index.js:458:21)
    at /usr/lib/node_modules/pm2/lib/DevCli.js:30:13
    at /usr/lib/node_modules/pm2/lib/API.js:153:14
    at /usr/lib/node_modules/pm2/lib/Client.js:54:16
```
`opts` is supposed to be an object but a string is passed instead. Looks like a good case for static typing.
```js
function run(cmd, opts) {
  var timestamp = opts.timestamp;

  opts.watch = true;
  opts.autorestart = true;
```

`$ pm2 -v` **2.4.5**
`$ node -v` **v7.9.0**

**Comment by RichAyotte** [comment]
Ahh, the change was made in https://github.com/Unitech/pm2/commit/439c6e93e2274f093239aaa2218b5c670ab02cc6

Just do `$ pm2-dev app.js ` now.

**Comment by joeauty** [comment]
Thank you! Just FYI the docs need to be updated here: http://pm2.keymetrics.io/docs/usage/pm2-development/

I should have checked pm2-dev -h though and noticed this, not terribly observant of me!

**Comment by joeauty** [comment]
Actually the help is wrong too?

` start [options] <file|json_file>  start target config file/script in development mode`

**Comment by vmarchaud** [comment]
because the start option still [exist](https://github.com/Unitech/pm2/blob/master/lib/DevCli.js#L128), sorry i didn't check myself before putting these tags on the issue (the `pm2-dev` isn't used to much so i forgot about it sometimes ^^).
I'll merge your PR for the doc tho, thanks for the feedback @joeauty and @RichAyotte
