### ISSUE TITLE
An alert should be displayed when passing --env env_name, and it doesn't exist

### ISSUE THREAD

**Issue by aseques** [Unitech/pm2#2829]
**What's going wrong?**
In some cases the user (me) could make wrong assumptions about the --env flag
**How could we reproduce this issue?**
I created a minimal bash to reproduce the issue

```
#!/bin/bash
echo "environment: $NODE_ENV"
sleep 50
```
- `export NODE_ENV=dev` ; `pm2 start test.sh  
Output is `environment: dev` (as expected)
- no NODE_ENV exported `pm2 start test.sh`
Output is `environment:`
- `export NODE_ENV=dev` ; `pm2 restart test.sh  --update-env`
Output is `environment: dev` (so it added the variables from env successfully)
- no NODE_ENV; pm2 start test.sh --env dev
Output is `environment: ` (i was expecting it to load NODE_ENV with the value dev, my bad, I've now read that it just points to environment in the process.json

After debugging the issue for some time I found that the cause was a shared environment variable on node-config and pm2 [same as here](https://github.com/lorenwest/node-config/issues/244), but some more noise when there were issues loading environments would have saved the time.

## Supporting information

```
PM2 version: 2.4.2
Node version: v6.9.5
Linux
```

**Comment by vmarchaud** [comment]
I don't get if there is an issue with PM2 or its coming from `node-config` ?

**Comment by aseques** [comment]
I was (wrongly) using the --env flag with an environment that wasn't defined anywhere, this just silently failed (no warnings), if there was an error when trying to load a non defined environment it would have saved me some debugging time, it might be the case too then there is a typo in the env_name (porduction i.e.).

**Comment by Unitech** [comment]
will land in next release
