### ISSUE TITLE
Mixed docker-compose, nodejs and native binary configurations

### ISSUE THREAD

**Issue by atrauzzi** [Unitech/pm2#2830]
I'm looking into the feasibility of using PM2 as a toplevel utility to manage a mixed multiple process setup.  I figured part of this would be well served by a discussion on how PM2 currently views itself when working with non-nodejs processes, as well as coexisting with a system like docker-compose.  I apologize if everything doesn't come out clearly in the first pass.  I'll happily clarify, edit or answer any questions where necessary.

---

I have a mixed scenario where I'm looking to ease the startup of my teams local development environment.  It's fairly mixed, but even without something like PM2, wouldn't be impossible to kick off using scripts if we had to.  Obviously that's not as nice as being able to plug it all into an interface like `pm2 dashboard`.

 - Docker containers running whatever the heck we can dream up
 - nodejs applications running natively
 - asp.net core applications running natively

There are a lot of strengths to be had from both PM2 and the docker ecosystems.  PM2 is very close to the application, however docker and compose have some really useful abstractions when it comes to networking, ports and filesystems.  What I'd like to do is get the best of all worlds, whenever it makes sense.

The first part might be less of a worry - I recall reading some small bits about how PM2 supports non-nodejs executables, so the native non-nodejs applications sound already possible today.

What I'm thinking/wondering about though is if there would be any merit in having PM2 support a toplevel docker compose file to invoke as part of an entire runtime profile.  PM2 currently offers the entrypoint for inside of containers, but maybe could it internalize a concept of a docker-compose file to boot alongside everything else (some running nodejs apps, some not) and give them as close to a first class treatment as possible?

You guys may already have thoughts on this, so perhaps I've missed a bunch of important thoughts.  Would love to hear more!

**Comment by vmarchaud** [comment]
Our strategy with PM2 and container is pretty much blurry cause we don't know where to put PM2 to make it useful.
 @Unitech developed `pm2-docker` in a idea that PM2 should be inside the container to be able to seamlessly start application with their `ecosystem.json` but inside a container to be able to push them into a container native infrastructure. But even with that, we don't know if its the best solution or not.

To be able to support at second class citizen docker-compose file, we should first support container as second class citizen but we don't cause handling an application life cycle isn't the same as handling a database life cycle. It will need a lot of work to do that.

For me its a costly strategy, the container ecosystem move really fast and for now we can't follow it cause we don't work the same way.
For example, docker is known to break compatibility every few months, we keep the compatibility for nodejs 0.12 and very old pm2 version (you can still upgrade from these versions without problem).

**Comment by atrauzzi** [comment]
Totally agree, which is why my thinking would be that instead of trying to anticipate what goes on inside of the docker ecosystem, just design around the external touchpoints - specifically docker-compose.

I guess what I'm suggesting is less about making PM2 aware of how compose (and by extension, docker) works, but instead making PM2 able to bootstrap a standard parallel configuration of docker-compose.  

The only difference to simply running docker compose at the same time might be that PM2 attempts to discover containers running PM2-managed nodejs applications.

**Comment by vmarchaud** [comment]
For me `making PM2 able to bootstrap a standard parallel configuration of docker-compose` is to make PM2 able to spawn containers from a docker-compose file, if not can you explain precisely a example command and what it should do ? Thanks

**Comment by atrauzzi** [comment]
@vmarchaud - Why not just rely on the docker tooling to be locally available?  This ensures that it remains abstracted.  This is only to run things.

In the case of PM2 actually getting insights and working with the running containers/processes within, at that point it might make sense to integrate with the docker APIs. On that, I don't think Docker is so unstable that the APIs couldn't be built around.

But again, maybe booting a `docker-compose.yml` and integrating with Docker can be approached in two separate passes.  Right now I'm running `docker-compose up` from PM2.  But that could be better because I have to tell it not to enforce any kind of restart policy.

**Comment by qiulang** [comment]
Another question I have is how to set the restart policy when using pm2 docker.

I always set my docker restart policy, e.g. always or on-failure. But pm2 can also restart node server, e.g. restart when node server crush.

So should I use docker restart policy or pm2 restart policy? If I use both, will it cause problems?

I asked the question at [SO](https://stackoverflow.com/questions/50663951/using-pm2-docker-with-restart-policy) but nobody seems to care about that :(
