### ISSUE TITLE
[PM2 Start app]: Help needed to start an app with following parameters - ERROR thrown

### ISSUE THREAD

**Issue by skumar1122** [Unitech/pm2#2832]
I am new to this PM2 tool and I really want this to use for my applications, Can you please help in providing information.
I wanted to start an application to start on Interface which needs database running on port and another to start UI.

here are my following calls to start app's-
 **$pm2 start rethinkdb --port 8082   (starts DB)
 $pm2 start stf local --public-ip 10.1.87.184**     (actual Interface)

**What's going wrong?**
>   error: unknown option `--http-port'

It doesn't like extra parameters to be mentioned when I start PM2, Is there any way to start above applications with PM2?

I can start normally with following in my local,
**$rethinkdb --port 8082   (starts DB)
 $stf local --public-ip 10.1.87.184**     (actual Interface)

**How could we reproduce this issue?**

## Supporting information

```
PM2 version: 2.4.0
Node version: v7.1.0
MAC - 10.12.4
```

**Comment by vmarchaud** [comment]
You need to use `--` to tell pm2 to stop parsing his options and give the rest to the program, then when you spawn direct binary, you need to tell pm2 that you don't want to use nodejs, so :
`pm2 start rethinkdb --interpreter none -- --port 8082`
`pm2 start stf local --interpreter none -- --public-ip 10.1.87.184`

**Comment by skumar1122** [comment]
Heya @vmarchaud,

Thanks for reply,
I have followed same and when I start both, other one getting status error , could you please check this,

```
1)
cwkwnprecp001-ilo:~ international$ pm2 start rethinkdb --interpreter none -- --port 8082
[PM2] Applying action restartProcessId on app [rethinkdb](ids: 0)
[PM2] [rethinkdb](0) ✓
[PM2] Process successfully started
┌───────────┬────┬──────┬───────┬─────────┬─────────┬────────┬─────┬───────────┬──────────┐
│ App name  │ id │ mode │ pid   │ status  │ restart │ uptime │ cpu │ mem       │ watching │
├───────────┼────┼──────┼───────┼─────────┼─────────┼────────┼─────┼───────────┼──────────┤
│ rethinkdb │ 0  │ fork │ 87791 │ online  │ 33      │ 0s     │ 2%  │ 10.9 MB   │ disabled │
│ stf       │ 1  │ fork │ 0     │ errored │ 15      │ 0      │ 0%  │ 0 B       │ disabled │
└───────────┴────┴──────┴───────┴─────────┴─────────┴────────┴─────┴───────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app


2)
cwkwnprecp001-ilo:~ international$ pm2 start stf local --interpreter none -- --public-ip 10.1.87.184
[PM2] Applying action restartProcessId on app [stf](ids: 1)
[PM2][ERROR] Process 1 not found
┌───────────┬────┬──────┬─────┬─────────┬─────────┬────────┬─────┬────────┬──────────┐
│ App name  │ id │ mode │ pid │ status  │ restart │ uptime │ cpu │ mem    │ watching │
├───────────┼────┼──────┼─────┼─────────┼─────────┼────────┼─────┼────────┼──────────┤
│ rethinkdb │ 0  │ fork │ 0   │ errored │ 48      │ 0      │ 0%  │ 0 B    │ disabled │
│ stf       │ 1  │ fork │ 0   │ errored │ 15      │ 0      │ 0%  │ 0 B    │ disabled │
└───────────┴────┴──────┴─────┴─────────┴─────────┴────────┴─────┴────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app


```
Thanks
SK

**Comment by vmarchaud** [comment]
Please check your logs, i can't debug your configuration, you need to read the documentation and play with the options.
