### ISSUE TITLE
how to close server on ctrl+c when in no-daemon

### ISSUE THREAD

**Issue by terencechow** [Unitech/pm2#2833]
**What's going wrong?**
I use this command to start my instances in development:
`pm2 start ecosystem.json --only development --no-daemon`

But when i'm done development I want to kill it with `ctrl+c`. Indeed pushing that stops the logs but I was surprised to find that the server is still up. Is their a flag that allows me to kill the server when I ctrl + c at the logs?

Alternatively, is it possible to pass `--only` to `pm2-dev`?
## Supporting information

```
PM2 version: `pm2 -v`
Node version: `node -v`
Windows? Mac? Linux?
```
pm2 2.4, Mac, Node 6.5

**Comment by vmarchaud** [comment]
If there is a daemon already started, the PM2 CLI will connect to it even with `--no-daemon`, but if there isn't you should have a : `2017-04-13 10:28:13: Launching in no daemon mode` and a `ctrl+c` should kill all processes.

**Comment by terencechow** [comment]
hmm.. 

I open my process with `./node_modules/pm2/bin/pm2 start ecosystem.json --only development --no-daemon` 

And in my logs I see:
```
[--no-daemon] Continue to stream logs
[--no-daemon] Exit on target PM2 exit pid=45750
```

And yet ctrl+c does not close the running process, it merely closes the logs. Not important though, low priority

**Comment by nodkrot** [comment]
Should we use `pm2-dev`??? CLI API is not consistent there (--ignore-watch, --only) doesn't work...  `pm2 start app --no-daemon` doesn't.

Another question: how can I set up my ecosystem.json so that I can watch (+ other custom configs) only in development env???
```
{
    "apps": [{
        "name": "app",
        "script": "./app.js",
        "watch": true,
        "ignore_watch": ["./src", "./public"],
        "env": {
            "NODE_ENV": "production"
        },
        "env_development": {
            "NODE_ENV": "development"
        }
    }, ...
```

**Comment by vmarchaud** [comment]
Use `pm2 kill && pm2 start ecosystem.json --only development --no-daemon`

**Comment by nodkrot** [comment]
Thanks you, `pm2-dev` is confusing...

**Comment by nodkrot** [comment]
@vmarchaud in case `pm2 kill && pm2 start ecosystem.json --only development --no-daemon` when I add `--no-autorestart` the parameter doesn't take effect, do you know why?
