### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by AkashBabu** [Unitech/pm2#2834]
**It would be great if i could check all the logs except for one script. Just say like if there are 10 running scripts, but i would like to see all the logs except for 8th one**

## Supporting information
Checking the logs based on pid patterns or something similar is expected. Thank you
```
PM2 version: `pm2 -v`
Node version: `node -v`
Windows? Mac? Linux?
```

**Comment by vmarchaud** [comment]
You can precise a application name or process id when doing a `pm2 logs`, see : 
```
▶ pm2 logs --help

  Usage: logs [options] [id|name]

```

**Comment by AkashBabu** [comment]
Hi vmarchaud, i know this usage, but what im asking for is not inclusion, it exclusion.
What i mean is when using `pm2 logs all`, is there a way to exclude some of the [ids] from being shown in logs
