### ISSUE TITLE
scheduled task as cron running a program haiving process.exit() causes status to be stopped/errored

### ISSUE THREAD

**Issue by pantchox** [Unitech/pm2#2835]
**What's going wrong?**
Using application declartion trying to have a "cron" job kind of task running every "X" minutes, if the app that need to run have "process.exit()" command the status column on "pm2 list" returns "stopped" and sometimes "errored".

**How could we reproduce this issue?**
using a .config.js file and simple js script file with these:
```js
module.exports = {
  /**
   * Application configuration section
   * http://pm2.keymetrics.io/docs/usage/application-declaration/
   */
  apps : [
    // First application
    {
      name      : "cron_simpleConsole",
      script    : "/home/pm2schedule_test.js",
      args: "myargs",
      cron_restart: "*/1 * * * *",
      autorestart: false,
    }
  ]
}
```
The simple js file
```js
var env = process.env.NODE_ENV || 'development';
var arg = process.argv[2];
console.log('I was executed! - ',env,'-',arg,'-', Date().toLocaleString());
process.exit();
```
Note: **this is just example code of using process.exit(), it is not the code i use but it has the same result i am trying to fix/understand**

running this config with pm2 will cause it to run once and be stopped/errored and never run again.
I know some will say "process.exit()" should not be called but sometimes i have no choice or else it big code refactoring which is not what i am after.

Is this how it is suppose to be? thanks!
## Supporting information

```
PM2 version: `2.4.2` 
Node version: `6.9.2`
Linux distro
```

**Comment by vmarchaud** [comment]
Because the process need to be running for the cron to work (since the cron is implemented inside the javscript process, not in the daemon), see https://github.com/Unitech/pm2/issues/2487.
