### ISSUE TITLE
Cannot install pm2, certificate expired

### ISSUE THREAD

**Issue by jlippold** [Unitech/pm2#2836]
**What's going wrong?**

Your cert is expired

**How could we reproduce this issue?**

go to https://tgz.pm2.io/gkt-1.0.0.tgz

Even tried on the http registry, same deal

![http://s3.amazonaws.com/PicUp/2qUCXW.png](http://s3.amazonaws.com/PicUp/2qUCXW.png)

**Comment by jlippold** [comment]
if you're desperate like me

```
npm config set strict-ssl false
```

**Comment by Unitech** [comment]
https://github.com/Unitech/pm2/commit/e18d976788255ff985d29c62c8614005e17c3103
pm2@2.4.5 with this change published

**Comment by Unitech** [comment]
Do this to force installation of latest pm2:

```bash
$ npm install pm2@latest -g
```

**Comment by robertjamesmiller** [comment]
we're using shrinkwrap, how do we fix in our npm-shrinkwrap.json ?

**Comment by vmarchaud** [comment]
Working on a automatic renewal on our side.

**Comment by vmarchaud** [comment]
Should be good sorry for the disagrement

**Comment by loque** [comment]
This is happening again!

**Comment by steven-xie** [comment]
Yeah, it's back.

**Comment by ibnclaudius** [comment]
Save for me.

**Comment by philipvonbargen** [comment]
Same thing again as before, certificate expired just now.

**Comment by wwallace** [comment]
@Unitech looks like this is happening again
