### ISSUE TITLE
Process not running after manual server reset from gcloud console

### ISSUE THREAD

**Issue by danielduckworth** [Unitech/pm2#2838]
**What's going wrong?**

Process not running after manual server reset from gcloud console.

The process initially runs fine with pm2 start app.js

I then ran 'pm2 startup' with sudo.

App runs fine until I manually restart the server from the gcloud console.

## Supporting information

```
PM2 version: `pm2 -v`

2.5.4

Node version: `node -v`

6.10.2

Windows? Mac? Linux?

Debian VM on Google Cloud.

**Comment by vmarchaud** [comment]
Could you share the systemd service file that PM2 generated ? (should be in `/etc/systemd/system/pm2-<user>.service`)
