### ISSUE TITLE
re build and restart all apps?

### ISSUE THREAD

**Issue by Swapnilchavan18** [Unitech/pm2#2839]
This is question. I have list of app running with pm2, if I want to update all apps with similar change, then how can I rebuild apps and restart them in one script or command? Thank you.

**Comment by soyuka** [comment]
`pm2 restart all`?

**Comment by Swapnilchavan18** [comment]
I also need to rebuild all application(or list of applications), something like I can specify applications names to rebuild and restart.

**Comment by tariky** [comment]
@Swapnilchavan18
 You can do it this way
`pm2 start app.json`

In app.json you create JSON object like this
`{
  "apps" : [{
    "script"    : "api.js",
    "instances" : 0,
    "exec_mode" : "cluster"
  }]
}`

**Comment by vmarchaud** [comment]
PM2 only handle the process management so it doesn't provide hook to rebuild your apps when they are restarted, i suggest you make a command that run both `npm run build` and `pm2 restart appName`.

**Comment by Swapnilchavan18** [comment]
ok Thank you, yes I understand, this is just a question in case pm2 want to expand to provide this automization feature.

**Comment by vmarchaud** [comment]
No problem, i think its better for us to focus on the process management part for now, build tools generally handle post-build hooks (so they can run a `pm2 restart`) so its an overlapping feature for me.
