### ISSUE TITLE
About the use of API

### ISSUE THREAD

**Issue by 510033939** [Unitech/pm2#2841]
1. When I get a process after pm2.start(), how do I listen to it stdout / stderr

2. How to send a message to Python process

`pm2.connect(function(err) {
    if (err) {
        console.error(err);
        process.exit(2);
    }
    pm2.start({
        name: 'hcccc',
        script    : 'app.py',         // Script to be run
        maxRestarts: 1
    }, function(err, apps) {
        
        // i want to listen stdout/stderr, According to the situation to do different things
        // what should i do ???
        if (err) console.log('err',err);
    });
});`

**Comment by vmarchaud** [comment]
1. You need to listen to the bus (example with a module [here](https://github.com/pm2-hive/pm2-syslog/blob/master/app.js#L21))
2. You cannot send message to python process since it need to implement IPC communication.
