### ISSUE TITLE
Question: does pm2 support running scripts without extension?

### ISSUE THREAD

**Issue by sergeyjsg** [Unitech/pm2#2842]
I'm trying to run following configuration from ecosystem.json:

```
{
      "name": "data_worker",
      "script": "workers.data_worker",
      "interpreter": "python",
      "interpreter_args": "-m",
}
```
but it always says `[PM2][ERROR] script not found : /workers.data_worker`
It looks like "script" must contain extension. Is it true? How to fix this?

**Comment by vmarchaud** [comment]
Try defining `cwd`, i think the problem here is the path of the script.

**Comment by sergeyjsg** [comment]
Didn't help... tried all ".", "./", "./workers", "./workers/".

**Comment by vmarchaud** [comment]
set `cwd` option with the absolute path : 
```
{
      "name": "data_worker",
      "script": "workers.data_worker",
      "cwd": "/var/www/myscript/",
      "interpreter": "python",
      "interpreter_args": "-m",
}
```
