### ISSUE TITLE
exec_interpreter "none" resets back to "node"

### ISSUE THREAD

**Issue by BabakMN** [Unitech/pm2#2847]
It seems that a false `isBinary` check sets `exec_interpreter` from `none` back to `node` again. Which then causes `Syntax Error` because a binary file ends up getting executed by node. The binary in this case is `google-chrome`. 

[Ref](https://github.com/Unitech/pm2/blob/b30651b0d80fd8c0b27925ec7efb0887226b8d8f/lib/Common.js#L365)

pm2 2.4.5, node v7.8.0, linux

**Comment by vmarchaud** [comment]
Published under PM2 `2.5`
