### ISSUE TITLE
Issue using startup command on a jailbreak command line

### ISSUE THREAD

**Issue by reubenkcoutinho** [Unitech/pm2#2852]
Can't run pm2 start on a _jailshell_ terminal. Not sure how this could be reproduced as the issue is on live server.

## Supporting information

```
PM2 version: 2.4.5
Node version: 6.10.2
OS: Linux (all i got when I typed uname. I also managed to figure out that it is a x86_64 architecture)
```
**[UPDATE]**
[1/05/2017]
- managed to find out the OS.
- renamed jailbreak to jailshell. 

> Jail shell is a way to restrict command access on terminal (from what I understand). This means I cannot run sudo commands

**Comment by vmarchaud** [comment]
What is a `jailbreak` command line ? What is happening ? Any errors ?

**Comment by reubenkcoutinho** [comment]
Hi @vmarchaud , I've updated the details.

**Comment by vmarchaud** [comment]
`pm2 startup` need sudo access to register the service on the init-system (systemd/systemd/upstart or whatever) so its normal behavior.
