### ISSUE TITLE
Doesn't work properly with tj/commander.js sub-commands

### ISSUE THREAD

**Issue by arzyu** [Unitech/pm2#2853]
**What's going wrong?**

I'm using [tj/commander.js](https://github.com/tj/commander.js) to create a tool chain of my service, see project structure below:
```
pm2-test
|- bin
|   |- service
|   |- service-start
|- package.json
```
```js
// ./bin/service
#!/usr/bin/env node
const program = require('commander');

program
  .command('start', 'start a service')
  .parse(process.argv);

console.log(process.argv);
```

Normally, I can start the service by running command `./bin/service start`, everything is fine.

`console.log(process.argv);` output:
```
[ '/Users/xxx/.nvm/versions/node/v7.8.0/bin/node',
  '/Users/xxx/pm2-test/bin/service',
  'start' ]
```

However, when I try to run `pm2 start ./bin/service -- start`, there will be a problem.

`console.log(process.argv);` output:
```
[ '/Users/xxx/.nvm/versions/node/v7.8.0/bin/node',
  '/Users/xxx/.nvm/versions/node/v7.8.0/lib/node_modules/pm2/lib/ProcessContainerFork.js',
  'start' ]
```

This will cause `commander` to fail to find `./bin/service-start` by parsing `process.argv`. And throw an error: `ProcessContainerFork-start does not exist`

Here is the demo: [pm2-test.zip](https://github.com/Unitech/pm2/files/958359/pm2-test.zip)

## Supporting information

```
PM2 version: 2.4.5
Node version: 7.8.0
macOS Serria 10.12.4
```

**Comment by vmarchaud** [comment]
From what you showed PM2 try to send the argument to the process but not to the actual script : I advise use the ecosystem file to correctly define which args you want to send (see the [doc](http://pm2.keymetrics.io/docs/usage/application-declaration/#general) but you want to use `args` entry).
