### ISSUE TITLE
How to start app in strict mode?

### ISSUE THREAD

**Issue by bgSosh** [Unitech/pm2#2857]
I'd like do `pm2 start app.js` with strict mode enabled, i.e. the equivalent of `node --use-strict app.js`.   How can I do this?

I've seen this line in the docs, but I believe this is for application params, not node options?

`$ pm2 start app.js -- -a 34     # Start app and pass option "-a 34" as argument`

Thank you

**Comment by vmarchaud** [comment]
Its in the documentation : http://pm2.keymetrics.io/docs/usage/pm2-doc-single-page/#considerations
![image](https://cloud.githubusercontent.com/assets/2820968/25481562/083c2516-2b4e-11e7-852e-cf4c6e9ef00b.png)
