### ISSUE TITLE
How to set NODE_ENV without using ecosystem/deploy commands?

### ISSUE THREAD

**Issue by gushogg-blake** [Unitech/pm2#2858]
The environment variable NODE_ENV doesn't seem to affect pm2 processes.  I've read up on how to inject environment variables with the ecosystem config, but is there a way of doing it without an ecosystem config -- ie. just pm2 `start` commands on the command line?

**Comment by gushogg-blake** [comment]
A quick fix is to simply set `process.env.NODE_ENV` from within the app, but I'd still be interested to know if it's possible to do this without a hack.

**Comment by vmarchaud** [comment]
As i answered on slack : 
You can just run `NODE_ENV=test pm2 start app.js`  or `NODE_ENV=development pm2 restart app --update-env` if the application is already started and you want to change it
