### ISSUE TITLE
Reinstalling PM2 starting an earlier project

### ISSUE THREAD

**Issue by saurabh95** [Unitech/pm2#2862]
**What's going wrong?**
I ran a node application using pm2 and then I uninstalled pm2, deleted all pm2 files and then I reinstalled it globally, then it automatically starts the earlier project, and it doesn't come up in `pm2 list`

## Supporting information

```
PM2 version: `pm2 -v` 2.4.6
Node version: `node -v` 0.10.25
Windows? Mac? Linux? Linux
```

**Comment by vmarchaud** [comment]
Because the file that stored processes state is inside pm2 files so logically if you delete them, they can't be respawned. If you want to update PM2 : `npm install -g pm2 && pm2 update`  will do the trick.
