### ISSUE TITLE
Can't Start Node File With -p Flag

### ISSUE THREAD

**Issue by JimTheMan** [Unitech/pm2#2864]
Hi,

I have a NodeJS script that I normally run like this:

`sudo node start game-of-ninja-server.js -p`

or 

`sudo forever start game-of-ninja-server.js -p`

However, when I try to use pm2

`sudo pm2 start game-of-ninja-server.js -p`

it gives me this error:

" error: option `-p --pid <pid>' argument missing"

and same error when I try to use --args flag:

`sudo pm2 start game-of-ninja-server.js --args="-p"`

**Comment by Unitech** [comment]
```
sudo pm2 start game-of-ninja-server.js -- -p
```

**Comment by JimTheMan** [comment]
bazinga!!

Thanks @Unitech. It works, but why? What is this phantom flag that is just two dashes? :)

 Is that documented?

**Comment by vmarchaud** [comment]
Its common for CLI command that spawn another process to pass arguments to that process after `--`, and of course its [documented ](http://pm2.keymetrics.io/docs/usage/quick-start/#42-starts): 
`$ pm2 start app.js -- -a 23  # Pass arguments '-a 23' argument to app.js script`
