### ISSUE TITLE
Watch & Restart seems not working (not fired) under root

### ISSUE THREAD

**Issue by sdubrez** [Unitech/pm2#2865]
Hi there!

**What's going wrong?** 
I've got an NodeJs/Express app. I can start it without problem. 
I've setup the _watch_ feature to be `true`. But still, when I'm editing my files and saving them, there is no restart from pm2.

Here is my `.json` app config file.

```
{
  "apps" : [
    {
      "name"            : "myExpressAppServer",
      "script"          : "./server.js",
      "watch"           : true,
      "ignore_watch"    : ["*.json", "*.log", "node_modules", "logs", "pids"],
      "instances"       : 0,
      "exec_mode"       : "cluster",
      "merge_logs"      : true,
      "error_file"      : "../logs/myExpressAppServer_err.log",
      "out_file"        : "../logs/myExpressAppServer_out.log",
      "pid_file"        : "../pids/myExpressAppServer.pid",
      "vizion"          : false,
      "cwd"             : "/home/hellow/lab/myExpressApp/server",
      "env"             : {
                                "APP_NODE_ENV"         : "development",
                                "APP_LISTEN_PORT"      : 3001,
                                "APP_LISTEN_IP"        : "127.0.0.1"
                          },
      "env_production"  : {
                                "APP_NODE_ENV"         : "production",
                                "APP_LISTEN_PORT"      : 3000,
                                "APP_LISTEN_IP"        : "127.0.0.1"
                          }
    }
}
```

## Supporting information

```
PM2 version: `2.4.6`
Node version: `7.10.0`
Linux/Debian: `Jessie (8)`

**Comment by sdubrez** [comment]
Ok I resolved my issue. 
I was executing `pm2 start ...` as root. When I executed `pm2 start ...` with the owner user of my project directory, the _Watch & Reload_ features worked fine.

But I don't really understand why. Do you have some explanations ?

**Comment by vmarchaud** [comment]
Actually i have no idea, check for pm2 logs in `/root/.pm2/pm2.log` for errors but if there isn't i guess it will stay answered ^^

**Comment by sdubrez** [comment]
I did not find something particular to my issue in logs so.. ^^

**Comment by sdubrez** [comment]
I tried to deploy an app using root instead of a particular user and the _Watch & Reload feature_ was working.

I guess, _Watch & Release feature_ doesn't work if you start the application with a different user than the owner user of your app directory.

**Comment by benimadimorman** [comment]
> Hi there!
> 
> **What's going wrong?** I've got an NodeJs/Express app. I can start it without problem. I've setup the _watch_ feature to be `true`. But still, when I'm editing my files and saving them, there is no restart from pm2.
> 
> Here is my `.json` app config file.
> 
> ```
> {
>   "apps" : [
>     {
>       "name"            : "myExpressAppServer",
>       "script"          : "./server.js",
>       "watch"           : true,
>       "ignore_watch"    : ["*.json", "*.log", "node_modules", "logs", "pids"],
>       "instances"       : 0,
>       "exec_mode"       : "cluster",
>       "merge_logs"      : true,
>       "error_file"      : "../logs/myExpressAppServer_err.log",
>       "out_file"        : "../logs/myExpressAppServer_out.log",
>       "pid_file"        : "../pids/myExpressAppServer.pid",
>       "vizion"          : false,
>       "cwd"             : "/home/hellow/lab/myExpressApp/server",
>       "env"             : {
>                                 "APP_NODE_ENV"         : "development",
>                                 "APP_LISTEN_PORT"      : 3001,
>                                 "APP_LISTEN_IP"        : "127.0.0.1"
>                           },
>       "env_production"  : {
>                                 "APP_NODE_ENV"         : "production",
>                                 "APP_LISTEN_PORT"      : 3000,
>                                 "APP_LISTEN_IP"        : "127.0.0.1"
>                           }
>     }
> }
> ```
> 
> ## Supporting information
> ```
> PM2 version: `2.4.6`
> Node version: `7.10.0`
> Linux/Debian: `Jessie (8)`
> ```

This shoud be open issue.

**Comment by naaraayananr** [comment]
> Actually i have no idea, check for pm2 logs in `/root/.pm2/pm2.log` for errors but if there isn't i guess it will stay answered ^^

there seems to have been some haste in closing the issue which is still persistent five years later too. could someone open this issue again for investigation please?
