### ISSUE TITLE
pm2 logs --raw doesn't display previous logs

### ISSUE THREAD

**Issue by serge1peshcoff** [Unitech/pm2#2868]
I'm trying to display my app logs with PM2, and they're in JSON, so I need raw logs. 
When using the `pm2 logs <app-name> --raw`, there are only logs that were emitter after the command start, the previous logs aren't displayed (though if I run it without the `--raw` flag, the previous logs are displayed).
The `--lines <n>` or `--lines=<n>` options seem to not work.

I've seen this issue: https://github.com/Unitech/PM2/issues/1277, however it was stated that it has been fixed and I'm still facing it.

Can you help me with it?

```
PM2 version: `2.4.6`
Node version: `7.10.0`, installed with `n`
Xubuntu Studio 17.04 x64
```

**Comment by vmarchaud** [comment]
Published under PM2 `2.5`
