### ISSUE TITLE
Add a possibility to run one-time scripts by crontab

### ISSUE THREAD

**Issue by serge1peshcoff** [Unitech/pm2#2869]
Let's say I have the application that has some scripts (that are not constantly running, they just do their job and quit) that are needed to be run at certain periods of time. (My case: I have the server application and a script (simple `.js` file) that makes a dump of the database, zips it into a file and moves it into a separate folder. And this script needs to run every `n` hours.)

It would be awesome to have the possibility to start these scripts with PM2 and have a config setup where you can specify when these scripts should be started.

There is `cron_restart` option, but it's not quite what I want.

**Comment by vmarchaud** [comment]
Duplicate https://github.com/Unitech/pm2/issues/2487
