### ISSUE TITLE
Why is min-uptime not available at the CLI

### ISSUE THREAD

**Issue by jdthorpe** [Unitech/pm2#2877]
I noticed that the [max-restarts is available on the CLI](https://github.com/Unitech/pm2/blob/1c3fcb83b65e430a5734d576610d27cc7a0bf4fd/bin/pm2#L39), but not [min-uptime](http://pm2.keymetrics.io/docs/usage/pm2-doc-single-page/#list-of-attributes-available), without which max-restarts is irrelevant for a process that takes a few seconds to start up.

```
PM2 version: 2.4.6
Node version: v6.9.2
Windows
```

**Comment by vmarchaud** [comment]
I advise you to use a [process file](http://pm2.keymetrics.io/docs/usage/application-declaration/) for advanced use of options, we don't want to allow all options for the CLI because it will make it too complex.
The CLI options are only intended if you want to setup basic options.

**Comment by jpgklassen** [comment]
Shouldn't we let the user decide how complicated they're willing to make their commands? It seems silly to allow MOST options on the command line but not a select few.
