### ISSUE TITLE
pm2 logs with regular expression for app names

### ISSUE THREAD

**Issue by tnguyen14** [Unitech/pm2#2888]
It would be great to have `pm2 logs` be able to handle a regex, such as `pm2 logs /foo-.*/`, similar to the `restart`, `stop` and `delete` commands raised in #2564

**Comment by vmarchaud** [comment]
For anyone wanting to make a PR, it should be pretty straightforward : getting [this logic](https://github.com/Unitech/pm2/blob/master/lib/API.js#L1310) into [this function](https://github.com/Unitech/pm2/blob/master/lib/API/LogManagement.js#L140) and [this one](https://github.com/Unitech/pm2/blob/master/lib/API/LogManagement.js#L227)

**Comment by sidthesloth92** [comment]
Have added the code to for pm2 logs to accept regex for names

**Comment by vmarchaud** [comment]
Published under PM2 `2.5`
