### ISSUE TITLE
how to set different env values for each clusters?

### ISSUE THREAD

**Issue by hbakhtiyor** [Unitech/pm2#2889]
e.g.

// Cluster 1
console.log(process.env.NODE_CLUSTER_ENV) // => "one"

// Cluster 2
console.log(process.env.NODE_CLUSTER_ENV) // => "two"

....

**Comment by vmarchaud** [comment]
[A PR](https://github.com/Unitech/pm2/pull/2801) is on the way to add this feature, however you already have a env variable called `NODE_INSTANCE_ID` that is injected and different in every worker in the cluster mode.
