### ISSUE TITLE
Ubuntu Startup Script - Not Working

### ISSUE THREAD

**Issue by ishanrakitha** [Unitech/pm2#289]
I'm using ubuntu server 12.10. i have genarated the start up script and executed the given command, but i have to manually execute "pm2 restart all" to get my process online. I can see my process in pm2 after system start up. it show as online. but it's not.

**Comment by audioathlete** [comment]
how would start an app with pm2 after vagrant-mount on centos 7 (uses systemd)?

**Comment by eexit** [comment]
Hello,

I'm having the same issue:
 - NodeJS v0.10.33
 - NPM 1.3.6
 - Centos 7

```
chkconfig --list | grep $(runlevel | awk '{ print $2}'):on

Note: This output shows SysV services only and does not include native
      systemd services. SysV configuration data might be overridden by native
      systemd configuration.

      If you want to list systemd services use 'systemctl list-unit-files'.
      To see services enabled on particular target use
      'systemctl list-dependencies [target]'.

iprdump        	0:off	1:off	2:on	3:on	4:on	5:on	6:off
iprinit        	0:off	1:off	2:on	3:on	4:on	5:on	6:off
iprupdate      	0:off	1:off	2:on	3:on	4:on	5:on	6:off
network        	0:off	1:off	2:on	3:on	4:on	5:on	6:off
pm2-init.sh    	0:off	1:off	2:on	3:on	4:on	5:on	6:off
```

The `pm2 dump; pm2 kill; pm2 resurrect` commands work wells... I don't get it.
Any idea?

Thanks!

**Comment by agusputra** [comment]
On Ubuntu, I followed @soyuka advice. Edit `/etc/init.d/pm2-init.sh` , and change `PM2_HOME="/root/.pm2"` to `HOME="/root"`
