### ISSUE TITLE
App in fork mode works but the status stucks at 'launching'

### ISSUE THREAD

**Issue by fott1** [Unitech/pm2#2893]
I've got a multi apps ecosystem.json with `1 app in cluster mode and 19 instances` and `1 in fork mode and 1 instance`. While both my apps are running without any issue, the app with 1 instance status remains stuck at launching. 

I tried 

- `pm2 stop and restart `for the specific apps with the status 'launching'
- `pkill -9 PM2; pkill -9 node;` and the start again the ecosystem
- update pm2 to the latest version

Any ideas? Weird thing is that the app is actually a chat, and works as expected. It is just the status that remains stuck.

**Comment by vmarchaud** [comment]
How do you start your application ? Can you fill the issue template (OS/PM2/Node versions) ?

**Comment by fott1** [comment]
Node version is v6.9.1
PM2 version is 2.1.5

I start the apps using `pm2 start ecosystem.config.json`, which includes both of my apps.

**Comment by vmarchaud** [comment]
Can you share the content of `ecosystem.config.json` ?

**Comment by fott1** [comment]
```javascript
{
        "apps": [{
                "name": "app1Name",
                "script": "./index.js",
                "instances": 15,
                "exec_mode": "cluster",
                "watch": false,
                "merge_logs": true,
                "wait_ready": true,
                "kill_timeout": 360000,
                "listen_timeout": 360000,
                "node_args": ["--max_old_space_size=500","--expose-gc"],
                "max_memory_restart": "2G",
                "env": {
                        "NODE_ENV": "development",
                },
                "env_production" : {
                        "NODE_ENV": "production"
                }
        },
        {
        "name": "app2Name",
        "script": "./app2index.js",
        "instances": 1,
        "exec_mode": "fork",
        "watch": false,
        "merge_logs": true,
        "wait_ready": true,
        "kill_timeout": 45000,
        "listen_timeout": 45000,
        "env": {
                "NODE_ENV": "development",
        },
        "env_production" : {
                "NODE_ENV": "production"
        }
    }]
}
```

**Comment by vmarchaud** [comment]
You use `"wait_ready": true` but you don't send the `process.send('ready)` event. You need to emit it to let PM2 know that your application is ready to handle request : http://pm2.keymetrics.io/docs/usage/signals-clean-restart/#graceful-start
