### ISSUE TITLE
Pm2 - Running from webstorm in dev environment ?

### ISSUE THREAD

**Issue by appsolutegeek** [Unitech/pm2#2897]
Hi,

I was going to ask weather PM2 would be overkill in a development environment but then I found pm2-dev

I presume this works similar to nodemon ?

I was wondering if its fairly easy to add to the run configuration in webstorm ?

anybody doing anything like that ?

Or would it be beneficial only to use PM2 in production and in dev use something like nodemon ?

Any ideas ?

Thanks

**Comment by vmarchaud** [comment]
PM2 is first designed for production use, you can use it for development but its not perfect, its up to you to choose it or not for you development flow.
Simple doc on `pm2-dev` : http://pm2.keymetrics.io/docs/usage/pm2-development/
