### ISSUE TITLE
Unable to configure process without starting it.

### ISSUE THREAD

**Issue by tonicsoft** [Unitech/pm2#2899]
The following SO question documents a very similar issue: https://stackoverflow.com/questions/32249538/pm2-loading-processes-json-without-automatically-starting-apps

When writing automated deployment scripts, it would be useful to separate the installation of the app from starting it. Ideally, the following would be possible (for an app named "app_name")

Install script (executed once on deployment):
```
sudo npm install pm2@2.4.6 -g
pm2 install app.js -n app_name
pm2 save
```

Start script (executed once on deployment, and potentially many times thereafter):
`pm2 start app_name`

Instead, one has to do it like this:

Install script (executed once on deployment):
`sudo npm install pm2@2.4.6 -g`

Start script (executed once on deployment, and potentially many times thereafter):
```
pm2 start app.js -n app_name
pm2 save
```

Obviously the second way works, it just doesn't seem 'clean'. Why save pm2 every time we call the start script?

```
PM2 version: 2.4.6
Node version: 6.9.5
Linux
```

**Comment by vmarchaud** [comment]
Duplicate https://github.com/Unitech/pm2/issues/2504
