### ISSUE TITLE
Update GRACEFUL_TIMEOUT isn't possible

### ISSUE THREAD

**Issue by bt404** [Unitech/pm2#2900]
I have deployed my app with pm2 in production environment, so I want to dynamically restart my app with new config of listen_timeout. I have tried:

1. execute `PM2_GRACEFUL_TIMEOUT=1000 pm2 restart config.js --update-env`;
2. put `listen_time: 1000` in config.js and then `pm2 restart config.js`;
3. put `env_production: {'PM2_GRACEFUL_TIMEOUT': 1000}` in config.js and then `pm2 restart --env production`;
4. execute `pm2 restart config.js --listen-time=1000`.

All the methods above failed. How can I realize the goal. Thanks!

```
PM2 version: 2.4.2
Node version: 6.10.3
Linux & Mac
```

**Comment by vmarchaud** [comment]
Can you tell me what are you trying to accomplish ? Because you try to modify two different configuration : `GRACEFUL_TIMEOUT` and `listen-time`, that's two different values.

**Comment by bt404** [comment]
I want to realize a graceful reload. But I find that pm2 won't send `SIGINT` signal until `GRACEFUL_TIMEOUT` ms(in `lib/God/Reload.js`), which is 8 seconds by default that I want to decrease.

Then I find the `GRACEFUL_TIMEOUT` constant assigned in `constant.js` with `process.env.PM2_GRACEFUL_TIMEOUT || 8000`. So I want to find a way to modify that environment variable.

Thanks!

**Comment by yellowblood** [comment]
Was this solved somehow? I'm facing the same issue. I actually want to increase this GRACEFUL_TIMEOUT but nothing seems to work. Stays on 8000. 

Also I'm not sure why isn't it the same as "kill_timeout".

**Comment by yellowblood** [comment]
I "solved" this by setting the global environment variable PM2_GRACEFUL_TIMEOUT in Windows. This overidded the 8 seconds default. I still can't understand why the "kill_timeout" configuration option doesn't override this timer. It drove me insane.
