### ISSUE TITLE
About using API to start and delete processes

### ISSUE THREAD

**Issue by 510033939** [Unitech/pm2#2901]
1.  I  just want this processe to run once ,  The configuration is right ?
       pm2.start({
                       name: pub_key,
                       script: history_main_path,
                       maxRestarts: 1,
                       args: [JSON.stringify(jsonObj)]
                   }, async function (err, app) {}

2. Sometimes I can't delete this process in PM2， And it will always restart, even though i set maxRestarts=1. Here's my code:
      pm2.start({
                       name: pub_key,
                       script: history_main_path,
                       maxRestarts: 1,
                       args: [JSON.stringify(jsonObj)]
                   }, function (err, app) {
                       pm2.launchBus(function (err, bus) {
                                bus.on('process:event', async function (data) {
                                    if(data.process.name == pub_key && data.process.pm_id == app[0].pm2_env.pm_id && data.event == 'exit'){
                                        pm2.delete(app[0].pm2_env.pm_id, function (err, data) {
                                            if (err) {
                                                console.log('delete err', err);
                                            } else {
                                                console.log('event dis', data);
                                                pm2.disconnect();
                                            }
                                        });
                                    }
                                });
                            })
                     }

**Comment by vmarchaud** [comment]
Can you re-open an issue with the template so it contain clear step to reproduce and the version you are using ?
