### ISSUE TITLE
[help wanted] pm2 running but now accessing via public domain address

### ISSUE THREAD

**Issue by AneesKhanzada** [Unitech/pm2#2903]
i am running this command but not working for me 
pm2 startOrRestart /var/www/rocket.chat/current/pm2.json

pm2 running 4 process of rocket.chat but cant be accessible via domain address on ubuntu

**Comment by vmarchaud** [comment]
Could you re-open an issue with the template filled ? A sample to reproduce the issue and the versions of PM2/NodeJs/OS you are using.
