### ISSUE TITLE
"TypeError: Cannot read property 'pm2_env' of undefined" while trying to use API

### ISSUE THREAD

**Issue by finom** [Unitech/pm2#2908]
**What's going wrong?**

I'm trying to use pm2 as a daemonizer for node scripts. See [1](https://github.com/Unitech/pm2/issues/2880), [2](https://github.com/Unitech/pm2/issues/2905). After some research I decided to use as less API functions as I can.  In [the project I do](https://github.com/finom/mongo-git-backup) I use `pm2.start` very similar way of how it's described in the documentation.

```js
pm2.start({
                script: `${__dirname}/daemon.js`,
                name: 'mongo-git-backup',
                error_file: `${__dirname}/err.log`,
                out_file: `${__dirname}/out.log`
            }, (err) => { // eslint-disable-line no-shadow
                pm2.disconnect();

                if (err) {
                    console.log(chalk.red(err));
                    reject(err);
                } else {
                    console.log(chalk.green('Done!'));
                    resolve();
                }
            });
```
It works great locally but I get error when I try to reuse this tool at remote server. I get:

```
/usr/lib/node_modules/mongo-git-backup/node_modules/pm2/lib/API.js:1031
        Common.printOut(conf.PREFIX_MSG + 'App [%s] launched (%d instances)', data[0].pm2_env.name, data.length);
                                                                                     ^

TypeError: Cannot read property 'pm2_env' of undefined
    at /usr/lib/node_modules/mongo-git-backup/node_modules/pm2/lib/API.js:1031:86
    at /usr/lib/node_modules/mongo-git-backup/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/usr/lib/node_modules/mongo-git-backup/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:191:7)
    at Parser._write (/usr/lib/node_modules/mongo-git-backup/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at Parser.Writable.write (_stream_writable.js:241:11)
    at Socket.ondata (_stream_readable.js:557:20)

```

**How could we reproduce this issue?**
Have no idea how to localize the issue. [The tool can be installed and run](https://github.com/finom/mongo-git-backup)  as described at the documentation.

```
mongo-git-backup export --db=DB --repo=REPO --daemonize
```

## Supporting information

```
PM2 version: `2.4.6`
Node version: `7.10`
Ubuntu 16
```

**Comment by finom** [comment]
The error happens there but I have no idea what does it mean https://github.com/Unitech/pm2/blob/master/lib/API.js#L1031

**Comment by vmarchaud** [comment]
Duplicate https://github.com/Unitech/pm2/issues/2870

**Comment by finom** [comment]
Finally, I decided to kill pm2 API in the project and use pm2 CLI via child_process.

**Comment by vmarchaud** [comment]
@finom You can also use the pm2 development version with `npm install -g Unitech/pm2#development` until we publish it to master.

**Comment by finom** [comment]
@vmarchaud I already switched to CLI. My thought is CLI is well-tested by many people but API is not and there may be other bugs at other platforms.

**Comment by vmarchaud** [comment]
@finom the API came much later than the CLI, all of our tests are based on the CLI so you are right.
