### ISSUE TITLE
"pm2 start" run using child_process doesn't create an instance

### ISSUE THREAD

**Issue by finom** [Unitech/pm2#2909]
**What's going wrong?**
When I run `pm2 start script.js` fat the terminal everything works fine but when I do the same using child_process it doesn't work. It returns  success messages (`[PM2] Starting ... in fork_mode (1 instance) [PM2] Done.`), list of other processes but they doesn't include the process I wanted to create.

I tried to pass `uid: process.getuid()` as an option to `execSync` (`exec`) but it didn't help.

**How could we reproduce this issue?**

```js
const { execSync } = require('child_process');

console.log(execSync('pm2 start script.js').toString('utf-8'));
```

## Supporting information

```
PM2 version: 2.4.6
Node version: 7.10
Ubuntu 16
```

**Comment by vmarchaud** [comment]
Care that PM2 will connect (or spawn if don't exist) to the Daemon exposed under `~/.pm2/rpc.sock`, so it must have spawned another daemon under a different user.
Checkout if there is other daemons by running `ps aux | grep PM2`.
If not, could you share the content of the `~/.pm2/pm2.log` inside a pastebin ? And then try with this snippet and share the ouput too : 
```
const { execSync } = require('child_process');

console.log(execSync('DEUG=* pm2 start script.js').toString('utf-8'));
```

**Comment by finom** [comment]
@vmarchaud I have looked at `~/.pm2/pm2.log` and it shows me that there was an error: pm2 had no permissions to write log to given `--log`. Thank you.

**Comment by finom** [comment]
@vmarchaud I'm not sure but I think this might be a bug. pm2 should fail instead showing success when it can't write to log files.

**Comment by vmarchaud** [comment]
@finom The response is just the acknowledgement that the process has been launched by the daemon, not the state of it. So it's not a bug, maybe not a perfect design but that's how it works for now :)
