### ISSUE TITLE
Cannot clone git repository

### ISSUE THREAD

**Issue by finom** [Unitech/pm2#2913]
**What's going wrong?**
My script runs `git clone <repository>` via child_process. It goes fine when I'm connected to my server by ssh and I run pm2 start. But once I log out the script throws an error:

 ```
Error: Command failed: 
        git clone -b master git@github.com:circlecell/dnslookup-backup.git /home/deployer/.mongo-git-backup/tmp
    
Cloning into '/home/deployer/.mongo-git-backup/tmp'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I guess this is something about SSH and daemons on Linux.
Also I run
```
eval `ssh-agent -s` &&
ssh-add ~/.ssh/id_rsa
```
before clone but it doesn't help.

**How could we reproduce this issue?**

Start pm2 script at a remote server, log out, wait a minute, log in and look at log files.
```
setInterval(() => {
  require('child_proces').execSync('git clone git@github.com:Unitech/pm2.git')
}, 5000)

```

## Supporting information

```
PM2 version: 2.4.6
Node version: 7.10.0
Ubuntu 16
```

**Comment by finom** [comment]
@vmarchaud do you have any thoughts? Thank you.

**Comment by vmarchaud** [comment]
Definitely not a problem from PM2 itself, from your logs : `ERROR: Repository not found.`
That's a response from github, not PM2, it must be coming from a network problem

**Comment by finom** [comment]
@vmarchaud  this is not Github response, this is Git error caused by some very specific things which happen when pm2 is run and a user who run it isn't logged out.

**Comment by vmarchaud** [comment]
This error message is printed by Git because it failed to access to the remote repository.
PM2 isn't linked to this behavior, you must have a problem with either the network or the ssh agent that authenticate you with github. 
Anyway i can't help you on this, it's your system and i don't know it sorry

**Comment by finom** [comment]
@vmarchaud got it. Thank you.
