### ISSUE TITLE
PM2 2.3 on Debian - Restart or Start does't work

### ISSUE THREAD

**Issue by Kaiserbald0** [Unitech/pm2#2915]
**What's going wrong?**
When I try to restart a process with `pm2 <id>` or `pm2 <name>`
I alway get this error:
`[PM2][ERROR] Process <ID> not found `
On the pm2 logs I have:
`PM2        | [RestartProcessId] PM2 is being killed, stopping restart procedure...`

And the process are working on and visible on if I type `pm2 list`.

If I delete a process, then I go to the folder and run:
`pm2 start ecosystem.json`
the process is starting but it is unable to restart if after using restart

This is happening both if I am logged into the server and using the CLI or if I am deploying using pm2 deploy

The only way to restart an app is to delete (`pm2 delete <name>` and restart it from the folder `pm2 startOrRestart ecosystem.json --env=staging`)

**How could we reproduce this issue?**

## Supporting information

```
PM2 version: `pm2 -v`: 2.3.0
Node version: `node -v`: v6.9.4
Windows? Mac? Linux?: Debian
```

Thanks

**Comment by vmarchaud** [comment]
Could you try to update to a newer version ? If still happening can you provide an example that reproduce the problem 100% of the time ?
