### ISSUE TITLE
purpose of gkt dependency

### ISSUE THREAD

**Issue by hhellbusch** [Unitech/pm2#2917]
What is the point of the GKT dependency?  

Looking at the code.. it does nothing.

![image](https://cloud.githubusercontent.com/assets/2072460/26701157/01c80b4e-46ee-11e7-85a3-25b87a153986.png)

 If there is no point to this package, I think it should be removed from the dependency list.

---

Noticed due to troubles during install due to SSL inspection / resigning. Able to work around by upgrading to latest NPM.  Looks like others have had issues due to this as well.  (e.g. 

w/ NPM v4.x
```
npm ERR! fetch failed https://tgz.pm2.io/gkt-1.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: unable to get local issuer certificate
npm ERR! fetch failed https://tgz.pm2.io/gkt-1.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: unable to get local issuer certificate
```

w/ NPM v5.0.1
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: gkt@https://tgz.pm2.io/gkt-1.0.0.tgz (node_modules/pm2/node_modules/gkt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: request to https://tgz.pm2.io/gkt-1.0.0.tgz failed, reason: unable to get local issuer certificate
```

**Comment by vmarchaud** [comment]
We already answered on few issues actually but anyway : it's a `optional` dependency that is used for analytics purpose for us.
I wasn't able to reproduce your problem (with both npm 4 & 5) but i restart the application that handle this request, is it fixed for you ?

**Comment by hhellbusch** [comment]
Issue on my end due to ssl inspection from the firewall. Issue would be
difficult to reproduce elsewhere.

**Comment by vmarchaud** [comment]
Sadly i can't help you otherwise, you can just use `npm install -g pm2 --no-optional` but it may still break on older npm version due to the fact that the flag isn't working properly.

**Comment by dgcoffman** [comment]
It's broken again.

**Comment by 599316527** [comment]
```
[2019-11-06 09:04:22] npm http fetch GET 403 https://tgz.pm2.io/gkt-1.0.0.tgz 122ms
```

It totally sucks! Please remove it.

**Comment by Unitech** [comment]
Go install the latest pm2 version
