### ISSUE TITLE
Windows: Interpreter path with spaces

### ISSUE THREAD

**Issue by dschnare** [Unitech/pm2#2918]
**What's going wrong?**
Using a custom interpreter in a process file with a spaces in the file name causes an error:

```
Blah is not recognized as an internal or external command
```

**How could we reproduce this issue?**

```
mkdir win
cd win
npm init --yes
npm install typescript ts-node pm2@2.4.6 -S
echo "console.log(`Who you gonna call?`)" > index.js
npm start
```

Where the `start` npm-script needs to be the following:
```
{
  "scripts": {
    "start": "pm2 start app.js"
  }
}
```

Here's `app.js` that defines the process:
```
const os = require('os')
const path = require('path')

// ERROR: On Windows, if there is spaces in the path to the interpreter then it
// won't load!

const platform = os.platform()
const interpreter = platform === 'win32'
  ? path.resolve('./node_modules/.bin/ts-node.cmd')
  : path.resolve('./node_modules/.bin/ts-node')

module.exports = {
  'name': 'ghoastbusters',
  'script': './index.js',
  'interpreter': interpreter,
  'watch': false
}
```

## Supporting information

```
PM2 version: `2.4.6`
Node version: `v6.10.2`
Windows 10
```

**Comment by dschnare** [comment]
I've tried to run `ts-node` with the same absolute path I give to pm2 by passing it to `child_process.spawn` and it works just fine.

I've also tried escaping the spaces in the app process file and that didn't work either.

See: https://superuser.com/questions/279008/how-do-i-escape-spaces-in-command-line-in-windows-without-using-quotation-marks#279121

**Comment by vmarchaud** [comment]
Can you try renaming your `app.js` to `ecosystem.config.js`, it should fail otherwise
