### ISSUE TITLE
API pm2.stop(processId, callback) the callback won't be called 

### ISSUE THREAD

**Issue by shivahn** [Unitech/pm2#2919]
**What's going wrong?**

when try to stop the process programmatic using the API pm2.stop with processId and callback passed as parameters, thought the request goes to API and client files of PM2 and it doesn't turn up will either success or error, if we constantly send the request multiple times it works and its intermediary, some times return with error callback already called or stopwatch error this.client.call cannot be called.

## Supporting information
server\node_modules\pm2\node_modules\async\lib\async.js:43
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at server\node_modules\pm2\node_modules\async\lib\async.js:43:36
    at ReqSocket.<anonymous> (server\node_modules\pm2\lib\Client.js:362:14)
    at ReqSocket.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at ReqSocket.emit (events.js:166:7)
    at Socket.<anonymous> (server\node_modules\pm2-axon\lib\sockets\sock.js:274:35)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
PM2 version: `pm2 -v` 2.4.2
Node version: `node -v` 4.1.1
Windows? Mac? Linux? Windows 7
```

**Comment by vmarchaud** [comment]
Could you provide a simple way to reproduce the problem ?

**Comment by shivahn** [comment]
On press on stop button implementing the following code to stop the process ID status to stopped.

pm2.connect(function() {
				pm2.stop(processId,function(err,details){
					if(err){ 
                                                     console.log('Error'+ err);
					}else {
						     console.log('Success');	
				        }
				});
});

what happens is that -after a single click on stop button and wait for long time the callback  with either details or error won't be returned.  when on mutiple clicks on stop button though status get changed to stopped , it will throw the exception "Error: Callback was already called."

**Comment by vmarchaud** [comment]
Can you check for error when doing `pm2.connect` ? It's possible that it fails.

**Comment by Unitech** [comment]
@shivahn I've tried to reproduce the bug (cf test link above) without success, please add some test in that file to reproduce the bug and i will fix it

**Comment by shivahn** [comment]
Hi Team,

Am running PM2 to evaluate , it works better than iisnode. it observed that
with PM2 getting a global error it kills all the applications running. Is
there  way around to come out of this.please advise.

pm2 v 2.6..1


Thanks,
Shivakumar
