### ISSUE TITLE
Process signaling to PM2 to request restart of all application instances

### ISSUE THREAD

**Issue by damianb** [Unitech/pm2#2927]
Hi - been doing some digging all over and haven't found anything in the pm2 documentation about whether or not this is supported.

I'm basically looking for a way that one of the application instances, once started, can indicate or signal to pm2 that the entire application needs restarted (let's say, for a big config reload or some such).  While I'm sure it'd be possible to do this with shell calls or the equivalent, I'm hoping to avoid that for obvious reasons.

**Comment by vmarchaud** [comment]
You can use the PM2 API : http://pm2.keymetrics.io/docs/usage/pm2-api/
```
const pm2 = require('pm2')

pm2.connect((err) => {
  pm2.restart('all', (err) {
    console.log('Process has been restarted');
  })
})
```

**Comment by damianb** [comment]
Ahhh, hadn't bumped into that.  Had been thinking along the lines of having to use signals.  Thanks!
