### ISSUE TITLE
Request with some additonal characters in PM2 Logs

### ISSUE THREAD

**Issue by bipin000** [Unitech/pm2#2928]
Hi,

My PM2 Logs shows many of the api request having additional characters  **^[[0m** in request what that mean  
06-06 16:23:14.474: ^[[0mGET /api/v0.0.1/test ^[[32m200 ^[[0m256.136 ms - 63^[[0m
while the many other request
06-06 16:23:15.131: GET /api/v0.0.1/test
whats the difference ?

## Supporting information

```
PM2 version: `2.4.5`
Node version: `4.8.2`
ubuntu 
```

**Comment by soyuka** [comment]
Those are ascii colors probably coming from your logger.

**Comment by vmarchaud** [comment]
Indeed there are termcaps that allow your terminal to color the text, they aren't rendered inside `pm2 logs`.
