### ISSUE TITLE
$HOME/.pm2/pids/app-pm_id.pid NOT match with pm2 list

### ISSUE THREAD

**Issue by sophister** [Unitech/pm2#2929]
**app process id from `pm2 list` NOT match  `$HOME/.pm2/pids/app-pm_id.pid`**

I get one application instance info from `pm2 list` as this:

```
│ NODE-PC-v1              │ 71 │ cluster │ 4265  │ online │ 3059    │ 25m    │ 62.914 MB    │ disabled │
```

but in the `/home/tomcat/.pm2/pids` directory, `cat NODE-PC-v1-71.pid` is  **8915**, NOT the same as **4265** from `pm2 list`

## Supporting information

PM2 version: `1.1.3`
Node version: `v5.3.0`
OS: `CentOS`

**Comment by vmarchaud** [comment]
Could you try with the latest PM2 version ?

**Comment by sophister** [comment]
@vmarchaud  OK, but we CAN NOT reproduce this problem. I'll try latest PM2, thx!
