### ISSUE TITLE
Disable timestamps on log streaming

### ISSUE THREAD

**Issue by rafaelkaufmann** [Unitech/pm2#293]
`pm2 logs` shows timestamps on every log entry, while the output is redirected raw to the log files. Therefore, I've set up Winston to prepend timestamps on the log entries so I can search the logs by timestamp. Therefore, inevitably, `pm2 logs` is showing double timestamps (one produced by PM2, the other produced by Winston). This would be easily fixed by giving `pm2 logs` a switch to turn off timestamps while streaming. Or even better, having them be off by default. :)

**Comment by eiser82** [comment]
@Unitech Is there a way to disable timestamps from the .json config file? I tried no including the `log_date_format` setting, but it keeps showing it. Thanks

**Comment by rodmaz** [comment]
The funny thing is that on a Mac it disables the timestamp logging. On Ubuntu it continues to display it.

**Comment by wyqydsyq** [comment]
Unsure if this was actually ever resolved or what as this ticket was closed without explanation on Aug 23, 2014, but currently PM2 shows timestamps in the logs, even if I specify `log_date_format: ''` (which should format all the timestamps to nothing).

Similar to OP, I am trying to use PM2 in conjunction with Winston.

![image](https://cloud.githubusercontent.com/assets/621277/22770392/d0fe9d6c-eedb-11e6-8118-cd97a6d94179.png)

**Comment by tpalfr** [comment]
same problem here. Is there a way to disable timestamp in logging ?

**Comment by wyqydsyq** [comment]
@Unitech please respond

**Comment by kenjinsama** [comment]
+1

**Comment by krvajal** [comment]
I found a simple solution to this:  don't use pm2, and move to [phusion passenger](https://www.phusionpassenger.com/)
