### ISSUE TITLE
can't delete app with name start at `--`

### ISSUE THREAD

**Issue by nonedeactivated** [Unitech/pm2#2936]
**pm2 says `error: unknown option` when deleting app with name that start at `--`**

## Supporting information

```
PM2 version: `2.4.6`
Node version: `4.6.2`
OS: Mac
```

**Comment by vmarchaud** [comment]
It's the way command line parsing works and we can't fix it, you should never use `--` inside a app name. Your only way out here is to `pm2 kill`
