### ISSUE TITLE
Can I deploy or scale up my node app with pm2 API?

### ISSUE THREAD

**Issue by oscchun** [Unitech/pm2#2940]
OK, I see the document about pm2 api, but i cannot find any string about deploy or scale my cluster mode app up. 
anybody can help me?

**Comment by vmarchaud** [comment]
Every CLI method is exposed on the `pm2` API, [pm2 scale is here](https://github.com/Unitech/pm2/blob/master/lib/API.js#L1517).

**Comment by oscchun** [comment]
@vmarchaud 
Oh, i'm so sorry..but
if there is a whole api document, please let me know where it is.

**Comment by soyuka** [comment]
http://pm2.keymetrics.io/docs/usage/pm2-api/#programmatic-api :)

**Comment by oscchun** [comment]
@soyuka 
I know there's api doc, but all functionalities are not in there.

**Comment by vmarchaud** [comment]
@oscchun indeed, if you want you can add it, the repository is [here](https://github.com/pm2-hive/pm2-hive.github.io) :)

**Comment by oscchun** [comment]
@soyuka @vmarchaud 
Ok. thank you for support. :)
