### ISSUE TITLE
PM2 scoped to app

### ISSUE THREAD

**Issue by damianobarbati** [Unitech/pm2#2944]
Is the following pattern harmful in a production environment?
Is this safe to use with multiple projects / pm2 instances?

In package.json:
```
    "scripts": {
        "pm2": "./node_modules/pm2/bin/pm2",
```
On terminal:
`yarn pm2 pm2.config.js`

I think it would be great to have pm2 scoped to package.

**Comment by damianobarbati** [comment]
Any news about this? :)

The only problem with scoped pm2 I'm thinking about is the following (in a CI environment):
1. current version is running on server, pm2 scoped-to/watching /project-dir
2. new version is pushed
3. CI tests then builds the new version
4. CI removes the /project-dir
5. CI rsync the new build to /project-dir

What's going to happen here?
. stopping pm2 before #4 would result in downtime / broken app
. removing the project-dir at #4 results in broken app as well? (node_modules with pm2 are wiped out and replace at #5!)

**Comment by Unitech** [comment]
By default and if you use a local pm2 for each application, they will end up to be managed by the same daemon.

What you could do, if you really want to have a separated pm2 instance for each application, is to play with the `PM2_HOME` environment variable (by default ~/.pm2). The `PM2_HOME` is the folder containing the unix socket file (allowing to communicate with the Daemon). So different PM2_HOME = independent pm2 instances.

Remind that when you daemonize a new instance of pm2 with a modified PM2_HOME, every time you call the pm2 CLI again, you will need to specify the PM2_HOME else it will query the default PM2 instance

**Comment by damianobarbati** [comment]
@Unitech thanks for the info, I didn't know about PM2_HOME! Playing with that right now.
