### ISSUE TITLE
Real-time monitoring non-functional on Ubuntu 

### ISSUE THREAD

**Issue by Oricul** [Unitech/pm2#2948]
**What's going wrong?**
Real-time monitoring is non-functional on Ubuntu 16.10 x64 (potentially restricted to Python3)
**How could we reproduce this issue?**
On Ubuntu 16.10 x64, install python3, install PM2 (steps below), add python script (I've done this through python3  or bash), start the service in pm2 and view logs.

Steps to install PM2:
- curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
- shutdown -r -t 00
- source ~/.bashrc
- nvm install stable
- npm install pm2@latest -g
## Supporting information

```
PM2 version: `pm2 -v` 2.5.0
Node version: `node -v` v8.1.2
Ubuntu 16.10 x64
```
I've gone through this process on two different servers with different python3 scripts, both on the same Ubuntu and python3 versions. Additionally, the logs are updating, but only after a restart or stop and start - just not in real-time. Real-time monitoring is non-functional (for me, at least) in `pm2 logs all` or `pm2 monit`. I've also tried looking through the issues, open and closed, but couldn't find anything similar - sorry.

**Comment by vmarchaud** [comment]
So whats the logs ? ^^

**Comment by Oricul** [comment]
After a `pm2 flush` and `pm2 restart all`:
```
root@vultr:~# pm2 logs
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        | 2017-06-18 11:24:31: Stopping app:proca id:0
PM2        | 2017-06-18 11:24:31: Stopping app:testing1 id:1
PM2        | 2017-06-18 11:24:31: pid=10710 msg=failed to kill - retrying in 100ms
PM2        | 2017-06-18 11:24:31: pid=10715 msg=failed to kill - retrying in 100ms
PM2        | 2017-06-18 11:24:32: App [proca] with id [0] and pid [10710], exited with code [0] via signal [SIGINT]
PM2        | 2017-06-18 11:24:32: pid=10710 msg=process killed
PM2        | 2017-06-18 11:24:32: Starting execution sequence in -fork mode- for app name:proca id:0
PM2        | 2017-06-18 11:24:32: pid=10715 msg=failed to kill - retrying in 100ms
PM2        | 2017-06-18 11:24:32: App name:proca id:0 online
PM2        | 2017-06-18 11:24:32: pid=10715 msg=failed to kill - retrying in 100ms
PM2        | 2017-06-18 11:24:32: pid=10715 msg=failed to kill - retrying in 100ms
PM2        | 2017-06-18 11:24:32: App [testing1] with id [1] and pid [10715], exited with code [0] via signal [SIGINT]
PM2        | 2017-06-18 11:24:32: pid=10715 msg=process killed
PM2        | 2017-06-18 11:24:32: Starting execution sequence in -fork mode- for app name:testing1 id:1
PM2        | 2017-06-18 11:24:32: App name:testing1 id:1 online

/root/.pm2/logs/proca-error-0.log last 15 lines:
/root/.pm2/logs/testing1-error-1.log last 15 lines:
/root/.pm2/logs/proca-out-0.log last 15 lines:
/root/.pm2/logs/testing1-out-1.log last 15 lines:
[STREAMING] Now streaming realtime logs for [all] processes
```

**Comment by vmarchaud** [comment]
Can't help you without any errors and i don't see abnormal log inside it also, it must be coming from your setup. Please provide a way to reproduce your problem

**Comment by Oricul** [comment]
Determined it was due to a buffer in my environment. After flushing each line `print("whatever",flush=True)` the real-time monitoring is now functional. Apologies.
