### ISSUE TITLE
How to set configuration for .pm2/pm2.log

### ISSUE THREAD

**Issue by gejiawen** [Unitech/pm2#2950]
Hi, there

I want to give a custom path to the .pm2/pm2.log, but I have no idea there are any configuration for this action.

```
PM2 version: 2.4.6
Node version:  8.0.0
Platform: Linux
```

**Comment by vmarchaud** [comment]
Duplicate https://github.com/Unitech/pm2/issues/2921
There is a workaround that consist of running the daemon with `PM2_LOG_FILE_PATH=/dev/null` with the latest PM2 version (`2.5`)
