### ISSUE TITLE
filtering double slash

### ISSUE THREAD

**Issue by black-snow** [Unitech/pm2#2952]
**What's going wrong?**
*pm2* seems to filter double slashes when passing to `start()`. While I do understand this for paths I consider this a bug for args.

Example:

```js
pm2.start({
    script: './whatever.js -- tcp://127.0.0.1:8001',
    name: 'whatever'
}, (err, proc) => {})
```

Output:
```
Error: script not found : /xyz/whatever.js -- tcp:/127.0.0.1:8001
```

Adding quotes doesn't help. Adding `-x` doesn't help. `--node-args` doesn't help either.

**How could we reproduce this issue?**
See above.

## Supporting information

```
PM2 version: `pm2 -v` 2.4.6
Node version: `node -v`v8.1.2
Windows? Mac? Linux? Mac x64 10.12.5
```

Can't believe I'm the first to stumble upon this. Am I missing something?

**Comment by vmarchaud** [comment]
You need to use `args` option, its documented here http://pm2.keymetrics.io/docs/usage/application-declaration/#general

**Comment by black-snow** [comment]
That works, thanks.
