### ISSUE TITLE
how can i add proccess info into log when set merge_logs true?

### ISSUE THREAD

**Issue by snadn** [Unitech/pm2#2954]
When I set merge_logs to true, all logs are output to a file. How do I know which process a log comes from?

### log from `pm2 logs` has proccess info
![image](https://user-images.githubusercontent.com/1269858/27365749-4ff2bbe4-5674-11e7-928c-be87517e34e2.png)

### log from log file has not proccess info

![image](https://user-images.githubusercontent.com/1269858/27365767-7175d878-5674-11e7-8f95-33050eaa299f.png)

```
PM2 version: 2.5.0
Node version: v6.11.0
Linux
```

**Comment by vmarchaud** [comment]
You can use json logging as documented [here](http://pm2.keymetrics.io/docs/usage/log-management/#directly-output-json-logs)
