### ISSUE TITLE
All files removed from Git after launching my app!

### ISSUE THREAD

**Issue by fruityfred** [Unitech/pm2#2955]
Hi all,

I have a very very (very) strange behaviour when I launch my app with pm2: after the launch, **all the files of my project are removed from the Git index**!

When I launch the app without pm2, directly with Node, everything works fine. But as soon as I launch it with pm2, all the files are removed. I have just repeated this a few times, and it behaves the same everytime! And this is the case on my two servers, with multiple users.

## Supporting information

Server is freshly installed with the following:
```
PM2 version: 2.5.0
Node version: 8.1.2
Linux Ubuntu
```

I launch the app with the following JSON launch file:
```
{
  "apps": [
    {
      "name": "Reyactif front (dev fred)",
      "script": "bin/www",
      "watch": "/home/fred/reyactif-front",
      "ignore_watch": ["public", "views", "\\.idea"],
      "cwd": "/home/fred/reyactif-front",
      "env": {
        "NODE_ENV": "development",
        "DEBUG": "*"
      }
    }
  ]
}
```

The editor I use is WebStorm (v2017.1,4).

Thank you very much for any help!

Regards,
Fred

**Comment by vmarchaud** [comment]
Can you try with the option `no_vizion: true` in the ecosystem ?

**Comment by fruityfred** [comment]
Does this option work in the JSON launch file? I do not have an ecosystem file...

**Comment by soyuka** [comment]
the json file is your ecosystem :)

**Comment by fruityfred** [comment]
Tried, but it behaves the same.

**Comment by fruityfred** [comment]
Well, my editor might be guilty... When I launch my app with pm2, but without the project opened in WebStorm, everything works fine, as expected (no files are removed).

Is pm2 writing something in the project directory that could bother WebStorm?

**Comment by vmarchaud** [comment]
PM2 doesn't write any file in the application directory by default, maybe try to remove PM2 options one by one to isolate any misconfiguration.
PS : closing since its doesn't come from PM2 itself

**Comment by fruityfred** [comment]
OK, thank you for your time!
I have created an issue on the WebStorm but tracker...
