### ISSUE TITLE
How to monitor in ELB?

### ISSUE THREAD

**Issue by lajpatshah** [Unitech/pm2#2960]
I have implemented pm2 in elb using start script.

I want to know how to run pm2 monit in elb?

**Comment by vmarchaud** [comment]
You need to connect on the remote server and do run the command, you can't monitor remotely with PM2 (but you can with [keymetrics.io](https://keymetrics.io), the platform we have done on top of PM2)

**Comment by lajpatshah** [comment]
Since the instance is controlled by elastic beanstalk, i cannot run any command on instance after remotely connecting to the server.

Anyway thanks
