### ISSUE TITLE
When `pm2 stop myapp`. PM2 kill all computer apps, and almost shutdown my computer :(

### ISSUE THREAD

**Issue by evaisse** [Unitech/pm2#2961]
**When `pm2 stop myapp`. My whole computer shutdown all apps & processes. then I cannot us eit anymore, I  must reboot to get back to work. :).**

Never seen this before since I'm using pm2.

**How could we reproduce this issue?**

A simple node js script (I'm using pmx metrics & action, maybe it's related). Launch it with pm2 : `pm2 start index.js`

When I restart the process, there is no problem.
When I want to stop the process : `pm2 stop index`, the whole computer shutdown all process. Then I must reboot to get back to work.

## Supporting information

```
PM2 2.5.0
Node v6.9.4
Mac 10.12.5
```

**Comment by vmarchaud** [comment]
Can you give us a sample code that reproduce the problem (with your configuration) ? It don't see any code in PM2 that could kill all your processes apart from your application launching itself these processes.

**Comment by evaisse** [comment]
I'm pretty sure this behavior is not excepted :)

here is the script : index.js
```
var pmx = require('pmx');

pmx.action('app:config', (reply) =>{
    reply({answer: 'foo'});
});

setInterval(() => 1, 100);
```

The problem is probably related to os version. Since when I'm running the same code on debian server, I don't have any problem.

I'd just try to use pm2 @2.1.0 to if it change something but the problem is still there.

**Comment by Unitech** [comment]
Any news? It looks like it's not related to PM2 at all

**Comment by evaisse** [comment]
This is the first time is see this behavior and it's clearly related to pm2. I will try to produces some additionnal logs but this is not easy since each time I call `pm2 stop index` my computer reboot.

**Comment by evaisse** [comment]
Hello, without node V6.11.1, I cannot reproduce the behavior anymore. 
```
pm2 v2.5.0
node v6.11.1
npm v3.10.10
```
MacOSX 10.12.5 (16F73)
