### ISSUE TITLE
Can't list PM2 processes ran from Supervisor

### ISSUE THREAD

**Issue by Noxalus** [Unitech/pm2#2962]
Hello everyone 😄 

I'm using [supervisor](http://supervisord.org/) to manage and monitor all my processes, and some of them use PM2. To launch these PM2 processes, I have a `pm2.json` configuration file that looks like that:

```
{
  "apps" : [
    {
      "name"        : "service1",
      "script"      : "/var/www/service1/dist/index.js",
      "instances"   : 2,
      "exec_mode"   : "cluster"
    },
    {
      "name"        : "service2",
      "script"      : "/var/www/service2/dist/index.js",
      "instances"   : 2,
      "exec_mode"   : "cluster"
    },
    {
      "name"        : "service3",
      "script"      : "/var/www/service3/dist/index.js",
      "instances"   : 2,
      "exec_mode"   : "cluster"
    }
  ]
}
```

Thus, the supervisor command for one service looks like that;

`/usr/bin/pm2 start /etc/pm2.json --only service1 --no-daemon`

(Please notice the `--no-daemon` that is needed because it's supervisor that handle this task)

The services are successfully launched, and I can access to them, but if I want to list them (using `pm2 list`), I get an empty list.

However, when I look at the running processes (`ps faux | grep pm2`), these services appear and have been run by the same user (*root* user in my test case):

```
root      6855  0.7  0.8 943772 34844 ?        Sl   16:39   0:09  \_ node /usr/bin/pm2 start /etc/pm2.json --only service1 --no-daemon
root     12161  0.4  2.2 1038660 92600 ?       Sl   16:49   0:02  |   \_ node /var/www/service1/dist/index.js
root     12167  0.4  2.3 1039544 95164 ?       Sl   16:49   0:02  |   \_ node /var/www/service2/dist/index.js
root     12192  0.3  1.7 1017484 70916 ?       Sl   16:49   0:02  |   \_ node /var/www/service3/dist/index.js
root     13534  0.5  1.7 1019144 72392 ?       Sl   16:53   0:02  |   \_ node /var/www/service1/dist/index.js
root     13535  0.5  1.8 1019884 73492 ?       Sl   16:53   0:02  |   \_ node /var/www/service2/dist/index.js
root     13541  0.5  1.7 1021736 72584 ?       Sl   16:53   0:02  |   \_ node /var/www/service3/dist/index.js
root      6873  0.0  0.7 906756 29448 ?        Sl   16:39   0:01  \_ node /usr/bin/pm2 start /etc/pm2.json --only service2 --no-daemon
root      6891  0.0  0.6 896284 27976 ?        Sl   16:39   0:01  \_ node /usr/bin/pm2 start /etc/pm2.json --only service3 --no-daemon

```

Moreover, it seems that NodeJS applications launched by PM2 are forked only from the first `pm2 start` command. That means if I want to restart the *service1*, it will restart NodeJS applications of *service1*, *service2* and *service3*, I would like to avoid that...

Did I do something wrong?

## Supporting information

```
PM2 version: `pm2 -v` => 2.5.0
Node version: `node -v` => v6.11.0
Ubuntu 14.04.5 LTS
```

**Comment by vmarchaud** [comment]
You might have two daemon launched (one with processes and one with no processes), just kill the ones that are empty.

**Comment by Noxalus** [comment]
Thank you very much for your answer @vmarchaud!

I always make sure to use PM2 commands with `no-deaemon` flag, even when I want to list the PM2 processes. When I looked to the running PM2 processes, I obtain the list that I posted above, there is no reference to any PM2 daemon.

Moreover, if I type `pm2 kill`, I get this:

```
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
[PM2] Stopping PM2...
[PM2][WARN] No process found
[PM2] All processes have been stopped and deleted
[PM2] PM2 stopped
```

The line `PM2 Successfully daemonized` seems to indicate that no PM2 daemon was actually running, isn't it?

Maybe I should start the PM2 daemon before to call `pm2 start [...] --no-daemon` if I want to list PM2 processes later?

**Comment by Noxalus** [comment]
Ok, I've perform a lot of tests, and there is definitely something I don't understand.

For instance, I've tried to launch the PM2 daemon but with the `--no-daemon` flag (still to be managed by supervisor later), and I noticed than when I launch a PM2 process (through `pm2 start pm2.json --only service1 --no-daemon`), it seems that this new process is directly attached to the PM2 daemon I've launched just before. 

It's a big problem for me because it means that if I kill the new process (*CTRL-C*), the NodeJS program is still running because it doesn't kill the daemon on which the PM2 process is attached. :/ That explains, in particular, why all NodeJS processes were attached to only one PM2 process when I perform a `ps faux | grep node`.

Is there a way to have independant PM2 processes that run only the script they are supposed to manage but that we can update using PM2 commands? Ideally, I think I would like to have something like that:

```
root     13802 13.3  0.8 887228 32492          Sl   09:01   0:00  \_ node /usr/bin/pm2 --no-daemon
root      6855  0.7  0.8 943772 34844 ?        Sl   16:39   0:09  |   \_ node /usr/bin/pm2 start /etc/pm2.json --only service1 --no-daemon
root     12161  0.4  2.2 1038660 92600 ?       Sl   16:49   0:02  |   |   \_ node /var/www/service1/dist/index.js
root     13534  0.5  1.7 1019144 72392 ?       Sl   16:53   0:02  |   |   \_ node /var/www/service1/dist/index.js
root      6873  0.0  0.7 906756 29448 ?        Sl   16:39   0:01  |   \_ node /usr/bin/pm2 start /etc/pm2.json --only service2 --no-daemon
root     12167  0.4  2.3 1039544 95164 ?       Sl   16:49   0:02  |   |   \_ node /var/www/service2/dist/index.js
root     13535  0.5  1.8 1019884 73492 ?       Sl   16:53   0:02  |   |   \_ node /var/www/service2/dist/index.js
root      6891  0.0  0.6 896284 27976 ?        Sl   16:39   0:01  |   \_ node /usr/bin/pm2 start /etc/pm2.json --only service3 --no-daemon
root     12192  0.3  1.7 1017484 70916 ?       Sl   16:49   0:02  |   |   \_ node /var/www/service3/dist/index.js
root     13541  0.5  1.7 1021736 72584 ?       Sl   16:53   0:02  |   |   \_ node /var/www/service3/dist/index.js
```

**Comment by vmarchaud** [comment]
I think the behavior here is that the CLI try to connect to the daemon even when the `--no-daemon` flag is here, it's definitely a problem PM2 side.

**Comment by Noxalus** [comment]
Thanks again for your answer.

Like you said, I think that the PM2 daemon is launched even if we use the `--no-daemon` and that the PM2 God daemon doesn't appear in the list of running processes.

If we exclude the supervisor thing from my tests and that we perform this simple tasks:
- Open a new terminal and run `pm2 start /etc/pm2.json --only service1 --no-daemon`
- Open a new terminal and run `pm2 start /etc/pm2.json --only service2 --no-daemon`
- Open a new terminal and run `ps faux | grep node`

We will see something like this:

```
root     14046  1.7  0.7 931592 29380 pts/3    Sl+  09:19   0:00   \_ node /usr/bin/pm2 start /etc/pm2.json --only service1 --no-daemon
root     14052  5.0  2.6 1025112 108492 pts/3  Sl+  09:19   0:02       \_ node /var/www/service1/dist/index.js
root     14058  5.2  2.5 1024076 105200 pts/3  Sl+  09:19   0:02       \_ node /var/www/service1/dist/index.js
root     14116 11.6  3.0 1040548 124176 pts/3  Sl+  09:20   0:02       \_ node /var/www/service2/dist/index.js
root     14122 11.9  3.1 1040572 125888 pts/3  Sl+  09:20   0:02       \_ node /var/www/service2/dist/index.js
root     14108  1.8  0.7 886892 31060 pts/0    Sl+  09:20   0:00   \_ node /usr/bin/pm2 start /etc/pm2.json --only service2 --no-daemon
```

Confirming what we just said. 

Now, if we run `pm2 list --no-daemon`, we can successfully list running PM2 processes like expected. But if we run `pm2 list` without `--no-daemon` flag, the text saying that PM2 has been daemonized is missing, so I suppose that the daemon is actually running. However, if we run `ps faux | grep pm2` we will only see this:

```
root     14046  1.7  0.7 931592 29380 pts/3    Sl+  09:19   0:00   \_ node /usr/bin/pm2 start /etc/pm2.json --only service1 --no-daemon
root     14108  1.8  0.7 886892 31060 pts/0    Sl+  09:20   0:00   \_ node /usr/bin/pm2 start /etc/pm2.json --only service2 --no-daemon
```

So the daemon is definitly, and implictly, ran into the PM2 *service1* process.

But if I think a little bit more about it, without the PM2 daemon, how are we supposed to list or perform operations on our PM2 processes? When we launch some processes without the `--no-daemon` flag, the PM2 God Daemon have access to all subprocesses and can deal with them (list/start/stop, etc...). So to answer to my original question, I'm not supposed to list PM2 processes using PM2 commands, but with Supervisor commands instead. If each NodeJS app are properly attached to the corresponding PM2 process, it should work as expected. 😄

**Comment by vmarchaud** [comment]
After investigating the issue inside the code, we cannot ship a fix about that without breaking our whole startup system, and a little explaination is needed here of what is happening : 

The daemon, even when started in `--no-daemon`, will try to expose the RPC server and the event bus into a socket file inside `~/.pm2/`.
Why this behavior ? Because when you setup `pm2 startup`, it register a systemd (or whatever init system you have) service with the `--no-daemon` flag enabled so systemd want to restart it for example. 
And it's because with the `--no-daemon` flag we expose the RPC server that you can manage processes started with the init system.

--------------
Solution : You need to start each daemon within a custom directory so each daemon can expose his RPC server. To do this, simply add a `PM2_HOME=/tmp/service1` before starting in no-daemon mode for each service.

**Comment by Noxalus** [comment]
Thanks for your consideration. I will try to use `PM2_HOME` env variable as you advice, but I think that I will try to find an equivalent of Supervisor to manage daemonized processes in the future.

**Comment by vmarchaud** [comment]
Yeah i think thats not necessarily a good idea to try using a process manager to manage a process manager ^^
