### ISSUE TITLE
Can I change my app script path for reloading?

### ISSUE THREAD

**Issue by oscchun** [Unitech/pm2#2963]
Hello. ;)

I have a question for using pm2.

I wanna reload my app after changing my app script path programmatically.
This is for zero downtime restart with new version code of my app.

only I have to copy my new version app to current path before reload or to change symlink?

please guide me to right way.. T.T

**Comment by vmarchaud** [comment]
Hello !
You can't change the script path and reload, PM2 won't pickup the changes, you need to delete the process and start the new one.
However what you can do is using symlink (like [capistrano do](http://capistranorb.com/documentation/getting-started/structure/))

**Comment by dword-design** [comment]
> However what you can do is using symlink (like [capistrano do](http://capistranorb.com/documentation/getting-started/structure/))

pm2 will resolve the symlink, so that doesn't work. And the paths in the dump (pm2 save) will also be resolved. Basically zero downtime deployment not possible with release folders.
