### ISSUE TITLE
pm2 update resets config

### ISSUE THREAD

**Issue by dnohr** [Unitech/pm2#2965]
Hi all,

When updating pm2 the config with saved websites resets. This means when I need to update pm2 all my sites will be down and I need to manually add the sites again.

OS: Ubuntu server
NODE: v8.1.2
NPM: 5.0.3
PM2: 2.5.0

Anybody experienced the same behaviour?

Following didn't work, only for OS restarts but not update.
pm2 startup ubuntu
pm2 save

**Comment by Unitech** [comment]
Are you using NVM? Have you upgraded the Node.js version since that?

Please verify pm2 bin path in the  /etc/systemd/system/pm2XXX is correct.
Don't forget to call pm2 save when you want to keep the same process list at every reboot.

**Comment by dnohr** [comment]
No, I'm not using NVM but using the latest Node.js version (8.1.2).

For now the issue occur when updating pm2 to the latest version. Somehow the config is ignored and I'm getting an empty list of pm2 tasks. The pm2 bin path is correct installed.

Other things I could try test? I'm running Ubuntu 16.10.

**Comment by Unitech** [comment]
fixed
