### ISSUE TITLE
pm2 don't start correctely

### ISSUE THREAD

**Issue by superjey** [Unitech/pm2#2969]
hello all.

when i run pm2 in my dir app it's allright
(cd /DATA/www && pm2 start /DATA/www/server.js)

but when i run since root_dir i have in web page this error " Cannot GET /  "
and it does not auto start my server.js also 
WHY???

the server.js is app of cryptpad
i use debian 8

npm -v >> 5.0.3
nvm --version >> 0.33.2

thanks

**Comment by Unitech** [comment]
since root_dir? Running in /DATA/www?

**Comment by superjey** [comment]
no root dir >> /root/
or other dir i have same fail

**Comment by Unitech** [comment]
any more precise infos? if you could give me some bash commands to reproduce the bug, please do

**Comment by superjey** [comment]
my web root dir is "/DATA/WEB/ {subdomain} "

git clone https://github.com/xwiki-labs/cryptpad.git /DATA/WEB/cryptpad
cd /DATA/WEB/cryptpad/
npm install
bower install --allow-root
pm2 start server.js
server   │ 0  │ fork │ 12394 │ online │ 0       │ 0s     │ 14% │ 24.2 MB   │ disabled

here, cryptpad work
i stop it and....

pm2 delete 0
cd /root (or other dir)
pm2 start /DATA/WEB/cryptpad/server.js
server   │ 0  │ fork │ 12563 │ online │ 0       │ 5m     │ 0%  │ 39.1 MB   │ disabled

but
curl https://cryptpad.myndd.com
Cannot GET /
________________________

if i use your web platform "app.keymetrics.io" my cryptpad work
this problem does not from pm2 but from my config so i think you can not help me.

**Comment by wallet77** [comment]
Closed due to a lack of activity.
Feel free to reopen if necessary.
