### ISSUE TITLE
Long log file names

### ISSUE THREAD

**Issue by satazor** [Unitech/pm2#2970]
**What's going wrong?**
Log file names are strangely huge and have a long number appended indefinitely:

<img width="815" alt="screen shot 2017-06-27 at 10 08 50" src="https://user-images.githubusercontent.com/1017236/27579866-e0d14e68-5b20-11e7-97c0-ce4e37f52d11.png">
 
**How could we reproduce this issue?**

I'm running pm2 for one year in production for https://npms.io and this started happening recently after upgrading. I don't really know the old pm2 version but it was a few months older. I'm also using logrotate to rotate the logs like so:

```
/xxx/.pm2/pm2.log /xxx/.pm2/logs/* {
        rotate 14
        daily
        missingok
        notifempty
        compress
        delaycompress
        copytruncate
        create 0640 xxx xxx
}
```

And it's working correctly as we can see here:

<img width="697" alt="screen shot 2017-06-27 at 10 15 29" src="https://user-images.githubusercontent.com/1017236/27580115-9c093678-5b21-11e7-97bd-97b6fac869ac.png">

## Supporting information

```
PM2 version: 2.5.0
Node version: 6.11.0
Linux Debian Jessie
```

I can't figure out why is this happening, is it a bug?

Thanks.

**Comment by vmarchaud** [comment]
Do you use the pm2-logrotate module or anything like that ? Maybe the log rotation script based on `logrotate.d` ?

**Comment by satazor** [comment]
@vmarchaud nop, I'm not using pm2-logrotate. I'm using the native logrotate that is available in most unix installations. I've supplied the logrotate config above.

**Comment by vmarchaud** [comment]
Someome made a PR [here](https://github.com/Unitech/pm2/pull/2814) to fix this problem few months ago, are you sure that the logrotate script is up to date ?

**Comment by satazor** [comment]
The logrotate config was missing the `*.log`! Thanks for you support.
