### ISSUE TITLE
Time parser for log file names (ecosystem.json)

### ISSUE THREAD

**Issue by pittersnider** [Unitech/pm2#2974]
Hello dear PM2's team and users,

I'm here today requesting a new feature, something I guess could help and improve the use of this software for a lot of PM2's users. It is, basically, a parser of time (through `moment` API) to use in `ecosystem.json`, more specific at fields `error_file` and `out_file` (log file names).

**i.e.,** I wanna use:

```
{
...
        "error_file": "./logs/YYYY-MM-DD.stacktrace.txt",
        "out_file": "./logs/YYYY-MM-DD.normal.txt"
...
}
```

Where `YYYY-MM-DD` will be replaced by `year` (YYYY), `month` (MM) and `day` (DD).

**Comment by wofdwid** [comment]
**PS:** if someone give me the file name/path where it is processed, I will make the modifications needed and then make a new pull request.

Thank you all.

**Comment by vmarchaud** [comment]
Since the log aren't rotated automatically, the date wouldn't be useful by default, i advise you to use either [pm2-logrotate](https://github.com/pm2-hive/pm2-logrotate) or the native linux implementation [doc here](http://pm2.keymetrics.io/docs/usage/log-management/#setting-up-a-native-logrotate)
