### ISSUE TITLE
PM2 Raspberry Pi Discord.js Bot issue

### ISSUE THREAD

**Issue by Johnny33r** [Unitech/pm2#2975]
Im hosting a Discord Bot on my Raspberry Pi.
The Problem ist that pm2 is restarting my like 3 times a day. When i do "pm2 list" the status is online and it shows me 1 restart. But when i go in Discord my Bot is offline. I allways have to restart my Bot manually with "pm2 restart discordbot.js".

**Comment by soyuka** [comment]
This looks like a problem with the program itself. May you check `pm2 logs` to see if everything is fine? 

You may also look in `~/.pm2/pm2.log` for pm2 internal logs.

**Comment by Johnny33r** [comment]
There's everything fine in the Logs.

**Comment by fncolon** [comment]
It's event emitter conflict.
