### ISSUE TITLE
Specify which signal to use for graceful restarts (i.e. not SIGINT)?

### ISSUE THREAD

**Issue by julien-c** [Unitech/pm2#2976]
Is there any way to do this?

I can catch `SIGINT` alright in my Node app, however it execs/spawns a couple of child processes and those are passed through the same signal, and thus instantly killed.

If I have a way to e.g. use `SIGUSR2`, this will solve my problem.

**Comment by Unitech** [comment]
Published on PM2 2.6.0:

```bash
$ npm install pm2@latest -g
$ pm2 update
```

**Comment by julien-c** [comment]
Thanks Alex @Unitech 👍
