### ISSUE TITLE
NODE_APP_INSTANCE always 0 since 2.5.0

### ISSUE THREAD

**Issue by pkaske** [Unitech/pm2#2984]
**What's going wrong?**

It seems that since 2.5.0 every instance has NODE_APP_INSTANCE set to 0.

**How could we reproduce this issue?**

Start an app in fork mode with two instances and output NODE_APP_INSTANCE. It should always be 0.
As soon as I downgraded to 2.4.4 it started working again.

## Supporting information

```
Node version: v8.1.2
Linux
```

**Comment by Whwitpohe** [comment]
I tried using the cluster and fork modes,
The cluster mode is working properly
Fork mode will appear NODE_APP_INSTANCE has been 0 case

**Comment by vmarchaud** [comment]
I'm not able to reproduce the problem with the test suites, could you explain how you start your application ?

**Comment by Whwitpohe** [comment]
@vmarchaud  
My configuration file is as follows
{
  "apps": [
    {
      "name"      : "sms.x",
      "max_memory_restart": "1024M",
      "log_date_format": "YYYY-MM-DD HH:mm:ss SSS",
      "script": "./app.js",
      "out_file": "./log/sms/app.log",
      "error_file": "./log/sms/err.log",
      "instances"  : 2,
      "exec_mode"  : "fork",
      "env": {
        "isMaster": "0",
        "CDN_PREFIX": "//dbde4sd21oahf.cloudfront.net",
        "MONGO_URL": "mongodb://localhost:27017/rocketchat",
        "MONGO_OPLOG_URL": "mongodb://localhost:27017/local",
        "ROOT_URL": "http://rocket.chat",
        "PORT": "4000"
      }
    }
  ]
}

在 2.4.6 版本是正常的, 可以获取到两个NODE_APP_INSTANCE, 0 和1 
但是在2.5.0 版本中, NODE_APP_INSTANCE 都是 0

**Comment by pkaske** [comment]
Sure. I put up a repo with sample to reproduce the problem.

https://github.com/pkaske/pm2-issue-2984

It a very basic hapijs server (copy pasted from the tutorial). Only difference really is that NODE_APP_INSTANCE is used to increment the port for the server.

1. Clone it
2. Edit paths in start.json
3. Install pm2@2.4.4
4. Start the app with `pm2 start start.json` and watch log output. It should all be fine. 4 instances running on ports 9990 to 9993
5. Delete the app (`pm2 delete pm2-issue-2984`)
6. Install latest pm2 && pm2 update && pm2 flush
7. Start app again. Now it should flood the log with errors because NODE_APP_INSTANCE is 0 in every instance and therefore node tries to use the same port for multiple hapi server instances.

I tried to capture the process in a video. Maybe this helps too?

[pm2-issue-2984.zip](https://github.com/Unitech/pm2/files/1111550/pm2-issue-2984.zip)

**Comment by vmarchaud** [comment]
I reproduced the problem, trying to find a fix

**Comment by Unitech** [comment]
Published on PM2 2.6.0:

```bash
$ npm install pm2@latest -g
$ pm2 update
```

**Comment by DamodarSojka** [comment]
The issue came back for me in the 4.2.3v

```
--- PM2 report ----------------------------------------------------------------
Date                 : Thu Apr 23 2020 11:50:14 GMT+0000 (Coordinated Universal Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 4.2.3
node version         : 12.16.1
node path            : not found
argv                 : /usr/bin/node,/usr/bin/pm2,start,--no-daemon,--node-args=--max-old-space-size=4056,-i,3,app/index.js
argv0                : node
user                 : undefined
uid                  : 0
gid                  : 0
uptime               : 3min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 4.2.3
node version         : 12.16.1
node path            : not found
argv                 : /usr/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : undefined
uid                  : 0
gid                  : 0
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
cpus nb              : 4
freemem              : 9898024960
totalmem             : 16624889856
home                 : /root
===============================================================================
--- PM2 list -----------------------------------------------
┌─────┬──────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name     │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼──────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ index    │ default     │ 1.0.0   │ cluster │ 16       │ 3m     │ 0    │ online    │ 0.4%     │ 152.3mb  │ root     │ disabled │
│ 1   │ index    │ default     │ 1.0.0   │ cluster │ 23       │ 3m     │ 0    │ online    │ 0.3%     │ 152.1mb  │ root     │ disabled │
│ 2   │ index    │ default     │ 1.0.0   │ cluster │ 30       │ 3m     │ 0    │ online    │ 0.3%     │ 152.8mb  │ root     │ disabled │
└─────┴──────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
```

All three instances have NODE_APP_INSTANCE equal to 0

**Comment by NinoSkopac** [comment]
I just updated to 5.1.1 and the issue is **fixed**!

**Comment by maganap** [comment]
@NinoSkopac It appears it came back on 5.2.0  :-/

**Comment by bigtotorouk** [comment]
i have a same error.

**Comment by RienNeVaPlus** [comment]
Happening on ubuntu, but working on windows.
Did anybody manage to fix this?
