### ISSUE TITLE
pm2 v2.5.0 crashes after aws codedeploy

### ISSUE THREAD

**Issue by bertyhell** [Unitech/pm2#2985]
We have the following setup:
an EC2 instance (ubuntu) with pm2 installed using `sudo npm i pm2 -g`
a travis build with aws code deploy using the following scripts:
stop.sh:
```
pm2 delete ./pm2.config.js
```

start.sh
```
export ENV=stage && pm2 start ./pm2.config.js
```

pm2.config.js
```
module.exports = {
  apps : [
    {
      name: "aggregator",
      script : "./dist/app/app.js"
    }]
};
```

**What's going wrong?**
When code deploy executes it's scripts it thinks everything executed correctly, but pm2 crashed.
when you try to run `pm2 list` on the server, you would get this error:
```
path.js:1184
          cwd = process.cwd();
                        ^

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at Object.resolve (path.js:1184:25)
    at Function.Module._resolveLookupPaths (module.js:263:17)
    at Function.Module._resolveFilename (module.js:330:31)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainer.js:7:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**How could we reproduce this issue?**
* install pm2 v2.5.0 using sudo in an ec2 instance
* setup codedeploy scripts
* trigger a deploy

## Supporting information

```
PM2 version: 2.5.0
Node version: v6.10.0
Linux: Ubuntu 16.04.2 LTS
```

This issue doesn't happen when i use pm2 v2.4.4

**Comment by vmarchaud** [comment]
Could you try to add `cwd` option inside your ecosystem (it's an absolute path), so your `script` is only the file ?

**Comment by Unitech** [comment]
it is because the script path do not exist anymore
not a pm2 issue, closing

**Comment by bertyhell** [comment]
> it is because the script path does not exist anymore

You mean the script path of the app inside pm2?
Wouldn't it be best to capture that exception and show the pm2 list with that app marked as "missing" or "errored"?
