### ISSUE TITLE
pm2 Multiple God Daemons Spawning

### ISSUE THREAD

**Issue by 360disrupt** [Unitech/pm2#2987]
Similar to https://github.com/Unitech/pm2/issues/2784 but `ps -aux | grep pm2` gives me:
```
root       837  2.7  3.7 125176 35684 ?        Ssl  15:56   0:02 PM2 v2.5.0: God Daemon (/root/.pm2)         
root       955  2.0  3.3  88364 32056 ?        Sl   15:56   0:01 node /usr/bin/pm2 save
root       957  2.0  3.3  88324 31772 ?        Sl   15:56   0:01 node /usr/bin/pm2 kill
root      1135  1.6  2.9  81044 28140 ?        Ssl  15:56   0:01 PM2 v2.5.0: God Daemon (/root/.pm2)         
root      1141  1.7  2.9  81692 28216 ?        Ssl  15:56   0:01 PM2 v2.5.0: God Daemon (/root/.pm2)         
root      1147  1.5  2.9  81124 27648 ?        Ssl  15:56   0:01 PM2 v2.5.0: God Daemon (/root/.pm2)         
root      1230  0.0  0.2   4276  2008 pts/0    S+   15:58   0:00 grep pm2
```

Also `pm2 list` shows me no running processes, but the server is running.

Reproduction: calling the script again:
```
#!/bin/sh
startPm2() {
  USER="root"
  PM2_HOME="/root/.pm2"
  export USER PM2_HOME

  #delete to avoid all pm2 issues
  rm -rf "$PM2_HOME"

  if [ -f /home/pi/app/newVersion.tar.gz ]; then
    bash /home/pi/app/deploy.sh
  else
    pm2 kill && pm2 start /home/pi/app/processes.json --output /home/pi/app/logs/pm2.out --error /home/pi/app/logs/pm2.err &
  fi
  pm2 save
  pm2 startup systemd # also had this before pm2 start, found diff. approaches online
}
startPm2
```

Before that I launched pm2 with user pi, but I had problems with permissions on `/home/pi/.pm2/rpc.sock`, also exporting `PM2_HOME` dind't prevent pm2 from creating `/root/.pm2`.

Additionally I have the problem, that `pm2` is not starting properly after unplugging the power. But I think it is not pm2 related:
https://stackoverflow.com/questions/44851282/reliable-start-pm2-on-rasbian-jessie-pi3-linux

## Supporting information
```
PM2 version: `2.5.0`
Node version: `v7.10.0`
raspbian Jessie
```

**Comment by 360disrupt** [comment]
I think this happens if using `start` and `startup`. For me expected behaviour would be that `startup` takes the current configuration and starts it at reboot but it seems to run simultaneously. In my code I had the problem, that through trying I generated a boot script for pi and root which may also caused errors. 

To remove these scripts: 
`sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 unstartup systemd -u pi --hp /home/pi` and `sudo pm2 unstartup`

**Comment by Unitech** [comment]
fixed long time ago
