### ISSUE TITLE
the load balance lose efficacy when use grpc in cluster mode

### ISSUE THREAD

**Issue by yunnysunny** [Unitech/pm2#2988]
We use grpc to communicate between two pcs. The server side starts with cluster mode with 4 instances. Grpc is based on http/2 technology, and the client should not open more than one HTTP/2 connection to a given host and port pair.
And we found that pm2's load balance based on socket handle. It result that once a persistent connection open , then  it will only communicate with the one it connected before. In other words, the load balance will  lose efficacy when use grpc.

**Comment by vmarchaud** [comment]
I understand your problem but i don't see the point of making an issue for this, every load balancer out here will have the same "problem", if the client is the same TCP connection, you can't load-balance it.

**Comment by yunnysunny** [comment]
I just wanna if this is a solution of doing load balance of grpc.
