### ISSUE TITLE
How to use local repository as repo

### ISSUE THREAD

**Issue by VladShcherbin** [Unitech/pm2#2989]
**What's going wrong?**

I have a local repo `dist.git`, initiated as `git init --bare`. Now I want to deploy it to production server so I set it in config:

```config
deploy: {
  production: {
    user: '...',
    host: '...',
    ref: 'master',
    repo: './dist/dist.git',
    path: '...'
  }
}
```

I tried relative path, absolute path, `${__dirname}/dist/dist.git`. No luck. The error is always the same:

```console
fatal: repository 'dist/dist.git' does not exist
```

Env:
```
PM2 version: 2.5.0
Node version: 8.1.2
Mac
```

**Comment by vmarchaud** [comment]
repository is the git repository, the one that will be used when running `git clone`

**Comment by VladShcherbin** [comment]
@vmarchaud yes, I init local git repository. I can clone it using `git clone`, but can't use with pm2 because it give me this error.

**Comment by VladShcherbin** [comment]
@vmarchaud here it is:

```console
git clone dist.git ./cloned

Cloning into './cloned'...
done.
```

pm2 can't use it for some reason.
