### ISSUE TITLE
Possibility to use local repository for pm2-deploy

### ISSUE THREAD

**Issue by VladShcherbin** [Unitech/pm2#2990]
Related to this [issue](https://github.com/Unitech/pm2/issues/2989)

After looking at pm2-deploy code, it clones the git repository from server, so when I was trying to use local repository it failed with error.

So, in order to use pm2-deploy you are *forced* to push repository somewhere from where it can be cloned using network (github / bitbucket / server / etc) .

Is it possible to make pm2-deploy use local repository?
If not, what's the solution if you don't want to push repo anywhere?

**Comment by vmarchaud** [comment]
You can't use `pm2-deploy` in this case, you can `shipit` for example.

**Comment by VladShcherbin** [comment]
@vmarchaud Thank you.
