### ISSUE TITLE
Apllication is slow when using pm2

### ISSUE THREAD

**Issue by akmittal** [Unitech/pm2#2993]
**What's going wrong?**
app is slow when using pm2
**How could we reproduce this issue?**
I have written a simple koa server
```
const Koa = require('koa');
const app = new Koa();

app.use(ctx => {
  ctx.body = 'Hello World';
});

app.listen(3000);
```

I am using [go-wrk](https://github.com/tsliwowicz/go-wrk) to load test the app.
1. Result using node koa.js
![node](https://user-images.githubusercontent.com/1594654/27768375-cbea50a4-5f2f-11e7-9986-7d8d300d8c16.PNG)

2. Result using pm2 start koa.js
![pm2 start](https://user-images.githubusercontent.com/1594654/27768378-d429dff0-5f2f-11e7-8311-d2be39bf42ab.PNG)
3. Result using pm2 start koa.js -i 0
![pm2 multiple instance](https://user-images.githubusercontent.com/1594654/27768382-ec731a90-5f2f-11e7-9400-ec837281ffbb.PNG)

## Supporting information

```
PM2 version: `2.5.0`
Node version: `8.1.3`
Windows
```

**Comment by Unitech** [comment]
aha what a benchmark.
It is just wrong or it might just be windows or a single core issue.

**Comment by baybird** [comment]
Having the same issue with using pm2. Slow down Node, and caused many 502 errors.
