### ISSUE TITLE
PM2 services not starting after unexpected restart

### ISSUE THREAD

**Issue by ErnaniRic** [Unitech/pm2#3000]
**What's going wrong?**
I have three PM2 services auto starting in a Raspberry Pi 3. When I restart the Rasp properly, with `sudo reboot`, they are started automatically and correctly. However, when there's an unexpected restart (unplugging the Rasp from an energy source, for example), the services are not started.

A message saying that PM2 is being daemonized appear in these situations, as the anexed image shows:
![error daemon](https://user-images.githubusercontent.com/29929035/27881227-3a111c96-619e-11e7-92aa-2b1f4c994ba2.png)

**How could we reproduce this issue?**
Install a service in a Raspberry Pi 3 (my services are JavaScript files) and setting them to auto start with `pm2 save`. Then, reboot the Rasp with sudo reboot to chek if the service is starting automatically; after that, unplug the Rasp from the energy source and check if, in this case, is also starting automatically.

## Supporting information

```
PM2 version: 2.4.6
Node version: 6.10.3
Raspbian Jessie version: 8
```

**Comment by Unitech** [comment]
Can you show me the file `/etc/systemd/system/pm2-pi.service`

**Comment by ErnaniRic** [comment]
Sure. Here it is:
![pm2-pi service](https://user-images.githubusercontent.com/29929035/27921813-5c2c841c-624f-11e7-8938-3034efecf3e5.png)

**Comment by ErnaniRic** [comment]
I have altered the `/etc/rc.local` file in a way that it starts each service at a time, like this:

> pm2 list
> 
> pm2 start moscaService.js
> pm2 start integrationService.js
> pm2 start app.js

However, the problem still persists. The services are started via this file if the Raspberry is booted correctly, but when is booted incorrectly, not.
Even though the services are being shown in the screen as `started` after each `pm2 start`, after I log and use `pm2 list`, no services are listed.

Could it be an authentication problem?

**Comment by ErnaniRic** [comment]
After testing, it seems that the cause of this problem was the micro SD card where the Raspbian was running. After changing the cards and copying the image, this error no longer occured as frequently.
