### ISSUE TITLE
Not starting TypeScript files inside Docker containers

### ISSUE THREAD

**Issue by danprince** [Unitech/pm2#3003]
**What's going wrong?**
If PM2 is started inside a Docker container, it starts a process, but doesn't actually seem to execute any of my TypeScript files.

Here's what happens when PM2 runs on my local development machine:

![image](https://user-images.githubusercontent.com/1266011/27938038-4579aa4c-62b3-11e7-8b93-5d45ed98fa38.png)

And here's the same setup but running inside a Docker container. It hangs indefinitely here:

![image](https://user-images.githubusercontent.com/1266011/27938067-7d3ddc96-62b3-11e7-9445-65787d292e35.png)

I can attach to a shell within the running container, then run `ts-node src/index.ts` to get the expected results, so I think the problem is something to do with how PM2 handles running the TypeScript file.

The same setup works fine inside the container if PM2 is running a JavaScript file.

**How could we reproduce this issue?**

I've put together a minimal example:

https://github.com/danprince/pm2-ts-docker

* Use `make pm2` to verify that it works when run locally.
* Use `make docker` to build + run a docker image to verify that it does not work in a container.

**Comment by Unitech** [comment]
add `RUN pm2 install typecript` in your dockerfile, else pm2 will not support ts transpilation

**Comment by danprince** [comment]
@Unitech What does `pm2 install typescript` do? Other than installing `ts-node` and `typescript`?

**Comment by vmarchaud** [comment]
@danprince Nothing else, just installing them in the right directory so PM2 can use them to start your applications

**Comment by danprince** [comment]
Ah, and because the PM2 install is global it doesn't pick up the local devDependencies... Bit of a slow moment there.

Thanks!
