### ISSUE TITLE
Feature request - pm2 bounce itself to clear out log viewer and lower cpu

### ISSUE THREAD

**Issue by dman777** [Unitech/pm2#3004]
**What's going wrong?**

When using `pm monit` and app has continues logging...like once every three seconds, cpu will slowly increase over the course of a few hours.

**feature request**

Have pm2 monitor bounce it's self once every N hours. Allow it to be set by the user according to the log activity.  

## Supporting information

```
PM2 version: `2.5.0`
Node version: `8.0.0`
  Linux
```

**Comment by vmarchaud** [comment]
Duplicate https://github.com/Unitech/pm2/issues/2793
