### ISSUE TITLE
pm2 startup systemv

### ISSUE THREAD

**Issue by dptole** [Unitech/pm2#3005]
**What's going wrong?**

The startup process does not work as intended. I have to edit the `/etc/init.d/pm2-ec2-user` file replacing the command

```
su - $USER -s $shell -c "PATH=$PATH; PM2_HOME=$PM2_HOME $*"
```

with

```
sudo -u $USER PM2_HOME=$PM2_HOME $* # start up my apps (it will crash)
sudo -u $USER authbind --deep pm2 update # update the apps so they can access port 80 as ec2-user
```

because I need to use the port 80 && not run the app as root && be able to `pm2 deploy` it. The original command `su - $USER -s $shell ......` does not work because it asks for the $USER's password, which is not set, we access it through a private key file.

Maybe I'm missing some bits of configuration to make the startup process work + allow pm2 deploy as non-root user and access the port 80. My wrapper worked just fine for me but I think you guys should know. Any idea how to make it work without editing the `/etc/init.d/pm2-ec2-user` file would be appreciated.

**How could we reproduce this issue?**

- Create a EC2 Amazon instance
- Create an app that should run as non-root but access ports below 1024
- Run the startup command (pm2 startup systemv)
- Configure the deploy options on your `pm2.json` file to be performed as a non-root user
- Try to deploy it and see if the app is still up

## Supporting information

```
PM2 version: `pm2 -v`
2.5.0
Node version: `node -v`
v8.1.3
Windows? Mac? Linux?
Amazon EC2
```

**Comment by vmarchaud** [comment]
Our startup script is (generally) aimed for people that have no knowledge of their init system. In the case of a custom configuration on your hand, you will indeed need to edit the service file yourself.
That's pretty much a behavior that we want to keep : we can't handle all variant of configuration that each init system handle cause it would be a lot of work.

**Comment by dptole** [comment]
@vmarchaud I thought I was doing something wrong. Thanks for answering me!
