### ISSUE TITLE
PM2-dev stuck on Stopping current development session

### ISSUE THREAD

**Issue by archasek** [Unitech/pm2#3006]
**What's going wrong?**

When I run `pm2-dev start pm2.json` with the json config:

```
{
    "apps": [{
        "name": "myApp",
        "script": "app.js",
        "ignore_watch": [
            ".*"
        ],
        "log_date_format": "YYYY-MM-DD HH:mm",
        "env": {
            "NODE_ENV": "development"
        }
    }]
}
```

The app and pm2 are ok, but when I want to exit/kill the process, PM2 gets stuck regardless on the number of CTRL+C tries.
I can see this kind of messages:
```
>>>>> [PM2 DEV] Stopping current development session
>>>>> [PM2 DEV] Stopping current development session
>>>>> [PM2 DEV] Stopping current development session
```

**How could we reproduce this issue?**

I don't really know, I think this occurs on any Windows environment when using pm2-dev (I reproduced this problem using another PC).

## Supporting information

```
PM2 version: 2.5.0
Node version: 7.9.0
Windows 7 Pro
```

**Comment by vmarchaud** [comment]
Can you try on a unix platform to see if it's also happening ?

**Comment by archasek** [comment]
Not yet. I am curious whether this issue is connected with a promise that is not resolved yet?

**Comment by Unitech** [comment]
I guess it come from https://github.com/Unitech/pm2/blob/development/lib/binaries/DevCLI.js#L123

**Comment by Unitech** [comment]
could you do:

```
$ DEBUG="pm2:*" pm2-dev start pm2.json
# CTRL-C
```

and paste all the logs here please thank you
