### ISSUE TITLE
PM2 leaking half sockets, eventually runs out of FDs

### ISSUE THREAD

**Issue by zimbabao** [Unitech/pm2#3008]
**What's going wrong?**
PM2 is leaking half sockets slowly and eventually runs our of the FDs and application stops working due to inability to open more files/connections.

```
$ sudo lsof -c PM2 | grep "TCPv6"   | wc -l
PM2\x20v2 8969 user1  108u     sock                0,8      0t0 1881420454 protocol: TCPv6
PM2\x20v2 8969 user1  109u     sock                0,8      0t0  912725028 protocol: TCPv6
PM2\x20v2 8969 user1  110u     sock                0,8      0t0  921818965 protocol: TCPv6
PM2\x20v2 8969 user1  111u     sock                0,8      0t0  967767400 protocol: TCPv6
PM2\x20v2 8969 user1  113u     sock                0,8      0t0 1129991518 protocol: TCPv6
PM2\x20v2 8969 user1  114u     sock                0,8      0t0  997754047 protocol: TCPv6
PM2\x20v2 8969 user1  115u     sock                0,8      0t0 2398051224 protocol: TCPv6
PM2\x20v2 8969 user1  122u     sock                0,8      0t0 2581250588 protocol: TCPv6
```
I don't have a clear repro for this, it happens in production.

**How could we reproduce this issue?**
No clear repro. Sorry about that.

**I'm looking for ideas to collect data more data about this. I'm trying to repro this in a controlled setup**

## Supporting information

```
PM2 version: 2.5.0
Node version: 8.1.1
Windows? Mac? Linux? : Linux - Ubuntu 16.04
```

**Comment by vmarchaud** [comment]
Do you use Keymetrics or it happens only with PM2 ? Could you please share a little bit more about your PM2 setup ?

**Comment by zimbabao** [comment]
Not using keymetrics. pm2 starting application in cluster mode (20-40 workers).

**Comment by Unitech** [comment]
Do applications restart often?

**Comment by zimbabao** [comment]
The application worker(not all workers) restarts on unexpected inputs. Can that cause the leakage?.

**Comment by omarcosr** [comment]
I noticed the same behavior on my machine, any update on this?
