### ISSUE TITLE
Using Name Variable in Cmd Doesn't Override Config.js FIle

### ISSUE THREAD

**Issue by jackrobson** [Unitech/pm2#3009]
**What's going wrong?**
I want to be able to run three instances of this same server. Therefore, I'd like to run 
pm2 start ecosystem.config.js --name development
pm2 start ecosystem.config.js --env staging --name staging
pm2 start ecosystem.config.js --env production --name production

However, it starts process called "example" instead of over-riding with name variable.

**How could we reproduce this issue?**
Here is my example ecosystem.config.js

module.exports = {
  apps : [
      {
        name: "example",
        script: "./server.js",
        env: {
            "PORT": 4000,
            "NODE_ENV": "development"
        },
        env_staging: {
            "PORT": 4250,
            "NODE_ENV": "staging",
        },
        env_production: {
            "PORT": 4500,
            "NODE_ENV": "production",
        }
      }
  ]
}

And here is a basic server.js

const express = require('express')
const app = express()

app.get('/', function (req, res) {
  res.send('Hello World!')
})

app.listen(3000, function () {
  console.log('Example app listening on port 3000!')
})

Run:
pm2 start ecosystem.config.js --name development

However, it starts process called "example" instead of over-riding with "development" name.

## Supporting information

```
PM2 version: `pm2 -v` 2.5.0
Node version: `node -v` 6.11.0
Windows? Mac? Linux?: Linux
```

**Comment by Unitech** [comment]
ecosystem.config.js can contains a lot of processes, you cannot override only one process name via CLI
