### ISSUE TITLE
Pass node-args with pm2-dev/pm2-docker

### ISSUE THREAD

**Issue by shaharmor** [Unitech/pm2#3011]
**What's going wrong?**
Can't pass node-args to pm2-dev

**How could we reproduce this issue?**
Try to pass any node-args to pm2-dev using `pm2-dev start app.js --node-args="w/e"`

**Comment by Unitech** [comment]
```
$ npm install Unitech/pm2#development -g
$ pm2-dev start app.js --node-args="w/e"
```

Will do the release next we after some stress test
