### ISSUE TITLE
[Question] Multiple pm2 on same server with docker

### ISSUE THREAD

**Issue by shaunwarman** [Unitech/pm2#3012]
What is best practice for [multiple pm2 on the same server](http://pm2.keymetrics.io/docs/usage/specifics/#multiple-pm2-on-the-same-server) when in a docker environment.

Ideally I would like to have nginx as load balancer to 2 different docker containers. These containers would have pm2 and some set of worker instances. The benefit here is that I can get availability benefits from pm2 in terms of graceful start/restart/shutdown and also have some retry capabilities at the nginx level from heartbeats and some 502 503.

Two challenges come to mind:
- Logging
- `instances: max`

*Logging*
With [multiple pm2 on the same server](http://pm2.keymetrics.io/docs/usage/specifics/#multiple-pm2-on-the-same-server) I can share a socket. Docker may hide the file system details, so would it make sense to share a data volume between the two pm2 containers for some resources?

*`instances: max`*
With 2 instances of pm2 on the same server will `instances: max` cause an over abundance of node workers now compared to the recommended 1:1 worker:cpu core?

Thoughts?

**Comment by gabrielcsapo** [comment]
@Unitech?

**Comment by vmarchaud** [comment]
Actually they cannot share the same socket file so indeed you will need to bind volumes to different directory on the host (like written on the `multiple pm2 on the same server` doc)
Also for the logging, the host should handle both PM2 trying to write on the same file so you should be able to bind the logs directory on the same directory

Speaking about the `instances: X` indeed you respect the 1 worker: 1 cpu rule. Note that you can tell Docker to `pin` a container on a specific CPU so you should checkout on this direction too
