### ISSUE TITLE
strange pm2 list output!!!

### ISSUE THREAD

**Issue by babakyakhchali** [Unitech/pm2#3013]
Hi
when using "pm2 list" I see modules that I did not install for pm2
![image](https://user-images.githubusercontent.com/4052371/28111974-970646a6-670c-11e7-9e90-035de0415ba0.png)
why are  "arr-diff arr-flatten"... listed as modules???
the version is 0.12.15
thanks

**Comment by vmarchaud** [comment]
You should upgrade to latest version

**Comment by babakyakhchali** [comment]
after updating I get this output
![image](https://user-images.githubusercontent.com/4052371/28352428-90a675a6-6c6b-11e7-9e95-4027d8cef70d.png)

it seems pm2 tries to load everything in node_modules folder as a module

**Comment by babakyakhchali** [comment]
It seems this is like [https://github.com/Unitech/pm2/issues/1692](url)
I renamed /root/.pm2/node_modules and it problem is solved
![image](https://user-images.githubusercontent.com/4052371/28352725-5b9bc846-6c6d-11e7-8fdc-02e53d8ec394.png)
thanks
