### ISSUE TITLE
Content of process.versions change between fork_mode and cluster_mode

### ISSUE THREAD

**Issue by dpjayasekara** [Unitech/pm2#3014]
**What's going wrong?**
Attribute values of `process.versions` object are different between fork_mode and cluster_mode. For an example, in cluster_mode `process.versions.node` outputs `8.0.0-rc.2`, and in fork_mode, it outputs `8.1.3` which is semver compliant. Here is the complete diff of the attributes:

<img width="936" alt="screen shot 2017-07-12 at 4 26 55 pm" src="https://user-images.githubusercontent.com/1533286/28116026-dba3c0fa-6724-11e7-809c-f1fbad70f8e5.png">

**How could we reproduce this issue?**

I have the following piece of code in my app which checks for the version using `semver` module. This fails in cluster_mode as the `process.versions.node` is not semver compliant in cluster_mode.

```
const semver = require('semver');
if (!semver.satisfies(process.versions.node, '>=8.0.0')) {
    throw new Error('node v8.0.0 or greater is required to run this application.');
}
```
What is causing this difference? and how to use semver check in cluster mode without applying a hack?

## Supporting information

```
PM2 version: 2.1.5
Node version: v8.1.3
OS: MacOS Sierra 10.12.5
```

**Comment by vmarchaud** [comment]
You need to run `pm2 update`, the cluster mode is spawning with the same version as the daemon but the fork mode will use the `node` binary in the PATH.

**Comment by dpjayasekara** [comment]
It worked. Thanks.

But I've got a new question then. If this is the case it affects the other applications running with a different `--interpreter` and in cluster_mode, isn't it? For an example, I need to run two applications, both in cluster_mode, one on node v4.x.x. and the other on node v8.x.x.

App 1: node v4
```
var semver = require('semver');
if (!semver.satisfies(process.versions.node, '>=4.0.0 <5.0.0')) {
    throw new Error('node version should be greater than or equal to v4.0.0 and less than v5.0.0 is required to run this application. detected node version: ' + process.versions.node);
}
```
App 1: node v8
```
var semver = require('semver');
if (!semver.satisfies(process.versions.node, '>=8.0.0')) {
    throw new Error(`node v8.0.0 or greater is required to run this application. detected node version:  ${process.versions.node}`);
}
```
After `pm2 update`, App1 does not work in cluster_mode.

Is this an issue or by design?
