### ISSUE TITLE
PM2 List Doesn't Show Processes

### ISSUE THREAD

**Issue by JimTheMan** [Unitech/pm2#3020]
**What's going wrong?**

**How could we reproduce this issue?**

First I run this:
sudo pm2 start game-of-ninja-server.js -- -p

Then:
pm2 list

shows nothing. :(

## Supporting information

```
PM2 version: `pm2 -v`
2.5.0

Node version: `node -v`
6.10.1

Windows? Mac? Linux?
Linux
"Debian GNU/Linux"
"Version 8 (jessie)"
```

**Comment by vmarchaud** [comment]
because you launched pm2 under root, you should have them if you run `sudo pm2 list`
