### ISSUE TITLE
Can I get resource usage information like pm2 monit shows?

### ISSUE THREAD

**Issue by oscchun** [Unitech/pm2#3021]
I really thank you for support great solution to manage nodes.

I wanna show system resource usage information on web like "pm2 monit" shows.
Can I get realtime information stream with pm2 API or another way?

Thank you.

**Comment by dpjayasekara** [comment]
I need this too. +1

**Comment by vmarchaud** [comment]
we've done [keymetrics.io](keymetrics.io) for that (and it help us to get money to keep maintaining PM2, however you can still use the PM2 API and do a solution alone)
