### ISSUE TITLE
pm2 high memory used.

### ISSUE THREAD

**Issue by superbogy** [Unitech/pm2#3022]
I have 4 machine on line， onceI found one of cluster pm2 used high memory。
```
 PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND

 9981 root      20   0 1334736 367984   5780 S   0.0  9.5 100:28.09 PM2 v2.5.0: God
```
Some times 15% memory was eat by pm2 and never release, It was terrible.😯

**Comment by vmarchaud** [comment]
Please use the issue template and fill the information relative to your OS, PM2 and nodejs version.
