### ISSUE TITLE
pm2-deploy greedily matching and removing branch name contents with slashes

### ISSUE THREAD

**Issue by c0bra** [Unitech/pm2#3023]
**What's going wrong?**

PM2 seems to be greedily matching slashes in a deploy config's `ref` spec and removing them.

Example: my branch is `build/stable` so I make my `ref` spec `origin/build/stable`. When I attempt to do a deploy setup, I get this error `Remote branch stable not found in upstream origin`.

To confirm, I made the `ref` spec `origin/foo/bar/biz/bar/asdfasdfasd` and I get `Remote branch asdfasdfasd not found in upstream origin`

**How could we reproduce this issue?**

Create a branch that has a slash in the name and try to deploy it.

## Supporting information

```
PM2 version: 2.5.0
Node version: 6.9.1
CentOS 6
```

**Comment by vmarchaud** [comment]
You should open an issue over this repo : https://github.com/Unitech/pm2-deploy
