### ISSUE TITLE
Load balancer layer 7 (based on host)

### ISSUE THREAD

**Issue by alexandernst** [Unitech/pm2#3024]
It would be nice if PM2 could listen on a single port and proxy/redirect all requests based on their domain.

Use case:

I have 3 different apps. Each one of them replies to requests on different domains.

    app1.js  --> "I'm www.app1.com"
    app2.js  --> "I'm www.app2.com"
    app3.js  --> "I'm www.app3.com"

Since I have NGINX in my server, I can't expose Node/Express, so I must use NGINX reverse proxy. This leads me to having to keep track at which internal port each app is listening:

    app1.s  --> NGINX reverse proxy to 20001
    app2.s  --> NGINX reverse proxy to 20002
    app3.s  --> NGINX reverse proxy to 20003

My proposal:

Make apps (`app1.js`, `app2.js`, `app3.js`) use [`vhost`](https://github.com/expressjs/vhost) and make PM2 listen to a single port (let's say 54321).

This way I could do:

    app1.s  --> NGINX reverse proxy to 54321
    app2.s  --> NGINX reverse proxy to 54321
    app3.s  --> NGINX reverse proxy to 54321

And everything would still work as expected as the apps will be using `vhost`, which will prevent them from replying to requests made to domains they don't belong to.

**Comment by astenmies** [comment]
This would be great. I'm using Next.js like more and more people I guess, and I think this feature definitely makes sense with Next.js projects and what it aims to solve.

**Comment by vmarchaud** [comment]
Currently the cluster mode is implemented as a layer 4 load balancer (tcp) so we can't have strategy based on the host header (which is on the layer 7).
If i understand, in your case you want PM2 to have a custom load balancer that behave exactly like nginx but without the configuration.
 I guess that if PM2 would be able to modify on-the-fly the nginx configuration, it should work too ?

**Comment by astenmies** [comment]
@vmarchaud NGINX proxies a port (like 80) to each app's port (like 3000, 3001, 3002). 

What I am wanting to achieve is 

- having an Express.js server config like the following, 
- running only on the port 3000, accessing a specific folder based on the domain name, 
- and have pm2 take care of it.

Is this currently achievable? How? Thx.

```
// Module dependencies.
var application_root = __dirname,
    express = require( 'express' ),
    vhost = require( 'vhost' );

function createVirtualHost(domainName, dirPath) {
    return vhost(domainName, express.static( dirPath ));
}

//Create server
var app = express();

//Create the virtual hosts
var potatoHost = createVirtualHost("www.potato.com", "potato");
var tomatoHost = createVirtualHost("www.tomato.com", "tomato");

//Use the virtual hosts
app.use(potatoHost);
app.use(tomatoHost);

//Start server
var port = 3000;
app.listen( port, function() {
    console.log( 'Express server listening on port %d in %s mode', port, app.settings.env );
});
```

**Comment by vmarchaud** [comment]
@astenmies Currently not, explained why above.

**Comment by astenmies** [comment]
@vmarchaud Thanks. Pointing the "potato.com" and "tomato.com" nginx configs to the same port wouldn't do the trick?

**Comment by alexandernst** [comment]
@vmarchaud I'm not too saavy in network related questions, so I'll agree with you on that it currently can't be done. The next question is: would it be possible (and plausible) to refactor the code in such a way that it would allow doing what this request is about?

**Comment by vmarchaud** [comment]
@alexandernst Currently we do not plan to change it, but its an idea we want to implement in the future.
@astenmies None but it's simpler in your case to use directly nginx to expose your files (and in the last case you can use `pm2 serve` and then forward the nginx traffic to the port of each `pm2 serve`)
