### ISSUE TITLE
npm  pm2 process killed !

### ISSUE THREAD

**Issue by matt212** [Unitech/pm2#3025]
hi, 

when i executed
`npm install pm2@latest -g`
this is the  error which , I got 
`Killed   ..........] \ extract:graceful-fs: sill pacote concat-map@https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz extracted to /usr/lib/node_modules/.sta

any recommedations on how to resolve this issues
my node -v is v8.1.4 and npm -v is 5.0.3
`

**Comment by vmarchaud** [comment]
Not related to PM2 itself, you should checkout with npm
