### ISSUE TITLE
Deployment permission being denied

### ISSUE THREAD

**Issue by wetherallCode** [Unitech/pm2#3026]
I'm trying to deploy my app, and I created the ecosystem.json. When I run 'pm2 deploy ecosystem.json production setup' i get permission denied and the deploy fails after I enter the correct password. I have ssh keys copied to the server and I can't figure out what I'm doing wrong. I'm totally new to this.

**Comment by vmarchaud** [comment]
Could you fill the issue template with the version of PM2/NodeJS/OS you are using + the logs you are getting ?
