### ISSUE TITLE
how to automatically start pm2 when system killed it?

### ISSUE THREAD

**Issue by hbakhtiyor** [Unitech/pm2#3030]
i'm experiencing that system killed the pm2 process

**Comment by vmarchaud** [comment]
See http://pm2.keymetrics.io/docs/usage/startup/

**Comment by hbakhtiyor** [comment]
the link only for system booting

**Comment by hbakhtiyor** [comment]
how about when system killed pm2 process? the `startup` script will not start for such scenario
