### ISSUE TITLE
Unable to deploy production setup

### ISSUE THREAD

**Issue by wetherallCode** [Unitech/pm2#3031]
I'm trying to deploy my app, and I created the ecosystem.json. 
{
  /**
   * Application configuration section
   * http://pm2.keymetrics.io/docs/usage/application-declaration/
   */
  apps : [

    {
      name      : "app",
      script    : "app.js",
      env_production : {
        NODE_ENV: "production"
      }
    }
  ],

  /**
   * Deployment section
   * http://pm2.keymetrics.io/docs/usage/deployment/
   */
  deploy : {
    production : {
      user : "deploy",
      host : "67.207.86.124",
      ref  : "origin/master",
      repo : "https://431c6f99c86179cf3a4907ea8e66fd968f41705d@github.com/wetherallCode/node-example.git",
      path : "~/node-example",
      "post-deploy" : "nvm install && npm install --production && /home/deploy/.nvm/versions/node/v8.1.3/bin/pm2 startOrRestart ecosystem.json --env production"
    }
  }
}

When I run 'pm2 deploy ecosystem.json production setup' from the command line, I get 

> --> Deploying to production environment
--> on host 67.207.86.124
  ○ hook pre-setup
deploy@67.207.86.124's password: 
mkdir: cannot create directory ‘/Users’: Permission denied
mkdir: cannot create directory ‘/Users’: Permission denied
mkdir: cannot create directory ‘/Users’: Permission denied

  

> setup paths failed
> 
> Deploy failed

I have ssh keys copied to the server and I can't figure out what I'm doing wrong. I'm totally new to this.

**How could we reproduce this issue?**

## Supporting information

```
PM2 version: `2.5.0`
Node version: `8.1.3`
macOS 10.12.5
```

**Comment by Unitech** [comment]
Look like the user "deploy" does not have access to the /Users path.
Btw you should put the absolute path instead of relative (path : "~/node-example",)

**Comment by wetherallCode** [comment]
How do i give deploy that access?
