### ISSUE TITLE
PM2 generated logrotate config matches already rotated files, too

### ISSUE THREAD

**Issue by CafeLungo** [Unitech/pm2#3033]
**What's going wrong?**
When running `pm2 logrotate`, the logrotate configuration it creates matches all files within the pm2 log directory, as in `/root/.pm2/logs/*`, instead of `/root/.pm2/logs/*.log`

**How could we reproduce this issue?**
As a user:
```
user@ip-1-1-1-1:~$ pm2 logrotate
user@ip-1-1-1-1:~$ cat /etc/logrotate.d/pm2-user
/home/user/.pm2/pm2.log /home/user/.pm2/logs/* {
        rotate 12
        weekly
        missingok
        notifempty
        compress
        delaycompress
        copytruncate
        create 0640 user user
}
```
The logrotate config, over time, ends up producing files with extensions such as the following examples:
```
app-out.log.3.gz.1.1.1.1.1.1.1.1
app-out.log.2.gz.2.gz.2.gz.4.gz
app-out.log.2.gz.2.gz.1.1.1.1.2.gz
```
This happens because the match pattern is wrong in the logrotate config. It ends up matching all the files, even the already rotated files. It should only match *.log, I believe.

## Supporting information

```
PM2 version: `pm2 -v`
2.5.0
Node version: `node -v`
v4.8.4
Windows? Mac? Linux?
Ubuntu 16.04.2
```

Let me know if you would like more information about anything.

**Comment by vmarchaud** [comment]
Fixed via https://github.com/Unitech/pm2/commit/211c4714d61b62700f09314bed271fbf70b5df28
You might have an old generated config file
