### ISSUE TITLE
Cannot start apps via node scripts (process file) on windows

### ISSUE THREAD

**Issue by TheMeteoRain** [Unitech/pm2#3034]
PM2 version: 2.5.0
Node version: 8.1.4 (also tried with LTS)
Platform: Windows

Hello,

It seems like you cannot start your applications with this kind of process file:
`module.exports = {
apps: [{
      script: "npm",
      name: "name",
      cwd: "./api",
      args: "run start"
 } ]};
`
However this works just fine on macOS

The errors I get looks like this.
![image](https://user-images.githubusercontent.com/14369871/28337659-0c46955e-6c0f-11e7-94f4-8235168e0d9f.png)

![image](https://user-images.githubusercontent.com/14369871/28337702-29a88134-6c0f-11e7-814d-cef60712bc7c.png)

But this works:
`module.exports = {
  apps: [
    {
      name: "name",
      script: "./api/app.js"
    }
  ]
};
`
This one I don't wan't to use, because then I would have to use pm2 environment variables, 
which I don't want to.

When I try to run individually with "npm start" or "node app.js". Everything works just fine. 

Thanks in advance!

EDIT: Just double checked, and yes the first process file works just fine on macOS.

**Comment by vmarchaud** [comment]
Does your app need babel to run (if yes please check [this doc](http://pm2.keymetrics.io/docs/tutorials/using-transpilers-with-pm2)) ?

**Comment by TheMeteoRain** [comment]
No it does not. It uses Typescript, but it is not the problem here, that compiles it to es5. Neither would be Babel, if it already works on mac? App works just fine on it's own. It just does not seem to work on windows with "cwd: ./../.." and "script: npm"

**Comment by TheMeteoRain** [comment]
bump

**Comment by Keramet** [comment]
Is the problem solved already? (I have the same one)

**Comment by TheMeteoRain** [comment]
No, they don't respond. It is still happening.

**Comment by antonvasilenko** [comment]
Still happening for me. Is there any solution found so far?

**Comment by TheMeteoRain** [comment]
No progress.
