### ISSUE TITLE
concurrent_actions is hardcoded to 2 on node >= 4

### ISSUE THREAD

**Issue by shaharmor** [Unitech/pm2#3036]
## What's going wrong?
Even after setting `PM2_CONCURRENT_ACTIONS` to a higher value, its being overridden to 2 here: https://github.com/Unitech/pm2/blob/fe4d600b0a9a9c1474b5154bf766471cc48e4b47/constants.js#L77

## How could we reproduce this issue?
Try to set `PM2_CONCURRENT_ACTIONS` to a higher value than 2

## Supporting information

pm2 2.4.6

**Comment by Unitech** [comment]
on pm2 2.6 there is a --parallel option

https://github.com/Unitech/pm2/commit/74fd7743fcb3fb812e6d05889128c365338630a7

**Comment by shaharmor** [comment]
Can it be set in the process.json file?

**Comment by shaharmor** [comment]
@Unitech ^ ?

**Comment by vmarchaud** [comment]
Could you try to set `parallel: 4` inside your process file ?

**Comment by Unitech** [comment]
Fixed.

Changelog: [2.9.0 CHANGELOG](https://github.com/Unitech/pm2/blob/master/CHANGELOG.md#290)
Introduced in version: 2.9.0

Update procedure:

```bash
npm install pm2 -g
pm2 update
```
