### ISSUE TITLE
Connection refused when talking to server locally

### ISSUE THREAD

**Issue by DavidHe1127** [Unitech/pm2#3042]
Run `pm2 start ecosystem.config.js` to spin up the server.

Try to send a `GET` by using `curl` to the server running locally and get the `connection refused` error.
From the log I can see app is running but I cannot talk to server.

See my `ecosystem.config.js` below

```javascript
module.exports = {
  apps: [
    {
      name: 'Blog API',
      script: './index.js',
      instances: 0,
      cwd: '.',
      'exec_mode': 'cluster',
      watch: false
    }
  ]
};
```

Any idea?

**Comment by vmarchaud** [comment]
Check your logs inside `~/.pm2/pm2.log` and `~/.pm2/logs`

**Comment by DavidHe1127** [comment]
Thanks @vmarchaud 

Logs show the error below

```
Error: Cannot find module '/Users/David/.config/yarn/global/node_modules/pm2/lib/ProcessContainerFork.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
module.js:471
    throw err;
```

and get it resolved by removing `.pm2` folder. But I have no idea why?

Can you clarify on this?

Thanks

**Comment by DavidHe1127** [comment]
Also question - is that recommended to install `pm2` locally and will it work properly?
