### ISSUE TITLE
Apllication get slowly when using pm2

### ISSUE THREAD

**Issue by magicalcosmos** [Unitech/pm2#3047]
My application got slowly when using pm2, I deployed my app to dev server, after two days, my test colleagues told me, my application was more and more slow when call data, I cannot find why, so I used "pm2 kill "  and then "pm2 start app.yml" again, it became normal. The below is my configuration:

```apps:
  - name : "app_server"
    script : "bin/www"
    watch : true
#   instances : 2
    exec_mode : "fork"
    env    :
      NODE_ENV: development
    env_production:
      NODE_ENV: production
    max_memory_restart : "4G"
    log_date_format : "YYYY-MM-DD HH:mm:SS"
```

Any idea for that?

**Comment by vmarchaud** [comment]
Can you try to take CPU Profile and/or Heapdump of the process ? Can't help you much without any debug information. Which node/pm2 version ? Which OS ?
