### ISSUE TITLE
Cron restarts app every minute when setInterval is used even though time was set in past.

### ISSUE THREAD

**Issue by aligajani** [Unitech/pm2#3048]

**Comment by vmarchaud** [comment]
Please fill the template

**Comment by aligajani** [comment]
@vmarchaud  What template?

**Comment by aligajani** [comment]
@vmarchaud 

## What's going wrong?

I  have a script that I need to run every 24 hours. It finishes in 1 min and has a setInterval() at the end to actually close it using node process as it doesn't shutdown by itself. This script works fine standalone. But, when I cronify it using PM2, it runs every minute, even when the time is set to 15 0 * * * . Absurd right? It should only run once every 24 hours at 12.15am but it runs every minute once it's cronified. 

## How could we reproduce this issue?

You can reproduce this issue by creating a script and setting it to shutdown manually using process.exit(0) inside a setInterval of 1 minute. Then you can cronify it to run every hour, but you will notice it will begin to run every minute. 

## Supporting information

Please run the following command (available on PM2 >= 2.6)

```
$ pm2 report
```


This reporting is not available is I am on 2.4

**Comment by aligajani** [comment]
@vmarchaud Any idea?

**Comment by vmarchaud** [comment]
The process need to be launched because all cronjob are inside processes and not inside the PM2 daemon, see https://github.com/Unitech/pm2/issues/2487

**Comment by aligajani** [comment]
@vmarchaud  Okay, not sure if I got that completely. Can you please elaborate? How do I fix it?

**Comment by aligajani** [comment]
I read your referenced issue, but mines different. I just want the cron to execute a script at a time.

**Comment by aligajani** [comment]
Okay I think it works now. Removed the setInterval() and process.exit. Wish there's a column to show pattern.
