### ISSUE TITLE
CPU usage in idle without any request?

### ISSUE THREAD

**Issue by Shadowman4205** [Unitech/pm2#3052]
Hello,
i am running docker container with pm2 
i am using keymetrics/pm2-docker-alpine:7 (not the latest one cause of this [issue](https://github.com/keymetrics/docker-pm2/issues/33) )
I have got CPU usage in idle  without using application without doing any request? 
i am using cluster mode with 4 instanses,wathcing is disabled. Any suggestion what can i check or to do?

some stats

> [ 0] website      Mem: 205 MB    CPU: 30 %  online xxx  

                                                                                                                          

>  [ 1] website      Mem: 205 MB    CPU: 13 %  online xxx

                                                                                                                                 

> [ 2] website      Mem: 218 MB    CPU: 12 %  online xxx  

                                                                                                                                

> [ 3] website      Mem: 206 MB    CPU: 30 %  online xxx

And its go like this once its go up 100% and down to 0  continuously.

**Comment by vmarchaud** [comment]
Can you try to reproduce outside of the container ? And if you succeed can you try to make a sample project that have the problem ?

**Comment by Shadowman4205** [comment]
My project based on [https://github.com/kriasoft/react-starter-kit](https://github.com/kriasoft/react-starter-kit/tree/feature/react-intl) with extra future feathers js for api (as sample).
