### ISSUE TITLE
restart app with env specific name doesnt work

### ISSUE THREAD

**Issue by broman-pl** [Unitech/pm2#3053]
I have environment specific app name defined in `ecosystem.config.js` 
```
    apps : [

        {
            name      : 'App Name',
            script    : 'lib/app.js',
            env: {
                name      : 'App Name DEV',
                NODE_ENV: 'development'
            },
            env_production : {
                name      : 'App Name PRD',
                NODE_ENV: 'production'
            }
        }
    ]
```

and it is working for starting app, correct name is used on list
but when I try to restart it I always getting new instance 
in debug it look like general name is used to check but then environment name is used to start 

```
[PM2][WARN] Applications App Name not running, starting...
[PM2] App [App Name DEV] launched (1 instances)
```

**Comment by vmarchaud** [comment]
You need to restart using `pm2 restart ecosystem.config.js` when you define different name for the same application depending on the env

**Comment by broman-pl** [comment]
As you may see in my description in debug output there is name defined in `ecosystem.config.js` so it is clear indication that I'm using `ecosystem.config.js` for `restart` or `startOrRestart` commands. And I still have this issue
