### ISSUE TITLE
pm2 describe API returns abnormal value

### ISSUE THREAD

**Issue by oscchun** [Unitech/pm2#3057]
hello, 

I'm using PM2 describe API for collecting system resource usage used by node processes.

I'm using mesos&marathon for infra environment and I allocate cpu : 0.2 for starting my application with marathon.

I recieved abnormal values using pm2 api just after loading my nodejs app in marathon application(docker).

I used cluster mode command to start process and I recieved values below.

monit { memory : 58167296, cpu : 1580}

is it possible?

**Comment by vmarchaud** [comment]
CPU consumption is hard to measure accurately, @soyuka made [pidusage](https://github.com/soyuka/pidusage) but it's not perfect. 
Feel free to open a PR on pidusage if you find a way to retrieve correct value in your case
