### ISSUE TITLE
pm2-docker PM2 logs should be optional or disabled

### ISSUE THREAD

**Issue by t3h2mas** [Unitech/pm2#3058]
## What's going wrong?
`pm2-docker` logs to the `~/.pm2/logs/` directory using the files `app-error-0.log` and `app-out-0.log` 
Inside of a Docker container, it makes sense to leave log drivers, and more importantly log rotation to the Docker engine.

This means that even if someone uses log rotation at the docker level, PM2 log management would have to be configured within the container

**Suggested fix:** 
Either default to 
`--output NULL`
`--error NULL`

Or support the arguments in `pm2-docker`, and make a note somewhere in documentation

## How could we reproduce this issue?
Run a docker container using `pm2-docker`. Be sure your app logs to stdout. 
Exec into the running container: `docker exec -it <CONTAINERNAME> bash`
Change into the logs directory: `cd ~/.pm2/logs`
Check file size: `du -h *`

Seeing anything but 0's there means that PM2 will continue to use up disk space from within the container

**Comment by vmarchaud** [comment]
Should be modified indeed

**Comment by Unitech** [comment]
that make sense, thanks for the feedback, I've just updated the command

**Comment by GaneshSinghPapola** [comment]
@t3h2mas are you using Linux ?
cause in my case no log file are creating by pm2-docker command..
but if i do pm2-start app.js then log files are creating in given path (im using windows 10)

**Comment by Unitech** [comment]
Fixed on recently published pm2 (2.7.0):

```bash
$ npm install pm2@latest -g
$ pm2 update
```

Now pm2-docker does not write logs by default

Let me know if there is any issue
