### ISSUE TITLE
How does PM2 determine process status?

### ISSUE THREAD

**Issue by takehilo** [Unitech/pm2#3059]
## What's going wrong?
I'd like to know how PM2 determines a process is `online` or `errored`. I'd appreciate it if you'd point at the module that does it.

**Comment by vmarchaud** [comment]
`online`: the process is started
`stopped`: the process isn't launched but the state of the application is still saved
`errored`: the process is `stopped` (it has been launched 16 times and each time it fail to stay alive for more than 500ms)

There isn't any module that compute this state, it's almost every where in the code of the daemon

**Comment by takehilo** [comment]
@vmarchaud Thank you.
