### ISSUE TITLE
Sending custom message to all clusters ?

### ISSUE THREAD

**Issue by ghost** [Unitech/pm2#306]
Would it be possible to send custom message to all clusters via PM2? For example I want to have maintenance mode for my service. Because it is critical that the service will not interrupt any running requests (because some of them may be money transactions) I need to be able to tell the service sort of "gracefulPause", so it will stop accepting connections and wait for all other connections to finish. I can implement this for a single process but when PM2 is in charge of clusters it would be very helpful if I could pass custom messages to the clusters via PM2. And in the clusters I would handle the message just like I handle the the "shutdown" message for graceful restart. For example `pm2 signal all "EnterMaintenance"`.

Additionally it would be nice if the clusters can send feedback to PM2 and notify it of their status, so when I list the processes they will display with custom status like "maintenance" and then maybe I could query the status like `pm2 status myprocess` and I will get "maintenance" and I can use this for automation from the command line.

**Comment by cage1618** [comment]
How can I send custom message to all clusters???

**Comment by cage1618** [comment]
How can I send custom message to all clusters in my code and I can use process.on('message') listen the event?

process.on('message', function(data) {
  // the data is my custom data send by the other code
})
