### ISSUE TITLE
PM2 does not work with Raven

### ISSUE THREAD

**Issue by niftylettuce** [Unitech/pm2#3063]
Not sure how to resolve this - I think it is the usage of `domain` in the context of Raven.

See <https://github.com/getsentry/raven-node/issues/355>.

Basically `raven` (a package that supports logging for [Sentry.io](https://sentry.io)) provides a middleware for Express apps ([as documented here](https://docs.sentry.io/clients/node/integrations/express/)).  There is a middleware for handling requests and errors (so metadata like logged in user ID's, browser user-agent, IP address of user, and email address of user get sent along with logs).

The script below works properly (it sends along the user's ID to Sentry for logging).  However as soon as I run the script with `pm2`, e.g. `pm2 start app.js -i 0` (with clustering enabled), the script stops working.  I think this is due to `domain` and clustering somehow, but I've not gone too deep here just yet.  I was hoping someone here could take a look at the `raven-node` `lib/client.js` file available at <https://github.com/getsentry/raven-node/blob/master/lib/client.js#L449-L459> and help debug this issue:.

```js
var app = require('express')();
var Raven = require('raven');

// TODO: REPLACE WITH A DSN TOKEN FROM <https://sentry.io>
var DSN = '******';

// Must configure Raven before doing anything else with it
Raven.config(DSN).install();

// The request handler must be the first middleware on the app
app.use(Raven.requestHandler());

// fake a user logged in
app.use(function(req, res, next) {
  req.user = { id: '123456' };
  next();
});

app.get('/', function mainHandler(req, res) {
    throw new Error('Broke!');
});

// The error handler must be before any other error middleware
app.use(Raven.errorHandler());

// Optional fallthrough error handler
app.use(function onError(err, req, res, next) {
    // The error id is attached to `res.sentry` to be returned
    // and optionally displayed to the user for support.
    res.statusCode = 500;
    res.end(res.sentry + '\n');
});

app.listen(3000);
```

**Comment by niftylettuce** [comment]
Also note that "working" (as mentioned above) means that Sentry receives the user's ID parameter.  If you run `node app.js` and then go to http://localhost:3000 - it works.  However `pm2 start app.js -i 0` does not send this user ID to Sentry.

**Comment by niftylettuce** [comment]
Furthermore, DSN is a token available through a free account at https://sentry.io.

**Comment by vmarchaud** [comment]
Does it works with `pm2 start app.js` (fork mode) ?

**Comment by niftylettuce** [comment]
Yes it does work @vmarchaud

**Comment by vmarchaud** [comment]
Maybe try with the [vanilla nodejs implementation](https://nodejs.org/dist/latest-v7.x/docs/api/cluster.html#cluster_cluster) ?

**Comment by mbrochh** [comment]
I have the same problem. However, even fork-mode does not work for me.

I have tried pretty much everything (see https://forum.sentry.io/t/sourcemaps-for-node-app-behind-pm2-not-working/9536 and https://twitter.com/mbrochh/status/1252778718478491649?s=20)

Really no idea what else to try, and I can't figure out if this is a PM2 issue or a sentry issue.

**Comment by niftylettuce** [comment]
Hey everyone, you should NOT be using Raven.  You should be using https://cabinjs.com instead.  Sentry and Raven have some very core security related issues, and I built Cabin out of frustration with it and services like Timber, Airbrake, etc.
