### ISSUE TITLE
[QUESTION] Fork vs cluster mode (esp. when using Docker)

### ISSUE THREAD

**Issue by Kitanotori** [Unitech/pm2#3064]
Does cluster mode have overhead compared to fork mode (e.g. 2 fork instances VS 1 cluster instance with 2 app instances), and if so, how much? 

I deploy Node.js apps in [ECS](https://aws.amazon.com/ecs/) clusters, for example, 2 t2.small instances, 1 container per instance. I understand that the recommended approach with Docker is to have one process per container. With >=2 containers, I can achieve zero downtime redeploys, so I don't need pm2's reload. Does it make any sense at all to run pm2 in cluster mode when deploying apps into Docker container clusters? 

Is there any situation in which running pm2 in cluster mode is more beneficial than running multiple Docker containers with fork mode pm2 instances load balanced by AWS Application Load Balancer?

**Comment by clarkeash** [comment]
This would be useful to know @Unitech
