### ISSUE TITLE
Using wine as an interpreter

### ISSUE THREAD

**Issue by majimboo** [Unitech/pm2#3065]
I'm trying to run a windows service on ubuntu using wine. Running the service directly by executing `wine Service.exe` works perfectly.

But executing it with PM2 gives me the error `bind failed with error 10048` (address/port taken) and some `page fault` that just keeps restarting.

Here are the commands with PM2 I've tried:

    pm2 start Service.exe -n service1 --interpreter wine
    pm2 start wine -n service1 -- Service.exe

This service is dependent on a config file that should be found within the same folder. Just a thought that it might be a `current working directory` issue.

But I can't seem to find out how to set the `cwd` with pm2. (other than using a json file)

**Comment by vmarchaud** [comment]
`pm2 start Service.exe -n service1 --interpreter wine --cwd <path>` ?
