### ISSUE TITLE
I'm running my nodejs & Expressjs application (Mongodb,redisDB) on Amazon Linux AMI @ec2 my start file is app.js and npm start running using (npm start) but when running pm2 start app.js after sudo npm install pm2 -g my application  is not running.

### ISSUE THREAD

**Issue by rkdaredevil** [Unitech/pm2#3068]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/Unitech/pm2/search?type=Issues) before creating one.

## Supporting information

Please run the following command (available on PM2 >= 2.6)

```
$ pm2 report
```

**Comment by vmarchaud** [comment]
Please fill the template with all informations
