### ISSUE TITLE
Error in babel node when running with pm2 ecosystem.config.js

### ISSUE THREAD

**Issue by ralphchristianeclipse** [Unitech/pm2#3071]
## What's going wrong?
![image](https://user-images.githubusercontent.com/25447231/28997431-373d9096-7a47-11e7-904f-9ef5392b140d.png)

What i'm trying to do is use pm2 just like nodemon --exec babel-node but instead of using the package.json script
I tried to use the ecosystem.config.js to manage all the env files and stuff

What i've encountered is that the path of the babel-node isn't detected well or my pathing for the babel-node inspector is wrong?

## How could we reproduce this issue?
Use this ecosystem.config.js

```javascript
{
      name: 'API',
      script: 'src/',
      watch: true,
      ignore_watch: ["node_modules"],
      interpreter: "./node_modules/.bin/babel-node",
      source_map_support: true,
      //instances: 0,
      //exec_mode: "cluster",
      env: {
        HOST: '0.0.0.0',
        PORT: 8000,
      
        DB_HOST: 'localhost',
        DB_NAME: 'trybal',
        DB_USER: 'root',
        DB_PASS: '',
        NODE_ENV: 'development'
      },
      env_production: {
        NODE_ENV: 'production'
      }
    }
```

**Comment by vmarchaud** [comment]
Did you read http://pm2.keymetrics.io/docs/tutorials/using-transpilers-with-pm2 ?

**Comment by ralphchristianeclipse** [comment]
@vmarchaud yes i've read it also tried the babel-register but its not working

**Comment by Unitech** [comment]
https://github.com/Unitech/pm2/issues/3043

**Comment by dimaninc** [comment]
any solution here?

**Comment by dimaninc** [comment]
https://github.com/Unitech/pm2/issues/1167
