### ISSUE TITLE
[question] Monitor processes with pm2-docker ?

### ISSUE THREAD

**Issue by robinparisi** [Unitech/pm2#3072]
Hi,

I've recently started to use pm2-docker and can’t figure out how to monitor pm2 processes inside a docker container.

Indeed, commands such as “status” or “monit” don’t seem to be available with pm2-docker.

Is there a way to monitor pm2 processes within a container (at least for displaying basic information as status does) ?

Thanks in advance for your response.

**Comment by vmarchaud** [comment]
the `pm2-docker` binary is only used to launch all applications, after that you need to use the `pm2` binary : `docker exec -it <container-id> pm2 monit`
