### ISSUE TITLE
How to allow node scripts to open port 80 and 433 without running PM2 as root

### ISSUE THREAD

**Issue by domingosl** [Unitech/pm2#3075]
Looking in this repo I found so many posts about the fact that if you need to open port 80 or 433 from a node script running using PM2 you need to launch PM2 as root, and this means that your node script will be also running as root. Isn't this potentially dangerous? if somebody hacks node they will be inside the system as root. I will like to run PM2 as a restricted user but with permission to open lower ports. This seems to be impossible on Ubuntu at least, you can allow certain process but not users to open lower ports, which makes me think that my approach is wrong.

**Comment by soyuka** [comment]
Usually you put nginx in front with a proxy on your nodejs app. More information here: http://pm2.keymetrics.io/docs/tutorials/pm2-nginx-production-setup

You could hack around with iptables to get what you want but I won't recommend it without knowing what you're doing.

**Comment by vmarchaud** [comment]
Relevant : http://pm2.keymetrics.io/docs/usage/specifics/#listening-on-port-80-w-o-root
Also ```sudo setcap CAP_NET_BIND_SERVICE=+eip `which node` ``` ([explaination](https://gist.github.com/firstdoit/6389682))
