### ISSUE TITLE
deploy production asks me to commit but my master/origin are up to date

### ISSUE THREAD

**Issue by wetherallCode** [Unitech/pm2#3080]
When I run deploy production it asks me to commit or stash my changes before deploying but my master/origin are up to date. How do I resolve this issue?

**Comment by brokenpeace** [comment]
My guess on the vagueness is that your.gitignore is not Seth property? Do a
got status and what it showing as modified

**Comment by wetherallCode** [comment]
That got it, thanks!

**Comment by brokenpeace** [comment]
Can you pease post.the more specific fix? What was it that you missed? Just want to ensure not something that could be an issue.
