### ISSUE TITLE
Leave process.sdtout/process.stderr alone?

### ISSUE THREAD

**Issue by juanjoLenero** [Unitech/pm2#3086]
Is there a setting or way to instruct pm2 to only output logs to stdout? Or leave logs alone entirely?

Our current app logs to stdout/stderr in all environments. Our production systems are already configured to handle that output and send it to our log aggregation service.

We have no need for log files, nor do we want extra strings/keys prepended to our app logs.

Using a process file like this one.
```js
/**
 * Application configuration section
 * http://pm2.keymetrics.io/docs/usage/application-declaration/
 */
module.exports = {
    apps : [
        {
            name: 'my-app',
            script: './src/server.js',
            instances: 0,
            exec_mode: 'cluster',
            source_map_support: false,
            watch: true,
            vizion: false,
            out_file: '/dev/stdout',
            error_file: '/dev/stderr'
        }
    ]
};
```

And running `pm2 start process.config.js --no-daemon` we can see the logs for all instances in the output, but they are prefixed by appname/process number.

If we let pm2 daemonize the processes with `pm2 start process.config.js` and then try to run `pm2 logs --raw` we get an error:
```
events.js:182
      throw er; // Unhandled 'error' event
      ^
Error: ENXIO: no such device or address, read
```

`pm2 logs --raw` with one instance works, and the ouput is not prefixed, just like we want it to be. Is there a solution to this problem?

**Comment by ninja-** [comment]
same here - my app does the logging by itself and using pm2 kinda duplicates the logs.
What I would recommend is to modify pm2's logrotate configuration
(generated by $ pm2 logrotate)
to throw away logs daily, so you can still use pm2 logs for debugging

**Comment by Unitech** [comment]
Try `pm2-runtime process.config.js`
