### ISSUE TITLE
How to start same binary file multiple times with different args?

### ISSUE THREAD

**Issue by xieranmaya** [Unitech/pm2#3089]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/Unitech/pm2/search?type=Issues) before creating one.

## What's going wrong?
I want to use PM2 to manage a binary executable file(not a *.js file), and it can be executed multiple times and send different args for different purpose, but when I started it for the second time, PM2 overwrote the previous running process.
It will run js file by this logic too

## How could we reproduce this issue?
pm2 start a.js -- a
pm2 start a.js -- b
With js file, I can change the source code of it and somehow circumvent this.
But with a binary file I can't do anything with it, is there a way to start a binary file for multiple times?

## Supporting information

Please run the following command (available on PM2 >= 2.6)

```
$ pm2 report
```

**Comment by Unitech** [comment]
Give different names to the binary when starting them via the option --name, also you may need to use --force

**Comment by xieranmaya** [comment]
Thank you very much, solves a big problem for me!
