### ISSUE TITLE
No logs with pm2-docker in windows

### ISSUE THREAD

**Issue by GaneshSinghPapola** [Unitech/pm2#3091]
## No logs with pm2-docker in windows

I tried to run application through docker with `pm2-docker process.json` command everything is running except path/error.log or path/out.log files are not being generated in specified location in process file.
i am using windows machine.

**Comment by vmarchaud** [comment]
Because by default `pm2-docker` ouput logs into `stdout` and `stderr`, thats the standard behavior with docker

**Comment by GaneshSinghPapola** [comment]
thanx @vmarchaud  so there is no reason to put error_file and out_file in process.json, right?

**Comment by vmarchaud** [comment]
Indeed when using docker there is no point to put it

**Comment by GaneshSinghPapola** [comment]
@vmarchaud  thanx for the info
