### ISSUE TITLE
pm2 start app.js --container

### ISSUE THREAD

**Issue by Unitech** [Unitech/pm2#3094]
Wizard to start a Node.js application inside a container and easily deploy a production container to a registry.

## Development mode

The development mode allows you to easily run an application inside a container, while restarting the application in case of file changes in the host machine.

Wrapping your app inside a container is as easy as:

```bash
$ pm2 start app.js --container
```

It will check if a local Dockerfile is present, if not pm2 will generates a Dockerfile with best practices for developing an application inside a container:

1/ It copies the local package.json and run npm install inside the container
1/ Host sources are exposed to the container via VOLUME
1/ pm2-dev is used to auto restart the application on file changes in the host!

## Production / Distribution

The distribution mode package the whole application sources inside a container image, ready to be pushed into your favorite registry.

Switching to distribution mode is simple:

```bash
$ pm2 start app.js --container --dist --image-name <image-name>
````

When switching to distribution mode, pm2 will edit the local Dockerfile to add some production stuff:
1/ COPY the whole source folder inside the target container
1/ Replace the CMD from pm2-dev to pm2 in production mode

## Trial

```bash
$ npm install Unitech/pm2#pm2-start-container -g
$ pm2 update
$ pm2 start app.js --container
```

*This is a v2 of the [first spec](https://github.com/Unitech/pm2/issues/2320)*

**Comment by simonepri** [comment]
It looks amazing 👍 
Should we document somewhere what we mean by `best practices`?

**Comment by Unitech** [comment]
beta release

```
$ pm2 start app.js --container
$ pm2 start app.js --container --dist --image-name keymetrics/something
```
