### ISSUE TITLE
pm2 list---> no <id> filed

### ISSUE THREAD

**Issue by wirechen** [Unitech/pm2#3095]
## pm2 list

Name         │ mode    │ status  │ ↺ │ cpu │ memory    │
├──────────────┼─────────┼─────────┼───┼─────┼───────────┤
│ apiserver193 │ cluster │ stopped │ 1 │ 0%  │ 0 B       │
│ im           │ fork    │ online  │ 2 │ 0%  │ 82.6 MB   │
│ test         │ cluster │ online  │ 0 │ 0%  │ 28.6 MB   │
│ test         │ cluster │ online  │ 0 │ 0%  │ 26.5 MB   │
│ test         │ cluster │ online  │ 0 │ 0%  │ 27.0 MB   │
│ test         │ cluster │ online  │ 0 │ 0%  │ 28.0 MB   │
└──────────────┴─────────┴─────────┴───┴─────┴────────

There is no id field, Why? 
version 2.6.1

**Comment by Unitech** [comment]
Increase the size of the terminal and do a pm2 ls again.
This is a shrank version of the pm2 ls when the terminal is < 80 cols
