### ISSUE TITLE
Why did my fork process showed stopped ?

### ISSUE THREAD

**Issue by qiulang** [Unitech/pm2#3098]
I already searched on the [issue tracker](https://github.com/Unitech/pm2/search?type=Issues) before creating one.

## What's going wrong?
I started my express using the simplest process file, just gave it a name:

```
{
    "apps": [{
            "name": "cs-cluster",
            "script": "./bin/www",
            "exec_mode" : "cluster"
    }]
}
```

But I was confused with the result, why my 'www' showed stopped while cs-cluster showed online?
I gave my 'www' the name 'cs-cluster', so wasn't the app 'cs-cluster' just the 'www'?

```
App name   │ id │ mode    │ pid   │ status  │ restart │ uptime │ cpu │ mem       │ user    │ watching
cs-cluster │ 1  │ cluster │ 47727 │ online  │ 1       │ 0s     │ 9%  │ 17.8 MB   │ qiulang │ disabled
www        │ 0  │ fork    │ 0     │ stopped │ 0       │ 0      │ 0%  │ 0 B       │ qiulang │ disabled 
```

## How could we reproduce this issue?
Just start a simple express app using cluster mode with a name

## Supporting information

Please run the following command (available on PM2 >= 2.6)

```
$ pm2 report
```

**Comment by vmarchaud** [comment]
Logically you should have all the logs with `pm2 logs PM2 --lines 100`, i don't understand what you meant with the renaming of your app, could you try to explain it more clearly please ?

**Comment by qiulang** [comment]
I can't reproduce the issue, so I will close it, sorry. But I had some idea what happened here.

My process.json  didn't have "instances" :0. It seems that without it pm2 will only start 1 process. 
By renaming my app I mean if I didn't give it a name, ("name": "cs-cluster"), pm2 will just app name 'www', which it was not identifiable.  I guess I probably started app named "cs-cluster" first then started it somewhere else called "www". But the at the second time the port was already used by "cs-cluster" so it failed to start.
