### ISSUE TITLE
PM2_GRACEFUL_LISTEN_TIMEOUT does not work on a per app base

### ISSUE THREAD

**Issue by comtaler** [Unitech/pm2#3099]
If pm2 is not running, everything works as expected.

But when pm2 is already started without the environment variable `PM2_GRACEFUL_LISTEN_TIMEOUT` and when I am trying start a new app([https://github.com/Unitech/pm2/tree/master/examples/wait-ready](https://github.com/Unitech/pm2/tree/master/examples/wait-ready)) using:
`PM2_GRACEFUL_LISTEN_TIMEOUT=8000 pm2 start app.js --wait-ready`

It only waits for 3 seconds, which is the default timeout. However, if I start the app using the json config file, it works fine.

**Comment by Unitech** [comment]
Use `--listen-timeout` instead:

```bash
$ pm2 start app.js --wait-ready --listen-timeout=8000
```

**Comment by Unitech** [comment]
updated http://pm2.keymetrics.io/docs/usage/signals-clean-restart/
