### ISSUE TITLE
pm2-dev creating and writing to .pm2 and .pm2-dev in docker volume making infinite restarts

### ISSUE THREAD

**Issue by jonathanasquier** [Unitech/pm2#3101]
Hi,
I'm trying to make a very basic development container with a volume on my project folder, and pm2-dev watching and restarting my app on change.
Dockerfile (volume is ./:/root)
```
FROM node:latest
RUN npm install pm2 -g
CMD ["pm2-dev", "root/server.js"]
```
the .pm2 and .pm2-dev folders are created and written to inside the volume and probably responsible for the infinite restarts. (ignore path won't work)

Am I missing something? I'm pretty sure there is an obvious workaround!
Thanks

**Comment by vmarchaud** [comment]
You should use `pm2-docker` inside your container : http://pm2.keymetrics.io/docs/usage/docker-pm2-nodejs/

**Comment by jonathanasquier** [comment]
I'm reading this from the docs
```
Replacing pm2-docker with pm2-dev will enable the watch and restart features. This is quite interesting in a development container when the host files are exposed to the container as a VOLUME.
```
so pm2-dev should be the way to in a dev container? it seems pm2-docker doesn't watch much...

**Comment by jonathanasquier** [comment]
Added `WORKDIR /root`
.pm2 and .pm2-dev still created so there wheren't the issue
works like a charm
```
FROM node:latest
RUN npm install pm2 -g
WORKDIR /root
CMD ["pm2-dev", "root/server.js"]
```
