### ISSUE TITLE
[BUG] combine_logs/merge_logs hasn't avoid suffix of pid file!

### ISSUE THREAD

**Issue by kanreisa** [Unitech/pm2#3102]
## What's going wrong?
`combine_logs`/`merge_logs` hasn't avoid suffix of pid file.

### **this is problem**
https://github.com/Unitech/pm2/blob/fd1f52d5e2413a5ad5ac7a52bbe9b5a14cc88732/lib/God.js#L101-L110

## How could we reproduce this issue?
http://pm2.keymetrics.io/docs/usage/application-declaration/#log-files
> if set to true, avoid to suffix logs/pid file with the process id

## Supporting information

```
pm2d version         : 2.6.1
```

**Comment by kanreisa** [comment]
@vmarchaud @Unitech ping

**Comment by Unitech** [comment]
We cannot remove the suffix on pid file, because if the user start multiple processes each process will write his pid on that same file

**Comment by vmarchaud** [comment]
We have updated the documentation to reflect this, closing this issue also

**Comment by kanreisa** [comment]
...
