### ISSUE TITLE
Sad thing that 'gkt' could not be accessed...

### ISSUE THREAD

**Issue by zilong-thu** [Unitech/pm2#3106]
I am using pm2@2.6.1 and find this dependency 'gkt' in package.json:

```
"gkt": "https://tgz.pm2.io/gkt-1.0.0.tgz"
```
which always cause error while installed with yarn:

```
$ yarn add pm2 --production
```

error message:

```
yarn add v0.27.5
[1/4] Resolving packages...
error An unexpected error occurred: "https://tgz.pm2.io/gkt-1.0.0.tgz: ETIMEDOUT".
```

I understand that 'gkt' is used for statistics purpose, but it is this kind of weird private usage that introduced chaos into node modules society, isn't it?

**Comment by vmarchaud** [comment]
You could use `--ignore-optional` flag to not install optional dependency. 
As i said everytime, for us the problem is every package manager not implementing the concept of `optional` dependency correctly.
