### ISSUE TITLE
process kill command with docker

### ISSUE THREAD

**Issue by GaneshSinghPapola** [Unitech/pm2#3107]
pm2 is not showing any activity  after running  with docker
im doing CMD ["pm2-docker", "--public", "XXX", "--secret", "YYY", "process.json"] in my dockerfile
in key metrics there is showing 2 servers connected but no graphs are there?

**Comment by vmarchaud** [comment]
You should open an up a ticket on the keymetrics zendesk, issues are only used for PM2 bugs.
