### ISSUE TITLE
PM2 spawns a new God daemon with nearly every command

### ISSUE THREAD

**Issue by environi** [Unitech/pm2#3108]
Nearly ever time I run a PM2 command, a new God daemon is spawned:

    -bash-4.1$ pm2 status
    [PM2] Spawning PM2 daemon with pm2_home=/user/me/.pm2
    [PM2] PM2 Successfully daemonized
    ┌──────┬──────┬────────┬───┬─────┬────────┐
    │ Name │ mode │ status │ ↺ │ cpu │ memory │
    └──────┴──────┴────────┴───┴─────┴────────┘
     Use `pm2 show <id|name>` to get more details about an app
    -bash-4.1$ pm2 status
    [PM2] Spawning PM2 daemon with pm2_home=/user/me/.pm2
    [PM2] PM2 Successfully daemonized
    ┌──────┬──────┬────────┬───┬─────┬────────┐
    │ Name │ mode │ status │ ↺ │ cpu │ memory │
    └──────┴──────┴────────┴───┴─────┴────────┘
     Use `pm2 show <id|name>` to get more details about an app
    -bash-4.1$ pm2 status
    [PM2] Spawning PM2 daemon with pm2_home=/user/me/.pm2
    [PM2] PM2 Successfully daemonized
    ┌──────┬──────┬────────┬───┬─────┬────────┐
    │ Name │ mode │ status │ ↺ │ cpu │ memory │
    └──────┴──────┴────────┴───┴─────┴────────┘
     Use `pm2 show <id|name>` to get more details about an app
    -bash-4.1$

But if we check for the existence of the God daemon:

    -bash-4.1$ ps aux | grep God
    me  456547  0.0  0.0 889560 24576 ?        Ssl  23:07   0:00 PM2 v2.5.0: God Daemon (/user/me/.pm2)
    me  456561  0.0  0.0 889516 24516 ?        Ssl  23:07   0:00 PM2 v2.5.0: God Daemon (/user/me/.pm2)
    me  457241  0.1  0.0 889496 24452 ?        Ssl  23:10   0:00 PM2 v2.5.0: God Daemon (/user/me/.pm2)
    me  457934  0.2  0.0 889376 24388 ?        Ssl  23:13   0:00 PM2 v2.5.0: God Daemon (/user/me/.pm2)
    me  458126  0.5  0.0 889560 24556 ?        Ssl  23:14   0:00 PM2 v2.5.0: God Daemon (/user/me/.pm2)
    me  458459  0.0  0.0 103300   908 pts/0    S+   23:15   0:00 grep God
    -bash-4.1$

I've spend over two weeks trying to find references to this, and probably over 20 hours total of actual work time trying to solve this, and nothing. I can't find any good examples of questions or issues asked anywhere with this same situation, and I also can't find any results on Google (try it) for `pm2 "Error: connect Unknown system error -116"` which appears as follows:

    -bash-4.1$ pm2 status
    events.js:160
          throw er; // Unhandled 'error' event
          ^
    
    Error: connect Unknown system error -116 /user/me/.pm2/rpc.sock
        at Object.exports._errnoException (util.js:1018:11)
        at exports._exceptionWithHostPort (util.js:1041:20)
        at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
    -bash-4.1$

Could you give me a hint as to what might be wrong? Point me in the right direction? Thanks so much in advance and sorry for all the bash copypasta, I wanted to make sure I gave as much info as possible.

**Comment by Unitech** [comment]
Could you run `pm2 report` please

**Comment by environi** [comment]
@Unitech 


    -bash-4.1$ pm2 report
    [PM2] Spawning PM2 daemon with pm2_home=/user/me/.pm2
    [PM2] PM2 Successfully daemonized
    ===============================================================================
    --- PM2 REPORT (Fri Aug 25 2017 14:41:05 GMT+0000 (GMT)) ----------------------
    ===============================================================================
    --- Daemon -------------------------------------------------
    pm2d version         : 2.6.1
    node version         : 6.11.2
    node path            : /usr/bin/pm2
    argv                 : /usr/bin/node,/usr/lib/node_modules/pm2/lib/Daemon.js
    argv0                : node
    user                 : me
    uid                  : 1435
    gid                  : 1435
    uptime               : 0min
    ===============================================================================
    --- CLI ----------------------------------------------------
    local pm2            : 2.6.1
    node version         : 6.11.2
    node path            : /usr/bin/pm2
    argv                 : /usr/bin/node,/usr/bin/pm2,report
    argv0                : node
    user                 : me
    uid                  : 1435
    gid                  : 1435
    ===============================================================================
    --- System info --------------------------------------------
    arch                 : x64
    platform             : linux
    type                 : Linux
    cpus                 : Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz
    cpus nb              : 48
    freemem              : 59803803648
    totalmem             : 67439632384
    home                 : /user/me
    ===============================================================================
    --- PM2 list -----------------------------------------------
    ┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
    │ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
    └──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
    ===============================================================================
    --- Daemon logs --------------------------------------------
    ┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
    │ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
    └──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
     Use `pm2 show <id|name>` to get more details about an app
     -bash-4.1$

**Comment by vmarchaud** [comment]
Could you run `ls -la ~/.pm2` and run the output here ?

**Comment by environi** [comment]
@vmarchaud 

    -bash-4.1$ ls -la ~/.pm2
    total 780
    drwxr-xr-x 5 me me   4096 Aug 25 14:41 .
    drwx------ 5 me me   4096 Aug 25 00:50 ..
    -rw-r--r-- 1 me me  20863 Aug 25 01:24 dump.pm2
    drwxr-xr-x 2 me me   4096 Aug 25 01:11 logs
    -rw-r--r-- 1 me me      2 Jul 15 00:59 module_conf.json
    drwxr-xr-x 2 me me   4096 Jul 15 00:59 node_modules
    drwxr-xr-x 2 me me   4096 Aug 25 01:24 pids
    -rw-r--r-- 1 me me 744956 Aug 25 14:41 pm2.log
    -rw-r--r-- 1 me me      5 Aug 25 14:41 pm2.pid
    srwxrwxr-x 1 me me      0 Aug 25 14:41 pub.sock
    srwxrwxr-x 1 me me      0 Aug 25 14:41 rpc.sock
    -rw-r--r-- 1 me me     13 Jul 15 00:59 touch
    -bash-4.1$

**Comment by environi** [comment]
@Unitech @vmarchaud I think I may have found the error, finally.

`$PM2_HOME` is by default located at `$HOME/.pm2`, and in many clusters (including our cluster) the `$HOME` directory is synced across a number of machines. When each machine spawns a God daemon, it overwrites the sockets in `$HOME/.pm2` for the daemons on the other machines, leaving all the other machines with a socket that isn't valid on that machine. So they start a new daemon, and the process continues.

This also explains why PM2 commands work when used quickly one after another. Because then the sockets don't have time to be overwritten by another machine.

I think there should be some notice about this problem when running in clusters, as it should be a problem on every cluster that syncs `$HOME`.

Thanks for your help.

**Comment by Unitech** [comment]
Ah interesting, if I see someone else having the same issue I will document this

Cheers

**Comment by jmwilkinson** [comment]
Same issue here.

**Comment by lucagervasi** [comment]
Similar issue here. I'm not syncing PM2_HOME, btw.
I'm using systemd with [this unit](https://gist.github.com/lucagervasi/dcdf0143884718a2b4b5f44ade622f74#file-pm2).
It spawns different god mode processes, making it uneasy to manage.

**Comment by liamomg** [comment]
same issue here in Windows environment. Anyone has a solution?

**Comment by Magnusri** [comment]
Same problem here. Windows env, PM2 version 3.2.8

**Comment by Magnusri** [comment]
> $ npm install pm2@3.2.4 -g

This fixed the problem!

Thank you, please tell me if you need any more info from me to fix this.

**Comment by Unitech** [comment]
Ok I think I have an idea about this issue, will fix it soon

**Comment by bcmux** [comment]
> Could you try with pm2@3.2.4 and tell me if this behavior is still reproduced?
> 
> ```
> $ npm install pm2@3.2.4 -g
> ```

Yep, this fixed the same issue for me as well.

Win 10
Node 10.15.0
npm 6.5.0

Let me know if you need anymore information.

**Comment by smartconvos** [comment]
Using `$ npm install pm2@3.2.4 -g` worked for me as well.  Randomly started getting "Spawning PM2 daemon..." response for any command I ran (ex: pm2 list).  After installing 3.2.4, it seems to be working normally again.  Any ideas if this is a version specific issue?

**Comment by iAbhinav** [comment]
> $ npm install pm2@3.2.4 -g

This fixed the issue. Thanks a lot.

**Comment by adapasuresh** [comment]
It helped in bring my Jenkins server
