### ISSUE TITLE
Documentation should not use `$` in bash example code blocks

### ISSUE THREAD

**Issue by niftylettuce** [Unitech/pm2#3109]
e.g. http://pm2.keymetrics.io/docs/usage/specifics/

We should remove the `$` in the code blocks, this is very bad practice.

**Comment by niftylettuce** [comment]
Also in the Wiki it is done here <https://github.com/Unitech/pm2/wiki>.

Where is the code for documentation located? @Unitech

**Comment by vmarchaud** [comment]
@niftylettuce https://github.com/pm2-hive/pm2-hive.github.io/
The wiki is generated from the docs

**Comment by niftylettuce** [comment]
I just submitted a PR that closes this issue, see <https://github.com/pm2-hive/pm2-hive.github.io/pull/104>.  Thank you.
