### ISSUE TITLE
Documentation for authbind is inaccurate

### ISSUE THREAD

**Issue by niftylettuce** [Unitech/pm2#3110]
We are sharing bad practices here <http://pm2.keymetrics.io/docs/usage/specifics/>.

Instead of this code block, it should be separated with a note.

# Listening on port 80 w/o root

It’s a general rule that you should not run node as root. However only root can bind to ports less than 1024. This is where authbind comes in. Authbind allows non-root users to bind to ports less than 1024.  Replace `%user%` with the user that will be running `pm2`.

```sh
sudo apt-get install authbind
sudo touch /etc/authbind/byport/80
sudo chown %user% /etc/authbind/byport/80
sudo chmod 755 /etc/authbind/byport/80
```

You should also add an alias to the user that runs `pm2` profile, e.g. `~/.bashrc` or `~/.zshrc` (note you will need to run `source ~/.bashrc` or `source ~/.zshrc` immediately after):

```diff
+alias pm2='authbind --deep pm2'
```

Finally ensure that `pm2` is updated with `authbind`:

```sh
authbind --deep pm2 update
```

Or simply `pm2 update` if you added the alias to your user's profile.

Now you can start applications using PM2 that can bind to port 80 without being root!

**Comment by vmarchaud** [comment]
I'm not sure the modification you want to make, could you open up a PR [directly on the documentation](https://github.com/pm2-hive/pm2-hive.github.io/blob/master/docs/features/specifics.md) to fix it ?

**Comment by niftylettuce** [comment]
Can you link to where the docs are?

**Comment by vmarchaud** [comment]
I link it in my previous comment but here you go : https://github.com/pm2-hive/pm2-hive.github.io/tree/master/docs/features

**Comment by niftylettuce** [comment]
I just submitted a PR that closes this issue, see <https://github.com/pm2-hive/pm2-hive.github.io/pull/104>.  Thank you.
