### ISSUE TITLE
Doesn't work for multiple receivers

### ISSUE THREAD

**Issue by Infernus666** [Unitech/pm2#3112]
Hello. I need to do ipc from a sender to multiple receiver processes. pm2-intercom works fine when there is one sender and one receiver but the message doesn't get received on multiple processes. Only 1 or at max 50% of the processes that are listening for 'message' would receive the packet.

Here's the code I'm using. Same script is being used for master and other processes. I'm telling them apart by using command line args in ecosystem.json.

```
var process = require('process');
argv = process.argv.slice(2);

if (argv[0] === 'master') {
    setInterval(function () {
        process.send({
            topic : 'cmd:topic',
            data  : {
                some : 'data'
            }
        });
    }, 15000);
} else {
    console.log("registering");
    process.on('message', function(packet) {
        if (packet.topic == 'cmd:topic') {
            console.log('Received packet', packet.data);
        }
    });
}
```
Thanks

**Comment by Unitech** [comment]
I would not recommend using pm2-intercom anymore, have a look at https://github.com/Unitech/spiderlink instead

**Comment by Unitech** [comment]
I would not recommend using pm2-intercom any more, have a look at https://github.com/Unitech/spiderlink instead

**Comment by edouardbrossette** [comment]
Hi,

If no error, PM2 in exec_mode : 'cluster'  will execute our app in child fork => giving no control on the 'master'. 
The only way (natively) to communicate with cluster will require the  'cluster.workers' object  who is only available in the master.
I need to scale my pm2 app and communicate between cluster. 
I do not want to use DB in the middle for this purpose for reasons (perf,..) 

Spiderlink is good for inter-server communication but for cluster communication it will require to create a socket server and client on cluster. Heavy for simple communication between proc... 

I want a vanilla light solution.

So i get back to the native node code.. can you broadcast => pipe message  from the master to the pm2 cluster child

Example for use in our app : 
`
 if (process.send) {
            process.send({
                data: {
                   "Hey brother! There's an endless road to rediscover"
                },
                type: "process:broadcast",
            });
        }
`
In Pm2 code, 
`
function eachWorker(callback) {
  for (const id in cluster.workers) {
    callback(cluster.workers[id]);
  }

if (msg.type === "process:broadcast")
{
eachWorker((worker) => {
  worker.send(msg.data);
});
}
`
