### ISSUE TITLE
Allow to specify Node.js version via interpreter arg 

### ISSUE THREAD

**Issue by liujb** [Unitech/pm2#3113]
I have specified Node.js version via interperter, But the version error.

![](http://7xp4um.com1.z0.glb.clouddn.com/15039171278666.jpg)

The absolute path `/home/xiaoju/node-v6.10.3-linux-x64/bin/node --version` is `6.10.3`

**Comment by soyuka** [comment]
I think that the nodejs version here is the one used by pm2, not related to your interpreter. You may also be interested in [this issue](https://github.com/Unitech/pm2/issues/1034#issuecomment-259760840).

**Comment by Unitech** [comment]
Yes, specifying the interpreter does not work in cluster mode.
In fork mode it works

**Comment by liujb** [comment]
@Unitech thanks.
