### ISSUE TITLE
[BUG][pm2 stop] will also send SIGINT to detached process (child_process.spawn)

### ISSUE THREAD

**Issue by Bingmang** [Unitech/pm2#3114]
I want to start a detached process using child_process.spawn

```js
      this._process = $.child_process.spawn('npm', ['start'], {
        cwd: $.path.resolve(this._options.npm_dir, this.package_name),
        detached: true,
        // TODO 重定向到文件
        stdio: ['ignore', this._log, this._log],
      })
```
but after that, i use

```sh
pm2 stop all
```

It will also kill my detached process,but if not use pm2, just use

```sh
node app.js
```

then ctrl+C, it will not kill my detached process.

Why pm2 worked like that? is that a bug? hope everyone seeing this and resolve the problem together.

===============================

My English is not so good, so I describe it again using Chinese, hope someone to help me to translate the issue better.

我用child_process.spawn起了一个detached的独立进程，就是希望父进程退出后不要把子进程关掉，但是用pm2 stop还是会把独立的进程关掉，如果是单纯的用node起，然后用Ctrl+C退出，就不会把这个独立进程杀掉。

这是为什么呢，我觉得是pm2的bug。

希望能修复这个BUG！

**Comment by Unitech** [comment]
Use the option `--no-treekill` when starting your application

**Comment by Bingmang** [comment]
thanks a lot !!
