### ISSUE TITLE
Required node env in cluster mode setup after startup

### ISSUE THREAD

**Issue by 2m0nd** [Unitech/pm2#3118]
Node environment NODE_EXTRA_CA_CERTS in cluster mode setup after startup node instance,
need setup required node parameter before startup, becuase similar parameters read one time on startup node.
I add PR with sample code which solves the problem https://github.com/Unitech/pm2/pull/3117.

**Comment by fdescamps** [comment]
Hi,

I'm very interested in this point.
Do you have some news about it ?

F.
