### ISSUE TITLE
start with specific uid using API

### ISSUE THREAD

**Issue by oscchun** [Unitech/pm2#3119]
I found solved issue below.
**************************
Feature added in upcoming PM2. To try it:

(Make sure pm2 is run as root to manipulate uid and gid)

$ pm2 save
$ pm2 kill
$ npm install Unitech/pm2#development -g
$ sudo pm2 resurrect
$ sudo pm2 start app --uid <uid>
Now pm2 ls display the user running the script
$ pm2 ls
**************************

how can I use this feature with pm2 API?

**Comment by vmarchaud** [comment]
You can use something like this : 
```
pm2.start({
  script: 'toto.js',
  uid: '1000',
  guid: '1000'
}, (err, apps) => {
// handle callback
})
```
