### ISSUE TITLE
Bug: Process env files that uses boolean values turns into string

### ISSUE THREAD

**Issue by ralphchristianeclipse** [Unitech/pm2#3126]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/Unitech/pm2/search?type=Issues) before creating one.

## What's going wrong?
Process env files that uses boolean values turns into string
## How could we reproduce this issue?
1. Add a pm2.config.js
2. put an env variable with a boolean e.g 

```js
env: {
   FORCE: true
}
```
3. do a console.log(typeof(process.env.FORCE))
4. it will return string which breaks this === operator from a library
## Supporting information

Please run the following command (available on PM2 >= 2.6)

```
$ pm2 report
```

**Comment by Unitech** [comment]
Environment variables are alway strings, so this is not a bug. You just need to cast the value
