### ISSUE TITLE
Add feature for restart on cpu usage limit - max_cpu_restart 

### ISSUE THREAD

**Issue by DanielHreben** [Unitech/pm2#3128]
There is awesome config option ```max_memory_restart```. 
It will be nice to have ```max_cpu_restart``` as well.

**Comment by vmarchaud** [comment]
Sadly the cpu usage isn't really reliable because it can be really hard to retrieve it on specific platforms (ie Windows), so we prefer to not implement it for now to avoid people complaining about restart when cpu wasn't over the threshold.

**Comment by DanielHreben** [comment]
@vmarchaud got it, but who runs node on windows in production? If windows support is only one reason to not implement it - mb it will be better to implement it at least for other platforms?

**Comment by vmarchaud** [comment]
@DanielHreben ahah if you knew :) The problem remains with other platforms also, we rely on `ps` to get the cpu usage and it's not really precise so yeah
