### ISSUE TITLE
QUESTION: What star, restart and reload hava difference?

### ISSUE THREAD

**Issue by ThinkRealize** [Unitech/pm2#3129]
The `start` or `restart` work look is same. I dot konw they hava different. The `reload` hava a little different that `reload` ms. Please talk me. Thanks!

**Comment by Unitech** [comment]
Restart / reload : http://pm2.keymetrics.io/docs/usage/signals-clean-restart/ 
http://pm2.keymetrics.io/docs/usage/cluster-mode/
