### ISSUE TITLE
the pm2 God Daemon take large mem(about 1.1g), and is slowly increasing

### ISSUE THREAD

**Issue by Qiubaowei** [Unitech/pm2#3132]
node v8.1.0
pm2 v2.4.6
centos
pm2.log has nothing error
it is running 10 simple applications(all fork mode). 

In the application just started，the pm2 God Daemon only eats about 50m mem, but As time goes by, it  is slowly increasing their memory (now it eats about 1.1g mem, and is still increasing)

**Comment by harshitj2005** [comment]
hi,
i am also having the same issue
node v6.9
linux ubuntu 16.04

currently i am using 5 application in fork mode each app consumes around 50-70 mb
but the pm2 is consuming 4 GB of ram.

here is output of `ps aux  | awk '{print $6/1024 " MB\t\t" $11}'  | sort -n`

![pm2_mem_usage](https://user-images.githubusercontent.com/9212282/30588103-14e9771a-9d53-11e7-8ac6-25f98c34e103.png)

here is .pm2/pm2.log

![pm2_logs_file](https://user-images.githubusercontent.com/9212282/30588158-4e3fc622-9d53-11e7-9522-55d18a141876.png)

**Comment by Qiubaowei** [comment]
@harshitj2005

**Comment by Qiubaowei** [comment]
Is the mem PM2 eats increasing slowly?

**Comment by harshitj2005** [comment]
yes

**Comment by Qiubaowei** [comment]
@harshitj2005   I'm ready to give it up and use forever

**Comment by vmarchaud** [comment]
If you can take a memory dump i will be really more useful, to do so :

Install the profiler with pm2 install profiler
- Run pm2 snapshot
- It should return you a path where the dump has been saved
Note that you need as much as twice RAM that the daemon is using to take a memory dump (since you need to make a copy of it)
