### ISSUE TITLE
What are recommendations for running multiple projects (about 30) on one server?

### ISSUE THREAD

**Issue by wwju** [Unitech/pm2#3133]
I can't understand what configuration is better for multiple projects

### Current configuration
I have one server and about 30 simple nodejs server-side projects, and their amount is growing.
They are being watched by only one pm2 process.
Config file `/home/user/pm2_processes.json` looks like this:
``` 
   "apps": [{
        "script": "/home/user/project1/current/server/index.js",
        "instances": 1,
        "exec_mode": "cluster",
        "name": "project1",
        "cwd": "/home/user/project1/current/",
    },
    // ..............................................
    // 20 more projects
   {
        "script": "/home/user/project2/current/server/index.js",
        "instances": 1,
        "exec_mode": "cluster",
        "name": "project2",
        "cwd": "/home/user/project2/current/",
    }]
```
And I can start everything by the command:
```
pm2 start /home/user/pm2_processes.json
```

### Possible configurations
Now I'm thinking that it might be better to have one of the configurations:

#### 1. Separate `process.json` files, one pm2
Keeping separate files `/home/user/project${number}/current/server/process.json` 

And can start all the projects like
```
pm2 start /home/user/project1/current/server/process.json
pm2 start /home/user/project2/current/server/process.json
```

#### 2. Separate `process.json` files, separate pm2 processes
And I can start all projects like that:
```
PM2_HOME=/home/user/project1/ ./node_modules/.bin/pm2 start /home/user/project1/current/server/process.json
PM2_HOME=/home/user/project2/ ./node_modules/.bin/pm2 start /home/user/project2/current/server/process.json
```

Could you help me and recommend what configuration is better or what are cons and proc of each one.

**Comment by soyuka** [comment]
I'd keep only one pm2 process. About ecosystem files, I'd recommend 1 per project (if a project uses some services, declare them in the same `process.json` file.

This should ease process management (with one pm2 process you don't need to find the correct PM2_HOME), and keep a good separation of concerns between your apps (one declaration per process).
