### ISSUE TITLE
Can not use shell_exec("pm2 start app.js"); to start pm2 on PHP 

### ISSUE THREAD

**Issue by sundayla** [Unitech/pm2#3135]
I want to start pm2 inside a php file, but it does't work.
PHP
`<?php
$output = shell_exec("pm2 start home/app.js"); 
print_r($output);
?>`
The output only show the following welcome message of PM2, and have't start the app.js.
`
Production Process Manager for Node.js apps
  | with a built-in Load Balancer.
  |  
  |  
  | Start and Daemonize any application:
  | $ pm2 start app.js
  |  
  | Load Balance 4 instances of api.js:
  | $ pm2 start api.js -i 4
  |  
  | Monitor in production:
  | $ pm2 monitor
  |  
  | Make pm2 auto-boot at server restart:
  | $ pm2 startup
  |  
  | To go further checkout:
  | http://pm2.io

`
my pm2 version is 2.6.1 
Thank you

**Comment by soyuka** [comment]
will be relative to php execution directory, you may want to use an absolute path.

**Comment by sundayla** [comment]
I have try shell_exec("pm2 list");  but the output is still the welcome message.
If I just put shell_exec("pm2");  it return welcome message+ -help content

I don't know why the respond is keep showing the welcome message and not truly function like I type the command on the SSH

**Comment by soyuka** [comment]
Works here:
```
(development ✗)❯ php -r 'echo shell_exec("pm2 list");'
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app

```

**Comment by sundayla** [comment]
It work on ssh like your output, but fail when I access the php page on the browser.

**Comment by tamaker** [comment]
@sundayla  - im trying to do the same thing.  did you ever resolve or find answer to this?

**Comment by sundayla** [comment]
@tamaker I can't do this finally.
PHP can not start a PM2 function even I try to start a node and call to start pm2  (PHP shell_exec node one.js  -> pm2 start app.js)
So, I think it is a PHP permissions problems (not sure)
Finally,  I tried another why to complete the task. 
Because I just want to start a pm2 on website. I change to run a websocket with a function to call another PM2 start.
