### ISSUE TITLE
Question: graceful start and reload

### ISSUE THREAD

**Issue by papakai** [Unitech/pm2#3136]
I found in your documentation that for graceful start, after completion the following message should be triggered:
```javascript
process.send('ready');
```

For graceful reload
```javascript
process.send('online');
```

Currently I am simply asking myself:
a) why are these messages not merged into one?
b) what reason is behind to have both messages?
c) is there some technical difference internally?

Would the below result in problems in case `ready` and `online` are somewhere concurrent?
```javascript
var server = require('https').createServer(srvcfg, app).listen(cfg.server, function() {
    //... some code ...

    process.send('ready');
    process.send('online');
  });
```

In addition:
PM2_GRACEFUL_LISTEN_TIMEOUT is overridable by listen_timeout. Wouldn't it make sense to have PM2_GRACEFUL_TIMEOUT to be overridable by kill_timeout too?

pm2 version: 2.4.1, but we plan to upgrade to the must current 2.6.x release in the next days.

**Comment by papakai** [comment]
I gave this a first trial - result: `process.send is not a function`. What am I missing here in general?

**Comment by vmarchaud** [comment]
It was a mistake, you only need to call `process.send('ready')`, could try update to the latest PM2 version and give me the process file or arguments that you are using to start your app ?

**Comment by papakai** [comment]
> Maybe this requires to be started with pm2 at all?

instead of starting the app via node directly, I started it via pm2 and then process.send seems to be available and working. I found also some resources in www pointing on process.send is only available conditionally (when being in context of a child process). This adds the requirement of pm2 on our local development area too. Or having different pm2 options there, and if path for process.send especially. So far good to know.

@vmarchaud 
What about my additional question above:

> PM2_GRACEFUL_LISTEN_TIMEOUT is overridable by listen_timeout. Wouldn't it make sense to have PM2_GRACEFUL_TIMEOUT to be overridable by kill_timeout too?

TIA!

**Comment by vmarchaud** [comment]
Indeed you need to launch it via PM2 to have `process.send` available, lot of people just add a condition like : 
```
if (process.send)
   process.send('ready')
```
And for your question :
`kill_timeout` is different than `listen_timeout` : [kill timeout](http://pm2.keymetrics.io/docs/usage/signals-clean-restart/#graceful-stop) is to the `stop` action to be graceful, however the [listen timeout](http://pm2.keymetrics.io/docs/usage/signals-clean-restart/#graceful-start) is for the `start` action.

**Comment by papakai** [comment]
@vmarchaud you got something wrong here :)

> Wouldn't it make sense to have PM2_GRACEFUL_TIMEOUT to be overridable by kill_timeout too?

**Comment by papakai** [comment]
bump :)
