### ISSUE TITLE
More references to deprecated gracefulReload in the docs

### ISSUE THREAD

**Issue by ExplodingCabbage** [Unitech/pm2#3138]
According to https://github.com/Unitech/pm2/issues/3078#issuecomment-323730125, `gracefulReload` is deprecated, but it's still referenced by several places in the docs. Hitting https://www.google.co.uk/search?q=site%3Apm2.keymetrics.io+gracefulReload brings up 8 results; some of them are just in comments, but many are in the main text of docs. None of them note the deprecation.

**Comment by vmarchaud** [comment]
If you actually click on every link, you should see that all reference to the command `pm2 gracefulReload` has been removed from the documentation but i guess google still have result in cache.

**Comment by ExplodingCabbage** [comment]
Oh - so the `gracefulReload` *method* is still valid and non-deprecated?

Anyway, there's still at least one instance of the command remaining - in the Cheat Sheet at http://pm2.keymetrics.io/docs/usage/quick-start/. There's also a usage at http://pm2.keymetrics.io/docs/usage/deployment/#related-commands that I'm not sure about.

**Comment by vmarchaud** [comment]
It still exists (compatibility) but we say its deprecated because we might drop it in PM2 v3
Also thanks for the links, removing it right now :)
