### ISSUE TITLE
Perform an action before deployement (pre-deploy)

### ISSUE THREAD

**Issue by darkterra** [Unitech/pm2#3139]
I every one,
Thank you for this amazing tool, I love PM2 !

But :
## What's going wrong?
It is not possible to perform an action on the remote server before deployment (Ex: Backup of a BDD)

**Comment by vmarchaud** [comment]
There is a hook to do this : `pre-deploy: 'your command'`

**Comment by darkterra** [comment]
Thank @vmarchaud !

Maybe the documentation, should be updated?

http://pm2.keymetrics.io/docs/usage/deployment/

Because on the documentation there is only 'pre-deploy-local'
Unless I missed something?

**Comment by vmarchaud** [comment]
Yes it should, feel free to make a PR to include it : https://github.com/pm2-hive/pm2-hive.github.io/blob/master/docs/features/deployment.md
You can find every available hook inside the deploy script [here](https://github.com/Unitech/pm2-deploy/blob/master/deploy)
