### ISSUE TITLE
Remove colon after the log format

### ISSUE THREAD

**Issue by nitrocode** [Unitech/pm2#3144]
I have a log format set in my `ecosystem.config.js`

          log_date_format: 'YYYY-MM-DD HH:mm:ss .SSS Z',

When I see the logs printed and I add additional information, there is a colon `:` in between the log date format and the additional information I printed via `console.log()`. Is there a way to remove the colon?

**Comment by vmarchaud** [comment]
Not currently, if it's because you want to parse the output, i would advise you to directly [output json formatted logs](http://pm2.keymetrics.io/docs/usage/log-management/#directly-output-json-logs), should way easier to parse them.

**Comment by nitrocode** [comment]
That's a good idea. We're short on time so we decided to make node output the columns to avoid the colon issue and we're going to use JSON after the next release. 

Just curious though, I tried looking for the colon in the code and didn't have much luck. Could you point me in the right direction? I'd like to get better at navigating pm2's code base.

Thanks

**Comment by vmarchaud** [comment]
No problem, its [here](https://github.com/Unitech/pm2/blob/master/lib/God/ForkMode.js#L164) if your app is in `fork_mode`, or [here](https://github.com/Unitech/pm2/blob/master/lib/ProcessContainer.js#L261) for the `cluster mode`, note that each time i'm only pointing to the `stdout`, `stderr` have the same behavior and is implemented next to the `stdout` one (for both mode).

**Comment by nitrocode** [comment]
Thank you! That comes in handy
