### ISSUE TITLE
How to set the error_file and out_file path in ecosystem.config.js without hard coding?

### ISSUE THREAD

**Issue by nitrocode** [Unitech/pm2#3145]
Here are my relevant settings in `ecosystem.config.js`. Is there a way I can store `/var/log/app` as an environment variable so I can pass it in for specific environments in pm2 ?

```
      error_file: `/var/log/app/err/${os.hostname()}_err.log`,
      out_file: `/var/log/app/app/${os.hostname()}.log`,
```

**Comment by Unitech** [comment]
Sure, just replace your os.hostname() with process.env.SOMETHING
