### ISSUE TITLE
log_date timezone error

### ISSUE THREAD

**Issue by weconquered** [Unitech/pm2#3149]
config：  log_date_format: "YYYY-MM-DD HH:mm:ss Z"
pm2 version： 2.6.1
OS： centos 7
OS TimeZone:  UTC 8:00。  in terminal is run "date" command.  the return is 2017年 09月 12日 星期二 14:47:37 CST

Q:  The log file as below:
2017-09-12 01:42:27 -05:00  XXXXXXXXXX

It seems the log timezone is Central Standard Time (USA)

==================================================
I edit a time.js as below: （It is correct）

var moment = require("moment")
console.log("hello", moment().format("YYYY-MM-DD HH:mm:ss"))

hello 2017-09-12 14:47:37
===================================================

what should i do ?  Is  any config i can use?

**Comment by vmarchaud** [comment]
Could you please fill the issue template, i don't understand the problem here (open a new issue).
