### ISSUE TITLE
pm2 startup: Execute generated command automatically

### ISSUE THREAD

**Issue by btilford** [Unitech/pm2#3152]
I'd like to execute the command that startup generates during provisioning (I'm using ansible and packer to build an AMI). 

I've tried the following 

* `$(pm2 startup | tail -1)` 
* `pm2 startup | tail -1 > /tmp/startup`

Both of these have the same error.
```
[PM2][ERROR] Init system not found
/bin/sh: 1: chmod: not found
```

I can probably fix the 2nd one about `chmod` but not sure how I'd be able to resolve not finding the init system.

Also executing the generated command manually does work so everything _"should be there"_.

**Comment by vmarchaud** [comment]
You should build and register yourself PM2 as a system service, just [pick a template](https://github.com/Unitech/pm2/tree/master/lib/templates/init-scripts) corresponding to your init system.

**Comment by btilford** [comment]
I'll give it a try. Any reason it wouldn't have detected Amazon Linux init system?

**Comment by vmarchaud** [comment]
@btilford Because no binary like `init.d` or `systemctl` etc has been found inside your PATH
