### ISSUE TITLE
Why is PM2 fork eating up 23 MB of my RAM for a piece of code this trivial?

### ISSUE THREAD

**Issue by aligajani** [Unitech/pm2#3154]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/Unitech/pm2/search?type=Issues) before creating one.

## What's going wrong?

This piece of code below is eating 23 MB of my RAM. It doesn't make sense. 

## How could we reproduce this issue?
I am running it like `pm2 start cron.js`

```
var exec = require('child_process').exec;
console.log('Running: ' + Date.now());
exec('node --version', (error, stdout, stderr) => console.log(stdout + stderr));
exec('pm2 --version', (error, stdout, stderr) => console.log(stdout + stderr));
```

## Supporting information

Please run the following command (available on PM2 >= 2.6)

I am using version *2.4.2* so it isn't available. 

```
$ pm2 report
```

**Comment by vmarchaud** [comment]
Welcome to Nodejs, it doesn't matter what code you are running, by default the engine (V8) take 20MB of RAM to run a process.

**Comment by aligajani** [comment]
Where does it say this? Any source please.
