### ISSUE TITLE
Error: ENOENT: no such file or directory, uv_chdir

### ISSUE THREAD

**Issue by longxianlin** [Unitech/pm2#3159]
in mac os
same error centos7

0|work-lry | Error: ENOENT: no such file or directory, uv_chdir
0|work-lry |     at Error (native)
0|work-lry |     at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:258:13
0|work-lry |     at /usr/local/lib/node_modules/pm2/node_modules/async/lib/async.js:52:16
0|work-lry |     at /usr/local/lib/node_modules/pm2/node_modules/async/lib/async.js:1209:30
0|work-lry |     at WriteStream.<anonymous> (/usr/local/lib/node_modules/pm2/lib/Utility.js:146:13)
0|work-lry |     at emitOne (events.js:96:13)
0|work-lry |     at WriteStream.emit (events.js:188:7)
0|work-lry |     at WriteStream.<anonymous> (fs.js:2114:10)
0|work-lry |     at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by vmarchaud** [comment]
Please use the issue template.

**Comment by krishlahoti1** [comment]
Did you resolve this issue?

**Comment by longxianlin** [comment]
no.

I just use docker. no need pm2 any more.

**Comment by treble-snake** [comment]
I've faced the same issue, figures out I had wrong path at `cwd`option in PM2 config file.
Guess yours can also be related to `cwd` option not set properly.
