### ISSUE TITLE
Creation of pid files and logs in a specific location

### ISSUE THREAD

**Issue by newlukai** [Unitech/pm2#3161]
I'm using pm2 with a JSON config file for my services. On my machine (Windows), HEOMDRIVE and HOMEPATH are set to a network location. Unfortunately, this means all pid and log files are created on the network which slows down working with PM2.
I tried to set "error_file", "out_file" and "pid_file" in the configuration as well as to set the PM2_HOME env variable. The first one didn't change anything for me and the latter option made PM2 to create the file structure in the new location as well as the pm2 log file, but the process logs and pids still are created on the network.

I just updated to 2.7.0. Any ideas? Thanks in advance.

**Comment by vmarchaud** [comment]
You need to permanently have `PM2_HOME` set in your environment if you want to make it works, then kill all running PM2 daemons using `taskkill` so your client doesn't connect to another daemon.

**Comment by newlukai** [comment]
Thanks, works now. I wasn't aware of the client server architecture. I should have thought of this, some messages include "daemon".
