### ISSUE TITLE
PM2 failes to determine "cluster_mode" for `0` or `max` instances

### ISSUE THREAD

**Issue by Turneliusz** [Unitech/pm2#3163]
On newest 2.7.0 (not tested previous version) PM2 is determining "exec_mode" as `fork_mode` instead of `cluster_mode` when specifying "instances" as: `0` or `max`. 

According to documentation:

> max means that PM2 will auto detect the number of available CPUs and run as many processes as possible in load balanced mode

See: http://pm2.keymetrics.io/docs/usage/cluster-mode/

See attached example with working and failing configuration JSON files. Application fail to listen to the specified port as execution mode is fork instead of cluster. Work-around is forcing "exec_mode" to be `cluster_mode` when specyfing `0` or `max` value for "instances". 

[bug-pm2.zip](https://github.com/Unitech/pm2/files/1318111/bug-pm2.zip)

**Comment by vmarchaud** [comment]
It's a wanted behavior, you can use `instances` with the fork mode as well so it's normal PM2 doesn't use the cluster mode by default.

**Comment by Turneliusz** [comment]
Documentation states:

> max means that PM2 will auto detect the number of available CPUs and run as many processes as possible in load balanced mode

**Comment by Turneliusz** [comment]
In general what it means is that:

~~~
pm2 start index.js -i max
~~~

is not an equivalent of:

~~~
{
    "apps": [
        {
            "script": "index.js",
            "instances": "max"
        }
    ]
}
~~~

We have been caught by this inconsistency really hard.

**Comment by vmarchaud** [comment]
Indeed the wording can be misleading, i'll modify it, thanks for the report

**Comment by Turneliusz** [comment]
Thanks!
