### ISSUE TITLE
Issue with Hazelcast cluster

### ISSUE THREAD

**Issue by gokhanoner** [Unitech/pm2#3166]
Hi,

We have use case: 2 nodejs servers, each has 16 hazelcast client nodes (https://github.com/hazelcast/hazelcast-nodejs-client) & load balanced with PM2.

Each hazelcast client instance opens a socket, apart from other things, they send heartbeat messages periodically to a server cluster. If the cluster couldn't get heartbeat, it just closes the connection.

Our app uses that clustered client instance. Problem is, we see some client instances are somehow hang and cannot recover. When PM2 disabled, everything works perfect. We checked the server logs & see that server cannot access some of the client instances for some reason.

Is it possible that PM2 stops unused instances while not active, preventing heartbeat messages to be sent ?

**Comment by vmarchaud** [comment]
Can you run `pm2 report` and give the result here please ? (so we can have more informations to pinpoint the issue)
