### ISSUE TITLE
Pass instance id to python APP as environment variable

### ISSUE THREAD

**Issue by sealabr** [Unitech/pm2#3168]
Need to pass "instance_id_env" as argument to a python aplication, this is easily done with nodejs.
I could pass as argument, but this number its not fixed.
I created a json file like this...

```
{
  "apps": [
    {
      "name": "myapp3",
      "script": "./py.py",
      "instances": 1,
      "instance_id_env": "NODE_APP_INSTANCE",
      "exec_mode": "fork",
      "env": {
        "NODE_ENV": "production"
      }
    }
  ]
}
```

need to get this id, tryied with sys.argv..
```

import sys
print(sys.argv)

```

**Comment by vmarchaud** [comment]
`NODE_APP_INSTANCE` is given inside the environment not in `argv`, you should get it with `os.envirion` (i think, dont know python well)
