### ISSUE TITLE
Question about PM2 Process Env

### ISSUE THREAD

**Issue by sealabr** [Unitech/pm2#3177]
Hello I'm Facing an issue in pm2 relataed with env variables passed by pm2 in windows/linux,

in windows my pm2 is showing uppercase "PM_ID" 
and in linux is showing "pm_id"

note I'm getting this values inside my app in python with os.environ.

this problem is about the version of my pm2 or OS distro?

**Comment by vmarchaud** [comment]
Not PM2 related, see [nodejs docs](https://nodejs.org/api/process.html#process_process_env) : 
```
On Windows operating systems, environment variables are case-insensitive.
```

**Comment by sealabr** [comment]
thanks
