### ISSUE TITLE
Different config value for different environments

### ISSUE THREAD

**Issue by vihanb** [Unitech/pm2#3178]
My `ecosystem.config.js` looks something like like:

```
module.exports = {
    "apps": [
        {
            "name": "My App",
            "script": "index.js",
            "exec_mode": "cluster",
            "instances": "max",
            "env_production": {
                "NODE_ENV": "production"
            }
        }
    ]
};
```

however I'd like `exec_mode` to only be `cluster` when I run my app using `--env production`, for any other case to run as `fork_mode`. Is this possible? I could only find a way to modify environment variables of the process depending on `--env production`.

**Comment by vmarchaud** [comment]
Duplicate https://github.com/Unitech/pm2/issues/3122
