### ISSUE TITLE
Request: command line option to read environment vars and set them to debug local

### ISSUE THREAD

**Issue by nitrocode** [Unitech/pm2#3179]
Is there a way to set env vars locally to test w/o pm2?

    $ pm2 load --env staging
    NODE_ENV: 'staging',
    AWS_PROFILE: 'default',
    AWS_REGION: 'us-west-1',
    DB_NAME: 'db'
    ...

My pm2 is set to cluster mode and it's easier for me to test locally but I have to set my environment vars each time. I have around 12 environment vars and I set them using shell scripts which have to be synchronized manually with my `ecosystem.config.js`. 

Is there a better way to do this? or is this a valid request?

**Comment by vmarchaud** [comment]
You can simply use `process.env.YOUR_VAR` inside your ecosystem file (only with `.config.js` extension).
