### ISSUE TITLE
pm2-dev reload API?

### ISSUE THREAD

**Issue by tnguyen14** [Unitech/pm2#3180]
I am using `pm2-dev` inside a docker container to do development, and it seems great so far. However, I am not able to do something like `pm2-dev reload` in order to reload the node process.

The use case is that I need to update the `DEBUG` environment variable, so I need to do something along the line of `DEBUG=* pm2 reload --update-env app` in order to get certain debug output.

Can `reload` and especially `--update-env` be added to `pm2-dev`?

**Comment by vmarchaud** [comment]
The aim of `pm2-dev` is that you never need to reload manually since at every file change the process is restarted. Even if possible, `--update-env` inside docker will be useless since the environment is inherited from the container.

**Comment by tnguyen14** [comment]
So I was trying out using `pm2-dev` as a way to do development inside a container. One of the things I'm used to doing when developing natively is to update the `DEBUG` environment variable to tune which part of the system I want to debug on. I think that's pretty key in the development workflow.

Do you have any suggestion on how to do that in the container way of working?

Instead of using `pm2-dev`, I switched to just `pm2`, and was able to do `pm2 reload --update-env`. Is that different from what you mean by the environment inherited from the container?

**Comment by vmarchaud** [comment]
When you update the environment value, you should need to restart the container right ?
In this case, it should be picked up by docker then given to PM2, then to your application.

I don't understand your development workflow exactly, can you explain how you do update the environment value ?

**Comment by tnguyen14** [comment]
Without docker, I just update it from the bash shell, so something like

```
DEBUG=app:models* pm2 reload --update-env
```

Are you saying that for the docker workflow, the `ENV` flag on docker can be set and will be picked up when the container is restarted?

I was under the impression that `pm2-dev` will manage the node process, so it can be refreshed without restarting the container (which would restart the pm2 process itself).
