### ISSUE TITLE
pm2 log output polluting syslog

### ISSUE THREAD

**Issue by larsenjh** [Unitech/pm2#3189]
After upgrading to pm2 version 2+ I started noticing that pm2 was writing all the stdout output of all the processes into the syslog, regardless of the fact that I had all the processes configured to write output (and stderr) to files in `~/.pm2/logs`. I can only assume that the stdout stream of each process (child processes of the main pm2 process?) are inheriting the stdout from the main pm2 service, thus being logged into syslog.
Is there any way at all to not have all this output being flushed into the syslog? It seems redundant, and we never had this issue with version 1 of pm2.

**Comment by vmarchaud** [comment]
I think you should be able to handle this via the configuration of the service [[ref]](https://serverfault.com/questions/858843/how-to-disable-logging-for-a-particular-systemd-unit), the one that is generated by pm2 is [here](https://github.com/Unitech/pm2/blob/master/lib/templates/init-scripts/systemd.tpl)
