### ISSUE TITLE
use pm2 start express project but can't access in browser

### ISSUE THREAD

**Issue by Pana** [Unitech/pm2#319]
I start a express service by `pm2 start app.js -i 3`, but can't access the service in browser.
`pm2 list` show the process is good.

**Comment by noyruto5** [comment]
I have the same problem. Can't load api run with pm2.

**Comment by LvChengbin** [comment]
I encountered the same problem. My server was working well as starting with `node server.js`.

**Comment by terryjiang2020** [comment]
I encountered the same problem. My express project is calling a python app as part of its process, and the python app is designed to access a browser to take screenshots and video recordings.

I can see the python app did reach out to the browser and do the things I ask it to do, but the screen recording and screenshots are not going through.

I tried the same by running the app manually, and it works perfectly fine.

BTW the python app is using Browser-Use to perform the user-like tasks, if that's a concern.
