### ISSUE TITLE
is it possible to have a front end 'manager' for PM2?

### ISSUE THREAD

**Issue by tamaker** [Unitech/pm2#3191]
I'm enjoying using PM2 and getting ready to finally prove to my team and boss that PM2 and Node.js are ready for production... questions:

1.) is it possible to use NGINX, PHP running on Ubuntu 14.04 to have a front-end page that allows me to trigger PM2 commands such as start, stop, status, kill and to be able to start / stop individual processes defined in my configuration.json file?   It all works great in CLI, but In our environment I need the ability to have an administrator (login required) page that allows for some control.  I saw and tried some info in your documentation for "PM2 API - Simple Example" ( http://pm2.keymetrics.io/docs/usage/pm2-api/#simple-example ) but it didn't work for me, i got an error when trying to run it in browser (error on require statement at start of code).

2.) I am also interested in knowing if I can have a dashboard (my own, not keymetrics) that lets me 
- see running processes
- get (if possible) a JSON file of all the data regarding those processes

Thanks

**Comment by vmarchaud** [comment]
1) You need to use the PM2 API, if you have any error with it you can open a new issue and i'll be happy to help you :)
2) Nope, even keymetrics don't retrieve all the data about the process, only the metrics from it, you need to code your custom solution.

**Comment by tamaker** [comment]
@vmarchaud thanks for the reply!
on the first, where I see var pm2 = require('pm2'); in the simple example here ( http://pm2.keymetrics.io/docs/usage/pm2-api/#simple-example )  I think I instead will need to have a <script> tag include the file for pm2, but which file would that be?  node_modules/pm2/bin/pm2 ???   when I try with that I get pm2 not defined.    Basically I want an HTML5 page that will allow me to test the PM2 API to start and stop a process.  Thx!

**Comment by vmarchaud** [comment]
You need to expose the API of PM2 via HTTP and then make request from your browser on this API. You can't use the javascript of PM2 from your browser
