### ISSUE TITLE
pm2 app restart again and again while watch is disabled

### ISSUE THREAD

**Issue by harshitj2005** [Unitech/pm2#3194]
hi,

i have an application which restart again and again while i have disbaled watch.

pm2.log are

> 2017-10-05 10:02:50: Change detected on path .git/index.lock for app billprocess - restarting
> 2017-10-05 10:02:50: Stopping app:billprocess id:10
> 2017-10-05 10:02:50: Unknown id 9
> 2017-10-05 10:02:50: App [billprocess] with id [10] and pid [31751], exited with code [0] via signal [SIGINT]
> 2017-10-05 10:02:50: pid=31751 msg=process killed
> 2017-10-05 10:02:50: Starting execution sequence in -fork mode- for app name:billprocess id:10
> 2017-10-05 10:02:50: App name:billprocess id:10 online

my pm2-ecosystem.json is

```
{
  "apps" : [{
    "name"       : "billprocess",
    "script"     : "app.js",
    "args"        : ["--color"],
    "watch"       : false,
    "ignore_watch" : ["[\\/\\\\]\\./","pids", "logs", "node_modules", "bower_components",".git",".git/index.lock",".idea"],
    "merge_logs"  : true,
    "cwd"         : ".",
    "error_file"  : "/var/log/billprocessv2.log",
    "out_file"    : "/var/log/billprocessv2.log",
    "pid_file"    : "./pids/msr.pid",
    "min_uptime"  : "30s", // defaults to 1000s
    "max_restarts"  : 30, // defaults to 15
    "restart_delay" : 10000,
    "max_memory_restart" : "10G",
    "env": {
      "NODE_ENV": "development"
    },
    "env_production" : {
      "NODE_ENV": "production"
    }
  }]
}

```

I have tried `"watch"       : ["app.js"]` still no resolution.

**Comment by harshitj2005** [comment]
update i did some research and used npm rebuild. after that problem seems to be resolved.
from last 30 mins my app didn't restart. updated pm2-ecosystem file
```

{
  "apps" : [{
    "name"       : "billprocess",
    "script"     : "app.js",
    "args"        : ["--color"],
    "watch"       : false,
    "ignore_watch" : ["[\\/\\\\]\\./","pids", "logs", "node_modules", "bower_components",".git",".git/index.lock",".idea"],
    "merge_logs"  : true,
    "cwd"         : ".",
    "no-autorestart":true,
    "error_file"  : "/var/log/billprocessv2.log",
    "out_file"    : "/var/log/billprocessv2.log",
    "pid_file"    : "./pids/msr.pid",
    "min_uptime"  : "30s", // defaults to 1000s
    "max_restarts"  : 30, // defaults to 15
    "restart_delay" : 10000,
    "max_memory_restart" : "10G",
    "env": {
      "NODE_ENV": "development"
    },
    "env_production" : {
      "NODE_ENV": "production"
    }
  }]
}

```

**Comment by yassinphilip** [comment]
I got the same one ; that pm2 should watch into .git/ by default is beyond me :|
