### ISSUE TITLE
PM2 Memory leak - High RAM usage

### ISSUE THREAD

**Issue by hiteshdua1** [Unitech/pm2#3216]
Hi @Unitech ,

PM2 God demon using 90% of the memory even after the application status has been changed to stopped.
This possible points towards the PM2 God memory demon that was consuming all the memory as displayed by ```top``` command

## What's going wrong?
High Memory Utilization was shown by PM2 GOD demon process , which was consuming around 90% of the system RAM.

## How could we reproduce this issue?
We are not sure of this, but 1 thing we can confirm is this machine was under stress testing to calculate the performance of the application .

## Supporting information
Analyzing the issue ourselves from other such issues we believe that the the pm2 log directory was out of space, which is shown in the pm2 logs. Our application process status was changed to stopped and the free available memory was close to 50 Mb only .

Although, Point to note here is that the application memory consumed as shown by the PM2 was close to 65 Mb only.

Running the free command displayed 
```
             total        used        free      shared  buff/cache   available
Mem:           3.9G        3.6G        113M         39M        153M         40M
Swap:          1.9G        1.9G        392K
```

And running the top command diplayed ```PM2 2.7.1 GOD Demon``` using 90% of the Memory.

## Possible Solution
For possible fix as was needed we ran the following command 
```
pm2 kill
```

Which killed all the processes and the RAM was released for the system. As of now the issue has not yet cropped up again because we still haven't tested it again for the stress test , but will let you know of the results if we find it replicating.

The output of the pm,2 report was interesting as the error displayed was that of Out of memory , but an ***unhanded one***  from the stack trace that is printed ( Please confirm ).

Note : We did run pm2 report, but that was **after** ``` PM2 kill ``` command.

```
===============================================================================
--- PM2 REPORT (Tue Oct 17 2017 07:49:15 GMT-0400 (EDT)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.7.1
node version         : 8.5.0
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : myitlab
uid                  : 999
gid                  : 999
uptime               : 279min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.7.1
node version         : 8.5.0
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : myitlab
uid                  : 999
gid                  : 999
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
cpus nb              : 2
freemem              : 3219623936
totalmem             : 4139368448
home                 : /export/home/myitlab
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬──────┬──────┬────────┬─────────┬────────┬─────┬───────────┬─────────┬──────────┐
│ App name │ id │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem       │ user    │ watching │
├──────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────┼───────────┼─────────┼──────────┤
│ app      │ 0  │ fork │ 4757 │ online │ 0       │ 4h     │ 0%  │ 96.8 MB   │ myitlab │ disabled │
└──────────┴────┴──────┴──────┴────────┴─────────┴────────┴─────┴───────────┴─────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/export/home/myitlab/.pm2/pm2.log last 20 lines:
PM2        | 2017-10-17 03:09:40: Application log path : /export/home/myitlab/.pm2/logs
PM2        | 2017-10-17 03:09:40: Process dump file    : /export/home/myitlab/.pm2/dump.pm2
PM2        | 2017-10-17 03:09:40: Concurrent actions   : 2
PM2        | 2017-10-17 03:09:40: SIGTERM timeout      : 1600
PM2        | 2017-10-17 03:09:40: ===============================================================================
PM2        | 2017-10-17 03:10:51: Starting execution sequence in -fork mode- for app name:app id:0
PM2        | 2017-10-17 03:10:51: Error: ENOSPC: no space left on device, write
PM2        |     at Object.fs.writeSync (fs.js:742:20)
PM2        |     at Object.fs.writeFileSync (fs.js:1310:24)
PM2        |     at /usr/lib/node_modules/pm2/lib/God/ForkMode.js:233:12
PM2        |     at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:421:16
PM2        |     at next (/usr/lib/node_modules/pm2/node_modules/async/dist/async.js:5302:29)
PM2        |     at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:906:16
PM2        |     at WriteStream.<anonymous> (/usr/lib/node_modules/pm2/lib/Utility.js:171:13)
PM2        |     at emitOne (events.js:115:13)
PM2        |     at WriteStream.emit (events.js:210:7)
PM2        |     at WriteStream.<anonymous> (fs.js:2165:10)
PM2        | 2017-10-17 03:10:51: App name:app id:0 online
PM2        | 2017-10-17 03:10:52: Error: ENOSPC: no space left on device, write
PM2        | 2017-10-17 03:10:52: Error: ENOSPC: no space left on device, write
```

**Comment by karlpokus** [comment]
@hiteshdua1 

> As of now the issue has not yet cropped up again because we still haven't tested it again for the stress test , but will let you know of the results if we find it replicating.

Please do.

**Comment by vmarchaud** [comment]
The printed error is definitively handled by the daemon and as you can see [here](https://github.com/Unitech/pm2/blob/master/lib/God/ForkMode.js#L233), the problem is that when your app is restarting, pm2 can't create the PID file.
If you can take a memory dump i will be really more useful, to do so : 
- Install the profiler with `pm2 install profiler`
- Run `pm2 snapshot`
- It should return you a path where the dump has been saved
Note that you need as much as twice RAM that the daemon is using to take a memory dump (since you need to make a copy of it)

**Comment by Unitech** [comment]
`PM2        | 2017-10-17 03:10:51: Error: ENOSPC: no space left on device, write`

**Comment by Unitech** [comment]
#3124

**Comment by yinrong** [comment]
+1 
![image](https://user-images.githubusercontent.com/4221569/48345328-b7fa4700-e6b2-11e8-98eb-169de9b44ecb.png)
