### ISSUE TITLE
Can i set $PM2_HOME to run multiple pm2 instances with cluster mode ?

### ISSUE THREAD

**Issue by crapthings** [Unitech/pm2#3217]
ubuntu 16

we have nvm on our server

nvm ls
node 4.7.3 default
node 8.7.0

each node version has its own pm2 installed as global

we start one of our app with node 4.7.3 and its running with cluster mode, and works fine.

when we try to start another node app that using 8.7.0, the pm2 seems to use 4.7.3 node.

```
nvm alias default 4
npm i -g pm2
pm2 start app1 app1-pm2-env.json (cluster mode, 2 instances)
```

```
nvm use 8
npm i -g pm2
pm2 start app2 app2-pm2-env.json (cluster mode, 2 instances)
```

but it has failed to start the app2, because its trying to run app2 with node 4.7.3.

after then, i've found $PM2_HOME that wiki said running multiple pm2 instances, so i

```
nvm use 8
PM2_HOME='.app2'
pm2 start app2 app2-pm2-env.json (cluster mode, 2 instances)
```

it still use the 4.7.3, and the app2 throw exception.

the weird thing is  if i remove "cluster mode 2 instances" from app2-pm2-env.json then run

```
nvm use 8
PM2_HOME='.app2'
pm2 start app2 app2-pm2-env.json (fork mode defaultly)
```

its using 8.7.0. but we need cluster mode.

i've already tried

1. nvm alias default 4
2. pm2 start app1
3. nvm alias default 8(just thought pm2 well use the default one)
4. nvm use 8
5. pm2 start app2

it still use node4.

maybe something wrong with god.js or its by design, or we can specify version that allow pm2 don't choose node version from exist pm2 instance/process? (not the exec_interpreter || --interpreter)

https://github.com/Unitech/pm2/blob/fd1f52d5e2413a5ad5ac7a52bbe9b5a14cc88732/lib/God.js#L154

https://github.com/Unitech/pm2/blob/0513526b82b4d07595eb754514d98be4ae516985/lib/God/ClusterMode.js#L34

if this issue has been solved, another great pm2 relative tool will work too.

https://github.com/andruschka/pm2-meteor/issues/54

**Comment by crapthings** [comment]
this print remote status

![image](https://user-images.githubusercontent.com/1147704/31707089-d33ad1f0-b3b0-11e7-9e08-2d4c0836417b.png)

**Comment by vmarchaud** [comment]
If you want to launch app with different nodejs version, you can use the `interpreter` config ([docs](http://pm2.keymetrics.io/docs/usage/application-declaration/#general)) and set it to a different node binary for each of your app. Note that you can use this with the cluster mode, it will be overridden to the default `node` binary available in the PATH

**Comment by crapthings** [comment]
i know interpreter can do fork mode.

so pm2 can't use different node version with cluster mode right now ?

even set a different PM2_HOME?

**Comment by crapthings** [comment]
how pm2 decide 4.7.3 to run our app

after i alias default node to 8x ?

**Comment by vmarchaud** [comment]
1. Indeed
2. You need to launch PM2 in the different home AFTER running `nvm use 8`

**Comment by crapthings** [comment]
i think its the only way to go for now. thanks
