### ISSUE TITLE
(Question) Updating application config based on changes from a JSON ecosystem

### ISSUE THREAD

**Issue by Unibozu** [Unitech/pm2#3218]
Hi,
I am using a mix of Jenkins/pm2/ELB to manage my deployments on production. Each application has it's own `pm2.json` describing its PM2 configuration and I wish to have PM2 updating all of the application configuration when I change something in the file.

Is there a way to make sure PM2 uses the new configuration from the JSON files when it changes? I have tried using `startOrReload pm2.json --update-env` without success.  For instance, I just tried to downscale the application to 1 instance from 1 by changing `instances: "max"` to `instances: 1`. This had no effect.

A not ideal workaround is to delete the application and re-create it, but this introduces some downtime and I'd like to avoid it.

Thanks
Clement

**Comment by Unitech** [comment]
"instances" attribute is not handled by startOrReload

We will document which attributes are updatable: https://github.com/pm2-hive/pm2-hive.github.io/issues/114

**Comment by Unitech** [comment]
#3124
