### ISSUE TITLE
Possible to run multiple instances of same app on different ports

### ISSUE THREAD

**Issue by waygee** [Unitech/pm2#322]
Hi,

I wanted to inquire whether it's possible to run my app.js multiple clusters like so:

app.js Cluster1 port 80
….
app.js Cluster2 port 81
….
app.js Cluster 3 port 82
….
app.js Cluster 4 port 83

My hosting provider, Rackspace, has advised me to try to set up this way.

Is this possible to do this under pm2 and have my app.js be running multiple clusters under different ports?

Thanks in advance for your help.

**Comment by aagam29** [comment]
What is the benefit of doing so ? @waygee 
Deploying the same application on multiple ports and then attaching a proxy say nginx will help you serve requests better ?

**Comment by alikarimii** [comment]
https://pm2.keymetrics.io/docs/usage/environment/

`
module.exports = {
  apps : [
      {
        name: "myapp",
        script: "./app.js",
        instances: 2,
        exec_mode: "cluster",
        watch: true,
        increment_var : 'PORT',
        env: {
            "PORT": 3000,
            "NODE_ENV": "development"
        }
      }
  ]
}
`
Use **increment_var** as in example

**Comment by jfoclpf** [comment]
> What is the benefit of doing so ? @waygee Deploying the same application on multiple ports and then attaching a proxy say nginx will help you serve requests better ?

Load balancing with NGINX, an example

```
upstream my_nodejs_upstream {
    server 127.0.0.1:3001;
    server 127.0.0.1:3002;
    server 127.0.0.1:3003;
    server 127.0.0.1:3004;
    keepalive 64;
}

server {
    listen 443 ssl;
    
    server_name www.my-website.com;
    ssl_certificate_key /etc/ssl/main.key;
    ssl_certificate     /etc/ssl/main.crt;
   
    location / {
    	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
    	proxy_set_header Host $http_host;
        
    	proxy_http_version 1.1;
    	proxy_set_header Upgrade $http_upgrade;
    	proxy_set_header Connection "upgrade";
        
    	proxy_pass http://my_nodejs_upstream/;
    	proxy_redirect off;
    	proxy_read_timeout 240s;
    }
}
```

Then in PM2

```js
module.exports = {
  apps : [
      {
        name: "myapp",
        script: "./app.js",
        instances: 4,
        exec_mode: "cluster",
        watch: true,
        increment_var : 'PORT',
        env: {
            "PORT": 3000,
            "NODE_ENV": "development"
        }
      }
  ]
}
```

Although PM2 with instances already does load balancing, so I don't know if it's worth the effort

Check this [article](https://codeforgeek.com/load-balancing-nodejs-servers-nginx/)

**Comment by joneldiablo** [comment]
hiii!!! @jfoclpf if I use 4 instances with exec_mode: 'cluster' (having 2 cores) I will get 8 instances running?
instance 1 - port 3000 (2 in cluster)
instance 2 - port 3001 (2 in cluster)
....

**Comment by mfahadshah** [comment]
> What is the benefit of doing so ? @waygee Deploying the same application on multiple ports and then attaching a proxy say nginx will help you serve requests better ?

In my case i need to do it because pm2 doesn't work well with socket io long polling so i used this approach to let nginx load balance my app with ip_hash. 
I do have some concerns if this approach will take away perks from pm2 like reload with zero down time. please answer if anyone knows. Thanks
