### ISSUE TITLE
python set environment language encoding no effect

### ISSUE THREAD

**Issue by CyrusLiu158** [Unitech/pm2#3224]
when i run a python script , the environment encoding is ascii, I want to set ''UTF-8", so I create daemon json  using LC_ALL and LANG, but no effect . the config file :

{
  "apps" : [{
    "name"        : "yf-dnn",
    "script"      : "./app.py",
    "watch"       : true,
    "cwd"         : "./",
    "exec_interpreter": "venv/bin/python",
    "exec_mode"  : "fork_mode",
    "max_memory_restart" : "50M",
    "env": {
      "LC_ALL": "zh_CN.UTF-8",
      "LANG": "zh_CN.UTF-8"
    }
  }]
}

**Comment by vmarchaud** [comment]
Could you re-open with the full issue template filled ?

**Comment by CyrusLiu158** [comment]
print error, log :
0|app      |     print('get_asset_location sub_text: ' + sub_text)
0|app      | UnicodeEncodeError: 'ascii' codec can't encode characters in position 29-55: ordinal not in range(128)
PM2        | App [app] with id [0] and pid [11232], exited with code [1] via signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:app id:0
PM2        | App name:app id:0 online
