### ISSUE TITLE
Support node args in cluster mode

### ISSUE THREAD

**Issue by ClementParis016** [Unitech/pm2#3227]
I'm having trouble to make PM2 run my Node.js apps with [`--inspect` option](https://nodejs.org/en/docs/guides/debugging-getting-started/).

If I only set `node_args: '--inspect'` in my `ecosystem.config.js` file, I can see in PM2 logs that the debugger gets attached to a random port number:

```
PM2        | Debugger attached.
PM2        | Debugger listening on port 5871.
PM2        | Warning: This is an experimental feature and could change at any time.
PM2        | To start debugging, open the following URL in Chrome:
PM2        |     chrome-devtools://devtools/remote/serve_file/@60cd6e859b9f557d2312f5bf532f6aec5f284980/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:5871/8d6c5344-14a0-40c2-aad7-fdb2f8f74578
```
As Node.js inspector documentation specifies that the default port is 9229, I've tried setting it manually with `node_args: '--inspect=9229'` but the result is the same (even with other ports), a random port number get assigned every time.

Is there any way I could set the inspector port in a predictable way?

Also, I'm running PM2 inside of a Vagrant box, if that may help to diagnose the problem.

<details>
<summary>View PM2 report</summary>

```
===============================================================================
--- PM2 REPORT (Mon Oct 23 2017 15:00:28 GMT+0200 (CEST)) ---------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.7.2
node version         : 6.11.2
node path            : /usr/bin/pm2
argv                 : /usr/bin/nodejs,/usr/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : vagrant
uid                  : 1000
gid                  : 1000
uptime               : 271min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.7.2
node version         : 6.11.2
node path            : /usr/bin/pm2
argv                 : /usr/bin/nodejs,/usr/bin/pm2,report
argv0                : node
user                 : vagrant
uid                  : 1000
gid                  : 1000
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
cpus nb              : 1
freemem              : 362819584
totalmem             : 1042198528
home                 : /home/vagrant
===============================================================================
--- PM2 list -----------------------------------------------
┌─────────────┬────┬─────────┬───────┬────────┬─────────┬────────┬─────┬───────────┬─────────┬──────────┐
│ App name    │ id │ mode    │ pid   │ status │ restart │ uptime │ cpu │ mem       │ user    │ watching │
├─────────────┼────┼─────────┼───────┼────────┼─────────┼────────┼─────┼───────────┼─────────┼──────────┤
│ omni-server │ 0  │ cluster │ 17858 │ online │ 0       │ 6m     │ 0%  │ 78.5 MB   │ vagrant │ enabled  │
│ omni-worker │ 1  │ cluster │ 17863 │ online │ 0       │ 6m     │ 0%  │ 89.1 MB   │ vagrant │ enabled  │
└─────────────┴────┴─────────┴───────┴────────┴─────────┴────────┴─────┴───────────┴─────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌─────────────┬────┬─────────┬───────┬────────┬─────────┬────────┬─────┬───────────┬─────────┬──────────┐
│ App name    │ id │ mode    │ pid   │ status │ restart │ uptime │ cpu │ mem       │ user    │ watching │
├─────────────┼────┼─────────┼───────┼────────┼─────────┼────────┼─────┼───────────┼─────────┼──────────┤
│ omni-server │ 0  │ cluster │ 17858 │ online │ 0       │ 6m     │ 0%  │ 78.5 MB   │ vagrant │ enabled  │
│ omni-worker │ 1  │ cluster │ 17863 │ online │ 0       │ 6m     │ 0%  │ 89.1 MB   │ vagrant │ enabled  │
└─────────────┴────┴─────────┴───────┴────────┴─────────┴────────┴─────┴───────────┴─────────┴──────────┘
```

</details>

**Comment by PassTheMayo** [comment]
Instead of `--inspect=9229`, have you tried `--inspect 9229`?

**Comment by ClementParis016** [comment]
@PassTheMayo Yes, I just did and Node doesn't understand it, it seems like it tries to execute a module called '9229'.

```
PM2        | 2017-10-23 18:35:17: App name:omni-server id:0 online
PM2        | module.js:471
PM2        |     throw err;
PM2        |     ^
PM2        |
PM2        | Error: Cannot find module '/home/vagrant/9229'
PM2        |     at Function.Module._resolveFilename (module.js:469:15)
PM2        |     at Function.Module._load (module.js:417:25)
PM2        |     at Module.runMain (module.js:604:10)
PM2        |     at run (bootstrap_node.js:383:7)
PM2        |     at startup (bootstrap_node.js:149:9)
PM2        |     at bootstrap_node.js:496:3
PM2        | 2017-10-23 18:35:17: App name:omni-server id:0 disconnected
PM2        | 2017-10-23 18:35:17: App [omni-server] with id [0] and pid [4961], exited with code [1] via signal [SIGINT]
PM2        | 2017-10-23 18:35:17: Script /var/www/marketplace/server.js had too many unstable restarts (16). Stopped. "errored"
```

Indeed, the Node docs say `--inspect=port` , which works well if I run the `node server.js --inspect=9229` command manually.

I've no idea how PM2 works under the hood, but maybe inspection can't work in cluster mode?

**Comment by vmarchaud** [comment]
Could you try without the cluster mode ? If i remember correctly the way we need to give specific node arguments is totally different and not handled currently

**Comment by ClementParis016** [comment]
@vmarchaud sure, I've just tried in fork mode and the ports I set are correctly bound to the debugger, so this issue appears to be specific to the cluster mode.

**Comment by ClementParis016** [comment]
I tried a few more things and it appears that when clustering a Node app ran with `--inspect=<port>`, Node automatically adds an extra `--inspect-port=<port>` with a different port number to each worker instance.

You can see this by adding `console.log(process.execArgv)` in a clustered app (with or without PM2), and when you run it with `--inspect=9229` it will log smthg like `[ '--inspect=9229', '--inspect-port=9237' ]`.

So it appears that PM2 is correctly passing the node args. Since Node is assigning a different port for each worker, I'm not even sure if there is a predictable way to determine on which port the debugger will be listening.

**Comment by evenfrost** [comment]
Any update on this? I need to use `inspect` in production, my app is in cluster mode. I don't want to downgrade the performance and move back to a single instance.

**Comment by thamizhchelvan** [comment]
Hi,

Any update on this issue, it would be good if we can set the starting port when we launch the app in cluster mode with --inspect flag.

**Comment by YounGoat** [comment]
Any update on this issue?

**Comment by Unitech** [comment]
It's not possible to add node arguments to applications running in cluster mode, as PM2 Daemon runs as the master. You can tweak node arguments of PM2 directly so clustered application will inherit the same node arguments: https://github.com/Unitech/pm2/blob/master/lib/Daemon.js#L49

**Comment by thefoxie** [comment]
> So it appears that PM2 is correctly passing the node args. Since Node is assigning a different port for each worker, I'm not even sure if there is a predictable way to determine on which port the debugger will be listening.

@ClementParis016 have you found a way how to tell which port is the right one? I just try one of four ports that are in output of `lsof -i | grep -i node`, which is not convenient at all.

**Comment by ClementParis016** [comment]
@thefoxie no I never figured it out

**Comment by DavidKrpt** [comment]
Hi, I'm facing the same issue in pm2 v 5.1.2, node v14.18.2.
@Unitech, can you please elaborate a little on your comment ?

> You can tweak node arguments of PM2 directly so clustered application will inherit the same node arguments:

I really need to activate the inspector in cluster mode whether programmatically or via node arguments. The port doesn't have to be custom, but I need a way to find out the port number in code, so that I can pass it to a function.
