### ISSUE TITLE
Pm2 websocket cluster high availability

### ISSUE THREAD

**Issue by aydinkn** [Unitech/pm2#3230]
Hello,

I have a socket.io server (websocket transport only) and I run it in cluster mode with -i 0
The problem is, I want to high availability on my server when I deploy updated server code.

When I reload the process, I receive SIGINT and this means I have to wait all websocket connections to close. When websocket connections count is 0 then I call process.exit(). But meantime pm2 still redirect new requests to that worker and new websocket connections keep coming.

How can I handle high availability with pm2?

**Comment by vmarchaud** [comment]
You should read https://github.com/Unitech/pm2/issues/389
