### ISSUE TITLE
Starting pm2 when it's not requested

### ISSUE THREAD

**Issue by vad1m** [Unitech/pm2#3233]
## What's going wrong?
Executing `pm2 -v` daemonizing the app, but it should only show currently installed version without starting anything.

## How could we reproduce this issue?
Kill all existing pm2 instances from memory and run `pm2 -v`

## Supporting information
Reproducible in 2.5.0 and also on latest 2.7.2

**Comment by vmarchaud** [comment]
Duplicate https://github.com/Unitech/pm2/issues/2871

**Comment by Unitech** [comment]
pending release
