### ISSUE TITLE
Memory + CPU on full load on a Express Request 

### ISSUE THREAD

**Issue by avolution** [Unitech/pm2#3235]
I have a problem with a express app which also use mongoose mongoose for connection MongoDB

On PM2 on every Request the CPU goes to 100% and the mem increasing to a few GB until the process is crashing.

I dont have this behavior when I run my App without PM2 

I use
```
pm2d version         : 2.7.2
node version         : 7.3.0
```

**Comment by vmarchaud** [comment]
Can you give a sample that reproduce the problem ? If possible a cpu profile and memory dump of your application also
