### ISSUE TITLE
Do custom commands have to spawned by a JS script?

### ISSUE THREAD

**Issue by Spazer9** [Unitech/pm2#3239]
I'd love to use PM2 for a project that both uses rails and node.

I want to manage the following processes but it seems like PM2 is more focused on actual script files rather than broad commands:

- `dotenv bundle exec rails s #starts the server`
- `dotenv bundle exec sidekiq #starts a worker`

I found myself trying to wrap these commands in a very hackish `startup.js` that pm2 likes which looks like:

```
const exec = require("child_process").exec
exec("dotenv bundle exec rails s", (error, stdout, stderr) => {})
```

I'm worried this could impact reliability or cause problems with performance. am I trying too hard to get pm2 to work for me?

**Comment by vmarchaud** [comment]
You can easily use a [process file](http://pm2.keymetrics.io/docs/usage/application-declaration/) with the configuration : 
```
  script: 'dotenv',
  scriptArgs: [ 'bundle', 'exec' ....]
```

**Comment by Spazer9** [comment]
@vmarchaud I have actually tried that and it seems to work, except for the fact that it fails to stop the ruby process when you run `pm2 stop all`

The process does exit according to `pm2 list` but you run `top` and it's still running, you have to manually `sudo kill PID` to get rid of it.

I partially know why, it is because Sidekiq doesn't receive any `SIGTERM` or `SIGINT` for some reason..

I have used [Eye](https://github.com/kostya/eye) and it kills processes perfectly, it just seems like pm2 doesn't pass through exit signals in binary processes like Sidekiq.
