### ISSUE TITLE
PM2 typescript + ecosystem.json

### ISSUE THREAD

**Issue by akaNightmare** [Unitech/pm2#3240]
Hello, 

I have `ecosystem.json` config
```
{
  "apps": [
    {
      "name": "app",
      "script": "./app.ts",
      "watch": true,
      "env": {
        "NODE_ENV": "development"
      },
      "exec_mode": "fork",
      "source_map_support": true,
      "node_args": ["--inspect=5252"],
      "merge_logs": true
    }
  ]
}
```
and have `tsconfig.json`, but nothing happened.

How to "friend" typescript (tsconfig.json) and `pm2` ?

**Comment by vmarchaud** [comment]
What do you mean `nothing happened` ? Is it starting ? Is there any error ?

**Comment by akaNightmare** [comment]
@vmarchaud 
> Is it starting ? Is there any error ?
no and no

**Comment by vmarchaud** [comment]
Could you check for error logs in `~/.pm2/pm2.log` ?

**Comment by MickL** [comment]
I got the same problem: Using ecosystem.json the tsconfig.json is not loaded. This will result in an error while compiling TypeScript for me: `Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.` because it needs to be set in tsconfig.json.

It works when starting the the app normally but not with ecosystem `pm2 start myApp.config.json`:

```
{
  "apps" : [
    {
      "name": "myApp",
      "script": "./main.ts",
      "env": {
        "environment": "prod",
        "max-old-space-size": 8192
      },
      "out_file": "/dev/null",
      "watch": false,
    }
  ]
}
```

**Comment by MickL** [comment]
@vmarchaud Please reopen

**Comment by suavelizard** [comment]
Yeah that worked for me but it is far from ideal.

**Comment by kolarski** [comment]
This still looks like an issue even with the MickL's fix. 

After a day of debugging - the problem was I was missing `"exec_mode": "fork",` in ecosystem.json

if you omit `exec_mode: fork` then I'm getting bunch of typescript errors that should not be there, indicating `tsconfig.json` is not used.

**Comment by arnaullfe** [comment]
Hi,for me don't work this solution. I Have my tsconfig.json:

`{
  "compilerOptions": {
    "target": "es2017",
    "module": "commonjs",
    "lib": ["dom", "es6", "es2017", "esnext.asynciterable"],
    "skipLibCheck": true,
    "sourceMap": true,
    "outDir": "./dist",
    "moduleResolution": "node",
    "removeComments": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "resolveJsonModule": true,
    "rootDir": "src",
    "composite": true,
    "declaration": true,
    "noEmitOnError": false,
    "preserveConstEnums": true,
  },
  "exclude": ["node_modules"],
  "include": ["src"],
}`

And my ecosystem.config.js:

`module.exports = {
  apps : [{
    name: "app",
    script: './index.ts',
    autorestart: true,
    exec_mode: "fork",
    watch: true,
    env: {
      NODE_ENV: 'development',
    },
    env_production: {
      NODE_ENV: 'production',
    },
  }
],
};
`

My strucutre is: 
   - index.ts
   - tsconfig.json
   -  ecosystem.config.js
   - src/
   - 
And i still have this error on the pm2 logs:
![Screenshot from 2021-09-02 23-12-56](https://user-images.githubusercontent.com/45872144/131916937-22e41cda-2687-4f45-8af9-cf79f22185dc.png)
