### ISSUE TITLE
Error with npm start

### ISSUE THREAD

**Issue by sbamniya** [Unitech/pm2#3241]
Hello,

I'm using `pme v2.7.1` and `node 6.11.0` and when I run `pm2 start npm -- start` then it returns, 

`[PM2] Applying action restartProcessId on app [npm](ids: 0)
[PM2] [npm](0) ✓
[PM2] Process successfully started
│ Name │ mode │ status │ ↺  │ cpu │ memory   │
│ npm  │ fork │ online │ 15 │ 0%  │ 8.9 MB   │

 Use `pm2 show <id|name>` to get more details about an app
` 
on ubuntu server but when I run `pm2 show npm`, it returns 

`Describing process with id 0 - name npm 
│ status            │ errored                                     │
│ name              │ npm                                         │
│ restarts          │ 15                                          │
│ uptime            │ 0                                           │
│ script path       │ /usr/local/bin/npm                          │
│ script args       │ start                                       │
│ error log path    │ /home/examin8/.pm2/logs/npm-error-0.log     │
│ out log path      │ /home/examin8/.pm2/logs/npm-out-0.log       │
│ pid path          │ /home/examin8/.pm2/pids/npm-0.pid           │
│ interpreter       │ node                                        │
│ interpreter args  │ N/A                                         │
│ script id         │ 0                                           │
│ exec cwd          │ /home/examin8/public_html/node/test-project │
│ exec mode         │ fork_mode                                   │
│ node.js version   │ 6.11.0                                      │
│ watch & reload    │ ✘                                           │
│ unstable restarts │ 0                                           │
│ created at        │ N/A                                         │

 Add your own code metrics: http://bit.ly/code-metrics
 Use `pm2 logs npm [--lines 1000]` to display logs
 Use `pm2 monit` to monitor CPU and Memory usage npm
`

Please help me, and let me know what I'm doing wrong.

**Comment by vmarchaud** [comment]
Checkout the logs, you should have error in them
