### ISSUE TITLE
pm2 api reports 0 for unstable_restarts

### ISSUE THREAD

**Issue by j3ddesign** [Unitech/pm2#3245]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/Unitech/pm2/search?type=Issues) before creating one.

## What's going wrong?
I'm using https://github.com/politinn/pm2-prometheus-exporter to get basic stats about my running apps, however the `unstable_restarts` value is returning incorrectly. It seems this pulls from `pm2_env.unstable_restarts` on each response from running the `list` command

## How could we reproduce this issue?
```
const pm2 = require('pm2');
pm2.list([], (err, resp) => {
   list.forEach(p => {
     console.log(p.pm2_env.unstable_restarts);
   })
});
```

## Supporting information

Please run the following command (available on PM2 >= 2.6)

```
$ pm2 report
```

**Comment by vmarchaud** [comment]
`unstable_restarts` is used as internal variable that doesn't count how much restart has been made, the one you are looking for is `restart_time`
