### ISSUE TITLE
feature request - log selected ids

### ISSUE THREAD

**Issue by diginfo** [Unitech/pm2#3247]
Right now I can log everything or one only, it would be really nice if I could do this:

pm2 log 0 2 4 6 8 10 12 14 16 18 20
or
pm2 log 0,2,4,6,8,10,12,14,16,18,20

**Comment by vmarchaud** [comment]
You can use regex to do this : 
```
# Display only logs about process containing "api" in their name
pm2 logs /api/

# It's a regex so you can filter with the normal syntax to filter with OR condition
pm2 logs /server_[12]/
```

We prefer to handle selection by regex, more powerfull than simple choice like this.
