### ISSUE TITLE
How do I call `pm2` to check if a process with given name is running?

### ISSUE THREAD

**Issue by cadorn** [Unitech/pm2#325]
I have a simple postdeploy script that gets called whenever I deploy to a server.

In that script I want to start a process if it is not started and if it is already started, then just reload it. How would I script that in bash using the `pm2` command?

**Comment by Redsandro** [comment]
@Unitech the output is not captured.

```
$ TEST=`pm2 describe test`
[PM2][WARN] test doesn't exist
$ echo $TEST

$ 
```

So how can we use that in a script?

**Comment by springuper** [comment]
--silent option can suppress error, so it can be use to force execute some commands, such like:

```bash
pm2 stop --silent some-name
pm2 delete --silent some-name
```

**Comment by Redsandro** [comment]
That doesn't help. I'm trying to detect whether a node is started from `pm2`, `forever`, or some other manager.

I figured out that `pm2` shows warnings on stderr, so the bash fix would be to redirect that to stdout:

```
$ TEST=`pm2 describe test 2>&1`
```

**Comment by carpii** [comment]
You can just use the exit code from pm2 describe..

````
#!/bin/bash

pm2 describe appname > /dev/null
RUNNING=$?

if [ "${RUNNING}" -ne 0 ]; then
  pm2 start ./deploy/development.yml
else
  pm2 restart nodechat
fi;
`````

**Comment by Redsandro** [comment]
Thanks! :+1:

**Comment by petarjs** [comment]
For me the problem was that any of the above solutions I tried gave a non-zero exit code, which would stop Jenkins' Post Build task and mark it as failed. The pm2 silent mode has a return code of 1 (even though it doesn't show errors in the output) (pm2 delete -s appName). Also, redirecting the output using `> /dev/null` still produced a non-zero exit code.

So what I did was this:

```sh
pm2 delete -s app || :
pm2 start ./index.js --name=app
```

The `|| :` part executes if the `pm2 delete` sets a non-zero return code (which happens when try to delete an app that does not exist yet). The `:` is a null operator that returns 0 success exit code. So whatever happens, the `pm2 start` line is executed.

**Comment by acrawly** [comment]
I came across this issue today using Codeship. I ended up doing this:

    pm2 start <appname> --update-env

If the app was already running, it just restarted it.

**Comment by Redsandro** [comment]
The problem with the last two options is that I cannot _observe_ if `pm2` is running this particular script.

I don't just want to delete the app if it's already running or start the app if it's not running. I want to know _which_ manager is running the app and execute the correct portion of the script. Otherwise I would start the app on all managers.

E.g. if running forever, restart forever. If running pm2, restart pm2. Report back to deploy script which manager was managing the script.

**Comment by matewilk** [comment]
@Redsandro I'm running @petarjs's solution in jenkins and I just had to add `#!/bin/bash` string at the beginning of `Execute shell` build step. 

Note I'm using a plugin that allows me to run `shell` scripts as a `post-build action`

**Comment by corysimmons** [comment]
https://github.com/Unitech/pm2/issues/325#issuecomment-281580956

![ihtnw](https://user-images.githubusercontent.com/224636/29357416-78267d1a-8245-11e7-9354-2dfb479cda62.gif)

**Comment by mysoluto** [comment]
if [ "$(pm2 id appname) "= "[]" ]; then
   pm2 start appname
else
  pm2 reload appname
fi

**Comment by mcelotti** [comment]
Thanks for https://github.com/Unitech/pm2/issues/325#issuecomment-281580956
In my .gitlab-ci.yml file I had to use quotes:
$ pm2 del --silent my-app || ':'

**Comment by ir-fuel** [comment]
AWS CodeDeploy keeps on throwing errors when running this when the process does not exist:

```
pm2 stop --silent server || ':'
pm2 delete --silent server || ':'
```

```
LifecycleEvent - ApplicationStop
Script - deploy/stop.sh
[stderr][PM2][ERROR] Process server not found
[stdout]┌──────────┬────┬─────────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
[stdout]│ App name │ id │ version │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
[stdout]└──────────┴────┴─────────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
[stdout] Use `pm2 show <id|name>` to get more details about an app
[stderr][PM2][ERROR] Process server not found
[stdout]┌──────────┬────┬─────────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
[stdout]│ App name │ id │ version │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
[stdout]└──────────┴────┴─────────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
[stdout] Use `pm2 show <id|name>` to get more details about an app
```

**Comment by naveenparashar47** [comment]
#325

> For me the problem was that any of the above solutions I tried gave a non-zero exit code, which would stop Jenkins' Post Build task and mark it as failed. The pm2 silent mode has a return code of 1 (even though it doesn't show errors in the output) (pm2 delete -s appName). Also, redirecting the output using `> /dev/null` still produced a non-zero exit code.
> 
> So what I did was this:
> 
> ```shell
> pm2 delete -s app || :
> pm2 start ./index.js --name=app
> ```
> 
> The `|| :` part executes if the `pm2 delete` sets a non-zero return code (which happens when try to delete an app that does not exist yet). The `:` is a null operator that returns 0 success exit code. So whatever happens, the `pm2 start` line is executed.

*********mike drop********

**Comment by qwertycody** [comment]
> I would suggest the following:
> 
> `pm2 pid <name>` which if:
> 
> 1. Process is running: prints pid to stdout and exits with 0.
> 2. Process is not running: prints nothing to stdout and exits with 1.

Just an FYI for anyone looking at this post in the future - PM2 returns 0 if the process is running or not running for the exit code.

The person who posted this was probably right at some point in time with previous revisions of PM2 but the current version I'm on as of 2022 doesn't follow this behavior.

![image](https://user-images.githubusercontent.com/4968312/187440926-e1eccd8e-055e-47a6-9833-ff9e6cdd2627.png)

![image](https://user-images.githubusercontent.com/4968312/187440986-74210d7d-0b5b-4f67-9eea-acba0c9c1c79.png)

**Comment by qwertycody** [comment]
This is a solution that I wrote up using shell execution in PHP - I use both functions in conjunction with each other.


```
private static function isRunning(string $serviceName, string $pm2Name) 
    {
        // The command 'pm2 pid' will return a process id of 0 if the process is not running
        //
        // What we do here is take the output of the command and check if the process id is 0 against the grep command via pipe
        //
        // If grep finds the exact match of 0 then the process is not running and returns an exit code of 0 which signifies 
        // that the PM2 process is not running
        //
        // If grep does not find an exact match of 0 then the process is running and returns an exit code of 1 which signifies
        // that the PM2 process is running
        $isStopped = ProcessManager::execCommandWithExec($serviceName, "pm2 pid '$pm2Name' | grep -w 0", false);

        if ($isStopped == 0)
        {
            return false;
        }
        else
        {
            return true;
        }
    }

private static function processExists(string $serviceName, string $pm2Name) 
    {
        $processExists = ProcessManager::execCommandWithExec($serviceName, "pm2 describe '$pm2Name'", false);
        return $processExists == 0;
    }
```

**Comment by labman010** [comment]
Why should we restart it if the process is already running?  i modify the someone's code to :
`
pm2 describe appname  > /dev/null
RUNNING=$?
if [ "${RUNNING}" -ne 0 ]; then
  pm2 start './app' --name "appname"
else
  pm2 pid appname > /dev/null
  RUNNING=$?
  if [ "${RUNNING}" -ne 0 ]; then
    pm2 restart appname
  fi;
fi;
`

**Comment by rajendrabadri123** [comment]
@labman010 I have used your reference to make it work properly, when checking PID we should check if its equals to "0" to restart the process isn't ? when PID is running then value it returns is greater than 0 or returns of PID number.


```
#!/bin/bash

APP_NAME="uvicorn:app"
APP_CONFIG_JS="ecosystem.config.js"

pm2 describe $APP_NAME > /dev/null

RUNNING1=$?

echo "RUNNING1 $RUNNING1"

if [ "${RUNNING1}" -ne 0 ]; then

echo "pm2 start $APP_NAME"
echo "pm2 start $APP_CONFIG_JS"

else pm2 pid $APP_NAME > /dev/null

RUNNING2=$(pm2 pid $APP_NAME)

echo "RUNNING2 $RUNNING2"

if [ "${RUNNING2}" -eq 0 ]; then

echo "pm2 restart $APP_NAME"
echo "pm2 restart $APP_CONFIG_JS"

fi;

fi;
```
