### ISSUE TITLE
post-deploy is no working

### ISSUE THREAD

**Issue by Taffyw** [Unitech/pm2#3250]
hello every i have a problem please help me~
"post-deploy": 'cnpm i && pm2 reload ecosystem.config.js --env production'
tip

 ○ deploying origin/master
  ○ executing pre-deploy-local
  ○ hook pre-deploy
  ○ fetching updates
  ○ full fetch
Fetching origin
From github.com:Taffyw/react-ssr
   bfe88b2..620d424  master     -> origin/master
  ○ resetting HEAD to origin/master
HEAD is now at 620d424 test
  ○ executing post-deploy `cnpm i && pm2 reload ecosystem.config.js --env production`
bash: cnpm: command not found

  post-deploy hook failed

Deploy failed

**Comment by vmarchaud** [comment]
hooks ran by pm2-deploy is in non-interactive session see https://github.com/Unitech/pm2/issues/1887
