### ISSUE TITLE
pm2 not working on aws ec2

### ISSUE THREAD

**Issue by ahsanaasim** [Unitech/pm2#3252]
## What's going wrong?
I have node application hosted in amazon ec2. I used nginx to point it in my domain. It runs perfectly when i use npm start to run the application. But when i use pm2, it doesnt work.

pm2 list command shows that the app is running.

But url doesn't work. Even when i again run npm start app gets started that clearly states that the port is free. So pm2 is not actually running anything on that port. But pm2 says app is online.

I am asuming something is wrong with installing pm2. 

## How could we reproduce this issue?
What i did is just installed pm2 globally using sudo. and started the app using pm2 start command. Tried these instructions as well.
https://github.com/Unitech/pm2/issues/837

## Supporting information
Created a question on stackoverflow. But no answers.
https://stackoverflow.com/questions/47010434/pm2-is-not-working-in-amazon-ec2-with-node-application

**Comment by ahsanaasim** [comment]
## Solved the issue
Uninstalled pm2.
Created a new user with root permission. 
installed pm2 again. 

The problem was i was running app.js. As it was a express project. So i had to start bin/www.
I tried the following command and it started working.
pm2 start bin/www

**Comment by XtremyS** [comment]
Thanks alot brother mine started working too!.
