### ISSUE TITLE
TypeError: Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by phiresky** [Unitech/pm2#3256]
This crashed my server.

https://github.com/Unitech/pm2/blob/70199f47f239b0ddb59a73bdc61a692cd4681b43/lib/Client.js#L401-L406
Seems like this code:

```js
    timer = setTimeout(function() {
      if (Client.client_sock.destroy)
        that.client_sock.destroy();
      that.client = null;
```

should be

```js
    timer = setTimeout(function() {
      if (that.client_sock.destroy)
        that.client_sock.destroy();
      that.client = null;
```

**Comment by phiresky** [comment]
This issue is still happening, and fairly annoying because it's impossible to catch outside the library. It's a pretty obvious typing mistake and a simple fix. @Unitech  could you please fix it? Thanks

**Comment by Unitech** [comment]
sorry, I haven't noticed your message, you could send a PR to make this faster.
Will be released next time, best

**Comment by phiresky** [comment]
Thank you.

**Comment by xu3891621** [comment]
I had the same problem,when will it be settled @Unitech
