### ISSUE TITLE
cluster mode for Python

### ISSUE THREAD

**Issue by sarkistlt** [Unitech/pm2#3260]
Hi, actually quick question. Is it a way to run python script in a cluster mode, similar to Node?

It works fine in fork mode, but didn't find any information about how to run anything besides JS in a cluster mode.

~~~json
{
  "apps": [
    {
      "name": "Python-API",
      "script": "./scripts/webapp.py",
      "interpreter": "python",
      "instances": 0,
      "exec_mode" : "cluster",
      "env": {
        "ENV": "development"
      },
      "env_production": {
        "ENV": "production"
      }
    }
  ]
}
~~~

config above won't work, only if I will remove instances and run it in fork mode

**Comment by sarkistlt** [comment]
related issue is #2323, but when I'm forcing fork mode with specified instances, it runs one instance fine and the rest is continuously restarting

**Comment by sarkistlt** [comment]
I think the reason is because I'm running service, and [host]:[port] already in use when using fork mode, don't have that problem with JS files when running it in cluster mode.

**Comment by vmarchaud** [comment]
Not supported, the cluster is a technology implemented inside NodeJS see https://nodejs.org/dist/latest-v8.x/docs/api/cluster.html#cluster_how_it_works

**Comment by slidenerd** [comment]
Just make a single python process and add the multiprocessing module to run parallel code, Python does not have the same limitations as node does with respect to processors
