### ISSUE TITLE
restart python script infinitly 

### ISSUE THREAD

**Issue by CyrusLiu158** [Unitech/pm2#3261]
when i run a python with status 'Process finished with exit code 0'.it is a successful end , but pm2 restart it infinitly . and set 'max_restarts' config no effect
env: python 2.7.11
daemon file:
{
  "apps": [
    {
      "name": "yf-dnn",
      "script": "app.py",
      "watch": true,
      "cwd": "./",
      "exec_interpreter": "./venv/bin/python",
      "max_memory_restart": "500M",
      "max_restarts"     : 5,
      "cron_restart"     : "30 2 * * *"
    }
  ]
}

**Comment by vmarchaud** [comment]
See the docs : 
```
number of consecutive unstable restarts (less than 1sec interval or custom time via min_uptime) before your app is considered errored and stop being restarted
```
You should use `autorestart: false` instead
