### ISSUE TITLE
run selective apps programmatically based on --env

### ISSUE THREAD

**Issue by kekkokk** [Unitech/pm2#3269]
Hi guys!
I cannot figure out how to start certain apps only if a certain --env parameter is passed to pm2.
I'd like to have one unique .config.js file with various apps (app1.js, app2.js, app3.js, ...) and their relative configurations.
but for example if I run pm2 in --env=production I don't want that app2.js is loaded.

**Comment by vmarchaud** [comment]
You can totally do it with a `ecosystem.config.js`, its simply a js script that must return the list, see http://pm2.keymetrics.io/docs/usage/application-declaration/#javascript-format

**Comment by kekkokk** [comment]
You probably misunderstood my question.

the list that the .js returns contains app1, app2, app3 but in the case of --env prod I'd like to only return app1 and app3.

How can I achieve this behavior?
