### ISSUE TITLE
'pm2 logs' why not support multiple lists？

### ISSUE THREAD

**Issue by BlackHole1** [Unitech/pm2#3270]
If I had three services (A, B, C)
```
┌──────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────┬───────────┬───────┬──────────┐
│ App name │ id │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem       │ user  │ watching │
├──────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼───────┼──────────┤
│ A        │ 0  │ fork │ 13904 │ online │ 0       │ 0s     │ 0%  │ 10.6 MB   │  bh   │ enabled  │
│ B        │ 1  │ fork │ 2016  │ online │ 0       │ 0s     │ 0%  │ 22.5 MB   │  bh   │ disabled │
│ C        │ 2  │ fork │ 15648 │ online │ 0       │ 0s     │ 0%  │ 31.9 MB   │  bh   │ disabled │
└──────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────┴───────────┴───────┴──────────┘
```

I just want to see A and B, But I can't do it.

because `pm2 logs` command only support `[id|name]` or `all`

Why don't add `pm2 logs ['A', 'B']`?

Translation from [Baidu](http://fanyi.baidu.com/)
Some of the meaning may not be clearly expressed, and if it causes obstacles in reading, I'm sorry

**Comment by vmarchaud** [comment]
You can do `pm2 logs /[AB/]` with a regex see http://pm2.keymetrics.io/docs/usage/log-management/#displaying-logs-in-real-time

**Comment by qaisjp** [comment]
> You can do `pm2 logs /[AB/]` with a regex see http://pm2.keymetrics.io/docs/usage/log-management/#displaying-logs-in-real-time

i think this should say `pm2 logs /[AB]/` instead.

a better (more general) example would be `pm2 logs "/(AppA|AppB)/"`
