### ISSUE TITLE
`pm2 --mini-list` wrong PID file path

### ISSUE THREAD

**Issue by jshkurti** [Unitech/pm2#3273]
```
pm2d version         : 2.7.2
node version         : 8.8.1
```
![pm2](https://user-images.githubusercontent.com/7647602/32674464-a62d6e42-c653-11e7-8e1b-2bb63c83e7ab.png)

`/home/joni/.pm2/pids/test-0.pid0.pid`
should be
`/home/joni/.pm2/pids/test-0.pid`

**Comment by Unitech** [comment]
Fixed.

Changelog: [2.9.0 CHANGELOG](https://github.com/Unitech/pm2/blob/master/CHANGELOG.md#290)
Introduced in version: 2.9.0

Update procedure:

```bash
npm install pm2 -g
pm2 update
```
