### ISSUE TITLE
Resource limit exceeded on startup

### ISSUE THREAD

**Issue by Pixelatex** [Unitech/pm2#3274]
## What's going wrong?
When running sudo pm2 startup ( as a non-root user)
I get the following error: 
>>> Executing systemctl start pm2-root
Job for pm2-root.service failed because a configured resource limit was exceeded. See "systemctl status pm2-root.service" and "journalctl -xe" for details.

Status and journal are not giving me any more details to help fix it.

## How could we reproduce this issue?
I doubt you can and it's most likely a server side issue but there is no documentation to be found on what to do in this case.

## Supporting information
The server is a digitalocean droplet ( 512 MB Memory / 20 GB Disk / AMS2 - Ubuntu NodeJS 6.11.2 on 16.04)

PM2 report: 
===============================================================================
--- PM2 REPORT (Sat Nov 11 2017 14:03:11 GMT+0000 (UTC)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.7.2
node version         : 6.11.5
node path            : undefined
argv                 : /usr/bin/node,/usr/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
uptime               : 55min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.7.2
node version         : 6.11.5
node path            : undefined
argv                 : /usr/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2630L 0 @ 2.00GHz
cpus nb              : 1
freemem              : 46206976
totalmem             : 512061440
home                 : /home/eward
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬──────┬──────┬────────┬─────────┬────────┬─────┬───────────┬──────┬──────────┐
│ App name │ id │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem       │ user │ watching │
├──────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────┼───────────┼──────┼──────────┤
│ server   │ 0  │ fork │ 5097 │ online │ 3632    │ 1s     │ 47% │ 35.6 MB   │ root │ disabled │
└──────────┴────┴──────┴──────┴────────┴─────────┴────────┴─────┴───────────┴──────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌──────────┬────┬──────┬──────┬────────┬─────────┬────────┬─────┬───────────┬──────┬──────────┐
│ App name │ id │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem       │ user │ watching │
├──────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────┼───────────┼──────┼──────────┤
│ server   │ 0  │ fork │ 5097 │ online │ 3632    │ 1s     │ 74% │ 36.1 MB   │ root │ disabled │
└──────────┴────┴──────┴──────┴────────┴─────────┴────────┴─────┴───────────┴──────┴──────────┘

**Comment by vmarchaud** [comment]
512M of RAM isn't enough for a javascript environment, you should have at least 1G. We cannot on anything on our side.

**Comment by Pixelatex** [comment]
Might be useful to add a recommended server spec in the documentation?

**Comment by lmj0011** [comment]
I have this issue also. see: https://github.com/Unitech/pm2/issues/2775#issuecomment-373254402

>512M of RAM isn't enough for a javascript environment, you should have at least 1G. We cannot do anything on our side.

Such a lazy answer, man. Devs needs docs

**Comment by wallet77** [comment]
@rmonnier is there any documentation on it ?

**Comment by lmj0011** [comment]
I ended up copying the systemd unit configuration file pm2 creates and removed `PIDFile=[path to pid file]` from it.

eg.

in `/etc/systemd/system/pm2-www.service` I have this.
```
[Unit]
Description=PM2 process manager
Documentation=https://pm2.keymetrics.io/
After=network.target

[Service]
Type=forking
User=www
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
Environment=PATH=/usr/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
Environment=PM2_HOME={{PATH_TO_USER_HOME}}/.pm2

ExecStart=/usr/lib/node_modules/pm2/bin/pm2 resurrect
ExecReload=/usr/lib/node_modules/pm2/bin/pm2 reload all
ExecStop=/usr/lib/node_modules/pm2/bin/pm2 kill

[Install]
WantedBy=multi-user.target
```

afterwards I ran these commands

```sh
  sudo systemctl daemon-reload;
  sudo systemctl enable pm2-www.service;
  sudo systemctl start pm2-www.service;
  sudo systemctl status pm2-www.service;
```
pm2-www.service was active after rebooting server

**Comment by agung07** [comment]
anyone resolve this issue?

**Comment by rknell** [comment]
https://github.com/Unitech/pm2/issues/3924

Killing PM2 before running startup seems to do the trick

**Comment by seanpierce** [comment]
@rknell this was the correct solution for me. I have way more ram than required, so the solution to "get more ram" was lazy advice. Thanks for diving into this.
