### ISSUE TITLE
pm2 crash while I stop an app

### ISSUE THREAD

**Issue by woshizoufeng** [Unitech/pm2#3275]
Hi,
pm2 crash while I stop an app. 

pm2 version: 2.4.5
node version: 7.10.0

pm2 log here:

> 2017-11-10 10:13:21: Stopping app:polaris/service/biz/sync_underwrite_result id:472
> 2017-11-10 10:13:21: ===============================================================================
> 2017-11-10 10:13:21: --- PM2 global error caught ---------------------------------------------------
> 2017-11-10 10:13:21: Time                 : Fri Nov 10 2017 10:13:21 GMT+0800 (CST)
> 2017-11-10 10:13:21: spawn ENOMEM
> 2017-11-10 10:13:21: Error: spawn ENOMEM
>     at exports._errnoException (util.js:1050:11)
>     at ChildProcess.spawn (internal/child_process.js:319:11)
>     at exports.spawn (child_process.js:378:9)
>     at /usr/local/services/nodev7.4.0/lib/node_modules/pm2/lib/TreeKill.js:33:14
>     at buildProcessTree (/usr/local/services/nodev7.4.0/lib/node_modules/pm2/lib/TreeKill.js:79:12)
>     at module.exports (/usr/local/services/nodev7.4.0/lib/node_modules/pm2/lib/TreeKill.js:32:5)
>     at Object.God.killProcess (/usr/local/services/nodev7.4.0/lib/node_modules/pm2/lib/God/Methods.js:223:7)
>     at God.stopProcessId (/usr/local/services/nodev7.4.0/lib/node_modules/pm2/lib/God/ActionMethods.js:265:9)
>     at Server.onmessage (/usr/local/services/nodev7.4.0/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/server.js:105:6)
>     at emitTwo (events.js:106:13)
>     at RepSocket.emit (events.js:194:7)
> 2017-11-10 10:13:21: ===============================================================================
> 2017-11-10 10:13:21: [PM2] Resurrecting PM2
> internal/child_process.js:319
>     throw errnoException(err, 'spawn');
>     ^
> 
> Error: spawn ENOMEM
>     at exports._errnoException (util.js:1050:11)
>     at ChildProcess.spawn (internal/child_process.js:319:11)
>     at Object.exports.spawn (child_process.js:378:9)
>     at Domain.<anonymous> (/usr/local/services/nodev7.4.0/lib/node_modules/pm2/lib/Daemon.js:47:49)
>     at Object.onceWrapper (events.js:293:19)
>     at emitOne (events.js:96:13)
>     at Domain.emit (events.js:191:7)
>     at Domain._errorHandler (domain.js:97:23)
>     at process._fatalException (bootstrap_node.js:301:33)
> 2017-11-10 10:14:18: ===============================================================================
> 2017-11-10 10:14:18: --- New PM2 Daemon started ----------------------------------------------------
> 2017-11-10 10:14:18: Time                 : Fri Nov 10 2017 10:14:18 GMT+0800 (CST)
> 2017-11-10 10:14:18: PM2 version          : 2.4.5
> 2017-11-10 10:14:18: Node.js version      : 7.10.0
> 2017-11-10 10:14:18: Current arch         : x64
> 2017-11-10 10:14:18: PM2 home             : /home/polaris/.pm2
> 2017-11-10 10:14:18: PM2 PID file         : /home/polaris/.pm2/pm2.pid
> 2017-11-10 10:14:18: RPC socket file      : /home/polaris/.pm2/rpc.sock
> 2017-11-10 10:14:18: BUS socket file      : /home/polaris/.pm2/pub.sock
> 2017-11-10 10:14:18: Application log path : /home/polaris/.pm2/logs
> 2017-11-10 10:14:18: Process dump file    : /home/polaris/.pm2/dump.pm2
> 2017-11-10 10:14:18: Concurrent actions   : 2
> 2017-11-10 10:14:18: SIGTERM timeout      : 1600
> 2017-11-10 10:14:18: ===============================================================================

**Comment by vmarchaud** [comment]
You don't have enough memory on your system, thats the meaning of the `ENOMEM` error
