### ISSUE TITLE
Suppress "Welcome Screen" when using --silent

### ISSUE THREAD

**Issue by centigrade-thomas-becker** [Unitech/pm2#3278]
## What's going wrong?
The Welcome Screen (the big ASCII PM2) should respect the --silent option.

I use pm2 to launch node processes inside docker containers. When a new container is created then pm2 prints the welcome screen in the log. Therefore the first 35 lines of each container log look like this:

```
container.service-foo |
container.service-foo |                         -------------
container.service-foo |
container.service-foo |                       PM2 process manager
container.service-foo |
container.service-foo | __/\\\\\\\\\\\\\____/\\\\____________/\\\\____/\\\\\\\\\_____
container.service-foo |  _\/\\\/////////\\\_\/\\\\\\________/\\\\\\__/\\\///////\\\___
container.service-foo |   _\/\\\_______\/\\\_\/\\\//\\\____/\\\//\\\_\///______\//\\\__
container.service-foo |    _\/\\\\\\\\\\\\\/__\/\\\\///\\\/\\\/_\/\\\___________/\\\/___
container.service-foo |     _\/\\\/////////____\/\\\__\///\\\/___\/\\\________/\\\//_____
container.service-foo |      _\/\\\_____________\/\\\____\///_____\/\\\_____/\\\//________
container.service-foo |       _\/\\\_____________\/\\\_____________\/\\\___/\\\/___________
container.service-foo |        _\/\\\_____________\/\\\_____________\/\\\__/\\\\\\\\\\\\\\\_
container.service-foo |         _\///______________\///______________\///__\///////////////__
container.service-foo |
container.service-foo |
container.service-foo |                        Getting started
container.service-foo |
container.service-foo |                         Documentation
container.service-foo |                         http://pm2.io/
container.service-foo |
container.service-foo |                       Start PM2 at boot
container.service-foo |                         $ pm2 startup
container.service-foo |
container.service-foo |                      Daemonize Application
container.service-foo |                        $ pm2 start <app>
container.service-foo |
container.service-foo |                      Monitoring/APM solution
container.service-foo |                     https://app.keymetrics.io/
container.service-foo |
container.service-foo |                         -------------
container.service-foo |
container.service-foo | [PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
container.service-foo | [PM2] PM2 Successfully daemonized
```

It would be nice if the Welcome Screen would respect the `--silent` option and not show itself in that case.

## How could we reproduce this issue?
Start pm2 with the option "--silent" on a host where the folder ~/.pm2 does not exist yet.

## Supporting information
Tested on pm2 2.4.6

**Comment by centigrade-thomas-becker** [comment]
As a workaround I added `pm2 status > /dev/null` to my startup file to "eat" the welcome screen.

**Comment by Unitech** [comment]
fixed, pending release

**Comment by Unitech** [comment]
Fixed.

Changelog: [2.9.0 CHANGELOG](https://github.com/Unitech/pm2/blob/master/CHANGELOG.md#290)
Introduced in version: 2.9.0

Update procedure:

```bash
npm install pm2 -g
pm2 update
```

**Comment by tjanson** [comment]
I’d appreciate if there was a way to silence the banner *only* (`--no-banner` or something). I’m in the same situation: lots of Docker container logs starting with the banner. But I’m actually interested in the regular output.

To be honest, as cool as the ASCII logo is, it’s pretty annoying in practice.

**Comment by OliverJAsh** [comment]
`PM2_DISCRETE_MODE=true` does the job but it probably hides other things as well which might not be desired.
