### ISSUE TITLE
why NODE_APP_INSTANCE is not sequence

### ISSUE THREAD

**Issue by puXiaoyi** [Unitech/pm2#3280]
app.js
```javascript
console.log("process instance id is:", process.env.NODE_APP_INSTANCE);
```
command.line
```shell
pm2 start app.js --no-daemon -i 0 
```
output
> 14:35:52 1|app      | process instance id is: 1
14:35:52 2|app      | process instance id is: 2
14:35:52 0|app      | process instance id is: 0
14:35:52 3|app      | process instance id is: 3

why NODE_APP_INSTANCE is not sequence?

I want to initialize db connection pool in one instance, so i compare the NODE_APP_INSTANCE with 0, but is seem to be wrong... how can i do ? sorry for my poor english.

**Comment by vmarchaud** [comment]
You can't know in advance which process will `console.log` first, the 0 is always the first launched by pm2 but after that its a race. You can just use `NODE_APP_INSTANCE === 0`
