### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by neophob** [Unitech/pm2#3285]
HI - thanks for PM2!

I do have a feature request.

Use Case:

- your startup a server, all services which are managed by pm2 are started at the same time
- because all services start at the same time, the system is overload and the application start time are not really deterministic anymore

Idea:

- allow to define a initial start delay time in ms, to delay the first start of a service.

what do you think about that?

**Comment by vmarchaud** [comment]
You can use `restart_delay` option see [docs](http://pm2.keymetrics.io/docs/usage/application-declaration/#control-flow)

**Comment by neophob** [comment]
thanks @vmarchaud - restart_delay is only applied when RESTARTING an application. however i would apply this delay when the application is STARTED
