### ISSUE TITLE
Failed to fetch http://apt.pm2.io/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found

### ISSUE THREAD

**Issue by evollu** [Unitech/pm2#3288]
I followed the steps here https://github.com/Unitech/pm2/wiki/Installing-PM2-with-APT
but when I do apt-get update I get error
`Failed to fetch http://apt.pm2.io/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found`

**Comment by Unitech** [comment]
We've added a note on the documentation about this way of installation being deprecated. We are going to rework this system. For now install it via `npm install pm2 -g`
