### ISSUE TITLE
pm2 web panel for control proccess

### ISSUE THREAD

**Issue by A1Gard** [Unitech/pm2#3289]
Hi dear developers

I love pm2 and it very very good idea for nodejs apps.

But I think some one can't use command easily , And I try to write a simple GUI web panel for control pm2 process.

and here is web panel repo : https://github.com/4xmen/pm2panel

I hope this will benefit for other one.

**Comment by Unitech** [comment]
Nice, if you have any feedback for me about the programmatic integration of PM2, please send it to me at contact@keymetrics.io
