### ISSUE TITLE
restart not watching

### ISSUE THREAD

**Issue by BusyHe** [Unitech/pm2#3293]
pm2.config.js
```
let config = {
    apps: [{
        name: 'jiegouhua',
        script: 'server.js',
        cwd: './',
        watch: [
            'server',
            'server.js',
            'server-config.js'
        ],
        error_file: './logs/err.log',
        out_file: './logs/out.log',
        log_date_format: 'YYYY-MM-DD HH:mm Z'
    }]
};
if (process.argv.length > 5) {
    config.apps[0].args = process.argv.splice(5).join(' ');
}
module.exports = config;

```
1. pm2 start pm2.config.js -- 8765 --noLogin `8765 --noLogin is my args`
![image](https://user-images.githubusercontent.com/17348825/33007620-86ae0e82-ce0a-11e7-9c4f-d3e95e7c443a.png)
watching is enabled

2. pm2 stop jiegouhua
![image](https://user-images.githubusercontent.com/17348825/33007652-a8f4e48e-ce0a-11e7-9aa7-00c3be730790.png)
watching is disabled

3. pm2 restart jiegouhua
![image](https://user-images.githubusercontent.com/17348825/33007676-c136f03c-ce0a-11e7-8894-10cb1e9b7816.png)
watching is disabled

why not watching is enabled

**Comment by vmarchaud** [comment]
Merging with https://github.com/Unitech/pm2/issues/2629

**Comment by BusyHe** [comment]
@vmarchaud  I don't know what I should do，can you help me

**Comment by vmarchaud** [comment]
@BusyHe Its looking like a bug from PM2, you cannot do much

**Comment by BusyHe** [comment]
@vmarchaud ok， now i stop id and start again
```
pm2 stop 0
```
restart
```
pm2 start pm2.config.js
```
