### ISSUE TITLE
There is a encoding mistake when use pm2 with pm2-intercome

### ISSUE THREAD

**Issue by sinbargit** [Unitech/pm2#3295]
See the below screenshot. 
![2017-11-21_115052](https://user-images.githubusercontent.com/16011848/33054595-27019476-ceb5-11e7-8707-f3dcfc643f2e.png)

There are some encoding mistake in it. My file is encoding in UTF-8.
What I do is: output log to the log-file via pm2 and pm2-intercom, and use the log4js midderware.Here is my pm2 configure

`{
            "name"   : "guoheng",
            "script" : "./index.js",
            "exec_mode": "cluster",
            "instances" : 2,
            "error_file"       : "./log/gameweb_error.log",
            "out_file"         : "./log/gameweb_info.log",
            "merge_logs"         : true,
            "log_date_format"  : "-",
            "max_memory_restart"  : "1024M"
        }`

By the way, is there any way to disable the timestamp of pm2 log?

**Comment by vmarchaud** [comment]
it's your terminal that doesn't support color, there are termcaps, you should try with `--no-color`
And for your second question, you can set `"log_date_format" : ""` it should works
