### ISSUE TITLE
CPU usage wrong in pm2 list

### ISSUE THREAD

**Issue by papakai** [Unitech/pm2#3299]
pm2 version in use: 2.6.1

See here:
![image](https://user-images.githubusercontent.com/229425/33071833-6d730612-cebd-11e7-9f7c-701197e82d6b.png)

Compared to the output of our monitoring app based on `pm2 jlist`
![image](https://user-images.githubusercontent.com/229425/33071880-9ae1c49e-cebd-11e7-8bda-a72102bcf032.png)

Output of `top` on that server:
![image](https://user-images.githubusercontent.com/229425/33071921-c043dcea-cebd-11e7-9db0-f20109a5b0ad.png)

`top` confirms that the values displayed in our monitoring app based on `pm2 jlist` are correct (about ~ 100%). `pm2 list` instead shows 1% for the affected processes.

**Comment by vmarchaud** [comment]
We use pidusage (https://github.com/soyuka/pidusage) to get the usage of a PID, its possible that the usage you see in the `pm2 list` are not the same that in top because its cached and only retrieved only each 5 seconds from memory, so you are looking at a old value. Either way open an issue on pidusage if you think the ouput is not correct.

**Comment by papakai** [comment]
@vmarchaud I am sure this is not affected by this 5s cache as we had this cpu usage monitored over 30 minutes. Honestly, as pm2 is not my project, shouldn't it be of Unitech's responsibility to forward such an error to the appropriate repository owners?

**Comment by papakai** [comment]
Please reopen this issue as this is not a cache issue. Thanks.

**Comment by vmarchaud** [comment]
It's pid usage that compute the value, so this issue doesn't belong to this repo. Remember that's an open source project, it's free so doesn't expect the maintainers to do all the work.

**Comment by papakai** [comment]
This is annoying - my screen shots show clearly that something is wrong but on pm2 side and also on pidusage side the issue is getting closed faster as I can say. Thus I am really asking myself how it is possible to get such issues fixed.

**Comment by soyuka** [comment]
@papakai the thing is that the value from `jlist` or `list` comes from the same method! Therefore it should be the same at a given time. Or maybe it's only visual (responsive cli-table)?

The CPU usage should be really close to the `top` computation, we use almost the same algorithm. 

If you want to be sure you can do something like this:

```
const pidusage = require('pidusage')
setInterval(function() {
pidusage.stat(myprocessid, function(err, stat) {
console.log(stat)
})
}, 1000)
```

By the way, if you want proper alerts when the CPU is really high, I'd advise you to consider using [Keymetrics](http://keymetrics.io) :).

**Comment by papakai** [comment]
Thanks for pointing on Keymetrics, but for now we use our own monitoring implementation based on pm2 jlist which is really sufficient.

**Comment by papakai** [comment]
So @vmarchaud looks like pm2 list might be affected - pm2 jlist and pm2 list use the same data source, but the output is different as shown. And as said: I can definitely confirm that this is not issued by the 5s data cache you mentioned above.
