### ISSUE TITLE
Running multiple npm scripts simultaneously

### ISSUE THREAD

**Issue by mayeaux** [Unitech/pm2#3303]
I am trying to run two npm scripts simultaneously like:

`$ pm2 start npm -- run memory --`
`$ pm2 start npm -- run cache --`

However, when I start the second script, it stops running the first process. How can I run them both simultaneously? 

Also, it would be great if it could display `cache` for example instead of just `npm`.

![screen shot 2017-11-21 at 1 14 42 pm](https://user-images.githubusercontent.com/7200471/33097216-3c85357e-cebe-11e7-8b99-ee496d1ddb88.png)

Anyway around these two issues? Thanks

**Comment by vmarchaud** [comment]
You can use `--name` to set a custom name for your script

**Comment by mayeaux** [comment]
Ty!

**Comment by slidenerd** [comment]
Instead of doing this, how to add them to ecosystem file?
