### ISSUE TITLE
"pm2 resurrect" without "pm2 startup"

### ISSUE THREAD

**Issue by lucasvall** [Unitech/pm2#3304]
So I have a “node” user under which my apps run. This user runs node using NVM.
As node user I cannot do "pm2 startup" but I can do this as root.
There are other tickets about this (for example: https://github.com/Unitech/pm2/issues/1413). This somehow may looks like it works, but not quite:

```
root> env PATH=$PATH:/home/node/.nvm/versions/node/ v6.12.0/bin pm2 startup -u node --hp /home/node"
```

The above does successfully create the start up script, but there is a problem in actual reboot of the machine: "pm2 resurrect" get’s executed as root, and although all apps are resurrected as node user and work fine, the pm2 version used is that of the root and not that of the node user’s NVM.

```
root> ps –aux
# … PM2 v2.4.4: God Daemon (/home/node/.pm2)
```

The version show there is different than that of node user. You can see after a reboot:

```
node> pm2 list
#>>>> In-memory PM2 is out-of-date, do:
#>>>> $ pm2 update
#In memory PM2 version: 2.4.4 // Root user version after a reboot
#Local PM2 version: 2.7.2 // Node user version. After “pm2 update” is the one running
```

Ultimately I want to remove node completely for the root user. In such case the "pm2 resurrect" won’t even work since it run as root.

So I’m looking at 2 options. One is running "pm2 resurrect" as node somewhere in the OS reboot process (like `/etc/rc.local`), doing:

```
root> runuser -l  node -c 'pm2 resurrect' // Will use node user’s NVM default version PM2
```

Furthermore, I don’t even need that. I can use the crontab (`@reboot /path/to/script.sh`), as node user, and run "pm2 resurrect" within a script (for example: https://askubuntu.com/questions/228304/how-do-i-run-a-script-at-start-up). NOTE: I could even edit the crontab as root and do the above "runuser" command.

Both of my options imply that “pm2 startup” script is not even needed.

Is there something that the script is doing that is necessary? Alternatively, how to make "pm2 resurrect" (in the start up script) run really as node?

**Comment by papakai** [comment]
@vmarchaud I know you're familiar with docker containers based on a nvm setup. Do you have any experience how to create a startup script under nvm (not root!) or any alternative solution?

Don't wonder that I am commenting here, Lucas and I, we're working for the same company.

**Comment by vmarchaud** [comment]
I can't debug it for you but you should check that the path that each client is using is the same (should be `/home/node/.pm2`), you can see it by activating debug :  `DEBUG=* pm2 ls`.
If you want to enforce it, use `PM2_HOME=/path/to/a/dir`

**Comment by crapthings** [comment]
same issue here, user install nvm, nvm install node then npm i -g pm2

pm2 startup doesn't create startup script

**Comment by papakai** [comment]
@vmarchaud 
```bash
pm2:paths pm2 home resolved to /home/node/.pm2 /home/node +0ms
  pm2:conf Using 2 parallelism (CONCURRENT_ACTIONS) +0ms
  pm2:client Using RPC file /home/node/.pm2/rpc.sock +0ms
  pm2:client Using PUB file /home/node/.pm2/pub.sock +0ms
  pm2:interface:daemon Getting interaction info +0ms
  pm2:interface:daemon [PING INTERACTOR] Trying to connect to Interactor daemon +1ms
  axon:sock connect attempt null:/home/node/.pm2/interactor.sock +0ms
  pm2:client [PING PM2] Trying to connect to server +4ms
  axon:sock connect attempt null:/home/node/.pm2/rpc.sock +2ms
  axon:sock error ENOENT +3ms
  axon:sock ignored ENOENT +0ms
  axon:sock connect +0ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +0ms
  axon:sock closing +1ms
  axon:sock closing 1 connections +0ms
  pm2:client Daemon alive +4ms
  axon:sock remove socket 0 +1ms
  pm2:client Launching RPC client on socket file /home/node/.pm2/rpc.sock +1ms
  axon:sock connect attempt null:/home/node/.pm2/rpc.sock +0ms
  axon:sock connect +1ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +2ms
  pm2:client RPC Connected to Daemon +1ms
  pm2:cli Now connected to daemon +0ms
  pm2:client Calling daemon method pm2:getVersion on rpc socket:/home/node/.pm2/rpc.sock +5ms
  pm2:client Calling daemon method pm2:getMonitorData on rpc socket:/home/node/.pm2/rpc.sock +2ms
  pm2:client Calling daemon method pm2:getMonitorData on rpc socket:/home/node/.pm2/rpc.sock +3ms

  # pm2 ls table

pm2:paths pm2 home resolved to /home/node/.pm2 /home/node +0ms
  pm2:conf Using 2 parallelism (CONCURRENT_ACTIONS) +0ms
  pm2:client Using RPC file /home/node/.pm2/rpc.sock +0ms
  pm2:client Using PUB file /home/node/.pm2/pub.sock +0ms
  pm2:interface:daemon Getting interaction info +0ms
  pm2:interface:daemon [PING INTERACTOR] Trying to connect to Interactor daemon +1ms
  axon:sock connect attempt null:/home/node/.pm2/interactor.sock +0ms
  pm2:client [PING PM2] Trying to connect to server +4ms
  axon:sock connect attempt null:/home/node/.pm2/rpc.sock +2ms
  axon:sock error ENOENT +3ms
  axon:sock ignored ENOENT +0ms
  axon:sock connect +0ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +0ms
  axon:sock closing +1ms
  axon:sock closing 1 connections +0ms
  pm2:client Daemon alive +4ms
  axon:sock remove socket 0 +1ms
  pm2:client Launching RPC client on socket file /home/node/.pm2/rpc.sock +1ms
  axon:sock connect attempt null:/home/node/.pm2/rpc.sock +0ms
  axon:sock connect +1ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +2ms
  pm2:client RPC Connected to Daemon +1ms
  pm2:cli Now connected to daemon +0ms
  pm2:client Calling daemon method pm2:getVersion on rpc socket:/home/node/.pm2/rpc.sock +5ms
  pm2:client Calling daemon method pm2:getMonitorData on rpc socket:/home/node/.pm2/rpc.sock +2ms
  pm2:client Calling daemon method pm2:getMonitorData on rpc socket:/home/node/.pm2/rpc.sock +3ms
```

That's the output of `DEBUG=* pm2 ls` for node user.
If I understood you correct, you requested to have both pm2 clients (root and node user) to point to /home/node/.pm2 for PM2_HOME, right?
On new machines, we won't have a root installation of node and thus also not of pm2. So basically the question is how to get the startup script working / generated just out of nvm / node user scope.

**Comment by papakai** [comment]
I got it working in ease. Here the procedure and things I stumbled about so that it allows @Unitech to further improve the startup script generator.

Here the debian release in use:
```bash
cat /etc/debian_version
8.6
```

under user "node" / nvm scope it did:
* pm2 startup
```bash
[PM2][ERROR] Init system not found
```
-> so auto-detection/-setup not working

* pm2 startup systemd //as we have a debian>=7 os (http://pm2.keymetrics.io/docs/usage/startup/#init-systems-supported points to systemd ...)
```bash
[PM2] To setup the Startup Script, copy/paste the following command:
sudo env PATH=$PATH:/home/node/.nvm/versions/node/v6.12.2/bin /home/node/.nvm/versions/node/v6.12.2/lib/node_modules/pm2/bin/pm2 startup systemd -u node --hp /home/node
```

* executing it:
```bash
node@fmonitoring:~$ sudo env PATH=$PATH:/home/node/.nvm/versions/node/v6.12.2/bin /home/node/.nvm/versions/node/v6.12.2/lib/node_modules/pm2/bin/pm2 startup systemd -u node --hp /home/node

-bash: sudo: command not found
```
Honestly I think the existance of sudo could be auto-detected so that the suggested command could be improved.

* ssh login as root and then
```bash
env PATH=$PATH:/home/node/.nvm/versions/node/v6.12.2/bin /home/node/.nvm/versions/node/v6.12.2/lib/node_modules/pm2/bin/pm2 startup systemd -u node --hp /home/node
```
Result:
```bash
[PM2] Init System found: upstart
-----------------------------------------------------------
 PM2 detected upstart but you precised systemd
 Please verify that your choice is indeed your init system
 If you arent sure, just run : pm2 startup
-----------------------------------------------------------
Platform systemd
Template
[Unit]
Description=PM2 process manager
Documentation=https://pm2.keymetrics.io/
After=network.target

[Service]
Type=forking
User=node
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
Environment=PATH=/home/node/.nvm/versions/node/v6.12.2/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
Environment=PM2_HOME=/home/node/.pm2
PIDFile=/home/node/.pm2/pm2.pid

ExecStart=/home/node/.nvm/versions/node/v6.12.2/lib/node_modules/pm2/bin/pm2 resurrect
ExecReload=/home/node/.nvm/versions/node/v6.12.2/lib/node_modules/pm2/bin/pm2 reload all
ExecStop=/home/node/.nvm/versions/node/v6.12.2/lib/node_modules/pm2/bin/pm2 kill

[Install]
WantedBy=multi-user.target

Target path
/etc/systemd/system/pm2-node.service
Command list
[ 'chmod +x /etc/systemd/system/pm2-node.service',
  'systemctl enable pm2-node',
  'systemctl start pm2-node',
  'systemctl daemon-reload',
  'systemctl status pm2-node' ]
[PM2] Writing init configuration in /etc/systemd/system/pm2-node.service
[PM2] Making script booting at startup...
>>> Executing chmod +x /etc/systemd/system/pm2-node.service
[DONE] 
>>> Executing systemctl enable pm2-node
/bin/sh: 1: systemctl: not found
[ERROR] Exit code : 127
[PM2][ERROR] systemctl enable pm2-node failed, see error above.
```
So this leaves me the questions:
* why init system upstart could be detected under root user but not under nvm scope / node user
* /bin/sh: 1: systemctl: not found -> this could be detected in advance to further improve the auto-detection?

* FINALLY: under root user:
```bash
env PATH=$PATH:/home/node/.nvm/versions/node/v6.12.2/bin /home/node/.nvm/versions/node/v6.12.2/lib/node_modules/pm2/bin/pm2 unstartup systemd -u node --hp /home/node
```

* nvm scope / node user
```bash
pm2 save
```
* Rebooting

working fine!

**Comment by papakai** [comment]
NOTE: the above targets to a clean system without any root installation of node.js / pm2. I suggest to clean a system up accordingly to only have a nvm installation so that side-effects can be avoided.
