### ISSUE TITLE
Need to run code in master

### ISSUE THREAD

**Issue by BobDickinson** [Unitech/pm2#3305]
I have looked at the PM2 clustering support and I'd like to take advantage of it.

My problem is that my application does work on the master (the cluster workers communicate to a shared cache on the master using IPC).  I don't see any way I can use PM2 and still get it to run my master code (it becomes the master itself, and only runs my app code as workers).  

Is there a way to indicate a module to be run as (from) master?

**Comment by vmarchaud** [comment]
Nope, the master is always the PM2 daemon, in your case i will suggest to implement the cluster inside your application and then launching it in fork mode
