### ISSUE TITLE
child_process fork when using pm2 cluster mod

### ISSUE THREAD

**Issue by feifeipan** [Unitech/pm2#3308]
HI guys,

There are two modules(sender and receiver).

The sender is running in pm2 cluster mod, and in sender.js
```
if(pm2.isMaster){  //NODE_APP_INSTANCE==0
    var n = child_process.fork("./receiver.js");
    ......
}

```

My question is: How can i get other sender process to communicate with the forked receiver.js?

**Comment by vmarchaud** [comment]
You cannot use `pm2.isMaster`, only `process.env.NODE_APP_INSTANCE === 0`
