### ISSUE TITLE
socket file been deleted in cluster mod

### ISSUE THREAD

**Issue by feifeipan** [Unitech/pm2#3310]
I create a server by listening socket path.

Here is my file "test.js" : 

```javascript
var path = require("path");
var net = require("net");
var os = require("os");
var fs = require("fs");

var socket_path = path.resolve(os.tmpdir(),"mytest.sock");

if(fs.existsSync(socket_path)){
	fs.unlinkSync(socket_path);
}

const server = net.createServer((c)=>{
	console.log("create server");


}).listen(socket_path, ()=>{
	console.log("server bound")
});

server.on("error", (err)=>{
	console.log("server error", err);
});

server.on("close", ()=>{
	console.log("server close");
});
```

When i use "pm2 start test.js", it works fine. But when i use "pm2 start test.js -i max", the socket file was deleted by pm2. (It works file when i use node command)

Env: Mac
Node: v6.12.0
PM2: v2.7.2

You may reproduce the problem, thanks.

**Comment by Unitech** [comment]
The issue is that when running in cluster, many processes are doing this:

```
if(fs.existsSync(socket_path)){
	fs.unlinkSync(socket_path);
}
```

You should better prefix socket_path with a random value
