### ISSUE TITLE
Create script in Debian 9 Stretch without sudo

### ISSUE THREAD

**Issue by jonabasque** [Unitech/pm2#3311]
Hi,
I am trying to create a start script in Debian 9 without sudo and for a non-root user.

If I try to execute the following command with the 'atseden' user;
**$  pm2 startup systemd -u atseden --hp /home/atseden**
I get the following result;
**[PM2] Init System found: systemd
[PM2] To setup the Startup Script, copy/paste the following command:
sudo env PATH=$PATH:/home/atseden/.nvm/versions/node/v6.12.0/bin pm2 startup systemd -u atseden --hp /home/atseden**

Ok, then I understand that I have to execute it as root, I exit the user 'atseden' and execute;
**# env PATH=$PATH:/home/atseden/.nvm/versions/node/v6.12.0/bin pm2 startup systemd -u atseden --hp /home/atseden/ghost-0.11.9/**
I get the following result;
**[PM2] Init System found: systemd
Platform systemd
Template
[Unit]
Description=PM2 process manager
Documentation=https://pm2.keymetrics.io/
After=network.target**

**[Service]
Type=forking
User=atseden
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
Environment=PATH=/home/atseden/.nvm/versions/node/v6.12.0/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
Environment=PM2_HOME=/home/atseden/.pm2
PIDFile=/home/atseden/.pm2/pm2.pid**

**ExecStart=/home/atseden/.nvm/versions/node/v6.12.0/lib/node_modules/pm2/bin/pm2 resurrect
ExecReload=/home/atseden/.nvm/versions/node/v6.12.0/lib/node_modules/pm2/bin/pm2 reload all
ExecStop=/home/atseden/.nvm/versions/node/v6.12.0/lib/node_modules/pm2/bin/pm2 kill**

**[Install]
WantedBy=multi-user.target**

**Target path
/etc/systemd/system/pm2-atseden.service
Command list
[ 'chmod +x /etc/systemd/system/pm2-atseden.service',
  'systemctl enable pm2-atseden',
  'systemctl start pm2-atseden',
  'systemctl daemon-reload',
  'systemctl status pm2-atseden' ]
[PM2] Writing init configuration in /etc/systemd/system/pm2-atseden.service
[PM2] Making script booting at startup...
~ >>> Executing chmod +x /etc/systemd/system/pm2-atseden.service
[DONE] 
~ >>> Executing systemctl enable pm2-atseden
Configuration file /etc/systemd/system/pm2-atseden.service is marked executable. Please remove executable permission bits. Proceeding anyway.
[DONE] 
~ >>> Executing systemctl start pm2-atseden
Failed to get D-Bus connection: Unknown error -1
[ERROR] Exit code : 1
[PM2][ERROR] systemctl start pm2-atseden failed, see error above.**

I do not understand what the problem is, I suppose someone else will be with my same scenario (Debian without sudo and non-root user with NVM & node), I hope you can help me.

regards!!

**Comment by vmarchaud** [comment]
Because you don't have `sytemctl` in your path (the CLI used to manage systemd service), you should use only `pm2 startup` to see which init system can found on your system.
Anyway it must be an issue on your system, i'm closing the issue

**Comment by vmarchaud** [comment]
`Failed to get D-Bus connection: Unknown error -1` 
You should check inside your syslog because its definitely not related to PM2, the script here is just running specific `systemctl` command.
