### ISSUE TITLE
pm2 ls memory data is not accurate

### ISSUE THREAD

**Issue by buzai** [Unitech/pm2#3319]
when i use pm2 run a project and run pm2 ls

it tell the project olly use 30m ram

but when i use htop i find it use 30% all of server`s ram

env:
node v7.6.0
Ubuntu 12.04.5 LTS \n \l
pm2 2.4.2

**Comment by soyuka** [comment]
htop may compute memory usage differently. 

Is your process using child processes? Can you give more details about the server (htop/pm2 outputs for example)? Could you give a reproducible case?

**Comment by buzai** [comment]
@soyuka 
![2017-11-30 08-56-15](https://user-images.githubusercontent.com/12568747/33407504-9fc57b86-d5ac-11e7-91b7-9f651bfc65fb.png)

**Comment by buzai** [comment]
root@iZ23s7jv21bZ:~# pm2 ls
┌──────────────────────┬────┬─────────┬───────┬────────┬─────────┬────────┬─────┬───────────┬──────────┐
│ App name             │ id │ mode    │ pid   │ status │ restart │ uptime │ cpu │ mem       │ watching │
├──────────────────────┼────┼─────────┼───────┼────────┼─────────┼────────┼─────┼───────────┼──────────┤
│ community            │ 15 │ fork    │ 22181 │ online │ 2       │ 37D    │ 0%  │ 26.6 MB   │ disabled │
│ datamining_9003      │ 25 │ fork    │ 26273 │ online │ 6       │ 6D     │ 0%  │ 28.4 MB   │ disabled │
│ datamining_test_8003 │ 24 │ fork    │ 29851 │ online │ 24      │ 16h    │ 0%  │ 30.4 MB   │ disabled │
│ retrieval            │ 19 │ fork    │ 22203 │ online │ 2       │ 37D    │ 0%  │ 26.7 MB   │ disabled │
│ server_entry_9206    │ 22 │ cluster │ 22197 │ online │ 8       │ 37D    │ 0%  │ 38.5 MB   │ disabled │
│ server_entry_9206    │ 23 │ cluster │ 22230 │ online │ 8       │ 37D    │ 0%  │ 38.2 MB   │ disabled │
│ statisticsollect     │ 5  │ fork    │ 1738  │ online │ 262     │ 8h     │ 0%  │ 27.5 MB   │ disabled │
│ yonghuixingweiUse    │ 8  │ fork    │ 22125 │ online │ 2       │ 37D    │ 0%  │ 37.5 MB   │ disabled │
│ yonghuxingwei        │ 12 │ fork    │ 22166 │ online │ 2       │ 37D    │ 0%  │ 56.5 MB   │ disabled │
└──────────────────────┴────┴─────────┴───────┴────────┴─────────┴────────┴─────┴───────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app

**Comment by buzai** [comment]
![2017-11-30 08-59-16](https://user-images.githubusercontent.com/12568747/33407545-c9b3e4e6-d5ac-11e7-826d-af4c198ab748.png)

**Comment by buzai** [comment]
![2017-11-30 09-00-35](https://user-images.githubusercontent.com/12568747/33407591-071365f0-d5ad-11e7-9621-d5fcba1c3431.png)

**Comment by buzai** [comment]
now in htop it is 14% ,  it use   cluster start express, but only start  1.

**Comment by buzai** [comment]
config is :
```
module.exports = {
    //多进程模式下的子进程数，为0时禁用多线程
    cluster: 1, //cpu_num,
    //出错挂掉后是否自动重启，仅当启用cluster时生效
    restart: true,
    //是否为开发调试模式,上线后改为false
    debug: false,
    //项目监听的端口
    port: 9003,
    //是否启用https
    https: true,
    //服务器超时设置（毫秒）
    timeout: 10000,
    //启动https的情况下，key和pem文件相对于主路径的位置
    keyfile: './key/ksbao'
};
```

pm2 start a js file . in this file 
```
﻿/**
 * 项目入口
 * v 1.1.160517
 */

//使用目录加载模块
var path = require('path');
var requireall = require('./modules/requireall'); //v1.0

//加载配置文件
var configPath = process.argv[2] ? './' + process.argv[2] : './config_formal';
var config = {};
requireall(path.join(__dirname, configPath), config);

//配置日志
var log4js = require('log4js');
log4js.configure(config.log4js);
var logger = log4js.getLogger('launch');

//多进程管理模块
var cluster = require('cluster');

//主程序脚本
var server = require('./server');

//启动程序
if (config.server.cluster && config.server.cluster > 0) {
    if (cluster.isMaster) {
        cluster.on('fork', function (worker) {
            worker.on('exit', function (code) {
                logger.fatal('worker=%d died with code=%d', worker.process.pid, code);
                if (code!=0 && config.server.restart) {
                    cluster.fork();
                }
            });
            worker.on('listening', function () {
                logger.info('fork process pid %d listening on port %d', worker.process.pid, config.server.port);
            });
        });
        for (var i = 0; i < config.server.cluster; i++) {
            cluster.fork();
        }
        logger.info('master process pid %d', process.pid);
    } else {
        server.start(config);
    }
}
else {
    server.start(config);
    logger.info('process pid %d listening on port %d', process.pid, config.server.port);
}

```

**Comment by soyuka** [comment]
I think that this is due to the fact that htop takes child processes into consideration whereas pm2 does not (when computing memory and cpu).

**Comment by buzai** [comment]
@soyuka but i just run one cluster

**Comment by soyuka** [comment]
Can you run `ps -o size -p 26273` (replace `-p` argument with the pid). Note that this will output the resident memory size and should match the one of pm2.

**Comment by buzai** [comment]
thank u , i find some like this

```
root     26273  0.3  0.3 932544 29292 ?        Ssl  Nov23  34:10 node /mnt/projects/datamining/launch_formal.js                  
root     26299  3.4 17.3 2606932 1422304 ?     S<l  Nov23 383:53 node /mnt/projects/datamining/launch_formal.js  
```

**Comment by soyuka** [comment]
exactly right this is why the results don't seem accurate, we only take the first process in the computation. I made a patch to start working on this (https://github.com/Unitech/pm2/pull/2879/files) but it slows the process of displaying data :|.

**Comment by buzai** [comment]
thank u very much
