### ISSUE TITLE
Problem with cluster

### ISSUE THREAD

**Issue by praveen4554** [Unitech/pm2#3320]
in pm2 cluster if i suppose to run the application like pm2 start app.js -i max --watch
1) it starts the application but the application is not running
2) if i stop one cluster it automatically stops other clusters and launches everything is happened
 Those are the problems.
My requirement is if one of the cluster process crashes or stop it need to restart the crashed process only or need to create another cluster process for the crashed process

**Comment by vmarchaud** [comment]
Please give us a way to replicate your issue and paste the content of `pm2 report` here

**Comment by praveen4554** [comment]
1. pm2 start app.js -i max 
let us say it creates 4 clusters with ids(0,1,2,3)  
2. pm2 stop 0
it stops the cluster 0
So currently running clusters are (1,2,3) and stopped cluster is 0

it is not creating any new cluster or automatically starts the cluster with id 0 

if one of cluster is stopped  or crashed it automatically starts the new cluster
