### ISSUE TITLE
Is it possible to kill PM2 daemon from process started using PM2

### ISSUE THREAD

**Issue by raeesaa** [Unitech/pm2#3322]
Hi,

I have come across a scenario where we need to kill PM2 daemon when an event is triggered from the process started via PM2. I tried adding following code in event listener, it kills the current process but does not kill the daemon,

```
pm2.connect(function(err) {
        if(err) {
                console.log(err);
        } else {
                console.log("pm2 connected!");
                pm2.killDaemon(function(err) {
                        if(err) {
                                console.log(err);
                        } else {
                                console.log("Daemon killed!");
                                process.exit(0);
                        }
                })
        }

})

```

Is it possible to achieve what I am trying to do?

**Comment by raeesaa** [comment]
@Unitech Could you please help me with this?

**Comment by stanleyxu2005** [comment]
Your shutdown code looks fine to me. I have a very similar setup as yours. But my code is not started with PM2. If the process of your code is started with pm2, I might recommend you first to detach this app from pm2 watch list and then run your shut down code.
