### ISSUE TITLE
Are there any events available to capture the exit/restart of the app?

### ISSUE THREAD

**Issue by ericpaulbasbas** [Unitech/pm2#3326]
## What's going wrong?
Just wondering if there are event listeners available to capture exit/restart events if pm2 is used programmatically. Since `forever-monitor` has events for exit and restart, pm2 should have it as well.

## Supporting information
I got this sample code from one of your docs, and don't see any listening mechanism even in the docs.

```
var pm2 = require('pm2');

// Connect or launch PM2
pm2.connect(function(err) {
  // Start a script on the current folder
  pm2.start('app.js', { name: 'app' }, function(err, proc) {
    if (err) throw new Error('err');

    // Get all processes running
    pm2.list(function(err, process_list) {
      console.log(process_list);

      // Disconnect to PM2
      pm2.disconnect(function() { process.exit(0) });
    });
  });
})
```

**Comment by Unitech** [comment]
https://github.com/Unitech/pm2/blob/f6c70529bbc04c0e1340e519eddb1534b952c438/test/interface/bus.spec.mocha.js#L94
cheers
