### ISSUE TITLE
PM2 start command was not executed in cron task

### ISSUE THREAD

**Issue by magenious** [Unitech/pm2#3330]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/Unitech/pm2/search?type=Issues) before creating one.

## How could we reproduce this issue?
In my cron task, I run 2 pm2 commands to start my processes, but I found first command executed successfully, but my second command was not executed all the time. 
code snipit:
```
var execAsync = function(script) {
    var timestamp = new Date().getTime();
    console.info(`timestamp: ${timestamp}, execute command: ${script}`);
    return exec(script, {async:true});
};

    console.info(`start redis`);
    execAsync(`pm2 start start_redis.js --log-date-format "YYYY-MM-DD HH:mm Z"`);
    execAsync(`pm2 start service_talker.js --log-date-format "YYYY-MM-DD HH:mm Z"`);
```

and my script log for the above code:
![image](https://user-images.githubusercontent.com/23720252/33607271-8412e3d0-d9fb-11e7-9687-c9e09aa4e14c.png)

the pm2 log:
![image](https://user-images.githubusercontent.com/23720252/33607376-e44c504c-d9fb-11e7-9271-ef75b7a4c746.png)

As you can see from the above logs, the time gap for the 2 pm2 commands was about 18ms， I thought this was not a challenge for pm2, but the second command was indeed not run. Then when I run the second pm2 command in CLI, it then could be started normally:
![image](https://user-images.githubusercontent.com/23720252/33607548-7e16f844-d9fc-11e7-9bb6-c759505f55be.png)

## Supporting information
My system: 64bit OS, x64 processor, win10 system
PM2 version: 2.8.0
node.js version: v6.10.2
Please run the following command (available on PM2 >= 2.6)

```
$ pm2 report
```

**Comment by vmarchaud** [comment]
You should just sleep for one second before each spawn, it could lead to race for spawning the pm2 daemon (so one process might be handled by a daemon that is not reachable anymore)

**Comment by magenious** [comment]
Hi, vmarchaud, Thanks for your comment.
