### ISSUE TITLE
Failed to start pm2-root.service: Unknown unit: pm2-root.service

### ISSUE THREAD

**Issue by anudeepakumar** [Unitech/pm2#3332]
pm2 -v
2.6.1

node -v
v8.4.0

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

> pm2 startup ubuntu

[PM2] Init System found: systemd
-----------------------------------------------------------
 PM2 detected systemd but you precised ubuntu
 Please verify that your choice is indeed your init system
 If you arent sure, just run : pm2 startup
-----------------------------------------------------------
Platform ubuntu
Template
[Unit]
Description=PM2 process manager
Documentation=https://pm2.keymetrics.io/
After=network.target

[Service]
Type=forking
User=root
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
Environment=PATH=/usr/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
Environment=PM2_HOME=/root/.pm2
PIDFile=/root/.pm2/pm2.pid

ExecStart=/usr/lib/node_modules/pm2/bin/pm2 resurrect
ExecReload=/usr/lib/node_modules/pm2/bin/pm2 reload all
ExecStop=/usr/lib/node_modules/pm2/bin/pm2 kill

[Install]
WantedBy=multi-user.target

Target path
/etc/systemd/system/pm2-root.service
Command list
[ 'chmod +x /etc/systemd/system/pm2-root.service',
  'systemctl enable pm2-root',
  'systemctl start pm2-root',
  'systemctl daemon-reload',
  'systemctl status pm2-root' ]
[PM2] Writing init configuration in /etc/systemd/system/pm2-root.service
[PM2] Making script booting at startup...
>>> Executing chmod +x /etc/systemd/system/pm2-root.service
[DONE]
>>> Executing systemctl enable pm2-root
Configuration file /etc/systemd/system/pm2-root.service is marked executable. Please remove executable permission bits. Proceeding anyway.
[DONE]
>>> Executing systemctl start pm2-root
Failed to start pm2-root.service: Unknown unit: pm2-root.service
See system logs and 'systemctl status pm2-root.service' for details.
[ERROR] Exit code : 1
[PM2][ERROR] systemctl start pm2-root failed, see error above.

**Comment by Unitech** [comment]
```
[PM2] Init System found: systemd

PM2 detected systemd but you precised ubuntu
Please verify that your choice is indeed your init system
If you arent sure, just run : pm2 startup
```

just type `pm2 startup` and no `pm2 startup ubuntu` and follow the instructions

**Comment by anudeepakumar** [comment]
Hi, I have tried with
`pm2 startup`
also..

# pm2 startup
[PM2] Init System found: systemd
Platform systemd
Template
[Unit]
Description=PM2 process manager
Documentation=https://pm2.keymetrics.io/
After=network.target

[Service]
Type=forking
User=root
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
Environment=PATH=/usr/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
Environment=PM2_HOME=/root/.pm2
PIDFile=/root/.pm2/pm2.pid

ExecStart=/usr/lib/node_modules/pm2/bin/pm2 resurrect
ExecReload=/usr/lib/node_modules/pm2/bin/pm2 reload all
ExecStop=/usr/lib/node_modules/pm2/bin/pm2 kill

[Install]
WantedBy=multi-user.target

Target path
/etc/systemd/system/pm2-root.service
Command list
[ 'chmod +x /etc/systemd/system/pm2-root.service',
  'systemctl enable pm2-root',
  'systemctl start pm2-root',
  'systemctl daemon-reload',
  'systemctl status pm2-root' ]
[PM2] Writing init configuration in /etc/systemd/system/pm2-root.service
[PM2] Making script booting at startup...
>>> Executing chmod +x /etc/systemd/system/pm2-root.service
[DONE]
>>> Executing systemctl enable pm2-root
Configuration file /etc/systemd/system/pm2-root.service is marked executable. Please remove executable permission bits. Proceeding anyway.
[DONE]
>>> Executing systemctl start pm2-root
Failed to start pm2-root.service: Unknown unit: pm2-root.service
See system logs and 'systemctl status pm2-root.service' for details.
[ERROR] Exit code : 1
[PM2][ERROR] systemctl start pm2-root failed, see error above.

**Comment by jaysee** [comment]
Hi,

Got same error here, on fresh debian 9,

`sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u USER --hp /home/USER` => seems to succeed

but can't start service : 
`service pm2-USER start` => `pm2-USER: unrecognized service`
nor using
`systemctl start pm2-USER` => `Failed to start pm2-USER.service: Unknown unit: pm2-USER.service
See system logs and 'systemctl status pm2-USER.service' for details.`, then `systemctl status pm2-USER.service` returns `Failed to get properties: No such interface ''`

anything ?
