### ISSUE TITLE
max_memory_restart seems like it's not working

### ISSUE THREAD

**Issue by ericpaulbasbas** [Unitech/pm2#3333]
## What's going wrong?
I got a script to start an app with `max_memory_restart` in the option and it's restarting to the set value.
## How could we reproduce this issue?
Below are my test codes. I got the `pm2 logs all` and `pm2 monit` open and I can see from `pm2 monit` that it's hitting the memory beyond the set value of `max_memory_restart`.

Thanks for the help.
```
//start.js
var pm2 = require('pm2');

pm2.connect(function (err) {
    if (err) {
        console.error(err);
        process.exit(2);
    }

    pm2.start({
        script: 'app.js',         // Script to be run
        max_memory_restart : "500M",
    }, function (err, apps) {
        if (err) throw err
    });
});
```

```
//app.js
runMemtest();
function runMemtest() {
    var arr = [];
    var val = 1;
    var max = 104642652;
    
    while (val < max) {
        val = val + 1;
        arr.push(val);
    }
    console.log('ARR1: ', arr.length);
}
```

**Comment by wallet77** [comment]
Hi @ericpaulbasbas ,

I made some tests, what you see in pm2 monit is the real time memory of your app.
But the memory check run into a setInterval which occurs every 30 second by default.

You can set this value with env variable PM2_WORKER_INTERVAL.
But keep in mind that between two checks your app can reach and even exceed the threshold "max_memory_restart".
