### ISSUE TITLE
Update pm2 ~ Issues when called using Octopus Deploy PowerShell Post-Deployment Script

### ISSUE THREAD

**Issue by KiraResari** [Unitech/pm2#3335]
Hello everyone,

I'm using Octopus Deploy for deployments of my project, and since the project relies on pm2, I wanted to add a post-deployment PowerShell Post-deployment script to the build step to update pm2. The script for this looks as follows:

```
npm install pm2@latest -g --silent
pm2 update --silent
```

This  works perfectly when I run it directly on the deloyment machine using PowerShell ISE.

However, when running it via Octopus Deploy, it apparently waited for some kind of user input, and caused the deployment step to run forever.

I have brought this to the attention of the Octopus Deploy staff, and they were able to reproduce the issue. According to their investigation, the issue seems to be with **pm2 update not liking running in a non-interactive PowerShell session**:

> From: Henrik Andersson (Support staff)
>
> Hi Kira,
> 
> Thanks for getting in touch!
> 
> It seems this is an issue with pm2 update not liking running in a non-interactive PowerShell session (which the Tentacle runs the script in), I've replicated this outside of Octopus by launching a PowerShell session in non-interactive mode and executing pm2 update.
> 
> I've tried to find a solution that works but have so far not been able to, you might want to raise an issue on the pm2 GitHub repo and see if they can provide a solution.
> 
> I'm sorry I don't have better news than that.
> 
> Thank you and best regards,
> Henrik

So, with this I want to raise this issue here.

Am I the first one who is experiencing this problem? And if not, what is a good way to resolve this?

Thanks in advance,
Kira Resari

**Comment by Vaane** [comment]
Having a similar issue with using `pm2 kill; pm2 resurrect`, command runs fine through Octopus Script runner but then seems to just hang infinitely until I restart the tentacle service on the server.

**Comment by IPWright83** [comment]
We're having the exact same issues with PM2 and Octopus. Currently trying to do a `pm2 delete {serviceName}` and if the service doesn't exist, it warns and then just hangs the process.

Unfortunately we've tried a few things and failed to get it work, likely outcome being we have to ditch PM2 which would be a shame.

**Comment by ngwwm** [comment]
It's still happening as of today. Did anyone get any solutions or workarounds?
