### ISSUE TITLE
Error of script's path resolution when using node_args

### ISSUE THREAD

**Issue by eole1712** [Unitech/pm2#3337]
PM2 version : 2.6.1
Node version : v8.9.1
Operating system : Mac OS Sierra 10.12.6

## What's going wrong?
Hi there.

I'm using @std/esm. When I do `node -r @std/esm .` to run my hello.js linked in package.json, it's works fine.
But when I'm trying to run it with pm2 via my config file : 
  {
    name: 'test',
    cwd: path.resolve(__dirname, 'test'),
    script: '.',
    node_args: '-r @std/esm',
  }

I have this error : 
service-pr | Error: EISDIR: illegal operation on a directory, read
service-pr |     at Object.fs.readSync (fs.js:675:18)
service-pr |     at tryReadSync (fs.js:540:20)
service-pr |     at Object.fs.readFileSync (fs.js:583:19)
service-pr |     at Object.Module._extensions..js (module.js:645:20)

If I replace <script: '.'> with <script: './lib/package.json'> it will work fine.

We can have EISDIR when we try to open a directory as a file so I think when we give some arguments to pm2, it stops trying to resolve script path like node does and just open it.

## How could we reproduce this issue?
 
Files:
---pm2.config.js
---/test
---/test/package.json
---/test/lib
---/test/lib/hello.js

pm2.config.js:
   module.exports = {
      apps: [{
            {
                name: 'test',
                cwd: path.resolve(__dirname, 'test'),
                script: '.',
                node_args: '-r @std/esm',
                exec_mode: 'cluster',
                instances: 1,
                trace: true,
             }
      }]
   };

/test/package.json:
   {
     "name": "test",
     "version": "0.0.0",
     "main": "./lib/hello.js"
   }

/test/lib/hello.js:
   console.log('Hello world');

## Supporting information

Please run the following command (available on PM2 >= 2.6)

/Users/ghukas_g/.pm2/pm2.log last 20 lines:
PM2        | 2017-12-07 12:55:48: App [test] with id [0] and pid [81848], exited with code [0] via signal [SIGINT]
PM2        | 2017-12-07 12:55:48: Starting execution sequence in -fork mode- for app name:test id:0
PM2        | 2017-12-07 12:55:48: App name:test id:0 online
PM2        | 2017-12-07 12:55:48: App [test] with id [0] and pid [81865], exited with code [0] via signal [SIGINT]
PM2        | 2017-12-07 12:55:48: Starting execution sequence in -fork mode- for app name:test id:0
PM2        | 2017-12-07 12:55:48: App name:test id:0 online
PM2        | 2017-12-07 12:55:48: App [test] with id [0] and pid [81882], exited with code [0] via signal [SIGINT]
PM2        | 2017-12-07 12:55:48: Starting execution sequence in -fork mode- for app name:test id:0
PM2        | 2017-12-07 12:55:48: App name:test id:0 online
PM2        | 2017-12-07 12:55:48: App [test] with id [0] and pid [81899], exited with code [0] via signal [SIGINT]
PM2        | 2017-12-07 12:55:48: Starting execution sequence in -fork mode- for app name:test id:0
PM2        | 2017-12-07 12:55:48: App name:test id:0 online
PM2        | 2017-12-07 12:55:48: App [test] with id [0] and pid [81916], exited with code [0] via signal [SIGINT]
PM2        | 2017-12-07 12:55:48: Starting execution sequence in -fork mode- for app name:test id:0
PM2        | 2017-12-07 12:55:48: App name:test id:0 online
PM2        | 2017-12-07 12:55:48: App [test] with id [0] and pid [81933], exited with code [0] via signal [SIGINT]
PM2        | 2017-12-07 12:55:48: Starting execution sequence in -fork mode- for app name:test id:0
PM2        | 2017-12-07 12:55:48: App name:test id:0 online
PM2        | 2017-12-07 12:55:48: App [test] with id [0] and pid [81950], exited with code [0] via signal [SIGINT]
PM2        | 2017-12-07 12:55:48: Script /Users/ghukas_g/Work/Brigad/brigad-back-end/test had too many unstable restarts (16). Stopped. "errored"

**Comment by vmarchaud** [comment]
the `script` option doesn't work like `node` do, you need to tell him the exact file, even if its a `index.js`
