### ISSUE TITLE
windows Powershell is throwing error while running pm2 

### ISSUE THREAD

**Issue by BONDbATIF** [Unitech/pm2#3338]
#3319 Your issue may already be reported!
Please search on the [issue tracker](https://github.com/Unitech/pm2/search?type=Issues) before creating one.

i written one ps1 file which will run pm2 and electron .while running from powershell IDE ,i do not get any error and pm2 started sucessfully but when i try to run from powershell it is throwing error  The term 'pm2' is not recognized as the name of a cmdlet below is my ps file code 
 //D:\Users\gotam.b\AppData\Roaming\npm\pm2 
// & node $serverJsFilePath;
 pm2 start $serverJsFilePath;// this my js file 
 //Putting sleep time to start server after that lanuching electron.
 Start-Sleep -s 3
//to start the UI from electron .
//D:\Users\gotam.b\AppData\Roaming\npm\electron.cmd
 //D:\Users\gotam.b\AppData\Roaming\npm\electron.cmd electron. 
  electron $indexJsFilePath;

I set pm2 bin path to env variable .
let me if you need futher details .

**Comment by vmarchaud** [comment]
Please re-open an issue with the template filled.
