### ISSUE TITLE
Cluster on VM with 2 network interfaces?

### ISSUE THREAD

**Issue by EddieOne** [Unitech/pm2#3340]
## What's going wrong?

On a VM with 2 network interfaces, using express 4, If I define an ip say '0.0.0.0' I get address in use error because of pm2 cluster. Maybe it's a clerical error in the docs, it wasn't clear how to achieve this when using pm2 cluster. I mean how to target a specific interface. No issues with port.

Doesn't work
`http.createServer(app).listen(8080, '0.0.0.0')`

Does work
`http.createServer(app).listen(8080)`

I ended up removing the interface as the fastest solution, maybe it's a bug or usage error.

## How could we reproduce this issue?

A VM with a local and internet interfaces. I think the local needs to be first. Run an express server, it should be only accessible from the local interface. But how to make it accessible to the other..

```
$ pm2 report
```

**Comment by vmarchaud** [comment]
I'm not able to reproduce : 
![image](https://user-images.githubusercontent.com/2820968/33940884-05ac6d60-e011-11e7-834a-2cc31382c995.png)
Could you give a sample that reproduce the problem ? Thanks

**Comment by EddieOne** [comment]
I didn't have time to retest, I can show you the gist of what is going on in my case though.

```
var express = require('express');
var https = require('https');
var http = require('http');
var app = express();

http.createServer(app).listen(80)
https.createServer(app).listen(443);

app.get('/', function(req, res) {
  res.send('oi');
});
```

My thinking, is maybe different ports are getting assigned different interfaces when using cluster mode with 2 nics.

**Comment by vmarchaud** [comment]
I'm not sure of my understanding of the situation but i tested with your example (on port 3000 because i don't want to run under root), and i'm still having normal behavior with your example : 
![image](https://user-images.githubusercontent.com/2820968/34037216-2f524a04-e188-11e7-9828-edf9a25cb92d.png)
If you have a sample example that reproduce a problem, don't hesitate to re-open :)

**Comment by EddieOne** [comment]
ok thanks, it's probably a network issue for me then. 😅
