### ISSUE TITLE
Please update moment

### ISSUE THREAD

**Issue by evheniy** [Unitech/pm2#3341]
nsp new problem with moment

Regular Expression Denial of Service

pm2@2.8.0 > cron@1.3.0 > moment-timezone@0.5.14 > moment@2.19.2 
pm2@2.8.0 > moment@2.19.2

https://nodesecurity.io/advisories/532

moment bug: https://github.com/moment/moment/issues/4328

**Comment by Unitech** [comment]
Fixed.

Changelog: [2.9.0 CHANGELOG](https://github.com/Unitech/pm2/blob/master/CHANGELOG.md#290)
Introduced in version: 2.9.0

Update procedure:

```bash
npm install pm2 -g
pm2 update
```
