### ISSUE TITLE
How to use Env variables

### ISSUE THREAD

**Issue by jeffersonest** [Unitech/pm2#3355]
how to use my enviroment vars, the tutorials is very wrong!
My code.

`module.exports = {
  apps : [
    {
      name              : 'marymaps',
      script            : 'server.js',
      watch             : true,
      autorestart       : false,
      log_date_format   : "YYYY-MM-DD HH:mm Z",
      error             : "./logs/server-js/stderr.log",
      env: {
        API_URL: "http://dev.api.marydrive.com/driver/ping" ,
        MONGO_URL : "mongodb://ec2-107-23-182-220.compute-1.amazonaws.com:27017/marydrivedb",
        NODE_ENV: "development",
      },
      env_prod : {
        API_URL: "http://api.marydrive.com/driver/ping" ,
        MONGO_URL : "mongodb://ec2-107-23-182-220.compute-1.amazonaws.com:27017/marydrivedb",
        NODE_ENV: "production",
      }
    }
  ]
};
`

**Comment by vmarchaud** [comment]
Please re-open an issue with the template filled and a clear explanation of whats happening
