### ISSUE TITLE
2.9.0 - Generated init script set with incorrect PM2_HOME path

### ISSUE THREAD

**Issue by rdamico** [Unitech/pm2#3356]
## What's going wrong?
On Amazon Linux (AMI) the `pm2 startup ...`  command generates an init script in which the PM2_HOME variable is set incorrectly (the value is set to `--hp` param without `/.pm2` appended).

This is causing PM2 start up (resurection) on system reboot to fail as it does not find the dump.pm2 process file created using `pm2 save`.

A side affect of this is that all PM2 runtime folders and files ending up in `--hp` on system init, manually starting PM2 (after sys start up, say pm2 kill & pm2 start cycle) these will he placed in `--hp/.pm2`

## How could we reproduce this issue?
Replace `<your_user>` and `<your_path>` as required 

1.  Set PM2 to start on system init.
```
sudo env PATH=$PATH:/usr/local/bin /usr/local/lib/node_modules/pm2/bin/pm2 startup systemv -u <your_user> --hp <your_path>
```

2. Open `/etc/init.d/pm2-app`. You should see the following line:
```
export PM2_HOME="<your_path>"
```

4. Start your application and action the `pm2 save` command. It will save the `dump.pm2` file to `<your_path>/.pm2`

5. Reboot system. You should find that PM2 is started but your applcation is not lauched as the init script seems to looking in `<your_path>` rather than `<your_path>/.pm2`
 
## Supporting information
PM2 Version: 2.9.0
Node: v6.11.5
NPM: 3.10.10

Let me know if its worthwhile running `pm2 report`

**Comment by Unitech** [comment]
Which amazon image exactly? We have not touched to initd.d script at all, we need to try this

**Comment by Unitech** [comment]
thanks bug reproduced and now fixed, publish will follow

**Comment by Unitech** [comment]
published

**Comment by Unitech** [comment]
To fix the issue:

```bash
$ npm install pm2 -g
$ pm2 update
$ pm2 unstartup
[... line to copy paste ...]
$ pm2 startup
[... line to copy paste ...]
```
