### ISSUE TITLE
Module are impossible to install without internet, offline

### ISSUE THREAD

**Issue by tefa-dev** [Unitech/pm2#3358]
Linked to [this issue](https://github.com/Unitech/pm2/issues/1509)

## What's going wrong?

``` pm2 install my-packed-module.tgz ``` calls npm/yarn to install dependencies. This is not ok for offline use.  This fails even with internet btw. I count on opening another issue when I will have more time.

## How could we reproduce this issue?

Shut down your router

## Supporting information

pm2 v2.9.1

**Comment by Unitech** [comment]
Your packed module should contain sub modules.
PM2 2.9.1 now use only NPM

**Comment by vmarchaud** [comment]
Could you try to untar the module then `pm2 install file://path/to/the/module` ?
