### ISSUE TITLE
Wrong os.tmpdir() when app started from pm2 but not when started from node app.js command

### ISSUE THREAD

**Issue by szamanis** [Unitech/pm2#3365]
## What's going wrong?
`os.tmpdir()` returns wrong folder when application runs from pm2.
The folder that it returns is `C:\Users\USER~1\AppData\Local\Temp\2\` 
If I stop the app from pm2 and I run my app from command `node app.js` then the folder is `C:\Users\USER~1\AppData\Local\Temp\3\` that is correct. If I stop from command and start from pm2 with `pm2 start theID` then i get the wrong tmpdir again.

Tried restart, stop, start but nothing.

Then I did `pm2 save`, `pm2 kill`, `pm2 update`, `pm2 resurrect` and the problem went away.

## How could we reproduce this issue?
Don't really know the only lead I can give you is that it was working and then it was not. Pm2 was running for at least a week.
## Supporting information
Short story, I use ExpressJS with `multer` to upload files in the temp folder and when the user save changes I move them into my app directory. If the user discard i just leave the files in temp to be recycled automatically.
Please run the following command (available on PM2 >= 2.6)

```
$ pm2 report
```

```
===============================================================================
--- PM2 REPORT (Fri Dec 22 2017 14:56:22 GMT+0200 (GTB Standard Time)) --------
===============================================================================
--- Daemon --------------------------------------------------------------------
pm2d version         : 2.8.0
node version         : 8.9.1
node path            : C:/Program Files/nodejs/node
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\USER\AppData\Roaming\npm\node_modules\pm2\lib\Daemon.js
argv0                : node
user                 : undefined
uid                  : N/A
gid                  : N/A
uptime               : 41min
===============================================================================
--- CLI -----------------------------------------------------------------------
local pm2            : 2.8.0
node version         : 8.9.1
node path            : C:/Program Files/nodejs/node
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\USER\AppData\Roaming\npm\node_modules\pm2\bin\pm2,report
argv0                : C:\Program Files\nodejs\node.exe
user                 : undefined
C:\Users\USER\AppData\Roaming\npm\node_modules\pm2\lib\API\Extra.js:70
        fmt.field('uid', process.geteuid());
                                 ^

TypeError: process.geteuid is not a function
    at C:\Users\USER\AppData\Roaming\npm\node_modules\pm2\lib\API\Extra.js:70:34
    at C:\Users\USER\AppData\Roaming\npm\node_modules\pm2\node_modules\pm2-axon-rpc\lib\client.js:45:10
    at Parser.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\pm2\node_modules\pm2-axon\lib\sockets\req.js:67:8)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at Parser._write (C:\Users\USER\AppData\Roaming\npm\node_modules\pm2\node_modules\amp\lib\stream.js:91:16)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at Parser.Writable.write (_stream_writable.js:290:11)
    at Socket.ondata (_stream_readable.js:639:20)

```

**Comment by Unitech** [comment]
mmmm I don't know much about the behavior of windows and temp folder. If there is a `Temp\2\` and `Temp\3\`, I guess there is a `Temp\1\` also

**Comment by szamanis** [comment]
I also dont know the behavior of temp in windows. I m telling you that requesting temp dir  using `os.tmpdir()` from a node instance it returns correct dir and then requesting from inside pm2 node instance will return the wrong dir. And the only way to fix that is by deleting all applications killing pm2 restarting machine and starting all applications again. 

Now it have happened again because I did a restart on machine and temp folder changed again to `temp\2` and after I did `pm2 resurrect` the temp folder was wrong again. 

What I have done is to go into `dump.pm2` and change all `temp\3` to `temp\2`. And after a `pm2 kill` and `pm2 resurrect` it works.

Can you please check.

Thank you again

**Comment by GreenRaccoon23** [comment]
I'm running into this issue as well. If I restart the system and run `pm2 resurrect`, then `os.tmpdir()` returns the wrong tmp dir (e.g., `...Temp\2` instead of  `...Temp\1`).

The root problem is that Windows changes the location of the tmp dir after the system restarts. `os.tmpdir()` returns the value of the `TMP` environment variable. When `pm2 resurrect` is run, the process is started with the same environment variables it was using when `pm2 save` was run.  Since the `TMP` environment variable was different before the system was restarted, `os.tmpdir()` will return the old tmp dir and not the current one.

One possible solution would be to add the ability to run something like `pm2 resurrect --update-env`. I'm not sure how difficult this would be or whether it would cause other problems though.
