### ISSUE TITLE
Update env while ignoring source code changes

### ISSUE THREAD

**Issue by James2516** [Unitech/pm2#3368]
Is it technically possible to implement a feature that restarts the app with updated environment variables (eg. from `*.config.js`), but ignores any source code changes (i.e. works even if the source code has been deleted from the server)?

**Comment by Unitech** [comment]
You could use [process actions](http://pm2.keymetrics.io/docs/usage/process-actions/) to change the behavior of your app at the runtime without requiring code change, else it's not possible
