### ISSUE TITLE
How can I combine the output and error logs?

### ISSUE THREAD

**Issue by dandv** [Unitech/pm2#337]
`forever` has a `-l` option that directs both STDOUT and STDERR of the app into the same file. This is useful as I can see after which operations (output via `console.log`) some error has occurred (output via `console.error`).

How can I do this with pm2?

**Comment by liukun** [comment]
Seems no good options here. My best bet is to use Heka or Logstash listening on TCP to manage logs yourself.

**Comment by soyuka** [comment]
#1996
