### ISSUE TITLE
Req Help Start/Stop Script daily 5-6 hour

### ISSUE THREAD

**Issue by AhrimanSefid** [Unitech/pm2#3371]
Hi All.
Me Need Help For Start/Stop Script daily 5-6 hour.
loop everyday 5-6 start next time stop 5-6.

**Comment by Unitech** [comment]
you can use the cron feature of pm2 via process files http://pm2.keymetrics.io/docs/usage/application-declaration/#control-flow

**Comment by AhrimanSefid** [comment]
sorry, athank you.
plz give me sample.
