### ISSUE TITLE
support forum

### ISSUE THREAD

**Issue by wyattbiker** [Unitech/pm2#3373]
Hi, Is there a support forum or is this it? Sorry for posting non bugs, just questions.
I have several questions could not find answers in the docs. I will list them here anyway.
Ubuntu 16.04. , NodeJS 9.3, PM2 latest.

- a) Where are the processes config files kept. I looked everywhere could not find one. 
- b) When using **pm2 ecosystem** is there a way to create from an existing app.
- c) Is there a way to change a flag _e.g. --watch_ without restart

**Comment by vmarchaud** [comment]
We don't have any forums, we currently only use the issues so no problem : 
- There are no persisted on the disk automaticly, you need to use `pm2 save` that will save a dump to `~/.pm2/dump.pm2`
- no
- no
