### ISSUE TITLE
Log configuration is ignored in cluster mode

### ISSUE THREAD

**Issue by juanpaulo** [Unitech/pm2#3384]
## What's going wrong?

Log configuration is ignored in cluster mode (log configuration below)

## How could we reproduce this issue?

Start and app in fork mode with the following configuration:

```
{
    name: 'pm2_app',
    script: 'server.js',
    log_date_format: 'YYYY-MM-DD HH:mm:ss',
    out_file: '~/pm2_app/logs/output.log',
    error_file: '~/pm2_app/logs/error.log',
    merge_logs: true
}
```

Stop and delete app then start in cluster mode using the following configuration:

```
{
    name: 'pm2_app',
    script: 'server.js',
    instances: 'max',
    exec_mode: 'cluster',
    log_date_format: 'YYYY-MM-DD HH:mm:ss',
    out_file: '~/pm2_app/logs/output.log',
    error_file: '~/pm2_app/logs/error.log',
    merge_logs: true
}
```

The app still starts but `pm2 logs name|id` will not output anything and the log configuration will be ignored and reset to default configuration (~/.pm2/pm2.log).

## Supporting information

Please run the following command (available on PM2 >= 2.6)

```
$ pm2 report
===============================================================================
--- PM2 REPORT (Thu Jan 04 2018 17:44:48 GMT+0900 (JST)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.9.1
node version         : 8.1.2
node path            : /usr/local/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : juanpaulo.gutierrez
uid                  : 1614662526
gid                  : 679754705
uptime               : 23min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.9.1
node version         : 8.1.2
node path            : /usr/local/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/bin/pm2,report
argv0                : node
user                 : juanpaulo.gutierrez
uid                  : 1614662526
gid                  : 679754705
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : darwin
type                 : Darwin
cpus                 : Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
cpus nb              : 4
freemem              : 22278144
totalmem             : 17179869184
home                 : /Users/juanpaulo.gutierrez
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬─────────┬───────┬────────┬─────────┬────────┬─────┬───────────┬─────────────────────┬──────────┐
│ App name │ id │ mode    │ pid   │ status │ restart │ uptime │ cpu │ mem       │ user                │ watching │
├──────────┼────┼─────────┼───────┼────────┼─────────┼────────┼─────┼───────────┼─────────────────────┼──────────┤
│ pm2_app  │ 0  │ cluster │ 96034 │ online │ 0       │ 11s    │ 0%  │ 41.5 MB   │ juanpaulo.gutierrez │ disabled │
│ pm2_app  │ 1  │ cluster │ 96035 │ online │ 0       │ 11s    │ 0%  │ 41.7 MB   │ juanpaulo.gutierrez │ disabled │
│ pm2_app  │ 2  │ cluster │ 96044 │ online │ 0       │ 11s    │ 0%  │ 41.9 MB   │ juanpaulo.gutierrez │ disabled │
│ pm2_app  │ 3  │ cluster │ 96063 │ online │ 0       │ 10s    │ 0%  │ 42.4 MB   │ juanpaulo.gutierrez │ disabled │
└──────────┴────┴─────────┴───────┴────────┴─────────┴────────┴─────┴───────────┴─────────────────────┴──────────┘
===============================================================================
```

**Comment by eddjlam** [comment]
Is there any update on this? I'm running into this same issue. But in my case the log_date_format is being ignored in cluster mode

my process file
`{
  "apps" : [{
    "name"        : "server",
    "script"      : "./lib/server.js",
    "instances"   : "max",
    "exec_mode"   : "cluster",
    "max_restarts": 3,
    "min_uptime"  : "5000",
    "log_date_format" : "YYYY-MM-DDTHH:mm:ss Z"
    }]
}`

produces this output
`Error: ENOENT: no such file or directory, open '/goshposh/web/lib/src/app/index.template.html'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at childProcess (/goshposh/web/lib/server.js:164:31)
    at Object.<anonymous> (/goshposh/web/lib/server.js:116:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at /home/ubuntu/.nvm/versions/node/v8.9.0/lib/node_modules/pm2/lib/ProcessContainer.js:331:23
Error: ENOENT: no such file or directory, open '/goshposh/web/lib/src/app/index.template.html'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at childProcess (/goshposh/web/lib/server.js:164:31)
    at Object.<anonymous> (/goshposh/web/lib/server.js:116:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at /home/ubuntu/.nvm/versions/node/v8.9.0/lib/node_modules/pm2/lib/ProcessContainer.js:331:23`

but if i put it into fork mode with this process file
`{
  "apps" : [{
    "name"        : "server",
    "script"      : "./lib/server.js",
    "instances"   : "max",
    "max_restarts": 3,
    "min_uptime"  : "5000",
    "log_date_format" : "YYYY-MM-DDTHH:mm:ss Z"
    }]
}`

i see timestamps in the logs
`2018-07-10T15:54:52 -07:00: Error: ENOENT: no such file or directory, open '/goshposh/web/lib/src/app/index.template.html'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at childProcess (/goshposh/web/lib/server.js:164:31)
    at Object.<anonymous> (/goshposh/web/lib/server.js:116:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v8.9.0/lib/node_modules/pm2/lib/ProcessContainerFork.js:83:21)
2018-07-10T15:54:52 -07:00: Error: ENOENT: no such file or directory, open '/goshposh/web/lib/src/app/index.template.html'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at childProcess (/goshposh/web/lib/server.js:164:31)
    at Object.<anonymous> (/goshposh/web/lib/server.js:116:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v8.9.0/lib/node_modules/pm2/lib/ProcessContainerFork.js:83:21)`

`pm2 report
===============================================================================
--- PM2 REPORT (Tue Jul 10 2018 15:58:40 GMT-0700 (PDT)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.10.2
node version         : 8.9.0
node path            : /home/ubuntu/.nvm/versions/node/v8.9.0/bin/pm2
argv                 : /home/ubuntu/.nvm/versions/node/v8.9.0/bin/node,/home/ubuntu/.nvm/versions/node/v8.9.0/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : ubuntu
uid                  : 1000
gid                  : 1000
uptime               : 414min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.10.2
node version         : 8.9.0
node path            : /home/ubuntu/.nvm/versions/node/v8.9.0/bin/pm2
argv                 : /home/ubuntu/.nvm/versions/node/v8.9.0/bin/node,/home/ubuntu/.nvm/versions/node/v8.9.0/bin/pm2,report
argv0                : node
user                 : ubuntu
uid                  : 1000
gid                  : 1000
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2666 v3 @ 2.90GHz
cpus nb              : 4
freemem              : 6951342080
totalmem             : 7841525760
home                 : /home/ubuntu
===============================================================================
--- PM2 list -----------------------------------------------`

**Comment by nsushain** [comment]
any update on this ? seeing this issue as well @Unitech

**Comment by constantx** [comment]
Seeing this as well, the log config is simply ignore and the pm2 process simply use the normal log out. Here's my config:

```
{
  "apps": [
    {
      "name"      : "app",
      "script"    : "./server/index.js",
      "exec_mode" : "cluster",
      "merge_logs": true,
      "error_file": "~/.pm2/logs/app-combined.log",
      "out_file": "~/.pm2/logs/app-combined.log",
      "env": {
        "instances": 1,
        "NODE_ENV": "development"
      },
      "env_staging": {
        "NODE_ENV": "staging"
      },
      "env_production" : {
        "instances" : "max",
        "NODE_ENV": "production",
        "exec_mode" : "cluster"
      }
    }
  ],
}
```

and here's what pm2 is using:

<img width="967" alt="image 2018-07-24 at 3 04 11 pm" src="https://user-images.githubusercontent.com/113969/43124969-e3bb9bda-8f52-11e8-97e0-261308b04b00.png">

**Comment by Unitech** [comment]
which pm2 version?

I've tried it with the PM2 3 and it works as expected:

![image](https://user-images.githubusercontent.com/757747/43132252-76333972-8f3b-11e8-8f8e-7aa666902fba.png)

![image](https://user-images.githubusercontent.com/757747/43132277-8a151c8a-8f3b-11e8-84a1-3c8f03c9c2ee.png)

**Comment by constantx** [comment]
I'm using `pm2@3.0.0`

**Comment by eddjlam** [comment]
I'm also using pm2@3.0.0 and it's not consistent sometimes the log will show the timestamp however java stack traces do not always show the timestamp
