### ISSUE TITLE
pm2 not updating NODE_ENV

### ISSUE THREAD

**Issue by saurav2501** [Unitech/pm2#3386]
I have set local and development NODE_ENV in pm2 config file. Initially I used local mode but when I tried to move from local to development mode using provided pm2 commands, it's not updating my NODE_ENV from local to development. I have tried following commands but none of them updated the NODE_ENV.
1) pm2 restart app.json --env development
2) pm2 reload app.json --env development
3) pm2 reload app.json --update-env development
4) pm2 restart app.json --update-env development

But while refreshing my page it's updating NODE_ENV. Kindly help through it may it's getting cached

**Comment by vmarchaud** [comment]
`--env` and `--update-env` are two different flag that doesnt have the same behavior : 
- `--env` is used to tell pm2 to pickup the dev environment from the `app.json`
- `--update-env` tell to the daemon to pickup the new environment sent by the CLI and inject it when restarting.
So you need to do `pm2 reload app.json --env development --update-env`

**Comment by saurav2501** [comment]
Thanks @vmarchaud for the reply. I have tried your given command but still it's not injecting development mode. This works only after refreshing the page and NODE_ENV changes from local to development. I think it's getting cached and not able to update the NODE_ENV while runnning the command.

**Comment by vmarchaud** [comment]
What do you mean by refreshing the page ?

**Comment by saurav2501** [comment]
My homepage which I get after starting my server

**Comment by vmarchaud** [comment]
Then it might be indeed your browser that is caching the view
