### ISSUE TITLE
Init system not found - Windows

### ISSUE THREAD

**Issue by Symous** [Unitech/pm2#3393]
Hi, When I run "pm2 startup" on Windows, it gave me an error that "Init system not found". How can I handle this ? Thanks!

OS: Windows 10 64 bit.
pm2 Version : 2.8

**Comment by vmarchaud** [comment]
`pm2 startup` only support unix systems see http://pm2.keymetrics.io/docs/usage/startup/#windows-consideration

**Comment by Symous** [comment]
Thanks my friend! :D

**Comment by HectorDiscord** [comment]
Hm so I can't use startup ? I have the same problem...

**Comment by youngaj** [comment]
Is there an alternative for windows?

**Comment by Unitech** [comment]
https://pm2.keymetrics.io/docs/usage/startup/#windows-consideration

**Comment by prmichaelsen** [comment]
Windows strikes again 😡

**Comment by derambakht** [comment]
https://www.npmjs.com/package/pm2-windows-startup

**Comment by Paladinhanxiao** [comment]
i use alpine on docker meet the same question

**Comment by faeztgh** [comment]
still nothing?!
