### ISSUE TITLE
sendDataToProcessId missing from types index.d.ts

### ISSUE THREAD

**Issue by Uniphix** [Unitech/pm2#3394]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/Unitech/pm2/search?type=Issues) before creating one.

## What's going wrong?
The type definition is missing sendDataToProcessId

## How could we reproduce this issue?
Just use typescript and try to use the function you can't without having it throw errors.   Error below:

error TS2339: Property 'sendDataToProcessId' does not exist on type 'typeof ...

## Supporting information

Please run the following command (available on PM2 >= 2.6)

```
$ pm2 report
```

**Comment by wallet77** [comment]
PM2 2.10.1 has been release:

```
$ npm install pm2@latest -g
$ pm2 update
```

**Comment by Uniphix** [comment]
Awesome @wallet77 I really appreciate it.  Having sendDataToProcessId warning/error driving me nuts.
