### ISSUE TITLE
Recurring issue with vizion, pm2 calling git status -s a ton of times

### ISSUE THREAD

**Issue by joshribakoff** [Unitech/pm2#3403]
pm2 completely takes down my dev box (Vagrant) because running `git status` there is slow. I don't want my process manager to run `git status`, I just want it to launch my process that's it. I tried the --no-vizion flag & also putting `vision: false` in the JSON, both have no effect on v2.9.1 of pm2.

To replicate, insert an error into a JS file. Each time pm2 attempts to restart the process, it also calls `git status -s` and calls `npm` a bunch of times (visible in output of `ps aux`). Furthermore, replace git with a process that just sleeps to observe them stacking up. This will simulate Vagrant, which has a slow filesystem due to Virtual Box. In a fast environment, it will complete quickly & exit. 

This seems to be a recurring issue, any way to get a permanent long term fix?

https://github.com/Unitech/PM2/issues/924
https://github.com/Unitech/PM2/issues/1074
https://github.com/Unitech/pm2/issues/1735
https://github.com/Unitech/pm2/issues/2867
https://github.com/Unitech/pm2/issues/3105

**Comment by neilrogers** [comment]
make sure you stop and delete the pm2 jobs then use --no-vizion flag. worked for me.
I used 

pm2 stop all ; pm2 delete all ; pm2 flush
