### ISSUE TITLE
if use pm2 to start server  will appear the console screen 'npm' about 5 second as picture.

### ISSUE THREAD

**Issue by linhhoang1234** [Unitech/pm2#3405]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/Unitech/pm2/search?type=Issues) before creating one.

## What's going wrong?
![image](https://user-images.githubusercontent.com/35241883/34912522-42a2dbdc-f916-11e7-957f-7e88133c2743.png)

## How could we reproduce this issue?
how to remove it?
## Supporting information

Please run the following command (available on PM2 >= 2.6)

```
$ pm2 report
```

**Comment by vmarchaud** [comment]
Duplicate https://github.com/Unitech/pm2/issues/2182
