### ISSUE TITLE
PM2 reload in cluster mode kill current connections

### ISSUE THREAD

**Issue by quydo** [Unitech/pm2#3407]
Hello team,

I have nodejs backend behind nginx proxy.

In nodejs backend I use PM2 for management, I started in cluster mode
ref: https://futurestud.io/tutorials/pm2-cluster-mode-and-zero-downtime-restarts

pm2 start index.js --name api -i 2 --watch  (1)

when I run command: pm2 reload api, there are some connections log 502 occur in nginx log, for example

OK 5.815 162.158.165.151 - - [16/Jan/2018:16:10:09 +0700] 502 "GET /api/v2/get_config?id=1235

I guess when I run command (1), pm2 will force x process and they can serve clients at this time, but It kill old processes (that serves some connections), instead of wait for they complete connections

I know nginx reload mechanism: nginx start new workers, all new connections will be served by these workers, and old workers will process old connections. After all old connections completed, it shutdown old nginx workers without downtime

Can I do this in PM2?

Thanks Team

**Comment by wallet77** [comment]
Hi @quydo,

Did you try "gracefulReload" option ?
