### ISSUE TITLE
pm2-docker edge case with auto-exit

### ISSUE THREAD

**Issue by Unitech** [Unitech/pm2#3408]
Greetings.

Recently one of our micro services running with pm2-docker inside a docker container abruptly went offline for no apparent reason with the simplest possible log:

{"log":"PM2 Daemon is dead\n","stream":"stderr","time":"2018-01-11T01:50:22.891420881Z"}

Any attempt to restart the docker was unsucesseful, again with the simplest possible log:

{"log":"Connecting...\n","stream":"stdout","time":"2018-01-11T10:29:35.369262203Z"} 
{"log":"..0 application online, exiting\n","stream":"stdout","time":"2018-01-11T10:29:36.565261564Z"} 
{"log":"Exiting PM2\n","stream":"stdout","time":"2018-01-11T10:29:36.571631221Z"}

**Comment by Unitech** [comment]
https://github.com/Unitech/pm2/commit/704ae518f5d7df0a631349e518d81cef51249a58

**Comment by wallet77** [comment]
PM2 2.10.1 has been released:
```
$ npm install pm2@latest -g
$ pm2 update
```
