### ISSUE TITLE
What is the maximu number of Apps I can start in my ecosystem? 

### ISSUE THREAD

**Issue by GoGross** [Unitech/pm2#3409]
What is the maximu number of Apps I can start in my ecosystem? I have 900 apps

`apps : [
		{
			name : 'MAIN Static',
			script : './https-static.js',
			port: 82,
			watch : true,
			max_memory_restart :'520M',
			ignore_watch : ['node_modules', 'logs','files','docs', 'doc_templates'],
			args : 'node',
			kill_timeout : 15000,
			//cwd: './nods/5n16XsxNKbEUdC5ZyaaDMMFJHEl6L96k/',
			env: {
				NODE_ENV: "development"
			}
		},{
			name : 'Gross',
			script : './https.js',
			port: 10000,
			instances : "max",
			exec_mode : "cluster",
			watch : true,
			max_memory_restart :'520M',
			ignore_watch : ['node_modules', 'logs', 'temp','files','docs', 'doc_templates'],
			args : 'node',
			kill_timeout : 15000,
			cwd: './nods/5n16XsxNKbEUdC5ZyaaDMMFJHEl6L96k/',
			env: {
				NODE_ENV: "development"
			}
		}`

900 of them

**Comment by wallet77** [comment]
Hi @GoGross,

There is no limitation in pm2.
You will have some memory or cpu limits but it depends on your machine/server sizing.
