### ISSUE TITLE
what is reload and restart diffrents?

### ISSUE THREAD

**Issue by buzai** [Unitech/pm2#3410]
i think in pm2: 
restart = kill all processid and start the apps;
reload =  kill app cluster process one by one ? or other method？

in some article reload achieves a 0-second-downtime reload. but why?

**Comment by wallet77** [comment]
hi @buzai,

In a next major release, so in PM3, we really want to have a more powerful 0-second-downtime system.
We will work on this soon, but basically, when reloading an app, pm2 should create new worker and keep old workers alive till they are processing some requests. And they exit when all operations are done.
Then we ensure, 0-second-downtime which is a very important feature when your application run in production.

**Comment by buzai** [comment]
@wallet77  u are right , i think  pm2 can listen old worker`s tcp active, if old worker dont has any tcp connect , it can be killed.
