### ISSUE TITLE
CRITICAL: Error : Error: [object Object], and all processes killed

### ISSUE THREAD

**Issue by dandv** [Unitech/pm2#342]
pm2 just killed and lost all my processes... What I did:
1. meteor bundle --debug myapp.tgz
2. rm -rf ~/prod/bundle
3. cd ~/prod; tar xzf ~/dev/myapp.tgz
4. pm2 restart 5

```
$ pm2 restart 5
Processing......
PM2 Restarting process by id 5
Processing......
PM2 Restarting process by id 5
Error : Error: [object Object]
10:42:13 [0s] dan:~/prod$ pm2 l
┌──────────┬────┬──────┬─────┬────────┬──────┬───────────┬────────┬────────┬──────────┐
│ App Name │ id │ mode │ PID │ status │ port │ Restarted │ Uptime │ memory │ err logs │
└──────────┴────┴──────┴─────┴────────┴──────┴───────────┴────────┴────────┴──────────┘
```

I know this isn't exactly easy to reproduce but I hope it might help. There's no useful log info in `pm2.log`.

**Comment by tomzhang** [comment]
hi, unitech. i just wonder in which condition that PM2's log feature will lost its function. i have been encountered this issue for many times.
