### ISSUE TITLE
Is there a specific reason p2-docker does not have an --attach flag?

### ISSUE THREAD

**Issue by AdrieanKhisbe** [Unitech/pm2#3427]
Hello,

I'm migrating some application to aws Elastic Container Services (ecs),
And I'm trying to get the logs working with cloudwatch.
So far we are launching the application with `pm2-docker` (2.6 (prior to no log by default)), and we by default does not see our log.
I saw in [Use PM2 with cloud provider](http://pm2.keymetrics.io/docs/usage/use-pm2-with-cloud-providers/) that for logging the `--attach` flag should be used. However it does not exist in neither `pm2-docker` and `pm2-runtime`

So I was wondering if there was a specific reason p2-docker does not have an --attach flag?
Is there another way to achieve the same behavior? (writing to stderr/stdout so that gets captured by cloudwatch).

Thanks in advance for your answer 😃

**Comment by Unitech** [comment]
the --attach flag is automatically added when running pm2-docker/pm2-runtime

Documentation has been updated
