### ISSUE TITLE
Feature Request: preserve old process when reload fails 

### ISSUE THREAD

**Issue by rokoroku** [Unitech/pm2#3429]
Sometimes we **reload** the existing process with newly bundled (transpiled) code, but the new bundled code often break the application. 

In this case, **pm2** can use old process without changing its state as `errored`. 
Just like **graceful stop & reload**, if pm2 couldn't get `ready` signal before `listen_timeout` (or get `error`), it can stash the new process and preserve the old process without sending kill signal.

This is a feature like blue-green deployment.

After taking some look at the source, it could be achieved with a simple boolean flag like `reloadOnlyAfterReady`.

Could it be a PR welcomed feature?

**Comment by wallet77** [comment]
Hi @rokoroku 

Yes it can definitely be a feature !
Do you want to take care of this ?

**Comment by rokoroku** [comment]
I'll try.

`wait_ready` already sounds like a feature for this, however, it kills old process anyway. 
May I add a flag like `reload_after_ready` ? any suggestion?

**Comment by pinkasey** [comment]
@Unitech 
Why was this Issue closed?
This feature is VERY MUCH IN NEED.

The behavior of "don't reload process X before process X-1 is done reloading _**SUCCESSFULLY**_" - is what we all want.
anyone who uses `pm2 reload` wants that.
No one wants their server to go completely down, during a bad deployment (deployment with a bug that prevents server from booting).

Won't anyone pick the glove from here?
After 7 years?
