### ISSUE TITLE
Logs not streaming to console

### ISSUE THREAD

**Issue by MrDrummer** [Unitech/pm2#3434]
## What's going wrong?
When doing `pm2 logs` new log entries are not getting shown. They used to.
I'm running a local node.js application which logs the loading process on startup. When (re)starting, the logs are not showing new logs.
When exiting logs and doing `pm2 logs` again, the old logs (that should have been streamed before) show up in the recent logs.

## How could we reproduce this issue?
No idea.

## Supporting information
Complete uninstall and reinstall does not fix this. I have also tried a different process and the same exact thing happens. I have *also* rebooted.

EDIT: To put it simply, it's like doing `pm2 logs --nostream`, but instead of auto-exiting logs, it just sits there (it doesn't say "streaming logs ... etc")

Report dump:
```===============================================================================
--- PM2 REPORT (Mon Jan 29 2018 00:59:55 GMT+0000 (GMT Standard Time)) --------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.9.3
node version         : 8.4.0
node path            : undefined
argv                 : D:\Software\NodeJS\node.exe,C:\Users\jacob\AppData\Roaming\npm\node_modules\pm2\lib\Daemon.js
argv0                : node
user                 : undefined
uid                  : N/A
gid                  : N/A
uptime               : 48min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.9.3
node version         : 8.4.0
node path            : undefined
argv                 : D:\Software\NodeJS\node.exe,C:\Users\jacob\AppData\Roaming\npm\node_modules\pm2\bin\pm2,report
argv0                : node
user                 : jacob
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : win32
type                 : Windows_NT **Edit: NT??? Windows 10.**
cpus                 : AMD FX(tm)-8320 Eight-Core Processor
cpus nb              : 8
freemem              : 9777438720
totalmem             : 17135693824
home                 : C:\Users\jacob
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────┬───────────┬───────┬──────────┐
│ App name │ id │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem       │ user  │ watching │
├──────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼───────┼──────────┤
│ nodebot  │ 0  │ fork │ 10800 │ online │ 1       │ 2m     │ 0%  │ 44.5 MB   │ jacob │ disabled │
└──────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────┴───────────┴───────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
C:\Users\jacob\.pm2\pm2.log last 20 lines:
PM2        | 2018-01-29 00:56:59: Stopping app:nodebot id:0
PM2        | 2018-01-29 00:56:59: App [nodebot] with id [0] and pid [10460], exited with code [1] via signal [SIGINT]
PM2        | 2018-01-29 00:56:59: pid=10460 msg=process killed
PM2        | 2018-01-29 00:56:59: Starting execution sequence in -fork mode- for app name:nodebot id:0
PM2        | 2018-01-29 00:56:59: App name:nodebot id:0 online```


Thanks in advance.

**Comment by MrDrummer** [comment]
Update: somehow it's randomly fixed itself.

**Comment by wallet77** [comment]
Hi @MrDrummer ,

Ok feel free to reopen it if you can reproduce.

**Comment by conglq** [comment]
I have the same issue :(. But no case to explain :)

**Comment by MrDrummer** [comment]
I got this issue again and to fix it I killed all node.js processes and then relaunched it. This of course contradicts my previous statement of rebooting, but I guess it's a method to try as soon as you notice this issue.

**Comment by MrDrummer** [comment]
OK, I just got this issue again. I beleive it's what happened the last time it happened to me.

To reproduce:
After a Windows 10 restart, start a node.js application with a batch file. (only flag is --name)

For me it has "spawning Daemeon" and doesn't do anything (didn't even start the app). I start it again and then it starts the app but doesn't show the logs. I know this because i do pm2 logs and restart the app. In my case i have a console.log when it's starting up, and the app is actually restarting, but isn't logged.

As I previously explained, to fix this I stop the app (important) then force exit via task manager all node.js processes (just the ones with the green icon). I start up the app again, it does its "spawning Daemeon" thing, close, restart and doing pm2 logs will work as expected.

Again, I'm not sure why a restart didn't fix it originally. ¯\_(ツ)_/¯

@wallet77 (IDK how to reopen tickets)

**Comment by mellmo** [comment]
on the same boat, using `tail -f` for now

**Comment by phalski** [comment]
I had the same issue (identical output aka no log steam), but not with `pm2 logs`. Instead I was starting an app with `pm2-runtime` that was not showing logs.

For some reason when I run `pm2 delete` with no args prior my target cmd, this fixes the issue for me:
```
# we need the || instead of && because 'pm2 delete' with no args prints help and exits 1
pm2 delete || pm2-runtime ...
```
This might work for `pm2 logs` as well.

**Comment by BoomerBoxer** [comment]
Having the same issue.

**Comment by rogerweb** [comment]
I was having the same problem and the root cause was a zombie pm2 process ("PM2 v3.2.1: God Daemon"). I just killed it and now everything is working fine.

```ps -ef | grep PM2```

**Comment by gtyamamoto** [comment]
Having the same issue, and it was after update pm2 to 3.2.2

**Comment by bruceCzK** [comment]
@rogerweb Yes. After kill all the zombie pm2 process, it works fine.
I think PM2 should do such things like automatically killing all other PM2 processes under the same user.

**Comment by MrDrummer** [comment]
Maybe a "pm2 kill" command? On windows there is a single command to kill all node processes, which is fine for me since it wont affect anything else running.

**Comment by flytbasepratap** [comment]
in Ubuntu, I had used "sudo pm2 kill ". and run process again it works for me...

**Comment by sindri55** [comment]
I had the same issue. i was enough for me to restart the pm2 server on nodejs

**Comment by nix-wolf** [comment]
Had this issue, a restart of my computer fixed it.

It was an apparently became an issue when it told me to update pm2, i wasnt going to because i was doing something else till i realized the logs were not tailing, but everytime I re-ran 'pm2 logs' the new logs would be there but it simply wouldnt tail, I updated the way the website exclaimed to do so and it didnt help, I restrarted the processes multiple times, and restarted pm2 nothing seemed to work so I tried a total reboot. IF this happens again I will try to pay attention and comment with more information if i can, this is only what I noticed now

**Comment by robertnicjoo** [comment]
even killing pm2 doesn't help, still can't stream logs.

**Comment by nix-wolf** [comment]
Hi?

**Comment by vegeman** [comment]
I faced the same issue today and I have a way might work for some cases.

If I use `sudo pm2 start XXX`, `pm2 logs` or any related script won't show the process information.
If I use `sudo pm2 logs` or any others related script with `sudo`, it works properly.

**Comment by nix-wolf** [comment]
That to me seems like a permission issue. Why are you starting processes
with sudo? I do not believe it would be a wise choice to run it as the
super user.

I know this isn't my case as I do not run it with sudo, but I'd assume that
if you did then the logs would only be visible to that use as they probably
would end up being owned by the super.

**Comment by vegeman** [comment]
It just a temporary testing environment and I want to expose 80 port straight from express.js.

**Comment by aghArdeshir** [comment]
I have the same issue using `pm2@4.5.1`. It happens randomly for me too.

For now I am using `tail -f`

**Comment by DaveSprague** [comment]
I was having the same issue with pm2@5.1.0 but I now realize I was starting the process incorrectly.  I was using:

sudo -u nodejs pm2 start app.py 

to start it, which I'd seen on this link: https://marketplace.digitalocean.com/apps/nodejs

but what I should have been using was simply:

pm2 start app.py 

Now I see the console.log and error messages correctly when I use:

pm2 logs

**Comment by kolchurinvv** [comment]
I sill have this issue. tried everything on in this thread. pm2@5.1.1 on Mac OS Big Sur

**Comment by arenddeboer** [comment]
Still very much an issue on Node.js 16.13.2 and 5.2.0

**Comment by Krylanc3lo** [comment]
Hello,

I have the same issue. Error log is working well but the console not is not displayed in real time and I need to reload the process to make it appears. any idea ?

thanks a lot!

**Comment by ridbay** [comment]
> I have the same issue using `pm2@4.5.1`. It happens randomly for me too.
> 
> For now I am using `tail -f`

What is the full command to use?

**Comment by tripower** [comment]
> Hello,
> 
> I have the same issue. Error log is working well but the console not is not displayed in real time and I need to reload the process to make it appears. any idea ?
> 
> thanks a lot!

have you found a solution?
I also do not see any logs in the dashboard but with "pm2 logs" on the machine I will see it in the CMD
I started the process with
pm2 start xxx.js /o ...
