### ISSUE TITLE
How to check current --env

### ISSUE THREAD

**Issue by morugu** [Unitech/pm2#3435]
I know that I can use `console.log(process.env.NODE_ENV);`.

is there a pm2 command?

Ex.
```
$ pm2 start pm2-config.json --env production // or develop or local
```

**Comment by wallet77** [comment]
Hi @morugu,

Unfortunately there is no such command in PM2.
I think it's easy, as you mentioned, with process.env.NODE_ENV to retrieve it.
But if it's relevant for many users we can open a PR.

**Comment by kenmorechalfant** [comment]
I second this being integrated with PM2 directly. However, I have found another solution that works great for now (at least for seeing the `NODE_ENV`): using **Process Metrics** aka PMX, as described [in the docs](http://pm2.keymetrics.io/docs/usage/process-metrics/)

`yarn add pmx`

In my Express app's `app.js`:
```
const Probe = require('pmx').probe()

Probe.metric({
  name    : 'NODE_ENV',
  value   : function() {
    return process.env.NODE_ENV
  }
})
```

Now it will show up in calls to `pm2 show appname` (bottom) or in `pm2 monit` (bottom left).
