### ISSUE TITLE
Crash: TypeError: Cannot read property 'call' of null

### ISSUE THREAD

**Issue by phiresky** [Unitech/pm2#3441]
Version 2.9.1

This is another issue, similar to #3256, but I can't figure out what it should be doing.

```
TypeError: Cannot read property 'call' of null
    at node_modules/pm2/lib/Client.js:514:25
    at node_modules/pm2/lib/Client.js:54:16
    at Timeout._onTimeout (node_modules/pm2/lib/Client.js:357:19)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

Around these lines: 

https://github.com/Unitech/pm2/blob/ce972e6913e449bed71cc70e90994f4a45c3e876/lib/Client.js#L508-L519

**Comment by wallet77** [comment]
Hi @phiresky 

any idea on how to reproduce this one ?

**Comment by phiresky** [comment]
Sadly no... this has happened randomly three times in the last few weeks on a process running 24/7. The functions I call are connect, list, describe, disconnect, stop, start, restart. It does not appear to correlate to calls to start/stop/restart.

**Comment by shaharmor** [comment]
this line `return self.client.call(method, app_conf, fn); ` should be wrapped with 
```js
if (self.client) {

}
```
