### ISSUE TITLE
pm2 install Debian 9.3 not working

### ISSUE THREAD

**Issue by knoxcard** [Unitech/pm2#3445]
Distributor ID: Debian
Description:    Debian GNU/Linux 9.3 (stretch)
Release:        9.3
Codename:       stretch

 **sudo npm install -g pm2**
/root/.npm-global/bin/pm2 -> /root/.npm-global/lib/node_modules/pm2/bin/pm2
/root/.npm-global/bin/pm2-docker -> /root/.npm-global/lib/node_modules/pm2/bin/pm2-docker
/root/.npm-global/bin/pm2-dev -> /root/.npm-global/lib/node_modules/pm2/bin/pm2-dev
/root/.npm-global/bin/pm2-runtime -> /root/.npm-global/lib/node_modules/pm2/bin/pm2-runtime

**whereis pm2**
pm2:

**Comment by wallet77** [comment]
Hi @knoxcard,

I can't reproduce this issue : 
Debian 9.3
Node : 8.9.4
Npm: 5.5.1

whereis pm2 : 
pm2: /home/vince/.nvm/version/node/v8.9.4/bin/pm2
