### ISSUE TITLE
pm2 doesn't keep process in list.

### ISSUE THREAD

**Issue by gormonn** [Unitech/pm2#3446]
pm2 doesn't keep process in list.
Sometimes, we find out that process is absent, however we don't see it in pm2 list with the status "mistake". It's confusing us. This normal behavior?
The possible reason of an exit from - a system - lack of connection with the Redis server.

**Comment by wallet77** [comment]
Hi @gormonn,

I don't really understand. What do you mean "porcess is absent" and status "mistake" ?

**Comment by gormonn** [comment]
"process is absent" that mean state like you kill all processes, and in `pm2 list` nothing will be found
status "mistake" - i'm sorry, i mean status "Errored"

**Comment by wallet77** [comment]
What is strange is if you kill a process, PM2 should restart it, so it will not appear as "errored" but "online".

Do you use specific arguments ? Like --no-autorestart ?

**Comment by gormonn** [comment]
no, i don't
How it is possible to define whether process by someone purposely has been removed?
