### ISSUE TITLE
deploy environment variable with spaces and single quotes acting strange

### ISSUE THREAD

**Issue by wasaylor** [Unitech/pm2#3449]
## What's going wrong?
In my ecosystem.json file, I have the deploy block with some environment variables. One variable is `CONTENT_SECURITY_POLICY` and the value is a content security policy with spaces and single quotes:
```
"env": {
…
"CONTENT_SECURITY_POLICY": "default-src 'none'; script-src 'self'; …"
…
}
```

So in the "executing post-deploy" step the spaces break the formatting when pm2 sets the environment:
```CONTENT_SECURITY_POLICY=default-src 'none'; script-src 'self'; …```
(attempts to execute script-src as if it were a program..)

I tried to change the line in ecosystem.json to this:
```
"CONTENT_SECURITY_POLICY": "\"default-src 'none'; script-src 'self'; …\""
```

But then the "executing post-deploy" step stops with:
```CONTENT_SECURITY_POLICY=` ```
And the rest of the post-deploy that should be present is missing

Ideally I want the format to look like this when setting the environment in post-deploy:
```CONTENT_SECURITY_POLICY="default-src 'none'; script-src 'self'; …"```

Any ideas?

## How could we reproduce this issue?

Create an ecosystem.json with an environment variable with spaces and single quotes.

## Supporting information

Please run the following command (available on PM2 >= 2.6)

```
pm2d version         : 2.9.1
node version         : 9.4.0
```
redacting the rest of the pm2 report. I'll add more if needed

**Comment by Xavier4492** [comment]
Hi, I have the same problem!
