### ISSUE TITLE
PM2 & Scoped private modules

### ISSUE THREAD

**Issue by daankets** [Unitech/pm2#3451]
## What's going wrong?
When installing a private/scoped PM2 module using `pm2 install @ourscope/api`, the NPM phase is going fine, after which pm2 tries to resolve package.json from the wrong directory (@ourscope is missing in the path). Strangely enough, exactly the same module can be installed on Mac, but not on Ubuntu 16.04.

## How could we reproduce this issue?
pm2 install any scoped module, and wait for the error trying to find package.json.

**my log:** The actual package.json is at `/opt/ouruser/.pm2/modules/api/node_modules/@ourscope/api/package.json` by the way...

```
[PM2][Module] Module downloaded
ENOENT: no such file or directory, open '/opt/ouruser/.pm2/modules/api/node_modules/api/package.json'
module.js:540
    throw err;
    ^

Error: Cannot find module '/opt/ouruser/.pm2/modules/api/node_modules/api/package.json'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (/usr/lib/node_modules/pm2/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at startModule (/usr/lib/node_modules/pm2/lib/API/Modules/Modularizer.js:268:22)
    at /usr/lib/node_modules/pm2/lib/API/Modules/Modularizer.js:203:7
    at /usr/lib/node_modules/pm2/lib/Configuration.js:64:14
    at FSReqWrap.oncomplete (fs.js:135:15)
```
(nothing relevant in pm2 report output)

**Comment by daankets** [comment]
I must stand corrected: it doesn't work on a Mac either. It only works when installing from the local dev directory, using `pm2 install .`. However, then it is not possible to _uninstall_ the module again (unless you didn't run pm2 save, then you can run pm2 update to get rid of it.

**Comment by daankets** [comment]
It's like @mattbrunetti mentioned in #3208. The canonicalisation of the module name is not handling the scoped modules correctly. `@scoped/` module is reduced to `module`.

**Comment by daankets** [comment]
I have forked the repo, and will issue a pull request when (and if) I can fix and test this.

**Comment by Unitech** [comment]
PM2 2.10.1 has been release:

```bash
$ npm install pm2@latest -g
$ pm2 update
```
