### ISSUE TITLE
PM2 Daemon is dead

### ISSUE THREAD

**Issue by stickyhands** [Unitech/pm2#3452]
Using PM2 inside docker, dies constantly then restart app, and dies again, etc...

```PM2 Daemon is dead```

node 8.9.0
PM2 2.9.3

**Comment by wallet77** [comment]
Hi @stickyhands,

Do you use your own docker file ?
Maybe this page can help you : http://pm2.keymetrics.io/docs/usage/docker-pm2-nodejs/

**Comment by stickyhands** [comment]
I already use "docker-runtime".
With my own dockerfile yes, I tried on a dockerfile that extends the official node (FROM node:8.9.0-slim or alpine where I then install PM2 inside) 
and then I tried with keymetrics/pm2:8-alpine

same behavior

**Comment by Unitech** [comment]
Could you try with the new pm2-runtime:

```
RUN npm install Unitech/pm2#development -g
CMD [ 'pm2-runtime', 'app.js' ]
```

**Comment by Unitech** [comment]
closing https://github.com/Unitech/pm2/issues/3266

**Comment by l00mi** [comment]
@Unitech Could you elaborate a bit on this please?
