### ISSUE TITLE
I can't install pm2-logrotate for Windows

### ISSUE THREAD

**Issue by moto-a** [Unitech/pm2#3456]
I tried install pm2-logrotate, but error was detected.

C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\lib\API\Modules\Modularizer.js:148
    process.chdir(process.env.HOME);
            ^

TypeError: Bad argument.
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\lib\API\Modules\Modularizer.js:148:13
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\mkdirp\index.js:48:26
    at FSReqWrap.oncomplete (fs.js:153:5)

Please tell me the solution.

Versions.
pm2    2.9.3
npm    5.5.1
node   8.9.3
Windows Server 2016 Standard

**Comment by wallet77** [comment]
hi @moto-a,

Could you put here what you have in variable : process.env.HOME ?
process.chdir can only fail if directory doesn't exist or if you don't have rights on it.

**Comment by moto-a** [comment]
Thank you for your reply.

process.env.HOME  is undefined.
I do not know why it is undefined.

**Comment by wallet77** [comment]
And if you force a value to your HOME variable does it work ?
It's probably an edge case.

**Comment by vmarchaud** [comment]
@wallet77 Not an edge case, the value of `HOME` is never set under windows, it's `HOME_DIR` from memory and also i don't see the point to `chdir` in this code.

**Comment by wallet77** [comment]
chdir is the function which throw an error because HOME variable is empty.
For windows it's USERPROFILE variable.

The best (generic) way to achieve this is to use require('os').homedir().

**Comment by preraksola** [comment]
When can we expect this to be released? I am still facing this issue in 2.10.3 version.

**Comment by wanganjun** [comment]
@preraksola 
Thanks @wallet77, i may find a solution.

```
set HOME=%USERPROFILE%
pm2 install pm2-logrotate
```

**Comment by wallet77** [comment]
Hi @preraksola 

I will be released with 3.0.0 version. But I don't know when exactly. I hope in a few weeks.

**Comment by moto-a** [comment]
>set HOME=%USERPROFILE%
>pm2 install pm2-logrotate

Awesome!!
Thanks to you, this problem has been solved.

**Comment by wallet77** [comment]
PM2 3.0.0 has been released:

$ npm install pm2@latest -g
$ pm2 update

Be aware of breaking changes, especially drop support for node 0.12.
Full list here : https://github.com/Unitech/pm2/blob/master/CHANGELOG.md
