### ISSUE TITLE
Detach process from pm2

### ISSUE THREAD

**Issue by ojhaujjwal** [Unitech/pm2#3462]
I have a process which handles long running jobs. It takes a lot of time to finish the job.
During the deployment, we need to run two version of the process. We cannot make the jobs wait at all. During the deployment, the previous version does not handle new jobs and the new process handles new jobs.

For that to happen, I was looking for a way to detach the process from pm2 so that I could run a new instance of process which can handle new jobs.

**Comment by Hashymawan** [comment]
I think you are looking for this:
 pm2 interact stop will stop the sync with Keymetrics until next pm2 reboot or until you perform a pm2 interact start.
pm2 interact delete will completely remove the interaction by deleting the file ~/.pm2/agent.json.
In this case if you want to connect again you will have to specify the public and private key again.

**Comment by ojhaujjwal** [comment]
no it is not about keymetrics.
In simple words

* I just want to tell pm2 to stop monitoring a process without stopping it.
* Because, I want to run a new version of the process
* And, I don't want to remove the current version of the process right away
* until it has finished all of its long-running tasks
* and I don't want any of the tasks to wait

**Comment by stanleyxu2005** [comment]
Same question. On MacOS, when I send sigint to redis-server, redis will try exitting. But PM2 think redis is dead, and restart redis. I hope to find a way to disable autorestart, when application is going to stop.
