### ISSUE TITLE
PM2 pull [id]

### ISSUE THREAD

**Issue by highfeed** [Unitech/pm2#3463]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/Unitech/pm2/search?type=Issues) before creating one.

## What's going wrong?
A command `PM2 pull` doesn't work with process id but only process name.

**Comment by wallet77** [comment]
PM2 3.0.0 has been released:

$ npm install pm2@latest -g
$ pm2 update

Be aware of breaking changes, especially drop support for node 0.12.
Full list here : https://github.com/Unitech/pm2/blob/master/CHANGELOG.md
