### ISSUE TITLE
Process Groups/Namespaces.

### ISSUE THREAD

**Issue by aero31aero** [Unitech/pm2#3471]
## Feature Request Description

Asking for an option to exclude an app from `all` based actions like `pm2 restart all`, `pm2 stop all`.

Is there a way to create process groups/namespaces and then refer to them via that name instead? Example, in the `processes.json` file, if we add:

```json
{
  "name": "app1",
  "group": "group1",
},
{
  "name": "app2",
  "group": "group1",
},
{
  "name": "app3",
}
```

Then `pm2 restart group1` would act on all the apps in group1.

## Usage Context?

We have around 8 processes that we manage using PM2, 6 of which are usually updated/deployed simultaneously. So, we had gotten into using `pm2 restart all` for brevity.

However, the recently added 8th process does not support freely restarting it (its an IRC daemon that would spam threads with user joins and exits on restart).

We know that it would be simple to define a bash alias here for this usecase and are currently using that. However, it would be nice to see this feature in pm2 by default.

**Comment by wallet77** [comment]
Hi @aero31aero,

Currently it's not possible. But it's a really good idea, we will add it for pm2V3.
What you can do is similar to your bash alias but directly with pm2.

`pm2 restart /app/`
Should do the trick.

**Comment by Unitech** [comment]
This feature has been incorporated to the latest PM2 release.
To update:

```bash
npm install pm2@latest -g
pm2 update
````

**Comment by BarryThrill** [comment]
https://github.com/Unitech/pm2/issues/4778 I found a small bug about namespacing 😁

**Comment by eyalroth** [comment]
@Unitech OMG I wasn't aware that the feature exists, it's really useful! It should probably be documented on the website...

**Comment by nielinjie** [comment]
How to set namespace from js api?

**Comment by eyalroth** [comment]
> How to set namespace from js api?

@nielinjie Add the `namespace` property to the apps JSONs:
```js
modules.exports = {
  apps: [
    {
      name: 'app1',
      namespace: 'general'
    },
    {
      name: 'app2',
      namespace: 'general'
    }
  ]
};
```

**Comment by nielinjie** [comment]
Thanks, I know this config file way. But I want set it via javascript api way .
https://pm2.keymetrics.io/docs/usage/pm2-api/


> > How to set namespace from js api?
> 
> @nielinjie Add the `namespace` property to the apps JSONs:
> 
> ```js
> modules.exports = {
>   apps: [
>     {
>       name: 'app1',
>       namespace: 'general'
>     },
>     {
>       name: 'app2',
>       namespace: 'general'
>     }
>   ]
> };
> ```

**Comment by eyalroth** [comment]
> Thanks, I know this config file way. But I want set it via javascript api way .
> https://pm2.keymetrics.io/docs/usage/pm2-api/

@nielinjie Oh, I haven't tried that, but the source code seems to accept a `namespace` key in the options.

**Comment by imkane** [comment]
How does namespacing work using `ecosystem.config.js`?

I have this:
```
apps: [
    {
      name: "App1"
      namespace: "getAssets",
      script:
        "node getAssets.js",
    },
    {
      name: "App2",
      namespace: "somethingElse",
      script:
        "node somethingElse.js",
    },
```

And I've tried running:
* `pm2 start ecosystem.config.js --namespace=getAssets`
* `pm2 start ecosystem.config.js getAssets`
* `pm2 start --namespace=getAssets`
* `pm2 start getAssets`
* `pm2 start /getAssets/`

However every time BOTH apps are started :cry: 

Any suggestions?

**Comment by eyalroth** [comment]
@imkane 
> How does namespacing work using `ecosystem.config.js`?

I think that they are mutually exclusive. I haven't looked into the source, but the help for the `start` command indicates that they are:
```
$ pm2 start -h
Usage: start [options] [name|namespace|file|ecosystem|id...]
```
and I couldn't find a command that only loads a configuration file to the process list.

What I usually do is:
```
$ pm2 start ecosystem.config.js
$ pm2 stop all
```

Perhaps you could open a ticket for a new feature that only loads an ecosystem file without starting the apps? (I'd vote for that)

**Comment by imkane** [comment]
@eyalroth so how would you "start" a namespace without using a config file? Where are the namespace apps loaded from?

**Comment by eyalroth** [comment]
> @eyalroth so how would you "start" a namespace without using a config file? Where are the namespace apps loaded from?

@imkane The list of apps is persisted after you "start" a config file, so you can `start` and `stop all`, and then you have the list populated so you can `start` a specific namespace anytime you want.

I'm not entirely sure when do the apps get removed from the list (other than an explicit `delete`).

**Comment by imkane** [comment]
Hmmm ok, maybe I'm confused.

I just want to be able to start/stop/restart a **group** of apps in one easy command. Without typing in their IDs or names. I was hoping namespaces could accomplish this, but it looks like they don't really do anything other than help label apps?

**Comment by bvsubhash** [comment]
> How does namespacing work using `ecosystem.config.js`?
> 
> I'm using pm2 version 5.1.1.
> 
> I have this:
> 
> ```
> apps: [
>     {
>       name: "App1"
>       namespace: "getAssets",
>       script:
>         "node getAssets.js",
>     },
>     {
>       name: "App2",
>       namespace: "somethingElse",
>       script:
>         "node somethingElse.js",
>     },
> ```
> 
> And I've tried running:
> 
> * `pm2 start ecosystem.config.js --namespace=getAssets`
> * `pm2 start ecosystem.config.js getAssets`
> * `pm2 start --namespace=getAssets`
> * `pm2 start getAssets`
> * `pm2 start /getAssets/`
> 
> However every time (unless there's an error) BOTH apps are started 😢
> 
> Any suggestions?



I observed the following items:
1. Your Ecosystem configuration file with multiple apps configuration should be ideally a JSON file (Not a JS file)
2. Current PM2 code does not support starting apps which are only in specific namespace from the configuration file but it supports starting a specific app alone using `--only` CLI option At the moment as a quick fix for your use case, you can group different namespace apps into different JSON files to start them separately for the first time.
3. When you execute command `pm2 start ecosystem.config.json`, it will start all the apps defined in the JSON file. If the app has a namespace, it will be started under that specific namespace. If not, it will be started under 'default' namespace. Once started, you can do all operations like stop, restart or start on a specific namespace using following commands:

```
pm2 start <namespace>
pm2 stop <namespace>
pm2 restart <namespace>
pm2 delete <namespace>
```

Now regarding the CLI commands, if your code script is getAssets.js and if you want to run it _without using any config JSON_ files, then you can do as follows:
```
pm2 start getAssets.js --name App1 --namespace getAssets 
pm2 start somethingElse.js --name App2 --namespace somethingElse
``` 

Once the above process gets started, you can normally use the start, stop, delete etc commands by providing namespace.

**Comment by eyalroth** [comment]
> Hmmm ok, maybe I'm confused.
> 
> I just want to be able to start/stop/restart a **group** of apps in one easy command. Without typing in their IDs or names. I was hoping namespaces could accomplish this, but it looks like they don't really do anything other than help label apps?

@imkane That's exactly what namespaces provide, with the caveat that you first have to "load" the configuration file, which is done by starting it (only once):

```
$ pm2 start ecosystem.config.js
$ pm2 stop all
```

and then you can start or stop namespaces/groups of apps as much as you want:

```
$ pm2 start group1
$ pm2 start group2
$ pm2 stop group1
$ pm2 stop all
$ pm2 start group2
...
```

**Comment by lopugit** [comment]
Ayo this feature is SICK ^ 🚀

**Comment by Alfian5229** [comment]
please add this feature in pm2 docs usage

**Comment by anuragpandey25** [comment]
Add this feature in docuemetation
