### ISSUE TITLE
autoExit is deprecated, but still used in the code

### ISSUE THREAD

**Issue by simoami** [Unitech/pm2#3477]
## What's going wrong?
--auto-start has been deprecated but we don't see a warning since the Feb 3 commit. Furthermore, it appears to still be a dependency in the code:
https://github.com/Unitech/pm2/blob/master/lib/binaries/Runtime4Docker.js#L123
```
if (commander.autoExit)
          Runtime.autoExitWorker();
```

## Supporting information

Please run the following command (available on PM2 >= 2.6)

```
$ pm2 report
```

```
pm2d version         : 2.10.0
node version         : 6.13.0
```

**Comment by wallet77** [comment]
Hi @simoami 

--auto-start has been replaced by --no-auto-exit.
The code still exist because if you don't set --no-auto-exit then autoExit is true.
