### ISSUE TITLE
.mjs files in watch array are ignored

### ISSUE THREAD

**Issue by damianobarbati** [Unitech/pm2#3479]
## What's going wrong?
.mjs files in watch array seem to be ignored.

## How could we reproduce this issue?
Fire pm2 with:
```
pm2 startOrReload pm2.config.js --env development -i 1 && pm2 logs
```

pm2.config.js:
```
const config = require('../package');

module.exports = {
    name: config.name,
    script: 'index.mjs',
    exec_mode: 'cluster',
    node_args: '--harmony --trace-deprecation --experimental-modules --max_old_space_size=512',
    max_memory_restart: '512M',
    max_restarts: 3,
    restart_delay: 3000,
    min_uptime: 3000,
    error_file: 'logs/error.log',
    out_file: 'logs/output.log',
    watch: ['package.json', 'index.mjs', 'config/', 'api/', 'models/'],
    env_development: {
        NODE_ENV: 'development',
    },
    env_staging: {
        NODE_ENV: 'staging',
    },
    env_production: {
        NODE_ENV: 'production',
    }
};
```

index.mjs
```
import sleep from 'sleep-promise';

(async function yo() {
    await sleep(1000);
    console.log('hello');
    yo();
})();
```

Try to change "hello" with "world" in index.mjs.

**Comment by jimmont** [comment]
In my case (pm2 version 2.10.1) all watch files are ignored: removing, adding or edits to a single file in the watch list like `watch: ["file.name"]` are ignored. I had a list of paths in an array and reduced it to one to troubleshoot and this is my finding so-far.

**Comment by wallet77** [comment]
Hi @jimmont 

Could you share with us the exact case of failure ?

**Comment by jimmont** [comment]
I did a `tail -f www/logs/combined.log` then `pm2 restart pm2.config.js`

the app starts, I then tried several ways of getting it to restart:
modify the package.main script directly, successfully PUT file www/files/restart.txt, edit/remove/add restart.txt directly while app runs;

In all cases the logs update to reflect PUT and show my app-level logging, including startup, but the watch never triggers a restart in any/all cases. It seems the `watch` does not work at all. I also tried adjusting the relative paths below to use absolute paths.

```
pm2 version 2.10.1
node v8.9.4 
Raspbian GNU/Linux 9.3 (stretch)
Linux 4.9.76-v7+ #1076 SMP Wed Jan 10 17:34:49 GMT 2018 armv7l GNU/Linux
```

`pm2.config.js` has:
```
var package = require('./package.json');
module.exports = {
	apps: [
		{
			name: 'theapp'
			,script: package.main
			,watch: ['app/', 'www/secrets.json', 'www/options.json', 'www/files/restart.txt']
			,env: {
				COMMON_VARIABLE: 'true'
				,NODE_ENV: 'development'
			}
			,env_production: {
				NODE_ENV: 'production'
			}
			,source_map_support: false
			,log_date_format: "YYYY-MM-DDTHH:mm:ss.sssZ"
			// console.log and console.error go here:
			,out_file: 'www/logs/combined.log'
			,error_file: 'www/logs/combined.log'
			,merge_logs: true
			,max_restarts: 15
			,max_memory_restart: "250M"
			,instances: 1
			,merge_logs: true // all instances merge
			,autorestart: true
			,post_update: ["npm install", "echo theapp"]
			// https://github.com/Unitech/pm2/issues/1076
		}
		,{
			name: 'auxillaryapp'
			,script: package.auxillary
			,watch: [package.auxillary]
			,error_file: 'sync.error.log'
			,instances: 1
			,max_restarts: 15
			,log_date_format: 'YYYY-MM-DD HH:mm Z'
			,merge_logs: true
			,exec_mode: 'cluster'
			,autorestart: true
			,restart_delay: 60000
		}
	],
};


```

**Comment by wallet77** [comment]
PM2 3.0.0 has been released:

$ npm install pm2@latest -g
$ pm2 update

Be aware of breaking changes, especially drop support for node 0.12.
Full list here : https://github.com/Unitech/pm2/blob/master/CHANGELOG.md
