### ISSUE TITLE
2 instances of of 2 different node servers aren't starting using pm2 cluster mode

### ISSUE THREAD

**Issue by Arvinsarc** [Unitech/pm2#3489]
Hi , 

I had started a node server with 2 instances using cluster mode of pm2.  I had a requirement for having running two node servers for two different services

went through the documentation made a pm2,json file --see below

{
  "apps": [
    
{
     "exec_mode": "cluster",
      "instances":2,
      "script": "/var/www/html/goodplaces/server.js",
      "name": "userModule",
      "node_args": [ "--harmony" ],
      "env": {
       "NODE_ENV": "production"
      }
      },
    {
      "exec_mode": "cluster",
     "instances": 2,
      "script": "/var/www/html/userauth/bin/www",
      "name": "userOauth",
      "node_args": [ "--harmony" ],
      "env": {
       "NODE_ENV": "production"
      }
     }
  ]
}

The first one i.e the user module runs completely fine but the second one oauth keeps erroring out.

**Comment by wallet77** [comment]
Hi @Arvinsarc 

I made a basic example like yours but I can't reproduce error.
The only difference is I'm not working with full path, and in your second app you don't work with a js file.
Is it normal ?

**Comment by Arvinsarc** [comment]
I changed that to a js file , it is still giving an error
