### ISSUE TITLE
PM2 modules report the PM2 version in pm2 list instead of their module (package) version.

### ISSUE THREAD

**Issue by daankets** [Unitech/pm2#3492]
## What's going wrong?
When I `pm2 module:install` a module (with package.json version 1.0.0), pm2 reports the version of the module as '2.10.0-beta' in `pm2 list`. This is my current pm2 version instead of the module version.

## How could we reproduce this issue?
Install any pm2 module, and run it. Then execute `pm2 list` and verify the module version against the actual package version.

## Supporting information
Not working in 2.10.0-beta on OSX.

**Comment by wallet77** [comment]
Hi @daankets 

I can't reproduce this behavior.
Could you provide a module name when this error occurred ?

**Comment by daankets** [comment]
Hi @wallet77, this happens with a private module in our Nexus repository. But I can try to prepare a simple demo in the course of tomorrow and publish it.
