### ISSUE TITLE
Sometimes Locks Socket/Port Until Killed

### ISSUE THREAD

**Issue by jvanalst** [Unitech/pm2#350]
This is on Mac OS X v10.8.2, node v0.10.26 and pm2 -V 0.7.8.

Sometimes when restarting/deleting/stopping a web server process the port remains open and stuck in the CLOSE_WAIT state. The only way to free the port and restart your application is to kill the pm2 Satan Daemonizer. (either with `pm2 kill` or `sudo kill ###`)

As you can imagine, having to kill pm2 is not an ideal solution if you have more than one application running at a time.
## 

Jeff

**Comment by vachanda** [comment]
I'm facing similar issue with PM2 version 1.1.2. Node version is 5.7.1.

We're using PM2 to power our node application behind nginx. PM2 is running in cluster mode. After each of out deployment we perform PM2 reload all operation to perform a zero downtime restart. But we find that PM2 still maintains some socket connections with close_wait state.

![image](https://cloud.githubusercontent.com/assets/12047814/16107556/b4f86d3c-33ba-11e6-9fdc-0a292dd5c6a8.png)
