### ISSUE TITLE
Unable to increase Node.JS app heap memory size running on AWS instance by PM2

### ISSUE THREAD

**Issue by maneshdas** [Unitech/pm2#3502]
Couldn't change the Node.JS instance heap size while passing V8 options through PM2 start command in AWS instance. Its working fine in on-premise machines. 
Any suggestions/advice will be helpful.

pm2 start /home/sever/src/bin/app.js -i 1 --name app_server --node-args="--max_old_space_size=2048"

Memory size is still 1.39GB (default limit) after running above command for ±2GB

**Comment by wallet77** [comment]
Hi @maneshdas 

Could you test without pm2 ? I'm guess is not related to pm2, just to be sure !

**Comment by maneshdas** [comment]
@wallet77, It is working fine with/without PM2 in other machines other than AWS.. 
Anyone faced such scenarios? and I am not sure is there any other variables controlling this in AWS.

Thanks!

**Comment by ihor-lev** [comment]
Possible typo in node args. Should be: `node --max-old-space-size=2048`.
