### ISSUE TITLE
pm2 install profiler installs v8-profiler-node8 but code looks for v8-profiler

### ISSUE THREAD

**Issue by mrfelton** [Unitech/pm2#3505]
Hi,

When you run `pm2 install profiler` it installs the `v8-profiler-node8` package. however when you try to use the profiler to create a snapshot with `pm2 snapshot` it complains `v8-profiler is not available`.

It seems that code is trying to require a package called `v8-profiler` even though what was actually installed was called `v8-profiler-node8`

see
https://github.com/Unitech/pm2/blob/0d009364d58b3f3cfe2c6fa40606c441ba73d5e9/lib/Daemon.js#L156

**Comment by wallet77** [comment]
Hi @mrfelton 

Good catch. Indeed we switch from v8-profiler to v8-profiler-node8 for compatibility reason.
I will fix it soon ;)

**Comment by ivosabev** [comment]
When is this expected to ship?

**Comment by wallet77** [comment]
PM2 3.0.0 has been released:

$ npm install pm2@latest -g
$ pm2 update

Be aware of breaking changes, especially drop support for node 0.12.
Full list here : https://github.com/Unitech/pm2/blob/master/CHANGELOG.md
