### ISSUE TITLE
pm2 "max_restarts" not working in app.json when there is more then one process

### ISSUE THREAD

**Issue by Adiii717** [Unitech/pm2#3508]
I tried pm2 with restart limit in YML and JSON file but it failed to work when I mention more then one process in JSON file.
Here is a process which works fine with restart limit.
```
{
 "apps": [
    {
      "name": "server-2",
      "script": "server-2.js",
      "max_restarts" : 5 
    }
]
}
```

But it's not controlling restart limit when I mention more than one process.
here is the JSON file.
```
{
  "apps": [
    {
      "name": "server-1",
      "script": "server-1.js",
      "max_restarts" : 5 
    },
    {
      "name": "server-2",
      "script": "server-2.js",
      "max_restarts" : 5  
    }
]
}
```

**Comment by mohammadmahdi123** [comment]
Yes. I have the problem as well.
