### ISSUE TITLE
Passing in command line program arguments to pm2-runtime

### ISSUE THREAD

**Issue by nickcodefresh** [Unitech/pm2#3509]
How do I pass program arguments to pm2-runtime? I'm trying 

`pm2-runtime ./bin/server.js --node-args="--swagger.enabled=true"`

but this gives me

```
[2018-03-02 11:39:41] PM2 log: Starting execution sequence in -fork mode- for app name:server id:0
[2018-03-02 11:39:41] PM2 log: App name:server id:0 online
node: bad option: --swagger.enabled=true
```
I've tried `pm2-runtime ./bin/server.js --swagger.enabled=true` but then the argument isn't passed to the program.

Thanks

Nick

**Comment by vmarchaud** [comment]
`pm2-runtime ./bin/server.js -- --swagger.enabled=true` should works
