### ISSUE TITLE
pm2 cluster EADDRINUSE

### ISSUE THREAD

**Issue by scriptsure** [Unitech/pm2#3518]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/Unitech/pm2/search?type=Issues) before creating one.

## What's going wrong?
When starting application in cluster mode i get the following:

 Error: bind EADDRINUSE null:4000

I AM TOTALLY POSITIVE THERE IS NOTHING RUNNING ON PORT 4000

running on the latest PM2 version... 2.10

## How could we reproduce this issue?
HAVE NO IDEA!

## Supporting information

{
  "apps": [
    {
      "name": "load",
      "script": "bin/www",
      "instances": "max",
      "exec_mode": "cluster",
      "watch": false,
      "cwd": "/home/ubuntu/sites/load",
      "env": {
        "NODE_ENV": "production"
      }
    }
  ]
}

Please run the following command (available on PM2 >= 2.6)

```
$ pm2 report

===============================================================================
--- PM2 REPORT (Mon Mar 05 2018 21:57:15 GMT+0000 (UTC)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.10.1
node version         : 8.9.3
node path            : undefined
argv                 : /usr/bin/node,/usr/lib/node_modules/pm2/bin/pm2,resurrect,--no-daemon
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
uptime               : 30min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.10.1
node version         : 8.9.3
node path            : undefined
argv                 : /usr/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
cpus nb              : 1
freemem              : 181116928
totalmem             : 2095595520
home                 : /home/ubuntu
===============================================================================

```

**Comment by cnscorpions** [comment]
same issue, nee help :(

**Comment by Unitech** [comment]
Not related to pm2
Check which app is listening on a port via ‘ sudo netstat -ltnp | grep -w ':80'’

**Comment by cnscorpions** [comment]
`sudo pkill PM2`, and then `pm2 reload all` solve this issue.
