### ISSUE TITLE
Watch for file changes?

### ISSUE THREAD

**Issue by majimboo** [Unitech/pm2#352]
Is there a way for PM2 to check for file changes and automatically reload a lot like how nodemon is doing it for node?

I can't find it in the documentation.

**Comment by anacicconi** [comment]
Hi, I'm new to NodeJs and some developers told me to use PM2 in production and Nodemon in development. However, I just saw that PM2 has a watch option so isn't it better to use only PM2 in production and development? Why are developers still combining both? Thanks ;)
