### ISSUE TITLE
Cluster mode sending data from one instance to another?

### ISSUE THREAD

**Issue by rclai** [Unitech/pm2#3520]
Not sure if this is the right place to ask, but is it possible to send data from one instance to another in cluster mode?

For example, if I'm `NODE_APP_INSTANCE` number 2, and I received a webhook request, I'd like to funnel that request to `NODE_APP_INSTANCE` number 0 to process.

**Comment by wallet77** [comment]
Hi @rclai 

There is no such built-in feature with pm2.

You should see instance in cluster mode like different apps. 
So when you want to communicate between them you can use a message queue system, a message bus or whatever to send/request data between applications.

Hope it can help.
