### ISSUE TITLE
 If the --no-daemon option is used, no signal is received.

### ISSUE THREAD

**Issue by KimSeongIl** [Unitech/pm2#3522]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/Unitech/pm2/search?type=Issues) before creating one.

## What's going wrong?

If I use --no-daemon in a docker container, I can not receive signals.

Using pm2-runtime works fine.

## How could we reproduce this issue?

I want to get SIGINT from nodejs when pm2 is killed with SIGTERM.

## Supporting information

Please run the following command (available on PM2 >= 2.6)

It works well.
```
CMD ["pm2-runtime", "start", "app/main.js"]  // Dockerfile

docker kill --signal=TERM <id>
```

It doesn't work.
```
CMD ["pm2", "start", "app/main.js", "--no-daemon"]  // Dockerfile

docker kill --signal=TERM <id>
```

**Comment by holm** [comment]
This just completely caught us off-guard. This was seemingly changed in just a patch release here: https://github.com/Unitech/pm2/commit/b9c01c99d54aba98ab790b8888500ac0f0af05c9

There doesn't seem to be any way to restore the old behavior either. Will have to downgrade for now.

**Comment by KimSeongIl** [comment]
@holm 
Thanks! I will use pm2-runtime.
