### ISSUE TITLE
 Too many logs are output at shutdown with graceful shutdown.

### ISSUE THREAD

**Issue by KimSeongIl** [Unitech/pm2#3524]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/Unitech/pm2/search?type=Issues) before creating one.

## What's going wrong?

Too many logs are output at shutdown.

## Supporting information

Please run the following command (available on PM2 >= 2.6)

```
pm2 start app/main.js --no-daemon --kill-timeout=10000 -i 4

kill -15 <pm2 id>
```

```

PM2        | pid=4382 msg=failed to kill - retrying in 100ms
PM2        | pid=4399 msg=failed to kill - retrying in 100ms
PM2        | pid=4364 msg=failed to kill - retrying in 100ms
PM2        | pid=4365 msg=failed to kill - retrying in 100ms
PM2        | pid=4382 msg=failed to kill - retrying in 100ms
PM2        | pid=4399 msg=failed to kill - retrying in 100ms
PM2        | pid=4364 msg=failed to kill - retrying in 100ms
PM2        | pid=4365 msg=failed to kill - retrying in 100ms
PM2        | pid=4382 msg=failed to kill - retrying in 100ms
PM2        | pid=4399 msg=failed to kill - retrying in 100ms
PM2        | pid=4364 msg=failed to kill - retrying in 100ms
PM2        | pid=4365 msg=failed to kill - retrying in 100ms
...........
...........
```

Too many logs are output at shutdown.
How can I hide or delay the log?

The logs are very much output until the time set by kill-timeout.

**Comment by wallet77** [comment]
PM2 3.0.0 has been released:

$ npm install pm2@latest -g
$ pm2 update

Be aware of breaking changes, especially drop support for node 0.12.
Full list here : https://github.com/Unitech/pm2/blob/master/CHANGELOG.md
