### ISSUE TITLE
Question: i have a loopback api that i want to deploy using pm2? 

### ISSUE THREAD

**Issue by AhmedMasoodSiddiqui** [Unitech/pm2#3526]
its just a question and i can't find the answer, whats the difference between "pm2 start ecosystem.config.js" and "pm2 deploy ecosystem.config.js" commands and if deploy is used do i need to configure config,json ,remote server configurations on server too?
PM2 version = 2.10.1
node version = v9.5.0
OS windows 10

**Comment by wallet77** [comment]
@robin-monnier do you have a clear explanation on that ?

Basically deploy will git pull a repository and start apps while pm2 start will only start apps defined in ecosystem.config.js
