### ISSUE TITLE
pm2 list shows empty but pm2 is running

### ISSUE THREAD

**Issue by imyashvinder** [Unitech/pm2#3528]
I am running node server in autoscaling and i have written few commands in bootstrap script to start pm2 after deployment. 
pm2 starts after deployment as expected but when i check pm2 list, it shows empty, while checking 'netstat -tnlp' i see node server already running on port 8080.

Bootstrap script:
cd /opt
npm install
pm2 start server
service nginx start

netstat -tnlp:
tcp        0      0 :::8080                     :::*                        LISTEN      3041/node /opt/serv     
tcp        0      0 :::22                       :::*                        LISTEN      2771/sshd

pm2 list:
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app

Now if i try to run pm2 again by killing the old one with pkill -f PM2 and re run
pm2 start server, everything works well and it shows the id in pm2 list as well but i want this to be run in aws userdata script so that autoscaling could work.

I also tried pkill -f PM2 in userdata and then re-run pm2 start server but that didn't help as well. 

More Info:
root user is running pm2
and i am also checking the above things from root user

I have googled enough :)

Regards,
Yash

**Comment by imyashvinder** [comment]
Hey Marc,

sudo pkill -f PM2
sudo pm2 start server.js -- prod
sudo pm2 startup
sudo pm2 save
sudo service nginx start

This worked for me :)


Regards,
Yash

**Comment by jonathanborges** [comment]
Still having problems with pm2-dev start config.yml. But pm2-runtime works fine. Can someone check this one, please?

**Comment by NahuPerez** [comment]
> Hey Marc,
> 
> sudo pkill -f PM2
> sudo pm2 start server.js -- prod
> sudo pm2 startup
> sudo pm2 save
> sudo service nginx start
> 
> This worked for me :)
> 
> Regards,
> Yash

work like a charm

**Comment by imyashvinder** [comment]
@NahuPerez Good to know buddy that it's working for you :)

**Comment by alikarimii** [comment]
1

**Comment by hadynz** [comment]
I am running into a similar problem at the moment. I believe it is because of https://github.com/Unitech/pm2/issues/992.

In short, PM2 is run by two different user types, and I am only able to see processes running that were invoked by my user. For example:

* `root` user - what CodeDeploy uses to build, deploy and run processes on my server
* my user `/home/ubuntu/<me>` - what I use when I login to my server to manually troubleshoot things on server

**Comment by robsonalvz** [comment]
Great explanation @hadynz 

> I am running into a similar problem at the moment. I believe it is because of #992.
> 
> In short, PM2 is run by two different user types, and I am only able to see processes running that were invoked by my user. For example:
> 
> * `root` user - what CodeDeploy uses to build, deploy and run processes on my server
> * my user `/home/ubuntu/<me>` - what I use when I login to my server to manually troubleshoot things on server

**Comment by PhantomNimbi** [comment]
Yo, I'm having this issue and the above steps aren't working for me. I have one bot started with `pm2 start index.js --name "NAME_HERE" --watch` and it's not showing up in the list of processes. 

The PM2 process also doesn't show up in the list of running processes but it is running and I can't check the logs for errors or anything.

I really need to find out how to stop **ALL** running PM2 processes so I can start fresh.

**Comment by MohamedJakkariya** [comment]
It's also happening to me without `sudo`. I checked closely when I try with `sudo`. It's working again. Hope it helps.

**Comment by bobkov-evgeny** [comment]
> sudo pkill -f PM2 sudo pm2 start server.js -- prod sudo pm2 startup sudo pm2 save sudo service nginx start
> 

Very appreciated, works great

**Comment by GurunadhPachappagari** [comment]
I was running the pm2 process using sudo 
but I was checking the pm2 list as normal user -> that is why I couldn't see any process

running `sudo pm2 list` worked for me 🤣

**Comment by fez6** [comment]
> Yo, I'm having this issue and the above steps aren't working for me. I have one bot started with `pm2 start index.js --name "NAME_HERE" --watch` and it's not showing up in the list of processes.
> 
> The PM2 process also doesn't show up in the list of running processes but it is running and I can't check the logs for errors or anything.
> 
> I really need to find out how to stop **ALL** running PM2 processes so I can start fresh.
> 
> the PM2 kill command doesn't work, nor does `sudo PM2 kill`, Only the visible processes are stopped. The one that isn't showing keeps running.

For me nothing of the above worked except `sudo pm2 kill`.
After killing and then starting it using `sudo pm2 start` it worked without any problems. ¯\\_(ツ)_/¯

**Comment by JohnyClash** [comment]
> I am running into a similar problem at the moment. I believe it is because of #992.
> 
> In short, PM2 is run by two different user types, and I am only able to see processes running that were invoked by my user. For example:
> 
> * `root` user - what CodeDeploy uses to build, deploy and run processes on my server
> * my user `/home/ubuntu/<me>` - what I use when I login to my server to manually troubleshoot things on server

Your comment lead me to figure out that  sudo pm2 list returns a seperate list vs pm2 list. Which answers my question.

**Comment by sagarVentura** [comment]
thanks it actually working  , issue i face i do npm run start on pm2 log it show pm2 is running but when do pm2 list it dont showing  any list   but by using @NahuPerez   solution it is now working fine , thanks man for support

**Comment by mrizwanashiq** [comment]
> Hey Marc,
> 
> sudo pkill -f PM2 sudo pm2 start server.js -- prod sudo pm2 startup sudo pm2 save sudo service nginx start
> 
> This worked for me :)
> 
> Regards, Yash

It worked for me, thanks @imyashvinder 

I started the process by `sudo pm2 start server.js`, but was checking the list by `pm2 list` (without sudo), even though the process was running, but still i could not see it in the pm2 list, once I put sudo like `sudo pm2 list`, it showed all running processes.
