### ISSUE TITLE
passing args to the script that are visible through linux ps

### ISSUE THREAD

**Issue by diginfo** [Unitech/pm2#3558]
Hi;

I have several (10+) instances of the same script file running each on a different database and when I try and view these via ps aux they all look identical other than their process ID.

But I need to be able to tell which process belongs to which site / database when I use linux top, ps etc etc etc.

I have already tried:

    args
    node_args

in my app.json file, but neither of these actually add the args to the process.

I have also tried defining the script with trailing dashes and that does not work either.

    "script": "/usr/share/nodejs/dev/run/app.js --site1",

What I would like to see when running a linux process based command is this:

    node /usr/share/nodejs/dev/run/pure/app.js site1

How can I do this ?

**Comment by wallet77** [comment]
Hi @diginfo 

I'm not sure that PM2 can achieve what you want.
Basically pm2 just start applications and manage them.
Indeed every instances are the same by definition. And the only way to differentiate them is their id.
