### ISSUE TITLE
Multiple PM2 on the same server

### ISSUE THREAD

**Issue by dev7005** [Unitech/pm2#3568]
We have two apps we want to start with the same PM2 on a server.
As we can see in the docu (http://pm2.keymetrics.io/docs/usage/specifics/#multiple-pm2-on-the-same-server) this is possible by calling:
PM2_HOME='.pm3' pm2 start echo.js

Unfortunately it doesn't work. When I try to list the instances we see instances with status _errored_.
But in the .pm3 folder we cannot find any logs - no entries in the logs folder.

With the app is everything fine. Instances are _online_ and there are also logfiles in .pm2/logs.

Are there any known issues?
Thank you!

**Comment by wallet77** [comment]
Hi @dev7005 

Maybe I misunderstood something.
But the doc you are referring to is to use 2 different pm2.

If you just want to launch multiple apps with **the same pm2**, just use basic command `pm2 start` on every app you want to start.

**Comment by dev7005** [comment]
Hi,
yes you are right, it is easily possible to launch multiple apps with the same pm2.
I misunderstood something wrong ..
Thank you!
