### ISSUE TITLE
Modules not automatically started

### ISSUE THREAD

**Issue by tjunnone** [Unitech/pm2#3577]
I can't seem to find any way to load modules like pm2-logrotate automatically when pm2 starts.

For example:
- pm2 install pm2-logrotate & start an app
- pm2 status: shows the app and the module "pm2-logrotate" running
- pm2 save
- pm2 kill
- pm2 resurrect
- pm2 status shows only the app running

Same thing with the generated startup scripts, the apps start but modules don't. "pm2 install pm2-logrotate" must be run after every single reboot. $PM2_HOME/module_conf.json contains "module-db": {"pm2-logrotate": "true" }".

Shouldn't the modules in module_conf.json always be reloaded?

Version: 2.10.2

**Comment by Unitech** [comment]
Modules have always been started along PM2. please update PM2
