### ISSUE TITLE
watch not working in ecosystem.config.js

### ISSUE THREAD

**Issue by ajostergaard** [Unitech/pm2#3578]
## What's going wrong?
Simply cannot get watch to watch anything when configured in ecosystem.config.js. It works if I use --watch but that watches too many files. It says watch and restart are enabled but never restarts anything and logs don't make any mention of watching. Have tried watching a file and an array of files too. User is not root.

## How could we reproduce this issue?
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
$ cat ecosystem.config.js
module.exports = {
  apps : [
    {
      name: 'feeder',
      script: 'feeder/app.js',
      watch: true,
    }
  ]
};
$ ls *
ecosystem.config.js

feeder:
app.js  node_modules  package.json  package-lock.json
$ pm2 start ecosystem.config.js
[PM2] Applying action restartProcessId on app [feeder](ids: 0)
[PM2] [feeder](0) ✓
┌──────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────┬──────────┬──────┬──────────┐
│ App name │ id │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem      │ user │ watching │
├──────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────┼──────────┼──────┼──────────┤
│ feeder   │ 0  │ fork │ 10562 │ online │ 22      │ 0s     │ 0%  │ 4.0 KB   │ bub  │ enabled  │
└──────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────┴──────────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
bubo@bubo:~$ touch feeder/app.js
bubo@bubo:~$ pm2 ls feeder
┌──────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────┬───────────┬──────┬──────────┐
│ App name │ id │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem       │ user │ watching │
├──────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼──────┼──────────┤
│ feeder   │ 0  │ fork │ 10562 │ online │ 22      │ 44s    │ 0%  │ 38.1 MB   │ bub  │ enabled  │
└──────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────┴───────────┴──────┴──────────┘
```

## Supporting information

```
$ pm2 report
===============================================================================
--- PM2 REPORT (Fri Mar 30 2018 17:58:20 GMT+0100 (BST)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.10.1
node version         : 8.10.0
node path            : undefined
argv                 : /usr/bin/node,/usr/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : bub
uid                  : 1002
gid                  : 1002
uptime               : 476min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.10.1
node version         : 8.10.0
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : bub
uid                  : 1002
gid                  : 1002
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Core(TM) i7-4910MQ CPU @ 2.90GHz
cpus nb              : 1
freemem              : 181456896
totalmem             : 1040437248
home                 : /home/bub
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬──────┬──────┬────────┬─────────┬────────┬─────┬───────────┬──────┬──────────┐
│ App name │ id │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem       │ user │ watching │
├──────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────┼───────────┼──────┼──────────┤
│ feeder   │ 0  │ fork │ 6552 │ online │ 21      │ 2s     │ 4%  │ 37.7 MB   │ bub │ enabled  │
└──────────┴────┴──────┴──────┴────────┴─────────┴────────┴─────┴───────────┴──────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌──────────┬────┬──────┬──────┬────────┬─────────┬────────┬─────┬───────────┬──────┬──────────┐
│ App name │ id │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem       │ user │ watching │
├──────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────┼───────────┼──────┼──────────┤
│ feeder   │ 0  │ fork │ 6552 │ online │ 21      │ 2s     │ 0%  │ 37.7 MB   │ bub │ enabled  │
└──────────┴────┴──────┴──────┴────────┴─────────┴────────┴─────┴───────────┴──────┴──────────┘
```

**Comment by VandalPaulius** [comment]
I have same issue. `ignore_watch` does not work in ecosystem file either

**Comment by tommedema** [comment]
Did you ever get this to work?

**Comment by ajostergaard** [comment]
Working on a new project, had the same problem, found this issue from ages ago but found a solution - might be the same might be different.

What I did this time is delete the app completely before starting it via ecosystem file - turns out watch settings weren't updating properly and the 'watching/enabled' bit may be misleading. I had created the app first and then switched to 'ecosystem'... A little more diagnostic output in logs etc around watching and watched might have helped.

Closing this issue as 'user error'-ish.

**Comment by VandalPaulius** [comment]
I would disagree that it's user error as it's not clear how to use it. If it's indeed user error and deleting app would help, would be beneficial to update docs for that.

**Comment by chrisdemetriad** [comment]
I also disagree. I have the same issue for ages. Whatever paths I use in the watch property, if I add one, or in the script name, it doesn't work. Spent two days on it. 

**It doesn't work.**

Changes to test1.js doesn't trigger a restart.
If I start test3.js manually with pm2 start bots/test3.js --watch, changes to test1.js will trigger a restart. process.cwd() returns /home/chris.

`
chris@localhost:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
matt@localhost:~$ cat bots/bots.json
[
        {
                "name": "test1",
                "script": "./bots/test1.js",
                "watch": "./bots/test1.js"
        },
        {
                "name": "test2",
                "script": "./bots/test2.js",
                "cwd": "./bots",
                "watch": true,
                "ignore_watch": [
                        "db",
                        "/db"
                ],
                "watch_options": {
                        "followSymlinks": false
                }
        },
...

chris@localhost:~$ pm2 report
===============================================================================
--- PM2 REPORT (Wed Feb 05 2020 15:13:47 GMT+0000 (Coordinated Universal Time))
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.0.3
node version         : 12.12.0
node path            : /usr/bin/pm2
argv                 : /home/chris/.nvm/versions/node/v12.12.0/bin/node,/usr/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : matt
uid                  : 1000
gid                  : 1000
uptime               : 42min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.0.3
node version         : 12.12.0
node path            : /usr/bin/pm2
argv                 : /home/chris/.nvm/versions/node/v12.12.0/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : chris
uid                  : 1000
gid                  : 1000
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : AMD EPYC 7601 32-Core Processor
cpus nb              : 1
freemem              : 743907328
totalmem             : 2090225664
home                 : /home/chris
===============================================================================
--- PM2 list -----------------------------------------------
┌────────────────────┬────┬──────┬───────┬────────┬─────────┬────────┬──────┬───────────┬──────┬──────────┐
│ App name           │ id │ mode │ pid   │ status │ restart │ uptime │ cpu  │ mem       │ user │ watching │
├────────────────────┼────┼──────┼───────┼────────┼─────────┼────────┼──────┼───────────┼──────┼──────────┤
│ test1        │ 1  │ fork │ 14937 │ online │ 31      │ 5m     │ 0.1% │ 38.2 MB   │ chris │ enabled  │
│ test2           │ 0  │ fork │ 14930 │ online │ 31      │ 5m     │ 0%   │ 38.2 MB   │ chris │ enabled  │

`

**Comment by vtolenti89** [comment]
I am also struggling with the same problem.

**Comment by ajostergaard** [comment]
@vtolenti89 assuming ALL your apps are defined in your ecosystem file try:

```
$ pm2 delete all
$ pm2 start ecosystem.config.js
```

That's essentially what got it working for me and when I understood this it worked every time.

**Comment by michaelcaterisano** [comment]
> @vtolenti89 assuming ALL your apps are defined in your ecosystem file try:
> 
> ```
> $ pm2 delete all
> $ pm2 start ecosystem.config.js
> ```
> 
> That's essentially what got it working for me and when I understood this it worked every time.

This worked for me

**Comment by Qoohsuan** [comment]
`module.exports = {
  apps : [{
    script: 'index.js',
    watch: ["index.js"],
    ignore_watch: ["node_modules"],
    watch_options: {
      usePolling: true,
      alwaysStat: true,
      useFsEvents: false
    },
    env: {
        NODE_ENV: "development"
    }
  }],

  deploy : {
    production : {
      user : 'SSH_USERNAME',
      host : 'SSH_HOSTMACHINE',
      ref  : 'origin/master',
      repo : 'GIT_REPOSITORY',
      path : 'DESTINATION_PATH',
      'pre-deploy-local': '',
      'post-deploy' : 'npm install && pm2 reload ecosystem.config.js --env production',
      'pre-setup': ''
    }
  }
};`

I put those code in my ecosystem.config.js
