### ISSUE TITLE
pm2 deploy production setup with ecosystem.config.js on Windows

### ISSUE THREAD

**Issue by Tyler-V** [Unitech/pm2#3579]
I'm trying to get the deployment setup. I have followed the guide a few times now, hopefully its something simple on my end but I'm having issues getting this setup.

Using Windows 10, I have a LEMP server hosted by digital ocean. I am using pm2 --version `2.10.2`.

I have tried running the command in powershell and git bash both throw errors.

1. Executed `pm2 ecosystem` in my project folder
2. Modified the `ecosystem.config.js` file to my settings below
3. `pm2 deploy production setup` (using powershell in the project folder)
4. `ssh root@[redacted]` connects to my server without issues
5. pm2, node, git, etc. are all installed on the server

```
--> Deploying to production environment
--> on host [redacted].com
Deploy failed
Deploy failed
```
```
module.exports = {
  apps: [{
    name: 'api',
    script: 'index.js',
    env: {
      COMMON_VARIABLE: 'true'
    },
    env_production: {
      NODE_ENV: 'production'
    }
  }],
  deploy: {
    production: {
      user: 'root',
      host: 'domain.com',
      ref: 'origin/master',
      repo: 'git@github.com:Tyler-V/api.git',
      path: '/var/www/[redacted].com/api',
      'post-deploy': 'npm install && pm2 reload ecosystem.config.js --env production'
    }
  }
};
```

**Comment by ajostergaard** [comment]
Doesn't it need a 'key' to connect?

**Comment by Tyler-V** [comment]
@ajostergaard I did see that in the docs, I don't have a .pem however.

In my '~/.ssh/' I have a id_rsa and id_rsa.pub file that I generated when setting up SSH keys for digital ocean initially. Is there another step I need to generate a .pem?

**Comment by Tyler-V** [comment]
Documenting resolution for future in case people search this particular issue.

1. Run all pm2 commands in git bash, **make sure you are opening git bash in administrator mode**
2. For private git repositories, [generate a SSH key on the server and add it to your github account](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/).
3. Run `pm2 deploy ecosystem.json production setup` first
4. Then you can run subsequent `pm2 deploy ecosystem.json production` after that for pushing code

**Comment by wallet77** [comment]
Hi @Tyler-V 

You confirm those steps solved this issue ?
If yes we will add it somewhere in the doc ;)
