### ISSUE TITLE
"npm i -g pm2" cannot fetch

### ISSUE THREAD

**Issue by oXman038** [Unitech/pm2#3580]
## What's going wrong?
Today (March 31), after I created new instance from aws ec2, when I am trying following command, it cannot fetch the url. Yesterday, it was working perfectly in the new opened different instance.
```
npm i -g pm2
```
It stucks as that:
![screen shot 2018-03-31 at 4 25 56 pm](https://user-images.githubusercontent.com/10633110/38168424-3ca8afa6-3500-11e8-86cb-a2c8a8164f8d.png)

**Comment by conradob** [comment]
I'm also facing this issue trying to install with yarn
![image](https://user-images.githubusercontent.com/1469697/38168672-15e7dda4-352a-11e8-8d1a-7bd56386a118.png)

**Comment by oXman038** [comment]
I found the solution in [here](https://github.com/Unitech/pm2/issues/2438), thanks.

**Comment by conradob** [comment]
This doesn't fix the issue, the certificate for gtk dependency https://tgz.pm2.io/gkt-1.0.0.tgz is expired causing the issue. Please reopen the issue.

**Comment by Unitech** [comment]
fixed yesterday night
