### ISSUE TITLE
code deployed well with 2.10.1 failed to deploy with 2.10.2

### ISSUE THREAD

**Issue by adalidda** [Unitech/pm2#3581]
Hi,

My app used meteor 1.6.1 + react. My app deployed well with pm2 version 2.10.1 but when I upgrade to version 2.10.2 the deploy failed with the following error:

|adaV4-AS |     at require (internal/module.js:12:17)
3|adaV4-AS |     at Object.<anonymous> (/opt/pm2-meteorFR/adaV4-ASIA-EN1/bundle/main.js:4:1)
3|adaV4-AS |     at Module._compile (module.js:409:26)
3|adaV4-AS |     at Object.Module._extensions..js (module.js:416:10)
3|adaV4-AS | SyntaxError: Unexpected token {
3|adaV4-AS |     at exports.runInThisContext (vm.js:53:16)
3|adaV4-AS |     at Module._compile (module.js:373:25)
3|adaV4-AS |     at Object.Module._extensions..js (module.js:416:10)
3|adaV4-AS |     at Module.load (module.js:343:32)
3|adaV4-AS |     at Function.Module._load (module.js:300:12)
3|adaV4-AS |     at Module.require (module.js:353:17)
3|adaV4-AS |     at require (internal/module.js:12:17)
3|adaV4-AS |     at Object.<anonymous> (/opt/pm2-meteorFR/adaV4-ASIA-EN1/bundle/main.js:4:1)
3|adaV4-AS |     at Module._compile (module.js:409:26)
3|adaV4-AS |     at Object.Module._extensions..js (module.js:416:10)

My server have 50 Gb RAM, 10 core CPU and 1 TB SSD disk under Ubuntu 17.10

When I downgrade back to version 2.10.1 everything is working again.

Thank You
Adalidda

**Comment by wallet77** [comment]
Hi @adalidda 

the only modification in 2.10.2 is the auto exit policy.
We just add some retry to have a better integration with container.
https://github.com/Unitech/pm2/pull/3569

I don't see how it can have an impact on your case.
If you have an idea, let me know ;)

**Comment by adalidda** [comment]
Thank You @wallet77. I don't know either but as we have 3 different apps deployed with PM2 and all 3 failed with version 2.10.2, I will try to find the common error between the 3 apps when deployed with PM2 version 2.10.2. All 3 were deployed successfully with PM2 version 2.10.1

Adalidda
