### ISSUE TITLE
reset application id 

### ISSUE THREAD

**Issue by adityamertia** [Unitech/pm2#3583]
Hi,

Is there a way in pm2 to reset the application id. PM2 version: v2.9.3
`pm2 delete all` should have reset all ids but it doesn't seem to do that. Is there any other way to reset the application id from ecosystem.js Logs below:
I am able to reset the application id only with `pm2 updatePM2` and not after `pm2 delete all`

**Comment by adityamertia** [comment]
Something that is irrelevant for user should not be shown to the user. And there is already #1371 that talks about it. 
If i keep deleting all apps and restarting the apps using `pm2 start ecosystem.js` it will keep on incrementing the ids indefinitely which by default also gets appended to the log files (logfilename-out-id.log). I am not quite clear on why it can't be reset. id can also be used to restart the application `pm2 restart <id>`

**Comment by adityamertia** [comment]
@vmarchaud any update pls ?

**Comment by hackstackmaster** [comment]
yes a good option to have !!!
