### ISSUE TITLE
Unable to run PM2 from a PHP API

### ISSUE THREAD

**Issue by rcfrias** [Unitech/pm2#3585]
## What's going wrong?
I am trying to run pm2 -v from the "apache" user (php api)

## How could we reproduce this issue?
Get a php script and execute the command as the user that installed pm2 in the server
i.e.
sudo -u ec2-user /usr/local/bin/pm2 -v

## Supporting information
/usr/bin/env: node: No such file or directory

**Comment by vmarchaud** [comment]
`/usr/bin/env: node: No such file or directory`
Your environment dont seems to find the `node` binary, you should checkout for this but it isn't related to pm2 itself, closing.

**Comment by rcfrias** [comment]
Is there any other way you know to operate pm2 from a php api on the same server? Do I really have to make the user "apache" download an install node and pm2 just for this to work?

**Comment by kounelios13** [comment]
pm2 is written in nodejs so you have to install nodejs

**Comment by rcfrias** [comment]
nodejs is already installed in the box, only that it was installed by another user, and somehow it seems unaccessible from the apache's user

**Comment by alexxk82** [comment]
I had to use a watcher on a directory to got pm2 and php work together. Pm2 watcher on a directory where i put some job.js files.. the files were executing by the watcher script... calling pm2 from a php script also did not work for me ;)
