### ISSUE TITLE
pm2 offical declaration file  incorrect

### ISSUE THREAD

**Issue by franckchen** [Unitech/pm2#3605]
HI:
i use pm2 api to run my service and my service write in typescript, but i found the pm2 declaration file told me the option to config pm2 run in cluster mode is 'execMode'. so my config set execMode = 'cluster'.
but finally,  pm2 run in fork mode. after some investigation, i found the option should be 'exec_mode', i thought that is a bug.
here is my code

```typescript
import path from 'path';
import pm2, {StartOptions} from 'pm2';

import {appName} from '../const/common';

pm2.connect(function (err) {
    if (err) {
        return;
    }

    const pm2Options: StartOptions = {
        name: appName,
        cwd: path.resolve(__dirname, '..'),
        script: '../app.js',
        // finally run in fork mode
        execMode: 'cluster',
        // works, run in cluster mode
        // exec_mode: 'cluster',
        instances: 0,
        maxMemoryRestart: 1024 * 1024 * 1024
    };

    pm2.start(
        pm2Options,
        function (err) {
            pm2.disconnect();

            if (err) {
                return;
            }
        }
    );
});
```

and here is declaration:
https://github.com/Unitech/pm2/blob/master/types/index.d.ts#L371

**Comment by wallet77** [comment]
Hi @franckchen 

Indeed all properties should not be in camelcase.
So it's the same problem with maxMemoryRestart, it should be max_memory_restart
