### ISSUE TITLE
Using PM2 makes concurrency performance worse than command lines

### ISSUE THREAD

**Issue by Dendiom** [Unitech/pm2#3613]
When we did  a stress test(**using locust**) on our mqtt server(only test mqtt connection), we discovered that if we start the project by **pm2 start pm2.json**, the RPS is between 1500~2000 (1500 clients can connect to server per seconds), but if we start it by **node mqttServer.js**, the RPS can reach 3500. 

Has anyone encountered the same problem? Why does this happen?

**Comment by wallet77** [comment]
Good to know !
I never noticed such a difference. Pm2 is like a wrapper around your app, so we can't have same performance comparing to a "standalone" app.
But the difference here is important.
I will give it a try soon !

**Comment by wallet77** [comment]
Hi @Dendiom 

I made some tests but I can't reproduce the gap you had.
Could you share with me how you configure locust ?

I test with a basic hello world app based on express.
I got around 140 RPS wihtout PM2, and 140 with pm2.

I will made some tests on another machine today.

**Comment by superplain99** [comment]
I have same issue.
especially with cluster mode, i got 20% lower performance. (1 cluster vs  native node)
and i have 40core(physical 20 + hyper thread 20 ) server machine.
but performance not going up from 5 or 6 cluster.
It is same with 40 cluster.
Am i something wrong?

- pm2.config.js
```
module.exports = {
        apps: [{
                name: 'ssp',
                script: './server.js',
                instances: 0,
                exec_mode: "cluster"
}]};
```

- test code
```
const Koa = require('koa');
const app = new Koa();

app.use(async ctx => {
  ctx.body = 'Hello World, koa.js';
});

app.listen(3000);
```

**Comment by Unitech** [comment]
Which Node.js version are you using @Dendiom @superplain99 ?

**Comment by Dendiom** [comment]
@Unitech @wallet77 
Thank you for your replay！
We use node **v8.9.1** for the test. As for the test details, we use sequelize(mysql orm) to do some authentication and authorization on mqtt's connection callback. When rps is very high, sequelize will throw 'ResourceTimeOut error' which caused by the slow release of mysql connection and the mem will increase quickly. 
The test phenomenon is that if we use **pm2** to start the process, sequelize will throw this error at a lower rps than using **node XXX** . We don't think there are any associations between pm2 and sequelize but the only difference between two test is the way to start mqtt server, so the test results make us confused. It's difficult to reproduce this result because our program is much more conmplicated than a simple http response. By the way, there are some other node processses managered by pm2, will this cause a gap? 
Thank you for your attension again!

**Comment by Unitech** [comment]
Np! How many CPUs are available on the server? Could you show us the pm2.json file?

If you have a sample code so we can try to reproduce this it would be very welcome.

About the node processed managed by PM2, for sure it's better to not clusterize your app across all CPUs available but instead make one CPU free for PM2 just in case

**Comment by superplain99** [comment]
@Unitech
I tried same benchmark with yours.
my node version is 10.0.0
and pm2 is 2.10.3

- node server.koa.js
```
./wrk -t 100 -c 100 htt://localhost:3000
Running 10s test @ htt://localhost:3000
  100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.19ms  394.60us  14.70ms   95.07%
    Req/Sec   193.54     10.65   272.00     93.12%
  194364 requests in 10.10s, 29.66MB read
Requests/sec:  19244.27
Transfer/sec:      2.94MB
```

- pm2 start server.koa.js -i 1
```
./wrk -t 100 -c 100 htt://localhost:3000
Running 10s test @ htt://localhost:3000
  100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    11.10ms   42.01ms 630.12ms   97.71%
    Req/Sec   183.11     19.43   260.00     91.81%
  180250 requests in 10.10s, 27.50MB read
Requests/sec:  17846.36
Transfer/sec:      2.72MB
```

is there anything i need to check??

**Comment by superplain99** [comment]
@Unitech 
Thank you for your test.
I tried same test with yours. Result is same between native node and  pm2.
But Using tool i used (http://naver.github.io/ngrinder/)  give me different result.
I don't know why. 
It's just load generator like wrk.
Do you have any clue?

**Comment by Dendiom** [comment]
@Unitech 
Thank you for your reply again! But I'm sorry that our boss told us to ignore the gap and we decide to do some load balance to avoid sequelize error.Thank you for your help!

**Comment by wallet77** [comment]
Closed due to lack of activity.
Feel free to reopen if necessary.

**Comment by nooballday** [comment]
Its weird, i've tried @Unitech's snippet and the result is not quite the same

`>>node index.js`

`ab -c 100 -n 1000 http://localhost:3000/`

Requests per second:    2907.85 [#/sec] (mean)
Time per request:       34.390 [ms] (mean)
Time per request:       0.344 [ms] (mean, across all concurrent requests)
Transfer rate:          440.15 [Kbytes/sec] received

`pm2 start index.js -i max`

`ab -c 100 -n 1000 http://localhost:3000/`

Requests per second:    2138.90 [#/sec] (mean)
Time per request:       46.753 [ms] (mean)
Time per request:       0.468 [ms] (mean, across all concurrent requests)
Transfer rate:          323.76 [Kbytes/sec] received

**Comment by mckibet** [comment]
my observation is that pm2 performance degrades when you are running logs at the same time
