### ISSUE TITLE
PM2 not working on Electron when asar is enabled

### ISSUE THREAD

**Issue by ndrantotiana** [Unitech/pm2#3617]
When packing my Electron application with the last version of PM2, I'm having the following error while asar is enabled (may be similar to  #2651)

> Error: Cannot find module 'c:\Program Files\MyApp\resources\app.asar\node_modules\pm2\lib\Daemon.js'
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Function.Module.runMain (module.js:693:10)
at startup (bootstrap_node.js:188:16)
at bootstrap_node.js:609:3

**Comment by ndrantotiana** [comment]
Anyone could help please?

**Comment by nmccready** [comment]
Looks like pm2 is a needed dependency of your main apps package.json, so add it.

**Comment by nmccready** [comment]
I am using pm2 with app.asar and it is working fine, it is within electron.asar that I have issues and it may be a similar problem.

**Comment by ayizhi** [comment]
> I am using pm2 with app.asar and it is working fine, it is within electron.asar that I have issues and it may be a similar problem.

Is it run on windows system?

**Comment by ayizhi** [comment]
I find the problem is lead by 
`var ClientJS = path.resolve(path.dirname(module.filename), 'Daemon.js');”`
 and 
`  var child = require('child_process').spawn(interpreter, node_args, {
    detached   : true,
    cwd        : that.conf.cwd || process.cwd(),
    env        : util._extend({
      'SILENT'      : that.conf.DEBUG ? !that.conf.DEBUG : true,
      'PM2_HOME'   : that.pm2_home
    }, process.env),
    stdio      : ['ipc', out, err]
  });`

in lib/Client.js

because of `spawn` cannot resolve the "Daemon.js" in asar

I can just try to change the source code but it is not graceful

**Comment by Unitech** [comment]
> It will be nice if the defination of ClientJs can by explosure to developer @Unitech thanks !

How do you see this?

**Comment by SashaDesigN** [comment]
I have the same issue with electron & pm2 in production after build binaries. It says nothing on pm2 start and returns null.

**Comment by SashaDesigN** [comment]
The issue is that Electron by default uses asar filesystem, so pm2 can't access files inside of it - I was able to make it work by adding asar: false into build config in package.json

**Comment by jgresham** [comment]
If `pm2.connect()` could throw an error in this case, that'd be helpful. Here is the error from `~/.pm2/pm2.log`
```
node:internal/modules/cjs/loader:936
  throw err;
  ^
Error: Cannot find module '/opt/<app-name>/resources/app.asar/node_modules/pm2/lib/Daemon.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```
