### ISSUE TITLE
aws codedeploy pm2 command not found.

### ISSUE THREAD

**Issue by matesio** [Unitech/pm2#3621]
I am trying to deploy nodeJS application using pm2, when i write on my console pm2 is working fine. but when i start code deploy processes it gives me error pm2 command not found.

LifecycleEvent - BeforeInstall
Script - scripts/stop_server.sh
[stderr]/opt/codedeploy-agent/deployment-root/da4fdd04-fc36-4bcd-a7d4-be85638f0204/d-Y53GTVVOS/deployment-archive/scripts/stop_server.sh: line 3: pm2: command not found

i installed it using -g ,with sudo.
here is my stop_server.sh:
#!/bin/bash
pm2 kill

**Comment by aaasp18** [comment]
+1

**Comment by jvguillen** [comment]
I ran into a similar issue. For some reason installing nodejs in the [recommend way by aws](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-up-node-on-ec2-instance.html) causes this problem.

I ended up install nodejs the following way:
```bash
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo apt-get install -y build-essential
```
