### ISSUE TITLE
How to disable log message "Unknown id _old_1"?

### ISSUE THREAD

**Issue by extensionsapp** [Unitech/pm2#3624]
## What's going wrong?
My log PM2. Every second "Unknown id _old_1"

![30703622-e689e0f6-9ef8-11e7-88a6-1cc92724f041](https://user-images.githubusercontent.com/8192379/39085185-b918612a-4587-11e8-868e-8441e59b5a9b.gif)

I have log files of 3GB. How to disable log message "Unknown id _old_1"?

![30704042-140c254c-9efa-11e7-87d5-97a8658a96a3](https://user-images.githubusercontent.com/8192379/39085256-bc02e8a0-4588-11e8-967a-a56283119691.gif)

## How could we reproduce this issue?

I do not know, maybe after the restart.

## Supporting information

```
$ pm2 report
===============================================================================
--- PM2 REPORT (Sat Apr 21 2018 17:17:51 GMT+0300 (MSK)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.10.2
node version         : 8.11.1
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : undefined
uid                  : 0
gid                  : 0
uptime               : 36min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.10.2
node version         : 8.11.1
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU D-1531 @ 2.20GHz
cpus nb              : 6
freemem              : 6739058688
totalmem             : 8363978752
home                 : /root
===============================================================================
```

**Comment by nhim175** [comment]
I got the same issue.

**Comment by RabeaWahab** [comment]
`pm2 kill` took care of the dead process 

https://github.com/Unitech/pm2/issues/2028

**Comment by SilentWalker** [comment]
`pm2 kill` works , but kills all process

**Comment by ajimix** [comment]
I'm having this problem since updating to version 4. The only solution is to do this: `pm2 kill && pm2 resurrect`

I've set up a cron job that runs this every hour and that so far "solved" the problem. Hopefully, there is a fix soon

**Comment by BarryRufer** [comment]
![p5bsfQe](https://user-images.githubusercontent.com/57297188/68248777-2a7fd780-0026-11ea-8f04-5cf308df85ad.png)

**Comment by BarryRufer** [comment]
PM2 version          : 4.1.2
Node.js version     : 10.16.3
Current arch         : x64

**Comment by krunkosaurus** [comment]
> pm2 kill && pm2 resurrect

Thanks this fixed it for me when nothing else would.

**Comment by yunnysunny** [comment]
> PM2 version : 4.1.2
> Node.js version : 10.16.3
> Current arch : x64

We have the same problem.

**Comment by roysG** [comment]
" --no-pmx"
Does someone tried to fix it with add this parameter when running pm2 start?
