### ISSUE TITLE
Cannot start PM2 with npm

### ISSUE THREAD

**Issue by theHazzard** [Unitech/pm2#3628]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/Unitech/pm2/search?type=Issues) before creating one.

## What's going wrong?
I want to start npm through pm2, I only found an issue saying that I have to run
```bash
 pm2 start npm -- start
```

I want to start it from a config file using
```bash
pm2 start pm2.production.json
```

how can I set the file to start npm instead of node?

## How could we reproduce this issue?
try to set npm on the config file

## Supporting information

Please run the following command (available on PM2 >= 2.6)

```
$ pm2 report
```

**Comment by Unitech** [comment]
Let's say you have a ecosystem.config.js file:

```
module.exports = {
  "script" : "npm",
  "args" : "start"                                                                                                                                                                                                  
}
```

Then

```
$ pm2 start ecosystem.config.js
```

**Comment by theHazzard** [comment]
Crear! Thanks
