### ISSUE TITLE
Pass arguments to binary file on windows 10

### ISSUE THREAD

**Issue by Bentleyj** [Unitech/pm2#3631]
I am running pm2 on windows 10 and I want to execute some binary files programmatically with a node app.

I've coppied the syntax from the example for a .js app but my arguments are not being passed properly to the binary by pm2.

Here is my function in my node app. This corrctly launches the .exe files but does not pass the arguments correctly so it immediately crashes.
```javascript
function startRecorder() {
	console.log("Starting Recorder!");
	pm2.start({
		name		: "recorder",
		script		: "test-sunrise-kingdom-recorder-v0-2018-04-26-1032",
		args		: ["--data-path=./data/Test1032/", "--settings-file=./data/settings-recorderSwitchCam1.xml", "--record-for-seconds=60"],
		exec_mode	: "fork",
		instances	: "1",
		interpreter	: "none",
		maxRestarts	: "3"
	}, function(err, apps) {
		console.log("Error starting Recorder");
		pm2.disconnect();
		if(err) throw err;
	});
}
```
When I run the following line in my CLI:
`pm2 start test-sunrise-kingdom-recorder-v0-2018-04-26-1032.exe -- --data-path "./data/Test1032/" --settings-file "./data/settings-recorderSwitchCam4.xml" --record-for-seconds 60`

It runs and is monitored by pm2 perfectly.

am I missing something about the syntax of the programmatic api for binary files? I have tried various versions of the args line such as:

`["--data-path './data/Test1032/'", "--settings-file './data/settings-recorderSwitchCam1.xml'", "--record-for-seconds 60"]`

But I get the same result.

**Comment by Bentleyj** [comment]
Hi There. Solved my own issue. I did not realize you had to pass each argument in separately.

Here is the correct syntax:

```
function startRecorder(data-path, settings-file, recordDuration) {
	console.log("Starting Recorder!");
	pm2.start({
		name		: "recorder",
		script		: "test-sunrise-kingdom-recorder-v0-2018-04-26-1032",
		args		: ["--data-path", "./data/Test1032/", "--settings-file", "./data/settings-recorderSwitchCam1.xml", "--record-for-seconds", "60"],
		exec_mode	: "fork",
		instances	: "1",
		interpreter	: "none",
		maxRestarts	: "3"
	}, function(err, apps) {
		pm2.disconnect();
		if(err) throw err;
	});
}
```

**Comment by wxf4150** [comment]
interpreter	: "none"
is useful
