### ISSUE TITLE
RScript Process not starting

### ISSUE THREAD

**Issue by sajukassim** [Unitech/pm2#3637]
The below shows error when I am using interpreter RScript

>pm2 start --interpreter=Rscript /sAJUDENTICK/run-myfile.R
[PM2] Applying action restartProcessId on app [run-myfile](ids: 0)
[PM2] [run-myfile](0) ✓
[PM2] Process successfully started
┌────────────┬────┬──────┬─────┬─────────┬─────────┬────────┬─────┬────────┬──────┬──────────┐
│ App name   │ id │ mode │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user │ watching │
├────────────┼────┼──────┼─────┼─────────┼─────────┼────────┼─────┼────────┼──────┼──────────┤
│ run-myfile │ 0  │ fork │ N/A │ errored │ 0       │ 0      │ 0%  │ 0 B    │ HP   │ disabled │
└────────────┴────┴──────┴─────┴─────────┴─────────┴────────┴─────┴────────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app

**Comment by sajukassim** [comment]
running rom command prompt C:\Program Files\R\R-3.4.3\bin, it works..

**Comment by Unitech** [comment]
I don't see any error in the output
