### ISSUE TITLE
Performance issue with new 2.10.3 release

### ISSUE THREAD

**Issue by Stradivario** [Unitech/pm2#3638]
## What's going wrong?
I have CI/CD with gitlab with private docker container.
I run my builds with gitlab runner from very long time
I am using nodejs and pm2 + pm2-docker to scale my containers
So far so good in my Dockerfile i have this
```yml

FROM node:8.9.4

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

RUN npm install -g pm2-docker ts-node typescript @gapi/cli pm2 jest

COPY package.json package.json

RUN npm install

ENV NODE_ENV=production  

COPY . .

CMD [ "gapi", "start", "--prod", "--docker" ]

```

So i am installing Evergreen version for every container every time in about 3 4 days i re-cache docker cache and i take the new dependencies.So far so good.
Yestarday i noticed that my PC is running something really intensive :D 100% on 24 Cores ?!?! :D 
I saw that when i Push to my gitlab it triggers Build which takes the new version of pm2 2.10.3 and my application FREEZES for about 2 Minutes with Intensive 100% CPU load when i attach to container and explore what is happening pm2 log JUST stays like that and nothing is happening in about 2 minutes my 4 Clusters are starting inside this container but my Computer Freezes. I decided to install pm2@2.10.2 just in case that this was the problem and everything work fine like usual.So i decided to tell you about my problem and what i am facing.

Node: 8.9.4
pm2: 2.10.3
OS: Ubuntu 18.04
Docker: 18.03.1-c

When i install pm2@2.10.2 problem went away :+1: 
Everything else is working just fine except that my computer Freezes on Builds which is not appropriate i will stick to 2.10.2 for now.

===============================================================================
--- PM2 REPORT (Mon Apr 30 2018 16:42:35 GMT+0000 (UTC)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.10.3
node version         : 8.9.4
node path            : undefined
argv                 : /usr/local/bin/node,/usr/local/bin/pm2-docker,process.yml,--only,APP
argv0                : node
user                 : undefined
uid                  : 0
gid                  : 0
uptime               : 10min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.10.3
node version         : 8.9.4
node path            : /usr/local/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/bin/pm2,report
argv0                : node
user                 : undefined
uid                  : 0
gid                  : 0
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU           X5675  @ 3.07GHz
cpus nb              : 12
freemem              : 26487549952
totalmem             : 46405005312
home                 : /root
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬─────────┬─────┬────────┬─────────┬────────┬─────┬────────────┬──────┬──────────┐
│ App name │ id │ mode    │ pid │ status │ restart │ uptime │ cpu │ mem        │ user │ watching │
├──────────┼────┼─────────┼─────┼────────┼─────────┼────────┼─────┼────────────┼──────┼──────────┤
│ APP      │ 0  │ cluster │ 23  │ online │ 0       │ 10m    │ 0%  │ 156.9 MB   │ root │ disabled │
│ APP      │ 1  │ cluster │ 29  │ online │ 0       │ 10m    │ 0%  │ 156.8 MB   │ root │ disabled │
│ APP      │ 2  │ cluster │ 55  │ online │ 0       │ 10m    │ 0%  │ 156.9 MB   │ root │ disabled │
│ APP      │ 3  │ cluster │ 81  │ online │ 0       │ 10m    │ 0%  │ 157.6 MB   │ root │ disabled │
└──────────┴────┴─────────┴─────┴────────┴─────────┴────────┴─────┴────────────┴──────┴──────────┘

**Comment by wallet77** [comment]
Hi @Stradivario 

I will try some benchmark.
In my memories version 2.10.3 contains only some fix for node 10. (not directly in pm2 source code but in another dependency).
I really don't understand how it can affect pm2 behavior and CPU consumption.
