### ISSUE TITLE
Running wiki.js in pm2 is always restarting the application and doesn't work

### ISSUE THREAD

**Issue by eddorneles** [Unitech/pm2#3641]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/Unitech/pm2/search?type=Issues) before creating one.

## What's going wrong?
I'm trying to run [wiki.js](https://github.com/Requarks/wiki)  on Windows Server 2012 with pm2.
When I run command `pm2 start` for the application it is always restarting.
As you can see in the pm2 log:

> 0|wiki     | Commands:
0|wiki     |   start             Start Wiki.js process
0|wiki     |   stop              Stop Wiki.js process
0|wiki     |   restart           Restart Wiki.js process
0|wiki     |   configure [port]  Configure Wiki.js using the web-based setup wizard
0|wiki     |
0|wiki     | Options:
0|wiki     |   --help     Show help                                                 [boolean]
0|wiki     |   --version  Show version number                                       [boolean]
0|wiki     |
0|wiki     | Read the docs at https://wiki.requarks.io
0|wiki     |
0|wiki     | You must provide one of the accepted commands above.
0|wiki     | √ Wiki.js has started successfully.
0|wiki     | √ Wiki.js has started successfully.

>PM2        | Stopping app:wiki id:0
PM2        | App [wiki] with id [0] and pid [3744], exited with code [1] via signal [SIGINT]
PM2        | pid=3744 msg=process killed
PM2        | Starting execution sequence in -fork mode- for app name:wiki id:0
PM2        | App name:wiki id:0 online
PM2        | Stopping app:wiki id:0
PM2        | App [wiki] with id [0] and pid [6992], exited with code [1] via signal [SIGINT]
PM2        | pid=6992 msg=process killed
PM2        | Starting execution sequence in -fork mode- for app name:wiki id:0
PM2        | App name:wiki id:0 online
PM2        | Stopping app:wiki id:0
PM2        | App [wiki] with id [0] and pid [1288], exited with code [1] via signal [SIGINT]
PM2        | pid=1288 msg=process killed
PM2        | Starting execution sequence in -fork mode- for app name:wiki id:0
PM2        | App name:wiki id:0 online
PM2        | Stopping app:wiki id:0
PM2        | App [wiki] with id [0] and pid [924], exited with code [1] via signal [SIGINT]
PM2        | pid=924 msg=process killed
PM2        | Starting execution sequence in -fork mode- for app name:wiki id:0

After the configuration all I need to do to run the wiki.js is use the command: `node wiki.js start`
and it works perfectly the issu only occurs with pm2

## How could we reproduce this issue?
In wiki.js directory I run `pm2 start wiki.js -- start` 
then `pm2 log`
## Supporting information

 PM2 REPORT (Thu May 03 2018 11:54:12 GMT-0300 (SA Eastern Standard Time)) -

Daemon 
pm2d version         : 2.10.3
node version         : 8.11.1
node path            : C:/Program Files/nodejs/node
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\u10464\AppData\Roaming\npm\node_modules\pm2\lib\Daemon.js
argv0                : node
user                 : undefined
uid                  : N/A
gid                  : N/A
uptime               : 8min

CLI 
local pm2            : 2.10.3
node version         : 8.11.1
node path            : C:/Program Files/nodejs/node
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\u10464\AppData\Roaming\npm\node_modules\pm2\bin\pm2,report
argv0                : C:\Program Files\nodejs\node.exe
user                 : u10464

System info 
arch                 : x64
platform             : win32
type                 : Windows_NT
cpus                 : Intel(R) Xeon(R) CPU E5-2699 v3 @ 2.30GHz
cpus nb              : 2
freemem              : 351764480
totalmem             : 4294496256
home                 : C:\Users\u10464

PM2 list
┌──────────┬────┬──────┬──────┬────────┬─────────┬────────┬─────┬───────────┬────────┬──────────┐
│ App name │ id │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem       │ user   │ watching │
├──────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────┼───────────┼────────┼──────────┤
│ wiki     │ 0  │ fork │ 3496 │ online │ 282     │ 1s     │ 0%  │ 45.2 MB   │ u10464 │ disabled │
└──────────┴────┴──────┴──────┴────────┴─────────┴────────┴─────┴───────────┴────────┴──────────┘
C:\Users\u10464\.pm2\pm2.log last 20 lines:
PM2        | [2018-05-03 11:54:06] PM2 log: Stopping app:wiki id:0
PM2        | [2018-05-03 11:54:06] PM2 log: App [wiki] with id [0] and pid [6232], exited with code [1] via signal [SIGINT]
PM2        | [2018-05-03 11:54:06] PM2 log: pid=6232 msg=process killed
PM2        | [2018-05-03 11:54:06] PM2 log: Starting execution sequence in -fork mode- for app name:wiki id:0
PM2        | [2018-05-03 11:54:06] PM2 log: App name:wiki id:0 online
PM2        | [2018-05-03 11:54:07] PM2 log: Stopping app:wiki id:0
PM2        | [2018-05-03 11:54:07] PM2 log: App [wiki] with id [0] and pid [2512], exited with code [1] via signal [SIGINT]
PM2        | [2018-05-03 11:54:07] PM2 log: pid=2512 msg=process killed
PM2        | [2018-05-03 11:54:07] PM2 log: Starting execution sequence in -fork mode- for app name:wiki id:0
PM2        | [2018-05-03 11:54:07] PM2 log: App name:wiki id:0 online
PM2        | [2018-05-03 11:54:09] PM2 log: Stopping app:wiki id:0
PM2        | [2018-05-03 11:54:09] PM2 log: App [wiki] with id [0] and pid [1540], exited with code [1] via signal [SIGINT]
PM2        | [2018-05-03 11:54:09] PM2 log: pid=1540 msg=process killed
PM2        | [2018-05-03 11:54:09] PM2 log: Starting execution sequence in -fork mode- for app name:wiki id:0
PM2        | [2018-05-03 11:54:09] PM2 log: App name:wiki id:0 online
PM2        | [2018-05-03 11:54:11] PM2 log: Stopping app:wiki id:0
PM2        | [2018-05-03 11:54:11] PM2 log: App [wiki] with id [0] and pid [1124], exited with code [1] via signal [SIGINT]
PM2        | [2018-05-03 11:54:11] PM2 log: pid=1124 msg=process killed
PM2        | [2018-05-03 11:54:11] PM2 log: Starting execution sequence in -fork mode- for app name:wiki id:0
PM2        | [2018-05-03 11:54:11] PM2 log: App name:wiki id:0 online

**Comment by Unitech** [comment]
How did you installed wiki.js? git clone or via `iex ((New-Object System.Net.WebClient).DownloadString('https://wiki.js.org/install.ps1'))`?
