### ISSUE TITLE
PM2 error: Error: spawn node ENOENT

### ISSUE THREAD

**Issue by atubo2012** [Unitech/pm2#3648]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/Unitech/pm2/search?type=Issues) before creating one.

## What's going wrong?
When I start up using following command, there are some errors in pm2.log : 
pm2 start process.json 
=====errors in pm2.log===============
**[2018-05-07 16:21:11] PM2 error: Error: spawn node ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)**

## Supporting information

Please run the following command (available on PM2 >= 2.6)
===============================================================================
--- PM2 REPORT (Mon May 07 2018 16:40:27 GMT+0800 (中国标准时间)) -------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.10.3
node version         : 6.11.0
node path            : undefined
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\x1\AppData\Roaming\npm\node_modules\pm2\lib\Daemon.js
argv0                : node
user                 : undefined
uid                  : N/A
gid                  : N/A
uptime               : 5min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.10.3
node version         : 6.11.0
node path            : undefined
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\x1\AppData\Roaming\npm\node_modules\pm2\bin\pm2,report
argv0                : node
user                 : x1
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : win32
type                 : Windows_NT
cpus                 : Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
cpus nb              : 4
freemem              : 3017281536
totalmem             : 8419135488
home                 : C:\Users\x1
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬──────┬─────┬─────────┬─────────┬────────┬─────┬────────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user │ watching │
├──────────┼────┼──────┼─────┼─────────┼─────────┼────────┼─────┼────────┼──────┼──────────┤
│ zhaogong │ 0  │ fork │ N/A │ errored │ 0       │ 0      │ 0%  │ 0 B    │ x1   │ enabled  │
└──────────┴────┴──────┴─────┴─────────┴─────────┴────────┴─────┴────────┴──────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
C:\Users\x1\.pm2\pm2.log last 20 lines:
PM2        | [2018-05-07 16:34:46] PM2 log: Node.js version      : 6.11.0
PM2        | [2018-05-07 16:34:46] PM2 log: Current arch         : x64
PM2        | [2018-05-07 16:34:46] PM2 log: PM2 home             : C:\Users\x1\.pm2
PM2        | [2018-05-07 16:34:46] PM2 log: PM2 PID file         : C:\Users\x1\.pm2\pm2.pid
PM2        | [2018-05-07 16:34:46] PM2 log: RPC socket file      : \\.\pipe\rpc.sock
PM2        | [2018-05-07 16:34:46] PM2 log: BUS socket file      : \\.\pipe\pub.sock
PM2        | [2018-05-07 16:34:46] PM2 log: Application log path : C:\Users\x1\.pm2\logs
PM2        | [2018-05-07 16:34:46] PM2 log: Process dump file    : C:\Users\x1\.pm2\dump.pm2
PM2        | [2018-05-07 16:34:46] PM2 log: Concurrent actions   : 2
PM2        | [2018-05-07 16:34:46] PM2 log: SIGTERM timeout      : 1600
PM2        | [2018-05-07 16:34:46] PM2 log: ===============================================================================
PM2        | [2018-05-07 16:34:46] PM2 log: [Watch] Start watching zhaogong
PM2        | [2018-05-07 16:34:46] PM2 log: Starting execution sequence in -fork mode- for app name:zhaogong id:0
PM2        | [2018-05-07 16:34:46] PM2 log: App name:zhaogong id:0 online
PM2        | [2018-05-07 16:34:46] PM2 error: Error: spawn node ENOENT
PM2        |     at exports._errnoException (util.js:1018:11)
PM2        |     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
PM2        |     at onErrorNT (internal/child_process.js:367:16)
PM2        |     at _combinedTickCallback (internal/process/next_tick.js:80:11)
PM2        |     at process._tickDomainCallback (internal/process/next_tick.js:128:9)

```
$ pm2 report
```

**Comment by Unitech** [comment]
how did you installed nodejs?

**Comment by atubo2012** [comment]
Solved after I changed the path in the process.json from "cwd": "/root/dev/zhaogong-be" to "cwd": "d:/zhaogong-be".

**Comment by alsotang** [comment]
I also meet this error message, and I solved it.

I use `pm2 startup` to init my services when the vps restart, and pm2 can not start my nodejs program with this error message.

After I inspect my environment, I find that I install nodejs through fnm(https://github.com/Schniz/fnm). My nodejs program is not in the system's original $PATH but a custom place. So maybe the start time of fnm is later than pm2. 

Instead, I install nodejs from apt.

from https://github.com/nodesource/distributions/blob/master/README.md

```
# Using Ubuntu
curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
sudo apt-get install -y nodejs

# Using Debian, as root
curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
apt-get install -y nodejs
```

**Comment by axi** [comment]
Found this while searching "PM2 error: Error: spawn node ENOENT" and it helped me figuring out that was a nodejs version issue. I wasn't using correct version, had to use:
```
pm2 start server.js --interpreter=/home/ubuntu/.nvm/versions/node/v16.13.2/bin/node
```

In case it can help someone someday :-)

**Comment by adrienjoly** [comment]
I got `spawn node ENOENT` and `TypeError: One of the pids provided is invalid` errors when trying to (re)start my app, after removing an old version of Node.js using `nvm uninstall vX.XX.XX`.

I fixed it by adding `--interpreter=$(nvm which default)` to `$ pm2 start app.js`. 🎉

Thank you @axi and @htolic (https://github.com/Unitech/pm2/issues/1413#issuecomment-125201497) for the hints! 🙌
