### ISSUE TITLE
[Docker] Typescript failing to start

### ISSUE THREAD

**Issue by samdenty** [Unitech/pm2#3649]
## What's going wrong?

PM2 is not behaving correctly when I attempt to start typescript files using docker.

## How could we reproduce this issue?

**Dockerfile**

```dockerfile
FROM keymetrics/pm2:latest-alpine

COPY index.ts index.ts
RUN pm2 install typescript

CMD [ "pm2-runtime", "start", "index.ts" ]
```

**index.ts**
```ts
console.log(1)
```

![image](https://user-images.githubusercontent.com/13242392/39703457-014e6820-5200-11e8-939d-b989d2fbed86.png)

[now.sh instance](https://zeit.co/samdd/t/afrnklpnjl)

**Comment by eddiemonge** [comment]
I'm getting cannot find TypeScript now when trying to do the same

**Comment by samdenty** [comment]
See https://github.com/TypeStrong/ts-node/issues/690
