### ISSUE TITLE
Identifying active handles reported by pm2 monit

### ISSUE THREAD

**Issue by steinfernandez** [Unitech/pm2#3655]
I'm using pm2 to run an app on two instances cloned from the same AMI on Amazon EC2. Recently, the app on instance 1 has started to consume far more memory than normal (immediately swells to 700mb on startup as compared to usual 200mb), while instance 2 behaves normally. Examining the instances for possible differences, I noticed that pm2 monit on instance 1 reports the app as having 2500+ active handles open despite minimal traffic to it. This is not the case on instance 2. Is there any way to identify what these active handles are and what's causing them? Thanks.

**Comment by wallet77** [comment]
Hi @steinfernandez 

Not directly with PM2.
Keymetrics has a "dump" feature for event loop. So you can see which handles are still opened.
And you can also use this module to make a dump by yourself : https://www.npmjs.com/package/event-loop-inspector
