### ISSUE TITLE
PM2 cpus used

### ISSUE THREAD

**Issue by tasca** [Unitech/pm2#3656]
I have server 2 cpus

config.json
{
   "apps": [
     {
       "exec_mode": "cluster_mode",
       "script": "server.js",
       "name": "server",
       "instances": 1,
       "env": {
         "PORT": 7000,
         "NODE_ENV": "production"
       },
       "error_file": "/home/tasca/server/logs/server-erro.log",
       "out_file": "/home/tasca/server/logs/server.out.log"
     },
     {
       "exec_mode": "cluster_mode",
       "script": "server.js",
       "name": "zampieri",
       "instances": 1,
       "env": {
         "PORT": 7001,
         "NODE_ENV": "production"
       },
       "error_file": "/home/tasca/server/logs/zampieri-erro.log",
       "out_file": "/home/tasca/server/logs/zampieri.out.log"
     }
}

Will PM2 use the 2 cpus?
a cluster every cpu?
thanks...

**Comment by wallet77** [comment]
Hi @tasca 

In your case pm2 will create a cluster for each application (even if it's the same file (server.js)).
So yes it will share the load on cpu.
But keep in mind that is not really pm2 which do that but your OS. Pm2 can only fork your application to create child process. Then your OS will do the rest.

You can see it if you use `ps -aux`, you will see two different processes.

![screenshot from 2018-05-14 16-56-29](https://user-images.githubusercontent.com/5022887/40005894-5e603a2c-5799-11e8-9529-8ddc15cf21ea.png)
