### ISSUE TITLE
`pm2 start npm -- start` error

### ISSUE THREAD

**Issue by marekchen** [Unitech/pm2#3657]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/Unitech/pm2/search?type=Issues) before creating one.

## What's going wrong?
After I run `pm2 start npm -- start`,then get errored.
error info is 
```
C:\PROGRAM FILES\NODEJS\NPM.CMD:1
(function (exports, require, module, __filename, __dirname) { :: Created by npm, please don't edit manually.
                                                              ^

SyntaxError: Unexpected token :
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Object.<anonymous> (C:\Users\marek\AppData\Roaming\npm\node_modules\pm2\lib\ProcessContainerFork.js:83:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
C:\PROGRAM FILES\NODEJS\NPM.CMD:1
(function (exports, require, module, __filename, __dirname) { :: Created by npm, please don't edit manually.
```

I found someone get the same error in [stackoverflow](https://stackoverflow.com/questions/50027163/pm2-start-npm-start-error).
Maybe it only get errored in win10, It works in my macbook.

## How could we reproduce this issue?
1.clone https://github.com/marekchen/pm-web3
2.npm install
3.npm run build
4.pm2 start npm -- start

## Supporting information
===============================================================================
--- PM2 REPORT (Fri May 11 2018 11:01:16 GMT+0800 (中国标准时间)) -------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.10.3
node version         : 8.11.1
node path            : undefined
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\marek\AppData\Roaming\npm\node_modules\pm2\lib\Daemon.js
argv0                : node
user                 : undefined
uid                  : N/A
gid                  : N/A
uptime               : 58min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.10.3
node version         : 8.11.1
node path            : undefined
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\marek\AppData\Roaming\npm\node_modules\pm2\bin\pm2,report
argv0                : node
user                 : chenpei
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : win32
type                 : Windows_NT
cpus                 : Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
cpus nb              : 8
freemem              : 8662110208
totalmem             : 17035272192
home                 : C:\Users\marek
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬──────┬─────┬─────────┬─────────┬────────┬─────┬────────┬─────────┬──────────┐
│ App name │ id │ mode │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user    │ watching │
├──────────┼────┼──────┼─────┼─────────┼─────────┼────────┼─────┼────────┼─────────┼──────────┤
│ pm-web   │ 0  │ fork │ 0   │ errored │ 15      │ 0      │ 0%  │ 0 B    │ chenpei │ disabled │
└──────────┴────┴──────┴─────┴─────────┴─────────┴────────┴─────┴────────┴─────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌──────────┬────┬──────┬─────┬─────────┬─────────┬────────┬─────┬────────┬─────────┬──────────┐
│ App name │ id │ mode │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user    │ watching │
├──────────┼────┼──────┼─────┼─────────┼─────────┼────────┼─────┼────────┼─────────┼──────────┤
│ pm-web   │ 0  │ fork │ 0   │ errored │ 15      │ 0      │ 0%  │ 0 B    │ chenpei │ disabled │
└──────────┴────┴──────┴─────┴─────────┴─────────┴────────┴─────┴────────┴─────────┴──────────┘

**Comment by Unitech** [comment]
What is inside run in the start directive in your package.json?

**Comment by lalalalaluk** [comment]
I have the same issue
my start directive is 
 "start": "ts-node -r tsconfig-paths/register src/main.ts ",

I use nest.js 
Why can't PM2 start QQ

**Comment by nicowernli** [comment]
I'm having the same issue, I think the problem comes when pm2 tries to read the npm.cmd file. When running `Get-Command npm` I get the path of the npm which my system is using and if I check the content of that file I see the same text from the error.

```
C:\Users\nicow\development\project [master ≡ +2 ~1 -0 !]> Get-Command npm

CommandType     Name                     Version    Source
-----------     ----                     -------    ------
Application     npm.cmd                  0.0.0.0    C:\Program Files\nodejs\npm.cmd
```
```
:: Created by npm, please don't edit manually.
@ECHO OFF

SETLOCAL

SET "NODE_EXE=%~dp0\node.exe"
IF NOT EXIST "%NODE_EXE%" (
  SET "NODE_EXE=node"
)

SET "NPM_CLI_JS=%~dp0\node_modules\npm\bin\npm-cli.js"
FOR /F "delims=" %%F IN ('CALL "%NODE_EXE%" "%NPM_CLI_JS%" prefix -g') DO (
  SET "NPM_PREFIX_NPM_CLI_JS=%%F\node_modules\npm\bin\npm-cli.js"
)
IF EXIST "%NPM_PREFIX_NPM_CLI_JS%" (
  SET "NPM_CLI_JS=%NPM_PREFIX_NPM_CLI_JS%"
)

"%NODE_EXE%" "%NPM_CLI_JS%" %*
```

**Comment by nguiard** [comment]
This is still happening on my Windows 10 machine. Whatever globally installed program from npm I try to start from pm2, it gives me this error.

Seems like pm2 assumes the program passed (npm, verdaccio, or whatever) to be a js file to be run with node, when they actually are .cmd files.
Reason I think so : you get the exact same errors if you locate the `<app>.cmd` file and try to run
`node <path_to_app>/<app>.cmd`. Of course node doesn't like to have to run a .cmd file.

I wonder however why pm2 makes that assumption. Because if you try `pm2 start node` for example, that works fine. It seems to only make the assumption on programs installed from npm (but I haven't tested a ton either).

However that all means there is a relatively easy workaround if you need it for now. As pm2 assumes a js file, just pass the js file the .cmd is trying to run. Locate the .js that the .cmd is trying to run, and give the absolute path to pm2. For instance:
`pm2 start "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js"`
or
`pm2 start C:\Users\Nicolas\AppData\Roaming\npm\node_modules\...\<script>.js`

That also works if you put it in the ecosystem file, as the `script` entry for the app.

**Comment by msm1089** [comment]
@nguiard Thanks for your workaround, works as expected. Only thing is I get a cmd window open whenever I run the command. Any idea how to prevent this?

**Comment by joelgb2194** [comment]
@msm1089 Did you figure out how to hide the cmd window?

**Comment by Feng-xiaoji** [comment]
> @msm1089 Did you figure out how to hide the cmd window?
“npm i -g pm2-windows-service”,
then add “PM2_HOME = xxx/.pm2” to system path , 
”pm2-service-install“ , first step choose "no", 
 services.msc you will see "pm2" 
maybe help you

**Comment by HerokunTan** [comment]
@nicowernli  Thank! save me!

**Comment by senher** [comment]
> This is still happening on my Windows 10 machine. Whatever globally installed program from npm I try to start from pm2, it gives me this error.
> 
> Seems like pm2 assumes the program passed (npm, verdaccio, or whatever) to be a js file to be run with node, when they actually are .cmd files.
> Reason I think so : you get the exact same errors if you locate the `<app>.cmd` file and try to run
> `node <path_to_app>/<app>.cmd`. Of course node doesn't like to have to run a .cmd file.
> 
> I wonder however why pm2 makes that assumption. Because if you try `pm2 start node` for example, that works fine. It seems to only make the assumption on programs installed from npm (but I haven't tested a ton either).
> 
> However that all means there is a relatively easy workaround if you need it for now. As pm2 assumes a js file, just pass to pm2 the .js file that the .cmd is trying to run. Locate the .js that the .cmd is trying to run, and give the absolute path to pm2. For instance:
> `pm2 start "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js"`
> or
> `pm2 start C:\Users\Nicolas\AppData\Roaming\npm\node_modules\...\<script>.js`
> 
> That also works if you put it in the ecosystem file, as the `script` entry for the app.

Tried this method and solved my problem，verry thinks,
I ran the following code
` pm2 start D:\dev\vue\myapp\node_modules\nuxt\bin\nuxt.js --name "myapp" -- run start`
It works very well！ Thanks again~

**Comment by Silventino** [comment]
The issue should be reopen as the error persists

**Comment by Naphier** [comment]
yes this is still an issue. A few messy workarounds, but this feature is worthless on windows.

**Comment by dlinning-jockey** [comment]
I'm also having this issue. 

Ecosystem.config.js file of:
```module.exports = {
	apps: [
		{
			name: "cms",
			script: "npm",
			args: "start"
		}
	]
};
```
and running `pm2 start` in the directory with that file, I get the same pm2 log of 

```0|cms      | C:\PROGRAM FILES\NODEJS\NPM.CMD:1
0|cms      | :: Created by npm, please don't edit manually.
0|cms      | ^
0|cms      | 
0|cms      | SyntaxError: Unexpected token ':'
0|cms      |     at wrapSafe (internal/modules/cjs/loader.js:1054:16)       
0|cms      |     at Module._compile (internal/modules/cjs/loader.js:1102:27)
0|cms      |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
0|cms      |     at Module.load (internal/modules/cjs/loader.js:986:32)
0|cms      |     at Function.Module._load (internal/modules/cjs/loader.js:879:14)0|cms      |     at Object.<anonymous> (C:\Users\linningd\AppData\Roaming\npm\node_modules\pm2\lib\ProcessContainerFork.js:32:23)
0|cms      |     at Module._compile (internal/modules/cjs/loader.js:1138:30)     
0|cms      |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
0|cms      |     at Module.load (internal/modules/cjs/loader.js:986:32)
0|cms      |     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
```

**Comment by SureshNegi** [comment]
SyntaxError: Unexpected token ':'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Object.<anonymous> (C:\Users\suresh-negi\AppData\Roaming\npm\node_modules\pm2\lib\ProcessContainerFork.js:32:23)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)

**Comment by dayrim** [comment]
Same issue for me.
```
0|@ftw-clo | SyntaxError: Unexpected token ':'
0|@ftw-clo |     at wrapSafe (internal/modules/cjs/loader.js:1054:16)
0|@ftw-clo |     at Module._compile (internal/modules/cjs/loader.js:1102:27)
0|@ftw-clo |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
0|@ftw-clo |     at Module.load (internal/modules/cjs/loader.js:986:32)
0|@ftw-clo |     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
0|@ftw-clo |     at Object.<anonymous> (C:\Users\msi4\AppData\Roaming\npm\node_modules\pm2\lib\ProcessContainerFork.js:32:23)
0|@ftw-clo |     at Module._compile (internal/modules/cjs/loader.js:1138:30)
0|@ftw-clo |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
0|@ftw-clo |     at Module.load (internal/modules/cjs/loader.js:986:32)
0|@ftw-clo |     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
```

**Comment by vitorbraga** [comment]
I have the same issue.
This ticket should be reopened.

**Comment by senher** [comment]
> I have the same issue.
> This ticket should be reopened.

try this : pm2 start --name 'myapp' server/index.js -i 4 -f

**Comment by Xairoo** [comment]
Still not working :/ I just created a new blank nextjs app and it's not working with pm2.

```
2|npm      | C:\PROGRAM FILES\NODEJS\NPM.CMD:1
2|npm      | :: Created by npm, please don't edit manually.
2|npm      | ^
2|npm      |
2|npm      | SyntaxError: Unexpected token ':'
2|npm      |     at wrapSafe (internal/modules/cjs/loader.js:979:16)
2|npm      |     at Module._compile (internal/modules/cjs/loader.js:1027:27)
2|npm      |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
2|npm      |     at Module.load (internal/modules/cjs/loader.js:928:32)
2|npm      |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
2|npm      |     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\pm2\lib\ProcessContainerFork.js:33:23)
2|npm      |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
2|npm      |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
2|npm      |     at Module.load (internal/modules/cjs/loader.js:928:32)
2|npm      |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)

```

**Comment by charlouze** [comment]
+1

**Comment by mspoerer** [comment]
I mean just closing an issue does not make it disappear. @Unitech Please consider to accept PR #4887 - I mean if the community tries to help, at least there should be a reaction. Thx to @myso-kr

**Comment by holtalanm** [comment]
the workarounds are pretty much all useless if trying to write an ecosystem script for multiple machines, since you probably shouldn't be hard-coding paths to installed libraries.

**Comment by Brouilles** [comment]
Same here.

**Comment by ysfaran** [comment]
In my opinion this is really essential and yet there is no update after two years..

**Comment by ysfaran** [comment]
I came up with another quite generic solution.

1. Create `pm2-npm.js` (I did similar for `yarn` and it works fine):

```js
const { execSync } = require("child_process");

// first two args can be ignored rest will be passed directly to the npm command
const [ingore, ignore2, ...args] = process.argv;

// windowsHide option will hide the cmd window
execSync(`npm ${args.join(" ")}`, { windowsHide: true, stdio: "inherit" });
```

2. Use above script to start a new process with `pm2`:

```sh
pm2 start ./pm2-npm.js --name <name> -- start
```
This would execute `npm start`.

___

Everything after `--` will directly be passed to `npm` so you can specify any script with any option:

```sh
pm2 start ./pm2-npm.js --name <name> -- run my-script --foo bar
```
Here it would execute `npm run my-script --foo bar`.

It's still sad that such a workarround is necessary an the devs don't give windows issues some love 😕

**Comment by Lzok** [comment]
@Brouilles I have this working for NextJS in my ecosystem.json file:
```json
{
  "apps" : [
     {
        "name"          : "app-nextjs",
        "script"        : "node_modules/next/dist/bin/next",
        "args"          : "start -p 3000",
        "cwd"           : "/srv/nextjsapp",
        "instances"     : 1,
        "exec_mode"     : "cluster"
     }
  ]
}
```

**Comment by lgh06** [comment]
same issue. windows 10; pm2 v5.1.2;

**Comment by dennohpeter** [comment]
> pm2 start node_modules/next/dist/bin/next -p 3001 --name "MyApp"

this worked for me thanks

**Comment by Dan86de** [comment]
Same issue for me. pm2-dev with node script giving `C:\PROGRAM FILES\NODEJS\NPM.CMD:1
Server Build-1  | :: Created by npm, please don't edit manually.`

**Comment by TokisakiYuu** [comment]
I have the same issue.

**Comment by asheroto** [comment]
> @Brouilles I have this working for NextJS in my ecosystem.json file:
> 
> ```json
> {
>   "apps" : [
>      {
>         "name"          : "app-nextjs",
>         "script"        : "node_modules/next/dist/bin/next",
>         "args"          : "start -p 3000",
>         "cwd"           : "/srv/nextjsapp",
>         "instances"     : 1,
>         "exec_mode"     : "cluster"
>      }
>   ]
> }
> ```

This works. And was able to remove instances and exec_mode too. Can name it anything then start it with `pm2 start filename.json`.

**Comment by piotr-cz** [comment]
I was assuming running pm2 on windows would work out of the box, as [readme.md](https://github.com/Unitech/pm2/blob/master/README.md) says
> Works on Linux (stable) & macOS (stable) & Windows (stable).

**Comment by piotr-cz** [comment]
Here is my take on workaround:

```js
module.exports = {
  apps : [{
    name          : "directus",
    script        : "npx",
    args          : "directus start",
    /** Force cmd interpreter on windows */
    interpreter   : process.platform === 'win32' && "C:\\Windows\\System32\\cmd.exe",
  }]
}
```

**Comment by larrykkk** [comment]
> @Brouilles I have this working for NextJS in my ecosystem.json file:
> 
> ```json
> {
>   "apps" : [
>      {
>         "name"          : "app-nextjs",
>         "script"        : "node_modules/next/dist/bin/next",
>         "args"          : "start -p 3000",
>         "cwd"           : "/srv/nextjsapp",
>         "instances"     : 1,
>         "exec_mode"     : "cluster"
>      }
>   ]
> }
> ```
**Thanks Lzok,**

In my cass (**use create-next-app and Nextjs too**),

you can use

```
pm2 start (will look for ecosystem.config.js)
```

so you can create `ecosystem.config.js` at project root and use this code to start you Nextjs App

```
module.exports = {
  apps: [
    {
      name: "your-app-name",
      script: "node_modules/next/dist/bin/next",
      args: "start"
    },
  ],
};
``` 

**remember you must have "start" script in your package.json**

**Comment by kulak91** [comment]
> 

Hero

**Comment by kushagra-aa** [comment]
This Was really helpful, Thank You, everyone!
I'm just curious,
why it is not handled by PM2,
why we gotta do such stuff, I've seen in some tutorials that it works right away

**Comment by Drift91** [comment]
As far as I can tell [this fork](https://github.com/jessety/pm2-installer) seems to work properly on Windows. Be sure to completely uninstall the original pm2 first before installing.

**Comment by Nubebuster** [comment]
Same issue. Interesting that it's not been fixed after 5 years almost

**Comment by linonetwo** [comment]
This works for `npm run start` in win11, and will prevent cmd.exe window popup:

```js
module.exports = {
  apps: [
    {
      name: 'qq-bot',
      // script: 'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
      // instances: 1,
      // exec_mode: 'cluster',
      script: 'npm',
      args: 'run start',
      cwd: 'D:/repo/qq-bot',
      interpreter: process.platform === 'win32' && 'C:\\Windows\\System32\\cmd.exe',
    },
  ],
};
```

I tried `C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js` with fork mode and it will popup cmd.exe.

I tried cluster mode, but it won't execute things in npm script, if that script point to a ps1 or bat shell file in node_modules/.bin

But with interpreter `cmd.exe` + `script: 'npm'` this works well.

**Comment by linonetwo** [comment]
No, not working, only resulted in

```
0|qq-bot   | D:\repo\qq-bot>Microsoft Windows [�汾 10.0.22621.1702]
0|qq-bot   | (c) Microsoft Corporation����������Ȩ����
```

And stop here.

**Comment by LERV1993** [comment]
My solution was to copy the node_modules folder from the path "C:\Program Files\nodejs". 

Paste it in the folder where I have project and execute the command "pm2 start "node_modules\npm\bin\npm-cli.js" --name {{PROJECT NAME}}".

This also prevented the opening of the CMD in widows 11.

I hope it helps.
Greetings.

**Comment by kc-ch** [comment]
When I deploy my. project in digital ocean, and used PM2 for live hosting, why the below error is giving


PM2        | 2023-08-02T06:46:06: PM2 log: Script /root/drukebird_frontend/browser.js had too many unstable restarts (16). Stopped. "errored"

/root/.pm2/logs/browser-out.log last 15 lines:
/root/.pm2/logs/browser-error.log last 15 lines:
0|browser  |     at Module._compile (node:internal/modules/cjs/loader:1198:14)
0|browser  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
0|browser  |     at Module.load (node:internal/modules/cjs/loader:1076:32)
0|browser  |     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
0|browser  | ReferenceError: window is not defined
0|browser  |     at Object.<anonymous> (/root/drukebird_frontend/browser.js:1:1)
0|browser  |     at Module._compile (node:internal/modules/cjs/loader:1198:14)
0|browser  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
0|browser  |     at Module.load (node:internal/modules/cjs/loader:1076:32)
0|browser  |     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
0|browser  |     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
0|browser  |     at Module._compile (node:internal/modules/cjs/loader:1198:14)
0|browser  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
0|browser  |     at Module.load (node:internal/modules/cjs/loader:1076:32)
0|browser  |     at Function.Module._load (node:internal/modules/cjs/loader:911:12) why this error is occurring when I am using pm2 to live host in digital ocean

**Comment by ljboxf** [comment]
> I came up with another quite generic solution.
> 
> 1. Create `pm2-npm.js` (I did similar for `yarn` and it works fine):
> 
> ```js
> const { execSync } = require("child_process");
> 
> // first two args can be ignored rest will be passed directly to the npm command
> const [ingore, ignore2, ...args] = process.argv;
> 
> // windowsHide option will hide the cmd window
> execSync(`npm ${args.join(" ")}`, { windowsHide: true, stdio: "inherit" });
> ```
> 
> 2. Use above script to start a new process with `pm2`:
> 
> ```shell
> pm2 start ./pm2-npm.js --name <name> -- start
> ```
> 
> This would execute `npm start`.
> 
> Everything after `--` will directly be passed to `npm` so you can specify any script with any option:
> 
> ```shell
> pm2 start ./pm2-npm.js --name <name> -- run my-script --foo bar
> ```
> 
> Here it would execute `npm run my-script --foo bar`.
> 
> It's still sad that such a workarround is necessary an the devs don't give windows issues some love 😕

Thank you so much, you are an absolute godsend!

**Comment by Zolastic** [comment]
> > I came up with another quite generic solution.
> > 
> > 1. Create `pm2-npm.js` (I did similar for `yarn` and it works fine):
> > 
> > ```js
> > const { execSync } = require("child_process");
> > 
> > // first two args can be ignored rest will be passed directly to the npm command
> > const [ingore, ignore2, ...args] = process.argv;
> > 
> > // windowsHide option will hide the cmd window
> > execSync(`npm ${args.join(" ")}`, { windowsHide: true, stdio: "inherit" });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. Use above script to start a new process with `pm2`:
> > 
> > ```shell
> > pm2 start ./pm2-npm.js --name <name> -- start
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This would execute `npm start`.
> > Everything after `--` will directly be passed to `npm` so you can specify any script with any option:
> > ```shell
> > pm2 start ./pm2-npm.js --name <name> -- run my-script --foo bar
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Here it would execute `npm run my-script --foo bar`.
> > It's still sad that such a workarround is necessary an the devs don't give windows issues some love 😕
> 
> Thank you so much, you are an absolute godsend!

Thanks for the solution. You've saved my day

**Comment by aymen157** [comment]
Issue still persists in 2026, 8 years later.
For anyone looking for a solution on win11, without having the cmd window popup; add this code to the start of your `ecosystem.config.cjs` file. it creates a script in the temp folder that we use as the script to run the app

```js const { execSync } = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');

const wrapper = path.join(os.tmpdir(), 'pm2-npm.js');
fs.writeFileSync(wrapper, `
const { execSync } = require('child_process');
const [,,  ...args] = process.argv;
execSync('npm ' + args.join(' '), { windowsHide: true, stdio: 'inherit' });
`);

// the usual module exports pm2 config
module.exports = {
    apps: [
    // vite html/ts project
    {
        name: 'web-app',
        script: wrapper, // --------> Important: use wrapper as the script
        args: 'run dev',
        cwd: 'C:/vite/web-app',
    },
]
}
```
