### ISSUE TITLE
pm2 deploy utilize 100% cpu and get crashed. #4484

### ISSUE THREAD

**Issue by bhiseweb** [Unitech/pm2#3673]
I am deploying my react app on ec2 instance using pm2. I created app using create-react-app.

whenever I run `pm2 deploy ecosystem.config.js production` sever get crashed and I received error  `fork: Cannot allocate memory`
![pm2-deploy](https://user-images.githubusercontent.com/31177960/40197575-70daca6a-5a31-11e8-8fc1-817e9566918a.png)

Then I am unable to ssh on server. also it doesn't create all required file in build folder. It shows only 3 files in build folder `favicon.ico,  favicon.png and manifest.json`

when I build in my local with production env build create properly.

Any help is appreciated thanks in advance.

**Comment by bhiseweb** [comment]
FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory
PM2        |  1: node::Abort() [PM2 v3.0.0: God Daemon (/home/deploy/.pm2)]
PM2        |  2: 0x11dd81c [PM2 v3.0.0: God Daemon (/home/deploy/.pm2)]
PM2        |  3: v8::Utils::ReportOOMFailure(char const*, bool) [PM2 v3.0.0: God Daemon (/home/deploy/.pm2)]
PM2        |  4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [PM2 v3.0.0: God Daemon (/home/deploy/.pm2)]
PM2        |  5: v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [PM2 v3.0.0: God Daemon (/home/deploy/.pm2)]
PM2        |  6: v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [PM2 v3.0.0: God Daemon (/home/deploy/.pm2)]
PM2        |  7: v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [PM2 v3.0.0: God Daemon (/home/deploy/.pm2)]
PM2        |  8: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<false>::ScanJsonString<true>() [PM2 v3.0.0: God Daemon (/home/deploy/.pm2)]
PM2        |  9: v8::internal::JsonParser<false>::ParseJsonObject() [PM2 v3.0.0: God Daemon (/home/deploy/.pm2)]
PM2        | 10: v8::internal::JsonParser<false>::ParseJsonValue() [PM2 v3.0.0: God Daemon (/home/deploy/.pm2)]
PM2        | 11: v8::internal::JsonParser<false>::ParseJsonObject() [PM2 v3.0.0: God Daemon (/home/deploy/.pm2)]
PM2        | 12: v8::internal::JsonParser<false>::ParseJsonValue() [PM2 v3.0.0: God Daemon (/home/deploy/.pm2)]
PM2        | 13: v8::internal::JsonParser<false>::ParseJsonObject() [PM2 v3.0.0: God Daemon (/home/deploy/.pm2)]
PM2        | 14: v8::internal::JsonParser<false>::ParseJsonValue() [PM2 v3.0.0: God Daemon (/home/deploy/.pm2)]
PM2        | 15: v8::internal::JsonParser<false>::ParseJson() [PM2 v3.0.0: God Daemon (/home/deploy/.pm2)]
PM2        | 16: v8::internal::Builtin_JsonParse(int, v8::internal::Object**, v8::internal::Isolate*) [PM2 v3.0.0: God Daemon (/home/deploy/.pm2)]

**Comment by khmelevskii** [comment]
+1

**Comment by thehappydinoa** [comment]
I just encountered this same error, has there been no feedback?

**Comment by ReagentX** [comment]
Randomly encountering this error as well.
