### ISSUE TITLE
Delay between 2 instances in cluster mode

### ISSUE THREAD

**Issue by wbeater** [Unitech/pm2#3678]
Hi everyone,
I have an issue as following:

## How can I make an instance delay to start x seconds after the previous instance started?
For example, I have 2 instances in cluster mode:
```
$ pm2 start myjob.js -i 2
```
Because 2 instances share the same resource (ex: An external application), 
The 1st instance will start the application
The 2nd instance need to wait 5 seconds, and check if the application already started or not,
if that application already existed, the 2nd instance connects to app, else launches a new one.
How can I do this?

Thank you.

**Comment by CurtisBelt** [comment]
Try:

`pm2 start myjob.js -i 2 --parallel=1 --wait-ready --listen-timeout 5000`

**Comment by yogithesymbian** [comment]
> e lau

not work , when i tried to `reload` its still delay and my apss just 502 bad gateway until a second the server is up again . so where is the zero delay ?
