### ISSUE TITLE
pm2 'cluster' mode fail to load package or env. variables

### ISSUE THREAD

**Issue by ericalves** [Unitech/pm2#3684]
Hi!

I have an application build with loopback (express). Its run ok with PM2 fork mode.

Now i try to enable cluster mode, but its didnt find my oracle connector. For this package works i need some enviroment variables.

Cluster mode:
![image](https://user-images.githubusercontent.com/2515487/40508731-cd8acdf4-5f6e-11e8-9503-007bc3311405.png)

![image](https://user-images.githubusercontent.com/2515487/40508858-e5116ffa-5f6e-11e8-87d9-bcd5b332c6d5.png)

fork mode:
![image](https://user-images.githubusercontent.com/2515487/40509070-5e2f7ef4-5f6f-11e8-9b06-b7bffcaa0694.png)

![image](https://user-images.githubusercontent.com/2515487/40509084-6a949cce-5f6f-11e8-817d-47509212c75c.png)

its my ecosystem.config.js file:
`module.exports = {
    apps : [{
        name        : "server_c",
        script      : "./server/server.js",
        env: {
          "NODE_ENV": "development",
          "LD_LIBRARY_PATH": "/opt/instantclient_12_1:/var/www/api/node_modules/instantclient",
          "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/ubuntu/strong-oracle.rc",
          "NLS_LANG": "PORTUGUESE_BRAZIL.AL32UTF8"
        },
        env_production : {
          "NODE_ENV": "production",
          "LD_LIBRARY_PATH": "/opt/instantclient_12_1:/var/www/api/node_modules/instantclient",
          "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/ubuntu/strong-oracle.rc",
          "NLS_LANG": "PORTUGUESE_BRAZIL.AL32UTF8"
        },
        exec_mode: "cluster",
        instances  : 2
    }]
}
`

I tried add LD_LIBRARY_PATH and PATH but doenst work.

Thanks!

**Comment by ericalves** [comment]
Up!

**Comment by fdescamps** [comment]
Hi,

Did you find a solution please ?

Thanks,

Regards,

**Comment by fdescamps** [comment]
Do you see this : https://github.com/Unitech/pm2/issues/3118

**Comment by nathanieltagg** [comment]
Bump!

This is a major issue for me. I have a very heavyweight application that has a massive LD_LIBRARY_PATH chain and other environment-variable dependencies.  I've verified that the 'env' section of the ecosystem file is honored if running in 'fork' mode, but not in 'cluster' mode..

In the meantime, I'm using cluster.js to get around the problem, but that means I don't have access to all the nice things provided by pm2 (incremental restart without downtime, reviving crashed subprocesses, etc)

Please address!

**Comment by Davetwo** [comment]
One solution in https://unix.stackexchange.com/a/548126/378457
