### ISSUE TITLE
sendSignal SIGINT is terminating the process without graceful (even with --kill-timeout 3000)

### ISSUE THREAD

**Issue by apoguy** [Unitech/pm2#3691]
## What's going wrong?
Using pm2 sendSignal SIGINT <process name> is terminating the process, without running the code in the app that listens for the SIGINT, and exiting with code 1.

## How could we reproduce this issue?
My node code for reading the SIGINT:
```
process.on("SIGINT", function () {
    //graceful shutdown
    server.end().then(() => {
        process.exit();
    }).catch((err) => {
        console.error(err);
    });

});
```
Im running pm2 like this:

> pm2 start server.js --name AppName --silent --kill-timeout 3000 --no-autorestart --disable-logs

When sending `pm2 sendSignal SIGINT AppName` the process ends with exit code 1, while if I run the app using node server.js and use CTRL+C, the app does catch the SIGINT and follows the correct behavior.

## Supporting information
```
PM2        | [2018-05-30 13:53:11] PM2 log: Starting execution sequence in -fork mode- for app name:AppName id:0
PM2        | [2018-05-30 13:53:11] PM2 log: App name:AppName id:0 online
PM2        | [2018-05-30 13:53:58] PM2 log: Stopping app:AppName id:0
PM2        | [2018-05-30 13:53:58] PM2 log: App [AppName] with id [0] and pid [15176], exited with code [1] via signal [SIGINT]
PM2        | [2018-05-30 13:53:58] PM2 log: pid=15176 msg=process killed
```

**Comment by aeisenberg** [comment]
I think we are having a similar issue. When our apps are in cluster mode, graceful shutdown seems to forcefully end a process before the kill-timeout is complete.

Have you determined the cause or found a solution here?

**Comment by aeisenberg** [comment]
Actually, on a deeper inspection. It looks like the graceful shutdown was actually working, but our log messages were not flushed to the log file before the final shutdown occurred. Once we added some code to wait for logging to be complete before shutting down everything appears to be happening normally.

It's just odd that the behavior is different in fork mode vs cluster mode.
