### ISSUE TITLE
PM2 deployment configuration - passing args with environment dependent values

### ISSUE THREAD

**Issue by proxeld** [Unitech/pm2#3702]
## What's going wrong?
I would like to pass arguments to my Node process whose values will depend on environment. I know how to pass environmental variables with dynamic values, but passing args is not clear.

## Supporting information
I tried to use environmental vars in args value but it does not seem to work:

```
apps: [
    {
      name: 'some-api',
      script: 'app.js',
      args: '--env $ENVIRONMENT',
      env: {
        COMMON_VARIABLE: true
      },
      env_dev: {
        ENVIRONMENT: 'dev'
      },
      env_dev: {
        ENVIRONMENT: 'test'
      }
    }
  ]
````

**Comment by MechanicalHuman** [comment]
Wouldnt be easier to just read `process.env.ENVIRONMENT` and use it inside of your app?

**Comment by proxeld** [comment]
Maybe, but I didn't want to modify application code. 
Anyway, I ended up parsing some arguments passed to `ecosystem.config.js` and passing them further in the configuration object.
