### ISSUE TITLE
Constantly getting permission issues with yarn

### ISSUE THREAD

**Issue by niftylettuce** [Unitech/pm2#3707]
Anytime a change is made I get a conflict on deploy (my `ecosystem.json` has a `uid` and `gid` set, and it's attempting to run `yarn` (to install deps) and then restart the threads).

```sh
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
info If you think this is a bug, please open a bug report with the information provided in "/var/www/staging/source/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error An unexpected error occurred: "EPERM: operation not permitted, chmod '/var/www/staging/source/node_modules/@ava/babel-preset-stage-4/node_modules/@babel/core/node_modules/.bin/babylon'".
```

My user `deploy` belongs to the `www-data` group.  I've tried this to no avail as well:

```sh
sudo chmod -R g+wr /var/www
sudo chown -R www-data:www-data /var/www
```

Seems that the owner of the files upon any changes getting pushed to the repo is the user `deploy` as opposed to `www-data` group.  Does pm2 not respect `gid`?  I can't find docs on this and the new docs site needs some work (e.g. algolia search doesn't even work for "group" keyword, yet the text "group" does exist in the docs).

**Comment by niftylettuce** [comment]
Related to https://github.com/yarnpkg/yarn/issues/992

**Comment by wallet77** [comment]
I close this one cause it's not related to pm2.
Feel free to reopen if necessary.
