### ISSUE TITLE
Keymetrics alerts are not working

### ISSUE THREAD

**Issue by sainaveen94** [Unitech/pm2#3709]
## What's going wrong?
All of a sudden Keymetrics Notification alerts are not working.

Is there any issue with Keymetrics?

## How could we reproduce this issue?
NA

## Supporting information
- Custom alert notifications are also not triggering.
- From past two days we are facing this issue.

**Comment by wallet77** [comment]
@sainaveen94 

Could you send pm2 and node's version ?
