### ISSUE TITLE
Proposal: switch to cli-table3

### ISSUE THREAD

**Issue by DanielRuf** [Unitech/pm2#3717]
cli-table3 is a maintained fork of cli-table2 (cli-table) and contains security fixes and improvements.

**Comment by soyuka** [comment]
Hi! Is there a bug or something else in the current implementation? We forked it ourselves and applied some needed fixes. Since then we haven't seen any issue on the subject ! 

https://github.com/keymetrics/cli-table-redemption/commits/master

**Comment by DanielRuf** [comment]
I am aware of this but it would be better to merge all changes in cli-table/cli-table3 which is fully API compatible to previous releases and forks.

**Comment by soyuka** [comment]
If it's already working why would we change ? :)
