### ISSUE TITLE
INFO logs are appended to error log file.

### ISSUE THREAD

**Issue by andreybavt** [Unitech/pm2#3729]
Hi,

I'm running a python 3.6.5 script with pm2 v.2.10.4.
In the script I have very basic logging like this:

```
import logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s %(message)s')
logging.info("test")
```
As an output I get 

> 2018-06-21 12:06:48,095 INFO test

I'd expect this line to be appended to the `*-out.log` file, but instead it appears in `*-error.log`

Can you please tell me if there's any configuration I have missed or what's the way to fix it?

Thanks

**Comment by haracejacob** [comment]
Hi, I solved this problem

Basically, python logging stream is `stderr` [see also](https://docs.python.org/3/library/logging.handlers.html#logging.StreamHandler)
>class logging.StreamHandler(stream=None)
>>Returns a new instance of the StreamHandler class. If stream is specified, the instance will use it for logging output; otherwise, `sys.stderr` will be used.

And pm2 logging `stdout` in `out_file` and `stderr` in `error_file`

So, you should split logging stream by logging level

```python
import logging

out_stream_handler = logging.StreamHandler(sys.stdout)
out_stream_handler.setLevel(logging.DEBUG)
out_stream_handler.addFilter(lambda record: record.levelno <= logging.INFO)

err_stream_handler = logging.StreamHandler(sys.stderr)
err_stream_handler.setLevel(logging.WARNING)

logging.basicConfig(
    handlers=[out_stream_handler, err_stream_handler]
)
```

without `.addFilter`, messages (higher than WARNING) will sends logging both `stdout` and `stderr`.

Best regards.
