### ISSUE TITLE
Documentation mistake (?) on Watch

### ISSUE THREAD

**Issue by ThomasDupont** [Unitech/pm2#3744]
## What's going wrong?
The command "pm2 stop --watch name_app" documented here [doc](http://pm2.keymetrics.io/docs/usage/watch-and-restart/)
thrown an error:

error: missing required argument `id|name|all|json|stdin'

## How could we reproduce this issue?
Just call the command

## Supporting information
The command "pm2 stop name_app --watch" works fine and stops watching

Version 2.9.3

**Comment by wallet77** [comment]
Hi @ThomasDupont 

Good catch.
I updated the doc. But keep it mind this site is the old documentation and it won't be updated in the future.
