### ISSUE TITLE
PM2 change detected on path, app restarting: Ignore-watch doesn't works

### ISSUE THREAD

**Issue by Raghuvar** [Unitech/pm2#3746]
@Unitech 
I am using PM2 on production for an express js web-app. There is a functionality of uploading a document inside a directory in the app. So, whenever I upload a document pm2 detect the changes and it gets restarted which leads to an error in uploading the document. I have used ignore-watch flag also and watch options too but the error is still persistent.

**Logs**

2018-06-28 05:58:34: Change detected on path uploads/<file_name>.pdf for app app - restarting
2018-06-28 05:58:34: Stopping app:app id:0
2018-06-28 05:58:35: App name:app id:0 disconnected

Please help me out!

Thanks

**Comment by comino** [comment]
Which version are you running? 

I just had the same issue with version 2.6.1. 
After upgrading to 2.10.4 the issue was solved.

**Comment by Raghuvar** [comment]
@comino I'm using v2.0.18 for PM2. Is upgrading is the only solution to go ahead with?

**Comment by vincenzo** [comment]
Man, never seen an option documented worse than `--ignore-watch` for PM2. 
I am using the latest 3.x and I can't for the life of me figure out what to pass to that option so that PM2 ignores all the AVA test files scattered across the codebase.

**Comment by joshhopkins** [comment]
I'm seeing the same thing. Have set `"watch": "false"` in `ecosystem.config`. Was fine until I started storing logs – now every time the log is updated, I'm seeing `process killed` `stopping app:...`

**Comment by damianobarbati** [comment]
Yeah --ignore-watch is buggy as hell. You have to use the pm2.config.js / ecosystem file to have it working.

**Comment by dennisideaonce** [comment]
@vincenzo You are a savior even after 3 years

**Comment by yogithesymbian** [comment]
> --ignore-watch

pm2 restart ecosystem.config.js --env production --ignore-watch

  error: option `--ignore-watch <folders|files>' argument missing
