### ISSUE TITLE
Excluding some output  logs from logs file

### ISSUE THREAD

**Issue by traBolic** [Unitech/pm2#3755]
Hi

I'm looking for a option for excluding the process.stdout.write kind of logs from **pm2 logs** command and **logs files**. App should need to log only "console.xxx" outs.

Is there any option for this?

**Comment by wallet77** [comment]
Hi @traBolic 

Unfortunately no, there isn't such command or option.
Pm2 was designed to log all output to ensure you don't miss information.

If a lot of people need this kind of option we can create a PR for this.
