### ISSUE TITLE
Integrating Keymetrics with AWS Lambdas

### ISSUE THREAD

**Issue by khaledosman** [Unitech/pm2#3758]
This is more of a question/feature request rather than a bug. 

Since PM2 requires either the CLI or the npm module to connect/start the application.. is there anyway to connect pm2 and keymetrics to a lambda considering that AWS takes care of the server/function itself without the need of manual setup? The main goal would be to use keymetrics' error and performance monitoring/alerting.

Thanks

**Comment by kernel-memory-dump** [comment]
following this +1

**Comment by alexandruluca** [comment]
Any follow up on this?
