### ISSUE TITLE
Error: bash and sh not available in $PATH

### ISSUE THREAD

**Issue by newlukai** [Unitech/pm2#3767]
## What's going wrong?
When I try to start my development environment using `pm2 start <configfile>`, pm2 exits with an error "bash and sh not available in $PATH". It's not really surprising to me since I'm working on Windows.

## How could we reproduce this issue?
Create a config file as follows:
`{
  apps: [{
    "name": "mongo",
    "script": "C:\\Program Files\MongoDB\Server\3.6\\bin\\mongod.exe",
    "args": "--dbpath C:\\some\\db\\path"
  }]
}`

and start pm2 using `pm2 start <pathToThatConfigFile>`.

## Supporting information
`pm2\lib\Common.js.verifyConf` looks for a space in the `script` property. If a space is found, it assumes that this script should be run in bash/sh.
But a space could also appear in a binary/command path, on Windows, Mac OS and Linux. Either I don't know how to properly configure pm2 to run MongoDB (or any other non-node program) or it's a bug, I guess.

```
===============================================================================
--- PM2 REPORT (Thu Jul 05 2018 09:43:37 GMT+0200 (Mitteleuropäische Sommerzeit))
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.0.0
node version         : 6.10.3
node path            : undefined
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\someUserName\AppData\Roaming\npm\node_modules\pm2\lib\Daemon.js
argv0                : node
user                 : undefined
uid                  : N/A
gid                  : N/A
uptime               : 79min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.0.0
node version         : 6.10.3
node path            : undefined
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\someUserName\AppData\Roaming\npm\node_modules\pm2\bin\pm2,report
argv0                : node
user                 : someUserName
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : win32
type                 : Windows_NT
cpus                 : Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
cpus nb              : 8
freemem              : 8209297408
totalmem             : 17054912512
home                 : C:\Users\someUserName
===============================================================================
```

**Comment by Unitech** [comment]
https://github.com/Unitech/pm2/commit/af60e99466b2dc2cec40328a4e790211159bb71c

**Comment by newlukai** [comment]
Thanks. Is working again. 👍

**Comment by KnightCoder** [comment]
I'm getting this same error when I tried to run nginx as a pm2 service. 
pm2 version: 3.0.3

This is my config file for nginx. 
```
module.exports = {
  apps : [{
    name      : 'nginx',
    script    : 'start nginx.exe',
    env: {
      NODE_ENV: 'development'
    },
    env_production : {
      NODE_ENV: 'production'
    }
  }]
};
``` 

This is the error output: 
```
pm2 start ecosystem.config.js

C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\lib\Common.js:623
        throw new Error('bash and sh not available in $PATH')
        ^

Error: bash and sh not available in $PATH
    at Object.Common.verifyConfs (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\lib\Common.js:623:15)
    at API._startJson (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\lib\API.js:882:27)
    at API.start (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\lib\API.js:324:12)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\bin\pm2:299:13
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\async\dist\async.js:3110:16
    at replenish (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\async\dist\async.js:1011:17)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\async\dist\async.js:1016:9
    at Object.eachLimit$1 (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\async\dist\async.js:3196:24)
    at Command.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\bin\pm2:298:13)
    at Command.listener (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\commander\index.js:315:8)

```

**Comment by Sodj** [comment]
I still have this error when running `pm2 start "npm start"` in my react project
I have pm2 v3.1.2

**Comment by snsarma** [comment]
Hi IS there a fix for this , I have been encountering the same error for the past couple of days when I do a pm2 start ecosystem.config.js

pm2 start ecosystem.config.js
C:\Users\SSarma\AppData\Roaming\npm\node_modules\pm2\lib\Common.js:669
        throw new Error('bash and sh not available in $PATH')
        ^

Error: bash and sh not available in $PATH
    at Object.Common.verifyConfs (C:\Users\SSarma\AppData\Roaming\npm\node_modules\pm2\lib\Common.js:669:15)
    at API._startJson (C:\Users\SSarma\AppData\Roaming\npm\node_modules\pm2\lib\API.js:926:27)
    at API.start (C:\Users\SSarma\AppData\Roaming\npm\node_modules\pm2\lib\API.js:334:12)
    at C:\Users\SSarma\AppData\Roaming\npm\node_modules\pm2\bin\pm2:291:13
    at C:\Users\SSarma\AppData\Roaming\npm\node_modules\pm2\node_modules\async\internal\withoutIndex.js:9:16
    at replenish (C:\Users\SSarma\AppData\Roaming\npm\node_modules\pm2\node_modules\async\internal\eachOfLimit.js:66:17)    at C:\Users\SSarma\AppData\Roaming\npm\node_modules\pm2\node_modules\async\internal\eachOfLimit.js:71:9
    at eachLimit (C:\Users\SSarma\AppData\Roaming\npm\node_modules\pm2\node_modules\async\forEachLimit.js:43:36)
    at Command.<anonymous> (C:\Users\SSarma\AppData\Roaming\npm\node_modules\pm2\bin\pm2:290:7)
    at Command.listener (C:\Users\SSarma\AppData\Roaming\npm\node_modules\pm2\node_modules\commander\index.js:315:8)

**Comment by fmalk** [comment]
This error appeared to me as well.
As indicated by @newlukai :

> pm2\lib\Common.js.verifyConf looks for a space in the script property. If a space is found, it assumes that this script should be run in bash/sh.

In Windows, avoid using spaces in the `script` parameter of pm2.config.js. If you have and index.js as starting point, you can just use `"script": "./folder"` and pm2 will run it.

**Comment by snsarma** [comment]
@fmalk Thanks for the inputs , I am able to start pm2 via ecosystem.config.js , I had one more question , Following is the content of my ecosystem.config.js file, I need to get the values stored in env and env_production in a variable in my component so that based on that I can hit the appropriate API.
Could you please suggest how I can retrieve the values stored in NODE_ENV of env and env_production.
This is the final blocker in our deployment as we have had to manually change them during the deployment.

module.exports = {
  apps : [{
    name: 'API',
    script: './build/server.js',

    // Options reference: https://pm2.io/doc/en/runtime/reference/ecosystem-file/
    args: 'one two',
    instances: 1,
    autorestart: true,
    watch: false,
    max_memory_restart: '1G',
    env: {
      NODE_ENV: 'development'
    },
    env_production: {
      NODE_ENV: 'production'
    }
  }],

  deploy : {
    production : {
      user : 'node',
      host : '212.83.163.1',
      ref  : 'origin/master',
      repo : 'git@github.com:repo.git',
      path : '/var/www/production',
      'post-deploy' : 'npm install && pm2 reload ecosystem.config.js --env production'
    }
  }
};

**Comment by fmalk** [comment]
@snsarma not really an expert but isn't what you're trying to do achieavable by running

`pm2 start <config> --env production`

**Comment by snsarma** [comment]
@fmalk  Thanks for the response , when I run the above , I am not able to view my app in the browser and the environment variable isn't retrieved either.The pm2 gets started but the app is not up in my browser , I just need to figure a way to differentiate between development and production environment. Based on that the appropriate API is hit. Any inputs are welcome.
