### ISSUE TITLE
BUG:why i use pm2 to deploy but address ip was wrong

### ISSUE THREAD

**Issue by 171563857** [Unitech/pm2#3773]
it's my pm2.json

{
        "apps": [{
                "name": "skill-box.0",
                "max_memory_restart": "1024M",
                "log_date_format": "YYYY-MM-DD HH:mm:ss SSS",
                "script": "/home/skill-box/bundle/main.js",
                "out_file": "/home/skill-box/logs/app.log",
                "error_file": "/home/skill-box/logs/err.log",
                "port": "8083",
                "env": {
                        "MONGO_URL": "mongodb://localhost:27017/meteor",
                        "MONGO_OPLOG_URL": "mongodb://localhost:27017/local",
                        "ROOT_URL": "https://120.76.136.x",
                        "DDP_DEFAULT_CONNECTION_URL": "https://120.76.136.x:8083",
                        "PORT": "8083"
                }
        }]
}

my address ip is '120.76.136.x'
but site url was wrong
![image](https://user-images.githubusercontent.com/22027896/42406189-1db1973a-81d5-11e8-8bc7-c83845d0e6ab.png)

i vim pm2.json again and remove all and meteor build again
but still mistake

**Comment by wallet77** [comment]
Hi @171563857 

I'm not sure it's related to pm2.
The output doesn't look like a pm2 output.

Could you run `pm2 report` ?
