### ISSUE TITLE
The charset of pm2 monitoring is not correct

### ISSUE THREAD

**Issue by FabienZa** [Unitech/pm2#3774]
I don't find how modify the charset used by pm2 when I use the commande `pm2 monit`.

The letters "à" or "é" are replaced by "?" in the board "Global logs".

But if I try to access directly to the log of the container with : `docker logs -f nodejs`, the letters are shown correctly.

With `pm2 monit`  :

    lq Process list qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqklq Global Logs qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqk
    x[ 0] node-js_server     Mem:  36 MB    CPU:  0  xx node-js_server > Client num?ro : 1                       x
    x                                                xx node-js_server > Client num?ro : 2                       x
    x                                                xx node-js_server > Client num?ro : 3                       x
    x                                                xx                                                          x
    mqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqjmqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqj

And with `docker logs` :  

    0|node-js_ | Client numéro : 1 
    0|node-js_ | Client numéro : 2 
    0|node-js_ | Client numéro : 3

Thanks for your help !

**Comment by wallet77** [comment]
Hi @FabienZa 

It seems to work here.

![screenshot from 2018-07-09 11-34-48](https://user-images.githubusercontent.com/5022887/42443041-ae258428-836c-11e8-8f7a-8f7c8250c2fc.png)

Maybe it depends of platform.
pm2 : 3.0.0
Node : 8.4.0 (also tested on 10.3.0)
Ubuntu : 18.04

**Comment by FabienZa** [comment]
Hi @wallet77 

Thanks for your answer, I run it inside a container, the platform inside the container is :  
pm2 : 2.10.4
Node : 8.11.3
Linux version 3.10.0-693.5.2.el7.x86_64 (Red Hat 4.8.5-16)

So, yes, if it's work for you, probably the problem is because of the environment of my container is not correctly configure for UTF8.
