### ISSUE TITLE
When all process are deleted and run pm2 update, old processes get restored

### ISSUE THREAD

**Issue by Unitech** [Unitech/pm2#3776]
https://github.com/Unitech/pm2/blob/29cccd9437e75e36f56d1afb0de3d73a5d033d21/lib/API/Startup.js#L407

**Comment by wallet77** [comment]
It's because they were stored in dump file. And after dump file refactoring we don't allow to save an empty file.

If you want to save an empty process list you have to use special command : 
`pm2 cleardump`

**Comment by Unitech** [comment]
Thanks, this should be documented here: https://pm2.io/doc/en/runtime/guide/startup-hook/

**Comment by wallet77** [comment]
Oups ... yes we forget this feature in documentation.
I will add it.

**Comment by wallet77** [comment]
Done : https://github.com/keymetrics/doc-pm2/pull/239
