### ISSUE TITLE
3.0.0 update downgrades back to previous version after restarting machine

### ISSUE THREAD

**Issue by Kovaelin** [Unitech/pm2#3778]
## What's going wrong?
PM2 3.0.0 update does not remain after reboot.

## How could we reproduce this issue?
Restart VPS.

**Comment by wallet77** [comment]
Hi @Kovaelin 

PM2 doesn't have a "revert" like feature.
I don't think it's related to pm2 itself.

**Comment by Unitech** [comment]
After upgrading run:

```
$ pm2 unstartup
$ pm2 startup
```

It will update init script to boot the right pm2 on server reboot

**Comment by Kovaelin** [comment]
Thank you.
