### ISSUE TITLE
Keymetrics website showing "Versioning module and post-deployment reports not activated (no .git found in the project)"

### ISSUE THREAD

**Issue by Kovaelin** [Unitech/pm2#3781]
## What's going wrong?
I'm getting an error message on the Keymetrics website, even though git is functioning properly.

>Versioning module and post-deployment reports not activated (no .git found in the project)

## Supporting information
https://github.com/keymetrics/keymetrics-support/issues/200

Is there something I can do to verify/ensure that Keymetrics is looking in the right place for .git?

**Comment by Unitech** [comment]
these are pm2 plus questions, you should better ask your question here: http://keymetrics.zendesk.com

Anyway, can you do a `ls` in the folder where you have started your node.js app?
