### ISSUE TITLE
pm2 trigger command hangs

### ISSUE THREAD

**Issue by pankleks** [Unitech/pm2#3786]
I sending custom command to pm2 process with `pm2 trigger myapp test`

After issuing command pm2 answers:

```
[myapp:4]="my answer"
1 processes have received command test
```

Then it hangs.

This does not happen everytime, in most cases it works - but I can't find any pattern.

System: Ubuntu 16.04, 18.04
PM2: 2.6, 3.0.0

In my app I respond according to doc:

```ts
        Pmx.action("test", (reply) => {
            reply(`my answer`);
        });
```

**Comment by Unitech** [comment]
Are you using https://www.npmjs.com/package/pmx or https://www.npmjs.com/package/@pm2/io?
Which pmx version?

Thanks

**Comment by pankleks** [comment]
Thanks for reply. I'm using Pmx

**Comment by pankleks** [comment]
Not sure how to check pmx version, I'm adding package `pm2` in version 2.10.4

**Comment by Unitech** [comment]
action.js: 

```
var pmx = require('pmx')

pmx.action("test", (reply) => {
  reply(`my answer`);
});
```

```
$ pm2 start action.js 
$ pm2 trigger action test
c1 processes have received command test
[action:0]="my answer"
```

PMX version 1.6.7, PM2 3.0

I did the command 20 times it worked every time.

How did you started your application?

**Comment by pankleks** [comment]
it's installed as pm2 module with `pm2 install my-app`

**Comment by wallet77** [comment]
It seems we have this behavior if the called action doesn't exist.
I will try to fix it.

Anyway if the command hangs so your action is not detected and probably not correctly initialized.
