### ISSUE TITLE
invalid ps -o flag used in PM2 3.0.0 when starting

### ISSUE THREAD

**Issue by mikebohlen** [Unitech/pm2#3791]
Mike Bohlen                                        Jul 11, 06:48 PDT            [2018-07-11T14:32:48.736Z] PM2 log: =============================================================================== [2018-07-11T14:32:48.810Z] PM2 log: Starting execution sequence in -cluster mode- for app name:Wo1 id:0 [2018-07-11T14:32:49.441Z] PM2 log: App name:Wo1 id:0 online      [2018-07-11T14:32:49.446Z] PM2 error: (node:7587) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exit[2018-07-11T14:32:49.508Z] PM2 error: Error caught while calling pidusage  [2018-07-11T14:32:49.512Z] PM2 error: Error: ps: 0509-048 Flag -o was used with invalid list. Usage: ps [-AMNZaedfklm] [-n namelist] [-F Format] [-o specifier[=header],...]    [-p proclist][-G\|-g grouplist] [-t termlist] [-U\|-u userlist] [-c classlist] [ -T pid] [ -L pidlist ]   [-@ [wparname] ]   Usage: ps [aceglnsuvwxX] [t tty] [processnumber]    [2018-07-11T14:32:49.514Z] PM2 log: =============================================================================== [2018-07-11T14:32:49.514Z] PM2 log: --- PM2 global error caught --------------------------------------------------- [2018-07-11T14:32:49.514Z] PM2 log: --- PM2 global error caught --------------------------------------------------- [2018-07-11T14:32:49.514Z] PM2 log: Time                 : Wed Jul 11 2018 14:32:49 GMT+0100 (CST) [2018-07-11T14:32:49.514Z] PM2 error: Cannot read property '7588' of undefined [2018-07-11T14:32:49.515Z] PM2 error: TypeError: Cannot read property '7588' of undefined     at /QOpenSys/pkgs/lib/nodejs8/lib/node_modules/pm2/lib/God/ActionMethods.js:79:30 |   | Mike Bohlen                                        Jul 11, 06:48 PDT            [2018-07-11T14:32:48.736Z] PM2 log: =============================================================================== [2018-07-11T14:32:48.810Z] PM2 log: Starting execution sequence in -cluster mode- for app name:Wo1 id:0 [2018-07-11T14:32:49.441Z] PM2 log: App name:Wo1 id:0 online      [2018-07-11T14:32:49.446Z] PM2 error: (node:7587) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exit[2018-07-11T14:32:49.508Z] PM2 error: Error caught while calling pidusage  [2018-07-11T14:32:49.512Z] PM2 error: Error: ps: 0509-048 Flag -o was used with invalid list. Usage: ps [-AMNZaedfklm] [-n namelist] [-F Format] [-o specifier[=header],...]    [-p proclist][-G\|-g grouplist] [-t termlist] [-U\|-u userlist] [-c classlist] [ -T pid] [ -L pidlist ]   [-@ [wparname] ]   Usage: ps [aceglnsuvwxX] [t tty] [processnumber]    [2018-07-11T14:32:49.514Z] PM2 log: =============================================================================== [2018-07-11T14:32:49.514Z] PM2 log: --- PM2 global error caught --------------------------------------------------- [2018-07-11T14:32:49.514Z] PM2 log: --- PM2 global error caught --------------------------------------------------- [2018-07-11T14:32:49.514Z] PM2 log: Time                 : Wed Jul 11 2018 14:32:49 GMT+0100 (CST) [2018-07-11T14:32:49.514Z] PM2 error: Cannot read property '7588' of undefined [2018-07-11T14:32:49.515Z] PM2 error: TypeError: Cannot read property '7588' of undefined     at /QOpenSys/pkgs/lib/nodejs8/lib/node_modules/pm2/lib/God/ActionMethods.js:79:30
-- | -- | --
  | Mike Bohlen                                        Jul 11, 06:48 PDT            [2018-07-11T14:32:48.736Z] PM2 log: =============================================================================== [2018-07-11T14:32:48.810Z] PM2 log: Starting execution sequence in -cluster mode- for app name:Wo1 id:0 [2018-07-11T14:32:49.441Z] PM2 log: App name:Wo1 id:0 online      [2018-07-11T14:32:49.446Z] PM2 error: (node:7587) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exit[2018-07-11T14:32:49.508Z] PM2 error: Error caught while calling pidusage  [2018-07-11T14:32:49.512Z] PM2 error: Error: ps: 0509-048 Flag -o was used with invalid list. Usage: ps [-AMNZaedfklm] [-n namelist] [-F Format] [-o specifier[=header],...]    [-p proclist][-G\|-g grouplist] [-t termlist] [-U\|-u userlist] [-c classlist] [ -T pid] [ -L pidlist ]   [-@ [wparname] ]   Usage: ps [aceglnsuvwxX] [t tty] [processnumber]    [2018-07-11T14:32:49.514Z] PM2 log: =============================================================================== [2018-07-11T14:32:49.514Z] PM2 log: --- PM2 global error caught --------------------------------------------------- [2018-07-11T14:32:49.514Z] PM2 log: --- PM2 global error caught --------------------------------------------------- [2018-07-11T14:32:49.514Z] PM2 log: Time                 : Wed Jul 11 2018 14:32:49 GMT+0100 (CST) [2018-07-11T14:32:49.514Z] PM2 error: Cannot read property '7588' of undefined [2018-07-11T14:32:49.515Z] PM2 error: TypeError: Cannot read property '7588' of undefined     at /QOpenSys/pkgs/lib/nodejs8/lib/node_modules/pm2/lib/God/ActionMethods.js:79:30

## Supporting information

```
$ pm2 report
```

**Comment by wallet77** [comment]
Which pm2 command are you using ?
We need more details to reproduce !

**Comment by mikebohlen** [comment]
pm2 start  some.js -i 1 --name somename --log /some.log

System  is IBM ppc64 AIX  shell is korn
 
from cli 

Mike Bohlen
MidRange Systems Administrator
Information Technology Department

Duncan Aviation, INC.
Lincoln Municipal Airport
Lincoln NE 68524
Ph:     402.479.1566
Cell:   402.499.3916
E-Mail: Mike.Bohlen@DuncanAviation.com

**Comment by mikebohlen** [comment]
works fine with Ver. 2.10.4 issue showed up in 3.0.0

Mike Bohlen
MidRange Systems Administrator
Information Technology Department

Duncan Aviation, INC.
Lincoln Municipal Airport
Lincoln NE 68524
Ph:     402.479.1566
Cell:   402.499.3916
E-Mail: Mike.Bohlen@DuncanAviation.com

**Comment by Unitech** [comment]
@soyuka

**Comment by Unitech** [comment]
@mikebohlen we don't have an AIX machine, could you post the result of the command:

`ps --help simple`
`ps --help output`
`ps --help list`

Thanks

**Comment by mikebohlen** [comment]
Usage: ps [-AMNZaedfklm] [-n namelist] [-F Format] [-o 
specifier[=header],...] 
                [-p proclist][-G|-g grouplist] [-t termlist] [-U|-u 
userlist] [-c classlist] [ -T pid] [ -L pidlist ] 
                [-@ [wparname] ]   
Usage: ps [aceglnsuvwxX] [t tty] [processnumber]   

Mike Bohlen
MidRange Systems Administrator
Information Technology Department

Duncan Aviation, INC.
Lincoln Municipal Airport
Lincoln NE 68524
Ph:     402.479.1566
Cell:   402.499.3916
E-Mail: Mike.Bohlen@DuncanAviation.com

**Comment by soyuka** [comment]
fixed in https://github.com/soyuka/pidusage/commit/7d55518b7d5d5aae964e64ddd7b13ecec75463a1
