### ISSUE TITLE
--update-env behaviour is not intuitive

### ISSUE THREAD

**Issue by awilkins** [Unitech/pm2#3796]
After a lot of frustration and experimentation, I have pinned down the quirks of `--update-env` that have been bugging me. These things are not clear from reading the documentation, but I also think it breaks the principle of least surprise and behaves counter to common sense.

`pm2.json`
```json
{
  "apps" : [{
    "name"             : "pm2-test",
    "script"           : "index.js",
    "env": {
      "NODE_ENV": "default",
      "VERB": "eats",
      "NOUN": "apples"
    },
    "env_production": {
      "NODE_ENV": "production",
      "VERB": "hates"
    },
    "env_development": {
      "NODE_ENV": "development",
      "SESSION_STORAGE": "memory"
    }
  }]
}
```

`index.js` is a small node server that serves

```javascript
`Dave ${process.env.VERB} ${process.env.NOUN}!\n`
```

## `--update-env` does not implicitly use the environment you started the app with

```
pm2 start pm2.json --env production
curl http://localhost:3000
> Dave hates apples!
```

Here we got env variables from both the default and environment section.

```
# Change default NOUN to "anchovies"
pm2 restart pm2.json
curl http://localhost:3000
> Dave hates apples!  # as expected
pm2 restart pm2.json --update-env
> Date eats anchovies! 
```

I would expect `Dave hates anchovies!` here and I think many people would. 

I expected this to update the environment I started the app with, not to splat it with the default environment. Neither `restart` or `reload` mention the `--update-env` option in their cli `--help`. The documentation mentions this option but not how it interacts with additional environments.

```
# Remove NOUN from the file completely
pm2 restart pm2.json --update-env
> Date eats anchovies!
```

This too is a concern. Now my running app has an environment that can't be reproduced by copying the ecosystem file elsewhere. If I removed a variable like e.g. `DEBUG` from the file, debugging will still continue in my running application. This is not the only ticket to mention this issue, but it bears repeating.

**Comment by Unitech** [comment]
I agree with you. 
I think we are going to inverse behavior. Update env by default, and if you want to keep the environment I will create a --keep-env

**Comment by Unitech** [comment]
So how could get back to the default env if the `--env` is memorized

**Comment by awilkins** [comment]
Good question.

I'm also not sure about inverting the behaviour in your highly used app ... while I feel the documentation both in the CLI and web could use some work, a change like that will no doubt surprise people who have learned these things the hard way.

Or maybe you mean this `--keep-env` flag preserves the previous `--env` parameter, rather than preserving the whole environment?

**Comment by Unitech** [comment]
Feel free to edit the PR if you want to make a suggestion
