### ISSUE TITLE
pm2 start graphql playground

### ISSUE THREAD

**Issue by timot7782** [Unitech/pm2#3798]
## What's going wrong?
- I m trying to deploy a graphql playground.
## How could we reproduce this issue?
- pm2 start graphql playground
## Supporting information
- [PM2] Starting /home/ec2-user/.nvm/versions/node/v8.11.2/bin/graphql in fork_mod                           e (1 instance)
[PM2] Done.
[PM2][ERROR] script not found : /home/ec2-user/hex_pos/playground
script not found : /home/ec2-user/hex_pos/playground

```
$ pm2 report
```
===============================================================================
--- PM2 REPORT (Fri Jul 13 2018 14:40:18 GMT+0000 (UTC)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.0.0
node version         : 8.11.2
node path            : /home/ec2-user/.nvm/versions/node/v8.11.2/bin/pm2
argv                 : /home/ec2-user/.nvm/versions/node/v8.11.2/bin/node,/home/ec2-user/.nvm/versions/node/v8.11.2/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : ec2-user
uid                  : 1000
gid                  : 1000
uptime               : 8min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.0.0
node version         : 8.11.2
node path            : /home/ec2-user/.nvm/versions/node/v8.11.2/bin/pm2
argv                 : /home/ec2-user/.nvm/versions/node/v8.11.2/bin/node,/home/ec2-user/.nvm/versions/node/v8.11.2/bin/pm2,report
argv0                : node
user                 : ec2-user
uid                  : 1000
gid                  : 1000
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
cpus nb              : 1
freemem              : 183398400
totalmem             : 1035329536
home                 : /home/ec2-user
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────┬───────────┬──────────┬──────────┐
│ App name │ id │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem       │ user     │ watching │
├──────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼──────────┼──────────┤
│ index    │ 0  │ fork │ 16185 │ online │ 0       │ 8m     │ 0%  │ 60.5 MB   │ ec2-user │ disabled │
└──────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────┴───────────┴──────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌──────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────┬───────────┬──────────┬──────────┐
│ App name │ id │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem       │ user     │ watching │
├──────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼──────────┼──────────┤
│ index    │ 0  │ fork │ 16185 │ online │ 0       │ 8m     │ 0%  │ 60.5 MB   │ ec2-user │ disabled │
└──────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────┴───────────┴──────────┴──────────┘

**Comment by wallet77** [comment]
Hi @timot7782 

It seems your start command is wrong.
I don't know what grapgql playground is but you can't have a space into start command.

**Comment by timot7782** [comment]
it is a playground environment for GraphQL
