### ISSUE TITLE
async.js  if (fn === null) throw new Error("Callback was already called.");

### ISSUE THREAD

**Issue by lizhu16** [Unitech/pm2#3804]
![image](https://user-images.githubusercontent.com/26211118/42806440-09a43874-89e1-11e8-906e-96c02573de86.png)
![image](https://user-images.githubusercontent.com/26211118/42806518-3b3a4e0a-89e1-11e8-87ae-599e5480ad39.png)

**Comment by Unitech** [comment]
Can you show us your ecosystem.conf.js

**Comment by lizhu16** [comment]
apps : [

    // First application
    {
      name      : 'loan',
      script    : './node_modules/nuxt/bin/nuxt',
      args: 'start -p 3003 -H 0.0.0.0',
      env: {
        COMMON_VARIABLE: 'true'
      },
      env_production : {
        NODE_ENV: 'production'
      }
    },
  ],

  /**
   * Deployment section
   * http://pm2.keymetrics.io/docs/usage/deployment/
   */
  deploy : {
    production : {
      user : 'www',
      host: ['39.107.74.227'],
      ref  : 'origin/master',
      repo : '......',
      path: '/data/wwwroot/loan.jiajiabank.com',
      'post-deploy': 'cnpm install && pm2 reload ecosystem.config.js --env production'
    },
    dev : {
      user : 'node',
      host : '......',
      ref  : 'origin/master',
      repo : 'git@github.com:repo.git',
      path : '/var/www/development',
      'post-deploy' : 'npm install && pm2 reload ecosystem.config.js --env dev',
      env  : {
        NODE_ENV: 'dev'
      }
    }
  }

**Comment by Unitech** [comment]
fixed with pm2-deploy@0.3.10 (just re run `npm install pm2 -g && pm2 update`)
