### ISSUE TITLE
pm2 cannot found module pm2/io

### ISSUE THREAD

**Issue by nguyenphuocnhatthanh** [Unitech/pm2#3805]
## What's going wrong?
i run pm2 start server.js with root user , but i give throw err

Error: Cannot find module '@pm2/io'
0|server   |     at Function.Module._resolveFilename (module.js:485:15)
0|server   |     at Function.Module._load (module.js:437:25)
0|server   |     at Module.require (module.js:513:17)
0|server   |     at require (internal/module.js:11:18)
0|server   |     at Object.injectModules (/usr/local/lib/node_modules/pm2/lib/ProcessUtils.js:6:19)

I run by npm version 5.0.3
node version 8.1.1
pm2 version 3.0.0

Pls help me

**Comment by wallet77** [comment]
Hi @nguyenphuocnhatthanh 

Is the module downloaded ? Could you check in node_modules repository, under @pm2/ ?

**Comment by nguyenphuocnhatthanh** [comment]
Hi @wallet77 
I found pm2/package.json and see
dependencies": {
    "@pm2/agent": "^0.5.4",
    "@pm2/io": "^2.0.2",
...
}
but i dont see io folder in node_modules... It's reason ?

**Comment by wallet77** [comment]
It's probably because npm failed to download it when you install pm2 v3.0.0.
You should reinstall pm2 I guess.

**Comment by nguyenphuocnhatthanh** [comment]
i tried reinstall pm2 but not work :(

**Comment by Unitech** [comment]
Can you show us the installation logs

**Comment by nguyenphuocnhatthanh** [comment]
I work fine when down version 3.0.0 -> 2.0.1
I dont know reason
@Unitech

**Comment by Unitech** [comment]
Run `npm cache clean --force` and run again `npm install pm2 -g`

I did an install of pm2 on centos machine it was a success:

```
[root@scw-79a6a0 ~]# npm install pm2 -g
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
/root/.nvm/versions/node/v10.7.0/bin/pm2 -> /root/.nvm/versions/node/v10.7.0/lib/node_modules/pm2/bin/pm2
/root/.nvm/versions/node/v10.7.0/bin/pm2-dev -> /root/.nvm/versions/node/v10.7.0/lib/node_modules/pm2/bin/pm2-dev
/root/.nvm/versions/node/v10.7.0/bin/pm2-runtime -> /root/.nvm/versions/node/v10.7.0/lib/node_modules/pm2/bin/pm2-runtime
/root/.nvm/versions/node/v10.7.0/bin/pm2-docker -> /root/.nvm/versions/node/v10.7.0/lib/node_modules/pm2/bin/pm2-docker
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/pm2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ pm2@3.0.0
```

**Comment by GIScyw** [comment]
can you have solved the problem? i meet the same problem now.

**Comment by SpeedyCraftah** [comment]
4 months later ~~ not a soul to be heard

**Comment by Askadias** [comment]
Unable to install pm2:
$ yarn global add pm2
yarn global v1.15.2
[1/4] 🔍  Resolving packages...
error Couldn't find package "@pm2/io@^4.1.2" required by "pm2" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
Please address ASAP.

**Comment by nguyenphuocnhatthanh** [comment]
Issue that have permission of user system... I run pm2 start without root and it's work :D

**Comment by djfm** [comment]
I have the same issue, the `node_modules/@pm2/io` folder doesn't have a `build` folder in it.
I'm using pm2 v5.3.0, installed with `yarn`.
Any ideas?
