### ISSUE TITLE
PM2 in AWS Linux

### ISSUE THREAD

**Issue by SubodhTengse** [Unitech/pm2#3808]
Hi All,
In our organization we couple of AWS Linux EC2 instances , and I am in stage where need to put access control and I have accomplished this with password based authentication , now different users logs with there user name and password , I am undergoing an issue with commands related to PM2 and NVM . As PM2 and NVM were installed with default ec2-user , when a new user logs in and wants to run any of these commands he gets prompt command not found . I tried multiple things but not able to find any fix for this . Any suggestion or work around to fix this will help us a lot .

**Comment by Unitech** [comment]
Do these other user can still access to the node CLI?

**Comment by SubodhTengse** [comment]
No the users are not using CLI .

**Comment by SubodhTengse** [comment]
Attaching  Sc
![image](https://user-images.githubusercontent.com/41463163/43058018-f58ed2dc-8e62-11e8-9276-f55c4c46222f.png)
reenshot for reference

**Comment by Unitech** [comment]
how did you installed node.js? nvm?

In production I would recommend installing node.js like that:

```
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by SubodhTengse** [comment]
Hi we have installed  node js with Yum Install command.
