### ISSUE TITLE
PM2 v3.0.0 does not forward the `"node_args": [...]` arguments to the destination executable

### ISSUE THREAD

**Issue by rom-melnyk** [Unitech/pm2#3810]
## What's going wrong?
PM2 v3.0.0 does not forward the `"node_args": [...]` arguments of the ecosystem file to the destination executable. v2 works as expected.  
Might be related to #3257.

```
$ cat pm2-config.json
{
  "apps": [{
    "name": "http",
    "script": "server/server.js",
    "watch": ["server"],
    "node_args": ["--inspect"]
  }]
}

$ pm2 start pm2-config.json
## all good; process started;
## pm2 monit shows "Interpreter args      --inspect"

$ ps -FA | grep 'node.*\/server\.js'
... node path/to/server/server.js
## no "--inspect" argument forwarded
```
chrome://inspect shows the target `node_modules/pm2/lib/ProcessContainerFork.js` which is not expected. With v2 the target was my `server/server.js` which I was able to debug.

Running the child process in _cluster mode_ does not help.

## Possible reason
Looks like the "--inspect" argument is applied _towards the container_ bun not forwarder _into the container._

## How could we reproduce this issue?
1. PM2 version 3.0.0.
1. Create ecosystem file for NodeJS process with `"node_args": ["--inspect"]`.
1. Run it.

### Expected result
Destination (child) process is run as `node --inspect filename`.

**Comment by Unitech** [comment]
Just tested it, ok the main script is not server.js but it's still the same you can set a breakpoint in your script and it will work

**Comment by rom-melnyk** [comment]
@Unitech, thank you for the answer.
So with the setup like I provided you were able to set/handle breakpoints and you chrome://inspect showed the actual file (not `node_modules/pm2/lib/ProcessContainerFork.js`) as the target, right?

**Comment by wallet77** [comment]
Hi @rom-melnyk ,

Yes the target file should be ProcessContainerFork.js because it's the entrypoint when you use fork mode.
But I confirmed that node-args are correctly send to child process.
