### ISSUE TITLE
Fresh Fedora 28 install has issues with non-root starup

### ISSUE THREAD

**Issue by xanthoes** [Unitech/pm2#3813]
New to node I've searched but haven't found anything like this in your issue log. 
Wanted to setup pm2 on a fresh install of Fedora 28 server, Node v8.11.3, pm2 v3.0.0. 

After running (as root) 'pm2 startup systemd -u *username* --hp /home/*username*'

When I reboot, and run: 'systemctl status pm2-*username*.service' 
It returns this error message: pm2-*username*.service: Can't convert PID files /home/*username*/.pm2/pm2.pid O_PATH file descriptor to proper file descriptor: Permission denied

My pm2 report:
[pm2-report.txt](https://github.com/Unitech/pm2/files/2215767/pm2-report.txt)

Anything else?

**Comment by xanthoes** [comment]
**Update**
I just noticed that my app is available on 127.0.0.1:1337 ONLY. I cannot use localhost, or the systems IP address to access my app.

**Comment by xanthoes** [comment]
**UPDATE**
So I've added a rule in the firewall (new to Fedora as well... normally have ubuntu. Had to figure that out). Now I have access to my app. HOWEVER, the systemctl still says "Active: failed" and:

Jul 21 03:22:17 home._hostname_.net systemd[1]: pm2-_username_.service: Can't convert PID files /home/_username_/.pm2/pm2.pid O_PATH file descriptor to proper >
Jul 21 03:22:17 home._hostname_.net systemd[1]: pm2-_username_.service: Can't convert PID files /home/_username_/.pm2/pm2.pid O_PATH file descriptor to proper >
Jul 21 03:23:46 home._hostname_.net systemd[1]: pm2-_username_.service: Start operation timed out. Terminating.
Jul 21 03:23:46 home._hostname_.net systemd[1]: pm2-_username_.service: Failed with result 'timeout'.
Jul 21 03:23:46 home._hostname_.net systemd[1]: Failed to start PM2 process manager.

**Comment by Unitech** [comment]
This is not advised to run yourself the pm2 startup command. Instead login with your user, then run `pm2 startup`, it will display a command to copy/paste in your terminal.

To remove the startup file: `pm2 unstartup` then re run `pm2 startup`
