### ISSUE TITLE
load-balance doesn't work in Windows 

### ISSUE THREAD

**Issue by zhuernm** [Unitech/pm2#3815]
## What's going wrong?
pm2 started two processes on tow CPU cores, but only use one core to calculate ( to response request).

## How could we reproduce this issue?
Windows server 2016

## Supporting information

--- PM2 REPORT (Mon Jul 23 2018 14:56:49 GMT+0800 (中国标准时间)) -------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.0.0
node version         : 7.9.0
node path            : undefined
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\lib\Daemon.js
argv0                : node
user                 : undefined
uid                  : N/A
gid                  : N/A
uptime               : 23min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.0.0
node version         : 7.9.0
node path            : undefined
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\bin\pm2,report
argv0                : node
user                 : Administrator
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : win32
type                 : Windows_NT
cpus                 : Intel(R) Xeon(R) Gold 6149 CPU @ 3.10GHz
cpus nb              : 2
freemem              : 597823488
totalmem             : 4294430720
home                 : C:\Users\Administrator
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬─────────┬──────┬────────┬─────────┬────────┬─────── ┬────────────┬───────────────┬──────────┐
│ App name │ id │ mode    │ pid  │ status │ restart │ uptime │ cpu   │ mem        │ user          │ watching │
├──────────┼────┼─────────┼──────┼────────┼─────────┼────────┼─────── ┼────────────┼───────────────┼──────────┤
│ app      │ 0  │ cluster │ 4376 │ online │ 0       │ 24m    │ 0%    │ 41.0 MB    │ Administrator │ disabled │
│ app      │ 1  │ cluster │ 1912 │ online │ 0       │ 23m    │ 11.9% │ 337.7 MB   │ Administrator │ disabled │
└──────────┴────┴─────────┴──────┴────────┴─────────┴────────┴─────── ┴────────────┴───────────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
C:\Users\Administrator\.pm2\pm2.log last 20 lines:
PM2        | [2018-07-23T14:32:50.338Z] PM2 log: --- New PM2 Daemon started ----------------------------------------------------
PM2        | [2018-07-23T14:32:50.339Z] PM2 log: Time                 : Mon Jul 23 2018 14:32:50 GMT+0800 (中国标准时间)
PM2        | [2018-07-23T14:32:50.339Z] PM2 log: PM2 version          : 3.0.0
PM2        | [2018-07-23T14:32:50.339Z] PM2 log: Node.js version      : 7.9.0
PM2        | [2018-07-23T14:32:50.339Z] PM2 log: Current arch         : x64
PM2        | [2018-07-23T14:32:50.339Z] PM2 log: PM2 home             : C:\Users\Administrator\.pm2
PM2        | [2018-07-23T14:32:50.339Z] PM2 log: PM2 PID file         : C:\Users\Administrator\.pm2\pm2.pid
PM2        | [2018-07-23T14:32:50.339Z] PM2 log: RPC socket file      : \\.\pipe\rpc.sock
PM2        | [2018-07-23T14:32:50.339Z] PM2 log: BUS socket file      : \\.\pipe\pub.sock
PM2        | [2018-07-23T14:32:50.340Z] PM2 log: Application log path : C:\Users\Administrator\.pm2\logs
PM2        | [2018-07-23T14:32:50.341Z] PM2 log: Process dump file    : C:\Users\Administrator\.pm2\dump.pm2
PM2        | [2018-07-23T14:32:50.341Z] PM2 log: Concurrent actions   : 2
PM2        | [2018-07-23T14:32:50.341Z] PM2 log: SIGTERM timeout      : 1600
PM2        | [2018-07-23T14:32:50.342Z] PM2 log: ===============================================================================
PM2        | [2018-07-23T14:32:50.407Z] PM2 log: Starting execution sequence in -cluster mode- for app name:app id:0
PM2        | [2018-07-23T14:32:50.760Z] PM2 log: App name:app id:0 online
PM2        | [2018-07-23T14:32:50.764Z] PM2 log: Starting execution sequence in -cluster mode- for app name:app id:1
PM2        | [2018-07-23T14:32:50.770Z] PM2 error: (node:276) DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
PM2        | [2018-07-23T14:32:51.268Z] PM2 log: App name:app id:1 online
PM2        | [2018-07-23T14:32:51.270Z] PM2 error: (node:276) DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.

**Comment by wallet77** [comment]
Hi @zhuernm 

As nodeJs documentation says : 

> In practice however, distribution tends to be very unbalanced due to operating system scheduler vagaries. Loads have been observed where over 70% of all connections ended up in just two processes, out of a total of eight.

https://nodejs.org/api/cluster.html#cluster_how_it_works

So it's not really a "bug" but an OS limitation and a behavior which is out of pm2 or nodeJs scope.
Especially on windows that does not support round-robin algorithm.
