### ISSUE TITLE
unable to start pm2 flask application

### ISSUE THREAD

**Issue by vijaysagi1** [Unitech/pm2#3816]
## What's going wrong?
 unable to start the flask application
the error is 

[2018-07-23T07:23:29.818Z] PM2 log: ===============================================================================
[2018-07-23T07:23:29.818Z] PM2 error: [PM2] Resurrecting PM2
Be sure to have the latest version by doing `npm install pm2@latest -g` before doing this procedure.
[PM2] Saving current process list...
/usr/local/lib/node_modules/pm2/node_modules/pidusage/lib/procfile.js:26
    buf = Buffer.alloc(SIZE)
                 ^
TypeError: Buffer.alloc is not a function
    at readUntilEnd (/usr/local/lib/node_modules/pm2/node_modules/pidusage/lib/procfile.js:26:18)
    at /usr/local/lib/node_modules/pm2/node_modules/pidusage/lib/procfile.js:67:5
    at FSReqWrap.oncomplete (fs.js:82:15)

## How could we reproduce this issue?
pm2 start app.py

## Supporting information
nodejs version: 4.2.6
pm2 3.0.0
npm 6.1.0

```
$ pm2 report



pls suggest the way forward```

**Comment by wallet77** [comment]
Hi @vijaysagi1 

It's because a flask app cannot be started as normal python app.
It should be started with `flask run` command.

```
$ export FLASK_APP=hello.py
$ pm2 start "flask run"
```

**Comment by Unitech** [comment]
Buffer.alloc requires Node v4.5.0

**Comment by vijaysagi1** [comment]
Thank u so much. its working
