### ISSUE TITLE
Get PM2 log timestamps to match server time zone?

### ISSUE THREAD

**Issue by yourfavorite** [Unitech/pm2#3818]
I am starting my app with the following command:
`pm2 start index.js --name server --log-date-format="MM-DD hh:mm:ss.SSS A"`

It works great but the timestamps do not match the time zone of my server. Instead it appears they are GMT. Is there a way to fix this?

**Comment by Unitech** [comment]
Hello, please refer to the moment lib: https://momentjs.com/docs/#/parsing/string-format/

**Comment by yourfavorite** [comment]
@Unitech 
Unless I'm missing something this does not cover how to get PM2 to log using the server's set time zone. I have the server timezone set to US Los Angeles, but my logs in PM2 are still GMT. I assume there is a setting somewhere in PM2 that will allow my logs to display in the desired time zone?

**Comment by yourfavorite** [comment]
I have also tried the following config file but my logs still do not appear in local time:
```module.exports = {
  apps : [
    // SERVER
    {
      name      : 'server',
      script    : 'index.js',
      log_date_format: 'MM-DD hh:mm:ss.SSS A',
      autorestart: true,
      env: {
        TZ: 'America/Los_Angeles'
      },
    },
  ],
};```

**Comment by yourfavorite** [comment]
Also, to clarify. The last log statement occurred at 11:26 AM in Los Angeles, but my PM2 console log shows the time as 7 hours ahead:

`0|server   | 07-24 06:26:32.514 PM: Server live`

**Comment by hkchakladar** [comment]
If restart the server after changing server timezone, your server timezone would be used in log time.

**Comment by yourfavorite** [comment]
@hkchakladar unless I'm missing something, this does not fix the issue. When I run `date` in terminal, I get the correct timestamp. However pm2 is still returning UTC time stamp.

**Comment by yourfavorite** [comment]
I gave another quick look on this and I believe we'd need to have pm2 modified to use `moment.utcOffset()` (http://momentjs.com/docs/#/manipulating/utc-offset/) and allow users to set a config option for the offset.

**Comment by hkchakladar** [comment]
@yourfavorite did you restarted your server?

**Comment by yourfavorite** [comment]
Yes. It does not fix the problem. For now I've just disabled timestamp logging for PM2 and I add the timestamps myself via a custom log function.

**Comment by mdumrauf** [comment]
I am facing this issue too

**Comment by tohagan** [comment]
same issue here.

**Comment by cjk** [comment]
Yes, this is *actually* a problem. PM2 is always on UTC, despite the timezone set in the OS.
Shouldn't be too hard to fix.

**Comment by makss** [comment]
Same Issue #3391

**Comment by shahidcodes** [comment]
I fixed it by doing following-
- first update the format (make sure server timezone is what you want)
```
pm2 restart 0 --log-date-format "HH:MM DD-MM-YYYY Z" 
```
- save all processes
```
pm2 save
```
- run these
```
npm i -G pm2 //if not latest  
pm2 update
```

**Comment by uchiwayas** [comment]
@shahidcodes for the date format make sure to use `HH:mm` instead of `HH:MM` because `m` is for minute and `M` is for Month, otherwise it will display the month where the minutes should be shown

**Comment by henno** [comment]
> pm2 restart 0 --log-date-format "HH:MM DD-MM-YYYY Z" 

HH:mm, not HH:MM because MM means month

**Comment by aliumch** [comment]
> If restart the server after changing server timezone, your server timezone would be used in log time.

this worked for me

**Comment by jvbutera** [comment]
> > pm2 restart 0 --log-date-format "HH:mm DD-MM-YYYY Z"
> 
> Where in this command we are telling pm2 to use my time zone?

"Z" is local timezone.

**Comment by medfarouk312** [comment]
> I fixed it by doing following-
> 
> * first update the format (make sure server timezone is what you want)
> 
> ```
> pm2 restart 0 --log-date-format "HH:mm DD-MM-YYYY Z" 
> ```
> 
> * save all processes
> 
> ```
> pm2 save
> ```
> 
> * run these
> 
> ```
> npm i -G pm2 //if not latest  
> pm2 update
> ```

thnx

**Comment by claudineigit** [comment]
> I fixed it by doing following-
> 
> * first update the format (make sure server timezone is what you want)
> 
> ```
> pm2 restart 0 --log-date-format "HH:mm DD-MM-YYYY Z" 
> ```
> 
> * save all processes
> 
> ```
> pm2 save
> ```
> 
> * run these
> 
> ```
> npm i -G pm2 //if not latest  
> pm2 update
> ```

Thanks. It worked perfectly.

**Comment by andraz** [comment]
I've found that `pm2 restart 0 --log-date-format "."` is a good workaround for the missing feature to disable pm2 log timestamps.

After this you can run this in the console and get a clean output: `pm2 logs 0 --raw`

You need to put something in the quotes, it still prints out that garbage, but better ignoring 3 chars no one ever asked for, than a huge block of text.
