### ISSUE TITLE
PM2 crash - segfault error

### ISSUE THREAD

**Issue by ChenL88** [Unitech/pm2#3819]
While running on Production , PM2 main process crash with kernel error:
**kernel: [603170.036435] PM2 v2.10.4: Go[3113]: segfault at 4052458c8e0 ip 000004052458c8e0 sp 00007ffdd456f4b8 error 15**

Amazon Linux AMI release 2018.03
PM2 version                        2.2.3
Main Node version :            8.11.3
** We using it to run node applications that use node interpreter 0.10 and up.

Help needed.

**Comment by Unitech** [comment]
Seems like a system / node issue not related to pm2 itself.
Could you try with the latest pm2 (3.0): `npm install pm2 -g ; pm2 update`

**Comment by ion-willo** [comment]
We just got
`Jul 25 20:06:49 ip-10-0-32-27 kernel: [621191.242432] PM2 v3.0.0: God[1683]: segfault at f5cb80 ip 0000000000f5cb80 sp 00007ffc291bf6a8 error 15 in node[400000+1dc1000]
`
Also Amazon Linux AMI

**Comment by vmarchaud** [comment]
@ion-willo Is there a core dump around ? Maybe in `~/.pm2` ?

**Comment by vmarchaud** [comment]
Note that the latest pm2 version require at least node 4 so if we find a fix and publish a fix, would you be able to upgrade ?

**Comment by ion-willo** [comment]
Sorry, no core dump files :(

We're currently running on node v10.7.0, so we should be good to go

**Comment by soyuka** [comment]
With no core dump we won't be able to help you debug this issue, please make sure to [set up your system](https://www.javascriptjanuary.com/blog/nodejs-postmortem-debugging-for-fun-and-production) so that dumps are generated and come back to us! Thanks!

**Comment by ion-willo** [comment]
Had another crash last night. Unfortunately the `ulimit -c` command did not stick. Hopefully we'll have another crash, this time with core dump, today or tomorrow.

**Comment by ChenL88** [comment]
after zip its 7M

**Comment by ChenL88** [comment]
sent .

**Comment by ion-willo** [comment]
We got some core dumps recently again. You want me to send them to tech@keymetrics.io?

**Comment by vmarchaud** [comment]
I didn't received the other one, would it be possible to send directly to `valentin at keymetrics dot io` and `vincent at keymetrics dot io` ?

**Comment by ion-willo** [comment]
Done. Please let me know if you don't receive it.

**Comment by vmarchaud** [comment]
@ion-willo got them, i will inspect them thanks

**Comment by ion-willo** [comment]
@vmarchaud 
```
node -v
v10.7.0
```

**Comment by ion-willo** [comment]
@vmarchaud any news on this issue? I have several more core dump files available if it will help.

**Comment by danamajid** [comment]
@ion-willo do you happen to be on the C5 EC2 instance type?

I am seeing this happen too in my set up, but only for services that are running on c5.

**Comment by ChenL88** [comment]
I'm also using C5 EC2 instance.
is there a fix for this?

**Comment by Unitech** [comment]
Could you try with the latest version of PM2 (3.2.0):

```bash
$ npm install pm2 -g
$ pm2 update
```

Blog post: https://blog.pm2.io/pm2-runtime-3-2-autumn-features/
Changelog: https://github.com/Unitech/pm2/releases/tag/3.2.0

**Comment by danamajid** [comment]
@Unitech fyi, after upgrading from 2.8.0 to 3.2.0 about 28 days ago we stopped seeing the occasional segfaults! Will report back if this changes.

**Comment by cchadwickk** [comment]
Hi
We're also experiencing pm2 randomly getting killed on m5 ec2 instance type.
Other than the log provided above we got a slightly longer log.

`kernel: [1084396.610433] PM2 v1.1.3: God[7020]: segfault at 7efc96cc7d80 ip 00007efc96cc7d80 sp 00007ffd61656208 error 15 in libstdc++.so.6.0.19[7efc96c69000+e6000]`

Does this help ?
Regards

**Comment by ion-willo** [comment]
Upgrading to v3.2.0 has been to good us so far too

**Comment by cchadwickk** [comment]
I have another doubt, and sorry if this is the wrong place to post this but pm2 version > 3.0 drops "gracefulReload", which is critical to our production environment. Do we need to alter the code somehow to use the "reload" option instead or is that a direct replacement for gracefulReload? @ion-willo

**Comment by ion-willo** [comment]
@cchadwickk I'm sure. We're not using that feature. We're using clustering where a restart is effectively a graceful restart AFAIK
