### ISSUE TITLE
pm2 gracefulReload all removed in 3.0.0?

### ISSUE THREAD

**Issue by scottbasgaard** [Unitech/pm2#3824]
I see this command was removed in 3.0.0 is there an alternative command to do the same thing or a new recommendation?

**Comment by scottbasgaard** [comment]
I'm guessing I should be using just `pm2 reload all`

**Comment by wallet77** [comment]
Hi @scottbasgaard 

Indeed gracefulReload and reload shared the same code.
This is why we drop it in 3.0.0

**Comment by scottbasgaard** [comment]
Thanks dude, sounds 👍 and swapped out what I needed.
