### ISSUE TITLE
PM2 won't start after update

### ISSUE THREAD

**Issue by dreaddymck** [Unitech/pm2#3825]
## What's going wrong?
Hangs on start. Reinstalling does not fix the problem.

[PM2] Spawning PM2 daemon with pm2_home=/home/dreaddy/.pm2
[PM2] PM2 Successfully daemonized
[PM2] Starting /home/dreaddy/Projects/socache-server/index.js in fork_mode (1 instance)
[PM2] Done.

then hangs........

## How could we reproduce this issue?
Do the recommended update
.
## Supporting information

```
$ pm2 report

[PM2] Spawning PM2 daemon with pm2_home=/home/dreaddy/.pm2
[PM2] PM2 Successfully daemonized
===============================================================================
--- PM2 REPORT (Tue Jul 24 2018 13:21:34 GMT-0500 (Eastern Standard Time)) ----
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.0.1
node version         : 10.7.0
node path            : /home/dreaddy/.nvm/versions/node/v10.7.0/bin/pm2
argv                 : /home/dreaddy/.nvm/versions/node/v10.7.0/bin/node,/home/dreaddy/.nvm/versions/node/v10.7.0/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : dreaddy
uid                  : 1000
gid                  : 1000
uptime               : 0min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.0.1
node version         : 10.7.0
node path            : /home/dreaddy/.nvm/versions/node/v10.7.0/bin/pm2
argv                 : /home/dreaddy/.nvm/versions/node/v10.7.0/bin/node,/home/dreaddy/.nvm/versions/node/v10.7.0/bin/pm2,report
argv0                : node
user                 : dreaddy
uid                  : 1000
gid                  : 1000
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Core(TM) i5-2540M CPU @ 2.60GHz
cpus nb              : 4
freemem              : 2191532032
totalmem             : 8245415936
home                 : /home/dreaddy
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘

```

**Comment by mdw19873** [comment]
I'm having this exact same issue since updating to 3.0.1

**Comment by pakastin** [comment]
Same thing here, both 3.0.0 and 3.0.1 – had to downgrade to 2.10.4

**Comment by mdw19873** [comment]
Downgrading to 2.10.4 got it working again

**Comment by sfrisk** [comment]
Same issue here, and switching to 3.0.1 didn't work!  Shall try downgrading to 2.10.4

**Comment by wallet77** [comment]
Hi @all 

I made some test on my personal computer.
It's working as expected on 3.x

Could you share you `pm2 report` ?

What you can try is to kill pm2 daemon.

**Comment by pakastin** [comment]
I tried pretty much everything: reboot, uninstall, reboot again, killall, install 3.0.0, install 3.0.1...nothing helps..

I'm running node `8.11.3`.

**Comment by mdw19873** [comment]
I tried many, many things as well. Uninstall, reinstall 3.0.0. Uninstall, reboot, reinstall 3.0.0. I even nuked the .pm2 folder and killed all runnings pm2 deamon and it just wouldn't work. I experienced the issue on both node 6.14.3 and 8.11.3 running on CentOS 7.5.1804. PM2 reports to follow

**Comment by dreaddymck** [comment]
Downgrading to 2.10.4 worked. 

Note: I also had to remove node_modules, package-lock.json and rebuild the projects.

After I got it all working. I tried updating PM2 once again to the latest. Same problem.

Any solutions?

**Comment by mdw19873** [comment]
`[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
===============================================================================
--- PM2 REPORT (Tue Jul 24 2018 19:08:40 GMT+0000 (UTC)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.0.1
node version         : 6.14.3
node path            : /bin/pm2
argv                 : /usr/bin/node,/usr/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
uptime               : 0min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.0.1
node version         : 6.14.3
node path            : /bin/pm2
argv                 : /usr/bin/node,/bin/pm2,report
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
cpus nb              : 1
freemem              : 420945920
totalmem             : 1038225408
home                 : /root
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app`

**Comment by sfrisk** [comment]
`
/usr/src/app # pm2 report
                        -------------
__/\\\\\\\\\\\\\____/\\\\____________/\\\\____/\\\\\\\\\_____
 _\/\\\/////////\\\_\/\\\\\\________/\\\\\\__/\\\///////\\\___
  _\/\\\_______\/\\\_\/\\\//\\\____/\\\//\\\_\///______\//\\\__
   _\/\\\\\\\\\\\\\/__\/\\\\///\\\/\\\/_\/\\\___________/\\\/___
    _\/\\\/////////____\/\\\__\///\\\/___\/\\\________/\\\//_____
     _\/\\\_____________\/\\\____\///_____\/\\\_____/\\\//________
      _\/\\\_____________\/\\\_____________\/\\\___/\\\/___________
       _\/\\\_____________\/\\\_____________\/\\\__/\\\\\\\\\\\\\\\_
        _\///______________\///______________\///__\///////////////__
                          Runtime Edition
        PM2 is a Production Process Manager for Node.js applications
                     with a built-in Load Balancer.
                Start and Daemonize any application:
                $ pm2 start app.js
                Load Balance 4 instances of api.js:
                $ pm2 start api.js -i 4
                Monitor in production:
                $ pm2 monitor
                Make pm2 auto-boot at server restart:
                $ pm2 startup
                To go further checkout:
                http://pm2.io/
                        -------------
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
===============================================================================
--- PM2 REPORT (Tue Jul 24 2018 19:07:46 GMT+0000 (UTC)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.0.1
node version         : 8.11.3
node path            : not found
argv                 : /usr/local/bin/node,/usr/local/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : undefined
uid                  : 0
gid                  : 0
uptime               : 0min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.0.1
node version         : 8.11.3
node path            : not found
argv                 : /usr/local/bin/node,/usr/local/bin/pm2,report
argv0                : node
user                 : undefined
uid                  : 0
gid                  : 0
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Core(TM) i7-7Y75 CPU @ 1.30GHz
cpus nb              : 2
freemem              : 337653760
totalmem             : 2096066560
home                 : /root
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
`

`
/usr/src/app # pm2-docker process.yml
[2018-07-24T19:09:24.613Z] PM2 log: Launching in no daemon mode
[2018-07-24T19:09:24.704Z] PM2 log: Starting execution sequence in -cluster mode- for app name:MyAppName id:0
[2018-07-24T19:09:24.792Z] PM2 log: App name:MyAppName id:0 online
[2018-07-24T19:09:24.794Z] PM2 log: Starting execution sequence in -cluster mode- for app name:MyAppName id:1
[2018-07-24T19:09:24.799Z] PM2 error: (node:147) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
[2018-07-24T19:09:24.880Z] PM2 log: App name:MyAppName id:1 online
[2018-07-24T19:09:24.882Z] PM2 error: (node:147) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
ReferenceError: window is not defined
    at Object.module.exports.Object.assign.i (/usr/src/app/webpack:/src/config.js:22:31)
    at __webpack_require__ (/usr/src/app/webpack:/webpack/bootstrap 85ce6d8f625c06cae405:19:1)
    at Object.<anonymous> (/usr/src/app/webpack:/src/data/sources/ddb/setupDynamoose.js:2:1)
    at __webpack_require__ (/usr/src/app/webpack:/webpack/bootstrap 85ce6d8f625c06cae405:19:1)
    at Object.<anonymous> (/usr/src/app/webpack:/src/server.js:7:1)
    at __webpack_require__ (/usr/src/app/webpack:/webpack/bootstrap 85ce6d8f625c06cae405:19:1)
    at /usr/src/app/webpack:/webpack/bootstrap 85ce6d8f625c06cae405:62:1
    at Object.<anonymous> (/usr/src/app/server.js:68:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
[2018-07-24T19:09:25.274Z] PM2 log: App name:MyAppName id:0 disconnected
[2018-07-24T19:09:25.276Z] PM2 log: App [MyAppName] with id [0] and pid [157], exited with code [0] via signal [SIGINT]
[2018-07-24T19:09:25.279Z] PM2 log: Starting execution sequence in -cluster mode- for app name:MyAppName id:0
ReferenceError: window is not defined
    at Object.module.exports.Object.assign.i (/usr/src/app/webpack:/src/config.js:22:31)
    at __webpack_require__ (/usr/src/app/webpack:/webpack/bootstrap 85ce6d8f625c06cae405:19:1)
    at Object.<anonymous> (/usr/src/app/webpack:/src/data/sources/ddb/setupDynamoose.js:2:1)
    at __webpack_require__ (/usr/src/app/webpack:/webpack/bootstrap 85ce6d8f625c06cae405:19:1)
    at Object.<anonymous> (/usr/src/app/webpack:/src/server.js:7:1)
    at __webpack_require__ (/usr/src/app/webpack:/webpack/bootstrap 85ce6d8f625c06cae405:19:1)
    at /usr/src/app/webpack:/webpack/bootstrap 85ce6d8f625c06cae405:62:1
    at Object.<anonymous> (/usr/src/app/server.js:68:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
`

**Comment by mdw19873** [comment]
https://pastebin.com/KtRHMiDM
https://pastebin.com/cfJd6saQ

**Comment by mkg20001** [comment]
This seems to fix it:
```
/usr/lib/node_modules/pm2/node_modules/pidusage/lib/procfile.js
     1	var fs = require('fs')
     2	var path = require('path')
     3	var updateCpu = require('./helpers/cpu')
     4	var parallel = require('./helpers/parallel')
     5	var history = require('./history')
     6	var cpuInfo = null
     7	// var Buffer = require('safe-buffer')
COMMENT OUT THE ABOVE LINE ^^
     8	var SIZE = 1024 // if the stat file is bigger then this I'll buy you a drink
     9	
    10	function noop () {}
```

**Comment by watson** [comment]
Yeah, we just ran into the same issue. The pidusage dependency is the culprit.

Unfortunately their GitHub repo messed up and doesn't contain all the correct commits?!?! So the code you get when you npm install isn't the same as in the repo. Seems like some of the releases on npm are messed up as well: https://github.com/soyuka/pidusage/issues/72

**Comment by watson** [comment]
The line was supposed to be `var Buffer = require('safe-buffer').Buffer` - I think that would fix it as well

**Comment by dreaddymck** [comment]
This is good news. Thanks for the response. 

Will they roll out a new version or will this be a install trial and error thing for @3.0.1?

**Comment by watson** [comment]
I think pinning pidusage to v2.0.13 for the time being will fix it as well

**Comment by dreaddymck** [comment]
Thank you. 
I Have not pinned the pidusage to confirm as of this moment. 
Will wait for an update.
Closing issue.

**Comment by watson** [comment]
@dreaddymck I think the issue is still relevant for others who have the same issue, so I vote for keeping it open until either a new version of pm2 is released that pins pidusage, or pidusage release a fix - whichever comes first

**Comment by mdw19873** [comment]
You should leave this issue open until it is resolved one of two ways

**Comment by dreaddymck** [comment]
Sorry about that. Got lost in debugs.

**Comment by anthonee1230** [comment]
@vmarchaud  Looks good now over here!

**Comment by calvinwhitehurst** [comment]
@vmarchaud Looks good, thank you!

**Comment by dreaddymck** [comment]
pm2@3.0.2 looks good here too. 

Thank you. 

Closing issue now.

**Comment by dreaddymck** [comment]
oops

**Comment by pakastin** [comment]
`3.0.2` works again, thanks! 😎👍

**Comment by mdw19873** [comment]
3.0.2 is working for me! Thanks!

**Comment by angelmadames** [comment]
3.0.2 worked for me as well. Thanks.

**Comment by martonic** [comment]
I have the same problem with pm2 version 3.0.2.  It outputs some normal-looking text and then hangs instead of starting a process. Version 2.10.4 seems to be working normally.  I am running Node 5.7.1.

**Comment by ismailkattakath** [comment]
The issue **exists** even after upgrading to version 3.0.2. Please find the PM2 Report below.
`===============================================================================
--- PM2 REPORT (Mon Aug 27 2018 12:04:32 GMT-0400 (EDT)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.0.4
node version         : 4.1.0
node path            : /usr/local/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/lib/node_modules/pm2/lib/Daemon.js
argv0                : undefined
user                 : deploy
uid                  : 1000
gid                  : 1000
uptime               : 0min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.0.4
node version         : 4.1.0
node path            : /usr/local/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/bin/pm2,report
argv0                : undefined
user                 : deploy
uid                  : 1000
gid                  : 1000
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
cpus nb              : 4
freemem              : 6389510144
totalmem             : 8373051392
home                 : /home/deploy
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘`

**Comment by ismailkattakath** [comment]
Unfortunately, even after upgrading to 3.0.2, the issue persists. Please find PM2 Report below:

> [PM2] Spawning PM2 daemon with pm2_home=/home/deploy/.pm2
[PM2] PM2 Successfully daemonized
===============================================================================
--- PM2 REPORT (Mon Aug 27 2018 12:04:32 GMT-0400 (EDT)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.0.4
node version         : 4.1.0
node path            : /usr/local/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/lib/node_modules/pm2/lib/Daemon.js
argv0                : undefined
user                 : deploy
uid                  : 1000
gid                  : 1000
uptime               : 0min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.0.4
node version         : 4.1.0
node path            : /usr/local/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/bin/pm2,report
argv0                : undefined
user                 : deploy
uid                  : 1000
gid                  : 1000
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
cpus nb              : 4
freemem              : 6389510144
totalmem             : 8373051392
home                 : /home/deploy
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘

**Comment by dreaddymck** [comment]
Just upgrade to 3.0.4 from 3.0.3 with no issues.

3.0.3 resolved this issue for me.

Try installing 3.0.3 then upgrade to 3.0.4.

**Comment by ismailkattakath** [comment]
Thank you for the quick response @dreaddymck . I've tried reinstalling pm2 to 3.0.3. At least I could get over issue with `pm2 update`. But, when I run the application, it still stuck at launching.

> ===============================================================================
--- PM2 REPORT (Mon Aug 27 2018 13:28:32 GMT-0400 (EDT)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.0.3
node version         : 4.1.0
node path            : /usr/local/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/lib/node_modules/pm2/lib/Daemon.js
argv0                : undefined
user                 : deploy
uid                  : 1000
gid                  : 1000
uptime               : 5min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.0.3
node version         : 4.1.0
node path            : /usr/local/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/bin/pm2,report
argv0                : undefined
user                 : deploy
uid                  : 1000
gid                  : 1000
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
cpus nb              : 4
freemem              : 6541201408
totalmem             : 8373051392
home                 : /home/deploy
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘

**Comment by dreaddymck** [comment]
I recall having a similar problem. That problem was because a port got stuck. I had to stop pm2 and kill that zombie processes.

Give that a try, check see if you have an occupied port.

Failing that  I would recommend downgrading the the version posted earlier in this thread and hang tight for the developer response.

**Comment by martonic** [comment]
I just tried pm2 version 3.04 and had the same problem. I can install it and run pm2 update. 

HOWEVER, if I then try to start a process, I get this:

$ pm2 start app.js --name k1
[PM2] Starting /home/example/app.js in fork_mode (1 instance)
[PM2] Done.

and it hangs - I have to use Ctrl-C to get back to the shell prompt, and then the process dies.

Reverting to version 2.10.4 solved the problem (again).
