### ISSUE TITLE
how to let log4js and pm2 be friend?

### ISSUE THREAD

**Issue by kazaff** [Unitech/pm2#383]
env:
node: 0.10.26
os: ubuntu 13

my code use [log4js](https://github.com/nomiddlename/log4js-node/wiki/Multiprocess) to log, when run `pm2 start app,js`, always return a error(`connect ECONNREFUSED`)~

why?

**Comment by thelonglqd** [comment]
PM2 in cluster mode does not run the master implementation (handling by itself)
if(!cluster.isMaster){
   log4js.configure('./config/log4js-master.json');
}

log4js need this line of code to configure logger.
Do not run this line of code lead log4js to default logger

defaultConfig =   {
  appenders: [
    { type: "console" }
  ],
  replaceConsole: false
};

Does any options for interrupting the master job done by PM2 ?

**Comment by thelonglqd** [comment]
Does pm2 support master implementation manually in new version ? I stuck by that case once again, with refresh all the worker configuration object ?

**Comment by Unitech** [comment]
Can you show me a code sample where you use log4js with the cluster mode? (besides the configuration on the master)

**Comment by thelonglqd** [comment]
The problem related to log4js was solved, log4js configuration can all define inside
`if(!cluster.isMaster)` (worker implementation).

Now I face another one, related to master implementation with pm2.
I has a service /refresh/config to refresh configuration object (assigned to a GLOBAL variable in NodeJS).
`GLOBAL.configData = {...}`
When I edit the configuration file (form of json file like below)
```
{
  "CRON_TIME_REFRESH_XXX": "0 * * * *",
  "CRON_TIME_REFRESH_YYY": "0 * * * *",
  "CRON_TIME_REFRESH_ZZZ": "0 * * * *",
  "CRON_TIME_REFRESH_TTT": "0 * * * *"
}
```
And after editing this file, I make a call to /refresh/config.
I need to refresh the GLOBAL.configData object to reflect what I just edited in the configuration file.
But, my application runs in cluster mode with feature provided by pm2, by the below command:
`pm2 start myApp -i -1`

Cause of GLOBAL variable in NodeJS just has effect on the process which it is running on.
So, just the GLOBAL variable of the process that served the request of /refresh/config change the configuration value, the rest do not!.

With built-in cluster mode of NodeJS, I can do something like sending message from worker to master and vice versa, but with pm2, I can not do this.

I took some research and found out you had a module like pm2-intercome, but I saw that "Module System" is disabled in PM2 home page (http://pm2.keymetrics.io/).

So sorry for not supplying very details about my project code.

If you had any ideas about this problem, please help to let me know

Many thanks in advance !

**Comment by mogongzi** [comment]
I submitted the same issue on log4js module one year ago:
https://github.com/nomiddlename/log4js-node/issues/265

**Comment by mogongzi** [comment]
Hi Unitech,

Please refer the example here:
https://github.com/nomiddlename/log4js-node/wiki/Clustered

**Comment by thelonglqd** [comment]
I put all the log4js configuration inside worker code, left the master blank like this (because of pm2 does not let me implement anything about the master)
```
if (cluster.isMaster) {
//left it blank
} else {
//log4js configuration goes here
}
```

And It works for me now.

**Comment by yintiefu** [comment]
@thelonglqd Can you show me the project code

**Comment by mogongzi** [comment]
Hi @yintiefu,

I'm not sure what project code you want. @thelonglqd 's description is fuzzy for me. I don't know whether his app can use log4js module under pm2 cluster mode. And from his code snippet, I don't think log4js can be configured successfully.

For the original issue, I think maybe "whether log4js module can be used under pm2 cluster mode (start with -i parameter) ?"  is the accruate statement. After went through the source code of log4js cluster appender (https://github.com/nomiddlename/log4js-node/blob/master/lib/appenders/clustered.js). It seems the configuration must be set up on the master process. However, pm2 doesn't allow you do this under cluster mode. There is no interface or variables can perform this action.

I know the commucation between master and other forked process is a little mess. After went through the source code of ClusterMode.js (pm2 https://github.com/Unitech/pm2/blob/master/lib/God/ClusterMode.js), there is no way to setup log4js' configuration at the current stage because there is no such exposed interface (maybe I was wrong).

Thanks for all you guys' help!

**Comment by git-patrickliu** [comment]
@mogongzi How is everything going with log4js and pm2 cluster mode now? I use 
`if (cluster.isMaster) {
//left it blank
} else {
//log4js configuration goes here
}`
and I lost many logs in my log files.

**Comment by magicdawn** [comment]
Any updates ?

**Comment by magicdawn** [comment]
Any good solution to log right in node production ?

**Comment by dominhhai** [comment]
@magicdawn [Winston](https://github.com/winstonjs/winston) may be helpful.

**Comment by mogongzi** [comment]
@magicdawn Frankly speaking, @dominhhai 's suggestion was right. I have to change the logging module from log4js to bunyan at the current stage :(

**Comment by magicdawn** [comment]
but bunyan & winston also need to handle the cluster problem, multi process write to a single file ?

**Comment by vmarchaud** [comment]
@magicdawn You can make a custom pm2 module that listen for all logs on the bus and write them where you want.

**Comment by magicdawn** [comment]
Looks like the `process.env. NODE_APP_INSTANCE` will be set
It will be the clustered instance id

**Comment by mogongzi** [comment]
@magicdawn So, is the problem still exist now? after at least 3 years later?

**Comment by magicdawn** [comment]
Yeah, if u use pm2 cluster mode, your code runs as workers, multiple wokers manipulate one file will leads to problems, the solution is the `process.env.NODE_APP_INSTANCE` set by pm2, use this variable to tell workers to write to, rotate log on different files.

**Comment by magicdawn** [comment]
But that's not on the official document ... Hahhh

**Comment by vmarchaud** [comment]
@magicdawn http://pm2.keymetrics.io/docs/usage/environment/#specific-environment-variables ?

**Comment by magicdawn** [comment]
Oh I missed that ..................................................

**Comment by NextZeus** [comment]
log4js cannot work in pm2 fork mode ,it only worked in cluster mode with my test. after looked @mogongzi `s comment , i decided to gave up log4js with pm2 , and try to use other log framework.

**Comment by yulrosy** [comment]
pm2 fork mode + log4js 1.x worked for me , but upgrade log4js to 2.x,  it doesn't work
