### ISSUE TITLE
this.registerToKM is not a function

### ISSUE THREAD

**Issue by canyoudev** [Unitech/pm2#3831]
## What's going wrong?
I installed pm2 without sudo following this instructions https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md

I started `pm2` app. Then I type `pm2 monitor` and it's throws me an error

```
TypeError: this.registerToKM is not a function
```

**Comment by wallet77** [comment]
Ok I reproduce this when you are not linked to Keymetrics.

**Comment by wallet77** [comment]
Hi @canyoudev 

It's fixed in PR https://github.com/Unitech/pm2/pull/3832.
But I think you want `pm2 monit` and not `pm2 monitor`, am I right ?

**Comment by canyoudev** [comment]
@wallet77 yes, that's correct. Thank you!

**Comment by Unitech** [comment]
fixed & published
