### ISSUE TITLE
pm2 v3.0.0 start command hangs on Intel (Ub16.04)

### ISSUE THREAD

**Issue by cnnaik** [Unitech/pm2#3835]
## What's going wrong?
I am working with **PM2 v3.0.0 on Intel (Ubuntu 16.04)** platform (installed **nodejs v 8.2.0**).
I could install pm2 successfully, but when I try to start server using command `pm2 start app.js`, it gets stuck. 

The console logs are as below:
_Spawning PM2 daemon with pm2_home=/home/test/.pm2
[PM2] PM2 Successfully daemonized
[PM2] Starting /home/test/workspace/PM2_3.0.0_Ubuntu16.04_s390x/app.js in fork_mode (1 instance)
[PM2] Done._

It **does not start the application** as expected. Also no logs could be found.

**Expected is:**
The command should display App name, App ID, Status, pid etc.

The same command works fine on Ubuntu18.04

## How could we reproduce this issue?
1. Install PM2 v3.0.0
   sudo npm install pm2@3.0.0 -g
2. Create a file app.js
var http = require('http');
var server = http.createServer(function (request, response) {
response.writeHead(200, {"Content-Type": "text/plain"});
response.end("Welcome to pm2\n");
});
server.listen(8080);
console.log("Server running at http://127.0.0.1:8080/");
3. Run the application
   pm2 start app.js

**Comment by wallet77** [comment]
Hi @cnnaik 

I'm not able to reproduce on a fresh install of ubuntu 16.04
PM2 : 3.0.0
node : 8.2.0

I think you should kill pm2 and pm2 agent and/or try to reinstall it.
