### ISSUE TITLE
PM2 monit does not display progress bars

### ISSUE THREAD

**Issue by ilikesomething** [Unitech/pm2#3836]
## What's going wrong?
`pm2 monit` does not display characters from progress bar packages (like : https://www.npmjs.com/package/cli-progress for example)

## How could we reproduce this issue?
`npm i cli-progress`

```js
const _cliProgress = require('cli-progress');
const bar1 = new _cliProgress.Bar({}, _cliProgress.Presets.shades_classic);
bar1.start(200, 0);
bar1.update(100);
bar1.stop();
```
`pm2 start --watch`
`pm2 monit`

## Supporting information

Works fine if you start without PM2

**Comment by micheljp** [comment]
Not really an issue for PM2. Can be solved for the [referenced package](https://www.npmjs.com/package/cli-progress) by setting noTTY to true in the configuration, e.g.:

`const fullLoadProgress = new _cliProgress.SingleBar({
  format: 'Load Progress |' + '{bar}' + '| {percentage}% || {value}/{total} EMPLIDS || ETA: {eta}s',
  barCompleteChar: '\u2588',
  barIncompleteChar: '\u2591',
  hideCursor: true,
  noTTYOutput: true
})`
