### ISSUE TITLE
execPath is from originating user even when using -user

### ISSUE THREAD

**Issue by ASwingler** [Unitech/pm2#3842]
pm2 v3.0.0
node v10.3
OS: Debian Stretch
Logged Error:
0|Controll | Error: spawn /root/.nvm/versions/node/v10.3.0/bin/node EACCES
0|Controll |     at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
0|Controll |     at onErrorNT (internal/child_process.js:406:16)
0|Controll |     at process._tickCallback (internal/process/next_tick.js:63:19)

I'm running the PM2 daemon as root, which is running a node process as a different user (using the -user and -cwd flags). This runs without a problem.

My problem is that when the node code forks a child process, it's picking up the version of node from the daemon and not the node process itself, which leads to the permission failure shown above.

I tried modifying the execPath of the child when it's instantiated by setting it to the execPath of the parent, but execPath is set to the daemon's execPath.

Is there a way to have execPath set appropriately when the daemon spawns a child process that runs under a different user, so that the code's forked children run under the same userid as their parent?

Thanks, Andrew.

**Comment by wallet77** [comment]
Hi @ASwingler 

Could you share how you fork your app ?
I think you should send execPath and maybe uid also in options.
https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options

**Comment by ASwingler** [comment]
Hi @wallet77 

Here's the snippet where I call the fork:
`this.cp_operled = await cp.fork(__dirname + '/child_runled',{ 'execPath' : process.execPath});`

I've tried using execPath and also uid with the same results each time. The process that's running the code snippet above is running with the correct uid but process.execPath is returning the path to node that's associated with the root userid, and not the userid that owns the process. 

It seems as though the PM2 daemon (running as root) starts a process that uses -user with the permissions of that user, but uses the execPath for root to fork that process instead of letting the process pick up its own version of node, which then means that the wrong path for node is being passed when the process forks a child.

I need PM2 to be able to kick off processes but allow those processes to use the environment (including path to node) from the user associated with -user. In that way each process is isolated and I can run different versions of node for each process if necessary.

Andrew.

**Comment by wallet77** [comment]
Hi @ASwingler 

I think options are third arg of fork. Second arg is for node_args.
Could you try like that : 
`this.cp_operled = await cp.fork(__dirname + '/child_runled',null, { 'execPath' : process.execPath});`

If it doesn't work I will investigate further.

**Comment by ASwingler** [comment]
Thanks for the quick response. I had already tried it as the third param with null as the second param but the outcome was the same.

**Comment by wallet77** [comment]
Ok I think I got it. If you use null as second args node will consider you have only 2 args instead of 3.
You should try with something like that : 
```
childProcess.fork('worker.js', [], {
    execPath: '/home/vince/.nvm/versions/node/v8.9.4/bin/node'
  })
```

It works for me with node or PM2.

**Comment by ASwingler** [comment]
That's great Vince. Thank you. This will work if I hard-code the node version instead of relying on the version of the calling (parent) process that's doing the childProcess.fork(). However I'd prefer not to have to hard-code the path to node if at all possible.

If I look at process.execPath on the parent it shows the node executable that the root daemon is running and not the version that I'd expect the user would pick up.
So:
PM2 runs as root and its version is:
/root/.nvm/versions/node/v10.3.0/bin/node

PM2 spawns a process running under user 'test' which has node installed and has path of:
/home/test/.nvm/versions/node/v10.3.0/bin/node

I'd expect the spawned process to use the node version from /home/test/... and not /root/...

What's the best way to ensure that the spawned process and any child processes run under the user specified in PM2 -user?

**Comment by wallet77** [comment]
If you don't want to hard code it you should use interpreter args.
For example in ecosystem file:  
```
{
  name: "my_app",
  interpreter: "/home/test/.nvm/versions/io.js/v10.3.0/bin/node",
}
```

Or using CLI : 
`pm2 start app.js --interpreter=/home/test/.nvm/versions/io.js/v10.3.0/bin/node`

**Comment by ASwingler** [comment]
Thanks. That will work.
