### ISSUE TITLE
Watch option Not working under Linux Containers 

### ISSUE THREAD

**Issue by naordah69** [Unitech/pm2#3843]
Watch option Not working under Linux Containers when code directory is mounted.

 Supporting information
this is my process.json information , included usePolling option.
 "apps" :
  [
      {
      "name"        : "express-app",
      "script"      : "bin/www",
      "append_env_to_name": true,
        "exec_mode" : "cluster",
        "watch":true,
        "watch_options": {
          "usePolling": true
        },

**Comment by geoshar** [comment]
strangely, try maybe `"restart_delay": 300,`

**Comment by naordah69** [comment]
No, Still not reloading.
