### ISSUE TITLE
Apps keep restarting for no reason

### ISSUE THREAD

**Issue by danielriosb** [Unitech/pm2#3851]
I have updated pm2 to the last version 3.0.3 and since then all my app keep restarting with no stop.
Before updating pm2 everything was working well. I have deleted, stopped and restarted every app but no solution. I even have restarted windows but still no solution. Everytime that i try to start a new app, it keeps restarting. I have started my app just using node command and everything works well. Hope someone can help me. 
<img width="989" alt="screen shot 2018-08-07 at 9 25 24 pm" src="https://user-images.githubusercontent.com/16639763/43811000-76c2975e-9a88-11e8-9c24-d642ecc14fb2.png">

**Comment by wallet77** [comment]
Could you share with us your app config ? And how you start it ?

Also run 
`pm2 report`

**Comment by Pensarfeo** [comment]
This is similar to the issue I was facing. I managed to reduce the problem to an error in my script. However, pm2 is not catching the error messages coming out of my Rscript. This is the script I am using to launch my Rscript.

```js
const pm2 = require('pm2')
const path = require('path')
const logFilePath = path.join(__dirname, "JSON-status.log")
console.log(logFilePath)

pm2.connect(function(err) {
  if (err) {
    console.error(err)
    process.exit(2)
  }

  pm2.start({
    script: '../R/main.r',
    maxRestarts: 10,
    interpreter: 'Rscript',
    output: logFilePath,
    error: logFilePath,
    watch: true,
  }, (err, apps) => {
    pm2.disconnect()
    if (err) { throw err }
    // trying to connect directly to the stderr
    // apps[0].stderr.on('data', (out) => {
    //   console.log(outString)
    // });
    console.log('print', apps[0])
  })
})
```

I also tried to connect to the stderr though apps, but ```apps[0].stderr.on``` is undefined; so I guess that's not the equivalent ```stderr``` object from node's ```child_process``` (?).
Any other ways of catching the output from my script?
