### ISSUE TITLE
Pm2 watch

### ISSUE THREAD

**Issue by Yvtq8K3n** [Unitech/pm2#3852]
Is it possible to watch for a external file?
Lets say i have the following file.
/home/marquez/.config/fseven/config.yaml
and the following ecosystem.config.js file.
```
module.exports = {
  apps : [{
    name      : 'fseven',
    script    : 'fseven',
    watch: '/home/marquez/.config/fseven/config.yaml',
    watch_options: {
       dot: true
    },
    env: {
      NODE_ENV: 'development'
    },
    env_production : {
      NODE_ENV: 'production'
    },
  }],
};

```

how can i reload my app everytime my config.yaml change? When i change the file, for some reason the application doesnt reload.

**Comment by wallet77** [comment]
Hi @Yvtq8K3n 


I made multiples test on absolute path in watch property, it worked every time.
Here my example, which is close to yours : 
```
{
  "apps" : [{
    "name": "server",
    "script": "server.js",
    "watch": "/home/vince/Dev/pmx-2/package.json",
    "watch_options": {
      "dot": true
    },
    "env": {
      "NODE_ENV": "development"
    },
    "env_production" : {
      "NODE_ENV": "production"
    }
  }]
}
```

**Comment by Yvtq8K3n** [comment]
Thanks, bro. The problem relies in the .config file. Pm2 uses a library called  chowkidar that ignores all files whit dots. The best solution was to change the file into a no dot directory, thanks for the help :)
