### ISSUE TITLE
Compatibility with Octopus Deploy

### ISSUE THREAD

**Issue by Steztric** [Unitech/pm2#3856]
## What's going wrong?
I deploy my app through Octopus Deploy, which will start the app with PM2 in the post deployment script. When the app is already running, everything is fine and it restarts the app. However, if the app is not running, Octopus will hang indefinitely.

I believe the difference is that when the app is not running I get a warning on the console that appears in yellow;

>pm2 start process.config.js
[PM2][WARN] Applications myapp not running, starting...
[PM2] App [myapp] launched (1 instances)

Is there any way to turn off this warning? I don’t understand why PM2 is warning me when I want to start a new app.

## How could we reproduce this issue?

The only way to reproduce this is through Octopus Deploy

## Supporting information

```
$ pm2 report

===============================================================================
--- PM2 REPORT (Fri Aug 10 2018 14:20:33 GMT+0800 (Malay Peninsula Standard Time))
===============================================================================
--- Daemon -------------------------------------------------
pm2d version : 2.9.3
node version : 8.9.4
node path : undefined
argv : G:\ProgramFiles\config_manager\tools\nodejs\node.exe,G:\ProgramFiles\config_manager\node_modules\
pm2\lib\Daemon.js
argv0 : node
user : undefined
uid : N/A
gid : N/A
uptime : 135min
===============================================================================
--- CLI ----------------------------------------------------
local pm2 : 2.9.3
node version : 8.9.4
node path : undefined
argv : G:\ProgramFiles\config_manager\tools\nodejs\node.exe,G:\ProgramFiles\config_manager\node_modules\
pm2\bin\pm2,report
argv0 : node
user : N171190
===============================================================================
--- System info --------------------------------------------
arch : x64
platform : win32
type : Windows_NT
cpus : Intel(R) Xeon(R) CPU E5-2697 v4 @ 2.30GHz
cpus nb : 4
freemem : 737570816
totalmem : 4294361088
home : C:\Users\TEMP
===============================================================================
```

**Comment by wallet77** [comment]
Hi @Steztric 

Is it you or Octopus which detect the warning ? Anyway I really don't undertsand why it's a problem.
Maybe we can switch warning to info.

I think the warn is here in case you try to **restart** an app not already started.

**Comment by Steztric** [comment]
Octopus uses Powershell to invoke the post deployment script. I don’t think anything is specifically trying to capture warnings. Perhaps it’s just the fact that it is trying to make the console line yellow? I have no idea.

I just updated to version 3.0.3 and luckily the problem has been fixed in between! Unless you want to specifically patch the previous version I am happy to close this issue.
