### ISSUE TITLE
pm2 在windows非管理员模式下无法运行

### ISSUE THREAD

**Issue by csj8520** [Unitech/pm2#3859]
非管理员模式下运行错误
C:\>pm2 list
connect EPERM //./pipe/rpc.sock
[PM2] Spawning PM2 daemon with pm2_home=C:\Users\chang\.pm2
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect EPERM //./pipe/rpc.sock
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

管理员模式下正常运行
C:\Windows\system32>pm2 list
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app

**Comment by AnDongCai** [comment]
我在管理员模式下也无法运行

![image](https://user-images.githubusercontent.com/29848463/58624004-c7b14400-8301-11e9-9c7c-7857664566fb.png)
环境： windows 10
            node      10.16.0

**Comment by WEDeach** [comment]
I ran into the same problem in pm2 4.5.0

When I try to install windows autostart script
