### ISSUE TITLE
Issue running node-red

### ISSUE THREAD

**Issue by JBX028** [Unitech/pm2#3861]
Hi,

I just bought a new pi3+ and installed [node-red](https://nodered.org/) into it . When I run it with command "node-red", nodered starts with not issue.

I have installed pm2 for which I have already 2 applications running this way but it doesn't work with node-red.

"which node-red" returns /usr/bin/node-red

When I run "pm2 start /usr/bin/node-red -- -v" version 3.0.3 is displayed but nothing starts and no errors are displayed. 

```
pi@raspberrypi:~/.node-red $ pm2 start node-red -- -v
3.0.3
```

This is however the procedure describe here : https://nodered.org/docs/getting-started/running
Also on my old pi, I was able to run it with no problem.

I have tried several variations of it without success.

My config is the following:

10 Aug 17:09:13 - [info] Node-RED version: v0.18.7

10 Aug 17:09:13 - [info] Node.js version: v9.11.2

10 Aug 17:09:13 - [info] Linux 4.9.80-v7+ arm LE

I have tried to downgrade node js to 8.11.3 but without more success.

Do you have any ideas of what I should do? I am don't know if it's an issue with node-red or pm2 because I can run node-red without pm2 but in the meantime, I have other processes running with pm2....
I have opened an incident to the node-red support site but they said to open one here.

Thanks in advance..

**Comment by wallet77** [comment]
Hi @JBX028 

I think because node-red is not really a node application but a program installed on your system, you should use a script to start it.
Something like that (not tested) : 
```
const spawn = require('child_process').spawn;

let command;
const program = 'node-red';

command = spawn(program, {windowsHide: false});
command.stdout.on('data', (data) => {
  console.log(data.toString());
});

command.stderr.on('data', (data) => {
  console.log(data.toString());
});

command.on('close', (code) => {
  console.log(`child process exited with code ${code}`);
});
```

**Comment by JBX028** [comment]
Hi,
thanks I will try. The thing is that this is however documented that you
can start node-red this way and with my old pi (unfortunately the sd card
is dead..) worked fine by running node-red with pm2.

**Comment by wallet77** [comment]
I've just tested with a fresh installation of node-red and it works with a simple 
`pm2 start node-red`

**Comment by JBX028** [comment]
Thanks again for your input. I never tried with a simple pm2 start node-red because the doc indicates to add -- -v at the end...
I will try this evening :)

**Comment by JBX028** [comment]
Hi,
works fine with pm2 start node-red
not sure why everywhere it is referenced to add -- -v at the end and also why it worked with my old pi but anyway the most important is that node-red can be started this way and is automatically started after a reboot (pm2 save & startup).
Thanks a lot for your help
