### ISSUE TITLE
Use ssh ProxyCommand in ssh_options of deploy config

### ISSUE THREAD

**Issue by khmelevskii** [Unitech/pm2#3862]
Hi. How I can use `ProxyCommand` in `ssh_options`:
```
        dev: {
            user: 'user',
            host: 'innersetrver',
            ref: 'origin/dev',
            repo: 'git@github.com:repo/repo',
            path: '/home/webdev/repo',
            ssh_options: ['ProxyCommand ssh -q -W %h:%p test@jmp.testsite.com'],
        },
```
I get an error
```
command-line line 0: Missing argument.

  fetch failed
```

but ssh command works fine
`ssh -o 'ProxyCommand ssh -q -W %h:%p test@jmp.testsite.com' user@innersetrver`

**Comment by rohit-gohri** [comment]
Anyone found a solution for this?

**Comment by prusswan** [comment]
Those single quotes will be truncated when the command is assembled in https://github.com/Unitech/pm2-deploy/blob/master/deploy. I can't get it work with any kind of escaping, the ProxyCommand option only works in `~/.ssh/config`

**Comment by rohit-gohri** [comment]
This is still an issue as far as I know

**Comment by StephanHoyer** [comment]
we do it via ssh
```
ssh -A proxyUser@proxyHost 'pm2 deploy ...'
```
Agent forwarding has to work of cause and `pm2` has to be accessible on the proxy.

Maybe this helps anyone.

**Comment by oyecomowa** [comment]
There's a better way. Setup a ssh tunnel through a jump host on your machine.
