### ISSUE TITLE
Headless daemon not being spawned

### ISSUE THREAD

**Issue by blake-edwards** [Unitech/pm2#3864]
## What's going wrong?
When using 'pm2 start hello.js', pm2 hangs and does not create a headless process displaying the app name, id, etc.
## How could we reproduce this issue?
Ubuntu 16.04.3 LTS
Node v4.2.6
pm2 3.0.3

hello.js contents:
```
#!/usr/bin/env nodejs
var http = require('http');
http.createServer(function (req, res) {
  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.end('Hello World\n');
}).listen(8080, 'localhost');
console.log('Server running at http://localhost:8080/');
```
hello.js running normally:
```
$ node hello.js 
Server running at http://localhost:8080/

$ curl localhost:8080
Hello World
```

Run this to reproduce:
```
$ pm2 start hello.js
```

## Supporting information
The output looks like this:
```
$ pm2 start hello.js 
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
[PM2] Starting /root/node/helloworld/hello.js in fork_mode (1 instance)
[PM2] Done.
```

Here is the output of running 'pm2 list' in a different terminal, while other terminal runs:

```
$ pm2 list
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
┌──────┬──────┬────────┬───┬─────┬────────┐
│ Name │ mode │ status │ ↺ │ cpu │ memory │
└──────┴──────┴────────┴───┴─────┴────────┘
 Use `pm2 show <id|name>` to get more details about an app
```

**Comment by wallet77** [comment]
Hi @blake-edwards 

Could you try `pm2 start hello.js --no-pmx` ?

**Comment by blake-edwards** [comment]
Hi @wallet77 

I tried this and it still did not work.. Anything else I can try?

**Comment by wallet77** [comment]
@blake-edwards 

Ok I assumed it was because of apm because when I test your code on node 4 it seems we had a bug (fixed) in @pm2/io.

Could you try to completely kill pm2 and agent then try to reinstall pm2 ?
```
pm2 kill
sudo npm remove pm2 -g
sudo npm install pm2@latest -g
```

Another remark : your issue is really close to this one : https://github.com/Unitech/pm2/issues/3766
As you can see node version seems to be in question and it's the same as yours (node4).

Could you try to update node version ?

**Comment by blake-edwards** [comment]
@wallet77  Your fix worked. Thank you so much. :D

**Comment by wallet77** [comment]
You're welcome.

**Comment by shiqihennuan** [comment]
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2

**Comment by shiqihennuan** [comment]
why?
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
