### ISSUE TITLE
pm2 dies when node process memory gets too high

### ISSUE THREAD

**Issue by zhangartist** [Unitech/pm2#3866]
If a NodeJS process' memory climbs too fast, and exceeds the computer's memory, ubuntu insta-kills PM2 with OOM (out of memory). And all the processes PM2 is monitoring gets killed as well.

Therefore PM2 dies and Node processes remain dead forever. Is there a solution to this?

**Comment by wallet77** [comment]
Hi @zhangartist 

It's look like the expected behavior.
The only way to ensure pm2 is alive in any case should be to create a cron task or any other watchdog solution.

It's not possible to catch OOM error : https://github.com/nodejs/help/issues/1026

**Comment by vmarchaud** [comment]
You can use `pm2 startup` to hook pm2 to your service manager, it should restart it even after OOM.
