### ISSUE TITLE
PM2 install Freenas not working

### ISSUE THREAD

**Issue by tonyschuite** [Unitech/pm2#3868]
## What's going wrong?
when installing on Freenas 11 jail, npm throws the following error:

`root@HomeBridge:/ # npm install -g pm2
npm ERR! code Z_DATA_ERROR
npm ERR! errno Z_DATA_ERROR
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/@pm2%2fio: invalid distance too far back

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-17T18_40_34_617Z-debug.log
`

## How could we reproduce this issue?
clean Jail on Freenas 11
pkg update && pkg upgrade
pkg install -y node npm dbus avahi-libdns gcc
sysrc dbus_enable="YES"
sysrc avahi_daemon_enable="YES"
ln -s /usr/local/include/avahi-compat-libdns_sd/dns_sd.h /usr/include/dns_sd.h
service dbus start
service avahi-daemon start

npm install -g pm2

(also tried adding the flags "@latest", "--unsafe-perm=true", "--allow-root")

**Comment by wallet77** [comment]
Hi @tonyschuite 

Could you send us the output of following commands ?
```
npm -v
node -v
```
