### ISSUE TITLE
pm2 IPC api can not work

### ISSUE THREAD

**Issue by ProfutW** [Unitech/pm2#3870]
I use the pm2 api pm2.launchBus to get the obj 'bus', and add a listener to it.Then I start a pm2 process to send msg to the parent process.However, the listener can not catch anything from the child process.
The code I use is the same as the official doc shows:
```
//parent.js
const pm2 = require('pm2');

pm2.connect(() => {
  pm2.launchBus((err, bus) => {
    if (err) console.error(err);
    bus.on('process:msg', (packet) => {
      console.log(packet.data);
    })
  })
  pm2.sendDataToProcessId({
    type: 'process:msg',
    data: {
      some: 'data',
      hello: true
    },
    id: 0,
    topic: 'some topic'
  }, (err, res) => {
    if (err) console.error(err);
    console.log(res);
  })
})

//child.js
process.on('message', (packet) => {
  console.log(packet.data);
  process.send({
    type: 'process:msg',
    data: {
      msg: 'test'
    }
  });
});
```
I first use 'pm2 start child.js' to start a process, then I use command 'node parent.js', log is here:
```
{ success: true,
  data: 
   { type: 'process:msg',
     data: { some: 'data', hello: true },
     id: 0,
     topic: 'some topic' } }
```
pm2 log shows:
```
0|pm2IPC.t | { some: 'data', hello: true }
```
The child process can get data from the parent, but the parent process can not, why?

pm2 version: 2.9.1
node version: 8.9.4
OS: Linux version 3.10.0-693.el7.x86_64 (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) )

**Comment by wallet77** [comment]
Hi @ProfutW 

I've just tested and it works fine.
Copy/paste of your code.
Node : 8.9.4
pm2: 3.0.3

**Comment by ProfutW** [comment]
@wallet77  Thanks. I've tested on another server,and it works...So weird.Maybe I need to reinstall pm2 or reboot my server.

**Comment by wallet77** [comment]
Maybe, or you can just try to delete apps and restart them : 

```
pm2 delete all
pm2 start child.js
```
