### ISSUE TITLE
Environment variable for instance number

### ISSUE THREAD

**Issue by ronag** [Unitech/pm2#3875]
I need an instance number which are randomly assigned from a bucket of [0...instances], i.e. the instance id is not enough.

Usually in a dev setup I will have e.g. 4 instances each of which will connect to 1 of 4 drive mounts, it doesn't matter which one they connect to as long as they all connect to different mounts specified in an array of 4 items.

**Comment by wallet77** [comment]
Hi @ronag 

I'm not sure to understand what you want to achieve but environment variables can't be managed by instance.
More exactly not by pm2. PM2 can set environment variable by app and environment only.

Then, in each instance, you can manage environment variable by yourself in runtime.

**Comment by ronag** [comment]
I want PM2 to set an environment variable "pm_instance_index" or something.

**Comment by wallet77** [comment]
So why not using `console.log(process.env.pm_id);` ? Why it's not enough ?

**Comment by ronag** [comment]
I need to be able to map the e.g. 4 mounts uniquely to each instance. If you just hash the `pm_id` I can end up with two instances trying to use the same mount.

**Comment by wallet77** [comment]
If you can't use pm_id or unique_id then the only way is to generate configuration and set an environment variable to specify the drive mounts.
But pm2 doesn't have such built-in feature.
