### ISSUE TITLE
PM2 error: Error: Error: spawn ps ENOENT

### ISSUE THREAD

**Issue by harlentan** [Unitech/pm2#3879]
pm2 version: 3.0.4
macOS High Sierra:10.13.2

after pm2 startup, the pm2 logs will who the error below every few seconds:
```
 PM2 error: Error: Error: spawn ps ENOENT
```

But the `ps` command is available  either from the sudo user or the current user

**Comment by harlentan** [comment]
If I do not use the pm2 startup, everything is all right.

**Comment by flohdot** [comment]
We had a similar problem with 3.0.3. `exec(df -k $someDir)` would fail with `no such file or directory`. Running the same script without pm2 did not result in this error.

**Comment by Unitech** [comment]
@heretogo @flohdot are you on mac os also?

**Comment by heretogo** [comment]
No, we are using Debian on EC2.

**Comment by BranndonWork** [comment]
I'm on a mac and having this issue also. For me I believe it has to due with user permissions. My `/usr/local` has been chowned by my account's `user:group` and not root, which PM2 may have been installed as.

If it's a permissions error, other than changing some ownership back to root, how should we go about fixing it?

**Comment by harlentan** [comment]
Any updating about this issue @Unitech

**Comment by soyuka** [comment]
Can you try that you indeed have access to the `ps` binary? It's mandatory on osx to retrieve process usage data.

**Comment by vyacheslav-lonschakov** [comment]
The error is gone after adding PATH variable from my user to "/Users/**_User_**/Library/LaunchAgents/pm2.**_user_**.plist" file
