### ISSUE TITLE
Pm2 doesn't start services with SELinux enabled (permissive or enforcing) in ports below 1024

### ISSUE THREAD

**Issue by q2dg** [Unitech/pm2#388]
I suppose you already know this, but I tell you just in case...

I wanted to bind the port 80 to my app running with a regular user, so I executed the _setcap cap_net_bind_service=+ep /usr/bin/node_ command without errors (I run Fedora 20). Starting my app with regular _node_ command was ok, but doing it with _pm2 start_ command gave me a **EACCESS** error. So, I thought this problem could be something related to SELinux. And it is: if I put _SELinux=Disabled_ in _/etc/selinux/config_ and I reboot, _pm2 start_ works ok. I think this is a little backward.

Thanks.

**Comment by cyqsimon** [comment]
Seriously guys. You need a spam bot to counter this stale bot.
