### ISSUE TITLE
ANSI escape code not working after updated to PM2 v3

### ISSUE THREAD

**Issue by nammaianh** [Unitech/pm2#3884]
I'm using PM2 v3.0.4 on OS X. I run `pm list --watch` but some ANSI code is not processed.

![image](https://user-images.githubusercontent.com/9427046/44765038-0b153100-ab7d-11e8-947a-f05d7c4d16a8.png)

**Comment by Unitech** [comment]
Available in PM2 4.1.0

```bash
npm install pm2@latest -g
pm2 update
```
