### ISSUE TITLE
Load Distribution is not proper. I

### ISSUE THREAD

**Issue by upardhi** [Unitech/pm2#3890]
Clustering is not working properly. If you try to run multiple requests, a load of the processor is not taking the proper load. It shows the load is only one core

Step to regenerate. Run this command in cmd on windows.
curl -s "http://localhost:3000?[1-100000]"

run ps list

![2018-09-01_141822](https://user-images.githubusercontent.com/6356988/44944342-a19e5800-adf2-11e8-91c6-7c861cef3ecb.png)

```
$ pm2 report
```

**Comment by wallet77** [comment]
Duplicate : https://github.com/Unitech/pm2/issues/3815
