### ISSUE TITLE
pm2 directory lack three package.json

### ISSUE THREAD

**Issue by banbantx** [Unitech/pm2#3891]
## What's going wrong?
when installed pm2 In mac ,  if you use 'npm list -g --depth 0' in terminal, you will find three error infos.
1.error: no such file or directory: lib/node_modules/pm2/node_modules/_@pm2_agent@0.5.13@@pm2/package.json;

2.error: no such file or directory: lib/node_modules/pm2/node_modules/_@pm2_io@2.1.3@@pm2/package.json;

3.error: no such file or directory: lib/node_modules/pm2/node_modules/_@pm2_js-api@0.5.24@@pm2/package.json;

## How could we reproduce this issue?

this issue must be happen. if you have installed pm2.

## Supporting information
my os env:
node: v8.11.4
mac_os: version 10.13.6

i think this issue has no relation with my env;  the reason may be is the dependency of pm2 lacking of package.json file. 

```
$ pm2 report
```

arch                 : x64
platform             : darwin
type                 : Darwin
cpus                 : Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
cpus nb              : 8
freemem              : 6602473472
totalmem             : 17179869184

**Comment by wallet77** [comment]
Hi @526142399 

I can't reproduce on Ubuntu 18.04.
Maybe it occurs only on mac.

**Comment by 526142399** [comment]
yes. It can't  be reproduced on Ubuntu os.
