### ISSUE TITLE
@pm2/io@~2.3.9 doesn't exists

### ISSUE THREAD

**Issue by manikumarrepuri** [Unitech/pm2#3902]
## What's going wrong?

Updated to the latest version of pm2, but it gives an error for @pm2/io@~2.3.9 doesn't exists

Checked the pm2/io npm package. There is no such version. They have the following versions.

2.1.0, 2.3.10, 2.3.11

## Supporting information

```
$ pm2 report
```

**Comment by wallet77** [comment]
It should work with pm2 3.1.2

```
$ npm install pm2@latest -g
$ pm2 update
```

**Comment by manikumarrepuri** [comment]
Appreciate it.

**Comment by manikumarrepuri** [comment]
This still does not resolve @pm2/io package automatically. Still referring a version 2.3.9, somehow this version does not exists.

**Comment by wallet77** [comment]
It's probably a cache issue with npm.
Pm2 now specify version 2.3.11

**Comment by manikumarrepuri** [comment]
Couldn't find any versions for "@pm2/io" that matches "~2.3.11"

**Comment by wallet77** [comment]
2.3.11 is the latest : https://www.npmjs.com/package/@pm2/io

**Comment by manikumarrepuri** [comment]
![image](https://user-images.githubusercontent.com/20675532/45309565-db224200-b51b-11e8-97b0-c94d112640cb.png)

The latest it has is 2.1.2.
Not sure why 2.3.9 and 2.3.11 is not showing here. Probably are they apm versions?. 

Pinning 2.1.2 would fix this issue. If you just try installing specific version of @pm2/io@2.3.11. Probably you will get an idea what I am talking about.

Thanks for the prompt response.

**Comment by manikumarrepuri** [comment]
2.3.9, 2.3.11 versions are not available. the only latest version it has is 2.1.2.  You could try installing, see if it installs either of 2.3.9 or 2.3.11. Or just say npm install @pm2/io@latest. It would install 2.1.2.

**Comment by Unitech** [comment]
```
