### ISSUE TITLE
Not getting process 'message' event on gracefulReload

### ISSUE THREAD

**Issue by paulshapiro** [Unitech/pm2#391]
Hey,

I've been wrapping up process cleanup, and started by using SIGTERMs. As they seem not to be compatible*\* with pm2, I moved to testing pm2 gracefulReload. But the problem is, my cluster children do not seem to have their callback for the 'message' event called.

```
process.on('message', function(msg) 
{
    console.log("pid " + process.pid + ": got process 'message' ", msg)
    if (msg == 'shutdown') {
        log.info("pid " + process.pid + ": Shutdown message received.")
        server.graceful_exit();
    } else {
        log.warn("pid " + process.pid + ": Got an unrecognized process message:", msg);
    }
});
```

Am I doing anything wrong? Really unsure as to why it's not working!

   *\* The processes receive an error 'channel closed' at ChildProcess.target.send when I use SIGTERM with pm2.

**Comment by elvis-macak** [comment]
Also meet the same problem,
with nodejs 0.12.7, pm2 0.14.5

the same code with you, also use the process to listen on `message`, but still cann't be called.
and I read the pm2 code and found it does send a `message` event. I'm not sure why does it happend.

did you solve this problem at last ?  thx
