### ISSUE TITLE
Intercept Incoming Request Before Dispatch to Forked Workers

### ISSUE THREAD

**Issue by crh3675** [Unitech/pm2#3920]
I need to intercept all incoming requests before PM2 dispatches them to enforce abuse monitoring software,  How do I do this?

Example:
Client makes 300 connections to my services.  I need to enforce throttling of their usage before any child workers actually do anything.

I would love to do something like:

`pm2 start app.js -i 0 --interceptor=/apps/middleware/abusemonitor.js`

Whereas abusemonitor.js exports a single function that gets called before anything is dispatched so that I can control incoming traffic.

**Comment by wallet77** [comment]
Hi @crh3675 

There is no such feature in PM2.
But if you want to control traffic you can do it into workers.

**Comment by crh3675** [comment]
I guess the problem for me is the asynchronous nature of NodeJS and using Redis as a cache.  If that many connections come it concurrently and it takes 10ms to set a Redis cache, it is the case that the "flood" will be allowed by the workers until that cache has been set.  At that point, it would be too late as that level of access would eat up all of the CPU and halt the system entirely.

If you have any creative ideas around this, I would appreciate it!
