### ISSUE TITLE
 Error: 404 Not Found: @pm2/io@~2.3.11

### ISSUE THREAD

**Issue by sharabiania** [Unitech/pm2#3929]
When trying to install `npm install pm2 -g` I I get the following error:

> npm ERR! code E404
npm ERR! 404 Not Found: @pm2/io@~2.3.11
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\asharabiani\AppData\Roaming\npm-cache\_logs\2018-09-27T14_50_35_791Z-debug.log
- My node version: v8.10.0
- nmp version 6.4.1
- `npm cache clean --force` did not solve the issue.

Part of the log file that indicates the error stack:
>115 verbose stack Error: 404 Not Found: @pm2/io@~2.3.11
115 verbose stack     at fetch.then.res (C:\Users\asharabiani\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
115 verbose stack     at tryCatcher (C:\Users\asharabiani\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
115 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\asharabiani\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
115 verbose stack     at Promise._settlePromise (C:\Users\asharabiani\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
115 verbose stack     at Promise._settlePromise0 (C:\Users\asharabiani\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
115 verbose stack     at Promise._settlePromises (C:\Users\asharabiani\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
115 verbose stack     at Async._drainQueue (C:\Users\asharabiani\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
115 verbose stack     at Async._drainQueues (C:\Users\asharabiani\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
115 verbose stack     at Immediate.Async.drainQueues (C:\Users\asharabiani\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
115 verbose stack     at runCallback (timers.js:794:20)
115 verbose stack     at tryOnImmediate (timers.js:752:5)
115 verbose stack     at processImmediate [as _immediateCallback] (timers.js:729:5)

**Comment by Unitech** [comment]
Can you try:

```
cd /tmp
npm install @pm2/io
```

**Comment by sharabiania** [comment]
> Can you try:
> 
> ```
> cd /tmp
> npm install @pm2/io
> ```
> And tell me the results

Same error! 
- Created a `tmp` folder.
- `cd  tmp`
- `npm install @pm2` (without `-g`)
 the log file:
>0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\asharabiani\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '@pm2/io' ]
2 info using npm@6.4.1
3 info using node@v8.10.0
4 verbose npm-session ec15c179dc57419f
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/@pm2%2fio 433ms
8 silly fetchPackageMetaData error for @pm2/io@latest 404 Not Found: @pm2/io@latest
9 timing stage:rollbackFailedOptional Completed in 0ms
10 timing stage:runTopLevelLifecycles Completed in 667ms
11 verbose stack Error: 404 Not Found: @pm2/io@latest
11 verbose stack     at fetch.then.res (C:\Users\asharabiani\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
11 verbose stack     at tryCatcher (C:\Users\asharabiani\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\asharabiani\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
11 verbose stack     at Promise._settlePromise (C:\Users\asharabiani\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (C:\Users\asharabiani\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
11 verbose stack     at Promise._settlePromises (C:\Users\asharabiani\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
11 verbose stack     at Async._drainQueue (C:\Users\asharabiani\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
11 verbose stack     at Async._drainQueues (C:\Users\asharabiani\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
11 verbose stack     at Immediate.Async.drainQueues (C:\Users\asharabiani\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
11 verbose stack     at runCallback (timers.js:794:20)
11 verbose stack     at tryOnImmediate (timers.js:752:5)
11 verbose stack     at processImmediate [as _immediateCallback] (timers.js:729:5)
12 verbose cwd C:\Users\asharabiani\Google Drive\sagomini\build-number
13 verbose Windows_NT 10.0.10586
14 verbose argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\asharabiani\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "@pm2/io"
15 verbose node v8.10.0
16 verbose npm  v6.4.1
17 error code E404
18 error 404 Not Found: @pm2/io@latest
19 verbose exit [ 1, true ]

**Comment by MarvinVk** [comment]
I have the same issue. 
The only way I know how to solve this is to install an earlier version `npm install pm2@2.10.4 -g`

**Comment by mlstoppa** [comment]
Same issue with a different module.
I successfully installed pm2 on my Windows machine, then after a few minutes I did the same on a freebsd server and got this error:

```
[bsdsrv]:ld-general-purpose# npm install -g pm2
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@pm2%2fagent - Not found
npm ERR! 404
npm ERR! 404  '@pm2/agent@~1.0.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'pm2'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-06T09_39_59_446Z-debug.log
```

I did many tries so far: clean the cache, remove node_modules directory and installed each module separately, but I always got this error.
How can I avoid it?
Thank you

**Comment by orange1337** [comment]
have the same issue

**Comment by orange1337** [comment]
probably npm is dead

**Comment by mlstoppa** [comment]
I had to get back to pm2@2.10.4 to have it installed as a previous user, do you really think npm is down?

**Comment by bubsly** [comment]
https://status.npmjs.org/ shows a partial outage at the moment. @mlstoppa @orange1337

**Comment by mlstoppa** [comment]
@bubsly Thank you very much, I didn't know I could have checked it by myself. I've just tried again the installation with the latest version of the module and it worked fine.
