### ISSUE TITLE
High CPU Usage.

### ISSUE THREAD

**Issue by WALNUTZGAMING** [Unitech/pm2#3936]
![capture](https://user-images.githubusercontent.com/38658663/46351583-4af29b00-c68a-11e8-996e-fb737085e45c.PNG)

_Originally posted by @WALNUTZGAMING in https://github.com/Unitech/pm2/issue_comments#issuecomment-426273926_

**Comment by WALNUTZGAMING** [comment]
Hey, I am having the same issues with the CPU but the memory seems fine. The WMI Provider Host CPU usage jumps is when I use PM2 when I use NodeJS "node index,js" the Provider Host is around 10% CPU Usage, What can I do to fix this?

**Comment by Unitech** [comment]
Try out the upcoming version:

```
$ npm install Unitech/pm2#development -g
$ pm2 update
```

You will see a decrease of CPU usage by 60%

**Comment by Unitech** [comment]
Could you try with the latest version of PM2 (3.2.0):

```bash
$ npm install pm2 -g
$ pm2 update
```

Blog post: https://blog.pm2.io/pm2-runtime-3-2-autumn-features/
Changelog: https://github.com/Unitech/pm2/releases/tag/3.2.0
