### ISSUE TITLE
[QUESTION] How to start multiple apps sequentially?

### ISSUE THREAD

**Issue by xyboox** [Unitech/pm2#3947]
So I have my main app and a few micro-services running on the same server. What I'd like to be able to do is to start sequentially the microservices, one after the other, if possible each started after the prev. sends some acknowledgement signal and the last being the main app ( in cluster mode ). I'm using the ecosystem.config.js file and I've tried with wait_ready but seems like as soon as the first app send the "ready" message, all the other are receiving it and starting. Is there a way to start them one after the other? Thanks!

**Comment by wallet77** [comment]
I think what you need is closed to this PR : https://github.com/Unitech/pm2/pull/3789
It has not been merged yet, but you can upvote this PR.

**Comment by xyboox** [comment]
Thanks @wallet77 !
