### ISSUE TITLE
All apps lost after "pm2 kill"

### ISSUE THREAD

**Issue by alexandernst** [Unitech/pm2#395]
I had a few apps running inside PM2. Then something weird happened and `pm2 restart <id>` wasn't working exactly the way I wanted, so I did `pm2 kill`.

Only after I ran that command and then `pm2 list` I realized that all the apps  were gone and I had to add them again, one by one. 

Is that the expected behaviour? Isn't there a way I can make PM2 save the apps I'm running and restore then after a `pm2 kill`?

**Comment by stratocode** [comment]
this sucks
