### ISSUE TITLE
Maybe a more compatible `pm2 package`?

### ISSUE THREAD

**Issue by poppinlp** [Unitech/pm2#3951]
The `pm2 package` command use `transform` argument for `tar` which is a difference between BSD tar and GNU tar.

This will make an error when there's a BSD tar in user system. And the macOS use BSD tar by default (at least in my mac). Although we could install GNU tar by self. But maybe it's a better way to have a more compatible `pm2 package` command? :)

**Comment by Unitech** [comment]
Hey @poppinlp, I see you've dig a bit on that bleeding new feature ;)

So yes I've developed the command based on the Ubuntu's tar (GNU tar 1.29):

```bash
tar zcf ${target_fullpath} -C ${base_folder} --transform 's,${module_folder_name},module,' ${module_folder_name}
```

Have you any clue on how to adapt this command with the BSD's tar?

**Comment by poppinlp** [comment]
OK. I'll make a test tonight or maybe a PR. :)
