### ISSUE TITLE
PM2 is not a recognized command

### ISSUE THREAD

**Issue by dutchvanderlinde** [Unitech/pm2#3964]
## What's going wrong?
So, I basically installed PM2 globally on my server, which is windows. Using `npm install pm2 -g`. I tried running it and it basically said `pm2 is not a valid command`. I don't know what to do, the command line is ran as Administrator and NODE/NPM is both in the path

## Supporting information

```
$ pm2 report
```

^^ doesn't work because PM2 isn't a recognized command.

**Comment by Eugenio161288** [comment]
I catch the same issue here.
pm2 isntalled globally on my machine. 

Environment:

OS: Windows 10
Node: 10.9.0

I saw few issues like that and it was mentioned there are issues on windows, but documentation says: "Works on Linux (stable) & macOS (stable) & Windows (stable). All Node.js versions are supported starting Node.js 4.X." 

Is there any chance it works on Windows without issues? 

Could someone help with that?

**Comment by Unitech** [comment]
Try to install mocha for example `npm install mocha -g` and let me know if you can use the mocha cli from your windows terminal.
We've tried it again here, global installation (hopefully...) works as expected

**Comment by Unitech** [comment]
Also try `Get-Command pm2` and lmk

**Comment by Eugenio161288** [comment]
Get-Command pm2 returns the following:

![image](https://user-images.githubusercontent.com/14542827/49994071-8f0eef80-ff99-11e8-9fdc-755c4dbe42d9.png)

Does it wrong with installation of pm2 on my environment?

**Comment by Unitech** [comment]
So this is not an issue related to pm2, make sure you've updated node/npm else open an issue on npm

**Comment by JustinW47** [comment]
I implemented workflow for deploy, but it shows below error while deploying it.
![Uploading Annotation 2024-08-22 170322.png…]()

**Comment by JustinW47** [comment]
`-bash: line 4: pm2: command not found
-bash: line 5: pm2: command not found
Error: Process completed with exit code 127.`
