### ISSUE TITLE
pm2 save node's output in a wrong file

### ISSUE THREAD

**Issue by phantom9999** [Unitech/pm2#3968]
when I use this config
```
{
    "apps": [
        {
            "name": "docx",
            "script": "./node_modules/node-docx/index.js",
            "args": "conf/server.json",
            "interpreter_args": "--trace_gc",
            "watch": false,
            "exec_mode": "cluster",
            "instances": 4,
            "error_file" : "log/err.log",
            "out_file" : "log/out.log",
            "log_date_format": "YYYY-MM-DD HH:mm Z",
            "combine_logs": false
        }
    ]
}
```
and start with cmd:
```
pm2 start conf/pm2.json
```
the output(gc log) should be saved in log/out.log, but in fact it is saved in ${USER}/.pm2/pm2.log
is it a bug???

here is the environment
- centos 7
- node 10.x
- pm2 3.1.3

**Comment by Karrade** [comment]
Having the same issue as seen in https://github.com/Unitech/pm2/issues/4735

**Comment by sathiz1993** [comment]
Same issue

Trying to start the pm2 process in the npm script. Logs are writing in pm2.log file

**System Specfication**
- ubuntu 18.04
- pm2 4.4
- node 10.20.1
- nextjs
 
Command used to initiate the pm2 process

```
pm2 start npm --name "appname" -i max -- start --watch
```
