### ISSUE TITLE
Dos not create memory snopshot file

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [Unitech/pm2#3988]
I am tring to create memory snapshot followed by instructions. However after running pm2 snapshot i got success message with file location but file is not there.

![image](https://user-images.githubusercontent.com/3918999/47554928-dc140500-d90a-11e8-9450-51ed6b459638.png)

## Supporting information

===============================================================================
--- PM2 REPORT (Fri Oct 26 2018 10:35:57 GMT+0200 (Central European Summer Time))
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.0.4
node version         : 10.10.0
node path            : not found
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\vytautas.pranskunas\AppData\Roaming\npm\node_modules\pm2\lib\Daemon.js
argv0                : node
user                 : undefined
uid                  : N/A
gid                  : N/A
uptime               : 15min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.0.4
node version         : 10.10.0
node path            : not found
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\vytautas.pranskunas\AppData\Roaming\npm\node_modules\pm2\bin\pm2,report
argv0                : node
user                 : vytautas.pranskunas
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : win32
type                 : Windows_NT
cpus                 : Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
cpus nb              : 8
freemem              : 6485909504
totalmem             : 17008504832
home                 : C:\Users\vytautas.pranskunas
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────┬────────────┬─────────────────────┬──────────┐
│ App name │ id │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem        │ user                │ watching │
├──────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────┼────────────┼─────────────────────┼──────────┤
│ server   │ 0  │ fork │ 22728 │ online │ 0       │ 15m    │ 0%  │ 100.8 MB   │ vytautas.pranskunas │ disabled │
└──────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────┴────────────┴─────────────────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
C:\Users\vytautas.pranskunas\.pm2\pm2.log last 20 lines:
PM2        | [2018-10-26T10:20:17.166Z] PM2 log: App [server] with id [0] and pid [20568], exited with code [1] via signal [SIGINT]
PM2        | [2018-10-26T10:20:17.245Z] PM2 log: pid=20568 msg=process killed
PM2        | [2018-10-26T10:20:17.376Z] PM2 log: PM2 successfully stopped
PM2        | [2018-10-26T10:20:21.913Z] PM2 log: ===============================================================================
PM2        | [2018-10-26T10:20:21.917Z] PM2 log: --- New PM2 Daemon started ----------------------------------------------------
PM2        | [2018-10-26T10:20:21.918Z] PM2 log: Time                 : Fri Oct 26 2018 10:20:21 GMT+0200 (Central European Summer Time)
PM2        | [2018-10-26T10:20:21.918Z] PM2 log: PM2 version          : 3.0.4
PM2        | [2018-10-26T10:20:21.918Z] PM2 log: Node.js version      : 10.10.0
PM2        | [2018-10-26T10:20:21.919Z] PM2 log: Current arch         : x64
PM2        | [2018-10-26T10:20:21.919Z] PM2 log: PM2 home             : C:\Users\vytautas.pranskunas\.pm2
PM2        | [2018-10-26T10:20:21.919Z] PM2 log: PM2 PID file         : C:\Users\vytautas.pranskunas\.pm2\pm2.pid
PM2        | [2018-10-26T10:20:21.919Z] PM2 log: RPC socket file      : \\.\pipe\rpc.sock
PM2        | [2018-10-26T10:20:21.919Z] PM2 log: BUS socket file      : \\.\pipe\pub.sock
PM2        | [2018-10-26T10:20:21.919Z] PM2 log: Application log path : C:\Users\vytautas.pranskunas\.pm2\logs
PM2        | [2018-10-26T10:20:21.919Z] PM2 log: Process dump file    : C:\Users\vytautas.pranskunas\.pm2\dump.pm2
PM2        | [2018-10-26T10:20:21.920Z] PM2 log: Concurrent actions   : 2
PM2        | [2018-10-26T10:20:21.920Z] PM2 log: SIGTERM timeout      : 1600
PM2        | [2018-10-26T10:20:21.920Z] PM2 log: ===============================================================================
PM2        | [2018-10-26T10:20:22.628Z] PM2 log: Starting execution sequence in -fork mode- for app name:server id:0
PM2        | [2018-10-26T10:20:22.638Z] PM2 log: App name:server id:0 online

**Comment by Unitech** [comment]
This is not a public feature, it is to dump pm2 memory not your application :)
