### ISSUE TITLE
`pm2 profile start` is not working(node 10.12.0 && pm2 3.2.2)

### ISSUE THREAD

**Issue by mopduan** [Unitech/pm2#3989]
## What's going wrong?
      `pm2 profile start` is not working.
## How could we reproduce this issue?
      run command `pm2 profile start`
## Supporting information
      node 10.12.0
      pm2 3.2.2

PS: I found the two functions `startProfilingPM2 && stopProfilingPM2 `  in pm2/lib/Daemon.js is not modify for inspector of Node.js v10.x.

Hope your reply! 
Thanks a lot!

**Comment by Unitech** [comment]
These commands are not documented because they are not usable, they are used internally to debug pm2. Check [pm2 plus](https://pm2.io/plus/) to get these commands working via web ui, best
