### ISSUE TITLE
[PM2][WARN] Expect "uid" to be a typeof [object Number], but now is [object String]

### ISSUE THREAD

**Issue by PandaTsui** [Unitech/pm2#3999]
## How could we reproduce this issue?
An error is as follows:
![image](https://user-images.githubusercontent.com/21979377/47830107-65bd4a00-ddc5-11e8-9c84-f9f800fca101.png)

## Supporting information
my pm2 version that is v3.2.2.

```
$ pm2 report
```
![image](https://user-images.githubusercontent.com/21979377/47830214-e4b28280-ddc5-11e8-8bc6-41ba2c0079e8.png)

**Comment by tsujp** [comment]
This is an issue on any pm2 version above 3.1.3. On a completely vanilla install, for example `npm i -g pm2` and then running `pm2 start --uid "user1" --gid "group1"` the error will occur @Unitech
