### ISSUE TITLE
Globally app logs

### ISSUE THREAD

**Issue by tomo92s** [Unitech/pm2#4008]
How to see the logs another user? I have discord bot and work with PM2. When i enter **pm2 logs** then i see logs my app but when i relog to another account then i dont see this logs. How to do that i see logs globally with different users in terminal?

**Comment by Unitech** [comment]
I imagine that you have one PM2 per user. So each user as an independent, isolated PM2 using the folder `/home/${USER}/.pm2`

If you want to do `pm2 logs` from one user on another you can do:  `PM2_HOME=/home/target_user/.pm2 pm2 logs` where `target_user` is the desired user running PM2.

What you could do also is to have one unique PM2 instance for all users by exporting the same PM2_HOME by default for all users. Cheers
