### ISSUE TITLE
cluster mode: restarting process doesn't reset cron_restart time

### ISSUE THREAD

**Issue by dannyarad** [Unitech/pm2#4009]
Hi

I would like the clustered processes to restart after 5 mins or when restart is invoked programmatically. Currently restarting process programmatically doesn't reset cron_restart start time which creates unwanted behaviour. Is there a solution for this?

Any suggestions would be appreciated,

Thanks

-Dan

**Comment by Unitech** [comment]
On the current public PM2 version the cron [is reset on restart](https://github.com/Unitech/pm2/blob/master/lib/ProcessContainer.js#L102)

On next release the cron job will be moved outside process: https://github.com/Unitech/pm2/pull/3944

**Comment by dannyarad** [comment]
> On the current public PM2 version the cron [is reset on restart](https://github.com/Unitech/pm2/blob/master/lib/ProcessContainer.js#L102)
> 
> On next release the cron job will be moved outside process: #3944

Thanks for replying. From what I tested running pm2 restart() on process that is timed to restart using cron doesn't reset cron_restart based on the time that restart() method was invoked on process.
