### ISSUE TITLE
App running but not working

### ISSUE THREAD

**Issue by bigdestroyer** [Unitech/pm2#4010]
I run Discord bot and its running with no issue. Problem is that the bot does not appear online or work on the Discord platform. If I manually  run it with the node command the bot is working without any issue.

### To reproduce the issue### 
1. Create a Amazon EC2 instance with Amazon Lightsail on OS only with Ubuntu 18.04 LTS.
2. Configure the firewall options in the instance network tab to allow port 80, 443, 3000 and 3001 (my app is defined on the ecosystem file to use port 3001, see below the link to the file(it was a js file but had to make txt to be able to upload))
[ecosystem.config.txt](https://github.com/Unitech/pm2/files/2574819/ecosystem.config.txt)
3. Start the apps with the ecosystem file.

*The bot is starting with a startup script that one of the community members said we should use to launch the app.js file (in my case named bot.js). I'm not to sure what it does if somebody can maybe explain. I mostly found that launching with a ecosystem file does not work. Below is the extract he tells on how to run it and it seems to be the only working way (at least on Amazon EC2 instances not Lightsail)
The startup script file is attached below (it was also a js file but had to make it txt to be able to upload)
[proxy.txt](https://github.com/Unitech/pm2/files/2574877/proxy.txt)

> Create a file named proxy.js in the same folder as bot.js and paste in
>
> `require('child_process').spawn('node',` ['bot.js'], { detached: true, stdio:[0,1,2] `});`
>
>should be able to start it via ;
>
>`pm2 start proxy.js --wait-ready --name="mybot" --log mybotlog.log --watch`
>
>--wait-ready waits for the bot to actually be ready before reporting it as online
>--watch will restart your bot on file changes ( say if you hit save in dbm )
>--name is what pm2 will put as the name of your application, useful for getting the logs with pm2 logs >[name]
>--log saves what would normally be in the console window to a file with this name

**Comment by Unitech** [comment]
can you reformat this issue and give a precise step by step way to reproduce this bug thanks

**Comment by bigdestroyer** [comment]
@Unitech I updated it, maybe it makes now bit more sense

**Comment by NafiAF** [comment]
Hello, I also use pm2 for my Discord Bot, the bot comes online but some of the features don't work like my play command to play music. When I try without pm2 it works perfectly fine.

**Comment by rjworks** [comment]
Helppo!!

**Comment by rjworks** [comment]
> Hello, I also use pm2 for my Discord Bot, the bot comes online but some of the features don't work like my play command to play music. When I try without pm2 it works perfectly fine.

Did you solve it??
