### ISSUE TITLE
SOC-2 or HIPAA Compliance?

### ISSUE THREAD

**Issue by whartonn** [Unitech/pm2#4011]
We are considering using pm2 for our Node application, but our environment must be SOC-2 compliant / HIPAA-compliant. Are you compliant with either of these?

Thank you!

**Comment by bkniffler** [comment]
I'm not too familiar with HIPAA/SOC-2, but aren't those related to servers? pm2 is 'just' a process manager.

**Comment by Unitech** [comment]
Check the page https://pm2.io/enterprise/ or contact us directly via the contact page
