### ISSUE TITLE
Cluster mode with option -1 is not working in v3.2.2

### ISSUE THREAD

**Issue by minimorph223** [Unitech/pm2#4012]
## What's going wrong?
Previously, we are using pm2 with cluster mode by -i -1 (means max cpu -1 ) and it worked in V3.1.3;
After upgrade to V3.2.2, the server started as fork mode. 
`Starting /src/bin/server in fork_mode (-1 instance)`

## How could we reproduce this issue?
just add option -i -1 when start
I tested -i max or -i [positive number] works good.

## Supporting information
pm2d version         : 3.2.2
node version         : 6.14.4
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : undefined
uid                  : 0
gid                  : 0
uptime               : 0min
![image](https://user-images.githubusercontent.com/6702159/48173540-22bc2300-e33f-11e8-80f4-b2a547edcc44.png)

![image](https://user-images.githubusercontent.com/6702159/48173372-71b58880-e33e-11e8-8b6b-77b945431bab.png)

**Comment by Unitech** [comment]
thanks for reporting, bug confirmed and fixed
