### ISSUE TITLE
Any way to get how much memory pm2 processes take w/o format to MB, GB etc? just raw bytes

### ISSUE THREAD

**Issue by liesislukas** [Unitech/pm2#4014]
I'm tracking a lot of stuff with [trafikito.com](https://trafikito.com/) and it allows to track output of any command. I use pm2 to run my nodejs scripts and would like to have then monitored in same dashboard of Trafikito. To make it happen i need a consistent format of output. Now when i run `pm2 list` i may get ram in MB, maybe GB or just Bytes. Can i always see raw output w/o format?

![image](https://user-images.githubusercontent.com/2733862/48253554-384d4d80-e410-11e8-9de2-0d550716304a.png)

so instead of 157.3M it would show raw 19662500

**Comment by Unitech** [comment]
`pm2 prettylist`?
