### ISSUE TITLE
log file cannot work

### ISSUE THREAD

**Issue by Mr-jiangzhiguo** [Unitech/pm2#4017]
## What's going wrong2
`pm2: v3.2.3`
In docker, `Dockerfile`:
```
...
CMD [ "pm2-runtime", "start", "ecosystem.config.js", "--env","buildtest", "--error","/var/nodejs/logs/op-test/error.log", "--output","/var/nodejs/logs/op-test/output.log" ]
```

above all, I want to chang log path,but `pm2 show id`,then it still `/root/.pm2/logs/op-error.log` and `/root/.pm2/logs/op-out.log`

**Comment by zffocussss** [comment]
same here

**Comment by Mr-jiangzhiguo** [comment]
Dockerfile: 
```Dockerfile
CMD [ "pm2-runtime", "start", "./ecosystem.config.js" ]
```
ecosystem.config.js: 
```js
module.exports = {
  /**
   * Application configuration section
   * http://pm2.keymetrics.io/docs/usage/application-declaration/
   */
  apps : [
    // First application
    {
      name : 'appname',
      script : 'bin/www',
      env : {
        NODE_ENV: 'production'
      },
      output: '/var/nodejs/logs/appname/output.log',
      error: '/var/nodejs/logs/appname/error.log',
    }
  ]
};
```

**Comment by zffocussss** [comment]
pm2-runtime start dist/app/pm2.config.js --env production

**Comment by zffocussss** [comment]
module.exports = {
    apps : [{
        "name": "pm2-ginobot-server",
        "max_memory_restart": "300M",
        "script": "dist/app/index.js",
        "out_file": "logs/pm2/teams-bot-access.log",
        "error_file": "logs/pm2/teams-bot-error.log",
//        "log_date_format": "YYYY-MM-DD HH:mm:ss",
        "instances": "{instances}",
        "exec_mode": "cluster",
        "watch": false,
//        "ignore_watch": [
//            "logs"
//        ],
        "env_production": {
            "NODE_ENV": "production"
        },
        "restart_delay": "10000"
    }]
};

**Comment by Mr-jiangzhiguo** [comment]
> @Mr-jiangzhiguo 大哥，我也是只有配置的，日志都没东西啊

你自个儿进容器里面，运行`pm2`相关命令看一看呗
