### ISSUE TITLE
Python - How to make pm2 working with multiprocessing?

### ISSUE THREAD

**Issue by BarryThrill** [Unitech/pm2#4024]
So I found new issue regarding pm2 (pm2.keymetrics.io/) - So I have been trying to figure out why my scripts didn't work with pm2

(What I mean by pm2 is that whenever you run with multiprocessing it creates a python.exe and open it up separated from PM2 Dashbord like picture here https://i.stack.imgur.com/965gw.png

So the question is how can I possible make it working for Pm2 dashboard.

I made a quick little script for those who want to test it out with pm2.

```
import multiprocessing, time, os, sys, threading
from utils import Logger

Checker = ['Helloworld']
logger = Logger()  # Logger from Utils

def test(findings):
    while True:

        logger.log("ping")
        time.sleep(1)


def main():

    try:
        jobs = []
        for finding in Checker:
            p = multiprocessing.Process(target=test, args=(finding ,))
            jobs.append(p)
            p.start()


    except KeyboardInterrupt:
        print('Keyboard - Interrupted')
        sys.exit()


if __name__ == '__main__':
    try:
        main()

    except KeyboardInterrupt:
        print('Keyboard - Interrupted')
        sys.exit()

```

**Comment by guilhermegonzaga** [comment]
Have you found a solution? I'm also having this problem
