### ISSUE TITLE
Fix Google documentation links

### ISSUE THREAD

**Issue by natesilva** [Unitech/pm2#4025]
When searching for PM2 documentation on Google, most links point to old documentation. When you click the link, you get a modal that directs you to the new documentation.

Google needs to be made to index the new documentation somehow.

* The old documentation could be archived.
* The old documentation links could redirect to the new documentation instead of presenting a modal.

A typical Google search that gives old results: https://www.google.com/search?q=pm2+update+env

**Comment by vmarchaud** [comment]
@shubs
