### ISSUE TITLE
PM2 Keep opening some windows (In Loop)

### ISSUE THREAD

**Issue by Arslan007** [Unitech/pm2#4040]
I am using latest PM2 on Windows 10 Machine with node 6.10 
When I run PM2 start command then PM2 keep opening some process (Some window opens and closes itself) in loop. It keeps doing until I kill PM2.

I have attached all the logs and relevant information.

Thanks

PS C:\Users\Arslan.Pervaiz> pm2 report
[PM2] Spawning PM2 daemon with pm2_home=C:\Users\Arslan.Pervaiz\.pm2
[PM2 I/O] Using: Public key: v5n8adhvrnb9dfk | Private key: uwwp3kzea5neh86 | Machine name: CA900695-eab7
[PM2] PM2 Successfully daemonized
[PM2][Module] Starting NPM module pm2-logrotate
[PM2][WARN] Applications pm2-logrotate not running, starting...
[PM2] App [pm2-logrotate] launched (1 instances)
===============================================================================
--- PM2 REPORT (Wed Nov 21 2018 17:33:51 GMT-0700 (Mountain Standard Time)) ---
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.2.2
node version         : 6.10.0
node path            : not found
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\Arslan.Pervaiz\AppData\Roaming\npm\node_modules\pm2\lib\Daemon.js
argv0                : node
user                 : undefined
uid                  : N/A
gid                  : N/A
uptime               : 0min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.2.2
node version         : 6.10.0
node path            : not found
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\Arslan.Pervaiz\AppData\Roaming\npm\node_modules\pm2\bin\pm2,report
argv0                : node
user                 : arslan.pervaiz
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : win32
type                 : Windows_NT
cpus                 : Intel(R) Xeon(R) CPU E5-1660 0 @ 3.30GHz
cpus nb              : 12
freemem              : 26157756416
totalmem             : 34315431936
home                 : C:\Users\Arslan.Pervaiz
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬─────────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ version │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴─────────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
Module
┌───────────────┬────┬─────────┬──────┬────────┬─────────┬─────┬──────────┬────────────────┐
│ Module        │ id │ version │ pid  │ status │ restart │ cpu │ memory   │ user           │
├───────────────┼────┼─────────┼──────┼────────┼─────────┼─────┼──────────┼────────────────┤
│ pm2-logrotate │ 0  │ 2.6.0   │ 3116 │ online │ 0       │ 0%  │ 7.7 MB   │ arslan.pervaiz │
└───────────────┴────┴─────────┴──────┴────────┴─────────┴─────┴──────────┴────────────────┘
===============================================================================
--- Daemon logs --------------------------------------------
C:\Users\Arslan.Pervaiz\.pm2\pm2.log last 20 lines:
PM2        | 2018-11-21T17:32:56: PM2 log: App [pm2-logrotate:0] exited with code [1] via signal [SIGINT]
PM2        | 2018-11-21T17:32:56: PM2 log: pid=13584 msg=process killed
PM2        | 2018-11-21T17:32:56: PM2 log: PM2 successfully stopped
PM2        | 2018-11-21T17:33:49: PM2 log: ===============================================================================
PM2        | 2018-11-21T17:33:49: PM2 log: --- New PM2 Daemon started ----------------------------------------------------
PM2        | 2018-11-21T17:33:49: PM2 log: Time                 : Wed Nov 21 2018 17:33:49 GMT-0700 (Mountain Standard Time)
PM2        | 2018-11-21T17:33:49: PM2 log: PM2 version          : 3.2.2
PM2        | 2018-11-21T17:33:49: PM2 log: Node.js version      : 6.10.0
PM2        | 2018-11-21T17:33:49: PM2 log: Current arch         : x64
PM2        | 2018-11-21T17:33:49: PM2 log: PM2 home             : C:\Users\Arslan.Pervaiz\.pm2
PM2        | 2018-11-21T17:33:49: PM2 log: PM2 PID file         : C:\Users\Arslan.Pervaiz\.pm2\pm2.pid
PM2        | 2018-11-21T17:33:49: PM2 log: RPC socket file      : \\.\pipe\rpc.sock
PM2        | 2018-11-21T17:33:49: PM2 log: BUS socket file      : \\.\pipe\pub.sock
PM2        | 2018-11-21T17:33:49: PM2 log: Application log path : C:\Users\Arslan.Pervaiz\.pm2\log
[pm2.log](https://github.com/Unitech/pm2/files/2606214/pm2.log)
[app-error.log](https://github.com/Unitech/pm2/files/2606216/app-error.log)
[agent.log](https://github.com/Unitech/pm2/files/2606218/agent.log)

s
PM2        | 2018-11-21T17:33:49: PM2 log: Process dump file    : C:\Users\Arslan.Pervaiz\.pm2\dump.pm2
PM2        | 2018-11-21T17:33:49: PM2 log: Concurrent actions   : 2
PM2        | 2018-11-21T17:33:49: PM2 log: SIGTERM timeout      : 1600
PM2        | 2018-11-21T17:33:49: PM2 log: ===============================================================================
PM2        | 2018-11-21T17:33:51: PM2 log: App [pm2-logrotate:0] starting in -fork mode-
PM2        | 2018-11-21T17:33:51: PM2 log: App [pm2-logrotate:0] online

**Comment by Unitech** [comment]
Use a more recent Node.js version (>=10) to avoid having these window popping

**Comment by RezaRahmati** [comment]
> Use a more recent Node.js version (>=10) to avoid having these window popping

Same issue here, 
I am using node 10.16.3 and pm2 4.2.3

**Comment by x3rt** [comment]
Same here
Node.js v14.16.0
pm2 5.1.0

**Comment by miervaldis42** [comment]
Yoho,
I have the same issue with Node 16.15.1 and pm2 5.2.2
So, I think the issue should be reopened @Unitech

**Comment by jeandelest** [comment]
Got the same issue
Node.js v16.20.2
pm2 5.3.0

**Comment by asdiallo** [comment]
Got the same issue
Node.js v14, v16, v18 & v20
pm2 5.3.0

**Comment by Reginald-Gillespie** [comment]
Same issue on node v20.15.1, pm2 version 5.4.3. It keeps opening terminal windows in the background. Even after stopping the app 5 minutes ago windows are still randomly opening.
