### ISSUE TITLE
pm2 with pino extreme mode

### ISSUE THREAD

**Issue by ad34** [Unitech/pm2#4044]
## What's going wrong?

I m using pino logging on my project. I want to switch to extreme mode ( https://github.com/pinojs/pino/blob/master/docs/extreme.md ) 

For some reason the extreme mode is working fine without pm2 but logs are not received when node.js is run with pm2

## How could we reproduce this issue?

const pinoLib = require("pino")
const dest = dest = pinoLib.extreme()
pino = pinoLib(dest)
pino.info("Pino configured in extreme mode")

## Supporting information

I tried with 

if (process.env.pm_out_log_path){
        dest = pinoLib.extreme(process.env.pm_out_log_path)
} else {
        dest = pinoLib.extreme()
    }

but for some reason, only the first lines are received in the log file.

**Comment by poppinlp** [comment]
`pino` extreme mode will make a buffer to handle logs which means not flush them out immediately.
Do you mean this?

**Comment by squareloop1** [comment]
This is still an issue. See related https://github.com/Unitech/pm2/issues/4872
