### ISSUE TITLE
Suggestion: For cluster reload, set concurrent_actions = 1 if there are only 2 instances, so that reloads are zero-downtime as expected

### ISSUE THREAD

**Issue by CurtisBelt** [Unitech/pm2#4047]
Currently the default setting for parallel is 2:
https://github.com/Unitech/pm2/blob/58c8c89a78fcf65531a8695cf19170b64cc82de5/lib/API.js#L1240
https://github.com/Unitech/pm2/blob/91786108d71b3fc6c182750c09b494619e28b28a/constants.js#L89-L93

This poses a problem when running cluster mode with 2 instances. The expectation is that `reload` will be zero-downtime, but it's actually not because it reloads "2 at a time" which will reload all of your instances at once.

I have solved this for myself by using `pm2 reload appname --parallel 1`. I didn't find any guide out there that mentions this, so instead of trying to spread the word about `--parallel`, maybe it's more effective to just force `concurrent_actions` it to be 1 when there are only 2 instances?

**Comment by kevinmarrec** [comment]
@f-hj This issue have been fixed in #4053 and should be closed right ?
