### ISSUE TITLE
running pm2 in cluster mode on binary file

### ISSUE THREAD

**Issue by mhmardani** [Unitech/pm2#4050]
## What's going wrong?
Im trying to start pm2 in cluster mode for a binary file that i built with pkg. but pm2 fails cuz node error running server on same ip. but when i try it on my js file it works well.

**these works well:** 
`pm2 start app.js  -i max`
`pm2 start app -i max`

**and this wont:**
`pm2 start app -i max`

**Comment by croeber** [comment]
I am having this same issue. Has this ever worked?

**Comment by knoxcard** [comment]
just ran into this today

**Comment by F1ks3r** [comment]
You can't run cluster on binary file.

[This answer](https://stackoverflow.com/questions/34682035/cluster-and-fork-mode-difference-in-pm2#answer-36177256) on GitHub sums it up pretty nicely.

```The cluster will only work with node as it's exec_interpreter because it will access to the nodejs cluster module (eg: isMaster, fork methods etc.)```
