### ISSUE TITLE
Document the difference between `restart` and `reload`

### ISSUE THREAD

**Issue by dandv** [Unitech/pm2#406]
Would be great for new pm2 users to understand the exact difference between `pm2 restart` and `pm2 reload`.

**Comment by ChennyBaBy** [comment]
reload doesnt seem to pick up my changes hmmm...

**Comment by sandy0280** [comment]
-> As opposed to restart, which kills and restarts the process, reload achieves a 0-second-downtime reload.
-> With reload, pm2 restarts all processes one by one, always keeping at least one process running.
