### ISSUE TITLE
Setting wrong proc.pm2_env.status in readyCb

### ISSUE THREAD

**Issue by SoSafeSec** [Unitech/pm2#4060]
Hi,
with a permanent startup failure i ran into an issue where max_restarts was exceeded and proc.pm2_env.status == errored but later on changed to online. A bit of reading led to this code.

https://github.com/Unitech/pm2/blob/91786108d71b3fc6c182750c09b494619e28b28a/lib/God.js#L149

So we enter readyCB with proc.pm2_env.vizion === true and exec finalizeProcedure() while proc.pm2_env.status is still errored but in line 149 proc.pm2_env.status is set to online. 

And finalizeProcedure() should also check for proc.pm2_env.status == cst.ERRORED_STATUS and abort parsing. 

Long story short...
```
/** Callback when application is launched */
  var readyCb = function ready(proc) {
      if (proc.pm2_env.vizion !== false && proc.pm2_env.vizion !== "false") {
        God.finalizeProcedure(proc);
      } else {
        God.notify('online', proc);
        proc.pm2_env.status = cst.ONLINE_STATUS;
        console.log(`App [${proc.pm2_env.name}:${proc.pm2_env.pm_id}] online`);
      }
      if (cb) cb(null, proc);
}
```
and
```
    if (!proc ||
        !proc.pm2_env ||
        proc.pm2_env.status == cst.STOPPED_STATUS ||
        proc.pm2_env.status == cst.STOPPING_STATUS ||
        proc.pm2_env.status == cst.ERRORED_STATUS ) {
      return console.error('Cancelling versioning data parsing');
}
```
, or?

**Comment by Unitech** [comment]
fix incoming thanks for tracking down this issue
