### ISSUE TITLE
PM2 God consuming memory more than app

### ISSUE THREAD

**Issue by prosunshining** [Unitech/pm2#4064]
## What's going wrong?
I'm running web server with PM2, which is advised for production.
But after 24 hours of running, PM2 God daemon is using about 1GB of memory.

That causes pm2 apps down when we have any other processes running.

PM2 God daemon starts at 48MB then grows up to 1GB...
## How could we reproduce this issue?

It normally goes down after 24 or 48 hours of running.
## Supporting information

Server's memory size: 2GB
App memory usage: 800MB
PM2 memory usage: 1GB

```
$ pm2 report
```

**Comment by holau01** [comment]
i have experienced the same issue. Found that xxx-out.log files had grown too large to more than 2GB. I then redirected all console outputs to /dev/null by using the “-o” parameter. It seems that this workaround can avoid the problem. Would like to know whether you are facing the same situation.

**Comment by Unitech** [comment]
@prosunshining telling that kind of things, without providing any information (`pm2 report` is an helper I built to make reporting easier, to avoid you having to type 10 commands. this is not for dogs ok?), anything to reproduce, without screenshot anything, is a waste of time for everyone. I've ran an app that is flooding log as hell and nothing leaks.
So if you want me to help you provide more information

**Comment by prosunshining** [comment]
@holau01 Your comment was helpful, I could find out that log file which has been full up to 2GB and got memory stuck. It worked well when disabled pm2 logging and streamed logs into local file. 
Thanks!

**Comment by yi** [comment]
I just experience this issue and found the root cause is [NodeJS backpressure](https://nodejs.org/en/docs/guides/backpressuring-in-streams/). Basically, pm2 failed to flush the log to disk in time (too much log output). And this issue was solved by reducing log output.
