### ISSUE TITLE
NODE_APP_INSTANCE value of '0' did not match any instance config file names

### ISSUE THREAD

**Issue by youjunke** [Unitech/pm2#4065]
WARNING: NODE_APP_INSTANCE value of '0' did not match any instance config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode

### **hi, Why is there always this warning? My ecosystem.config.js  is as follows：**

apps: [
    {
      name: 'demo',
      script: 'src',
      ignore_watch: ['node_modules', 'logs', 'public'],
      output: './logs/out.log',
      error: './logs/error.log',
      env: {
        NODE_ENV: 'development'
      },
      env_production: {
        NODE_ENV: 'production'
      }
    }
  ]

**Comment by Unitech** [comment]
https://github.com/lorenwest/node-config/issues/244#issuecomment-320778070
