### ISSUE TITLE
Set log path to "/dev/null" doesn't work

### ISSUE THREAD

**Issue by Bingmang** [Unitech/pm2#4066]
## What's going wrong?

I set the log's output path to `/dev/null`, pm2 will output the log to the user's home directory, and it will gradually occupying the entire disk.

## How could we reproduce this issue?

Set the log's output path to `/dev/null`

```js
module.exports = {
  apps: [{
      name: 'app',
      script: 'app.js',
      output: '/dev/null',
      error: '/dev/null'
    }]
}
```

## Supporting information

```
$ pm2 report
```

**Comment by Bingmang** [comment]
By the way, I'm using the cluster mode.

**Comment by Unitech** [comment]
Just tried and the logs are not saved at all. Which platform are you running? Could you copy/paste the report of `pm2 report` thank you
