### ISSUE TITLE
PM2 not allowing to connect sequelize 

### ISSUE THREAD

**Issue by javeedrahman** [Unitech/pm2#4067]
Hi,

I am using PM2 and also using Sequelize to connect MySQL.

I have given correct credential but it is showing error. It is working fine with forever.

Kindly refer the image --> http://joxi.ru/EA4RNO5iw4eojm

**Comment by Unitech** [comment]
Hello, could you show me the code snippet that fails? (without pass))

**Comment by javeedrahman** [comment]
Hi @Unitech,

The issue is process.env.DATABASE_NAME is showing "undefined" variable while accessing from PM2.

So, the database is not able to access the database.

Could you please help me.

**Comment by javeedrahman** [comment]
Hi @Unitech,

what if I want to set multiple env variable 
DATABASE_USER = 'username' DATABASE_USER = 'password' pm2 start app.js
?
