### ISSUE TITLE
"pm2 reload myapp" does not reuse wait_ready set in ecosystem

### ISSUE THREAD

**Issue by xushuwei202** [Unitech/pm2#4069]
"pm2 reload myapp" does not reuse wait_ready set in ecosystem.

When I start my app using "pm2 start ecosystem.json", wait_ready's value is true.
Then later I use the command "pm2 reload all", the wait_ready will be false  .

- node version: 10.13.0
- pm2 version: 3.2.2 & 3.2.3

ecosystem.json:
`{
    "apps":[
        {
           "name": "myapp",
           "script" : "index.js",
           "instances" : 2,
            "node_args"  : "--max-semi-space-size=128",
            "exec_mode"  : "cluster",
              "wait_ready": true,
        }
     ]
}
 `

**Comment by Unitech** [comment]
My bad, I've forgoten to remove this statement while coding [here](https://github.com/Unitech/pm2/blob/master/lib/God/Reload.js#L125) 

Fixed and tested [here](https://github.com/Unitech/pm2/commit/a1ad1128d95e6b09d1ddc7ad7ebd0a9bab5064b8) will land on next release

**Comment by Unitech** [comment]
published

```bash
$ npm install pm2@latest -g
$ pm2 update
```

**Comment by xushuwei202** [comment]
> published
> 
> ```shell
> $ npm install pm2@latest -g
> $ pm2 update
> ```

Thank you!
