### ISSUE TITLE
Socket handles does not close after calling sendDataToProcessId

### ISSUE THREAD

**Issue by bahamut657** [Unitech/pm2#4070]
## What's going wrong?

using method sendDataToProcessId seems to spawn up to 3 sockets connection that will not be closed. Mantaning the task active for long time could cause system crashes

## How could we reproduce this issue?
```
               const pm2 = require("pm2")
               var msg = {
                type: "process:msg",
                data: {
                  cmd: "TEST CMD",
                  p: {a:1,b:2,c:3},
                  from: 1,
                  reqid: 2,
                },
                id: 1,
                topic: "MyTestTopic"
              }
              pm2.sendDataToProcessId(msg, (err, res) => {

                if (err) {
                  reject(err)
                } else {
                    // WORK COMPLETED
                }
           })



```
Any call to this method seems to mantain refs to socket handles
I can found (after 10 minutes of work) 700 handles' files in /proc/PID/fd/

If I run the same code without using PM2 it will results in no  leaked handles

## Supporting information

Attached the PM2 report log
[report.log](https://github.com/Unitech/pm2/files/2672839/report.log)

**Comment by Unitech** [comment]
I tried to reproduce the issue

```
var pm2 = require('.')

setInterval(function() {
  pm2.list(function(err) {
    console.log(err, 'ok')
  })

  pm2.sendDataToProcessId({
    topic: "process:msg",                                                                                                                                                                                           
    data: {
      OK: 'OK'
    },
    id: 0
  }, (err, res) => {
    console.log(err, res)
  })
}, 1000)
```

Ran: 

```
$ lsof <PM2_PID> | wc -l
$ lsof <APP_PID> | wc -l
```

Sockets are release on exit and stable in the long run

Provide more information (commands used to monitor sockets opened, who is leaking sockets and so on)
