### ISSUE TITLE
should i use pm2 restart my app install a while loop

### ISSUE THREAD

**Issue by toknT** [Unitech/pm2#4076]
I am new to nodejs.

There is  a app. js script do some process, and after it finiahed it wait 10 seconds.

So is it a  good way to use pm2 autorestart it? or add a while true loop? (I know i should not ask here but, I search it in google no thing be found)

**Comment by soyuka** [comment]
You can do either:
- use pm2 with a cron (every 10 seconds) + auto restart to false
- use nodejs with a `setInterval`

Both are fine, the later is easier to setup.
