### ISSUE TITLE
Remove traffic from closing processes

### ISSUE THREAD

**Issue by azazdeaz** [Unitech/pm2#4078]
When i reload a cluster, my processes properly get the `SIGINT` signal and pm2 waits until it closes, but it won't remove the traffic from the closing process. So after `SIGINT` the process will wait until all the requests finish, but pm2 will keep giving requests to the process. 
I didn't find anything in the docs about this, can i tell pm2 to remove traffic from closing processes?
```
pm2d version         : 2.10.4
node version         : 8.11.3
```

**Comment by Unitech** [comment]
How can you notice that the old process still get queries? Are your calling something like `server.close` and the callback never get called?

**Comment by azazdeaz** [comment]
Thank you! I was reading the old docs :sweat_smile:
