### ISSUE TITLE
env with json value not preserved

### ISSUE THREAD

**Issue by FTwex** [Unitech/pm2#4080]
## What's going wrong?
It seems that since the 3.2.3 release env variables set in the process file are not handled the same way.
With release <=3.2.2 if I dump my process env (`pm2 env 0` for example) I have something like that:
`ENV_VARIABLE_NAME={"key":"value"}`

Since release 3.2.3 if I dump env I have something like that:
`ENV_VARIABLE_NAME=[object Object]`

This break my code because I try to do a JSON.parse on that value and it fails.

I would like to know if I'm not using pm2 env in the right way or if it's a side effect ?

**Comment by Unitech** [comment]
That's pretty exotic to pass JSON directly like that without stringifying it.
With PM2 <=3.2.2, how these variables were looking like?

**Comment by FTwex** [comment]
Sorry I've made a mistake in my example
With PM2 <=3.2.2 env were like this ENV_VARIABLE_NAME='{"key":"value"}' so yes a string.

My process file is in JSON and env looks like that:
<img width="256" alt="image" src="https://user-images.githubusercontent.com/9253765/50172841-3bccd200-02f6-11e9-9045-e43b14b11730.png">
I guess PM2 stringified env values, as as i seen it in the PM2 source code

But it seem that in the latest release something has changed and prevent objects from being stringified

**Comment by Unitech** [comment]
I've restore the previous stringification behavior, will release it soon

**Comment by Unitech** [comment]
published

```bash
$ npm install pm2@latest -g
$ pm2 update
```
