### ISSUE TITLE
Wrong interpreter when using cluster mode

### ISSUE THREAD

**Issue by robertsLando** [Unitech/pm2#4082]
I'm having this issue when launching my app in cluster mode. 
If I run `pm2 start app`  everything works correctly but if I run `pm2 start ecosystem.config.json` I got this error: 

```bash
 ~/app:1
 (function (exports, require, module, __filename, __dirname) { ELF
                                                               ^
 
 SyntaxError: Invalid or unexpected token
     at createScript (vm.js:80:10)
     at Object.runInThisContext (vm.js:139:10)
     at Module._compile (module.js:616:28)
     at Object.Module._extensions..js (module.js:663:10)
     at Module.load (module.js:565:32)
     at tryModuleLoad (module.js:505:12)
     at Function.Module._load (module.js:497:3)
     at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:323:23
     at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
     at next (/usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:5329:29)
```

ecosystem.config.js: 

```javascript
module.exports = {
  apps : [
      {
        script: "app",
        exec_interpreter : "none",
        instances : "max",
        exec_mode : "cluster"
      }
  ]
}
```

I think it is a problem related with the interpreter but I don't understand why it doesn't work just in cluster mode and it works in single instance mode. 
The app is a nodejs application packaged using [pkg](https://github.com/zeit/pkg). I output there other information about `app` file: 

```bash
app: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, BuildID[sha1]=0f362bc7852d2f8ab7e1b7c95ad989883021996f, with debug_info, not stripped
```

### UPDATE

Seems like I get the same error `SyntaxError: Invalid or unexpected token` when lunching the app with the command: `node app`.
So the question is why pm2 uses a different interpreter (even if it is specified as 'none') when using cluster mode?

**Comment by robertsLando** [comment]
As I discovered seems cluster only works with node applications so it can't works with my binary file. 
My workaround for this has been to manually cluster my app by following this tutorial: 

https://www.sitepoint.com/how-to-create-a-node-js-cluster-for-speeding-up-your-apps/

Than launch it with pm2 and everything works fine.

I think that pm2 should throw an documented error when try to launch apps that are not nodejs applications using cluster mode.

**Comment by Unitech** [comment]
PM2 load balance only Node.js application and needs to manage the node binary itself. I've added a note on the doc
