### ISSUE TITLE
npm test fail: test.json@latest not found

### ISSUE THREAD

**Issue by yinrong** [Unitech/pm2#4086]
## What's going wrong?
npm test fails:

![image](https://user-images.githubusercontent.com/4221569/50390590-ec622800-0773-11e9-86de-9d8ded2e06b7.png)

![image](https://user-images.githubusercontent.com/4221569/50390604-0a2f8d00-0774-11e9-90ce-77c9d5c7fa65.png)

## How could we reproduce this issue?
```
git clone ...
npm i
npm test

FAILS!
```

## Supporting information

```
$ node -v
v8.11.3

```

**Comment by Unitech** [comment]
first screenshot, this is normal, this is a voluntary fail that pass the test.
For the second screenshot you've forgot to install python interpreter
https://github.com/Unitech/pm2/tree/development
