### ISSUE TITLE
Environment variable is string instead of number

### ISSUE THREAD

**Issue by jahirfiquitiva** [Unitech/pm2#4089]
## What's going wrong?
I'm trying to save an environment variable which is a number. Like
```javascript
env_local: {
    NODE_ENV: 'local',
    PORT: 8080,
    MAX_TIMEOUT: 10000
}
```

When I get it to use it, like:
`const timeout = process.env.MAX_TIMEOUT || 10000;`
and I do `console.log(typeof timeout);`, it outputs `string`, and I need it as number, otherwise it crashes

Mind explaining what am I doing wrong? Thanks in advance!

**Comment by jahirfiquitiva** [comment]
I also, want to know how to do it with float values, like `0.5`. Because, once again, it says its type is `string`
Thanks

**Comment by Unitech** [comment]
Environment variables can only contain string values, use `parseInt(process.env.MAX_TIMEOUT)`
