### ISSUE TITLE
`pm2 pid` should return pid

### ISSUE THREAD

**Issue by ArturFormella** [Unitech/pm2#4107]
Hello!
I think pm2 pid should return pid in any case. Without any other information. 
```
sudo npm install pm2 -g    # install latest version
pm2 pid myapp 2>/dev/null
29316

(...)

sudo npm install pm2@3.2.4 -g    # prev version to simulate my broken prod
pm2 pid myapp 2>/dev/null
>>>> In-memory PM2 is out-of-date, do:
>>>> $ pm2 update
In memory PM2 version: 3.2.5
Local PM2 version: 3.2.4

29316
```

How to disable this update-information (flags?, ENVs?)

**Comment by Irytacja** [comment]
I highy agree with OP,  `pm2 pid app_name` should return only pid.

**Comment by ArturFormella** [comment]
Workaround:
`pm2 pid myapp | tail -n 1`
but one won't know it's needed before it crash

**Comment by ArturFormella** [comment]
sadly, this is still in effect
