### ISSUE TITLE
PM2v 3.2.7 is not compatible with old Node versions

### ISSUE THREAD

**Issue by Arslan007** [Unitech/pm2#4111]
## What's going wrong?
Latest PM2 NPM package is mot compatible with Node JS 8.9.0. PM2 starts the daemon then right after it gets down. There are no errors in logs or console. While PM2@3.2.4 works fine with Node JS 8.9.0 

## How could we reproduce this issue?
I believe just test with Node JS 8.9.0 Application then its shouldnot work.

**Comment by huanghai21** [comment]
got the same problem with pm2@3.2.7, while the nodejs version is v10.15.0

```
[PM2] Spawning PM2 daemon with pm2_home=C:\Users\XXX\.pm2
[PM2] PM2 Successfully daemonized
[PM2][WARN] Applications  TEST not running, starting...
[PM2] App [TEST ] launched (1 instances)
```
it shows a WARN first, then the TEST app was running, then it shutdown without any errors or information tips.

**Comment by hunglee** [comment]
same problem with pm2@3.2.7 with the nodejs version is v10.15.0, OS: WINDOWS Server 2012

**Comment by mgryniak** [comment]
pm2@3.2.7, nodejs v8.9.4, OS: WINDOWS Server 2016

**Comment by Unitech** [comment]
pm2@3.2.8 published with rollback of node exec path adaption
