### ISSUE TITLE
error log formatter

### ISSUE THREAD

**Issue by mhf-ir** [Unitech/pm2#4120]
## What's going wrong?
I cant save error log as json or structure data format for using in log collector service like fluentbit.

## How could we reproduce this issue?
Jus set the error log see the result:

## Supporting information
I cant find any value to set error log formats
* It's will be awesome of logs could be pass to tcp or udp service directly
* it's will be awesome if i can modify json data befor send to log metrics.

```js
module.exports = {
  apps: [
    {
      name: 'sample',
      script: 'index.js',
      log_date_format: 'X',
      error_file: '/tmpfs/logs/pm2.error.log',
      out_file: '/tmpfs/logs/pm2.out.log',
      log_type: 'json',
      error_log_type: 'json', // ??????
      combine_logs: true,
      env: {
        NODE_ENV: 'production',
      },
    },
  ],
};
```

**Comment by fluxsauce** [comment]
I'm looking for the same thing; we use `log4js` to route and render logs. We display logs in a human readable format but store a version in JSON that Splunk consumes. However, `pm2` doesn't provide the granularity to allow `output` to be unformatted and `error` to be in JSON. Therefore, I can set `log_type` to `json`, but that corrupts the already formatted human readable output.

**Comment by damianobarbati** [comment]
+1 for this.

If I have a console.log like:
```
//my stuff
console.log({ fingerprint, response });
```
I get a log like this:
```
{
  "message": "{ fingerprint: '410868409',\n   response:\n   'OK' }",
  "timestamp": "2019-03-26 12:01 +01:00",
  "type": "out",
  "process_id": 0,
  "app_name": "webapi.translated.com"
}
```

Which prevents me from processing the log from `jq` since message is a string and not a json itself, merged with the PM2 logging metadata.
