### ISSUE TITLE
PM2 WONT WORK for me

### ISSUE THREAD

**Issue by NicoB12** [Unitech/pm2#4122]
## Supporting information

PS C:\Users\Nico Bernales\.pm2> pm2 start bot.js
[PM2] Spawning PM2 daemon with pm2_home=C:\Users\Nico Bernales\.pm2
[PM2] PM2 Successfully daemonized
[PM2] Starting C:\Users\Nico Bernales\.pm2\bot.js in fork_mode (1 instance)
[PM2] Done.
┌──────────┬────┬─────────┬──────┬───────┬────────┬─────────┬────────┬─────┬───────────┬───────────────┬──────────┐
│ App name │ id │ version │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem       │ user          │ watching │
├──────────┼────┼─────────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼───────────────┼──────────┤
│ bot      │ 0  │ 1.0.0   │ fork │ 11816 │ online │ 0       │ 0s     │ 0%  │ 55.2 MB   │ Nico Bernales │ disabled │
└──────────┴────┴─────────┴──────┴───────┴────────┴─────────┴────────┴─────┴───────────┴───────────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
PS C:\Users\Nico Bernales\.pm2> pm2 show 0
[PM2] Spawning PM2 daemon with pm2_home=C:\Users\Nico Bernales\.pm2
[PM2] PM2 Successfully daemonized
[PM2][WARN] 0 doesn't exist
PS C:\Users\Nico Bernales\.pm2>
![untitled](https://user-images.githubusercontent.com/46690665/51139088-dd0b6180-187d-11e9-951e-1108b1e655a5.png)

```
$ pm2 report
```

**Comment by NicoB12** [comment]
Can you link me sir @liamomg ? Thank you for your respond. Big help for me.

**Comment by liamomg** [comment]
I have already linked in the previous comment. https://github.com/Unitech/pm2/issues/3108

**Comment by NicoB12** [comment]
All good sir. Thank you very much. May I ask another question sir. There is a setup about pm2 sir that identifies if my javascript is still on going or not? Because I have a script but like a BOT. It is still online but don't work if it hangs.

**Comment by NicoB12** [comment]
Can I write you sir?

**Comment by liamomg** [comment]
Umm...I am not quite sure what is your question

**Comment by NicoB12** [comment]
Do you have a recommend, example. I will give you file and you need to accept it and then after you accept it it automatically send back to me. Like that sir.

**Comment by Unitech** [comment]
@NicoB12 which pm2 version are you using? (`pm2 -v`)

**Comment by NicoB12** [comment]
This sir, https://github.com/Unitech/pm2/issues/3108

**Comment by cy6eria** [comment]
I got same problem on a Windows Server. I've found a hack. It works while the monitor (`pm2 monit`) is on screen (in the other PowerShell window).

**Comment by Unitech** [comment]
How did you installed Node.js guys? Could you run `Get-Command node`

**Comment by JardaHosek** [comment]
I've installed node-v10.15.0-x64.msi
Get-Command node: Application, node.exe, 10.15.0.0, C:\Program Files\nodejs\node.exe

**Comment by Unitech** [comment]
closing in favor of https://github.com/Unitech/pm2/issues/4128
