### ISSUE TITLE
PM2  take around 6 Giga bytes of memory on linux server

### ISSUE THREAD

**Issue by almgwary** [Unitech/pm2#4123]
## What's going wrong?
PM2 process takes about 8G Ram on linux server
it run 5 node application each one takes 1GB memory 
## How could we reproduce this issue?
i run pm2 for 1 month
## Supporting information

```
$ pm2 report
```

**Comment by almgwary** [comment]
This all information I have, why PM2 have to use all that memory it is just process manger

**Comment by Unitech** [comment]
Please run `pm2 report` and tell me a bit more about your application (like the modules you are using)

**Comment by alyrik** [comment]
This issue seems to be related somehow with #4213.
