### ISSUE TITLE
PM2 start command prepends console logs with metadata

### ISSUE THREAD

**Issue by errolpais** [Unitech/pm2#4125]
## What's going wrong?
My application is kicked off using `pm2 start` command and the console logs are forwarded to splunk. I want to make use of splunk's json parsing features but my application console logs are being prepended with the timestamp, instance number and an application name (eg. `10:41:59 5|application_name  | logged_message`  ) which makes the string unrecognizable as json

I would like PM2 start command to have the option to not prepend logs. Perhaps a flag like --no-log-prepend or --no-log-stamp. This is similar to the feature request made for #709 except that its for the pm2 start command as opposed to the pm2 logs command

## How could we reproduce this issue?
* Execute application using `pm2 start app.js -i 8`
* See that console logs are being prepended with additional metadata for that event

## Supporting information
pm2d version         : 3.2.2
node version         : 8.11.3
platform: linux

**Comment by Unitech** [comment]
`pm2 logs --json`
