### ISSUE TITLE
My app is getting killed somehow but not restarted

### ISSUE THREAD

**Issue by jlubeck** [Unitech/pm2#4154]
I'm using pm2 programmatically, and it's been working just fine most of the time. But every now and then, my app stops working. I check for running processes, and node is not there like when the app is running.

Also, pm2.log shows this at the time it stopped working:

```
2019-02-05T05:00:33: PM2 log: App [index:0] exited with code [0] via signal [SIGKILL]
2019-02-05T05:00:33: PM2 log: App [index:0] starting in -fork mode-
2019-02-05T05:00:33: PM2 log: App [index:0] online
```

It should be online right? But it isn't...

This is my startup script:

```
// The Method to call the scan script
let pm2 = require('pm2')

pm2.connect(err => {
    if (err) {
        var currentDate = '[' + new Date().toJSON() + '] ';
        console.error(currentDate, err)
        process.exit(2)
    }

    pm2.start({
        script: '/usr/lib/index.js'
    }, (err, app) => {
        var currentDate = '[' + new Date().toJSON() + '] ';
        console.log(currentDate, 'Succesfully started pm2')
        console.log(app)
        pm2.disconnect()
        if(err) throw err
    })
})
```

Not sure what more information I can give to try to solve this but I'd appreciate any help!

**Comment by comtaler** [comment]
I have a similar issue. The difference is that I didn't use it programmatically. I have an app list in a config and start my node program using the config file. Once in a while when I try to restart the app, it will give a similar log. And my app runs in cluster mode. Here my pm2 log:

> PM2      | App [app:6] starting in -cluster mode-
> PM2      | App name:app id:6 disconnected
> PM2      | App [app:6] exited with code [1] via signal [SIGINT]
> PM2      | App [app:6] starting in -cluster mode-
> PM2      | App name:app id:6 disconnected
> PM2      | App [app:6] exited with code [1] via signal [SIGINT]
> PM2      | App [app:6] starting in -cluster mode-
> PM2      | App name:appid:6 disconnected
> PM2      | App [app:6] exited with code [1] via signal [SIGINT]
> PM2      | Script /home/app had too many unstable restarts (16). Stopped. "errored"

**Comment by comtaler** [comment]
Is there any update on this issue?
This is urgent for me. Does anyone know which version works without this issue?

**Comment by jlubeck** [comment]
Ok, I at least found the culprit:
[Wed Feb 27 14:07:09 2019] 172614.404528@0] lowmemorykiller: Killing 'node /usr/lib/i' (1110), adj 0,

It is being killed because of low memory apparently. Is this why pm2 is not restarting it? 

And if it is, is there a way to automatically restart the computer after this happens? (I realize this might not be a pm2 question, but any help is appreciated)
