### ISSUE TITLE
PM2 Doesn't merge logs

### ISSUE THREAD

**Issue by deemeetree** [Unitech/pm2#4167]
## What's going wrong?

https://stackoverflow.com/questions/54743236/cant-merge-the-standard-and-error-log-in-pm2

## How could we reproduce this issue?

https://stackoverflow.com/questions/54743236/cant-merge-the-standard-and-error-log-in-pm2

## Supporting information

```
$ pm2 report
```

**Comment by guillett** [comment]
Hi @deemeetree looking at your StackOverflow link, you managed to solve your problem. Can you close your issue if that's the case? Many thanks!


Note: I have issues merging logs.
