### ISSUE TITLE
daemon won't spawn

### ISSUE THREAD

**Issue by SRugina** [Unitech/pm2#4184]
## What's going wrong?

installing pm2 then doing almost any pm2 command returns:

`[PM2] Spawning PM2 daemon with pm2_home=/home/user/.pm2`

and nothing else. attempting to do the command that pm2 startup outputs returns:

    [PM2][ERROR] Init system not found
    Platform systemd
    Template
    [Unit]
    Description=PM2 process manager
    Documentation=https://pm2.keymetrics.io/
    After=network.target
    
    [Service]
    Type=forking
    User=user
    LimitNOFILE=infinity
    LimitNPROC=infinity
    LimitCORE=infinity
    Environment=PATH=/snap/node/1729/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
    Environment=PM2_HOME=/home/user/.pm2
    PIDFile=/home/user/.pm2/pm2.pid
    
    ExecStart=/usr/local/lib/node_modules/pm2/bin/pm2 resurrect
    ExecReload=/usr/local/lib/node_modules/pm2/bin/pm2 reload all
    ExecStop=/usr/local/lib/node_modules/pm2/bin/pm2 kill
    
    [Install]
    WantedBy=multi-user.target
    
    Target path
    /etc/systemd/system/pm2-user.service
    Command list
    [ 'systemctl enable pm2-user' ]
    [PM2] Writing init configuration in /etc/systemd/system/pm2-user.service
    [PM2] Making script booting at startup...
    [PM2] [-] Executing: systemctl enable pm2-user...
    /bin/sh: 1: systemctl: not found
    [ERROR] Exit code : 127
    [PM2][ERROR] systemctl enable pm2-user failed, see error above.

even though `pm2 startup` returns:

    [PM2] Init System found: systemd
    [PM2] To setup the Startup Script, copy/paste the following command:
    sudo env PATH=$PATH:/snap/node/1729/bin /usr/local/lib/node_modules/pm2/bin/pm2 startup systemd -u user --hp /home/user

Also had this issue on my production servers, although I eventually somehow managed to fix those - can't remember how, and those situation didn't give me the pm2 startup errors so this is a slightly different problem I think.

The pm2 logs are all empty

## How could we reproduce this issue?

    npm install pm2@latest -g
    pm2 ls

## Supporting information

```
$ pm2 report
[PM2] Spawning PM2 daemon with pm2_home=/home/user/.pm2
```

**Comment by Unitech** [comment]
```

[PM2] [-] Executing: systemctl enable pm2-user...
/bin/sh: 1: systemctl: not found
[ERROR] Exit code : 127
```

Looks like there is a wrong discovery, which linux distribution are you using?

**Comment by vmarchaud** [comment]
@SRugina Did you use `snap` to install nodejs ?

**Comment by SRugina** [comment]
@Unitech I'm using Pop!_OS 18.10 - essentially ubuntu 18.10 with a skin. @vmarchaud yeah I used snap to install nodejs.

**Comment by SRugina** [comment]
@vmarchaud should I try using node from the binary on their website (https://nodejs.org/dist/v10.15.3/node-v10.15.3-linux-x64.tar.xz) instead of snap?

**Comment by SRugina** [comment]
Can confirm - uninstalling global pm2, uninstalling node snap package, compiling nodejs v10.15.3 from source (https://nodejs.org/dist/v10.15.3/node-v10.15.3.tar.gz instructions at https://github.com/nodejs/node/tree/v0.10.15-release), installing global pm2 worked.

**Comment by aral** [comment]
@SRugina Glad you got it working. For future reference, pm2 also works with Node installed via [nvm](https://github.com/creationix/nvm) (tested on Pop!_OS 18.10) ;)
