### ISSUE TITLE
how to restart app when app  state is 503?

### ISSUE THREAD

**Issue by yiwong2001** [Unitech/pm2#4200]
##  How to restart when app state is 503.

```
$ pm2 report
```
Hi there,

Thank you for offering such a cool tools.  I wonder is there a way to restart service when app get 503 error? 

MY node app got following error when it got heavy traffic.
503 Service Temporarily Unavailable

Best, Ian

**Comment by khiettran** [comment]
Today, I get the same issue, have been searching for hours but no luck :(
