### ISSUE TITLE
Bug in application streaming data after update from 3.2.9 to 3.4.0

### ISSUE THREAD

**Issue by jeffrson** [Unitech/pm2#4206]
My application uses SFTP (via ssh2-promises) to copy data.

It opens a readStream (sftp.createreadstream) and a writeStream (sftp2.createwritestream) and copies data with readStream.pipe(writeStream).

After I upgraded pm2 to 3.4.0 I get strange copy errors (exception log contains "cannot access method slice of undefined"). Error codes appear to come from my application, but breakpoints are not hit (from where the codes are sent).

As soon as I go back to 3.2.9 everything works again.

**Comment by vmarchaud** [comment]
which node version are you using ?

**Comment by jeffrson** [comment]
10.15.3 - sorry

**Comment by jeffrson** [comment]
pm2 3.3.1 seems good as well

**Comment by vmarchaud** [comment]
Hey,

It should be fixed with a pm2 re-installation:
```
npm install pm2 -g
pm2 update
```
