### ISSUE TITLE
PM2 3.2.2 full CPU, RAM

### ISSUE THREAD

**Issue by ngankilo** [Unitech/pm2#4211]
![df14d4f41c1ffe41a70e](https://user-images.githubusercontent.com/18714380/54862339-078d0580-4d6c-11e9-90c2-91c7ed2e4542.png)

Here is my file ecosystem.config.js

    module.exports = {
    apps: [

        {
            name        : 'GSO',
            script      : 'http.js',
            error_file  : "/dev/null",
            out_file    : "/dev/null",
            instances   : 'max',
            exec_mode   : 'cluster',
            env         : {
                NODE_ENV: 'production',
                PORT    : 6969
            }
        }
    ] }

**Comment by Unitech** [comment]
Upgrade to pm2 latest, there were an issue with the inspector module. Re open the issue if you still see this behavior
