### ISSUE TITLE
PM2 dies and loses process

### ISSUE THREAD

**Issue by arasmussen** [Unitech/pm2#4214]
## What's going wrong?
When I run `pm2 list`, I get the following:

```
[PM2] Spawning PM2 daemon with pm2_home=/home/ec2-user/.pm2
[PM2] PM2 Successfully daemonized
```

This would indicate that PM2 wasn't running in the first place. What's more, my process isn't running, and I have to `pm2 start` it again. After doing so, I run `pm2 save`, but PM2 still loses my process after hours/days.

## How could we reproduce this issue?
I'm honestly not entirely sure. It started happening to us recently on multiple machines when we migrated from EC2 t2 instances to EC2 t3 instances.

Seems similar to https://github.com/Unitech/pm2/issues/2013, but that issue is quite old and didn't have helpful information on it.

## Supporting information

```
$ uname -a
Linux version: Linux ip-x-x-x-x 4.14.104-78.84.amzn1.x86_64 #1 SMP Mon Mar 4 19:19:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ node -v
v6.9.1

$ pm2 -v
2.4.0

$ pm2 start ~/MyApp.js -i 4 # Cluster Mode
```

I'm not running out of memory, CPU, or disk space. As far as I can tell, my EC2 server isn't crashing. `~/.pm2/pm2.log` doesn't have any useful error messages in it.

**Comment by arasmussen** [comment]
I updated pm2 to version 3.4.0, and ran `pm2 startup`, `pm2 save`. Will re-open if the problem is still happening.

**Comment by jfoclpf** [comment]
Very strange and I had a similar problem now.

I was warned my sites were down, and I had to `pm2 resurrect` to restore all saved processes since `pm2 ls` was empty. But what surprised me most is that they went down without anything I could trace (not a reboot at least, since `uptime` gives me 81 days). I had obviously previously saved the list with `pm2 save` and `pm2 startup`.

This is scary, because I never know now if the processes may suddenly go down.

Any idea of what can flush the processes list?

**Comment by goors** [comment]
I have same problems, i think this was never addressed in pm2. For some reason it just loses state, no logs, no why and processes are already running and when you do resurrect it does not look if processes are running it just spins up new ones.
I switched all my pm2 something like with systemd:

```
[Unit]
Description=My Node.js App
After=network.target

[Service]
ExecStart=/usr/bin/node /path/to/app.js
Restart=always
User=yourusername
Group=yourgroup
Environment=NODE_ENV=production
WorkingDirectory=/path/to
StandardOutput=append:/var/log/myapp.log
StandardError=append:/var/log/myapp.err

[Install]
WantedBy=multi-user.target
```

and not just for node apps ....  Hopes this helps someone.
