### ISSUE TITLE
Compatibility with pnpm - missing inspector dependency

### ISSUE THREAD

**Issue by mauron85** [Unitech/pm2#4221]
## What's going wrong?
PM2 is not currectly compatible with [pnpm]() package manager. Pnpm [requires all dependencies to be declared](https://www.kochan.io/nodejs/pnpms-strictness-helps-to-avoid-silly-bugs.html) in `package.json`.

Running [dependency-check](https://www.npmjs.com/package/dependency-check) reveals that `inspector` package declaration is missing in pm2 `package.json`.

This means pm2 is currently relying that `inspector` will be installed by one of its dependency.
This is not robust and could potentially [introduce silly bugs](https://www.kochan.io/nodejs/pnpms-strictness-helps-to-avoid-silly-bugs.html) not only for users using pnpm.

## How could we reproduce this issue?

Try to install via `pnpm -g install pm2` and try to use it. You'll get weird errors, like pm2 forgetting configuration.

## Supporting information

```
dependency-check ./package.json
Fail! Dependencies not listed in package.json: inspector
```

https://www.kochan.io/nodejs/pnpms-strictness-helps-to-avoid-silly-bugs.html

```
$ pm2 report
```

Run report is not relevant in this context, as this is pre install issue.

**Comment by marwenbk** [comment]
same issue pnpm is not supported
