### ISSUE TITLE
Can't see logs for app name containing space

### ISSUE THREAD

**Issue by AnubrataDS** [Unitech/pm2#4222]
## What's going wrong?
In `ecosystem.config.js`, if an app name has a space in it, then `pm2 logs <appname>` takes only the part of the appname before the space and tries to find logs for it.

Even `pm2 show <id>` suggests to use `pm2 logs <appname>` (See attached screenshots below) 

## How could we reproduce this issue?
- Use an `ecosystem.config.js` where any app name has a space in it
- Start pm2 
- Try to see logs of said app using `pm2 logs <appname>` 
## Supporting information

(Using powershell on windows 10 x64)

This is the end of the output when I did `pm2 show 1` 

![Screenshot_8](https://user-images.githubusercontent.com/20087176/55228504-44f80400-5240-11e9-844a-80e82526f4b0.png)

(Update Cron is the appname in ecosystem.config.js)

![Screenshot_9](https://user-images.githubusercontent.com/20087176/55228631-96a08e80-5240-11e9-915c-f334b9d5cf70.png)

(No output after this)

**Comment by BonLouis** [comment]
Same issue here using gnome-terminal and ssh :
`gnome-terminal -e 'bash -c "ssh user@server -- pm2 log "process with space""'`
Would be awesome if pm2 handle it. For now, I have to remove those space...
