### ISSUE TITLE
pm2 restart infinite when port was occupied

### ISSUE THREAD

**Issue by simplast** [Unitech/pm2#4230]
Is there any way to set a upper limit to restart during limited time,like five at most in ten seconds?
This is my .config.js:

module.exports = {
  apps: [{
    name: "fsdt",
    script: "bin/www",
    watch: false,
    max_memory_restart:"200M",
    env: {
      "NODE_ENV": "development",
    },
    env_production: {
      "NODE_ENV": "production"
    }
  }]
}

**Comment by Khromushkin** [comment]
I think max_restarts and min_uptime are the params which you are looking for.
