### ISSUE TITLE
max-memory-restart delaying?

### ISSUE THREAD

**Issue by Talg123** [Unitech/pm2#4238]
When I run my PM2 and I set the max-memory-restart argument, it seems like it takes a while \ it wont restart at the limit I gave to it.

`            "node_args" : "--max-old-space-size=768",
            "max_memory_restart" : "50M",`

this is what I use, and it seems like it can go up to 300\400 M and then restarts.
Is there a delay till when the PM2 find there is memory limit till it actully restarts?

Tnx Tal.

**Comment by Unitech** [comment]
Yes it depends on the worker interval: https://github.com/Unitech/pm2/blob/master/lib/Worker.js#L183

You can change the worker interval via:
https://github.com/Unitech/pm2/blob/master/constants.js#L101

```bash
$ PM2_WORKER_INTERVAL=5000 pm2 update
```
