### ISSUE TITLE
PM2 cluster mode worsens performance esxpress server

### ISSUE THREAD

**Issue by ihorzakutynsky** [Unitech/pm2#4241]
## What's going wrong?
When we run simple express server in pm2 cluster mode, the performance is decreases.

#### server.js
```
const express = require('express');
const app = express();

const PORT = process.env.PORT || 3000;

app.get('/ping', function (req, res) {
  res.send({ message:'pong' });
});

app.listen(PORT, function () {
  console.log(`Example app listening on port ${PORT}`);
});
```

## How could we reproduce this issue?

1. Run server without pm2: 
```$ node server.js```
2. Make AB testing:
```$ ab -c 100 -n 100000 http://localhost:3000/ping```
3. Run server with pm2 in cluster mode: 
```$ pm2 start server.js -i max```
4. Make AB testing:
```$ ab -c 100 -n 100000 http://localhost:3000/ping```
5. Compare results

In my case i get **8591** requests for native node run, and **5471** for pm2 cluster mode (4 core cpu 2.70GHz) 
## Supporting information
**Node**: v11.12.0
**PM2**: v3.4.0

**Comment by knoxcard** [comment]
Are all four app instances fighting to use the same port?

**Comment by ihorzakutynsky** [comment]
@knoxcard, after cutting, i get 6300 req

**Comment by Unitech** [comment]
I've done this benchmark once:
Configuration:
https://gist.github.com/Unitech/f56f3c3135631c14355bdca791d5eba4
https://gist.github.com/Unitech/4be07d1dd815afce793b6ab60949c167

**Comment by Unitech** [comment]
haproxy:

```

>>> wrk -c 100 http://localhost:6001
Running 10s test @ http://localhost:6001
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.43ms    4.50ms  56.72ms   86.00%
    Req/Sec    14.50k     2.31k   18.41k    89.50%
  288589 requests in 10.01s, 34.40MB read
Requests/sec:  28837.34
Transfer/sec:      3.44MB
```

Nginx (tcp stream):

```
>>> wrk -c 100 http://localhost:7001
Running 10s test @ http://localhost:7001
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.94ms    2.55ms  44.78ms   93.74%
    Req/Sec    13.61k     1.57k   16.67k    90.00%
  270752 requests in 10.02s, 32.28MB read
Requests/sec:  27011.39
Transfer/sec:      3.22MB
```

PM2:

```
>>> wrk -c 100 http://localhost:8001
Running 10s test @ http://localhost:8001
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.62ms    7.83ms 225.85ms   97.73%
    Req/Sec    17.79k     2.80k   21.40k    85.50%
  354083 requests in 10.01s, 42.21MB read
Requests/sec:  35387.79
Transfer/sec:      4.22MB
````

NGINX: Requests/sec:  28837.34
HAPROXY: Requests/sec:  27011.39
PM2: Requests/sec:  35387.79

PM2 cluster is the fatest because it passes file descriptor instead of stream/sockets to child processes. PM2 cluster also divide the number of sockets by 2
