### ISSUE TITLE
Feature request, ignore files by extension

### ISSUE THREAD

**Issue by auxcoder** [Unitech/pm2#4252]
Would be nice to, in watch mode, backlist files by its extension.
**Use case**: Changing files `*.md` at a subfolder level (or any) should no trigger restart.
Thanks for such of tool.

**Comment by Unitech** [comment]
Something like that: https://github.com/Unitech/pm2/pull/4224?

**Comment by auxcoder** [comment]
Yes, exactly that, thanks.
