### ISSUE TITLE
PM2 web - memory leak

### ISSUE THREAD

**Issue by VictorBaudot** [Unitech/pm2#4255]
![image](https://user-images.githubusercontent.com/33088396/56473383-09311280-646b-11e9-85b1-75af054fae2e.png)

![image](https://user-images.githubusercontent.com/33088396/56473422-8066a680-646b-11e9-90a4-dcb39eec10e3.png)

I'm using pm2 web on multiple servers and on all of them it looks like there is memory leaks as the memory consumption keep increasing.

Tell me if you need more informations.

```
===============================================================================
--- PM2 REPORT (Sun Apr 21 2019 19:24:26 GMT+0200 (Central European Summer Time))
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.2.2
node version         : 11.14.0
node path            : /home/victor/.yarn/bin/pm2
argv                 : /usr/bin/node,/home/victor/.config/yarn/global/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : victor
uid                  : 1001
gid                  : 1001
uptime               : 547min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.2.2
node version         : 11.14.0
node path            : /home/victor/.yarn/bin/pm2
argv                 : /usr/bin/node,/home/victor/.yarn/bin/pm2,report
argv0                : node
user                 : victor
uid                  : 1001
gid                  : 1001
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel Core Processor (Haswell, no TSX)
cpus nb              : 1
freemem              : 178827264
totalmem             : 2039889920
home                 : /home/victor
===============================================================================
```

**Comment by kaven276** [comment]
I have too.

 "_id": "pm2@3.2.2",

node -v
v8.9.3
[wosale@wosale ~]$

**Comment by kaven276** [comment]
Fri Aug 30 11:40:01 CST 2019
  RSS
77972
Fri Aug 30 11:50:01 CST 2019
  RSS
75340
Fri Aug 30 12:00:01 CST 2019
  RSS
80968
Fri Aug 30 12:10:01 CST 2019
  RSS
122388
Fri Aug 30 12:20:01 CST 2019
  RSS
145320
Fri Aug 30 12:30:01 CST 2019
  RSS
179296

**Comment by victorboissiere** [comment]
We seem to have the same issue as we cannot reproduce it without PM2 (using node index.js)

**Comment by OmgImAlexis** [comment]
Possibly related. Also keep in kind the devs tend to just close issues instead of helping at least that’s what they did for me when I tried reporting a memory leak. Ended up just ditching pm2.

https://github.com/Unitech/pm2/issues/4510

**Comment by LosTigeros** [comment]
![mem](https://user-images.githubusercontent.com/6253928/78423592-97e07480-7667-11ea-9fdb-9dcfa2ac68d6.png)
My RAM usage when I was using node and after I've started using pm2.
Now I have to manually reload everything to not go OOM... Thinking of switching back to node.

**Comment by OmgImAlexis** [comment]
Bad bot.
