### ISSUE TITLE
PM2 monit not displaying global logs

### ISSUE THREAD

**Issue by ernitishkumar** [Unitech/pm2#4257]
## What's going wrong?
I am using pm2 3.5 on centos 7.

My node server application requires port 443 to run and because of that I have to run my application by using command

`sudo -E pm2 start server.js -i max`

When I start pm2 with sudo command the logs or default pm2 folders are created under
`/root/.pm2/logs/`

and because of that sudo pm2 does not shows any logs even when I select individual applications.

## How could we reproduce this issue?
Run pm2 with below command

`sudo -E pm2 start server.js -i max`

then do

`sudo pm2 monit`

then try to view global logs by selecting app name.

## Supporting information

```
$ pm2 report
```

**Comment by Unitech** [comment]
Hello, Since 3.5.0, only the logs of the selected app is shown. You have to select the right process in the top left box

**Comment by ernitishkumar** [comment]
> Hello, Since 3.5.0, only the logs of the selected app is shown. You have to select the right process in the top left box

I have clearly mentioned it in the OP that I have done that still it is not displaying. When I run pm2 without sudo then it displays the logs not when I run it with sudo -E pm2 

Kindly read my whole issue first !

**Comment by edmondburnett** [comment]
Same issue here with 3.5.1. No logs are displayed in `monit` regardless of the app selection in the left pane.

**Comment by Droppix** [comment]
Same issue with 4.4.0 on Mac.
pm2 start ecosystem.json -i 4

**Comment by kikoncuo** [comment]
Same issue with 4.5.5 on windows 
pm2 start server.js -i 4

**Comment by NullDev** [comment]
Same issue on 4.5.6

![image](https://user-images.githubusercontent.com/22935000/114364069-54bdb900-9b79-11eb-9cc9-14b2e397afa0.png)

**Comment by GuFFy12** [comment]
same(
![image](https://user-images.githubusercontent.com/49491499/114411367-8ceae900-9bc5-11eb-9529-6a9053bc4416.png)

**Comment by HaruMiyaGi** [comment]
System: WSL Ubuntu 20.04 LTS
PM2: version 5.1.2

I am not seeing any logs too, but `pm2 logs` does show

**Comment by NotGovernor** [comment]
No logs her either. I'd post screen shots but it looks identical to the above.  Can we reopen this for investigation? <3

**Comment by stoplion** [comment]
No logs either. Please can we get answer?

**Comment by PROPHESSOR** [comment]
+1, please fix it

- `pm2 monit` shows no logs
  - If the application crashes and constantly reloads, errors are displayed in the log window, but during normal operation of the application, the logs are empty
- `pm2 logs app` shows logs correctly

**Comment by tasdflkjweio** [comment]
This is still an issue

**Comment by lucas-labs** [comment]
I can confirm this is still in issue, at least on Windows.

`pm2 monit` doesnt show any logs:

![image](https://user-images.githubusercontent.com/12949236/169646014-ff58b159-c97c-46bb-ac96-5743f62a257d.png)

`pm2 log` shows logs correctly:

![image](https://user-images.githubusercontent.com/12949236/169646059-2a6ce7c5-e701-41ed-96ab-bd5f32817318.png)

**Comment by sourcec0de** [comment]
Same issue

**Comment by yofisim** [comment]
Same issue for me here. `pm2 monit` doesn't show live logs per instance.

**Comment by DarinDev1000** [comment]
Same issue

**Comment by prenaux** [comment]
Same issue on macOS 12.4.1 (M1 mbp)
pm2 version 5.2.0

**Comment by Vandomas** [comment]
same, ubuntu 20, pm2 5.2.0

**Comment by WouterVanHecke** [comment]
Why is this issue closed with so many people having this issue?

**Comment by walker0643** [comment]
I have this issue as well. "pm2 logs" works, "pm2 monit" does not show logs.

PM2 5.2.2 on Debian 11.

**Comment by hyungseon88** [comment]
I have this issue too, "pm2 logs" show log, "pm2 monit" not show log

pm2 5.2.2 on macOS 12.6

**Comment by ArtiomLiakh** [comment]
![image](https://user-images.githubusercontent.com/70390197/210263648-b87a9a1b-542e-4865-bc29-eea2c5161623.png)
Same
`pm2 start app.js --name Bot --time --log /logs`

**Comment by Emmet-v15** [comment]
Why is this closed?, There are still no logs for me and it's been 4 years since this issue has been opened

**Comment by hyroqi** [comment]
I think this is what y'all call "sweeping it under the rug" hahaha

**Comment by tasdflkjweio** [comment]
@hyroqi It seems like `pm2` isn't maintained anymore. All of the unanswered questions on their official docs pages and closed-yet-unaddressed issues in git.

**Comment by splurgebudget** [comment]
I see logs in `pm2 monit` using version `5.2.2`... but only NEW log stuff (since running `monit`) shows up.

What I mean is: `pm2 monit` does not show _historical_ logs... it only shows log entries _while it is running_.

**Comment by splurgebudget** [comment]
@tasdflkjweio : I'm not sure what gives you the impression pm2 isn't maintained anymore.  Just look at the commit history: https://github.com/Unitech/pm2/commits/master .   There are already several commits from 2023 (and many in 2022)... including merging external PRs.

**Comment by kutovoy** [comment]
4 years and counting, same issue (pm2 monit shows no logs while pm2 logs and pm2 report shows logs).

pm2 version 5.3.0

pm2 monit used to work until I updated node with nvm and switched to ecosystem config file. Unfortunately I was changing a lot of stuff during the day so I didn't notice what exactly made it broke...

**Comment by kubre** [comment]
On Windows, pm2 logs correctly
![image](https://github.com/Unitech/pm2/assets/20380094/c48e8276-335b-4488-9a0f-bc922c6647f7)

**Comment by Emmet-v15** [comment]
I don't see any logs in that screenshot

**Comment by kubre** [comment]
> I don't see any logs in that screenshot, specifically the output of the application, which is probably the 2 year old bug OP was talking about

Oh I meant `pm2 logs` command works well, and `pm2 monit` fails

**Comment by Emmet-v15** [comment]
> @tasdflkjweio : I'm not sure what gives you the impression pm2 isn't maintained anymore.  Just look at the commit history: https://github.com/Unitech/pm2/commits/master .   There are already several commits from 2023 (and many in 2022)... including merging external PRs and even releasing version 5.3.0 a month ago.

The fact that this hasn't been fixed is probably, what gives them the impression

**Comment by splurgebudget** [comment]
@Emmet-v15 @kubre : did you try actually making something happen in the log while you had `pm2 monit` up?

When I first run `pm2 monit` the logs are blank... but as soon as I do anything that generates log entries they show up.

Here is an example (with pm2 5.2.2):

<img width="1037" alt="image" src="https://github.com/Unitech/pm2/assets/124757361/6f6378bf-dbec-4688-8a2d-e80760fc144e">

**Comment by kutovoy** [comment]
Yes I did. This issue is still happening a lot and I didn't have it before. My apps are generating a lot of output but its only visible in ~/.pm2/pm2.log most of the time. Issue is on and off but is happening a lot.

**Comment by Emmet-v15** [comment]
> @Emmet-v15 @kubre : did you try actually making something happen in the log while you had `pm2 monit` up?
> 
> When I first run `pm2 monit` the logs are blank... but as soon as I do anything that generates log entries they show up.
> 
> Here is an example (with pm2 5.2.2):
> 
> <img width="1037" alt="image" src="https://github.com/Unitech/pm2/assets/124757361/6f6378bf-dbec-4688-8a2d-e80760fc144e">
> 

Even so, this is not the expected behaviour, i have better things to do on my server y
than keep that dashboard open at all times

**Comment by kubre** [comment]
@splurgebudget pm2 logs do display and not pm2 monit, and only nothing appears inside monit. Yes the server is generating logs while this is happening

**Comment by kutovoy** [comment]
Can we please have this resolved or at least issue reopened? Any information we need to provide? I am unfortunately planning to look for another solution where I can see logs and where github issues are not incorrectly closed when the issue is not resolved. PM2 is otherwise a great tool that I love - I would rather keep using it but problem with logs not showing up is affecting troubleshooting especially when servers/apps have issues. Thanks in advance!

**Comment by yemreak** [comment]
I've come up with a workaround, although it's a bit unconventional. You can utilize tmux and execute pm2 monit. After that, hit Control + B + D to go back, and pm2 monit will continue running in the background. Meanwhile, you can run all your other pm2 commands while the tmux session is active. Finally, use only tmux a command instead of pm2 monit to see logs (tested)

https://github.com/Unitech/pm2/issues/5325#issuecomment-1714914329

**Comment by splurgebudget** [comment]
BTW: I don't really use `pm2 monit` much anymore.  Just `pm2 log` works great.  Use `--lines <n>` to see back into the log of any running process... and continue to monitor that log.

**Comment by JP-HoneyBadger** [comment]
I have the same issue, just deployed my first nextjs app router website.  If a monitor is open and you stop and then start, it will show that first load, then nothing else is shown.  If you open the monitor while it is running, normal use, it is blank and nothing ever show.

**Comment by aaditya45** [comment]
any solution yet????????

**Comment by kodmanyagha** [comment]
```bash
pm2 restart all
pm2 monit
```

and logs are coming. Interesting. This isn't the real solution but works for now. Please fix this folks...

**Comment by otoinsa** [comment]
I still see the same problem
tried on CentOS
macOS
and FreeBSD

pm2 monit wont show logs for selected instances even if events are logged
this can be confirmed at looking at the logs, but pm2 logs will display them
monit will not however

**Comment by kutovoy** [comment]
Can we please at least have this issue reopened (if not fixed)?

**Comment by anshvert** [comment]
> ```shell
> pm2 restart all
> pm2 monit
> ```
> 
> and logs are coming. Interesting. This isn't the real solution but works for now. Please fix this folks...

This worked for some reason

**Comment by zackees** [comment]
Yeah, hitting this issue. Sometimes the logs show and sometimes not.

This is happening with python apps.

**Comment by Emmet-v15** [comment]
Yeah, you have to put --logs ./a/path when you register it and it shows
logs.

**Comment by zackees** [comment]
No the process is actually is hanging. | tee is showing no output is getting to the log.

I found a work around, have a run.py that just has os.system to invoke the real thing

**Comment by zackees** [comment]
Is this a problem with the way pm2 forks a process? My app has a bunch of locks that are getting loaded at python init time, including one for a locked_print function.

Is it possible that this lock is loading up then the process is forked? If so, this would explain the deadlock at startup. A process copied lock would have bad information that would never allow it to be acquired.

If so, then the fix i presented with just an os.system shim to invoke the command would explain why it works now.

**Comment by ZedUnknown** [comment]
Frustrating enough, I found the solution is to run `pm2 monit` before running `pm2 restart all` in a separate terminal.
