### ISSUE TITLE
Error: spawn ..\Roaming\npm\node_modules\pm2\node_modules\.bin\ts-node ENOENT

### ISSUE THREAD

**Issue by yeongjet** [Unitech/pm2#4263]
## What's going wrong?
After running `pm2 install typescript` and `pm2 start hello.ts` got this error.
pm2 is global installed on win10, have check these issues: #2742 #3312 #2675 but haven't solve it.
 `C:\Users\me\AppData\Roaming\npm\node_modules\pm2\node_modules\.bin\ts-node` is exists.

## Supporting information

$ pm2 report
```
PM2        | 2019-04-30T03:45:22: PM2 log: Stopping app:hello id:25
PM2        | 2019-04-30T03:45:22: PM2 error: app=hello id=25 does not have a pid
PM2        | 2019-04-30T03:45:49: PM2 log: App [hello:26] starting in -fork mode-
PM2        | 2019-04-30T03:45:49: PM2 log: App [hello:26] online
PM2        | 2019-04-30T03:45:49: PM2 error: Error: spawn C:\Users\me\AppData\Roaming\npm\node_modules\pm2\node_modules\.bin\ts-node ENOENT
PM2        |     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:19)
PM2        |     at onErrorNT (internal/child_process.js:431:16)
PM2        |     at processTicksAndRejections (internal/process/task_queues.js:84:17)
PM2        | 2019-04-30T03:45:49: PM2 error: Cancelling versioning data parsing
```

But it's running successful under the cluster mode: `pm2 start .\hello.ts -i max`

**Comment by Falagan** [comment]
+1

**Comment by tzjoke** [comment]
I'm facing the same problem. It was OK several months ago.

@yeongjet @Falagan Have you solved the problem?

**Comment by yeongjet** [comment]
@tzjoke No, I think it should run with cluster mode.

**Comment by tzjoke** [comment]
@yeongjet Well, now it does work under cluster mode but it worked well with fork mode before for sure. Weird...

**Comment by ginus** [comment]
+1

**Comment by chenwenqin** [comment]
+1

**Comment by Ryuurock** [comment]
???? @Unitech

**Comment by Dep0sit** [comment]
This still happens, has anyone found fixes? Please tag me if you have.

**Comment by fourwadu** [comment]
Any luck, guys? Still having this issue

**Comment by zwift-tuan** [comment]
Having the same issue on windows but not on linux. Anyone have any luck?

**Comment by albaylood1437** [comment]
> +1

what do you mean

**Comment by ysfaran** [comment]
It feels like the devs really don't care about windows issues at all.. I'm trying to use pm2 so bad but there is always an issue specifically related to windows..

most of the issues are already open for more than two years and there is still no response from the devs

**Comment by GunasekaranR** [comment]
Hi Team,
Iam also facing the issue when trying to run the typescript with the Pm2. Any one has any solution please suggest.

Before executing I have installed 
pm2 install typescript

Command used to execute the script:
pm2 start index.ts .env.staging --name aman-user-service

![image](https://user-images.githubusercontent.com/25734231/153267078-29f17ea0-4440-4a4d-95dc-2abb05602cc9.png)

**Comment by DarioKolic** [comment]
If anyone needs a potential solution (it solved my ts-node problem)
Make sure you have *typescript* installed in pm2

### For current working directory: 
`npm i --save-dev pm2`

### In package.json add a script:
`"postinstall": "pm2 install typescript"`

This will install typescript globally or in current working directory to pm2 `node_modules` when you run `npm install`
If you have global and don't want a script just run it

### Finally change `exec_mode` to `cluster`
For some reason `exec_mode: "fork"` does not work with ts-node

Your `script` file can now be `.ts`
