### ISSUE TITLE
catch some TCP connect to  ****rev.poneytelecom.eu while startup pm2

### ISSUE THREAD

**Issue by woniu1983** [Unitech/pm2#4273]
While pm2 startup, we use wireshark and catch some strange tcp data to  ip 163.*.

use nslookup and found it lead to ****rev.poneytelecom.eu,
Everybody who knows about this issue？

Why and where it be called in pm2 ?  
Can we stop this call ?

**Comment by Unitech** [comment]
Have you linked pm2 runtime to [pm2.io](https://pm2.io)?

**Comment by woniu1983** [comment]
> Have you linked pm2 to [pm2.io](https://pm2.io)?

No, i didn't conntct to the pm2.io (pm2 plus).
I used the pm2 version 2.6.x, does it default enable the monitor?

**Comment by woniu1983** [comment]
> Have you linked pm2 to [pm2.io](https://pm2.io)?

We just use the PM2  Runtime, seems not include the monitor....

**Comment by Unitech** [comment]
Weird, I do not remember having done any query on a server with PM2 2.0
Anyway if PM2 3.x fix the issue that's good, closing the issue

**Comment by AAber** [comment]
The connection to rev.poneytelecom.eu is due to the pm2 Keymetrics link connection that is enabled.
To disable the connection run:
``pm2 link delete``
