### ISSUE TITLE
Error in node 4.x due to debug dependency

### ISSUE THREAD

**Issue by gpcastro** [Unitech/pm2#4278]
## What's going wrong?
PM2 is failing in Node 4.x versions. It outpus the following error:

```
/usr/local/lib/node_modules/pm2/node_modules/needle/node_modules/debug/src/node.js:132
        let val = process.env[key];
        ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```
## How could we reproduce this issue?
Install and run PM2 (e.g. `pm2 --version`) on a Node 4.x environment. 

## Supporting information
The dependency of `needle` is specified using `^2.2.1`, which if installed recently downloads version `2.3.1`. That version of needle depends on package `debug` version `4.1.0`, which does not support Node 4.x (and [won't](https://github.com/visionmedia/debug/issues/611)). So one way to fix the issue is to change `needle` dependency to `~2.2.1` instead.

There's a [issue](https://github.com/tomas/needle/issues/278) on needle as well.

**Comment by Unitech** [comment]
we do not support Node 4 anymore with pm2 3.x
Use pm2 2.x if you need support for node 4

**Comment by gpcastro** [comment]
The documentation needs to be updated then. On the [npm](https://www.npmjs.com/package/pm2) page is says: 
> Works on Linux (stable) & macOS (stable) & Windows (stable). All Node.js versions are supported starting Node.js 4.X.
