### ISSUE TITLE
Programmatically setting pm2-logrotate parameters

### ISSUE THREAD

**Issue by vthil3049** [Unitech/pm2#4283]
I'm writing a server admin app in ElectronJS. I'm using pm2-logrotate to manage my application.
The CLI works great for managing the log files, but I now have the need to manage the max_size and retain values, using this Admin app. Is there a way to programmatically change these parameters?

## 
Currently I have code in my app which does this in a clunky way, by running an exec like this:
```
exec('pm2 set pm2-logrotate:retain '+newRetainValue, (erro) => {
      if (error) {
        console.log(error);
        return;
      }
     console.log('Changed retain value');
})
```
## 
Is there a better way to do this? I'm using pm2 v3.2.9.

## 

Thanks in advance for any help or suggestions.

**Comment by Unitech** [comment]
https://github.com/Unitech/pm2/blob/development/test/programmatic/resurect_state.mocha.js#L46
