### ISSUE TITLE
pm2 repo isn't available

### ISSUE THREAD

**Issue by AmetPreply** [Unitech/pm2#4289]
## What's going wrong?

```
error https://tgz.pm2.io/gkt-1.0.0.tgz: Request failed "503 Service Unavailable"
```

**Comment by bradennapier** [comment]
Destroying us right now... wow.  Worst possible time to break your product completely.

**Comment by AmetPreply** [comment]
We made a fix for that in our Dockerfiles. Maybe it will be helpful for some people:
<img width="539" alt="Screen Shot 2019-05-23 at 13 15 21" src="https://user-images.githubusercontent.com/39903467/58245149-d70e1b80-7d5c-11e9-9a77-0336e8333558.png">

**Comment by Eywek** [comment]
Should be fixed, sorry for the inconvenience

**Comment by lukejacksonn** [comment]
Having `gkt` as an optional dependency (which can't be ignored as part of a recursive install) that lives on a server outside of the npm ecosystem is irresponsible. What makes it worse is that `gkt` does nothing but `console.log('Smarty Smart Smarter');` 👎

**Comment by bradennapier** [comment]
I sure hope it doesn't just log some random text?  A post from a few years ago seems to indicate that it is used from analytics.

**Comment by jevakallio** [comment]
> I sure hope it doesn't just log some random text?

Indeed it does. The code is never executed, so it doesn't matter what it does. I believe pm2 are logging the http requests to the tarball for analytics purposes to find out who, when and where is downloading their package.

I'm not the judge on whether that's a good idea to begin with (seems like a potential security hole), but if the service is not reliable and results in failing builds, it's definitely not a responsible approach.

**Comment by bradennapier** [comment]
Seems it is unlike that would even provide any details that are really helpful anyway since it probably largely just shows installs that come from devops servers and such. I'm not in Canada or Ireland and 90% of my installs probably look like they come from there... lol

**Comment by zuopf769** [comment]
we use --ignore-optional params hanle this question
yarn install --production=false --ignore-optional;

**Comment by AmetPreply** [comment]
Looks like it works.
I'm closing this issue.

**Comment by DanielRuf** [comment]
> Should be fixed, sorry for the inconvenience

So you still fetch from your own domain to count the downloads and installs? Interesting approach for tracking for sure ;-)

> Having `gkt` as an optional dependency (which can't be ignored as part of a recursive install) that lives on a server outside of the npm ecosystem is irresponsible.

Exactly. This is not ok and can break anytime in the future again. And this is not rare: https://github.com/Unitech/pm2/issues/4289#issuecomment-495157865

**Comment by jevakallio** [comment]
@AmetPreply any chance you could do something about this so that it doesn't keep recurring? This is not the first time this has happened.

**Comment by Eywek** [comment]
> So you still fetch from your own domain to count the downloads and installs? Interesting approach for tracking for sure ;-)

You can found some explanations here https://github.com/keymetrics/gkt, I'm not the maintainer of PM2, it's not my job to decide of changes like that sorry

**Comment by AmetPreply** [comment]
@jevakallio I'm not related to pm2, I'm just a usual engineer who has got errors in CI and reported this issue :)

**Comment by DanielRuf** [comment]
No info about what they collect (IP addresses are personal data and can be only stored anonymized - GDPR and other regulations forbid the collection of such data without letting the users know and without any anonymization).

**Comment by Eywek** [comment]
https://pm2.io/legals/privacy_policy.pdf

**Comment by DanielRuf** [comment]
> pm2.io/legals/privacy_policy.pdf

Looks more like this describes only what you do on pm2.io, not in the cli (and if IP addresses are stored in full or anonymized for example by removing the last octet or block). Or I oversaw these details there.

**Comment by ryanolee** [comment]
https://tgz.pm2.io/gkt-1.0.0.tgz Looks to have gone back down again :(

**Comment by manast-apsis** [comment]
incredible...

**Comment by zamiang** [comment]
Is there a workaround for this for people using npm instead of yarn? This blocked builds / deployments for us and is not acceptable going forward.

**Comment by Unitech** [comment]
This optionalDependency is not really optional from what I can conclude...
I dropped the external package and published pm2 on 3.5.1

**Comment by Unitech** [comment]
I will provide more information about this GKT package today.

Just to let you know that this allow us to count download, crunch analytics and also have this Dashboard to track downloads: https://map.keymetrics.io/

**Comment by arcanis** [comment]
> This optionalDependency is not really optional from what I can conclude...

The `optionalDependency` field was always about making the *build* optional (basically, if the package build doesn't support the platform then it's still fine; possible because you have a fallback). If the package can't be fetched it's still an error (because then we don't even know whether the package exists in the first place).

The `gtk` always was a hack and it's not the first time we've mentioned it. If you want stats then open an issue on npm and Yarn to ask for your use case to be officially recognized (while I admit it'll be a tough sell considering you're the only package I know using this pattern).

**Comment by DanielRuf** [comment]
Maybe you can use `/etc/hosts` to route the requests to somewhere else which returns a statuscode of `200`.

**Comment by DanielRuf** [comment]
Is there some original discussion about this? Would like to know why a postinstall script or some CLI flag or other solution was not used for this.

**Comment by Unitech** [comment]
@DanielRuf we gonna find another way. My main concern is that pm2 runtime works properly for now, so we can skip analytics. There is no more external module on pm2@3.5.1

Just install the latest version:

```bash
$ npm install pm2@latest -g
```

**Comment by DanielRuf** [comment]
Sounds good =)

And thanks for publishing a new release without this package.

Maybe the telemetry plugin solution of Gatsby gives some ideas. https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/telemetry.md

But this should be maybe optin. At least I have enough info what they collect and how and how I can prevent this.

**Comment by Unitech** [comment]
That's excellent, thanks for sharing

**Comment by CharlotteDunois** [comment]
> 
> With PM2 I always kept privacy first and never retrieved any user data, that is always my priority.

Dialing home using a package is quite the opposite of "privacy first". There is absolutely no transparency what is collected using this hack.

**Comment by DanielRuf** [comment]
Hi @CharlotteDunois 

the optional dependency is removed in the latest release and the team is thinking about a better approach.

> @DanielRuf we gonna find another way. My main concern is that pm2 runtime works properly for now, so we can skip analytics. There is no more external module on pm2@3.5.1

**Comment by dmitriz** [comment]
@Eywek
> You can found some explanations here https://github.com/keymetrics/gkt, I'm not the maintainer of PM2, it's not my job to decide of changes like that sorry

That repo seems to have moved to a new home :-)
https://web.archive.org/web/20180617144122/https://github.com/keymetrics/gkt

**Comment by Eywek** [comment]
Maybe because the dependency was removed

**Comment by dmitriz** [comment]
Not from 8 other packages, some of which closely resemble `pm2`:
https://www.npmjs.com/browse/depended/gkt

**Comment by Eywek** [comment]
Sorry I’m not at the origin of that decision

**Comment by DanielRuf** [comment]
@dmitriz these seem to be old forks. Their maintainers have to change this.
