### ISSUE TITLE
Pm2 cluster runs cron job for multiple times

### ISSUE THREAD

**Issue by itsaakashpatel** [Unitech/pm2#4292]
## What's going wrong?

Hey Pm2 team,

In my project, PM2 is running on cluster mode. I set up the cron job and it runs for multiple times or maybe a number of active threads times.

What could be the possible solution to resolve this issue?

Thanks!

**Comment by itsaakashpatel** [comment]
@Unitech @jshkurti  Can you help me to solve this issue?

Thanks!
Aakash

**Comment by danihenrique** [comment]
Hello!

Every cluster process has your own ID (process.env.pm_id)

For example:
api | 0 | cluster | online
api | 1 | cluster | online
api | 2 | cluster | online

So, you can make a check inside your code when is necessary to avoid multiples verifications.
if (process.env.pm_id === '0') {
 // Do your cronjob here.
}

**Comment by Unitech** [comment]
x x https://github.com/Unitech/pm2/issues/4485
