### ISSUE TITLE
Watch is not saved

### ISSUE THREAD

**Issue by Code8525** [Unitech/pm2#4293]
watching path is not saved.

pm2 start /var/www/app/server.js  --watch=/var/www/app/
pm2 stop 0
pm2 start 0

![image](https://user-images.githubusercontent.com/22520032/58306557-0f2d6100-7e26-11e9-89ae-cb6bd945e375.png)

**Comment by sergeymorkovkin** [comment]
According to the documentation, it's a boolean switch. For specifying a directory of multiple directories you should use an ecosystem file. But it doesn't work either.
