### ISSUE TITLE
--experimental-modules flag doesn't work with node 12

### ISSUE THREAD

**Issue by trofima** [Unitech/pm2#4295]
--experimental-modules flag doesn't work with node 12

pm2 version is 3.5.1  

SyntaxError: Unexpected token {

**Comment by netoec84** [comment]
I have the same problem in pm2 3.5.0 with node v12.0.0. I try with follow confing file

`{
  "apps": [
    {
      "script": "app.js",
      "name": "APP",
      "interpreter_args": [
        "--experimental-modules",
        "--no-warnings"
      ]
    }
  ]
}`
