### ISSUE TITLE
Shared config?

### ISSUE THREAD

**Issue by georgyfarniev** [Unitech/pm2#4305]
Hello. Thanks for working on this useful tool. 

I have many applications in single ecosystem.config.json, and it's unclear from documentation how to set shared configuration for multiple apps. For example, I need to supply same environment variables to all apps. How can I achieve it?

**Comment by ketozhang** [comment]
(adding a comment to remove stale) Beyond sourcing a shared external env file, I don't see any way to do this. Is there a JS way to do this, like defining a variable storing shared env and then merging it to every app env?
