### ISSUE TITLE
Duplicate processes if start command called while start command is already running

### ISSUE THREAD

**Issue by KyleJune** [Unitech/pm2#4311]
## What's going wrong?

If start command is issued twice, the second start command will restart the processes that have been started so far by the first start command call then spawn duplicates of all the processes that still need to be prepared.

There should be a safeguard in the CLI.start command to prevent duplicate processes from being spawned in the event that start is called while PM2 was still starting. This issue was difficult to track down because in our case, we had many processes that use a lot of resources, when PM2 started double the number of processes that we wanted, the system would get overloaded and require us to manually restart it.

## How could we reproduce this issue?

Have a cluster with multiple apps in the ecosystem json file.
Run pm2 start then run it again while the first pm2 start command is still starting processes up.
You can make the issue easier to produce by adding a delay of a few seconds to the callback so that it takes longer to start.

The start script does not create a lock, so multiple start command calls could be made while it is already starting. If no processes were prepared yet at the time of the second call, it will create a double of all the instances. If some processes were prepared at the time of the second call, those will be restarted then the remaining ones will get started by both the first and second command.

In my supporting information below, there should be 2 appA, 2 appB, 2 appC, and 1 appD. The second start command was issued after appA and appB had been prepared already, so those processes just got restarted. Then we end up with double the number of appC and appD than we wanted. Our apps are node apps, the duplicates have the same process.env.NODE_APP_INSTANCE values as the processes created by the first pm2 start command.

The reason why this happened for us is that we have a script that stops and starts PM2 with a delay between them. During the time between stopping and starting our monit.d detected PM2 was not running and restarted it. Then our script that was waiting before doing pm2 start would call the command a second time.

## Supporting information

I removed some information from the report below but it has the important information in it.
```
$ pm2 report
===============================================================================
--- PM2 REPORT (Fri Jun 07 2019 13:46:36 GMT-0700 (PDT)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.10.4
node version         : 4.2.3
node path            : undefined
argv                 : /var/REMOVED/bin/node-v4.2.3/bin/node,/home/kylej/REMOVED/node_modules/pm2/lib/Daemon
.js
argv0                : undefined
user                 : www
uid                  : 33
gid                  : 33
uptime               : 0min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.10.4
node version         : 4.2.3
node path            : undefined
argv                 : /var/REMOVED/bin/node-v4.2.3/bin/node,/home/kylej/REMOVED/node_modules/.bin/pm2,repor
t
argv0                : undefined
user                 : www
uid                  : 33
gid                  : 33
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Core(TM) i5-7440HQ CPU @ 2.80GHz
cpus nb              : 2
freemem              : 2179817472
totalmem             : 10466934784
home                 : /var/www
===============================================================================
--- PM2 list -----------------------------------------------
┌────────────┬────┬─────────┬───────┬────────┬─────────┬────────┬─────┬────────────┬──────────┬──────────┐
│ App name   │ id │ mode    │ pid   │ status │ restart │ uptime │ cpu │ mem        │ user     │ watching │
├────────────┼────┼─────────┼───────┼────────┼─────────┼────────┼─────┼────────────┼──────────┼──────────┤
│ appC │ 4  │ cluster │ 13749 │ online │ 0       │ 37s    │ 0%  │ 106.0 MB   │ www │ disabled │
│ appC │ 6  │ cluster │ 13776 │ online │ 0       │ 34s    │ 0%  │ 103.8 MB   │ www │ disabled │
│ appC │ 8  │ cluster │ 13802 │ online │ 0       │ 31s    │ 0%  │ 103.6 MB   │ www │ disabled │
│ appC │ 9  │ cluster │ 13811 │ online │ 0       │ 29s    │ 0%  │ 103.9 MB   │ www │ disabled │
│ appA │ 1  │ cluster │ 13717 │ online │ 1       │ 38s    │ 0%  │ 125.9 MB   │ www │ disabled │
│ appA │ 3  │ cluster │ 13722 │ online │ 1       │ 38s    │ 0%  │ 123.5 MB   │ www │ disabled │
│ appB     │ 0  │ cluster │ 13712 │ online │ 1       │ 38s    │ 0%  │ 106.1 MB   │ www │ disabled │
│ appB     │ 2  │ cluster │ 13744 │ online │ 1       │ 37s    │ 0%  │ 106.6 MB   │ www │ disabled │
│ appD   │ 5  │ cluster │ 13754 │ online │ 0       │ 37s    │ 0%  │ 103.0 MB   │ www │ disabled │
│ appD   │ 7  │ cluster │ 13777 │ online │ 0       │ 34s    │ 0%  │ 103.3 MB   │ www │ disabled │
└────────────┴────┴─────────┴───────┴────────┴─────────┴────────┴─────┴────────────┴──────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/var/pm2/pm2.log last 20 lines:
PM2        | [2019-06-07 13:45:58] PM2 log: pid=13677 msg=failed to kill - retrying in 100ms
PM2        | [2019-06-07 13:45:58] PM2 log: pid=13677 msg=failed to kill - retrying in 100ms
PM2        | [2019-06-07 13:45:58] PM2 log: pid=13677 msg=failed to kill - retrying in 100ms
PM2        | [2019-06-07 13:45:58] PM2 log: App name:appA id:2 disconnected
PM2        | [2019-06-07 13:45:58] PM2 log: App [appA] with id [2] and pid [13677], exited with code [1] via signal [SIGINT]
PM2        | [2019-06-07 13:45:58] PM2 log: pid=13677 msg=process killed
PM2        | [2019-06-07 13:45:58] PM2 log: Starting execution sequence in -cluster mode- for app name:appA id:2
PM2        | [2019-06-07 13:45:58] PM2 log: App name:appA id:2 online
PM2        | [2019-06-07 13:45:58] PM2 log: Starting execution sequence in -cluster mode- for app name:appC id:4
PM2        | [2019-06-07 13:45:58] PM2 log: Starting execution sequence in -cluster mode- for app name:appD id:5
PM2        | [2019-06-07 13:45:59] PM2 log: App name:appD id:5 online
PM2        | [2019-06-07 13:45:59] PM2 log: App name:appC id:4 online
PM2        | [2019-06-07 13:46:01] PM2 log: Starting execution sequence in -cluster mode- for app name:appC id:6
PM2        | [2019-06-07 13:46:01] PM2 log: Starting execution sequence in -cluster mode- for app name:appD id:7
PM2        | [2019-06-07 13:46:01] PM2 log: App name:appC id:6 online
PM2        | [2019-06-07 13:46:01] PM2 log: App name:appD id:7 online
PM2        | [2019-06-07 13:46:04] PM2 log: Starting execution sequence in -cluster mode- for app name:appC id:8
PM2        | [2019-06-07 13:46:04] PM2 log: App name:appC id:8 online
PM2        | [2019-06-07 13:46:06] PM2 log: Starting execution sequence in -cluster mode- for app name:appC id:9
PM2        | [2019-06-07 13:46:06] PM2 log: App name:appC id:9 online
```

**Comment by kawadhiya21** [comment]
this is still an issue. I am facing this.

**Comment by estoylive** [comment]
same here

**Comment by estoylive** [comment]
i had to start with the id number, if I use it fail name it will start it 2 times

**Comment by shaobaili3** [comment]
still have the same issue 

please fix it ASAP

had to delete all and start one by one to prevent this issue

😭😭😭

**Comment by webbyus** [comment]
still have the same issue (2023)

**Comment by dkduyanh** [comment]
I face this issue when running my app under Pm2 and AlpineLinux

**Comment by Aqitaniya** [comment]
The same issue. I think it's depend of count CPU kernels. Who know is it normal? Or need to be only one process ?

**Comment by anwarhamr** [comment]
I have this problem w/ the API.  Doing a start multiple times with the same name creates duplicate processes.  I've tied to query the pm2.list function but they must not be started or in that list by the time the next start is requested.  I've tried to manage this other ways w/ memory queues but something the the timing of when it starts.  Any chance of getting a start option w/ "UniqueName" or something that would disallow a start of two processes.
