### ISSUE TITLE
pm2 trigger commands of heapdump and heap memory sampling returns ok with no dumps

### ISSUE THREAD

**Issue by AmitPhulera** [Unitech/pm2#4314]
Hi.

I was trying to profile my node based app running with pm2.

I came across **pm2 describe <appid>** command which displays these "Actions available" list with following options 

- km:heapdump
- km:cpu:profiling:start
- km:cpu:profiling:stop
- km:heap:sampling:start
- km:heap:sampling:stop

First of all, are these some default actions that pm2 provides as I didn't find any documentation regarding them on website.
Second, I tried heap dump and heap sampling and got a success:true output in both the cases but no dump file was created in ~/.pm2. 

I find this feature pretty cool, I just wanted to know that if am I missing something here?
It would be really helpful if you can tell me how am I supposed to use it?
Thanks.

**Comment by EddieOne** [comment]
You need to pay for keymetrics, they tend to always increase the price. If you have one of the old plans, you will find they also removed this even for paying customers.

**Comment by AmitPhulera** [comment]
Then option should be removed from CLI I guess :thinking: 
It is just creating confusion and will probably cause a lot wasted efforts.

**Comment by EddieOne** [comment]
I ended up using this. https://www.npmjs.com/package/heapdump

**Comment by RealYukiSan** [comment]
i've no idea what this command do:

```
[user@server ~]$  pm2 trigger main km:heapdump
1 processes have received command km:heapdump
[main:0:default]={"success":true}
```

would be great if there's any documentation about it.
