### ISSUE TITLE
pm2 hangs every time with express api + prom-client

### ISSUE THREAD

**Issue by shubh-07** [Unitech/pm2#4323]
I am using pm2 to run multiple express and micro-service API's.
In one of the express API's i am using prom-client(Prometheus client for node.js) to return prometheus metrics for that API.
I have created a /metrics route in the express API which aggregate metrics from all the instances and returns metrics for the API. 
Prometheus is a pull system so it scrapes data from that API every minute(default duration).
Now the system works perfectly fine for 4-5 days when scrape duration is 1 min but after that PM2 hangs for indefinite time resulting in blocking of all the API's running through PM2 on the system.

I also tested this scenario by reducing scrape duration to 5 sec. And after that i noticed pm2 got hung in 4-5 hours. 

pm2 -v  - 3.5.0
node -v - 8.11.4
prom-client -v - latest

**Comment by lucasyvas** [comment]
I'd be interested to know what you find about this. I have a similar problem with pm2 on Windows Server (potentially).

The reason I think it is PM2 is that I have multiple express services running under PM2, some of which I KNOW are not even being it. During the "hang" phase, even the APIs not being used become unreachable. My initial thought was this was a memory problem on my end, but this piece of evidence does not line up with that.

I'm going to try removing PM2 from the equation and replace it with Windows services to see if the result is different. For me, the hang is at the same time almost every day, regardless of load.

**Comment by shubh-07** [comment]
Yes that was exactly the issue I was facing. My findings related to this issue were - It completely utilizes the RAM of the system for around couple of minutes reaching a deadlock and after this duration the pm2 hangs & then not responding through its cli, all the api's running through it becomes unstable and along with that it hangs all the other services too which are running on the server (e.g tomcat, grafana, influx, etc.). 
Also when I did load testing on the api's running through pm2, i hit around 1000 requests per minute in 5-6 different api's. It showed me very unusual behaviour. The system got hanged within 15 minutes after and that made me certain that the issue is related to memory only. The situation could be that pm2 functions while executing takes up memory (ram and heap) and after completing there functionality they are not freeing up the resources(space) they have taken from RAM manually and left this on nodejs system only (Node js calls garbage collector function automatically after some duration.) and that causes system to utilize memory very fast.

**Comment by lucasyvas** [comment]
In my case, it was PM2 as well. I replaced it with NSSM on Windows server for a client. Low and behold, it now runs flawlessly with zero code changes. It's a little less convenient, but hey, it works pretty damn well. I appreciate the work put into PM2, however I don't see a need to use it again after this 6 month on/off troubleshooting.
