### ISSUE TITLE
SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by Eluminati** [Unitech/pm2#4331]
I searched for another bug and found #3211 but this seems to be another bug...

## What's going wrong?
I am creating my ecosystem.config.js dynamically and if I start my app everything is fine. But when I change a file or my app crashes, then pm2 crashes when trying to restart my app. If I kill pm2 and start it manually, everything works fine until the next restart.

The traceback is the following:

```
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    2019-06-23T17:13:05: PM2 log: App name:GameServer id:0 disconnected
at Object.<anonymous> (D:\Atom_projects\Game\node_modules\pm2\lib\ProcessContainer.js:17:20)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:868:12)
    at internal/main/run_main_module.js:21:11
undefined:1
undefined
^
```
my ecosystem.config.js looks like this:

```javascript
/* eslint-disable camelcase */
// Options reference: https://pm2.io/doc/en/runtime/reference/ecosystem-file/
const defaults = {
    instances: 2,
    autostart: true,
    restart_delay: 5000,
    max_restarts: 3,
    watch: "out/app",
    watch_options: {
        "followSymlinks": false
    },
    ignore_watch: [
        "out/app/client",
        "out/app/config",
        "out/app/server/config"
    ],
    log: false,
    merge_logs: true,
    source_map_support: true,
    max_memory_restart: '1G'
};
const gameServer = Object.assign({}, defaults, {
    name: 'GameServer',
    "node_args": ["--inspect=7000"],
    script: 'out/app/GameServer.js',
    pid_file: "var/pids/gameServer.pid",
    error: "var/logs/gameServerError.log",
    env: {
        NODE_ENV: 'development',
        PORT: 3000
    },
    env_production: {
        NODE_ENV: 'production',
        PORT: 8080
    }
});
const webServer = Object.assign({}, defaults, {
    name: 'WebServer',
    "node_args": ["--inspect=7001"],
    script: 'out/app/WebServer.js',
    pid_file: "var/pids/webServer.pid",
    error: "var/logs/webServerError.log",
    env: {
        NODE_ENV: 'development',
        PORT: 3001
    },
    env_production: {
        NODE_ENV: 'production',
        PORT: 8081
    }
});

module.exports = {
    apps: [gameServer, webServer]
};

```
I am using Windows 10 x64 and PM2 version 3.5.1

**Comment by ataft** [comment]
I'm getting the same thing all of a sudden too, not sure what changed to mess things up. Also Windows 10 x64, but PM2 version 2.10.1

**Comment by Eluminati** [comment]
Do you have something like "node_args": ["--inspect=7000"] in your config? After removing this it stopped crashing

**Comment by ataft** [comment]
Oddly enough, _adding_ node_args seems to have fixed it. This is the line in processContainer.js that's throwing the error:
```
// Load all env-vars from master.
var pm2_env = JSON.parse(process.env.pm2_env);
```

For some reason, `process.env.pm2_env` is not being loaded. I'm wondering if this has something to do with having pm2 installed both locally and globally. I have it locally for using the programmatic api, and globally for development.

**Comment by Eluminati** [comment]
It seems to be a Problem with the cluster mode. If I am running in fork mode everything is running well every time. Then I can use every config.

**Comment by zzclynn** [comment]
> Oddly enough, _adding_ node_args seems to have fixed it. This is the line in processContainer.js that's throwing the error:
> 
> ```
> // Load all env-vars from master.
> var pm2_env = JSON.parse(process.env.pm2_env);
> ```
> 
> For some reason, `process.env.pm2_env` is not being loaded. I'm wondering if this has something to do with having pm2 installed both locally and globally. I have it locally for using the programmatic api, and globally for development.

met this error as well, local and global running same time

**Comment by ataft** [comment]
It turns out that changing `node_args` didn't reliably solve the problem for me. Also, I need to use the `node_args`, so this would not be a viable solution.

I have been able to work around this reliably by starting my application with `node . start` instead of `npm run start`. My start script uses the programmatic api to call `pm2.start()`.

It's difficult to pinpoint the problem, but it seems clear that there are issues running multiple instances of pm2 apps on the same machine. As stated earlier, I'm on Windows 10 x64 and PM2 version 2.10.1. I tried upgrading PM2, but the problem persisted.

**Comment by gjovanov** [comment]
Hi gents,
I too have encountered the same problem on WIN10 with pm2 `4.2.1` version.

For some reason this:
`packages.json`
```json
{
  "scripts": {
   ...
    "dev:api:multi": "pm2 start server/api/index.js -i max --no-autorestart -f"
   ....
}
```

`npm run dev:api:multi`

throws the reported error: `SyntaxError: Unexpected token u in JSON at position 0` being thrown in:

ProcessContainer.js in line 16.

`var pm2_env = JSON.parse(process.env.pm2_env);`

However, if I run directly without `npm run`:
`pm2 start server/api/index.js -i max --no-autorestart -f`

then it works.


Any idea why is this happening?

Thanks.

**Comment by snialMr** [comment]
I had the same problem because of the "Git bash" terminal I was using
