### ISSUE TITLE
unable to run pm2 in jenkins

### ISSUE THREAD

**Issue by rajendar38** [Unitech/pm2#4336]
I have installed jenkins and  trying to run node js app, i am not getting error job was successful
but the application is not bootstrapping 

`Running as SYSTEM
Building in workspace /Users/Shared/Jenkins/Home/workspace/mysampleJob
No credentials specified
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/rajendar38/node-app.git # timeout=10
Fetching upstream changes from https://github.com/rajendar38/node-app.git
 > git --version # timeout=10
 > git fetch --tags --force --progress https://github.com/rajendar38/node-app.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision 99ac0a176e5970eef8c83c8684d57871e325cb37 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 99ac0a176e5970eef8c83c8684d57871e325cb37
Commit message: "simple node app with test 2"
 > git rev-list --no-walk 99ac0a176e5970eef8c83c8684d57871e325cb37 # timeout=10
[mysampleJob] $ /bin/sh -xe /Users/Shared/Jenkins/tmp/jenkins1650676890501354031.sh
+ export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/go/bin
+ PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/go/bin
+ npm install
audited 2468 packages in 4.383s
found 55 vulnerabilities (16 low, 19 moderate, 19 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
+ who am i
jenkins  tty??    Jun 29 20:59 
+ pm2 start index.js
[PM2] Spawning PM2 daemon with pm2_home=/Users/Shared/Jenkins/.pm2
[PM2] PM2 Successfully daemonized
[PM2] Starting /Users/Shared/Jenkins/Home/workspace/mysampleJob/index.js in fork_mode (1 instance)
[PM2] Done.
┌──────────┬────┬─────────┬──────┬───────┬────────┬─────────┬────────┬─────┬───────────┬─────────┬──────────┐
│ App name │ id │ version │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem       │ user    │ watching │
├──────────┼────┼─────────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼─────────┼──────────┤
│ index    │ 0  │ 0.0.2   │ fork │ 41576 │ online │ 0       │ 0s     │ 0%  │ 12.4 MB   │ jenkins │ disabled │
└──────────┴────┴─────────┴──────┴───────┴────────┴─────────┴────────┴─────┴───────────┴─────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
+ pm2 list
┌──────────┬────┬─────────┬──────┬───────┬────────┬─────────┬────────┬─────┬───────────┬─────────┬──────────┐
│ App name │ id │ version │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem       │ user    │ watching │
├──────────┼────┼─────────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼─────────┼──────────┤
│ index    │ 0  │ 0.0.2   │ fork │ 41576 │ online │ 0       │ 0s     │ 27% │ 33.2 MB   │ jenkins │ disabled │
└──────────┴────┴─────────┴──────┴───────┴────────┴─────────┴────────┴─────┴───────────┴─────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
+ pm2 status index.js
┌──────────┬────┬─────────┬──────┬───────┬────────┬─────────┬────────┬─────┬───────────┬─────────┬──────────┐
│ App name │ id │ version │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem       │ user    │ watching │
├──────────┼────┼─────────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼─────────┼──────────┤
│ index    │ 0  │ 0.0.2   │ fork │ 41576 │ online │ 0       │ 0s     │ 0%  │ 33.2 MB   │ jenkins │ disabled │
└──────────┴────┴─────────┴──────┴───────┴────────┴─────────┴────────┴─────┴───────────┴─────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
Finished: SUCCESS`

**Comment by JojiePalahang** [comment]
This is only my suggestion: 
What I did is to install pm2 during build process and when to run the application just the local pm2 like this 
`
bat 'node_modules\\.bin\\pm2 start ecosystem.config.js --env dev'
bat 'node_modules\\.bin\\pm2 reload all'
`

**Comment by beloappcomtest** [comment]
Is there any updates ?

**Comment by agiratech-gopal** [comment]
Its late but just help someone in need:

Issue: pm2 would have been installed with ***ubuntu*** user or ***root***, which Jenkins can't access

 - Login to Jenkins: `sudo su jenkins` (if password is required, set
   password from root user `sudo passwd jenkins`) 
 - Install PM2: `npm i -g
   pm2`

Now, Jenkins should be able to run pm2

**Comment by yijinc** [comment]
> Its late but just help someone in need:
> 
> Issue: pm2 would have been installed with _**ubuntu**_ user or _**root**_, which Jenkins can't access
> 
> * Login to Jenkins: `sudo su jenkins` (if password is required, set
>   password from root user `sudo passwd jenkins`)
> * Install PM2: `npm i -g pm2`
> 
> Now, Jenkins should be able to run pm2

thx & mark
