### ISSUE TITLE
gyp_main.py: error: no such option: --no-parallel

### ISSUE THREAD

**Issue by dibu28** [Unitech/pm2#434]
I have error installing pm2 package with 'npm install -g pm2' on Ubuntu 14
node.js version:  v0.10.25
npm version: 1.4.7

from error log:
gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2

**Comment by ekg** [comment]
FWIW, I had the same problem (came here by searching around) and `sudo apt-get remove gyp` seems to have resolved it.
