### ISSUE TITLE
Work with pm2 without commandline

### ISSUE THREAD

**Issue by jozvo** [Unitech/pm2#4342]
Please help me, How can I work with `pm2` without command line,
has `pm2` any gui control panel?

**Comment by jozvo** [comment]
Any idea or tools?

**Comment by A1Gard** [comment]
@jozvo  I'm code a web panel for pm2.
You can see here:
https://github.com/4xmen/pm2panel
This is not pm package**, Plz be careful** because it's has **full permission** for `nodejs` apps .
