### ISSUE TITLE
pm2 cron stays alive

### ISSUE THREAD

**Issue by Pierre-Demessence** [Unitech/pm2#4345]
## What's going wrong?
It seems that the pm2 cron stays even after you `delete` the process.

## How could we reproduce this issue?
_On my example I use `xclock` as a test process but you can replace it with anything.
Something graphical is handy since it's easier to see what happens, but even `cat` works if you read `~/.pm2/pm2.log`._

1. `pm2 start xclock`
It opens `xclock`.
2. `pm2 delete 0`
It closes `xclock`.
3. `pm2 start xclock -c "* * * * * *"`
It opens `xclock` and, after about 20 seconds (I don't know why), the cron restart it every seconds.
4. `pm2 delete 0`
It closes `xclock`.
5. `pm2 start xclock`
You'd expect it to have the same behavior as step **1**.
But the behavior is instead the one of step **3**.
You can also see that **right after step 2** by watching `~/.pm2/pm2.log` as you'll see pm2 trying to restart a PM ID which doesn't exist anymore.

### Notes
* You don't have to use the same process for step 3 and 5 as the cron is attached to a PM ID.
* To get back normal behavior, afaik, only a `pm2 kill` works.

## Supporting information
I'm on the latest version (3.5.1)

**Comment by Unitech** [comment]
x https://github.com/Unitech/pm2/issues/4485
