### ISSUE TITLE
pm2 spawns thousands of processes on startup

### ISSUE THREAD

**Issue by calebc01** [Unitech/pm2#4352]
We've been running pm2 for over a year, and this issue just manifested.

Two separate servers, running unique code, simultaneously started spawning multiple node processes.  Rebooting the servers and restarting the pm2 service repeated the behavior.

We can run our server just fine using 

`node app.js`

But running via the following causes processes to spawn until the processor utilization rails at 100% and the server crashes:

`pm2 start app`

Logs indicate that this problem began simultaneously on both servers (around 10:30 PM MST on Sunday, 7/14/2019).  Perhaps coincidentally, pm2's website seemed to be down during the same time period.

**Comment by noctune** [comment]
Also hitting this issue since about a week ago. Even just `pm2 list` seems to cause problems sometimes. However, it's unclear what exactly is causing it.

**Comment by madsjk816** [comment]
Having the same problems starting in roughly the same period of time - what version of PM2 are you running?

**Comment by calebc01** [comment]
> Having the same problems starting in roughly the same period of time - what version of PM2 are you running?

The latest version, 3.5.1.  Were either of you linked to pm2's monitoring service?  When I removed the link to the service and disabled any code that tried to report logs to pm2, the problem went away.

**Comment by madsjk816** [comment]
> > Having the same problems starting in roughly the same period of time - what version of PM2 are you running?
> 
> The latest version, 3.5.1. Were either of you linked to pm2's monitoring service? When I removed the link to the service and disabled any code that tried to report logs to pm2, the problem went away.

We were running on V3.0.0 but updating to the latest version of PM2 seems to have done the trick for us. We have not experienced any issues for the past 24 hours. We are linked to pm2's monitoring service.

**Comment by oyatek** [comment]
Some for me. I didn't find a solution and finally switched to "forever" instead of pm2

**Comment by calebc01** [comment]
The fact that this happened, that pm2 never responded, and that paid pm2 accounts didn't get responses to support requests, is a fantastically good argument for switching away from pm2.
