### ISSUE TITLE
"pm2 stop" not working when executet over IFTTT Webhook (Raspberry Pi)

### ISSUE THREAD

**Issue by RobinNowak** [Unitech/pm2#4359]
Hey Team,

I am working on a Project and unfortunatly im stuck at the Moment and I hope you guys maybe have an idea or solution for my problem.

I wrote an easy bash script (stopMirror.sh) with the commands
"pm2 stop mm"
"hueadm light 4 off" (a command to turn off a Philips Hue Light)

(mm.sh is a script that starts the MagicMirror program.)

If i execute the script stopMirror.sh normally, everything works perfectly fine and the MagicMirror Programm stops AND the Hue light is turned off.

After making a new Applet over IFTTT.com that sends a Webrequest to my Raspberry Pi after Pressing a Button, the script also gets executed BUT just the Light is getting turned off...
So the command "pm2 stop mm" is not working when executed over the Webrequest.

I also tried commands like: pm2 kill mm or pm2 killall, but none of them was able to shut down the mm process.

Any ideas?

Thank you!

**Comment by tianhuihui4217** [comment]
> Hey Team,
> 
> I am working on a Project and unfortunatly im stuck at the Moment and I hope you guys maybe have an idea or solution for my problem.
> 
> I wrote an easy bash script (stopMirror.sh) with the commands
> "pm2 stop mm"
> "hueadm light 4 off" (a command to turn off a Philips Hue Light)
> 
> (mm.sh is a script that starts the MagicMirror program.)
> 
> If i execute the script stopMirror.sh normally, everything works perfectly fine and the MagicMirror Programm stops AND the Hue light is turned off.
> 
> After making a new Applet over IFTTT.com that sends a Webrequest to my Raspberry Pi after Pressing a Button, the script also gets executed BUT just the Light is getting turned off...
> So the command "pm2 stop mm" is not working when executed over the Webrequest.
> 
> I also tried commands like: pm2 kill mm or pm2 killall, but none of them was able to shut down the mm process.
> 
> Any ideas?
> 
> Thank you!

i have ths same problem , use pm2 in shell, but i solve this problem.
you should use  :   pm2 stop "mm".  you will find that you are successful.
