### ISSUE TITLE
Error: ESPIPE: invalid seek, read

### ISSUE THREAD

**Issue by rup2701** [Unitech/pm2#4360]
## What's going wrong?

Following two errors repeatedly in the logs:

Error: ESPIPE: invalid seek, read
PM2 error: Error caught while calling pidusage

**Stacktrace:**
2019-07-20 14:27:23 default[20190720t070820]  2019-07-20T14:27:23: PM2 error: Error caught while calling pidusage
2019-07-20 14:27:23 default[20190720t070820]  2019-07-20T14:27:23: PM2 error: Error: ESPIPE: invalid seek, read
2019-07-20 14:27:23 default[20190720t070820]  2019-07-20T14:27:23: PM2 log: Stopping app:API id:0
2019-07-20 14:27:23 default[20190720t070820]  2019-07-20T14:27:23: PM2 log: App [API:0] exited with code [0] via signal [SIGINT]
2019-07-20 14:27:23 default[20190720t070820]  2019-07-20T14:27:23: PM2 log: pid=32 msg=process killed
2019-07-20 14:27:23 default[20190720t070820]  2019-07-20T14:27:23: PM2 log: PM2 successfully stopped

## How could we reproduce this issue?

We followed steps from here: http://pm2.keymetrics.io/docs/usage/use-pm2-with-cloud-providers/
to run a **NodeJS** app on **Google AppEngine**.

## Supporting information

```
$ pm2 report
```
Not able to run it on AppEngine/shell.

**Comment by italoiz** [comment]
I am also getting the same error in **Google Cloud Run**. @rup2701 did you manage to solve?

**Comment by JonasLaux** [comment]
@italoiz i had the same problem with cloud run. After hours of trying out stuff, i just deleted the Cloud Run instance and redeployed it. This did the trick.

**Comment by shaikhriyaz434** [comment]
same problem with the cloud run. Locally working fine but when deployed, the log is flooded with the error.

**Comment by jimsorock** [comment]
Same, haven't tried deleting the service but I have redeployed/replaced the service.

**Comment by neil-119** [comment]
I am getting the same issue on Google Cloud Run as well:

```
2020-06-17 15:14:01.536 CDT2020-06-17T20:14:01: PM2 error: Error caught while calling pidusage
2020-06-17 15:14:01.536 CDT2020-06-17T20:14:01: PM2 error: Error: ESPIPE: invalid seek, read
```

... repeating endlessly and filling up Stackdriver logs. Did anyone manage to fix this? I tried deleting and redeploying the service but it had no effect.

**Comment by max-mykhailenko** [comment]
Have the same problem in docker

**Comment by marcusflat** [comment]
I have the same problem, but looks that anyone found a solution =/

**Comment by lazharichir** [comment]
@neil-119 have you found any solution for that? The same problem with `pm2` on Cloud Run using `pm2-runtime server.js` but not finding any solution anywhere!

**Comment by ishaarawy** [comment]
I am getting the same error also on Google Cloud Run

**Comment by luisguerra** [comment]
__I know this is not the best solution but it worked for me__, the thing is that `pidusage` package cannot read the memory and cpu percentage through the procfiles (which is the default method), I fixed by modifying the file on the pm2 project ([See here](https://github.com/Unitech/pm2/blob/master/lib/God/ActionMethods.js#L60)) where its being called and added the param `{ usePs: true }`

According to the documentation on https://www.npmjs.com/package/pidusage

```
By default, pidusage will use procfile parsing on most unix systems. If you want to use ps instead use the usePs option:

pidusage(pid, {usePs: true})
```

The solution is to run this command (in my case I added to my Dockerfile)), which is part of the process)
```
RUN sed -i 's/pidusage(pids, function retPidUsage(err, statistics) {/pidusage(pids, { usePs: true }, function retPidUsage(err, statistics) {/' {PATH WHERE YOU HAVE INSTALLED YOUR MODULES}/node_modules/pm2/lib/God/ActionMethods.js
```

**Comment by edi** [comment]
Same issue here, with DigitalOcean Apps Platform

**Comment by edelbalso** [comment]
This just happened to me too on DigitalOcean Apps Platform as well

**Comment by studentIvan** [comment]
Got the same on DigitalOcean Apps Platform

**Comment by edi** [comment]
I think we should just be allowed to configure pidusage’s {usePs: true} via a flag. That would sort everything.

or at least fallback to it in case it triggers an error when using the default procFs

**Comment by studentIvan** [comment]
Can somebody share the solution to fix that? @edi can you tell more about the patch-package solution?

this is my current Dockerfile example

```
FROM node:12-alpine

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
WORKDIR /home/node/app
RUN npm install -g pm2
RUN sed -i 's/pidusage(pids, function retPidUsage(err, statistics) {/pidusage(pids, { usePs: true }, function retPidUsage(err, statistics) {/' /usr/local/lib/node_modules/pm2/lib/God/ActionMethods.js
COPY package*.json ./
COPY yarn.lock ./
USER node
RUN yarn
COPY --chown=node:node . .
RUN yarn build
EXPOSE 3000
CMD ["pm2-runtime", "process.yml"]
```

I also added `"postinstall": "patch-package"` to the "scripts" in package.json

both didn't help

**Comment by studentIvan** [comment]
@edi after this replace I got the new error:

```
2021-04-13T22:07:22: PM2 error: Error: ps: unrecognized option: p
ct-api-microservice | 2021-04-14 01:07:22 BusyBox v1.31.1 () multi-call binary.
ct-api-microservice | 2021-04-14 01:07:22 
ct-api-microservice | 2021-04-14 01:07:22 Usage: ps [-o COL1,COL2=HEADER]
ct-api-microservice | 2021-04-14 01:07:22 
ct-api-microservice | 2021-04-14 01:07:22 Show list of processes
ct-api-microservice | 2021-04-14 01:07:22 
ct-api-microservice | 2021-04-14 01:07:22       -o COL1,COL2=HEADER     Select columns for display
ct-api-microservice | 2021-04-14 01:07:22 
ct-api-microservice | 2021-04-14 01:07:24 2021-04-13T22:07:24: PM2 error: Error caught while calling pidusage
ct-api-microservice | 2021-04-14 01:07:24 2021-04-13T22:07:24: PM2 error: Error: ps: unrecognized option: p
```

```
~/app $ cat /usr/local/lib/node_modules/pm2/lib/God/ActionMethods.js | grep pidu
sage
var pidusage      = require('pidusage');
    pidusage(pids, { usePs: true }, function retPidUsage(err, statistics) {
        console.error('Error caught while calling pidusage');
~/app $ 
```

**Comment by edi** [comment]
@studentIvan I'm pretty sure your file gets corrupted after that change. Please refer to my opened issue, here, for the patch-package workaround.

https://github.com/Unitech/pm2/issues/5045

Regards

**Comment by avently** [comment]
@Unitech hello. I'm using the latest version of the lib and this error still present. Could you please find a fix? I can test the fix if you need. In my case I see the problem on AppEngine and I can't just patch the lib in this case.

**Comment by syahiaoui** [comment]
I solved the probleme by adding this lines:

```js
const signalTraps = ['SIGTERM', 'SIGINT', 'SIGUSR2'];
const sleep = (ms) => new Promise(resolve => setTimeout(resolve, ms));

signalTraps.map(type => {
    process.once(type, async() => {
        try {
            logger.warn(`Received ${type}, closing express and PubSub ...`);
            await app.close();
            await pubSubClient.close();
            await sleep(shutdownSleepMs);
        } finally {
            process.exit(0);
        }
    });
});
```

**Comment by Apezdr** [comment]
Any chance this can make it in?

**Comment by lomse** [comment]
> 

I'm not running the app in a docker container. At what point should I run this command?

**Comment by eazylaykzy** [comment]
> Same issue here, with DigitalOcean Apps Platform. I've used the `patch-package` library to sort the issue upon build time.

@edi I'm equally experiencing this intermittently on App Platform (DO), could you please describe how you solve this?

Thanks.

**Comment by draizada** [comment]
> I use `patch-package` to fix this issue. To fix this issue, do the following:
> 
> 1. Install `patch-package`: https://www.npmjs.com/package/patch-package
> 2. Open the file in vscode `code node_modules/pm2`
> 3. do the following update in the `lib/God/ActionMethods.js`
> 
> ```
> -    pidusage(pids, function retPidUsage(err, statistics) {
> -      // Just log, we'll set empty statistics
> -      if (err) {
> -        console.error('Error caught while calling pidusage');
> -        console.error(err);
> -
> -        return cb(null, processes.map(function(pro) {
> -          pro['monit'] = {
> -            memory : 0,
> -            cpu : 0
> -          };
> -          return pro
> -        }))
> -      }
> -
> -      if (!statistics) {
> -        console.error('Statistics is not defined!')
> -
> -        return cb(null, processes.map(function(pro) {
> -          pro['monit'] = {
> -            memory : 0,
> -            cpu : 0
> -          };
> -          return pro
> -        }))
> -      }
> -
> -      processes = processes.map(function(pro) {
> -        if (filterBadProcess(pro) === false) {
> -          pro['monit'] = {
> -            memory : 0,
> -            cpu : 0
> -          };
> -
> -          return pro;
> -        }
> -
> -        var pid = getProcessId(pro);
> -        var stat = statistics[pid];
> -
> -        if (!stat) {
> -          pro['monit'] = {
> -            memory : 0,
> -            cpu : 0
> -          };
> -
> -          return pro;
> -        }
> -
> -        pro['monit'] = {
> -          memory: stat.memory,
> -          cpu: Math.round(stat.cpu * 10) / 10
> -        };
> -
> -        return pro;
> -      });
> -
> -      cb(null, processes);
> -    });
> +    pidusage(pids, { usePs: true });
> ```
> 
> 4. Next run `npx patch-package pm2`
> 5. Commit the changes in. your project
> 6. Push the changes.
> 7. Remember to update your package.json file with a `postinstall` npm script as explain [here](https://www.npmjs.com/package/patch-package)

Done the above - still throwing the same error - 
build command: npm run postinstall 
run command: pm2-runtime start pm2.yml 
on Digital Ocean App platform 

Any help would be great. TIA

**Comment by evtaylor** [comment]
For anyone stumbling on this thread looking for an answer you can now just set an environment variable: `PIDUSAGE_USE_PS` to `true` as described [here](https://github.com/Unitech/pm2/issues/5045#issuecomment-950732012) and in the [pidusage docs](https://github.com/soyuka/pidusage).

**Comment by raineorshine** [comment]
Make sure to `pm2 kill` first before testing the change.

**Comment by georgeben** [comment]
I am running the app on Digital Ocean App platform, I updated my start script to

```json
 "start": "cross-env NODE_ENV=production PIDUSAGE_USE_PS=false pm2-runtime start ecosystem.config.js --env production",
```

I am running the app in a docker container. But I still get the error
[2024-01-09 20:24:35] 2024-01-09T20:24:35: PM2 error: Error caught while calling pidusage
[2024-01-09 20:24:35] 2024-01-09T20:24:35: PM2 error: Error: ESPIPE: invalid seek, read

Please help
