### ISSUE TITLE
Vulnerability in async dependency

### ISSUE THREAD

**Issue by RiaanWest** [Unitech/pm2#4367]
There is a new vulnerability in lodash 4.17.11, which is a dependency of async. (https://www.npmjs.com/advisories/1065)

async has since updated the package.json at v2.6.3 (https://github.com/caolan/async/compare/2.x). 

Could you please update your dependencies to fix it?

**Comment by tapsboy** [comment]
This seems to have popped up again an issue due async being a dependency of vizion. I created an issue for this: #4670

**Comment by Unitech** [comment]
PM2 4.3.0 published:

```bash
npm install pm2@latest -g
pm2 update
```
