### ISSUE TITLE
rror Couldn't find package "@pm2/io@^4.1.2" required by "pm2@^3.5.1" on the "npm" registry.

### ISSUE THREAD

**Issue by zalewskigrzegorz** [Unitech/pm2#4373]
## What's going wrong?
The package can not be installed 
error Couldn't find package "@pm2/io@^4.1.2" required by "pm2@^3.5.1" on the "npm" registry.

## How could we reproduce this issue?
yarn install

**Comment by ihl396** [comment]
Has anyone resolved this yet? I'm seeing the exact same issue and its breaking pipelines.

**Comment by Askadias** [comment]
Same thing. Can somebody please take a look? It's kind a blocking issue
