### ISSUE TITLE
env LD_PRELOAD not effect on Cluster Mode

### ISSUE THREAD

**Issue by Cow258** [Unitech/pm2#4375]
https://github.com/Unitech/pm2/issues/3684
https://github.com/Unitech/pm2/issues/2618
https://github.com/lovell/sharp/issues/1803

## What's going wrong?
Unable to load env `LD_PRELOAD` under Cluster Mode

## How could we reproduce this issue?
Full detail here
https://github.com/lovell/sharp/issues/1803

## Supporting information

```
$ pm2 report
--- PM2 report ----------------------------------------------------------------
Date                 : Tue Jul 30 2019 04:04:02 GMT+0000 (Coordinated Universal Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.5.1
node version         : 12.6.0
node path            : not found
argv                 : /usr/bin/node,/usr/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : ubuntu
uid                  : 1000
gid                  : 1000
uptime               : 40min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.5.1
node version         : 12.6.0
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : ubuntu
uid                  : 1000
gid                  : 1000
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
cpus nb              : 1
freemem              : 395948032
totalmem             : 1031700480
home                 : /home/ubuntu
===============================================================================
```

**Comment by Cow258** [comment]
@Unitech This issue still here for a long time, could you please take a look at this? Thanks

**Comment by Cow258** [comment]
The issue still here today

**Comment by lokoArt** [comment]
Facing the same issue. any suggestions?

**Comment by Unitech** [comment]
Cluster mode is tightly link on how PM2 has been started. 
So if you want to load a specific LD_PRELOAD, you need to restart PM2 with that env variable.

So:
```bash
pm2 kill
LD_PRELOAD=xxxx pm2 ls
# Now if you start an app in cluster mode, LD_PRELOAD will be injected in that app
pm2 start app.js -i max
```

**Comment by Cow258** [comment]
@Unitech About ensure pm2 used `LD_PRELOAD` when system boot up?

**Comment by Cow258** [comment]
@lokoArt 
Currently,\
I am using `fork` mode to prevent memory leak.\
But that cause unable to provide zero-downtime service,\
all update required between scheduled maintenance period like 02:00-03:00,\
or accept the downtime when you need update immediate.

If set env `LD_PRELOAD=xxxx` before `pm2` start that is work,\
I will change all instance into cluster mode.

**Comment by Cow258** [comment]
Successful to add `LD_PRELOAD=xxxx` into Cluster mode!
🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉

Add `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.1`\
Into `/env/environment`\
Also do\
`export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.1`\
Then\
`sudo reboot`

The cluster mode will working with `LD_PRELOAD=xxxx`,\
Not issue when processing many big size images with `sharp.js`,\
Thanks to @Unitech provide some tips for this issue.\

**Comment by jordygroote** [comment]
> Successful to add `LD_PRELOAD=xxxx` into Cluster mode!
> 🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉
> 
> Add `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.1`
> Into `/env/environment`
> Also do
> `export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.1`
> Then
> `sudo reboot`
> 
> The cluster mode will working with `LD_PRELOAD=xxxx`,
> Not issue when processing many big size images with `sharp.js`,
> Thanks to @Unitech provide some tips for this issue.\

Where to place ```LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.1 ```, ```/env/environment``` isn't a valid directory?

**Comment by matthijs88** [comment]
@jordygroote I ran into the same problem. It's `/etc/enviroment`

**Comment by Cow258** [comment]
## Update
### Install latest jemalloc 5.2.1 on Ubuntu 18

Refer: https://gist.github.com/diginfo/be7347e6e6c4f05375c51bca90f220e8

```bash
sudo apt-get -y install autoconf libxslt-dev xsltproc docbook-xsl
git clone https://github.com/jemalloc/jemalloc.git
cd jemalloc
autoconf
./configure
make dist
sudo make install
```
You can found jemalloc at `/usr/local/lib/libjemalloc.so.2`
```bash
sudo su
vi /etc/enviroment

# Then add this line
LD_PRELOAD=/usr/local/lib/libjemalloc.so.2
```
Then
```bash
export LD_PRELOAD=/usr/local/lib/libjemalloc.so.2
```
Then optional reboot `sudo reboot`

**Comment by Cow258** [comment]
# Update
I faced this problem again in a week, and it took me 2 days to solve it
After seeing this comment, I got the answer
https://github.com/nodejs/help/issues/1518#issuecomment-997221787

Somehow, the `LD_PRELOAD` environment variable may not work
You need to modify `/etc/ld.so.preload` to solve this problem
```bash
# make install version
sudo echo "/usr/local/lib/libjemalloc.so.2" >> /etc/ld.so.preload

# apt-get version
sudo echo "/usr/lib/x86_64-linux-gnu/libjemalloc.so" >> /etc/ld.so.preload
```
Then restart all `node` processes to use `jemalloc` for allocation:
```bash
# If you are using pm2
pm2 kill
pm2 resurrect
```
Then check the `PID` of your running `node` process and plug it into the command below to verify it is using `jemalloc`:
```bash
ps aux | grep node
cat /proc/<PID>/smaps | grep jemalloc
```

**Comment by hypo-thesis** [comment]
@Cow258 Thanks mate. I owe you a debt.

**Comment by rayanchemin** [comment]
> # Update
> 
> I faced this problem again in a week, and it took me 2 days to solve it After seeing this comment, I got the answer [nodejs/help#1518 (comment)](https://github.com/nodejs/help/issues/1518#issuecomment-997221787)
> 
> Somehow, the `LD_PRELOAD` environment variable may not work You need to modify `/etc/ld.so.preload` to solve this problem
> 
> ```shell
> # make install version
> sudo echo "/usr/local/lib/libjemalloc.so.2" >> /etc/ld.so.preload
> 
> # apt-get version
> sudo echo "/usr/lib/x86_64-linux-gnu/libjemalloc.so" >> /etc/ld.so.preload
> ```
> 
> Then restart all `node` processes to use `jemalloc` for allocation:
> 
> ```shell
> # If you are using pm2
> pm2 kill
> pm2 resurrect
> ```
> 
> Then check the `PID` of your running `node` process and plug it into the command below to verify it is using `jemalloc`:
> 
> ```shell
> ps aux | grep node
> cat /proc/<PID>/smaps | grep jemalloc
> ```

Thank you so much!

**Comment by lwmxiaobei** [comment]
node:16.20.2-alpine3.18 docker image invalid，No information about jemalloc can be seen in smaps
