### ISSUE TITLE
Environment variables in cluster mode - please reopen

### ISSUE THREAD

**Issue by nathanieltagg** [Unitech/pm2#4379]
This is a request to re-open issue 3062.  This issue is affecting me, and the resolution is not sufficient. https://github.com/Unitech/pm2/issues/3062

When working in fork mode, everything is fine: environment variables declared in the ecosystem are properly applied to the executable, and all is well.

However, when working in cluster mode, it looks like this is NOT the case. Rather, it seems that there is a master Node script that is running the cluster instances, and instead of running them with an environment as defined, instead environment variables are being injected with process.ENV or similar.

The problem here is that (at least on Linux systems) the LD_LIBRARY_PATH variable cannot be injected this way in order for libraries to be resolved. They must be set in the calling process. 

(In principle, the problem could be solved by setting up library RPATHs so all the external libraries point to each other, but in practice I cannot do that: my executable library chain is about 10 libraries deep, all using the environment method and I'm not even able to modify the binaries in any easy way.)

## How could we reproduce this issue?

I've created a small proof-of-principle repository here:
https://github.com/nathanieltagg/pm2-environment-test

Follow the instructions in the README on a Linux machine to see the problem. Similar problems can be shown for OSX running with DYLD_LIBRARY_PATH (in insecure mode).

**Comment by ataft** [comment]
Could this issue be related to #4331? I'm having an issue where pm2 is throwing an error because `process.env.pm2_env` is null.

**Comment by nathanieltagg** [comment]
> Could this issue be related to #4331? I'm having an issue where pm2 is throwing an error because `process.env.pm2_env` is null.

I don't THINK so...?  My variables are getting correctly injected.. it's just that injection is insufficient and I need them defined by the forking process.

**Comment by nathanieltagg** [comment]
After more reading, I learn this is endemic to most OS-es - you cannot modify the library paths after the process has loaded. The only two options are to either have the shell process load the variables, or re-execvp the current process.  I'm guessing the latter is the correct option for PM2, but it is much too buried in code for me to figure out how to fix it. Any response from devs?

**Comment by ChristianGfK** [comment]
It's a shame the that this was closed by a bot without any dev response.
This issue is affecting us as well. :\

**Comment by Akshay9790** [comment]
Hi @nathanieltagg @ChristianGfK, Were you able to fix this issue in you app?

**Comment by nathanieltagg** [comment]
No.  I had a workaround, which was essentially to inject all the environment variables into the /etc/init.d/pm2 startup script before pm2 started, which made the whole thing very fragile, made logs difficult to read, and there was no way of automating the process when the environment changed.  

It went into the lump problems of environment variables are bad...
