### ISSUE TITLE
pm2.log and pm2.pid files location

### ISSUE THREAD

**Issue by adshpagin** [Unitech/pm2#438]
Hello! Thank you for the PM2 project, it's great!
I've got a question about pm2.log and pm2.pid files. As far as I know these files are always located in ~/.pm2/ directory and there is now way to change it via configuration.
Is it possible to add customization for the location of these files?
It would be great to have separate path settings for pm2.log and pm2.pid respectively.

For example:

/var/log/my_project/pm2.log
/var/run/my_project/pm2.pid

Thank you!

**Comment by stevenvachon** [comment]
The `--error`, `--log` and `--output` options seem to be completely ignored too.

**Comment by steerben** [comment]
It seems that when transfering parts of the constants from `constants.js` to `sample-conf.js` the introduced functionality implemented in `aa19782` has been removed. Could these two lines be added again to be able to set the pm2 log path via an env variable?

**Comment by zdychacek** [comment]
Will this functionality ever be restored again?

Thank you.

O.

**Comment by Unitech** [comment]
Feel free to send a PR on dev branch (https://github.com/Unitech/pm2/blob/development/paths.js) for this feature to land on PM2 2.0

Otherwise we will do it on PM2 > 2.0

**Comment by cdambo** [comment]
Thanks for this fix! when will it be released?
