### ISSUE TITLE
--experimental-modules flag appears to be ignored

### ISSUE THREAD

**Issue by Andrey-Bushman** [Unitech/pm2#4385]
I saw similar issue [here](https://github.com/Unitech/pm2/issues/3294), but it is old and closed. Therefore I create new issue.

[Here](https://github.com/Andrey-Bushman/pm2-es-modules-example) is the simple example. It shows the problem. Look its `readme.md` file, please. How can I solve the problem?

Thank you.

**Comment by Andrey-Bushman** [comment]
I found [issue #3751](https://github.com/Unitech/pm2/issues/3751) and tried to use [esm](https://www.npmjs.com/package/esm) module instead of `--experimental-modules` option. It works fine. I will use it now. But it is workaround. It would be nice if the `--experimental-modules` option worked too. 

Thank you.

**Comment by sidvishnoi** [comment]
The `--experimental-modules` flag works with pm2, but it doesn't take `"type": "module"` from package.json into account.

Example code:
``` js
// foo.js
export const foo = "bar";

// index.js
import { foo } from './foo.js';
console.log(foo)

// package.json
{
  "type": "module"
}
```

Running with node directly:
``` bash
$ node --experimental-modules index.js
(node:11912) ExperimentalWarning: The ESM module loader is experimental.
bar
```

Running with pm2:
``` bash
$ pm2 start index.js --node-args="--experimental-modules"
$ pm2 logs index --raw --err

(node:9712) ExperimentalWarning: The ESM module loader is experimental.
E:\GitHub\pm2-test\index.js:1
import { foo } from './foo.js';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:720:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Proxy.Module._load (internal/modules/cjs/loader.js:556:12)
    at Object.<anonymous> (C:\Users\[REDACTED]]\v12.6.0\node_modules\pm2\lib\ProcessContainerFork.js:27:21)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at internal/modules/esm/translators.js:87:15
```

**Comment by Andrey-Bushman** [comment]
> The `--experimental-modules` flag works with pm2, but it doesn't take `"type": "module"` from package.json into account.
> 
> Example code:
> 
> ```js
> // foo.js
> export const foo = "bar";
> 
> // index.js
> import { foo } from './foo.js';
> console.log(foo)
> 
> // package.json
> {
>   "type": "module"
> }
> ```
> 
> Running with node directly:
> 
> ```shell
> $ node -v
> v12.6.0
> $ node --experimental-modules index.js
> (node:11912) ExperimentalWarning: The ESM module loader is experimental.
> bar
> ```
> 
> Running with pm2:
> 
> ```shell
> $ pm2 --version
> 3.5.1
> $ pm2 start index.js --node-args="--experimental-modules"
> $ pm2 logs index --raw --err
> 
> (node:9712) ExperimentalWarning: The ESM module loader is experimental.
> E:\GitHub\pm2-test\index.js:1
> import { foo } from './foo.js';
>        ^
> 
> SyntaxError: Unexpected token {
>     at Module._compile (internal/modules/cjs/loader.js:720:23)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
>     at Module.load (internal/modules/cjs/loader.js:643:32)
>     at Proxy.Module._load (internal/modules/cjs/loader.js:556:12)
>     at Object.<anonymous> (C:\Users\[REDACTED]]\v12.6.0\node_modules\pm2\lib\ProcessContainerFork.js:27:21)
>     at Module._compile (internal/modules/cjs/loader.js:776:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
>     at Module.load (internal/modules/cjs/loader.js:643:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
>     at internal/modules/esm/translators.js:87:15
> ```

Thank you. How can I solve it?

**Comment by sidvishnoi** [comment]
> How can I solve it?

No idea. I'm reporting to support this issue to be fixed.

> I see node hasn't --type parameter

Yes, there isn't. It has to be fixed at pm2 level.
