### ISSUE TITLE
Update AGPL-3.0 license to "AGPL-3.0-only" or "AGPL-3.0-or-later"

### ISSUE THREAD

**Issue by scmccoy** [Unitech/pm2#4401]
## What's going wrong?
The "AGPL-3.0" license is marked as deprecated by SPDX. The current valid identifiers are "AGPL-3.0-only" and "AGPL-3.0-or-later". According to [SPDX](https://spdx.org/licenses/AGPL-3.0-or-later.html),

> Release 3.0 replaced previous Identifiers for GNU licenses with more explicit Identifiers to 
> reflect the “this version only” or “any later version” option specific to those licenses. As
> such, the previously used Identifiers for those licenses are deprecated as of v3.0.

Using the deprecated "AGPL-3.0" license identifier causes this module to be flagged as a vulnerability in tools like Snyk.

**Comment by pombredanne** [comment]
> Using the deprecated "AGPL-3.0" license identifier causes this module to be flagged as a vulnerability in tools like Snyk.

MO is that's pretty dumb of them! This is deprecated but still widely used and should be supported by tools including the `npm` tool itself that validates the license field of the package.json
