### ISSUE TITLE
pm2 for java - Could NOT read system variables.

### ISSUE THREAD

**Issue by Sky-Walkrr** [Unitech/pm2#4405]
## What's going wrong?
Try to use a JSON file to run Java process with PM2, but could not read the system variable which defined in `/etc/profile`.

The JSON file `config.json` shows below:

```JSON
{
    "name": "my_app",
    "script": "java",
    "args": [
       "-jar",
        "-Denv=test",
        "-Dip=${LOCAL_IP}",
        "/home/app/my_app.jar"
    ],
    "exec_interpreter": "",
    "exec_mode": "fork"
}

```

`${LOCAL_IP}` is a system-wide variable defined in `/etc/profile`, it could be used in other apps.

Then use `pm2 start config.json `, the Java process runs. But when run `pm2 show my_app`, I notice that the ip is just the string "${LOCAL_IP}".

So I'm confusing, how to load system variables in this situation?
## How could we reproduce this issue?

Just use the JSON file below to run any JAR file.

## Supporting information

```
$ pm2 report
```

**Comment by linxux** [comment]
Same issue for `args`
