### ISSUE TITLE
AWS Lighsail, Node JS had too many unstable restarts (16)

### ISSUE THREAD

**Issue by gnkevadia** [Unitech/pm2#4406]
## What's going wrong?
--- PM2 report ----------------------------------------------------------------
Date                 : Wed Aug 28 2019 08:00:35 GMT+0000 (Coordinated Universal Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.5.1
node version         : 10.16.0
node path            : /opt/bitnami/nodejs/bin/pm2
argv                 : /root/.nvm/versions/node/v10.16.0/bin/node,/opt/bitnami/nodejs/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
uptime               : 0min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.5.1
node version         : 10.16.0
node path            : /opt/bitnami/nodejs/bin/pm2
argv                 : /root/.nvm/versions/node/v10.16.0/bin/node,/opt/bitnami/nodejs/bin/pm2,report
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
cpus nb              : 1
freemem              : 252223488
totalmem             : 1038721024
home                 : /root
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬─────────┬──────┬─────┬─────────┬─────────┬────────┬─────┬────────┬──────┬──────────┐
│ App name │ id │ version │ mode │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user │ watching │
├──────────┼────┼─────────┼──────┼─────┼─────────┼─────────┼────────┼─────┼────────┼──────┼──────────┤
│ API      │ 0  │ 1.0.0   │ fork │ 0   │ errored │ 15      │ 0      │ 0%  │ 0 B    │ root │ disabled │
└──────────┴────┴─────────┴──────┴─────┴─────────┴─────────┴────────┴─────┴────────┴──────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/root/.pm2/pm2.log last 20 lines:
PM2        | 2019-08-28T08:00:24: PM2 log: App [API:0] exited with code [1] via signal [SIGINT]
PM2        | 2019-08-28T08:00:24: PM2 log: App [API:0] starting in -fork mode-
PM2        | 2019-08-28T08:00:24: PM2 log: App [API:0] online
PM2        | 2019-08-28T08:00:25: PM2 log: App [API:0] exited with code [1] via signal [SIGINT]
PM2        | 2019-08-28T08:00:25: PM2 log: App [API:0] starting in -fork mode-
PM2        | 2019-08-28T08:00:25: PM2 log: App [API:0] online
PM2        | 2019-08-28T08:00:25: PM2 log: App [API:0] exited with code [1] via signal [SIGINT]
PM2        | 2019-08-28T08:00:25: PM2 log: App [API:0] starting in -fork mode-
PM2        | 2019-08-28T08:00:25: PM2 log: App [API:0] online
PM2        | 2019-08-28T08:00:25: PM2 log: App [API:0] exited with code [1] via signal [SIGINT]
PM2        | 2019-08-28T08:00:25: PM2 log: App [API:0] starting in -fork mode-
PM2        | 2019-08-28T08:00:25: PM2 log: App [API:0] online
PM2        | 2019-08-28T08:00:25: PM2 log: App [API:0] exited with code [1] via signal [SIGINT]
PM2        | 2019-08-28T08:00:25: PM2 log: App [API:0] starting in -fork mode-
PM2        | 2019-08-28T08:00:25: PM2 log: App [API:0] online
PM2        | 2019-08-28T08:00:25: PM2 log: App [API:0] exited with code [1] via signal [SIGINT]
PM2        | 2019-08-28T08:00:25: PM2 log: App [API:0] starting in -fork mode-
PM2        | 2019-08-28T08:00:25: PM2 log: App [API:0] online
PM2        | 2019-08-28T08:00:25: PM2 log: App [API:0] exited with code [1] via signal [SIGINT]
PM2        | 2019-08-28T08:00:25: PM2 log: Script /opt/bitnami/apache2/htdocs/buoyd_node/index.mjs had too many unstable restarts (16). Stopped. "errored"
## Supporting information

```
$ pm2 report
```

**Comment by gnkevadia** [comment]
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/ec2-user/html/index.mjs
0|API      |     at Object.Module._extensions..mjs (internal/modules/cjs/loader.js:813:11)
0|API      |     at Module.load (internal/modules/cjs/loader.js:653:32)
0|API      |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
0|API      |     at Proxy.Module._load (internal/modules/cjs/loader.js:585:3)
0|API      |     at Object.<anonymous> (/root/.nvm/versions/node/v10.16.3/lib/node_modules/pm2/lib/ProcessContainerFork.js:27:21)
0|API      |     at Module._compile (internal/modules/cjs/loader.js:778:30)
0|API      |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
0|API      |     at Module.load (internal/modules/cjs/loader.js:653:32)
0|API      |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
0|API      |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by Unitech** [comment]
not related to pm2
