### ISSUE TITLE
Can't link to pm2 server

### ISSUE THREAD

**Issue by developerconor** [Unitech/pm2#4410]
Currently getting an issue where I cannot link to pm2 plus server.

root@v2-monitors:/monitors/v3# pm2 plus 
[PM2 I/O] Successfully authenticated 
[PM2 I/O] Successfully validated 
(node:1927) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'offer_type' of undefined 
    at /usr/local/lib/node_modules/pm2/lib/API/pm2-plus/PM2IO.js:306:49
    at Array.forEach (<anonymous>)
    at io.bucket.retrieveAll.then.res (/usr/local/lib/node_modules/pm2/lib/API/pm2-plus/PM2IO.js:305:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:1927) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1927) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Any help would be great. Anything you need me to provide you with etc

**Comment by mzalazar** [comment]
PM2 "plus" is not free, did you pay for that service?

**Comment by Unitech** [comment]
Fixed via pm2 4.x
