### ISSUE TITLE
no daemon failing to start when specified log path not exist

### ISSUE THREAD

**Issue by thunder-night** [Unitech/pm2#4415]
## What's going wrong?
if we specify log path, and the path is not exist,  pm2-docker or pm2 --no-daemon will failed with error message "ENOENT: no such file or directory..."

for an example, set error_log = "/root/home/appadmin/pm2/logs/xxxx" in our json file. "/root/home/appadmin" exist in system, and "/root/home/appadmin/pm2/logs/xxxx" not.
note: error happend when more than one dir not exist

## Supporting information
i know pm2 will create the missing fold in [https://github.com/Unitech/pm2/blob/master/lib/Common.js#L216](url). but this is wrong when the path is not exist. Because mkdirp create missing dir step-by-step asynchronously.  this will  cause [https://github.com/Unitech/pm2/blob/master/lib/God/ForkMode.js#L84](url) error as this code execute before the log path created

**Comment by zyf0330** [comment]
I meet this problem too.
