### ISSUE TITLE
PM2 not restarting an inactive Nodejs instance (Fork)

### ISSUE THREAD

**Issue by bloodymind** [Unitech/pm2#4416]
## What's going wrong?
Something weird happened today while debugging a slow API, suddenly an instance of Node.js (Fork Number 146 below) stoped working for 50 minutes and PM2 couldn't detect an issue and didn't restart it! 

Here is what i've found: 

-> Dash 
![image](https://user-images.githubusercontent.com/4992012/64701908-ebac2600-d4a9-11e9-9c46-a18ab06a6045.png)

-> list 
![image](https://user-images.githubusercontent.com/4992012/64701962-fd8dc900-d4a9-11e9-9527-ed2812d6d53a.png)

## How could we reproduce this issue?
No idea! there is no logs to share about that particular Node.js instance :(it suddenly stoped working, previous logs are returning 200 code status

NB: 
- I'm using PM2 version: 3.5.1
- node -v: v10.15.3
- Os: Red Hat Enterprise 7

It worked fine when i reloaded the App myself but i want to understand why this happened and if i'll need a human intervention to check after PM2 inactive instances. 

Idea idea?

**Comment by Unitech** [comment]
Your application seems not auto exiting in case of an internal issue
