### ISSUE TITLE
pm2 cluster not working on centos 7.6

### ISSUE THREAD

**Issue by CodMonk** [Unitech/pm2#4420]
I've tried to start my React JS application in cluster mode on centos 7.6 but does not seems to be working although it works if use only 1 instance to start the application.

Any clue what I am doing wrong when using pm2 ?

Here are the pm2 logs and start commands which I tried for both the cases -

### **Single Instance**

pm2 start npm --name "app1" --instances 1   -- run start
[PM2] Starting /usr/local/bin/npm in fork_mode (1 instance)
[PM2] Done.
┌──────────┬────┬─────────┬──────┬──────┬────────┬─────────┬────────┬─────┬──────────┬──────┬──────────┐
│ App name │ id │ version │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem      │ user │ watching │
├──────────┼────┼─────────┼──────┼──────┼────────┼─────────┼────────┼─────┼──────────┼──────┼──────────┤
│ app1     │ 0  │ N/A     │ fork │ 8306 │ online │ 0       │ 0s     │ 0%  │ 3.4 MB   │ root │ disabled │
└──────────┴────┴─────────┴──────┴──────┴────────┴─────────┴────────┴─────┴──────────┴──────┴──────────┘

PM2        | 2019-09-15T09:42:36: PM2 log: App [app1:0] starting in -fork mode-
PM2        | 2019-09-15T09:42:36: PM2 log: App [app1:0] online

/root/.pm2/logs/app1-out-0.log last 15 lines:
0|app1     |
0|app1     | > app1@1.0.0 start /home/app1
0|app1     | > webpack-dev-server --mode production --open --hot
0|app1     |
0|app1     | ℹ ｢wds｣: Project is running at http://xxx.xxx.xxx.xxx:80/
0|app1     | ℹ ｢wds｣: webpack output is served from /
0|app1     | ℹ ｢wds｣: 404s will fallback to /index.html
0|app1     | ℹ ｢wdm｣: Compiled with warnings.

/root/.pm2/logs/app1-error-0.log last 15 lines:
0|app1     | Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/dist/cjs.js!src/components/grid/jsgrid-theme.min.css:
0|app1     |     Entrypoint undefined = extract-text-webpack-plugin-output-filename
0|app1     |        [0] ./node_modules/css-loader/dist/runtime/api.js 2.61 KiB {0} [built]
0|app1     |        [1] ./node_modules/css-loader/dist/cjs.js!./src/components/grid/jsgrid-theme.min.css 32.8 KiB {0} [built]
0|app1     | Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/dist/cjs.js!src/components/grid/jsgrid.min.css:
0|app1     |     Entrypoint undefined = extract-text-webpack-plugin-output-filename
0|app1     |        [0] ./node_modules/css-loader/dist/runtime/api.js 2.61 KiB {0} [built]
0|app1     |        [1] ./node_modules/css-loader/dist/cjs.js!./src/components/grid/jsgrid.min.css 1.91 KiB {0} [built]
0|app1     | Child html-webpack-plugin for "index.html":
0|app1     |      1 asset
0|app1     |     Entrypoint undefined = index.html
0|app1     |        [0] (webpack)/buildin/module.js 519 bytes {0} [built]
0|app1     |        [1] (webpack)/buildin/global.js 509 bytes {0} [built]
0|app1     |        [2] ./node_modules/lodash/lodash.js 527 KiB {0} [built]
0|app1     |        [3] ./node_modules/html-webpack-plugin/lib/loader.js!./index.html 1.69 KiB {0} [built]

### **Cluster Mode** 

 pm2 start npm --name "app1" --instances 2   -- run start
[PM2] Starting /usr/local/bin/npm in cluster_mode (2 instances)
[PM2] Done.
┌──────────┬────┬─────────┬─────────┬──────┬────────┬─────────┬────────┬─────┬───────────┬──────┬──────────┐
│ App name │ id │ version │ mode    │ pid  │ status │ restart │ uptime │ cpu │ mem       │ user │ watching │
├──────────┼────┼─────────┼─────────┼──────┼────────┼─────────┼────────┼─────┼───────────┼──────┼──────────┤
│ app1     │ 0  │ N/A     │ cluster │ 8410 │ online │ 0       │ 0s     │ 0%  │ 25.8 MB   │ root │ disabled │
│ app1     │ 1  │ N/A     │ cluster │ 8417 │ online │ 0       │ 0s     │ 0%  │ 19.3 MB   │ root │ disabled │
└──────────┴────┴─────────┴─────────┴──────┴────────┴─────────┴────────┴─────┴───────────┴──────┴──────────┘

/root/.pm2/logs/app1-out-1.log last 15 lines:
1|app1     |
1|app1     | > app1@1.0.0 start /home/app1
1|app1     | > webpack-dev-server --mode production --open --hot
1|app1     |

/root/.pm2/logs/app1-error-0.log last 15 lines:
0|app1     |        [1] ./node_modules/css-loader/dist/cjs.js!./src/components/grid/jsgrid.min.css 1.91 KiB {0} [built]
0|app1     | Child html-webpack-plugin for "index.html":
0|app1     |      1 asset
0|app1     |     Entrypoint undefined = index.html
0|app1     |        [0] (webpack)/buildin/module.js 519 bytes {0} [built]
0|app1     |        [1] (webpack)/buildin/global.js 509 bytes {0} [built]
0|app1     |        [2] ./node_modules/lodash/lodash.js 527 KiB {0} [built]
0|app1     |        [3] ./node_modules/html-webpack-plugin/lib/loader.js!./index.html 1.69 KiB {0} [built]
0|app1     | npm ERR! code ELIFECYCLE
0|app1     | npm ERR! errno 1
0|app1     | npm ERR! app1@1.0.0 start: `webpack-dev-server --mode production --open --hot `
0|app1     | npm ERR! Exit status 1
0|app1     | npm ERR!
0|app1     | npm ERR! Failed at the app1@1.0.0 start script.
0|app1     | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by chenhaihong** [comment]
Maybe u used the same port.
