### ISSUE TITLE
Error while executing  /usr/bin/git ls-remote -h -t http://ikt.pm2.io/ikt.git

### ISSUE THREAD

**Issue by Hammza1** [Unitech/pm2#4435]
## What's going wrong?
I can't install the dependencies while. whener i run npm install I got this issue: fatal: unable to access 'http://ikt.pm2.io/ikt.git/': Could not resolve host: ikt.pm2.io
## Supporting information

```
$ pm2 report
```

**Comment by gms-ge-juntilla** [comment]
i am also having this issue 😅

**Comment by Nico-92** [comment]
Same here

**Comment by Unitech** [comment]
```
npm install pm2@latest
```

**Comment by Unitech** [comment]
closing this issue, please upgrade to more recent PM2 version (this git thing was 4 years ago)

**Comment by godaipl** [comment]
> ```
> npm install pm2@latest
> ```

thanks ,It works right
