### ISSUE TITLE
Cannot use --spa with ecosystem file.

### ISSUE THREAD

**Issue by reservce** [Unitech/pm2#4438]
I try to use PM2 with "react-scripts build" and get 404-not-found issue when reloading the page.
Then I find a solution to run _pm2 serve_ with arguments _--spa_.
This command works perfectly:
`pm2 serve build --spa --port 8089.`
That 404 issue is solved with "--spa".
However,
## What's going wrong?
It's not working after changing to use ecosystem file:
_config.json_
```
{
  "apps": [
    {
      "script": "serve",
      "args": "--spa",
      "env": {
        "PM2_SERVE_PATH": "build",
        "PM2_SERVE_PORT": 8089
      }
    }
  ]
}
```

The 404 issue appears again.
It seems the "--spa" arg wasn't passed into a command line.
So did I config the ecosystem file correctly?

## How could we reproduce this issue?
Just create any demo react app and then:
1. react-scripts build
The source code will be in folder "build".
2. pm2 serve build --spa --port 8089 (Everything works fine)
3. pm2 start config.json (404 error when reload in a certain page)
## Supporting information
Nothing.

**Comment by Unitech** [comment]
In the "env" section you could add `PM2_SERVE_SPA: true`

**Comment by Unitech** [comment]
Doc has been updated: http://pm2.keymetrics.io/docs/usage/expose/

**Comment by Fit-garth888** [comment]
@Unitech https://shared-hosting.github.io/YffFVsaWTKrHbtyn_cxu0slWqwyh5REhkBA7WJ3uJAv7viCHu4sQNOWyegaAIjSw8rQzK22Sqa8/
