### ISSUE TITLE
Deploy conflicts with package-lock.json

### ISSUE THREAD

**Issue by endel** [Unitech/pm2#4440]
Hello there,

It is usually recommended to push the `package-lock.json` file into the repository. I wonder if this error I'm seeing is possible to avoid somehow? The server has to run `npm install`, and the package-lock.json file gets updated remotely, too. Thus, causing this error when trying to deploy after a change in the latest `package-lock.json` file in the repo:

```
--> Deploying to production environment
--> on host xxx.xxx.xxx.xxx
  ○ deploying origin/master
  ○ executing pre-deploy-local
  ○ hook pre-deploy
  ○ fast forward master
M	package-lock.json
Your branch is behind 'origin/master' by 6 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
Already on 'master'
From github.com:endel/xxx
 * branch            master     -> FETCH_HEAD
Updating d8b76ed..597182f
error: Your local changes to the following files would be overwritten by merge:
	package-lock.json
Please commit your changes or stash them before you merge.
Aborting

  git pull failed

Deploy failed
```

Appreciate your help! Cheers

**Comment by isikhi** [comment]
You can use ```npm ci```

**Comment by Unitech** [comment]
Looks like `npm ci` would fix that issue https://docs.npmjs.com/cli/ci.html#description Thanks for sharing @isikhi
