### ISSUE TITLE
can pm2 command line config be prior to the corresponding config of pm2.json

### ISSUE THREAD

**Issue by kris-ly** [Unitech/pm2#4446]
pm.json is as follow：
```JSON
{
    "apps": [
        {
            "script": "index.js",
            "instances": 8,
            "max_memory_restart": "1024M",
            "error_file": "/opt/logs/err/err.log",
            "out_file": "/opt/logs/log/out.log"
        }
    ]
  }
```

when start an application by follow command
```bash
$ pm2 start pm2.json -i 2
```
the config of instances is supposed to be 2 instead of 8, can pm2 support this usage？

**Comment by Unitech** [comment]
Nope you could not override the instances param via -i because you can multiple app in the ecosystem.json

**Comment by kris-ly** [comment]
> Nope you could not override the instances param via -i because you can have multiple app in the ecosystem.json

if the instances param doesn't exist in pm.json, `-i` in `pm2 start pm2.json -i 2` doesn't work??
