### ISSUE TITLE
pm2 deploy giving me perm issues on .git/index.lock 

### ISSUE THREAD

**Issue by visgotti** [Unitech/pm2#4447]
When I run my pm2 deploy command I get - 
fatal: Unable to create '/var/www/production/source/.git/index.lock': Permission denied

The user I'm logging into the server with 100% has all sudo rights. But it seems like when I'm trying to create the git index lock it won't let me because it's probably doing it without using sudo?

here's my deploy script

```
  "user" : "gotti",
      "host" : ["198.xxx.xx.xx2"],
      "ref"  : "origin/master",
      "repo" : "https://github.com/visgotti/repo.git",
      "path" : "/var/www/production",
      "ssh_options": ["StrictHostKeyChecking=no", "PasswordAuthentication=yes"],
      "pre-setup" : "../initial_server_setup.sh",
      "post-setup": "ls -la",
      "post-deploy" : "cd ./Web-Server; npm install && sudo pm2 startOrRestart ecosystem.json --env production",
      "env"  : {
        "NODE_ENV": "production"
      }
```

**Comment by Unitech** [comment]
Permission problems. You use pm2 with sudo, deploy without sudo etc. Not related to pm2, closing
