### ISSUE TITLE
How to set TOP secret environment variables in ecosystem.config.js ?

### ISSUE THREAD

**Issue by debianw** [Unitech/pm2#4448]
Since it is too risky to commit `ecosystem.config.js` with secret environment variables to a repository then how I could set environment variables coming from a CI like gitlab or CircleCI ?

Example:

```
module.exports = {
  apps: [
    {
      name: 'app-name',
      script: 'service.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env_staging: {
        TOP_SECRET_ENV_VARIABLE: process.env.TOP_SECRET_ENV_VARIABLE,
      }
    }
  ],

  deploy: {
    production: {
      user: 'xxxxxx',
      host: 'xxxxxx',
      ref: 'origin/master',
      repo: 'xxxxxx',
      path: 'xxxxxx',
      'post-deploy':
        'npm install && pm2 reload ecosystem.config.js --env production'
    },
  }
};
```

**Comment by imkane** [comment]
Great question, I'm also curious!

**Comment by marceloavf** [comment]
I'm also trying to do it, but not successful .

**Comment by debianw** [comment]
@marceloavf I gave up with `ecosystem.config.js`, it is so painful and don't support TOP secret environment variables.

I did my own recipe

**Comment by lhguerra** [comment]
@debianw do you mind sharing that recipe?

**Comment by ashiqsultan** [comment]
I solved it by storing the key in the server manually and requiring the key in `ecosystem.config.js` file
Example
* `/etc/config/apikey`  or store in the directory you wish.
* The file `api-key` will contain Top secret key.
Now in ecosystem.config.js file
```
//ecosystem.config.js
const  fs = require('fs');
const  path = require('path');
const  pathToSecretKey = path.join('/etc', 'dir-name', 'api-key');
const  secretKey = () => {
try {
	const  readSecretKey = fs.readFileSync(pathToSecretKey, 'utf8');
	return  readSecretKey.trim(); //triming the string to omit any trainling
} catch (error) {
	console.error(`Error reading Secret Key ${error}`);
	console.log('Exiting prosses with error status code 1');
	process.exit(1);
}
};
module.exports = {
	apps: [
		{
		name:  'site-api',
		script:  './index.js',
		instances:  0,
		exec_mode:  'cluster',
		autorestart:  true,
		max_memory_restart:  '1G',
		env: {
		  NODE_ENV:  'production',
		  SECRET_KEY:  secretKey()
		}
	}
]
};
```

**Comment by notflip** [comment]
I have a .env file (that holds my secrets) that I would love to have on my server, and I see that pm2 created a /shared folder when deploying, but I don't see how to use files in that folder?

**Comment by jishnu-cv** [comment]
I would still love to read a little paragraph about this in the PM2 official document, about the best practices.
I wonder why their [https://pm2.io/docs/runtime/best-practices/environment-variables/](url) page doesn't have any reference to this

**Comment by jishnu-cv** [comment]
Please reopen #4448 and make a note on this

**Comment by gie3d** [comment]
I'm not sure if this makes sense to you guys

```javascript
require('dotenv/config');
module.exports = {
    apps: [{
        name: 'app1',
        script: './dist/index.js',
        env: {
            ...process.env
        }
    }]
}
```
