### ISSUE TITLE
new(ish) systeminformation requirement reduces portability

### ISSUE THREAD

**Issue by ThePrez** [Unitech/pm2#4457]
## What's going wrong?
```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for systeminformation@4.14.12: wanted {"os":"darwin,linux,win32,freebsd,openbsd,netbsd,sunos","arch":"any"} (current: {"os":"aix","arch":"ppc64"})
npm ERR! notsup Valid OS:    darwin,linux,win32,freebsd,openbsd,netbsd,sunos
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   aix
npm ERR! notsup Actual Arch: ppc64
```
I believe this is caused by the new dependency on the not-as-portable `systeminformation` package, introduced here: 
https://github.com/Unitech/pm2/commit/2833774d7fb87430566706a37c1662474308ff37

This is troublesome for numerous customers running `pm2` on IBM i (reports OS as `aix`)

## How could we reproduce this issue?
`npm install -g pm2` on IBM i, AIX, or any other platform not supported by systeminformation

## Supporting information

Possible fixes:
1. Make systeminformation an optional requirement
2. Port systeminformation to more platforms
3. Revert the requirements on systeminformation

**Comment by Unitech** [comment]
Thanks for reporting.
I will make `systeminformation` optional for now while @sebhildebrandt might find a solution for IBM platforms.

**Comment by sebhildebrandt** [comment]
Thank you for reporting. Will have a look on porting systeminformation to other platforms.

**Comment by Unitech** [comment]
@ThePrez could you try the branch please:

```
npm install Unitech/pm2#development -g
```

And let me know if the install and PM2 initialization is running as expected

**Comment by ThePrez** [comment]
That branch does install cleanly. Thanks for a prompt response!

**Comment by Unitech** [comment]
release on 4.1.2

**Comment by ThePrez** [comment]
That's an amazing turnaround. Thanks, @Unitech !!!
