### ISSUE TITLE
git pull always falling on stderr

### ISSUE THREAD

**Issue by wolfzer44** [Unitech/pm2#4462]
## What's going wrong?

If I try to do a git pull using pm2 deploy always the return will fall on stderr no matter if it was a working or not.

## How could we reproduce this issue?
```await spawn('pm2',['deploy', ENV, 'update', 'exec', 'git', 'pull'])```

**Comment by Unitech** [comment]
Please open an issue on https://github.com/Unitech/pm2-deploy and CC @vladimyr
Might me linked to https://github.com/Unitech/pm2-deploy/pull/179
