### ISSUE TITLE
Version 4.1.0 broke something when using an interpreter with arguments

### ISSUE THREAD

**Issue by SamD** [Unitech/pm2#4463]
## What's going wrong?
Setup an ecosystem file using `ts-node` as the interpreter and `ts-node` arguments
e.g.
```
    interpreter: node_modules/.bin/ts-node
    interpreter_args: -T -r tsconfig-paths/register
```
results in node.js being called for some reason

## How could we reproduce this issue?
full sample ecosystem app configuration
```
apps:
  - name: server
    script: ./src/main.ts
    watch: ['./src']
    ignore_watch: ['node_modules']
    interpreter: node_modules/.bin/ts-node
    interpreter_args: -T -r tsconfig-paths/register
    instances: 1
    env:
      CONFIG_ENV_FILE: application.properties.yaml
    env_development:
      NODE_ENV: development
      DEBUG: axios
      TS_NODE_TRANSPILE_ONLY: true
      TS_NODE_TYPE_CHECK: true
    env_production:
      NODE_ENV: production
```

## Supporting information

After upgrading pm2 an application that had started fine was immediately failing due to too many restarts, looking at the pm2.log it displayed
```
.nvm/versions/node/v12.12.0/bin/node: bad option: -T
2019-10-18T16:27:23: PM2 log: App server-dev id:0 disconnected
2019-10-18T16:27:23: PM2 log: App [server-dev:0] exited with code [9] via signal [SIGINT]
2019-10-18T16:27:23: PM2 log: App [server-dev:0] starting in -cluster mode-
``` 
My interpreter is ts-node not node, but the log shows node being invoked

This does not exist in `4.0.2` but does in `4.1.0` 

Another thing is I did not start using `cluster` mode, where the mode that displays in `4.0.2` which works is `fork`

**Comment by Unitech** [comment]
Hi,
Now when specifying `instances` to 1 and not specifying the `exec_mode` will automatically run your application in cluster_mode to be able to `pm2 scale app`.

Either remove `instances:  1` or keep it but specify `exec_mode: 'fork'`
https://github.com/Unitech/pm2/blob/master/CHANGELOG.md#410

**Comment by SamD** [comment]
> Hi,
> Now when specifying `instances` to 1 and not specifying the `exec_mode` will automatically run your application in cluster_mode to be able to `pm2 scale app`.
> 
> Either remove `instances: 1` or keep it but specify `exec_mode: 'fork'`
> https://github.com/Unitech/pm2/blob/master/CHANGELOG.md#410

Thanks!

**Comment by bwgjoseph** [comment]
Hi @Unitech,

Didn't want to open up an issue, but maybe the [documentation](https://pm2.keymetrics.io/docs/usage/pm2-doc-single-page/#advanced-features) can be updated to indicate this?

I was wondering why was this happening after I upgraded to `4.1.x` as well.

Thanks.
