### ISSUE TITLE
connect EACCES 127.0.0.1:3306 need help

### ISSUE THREAD

**Issue by Domitresku** [Unitech/pm2#4465]
Hey, I have a problem. Yesterday, my server was working fine, but today? It came out with this

[ERROR] connect EACCES 127.0.0.1:3306

[ERROR] [MySQL] [es_extended] An error happens on MySQL for query "SELECT * FROM items": connect EACCES 127.0.0.1:3306
[ERROR] [MySQL] [es_extended] An error happens on MySQL for query "SELECT * FROM jobs": connect EACCES 127.0.0.1:3306

SCRIPT ERROR: @es_extended/server/common.lua:23: bad argument #1 to 'for iterator' (table expected, got nil)
> ref (@es_extended/server/common.lua:23)
> setImmediate (@mysql-async/mysql-async.js:14431)

SCRIPT ERROR: @es_extended/server/common.lua:35: attempt to get length of a nil value (local 'result')
> fn (@mysql-async/lib/MySQL.lua:197)

Can someone help me? I would be very thankful

**Comment by ElvisJin** [comment]
I also get this error.

Server is running on port 8080.
error:  Error: connect EACCES ::1:3306
  at TCPConnectWrap.afterConnect [as oncomplete] (d:\WORK\Dev\Express.js\nodejs-express-mysql\lib\net.js:1494:16)
  ... ...

Please help me. 
Could you tell me how did you solve your problem?

**Comment by YuriiKulis** [comment]
The error message "Error: connect EACCES ::1:3306" typically indicates a permissions issue when trying to connect to MySQL database on localhost (::1 is the IPv6 representation of localhost).  
 
Here are a few steps to troubleshoot and resolve this issue: 
 
1. **Check MySQL Connection Settings**: Make sure your MySQL server is running and listening on port 3306. Also, verify the username, password, and database name in your connection configuration. 
 
2. **Check Firewall Settings**: Ensure that your firewall is not blocking the connection to MySQL on port 3306. 
 
3. **Check User Permissions**: Verify that the user you are using to connect to the MySQL database has the necessary permissions to access the database. 
 
4. **Check MySQL Configuration**: Check the MySQL configuration file (my.cnf) to ensure that MySQL is configured to allow connections from localhost. 
 
5. **Check Port Availability**: Make sure that port 3306 is not being used by another application on your system. 
 
By following these steps, you should be able to diagnose and resolve the "Error: connect EACCES ::1:3306" issue. Let me know if you need further assistance.
