### ISSUE TITLE
A Problem with Not Normal Return in Terminal

### ISSUE THREAD

**Issue by waitspring** [Unitech/pm2#4467]
## What's going wrong?
I have installed the PM2 with the command `npm install -g pm2`, but however I excute any pm2 command, my terminal just return me this information:
> [root ~]# pm2 -v  
> [PM2] Spawning PM2 daemon with pm2_home=/root/.pm2  
> [root ~]#

**Comment by waitspring** [comment]
I have checked the /root/.pm2 directory and find the error log in  /opt/.pm2/pm2.log file, like this:

> /usr/lib/node_modules/pm2/node_modules/chokidar/index.js:150
>  async remove(item) {
>        ^^^^^^
>
> SyntaxError: Unexpected identifier
>    at createScript (vm.js:56:10)
>    at Object.runInThisContext (vm.js:97:10)
>    at Module._compile (module.js:549:28)
>   at Object.Module._extensions..js (module.js:586:10)
>   at Module.load (module.js:494:32)
>   at tryModuleLoad (module.js:453:12)
>   at Function.Module._load (module.js:445:3)
>   at Module.require (module.js:504:17)
>   at require (internal/module.js:20:19)
>   at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/Watcher.js:6:16)

**Comment by waitspring** [comment]
Maybe this is a version problem!  
If we use the commad `npm uninstall -g pm2` to remove pm2, and use the command `npm install -g pm2@3.5.1` re-install pm2, we can use the pm2 normally.
Thanks for the friend Mr.chipallen2

**Comment by Unitech** [comment]
required node version for PM2 4.x is Node >=8.0
https://github.com/Unitech/pm2/blob/master/package.json#L7
