### ISSUE TITLE
Default wait_ready time?

### ISSUE THREAD

**Issue by kumarrishav** [Unitech/pm2#4472]
## What's going wrong?
What will happen if I use wait_ready to true and with listen_timeout but not using process.send('ready') anywhere.

Will app be ready after listen_timeout or there is some default value(as I didn't mention process.send('ready')) after which app is ready?

## Supporting information

```
$ pm2 report
```

**Comment by kumarrishav** [comment]
also, request starts reaching my express middleware before app is ready.

Say, listen_timeout is 60 sec (and wait ready to true) and I am not sending any process.send('ready').

 When am I sending request to the route, it starts giving 200 even before 60 sec. What should be the behavior of app before listen_timeout?

**Comment by kumarrishav** [comment]
https://github.com/Unitech/pm2/blob/master/lib/God.js#L290

Seems like app will get ready after listen_timeout if there is no process.send('ready')

**Comment by Unitech** [comment]
Is the doc clear enough to you here: https://pm2.keymetrics.io/docs/usage/signals-clean-restart/?

**Comment by kumarrishav** [comment]
Thanks for the reply. Got bit confused after reading above link and https://pm2.keymetrics.io/docs/usage/pm2-doc-single-page/#control-flow 

But after looking into the code. I got it.

But I still struggle with this: https://github.com/Unitech/pm2/issues/4473
