### ISSUE TITLE
How to disable " In-memory PM2 is out-of-date"?

### ISSUE THREAD

**Issue by topochkina** [Unitech/pm2#4476]
How to disable this alert after every command:
```
>>>> In-memory PM2 is out-of-date, do:
>>>> $ pm2 update
In memory PM2 version: 4.1.2
Local PM2 version: 3.5.1
```

**Comment by topochkina** [comment]
I need command check PID
`pm2 pid app.js`

and 

```

>>>> In-memory PM2 is out-of-date, do:
>>>> $ pm2 update
In memory PM2 version: 4.1.2
Local PM2 version: 3.5.1

2125
```

My application cannot receive PID automatically and because of this it does not restart.
How to remove this intrusive update from the output of the command?

**Comment by Unitech** [comment]
It means that you are running a CLI that is different from the version in memory.
Have you tried running `pm2 update`? 
Could you copy/paste the output of the command `which pm2`?

**Comment by topochkina** [comment]
> It means that you are running a CLI that is different from the version currently running.
> Have you tried running `pm2 update`?
> Could you copy/paste the output of the command `which pm2`?

I do not want to be updated. The system has been working automatically for years. Due to this pop-up message, the operation is broken.

**Comment by acardinale** [comment]
Same problem.
In my case it was NVM that caused the problem.
It was enough for me to delete the old version of Node.js where PM2 was installed
`nvm uninstall 8`

**Comment by jasonk** [comment]
For anybody else that ends up here from Google, after a lot of trying random things I found that this message is disabled if you run `pm2` with `--silent`.

This is especially helpful for things like `pm2 jlist` where the output won't be valid JSON because this message gets written to stdout, instead of stderr where it belongs.
