### ISSUE TITLE
service is running on pm2 but curl localhost:3000 does not response

### ISSUE THREAD

**Issue by linhchelsea** [Unitech/pm2#4484]
Hi guys, 

I am deploying 5 node js socket instances.
Today, I got an alert that one of them was dead. 
When I was checking the instances, I got a problem.
I typed pm2 list, my instance still work. 
After that, I tried to curl localhost:3000, oops, service did not response the index file.

Any body got this problem before?
I am so sorry because of my English!
Thank you so much!

**Comment by Unitech** [comment]
PM2 cannot check that your API is effectively listening and answering to a port. Have you checked the logs?

**Comment by linhchelsea** [comment]
Yes, but there is nothing in the log file.
