### ISSUE TITLE
Changing load balancing strategy

### ISSUE THREAD

**Issue by nestoru** [Unitech/pm2#4503]
# What's going wrong?
In cluster mode a given worker will eventually get overwhelmed  by long and cpu/ram intensive tasks while other workers will be literally at 0% CPU and/or app startup RAM consumption. Shouldn't pm2 have a by busyness strategy option in addition to the round robin strategy? A configurable strategy is fine fo course. 

## How could we reproduce this issue?
Make a simple app that responds to two endpoints /slow and /fast. Make sure the slow implementation eats CPU and RAM for 5 seconds. Make sure the fast returns the response after 100 msec. Make a bash loop that uses curl to run 1000 request or less depending on your dev hardware capacity.  Expected: CPU and memory to be distributed evenly. Received: At least one node will be consuming higher CPU and RAM and could even crash while other nodes are plenty of capacity.

## Supporting information
The pm2 documentation I was able to read states that round robin is the pm2 load balancing strategy. Apparently there is no way to change this. Most likely a new feature request? 

```
$ pm2 report
```

**Comment by aprilmintacpineda** [comment]
Yeah, I'm also looking into this. I'm creating a nodejs experimental app for my research and studies and I came across many ways to achieve clustering. One of which is by using nodejs cluster or something else like pm2's cluster. pm2 talked about cluster mode but I can't see any details about how it handles load balancing so I'm not sure if it's reliable for this matter.

**Comment by aprilmintacpineda** [comment]
Don't you dare!

**Comment by tunesmith** [comment]
best way I can think of for this is to not use cluster and instead use pm2 to load multiple instances on different ports, and use something like nginx or haproxy in front of it to load balance to the different instances using something like `leastconn` load balancing strategy. I haven't tried it myself but that's the theory.
