### ISSUE TITLE
pm2 4.2.0 not update in npmjs.

### ISSUE THREAD

**Issue by wayahead** [Unitech/pm2#4509]
Until now, pm2 in npms regsitry is still 4.1.2 although 4.2.0 has been released days. Could you please update pm2 release in npmjs? Thx

**Comment by Unitech** [comment]
Yes I'm finalizing some benchmarks before releasing 4.2.0

**Comment by Bodasia** [comment]
Can you give as any ETA? Thanks

**Comment by wayahead** [comment]
Many thanks for your response, I realized I should close this issue. By the way, what is ETA?

**Comment by Unitech** [comment]
I had to run a benchmark for a week to verify that no leak is happening

![image](https://user-images.githubusercontent.com/757747/69531737-b5dcf080-0f74-11ea-900a-6b79dad6a5e1.png)

Everything looks good so I will publish it by today

**Comment by Unitech** [comment]
This fix has been incorporated to the latest PM2 release.
To update:

```bash
npm install pm2@latest -g
pm2 update
````
