### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by OmgImAlexis** [Unitech/pm2#4510]
## What's going wrong?
I'm seeing a memory leak.

## How could we reproduce this issue?
Create `index.js` with this content.

```js
process.title = 'graphql-api';
setTimeout(() => {}, 1000000000);
```

Run `node index.js` and it'll show 30MB of RAM used in top.

<hr>

Create a `ecosystem.config.js` file with this content.
```js
const common = {
        name: 'graphql-api',
        script: './index.js',
        watch: false,
        wait_ready: true,
        listen_timeout: 3000,
        exp_backoff_restart_delay: 100,
        max_memory_restart: '200M'
};

const envs = {
        env_production: {
                NODE_ENV: 'production'
        }
};

module.exports = {
        apps: [{
                ...common,
                ...envs
        }]
};
```

Run `pm2 start ecosystem.config.js` and it'll show 35MB+ of RAM used in top. The RAM also keeps going up every few seconds. After about 10 minutes I've seen it hit as high as 100MB

## Supporting information
I'm only using 3.2.2 as per https://github.com/Unitech/pm2/issues/4256 and it change anything. I also tried this with 3.5.0 and the latest 4.1.2 with the same results.

```
root@unmini:/usr/local/node/graphql-api# pm2 report
===============================================================================
--- PM2 REPORT (Fri Nov 15 2019 20:36:02 GMT-0800 (Pacific Standard Time)) ----
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.2.2
node version         : 10.16.3
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
uptime               : 74min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.2.2
node version         : 10.16.3
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Celeron(R) CPU 1037U @ 1.80GHz
cpus nb              : 2
freemem              : 6961848320
totalmem             : 8283369472
home                 : /root
===============================================================================
--- PM2 list -----------------------------------------------
┌─────────────┬────┬─────────┬──────┬───────┬────────┬─────────┬────────┬─────┬───────────┬──────┬──────────┐
│ App name    │ id │ version │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem       │ user │ watching │
├─────────────┼────┼─────────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼──────┼──────────┤
│ graphql-api │ 0  │ 2.1.4   │ fork │ 16343 │ online │ 0       │ 2m     │ 0%  │ 36.2 MB   │ root │ disabled │
└─────────────┴────┴─────────┴──────┴───────┴────────┴─────────┴────────┴─────┴───────────┴──────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌─────────────┬────┬─────────┬──────┬───────┬────────┬─────────┬────────┬─────┬───────────┬──────┬──────────┐
│ App name    │ id │ version │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem       │ user │ watching │
├─────────────┼────┼─────────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼──────┼──────────┤
│ graphql-api │ 0  │ 2.1.4   │ fork │ 16343 │ online │ 0       │ 2m     │ 0%  │ 36.2 MB   │ root │ disabled │
└─────────────┴────┴─────────┴──────┴───────┴────────┴─────────┴────────┴─────┴───────────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
```

**Comment by OmgImAlexis** [comment]
That same app still running and you can see the memory has increased. Where as with `nohup` or just directly with `node` I don't see this issue at all.



```
--- PM2 report ----------------------------------------------------------------
Date                 : Fri Nov 15 2019 21:10:59 GMT-0800 (Pacific Standard Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 4.1.2
node version         : 10.16.3
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
uptime               : 32min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 4.1.2
node version         : 10.16.3
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Celeron(R) CPU 1037U @ 1.80GHz
cpus nb              : 2
freemem              : 6957559808
totalmem             : 8283369472
home                 : /root
===============================================================================
--- PM2 list -----------------------------------------------
┌────┬─────────────────────────┬─────────┬─────────┬──────────┬────────┬──────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name                    │ version │ mode    │ pid      │ uptime │ ↺    │ status   │ cpu      │ mem      │ user     │ watching │
├────┼─────────────────────────┼─────────┼─────────┼──────────┼────────┼──────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ 0  │ graphql-api             │ 2.1.4   │ fork    │ 16735    │ 31m    │ 0    │ online   │ 0.3%     │ 39.6mb   │ root     │ disabled │
└────┴─────────────────────────┴─────────┴─────────┴──────────┴────────┴──────┴──────────┴──────────┴──────────┴──────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/root/.pm2/pm2.log last 20 lines:
PM2        | 2019-11-15T20:37:24: PM2 log: pid=16343 msg=process killed
PM2        | 2019-11-15T20:37:52: PM2 log: [PM2][WORKER] Reset the restart delay, as app graphql-api is up for more than 30000
PM2        | 2019-11-15T20:38:47: PM2 log: PM2 successfully stopped
PM2        | 2019-11-15T20:38:48: PM2 log: ===============================================================================
PM2        | 2019-11-15T20:38:48: PM2 log: --- New PM2 Daemon started ----------------------------------------------------
PM2        | 2019-11-15T20:38:48: PM2 log: Time                 : Fri Nov 15 2019 20:38:48 GMT-0800 (Pacific Standard Time)
PM2        | 2019-11-15T20:38:48: PM2 log: PM2 version          : 4.1.2
PM2        | 2019-11-15T20:38:48: PM2 log: Node.js version      : 10.16.3
PM2        | 2019-11-15T20:38:48: PM2 log: Current arch         : x64
PM2        | 2019-11-15T20:38:48: PM2 log: PM2 home             : /root/.pm2
PM2        | 2019-11-15T20:38:48: PM2 log: PM2 PID file         : /root/.pm2/pm2.pid
PM2        | 2019-11-15T20:38:48: PM2 log: RPC socket file      : /root/.pm2/rpc.sock
PM2        | 2019-11-15T20:38:48: PM2 log: BUS socket file      : /root/.pm2/pub.sock
PM2        | 2019-11-15T20:38:48: PM2 log: Application log path : /root/.pm2/logs
PM2        | 2019-11-15T20:38:48: PM2 log: Process dump file    : /root/.pm2/dump.pm2
PM2        | 2019-11-15T20:38:48: PM2 log: Concurrent actions   : 2
PM2        | 2019-11-15T20:38:48: PM2 log: SIGTERM timeout      : 1600
PM2        | 2019-11-15T20:38:48: PM2 log: ===============================================================================
PM2        | 2019-11-15T20:39:00: PM2 log: App [graphql-api:0] starting in -fork mode-
PM2        | 2019-11-15T20:39:03: PM2 log: App [graphql-api:0] online

```


Please copy/paste the above report in your issue on https://github.com/Unitech/pm2/issues

**Comment by OmgImAlexis** [comment]
I noticed I still have `wait_ready` in the `ecosystem.config.js`.

Even if I add this section there's no different.
```js
if (process.send) {
	process.send('ready');
}
```

Same goes with removing the `wait_ready`.

**Comment by Unitech** [comment]
Been ~6hours that I run your sample code and there is no leak at all
Are you using pm2.io by any chance? So I can check what is happening

**Comment by OmgImAlexis** [comment]
The leak starts seconds after I run this.

Are you checking top? I’ve seen this on every machine I’ve tried it on.

No this is an internal app.

**Comment by Unitech** [comment]
Under Node v10.17.0
PM2 version 4.1.2

I started your sample app containing a `setTimeout(() => {}, 1000000000);`
The memory is stable over the long run, when the memory is not used actively we have to wait longer for garbage collections cycles.

Here us the memory usage of the app over 24h:
![image](https://user-images.githubusercontent.com/757747/69187235-7ba9c400-0b1a-11ea-972b-1354b202841e.png)

About PM2 memory usage itself it's also pretty stable over time (here we can see PM2 memory is being accessed many times because of some periodic workers, but at the end the memory does not *leak*):
![image](https://user-images.githubusercontent.com/757747/69187525-11455380-0b1b-11ea-921d-c3a4c1bf5b6e.png)

**Comment by OmgImAlexis** [comment]
@Unitech again check `top`. The issue comes down the process itself. There shouldn't be any reason the process has any increase in memory. I get pm2's process may increase but that's the god process not my app.

**Comment by OmgImAlexis** [comment]
If this issue just ends up being closed we'll just move away from pm2 as this is affecting most of our users.

**Comment by Unitech** [comment]
The first chart I showed you is the app with the `setTimeout[...]`.

If you prefer here is the screenshot of htop:
![Screenshot from 2019-11-20 10-38-56](https://user-images.githubusercontent.com/757747/69227453-1ab5d680-0b82-11ea-9e9c-7fe8eb9ce34f.png)

Memory over time of your graphql-api is STABLE over time.
Memory over time of PM2 God Daemon is STABLE over time.

I did not managed to reproduce your leak.

**Comment by OmgImAlexis** [comment]
Is there anything else I can do to debug as I’m seeing the issue on all the machines I test this on.

**Comment by Unitech** [comment]
Send me a screenshot over of your `top` screen

**Comment by OmgImAlexis** [comment]
It keeps climbing. RES goes up slowly at the start but as time goes on it'll go up quickly. 

![Screen Shot 2019-11-21 at 10 51 37 am](https://user-images.githubusercontent.com/6525926/69289604-f4a93880-0c4c-11ea-993c-5958ad9fc329.png)
![Screen Shot 2019-11-21 at 10 49 59 am](https://user-images.githubusercontent.com/6525926/69289605-f4a93880-0c4c-11ea-9ca4-ec04be94db56.png)

**Comment by OmgImAlexis** [comment]
Also noting I was seeing this going up quicker before. The screenshots above were just after a fresh boot so I'm not sure if that's affecting anything.

**Comment by OmgImAlexis** [comment]
@Unitech is https://github.com/Unitech/pm2/issues/4256 related? That's the issue that made me look into this. Our main app is seeing a climb of 1MB/s or higher in same cases.

**Comment by OmgImAlexis** [comment]
Here's a good example. The process with the smaller RES usage is one started with `node index.js`. Notice it doesn't increase at all.


![Screen Shot 2019-11-21 at 11 49 10 am](https://user-images.githubusercontent.com/6525926/69292270-9765b500-0c55-11ea-9d71-0113f21fc8ec.png)

![Screen Shot 2019-11-21 at 11 53 32 am](https://user-images.githubusercontent.com/6525926/69292269-9765b500-0c55-11ea-8be5-1ba02848d522.png)

**Comment by OmgImAlexis** [comment]
Unless I'm missing something the process itself shouldn't be using any more memory than running directly against `node`.

**Comment by OmgImAlexis** [comment]
![Screen Shot 2019-11-21 at 1 16 00 pm](https://user-images.githubusercontent.com/6525926/69299716-2b894980-0c61-11ea-84a6-939bac065d55.png)

**Comment by Unitech** [comment]
It’s not leaking memory, memory is stable over time. If you don’t want process orchestration run ‘pm2 start app.js —no-pmx’

**Comment by adamalexander** [comment]
@Unitech what is process orchestration?

**Comment by OmgImAlexis** [comment]
So I was right all along. 🙃

**Comment by leocwolter** [comment]
I was using pm2 (5.3.1) on a cloud run instance that presented memory leak issues, trie to update it to 6.0.5 and it didn't work, also tried to disable `pmx` and the memory leak continued to happen.
After removing pm2 (thats the only change between the images bellow), the memory leak was solved: 

With pm2:
![Image](https://github.com/user-attachments/assets/c9519164-2d3a-4b50-9169-6b6e5150da2d)

Without pm2: 
![Image](https://github.com/user-attachments/assets/74c21984-e4a6-49ec-bc50-b6d062f4f2ea)

**Comment by sondn-vvt** [comment]
@leocwolter what is your alternative for pm2 to produce that result?
