### ISSUE TITLE
Feature proposal: make available string interpolation(substitution) in the ecosystem file

### ISSUE THREAD

**Issue by alexander-gusev** [Unitech/pm2#4514]
If you need to dynamically compute and set some variables (in my case COMMIT_SHA environment variable), it could be conveniently to compute them directly in the ecosystem file.

Example:
ecosystem.yaml
```bash
apps:
  - script: ./
    env:
      COMMIT_SHA: 69a8849
```

I need to compute COMMIT_SHA dynamically since it's the current commit id. So now I just replace it every time I pull new commits with the help of this script
```bash
sed -i "" "s/COMMIT_SHA: .*/COMMIT_SHA: $(git rev-parse --short HEAD)/" ecosystem.yaml
```
However, it would be more comfortable to do it directly in the ecosystem file like here:
```bash
apps:
  - script: ./
    env:
      - COMMIT_SHA=$(git rev-parse --short HEAD)
```

This feature is implemented in the docker-compose file and I suppose in many others config files.
Thanks in advance 🙂

**Comment by pke** [comment]
Maybe that is to complex to implement. Easier might be to just support ENV substitution. Then you could export your COMMIT_SHA to an env variable before calling pm2

```yaml
apps:
  - script: ./
    env:
      - COMMIT_SHA=$COMMIT_SHA
```
