### ISSUE TITLE
warning pm2@4.1.2: The engine "embed" appears to be invalid.

### ISSUE THREAD

**Issue by cekvenich** [Unitech/pm2#4516]
I followed instructions to add trace.
I get warning:
warning pm2@4.1.2: The engine "embed" appears to be invalid.

**Comment by mrG0bliN** [comment]
true!

**Comment by Unitech** [comment]
This fix has been incorporated to the latest PM2 release.
To update:

```bash
npm install pm2@latest -g
pm2 update
````

**Comment by cekvenich** [comment]
This issues is not related to pm2 -g. It is regarding:
    "@pm2/io": ">=4.3.3"
So I guess you'll be releasing 4.3.4. When can we expect this?
