### ISSUE TITLE
HttpInterface exposes critical environment variables

### ISSUE THREAD

**Issue by MichielDeMey** [Unitech/pm2#452]
Hi,

My issue is that currently, the HttpInterface API exposes critical environment variables such as usernames and passwords.

I would suggest having an option to strip environment variables and other potentially sensitive information from the API, since we don't always want to expose this to others.

**Comment by jrottenberg** [comment]
The pull request is not valid anymore (need a rebase), but is there anything beside that prevents the integration ?

**Comment by LukasBeaton** [comment]
Any plans to merge this in?

This would be really nice to have!!!
