### ISSUE TITLE
pm2 in cluster mode with --wait-ready starts nodes in sequence 

### ISSUE THREAD

**Issue by sagir-ma** [Unitech/pm2#4521]
When running our app with pm2 in cluster mode with --wait-ready nodes start in sequence and not in parallel.
How can the nodes be started simultaneously?

**Comment by Unitech** [comment]
PM2_CONCURRENT_ACTIONS=16 pm2 restart APP

**Comment by sagir-ma** [comment]
Great, that worked.
Now when we add --listen-timeout 30000 it launches the nodes in sequence even when adding PM2_CONCURRENT_ACTIONS. How can we make it wait for our server to be ready and start nodes simultaneously?

**Comment by bogdank-ma** [comment]
In my case PM2_CONCURRENT_ACTIONS applies only when I **restart existing** processes (listed in dump.pm2)
When I start app for the **first** time on fresh instance, it still launches sequentially
Is it the expected behavior
