### ISSUE TITLE
Critical Error: [PM2][ERROR] Interpreter X is NOT AVAILABLE in PATH.

### ISSUE THREAD

**Issue by akopchinskiy** [Unitech/pm2#4528]
Critical Error during run of TypeScript code:

```
[PM2][ERROR] Interpreter C:\Users\work\AppData\Roaming\npm\node_modules\pm2\node_modules\.bin\ts-node is NOT AVAILABLE in PATH. (type 'which C:\Users\work\AppData\Roaming\npm\node_modules\pm2\node_modules\.bin\ts-node' to double check.)
```

**Command to run:**
`pm2 start ts-node ./src/plain.ts`

Simple run with `ts-node ./src/plain.ts` works normaly.

**Versions:** 
node= v13.2.0
tsc =3.7.2
ts-node = v8.5.2
pm2 4.2.0

**Comment by aapiw** [comment]
These are a few things need to try:
1. Install your nodejs correctly, because of the `Interpreter` seems was not installed properly, or try to do reinstall
2. Try to include the interpreter option e.g: `pm2 start ts-node ./src/plain.ts --interpreter /home/aapiw/.nvm/versions/node/v10.13.0/bin/node`
if you don't know where is your node path type `which node` and will show you the correct path

**Comment by akopchinskiy** [comment]
> These are a few things need to try:

> 1. Install your nodejs correctly, because of the `Interpreter` seems was not installed properly, or try to do reinstall

No. Everything works but this.

> 2. Try to include the interpreter option e.g: `pm2 start ts-node ./src/plain.ts --interpreter /home/aapiw/.nvm/versions/node/v10.13.0/bin/node`

And write script differently for dev and prod environments? No, thanks.

>    if you don't know where is your node path type `which node` and will show you the correct path

'which' is not recognized as an internal or external command,
operable program or batch file.

**Comment by avetisk** [comment]
I've got the same issue and it's driving me crazy! (I'm on macOS).

@akopchinskiy if I find the solution, I'll post it here.

**Comment by avetisk** [comment]
@akopchinskiy here's a cheap solution:

In the `types/index.d.ts` there's a mention:
```
/**
   * (Default: “node”) The interpreter for your script (eg “python”, “ruby”, “bash”, etc).
   * The value “none” will execute the ‘script’ as a binary executable.
   */
  interpreter?: string;
```

The important part is `The value “none” will execute the ‘script’ as a binary executable.`.

Thus, I was able to run it like this: 
```
yarn pm2-dev start --interpreter none '/bin/bash yarn ts-node -r tsconfig-paths/register ./run.ts'               
```

In your case it maybe a bit different on Windows, but I think this should work as expected too:

```
pm2 start --interpreter none 'ts-node ./src/plain.ts'
```

**Comment by vinirb15** [comment]
> Critical Error during run of TypeScript code:
> 
> ```
> [PM2][ERROR] Interpreter C:\Users\work\AppData\Roaming\npm\node_modules\pm2\node_modules\.bin\ts-node is NOT AVAILABLE in PATH. (type 'which C:\Users\work\AppData\Roaming\npm\node_modules\pm2\node_modules\.bin\ts-node' to double check.)
> ```
> 
> **Command to run:** `pm2 start ts-node ./src/plain.ts`
> 
> Simple run with `ts-node ./src/plain.ts` works normaly.
> 
> **Versions:** node= v13.2.0 tsc =3.7.2 ts-node = v8.5.2 pm2 4.2.0


install the ts package:
```
pm2 install typescript
```
and try again

**Comment by mdnelles** [comment]
My issue was with `ts-node` I constructed the following on ubuntu and it worked

```
pm2 start ./src/server.ts --interpreter /root/.nvm/versions/node/v16.16.0/bin/ts-node --watch --name node-server
```

NOTE: you can find the path to your `ts-node`  using which command
