### ISSUE TITLE
Replace momentjs with dayjs or luxon to drastically reduce bundle size

### ISSUE THREAD

**Issue by cktang88** [Unitech/pm2#4530]
Replace to reduce bundle size. Moment.js is about 20x heavier than dayjs and does basically the same thing :(
Day.js https://github.com/iamkun/dayjs
Luxon https://moment.github.io/luxon/

**Comment by Unitech** [comment]
Yes true that moment is bloated: https://bundlephobia.com/result?p=moment@2.24.0
I already started to migrate from moment with date-fns: https://bundlephobia.com/result?p=date-fns@2.8.1
 
I wonder if I Luxon is a drop in replacement of moment

**Comment by Unitech** [comment]
`
moment().format('LTS')
moment().diff(parseInt(t1))
`

This are the only momentjs calls ^^' so yes I will drop moment

**Comment by cktang88** [comment]
`dayjs` is a drop in replacement of moment, and is even lighter than `date-fns`... https://bundlephobia.com/result?p=dayjs@1.8.17

**Comment by Unitech** [comment]
date-fns + moment have been replaced by dayjs

**Comment by Unitech** [comment]
PM2 4.3.0 published:

```bash
npm install pm2@latest -g
pm2 update
```
