### ISSUE TITLE
Please bring back the --sort option

### ISSUE THREAD

**Issue by datdinhquoc** [Unitech/pm2#4536]
#3994  
## What's going wrong?
The --sort option is no longer available in PM2 4.2.
I have many processes running and usually use "pm2 delete all" to have the process ids reindexed from zero; and run "pm2 list --sort id" to see them in order. It's great that --sort option was in version 3.5 but it's sad now that --sort option is no longer in version 4.2. 
Please bring the --sort option back.

## How could we reproduce this issue?
Use PM2 3.5, run: pm2 list --sort id
[A table with rows sorted by id]

Use PM2 4.2, run: pm2 list --sort id
error: unknown option `--sort'

**Comment by datdinhquoc** [comment]
not stale pls, this --sort option is useful

**Comment by jimmybrancaccio** [comment]
No, bad bad.

**Comment by LewisTehMinerz** [comment]
Good feature, bad bot.

**Comment by 10w73** [comment]
I'd love to see you bringing --sort back too!

**Comment by BarryThrill** [comment]
I agree! Even if its possible to add --sort namespace:desc aswell!

**Comment by AcidSlide** [comment]
Yup "--sort" is very useful.. please please please bring it back

why did they remove it (again) anyway??? this is I think the second time they removed it

**Comment by Unitech** [comment]
option restored, will land on next release

**Comment by db926** [comment]
> option restored, will land on next release
When is the next release ?

**Comment by Unitech** [comment]
Released:

```bash
npm install pm2@latest -g
pm2 update
```

Cheers!

**Comment by AcidSlide** [comment]
Thanks! `--sort` is a very helpful option.  Tested and working! Super thanks!

I just hope they don't remove it (again) in future releases.. hahaha
