### ISSUE TITLE
PM2 start treats sub-string as a seperate command.

### ISSUE THREAD

**Issue by Shubham-S-Yadav** [Unitech/pm2#4538]
![pm2-v4 2 0](https://user-images.githubusercontent.com/31968975/70782776-cd5a0d00-1dad-11ea-9923-7e3827221d02.PNG)
![pm2-v4 1 2](https://user-images.githubusercontent.com/31968975/70782874-098d6d80-1dae-11ea-9998-62b4f7a847ef.PNG)

## What's going wrong?
While using pm2 start getting error in latest version of pm2, it is treating sub-strings inside a string as a separate command where as in 4.1.2 it is working properly.

## How could we reproduce this issue?
on command prompt you can hit command as:
==> pm2 start "python3 manage.py runserver 0.0.0.0:8000"
(command specific to python ,Django)

## Supporting information
Also attaching snaps of the issues.
Thank you guys for this wonderful library, keep up the good work :)

```
$ pm2 report
```

**Comment by Shubham-S-Yadav** [comment]
@Unitech any updates on the issue?

**Comment by michaldolnik** [comment]
@Unitech I am experiencing the same issue. I want to pass one command line argument to python script, but it does not work. Do you have any update ?

**Comment by Unitech** [comment]
Just did exec:

```
pm2 start "python -c \"print('X')\""
```

And it worked as expected:

```
[TAILING] Tailing last 15 lines for [1] process (change the value with --lines option)
/home/unitech/.pm2/logs/python--c--print--X----error.log last 15 lines:
/home/unitech/.pm2/logs/python--c--print--X----out.log last 15 lines:
1|python - | X
1|python - | X
1|python - | X
1|python - | X
1|python - | X
1|python - | X
1|python - | X
1|python - | X
1|python - | X
1|python - | X
1|python - | X
1|python - | X
1|python - | X
1|python - | X
1|python - | X
```

**Comment by michaldolnik** [comment]
And how should it be run when I want to run script.py and pass parameter to it? 

I am doing it this way:
`pm2 start script.py --name appname --interpreter python3 -- config/xyz.yml`

Thanks

**Comment by Unitech** [comment]
Just tried:

```
#!/usr/bin/python                                                                                                                                                                                                    
import time
import sys

while 1:
    arguments = len(sys.argv) - 1
    position = 1
    print ("The script is called with %i arguments" % (arguments))
    while (arguments >= position):
        print ("Parameter %i: %s" % (position, sys.argv[position]))
        position = position + 1
    print("Start : %s" % time.ctime())
    print("second line")
    time.sleep(1)
```

and 

```
pm2 start echo.py --name appname --interpreter python3 -- myarg
```

Prints:

```
0|appname  | The script is called with 1 arguments
0|appname  | Parameter 1: myarg
0|appname  | Start : Fri Jan 29 09:36:37 2021
0|appname  | second line
0|appname  | The script is called with 1 arguments
0|appname  | Parameter 1: myarg
0|appname  | Start : Fri Jan 29 09:36:38 2021
0|appname  | second line
```
