### ISSUE TITLE
Memory default limit

### ISSUE THREAD

**Issue by EvilPsycho656** [Unitech/pm2#4542]
## What's going wrong?
my pm2 services that run under a specific user (about 10 services) restart randomly twice or three times a day for about 1 minute of constant restarting, which causes the server cpu to rise to about 98%.
i want to ask what is the default memory limit for all services that run under one user, and if that limit is reached does it restart them (total pm2 limit not per service)?
What could cause the restart issue? is there a way i can find logs of this issue?

## Supporting information
my pm2 version is 3.5.1
i run node v6 and v11 services.

```

```

**Comment by Unitech** [comment]
Please upgrade to more latest PM2
