### ISSUE TITLE
pm2 & jailkit configuration

### ISSUE THREAD

**Issue by Tripayou** [Unitech/pm2#4548]
Hi!
I'm trying to run apps with pm2 in a jail environment using jailkit. I think I have to configure a path somewhere but I'm lost with it. My config files:
- startup script:
```
[Unit]
Description=PM2 process manager
Documentation=https://pm2.keymetrics.io/
After=network.target

[Service]
Type=forking
User=<USER>
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
Environment=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
Environment=PM2_HOME=/home/jail/home/<USER>/.pm2
PIDFile=/home/jail/home/<USER>/.pm2/pm2.pid
Restart=on-failure

ExecStart=/usr/lib/node_modules/pm2/bin/pm2 resurrect
ExecReload=/usr/lib/node_modules/pm2/bin/pm2 reload all
ExecStop=/usr/lib/node_modules/pm2/bin/pm2 kill

[Install]
WantedBy=multi-user.target
```
- app section in ecosystem file:
```
{
	name: '<APP_NAME>',
	script: '<APP_NAME>/index.js',
	cwd: '/home/jail/home/<USER>',
	error_file: '.pm2/logs/<APP_NAME>-error.log',
	out_file: '.pm2/logs/<APP_NAME>-out.log'	
}
```

If I try to run app with `pm2 start <APP_NAME>` I get the following error:

`[PM2][ERROR] Error while launching application Error: ENOENT: no such file or directory, open '/home/<USER>/.pm2/logs/<APP_NAME>-out.log`

The files are in the jail:

`ls /home/jail/home/<USER>/.pm2/logs`
`<APP_NAME>-error.log <APP_NAME>-out.log`

but `/home/<USER>` folder doesn't exists.

I think pm2 is looking for files in `/home/<USER>` instead of `/home/jail/home/<USER>` but I don't know how to fix it.
Thnanks for the help!

**Comment by Unitech** [comment]
Use the PM2_HOME environment variable to access to your chrooted PM2.
`PM2_HOME=/home/jail/home/<USER>/.pm2 pm2 ls`
