### ISSUE TITLE
how to setup pm2 when using same disk

### ISSUE THREAD

**Issue by LoveofRedMoon** [Unitech/pm2#4550]
I have two servers names A B
A & B has the same disk storage
but A & B have different memory

when I start some projects with pm2 on A & B
they will modify the same path to write PID
this cause 'pm2 list' shows no applications but the appliction process already exists

**Comment by Unitech** [comment]
You can override `PM2_HOME=/other/folder pm2 ls` to run a second PM2 on the same machine. But note that to access to this second daemonized PM2, you will have to specify this new PM2_HOME each time you run a command

**Comment by LoveofRedMoon** [comment]
> You can override `PM2_HOME=/other/folder pm2 ls` to run a second PM2 on the same machine. But note that to access to this second daemonized PM2, you will have to specify this new PM2_HOME each time you run a command

Thanks a lot!
I encapsulated the command named 'PM3' and linked with `PATH`
so I can use command 'pm2 list' on A
and command 'pm3 list' on B
