### ISSUE TITLE
Error when disabling logs

### ISSUE THREAD

**Issue by codpot** [Unitech/pm2#4560]
## What's going wrong?

(1)
When "out_file" or "error_file" set to "/dev/null" in Windows.
PM2 creates "C:\dev\null".
Stop PM2 app and remove "C:\dev" folder.
Start PM2 app occurs error.

(2)
When "out_file" or "error_file" set to "NULL" in Windows and Linux.
When run "pm2 flush", PM2 creates file named "NULL".

## How could we reproduce this issue?

(1)
pm2 start ecosystem.config.js
pm2 stop all
REMOVE C:\DEV
pm2 start all

(2)
pm2 start ecosystem.config.js
pm2 flush all

## Supporting information

```
$ pm2 report
```

**Comment by Unitech** [comment]
PM2 4.3.0 published:

```bash
npm install pm2@latest -g
pm2 update
```
