### ISSUE TITLE
Restart command makes PM2 start two processes

### ISSUE THREAD

**Issue by Nicklason** [Unitech/pm2#4567]
## What's going wrong?

When I restart a process by ecosystem file, two processes are spawned. I looked at the logs and I think I found a pattern in what it does when it restarts properly, and when it starts two processes.

When restarting the process by name it works how I would expect it (pm2 restart myscript). It stops the process and once it has been killed it starts a new one. Log:

App [myscript:0] exited with code [0] via signal [SIGINT]
App [myscript:0] will restart in 1000ms
pid=23476 msg=process killed
App [myscript:0] starting in -fork mode-
App [myscript:0] online

But when I restart it by ecosystem file (pm2 restart ecosystem.json), it does this:

pid=35060 msg=process killed
App [myscript:0] starting in -fork mode-
App [myscript:0] online
App [myscript:0] exited with code [0] via signal [SIGINT]
App [myscript:0] will restart in 1000ms
App [myscript:0] starting in -fork mode-
App [myscript:0] online

It is almost like it does the same but in a different order, which results in the script being started twice. To me it looks like it sees that the process is killed and starts it, but then it sees that the original process exited and then starts it yet again.

Since the script is ran twice, one of them crashes and is then restarted, making the other process crash and restart, and it continues like this until I kill the PM2 daemon. Using `pm2 kill` stops both processes.

## Supporting information

--- PM2 report ----------------------------------------------------------------
Date                 : Sun Jan 05 2020 20:10:04 GMT+0100 (Centraleuropæisk normaltid)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 4.2.1
node version         : 13.5.0
node path            : not found
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\nickl\AppData\Roaming\npm\node_modules\pm2\lib\Daemon.js
argv0                : node
user                 : undefined
uid                  : N/A
gid                  : N/A
uptime               : 0min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 4.2.1
node version         : 13.5.0
node path            : not found
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\nickl\AppData\Roaming\npm\node_modules\pm2\bin\pm2,report
argv0                : node
user                 : nickl
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : win32
type                 : Windows_NT
cpus                 : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
cpus nb              : 16
freemem              : 17528840192
totalmem             : 34274660352
home                 : C:\Users\nickl
===============================================================================

**Comment by clint-latch** [comment]
Seeing this issue as well. Windows seems to be the common cause

**Comment by freakcoderz** [comment]
> Seeing this issue as well. Windows seems to be the common cause

I have the same issue on Linux. Happened after using save

**Comment by laocoi** [comment]
Getting the same issue in Windows. Must restart the computer every time update the code
