### ISSUE TITLE
Wrong CWD using pm2-runtime

### ISSUE THREAD

**Issue by daaru00** [Unitech/pm2#4576]
## What's going wrong?

When using `pm2-runtime process.yml` current working directory passed to NodeJS script become: `./process.yml/` as a "directory parameters" or somethings similar.

Set "cwd" app's option configuration in `process.yml` does not made any difference, seems completely ignored.

## How could we reproduce this issue?

I follow [Docker guide](https://pm2.keymetrics.io/docs/usage/docker-pm2-nodejs/) and created a `process.yml` file:
```yaml
apps:
  - script: ./node_modules/nuxt-start/bin/nuxt-start.js
    name: 'app'
    instances: 'max'
    exec_mode: cluster
    env: 
      NODE_ENV: 'production'
```
then set Docker entrypoint to `/usr/bin/pm2-runtime process.yml` (guide suggest to use `CMD ["pm2-runtime", "process.yml"]` that has the same effect) and Nuxt fail during start-up:
```
Error: No build files found in /app/process.yml/.nuxt/dist/server. 
```
my app reside in `/app` (as volume), so you can notice the wrong CWD "/app/process.yml/" passed to script.

## Supporting information

```

--- PM2 report ----------------------------------------------------------------
Date                 : Thu Jan 09 2020 16:52:39 GMT+0000 (Coordinated Universal Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 4.2.1
node version         : 10.17.0
node path            : not found
argv                 : /usr/bin/node,/usr/bin/pm2-runtime,process.yml,--only,app
argv0                : node
user                 : undefined
uid                  : 0
gid                  : 0
uptime               : 0min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 4.2.1
node version         : 10.17.0
node path            : not found
argv                 : /usr/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : undefined
uid                  : 0
gid                  : 0
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
cpus nb              : 8
freemem              : 253816832
totalmem             : 16698138624
home                 : /root
===============================================================================
--- PM2 list -----------------------------------------------
┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │
├────┼────────────────────┼──────────┼──────┼───────────┼──────────┼──────────┤
│ 0  │ app                │ cluster  │ 5    │ online    │ 0%       │ 35.1mb   │
│ 1  │ app                │ cluster  │ 5    │ launching │ 0%       │ 0b       │
│ 2  │ app                │ cluster  │ 4    │ online    │ 58.2%    │ 60.9mb   │
│ 3  │ app                │ cluster  │ 4    │ online    │ 0%       │ 50.8mb   │
│ 4  │ app                │ cluster  │ 4    │ online    │ 0%       │ 50.7mb   │
│ 5  │ app                │ cluster  │ 4    │ online    │ 0%       │ 43.2mb   │
│ 6  │ app                │ cluster  │ 4    │ online    │ 0%       │ 39.8mb   │
│ 7  │ app                │ cluster  │ 4    │ launching │ 0%       │ 0b       │
└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
```

**Comment by daaru00** [comment]
Same error using `pm2-runtime start ecosystem.config.js`:
```
Error: No build files found in /app/ecosystem.config.js/.nuxt/dist/server
```

**Comment by jsjain** [comment]
any updates on this issue ?

**Comment by koeshiro** [comment]
And again FATAL  No build files found in /docker-.../pm.config.js/.nuxt/dist/server

**Comment by k90mirzaei** [comment]
I have same issue @jsjain, Did you find any solution?

**Comment by jsjain** [comment]
giving the cwd, fixed it for me

**Comment by mercs600** [comment]
@jsjain cwd in ecosystem file ? can you give an example ?

**Comment by jsjain** [comment]
yeah sure, `cwd: '/user/src/app'` assuming this is where your code is. and along with it script will still be the same `script: ./node_modules/nuxt-start/bin/nuxt-start.js`

**Comment by mercs600** [comment]
thanks @jsjain, but finally I changed my script in ecosystem, because our app is working in workspace: 

```js
  script: './node_modules/nuxt/bin/nuxt.js',
  args: `-c ${join(__dirname, 'packages/your-app/nuxt.config.js')}`,
```

**Comment by tcstory** [comment]
meet the same problem. can anyone help?

**Comment by scribnar** [comment]
I have the same issue. Any fix?

**Comment by TheSycamore** [comment]
I also have the exact same problem

**Comment by TheSycamore** [comment]
I am experiencing the same problem.

node: v14.16.0
nuxt: 2.15.3
pm2: 4.5.5

**Works fine:**
pm2 start ecosystem.config.js

**Doesn't work:**
pm2-runtime start ecosystem.config.js

**Error output:**
```
✖ Nuxt Fatal Error
Error: No build files found in /var/www/ui/ecosystem.config.js/.nuxt/dist/server.
Use either `nuxt build` or `builder.build()` or start nuxt in development mode.
```

As you can see from above the path is incorrect:

**Incorrect path:**
`/var/www/ui/ecosystem.config.js/.nuxt/dist/server`

**Intended path:**
`/var/www/ui/.nuxt/dist/server`


My /var/www/ui/ecosystem.config.js file:
```
module.exports = {
  apps: [
    {
      name: 'ui',
      cwd: '/var/www/ui/',
      exec_mode: 'cluster',
      instances: 'max', // Or a number of instances
      script: './node_modules/nuxt/bin/nuxt.js',
      args: 'start',
      env: {
        NODE_ENV: "development",
      },
      env_production: {
        NODE_ENV: "production",
      }
    }
  ]
}
```



Multiple people are having this issue including myself:
https://github.com/Unitech/pm2/issues/4576
https://github.com/nuxt/nuxt.js/issues/8704
https://github_com.jam.dev/nuxt/nuxt.js/issues/8723

**Comment by maosmurf** [comment]
FWIW this also happens with NextJS

**Comment by saachinsiva** [comment]
I am trying to run NextJS in Docker with pm2 and get similar error. anybody have any luck running this in cluster mode?

**Comment by galaxy-s10** [comment]
> 我正在尝试使用 pm2 在 Docker 中运行 NextJS 并得到类似的错误。有人有幸在集群模式下运行它吗？
> 
> 我的 Docker 命令如下所示：CMD [ "pm2-runtime" ,"start","pm2.json"]
> 
> pm2.json文件
> 
> ```
> {
>   "apps": [
>     {
>       "name": "App-Client",
>       "cwd": "/usr/app/client",
>       "script": "node_modules/next/dist/bin/next",
>       "args": "start -p 4000",
>       "instances": "max",
>       "exec_mode": "cluster",
>       "kill_timeout": 5000,
>       "env": { "NODE_ENV": "production", "production": true }
>     }
>   ]
> }
> ```
> 
> 错误：（如您所见，它在 pm2.json 文件夹中寻找 .next 文件夹）
> 
> 2021-12-03T04:31:51：PM2 日志：App [App-Client:0] 通过信号 [SIGINT] 以代码 [1] 退出 2021-12-03T04:31:51：PM2 日志：App [App-Client :0] 从 -cluster 模式开始- 错误：无法在 '/usr/app/client/pm2.json/.next' 目录中找到有效的构建！在启动服务器之前尝试使用“下一次构建”构建您的应用程序。 在 Server.readBuildId (/usr/app/dip/client/node_modules/next/next-server/server/next-server.ts:1671:15) 在新服务器 (/usr/app/dip/client/node_modules/next /next-server/server/next-server.ts:179:25) 在 createServer (/usr/app/dip/client/node_modules/next/server/next.ts:41:10) 在启动时 (/usr/app /dip/client/node_modules/next/server/lib/start-server.ts:9:15) 在 exec (/usr/app/dip/client/node_modules/next/cli/next-start.ts:53:3 ) 在 /usr/app/dip/client/node_modules/next/bin/next.ts:107:36 2021-12-03T04:31:51: PM2 日志：App 名称：App-Client id：1 已断开连接

me too

**Comment by yigitsimsek** [comment]
Why was this closed? I have the same problem with NextJS and I've been trying to fix it for some time now.
