### ISSUE TITLE
App started by jenkins did not show in ssh terminal

### ISSUE THREAD

**Issue by harrisoff** [Unitech/pm2#4582]
## What's going wrong?
I ran `sudo pm2 startOrReload ecosystem.config.js` and `sudo pm2 status` in jenkins shell, and in the jenkins console output I could see the process was created.
![impicture_20200119_200949](https://user-images.githubusercontent.com/29137942/72680690-bf5b8280-3af7-11ea-9809-89ed0b1427fa.png)

After that when I logged in to the server by ssh, `pm2 status` returned an empty table, but the process did exist.
![impicture_20200119_200850](https://user-images.githubusercontent.com/29137942/72680692-c2567300-3af7-11ea-9eb4-7ee3cfc53601.png)

## How could we reproduce this issue?
jenkins v2.190.3

1. A simple express server.
   1. ecosystem.config.js
      ```js
      module.exports = {
        apps: [{
          name: 'upload-server',
          script: 'app.js',
          instances: 1,
          autorestart: false,
          watch: false,
          max_memory_restart: '1G',
        }],
      };
      ```
2. deploy with jenkins
   1. use github repo
   2. shell command
      ```shell
      echo $WORKSPACE
      npm i
      sudo pm2 -v
      sudo pm2 startOrReload ecosystem.config.js
      sudo pm2 status
      ps -aux|grep pm2
      ```
   3. other settings leave default

## Supporting information

```
$ pm2 report
```
![impicture_20200119_201944](https://user-images.githubusercontent.com/29137942/72680810-1ca40380-3af9-11ea-9655-360ca0c8a7ea.png)

Chat is another app which I operated through ssh terminal.
Upload-server was started by jenkins, and its logs were not showing in the report.

**Comment by sgnd** [comment]
I have the same problem as this.

**Comment by harrisoff** [comment]
@sgnd 
Switch to user jenkins and use `sudo` will work.
```shell
su jenkins
sudo pm2 status
```
Now I'm not sure if it is a bug or I'm lacking in Linux knowledge.

**Comment by sgnd** [comment]
@harrisoff thank you for the reply.
I trying to run that command
```
$ sudo su jenkins
$ sudo pm2 list
[sudo] password for jenkins:
```
Need password to run pm2, what the password for jenkins?

**Comment by harrisoff** [comment]
@sgnd 
Sorry this didn't happen to me.
