### ISSUE TITLE
My PM2 application does not respond when it comes to a certain memory size

### ISSUE THREAD

**Issue by mronline** [Unitech/pm2#4592]
## What's going wrong?

I have a socket application running on PM2. When my application reaches 580MB, it no longer responds and cannot be accessed either from the socket or from http. Is there a default memory limit of PM2? There is no error in PM2 error logs as to why this is the case. If I use --max-old-space-size, will my problem be fixed?

```
Server:
CentOS Linux release 7.6.1810 (Core) x86_64
Memory: 3GB
Nodejs v10.15.3
PM2: 3.5.0
```

## Supporting information

```
$ pm2 report
```

**Comment by Unitech** [comment]
You can use https://pm2.keymetrics.io/docs/usage/memory-limit/
