### ISSUE TITLE
pm2 doesn't allow me to save

### ISSUE THREAD

**Issue by ObakeFilter** [Unitech/pm2#4594]
Hey guys, I've met with an odd problem which prevents me to use the current pm2 installation, and doesn't disappear even after updating / removing & updating pm2 using NPM.

When typing pm2 status, I get the following warning.

[PM2][WARN] Current process list running is not in sync with saved list. www differs. Type 'pm2 save' to synchronize.
![image](https://user-images.githubusercontent.com/10092363/73613200-f784ba00-45fb-11ea-93f0-c4c60b51e33b.png)

Trying to save, gives me the following error.
![image](https://user-images.githubusercontent.com/10092363/73613208-0f5c3e00-45fc-11ea-8675-30b62fc0e271.png)

Even though my dump.pm2 does exist in the correct path.
![image](https://user-images.githubusercontent.com/10092363/73613237-40d50980-45fc-11ea-8961-48bba4d67345.png)
![image](https://user-images.githubusercontent.com/10092363/73613300-c0fb6f00-45fc-11ea-9435-c6f0eefa3daa.png)

Also, running pm2 -h gives me the following:
![image](https://user-images.githubusercontent.com/10092363/73613245-5b0ee780-45fc-11ea-98da-f0b27126e7cf.png)

I can't run any processes, and virtually every command I try to run gives me the same warning.

Edward

**Comment by VentyCZ** [comment]
There are no processes running under PM2?
Just remove the dump file.

Or try running `pm2 save --force`.
