### ISSUE TITLE
pm2 status dosen't show process id?

### ISSUE THREAD

**Issue by gold-fisher** [Unitech/pm2#4617]
hello, I use "pm2 status" in command line on Ubuntu, but it dosen't show PID. I have tried restarting pm2, but it dosen't work. how to solve it?

**Comment by Unitech** [comment]
![image](https://user-images.githubusercontent.com/757747/75238759-d01baa00-57c1-11ea-9c2a-ca8ace3858ad.png)

The PID is correctly shown. Please reopen issue with screenshot

**Comment by gold-fisher** [comment]
![1582626651(1)](https://user-images.githubusercontent.com/24870097/75239219-4a1d5480-57fd-11ea-9136-a89cd4ecc415.jpg)
The PID isn't shown.

**Comment by gold-fisher** [comment]
I tried to use “pm2 list”, the PID is not shown.
