### ISSUE TITLE
UV_THREADPOOL_SIZE doesn't work properly on windows

### ISSUE THREAD

**Issue by fbsanches** [Unitech/pm2#4621]
Uv_threadpool_size is not working properly on my server.
before starting any asynchronous method, I set the variable

process.env.UV_THREADPOOL_SIZE = 32

but it works well for a few minutes and then goes back to default 4. 
Is there any way to define this value in pm2 outside the project?
I tried it this way:

set UV_THREADPOOL_SIZE = 34 & node index.js

but it runs directly on the node and does not use pm2.

If I define the ecosystem file in the ENV variable like this:

```
env: {
       "NODE_ENV": "production",
       "UV_THREADPOOL_SIZE": 32
     }
```

it also doesn't work.
It always appears undefined.

Every help is welcome?
My server is windows server 2016
node 11.14
pm2 4.2.3

**Comment by nicholas-ochoa** [comment]
I've found the only way to get this working under Windows is using cross-env or setting an actual environment variable in system properties. Setting it from within Node (which I assume is how PM2 is doing it) does not appear to work under Windows.

**Comment by fbsanches** [comment]
Thanks for the answer. I'm still in trouble. I don't know where the problem is. My connections line up and it is slow to include in the database. I've already updated drivers but I don't suspect that's the problem. Unless I do a test switching servers and putting linux. Do you recommend a good server distribution?
