### ISSUE TITLE
Possibility to customize which column to display in "pm2 list"

### ISSUE THREAD

**Issue by cacom-production** [Unitech/pm2#4631]
Hello,

It would be nice if we can choose which column we want to display in the pm2 list
It will leave more room to the chosen columns.
My 'namespace' are quite long, and the pm2 list doesn't display it totally, it's truncated

It would also be nice to add custom fields (issue #4335)

**Comment by szkrd** [comment]
The patch allows customizing the columns with env vars, for example:
```
PM2_LS_APP_HEAD="id:5,name,mode,↺"
```
The order is ignored, column size and column visibility may be customized though.

Could not find lint config or a way to run pm2 list related tests only, so I tried to replicate the existing style and to keep the change contained... Please let me know what else is needed :pray: Thank you!

**Comment by szkrd** [comment]
I've deleted my PR for lack of activity. Fortunately I'm not using pm2 at my current job.
