### ISSUE TITLE
every restart --inspect port increment

### ISSUE THREAD

**Issue by timofeyp** [Unitech/pm2#4636]
I pass `node_args: ["--inspect=127.0.0.1:9229"],` in ecosystem.config.js file, but every restart listen port number increments on 1. Previous port isn't busy, I checked by `lsof -i :portnumber`

`--- Daemon logs --------------------------------------------
/home/adminvks/.pm2/pm2.log last 20 lines:
PM2        | Debugger listening on ws://127.0.0.1:9238/1920d7f2-cad5-4463-a1d9-40ad45cd74fc
PM2        | For help, see: https://nodejs.org/en/docs/inspector
PM2        | 2020-03-13T18:31:55: PM2 log: App [schsrv:0] online
PM2        | 2020-03-13T18:34:04: PM2 log: App [schsrv:0] starting in -cluster mode-
PM2        | Debugger listening on ws://127.0.0.1:9239/6e4cbeb0-5db2-4a8e-810d-29a003485ac0
PM2        | For help, see: https://nodejs.org/en/docs/inspector
PM2        | 2020-03-13T18:34:04: PM2 log: App [schsrv:0] online
PM2        | 2020-03-13T18:34:06: PM2 log: -reload- New worker listening
PM2        | 2020-03-13T18:34:06: PM2 log: Stopping app:schsrv id:_old_0
PM2        | 2020-03-13T18:34:06: PM2 log: App name:schsrv id:_old_0 disconnected
PM2        | 2020-03-13T18:34:06: PM2 log: App [schsrv:_old_0] exited with code [0] via signal [SIGINT]
PM2        | 2020-03-13T18:34:06: PM2 log: pid=5908 msg=process killed
PM2        | 2020-03-13T18:36:46: PM2 log: Stopping app:schsrv id:0
PM2        | 2020-03-13T18:36:46: PM2 log: App name:schsrv id:0 disconnected
PM2        | 2020-03-13T18:36:46: PM2 log: App [schsrv:0] exited with code [0] via signal [SIGINT]
PM2        | 2020-03-13T18:36:46: PM2 log: pid=6099 msg=process killed
PM2        | 2020-03-13T18:37:30: PM2 log: App [schsrv:0] starting in -cluster mode-
PM2        | Debugger listening on ws://127.0.0.1:9240/b1a19a6c-045a-41e1-bc3b-e4e7141b0abe
PM2        | For help, see: https://nodejs.org/en/docs/inspector
PM2        | 2020-03-13T18:37:30: PM2 log: App [schsrv:0] online`

How to store port number 9229 on every restart ?

**Comment by aljaazm** [comment]
I assume that this is still not fixed? I'm experiencing the same issue
