### ISSUE TITLE
Cmd window pops up when there is a ".git" folder in the project root path

### ISSUE THREAD

**Issue by Aaron-Bird** [Unitech/pm2#4642]
## What's going wrong?

Some cmd.exe pops up when the root directory has the ".git" and starts with "pm2 start".
Can these popups be hidden?

## How could we reproduce this issue?

- windows 7
- node 13.11.0
- pm2 4.2.3

I created a demo:  
https://github.com/Aaron-Bird/pm2-demo  

Some cmd windows will pop up during startup.

```js
git clone git@github.com:Aaron-Bird/pm2-demo.git
cd pm2-demo
yarn 
pm2 start demo.js
```

![2](https://user-images.githubusercontent.com/25508292/77432437-05df9d00-6e19-11ea-8636-89c8f7da12ff.PNG)

----

But the cmd popup does not appear after deleting the ".git" folder.

```js
pm2 delete all
rd /s/q .git
pm2 start demo.js
```

**Comment by Aaron-Bird** [comment]
I found a temporary solution: downgrade to 3.0.3

**Comment by linonetwo** [comment]
Why 3.0.3 solve this?

it's 5.3.0 now
