### ISSUE TITLE
deploy failed with Not a git repository

### ISSUE THREAD

**Issue by hepatus** [Unitech/pm2#4643]
Hi,

I encounter a problem in the deployment of my project with pm2.
I have seen several issues on the subject but they are all closed and no solution is proposed in them.

I have successfully done this command 
`pm2 deploy ecosystem.config.js preproduction setup`

but when I try to deploy
`pm2 deploy ecosystem.config.js preproduction`

I have this error : 
```
Not a git repository
To compare two paths outside a working tree:
usage: git diff [--no-index] <path> <path>

  commit or stash your changes before deploying

Deploy failed
```

here is my ecosystem.config.js
```js
module.exports = {
  apps: [
    {
      "name": "swizi-chat",
      "script": "./src/index.js",
      "env-preproduction": {
       
      },
    },
  ],
  deploy: {
    preproduction: {
      "host": "x.x.x.x",
      "user": "node",
      "ref": "origin/master",
      "repo": "git@gitlab.com:myproject.git",
      "path": "/var/nodejs/my-project",
      "post-deploy":
        "npm install && pm2 reload ecosystem.config.js --env preproduction && pm2 save",
    },
  },
};

```
pm2 version is 4.2.3

Thx for your help

**Comment by rolivares** [comment]
same error here

**Comment by hepatus** [comment]
UP

nobody to help us ?

**Comment by hepatus** [comment]
the problem seems to be in the "check_for_local_changes" function in deploy script. I think the check is not done in the correct directory. 
@rolivares : The walkraround is to disable this check using --force option

**Comment by palbrecht1** [comment]
Ehhh... same issue ... any update?
