### ISSUE TITLE
PM2 Fails to install (Ubuntu 18.04)

### ISSUE THREAD

**Issue by danucalovj** [Unitech/pm2#4645]
Weird, this just started happening today on a new VM (Ubuntu 18.04), had been working all week other boxes I built for a project.

**System Versions:**

root@vagrant:/home/vagrant# node --version
v10.19.0
root@vagrant:/home/vagrant# npm --version
6.14.3

**Command to Install:**

npm i -g pm2

**Error:**

root@vagrant:/home/vagrant# npm i -g pm2
npm ERR! code EINTEGRITY
npm ERR! sha512-CvAbpIB7ObOuwvqhDBB/E4Z4ANRx2dBk08zYpGPNg+1fDj14FJg2e7DWA8bblSGNC8QarIXPaqPDJBL1e8cRQw== integrity checksum failed when using sha512: wanted sha512-CvAbpIB7ObOuwvqhDBB/E4Z4ANRx2dBk08zYpGPNg+1fDj14FJg2e7DWA8bblSGNC8QarIXPaqPDJBL1e8cRQw== but got sha512-DHUW87IjwcnPyxx69xLtTuDZzMY1OOnFnCD7CLQVaXpwLP68HQ9YU8ukWIcmsBrl1p717XNAwjCtDTpOU5CfQw==. (298923 bytes)
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has 
changed to use Promises in 1.x.)
npm ERR! Unexpected token  in JSON at position 35272 while parsing near '...:79602,"npm-signatL�݄c@�kqlKs�� PGP SI...'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-26T22_55_51_163Z-debug.log

**Debug Log Output:**

root@vagrant:/home/vagrant# cat /root/.npm/_logs/2020-03-26T22_55_51_163Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'i', '-g', 'pm2' ]
2 info using npm@6.14.3
3 info using node@v10.19.0
4 verbose npm-session aa9c5fd06bd8803d
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/pm2 163ms
8 http fetch GET 200 https://registry.npmjs.org/pm2/-/pm2-4.2.3.tgz 105ms
9 silly pacote tag manifest for pm2@latest fetched in 293ms
10 timing stage:loadCurrentTree Completed in 325ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
16 silly install loadAllDepsIntoIdealTree
17 silly resolveWithNewModule pm2@4.2.3 checking installable status
18 http fetch GET 200 https://registry.npmjs.org/async 140ms
19 http fetch GET 200 https://registry.npmjs.org/chokidar 145ms
20 silly fetchPackageMetaData error for chokidar@^3.2.0 Unexpected token  in JSON at position 35272 while parsing near '...:79602,"npm-signatL�
݄c@�kqlKs�� PGP SI...'
21 http fetch GET 200 https://registry.npmjs.org/commander 147ms
22 http fetch GET 200 https://registry.npmjs.org/blessed 148ms
23 http fetch GET 200 https://registry.npmjs.org/chalk 152ms
24 silly fetchPackageMetaData error for chalk@2.4.2 Unexpected token  in JSON at position 16391 while parsing near '...W80QPta1QZiJD|�� �� )
                                                                                                                                            ��
*���shasum":"d6...'
25 http fetch GET 200 https://registry.npmjs.org/cli-table-redemption 294ms
26 http fetch GET 200 https://registry.npmjs.org/@pm2%2fpm2-version-check 309ms
27 http fetch GET 200 https://registry.npmjs.org/async/-/async-3.2.0.tgz 181ms
28 http fetch GET 200 https://registry.npmjs.org/@pm2%2fjs-api 357ms
29 http fetch GET 200 https://registry.npmjs.org/@pm2%2fagent 365ms
30 http fetch GET 200 https://registry.npmjs.org/blessed/-/blessed-0.1.81.tgz 190ms
31 http fetch GET 200 https://registry.npmjs.org/commander/-/commander-2.15.1.tgz 190ms
32 http fetch GET 200 https://registry.npmjs.org/cron 204ms
33 http fetch GET 200 https://registry.npmjs.org/date-fns 197ms
34 http fetch GET 200 https://registry.npmjs.org/@pm2%2fio 375ms
35 silly pacote range manifest for async@^3.1.0 fetched in 395ms
36 silly resolveWithNewModule async@3.2.0 checking installable status
37 silly pacote version manifest for blessed@0.1.81 fetched in 397ms
38 http fetch GET 200 https://registry.npmjs.org/cli-table-redemption/-/cli-table-redemption-1.0.1.tgz 88ms
39 silly resolveWithNewModule blessed@0.1.81 checking installable status
40 silly pacote version manifest for commander@2.15.1 fetched in 398ms
41 silly resolveWithNewModule commander@2.15.1 checking installable status
42 verbose stack Error: sha512-CvAbpIB7ObOuwvqhDBB/E4Z4ANRx2dBk08zYpGPNg+1fDj14FJg2e7DWA8bblSGNC8QarIXPaqPDJBL1e8cRQw== integrity checksum failed when using sha512: wanted sha512-CvAbpIB7ObOuwvqhDBB/E4Z4ANRx2dBk08zYpGPNg+1fDj14FJg2e7DWA8bblSGNC8QarIXPaqPDJBL1e8cRQw== but got sha512-DHUW87IjwcnPyxx69xLtTuDZzMY1OOnFnCD7CLQVaXpwLP68HQ9YU8ukWIcmsBrl1p717XNAwjCtDTpOU5CfQw==. (298923 bytes)
42 verbose stack     at Transform.on (/usr/lib/node_modules/npm/node_modules/ssri/index.js:328:19)
42 verbose stack     at Transform.emit (events.js:203:15)
42 verbose stack     at endReadableNT (_stream_readable.js:1145:12)
42 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
43 verbose cwd /home/vagrant
44 verbose Linux 4.15.0-58-generic
45 verbose argv "/usr/bin/node" "/usr/bin/npm" "i" "-g" "pm2"
46 verbose node v10.19.0
47 verbose npm  v6.14.3
48 error code EINTEGRITY
49 error sha512-CvAbpIB7ObOuwvqhDBB/E4Z4ANRx2dBk08zYpGPNg+1fDj14FJg2e7DWA8bblSGNC8QarIXPaqPDJBL1e8cRQw== integrity checksum failed when using sha512: wanted sha512-CvAbpIB7ObOuwvqhDBB/E4Z4ANRx2dBk08zYpGPNg+1fDj14FJg2e7DWA8bblSGNC8QarIXPaqPDJBL1e8cRQw== but got sha512-DHUW87IjwcnPyxx69xLtTuDZzMY1OOnFnCD7CLQVaXpwLP68HQ9YU8ukWIcmsBrl1p717XNAwjCtDTpOU5CfQw==. (298923 bytes)
50 verbose exit [ 1, true ]

**Comment by wsz7777** [comment]
debian 10.2

npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm ERR! code 1
npm ERR! path /data/00/server/node_modules/utf-8-validate
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! make: Entering directory '/data/00/server/node_modules/utf-8-validate/build'
npm ERR!   CC(target) Release/obj.target/validation/src/validation.o
npm ERR! make: Leaving directory '/data/00/server/node_modules/utf-8-validate/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.16.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/root/.nvs/node/14.16.0/x64/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/data/00/server/node_modules/utf-8-validate/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.nvs/node/14.16.0/x64/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/14.16.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/14.16.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/root/.nvs/node/14.16.0/x64/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/14.16.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/data/00/server/node_modules/utf-8-validate',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! ../src/validation.c:2:10: fatal error: assert.h: No such file or directory
npm ERR!  #include <assert.h>
npm ERR!           ^~~~~~~~~~
npm ERR! compilation terminated.
npm ERR! make: *** [validation.target.mk:111: Release/obj.target/validation/src/validation.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/root/.nvs/node/14.16.0/x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! gyp ERR! System Linux 4.19.0-11-amd64
npm ERR! gyp ERR! command "/root/.nvs/node/14.16.0/x64/bin/node" "/root/.nvs/node/14.16.0/x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /data/00/server/node_modules/utf-8-validate
npm ERR! gyp ERR! node -v v14.16.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-30T03_20_17_196Z-debug.log

**Comment by wsz7777** [comment]
wget -qO- https://getpm2.com/install.sh | bash

it's work, but I con't find pm2 dir
