### ISSUE TITLE
pm2 WatchDog 

### ISSUE THREAD

**Issue by Unitech** [Unitech/pm2#466]
Add a second process that interacts with pm2 to see if he's still alive and if not to bring it alive.
pm2 will also check if the watchdog is still alive.
- At starts pm2 launch the watchgod
- The watchdog ping pm2 and get the process list runned by pm2 every 5 seconds
- pm2 ping the watchdog to see if he's still alive, if not bring it back online
- if the watchdog don't manage to ping pm2, bring it alive and resurrect the processes previously dumped

**Comment by cbratschi** [comment]
Is this watchdog documented somewhere? I am currently using the systemd watchdog on Raspbian and would like to use a similar feature in pm2 from Node.js and native code. If the Node process hangs it should first be restarted and in worst case the device should reboot.

**Comment by ma-zal** [comment]
Hello.
I wrote [pm2-watchdog](https://github.com/ma-zal/pm2-watchdog) module, that checks webserver http responses.  

Maybe it can help you, or you can fork it and improve it to your purposes. :-)
