### ISSUE TITLE
PM2 Process delete automatically on exit from terminal

### ISSUE THREAD

**Issue by vrakesh1** [Unitech/pm2#4669]
## What's going wrong?
I start build using following command in terminal on mac
pm2 start local.js --name rakapr15
when i logout from server or close terminal then this process remove automatically and build stop running.

## Supporting information
pm2 version is 4.2.1

```
$ pm2 report
```

--- Daemon logs --------------------------------------------
/home/chenhon5/.pm2/pm2.log last 20 lines:
PM2        | 2020-04-15T10:16:33: PM2 log: ===============================================================================
PM2        | 2020-04-15T10:16:33: PM2 log: --- New PM2 Daemon started ----------------------------------------------------
PM2        | 2020-04-15T10:16:33: PM2 log: Time                 : Wed Apr 15 2020 10:16:33 GMT-0700 (Pacific Daylight Time)
PM2        | 2020-04-15T10:16:33: PM2 log: PM2 version          : 4.2.1
PM2        | 2020-04-15T10:16:33: PM2 log: Node.js version      : 10.19.0
PM2        | 2020-04-15T10:16:33: PM2 log: Current arch         : x64
PM2        | 2020-04-15T10:16:33: PM2 log: PM2 home             : /home/chenhon5/.pm2
PM2        | 2020-04-15T10:16:33: PM2 log: PM2 PID file         : /home/chenhon5/.pm2/pm2.pid
PM2        | 2020-04-15T10:16:33: PM2 log: RPC socket file      : /home/chenhon5/.pm2/rpc.sock
PM2        | 2020-04-15T10:16:33: PM2 log: BUS socket file      : /home/chenhon5/.pm2/pub.sock
PM2        | 2020-04-15T10:16:33: PM2 log: Application log path : /home/chenhon5/.pm2/logs
PM2        | 2020-04-15T10:16:33: PM2 log: Worker Interval      : 30000
PM2        | 2020-04-15T10:16:33: PM2 log: Process dump file    : /home/chenhon5/.pm2/dump.pm2
PM2        | 2020-04-15T10:16:33: PM2 log: Concurrent actions   : 2
PM2        | 2020-04-15T10:16:33: PM2 log: SIGTERM timeout      : 1600
PM2        | 2020-04-15T10:16:33: PM2 log: ===============================================================================
PM2        | 2020-04-15T10:16:37: PM2 log: App [pm2-server-monit:0] starting in -fork mode-
PM2        | 2020-04-15T10:16:37: PM2 log: App [pm2-server-monit:0] online
PM2        | 2020-04-15T10:16:37: PM2 log: App [rakapr15:1] starting in -fork mode-
PM2        | 2020-04-15T10:16:37: PM2 log: App [rakapr15:1] online

**Comment by vrakesh1** [comment]
can anybody help please

**Comment by douglasoliveiraadv** [comment]
The same is happening to me

**Comment by Unitech** [comment]
I barely can see how is that possible.
Please run `pgrep PM2` to check if PM2 is running in background

**Comment by douglasoliveiraadv** [comment]
In my case, using WHMCpanel, it worked after I put the account in Normal Sheel mode and then went back to Jailed Shell. After this procedure, PM2 returned to normal operation.

**Comment by Zonalds** [comment]
I had same issue. Apparently the support can't  hasn't be helpful. You might want to use the good old 'screen' while you try to find a solution.

**Comment by ssoftwares** [comment]
> on. Thank you!

Bro you saved my day. Thank you so much sir.
