### ISSUE TITLE
lodash security alert due to older vizion version

### ISSUE THREAD

**Issue by tapsboy** [Unitech/pm2#4670]
## What's going wrong?
Installing pm2 as a dependency, the generated package-lock create dependency of insecure version 4.17.10

## How could we reproduce this issue?
`npm install --save pm2`
search for 4.17.10 against lodash

## Supporting information

    "vizion": {
      "version": "2.0.2",
      "resolved": "https://registry.npmjs.org/vizion/-/vizion-2.0.2.tgz",
      "integrity": "sha512-UGDB/UdC1iyPkwyQaI9AFMwKcluQyD4FleEXObrlu254MEf16MV8l+AZdpFErY/iVKZVWlQ+OgJlVVJIdeMUYg==",
      "requires": {
        "async": "2.6.1",
        "git-node-fs": "^1.0.0",
        "ini": "^1.3.4",
        "js-git": "^0.7.8",
        "lodash.findindex": "^4.6.0",
        "lodash.foreach": "^4.5.0",
        "lodash.get": "^4.4.2",
        "lodash.last": "^3.0.0"
      },
      "dependencies": {
        "async": {
          "version": "2.6.1",
          "resolved": "https://registry.npmjs.org/async/-/async-2.6.1.tgz",
          "integrity": "sha512-fNEiL2+AZt6AlAw/29Cr0UDe4sRAHCpEHh54WMz+Bb7QfNcFw4h3loofyJpLeQs4Yx7yuqu/2dLgM5hKOs6HlQ==",
          "requires": {
            "lodash": "^4.17.10"
          }
        }
      }
    },
==========

Upgrading vizion dependency to 2.2.0 should solve the issue

**Comment by alexlemaire** [comment]
Bouncing on this issue because there seem to be another vulnerability with `vizion` for versions below `2.1.0`

See [here](https://snyk.io/vuln/SNYK-JS-VIZION-565230)

**Comment by Unitech** [comment]
PM2 4.3.0 published:

```bash
npm install pm2@latest -g
pm2 update
```

**Comment by soundstep** [comment]
@Unitech can I see how you fixed the vulnerability? Any commit I can look at please?
