### ISSUE TITLE
PM2 global error caught

### ISSUE THREAD

**Issue by tracycollins** [Unitech/pm2#4676]
## What's going wrong?

version 4.3.0 of pm2 fails instantly and repeatedly (and keeps rebooting) with error:

> 2020-04-20T02:50:05: PM2 error: Cannot use 'in' operator to search for 'hash' in undefined
> 2020-04-20T02:50:05: PM2 error: TypeError: Cannot use 'in' operator to search for 'hash' in undefined
>     at Object.get (/home/tc/.nvm/versions/node/v12.16.2/lib/node_modules/pm2/node_modules/vizion/lib/helper.js:1
> 

running on debian 10-buster
npm 6.14.4
node v12.16.2

version pm2@4.2.3 works

## How could we reproduce this issue?

npm i -g pm2@latest
check pm2.log

## Supporting information

> 2020-04-20T02:50:04: PM2 log: ===============================================================================
> 2020-04-20T02:50:04: PM2 error: [PM2] Resurrecting PM2
> 2020-04-20T02:50:05: PM2 log: PM2 successfully stopped
> 2020-04-20T02:50:05: PM2 log: ===============================================================================
> 2020-04-20T02:50:05: PM2 log: --- New PM2 Daemon started ----------------------------------------------------
> 2020-04-20T02:50:05: PM2 log: Time                 : Mon Apr 20 2020 02:50:05 GMT+0000 (Coordinated Universal Time)
> 2020-04-20T02:50:05: PM2 log: PM2 version          : 4.3.0
> 2020-04-20T02:50:05: PM2 log: Node.js version      : 12.16.2
> 2020-04-20T02:50:05: PM2 log: Current arch         : x64
> 2020-04-20T02:50:05: PM2 log: PM2 home             : /home/tc/.pm2
> 2020-04-20T02:50:05: PM2 log: PM2 PID file         : /home/tc/.pm2/pm2.pid
> 2020-04-20T02:50:05: PM2 log: RPC socket file      : /home/tc/.pm2/rpc.sock
> 2020-04-20T02:50:05: PM2 log: BUS socket file      : /home/tc/.pm2/pub.sock
> 2020-04-20T02:50:05: PM2 log: Application log path : /home/tc/.pm2/logs
> 2020-04-20T02:50:05: PM2 log: Worker Interval      : 30000
> 2020-04-20T02:50:05: PM2 log: Process dump file    : /home/tc/.pm2/dump.pm2
> 2020-04-20T02:50:05: PM2 log: Concurrent actions   : 2
> 2020-04-20T02:50:05: PM2 log: SIGTERM timeout      : 1600
> 2020-04-20T02:50:05: PM2 log: ===============================================================================
> 2020-04-20T02:50:05: PM2 log: App [pm2-logrotate:0] starting in -fork mode-
> 2020-04-20T02:50:05: PM2 log: App [pm2-logrotate:0] online
> 2020-04-20T02:50:05: PM2 log: ===============================================================================
> 2020-04-20T02:50:05: PM2 log: --- PM2 global error caught ---------------------------------------------------
> 2020-04-20T02:50:05: PM2 log: Time                 : Mon Apr 20 2020 02:50:05 GMT+0000 (Coordinated Universal Time)
> 2020-04-20T02:50:05: PM2 error: Cannot use 'in' operator to search for 'hash' in undefined
> 2020-04-20T02:50:05: PM2 error: TypeError: Cannot use 'in' operator to search for 'hash' in undefined
>     at Object.get (/home/tc/.nvm/versions/node/v12.16.2/lib/node_modules/pm2/node_modules/vizion/lib/helper.js:10:18)
>     at /home/tc/.nvm/versions/node/v12.16.2/lib/node_modules/pm2/node_modules/vizion/lib/git/git.js:47:28
>     at /home/tc/.nvm/versions/node/v12.16.2/lib/node_modules/pm2/node_modules/vizion/lib/git/js-git-service.js:51:14
>     at /home/tc/.nvm/versions/node/v12.16.2/lib/node_modules/pm2/node_modules/js-git/mixins/fs-db.js:77:40
>     at ReadFileContext.callback (/home/tc/.nvm/versions/node/v12.16.2/lib/node_modules/pm2/node_modules/git-node-fs/lib/node-fs.js:20:41)
>     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:257:13)
> 2020-04-20T02:50:05: PM2 log: ===============================================================================
> 2020-04-20T02:50:05: PM2 error: [PM2] Resurrecting PM2

```
$ pm2 report
```

**Comment by Unitech** [comment]
thanks for reporting, vizion downgraded and new pm2 published on 4.3.1 while I'm inspecting this

**Comment by Unitech** [comment]
fix via https://github.com/keymetrics/vizion/commit/4d587b439e27b9ff06a5989db0e80099916b78fd
