### ISSUE TITLE
File Deletion Causes Impossible Restart Attempts

### ISSUE THREAD

**Issue by Lonniebiz** [Unitech/pm2#4682]
**PM2:**  4.3.1
**Node:** 14.0.0
**OS:** Ubuntu Server 18.04

Previously, in PM2 version 4.2.3, if you deleted a service's script file, while the service was running via PM2, it would not cause the service to halt.

Now, in PM2 version 4.3.1, it seems this default behavior has changed; deleting the file causes PM2 to restart the script that isn't there. It seems that PM2 generally assumes that any type of file system change should invoke restart. However, **file deletion** is a type of file system change that should be omitted from invoking restart. You cannot restart something that isn't there.

**Note:**  The script file I'm speaking of was started like this:
`pm2 start service.js`

Notice, that I have not specified `--watch`, as I'm currently reading about [here](https://pm2.keymetrics.io/docs/usage/watch-and-restart/). Therefore, the only time I would expect PM2 to attempt restarting would be when the script crashes. To me, it seems like `--watch` is happening even when you don't input that argument. I need `--nowatch`! This is breaking default behavior of `start`.

Perhaps the simplest way to address this, would be to check for the existence of the file before invoking a script restart.

I have no problem with this auto-restart behavior for when I return the file to that location; that will actually be handy. However, PM2 shouldn't assume that any file system change is an overwrite.

I have very specific reasons for removing the file instead of overwriting it and I'd like the running service to remain running until I replace the file I've deleted.

**Comment by Lonniebiz** [comment]
As a workaround, I've downgraded to version 4.2.3.

**Comment by Lonniebiz** [comment]
I don't like this feature auto-closing issues due to them being stale for such a short period of time:
![stale](https://user-images.githubusercontent.com/151919/82763376-cc9dbc00-9dcc-11ea-9fc9-93648d20ca6e.png)

**Comment by Lonniebiz** [comment]
PM2 keeps telling me to upgrade to 4.4.0:
```
PM2       | [PM2] This PM2 is not UP TO DATE
PM2       | [PM2] Upgrade to version 4.4.0
```
However, I cannot upgrade to 4.4.0 because of this regression bug I've noticed since 4.31. So far, no one has even addressed my issue with a comment. Please advise.

**Comment by Lonniebiz** [comment]
Can anyone please address this issue? It has been two months with no reply.

**Comment by Lonniebiz** [comment]
In the past, PM2 has always allowed me to achieve the configuration I wanted. Since I've receive no feedback in two months, for this issue, starting today I'm looking into [alternatives](https://expressjs.com/en/advanced/pm.html).

**Comment by Lonniebiz** [comment]
For an example of what I'm talking about. Systemd allows you to check if the path exist, before starting the service with [ConditionPathExists](https://www.youtube.com/watch?v=gbR6KjDc0ds&t=7m56s).

**Comment by Unitech** [comment]
I did not know about this "Systemd allows you to check if the path exist, before starting the service with ConditionPathExists." 
I will make this issue as feature request
