### ISSUE TITLE
args stored as string

### ISSUE THREAD

**Issue by 7c** [Unitech/pm2#4690]
node_version: '10.20.1',
pm2 version 4.4.0,
ubuntu 16 LTS 64bit English,
PM2_HOME: '/root/.pm2'

since recent installation i am getting:

```
undefined:1
--group,vpn2_hostserver
 ^

SyntaxError: Unexpected number in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.module.exports [as describe] (/usr/lib/node_modules/pm2/lib/API/UX/pm2-describe.js:59:86)
    at /usr/lib/node_modules/pm2/lib/API.js:1889:14
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/pm2/lib/API.js:1888:20
    at /usr/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at Parser.emit (events.js:198:13)
    at Parser._write (/usr/lib/node_modules/pm2/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:415:12)
```

when i type 'pm2 describe <name>'. Our scripts do this to start our software:

```
pm2 describe rconfig-peer || { pkill -f rconfig-peer; pm2 start /opt/rconfig-peer/rconfig-peer.js -- --group vpn2_hostserver && pm2 save; }
```

I have put some debug line into `/usr/lib/node_modules/pm2/lib/API/UX/pm2-describe.js` file and have seen pm2_env.args is a string: 

```
...
     args: '--group,vpn2_hostserver'
...
```

while in old versions (3.5.1 and 4.1.x) it is an object:
```
[ '--group', 'vpn2_hostserver' ]
```

i have no clue why and how the arguments passed with start were stored as string . Same behaviour has happened on 200 of our cloud servers with 4.4.0 - we have downgraded all to 4.2.1 - all is well now

**Comment by cheneyweb** [comment]
I have met that problem too

**Comment by 7c** [comment]
same issue happens at 4.3.0 too... i have downgraded everything to 4.2.1 - then it was quite. Also this version suddenly has starting the app again without counting as already running, so the app was running twice.
