### ISSUE TITLE
PM2 not working from PHP Exec()

### ISSUE THREAD

**Issue by Karrade** [Unitech/pm2#4691]
#What's going wrong?
The following code is being displayed and the file is not running
`Array ( [0] => [1] => ------------- [2] => [3] => __/\\\\\\\\\\\\\____/\\\\____________/\\\\____/\\\\\\\\\_____ [4] => _\/\\\/////////\\\_\/\\\\\\________/\\\\\\__/\\\///////\\\___ [5] => _\/\\\_______\/\\\_\/\\\//\\\____/\\\//\\\_\///______\//\\\__ [6] => _\/\\\\\\\\\\\\\/__\/\\\\///\\\/\\\/_\/\\\___________/\\\/___ [7] => _\/\\\/////////____\/\\\__\///\\\/___\/\\\________/\\\//_____ [8] => _\/\\\_____________\/\\\____\///_____\/\\\_____/\\\//________ [9] => _\/\\\_____________\/\\\_____________\/\\\___/\\\/___________ [10] => _\/\\\_____________\/\\\_____________\/\\\__/\\\\\\\\\\\\\\\_ [11] => _\///______________\///______________\///__\///////////////__ [12] => [13] => [14] => Runtime Edition [15] => [16] => PM2 is a Production Process Manager for Node.js applications [17] => with a built-in Load Balancer. [18] => [19] => Start and Daemonize any application: [20] => $ pm2 start app.js [21] => [22] => Load Balance 4 instances of api.js: [23] => $ pm2 start api.js -i 4 [24] => [25] => Monitor in production: [26] => $ pm2 monitor [27] => [28] => Make pm2 auto-boot at server restart: [29] => $ pm2 startup [30] => [31] => To go further checkout: [32] => http://pm2.io/ [33] => [34] => [35] => ------------- [36] => )`
## How could we reproduce this issue?
this is the php code i am using. i can execute other things fine. just not pm2
`chdir('/root/bots/myBot/');
	echo getcwd() . "\n";
	exec("pm2 start myBot.js --watch", $output);`

```

**Comment by ihabhamad** [comment]
@Karrade  after googling it and test 
use this 
HOME=/home/user/ pm2 status
that's work with me shell_exec()
