### ISSUE TITLE
Possible to run two instances of different versions of pm2 on two Node versions with nvm?

### ISSUE THREAD

**Issue by cyqsimon** [Unitech/pm2#4692]
`app 0` only works on `pm2@3.1.3` or less, which needs `Node v13` or less because this version of `pm2` breaks on `Node v14`.

`app 1` prefers newest version of `pm2`, ideally running on `Node v14`.

I know that with `nvm`, the global packages of different versions of `Node` are separate, so it is possible to install one version of `pm2` for each `Node` version. But it seems like the `pm2` instances will try to use the same data directory (`~/.pm2`), which I suspect will likely cause some conflict. Also maybe their startup entries in `systemctl` will conflict as well. Anyway, there is no clear documentation regarding this that I can find online.

So is it possible to run two instances of different versions of `pm2` without putting them in containers? If yes, can someone please provide some procedures? Thanks.

Environment:
- `CentOS 7` `kernel 5.6.10`
- `nvm` w/ `Node v13.14.0` & `Node v14.2.0`

**Comment by Unitech** [comment]
You can run multiple version of PM2 by overriding the env variable `PM2_HOME`

`PM2_HOME=/tmp/pm2 pm2 start app.js`
`PM2_HOME=/tmp/pm2 pm2 ls`
