### ISSUE TITLE
pm2 flush "app name with space" doesnt work

### ISSUE THREAD

**Issue by edreal** [Unitech/pm2#4696]
When I try flushing app name which has spaces like: `pm2 flush "hello world"` it shows the file paths correctly and says that they were flushed but actually nothing happened. After that `pm2 logs` will still show the old logs.

PM2 version: 4.4.0
Node version: 13.9
Operating System: Debian 9

**Comment by komorebi-san** [comment]
@edreal How did u manage to resolve it 
Same here.

PM2 version: 4.4.0
Node version: 8.1.0
Operating System: Ubuntu 18.04

**Comment by edreal** [comment]
@komorebi-san as workaround I just used hyphen instead of using space.
