### ISSUE TITLE
laravel echo server pm2 cluster mode not working 

### ISSUE THREAD

**Issue by mohamadchoker** [Unitech/pm2#4702]
Hello, 
I'm running the echo server using cluster mode and stress testing the server with a script that subscribes 10k users to the socket. It ends up with 7984 users connected to the socket and the odd thing that I'm monitoring pm2 and I can see that 1 node is working (increased CPU, memory) while other nodes' values do not change.

this my pm2 conf.json file:

`module.exports = {
  apps : [{
    name       : "echo",
    script     : "server.js",
    args: "start",
    instances  : "4",
    exec_mode  : "cluster"
  }],

};`

![Screenshot from 2020-05-12 15-41-18](https://user-images.githubusercontent.com/11899428/81693156-2d8dd180-9468-11ea-87d9-f506656fc036.png)

**Comment by dpanic** [comment]
I think args are not working in cluster mode
