### ISSUE TITLE
docs: update-env missing documentation

### ISSUE THREAD

**Issue by AoDev** [Unitech/pm2#4705]
I've been looking for a way to update the _ecosystem config_ and make pm2 reflect those changes. It "seems" that the `update-env option` is what we are supposed to use. But it is barely documented.

Could you please extend the docs about it?

So far I haven't managed to use it properly to update a single service config.
I found [this SO question](https://stackoverflow.com/questions/44508316/reload-pm2-configuration-file) but the solution there reloads all services. I have tried to specify the app but this does not seem to work. What is the proper command to reload / restart a single app with the updated config.

For example, in my case, I have switched an app from _cluster 2 instances_ to _a single fork instance_.

**Comment by AoDev** [comment]
ping

**Comment by evenfrost** [comment]
Same here. Issues about `--update-env` not being picked up are all pretty dated, wondering whether it will work for deployment with `pm2 deploy` or/and for `pm2 reload all`. I need zero downtime on my server, so stopping and then starting again the nodes is not an option.

**Comment by AoDev** [comment]
Another issue closed without answer...

**Comment by staznz** [comment]
I haven't had any luck with `--update-env` either. It just doesn't pick up the updated config!
