### ISSUE TITLE
[Question] PM2 with Deno script

### ISSUE THREAD

**Issue by aralroca** [Unitech/pm2#4710]
Is it possible to run a Deno script directly with PM2?

I did a workaround creating a bash file:

```bh
#!/bin/bash
deno run -A myCode.ts
```

And

```
➜ pm2 start ./app.sh 
```

But I'm not sure if it is recommended to do this... I tried with `--interpreter` flag but I didn't get it...

Thank you a lot 👏

**Comment by aralroca** [comment]
Stale bot, I'm waiting for a answer 🙌

**Comment by jlopezxs** [comment]
You can use interpreter option:

```sh
pm2 start index.ts --interpreter="deno" --interpreter-args="run --allow-net" 
```

**Comment by aralroca** [comment]
Thank you so much for your answer @jlopezxs
