### ISSUE TITLE
pm2 problem with starting python multiprocess on windows

### ISSUE THREAD

**Issue by potoo0** [Unitech/pm2#4711]
There are two problems with starting python multiprocess  on windows(shown in figure 1):
1. for each child process will start a terminal;
2. `pm2 log [nodeName]` only logging `__main__`, cannot receive child process.

![image](https://user-images.githubusercontent.com/34411681/82143460-bb0d5f00-9876-11ea-82a9-85826d7b0bf9.png)
(*figure 1*)

Here is my test script:
```python
# test.py
import multiprocessing as mp
import time
from loguru import logger
import sys


def put1(q):
    logger.info('Process: put put put')
    cnt = 0
    while True:
        cnt += 1
        q.put(cnt)
        logger.info(f'put1: {cnt}')

        time.sleep(0.5)

        if q.qsize() > 10:
            q.get()
    

def get1(q):
    logger.info('Process: get11111')
    while True:
        cnt = q.get()
        logger.info(f'get11111: {cnt}')

        time.sleep(0.3)


if __name__ == '__main__':
    logger.add(sys.stdout)
    logger.info(".....start.....")

    q = mp.Queue()
    proceesses = []

    proceesses.append(
        mp.Process(target=put1, args=(q,))
    )
    proceesses.append(
        mp.Process(target=get1, args=(q,))
    )

    for p in proceesses:
        p.start()
```

**Comment by zxj17815** [comment]
I have the same problem,I deploy web application on windows by uvicirn.
There are other cases, when I use a virtual environment, an interpreter terminal will also pop up
