### ISSUE TITLE
environment variables not loaded using dotenv when pm2 cluster mode

### ISSUE THREAD

**Issue by adriano-di-giovanni** [Unitech/pm2#4718]
Environment variables aren't loaded when the app is started in cluster mode using pm2 and the .env file is located elsewhere.

The `DOTENV_CONFIG_DEBUG` and `DOTENV_CONFIG_PATH` variables are correctly loaded into each worker's `process.env`.

Everything works fine in cluster mode when the .env file lives in its canonical location.

```javascript
module.exports = {
  apps: [
    {
      // relevant attributes only
      exec_mode: 'cluster',
      node_args: '--require dotenv/config',
      script: './index.js',
      env: {
        NODE_ENV: 'development',
      },
      env_development: {
        DOTENV_CONFIG_DEBUG: true,
        DOTENV_CONFIG_PATH: '/path/to/.env',
      }
    }
  ],
  deploy: {
    development: {
      // relevant attributes only
      'post-deploy': 'npm install && pm2 startOrRestart ecosystem.config.js --env development,
    },
  }
}
```

pm2 4.4.0
dotenv 8.2.0

**Comment by wujingquan** [comment]
We have the same problem.

**Comment by mfmsajidh** [comment]
This issue is still present in the current version. Cannot load dotenv in cluster mode

**Comment by TheReidZhang** [comment]
This issue is still present. Please reopen the issue. @Unitech

**Comment by novecento** [comment]
May we reopen ?

**Comment by itsTeknas** [comment]
+reopen

**Comment by johnfox** [comment]
+reopen just spent 2 hours trying to debug this. The only functional option is to have `.env` file in the root of the dir. this is messing my setup :D
