### ISSUE TITLE
What exactly is HTTP P95 Latency monitoring?

### ISSUE THREAD

**Issue by gferrand** [Unitech/pm2#4721]
Could anyone point me to where I can read more about what HTTP P95 Latency means? The number we see on our dashboard is quite different than HTTP Latency.

Thanks!

**Comment by EdmondAmaning** [comment]
It measures latency from the 95 percentile of virtual users. Example:
For the 95 percentile of requests the latency was 3ms

**Comment by Allan-Nava** [comment]
> It measures latency from the 95 percentile of virtual users. Example: For the 95 percentile of requests the latency was 3ms

Is it correct?
