### ISSUE TITLE
pm2-runtime: env spawn E2BIG

### ISSUE THREAD

**Issue by dmpvost** [Unitech/pm2#4725]
## What's going wrong?

When I start my app with pm2-runtime in gitlab CI.
The current env is inherint from gitlab env.

And it appear that it's too big. `PM2 error: Trace: Error: spawn E2BIG`
The command filter_env is not available for pm2-runtime

```
2020-05-27T15:49:39: PM2 error: Trace: Error: spawn E2BIG
     at ChildProcess.spawn (internal/child_process.js:407:11)
     at spawn (child_process.js:548:9)
     at fork (child_process.js:116:10)
     at createWorkerProcess (internal/cluster/master.js:134:10)
     at EventEmitter.cluster.fork (internal/cluster/master.js:169:25)
     at Object.nodeApp (/usr/local/lib/node_modules/pm2/lib/God/ClusterMode.js:48:21)
     at Object.executeApp (/usr/local/lib/node_modules/pm2/lib/God.js:245:9)
     at inject (/usr/local/lib/node_modules/pm2/lib/God.js:159:18)
     at Object.injectVariables (/usr/local/lib/node_modules/pm2/lib/God.js:586:10)
     at /usr/local/lib/node_modules/pm2/lib/God.js:157:9 {
   errno: 'E2BIG',
   code: 'E2BIG',
   syscall: 'spawn'
 }
```

## How could we reproduce this issue?

Try to start pm2-runtime under GitlabCI

## Supporting information

```
$ pm2 report
```
https://github.com/keymetrics/docker-pm2/issues/81

**Comment by himanshurobo** [comment]
Sharing error logs : -

PM2        |     at EventEmitter.cluster.fork (internal/cluster/master.js:169:25)
PM2        |     at Object.nodeApp (/usr/lib/node_modules/pm2/lib/God/ClusterMode.js:48:21)
PM2        |     at Object.executeApp (/usr/lib/node_modules/pm2/lib/God.js:245:9)
PM2        |     at inject (/usr/lib/node_modules/pm2/lib/God.js:159:18)
PM2        |     at Object.injectVariables (/usr/lib/node_modules/pm2/lib/God.js:586:10)
PM2        |     at /usr/lib/node_modules/pm2/lib/God.js:157:9 {
PM2        |   errno: 'E2BIG',
PM2        |   code: 'E2BIG',
PM2        |   syscall: 'spawn'
PM2        | }
PM2        |     at Object.God.logAndGenerateError (/usr/lib/node_modules/pm2/lib/God/Methods.js:34:15)
PM2        |     at Object.nodeApp (/usr/lib/node_modules/pm2/lib/God/ClusterMode.js:50:11)
PM2        |     at Object.executeApp (/usr/lib/node_modules/pm2/lib/God.js:245:9)
PM2        |     at inject (/usr/lib/node_modules/pm2/lib/God.js:159:18)
PM2        |     at Object.injectVariables (/usr/lib/node_modules/pm2/lib/God.js:586:10)
PM2        |     at /usr/lib/node_modules/pm2/lib/God.js:157:9
PM2        |     at /usr/lib/node_modules/pm2/node_modules/async/internal/map.js:22:9
PM2        |     at replenish (/usr/lib/node_modules/pm2/node_modules/async/internal/eachOfLimit.js:81:17)
PM2        |     at /usr/lib/node_modules/pm2/node_modules/async/internal/eachOfLimit.js:86:9
PM2        |     at _asyncMap (/usr/lib/node_modules/pm2/node_modules/async/internal/map.js:20:12)

**Comment by dmpvost** [comment]
I find a twix,  rewrite the variable env only with my usage.

The problem is that gitlab have too much argument in args. 

I have reset all variable env just for this command with `env -i`
and add just the strict minimum arguments

`env -i PWD="/app" HOME="/root" NODE_VERSION="12.13.0" pm2-runtime`

Work fine

**Comment by chemsseddine** [comment]
@dmpvost pm2-runtime will not be available if you are doing env -i , how are you managing this ?

**Comment by chemsseddine** [comment]
great thanks a lot @dmpvost  , I think that PATH env var is important
