### ISSUE TITLE
pm2 crashes with type: module and --experimental-modules

### ISSUE THREAD

**Issue by NebSehemvi** [Unitech/pm2#4727]
##  What's going wrong?

I can't start process with pm2 with `"type": "module"` in my package.json and the following pm2 config file:
```
export default {
  apps: [
    {
      name: 'app',
      script: 'src/app.js',
      node_args: '--experimental-modules',
    },
  ],
};
```

The error I've got:
```
 pm2 start pm2.config.js

(node:21648) Warning: require() of ES modules is not supported.
require() of D:\Codework\BITBUCKET\backend\pm2.config.js from D:\Codework\BITBUCKET\backend\node_modules\pm2\lib\Common.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename pm2.config.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from D:\Codework\BITBUCKET\backend\package.json.
[PM2][ERROR] File pm2.config.js malformated
D:\Codework\BITBUCKET\backend\pm2.config.js:1
export default {
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:983:16)
    at Module._compile (internal/modules/cjs/loader.js:1033:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.Common.parseConfig (D:\Codework\BITBUCKET\backend\node_modules\pm2\lib\Common.js:320:12)
    at API._startJson (D:\Codework\BITBUCKET\backend\node_modules\pm2\lib\API.js:957:25)
    at API.start (D:\Codework\BITBUCKET\backend\node_modules\pm2\lib\API.js:333:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @0.1.1 start: `pm2 start pm2.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @0.1.1 start script.
```

Is it possible to run pm2 with such settings? 

## How could we reproduce this issue?

1) Set type 'module' in package.json
2) Set --experimental-modules in node_args and use export default for exporting config
3) Run pm2 with the config

## Supporting information
pm2 - 4.4.0
node - v13.1.0
OS: Windows

**Comment by NebSehemvi** [comment]
Please take into account this issue too: [https://github.com/Unitech/pm2/issues/4591](#4591)
I guess it's related.
Though there is a 'patch', I guess it's better to have another solution

**Comment by NebSehemvi** [comment]
I'm facing pretty much the same problem on Ubuntu.

OS: Ubuntu 18.04
Node: 14.3.0
pm2 - 4.4.0

**Comment by david-saint** [comment]
I think if you pm2 to the latest version fixes the issue.

`yarn global add pm2@latest` then `pm2 update` fixed the issue for me

**Comment by NebSehemvi** [comment]
> I think if you pm2 to the latest version fixes the issue.
> 
> `yarn global add pm2@latest` then `pm2 update` fixed the issue for me

Unfortunately, 4.4.0 **is** the latest version of pm2.

Solution I found is adding "-r esm" to node_args and installing esm module to dependencies. But it's not an ideal solution. The problem with "type": "module" and --experimental-modules exist at least for two years.
