### ISSUE TITLE
PM2 autorestart false ends with exit code 2

### ISSUE THREAD

**Issue by lechen26** [Unitech/pm2#4730]
Hi

i have a PM2 Node app deployed on Kubernetes.
we want to create a CronJob resource on Kubernetes as the rest of our deployments.
problem is the PM2 is wrapping the application and acts a bit different.

basically in order to prevent PM2 from restart the application when it ends successfully with exit code 0, i've added the "autorestart: false" on the json file.
the thing is, although it does not restart the app, it says "PM2 ended successfully" but exist with exit code 2, which is causing the k8s itself to restart the pod.

i would assume it should ends with exist 0 if there are no restarts needed.
any way to control that?

10x

**Comment by nicosefer** [comment]
any update on this? I'm facing the same issue

**Comment by nicosefer** [comment]
any update on this? I'm facing the same issue

**Comment by Gheri** [comment]
@nicosefer & @lechen26 did you guys find any workaround for this ??

**Comment by cevaris** [comment]
same issue in 2025
