### ISSUE TITLE
[PM2][ERROR] Permission denied, to give access to current user

### ISSUE THREAD

**Issue by riverviewlegal** [Unitech/pm2#4734]
ubuntu@production:/etc/mediawiki/parsoid$ pm2 start bin/server
[PM2][ERROR] Permission denied, to give access to current user:
$ sudo chown ubuntu:ubuntu /home/ubuntu/.pm2/rpc.sock /home/ubuntu/.pm2/pub.sock
ubuntu@production:/etc/mediawiki/parsoid$

## What's going wrong?
Any time I run a PM2 command I get the following error "[PM2][ERROR] Permission denied, to give access to current user:"

## Supporting information

```
$ pm2 report

ubuntu@production:/etc/mediawiki/parsoid$ pm2 report
[PM2][ERROR] Permission denied, to give access to current user:
$ sudo chown ubuntu:ubuntu /home/ubuntu/.pm2/rpc.sock /home/ubuntu/.pm2/pub.sock
ubuntu@production:/etc/mediawiki/parsoid$


```

**Comment by Unitech** [comment]
Even if you run `sudo chown ubuntu:ubuntu /home/ubuntu/.pm2/rpc.sock /home/ubuntu/.pm2/pub.sock` you got a permission denied? How did you installed PM2?

**Comment by bvandenbon** [comment]
actually, you may want to run
` sudo chown ubuntu:ubuntu *.sock` 
because there is also an `interactor.sock`  which has the wrong user.
