### ISSUE TITLE
too many unstable restarts (16). Stopped. "errored"

### ISSUE THREAD

**Issue by shazzwazz20** [Unitech/pm2#4742]
Node version : 12
pm2 version : Latest 4.4

**My .js file**
_var http = require('http');
http.createServer(function (req, res) {
  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.end('Hello World\n');
}).listen(8080, 'localhost');
console.log('Server running at http://localhost:8080/');_

After running command npm2 start test.js ,it show status=Online for few seconds but after few seconds it show status=Errored

**pm2 report** 
PM2        | 2020-06-13T14:51:42: PM2 log: App [test:0] exited with code [1] via signal [SIGINT]
PM2        | 2020-06-13T14:51:42: PM2 log: App [test:0] starting in -fork mode-
PM2        | 2020-06-13T14:51:42: PM2 log: App [test:0] online
PM2        | 2020-06-13T14:51:42: PM2 log: App [test:0] exited with code [1] via signal [SIGINT]
PM2        | 2020-06-13T14:51:42: PM2 log: App [test:0] starting in -fork mode-
PM2        | 2020-06-13T14:51:42: PM2 log: App [test:0] online
PM2        | 2020-06-13T14:51:43: PM2 log: App [test:0] exited with code [1] via signal [SIGINT]
PM2        | 2020-06-13T14:51:43: PM2 log: App [test:0] starting in -fork mode-
PM2        | 2020-06-13T14:51:43: PM2 log: App [test:0] online
PM2        | 2020-06-13T14:51:43: PM2 log: App [test:0] exited with code [1] via signal [SIGINT]
PM2        | 2020-06-13T14:51:43: PM2 log: App [test:0] starting in -fork mode-
PM2        | 2020-06-13T14:51:43: PM2 log: App [test:0] online
PM2        | 2020-06-13T14:51:43: PM2 log: App [test:0] exited with code [1] via signal [SIGINT]
PM2        | 2020-06-13T14:51:43: PM2 log: App [test:0] starting in -fork mode-
PM2        | 2020-06-13T14:51:43: PM2 log: App [test:0] online
PM2        | 2020-06-13T14:51:43: PM2 log: App [test:0] exited with code [1] via signal [SIGINT]
PM2        | 2020-06-13T14:51:43: PM2 log: App [test:0] starting in -fork mode-
PM2        | 2020-06-13T14:51:43: PM2 log: App [test:0] online
PM2        | 2020-06-13T14:51:43: PM2 log: App [test:0] exited with code [1] via signal [SIGINT]
PM2        | 2020-06-13T14:51:43: PM2 log: Script /srv/test.js had too many unstable restarts (16). Stopped. "errored"

**Comment by ShahriarKh** [comment]
Hello. Do you remember how you got this fixed?

**Comment by RIKASHIKI** [comment]
> Hello. Do you remember how you got this fixed?

sorry friend I just replied now, some time ago I tried to update it but the program was too old, so I didn't continue it anymore
