### ISSUE TITLE
Security update to Vizion Package

### ISSUE THREAD

**Issue by ripplethor** [Unitech/pm2#4743]
https://snyk.io/test/npm/vizion/0.2.13

Command Injection
Vulnerable module: vizion
Introduced through: vizion@0.2.13
Detailed paths
Introduced through: vizion@0.2.13
Remediation: Upgrade to vizion@2.1.0.
Overview
vizion is a Git/Subversion/Mercurial repository metadata parser.

Affected versions of this package are vulnerable to Command Injection. The argument revision can be controlled by users without any sanitization.

**Comment by mapleeit** [comment]
Is there anyone who can take care of this?
