### ISSUE TITLE
Cannot start and give me status errored

### ISSUE THREAD

**Issue by ivanjuliant** [Unitech/pm2#4745]
i have some issue, before i got an issue like this i was install SSL using certbot and successfully, but after i check url doesn't give me a result, and then i try to see my app.js status, then i see status Online but not giving a result, so i run this command because i looking for a solution `pm2 start app.js --node-args="--harmony-destructuring --harmony_rest_parameters"` but after then give me status errored and i try to start again always stopped automaticaly, and i see status list and then status errored, i try another way but i see this error :

PM2        | 2020-06-15T15:30:49: PM2 log: App [app:0] exited with code [9] via signal [SIGINT]
PM2        | 2020-06-15T15:30:49: PM2 log: App [app:0] starting in -fork mode-
PM2        | 2020-06-15T15:30:49: PM2 log: App [app:0] online
PM2        | 2020-06-15T15:30:49: PM2 log: App [app:0] exited with code [9] via signal [SIGINT]
PM2        | 2020-06-15T15:30:49: PM2 log: App [app:0] starting in -fork mode-
PM2        | 2020-06-15T15:30:49: PM2 log: App [app:0] online
PM2        | 2020-06-15T15:30:49: PM2 log: App [app:0] exited with code [9] via signal [SIGINT]
PM2        | 2020-06-15T15:30:49: PM2 log: App [app:0] starting in -fork mode-
PM2        | 2020-06-15T15:30:49: PM2 log: App [app:0] online
PM2        | 2020-06-15T15:30:49: PM2 log: App [app:0] exited with code [9] via signal [SIGINT]
PM2        | 2020-06-15T15:30:49: PM2 log: App [app:0] starting in -fork mode-
PM2        | 2020-06-15T15:30:49: PM2 log: App [app:0] online
PM2        | 2020-06-15T15:30:49: PM2 log: App [app:0] exited with code [9] via signal [SIGINT]
PM2        | 2020-06-15T15:30:49: PM2 log: App [app:0] starting in -fork mode-
PM2        | 2020-06-15T15:30:49: PM2 log: App [app:0] online
PM2        | 2020-06-15T15:30:49: PM2 log: App [app:0] exited with code [9] via signal [SIGINT]
PM2        | 2020-06-15T15:30:49: PM2 log: App [app:0] starting in -fork mode-
PM2        | 2020-06-15T15:30:49: PM2 log: App [app:0] online
PM2        | 2020-06-15T15:30:49: PM2 log: App [app:0] exited with code [9] via signal [SIGINT]
PM2        | 2020-06-15T15:30:49: PM2 log: Script /root/codeo-promo/app.js had too many unstable restarts (16). Stopped. "errored"

anyone can help about this ?

**Comment by aksel** [comment]
This happens for me too, except I run it via an ecosystem file, and in cluster mode. Setting exec_mode to fork makes it work for me.

Node v14.4.0
PM2 v4.4.0

Here's the ecosystem file:
```
module.exports = {
  apps: [{
    name: 'express',
    script: 'src/bin/www.js',
    node_args: '-r esm',
    instances: 1,
    autorestart: true,
    max_restarts: 10,
    watch: true,
    env: {
      NODE_ENV: 'development',
      PORT: 5010,
    },
  }],
};
```

**Comment by aksel** [comment]
I found out why this was happening for me.

For some reason, ~/.pm2/node_modules did not exist. Creating that folder fixed it for me.

`mkdir -p ~/.pm2/node_modules`

No clue why this happens.
