### ISSUE TITLE
How can I run PM2 as user, without SUDO before the command?

### ISSUE THREAD

**Issue by tamaker** [Unitech/pm2#4757]
I'm running pm2 4.4.0, node.js 12.16.3 on an Ubuntu 18.04 machine and need to know how I can run PM2 commands WITHOUT having to use SUDO under my user account.    Is there some sort of CHOWN I can r un to fix this? or do I need to uninstall and reinstall via NPM with some specific level (i.e. globally, etc.)?

**Comment by anwarhamr** [comment]
related https://github.com/Unitech/pm2/issues/4734
