### ISSUE TITLE
On pm2 start or restart, display logs in terminal for 10 seconds

### ISSUE THREAD

**Issue by Unitech** [Unitech/pm2#4765]
This will permit to check if everything is working as expected on application started / restarted without having to re run pm2 ls + pm2 logs

**Comment by GustavoSD** [comment]
Is this a problem or it is a feature you would like pm2 to implement in the future?

**Comment by BarryThrill** [comment]
> This will permit to check if everything is working as expected on application started / restarted without having to re run pm2 ls + pm2 logs

Is it possible to change the keywords for closing the logs as when you run a script etc. python script with pm2, by default doing CTRL-C will first kill the python script and then the pm2 logs. I would recommend if its possible to set it as a argument etc --no-preview which skips the 10 seconds preview of logs?
