### ISSUE TITLE
PM2 is reading NVM version instead of Package.json on MacOS when using 'npm start' approach.

### ISSUE THREAD

**Issue by divineforge** [Unitech/pm2#4766]
## What's going wrong?
PM2 is reading version from 'nvm' instead of package.json. This is odd when running on Mac machine, but works fine in Linux machine (AWS Server),  

## How could we reproduce this issue?
- install node using nvm, and npm install pm2 globally.
- use pm2 configuration script, to start, using `script:npm`, `args: start` (invoking an npm start approach)

## Supporting information
PM2 4.4 running on MacOS

```
$ pm2 report
```
<img width="304" alt="Screenshot 2020-07-01 at 10 56 13 AM" src="https://user-images.githubusercontent.com/1146195/86198257-c51ac100-bb89-11ea-912e-848d63a1710c.png">

**Comment by divineforge** [comment]
https://stackoverflow.com/questions/68753840/pm2-process-manager-is-not-showing-the-actual-version-from-each-project-package

finally found the answer myself.

**Comment by jcodog** [comment]
But how do we resolve this? Is there no way to make it run and point to the correct path of the project file so it reads the package,json from the project instead of the package.json from npm, nvm or yarn etc.
