### ISSUE TITLE
Cluster multiple processes but pass different arguments to one of them?

### ISSUE THREAD

**Issue by nathanpeck** [Unitech/pm2#477]
I'd like to be able to cluster a process, but have one of the processes in the cluster play a special role, in this case to act as a garbage collector:

``` json
[
  {
    "name"       : "server",
    "script"     : "./server.js",
    "instances"  : "3",
    "exec_mode"  : "cluster_mode",
    "port"       : 9090,
  },
  {
    "name"       : "server-gc",
    "script"     : "./server.js",
    "args"        : "['--role=gc']",
    "instances"  : "1",
    "exec_mode"  : "cluster_mode",
    "port"       : 9090,
  }
]
```

This does not work because PM2 refuses the start the second script. Is there any way to do something similar to this with PM2, or am I going to have to code my own special purpose solution?

**Comment by petewarrior** [comment]
I created a symlink to the script and start that one.

**Comment by Flicksie** [comment]
4 Years later we still don't have this natively without a -f flag?

**Comment by gitgayhub** [comment]
> I created a symlink to the script and start that one.

thanks for the workaround

it's 2019 and we still don't have this feature, the "-f" flag doesn't work for me either

**Comment by danderson00** [comment]
Why is this issue closed? The suggested workaround (using the `-f` flag) does not appear to work, despite passing different arguments after `--` and naming the process differently. PM2 decides to `restartProcessId` instead of starting a new instance.
