### ISSUE TITLE
Variable substitution in processes.json

### ISSUE THREAD

**Issue by ravi** [Unitech/pm2#478]
It would be nice if processes.json could support variable/macro substitution so that I can have flexible install paths for the code:

```
    {
        "script" : "$INSTALL_DIR/bin/myapp.js"
        "args"   : "[ '--config', '$INSTALL_DIR/etc/config.json' ]"
        "out_file" : "$INSTALL_DIR/log/myapp.out"
        ....
    }
```

**Comment by vmarchaud** [comment]
You can[ write javascript](http://pm2.keymetrics.io/docs/usage/application-declaration/#json-javascript) inside ecosystem.json declaration in recent pm2 version.
