### ISSUE TITLE
Broken dependency @pm2/agent@~1.0.2

### ISSUE THREAD

**Issue by avalero** [Unitech/pm2#4802]
When running `yarn global pm2` it produces the following error

`error Couldn't find package "@pm2/agent@~1.0.2" required by "pm2" on the "npm" registry.`

**Comment by chayutzee** [comment]
Same here is my Error logs. 😥

error Couldn't find package "@pm2/agent@~1.0.2" required by "pm2" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
Error: Couldn't find package "@pm2/js-api@~0.6.0" required by "pm2" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/opt/yarn-v1.13.0/lib/cli.js:727:66)
    at new MessageError (/opt/yarn-v1.13.0/lib/cli.js:756:123)
    at PackageRequest.<anonymous> (/opt/yarn-v1.13.0/lib/cli.js:35729:17)
    at Generator.throw (<anonymous>)
    at step (/opt/yarn-v1.13.0/lib/cli.js:304:30)
    at /opt/yarn-v1.13.0/lib/cli.js:317:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Couldn't find package "@pm2/io@~4.3.5" required by "pm2" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/opt/yarn-v1.13.0/lib/cli.js:727:66)
    at new MessageError (/opt/yarn-v1.13.0/lib/cli.js:756:123)
    at PackageRequest.<anonymous> (/opt/yarn-v1.13.0/lib/cli.js:35729:17)
    at Generator.throw (<anonymous>)
    at step (/opt/yarn-v1.13.0/lib/cli.js:304:30)
    at /opt/yarn-v1.13.0/lib/cli.js:317:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Couldn't find package "@pm2/pm2-version-check@latest" required by "pm2" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/opt/yarn-v1.13.0/lib/cli.js:727:66)
    at new MessageError (/opt/yarn-v1.13.0/lib/cli.js:756:123)
    at PackageRequest.<anonymous> (/opt/yarn-v1.13.0/lib/cli.js:35729:17)
    at Generator.throw (<anonymous>)
    at step (/opt/yarn-v1.13.0/lib/cli.js:304:30)
    at /opt/yarn-v1.13.0/lib/cli.js:317:13
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by utkarshdeep10** [comment]
Same issue
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@pm2%2fagent - Not found
npm ERR! 404 
npm ERR! 404  '@pm2/agent@~1.0.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'pm2'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/utkarsh/.npm/_logs/2020-08-06T09_35_10_266Z-debug.log
```

**Comment by lgc** [comment]
Same issue

**Comment by brunowego** [comment]
Yep! Broken dependency...

**Comment by likepeach789** [comment]
Same issue, the dependency is totally broken..

**Comment by jakejakeho** [comment]
npm install -g pm2
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@pm2%2fagent - Not found
npm ERR! 404
npm ERR! 404  '@pm2/agent@~1.0.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'pm2'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by yurymuski** [comment]
Checked previous versions, only 2.10.4 still installs.
Could be fast workaround for someone:
```npm install pm2@2.10.4 -g```

**Comment by grv-sng** [comment]
same issue
`npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@pm2%2fagent - Not found
npm ERR! 404 
npm ERR! 404  '@pm2/agent@~1.0.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'pm2'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-06T09_57_40_757Z-debug.log`

**Comment by jakejakeho** [comment]
Copy from https://status.npmjs.org/
```
Update - The issue with the npm website was resolved. We are still looking into error telemetry for installation of scoped packages but are seeing signs of improvement.
Aug 6, 09:33 UTC
```

**Comment by lon-io** [comment]
Same:

```
root@6e0c161fbb4b:/wwnow-api# npm i @pm2/pm2-version-check@1.0.0
npm ERR! code E404
npm ERR! 404 Not Found - GET https://npm-registry.westwing.eu/repository/npm/@pm2%2fpm2-version-check - Not found
npm ERR! 404
npm ERR! 404  '@pm2/pm2-version-check@1.0.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-06T10_02_31_242Z-debug.log
```

**Comment by kushsingh11** [comment]
Same here

**Comment by jakejakeho** [comment]
It seems ok now. Please try again!!
`+ pm2@4.4.0
added 99 packages from 73 contributors, removed 131 packages, updated 30 packages and moved 1 package in 4.865s`

**Comment by Unitech** [comment]
closing at it was related to npm
