### ISSUE TITLE
 code E404 while trying to install pm2 using npm

### ISSUE THREAD

**Issue by roshanconnor123** [Unitech/pm2#4803]
## What's going wrong?
Hi
When I tried to install pm2 via npm I am getting `npm ERR! code E404`
## Supporting information
The command I ran `npm i pm2 -g`

Output :
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@pm2%2fagent - Not found
npm ERR! 404
npm ERR! 404  '@pm2/agent@~1.0.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'pm2'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-08-06T09_50_56_130Z-debug.log
```

```
$ pm2 report
```

**Comment by impacmp** [comment]
same here

**Comment by lon-io** [comment]
Getting a similar error, but for version check:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://npm-registry.westwing.eu/repository/npm/@pm2%2fpm2-version-check - Not found
npm ERR! 404
npm ERR! 404  '@pm2/pm2-version-check@1.0.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-06T10_00_28_545Z-debug.log
```

**Comment by basharov** [comment]
I see a similar error, but it sometimes shows `http://registry.npmjs.org/@pm2%2fagent` as not found, and sometimes `https://registry.npmjs.org/@pm2%2fio`

**Comment by jcdsr** [comment]
I'm having the same issue, trying to install pm2 - 4.4.0



npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@pm2%2fjs-api - Not found
npm ERR! 404 
npm ERR! 404  '@pm2/js-api@~0.6.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'pm2'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by chintansureliya** [comment]
Same here from last 1 hour.
Please fix this ASAP this is a showstopper for alot of organizations

**Comment by basharov** [comment]
Tried again and it worked.

**Comment by phamvanhiepvn** [comment]
cay

**Comment by roshanconnor123** [comment]
Gonna try again now

> Tried again and it worked.

**Comment by jcdsr** [comment]
is working now, bizarre!

**Comment by chintansureliya** [comment]
Seems like an issue with NPM cache.

https://status.npmjs.org/incidents/cksjqc1w11v5

**Comment by Unitech** [comment]
closing at it was related to npm

**Comment by Devendra-Raj-Sharma** [comment]
same here

PS C:\Users\DEVENDRA RAJ SHARMA\Desktop\Project> npm i cloudnary
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/cloudnary - Not found   
npm ERR! 404 
npm ERR! 404  'cloudnary@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DEVENDRA RAJ SHARMA\AppData\Local\npm-cache\_logs\2021-09-20T10_37_37_713Z-debug.log

**Comment by hengshanMWC** [comment]
npm i pm2 -g
npm ERR! code E404
npm ERR! 404 Not Found - GET https://cdn.npmmirror.com/binaries/npm/pm2
npm ERR! 404 
npm ERR! 404  'pm2@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /www/server/nodejs/v16.20.2/cache/_logs/2024-08-15T12_36_03_884Z-debug-0.log
