### ISSUE TITLE
The "data" argument must be of type string or an instance of Buffer

### ISSUE THREAD

**Issue by NMW03** [Unitech/pm2#4814]
I upgraded my node.js version to 14.0.0. After running pm2 update this I get this errors:
![image](https://user-images.githubusercontent.com/50991261/90324372-0838c400-df7f-11ea-89a4-cefb9b65c14e.png)
![image](https://user-images.githubusercontent.com/50991261/90324377-15ee4980-df7f-11ea-855d-159c821b120b.png)

**Comment by Unitech** [comment]
upgrade pm2 to latest

**Comment by cseitz** [comment]
I just encountered this issue. For some reason, PM2 would start rebooting all the processes every few minutes. Updating PM2 to latest resolved this.

Hopefully, if anyone else encounters the same problem because you were using outdated PM2 like me, you'll see this to know that this is the solution.

**Comment by vallamost** [comment]
I am seeing this issue but my PM2 is at the latest version :|, I'm even using the PM2 alpine image..
