### ISSUE TITLE
Can't startup, please help

### ISSUE THREAD

**Issue by mani95lisa** [Unitech/pm2#483]
node 0.11.10
pm2 0.8.12

When I use `node index`, I got this:

```
js-bson: Failed to load c++ bson extension, using pure JS version
SMTP Configured!
Listening on 8000
db connection open
```

But when I use `pm2 start index.js`, application can't run , and I just got this error:

```
js-bson: Failed to load c++ bson extension, using pure JS version
```

Please help me out, thanks for your time!

**Comment by coyle** [comment]
I am getting the same issue when running pm2

I can run node <filename> and no errors

When I run pm2 start <filename> it throws:

js-bson: Failed to load c++ bson extension, using pure JS version

**Comment by coyle** [comment]
ok I found my issue.. 
I ran:
```npm uninstall pm2 -g
   ps -aux | grep pm2
````
then killed every job that was running a pm2 instance
then I went and removed the $PM2_HOME folder
finally, I re-ran npm install pm2 -g

That did the trick and I am no longer getting the error:

```js-bson: Failed to load c++ bson extension, using pure JS version```

when running pm2
