### ISSUE TITLE
PM2 unable to run ESM packages: ERR_UNSUPPORTED_ESM_URL_SCHEME

### ISSUE THREAD

**Issue by ox-harris** [Unitech/pm2#4839]
## What's going wrong?
In this version of pm2 (v4.4.1), `pm2.start ('reference/to/esm-package/script.js')` is throwing the following error in `err.log` file: Error `[ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader`

The stack trace reveals the problem to be with the ESM script loader in `lib\ProcessContainerFork.js:29:24`. There the import statement is attempting to import the ESM script using the file path instead of a file scheme.

## How could we reproduce this issue?
Try starting a script within an ES module package: `pm2.start ('reference/to/esm-package/script.js')`, then find the error in the `err` file for the process. 

## Supporting information
PM2 version:  v4.4.1
Node version: v13.7.0
OS: windows

I wouldn't mind submitting a PR for a fix. It simply requires converting the given path to a file URL using `url.pathToFileURL()`.
So, instead of `import(process.env.pm_exec_path);`, we should now have `import(url.pathToFileURL(process.env.pm_exec_path));`

**Comment by Unitech** [comment]
published in pm2@4.5.0

```bash
npm install pm2@latest -g
```

**Comment by ParallelUniv3rse** [comment]
Hi guys, 
still having trouble with this when running basic `pm2 start ecosystem.json` on windows in cluster mode. 
I've tried switching to fork mode, but no luck there either. Process is till using ProcessContainer.js where this same exact issue occurs on line 301. 

Any special steps on how to make use of this fix?

**Comment by pubmikeb** [comment]
@Unitech, unfortunately this issue is still relevant for `pm2` v.5.1.0 running on Node.js 16.4.0.
Currently, I can't use `"exec_mode": "cluster"`, only `"exec_mode": "fork"` can be used.

Please, fix the incompatibility to be able use the full potential of `pm2`.

**Comment by ulziibadrakh-p** [comment]
Any solution?
