### ISSUE TITLE
pm2 cluster mode in a udp server

### ISSUE THREAD

**Issue by janpoltan** [Unitech/pm2#4861]
I cant seem to make the node app to use clustering mode when setting up a udp server

```js
const dgram = require('dgram');
const server = dgram.createSocket({
  type: 'udp4',
  reuseAddr: true
});
const { handler } = require('./fn/index');

const HOST = '0.0.0.0';
const PORT = 3001;


server.on('error', (err: Error) => {
  console.log(`server error:\n${err.stack}`);
  server.close();
});

server.on('message', (msg: string, rinfo: any) => {
  const base64 = Buffer.from(msg, 'hex').toString('base64');
  console.log(`Server got: ${base64} from ${rinfo.address}:${rinfo.port}`);
  const event = {
    data: base64,
    timestamp: Date.now().toString()
  };
  handler(event).then((r: string) => {
    console.log('Done', r);
  });
});

server.on('listening', () => {
  const address = server.address();
  console.log(`Server listening ${address.address}:${address.port}`);
});

server.bind({
  address: HOST,
  port: PORT,
  exclusive: true
});
```
pm2 config

```
module.exports = {
  apps: [
    {
      script: 'build/server.js',
      instances: 'max',
      exec_mode: 'cluster_mode'
    }
  ]
};
```
pm2 started 4 processes based on cpu count

Tried looking in the process logs, and test using a fast network traffic generator (~50ms interval), and it 
seems only a single process is handling the requests instead of load balancing them.

**Comment by Unitech** [comment]
Tried this example: https://gist.github.com/Unitech/ca40379518b794c134846c0cd84924c7
With pm2 start -i max server.js + pm2 start -i max client.js

![Screenshot from 2020-09-28 13-43-48](https://user-images.githubusercontent.com/757747/94428260-b6e03f00-0190-11eb-9c7b-c613e81fd81d.png)

Load balancing works great!

**Comment by Unitech** [comment]
You can use `pm2 imonit` to get this monitoring view on the left
