### ISSUE TITLE
[PM2] Spawning PM2 daemon with pm2_home=/home/xnl4r2wj90p5/.pm2

### ISSUE THREAD

**Issue by Nupur13** [Unitech/pm2#4862]
## Supporting information

```
$ pm2 report
```

*****************************************************
PM2 version          : 3.5.0
Node.js version      : 10.15.3

***********************************
Disk Space:
Filesystem      Size  Used Avail Use% Mounted on
-               118G   18G   96G  16% /
**********************************
Please suggest, it my website goes down twice in a month due to spawning pm2 and there is not much info in logs also.

**Comment by Unitech** [comment]
upgrade pm2 to more recent version
