### ISSUE TITLE
How To Script "Call PM2" From PHP or Web or Exec (Command)?

### ISSUE THREAD

**Issue by wulandrima1** [Unitech/pm2#4863]
How to script call pm2 from php?

pm2.php
shell_exec(" pm2 start api.js");

i running my server ubuntu example.com/pm2.php
but dont work, show "message of welcome"

can you help me?

**Comment by Unitech** [comment]
Just tried this: 

```
<?php
echo shell_exec("pm2 start examples/echo/log.js");
?>
```

that works
