### ISSUE TITLE
socket.io response 404

### ISSUE THREAD

**Issue by jazuly** [Unitech/pm2#4866]
## What's going wrong?
my websocket return 404 when i run my project with pm2

## Supporting information
my project can run without problem when i run it manually with `npm run start`

here my `ecosystem.config.js`
```
module.exports = {
  apps: [
    {
      name: 'vconference',
      exec_mode: 'cluster',
      instances: '1',
      script: './node_modules/nuxt/bin/nuxt.js',
      args: 'start',
      watch: true,
        env: {
          "PORT": 3004,
          "NODE_ENV": "production"
        }
    }
  ]
}
```

**Comment by Unitech** [comment]
Related to your app not pm2
