### ISSUE TITLE
unable to login to pm2 plus

### ISSUE THREAD

**Issue by the-cute-panda** [Unitech/pm2#4867]
I'm unable to login to pm2 plus it just says [PM2 I/O] Failed to authenticate: certificate has expired

**Comment by the2003s** [comment]
Today when I logged into my PM2 dashboard I got errors saying "Failed to load the page. Please retry later". I tried opening an incognito window and the same thing happened. I see a an error in the browser console "ERR_CERT_DATE_INVALID"

**Comment by Unitech** [comment]
fixed

**Comment by jayvi** [comment]
xhr.js:178 XHR failed loading: POST "https://supernova.keymetrics.io/api/bucket/5f523c19fbadf42f8cee2e72/data/metrics/list".
(anonymous) @ xhr.js:178
e.exports @ xhr.js:12
e.exports @ dispatchRequest.js:50
Promise.then (async)
u.request @ Axios.js:61
(anonymous) @ bind.js:9
(anonymous) @ network.js:210
(anonymous) @ network.js:261
Promise.then (async)
_updateTokens @ network.js:257
(anonymous) @ network.js:204
(anonymous) @ browser_strategy.js:35
Promise.then (async)
retrieveTokens @ browser_strategy.js:30
s @ network.js:196
(anonymous) @ network.js:218
Promise.catch (async)
(anonymous) @ network.js:184
(anonymous) @ async.js:3880
l @ async.js:1011
u @ async.js:995
(anonymous) @ async.js:969
(anonymous) @ async.js:3885
(anonymous) @ network.js:168
Promise.then (async)
(anonymous) @ network.js:165
(anonymous) @ async.js:3880
l @ async.js:1011
(anonymous) @ async.js:1016
me @ async.js:1041
(anonymous) @ async.js:1046
rn @ async.js:3879
bn @ async.js:4735
(anonymous) @ network.js:144
request @ network.js:143
(anonymous) @ endpoint.js:28
Promise.then (async)
(anonymous) @ endpoint.js:21
(anonymous) @ endpoint.js:19
(anonymous) @ pm2Io.js:89
SET_CURRENT_BUCKET @ actions.js:403
(anonymous) @ vuex.esm.js:772
l.dispatch @ vuex.esm.js:453
dispatch @ vuex.esm.js:343
(anonymous) @ index.js:922
p @ vue-router.esm.js:1962
i @ vue-router.esm.js:1736
i @ vue-router.esm.js:1740
pe @ vue-router.esm.js:1744
_e.confirmTransition @ vue-router.esm.js:1991
_e.transitionTo @ vue-router.esm.js:1893
t.push @ vue-router.esm.js:2203
je.push @ vue-router.esm.js:2584
goToBucket @ index.vue:148
click @ index.vue?33b6:128
ze @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
s._wrapper @ vue.runtime.esm.js:6917
xhr.js:178 XHR finished loading: GET "https://app.keymetrics.io/api/bucket".
(anonymous) @ xhr.js:178
e.exports @ xhr.js:12
e.exports @ dispatchRequest.js:50
Promise.then (async)
u.request @ Axios.js:61
(anonymous) @ bind.js:9
_updateTokens @ network.js:251
(anonymous) @ network.js:204
(anonymous) @ browser_strategy.js:35
Promise.then (async)
retrieveTokens @ browser_strategy.js:30
s @ network.js:196
(anonymous) @ network.js:218
Promise.catch (async)
(anonymous) @ network.js:184
(anonymous) @ async.js:3880
l @ async.js:1011
u @ async.js:995
(anonymous) @ async.js:969
(anonymous) @ async.js:3885
(anonymous) @ network.js:168
Promise.then (async)
(anonymous) @ network.js:165
(anonymous) @ async.js:3880
l @ async.js:1011
(anonymous) @ async.js:1016
me @ async.js:1041
(anonymous) @ async.js:1046
rn @ async.js:3879
bn @ async.js:4735
(anonymous) @ network.js:144
request @ network.js:143
(anonymous) @ endpoint.js:28
Promise.then (async)
(anonymous) @ endpoint.js:21
(anonymous) @ endpoint.js:19
(anonymous) @ pm2Io.js:89
FETCH_APPS @ frontendApplications.js:94
(anonymous) @ vuex.esm.js:772
l.dispatch @ vuex.esm.js:453
dispatch @ vuex.esm.js:343
SET_CURRENT_BUCKET @ actions.js:408
(anonymous) @ vuex.esm.js:772
l.dispatch @ vuex.esm.js:453
dispatch @ vuex.esm.js:343
(anonymous) @ index.js:922
p @ vue-router.esm.js:1962
i @ vue-router.esm.js:1736
i @ vue-router.esm.js:1740
pe @ vue-router.esm.js:1744
_e.confirmTransition @ vue-router.esm.js:1991
_e.transitionTo @ vue-router.esm.js:1893
t.push @ vue-router.esm.js:2203
je.push @ vue-router.esm.js:2584
goToBucket @ index.vue:148
click @ index.vue?33b6:128
ze @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
s._wrapper @ vue.runtime.esm.js:6917
pm2Io.js:64 Unexpected pm2-js-api error: Error: Network Error
    at e.exports (createError.js:16)
    at XMLHttpRequest.f.onerror (xhr.js:83)
(anonymous) @ pm2Io.js:64
(anonymous) @ pm2Io.js:104
Promise.then (async)
(anonymous) @ pm2Io.js:97
FETCH_APPS @ frontendApplications.js:94
(anonymous) @ vuex.esm.js:772
l.dispatch @ vuex.esm.js:453
dispatch @ vuex.esm.js:343
SET_CURRENT_BUCKET @ actions.js:408
(anonymous) @ vuex.esm.js:772
l.dispatch @ vuex.esm.js:453
dispatch @ vuex.esm.js:343
(anonymous) @ index.js:922
p @ vue-router.esm.js:1962
i @ vue-router.esm.js:1736
i @ vue-router.esm.js:1740
pe @ vue-router.esm.js:1744
_e.confirmTransition @ vue-router.esm.js:1991
_e.transitionTo @ vue-router.esm.js:1893
t.push @ vue-router.esm.js:2203
je.push @ vue-router.esm.js:2584
goToBucket @ index.vue:148
click @ index.vue?33b6:128
ze @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
s._wrapper @ vue.runtime.esm.js:6917
xhr.js:178 GET https://supernova.keymetrics.io/api/bucket/5f523c19fbadf42f8cee2e72/applications net::ERR_CERT_DATE_INVALID
(anonymous) @ xhr.js:178
e.exports @ xhr.js:12
e.exports @ dispatchRequest.js:50
Promise.then (async)
u.request @ Axios.js:61
(anonymous) @ bind.js:9
(anonymous) @ network.js:210
(anonymous) @ network.js:261
Promise.then (async)
_updateTokens @ network.js:257
(anonymous) @ network.js:204
(anonymous) @ browser_strategy.js:35
Promise.then (async)
retrieveTokens @ browser_strategy.js:30
s @ network.js:196
(anonymous) @ network.js:218
Promise.catch (async)
(anonymous) @ network.js:184
(anonymous) @ async.js:3880
l @ async.js:1011
u @ async.js:995
(anonymous) @ async.js:969
(anonymous) @ async.js:3885
(anonymous) @ network.js:168
Promise.then (async)
(anonymous) @ network.js:165
(anonymous) @ async.js:3880
l @ async.js:1011
(anonymous) @ async.js:1016
me @ async.js:1041
(anonymous) @ async.js:1046
rn @ async.js:3879
bn @ async.js:4735
(anonymous) @ network.js:144
request @ network.js:143
(anonymous) @ endpoint.js:28
Promise.then (async)
(anonymous) @ endpoint.js:21
(anonymous) @ endpoint.js:19
(anonymous) @ pm2Io.js:89
FETCH_APPS @ frontendApplications.js:94
(anonymous) @ vuex.esm.js:772
l.dispatch @ vuex.esm.js:453
dispatch @ vuex.esm.js:343
SET_CURRENT_BUCKET @ actions.js:408
(anonymous) @ vuex.esm.js:772
l.dispatch @ vuex.esm.js:453
dispatch @ vuex.esm.js:343
(anonymous) @ index.js:922
p @ vue-router.esm.js:1962
i @ vue-router.esm.js:1736
i @ vue-router.esm.js:1740
pe @ vue-router.esm.js:1744
_e.confirmTransition @ vue-router.esm.js:1991
_e.transitionTo @ vue-router.esm.js:1893
t.push @ vue-router.esm.js:2203
je.push @ vue-router.esm.js:2584
goToBucket @ index.vue:148
click @ index.vue?33b6:128
ze @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
s._wrapper @ vue.runtime.esm.js:6917
xhr.js:178 XHR failed loading: GET "https://supernova.keymetrics.io/api/bucket/5f523c19fbadf42f8cee2e72/applications".
(anonymous) @ xhr.js:178
e.exports @ xhr.js:12
e.exports @ dispatchRequest.js:50
Promise.then (async)
u.request @ Axios.js:61
(anonymous) @ bind.js:9
(anonymous) @ network.js:210
(anonymous) @ network.js:261
Promise.then (async)
_updateTokens @ network.js:257
(anonymous) @ network.js:204
(anonymous) @ browser_strategy.js:35
Promise.then (async)
retrieveTokens @ browser_strategy.js:30
s @ network.js:196
(anonymous) @ network.js:218
Promise.catch (async)
(anonymous) @ network.js:184
(anonymous) @ async.js:3880
l @ async.js:1011
u @ async.js:995
(anonymous) @ async.js:969
(anonymous) @ async.js:3885
(anonymous) @ network.js:168
Promise.then (async)
(anonymous) @ network.js:165
(anonymous) @ async.js:3880
l @ async.js:1011
(anonymous) @ async.js:1016
me @ async.js:1041
(anonymous) @ async.js:1046
rn @ async.js:3879
bn @ async.js:4735
(anonymous) @ network.js:144
request @ network.js:143
(anonymous) @ endpoint.js:28
Promise.then (async)
(anonymous) @ endpoint.js:21
(anonymous) @ endpoint.js:19
(anonymous) @ pm2Io.js:89
FETCH_APPS @ frontendApplications.js:94
(anonymous) @ vuex.esm.js:772
l.dispatch @ vuex.esm.js:453
dispatch @ vuex.esm.js:343
SET_CURRENT_BUCKET @ actions.js:408
(anonymous) @ vuex.esm.js:772
l.dispatch @ vuex.esm.js:453
dispatch @ vuex.esm.js:343
(anonymous) @ index.js:922
p @ vue-router.esm.js:1962
i @ vue-router.esm.js:1736
i @ vue-router.esm.js:1740
pe @ vue-router.esm.js:1744
_e.confirmTransition @ vue-router.esm.js:1991
_e.transitionTo @ vue-router.esm.js:1893
t.push @ vue-router.esm.js:2203
je.push @ vue-router.esm.js:2584
goToBucket @ index.vue:148
click @ index.vue?33b6:128
ze @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
s._wrapper @ vue.runtime.esm.js:6917
xhr.js:178 XHR finished loading: GET "https://app.keymetrics.io/api/bucket".
(anonymous) @ xhr.js:178
e.exports @ xhr.js:12
e.exports @ dispatchRequest.js:50
Promise.then (async)
u.request @ Axios.js:61
(anonymous) @ bind.js:9
_updateTokens @ network.js:251
(anonymous) @ network.js:204
(anonymous) @ browser_strategy.js:43
Promise.then (async)
retrieveTokens @ browser_strategy.js:40
s @ network.js:196
(anonymous) @ network.js:218
Promise.catch (async)
(anonymous) @ network.js:184
(anonymous) @ async.js:3880
l @ async.js:1011
u @ async.js:995
(anonymous) @ async.js:969
(anonymous) @ async.js:3885
(anonymous) @ network.js:168
Promise.then (async)
(anonymous) @ network.js:165
(anonymous) @ async.js:3880
l @ async.js:1011
(anonymous) @ async.js:1016
me @ async.js:1041
(anonymous) @ async.js:1046
rn @ async.js:3879
bn @ async.js:4735
(anonymous) @ network.js:144
request @ network.js:143
(anonymous) @ endpoint.js:28
Promise.then (async)
(anonymous) @ endpoint.js:21
(anonymous) @ endpoint.js:19
(anonymous) @ pm2Io.js:89
RETRIEVE_USERS @ actions.js:1115
(anonymous) @ vuex.esm.js:772
l.dispatch @ vuex.esm.js:453
dispatch @ vuex.esm.js:343
(anonymous) @ index.vue:117
created @ index.vue:116
ze @ vue.runtime.esm.js:1854
Qt @ vue.runtime.esm.js:4219
e._init @ vue.runtime.esm.js:5008
a @ vue.runtime.esm.js:5154
(anonymous) @ vue.runtime.esm.js:3283
init @ vue.runtime.esm.js:3114
n @ vue.runtime.esm.js:3301
(anonymous) @ vue.runtime.esm.js:5978
d @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6216
x @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6193
x @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6193
x @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6193
x @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6193
x @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6482
e._update @ vue.runtime.esm.js:3948
i @ vue.runtime.esm.js:4066
pn.get @ vue.runtime.esm.js:4479
pn.run @ vue.runtime.esm.js:4554
cn @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
Ke @ vue.runtime.esm.js:1906
Promise.then (async)
Ue @ vue.runtime.esm.js:1933
tt @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
pn.update @ vue.runtime.esm.js:4544
ce.notify @ vue.runtime.esm.js:730
(anonymous) @ vue.runtime.esm.js:882
addItem @ index.js:465
ze @ vue.runtime.esm.js:1854
e.$emit @ vue.runtime.esm.js:3888
n @ index.js:181
DISPLAY_NOTIFICATION @ notifications.js:25
(anonymous) @ vuex.esm.js:772
l.dispatch @ vuex.esm.js:453
dispatch @ vuex.esm.js:343
(anonymous) @ index.js:929
async function (async)
(anonymous) @ index.js:927
p @ vue-router.esm.js:1962
i @ vue-router.esm.js:1736
i @ vue-router.esm.js:1740
pe @ vue-router.esm.js:1744
_e.confirmTransition @ vue-router.esm.js:1991
_e.transitionTo @ vue-router.esm.js:1893
t.push @ vue-router.esm.js:2203
je.push @ vue-router.esm.js:2584
goToBucket @ index.vue:148
click @ index.vue?33b6:128
ze @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
s._wrapper @ vue.runtime.esm.js:6917
Show 35 more frames
pm2Io.js:64 Unexpected pm2-js-api error: Error: Network Error
    at e.exports (createError.js:16)
    at XMLHttpRequest.f.onerror (xhr.js:83)
(anonymous) @ pm2Io.js:64
(anonymous) @ pm2Io.js:104
Promise.then (async)
(anonymous) @ pm2Io.js:97
RETRIEVE_USERS @ actions.js:1115
(anonymous) @ vuex.esm.js:772
l.dispatch @ vuex.esm.js:453
dispatch @ vuex.esm.js:343
(anonymous) @ index.vue:117
created @ index.vue:116
ze @ vue.runtime.esm.js:1854
Qt @ vue.runtime.esm.js:4219
e._init @ vue.runtime.esm.js:5008
a @ vue.runtime.esm.js:5154
(anonymous) @ vue.runtime.esm.js:3283
init @ vue.runtime.esm.js:3114
n @ vue.runtime.esm.js:3301
(anonymous) @ vue.runtime.esm.js:5978
d @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6216
x @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6193
x @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6193
x @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6193
x @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6193
x @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6482
e._update @ vue.runtime.esm.js:3948
i @ vue.runtime.esm.js:4066
pn.get @ vue.runtime.esm.js:4479
pn.run @ vue.runtime.esm.js:4554
cn @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
Ke @ vue.runtime.esm.js:1906
Promise.then (async)
Ue @ vue.runtime.esm.js:1933
tt @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
pn.update @ vue.runtime.esm.js:4544
ce.notify @ vue.runtime.esm.js:730
(anonymous) @ vue.runtime.esm.js:882
addItem @ index.js:465
ze @ vue.runtime.esm.js:1854
e.$emit @ vue.runtime.esm.js:3888
n @ index.js:181
DISPLAY_NOTIFICATION @ notifications.js:25
(anonymous) @ vuex.esm.js:772
l.dispatch @ vuex.esm.js:453
dispatch @ vuex.esm.js:343
(anonymous) @ index.js:929
async function (async)
(anonymous) @ index.js:927
p @ vue-router.esm.js:1962
i @ vue-router.esm.js:1736
i @ vue-router.esm.js:1740
pe @ vue-router.esm.js:1744
_e.confirmTransition @ vue-router.esm.js:1991
_e.transitionTo @ vue-router.esm.js:1893
t.push @ vue-router.esm.js:2203
je.push @ vue-router.esm.js:2584
goToBucket @ index.vue:148
click @ index.vue?33b6:128
ze @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
s._wrapper @ vue.runtime.esm.js:6917
Show 6 more frames
xhr.js:178 GET https://supernova.keymetrics.io/api/bucket/5f523c19fbadf42f8cee2e72/users_authorized net::ERR_CERT_DATE_INVALID
(anonymous) @ xhr.js:178
e.exports @ xhr.js:12
e.exports @ dispatchRequest.js:50
Promise.then (async)
u.request @ Axios.js:61
(anonymous) @ bind.js:9
(anonymous) @ network.js:210
(anonymous) @ network.js:261
Promise.then (async)
_updateTokens @ network.js:257
(anonymous) @ network.js:204
(anonymous) @ browser_strategy.js:43
Promise.then (async)
retrieveTokens @ browser_strategy.js:40
s @ network.js:196
(anonymous) @ network.js:218
Promise.catch (async)
(anonymous) @ network.js:184
(anonymous) @ async.js:3880
l @ async.js:1011
u @ async.js:995
(anonymous) @ async.js:969
(anonymous) @ async.js:3885
(anonymous) @ network.js:168
Promise.then (async)
(anonymous) @ network.js:165
(anonymous) @ async.js:3880
l @ async.js:1011
(anonymous) @ async.js:1016
me @ async.js:1041
(anonymous) @ async.js:1046
rn @ async.js:3879
bn @ async.js:4735
(anonymous) @ network.js:144
request @ network.js:143
(anonymous) @ endpoint.js:28
Promise.then (async)
(anonymous) @ endpoint.js:21
(anonymous) @ endpoint.js:19
(anonymous) @ pm2Io.js:89
RETRIEVE_USERS @ actions.js:1115
(anonymous) @ vuex.esm.js:772
l.dispatch @ vuex.esm.js:453
dispatch @ vuex.esm.js:343
(anonymous) @ index.vue:117
created @ index.vue:116
ze @ vue.runtime.esm.js:1854
Qt @ vue.runtime.esm.js:4219
e._init @ vue.runtime.esm.js:5008
a @ vue.runtime.esm.js:5154
(anonymous) @ vue.runtime.esm.js:3283
init @ vue.runtime.esm.js:3114
n @ vue.runtime.esm.js:3301
(anonymous) @ vue.runtime.esm.js:5978
d @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6216
x @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6193
x @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6193
x @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6193
x @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6193
x @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6482
e._update @ vue.runtime.esm.js:3948
i @ vue.runtime.esm.js:4066
pn.get @ vue.runtime.esm.js:4479
pn.run @ vue.runtime.esm.js:4554
cn @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
Ke @ vue.runtime.esm.js:1906
Promise.then (async)
Ue @ vue.runtime.esm.js:1933
tt @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
pn.update @ vue.runtime.esm.js:4544
ce.notify @ vue.runtime.esm.js:730
(anonymous) @ vue.runtime.esm.js:882
addItem @ index.js:465
ze @ vue.runtime.esm.js:1854
e.$emit @ vue.runtime.esm.js:3888
n @ index.js:181
DISPLAY_NOTIFICATION @ notifications.js:25
(anonymous) @ vuex.esm.js:772
l.dispatch @ vuex.esm.js:453
dispatch @ vuex.esm.js:343
(anonymous) @ index.js:929
async function (async)
(anonymous) @ index.js:927
p @ vue-router.esm.js:1962
i @ vue-router.esm.js:1736
i @ vue-router.esm.js:1740
pe @ vue-router.esm.js:1744
_e.confirmTransition @ vue-router.esm.js:1991
_e.transitionTo @ vue-router.esm.js:1893
t.push @ vue-router.esm.js:2203
je.push @ vue-router.esm.js:2584
goToBucket @ index.vue:148
click @ index.vue?33b6:128
ze @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
s._wrapper @ vue.runtime.esm.js:6917
Show 36 more frames
createError.js:16 Uncaught (in promise) Error: Network Error
    at e.exports (createError.js:16)
    at XMLHttpRequest.f.onerror (xhr.js:83)
e.exports @ createError.js:16
f.onerror @ xhr.js:83
Promise.then (async)
created @ index.vue:123
ze @ vue.runtime.esm.js:1854
Qt @ vue.runtime.esm.js:4219
e._init @ vue.runtime.esm.js:5008
a @ vue.runtime.esm.js:5154
(anonymous) @ vue.runtime.esm.js:3283
init @ vue.runtime.esm.js:3114
n @ vue.runtime.esm.js:3301
(anonymous) @ vue.runtime.esm.js:5978
d @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6216
x @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6193
x @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6193
x @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6193
x @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6193
x @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6482
e._update @ vue.runtime.esm.js:3948
i @ vue.runtime.esm.js:4066
pn.get @ vue.runtime.esm.js:4479
pn.run @ vue.runtime.esm.js:4554
cn @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
Ke @ vue.runtime.esm.js:1906
Promise.then (async)
Ue @ vue.runtime.esm.js:1933
tt @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
pn.update @ vue.runtime.esm.js:4544
ce.notify @ vue.runtime.esm.js:730
(anonymous) @ vue.runtime.esm.js:882
addItem @ index.js:465
ze @ vue.runtime.esm.js:1854
e.$emit @ vue.runtime.esm.js:3888
n @ index.js:181
DISPLAY_NOTIFICATION @ notifications.js:25
(anonymous) @ vuex.esm.js:772
l.dispatch @ vuex.esm.js:453
dispatch @ vuex.esm.js:343
(anonymous) @ index.js:929
async function (async)
(anonymous) @ index.js:927
p @ vue-router.esm.js:1962
i @ vue-router.esm.js:1736
i @ vue-router.esm.js:1740
pe @ vue-router.esm.js:1744
_e.confirmTransition @ vue-router.esm.js:1991
_e.transitionTo @ vue-router.esm.js:1893
t.push @ vue-router.esm.js:2203
je.push @ vue-router.esm.js:2584
goToBucket @ index.vue:148
click @ index.vue?33b6:128
ze @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
s._wrapper @ vue.runtime.esm.js:6917
xhr.js:178 XHR failed loading: GET "https://supernova.keymetrics.io/api/bucket/5f523c19fbadf42f8cee2e72/users_authorized".
(anonymous) @ xhr.js:178
e.exports @ xhr.js:12
e.exports @ dispatchRequest.js:50
Promise.then (async)
u.request @ Axios.js:61
(anonymous) @ bind.js:9
(anonymous) @ network.js:210
(anonymous) @ network.js:261
Promise.then (async)
_updateTokens @ network.js:257
(anonymous) @ network.js:204
(anonymous) @ browser_strategy.js:43
Promise.then (async)
retrieveTokens @ browser_strategy.js:40
s @ network.js:196
(anonymous) @ network.js:218
Promise.catch (async)
(anonymous) @ network.js:184
(anonymous) @ async.js:3880
l @ async.js:1011
u @ async.js:995
(anonymous) @ async.js:969
(anonymous) @ async.js:3885
(anonymous) @ network.js:168
Promise.then (async)
(anonymous) @ network.js:165
(anonymous) @ async.js:3880
l @ async.js:1011
(anonymous) @ async.js:1016
me @ async.js:1041
(anonymous) @ async.js:1046
rn @ async.js:3879
bn @ async.js:4735
(anonymous) @ network.js:144
request @ network.js:143
(anonymous) @ endpoint.js:28
Promise.then (async)
(anonymous) @ endpoint.js:21
(anonymous) @ endpoint.js:19
(anonymous) @ pm2Io.js:89
RETRIEVE_USERS @ actions.js:1115
(anonymous) @ vuex.esm.js:772
l.dispatch @ vuex.esm.js:453
dispatch @ vuex.esm.js:343
(anonymous) @ index.vue:117
created @ index.vue:116
ze @ vue.runtime.esm.js:1854
Qt @ vue.runtime.esm.js:4219
e._init @ vue.runtime.esm.js:5008
a @ vue.runtime.esm.js:5154
(anonymous) @ vue.runtime.esm.js:3283
init @ vue.runtime.esm.js:3114
n @ vue.runtime.esm.js:3301
(anonymous) @ vue.runtime.esm.js:5978
d @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6216
x @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6193
x @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6193
x @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6193
x @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6193
x @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6482
e._update @ vue.runtime.esm.js:3948
i @ vue.runtime.esm.js:4066
pn.get @ vue.runtime.esm.js:4479
pn.run @ vue.runtime.esm.js:4554
cn @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
Ke @ vue.runtime.esm.js:1906
Promise.then (async)
Ue @ vue.runtime.esm.js:1933
tt @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
pn.update @ vue.runtime.esm.js:4544
ce.notify @ vue.runtime.esm.js:730
(anonymous) @ vue.runtime.esm.js:882
addItem @ index.js:465
ze @ vue.runtime.esm.js:1854
e.$emit @ vue.runtime.esm.js:3888
n @ index.js:181
DISPLAY_NOTIFICATION @ notifications.js:25
(anonymous) @ vuex.esm.js:772
l.dispatch @ vuex.esm.js:453
dispatch @ vuex.esm.js:343
(anonymous) @ index.js:929
async function (async)
(anonymous) @ index.js:927
p @ vue-router.esm.js:1962
i @ vue-router.esm.js:1736
i @ vue-router.esm.js:1740
pe @ vue-router.esm.js:1744
_e.confirmTransition @ vue-router.esm.js:1991
_e.transitionTo @ vue-router.esm.js:1893
t.push @ vue-router.esm.js:2203
je.push @ vue-router.esm.js:2584
goToBucket @ index.vue:148
click @ index.vue?33b6:128
ze @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
s._wrapper @ vue.runtime.esm.js:6917
Show 36 more frames


still have the error with the monitoring
