### ISSUE TITLE
How to call exec("pm2 start app.js") in php?

### ISSUE THREAD

**Issue by wulandrima1** [Unitech/pm2#4870]
## What's going wrong?
How to call exec("pm2 start app.js") in php?
## Supporting information
because i execute my browser call.php not work.. and show information
Production Process Manager for Node.js apps
  | with a built-in Load Balancer.
  |  
  |  
  | Start and Daemonize any application:
  | $ pm2 start app.js
  |  
  | Load Balance 4 instances of api.js:
  | $ pm2 start api.js -i 4
  |  
  | Monitor in production:
  | $ pm2 monitor
  |  
  | Make pm2 auto-boot at server restart:
  | $ pm2 startup
  |  
  | To go further checkout:
  | http://pm2.io

```
$ pm2 report
```

**Comment by Unitech** [comment]
https://github.com/Unitech/pm2/issues/4863
