### ISSUE TITLE
--max-memory-restart restarting during a node setInterval process

### ISSUE THREAD

**Issue by guirkgumbo** [Unitech/pm2#4880]
## What's going wrong?
I have a cluster running with a max-memory-restart which works well.
But we have this one process that runs in a setInterval that has to wait for a response from an outside source.

If the max-memory has been reached on a thread that has the setInterval running the thread doesn't wait for it to stop and restarts it. Then the setInterval doesn't complete and the rest of function doesn't go on.
## Supporting information
Picture of the setInterval running waiting for a response from an aws server to be done spinning up before it fires the next part of the function.
![image](https://user-images.githubusercontent.com/32440366/96032516-c87e4380-0e2c-11eb-9518-d05afcd1f7e5.png)

```
$ pm2 report
```

**Comment by vijayarun** [comment]
Any workaround for this scenario?

**Comment by guirkgumbo** [comment]
@vijayarun We ended up using a combination of AWS Cloudwatch functions and SNS. With that set up AWS SNS can send a rest request to our backend when the server is turned on/off and we just track that state in the database. Any functions that depend on a remote server check the database to see if the server is on or not. You can also use the AWS SDK to toggle server state.

Definitely better to go that route than have a rogue setInterval running around.
