### ISSUE TITLE
vizion 0.2.13 vulnerability

### ISSUE THREAD

**Issue by CraigSnowden** [Unitech/pm2#4898]
## What's going wrong?

Vulnerability found in the version of vizion being used (v0.2.13), https://snyk.io/vuln/SNYK-JS-VIZION-565230.

I note that vizion was upgraded in pm2 4.3.0 and then downgraded in 4.3.1 due to #4676. It's unclear whether the investigations came to anything. 

Previously reported in #4743.

## How could we reproduce this issue?

See vulnerabilities listed: https://snyk.io/test/npm/pm2/4.5

**Comment by melya** [comment]
@Unitech would you consider to fix this issue or it needs more effort to be fixed ?

**Comment by MaggieFero** [comment]
The previously-patched version pm2 4.3.0 upgraded Vizion to ~2.2.0, but only @2.1.0 is required to avoid the vulnerability...would a patch to that level be considered?

**Comment by brunoargolo** [comment]
Hi @Unitech do you have any more info on what caused  [#4676](https://github.com/Unitech/pm2/issues/4676) ?
I see the current version of VIZION is still 2.2.0,  Are there any plans to upgrade vizion
 


> The previously-patched version pm2 4.3.0 upgraded Vizion to ~2.2.0, but only @2.1.0 is required to avoid the vulnerability...would a patch to that level be considered?

That is  worth a shot.

**Comment by Unitech** [comment]
Hello @brunoargolo, thanks for pointing out the issue that made me choose to downgrade to older vizion. [I have patched vizion](https://github.com/keymetrics/vizion/commit/4d587b439e27b9ff06a5989db0e80099916b78fd) accordingly so I can put vizion 2.2.x again in PM2. Will run some test before shipping this patch on 4.5.3

**Comment by Unitech** [comment]
released on 4.5.4
