### ISSUE TITLE
systeminformation should be updated

### ISSUE THREAD

**Issue by notaphplover** [Unitech/pm2#4935]
## What's going wrong?

`systeminformation` should be updated to solve a [command injection vulnerability](https://github.com/advisories/GHSA-94xh-2fmc-xf5j).

**Comment by paolocattani** [comment]
Still no update about this? it has been over two month

**Comment by Unitech** [comment]
I'm in charge of that PM2 module and you can trust that if they were a real "vulnerability" I would work on it and publish the module asap.

But that module is an optionalDependency and is not used in PM2 mainstream.
If you'd like to remove any kind of false alert from snyk you can use the development branch of PM2:

```
npm install Unitech/pm2#development -g
pm2 update
```

And you know what? By using this version you will even get a nice system information at bottom of each of `pm2 ls`

**Comment by paolocattani** [comment]
@Unitech thanks for details and super fast response :smile:. I didn't want to look rude, I was just surprised :innocent:

**Comment by mashpie** [comment]
Today multiple reports came up with publishing of https://www.npmjs.com/advisories/1628... so:

Even though `syteminformation` is declared an optional dependency that might even not be installed, `snyk test`, `npm audit` and `yarn audit` constantly report that security risk. And those, in turn, blocked QA and CI/CD pipelines from deploying. 

To silence those false positives without switching to development branch we had to add a resolution to the patched version like so:

```json
"resolutions": {
    "pm2/systeminformation": ">=5.3.1"
 }
```

Now yarn and snyk stop complaining even without installing that package. For npm-based projects, one might check with https://www.npmjs.com/package/npm-force-resolutions. Be aware that this might lead to incompatibility issues if you want to use that "optionalDependency".  Referencing (and using) a stable patched version will still be the only fix.

**Comment by laurelgr** [comment]
Had the same problem with the recent report on this vulnerability (systeminformation >=5.3.1 this time).
Different vulnerability from the author's one, but latest answer on the subject was a week ago. Not sure if should ignore like previous or open another issue for update, @Unitech  ?
