### ISSUE TITLE
Blocking requests not running simultaneously on PM2

### ISSUE THREAD

**Issue by vighnesh153** [Unitech/pm2#4947]
## What's going wrong?
Blocking requests not running simultaneously on PM2

## How could we reproduce this issue?
```js
const winston = require("winston");

const logger = winston.createLogger({
  transports: new winston.transports.File({
    filename: "./hello.log",
    format: winston.format.combine(
      winston.format.timestamp({
        format: "YYYY-MM-DD HH:mm:ss",
      }),
      winston.format.json()
    ),
  }),
});

const express = require("express");
const app = express();

app.use("/status", (req, res) => {
  logger.info("/status start");
  res.sendStatus(200);
  logger.info("/status end");
});

app.use("/p", (req, res) => {
  logger.info("/p start");
  let i = 0;
  const max = 10 ** 10;
  while (i < max) {
    i += 1;
  }
  res.send(`${i}`);
  logger.info("/p end");
});

app.listen(3005, () => {
  logger.silly("Serving on port: 3005");
});
```

I am using `winston` for logging and PM2 for clustering using the following command
```shell
$ pm2 start index.js -i 0
```
It has launched 4 instances.

Now, when I visit the routes `/p`, `/p`, `/status` **in order** in **different tabs** with around 1 second delay between (request 1 and request 2) and (request 2 and request 3), I expected to get response for request 1 and request 2 after some time but with around 1 second delay and response for request 3 should come instantly.

Actual: The response for request 3 did come instantly but something weird happened with request 1 and request 2. The request 2 didn't even start until request 1 was completed. Here are logs that I got. You can see the time stamp for the end of request 1 and start of request 2.

```json
{"message":"/p start","level":"info","timestamp":"2020-12-28 09:14:49"}
{"message":"/status start","level":"info","timestamp":"2020-12-28 09:14:53"}
{"message":"/status end","level":"info","timestamp":"2020-12-28 09:14:53"}
{"message":"/p end","level":"info","timestamp":"2020-12-28 09:15:03"}
{"message":"/p start","level":"info","timestamp":"2020-12-28 09:15:03"}
{"message":"/p end","level":"info","timestamp":"2020-12-28 09:15:17"}
```

Why did the request 1 and request 2 not start at the same time (with 1 second delay, of course)? And if they are running synchronously, why did request 3 respond instantly and not wait for request 1 and 2 to complete?

**Comment by climba03003** [comment]
I think it is not a bug and it should be a normal behavior for Express.
Express will treat each route asynchronize so it can handle as much request as possible by a single thread.
All the 3 request is handle immediately when it received. As a result, ```/status``` can be show between the request 1.

It can also result in various of order. For example
```
/p start
/status start
/p start
/p end
/status end
/p end
```

**Comment by vighnesh153** [comment]
This was happening because of the `Keep Alive` header. In the browser, it was using the same connection socket for the request. When I made a request using the Fetch API, the requests were served by different instances.
