### ISSUE TITLE
Bugs in `pm2 monit`

### ISSUE THREAD

**Issue by AurevoirXavier** [Unitech/pm2#4956]
Don't know what actually it is.

But see: https://github.com/alacritty/alacritty/issues/4668

I'd love to provide any log that you need, please told me.

**Comment by Jaakkonen** [comment]
[fx](https://github.com/antonmedv/fx) also shows same error log when exiting
```

Error on alacritty.plab_norm:
"%t;7%;%?%p4%t;5%;%?%p7%t;8%;m"

var v,
 stack = [],
 out = [];
) {out.push(";
7")};
if ((stack.push(v = params[3]),
 v)) {out.push(";
5")};
if ((stack.push(v = params[6]),
 v)) {out.push(";
8")}out.push("m");
return out.join("");

```
So this looks like being a problem in the TUI library.
