### ISSUE TITLE
--cron not seemingly working

### ISSUE THREAD

**Issue by stockholmux** [Unitech/pm2#496]
I can't seem to get pm2's cron to actually restart a process - take this example:

```
kyle@--------------:~/nodeSites/gustavus$ date
Mon Jun  2 08:34:58 EDT 2014
kyle@--------------:~/nodeSites/gustavus$ pm2 start wpServices.node.js -n wpService --cron 36 8 * * * -x
36
PM2 Process launched
┌─────────────┬────┬─────────┬───────┬────────┬──────┬───────────┬────────┬───────────┬────────────────────────────────────────────┐
│ App Name    │ id │ mode    │ PID   │ status │ port │ Restarted │ Uptime │    memory │ err logs                                   │
├─────────────┼────┼─────────┼───────┼────────┼──────┼───────────┼────────┼───────────┼────────────────────────────────────────────┤
│ wpService   │ 17 │ fork    │ 3228  │ online │      │         0 │ 0s     │  4.719 MB │ /home/kyle/.pm2/logs/wpService-err-17.log  │
└─────────────┴────┴─────────┴───────┴────────┴──────┴───────────┴────────┴───────────┴────────────────────────────────────────────┘
kyle@--------------:~/nodeSites/gustavus$ date
Mon Jun  2 08:35:17 EDT 2014
kyle@--------------:~/nodeSites/gustavus$ date
Mon Jun  2 08:36:09 EDT 2014
kyle@--------------:~/nodeSites/gustavus$ pm2 list
┌─────────────┬────┬─────────┬───────┬────────┬──────┬───────────┬────────┬───────────┬────────────────────────────────────────────┐
│ App Name    │ id │ mode    │ PID   │ status │ port │ Restarted │ Uptime │    memory │ err logs                                   │
├─────────────┼────┼─────────┼───────┼────────┼──────┼───────────┼────────┼───────────┼────────────────────────────────────────────┤
│ wpService   │ 17 │ fork    │ 3228  │ online │      │         0 │ 69s    │ 25.773 MB │ /home/kyle/.pm2/logs/wpService-err-17.log  │
└─────────────┴────┴─────────┴───────┴────────┴──────┴───────────┴────────┴───────────┴────────────────────────────────────────────┘
```

(other process were redacted)

Am I doing something wrong or is this an actual bug?

**Comment by naggie** [comment]
Yes cron-like timing is very useful. I currently have 10 processes that I run for local development at work, together with a few maintenance tasks. Having everything in one JSON file is great!

**Comment by michaelBenin** [comment]
Hey, just to add to this, I've noticed that having a config where:

````
{
  "apps": [
    {
      "name": "cron-script",
      "cwd": ".",
      "script": "dist/server/index.js",
      "exec_mode": "fork_mode",
      "min_uptime": 1000,
      "watch": false,
      "merge_logs": true,
      "log_file": "logs/pm2_child.log",
      "error_file": "logs/pm2_error.log",
      "out_file": "logs/pm2_child_out.log",
      "exec_interpreter": "node",
      "env": {
        "NODE_ENV": "production"
      },
      "pmx": false,
      "vizion": false,
      "cron_restart": "*/1 * * * *", // restart every minute (used for testing)
      "autorestart": false // this is the problem here
    }
  ]
}
````

Having autorestart false disables the cron restart. I want to be able to exit the process gracefully after the script runs. My work around is to close all the db connections and sockets after the script runs but do not exit it. I feel like this is an issue with the cron_restart.

**Comment by v29neil** [comment]
@michaelBenin any update on this??
i simply created a bash file  
#!/usr/bin/env bash
echo "test"
exit 0

My config file is this :
 apps:[{
  "name": "test",
  "script": "./backup/test.sh",
  "exec_interpreter": "bash",
  "exec_mode"  : "fork_mode",
  "cron_restart": "* * * * *",
  "autorestart": true
}]

but it doesnt work.

**Comment by michaelBenin** [comment]
What version of pm2? This issue is not new.

**Comment by v29neil** [comment]
pm2 --version
2.3.0

It seems to working with js file.(cluster_mode)

**Comment by vmarchaud** [comment]
Currently cron_restart is only working inside JS process, see https://github.com/Unitech/pm2/issues/2487

**Comment by v29neil** [comment]
but according to https://github.com/Unitech/pm2/blob/master/CHANGELOG.md#0147
It should work. correct me if i am wrong.

**Comment by v29neil** [comment]
I changed my script 
```
echo "test"
keepgoing=1
trap '{ echo "sigint"; keepgoing=0; }' SIGINT

while (( keepgoing )); do
    echo "sleeping"
    sleep 5
done

```
So that it should end gracefully , just for testing purpose. But no luck. Its not working

**Comment by vmarchaud** [comment]
Actually no, the change was that its the process container that ask to pm2 to be killed (see https://github.com/Unitech/pm2/blob/master/lib/ProcessContainerFork.js#L20)

**Comment by shtse8** [comment]
@michaelBenin  Any updates? I have the same problem with `--no-autorestart`. If I don't have this flag, my program will be auto restarted 15 times and then got error. But if I enable this flag, my cron will not restart the program.

**Comment by leodutra** [comment]
Any updates?

Is there a PM2 way to run `cron_restart` with `autorestart: false`?
If yes, is `exec_mode: 'cluster'` required or am I able to run it with `fork`?

Is PM2 cron_restart intended to "ease" deployment configs and "replace" crontab for PM2 apps?

We should promote a task force to reunite drawbacks and superficially documented features... Unitech is losing "mony". PM2 is awesome but these issues causes a lot of trouble.

**Comment by leodutra** [comment]
I built this file and am sharing just to help other devs.
It follows the workaround of @stockholmux 

This will consider you listed your routines as apps with `autorestart: false` inside your ecosystem.
The reason for this is use the same set of `env_*` definitions for the microservice and its routines.

**Run the microservice using the `--only` parameter, probably in your `post-deploy` hook or process file, and remind to configure routines as `autorestart: false`.**

The builder will automatically consider PM2 path from NVM default alias and your project root path.

Just need to edit * * * * *, "PM2_ENVS" AND  "ROUTINES_NAMES" for your expectations.

```sh
#!/bin/sh
# RUN THIS FILE INSIDE YOUR PROJECT ROOT ON THE FINAL ENVIRONMENT HOST

PM2_ENVS=('development' 'staging' 'production')
ROUTINES_NAMES=('pm2-app-a', 'pm2-app-b')

PROJ_DIR="cd $(dirname "$0")/.."
NODE_VERSION=$(cat ~/.nvm/alias/default)
PM2="~/.nvm/versions/node/v$NODE_VERSION/bin/pm2"

for PM2_ENV in "${PM2_ENVS[@]}"
do
    echo "# PM2 ENVIRONMENT=$PM2_ENV"
    for ROUTINE_NAME in "${ROUTINES_NAMES[@]}"
    do
        echo "* * * * * $PM2 '$PROJ_DIR/ecosystem.config.js' --env '$PM2_ENV' --only '$ROUTINE_NAME'"
    done
done
```
