### ISSUE TITLE
Please update axios module to version 0.21.1

### ISSUE THREAD

**Issue by orange1337** [Unitech/pm2#4972]
## What's going wrong?

I have dependabot alert "high severity"
pm2@4.5.1 requires axios@^0.19.0 via @pm2/js-api@0.6.1

## Supporting information

```
$ pm2 report
```

**Comment by SubJunk** [comment]
I see the same alert, please fix

**Comment by SubJunk** [comment]
I get the same alert. This page has details on the vulnerability https://github.com/advisories/GHSA-4w2v-q235-vp99

**Comment by eyedean** [comment]
On the same note, I am getting a package warning on "debug" package, which is at 4.3.0 and should be 4.3.1+:
```
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
```

**Comment by Unitech** [comment]
@orange1337 please update your PM2 install, the @pm2/js-api module has been patched 19 days ago.
https://github.com/keymetrics/pm2-io-js-api/commit/9f824c0e280dbd7c454cd0cf1bc464dbe592c02d

**Comment by SubJunk** [comment]
@Unitech thanks for that. People who are already using pm2 wouldn't get the update because of the line https://github.com/Unitech/pm2/blob/master/package.json#L171 which only defines `~0.6.0`. It might be good to bump the version there to ensure people get the security patch.

**Comment by Unitech** [comment]
4.5.2 published
