### ISSUE TITLE
pm2 deploy typescript with zero downtime

### ISSUE THREAD

**Issue by TimTheToaster** [Unitech/pm2#4974]
I spent about 7 hours working on this yesterday so I figured I'd put this knowledge out there. The only issue here is how difficult this was to do but I wanted to put this out there and figured this was the best place.

**The Problem**

How do you create a typescript project that uses `pm2 deploy production` for "push to deploy" in such a way that it uses `wait_ready` to ensure zero downtime?

**Disclaimer**

As far as "you shouldn't use `ts-node` in production", that's a valid concern to keep in mind but it should also be measured against the needs of the project. I have a project that is very light. I just wanted an easy push-button solution for making changes. Please refer to [this comment](https://github.com/TypeStrong/ts-node/issues/653#issuecomment-410267473) for more information

**The Solution**

Apparently `wait_ready` doesn't work for projects in fork mode. And deploying in cluster mode results in the tsconfig.json file not being respected. Here's my setup:

For one, I have my `.profile` set on my local machine and my production machine to export the appropriate `NODE_ENV`.

`ecosystem.config.js`:

```js
const path = require('path')
const isProd = process.env.NODE_ENV === 'production';
const prodPath = '/home/ubuntu/PROJECT_NAME'

module.exports = {
  apps: [{
    name: 'PROJECT_NAME',
    script: 'src/index.ts',
    env: {
      TS_NODE_PROJECT: isProd ? path.resolve(prodPath, 'source', 'tsconfig.json') : path.resolve(__dirname, 'tsconfig.json'),
    },
    wait_ready: true,
    exec_mode: 'cluster',
    instances: 1,
  }],
  deploy: {
    production: {
      user: '...',
      host: '...',
      ref: '...',
      repo: '...',
      path: prodPath,
      env: {
        "NODE_ENV": "production"
      },
      'post-deploy': [
        'yarn',
        'pm2 reload ecosystem.config.js --env production',
      ].join(' && '),
    }
  }
};
```

Then, in my code, I have `process.send('ready')` executed when it's safe to kill the old process.

In my `package.json`, I have:

```js
  "scripts": {
    "start": "ts-node src/index.ts",
    "dev": "pm2 start --watch --no-daemon",
    "deploy": "git push && pm2 deploy production"
  },
```

This enables me to run `yarn deploy` to both push out code and deploy to production in one move.

I hope this information saves someone 7 hours.

**Comment by shikhartechxle** [comment]
Hey is their anyone else facing the same issue, not sure I have been facing the same recently and it's been nightmare for me.
Any help or direction will be heavily appreciated
