### ISSUE TITLE
Add an option to set a respawn delay between auto-restarts

### ISSUE THREAD

**Issue by ravi** [Unitech/PM2#498]
It would be nice to have an option to set a respawn delay between auto-restarts to avoid a fork bomb. This can also be used as a way to run a periodic process with some interval between runs (not possible through cron which uses fixed time points to launch a process).

CORRECTION: pm2 already has code to avoid fork bombs, but the ability to specify a delay would still be quite useful to provide a gap between runs for processes that execute iteratively.

**Comment by mlegenhausen** [comment]
+1

**Comment by parisholley** [comment]
+1 server can go high cpu, and become unresponsive if all the processes endlessly restart. would be great to put a delay before each try

**Comment by jshkurti** [comment]
Alright, I'm going to implement this, how about `PM2_RESTART_DELAY` as env variable ?

**Comment by rbarkas** [comment]
I think it would be better if it were implemented on a task by task basis, i.e. as an option in the JSON app declarations and as an argument to command line 'pm2 start'.

Different programs may (and in my case will) have different restart delay requirements.

If you think it best there could be a global PM2_RESTART_DELAY env var that could be overridden by the JSON declaration or individual start command

**Comment by Gank** [comment]
+1

**Comment by Ephigenia** [comment]
+1

**Comment by ravi** [comment]
FWIW, here are the changes I made to an older version of PM2 to accomplish the above:

```
--- a/node/lib/node_modules/pm2/bin/pm2
+++ b/node/lib/node_modules/pm2/bin/pm2
@@ -34,6 +34,7 @@ commander.version(pkg.version)
   .option('--interpreter <interpreter>', 'the interpreter pm2 should use for executing app (bash, python...)')
   .option('--no-daemon', "run pm2 daemon in the foreground if it doesn't exist already")
   .option('--merge-logs', 'merge logs from different instances but keep error and out separated')
+  .option('--respawn-delay <seconds>', 'delay between process respawns')
   .option('--watch', 'watch application folder for changes')
   .option('--node-args <node_args>', "space delimited arguments to pass to node in cluster mode - e.g. --node-
       function(val) {
diff --git a/node/lib/node_modules/pm2/lib/CLI.js b/node/lib/node_modules/pm2/lib/CLI.js
index 0ccfd99..7aa5c4a 100644
--- a/node/lib/node_modules/pm2/lib/CLI.js
+++ b/node/lib/node_modules/pm2/lib/CLI.js
@@ -62,6 +62,9 @@ CLI.startFile = function(script) {
   else
     appConf['exec_interpreter']    = 'node';

+   if( commander.respawnDelay )
+       appConf['respawn_delay'] = commander.respawnDelay;
+
   if (commander.startOneTime)
     appConf['one_launch_only'] = cst.ONE_LAUNCH_STATUS;

diff --git a/node/lib/node_modules/pm2/lib/God.js b/node/lib/node_modules/pm2/lib/God.js
index 6b5ad5e..cf18e20 100644
--- a/node/lib/node_modules/pm2/lib/God.js
+++ b/node/lib/node_modules/pm2/lib/God.js
@@ -115,7 +115,12 @@ function handleExit(clu, exit_code) {
   if (!stopping)
     clu.pm2_env.restart_time = clu.pm2_env.restart_time + 1;

-  if (!stopping && !overlimit) God.executeApp(clu.pm2_env);
+  if (!stopping && !overlimit)
+  {
+      var delay = clu.pm2_env.respawn_delay || 0;
+      console.log("Respawning process in %d seconds...", delay);
+      setTimeout(God.executeApp.bind(God), delay*1000, clu.pm2_env);
+  }
 };
```

If, like me, you plan to use the respond delay as a poor man's cron, you will still need to deal with the limit set by `max_restarts` if your app exits in less than `min_uptime`.

**Comment by rangercyh** [comment]
+1

**Comment by jshkurti** [comment]
Here we go.
`pm2 start app.js --restart-delay 4000` (delay is in milliseconds)
or in JSON declaration:
```json
  "restart_delay" : "4000"
```

Avaible on #development for now, soon to be published :)

https://github.com/Unitech/PM2/commit/12261c6b4ae17e69bc0721c9a68167731b26ba4b

**Comment by michahell** [comment]
Is this option implemented?

**Comment by michahell** [comment]
Im super confused. What is being used?
```javascript
"restart_delay" : "4000"
```
or, as documented in http://pm2.keymetrics.io/docs/usage/watch-and-restart/ and https://github.com/paulmillr/chokidar#api:
```javascript
awaitWriteFinish: {
   stabilityThreshold: 2000,
   pollInterval: 100
}
```
in which case an application.JSON file could look like this:
```javascript
[
  {
    "name": "servername",
    "script": "./someserver.js",
    "env": {
      "NODE_ENV": "test"
    },
    "watch": "./somedir",
    "watch_options": {
      "awaitWriteFinish": {
        "stabilityThreshold": 10000,
        "pollInterval": 1000
      },
    }
  },
...
]
```
What is being used when and where?

**Comment by soyuka** [comment]
@michahell What exactly are you trying to do?
I don't think that `--restart-delay` would be effective through the watch.

**Comment by michahell** [comment]
I would like to watch a single file, if it changes (and is done writing, hence the awaitWriteFinish delay), the server should restart. This has worked before (a few months) but we had not updated pm2 in a while. Recently, we did, to 0.15.7, but we updated from a version from the stoneage, so I'm not sure from which version onwards this behaviour changed. 
Right now it's unclear what option is active or actually works. I did find [this issue](https://github.com/Unitech/pm2/issues/1729) so it might be related to this. I will try to update pm2 next monday and see if that will help.

**Comment by Altiano** [comment]
Any update about this feature?

**Comment by taskinosman** [comment]
would be very useful, restarting too fast causes our mysql servers being full very fast. Imagine there is a bug at start and pm2 restarts the app every seconds. This is big issue for most of people i suppose

**Comment by chienjchienj** [comment]
still looking for this feature...
