### ISSUE TITLE
Volnurability in Dependency: "Debug" package should be >= 4.3.1

### ISSUE THREAD

**Issue by eyedean** [Unitech/pm2#4986]
## What's going wrong?
I get:
```
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
```
as [you are on debug 4.3.0](https://github.com/Unitech/pm2/blob/master/package.json#L181).

## Supporting information

I reported this in https://github.com/Unitech/pm2/issues/4972#issuecomment-766301542 to be piggy-backed in the pm2's `4.5.2`, but it seems like my comment was missed.

**Comment by Unitech** [comment]
Fixed via latest pm2

```bash
npm install pm2@latest -g
pm2 update
```
