### ISSUE TITLE
PM2 logo

### ISSUE THREAD

**Issue by AlexZeDim** [Unitech/pm2#4994]
## Requiers clarification. 

It's not an issue report, but a question. I'd like to add the PM2 to the [simple-icons](https://simpleicons.org/). But the real problem is various logos of the module on Github, npmjs, and the website. @Ulflander, which version of the logo should be chosen and which one will be correct for representing PM2? 

Is that a hamburger-style like, or the correct version will be the logo from GitHub documentation from the current repo?

**Comment by Unitech** [comment]
Hi, the one in the doc of the current repo is the correct one
