### ISSUE TITLE
Pm2 version 4.5.5 npm WARN deprecated debug@4.1.1: Debug

### ISSUE THREAD

**Issue by JigneshR** [Unitech/pm2#5011]
Getting WARN while update pm2 version.
------------------------------------------------------------------------------------------------------------------------

[root@centos8 ~]# npm install -g pm2
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)

changed 201 packages, and audited 202 packages in 11s

9 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
------------------------------------------------------------------------------------------------------------------------

How to fixed that WARN?

**Comment by redevill** [comment]
Something wrong with the publish of the latest version?

The code in this repo, shows clearly that the debug module is at V4.3.1
However, when installing PM2@4.5.5, The install is still giving the deprecation warning.
npm list debug@4.1.1 still shows PM2 responsible as having the older version dependency.

**Comment by brandonparrottFR** [comment]
```yarn why v1.22.4
warning package.json: No license field
[1/4] Why do we have the module "debug"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "debug@4.3.1"
info Has been hoisted to "debug"
info Reasons this module exists
   - Hoisted from "pm2#debug"
   - Hoisted from "pm2#@pm2#pm2-version-check#debug"
   - Hoisted from "pm2#pm2-axon#debug"
   - Hoisted from "pm2#@pm2#js-api#debug"
   - Hoisted from "pm2#@pm2#agent#proxy-agent#debug"
   - Hoisted from "pm2#@pm2#io#require-in-the-middle#debug"
   - Hoisted from "pm2#@pm2#agent#proxy-agent#pac-proxy-agent#debug"
info Disk size without dependencies: "88KB"
info Disk size with unique dependencies: "104KB"
info Disk size with transitive dependencies: "104KB"
info Number of shared dependencies: 1
=> Found "@pm2/io#debug@4.1.1"
info This module exists because "pm2#@pm2#io" depends on it.
info Disk size without dependencies: "112KB"
info Disk size with unique dependencies: "128KB"
info Disk size with transitive dependencies: "128KB"
info Number of shared dependencies: 1
=> Found "pm2-axon-rpc#debug@3.2.7"
info This module exists because "pm2#pm2-axon-rpc" depends on it.
info Disk size without dependencies: "84KB"
info Disk size with unique dependencies: "100KB"
info Disk size with transitive dependencies: "100KB"
info Number of shared dependencies: 1
=> Found "needle#debug@3.2.7"
info This module exists because "pm2#needle" depends on it.
info Disk size without dependencies: "84KB"
info Disk size with unique dependencies: "100KB"
info Disk size with transitive dependencies: "100KB"
info Number of shared dependencies: 1
=> Found "@pm2/agent#debug@4.1.1"
info This module exists because "pm2#@pm2#agent" depends on it.
info Disk size without dependencies: "112KB"
info Disk size with unique dependencies: "128KB"
info Disk size with transitive dependencies: "128KB"
info Number of shared dependencies: 1
=> Found "@pm2/agent#pm2-axon-rpc#debug@3.2.7"
info This module exists because "pm2#@pm2#agent#pm2-axon-rpc" depends on it.
info Disk size without dependencies: "84KB"
info Disk size with unique dependencies: "100KB"
info Disk size with transitive dependencies: "100KB"
info Number of shared dependencies: 1
=> Found "@pm2/agent#pm2-axon#debug@3.2.7"
info This module exists because "pm2#@pm2#agent#pm2-axon" depends on it.
info Disk size without dependencies: "84KB"
info Disk size with unique dependencies: "100KB"
info Disk size with transitive dependencies: "100KB"
info Number of shared dependencies: 1
=> Found "@pm2/agent-node#debug@3.2.7"
info This module exists because "pm2#@pm2#io#@pm2#agent-node" depends on it.
info Disk size without dependencies: "84KB"
info Disk size with unique dependencies: "100KB"
info Disk size with transitive dependencies: "100KB"
info Number of shared dependencies: 1
=> Found "http-proxy-agent#debug@3.1.0"
info This module exists because "pm2#@pm2#agent#proxy-agent#http-proxy-agent" depends on it.
info Disk size without dependencies: "104KB"
info Disk size with unique dependencies: "120KB"
info Disk size with transitive dependencies: "120KB"
info Number of shared dependencies: 1
=> Found "https-proxy-agent#debug@3.2.7"
info This module exists because "pm2#@pm2#agent#proxy-agent#https-proxy-agent" depends on it.
info Disk size without dependencies: "84KB"
info Disk size with unique dependencies: "100KB"
info Disk size with transitive dependencies: "100KB"
info Number of shared dependencies: 1
=> Found "get-uri#debug@2.6.9"
info This module exists because "pm2#@pm2#agent#proxy-agent#pac-proxy-agent#get-uri" depends on it.
info Disk size without dependencies: "108KB"
info Disk size with unique dependencies: "124KB"
info Disk size with transitive dependencies: "124KB"
info Number of shared dependencies: 1
Done in 0.68s.```

**Comment by JigneshR** [comment]
@brandonparrottFR Can you provide more details? 
Issue has been fixed?
Provide fixes/installation details.

**Comment by brandonparrottFR** [comment]
Yes, sorry for not giving details in my first comment. 

When installing pm2@4.5.5, I was receiving the following warnings:

```
warning pm2 > @pm2/agent > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos reg
ression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/
visionmedia/debug/issues/797)                                                                                    
warning pm2 > @pm2/io > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regres
sion when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/vis
ionmedia/debug/issues/797) 
```

`@pm2/agent` and `@pm2/io` still need to upgrade debug in their package.json. 

To workaround this issue, I am currently setting the following in the global `package.json` and installing:

```
{
  "dependencies": {
    "pm2": "^4.5.5"
  },
  "resolutions": {
    "pm2/**/debug": "^4.3.1"
  }
}
```

**Comment by redevill** [comment]
@brandonparrottFR - Is that part of native package.json ("resolutions")... or are you using https://www.npmjs.com/package/npm-force-resolutions?

**Comment by redevill** [comment]
The situation appears to have changed (Possibly due to my npm upgrade to the latest? V7.7.6)
npm audit now shows (I already had installed PM2 V4.5.5 ):

# npm audit report

netmask  <2.0.1
Severity: high
netmask npm package vulnerable to octal input data - https://npmjs.com/advisories/1658
fix available via `npm audit fix --force`
Will install pm2@3.5.2, which is a breaking change
node_modules/netmask
  pac-resolver  *
  Depends on vulnerable versions of netmask
  node_modules/pac-resolver
    pac-proxy-agent  *
    Depends on vulnerable versions of pac-resolver
    node_modules/pac-proxy-agent
      proxy-agent  >=1.1.0
      Depends on vulnerable versions of pac-proxy-agent
      node_modules/proxy-agent
        @pm2/agent  >=0.5.25
        Depends on vulnerable versions of proxy-agent
        node_modules/@pm2/agent
          pm2  >=3.3.0
          Depends on vulnerable versions of @pm2/agent
          Depends on vulnerable versions of @pm2/io
          node_modules/pm2
        @pm2/agent-node  >=1.0.8
        Depends on vulnerable versions of proxy-agent
        node_modules/@pm2/agent-node
          @pm2/io  >=2.4.6
          Depends on vulnerable versions of @pm2/agent-node
          node_modules/@pm2/io

8 high severity vulnerabilities

# Now
If you follow the npm directions (which states that it will install a LOWER version of 3.5.2) 
using the command npm audit fix --force
The output then indicates that you have similar issues, but that the same command will now install 4.5.5
You can bounce back and forth till something goes numb...

**Comment by Unitech** [comment]
Fixed via latest pm2

```bash
npm install pm2@latest -g
pm2 update
```
