### ISSUE TITLE
Can I restore my code through pm2~

### ISSUE THREAD

**Issue by jamninetyfive** [Unitech/pm2#5015]
## What's going wrong?
I used the rm -rf command to delete my project, but I regret it.But PM2 is running and still working.Just really want to know
## How could we reproduce this issue?
do not！
## Supporting information

```
$ pm2 report
```

**Comment by rowisahub** [comment]
No, pm2 runs the program you tell it to run. it doesn't create or remove files. 

For example if my code required everything with out ever deleting the cache for it, you can still run your program fine. But if your code deletes a require cache, like to get a updated json file, then it would give you an error saying it's not there.

Sorry man, you have to make a new program. You can probably find a trash bin for Linux though if your worried it might happen again.
