### ISSUE TITLE
High Severity Vulnerability in Netmask

### ISSUE THREAD

**Issue by ckarsan** [Unitech/pm2#5036]
## What's going wrong?
High severity vulnerability reported with "netmask"  used in pm2

## How could we reproduce this issue?
npm audit

Seems its patched in netmask v2.0.1 so updating this should fix it

**Comment by davegrix** [comment]
For a short term solution, I have replaced the package in package-lock.json with ` "netmask": {
      "version": "2.0.1",
      "resolved": "https://registry.npmjs.org/netmask/-/netmask-2.0.1.tgz",
      "integrity": "sha512-gB8eG6ubxz67c7O2gaGiyWdRUIbH61q7anjgueDqCC9kvIs/b4CTtCMaQKeJbv1/Y7FT19I4zKwYmjnjInRQsg=="
    },`

I haven't had a chance to test this fully yet, but PM2 appears to operate normally with it.

**Comment by Unitech** [comment]
fixed via 4.5.6

```bash
npm install pm2@latest -g
pm2 update
```
