### ISSUE TITLE
Hide pm2-sysmonit errors in console

### ISSUE THREAD

**Issue by wolf-yuan-6115** [Unitech/pm2#5099]
## What's going wrong?

Pm2 will display pm2-sysmonit error in console when starting process using pm2-runtime
## How could we reproduce this issue?

Start a process in repl.it or heroku, start a process using pm2-runtime with latest pm2

**Comment by Unitech** [comment]
With pm2@5.1.0, pm2-sysmonit is not set to run by default.

```bash
npm install pm2@latest -g
pm2 update
```
