### ISSUE TITLE
Can't remove or disable pm2-sysmonit

### ISSUE THREAD

**Issue by supernovaplus** [Unitech/pm2#5101]
I'm using `pm2 v5.0.4` with `node v14.17.0` on `Ubuntu 20.04.2 LTS`

I cannot remove or disable the pm2-sysmonit module

uninstall command says unkown module
```
pm2 uninstall pm2-sysmonit
[PM2][Module] Uninstalling module pm2-sysmonit
[PM2][Module][ERROR] Unknown module
```
setting the `pm2 set pm2:sysmonit false` does nothing, even after reboot the process still working

```pm2 stop 0``` stops the process but then it starts again on reboot, same with ```pm2 delete 0```.

**Comment by Unitech** [comment]
With pm2@5.1.0, pm2-sysmonit is not set to run by default.

```bash
npm install pm2@latest -g
pm2 update
```
