### ISSUE TITLE
Tips: How to deploy on PM2 with yarn berry

### ISSUE THREAD

**Issue by HADMARINE** [Unitech/pm2#5113]
## What's going wrong?
I couldn't deploy successfully with yarn PnP mode, but i've figured out.

You must add 
```javascript
require("./<root-to-pnp.js>/.pnp.js").setup();
```
on the top of the root file, below "use strict"; if exists. (maybe index.js I guess)

Then you can deploy pm2 without using yarn interpreter that is hard to setup.

Example Code (built with babel.js)
```javascript
"use strict";

require('../.pnp.js').setup();

var _App = require("./App");

(0, _App.Root)();
```

**Comment by merceyz** [comment]
The docs for Yarn PnP documents the different ways of initializing it https://yarnpkg.com/features/pnp/#initializing-pnp

```js
require('./.pnp.cjs').setup();
```
or
```sh
node -r ./.pnp.js ./server.js
NODE_OPTIONS="--require $(pwd)/.pnp.js" node ./server.js
```

**Comment by HADMARINE** [comment]
Oh, I didn't see that. Thanks.
I'll close this issue.
