### ISSUE TITLE
socket port is always same

### ISSUE THREAD

**Issue by xml4cn** [Unitech/pm2#513]
pm2:0.7.8  
node:v0.10.26  
linux：Linux version 2.6.32-431.11.2.el6.x86_64   centos
/etc/init.d/  file:
start() {
    echo "Starting $NAME"
    $NODE $PM2 start $APP
}

I use restify start a web server .   when i create a udp socket, it always to bind the same port.  Why is not a random port??
code:

```
var dgram = require("dgram");

function createSocket() {
    var server = dgram.createSocket("udp4");

    server.on("message", function(msg, rinfo) {
        console.log("server got: " + msg + " from " +
            rinfo.address + ":" + rinfo.port);
    });

    server.on("listening", function() {
        var address = server.address();
        console.log("server listening " +
            address.address + ":" + address.port);
    });

    server.bind();
}

createSocket();
setTimeout(function() {
    createSocket();
}, 5000);
```

0.0.0.0:45068
0.0.0.0:45068

**Comment by tamaker** [comment]
@soyuka I'm looking for ways to  start a group of child processes with PM2 that each  use specific, pre-defined ports (not random ports).   Will pm2 allow me to do this?   Also I want to NOT have the master process load balance traffic, and need each child process to only be available to a unique / specific set of  users who will use the assigned port.  Is this possible with pm2 and are there any examples that show this?  Thanks!

**Comment by soyuka** [comment]
I think I've answered you on stackoverflow, don't hesitate to write me an email if you want to talk about this more deeply.

**Comment by tamaker** [comment]
Thanks for replying!   I did take a look at the stackoverflow response and have been experimenting with Pm2 for almost 24 hours straight and its AWESOME!
 
Question:  I think, based on your reply, for my needs I will run my script in fork mode and spawn a process fork, each with a unique port.  I want to use a configuration file to manage and run the process from...
similar to this example I see online...  but how in my 'script' (the script that gets called  / run) do I access the "PORT" thats defined in the configuration file (i.e. - in my ./lib/index.js - I have app.listen((portNum), () => {...   how do I associate the variable portNum with whats defined in the configuration file as "PORT"?
 
{
 "apps": [
 {
 "exec_mode": "fork_mode",
 "script": "./lib/index.js",
 "name": "proj-0",
 "node_args": [ "--harmony" ],
 "env": {
 "PORT": 4001,
 "NODE_ENV": "production"
 },
 "error_file": "/var/www/logs/proj-0.err.log",
 "out_file": "/var/www/logs/proj-0.out.log"
 },
 {
 "exec_mode": "fork_mode",
 "script": "./lib/index.js",
 "name": "proj-1",
 "node_args": [ "--harmony" ],
 "env": {
 "PORT": 4002,
 "NODE_ENV": "production"
 },
 "error_file": "/var/www/logs/proj-1.err.log",
 "out_file": "/var/www/logs/proj-1.out.log"
 }
 ]
}
 
 
--------- Original Message --------- Subject: Re: [Unitech/pm2] socket port is always same (#513)

**Comment by soyuka** [comment]
`process.env.PORT`?
