### ISSUE TITLE
`pm2` not working on node v-16.6.1

### ISSUE THREAD

**Issue by muhitrhn** [Unitech/pm2#5146]
I installed pm2 using this command `npm i pm2`. But when i run `pm2 start .`, it says `pm2 is not a recognized command`. I have also tried rebooting the instance but same issue.

**Comment by dacuna-ic** [comment]
to execute it like that you need to install the package globally (e.g. `npm i -g pm2`), you should be otherwise be able to run with [npx](https://docs.npmjs.com/cli/v7/commands/npx) `npx pm2 start . .`
