### ISSUE TITLE
critique on the pace of maintenance

### ISSUE THREAD

**Issue by tjwebb** [Unitech/pm2#515]
@Unitech I think you've got a great idea here, but I think the number of people using this module and filing issues is out-running the pace of maintenance and improvement. I use `pm2` for one of my projects but am now running into many of the same issues that others have filed, and it's difficult to have faith in the project when so many important issues are not being addressed.

I'm a user at a crossroads: `pm2` is extremely useful, but we are now considering switching to another tool because bugs are introduced at roughly the same rate they are fixed, and we're having to spend a lot of effort working around all the issues that are outstanding. All projects will have issues that cause inconvenience, but many of the outstanding issues here are serious, especially considering that the primary use for `pm2` is to monitor and maintain live systems.

I'd like to see more maintainers brought into this project, since maybe the project is now more popular than you alone can manage. I congratulate you on your success, but in order for us to rely on `pm2` in the long term, I really would like to see more velocity in resolving some of these issues, so I propose that you choose one or two folks from the existing community of users and/or contributors to add as collaborators to this project. 

Perhaps in the comments here, people can nominate themselves or others to take on this responsibility. Let me know what you think. Thanks, and great work.

**Comment by Unitech** [comment]
@tjwebb I hope you've seen some progress since you wrote your message :) We are now a team of multiple developers and we're proud to maintain PM2 open source and our premium versions. Hope you continued to use PM2!
