### ISSUE TITLE
Cannot find the process id when restarting node process

### ISSUE THREAD

**Issue by JaivalBhup** [Unitech/pm2#5170]
## **PM2** Restart a node process id ISSUE?
I have some services running on pm2. I can use pm2 start to add the service to the pm2 but when I do pm2 restart it says process id not found. All I can do is pm2 update but it restarts all the services and that not a reliable option for me. Any help is appreciated.

**Comment by Ionys320** [comment]
Hi, are you using cluster mode?

**Comment by JaivalBhup** [comment]
No I got it. 
Thank you.
