### ISSUE TITLE
Can I set --interpreter in cluster mode?

### ISSUE THREAD

**Issue by tjwebb** [Unitech/pm2#519]
I have multiple versions of node installed (managed using https://github.com/visionmedia/n) and I want to use the `interpreter` setting to set different node versions for different processes. But this only seems to have effect in `fork` mode. Am I possibly doing something wrong?

**Comment by Benew** [comment]
+1, @Unitech the restriction of fork mode is there because cluster mode is a node-only feature but if we need different clusters with different versions of node (nvm) this should work right?
