### ISSUE TITLE
`pm2 startup` does not work on macOS – "Failure when trying to write startup script"

### ISSUE THREAD

**Issue by dislick** [Unitech/pm2#5193]
Running `pm2 startup` and then running the generated command results in the following error.

```
[PM2][ERROR] Failure when trying to write startup script
ENOENT: no such file or directory, open '/Users/signum/Library/LaunchAgents/pm2.signum.plist'
```

The issue is that the folder `~/Library/LaunchAgents` does not exist on a fresh macOS install (only verified with the M1 Mac Mini).

## Workaround

Manually create the folder first:

```
mkdir -p ~/Library/LaunchAgents
```

Then run `pm2 startup` as you usually would.

**Comment by fliodhais** [comment]
just wondering if this should be marked as resolved? It appears like the PR merged into dev branch awhile ago
