### ISSUE TITLE
Pm2 not start NodeJS (NextJS) app on Windows Server

### ISSUE THREAD

**Issue by moisesmdpf** [Unitech/pm2#5221]
## What's going wrong?
pm2 does not start a NextJs app using pm2 start, on windows server.

## How could we reproduce this issue?
To reproduce the error, the steps are as follows.

1. Create a nextjs app using: npx create-next-app@latest
2. Run `npm run build`
3. Create the configuration file `ecosystem.config.js`
4. Run `pm2 start`

## Supporting information
In my particular case I am using pm2 to run a nextjs application. I've tested this same config on my local maching running Ubuntu 20.04.3 LTS and everything works perfect.

Additionally, this is the `ecosystem.config.js` file that I am using in the application.

```js
module.exports = {
  apps : [{
    name   : "sistematizacion-movil-site",
    script : "npm",
    args: "run start",
    error_file: './logs/service_gateway.err',
    log_date_format: 'YYYY-MM-DD HH:mm:ss SSS',
  }]
}
```

Also, I include the error report generated in the log: `service_gateway.err`

```
2021-11-08 13:27:05 757: C:\PROGRAM FILES\NODEJS\NPM.CMD:1
2021-11-08 13:27:05 757: :: Created by npm, please don't edit manually.
2021-11-08 13:27:05 757: ^
2021-11-08 13:27:05 757: 
2021-11-08 13:27:05 757: SyntaxError: Unexpected token ':'
2021-11-08 13:27:05 757:     at Object.compileFunction (node:vm:352:18)
2021-11-08 13:27:05 757:     at wrapSafe (node:internal/modules/cjs/loader:1031:15)
2021-11-08 13:27:05 757:     at Module._compile (node:internal/modules/cjs/loader:1065:27)
2021-11-08 13:27:05 757:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
2021-11-08 13:27:05 757:     at Module.load (node:internal/modules/cjs/loader:981:32)
2021-11-08 13:27:05 758:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2021-11-08 13:27:05 758:     at Object.<anonymous> (C:\Users\vm-002\AppData\Roaming\npm\node_modules\pm2\lib\ProcessContainerFork.js:33:23)
2021-11-08 13:27:05 758:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
2021-11-08 13:27:05 758:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
2021-11-08 13:27:05 758:     at Module.load (node:internal/modules/cjs/loader:981:32)
```

## PM2 Report

```
--- PM2 report ----------------------------------------------------------------
Date                 : Mon Nov 08 2021 15:27:30 GMT+0000 (Coordinated Universal Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 5.1.2
node version         : 16.13.0
node path            : not found
argv                 : C:\Program Files (x86)\nodejs\node.exe,C:\Users\vm-002\AppData\Roaming\npm\node_modules\pm2\lib\Daemon.js
argv0                : node
user                 : undefined
uid                  : N/A
gid                  : N/A
uptime               : 4923min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 5.1.2
node version         : 16.13.0
node path            : not found
argv                 : C:\Program Files\nodejs\node.exe,C:\Users\vm-002\AppData\Roaming\npm\node_modules\pm2\bin\pm2,report
argv0                : C:\Program Files\nodejs\node.exe
user                 : vm-002
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : win32
type                 : Windows_NT
cpus                 : Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz
cpus nb              : 1
freemem              : 267542528
totalmem             : 2147012608
home                 : C:\Users\vm-002
===============================================================================
--- PM2 list -----------------------------------------------
┌─────┬───────────────────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name                          │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼───────────────────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ sistematizacion-movil-site    │ default     │ N/A     │ fork    │ 0        │ 0      │ 30   │ errored   │ 0%       │ 0b       │ vm-002   │ disabled │
└─────┴───────────────────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
C:\Users\vm-002\.pm2\pm2.log last 20 lines:
PM2        | 2021-11-08T13:27:03: PM2 log: App [sistematizacion-movil-site:0] exited with code [1] via signal [SIGINT]
PM2        | 2021-11-08T13:27:03: PM2 log: App [sistematizacion-movil-site:0] starting in -fork mode-
PM2        | 2021-11-08T13:27:03: PM2 log: App [sistematizacion-movil-site:0] online
PM2        | 2021-11-08T13:27:03: PM2 log: App [sistematizacion-movil-site:0] exited with code [1] via signal [SIGINT]
PM2        | 2021-11-08T13:27:03: PM2 log: App [sistematizacion-movil-site:0] starting in -fork mode-
PM2        | 2021-11-08T13:27:03: PM2 log: App [sistematizacion-movil-site:0] online
PM2        | 2021-11-08T13:27:03: PM2 log: App [sistematizacion-movil-site:0] exited with code [1] via signal [SIGINT]
PM2        | 2021-11-08T13:27:03: PM2 log: App [sistematizacion-movil-site:0] starting in -fork mode-
PM2        | 2021-11-08T13:27:03: PM2 log: App [sistematizacion-movil-site:0] online
PM2        | 2021-11-08T13:27:03: PM2 log: App [sistematizacion-movil-site:0] exited with code [1] via signal [SIGINT]
PM2        | 2021-11-08T13:27:03: PM2 log: App [sistematizacion-movil-site:0] starting in -fork mode-
PM2        | 2021-11-08T13:27:03: PM2 log: App [sistematizacion-movil-site:0] online
PM2        | 2021-11-08T13:27:04: PM2 log: App [sistematizacion-movil-site:0] exited with code [1] via signal [SIGINT]
PM2        | 2021-11-08T13:27:05: PM2 log: App [sistematizacion-movil-site:0] starting in -fork mode-
PM2        | 2021-11-08T13:27:05: PM2 log: App [sistematizacion-movil-site:0] online
PM2        | 2021-11-08T13:27:05: PM2 log: App [sistematizacion-movil-site:0] exited with code [1] via signal [SIGINT]
PM2        | 2021-11-08T13:27:05: PM2 log: App [sistematizacion-movil-site:0] starting in -fork mode-
PM2        | 2021-11-08T13:27:05: PM2 log: App [sistematizacion-movil-site:0] online
PM2        | 2021-11-08T13:27:05: PM2 log: App [sistematizacion-movil-site:0] exited with code [1] via signal [SIGINT]
PM2        | 2021-11-08T13:27:05: PM2 log: Script C:\PROGRAM FILES\NODEJS\NPM.CMD had too many unstable restarts (16). Stopped. "errored"

```

**Comment by moisesmdpf** [comment]
## UPDATE


Investigating a little deeper, I have realized that for Windows 10 the same error also occurred. But it is a problem that is related to pm2 and the way it seeks to execute the `npm` script

This error is related to another one previously placed within github. This is the link to the solution of this problem: https://github.com/Unitech/pm2/issues/3657

In summary, the problem lies in how pm2 locates the `npm` script in Windows. For linux based systems the npm script is a bash file. Which is executable for the nodejs runtime. On the other hand, for Windows systems this script is created as a cmd file, being only executable for the Windows command interpreter. 

However, pm2 for some reason tends to only look for the bash file. Which generates error in operating systems such as Windows.

The solution is to replace in the `ecosystem.config.js` file in the` script` input the value for the path to the `npm-cli.js` file, this way we will execute the `npm` CLI directly. 

An detailed explanaition is described in the link above.

**Comment by msalsbery** [comment]
> ## UPDATE
> Investigating a little deeper, I have realized that for Windows 10 the same error also occurred. But it is a problem that is related to pm2 and the way it seeks to execute the `npm` script
> 
> This error is related to another one previously placed within github. This is the link to the solution of this problem: #3657
> 
> In summary, the problem is related in how pm2 locates the `npm` script in Windows. For linux based systems the npm script is a bash file. On the other hand, for Windows systems this script is created as a cmd file, being only executable for the Windows command interpreter.
> 
> However, pm2 for some reason tends to only look for the bash file. Which generates error in operating systems such as Windows.
> 
> The solution consists of modifying the value of the `script` entry and placing there, the path to the` npm-cli.js` file. Normally the path to this file is this:
> 
> ```
> C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
> ```
> 
> So our final ecosystem.config file, will look something like this:
> 
> ```js
> module.exports = {
>   apps : [{
>     name   : "my-next-js-app",
>     script : "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js",
>     args: "run start",
>     error_file: './logs/service_gateway.err',
>     log_date_format: 'YYYY-MM-DD HH:mm:ss SSS',
>   }]
> }
> ```
> 
> An detailed explanaition is described in the link above.

Just want to add, this is still an issue, and this is still a valid solution!

**Comment by msalsbery** [comment]
> @macmoi @msalsbery I use fnm. I should be able to find this in the nodejs directory right ? I'm asking because I could only find npm and npm.cmd, at work, but I think I was looking in the wrong place. The purpose of my message is to garner if the situation is the same today.

I don't know where fnm puts the executables, sorry.

For what it's worth, looking on Windows 10, I find it at 

`C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js`

and at

`C:\Users\myusername\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js`

If you use `npm install -g npm` to update npm to latest version, it'll be at the second location (where the global node_modules are in a default installation)
