### ISSUE TITLE
Can't use instances  exec_mode": "cluster" at esmodule ?

### ISSUE THREAD

**Issue by cx690** [Unitech/pm2#5236]
## What's going wrong?

I have config as this: config.json
```js
{
    "apps": [
        {
            "name": "app",
            "script": "./dist/app.js",
            "instances": "max",
            "exec_mode": "cluster",
            "autorestart": true,
            "node_args": "--experimental-specifier-resolution=node",
            "env": {
                "NODE_ENV": "production"
            }
        }
    ]
}
```
package.json: type:module.
The ./dist/app.js is esModule.

##Environment
- Windows 10
- NodeJS: v14.17.0
- NPM: v6.14.13
- pm2: v5.1.2

## How could we reproduce this issue?
`pm2 start config.json`

## error logs
//app-error-0.log
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'e:'
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:782:11)
    at Loader.resolve (internal/modules/esm/loader.js:88:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:241:28)
    at Loader.import (internal/modules/esm/loader.js:176:28)
    at importModuleDynamically (internal/modules/cjs/loader.js:1011:27)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\lib\ProcessContainer.js:301:26
    at wrapper (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\async\internal\once.js:12:16)
    at next (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\async\waterfall.js:96:20)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\pm2\node_modules\async\internal\onlyOnce.js:12:16

## Supporting information

C:\Users\Administrator\.pm2\pm2.log last 20 lines:
PM2        | 2021-12-02T16:25:04: PM2 log: Stopping app:app id:_old_4
PM2        | 2021-12-02T16:25:04: PM2 log: Stopping app:app id:_old_5
PM2        | 2021-12-02T16:25:04: PM2 log: App name:app id:_old_4 disconnected
PM2        | 2021-12-02T16:25:04: PM2 log: App [app:_old_4] exited with code [1] via signal [SIGINT]
PM2        | 2021-12-02T16:25:04: PM2 log: App name:app id:_old_5 disconnected
PM2        | 2021-12-02T16:25:04: PM2 log: App [app:_old_5] exited with code [1] via signal [SIGINT]
PM2        | 2021-12-02T16:25:04: PM2 log: pid=14476 msg=process killed
PM2        | 2021-12-02T16:25:04: PM2 log: App [app:6] starting in -cluster mode-
PM2        | 2021-12-02T16:25:04: PM2 log: pid=11564 msg=process killed
PM2        | 2021-12-02T16:25:04: PM2 log: App [app:7] starting in -cluster mode-
PM2        | 2021-12-02T16:25:04: PM2 log: App [app:6] online
PM2        | 2021-12-02T16:25:04: PM2 log: App [app:7] online
PM2        | 2021-12-02T16:25:07: PM2 log: Stopping app:app id:_old_6
PM2        | 2021-12-02T16:25:07: PM2 log: Stopping app:app id:_old_7
PM2        | 2021-12-02T16:25:08: PM2 log: App name:app id:_old_7 disconnected
PM2        | 2021-12-02T16:25:08: PM2 log: App name:app id:_old_6 disconnected
PM2        | 2021-12-02T16:25:08: PM2 log: App [app:_old_7] exited with code [1] via signal [SIGINT]
PM2        | 2021-12-02T16:25:08: PM2 log: App [app:_old_6] exited with code [1] via signal [SIGINT]
PM2        | 2021-12-02T16:25:08: PM2 log: pid=1632 msg=process killed
PM2        | 2021-12-02T16:25:08: PM2 log: pid=3064 msg=process killed

**Comment by cx690** [comment]
```js
//app.js
import koa from 'koa';
import { createServer } from 'http';

const app = new koa();
const server = createServer(app.callback());

app.use(async (ctx) => {
    ctx.response.body = 'hello world';
})

server.listen(3000);

console.log('Start server at 3000...');
```

**Comment by vortesnail** [comment]
same problem

**Comment by peterphonic** [comment]
@vortesnail  @cx690 Also have this problem.  I can't find how to use pm2 with a node.js project using es6 module.  Is this possible?  I am using last node version with last plm2 version....

**Comment by yi-ge** [comment]
In 2024, we are still facing the same issues.
