### ISSUE TITLE
Error Cannot find module (at require-in-the-middle)

### ISSUE THREAD

**Issue by fryossi** [Unitech/pm2#5268]
## What's going wrong?
```
 Error: Cannot find module
 at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
 at Module.Hook._require.Module.require (/user/.nvm/versions/node/v12.16.2/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
 at require (internal/modules/cjs/helpers.js:77:18)
```
## How could we reproduce this issue?
Just using regular start command
## Supporting information

Error occurred after old deamon upgrade 2.9.3 -> 5.1.2.
Node version: 12.16.2
pm2 version: 5.1.2
Downgraded to 4.5.6 before filling up this issue so I don't have the report.

**Comment by fryossi** [comment]
Running `ps -e | grep PM2` gives 3 running processes of PM2. I guess that was the root cause

**Comment by dermx-media** [comment]
> Try to run your process with the `cwd` attribute. See [configuration file](https://pm2.keymetrics.io/docs/usage/application-declaration/).

thanks, that works; i had another stupid error where package is missing. but this works really well.

**Comment by xiaofengli** [comment]
> Try to run your process with the `cwd` attribute. See [configuration file](https://pm2.keymetrics.io/docs/usage/application-declaration/).

works well, thanks!

**Comment by SnNano** [comment]
> Try to run your process with the `cwd` attribute. See [configuration file](https://pm2.keymetrics.io/docs/usage/application-declaration/).
Sorry I didn't get your answer how did you solve it?
