### ISSUE TITLE
PM2 restart "services.json" doesn't update environment variables

### ISSUE THREAD

**Issue by gillesdemey** [Unitech/pm2#528]
We're using a JSON file to define all our node services and their appropriate environment variables, script starting points etc.

When adding an environment variable for one of our services and issuing `pm2 restart services.json` it doesn't actually add the environment variable to the process (tested using `pm2 dump`).

Deleting all the services and adding them again does work though but takes down our API's for a while.

**Comment by mykwillis** [comment]
I'm trying to figure out how one is supposed to refresh an environment variable for a cluster that is doing 0 downtime reloads using: 

```
pm2 reload myapp.json
```

It seems that the refresh of environment was only implemented with `pm2 restart`, but that doesn't give 0 downtime. 

Is it intentional that changes to the .JSON file are not picked up by PM2 when a `reload` is invoked? `pm2 delete` and `pm2 start` seems a long way from zero downtime.

**Comment by ericherdzik** [comment]
+1 @mykwillis Would like to have a way to gracefully load a new environment configuration.

**Comment by Evanlec** [comment]
+1 -- this would be very useful -- found that pm2 restart didn't even work -- I had to do pm2 delete; pm2 start xxx.json

**Comment by StyleT** [comment]
+1 without this feature I can't perform zero downtime deploy

**Comment by CJMcGregor** [comment]
+1 This is a much needed feature to have reload / gracefulReload  refresh env vars.

**Comment by Unitech** [comment]
It's not the case for reload / gracefulReload, but this feature is available for restarts with PM2 1.0:

You can try it:

```bash
$ npm install Unitech/pm2#development -g
```

You can also [restart with different pre-defined environment variables](http://pm2.keymetrics.io/docs/usage/application-declaration/#switching-to-different-environments)

**Comment by mhchaudhry** [comment]
Also agree. Would definitely like the ability to update env with zero downtime. i.e. reload
e.g.
pm2 reload app.json --env debug    (sets NODE_DEBUG, DEBUG vars)
pm2 reload app.json --env nodebug (turns debugging off)

**Comment by gflandre** [comment]
+1

**Comment by Florelli** [comment]
+1

**Comment by soyuka** [comment]
@gflandre @Florelli did you try the development version?

**Comment by gflandre** [comment]
@soyuka no I haven't yet (our issue is with production use, so it requires us to use a stable version).
Does it allow zero-downtime reloads w/ env update? I'll give it a go on my dev env anyway :)

**Comment by Booom3** [comment]
I've ran into this problem too, I need it to reload the environment variables. I couldn't get it to do it until I deleted the process itself from PM2 and started it as if it was new.

**Comment by sameetn** [comment]
Any update on this? We have th same issue with 2.1.3 although we do not use the json file.

**Comment by AuspeXeu** [comment]
Same issue ...

**Comment by vmarchaud** [comment]
See `--update-env` docs [here](http://pm2.keymetrics.io/docs/usage/application-declaration/#updating-configurations-of-already-running-applications).

**Comment by AuspeXeu** [comment]
@vmarchaud seems not to affect log file configuration changes though...

**Comment by vmarchaud** [comment]
Yeah some options aren't updated, we are thinking about changing this behavior but it has some pro and cons.

**Comment by Zing22** [comment]
+1 `restart` and `reload` will not reload `ignore_watch` configuration, which took me two hours to fix my bug.

**Comment by vmarchaud** [comment]
Reminder : You need to pass the `ecosystem.json` path if you started the application with it, pm2 doesnt save its location so PM2 can't pickup change by using `pm2 restart applicationName`

**Comment by Zing22** [comment]
@vmarchaud the bash history shows that I used `pm2 restart ecosystem.json` all the time, and I tried again just a moment ago, the output was:
``` shell
# pm2 restart ecosystem.json
[PM2] Applying action restartProcessId on app [UEMINA](ids: 0)
[PM2] [UEMINA](0) ✓
```
and the change of `ignore_watch` didn't affect. But if I turn `watch` from true to false, it could work.
My pm2 version is 2.0.18, on CentOS 7.

**Comment by vmarchaud** [comment]
@Zing22 You should update, behavior have changed around 2.x if i correctly recall

**Comment by Zing22** [comment]
@vmarchaud Problem still there, BTW, the exec mode is `fork`.
Is there a command like `pm2 show 0` to display `ignore_watch` list?

anyway, thanks for your time : )

**Comment by vmarchaud** [comment]
@Zing22 You can dump the process data using `pm2 prettylist` and see the options

**Comment by arcreative** [comment]
Ok so maybe I'm taking crazy pills or something, but I keep having persistent problems with ENV vars and code/assets just downright _not updating_ when I do a `pm2 restart` either from the server or Capistrano deployment.  It's maddening.  If I ever make a meaningful change, I have to do `cap production pm2:stop && cap production pm2:delete || cap production pm2:start`, and now it's to the point where I don't _ever_ trust that `restart` is going to do what I need it to.  It just seems horribly unreliable to me and it's happened on multiple projects that are in no way cloned from one another.  Am I just fundamentally misunderstanding what is supposed to be happening here?

More context: I'm using `.env` files (via `node-dotenv` module), `npm shrinkwrap` (shrinkwrap changes were also ignored on last deploy--when I finally stopped and deleted the pm2 process, the next run exhibited a require error that wasn't previously an issue, telling me that pm2 is "caching" or remembering something I don't want it to).

All other process managers I've worked with do a CLEAN RESTART from scratch when you restart them.  There should be no state left on the process via PM2 or any other portion of the stack.  

If I can't get this figured out in a sensible way I'm going to have to drop PM2 entirely for my sanity's sake :-)

**Comment by dendrochronology** [comment]
Although this issue was closed in 2014, I still see weird behavior around restarts, even with tiny example projects. The only consistent solution I have is to run `pm2 kill` to unload the daemon entirely.

**Comment by nebular** [comment]
please fix this broken, complex and useless functionality. Env Vars are Env Vars, not JSON, not YML, not ecosystems, not anything different to a EXPORT VAR=VALUE and process.env returning the correct value.

**Comment by Norbz** [comment]
This is indeed not fix, and actually I find it more and more unreliable with the latest version

Before, I could just pm2 update, now I often need to kill and reload everything, making no downtime reload impossible...
I don't get why such and important yet probably easy to fix issue can go on for 7 years now...

**Comment by arcreative** [comment]
Seems to me that the only salient plan of action at this point is to stop using this solution in its entirety.  Definitely had some potential and great things going for it, but the maintainers don't seem to be taking this seriously enough--at least for my production needs.

**Comment by LuckyArd110** [comment]
Okay, this problem come in 2022

**Comment by Ozak93** [comment]
Still a problem in 2023.

**Comment by Ozak93** [comment]
> Seems to me that the only salient plan of action at this point is to stop using this solution in its entirety. Definitely had some potential and great things going for it, but the maintainers don't seem to be taking this seriously enough--at least for my production needs.

What alternatives is there? i'd love to know what you use now

**Comment by Ozak93** [comment]
Ah! I doubt Kubernetes beats the simplicity of pm2 though... I'll try it nonetheless thanks!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by arcreative** [comment]
@Ozak93 absolutely not. While it's definitely not analogous to PM2, having pods for each process with health checks was functionally the same for us. It's a direction we wanted to head anyway, definitely a massive time investment, but you get to feel like a sorcerer when you're done 😆

**Comment by odufuwa-segun** [comment]
Still a problem in 2026.
