### ISSUE TITLE
Limit logs size?

### ISSUE THREAD

**Issue by roytan883** [Unitech/pm2#535]
Can i configure pm2 with limit logs size? I don't want the logs file increase permanently.

like log4js:
"maxLogSize": 104857600,
"backups": 5

**Comment by jshkurti** [comment]
You can now install the module pm2-logrotate `pm2 install pm2-logrotate` which will automatically rotate logs for each application running with PM2 including PM2 logs itself.

See https://www.npmjs.com/package/pm2-logrotate#configure for more info.
