### ISSUE TITLE
pm2 cron schedule starts immediately, but it should start next morning instead

### ISSUE THREAD

**Issue by smartini87** [Unitech/pm2#5479]
## What's going wrong?
I set up the cron job like "**pm2 start index.js --cron '00 06 * * *' --no-autorestart**" at 4pm and I expected pm2 to start the next morning at 6AM, but it immediately starts the node script. Is this intended that it "knows" it's after 6AM so just start it?

## How could we reproduce this issue?
"pm2 start index.js --cron '00 06 * * *' --no-autorestart"

## Supporting information
I use pm2 5.2.2 on my newest Raspberry Pi (v4) version (standard OS)

**Comment by GravePlayz** [comment]
Using the --cron option tells it at what time you want it to restart, not what time you want it to start at.

**Comment by smartini87** [comment]
Thank you for the explanation.
Is there a possibility to add 'beginn cron job at' as a new feature?

**Comment by esetnik** [comment]
Came here with the same issue. There should be an option that prevents the initial run from occurring, e.g. "just schedule, do not run now".

**Comment by alexgalkin** [comment]
there is no option for this as far as I know. But I have added the following condition to index.js itself when I had similar requirement:

```
if (!process.env.prev_restart_delay && process.env.cron_restart) {
  console.log('skipping initial launch....');
  process.exit(0);
  return;
}
```

this will stop the process immediately but it still will be restarted by cron. Note you should also disable autorestart (--no-autorestart)

After the subsequent start on the script `prev_restart_delay` option will be available and the condition will be skipped and your script will run.

Not ideal, but works in my case.

**Comment by ultimate-tester** [comment]
I'm going through the issues to find mentions about not auto-starting a new process, which I now created a PR for:
#5780

**Comment by markcellus** [comment]
Hmm @Unitech this should probably be reopened. The PR referenced introduces an `autostart` configuration option that doesn't work for the purposes of the original issue filed. 

With the following command, copy..sh should not start initially upon running the command, but should start at cron time set.

```
pm2 start copy.sh --no-autostart --cron-restart="0 10 25 4 *"
```

But running this the copy.sh script doesn't run at all--not even at the cron time.

**Comment by markcellus** [comment]
@alexgalkin thanks for your efforts! However, the following script you recommended doesn't seem to work for me.

```
if (!process.env.prev_restart_delay && process.env.cron_restart) {
  console.log('skipping initial launch....');
  process.exit(0);
  return;
}
```

Still ends up running the script on every `reload` or `restart`. even when `cron_restart` is set in ecosystem file. I don't see anywhere in the docs how `process.env` is populated but it appears that `process.env.cron_restart` is never actually set if specified in an ecosystem file.

**Comment by alexgalkin** [comment]
> --cron-restart="0 10 25 4 *"

This cron means `At 10:00 April, 25`. Just want to make sure that you checked with something more frequent.

**Comment by alexgalkin** [comment]
> Still ends up running the script on every reload or restart. even when cron_restart is set in ecosystem file. I don't see anywhere in the docs how process.env is populated but it appears that process.env.cron_restart is never actually set if specified in an ecosystem file.

That's correct. My case was particular about `the first run`. When it runs initially it is skipped. On every subsequent restart it is executed though. I have not found better workaround at that point unfortunately.
