### ISSUE TITLE
pm2 memory vs heap size

### ISSUE THREAD

**Issue by AmosSzust** [Unitech/pm2#5514]
I'm experiencing a heap out of memory and I'm trying to understand what the cause is.

I see 828 MB in memory but only ~700mb in heap. When the crash occurs, heap remains around 700mb but the memory rises up to 1.6gb and then fails.

![image](https://user-images.githubusercontent.com/100950035/210612537-e12a3ff8-0322-4439-9180-2b1d2e305367.png)

node version 18.12.1
It happens on both Windows and Debian

I narrow it down to the following code:
```
const cache: any = memoryCache.exportItemsToJson();
let ws = createWriteStream('cache.bin');
for (let key in cache) {
    ws.write(`${JSON.stringify({ [key]: cache[key] })}\n`);
}
ws.end();
ws.close();

exportItemsToJson(): any {
    const cacheOutput = {};
    for (let [key, valueWrapper] of this.itemKeyToValueWrapperMap) {
        Object.assign(cacheOutput, { [key as string]: valueWrapper });
    }
    return cacheOutput;
}
```

**Comment by AmosSzust** [comment]
The problem was to check if write fails and if so, wait for drain event.

**Comment by YemYigit** [comment]
@AmosSzust How did you allocate all the memory available in system? Did any custom configurations for that? 

PM2 always allocates minimum possible memory for me

**Comment by AmosSzust** [comment]
You can read here
https://medium.com/weekly-webtips/increase-node-js-memory-limit-bonus-pm2-62cda081ce2a
