### ISSUE TITLE
pm2 pid path not matching up with actual path

### ISSUE THREAD

**Issue by ttback** [Unitech/pm2#554]
So if i desc an app i run with following conifg.json:

``` Javascript
[{
"name" : "app",
"script" : "/opt/app/app.js",
"error_file": "/var/app/logs/app.stderr.log",
"out_file": "/var/app/logs/app.stdout.log",
"pid_file": "/var/app/run/app.pid"
}]
```

When i pm2 desc the process, it tells me pid path: `/var/app/run/monitor.pid`
But the actual path is /var/app/run/app.pid1.pid

Did i put the config.json wrong? Like the log path, which show up as `/var/app/logs/app.stderr-1.log`, the pid files should also base around the id of pm2 process, right?

**Comment by Bijoshtj** [comment]
Im getting this problem.
```
[
    {
      "name": "app",
      "pid": "/var/run/app.pid",
      "script": "npm",
      "args": "run start",
      "env": {
        "NODE_ENV": "production",
      },
      "cwd": "/home/user/project/app",
      "max_restarts": "10"
    }
  ]

```

When i start by pm2 start app.json

pid created is /var/run/app-{id}.pid (eg:  /var/run/app-0.pid)
