### ISSUE TITLE
cant login into pm2

### ISSUE THREAD

**Issue by SuperchupuDev** [Unitech/pm2#5593]
## What's going wrong?
i randomly decided to go into my servers overview pm2+ page and it was stuck loading which didn't happen yesterday, the console had no errors, so i decided to log off and try again

when trying to log in again, https://id.keymetrics.io/api/oauth/login returns Unknown user after a lot of seconds of loading on login button click
![image](https://user-images.githubusercontent.com/53496941/234673965-ec053c4e-d113-4391-b33b-2dbafca253a5.png)

logging in with `pm2 monitor` throws undefined
![image](https://user-images.githubusercontent.com/53496941/234674218-fc943760-dfac-491b-a59f-f3a91f0052fb.png)

i tried to reach out via the contact form but it internally gives 503, visually the submit button just doesn't do anything
![image](https://user-images.githubusercontent.com/53496941/234674668-67406aad-552a-4465-a7c4-75057c680036.png)

i imagine this is just a normal internally known outage but i'm reporting this in case it isn't, my local pm2 installation and `pm2 monit` both work fine

## How could we reproduce this issue?
- log in
- hopefully see

## Supporting information

<details><summary>pm2 report</summary>
<p>

```
--- PM2 report ----------------------------------------------------------------
Date                 : Wed Apr 26 2023 20:55:45 GMT+0200 (Central European Summer Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 5.3.0
node version         : 20.0.0
node path            : not found
argv                 : /usr/local/bin/node,/usr/local/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
uptime               : 2844min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 5.3.0
node version         : 20.0.0
node path            : /usr/local/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/bin/pm2,report
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz
cpus nb              : 1
freemem              : 423530496
totalmem             : 1024294912
home                 : /root
===============================================================================
--- PM2 list -----------------------------------------------
┌────┬─────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name        │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user
     │ watching │
├────┼─────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0  │ gasbot      │ default     │ N/A     │ fork    │ 990      │ 2D     │ 1    │ online    │ 0%       │ 37.6mb   │ root
     │ disabled │
│ 1  │ hee8-bot    │ default     │ N/A     │ fork    │ 1026     │ 2D     │ 1    │ online    │ 0%       │ 46.6mb   │ root
     │ disabled │
└────┴─────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/root/.pm2/pm2.log last 20 lines:
PM2        | 2023-04-24T21:30:47: PM2 log: Process dump file    : /root/.pm2/dump.pm2
PM2        | 2023-04-24T21:30:47: PM2 log: Concurrent actions   : 2
PM2        | 2023-04-24T21:30:47: PM2 log: SIGTERM timeout      : 1600
PM2        | 2023-04-24T21:30:47: PM2 log: ===============================================================================
PM2        | 2023-04-24T21:30:52: PM2 log: App [gasbot:0] starting in -fork mode-
PM2        | 2023-04-24T21:30:52: PM2 log: App [hee8-bot:1] starting in -fork mode-
PM2        | 2023-04-24T21:30:52: PM2 log: App [gasbot:0] online
PM2        | 2023-04-24T21:30:52: PM2 log: App [hee8-bot:1] online
PM2        | 2023-04-24T19:31:57: PM2 log: Process 0 in a stopped status, starting it
PM2        | 2023-04-24T19:31:57: PM2 log: Stopping app:gasbot id:0
PM2        | 2023-04-24T19:31:57: PM2 log: App [gasbot:0] exited with code [0] via signal [SIGINT]
PM2        | 2023-04-24T19:31:57: PM2 log: pid=843 msg=process killed
PM2        | 2023-04-24T19:31:57: PM2 log: App [gasbot:0] starting in -fork mode-
PM2        | 2023-04-24T19:31:57: PM2 log: App [gasbot:0] online
PM2        | 2023-04-24T19:32:09: PM2 log: Process 1 in a stopped status, starting it
PM2        | 2023-04-24T19:32:09: PM2 log: Stopping app:hee8-bot id:1
PM2        | 2023-04-24T19:32:09: PM2 log: App [hee8-bot:1] exited with code [0] via signal [SIGINT]
PM2        | 2023-04-24T19:32:09: PM2 log: pid=844 msg=process killed
PM2        | 2023-04-24T19:32:09: PM2 log: App [hee8-bot:1] starting in -fork mode-
PM2        | 2023-04-24T19:32:09: PM2 log: App [hee8-bot:1] online
```
</p>
</details>

**Comment by tondy1** [comment]
Same here

**Comment by bagus-anjari** [comment]
same here, i get warning [PM2.IO][WARNING] Not managed to connect to PM2 Plus, retrying in background
 when entering command link PM2 to PM2.io

**Comment by mautz-et-tong** [comment]
+1

**Comment by Aleksandr-JS-Developer** [comment]
Can`t to connect monitor.

https://stackoverflow.com/questions/76120988/how-to-enable-web-monitor-in-pm2

**Comment by mizzyexists** [comment]
@Unitech, can we please get an update on this? It's been 24 hours and there are still issues with the web dashboard.

**Comment by Aleksandr-JS-Developer** [comment]
Got new error:

`$ mp2 monitor`

![Screenshot_295](https://user-images.githubusercontent.com/59054779/235072394-bdba32ae-2f94-47bc-b9e7-35f8747fd24e.png)

**Comment by zzhiren** [comment]
> same here, i get warning [PM2.IO][WARNING] Not managed to connect to PM2 Plus, retrying in background when entering command link PM2 to PM2.io

+1

**Comment by MachineR8** [comment]
Same problems

**Comment by HamoBoker** [comment]
Same issue here, i can't open my Bucket and i get this warning `Not managed to connect to PM2 Plus, retrying in background` when i try to link a new bucket

**Comment by vieira-avmb** [comment]
> Same issue here, i can't open my Bucket and i get this warning `Not managed to connect to PM2 Plus, retrying in background` when i try to link a new bucket

same here

**Comment by spectreq666** [comment]
> same here, i get warning [PM2.IO][WARNING] Not managed to connect to PM2 Plus, retrying in background when entering command link PM2 to PM2.io

Same!

**Comment by spectreq666** [comment]
I don't know how, but now I have only one trouble:
PM2 IO dashboard is not updating in realtime, to get new info I need to refresh page

**Comment by NerdPlaysGames** [comment]
I am getting the retrying in the background error as well. My free bucket works perfectly fine. It's just my Plus bucket.

**Comment by SuperchupuDev** [comment]
my free bucket works now after using `pm2 monitor`. should i close this?

**Comment by mcaratioxalis** [comment]
> my free bucket works now after using `pm2 monitor`. should i close this?

Mine worked too, with link command

**Comment by mizzyexists** [comment]
Mine worked as well.

**Comment by dzlandis** [comment]
I'm still facing issues unfortunately. I'm still prompted to run `pm2 plus` when running `pm2 link` which is different than how I've had to do it previously. Additionally, when I tried to go through the login phase, I was not sure what to put since my account was created with a third-party login. I also tried adding a password and using that, but I got the following error when I tried that too:
```
[PM2 I/O] Unexpected error : Missing mandatory field refresh_token to make a POST request on /api/oauth/token
```

**Comment by Giildo** [comment]
+1 

![pm2](https://user-images.githubusercontent.com/34237011/235353695-01a62b25-8176-430d-9db7-08aab0b1ada5.png)

**Comment by NerdPlaysGames** [comment]
Mine seems to be working now. Was greeted by a bunch of errors which was a relief

**Comment by markpaul099** [comment]
it's fixed now I think

**Comment by Aleksandr-JS-Developer** [comment]
Monitor works for me now

**Comment by SuperchupuDev** [comment]
awesome closing then i think

**Comment by dameso** [comment]
+1

pm2 link...
[PM2.IO][WARNING] Not managed to connect to PM2 Plus, retrying in background.
[+] PM2+ activated!

pm2 monitor ( login )
[PM2 I/O] Authenticating ...
[PM2 I/O] Failed to authenticate: socket hang up
