### ISSUE TITLE
Set timezone

### ISSUE THREAD

**Issue by CodersBrothers** [Unitech/pm2#560]
Will be cool set timezone of application in the json config? For example:

``` json
{
    "apps" : [
        {
            "name"         : "Test",
            "timezone"     : "Europe/Amsterdam",
            "script"       : "./app.js",
            "exec_mode"    : "cluster_mode"
        }
    ]
}
```

And pm2 make this inside:

``` javascript
process.env.TZ = 'Europe/Amsterdam';
```

**Comment by weconquered** [comment]
but it does not work now :  
set as :   TZ: "Asia/Shanghai"
format in log file:  2017-08-14 23:51:20 -04:00:

**Comment by faller** [comment]
same question

**Comment by joaobarcia** [comment]
Agree, this does not work on Windows either
