### ISSUE TITLE
NPM warns about a vulnerability in semver

### ISSUE THREAD

**Issue by OIRNOIR** [Unitech/pm2#5623]
When installing PM2 then running `npm audit`, it shows as having 7 moderate security vulnerabilities caused by dependencies with vulnerable versions of `semver`. It would be great if these could be updated to fix the problem.
https://github.com/advisories/GHSA-c2qf-rxjj-qqgw

The `npm audit` output on a clean install (`npm i pm2`) is below:

```
# npm audit report

semver  <7.5.2
Severity: moderate
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
fix available via `npm audit fix --force`
Will install pm2@2.10.4, which is a breaking change
node_modules/@opencensus/core/node_modules/semver
node_modules/@opencensus/propagation-b3/node_modules/semver
node_modules/@pm2/agent/node_modules/semver
node_modules/@pm2/io/node_modules/semver
node_modules/async-listener/node_modules/semver
  @opencensus/core  <=0.0.21
  Depends on vulnerable versions of semver
  node_modules/@opencensus/core
  node_modules/@opencensus/propagation-b3/node_modules/@opencensus/core
    @opencensus/propagation-b3  0.0.3 - 0.0.21
    Depends on vulnerable versions of @opencensus/core
    node_modules/@opencensus/propagation-b3
      @pm2/io  *
      Depends on vulnerable versions of @opencensus/core
      Depends on vulnerable versions of @opencensus/propagation-b3
      Depends on vulnerable versions of semver
      node_modules/@pm2/io
        pm2  >=3.0.0
        Depends on vulnerable versions of @pm2/agent
        Depends on vulnerable versions of @pm2/io
        node_modules/pm2
  @pm2/agent  >=0.5.3
  Depends on vulnerable versions of semver
  node_modules/@pm2/agent
  async-listener  >=0.6.4
  Depends on vulnerable versions of semver
  node_modules/async-listener

7 moderate severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force
```
`npm audit fix` has no effect, and `npm audit fix --force` would revert back to an extremely old version.

**Comment by catalin25** [comment]
have you solved it bro?

**Comment by catalin25** [comment]
I'm loosing my bachelor degree because of this

**Comment by OIRNOIR** [comment]
Nope, this is literally impossible for me to solve as it requires access to the PM2 repository to update dependencies.

**Comment by MChuduk** [comment]
@OIRNOIR  You can use `resolutions` in your `package.json`, but is a workaround and applied in exceptional cases:
```
  "resolutions": {
    "semver": "~7.5.2"
  }
```
It will probably be fixed in the next release.

**Comment by OIRNOIR** [comment]
> @OIRNOIR You can use `resolutions` in your `package.json`, but is a workaround and applied in exceptional cases:
> 
> ```
>   "resolutions": {
>     "semver": "~7.5.2"
>   }
> ```
> 
> It will probably be fixed in the next release.

minor fix: In NPM, it is called "overrides" instead of "resolutions" but that works for now

**Comment by mirul786** [comment]
"overrides": {
    "semver": "~7.5.2"
  }
  
  This worked for me...

**Comment by mrizwan83** [comment]
,
  "overrides": {
    "semver": "~7.5.2"
  } 
  add this to the end of your dependencies, it worked for me also! Thank You! I was going crazy the past few days lol

**Comment by mrizwan83** [comment]
# npm audit report

semver  <7.5.2
Severity: moderate
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
fix available via `npm audit fix --force`
Will install bcrypt@5.0.1, which is a breaking change
node_modules/make-dir/node_modules/semver
  make-dir  2.0.0 - 3.1.0
  Depends on vulnerable versions of semver
  node_modules/make-dir
    @mapbox/node-pre-gyp  >=1.0.1
    Depends on vulnerable versions of make-dir
    node_modules/@mapbox/node-pre-gyp
      bcrypt  >=5.1.0
      Depends on vulnerable versions of @mapbox/node-pre-gyp
      node_modules/bcrypt

4 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
  
  Insert the "overrides": {"semver": "~7.5.2"} into your package.json 
~> npm update

added 2 packages, removed 2 packages, changed 2 packages, and audited 195 packages in 13s

30 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities 
it works!!

**Comment by OIRNOIR** [comment]
> # npm audit report
> semver <7.5.2 Severity: moderate semver vulnerable to Regular Expression Denial of Service - [GHSA-c2qf-rxjj-qqgw](https://github.com/advisories/GHSA-c2qf-rxjj-qqgw) fix available via `npm audit fix --force` Will install bcrypt@5.0.1, which is a breaking change node_modules/make-dir/node_modules/semver make-dir 2.0.0 - 3.1.0 Depends on vulnerable versions of semver node_modules/make-dir @mapbox/node-pre-gyp >=1.0.1 Depends on vulnerable versions of make-dir node_modules/@mapbox/node-pre-gyp bcrypt >=5.1.0 Depends on vulnerable versions of @mapbox/node-pre-gyp node_modules/bcrypt
> 
> 4 moderate severity vulnerabilities
> 
> To address all issues (including breaking changes), run: npm audit fix --force
> 
> Insert the "overrides": {"semver": "~7.5.2"} into your package.json ~> npm update
> 
> added 2 packages, removed 2 packages, changed 2 packages, and audited 195 packages in 13s
> 
> 30 packages are looking for funding run `npm fund` for details
> 
> found 0 vulnerabilities it works!!

That works, but it's still a very temporary fix. I wouldn't consider this issue resolved until pm2 itself is updated to resolve the issue.

**Comment by caratlane-akshay** [comment]
"overrides": {
"semver": "~7.5.2"
}

This worked for me. 
Thanks

**Comment by usmandilmeer** [comment]
I have solved it without adding👇👇
"overrides": {
"semver": "~7.5.2"
}

First, I cloned my GitHub repository and then checked the package-lock.json file. I discovered that semver was a dependency of the nodemon package in my case. To resolve the security vulnerability, I uninstalled nodemon and reinstalled it as a dev dependency. This simple action successfully fixed the security issue on GitHub.

If you are facing a similar problem, check your package-lock.json file and try to fix it using the same approach. I hope it will be fixed for you as well.

**Comment by mindraptor** [comment]
semver dependency is on npm itself.
Fixed in package.json by adding npm override:

"overrides": {
    "npm": ">=9.8.1"
  }

**Comment by OIRNOIR** [comment]
This is no longer an issue.

**Comment by Chandula1999** [comment]
How to Solve this ...
npm audit
# npm audit report

semver  7.0.0 - 7.5.1
Severity: high
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
fix available via `npm audit fix`
node_modules/simple-update-notifier/node_modules/semver
  simple-update-notifier  1.0.7 - 1.1.0
  Depends on vulnerable versions of semver
  node_modules/simple-update-notifier
    nodemon  2.0.19 - 2.0.22
    Depends on vulnerable versions of simple-update-notifier
    node_modules/nodemon

3 high severity vulnerabilities

To address all issues, run:
  npm audit fix
