### ISSUE TITLE
cli-progress's progress show as error

### ISSUE THREAD

**Issue by SarkarKurdish** [Unitech/pm2#5688]
I'm using cli-progress it works fine without pm2, when using p2m with these settings

```javascript
      const b1 = new cliProgress.SingleBar({
        format:
          "Public Ip Sessions |" +
          colors.cyan("{bar}") +
          "| {percentage}% || {value}/{total} Lines || ETA: {eta}s || Elapsed Time {duration}s",
        barCompleteChar: "\u2588",
        barIncompleteChar: "\u2591",
        hideCursor: false,
        stopOnComplete: true,
        noTTYOutput: true,
      });
```

```bash
[TAILING] Tailing last 15 lines for [0] process (change the value with --lines option)
/home/user/.pm2/logs/process-1-out.log last 15 lines:
0|process- | File Download Complete
0|process- | ⚡ Counting lines...

/home/user/.pm2/logs/process-1-error.log last 15 lines: // <--------------- Note it logs in the error file
0|process- | Download Progress |████████████████████████████████████░░░░| 89% || 74542743552/82931332868 Chunks || ETA: 22s
0|process- | Download Progress |████████████████████████████████████░░░░| 90% || 75280941056/82931332868 Chunks || ETA: 30s
0|process- | Download Progress |█████████████████████████████████████░░░| 91% || 75966840832/82931332868 Chunks || ETA: 23s
0|process- | Download Progress |█████████████████████████████████████░░░| 92% || 76596106992/82931332868 Chunks || ETA: 17s
0|process- | Download Progress |█████████████████████████████████████░░░| 93% || 77289732776/82931332868 Chunks || ETA: 15s
0|process- | Download Progress |██████████████████████████████████████░░| 94% || 77968955120/82931332868 Chunks || ETA: 14s
0|process- | Download Progress |██████████████████████████████████████░░| 94% || 78666124192/82931332868 Chunks || ETA: 11s
0|process- | Download Progress |██████████████████████████████████████░░| 95% || 79338391032/82931332868 Chunks || ETA: 10s
0|process- | Download Progress |███████████████████████████████████████░| 96% || 80044361128/82931332868 Chunks || ETA: 7s
0|process- | Download Progress |███████████████████████████████████████░| 97% || 80590667776/82931332868 Chunks || ETA: 6s
0|process- | Download Progress |███████████████████████████████████████░| 98% || 81314185216/82931332868 Chunks || ETA: 5s
0|process- | Download Progress |████████████████████████████████████████| 98% || 81945410216/82931332868 Chunks || ETA: 3s
0|process- | Download Progress |████████████████████████████████████████| 99% || 82621482488/82931332868 Chunks || ETA: 5s
0|process- | Download Progress |████████████████████████████████████████| 99% || 82931073104/82931332868 Chunks || ETA: 1s
0|process- | 

```

the other logs goes to the (out) file only the progress ones go to the error file.

**Comment by SarkarKurdish** [comment]
Forgot to mention, every progress update creates a new line while it is suppose to update the original line not creare another one

**Comment by SarkarKurdish** [comment]
It's was a configuration from the package not an issue with pm2. [Fix is here](https://github.com/npkgz/cli-progress/issues/151#issuecomment-1755859896)

**Comment by amrsa1** [comment]
> Forgot to mention, every progress update creates a new line while it is suppose to update the original line not creare another one

How do you manage to solve this ?

**Comment by SarkarKurdish** [comment]
> > Forgot to mention, every progress update creates a new line while it is suppose to update the original line not creare another one
> 
> How do you manage to solve this ?

It is not an issue to be fixed, pm2 simply save any terminal (stdout) update to a file, and every time cli-progress updates the progress it is just a newline plus the deletion of the previous one, and cli-progress don't have access to the pm2 log file to update that, you can say that cli-progress gives you the illusion of a consistent animation while in reality it just prints another line

**Comment by amrsa1** [comment]
> > > Forgot to mention, every progress update creates a new line while it is suppose to update the original line not creare another one
> > 
> > How do you manage to solve this ?
> 
> It is not an issue to be fixed, pm2 simply save any terminal (stdout) update to a file, and every time cli-progress updates the progress it is just a newline plus the deletion of the previous one, and cli-progress don't have access to the pm2 log file to update that, you can say that cli-progress gives you the illusion of a consistent animation while in reality it just prints another line

Thanks for reply, actually it turn out to be an issue when using "\n" in a console log.

It worked fine once i removed it

**Comment by SarkarKurdish** [comment]
> > > > Forgot to mention, every progress update creates a new line while it is suppose to update the original line not creare another one
> > > 
> > > 
> > > How do you manage to solve this ?
> > 
> > 
> > It is not an issue to be fixed, pm2 simply save any terminal (stdout) update to a file, and every time cli-progress updates the progress it is just a newline plus the deletion of the previous one, and cli-progress don't have access to the pm2 log file to update that, you can say that cli-progress gives you the illusion of a consistent animation while in reality it just prints another line
> 
> Thanks for reply, actually it turn out to be an issue when using "\n" in a console log.
> 
> It worked fine once i removed it

Sure things, my reply was PM2 specific didn't know your issue was with terminal
