### ISSUE TITLE
pm2 startup error on Centos 6.3

### ISSUE THREAD

**Issue by markkevans** [Unitech/pm2#57]
When running pm2 startup the following error is generated

pm2 startup
{ [Error: Command failed: /bin/sh: update-rc.d: command not found
] killed: false, code: 127, signal: null }

I guess there are 2 possible solutions
1. Check Platform OS and if not debian / ubuntu don't attempt to run update-rc.d
2. Check if update-rc.d script exists on the platform before attempting to run it

Any thoughts on the best way to solve this?

**Comment by frankbecker** [comment]
I was able to run the startup command on an Oracle Linux machine, might have been Red Hat, even though I tried using redhat as a platform option.
    pm2 startup centos

This worked beautifully, my pm2 processes restart when the server restarts.

**Comment by jshkurti** [comment]
:+1:
