### ISSUE TITLE
Axios Cross-Site Request Forgery Vulnerability

### ISSUE THREAD

**Issue by smo043** [Unitech/pm2#5728]
Please update the version of axios. A vulnerability has been reported. Thanks.

```
pm2@5.3.0 -> @pm2/js-api@0.6.7 -> axios@0.21.4
```

![image](https://github.com/Unitech/pm2/assets/17010033/123337c9-b3cf-47b0-be9d-aaf116542d8b)

**Comment by bthomas2622** [comment]
GitHub Advisory Database entry: https://github.com/advisories/GHSA-wf5p-g6vw-rhxx

**Comment by faithfulojebiyi** [comment]
`@pm2/js-api  *
  Depends on vulnerable versions of axios
  node_modules/@pm2/js-api
    pm2  >=3.0.0
    Depends on vulnerable versions of @pm2/js-api
    node_modules/pm2`

**Comment by estevanpedro** [comment]
Why everyone is just acting like this isn't a problem?

**Comment by WillianAgostini** [comment]
Related https://github.com/keymetrics/pm2-io-js-api/issues/76

**Comment by Nightbr** [comment]
Hey everyone, there is also a High vulnerability on `Axios <1.6.4` now: https://security.snyk.io/vuln/SNYK-JS-AXIOS-6144788

I really think you should consider upgrading it as soon as possible. We have done it in our full code base and pm2 is the last step to get ride of old Axios version. let me know if we can help on this! Best

**Comment by boxexchanger** [comment]
any update?

**Comment by OIRNOIR** [comment]
> any update?

The pull request seems to have just been merged into https://github.com/keymetrics/pm2-io-js-api. All we really need now is a new version release and for pm2 to be updated to have the new version as a dependency (maybe?)

**Comment by Unitech** [comment]
fixed via pm2@5.3.1
