### ISSUE TITLE
UUID Version Issue

### ISSUE THREAD

**Issue by rojanmagar2001** [Unitech/pm2#5733]
Install npm
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

**Comment by WillianAgostini** [comment]
Related keymetrics/pm2-io-js-api#76

**Comment by rojanmagar2001** [comment]
When will it be fixed?

**Comment by mjwweb** [comment]
Hopefully this is fixed soon. pm2 uses uuid@3.4.0. The latest version is [uuid@9.0.1](https://www.npmjs.com/package/uuid)

**Comment by sephentos** [comment]
@Unitech It's been almost three years. Can we expect an update regarding this?

**Comment by DulalSandip** [comment]
@Unitech , can you fix this issue soon, the latest npm package have uuid 3 version, we are facing deprecated issue.

**Comment by xianping-yan** [comment]
pnpm  ----- 

 WARN  1 deprecated subdependencies found: uuid@3.4.0

**Comment by firmin-kaman** [comment]
Cela va faire 04 ans que les utilisateurs se plaignent. On peut donc en conclure que la librairie (package) n'est plus maintenu et est abandonner (PM2). Je conseille vivement de passer à une autre librairie comme **_Nodemon_** etc. Vraiment décu de @Unitech !!!

**Comment by Unitech** [comment]
Feature landed

Update PM2 to 5.4.0

```bash
$ npm install pm2@5.4.0 -g
$ pm2 update
```
