### ISSUE TITLE
Unable to run npm install pm2 or npm install pm2@latest

### ISSUE THREAD

**Issue by martinrombach88** [Unitech/pm2#5758]
## What's going wrong?
Unable to install the 

npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /Users/martin/Code/js_calculator_api_v2/node_modules/dayjs
npm ERR! dest /Users/martin/Code/js_calculator_api_v2/node_modules/.dayjs-dd2YnPcB
npm ERR! errno -66
npm ERR! ENOTEMPTY: directory not empty, rename '/Users/martin/Code/js_calculator_api_v2/node_modules/dayjs' -> '/Users/martin/Code/js_calculator_api_v2/node_modules/.dayjs-dd2YnPcB'

## How could we reproduce this issue?
Run the npm install pm2 command

## Supporting information
App is a Node.js/Typescript app, with Express. IDE is Visual Studio Code.
NPM 9.8.1. 
```
# Run the following commands
$ pm2 report
```

**Comment by WillianAgostini** [comment]
It doesn't seem to be an issue with pm2, but rather with the node_modules directory. Have you tried deleting the node_modules folder and the package-lock.json file?
```shell
$ rm -rf node_modules
$ rm -rf package-lock.json
```
And then run:

```shell
$ npm install
$ npm install pm2
```

**Comment by martinrombach88** [comment]
I ended up finding a different solution than pm2 in the end. I hope I'm the only one who got this error.
