### ISSUE TITLE
pm2 failing npm audit

### ISSUE THREAD

**Issue by mmtdm** [Unitech/pm2#5760]
## What's going wrong?
installation of pm2 fails to pass npm audit

## How could we reproduce this issue?
mkdir test && cd test
npm init -y
npm install pm2 --save

added 162 packages, and audited 163 packages in 2s

13 packages are looking for funding
  run `npm fund` for details

6 high severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

## Supporting information

```
# Run the following commands
$ pm2 report
```

**Comment by mmtdm** [comment]
even worse if you run npm audit fix --force

22 vulnerabilities (4 moderate, 16 high, 2 critical)

**Comment by boxexchanger** [comment]
https://github.com/TooTallNate/proxy-agents/issues/280

**Comment by OIRNOIR** [comment]
proxy-agent has released an update to fix the vulnerability. Run `npm update`.
