### ISSUE TITLE
Create process but not start

### ISSUE THREAD

**Issue by darkdiesel** [Unitech/pm2#5768]
Is it possible create process and not start it. Save list and then start when you need?

**Comment by Void-Monarch** [comment]
You can probably use a config file for it.

https://pm2.keymetrics.io/docs/usage/application-declaration/

![image](https://github.com/Unitech/pm2/assets/102967317/a30ae739-2feb-463d-a4ec-e9fa8bb323fd)

**Comment by mudmixer-wes** [comment]
That doesn't work. I opened this issue quite some time ago and never got a response: https://github.com/Unitech/pm2/issues/5711

**Comment by ultimate-tester** [comment]
What is the exact use case of adding an app to the list to launch it later? Why don't you just do `pm2 start ...` later then?

**Comment by ultimate-tester** [comment]
I'm going through the issues to find mentions about not auto-starting a new process, which I now created a PR for:
#5780

**Comment by Unitech** [comment]
Feature landed

Update PM2 to 5.4.0

```bash
$ npm install pm2@5.4.0 -g
$ pm2 update
```

**Comment by mudmixer-wes** [comment]
Let's go!

**Comment by darkdiesel** [comment]
Wow! Thanks a lot!
