### ISSUE TITLE
AppData/Roaming/npm/pm2: 15: exec: node: not found

### ISSUE THREAD

**Issue by mike-rambil** [Unitech/pm2#5825]
## What's going wrong?
All commands in pm2 lead to me this error(provided below).

I just installed pm2 in windows cmd (which didn't work), uninstalled it and reinstalled it using the wsl terminal.

This is the error that I receive when I try to run my nextjs application
``` 
 
mike@Mykl:/mnt/c/Github/whk-wms-front-end$ pm2 start npm --name whk-wms-frontend -- start --port 4000
/mnt/c/Users/miche/AppData/Roaming/npm/pm2: 15: exec: node: not found

```
## How could we reproduce this issue?

1) Use WSL in windows
2) Install pm2
3) Run pm2 start npm --name <app name> -- start --port 4000 

## Supporting information

pm2 report command also gives me the same error

```
mike@Mykl:/mnt/c/Github/whk-wms-front-end$ pm2 report
/mnt/c/Users/miche/AppData/Roaming/npm/pm2: 15: exec: node: not found
```

**Comment by groom7** [comment]
Have you found a solution?

**Comment by mike-rambil** [comment]
are you getting this as well? @groom7

**Comment by groom7** [comment]
> are you getting this as well? @groom7

Installing nodejs and npm helped me

**Comment by mike-rambil** [comment]
I think I did this too and was able to solve it as well during that time with this same method. I don't recall what I did, but this sounds like it!

Awesome!
