### ISSUE TITLE
Add a -q, --quiet option, and reduce the default level of verbosity.

### ISSUE THREAD

**Issue by nathanpeck** [Unitech/pm2#59]
pm2 is very verbose by default even without the -v, --verbose option. I feel that some of this default verbosity could be reduced and output only if the -v option is specified. Additionally, I feel pm2 needs a -q, --quiet option where it does not output to the console except in case of errors.

For an example of what I mean by reducing the default level of verbosity consider what happens when executing `pm2 stopAll`

```
$ pm2 stopAll
⌬ PM2 Stopping all processes
  ◡ Processing...

┌────────┬────┬─────┬────────┬───────────┬──────────────┬────────┬──────────┐
│ Script │ id │ PID │ status │ Restarted │ Last restart │ memory │ err logs │
└────────┴────┴─────┴────────┴───────────┴──────────────┴────────┴──────────┘
```

If pm2 stopped all processes then there shouldn't be any processes to list, and this process list below the command is useless nearly 100% of the time except perhaps if pm2 has a bug which caused a process to not be stopped.

This is just one example of where excessive console output could be trimmed out and only output if the user explicitly specifies the  -v option.

What are your thoughts on this? Does anyone else agree? If so I may spend some time creating a less verbose fork and submit a pull request.

**Comment by ryanjrose** [comment]
3 years later and here I am hoping for the same thing..

**Comment by Unitech** [comment]
`PM2_SILENT=true pm2 <command>`

**Comment by ryanjrose** [comment]
Ah, thats great!  Thanks!

**Comment by azarus** [comment]
> 3 years later and here I am hoping for the same thing..
4 years later i am wondering what is the issue when i only get this error:
`Deploy failed`
I think pm2 needs the oposite (more proper error logging than this..)
