### ISSUE TITLE
Keep scrips running with PM2 after closing the shell

### ISSUE THREAD

**Issue by louwers** [Unitech/pm2#593]
After starting my test.js using `pm2 start test.js` _or_ by spwaning it programmatically, everything seems to be working fine. My script slowly counts from 0 to 100 and passes the result to Firebase.

However, when I quit Terminal (the OS X app I use to ssh into my shared hosting server), the script does not keep running. I do not see the counter go up anymore when I look into my database. I might have misunderstood the purpose of PM2 completely, but is this supposed to happen? If you need more information I will be happy to provide it. Thanks!

![screen shot 2014-07-27 at 11 16 51 pm](https://cloud.githubusercontent.com/assets/649392/3715164/5c3d3300-15d3-11e4-89fd-6c399f84d043.png)

**Comment by marko-mlinarevic** [comment]
did you found out what was the issue
