### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Volox** [Unitech/pm2#6]
Running on windows i keep seeing `Launching daemon` but nothing happens.
I tried with the json file and manually with `pm2 start app.js` but with no luck.
Also `pm2 list` and the other commands give the same result.
I am doing something wrong?

Thanks.

OS: Win 7 x64
node: 0.10.3

**Comment by mike-aungsan** [comment]
I have the same problem on widows server.

**Comment by HalfdanJ** [comment]
I also still have this problem, also after installing the development branch

**Comment by echiu64** [comment]
Try setting PM2_HOME to your C:\Users\<username>\.pm2 directory (Win Vista/7/8)
Or take a simple one line patch described in this pull: https://github.com/Unitech/PM2/pull/982
