### ISSUE TITLE
Apache server error with pm2 & proxypass

### ISSUE THREAD

**Issue by fitamix** [Unitech/pm2#602]
I have an apache web server: Apache/2.2.3. 
I have configured a proxypass serving a NodeJS app. I run with pm2: pm2 start app.js 
Calling the apache, which in turn calls the proxypass that solves pm2, a high percentage of requests that are error: 
- (20014) Internal error: proxy: error reading status line from remote server localhost 
- Proxy: Error reading from remote server returned by "url" 

But if I run the same NodeJS application with supervisor, all goes well and does not give any error.

**Comment by djbobbydrake** [comment]
I am running into the same issue. Running Apache + PM2. Any insights other than switching to Nginx?

**Comment by dgielis** [comment]
did anybody find a solution for the issue when using Apache as reverse proxy for pm2?
