### ISSUE TITLE
Change location of configuration files/logs/pids... to standard file path for Unix like systems

### ISSUE THREAD

**Issue by Unitech** [Unitech/pm2#604]
Following [http://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard](http://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard)

PM2 configuration files will be located in /etc/pm2
Logs in `/var/log`
PID files in `/var/run`
PM2 dump file in `/var/lib`

**Comment by sgarbesi** [comment]
+1 for log files
