### ISSUE TITLE
Can't set debug port by specifying --node-args="--debug=7001"

### ISSUE THREAD

**Issue by MeanwhileMedia** [Unitech/pm2#610]
```
pm2 start main.js --node-args="--debug=7001"
```

When running the above cli command, the node process does receive the "--debug" argument, but ignores the port. The console responds:

```
Debugger listening on port 5863
```

I am assuming port #5863 is just a default selected by node. Any ideas why the port isn't getting set?

**Comment by HighSoftWare96** [comment]
In your PM2 configuration file I think you have to use this parameters:
"node_args": ["--inspect=localhost:YOUR_PORT_NUMBER"],

**Comment by Shogobg** [comment]
@HighSoftWare96 it's not working.

**Comment by lucrus73** [comment]
Same here, it's not working. I start my process with
    
    # pm2 start process.json

and here are the contents of `process.json`

    {
        "apps": [{
            "name": "myapp-debug",
            "script": "app.js",
            "watch": true,
            "exec_mode": "cluster",
            "cwd": "/srv/myapp/",
            "instances": 1,
            "merge_logs": true,
            "error_file": "/var/log/myapp/error.log",
            "out_file": "/var/log/myapp/out.log",
    	"node_args": ["--inspect=127.0.0.1:9230","--inspect-port=9230"],
            "env": {
               "MONGODB": "mongodb://admin:secret@localhost:27017/mydb",
               "TIMEZONE": "+01:00",
            }
        }]
    }

after starting it I get node listening on a different port (currently 9694, but it changes on every restart). I've already tried several variations such as specifying `--inspect` only, or leaving out the ip address, and the like, but it never listens on 9230.
I'm using pm2 version 5.2.0 and node version 14.19. 

Running `node --inspect=9230 app.js` does work as expected with the debugger listening on port 9230.

**Comment by lucrus73** [comment]
> Same here, it's not working. 

Never mind, it now works. I don't know what did to make it work (or what I was doing wrong), but it works.
