### ISSUE TITLE
Only start/restart/reload certain apps in the multi process processes.json

### ISSUE THREAD

**Issue by starsirius** [Unitech/pm2#624]
We [declare multiple apps](https://github.com/Unitech/pm2#json-app-declaration) (e.g. development, staging, production apps) in the processes.json file. Now it looks like doing `pm2 start processes.json` will start all the apps in the JSON file. Is there a way to start/restart/reload only certain apps defined in the process.json file? Otherwise, we will need to have multiple json files (one for each app) which doesn't really make sense. Thanks!

**Comment by ieugen** [comment]
+1 for this feature. I with to have multiple configurations in the same file: dev and production and start only dev locally. The difference between the environments are just environment variables for now, but not both applications should be started.

**Comment by ravi** [comment]
Anyone have a preference on the implementation? I am inclined to implement `pm2 start processes.json --only app1` or some version that works with PM2 option parsing, rather than an 'include' feature.

**Comment by runk** [comment]
+1 for `pm2 load processes.json`

**Comment by Telemakhos** [comment]
+1

**Comment by creynders** [comment]
:+1: for `pm2 load processes.json`

**Comment by leohihimax** [comment]
+1

**Comment by joergpatz** [comment]
+1 

any ideas/updates?

I also don't like to split the processes.json. My use case is that I define the [webpack-dev-server](https://webpack.github.io/docs/webpack-dev-server.html) in the processes.json which pm2 shouldn't start for production.

**Comment by Unitech** [comment]
Would something like this work for you:?

```bash
$ pm2 restart process.json <application-name>
```

**Comment by joergpatz** [comment]
Yes!

`pm2 start processes.json <app-name>*`  would be great!

_*single or list of app-names_

**Comment by Unitech** [comment]
Finally it's going to be 

```
$ pm2 restart process.json --only <application-name>
```

It's more explicit

**Comment by Unitech** [comment]
available in dev branch

**Comment by Unitech** [comment]
Available in the latest PM2 version,

Doc: http://pm2.keymetrics.io/docs/usage/application-declaration/#act-on-specific-process
Tests: https://github.com/Unitech/pm2/blob/master/test/bash/json_file.sh#L89

**Comment by joergpatz** [comment]
Great, Thank you!

**Comment by EvanCarroll** [comment]
@Unitech is there a method of disabling an app without deleting the entry in process.json, such as for a non-paying customer?

**Comment by ravi** [comment]
Hmm, am I doing something wrong or did this option disappear between 10.x and 15.x?
```
$ pm2 --version
0.10.7
$ pm2 help | grep only
    --only                               Start only a specific process from JSON file
```
```
$ pm2 --version
0.15.7
$ pm2 help | grep only
$
```

**Comment by lekhnath** [comment]
--only does not work with rundev .
I tried rundev ecosystem.config.js --only API but not filtering

**Comment by 360disrupt** [comment]
The [docs](http://pm2.keymetrics.io/docs/usage/process-management/) are misleading imho. I frist tried: `pm2 start <json> --name <name>` which started all apps instead of `pm2 start <json> --only <name>`

**Comment by geoshar** [comment]
`--only` works only for one process, would be nice an improve of this like: `--only process1 process2`
and maybe some regular expressions here;)

**Comment by wallet77** [comment]
@geoshar  it's already done in latest version.

`$ pm2 start ecosystem.json --only "app1,app2"`

**Comment by MattiasMartens** [comment]
This does not work with `pm2 deploy`. My use case is that I have some worker processes that I only want to run in certain environments. I can make the processes terminate themselves if they are not in the correct environment, but that feels like a hack.
