### ISSUE TITLE
How to programmatically pass env variables

### ISSUE THREAD

**Issue by gorangajic** [Unitech/pm2#645]
I want to start app programmatically and pass some env variables, how to do that ?

Sorry for asking question here but I have looked at the source and can't figure that out

**Comment by erhhung** [comment]
It doesn't look like the underlying issue of not being able to pass the root environment variables *as-is* to the worker processes (at least in clustered mode) is resolved. While in `main.js` I can call `pm2.start()` with settings *added* to `env`, and those do show up in the worker `app.js`, what if I have unset certain vars in the root environment which I don't want in the worker?

For example, I define, by default, `http_proxy` in my `.bash_profile`, but I also have handy bash functions `proxyon/proxyoff` that set and unset that and all proxy related variables in my current environment. If I unset `http_proxy`, I expect that not show up in the worker process, but that's not what I'm seeing. I can verify in `main.js` that `process.env` does not contain `http_proxy`, and I've even called `pm2.start()` with `{env: process.env}`, but, again, that seems only to have an additive effect.

**Comment by ylligashi** [comment]
PM2 docs can help you:
http://pm2.keymetrics.io/docs/usage/pm2-doc-single-page/
