### ISSUE TITLE
Pass parameters to the node app via command

### ISSUE THREAD

**Issue by Globegitter** [Unitech/pm2#652]
I have seen you can define `args` in the `processes.json`, but it would be really ideal to pass arguments directly to the app, ideally how forever does it, or otherwise exactly how the `--node-args` flag works.

To give a proper example, I can run my SailsJS app with certain parameters like `sails lift --prod` or `sails lift --verbose` I would love to somehow run `pm2 start app.js --prod` or `pm2 start app.js --args="--prod"`

Or is that somehow already possible?

**Comment by souravtyson** [comment]
i tried to run the node application with pm2 as 
`pm2 start pm2.config.json -- --prod --prof`

but the prof file is not generated.
Can anyone help me with this
