### ISSUE TITLE
Too Many Unstable Restarts

### ISSUE THREAD

**Issue by 58bits** [Unitech/pm2#659]
Hi all - I have a node server which runs fine under forever, and will 'start' under PM2, however, as soon as the first request hits the server - the PM2 errors out with the message...

Script index.js had too many unstable restarts (15). Stopped. "errored"

I'm starting the server in 'forked' mode (under node v0.10.31) with the following...

NODE_ENV=production pm2 start index.js -xn 'myapp'

The error log file contains...

node: ../deps/uv/src/unix/core.c:701: uv__io_stop: Assertion `loop->watchers[w->fd] == w' failed.

The only thing that's a little different about this server, is that it's listening on two ports (there are two node createServer commands each on a different port - one for api access and the other for gui access)

Any ideas?

**Comment by levicoradine** [comment]
Sorry to resurrect this, but I'm experiencing a seemingly similar situation:

```2021-02-26T18:24:59: PM2 log: App [foo-server:2] exited with code [0] via signal [SIGKILL]
2021-02-26T18:25:03: PM2 log: App [foo-server:2] starting in -cluster mode-
node: ../deps/uv/src/unix/core.c:930: uv__io_stop: Assertion `loop->watchers[w->fd] == w' failed.
./cmd.sh: line 39:    16 Aborted                 (core dumped) pm2-runtime "${PM2_ECOSYSTEM_FILE}"
``` 

This is for an app built into a `FROM node:14-buster` Docker container, where our install basically is this:

```RUN DEBIAN_FRONTEND=noninteractive && \
  apt-get update -y && \
  apt-get -y install mdbtools ncat && \ 
  apt-get clean && \
  npm install -g pm2 npm@7 && \
  npm install --production && \
  pm2 install pm2-logrotate && \
  pm2 set pm2-logrotate:max_size 1M && \
  pm2 set pm2-logrotate:compress true && \
  pm2 set pm2-logrotate:retain 7
```

Any insights would be welcome. Thanks.

**Comment by olawalejuwonm** [comment]
Also having this issue.

Any solution please?

> Sorry to resurrect this, but I'm experiencing a seemingly similar situation:
> 
> ```
> events.js:292
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: write EPIPE
>     at process.target._send (internal/child_process.js:832:20)
>     at process.target.send (internal/child_process.js:703:19)
>     at sendHelper (internal/cluster/utils.js:27:15)
>     at send (internal/cluster/child.js:199:10)
>     at EventEmitter.cluster._setupWorker (internal/cluster/child.js:49:3)
>     at initializeClusterIPC (internal/bootstrap/pre_execution.js:345:13)
>     at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:67:3)
>     at internal/main/run_main_module.js:7:1
> Emitted 'error' event on Worker instance at:
>     at process.<anonymous> (internal/cluster/worker.js:30:12)
>     at process.emit (events.js:315:20)
>     at internal/child_process.js:836:39
>     at processTicksAndRejections (internal/process/task_queues.js:75:11) {
>   errno: -32,
>   code: 'EPIPE',
>   syscall: 'write'
> }
> 2021-02-26T15:01:26: PM2 log: App [svcs-server:1] exited with code [1] via signal [SIGINT]
> 2021-02-26T18:25:03: PM2 log: App [foo-server:2] starting in -cluster mode-
> node: ../deps/uv/src/unix/core.c:930: uv__io_stop: Assertion `loop->watchers[w->fd] == w' failed.
> ./cmd.sh: line 39:    16 Aborted                 (core dumped) pm2-runtime "${PM2_ECOSYSTEM_FILE}"
> ```
> 
> This is for an app built into a `FROM node:14-buster` Docker container, where our install basically is this:
> 
> ```
>   apt-get update -y && \
>   apt-get -y install mdbtools ncat && \ 
>   apt-get clean && \
>   npm install -g pm2 npm@7 && \
>   npm install --production && \
>   pm2 install pm2-logrotate && \
>   pm2 set pm2-logrotate:max_size 1M && \
>   pm2 set pm2-logrotate:compress true && \
>   pm2 set pm2-logrotate:retain 7
> ```
> 
> Any insights would be welcome. Thanks.
