### ISSUE TITLE
pm2 hangs after starting a process

### ISSUE THREAD

**Issue by pedily** [Unitech/pm2#661]
Everything works fine until i launch a script.
The script is up and running, but as soon as it runs i am unable to launch pm2 with any option, it just does not react until i reboot the server.

$pm2 list -> shows empty list
$pm2 start server.js -> starts script and shows list with one entry
$pm2 save -> nothing, have to ctrl+c
$pm2 list -> nothing, have to ctrl+c

I am running a VPS with ubuntu 14.04.
I installed pm2 with sudo and the --unsafe-perm flag

**Comment by dptole** [comment]
I had the same problem: the pm2 process just stuck before deletingProcessId or any other call. The only way for me to solve this problem was to `kill -9 <PID_OF_PM2>`.

**Comment by michaelBenin** [comment]
Just wanted to add a note here, if you're booting your app up and waiting for connections to be made in an initializer before load balancing traffic, if you don't emit the ready event from your process and in the pm2 config have `wait_ready` set to true, then this will reproduce the same behavior above. To emit the ready event, here's an example:

```
const startServer = () => {
  const server = createOrGetServer().listen(port, () => {
    log.info(
      {
        port
      },
      'Server is running.'
    );
  });
 
  // emit ready event
  process.send('ready');
  setServer(server);
};
```

**Comment by yogithesymbian** [comment]
i have same issue on this day , its hangs and cannot delete all cannot kill
