### ISSUE TITLE
Promisify CLI programmatic interface

### ISSUE THREAD

**Issue by Unitech** [Unitech/pm2#663]
Promisify CLI programmatic interface via ES6 builtin Promises (http://www.html5rocks.com/en/tutorials/es6/promises/) and so activate harmony by default for PM2

**Comment by rumkin** [comment]
👍 Vote for promise interface. It's the de facto standard.

**Comment by Unitech** [comment]
You can use bluebird to promisify [the current available API](http://pm2.keymetrics.io/docs/usage/pm2-api/)
https://gist.github.com/59naga/931a71306859f041f5f9
