### ISSUE TITLE
startOrRestart command is targeting the wrong process

### ISSUE THREAD

**Issue by binarykitchen** [Unitech/pm2#678]
When I run `pm2 startOrRestart ./etc/pm2/development.json` I can see afterwards on `pm2 ls` that it has restarted a different process and stopped the one I wanted to restart.

Looks like a serious bug. The `startOrRestart` command seems to target the wrong process. It should parse the given json and respect it.

Make sure you have a test case for this scenario. Thanks!

**Comment by vmarchaud** [comment]
Should be working on newest pm2 version ;)
Open a new issue if anyone still have the problem
