### ISSUE TITLE
Too many unstable restarts

### ISSUE THREAD

**Issue by binarykitchen** [Unitech/pm2#686]
```
Entering in fork mode
Script /var/www/videomail-gith/server.js 2 exit
Script /var/www/videomail-gith/server.js had too many unstable restarts (15). Stopped. "errored"
```

How come? What does this mean "unstable restart"? This is happening when I am restarting another app named dev.videomail.io, see ticket https://github.com/Unitech/PM2/issues/678

**Comment by rpavez** [comment]
This problem seems to be happening when using filenames like processes.json.dev, processes.json.production, processes.json.stage, doesn't seems to happen when using just process.json.
