### ISSUE TITLE
Neat feature: Listen to GitHub webhooks

### ISSUE THREAD

**Issue by binarykitchen** [Unitech/pm2#693]
If pm2 could listen to GitHub webhooks, run a pre-defined deployment script and restart the PM2 process at the end, that would be awesome!

Have you ever considered this? Or is already a solution for that out there? At the moment I am using https://www.npmjs.org/package/gith which is pretty old and adds more work for me.

**Comment by lgomez** [comment]
@binarykitchen Hi. I'm about to try to add a simple web server running a hook that github calls. That hook could exec `pm2 forward` or something like that on the server. Not sure it works but plan on trying it. Have you had any luck setting yours up? I don't think I can run deploy from within the deployment server. I use deploy from my local environment. I'll share if it works.

**Comment by jshkurti** [comment]
Use `pm2 pull` instead.

**Comment by binarykitchen** [comment]
@jshkurti Pull? Couldn't find any documentation on that command in the readme ...

**Comment by carnesen** [comment]
Dunno about the readme but it's described as such in the command-line help:

"pull <name> [commit_id]                                    updates
repository for a given app"

**Comment by jshkurti** [comment]
https://github.com/Unitech/PM2/blob/master/doc/PULL.md

**Comment by oowl** [comment]
Hey, I just made [pm2-webhook](https://www.npmjs.com/package/pm2-webhook) module. It creates listeners for webhooks and executes `pm2 pull <app name>` right after your push. Hope it will be usefull.

**Comment by binarykitchen** [comment]
cool thanks @oowl
