### ISSUE TITLE
How to install pm2 into a non-network RedHat6.5 enviroment?

### ISSUE THREAD

**Issue by Susan-liu** [Unitech/pm2#698]
I want to install nodejs and pm2 to the non-network Redhat6.5 enviroment.
I have installed nodejs by  tar  the node-v0.10.13.tar.gz , ./configure and make & make install command.
But i can't install pm2 by the same command because there are no configure file in pm2-0.5.6.tgz.
Can anyone tell me if there have a way to solve the problem?

and 
I find another way to install pm2 into the non-network Redhat enviroment.(following method)
   Step1. copy /usr/local/lib/node_modules/pm2（another CentOS 6.4 server which has been installed nodejs and pm2) , and paste the pm2 folder to the non-network Redhat6.5 enviroment into  the same directory.
   Step2.  execute the command: ln -s /usr/local/lib/node_modules/pm2/bin/pm2 /usr/local/bin/pm2
With the Step1,Step2, i can execute the command "pm2 start" at the non-network RedHat6.5.
But i don't know whether this method is feasible, and if there have any potential problems.

**Comment by jhakasjk** [comment]
What exact command should i write to install pm2 via npmbox?

**Comment by jaygithub18** [comment]
Need latest pm2 package, where can I get that ?

**Comment by FrankGoortani** [comment]
Do `npm-bundle pm2` on a machine that has access to internet, then copy the zip file to your server and do `npm i pm2-[version].tgz`
