### ISSUE TITLE
Fork mode? 

### ISSUE THREAD

**Issue by MrScruffyish** [Unitech/pm2#700]
Hi.
I just tried to start my app and I got the message

[PM2] You shouldn't use the cluster_mode with node 0.10.x. Instead use fork mode with -x

I find the documentation kind of short on this for those not very technical

What does this mean? 

I have two scenarios where I start with
pm2 foo.js -i 1
pm2 bar.js -i 3

what should I use instead to take advantage of multiple cores in the case of bar.js ?

**Comment by svidhani** [comment]
What is the difference between fork mode and cluster mode?

**Comment by Unitech** [comment]
rtfm http://pm2.keymetrics.io/
