### ISSUE TITLE
support for npm-config?

### ISSUE THREAD

**Issue by ahmadnassri** [Unitech/pm2#702]
setting [environment configs](https://www.npmjs.org/doc/cli/npm-config.html) through `package.json` and `~/.npmrc` is ignored when running with `pm2` (unless I missed something obvious)

**Comment by xpepermint** [comment]
+1

**Comment by xpepermint** [comment]
This https://github.com/Unitech/pm2/issues/1317#issuecomment-143426394 is related topic.

**Comment by xpepermint** [comment]
any progress?
