### ISSUE TITLE
pm2 logs & bunyan

### ISSUE THREAD

**Issue by iliakan** [Unitech/pm2#709]
With bunyan logger, logs come in JSON.
Usually I watch them with `tail -f my.log | bunyan -o short`, so that `bunyan` CLI utilify parses and nicely shows JSON for me.

But PM2 adds a prefix to each record, so `bunyan` can't parse it any more.
Is there a way to use `pm2 logs` with `bunyan` filtering?

**Comment by aishwar** [comment]
May be a little late, but for people who want to use "pm2 logs" and still see the buynan formatted output, you could do this:

    pm2 logs <app> | grep -o '\{.*' | bunyan

That strips out the pm2 appended appname in front of each of the log line, so the output becomes valid JSON per line and the bunyan CLI can parse and print a formatted line.

**Comment by raine** [comment]
pm2 logs could have an option to not prefix logs?

**Comment by hertzg** [comment]
@raine I agree that options would be nice

**Comment by raine** [comment]
Currently it's difficult to get application's logs out of `pm2 logs` without decoration (timestamp or app name etc.). I couldn't figure out a trivial sed or grep pattern that would do the job.

**Comment by MichielDeMey** [comment]
+1 for the `--raw` option as proposed by @raine.

**Comment by purgna** [comment]
+1 for --raw please.

**Comment by GDownes** [comment]
+1 for --raw

**Comment by GDownes** [comment]
jshkurti confimed in the feature request issue #1189 thread. "Feature request: PM2 logs raw format" that a raw format will be provide in the next release. https://github.com/Unitech/PM2/issues/1189#issuecomment-94468812

**Comment by jshkurti** [comment]
Do you wish to keep PM2 logs showing when the `--raw` param is passed ?
```
PM2: 2015-04-21 16:00:40: App name:server id:0 exited with code 1
PM2: 2015-04-21 16:00:40: Starting execution sequence in -fork mode- for app name:server id:0
PM2: 2015-04-21 16:00:40: App name:server id:0 online
```

**Comment by raine** [comment]
For bunyan use case it doesn't matter because you can say `--strict` to suppress lines unintelligible to bunyan.

**Comment by GDownes** [comment]
I agree with raine, keeping them showing wouldn't affect the bunyan use case.

**Comment by jshkurti** [comment]
Here we go https://github.com/Unitech/PM2/pull/1201

Can you give it a try ? `npm i -g git://github.com/Unitech/PM2#raw_logs`

It will be included in the next release ;)

**Comment by astephensen** [comment]
Works perfectly here running `pm2 logs --raw | bunyan` :+1:

**Comment by astanciu** [comment]
My app outputs color coded logs and this --raw option seems to strip that away. Any chance we can really get the raw logs, so originating colors will still work?

**Comment by iamsebastian** [comment]
Same question here, as @astanciu already mentioned. Any possibility to keep colors from `debug`/`chalk` package?

**Comment by barkthins** [comment]
how about a small hook so that logs will display via bunyan without stripping anything or removing colors?

**Comment by jackishere** [comment]
`pm2 logs --raw |bunyan -o short`

makes the different

**Comment by shuperry** [comment]
I tried, this command works:

pm2 logs --raw --name kingnoshop-api| bunyan

kingnoshop-api is my app name.

**Comment by zamrokk** [comment]
`pm2 logs --raw |bunyan`  👍

**Comment by bidadh** [comment]
`pm2 logs --raw |bunyan` works

**Comment by tinybug** [comment]
great!

**Comment by jtchallenga** [comment]
Does `pm2 logs --raw |bunyan` not work anymore?
PM2 is prefixing the raw output with a timestamp, and I'm not sure how to stop this.

**Comment by raine** [comment]
@jtchallenga I am not getting timestamps on version 2.4.2.

**Comment by jtchallenga** [comment]
Ah, figured it out. 
I am loading my app via an ecosystem.json, where I needed specify `"log_date_format": ""` instead of another value.

**Comment by mwakerman** [comment]
Is it possible to set `raw: true` in process file to have pm2 logs to the console without the processId and name prefix? Our use case is that we are using pm2-docker and logspout to ship our logs into logstash and the pure json logs are much easier to parse.

**Comment by mwakerman** [comment]
Thanks @vmarchaud, unfortunately that doesn't remove the `id` and `App name` prefix. So we still get something like:
```
0|api      | {
0|api      |   "level": "info",
0|api      |   "message": "::ffff:172.19.0.6 - - [30/Aug/2017:09:30:23 +0000] \"POST /api/v1/auth/logout HTTP/1.1\" 204 - \"https://domain.tech/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.109 Safari/537.36\" -\n",
0|api      |   "timestamp": "2017-08-30T09:30:23.566Z"
0|api      | }
0|api      | {"message":"{\n  \"level\": \"info\",\n  \"message\": \"::ffff:172.19.0.6 - - [30/Aug/2017:09:31:28 +0000] \\\"POST /api/v1/auth/login HTTP/1.1\\\" 200 155 \\\"https://domain.tech/login\\\" \\\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.109 Safari/537.36\\\" 3c285e4b-575c-4044-9d41-ed7e5a881f8e\\n\",\n  \"timestamp\": \"2017-08-30T09:31:28.312Z\"\n}\n","timestamp":"2017-08-30T09:31:28.313Z","type":"out","process_id":0,"app_name":"api"}
0|api      | {"message":"{\n  \"level\": \"info\",\n  \"message\": \"::ffff:172.19.0.6 - - [30/Aug/2017:09:31:28 +0000] \\\"GET /api/v1/document/previews HTTP/1.1\\\" 200 496 \\\"https://domain.tech/document\\\" \\\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.109 Safari/537.36\\\" 3c285e4b-575c-4044-9d41-ed7e5a881f8e\\n\",\n  \"timestamp\": \"2017-08-30T09:31:28.364Z\"\n}\n","timestamp":"2017-08-30T09:31:28.365Z","type":"out","process_id":0,"app_name":"api"}
```

Note the `0|api      | ` at the beginning of every line.

**Comment by vmarchaud** [comment]
@mwakerman Can you share your process file ?

**Comment by mwakerman** [comment]
It's an express js and I'm using winston for console logging with `json: true`. To get the above, my process file looks like:

```
$ cat ecosystem.config.js
module.exports = {
  apps : [
    {
      name      : 'api',
      script    : 'bin/www',
      exec_mode  : 'cluster',
      instances: 2,
      log_type: 'json'
    },
  ],
};
```

**Comment by vmarchaud** [comment]
@mwakerman And which binary are you using to start this proces flie (also the flags you are giving to it) ?

**Comment by mwakerman** [comment]
I'm using `pm2-docker` and `pm2-docker start ecosystem.config.js` to start the process (no other flags).

**Comment by vmarchaud** [comment]
@mwakerman You should use `pm2-docker start ecosystem.config.js --raw --auto-exit`. `--raw` to delete the prefix and `--auto-fix` so PM2 can exit when there is no more processes running

**Comment by mwakerman** [comment]
To be clear, the issue is with the console logs (rather than the file logs, which are well formatted when using `raw: true` in the process file).

**Comment by vmarchaud** [comment]
Yes, its the `pm2-docker` binary that need to have the option to stream the logs without prefix, see https://github.com/Unitech/pm2/blob/master/lib/binaries/Runtime4Docker.js#L21

**Comment by felipekm** [comment]
I ended with (had to install bunyan globally):

`pm2 logs <app_name> | bunyan -o short`
