### ISSUE TITLE
pm2 doesn't stop app

### ISSUE THREAD

**Issue by pkopac** [Unitech/pm2#715]
Hi!

Problem: "stop" doesn't work properly.
node version: v0.10.29
pm2 version: 0.10.7

Scenario:
1) run the app from json config: _pm2 start json_
2) access app from browser
3) stop app: _pm2 stop app-name_
4) try to access it in web browser again: **it still runs**
5) after a while pm2 restarts the app, it gets a new PID.

This is very strange. Why doesn't pm2 kill the app? Why does it restart the app instead?

I'm also using a PID file in configuration - the file stays there, even though pm2 list tells me the app is "stopped".

Thank you for feedback!

**Console output:**
pkopac@x:~$ pm2 stop app-name
[PM2] Stopping app-name
[PM2] Stopping process by name app-name
┌────────────┬────┬──────┬──────┬─────────┬───────────┬────────┬────────┬─────────────┐
│ App name   │ id │ mode │ PID  │ status  │ restarted │ uptime │ memory │    watching │
├────────────┼────┼──────┼──────┼─────────┼───────────┼────────┼────────┼─────────────┤
│ app-name │ 0  │ fork │ 7376 │ stopped │         0 │ 0      │ 0 B    │ unactivated │
└────────────┴────┴──────┴──────┴─────────┴───────────┴────────┴────────┴─────────────┘
 Use `pm2 desc[ribe] <id>` to get more details
pkopac@x:~$ pm2 list
┌────────────┬────┬──────┬──────┬─────────┬───────────┬────────┬────────┬─────────────┐
│ App name   │ id │ mode │ PID  │ status  │ restarted │ uptime │ memory │    watching │
├────────────┼────┼──────┼──────┼─────────┼───────────┼────────┼────────┼─────────────┤
│ app-name │ 0  │ fork │ 7376 │ stopped │         0 │ 0      │ 0 B    │ unactivated │
└────────────┴────┴──────┴──────┴─────────┴───────────┴────────┴────────┴─────────────┘
 Use `pm2 desc[ribe] <id>` to get more details
pkopac@x:~$ pm2 list
┌────────────┬────┬──────┬──────┬────────┬───────────┬────────┬─────────────┬─────────────┐
│ App name   │ id │ mode │ PID  │ status │ restarted │ uptime │      memory │    watching │
├────────────┼────┼──────┼──────┼────────┼───────────┼────────┼─────────────┼─────────────┤
│ app-name │ 0  │ fork │ 7398 │ **online** │         1 │ 14s    │ 43.020 MB   │ unactivated │
└────────────┴────┴──────┴──────┴────────┴───────────┴────────┴─────────────┴─────────────┘
 Use `pm2 desc[ribe] <id>` to get more details

**Comment by DomeQdev** [comment]
I have same problem

**Comment by DomeQdev** [comment]
- [ ] 

- [ ] 

- [ ] 

- [ ]
