### ISSUE TITLE
Unix socket owner, not the "run-as-user" user

### ISSUE THREAD

**Issue by jfbelisle** [Unitech/pm2#716]
I manage PM2 with the root user and start my node app with the run_as_user and run_as_group flags.

So when the app is started with those flags set for a different user than root, everything is ok except that the socket created is own by root and not the specify user. This is causing me problems since i'm using Apache which is proxying the specify user to the socket but it doesn't have any rigths on it.

```
"apps" : [
    {
        "name"        : "otherUser",
        "cwd"         : "/home/otherUser/public_html/nodejs",
        "script"      : "app.js",
        "watch"       : "false",
        "run_as_user" : "otherUser",
        "run_as_group": "apache",
        "exec_mode"   : "cluster_mode",
        "error_file" : "./logs/child-err.log",
        "out_file"   : "./logs/child-out.log",
        "pid_file"   : "./logs/child.pid",
        "instances"   : "1",
        "env": {
            "NODE_ENV": "development"
        }
    }
]
```

I think to socket creation should take into account the run_as_user flag for socket creation.

**Comment by zxqfox** [comment]
Still beta? ;-(
