### ISSUE TITLE
Node 0.10.x - Port still in use after a "pm2 stop :id"

### ISSUE THREAD

**Issue by stumpyfr** [Unitech/pm2#74]
When I kill a pm2 process (http server with expressjs) with the kill command and try to restart the same process without pm2 I get:

```
server started on port 4242
   warn  - error raised: Error: listen EADDRINUSE

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at Server.listen (net.js:1127:5)
```

If I start the process with pm2, everything is working.

To be able to start the process without pm2, I need to kill the pm2 demon process: 'pm2: Satan Daemonizer'.

Not very practical :).

**Comment by dlinx** [comment]
Same problem with pm2 0.12.10
Tried with pm2 stop, pm2 restart, pm2 kill.

pm2 is not killing process if the process is running for few days and when I restarted that application using pm2 restart. I needed to kill node process manually from task manager.

platform: Windows server x64
pm2 version: 0.12.10

**Comment by jshkurti** [comment]
Give it a try with PM2 v0.12.15 and Node.js >= 0.11.x

**Comment by ChrisCTX** [comment]
Suffering the same thing as the original post.

PM2 0.14.2
Node v0.12.4
Windows 8

Because of it. automatic reloading also fails and thus is unusable.
Only way to start my server again is to kill the node process from task manager and start again.

Any logs or files that I can help with to try and find a solution?

**Comment by mikkotikkanen** [comment]
Same here. 

Windows 7
pm2 0.14.3
node 0.12.2
npm 2.7.4

It fails to kill the process, only way to get the port free again is to manually kill the node.exe from process manager.


This is what the `pm2 logs` shows when trying to do `pm2 restart app`
```
PM2 Stopping app:app id:0
PM2 7620 pid can not be killed { [Error: kill ESRCH] code: 'ESRCH', errno: 'ESRCH', syscall: 'kill' }
PM2 Starting execution sequence in -fork mode- for app name:app id:0
PM2 App name:app id:0 online
```

**Comment by axelboc** [comment]
Same issue and `ESRCH` error with the following config:

- Windows 8.1
- pm2 0.14.5
- node 0.12.4
- npm 2.11.3

**Comment by EddieOne** [comment]
+1

**Comment by jshkurti** [comment]
@EddieOne you're on Windows as well ?

**Comment by axelboc** [comment]
Not sure if it matters at all, but my app does real-time things with [Primus](https://github.com/primus/primus). I tried listening for the shutdown signal and gracefully closing the Express and Primus servers, but it didn't fix the issue.

**Comment by EddieOne** [comment]
@jshkurti no I tried pm2 on a linux machine. My app is using socket.io and pm2 clustering. Same problem though.

**Comment by l0oky** [comment]
+1

**Comment by nesukun** [comment]
+1
node v0.12.7
pm2 0.15.10
osx 10.11.1

**Comment by EddieOne** [comment]
I wonder, does this always happen on machines that also have forever globally installed?

**Comment by alxpereira** [comment]
+1 
Amazon Web Services linux OS
node v0.10.36
pm2 0.15.10

**Comment by sayak-sarkar** [comment]
+1
RHEL7
node v0.10.36
pm2 1.0.0
I literally need to reboot the server every time a process goes rogue since trying to do a `kill -9 <PID>` based upon the output of `netstat -nltp |  grep 3000` says Process doesn't exist, yet somehow blocking my port 3000!

**Comment by alxpereira** [comment]
FYI, found a possible source of problem on cloud servers. 
pm2 was launched by default as a sudo process in my automatic script, so when I was trying to relaunch one as a normal user I should be careful to use sudo.

Note : pm2 isn't the same using sudo & no-sudo users

**Comment by milabs** [comment]
+1
ArchLinux
node v5.5.0
npm  v3.5.3

Using `pm2 stop ID` for the node process doesn't stop it and 3000 port still available.
~~~
{
    "name": "app",
    "script": "/usr/bin/npm",
    "args": "start",
    "cwd": "/opt/xxx/var/node/app",
    "restart_delay": 1,
    "watch": false
}
~~~

**Comment by leonardodelfino** [comment]
+1

**Comment by cmal** [comment]
+1
$ uname -a
Linux jd-www 2.6.32-573.8.1.el6.x86_64 #1 SMP Tue Nov 10 18:01:38 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ node -v
v8.9.3

$ pm2 -v
2.9.1
