### ISSUE TITLE
pm2 crashes if trying to shut down a process with a port conflict issue

### ISSUE THREAD

**Issue by solarfly73** [Unitech/PM2#740]
pm2 crashes when trying to shut down/clean up a process that has declared it runs on a port that is actually owned by another system process.

Steps to reproduce:
1. Define a node service that uses port 80.
2. Install nginx or apache and run it on port 80.
3. State in the JSON that the service runs on port 80
4. pm2 start process.json   (the process won't be able to start due to a port conflict)
5. pm2 stop the process

Result: pm2 0.92 crashes with a backtrace and pm2 0.10.8 just hangs.  This hangs the system indefinitely on a shutdown and trashes the pm2 dump file so that processes won't start up again unless you specify the json.

0.92 backtrace:
assert.js:92
throw new assert.AssertionError({
          ^
AssertionError: false == true
    at ChildProcess. (child_process.js:372:7)
    at ChildProcess.emit (events.js:117:20)
    at handleMessage (child_process.js:349.11)
    at Pipe.channel.onread (child_process.js:349:11)

pm2 0.10.8 as stated just prints the [OK] stopping bla bla  and hangs.

**Comment by soyuka** [comment]
Closing, +15 days waiting.
