### ISSUE TITLE
Method to provide arguments should be documented

### ISSUE THREAD

**Issue by basicallydan** [Unitech/pm2#749]
#13's fix introduced the ability to do this:

```
pm2 start app.js -- --param
```

But it's not documented in the readme or wiki. Not sure what the general approach is for documentation, but I'd be happy to slap it in the readme somewhere if @Unitech doesn't have a problem with it!

**Comment by majgis** [comment]
That link above is broken.  The link on the ADVANCED_README.md page is broken as well and there is no content I can find to link to.  I was only able to glean this information from these github issues.

**Comment by soyuka** [comment]
I think it has moved there : http://pm2.keymetrics.io/docs/usage/pm2-doc-single-page/

**Comment by majgis** [comment]
Yes, thank you: http://pm2.keymetrics.io/docs/usage/pm2-doc-single-page/#42-ways-of-starting-processes

**Comment by OnkelTem** [comment]
How to pass a parameter via command line to an app when using application declaration JSON file like it was described in here: http://pm2.keymetrics.io/docs/usage/application-declaration/ ?
Say I'd like to have single app.json file and pass parameters via `pm2 start app.json -- -a -b -c`. But this doesn't work (which seems like a bug for me)

**Comment by coldlamper** [comment]
I too am unable to get the following syntax to work
```
pm2 start app.js -- -a -b -c
```
If `console.log('process.argv', process.argv);` in app.js I get something similar to 
```
process.argv [ '/home/brian/.nvm/versions/node/v5.1.1/bin/node',
app-0   '/home/brian/.nvm/versions/node/v5.1.1/lib/node_modules/pm2/lib/ProcessContainerFork.js' ]

```

**Comment by gregglind** [comment]
#567 discusses this as well.
