### ISSUE TITLE
upstream prematurely closed connection while reading response header from upstream

### ISSUE THREAD

**Issue by craigrosborne** [Unitech/pm2#754]
Hi

We are running an express app and we are randomly seeing these errors returned to our NGINX request proxy and all requests. If we just run the application under node we don't have any issues. We are starting the application as follows

pm2 start /var/www/xxx/wwwapi/app.js -i 1 --name "xxx.webapi" --watch -o /var/log/www/xxx/wwwapi/stdout.log -e /var/log/www/xxx/wwwapi/stderr.log -p /var/log/www/xxx/wwwapi/pid.log -- port=8085 host=0.0.0.0 platformKey=xxxx debugOutput=true

I am running version 0.9.5

Thanks
Craig

**Comment by lltb** [comment]
@craigrosborne thank u, I encountered exactly the same problem as yours.

**Comment by ahmed56734** [comment]
it's 2023 and I got the same issue @craigrosborne
