### ISSUE TITLE
Multiple instance of an app (in fork mode) bound to different ports + load balancing using nginx

### ISSUE THREAD

**Issue by zeusdeux** [Unitech/pm2#765]
So this isn't an issue per se but I haven't been able to find data on this and would appreciate the help.

The idea is to run multiple instance of the same app (in fork mode) bound to different ports using pm2, on a single machine. The requests to these apps will be load balanced using nginx as a reverse proxy.

I run the first instance using the following command:

``` javascript
APP_PORT=3000 pm2 start -x ./bin/server --name "app1"
```

This works fine. But when I do:

``` javascript
APP_PORT=4000 pm2 start -x ./bin/server --name "app2"
```

I get an error saying:

``` javascript
[PM2] [ERROR] Script already launched, add -f option to force re execution
```

How do I start multiple instances of the same app bound to different ports on a the same machine using pm2?

Thanks in advance!

**Comment by dtouch3d** [comment]
@Unitech Can you please elaborate on json5 and how it affects this issue ? I can't find anything like repeating the same config block over and over again with slight variations, as this is what is usually needed in these cases.

**Comment by matt212** [comment]
Hi,
I am new nginx and i wanted to  load balance my nodejs webapp using nginx and there are load of confusing articles about it  is there any stream line walkthrough for nginx for nodejs webapps in localhost based system ? 
 pm2 clustering is good but when i perform apache benchmark test the result for static content are poor !
cluster screen grab 
![screenshot from 2016-02-27 17 57 27](https://cloud.githubusercontent.com/assets/1698139/13374272/854cf666-dd4d-11e5-86be-216136f87e71.png)
and apache benchmark screenshot
![screenshot from 2016-02-27 10 31 07](https://cloud.githubusercontent.com/assets/1698139/13374277/9a612428-dd4d-11e5-9d5c-92a128200fa1.png)

**Comment by ChStark** [comment]
one workaround that surprisingly worked for me is creating symlinks

**Comment by Zaggen** [comment]
I personally run multiple instances of my app in different ports with pm2, i name the instance after the port, like 'myapp:8080' and i have a js loadbalancer and the nginx on lets say por 1337, then the nginx forwards the traffic from the port 80 and serves the static files.

This is the load balancer i created for that, it uses redis to register and unregister servers, feel free to use it.

https://gist.github.com/Zaggen/bbec82153f45ec60a136dca8e9ed65e7

**Comment by pinich** [comment]
Here is a really useful tutorial on how to implement clustering in PM2 [https://keymetrics.io/2015/03/26/pm2-clustering-made-easy/](https://keymetrics.io/2015/03/26/pm2-clustering-made-easy/)

🔢

**Comment by rocksconnect** [comment]
{
   "apps":[
      {
         "name":"development",
         "script":"./server.js",
         "env":{
            "NODE_ENV":"development",
            "PORT":3000,

         }
      },
      {
         "name":"production",
         "script":"./server.js",
         "env":{
            "NODE_ENV":"production",
            "PORT":80,

         }
      },
      {
         "name":"staging",
         "script":"./server.js",
         "env":{
            "NODE_ENV":"staging",
            "PORT":4000,

         }
      }
   ]
}

**Comment by Pranidhi0421** [comment]
I am using Q module to retrieve the data. Data is saved based on UUID value and trying to get based on that UUID value, but i am getting undefined values when i run pm2 in cluster mode whereas same code is working fine in fork mode. How to resolve this issue?

**Comment by lid3rs** [comment]
> I was able to launch multiple instances of the same script using json config:
> 
> ```shell
> pm2 start pm2.json
> ```
> 
> pm2.json:
> 
> ```json
> {
>   "apps": [
>     {
>       "exec_mode": "fork_mode",
>       "script": "./lib/index.js",
>       "name": "proj-0",
>       "node_args": [ "--harmony" ],
>       "env": {
>         "PORT": 4001,
>         "NODE_ENV": "production"
>       },
>       "error_file": "/var/www/logs/proj-0.err.log",
>       "out_file": "/var/www/logs/proj-0.out.log"
>     },
>     {
>       "exec_mode": "fork_mode",
>       "script": "./lib/index.js",
>       "name": "proj-1",
>       "node_args": [ "--harmony" ],
>       "env": {
>         "PORT": 4002,
>         "NODE_ENV": "production"
>       },
>       "error_file": "/var/www/logs/proj-1.err.log",
>       "out_file": "/var/www/logs/proj-1.out.log"
>     }
>   ]
> }
> ```

Optimised your answer:

```
// Options reference: https://pm2.io/doc/en/runtime/reference/ecosystem-file/
const app = {
    name: "Autoremont",
    script: "server.js",
    args: "one two",
    instance_var: "INSTANCE_ID",
    log_date_format: "YYYY-MM-DD HH:mm Z",
    autorestart: true,
    max_memory_restart: "1G"
};

module.exports = {
    apps: [
        {
            ...app,
            ...{
                watch: false,
                env: {
                    PORT: 5000,
                    NODE_ENV: "production"
                }
            }
        },
        {
            ...app,
            ...{
                watch: true,
                env: {
                    PORT: 5001,
                    NODE_CONFIG_DIR: "/home/admin/domains/astanguautoremont.ee/public_html/staging/config/",
                    NODE_ENV: "staging"
                }
            }
        }
    ],

    deploy: {
        production: {
            user: "node",
            host: "212.83.163.1",
            ref: "origin/master",
            repo: "git@github.com:repo.git",
            path: "/var/www/production",
            "post-deploy": "npm install && pm2 reload ecosystem.config.js --env production"
        }
    }
};
```
