### ISSUE TITLE
Unable to restart pm2 process from within another pm2 process (0.11.1)

### ISSUE THREAD

**Issue by edorivai** [Unitech/PM2#783]
For quite a while I've been running a production server using PM2 0.9.1. We run two processes; let's call them *restartable.js* and *restarter.js*.

*restartable.js* is a script that will be restarted by *restarter.js*. This is done by running a child process withing *restarter.js* like this: 
```javascript
var spawnChildProcess = require('child_process').spawn;
spawnChildProcess('pm2', ['restart', '0']); // 0 is the identifier of restartable.js
```
This all worked flawlessly in 0.9.1, but since we update to 0.11.1 we're unable to restart *restartable.js* through *restarter.js*. What happens is that *restartable.js* is stopped, but never actually restarted.
The following is printed when logging for *restartable.js* right after the restart attempt
```
[PM2] Process with pid 41519 still not killed, retrying...
[PM2] Process with pid 41519 killed
[PM2] Starting execution sequence in -fork mode- for app name:restarter id:1
[PM2] App name:restarter id:1 online
```

From that point on it is also not possible to restart the process through commandline with
```
pm2 restart 0
```
I've also tried the same setup using pm2@0.10.0; this showed the same problem.
We've tried this setup with the most basic content for *restartable.js*, which ruled out any problems specific to the restartable script.

Is this the expected behaviour? We've reverted to 0.9.1 for now, but I'm kinda suspecting I'm misusing PM2.

**Comment by Unitech** [comment]
Fixed with the lastest PM2 (>0.12.x)
