### ISSUE TITLE
Segmentation Fault OpenSuse 13.2

### ISSUE THREAD

**Issue by nrwahl** [Unitech/pm2#798]
OpenSuse 13.2 just came out recently, and I'm working on updating some servers but every other command with PM2 is throwing a Segmentation Fault. Otherwise it appears to function, but I don't trust it for business purposes yet.

**Comment by NiklasMerz** [comment]
I bot the same Problem. I will look for details

**Comment by hugoeustaquio** [comment]
I have the same problem, and I'm using slackware 64 bits (pure 64 bits).
I can't provide more information, because the command doesn't respond nothing else than "Segmentation fault", ex:

bash-4.3$ pm2 --help
Segmentation fault

**Comment by hugoeustaquio** [comment]
I can only assume you used something that depends on 32 bits compatibility.

**Comment by hugoeustaquio** [comment]
I upgraded node 0.10.35 with 0.12.4 (newest slackware package on slackbuilds) and it worked.
I assume it's safe to say the bug was in the node, and not in pm2. Also it's resolved.
