### ISSUE TITLE
Limited usefulness of watch mode while developing

### ISSUE THREAD

**Issue by goloroden** [Unitech/pm2#813]
Basically, watch mode is a great thing in production mode. Unfortunately, it does not exactly what I would expect while in development mode.

Supposed you change your code in a way that you need to make changes in two `.js` files. You change file A, save it, and PM2 instantly restarts your application (which is a good thing). Unfortunately, since changes have not yet been made to file B, the application crashes, and PM2 restarts again - and it crashes again - and PM2 restarts - and so on ...

While this is fine in production mode, it eats up lots of CPU time and system resources in development mode.

What I would be wishing for is another switch that you can use to tell watch mode only to restart **once**, or when another change in the filesystem appears. This way you can save, have your application restarted, and if it crashes, PM2 doesn't get hyperactive, but waits for the next change ;-)

To be able to differentiate this from a real crash, one could also use some timing behavior: If you are in watch mode and the app crashes multiple times within a very short time span, just stop, and wait for the next file change; otherwise restart.

What do you think about this? Or, is there another way of solving my issue that I didn't think of so far?

PS: Basically I'm thinking of something similar to how [nodemon](https://github.com/remy/nodemon) behaves.

**Comment by MattiSG** [comment]
A config switch or env variable would indeed be a good way to control this behaviour  :)
