### ISSUE TITLE
process-level environment variables

### ISSUE THREAD

**Issue by bevacqua** [Unitech/pm2#83]
I would like to be able to have pm2 run my node application with a `NODE_ENV` variable. Ultimately doing

``` shell
NODE_ENV=staging node /foo/bar/baz/app.js
```

Is this possible? Could we add this feature? It's also useful for setting things like PORT, which don't belong on system-wide env variables.

My use case is setting `NODE_ENV` to whatever name is given to an EC2 instance on  creation in my [**grunt-ec2**](https://github.com/bevacqua/grunt-ec2) deployment module.

**Comment by fddayan** [comment]
you can also specify any environment variable

from the docs:
```json
{
  "apps" : [{
    "name"        : "worker-app",
    "script"      : "worker.js",
    "args"        : ["--toto=heya coco", "-d", "1"],
    "watch"       : true,
    "node_args"   : "--harmony",
    "merge_logs"  : true,
    "cwd"         : "/this/is/a/path/to/start/script",
    "env": {
        "NODE_ENV": "production",
        "AWESOME_SERVICE_API_TOKEN": "xxx"
    }
  },{
    "name"       : "api-app",
    "script"     : "api.js",
    "instances"  : 4,
    "exec_mode"  : "cluster_mode",
    "error_file" : "./examples/child-err.log",
    "out_file"   : "./examples/child-out.log",
    "pid_file"   : "./examples/child.pid"
  }]
}
```

**Comment by jalevin** [comment]
Just wanted to add another gotcha I stumbled upon while defining multiple apps in a processes.json file.

I could run ```NODE_ENV=production pm2 start myapp.js --name myapp``` without issues, however, when I was defining multiple apps in processes.json, it would seemingly restart the app for no reason without leaving any trace in the logs.

If you're using a sqlite database and have``` "watch": true``` in your processes.json, it will see the database changes and continuously restart the application without any errors.

**Comment by jcollum** [comment]
> If you're using a sqlite database and have"watch": true in your processes.json, it will see the database changes and continuously restart the application without any errors.

I had a similar issue with some tests. Decided `watch` option was more trouble than it was worth. If I could set it to watch specific files (maybe I can, I don't recall seeing that though) then it would be useful.

**Comment by soyuka** [comment]
just give watch the files you want to watch:
```json
watch: ['foo', 'bar']
```

**Comment by jcollum** [comment]
Ah, thanks. I haven't committed to pm2 enough to start writing pm2 json app declarations though and including them in my codebase, so I won't be using that yet.

**Comment by tamilvendhank** [comment]
ENV=dev pm2 start index.js works.

pm2 restart doest work.

$ pm2 --version
0.15.10

**Comment by jcollum** [comment]
@tamilvendhank pm2 restart will just restart the app with the same environment variables; if you change the environment you have to delete the process and start a new one.

**Comment by soyuka** [comment]
You should be able to do :
ENV=production pm2 restart 0

And observe changes. Or use json env and change them with --env
Le jeu. 31 mars 2016 à 16:13, Justin Collum <notifications@github.com> a
écrit :

**Comment by jcollum** [comment]
Actually you're right, I don't know what I was talking about, I'll delete my comment.

**Comment by soyuka** [comment]
@jcollum please don't errors are part of a learning process ;).

About `--watch` you can use `--ignore-watch` to ignore some files (here the sqlite db).

More about json environments [here](http://pm2.keymetrics.io/docs/usage/pm2-doc-single-page/#switching-to-different-environments). I'll do a tutorial asap if you want me too.

**Comment by rpasunuri** [comment]
Please let me know how to set process.env variable value through the pm2

**Comment by shhhplus** [comment]
@rpasunuri 
NODE_ENV=development pm2 start app.js

**Comment by rpasunuri** [comment]
@shhhplus

I tried with the "NODE_ENV=development pm2 start app.js" but i am getting below error for NODE_ENV.

Error: 'NODE_ENV' is not recognized as an internal or external command

**Comment by shhhplus** [comment]
@rpasunuri 
http://stackoverflow.com/questions/11928013/node-env-is-not-recognized-as-an-internal-or-external-command-operable-comman/11928210

**Comment by munzx** [comment]
Just write "NODE_ENV="production" pm2 start server.js" , this works for me :)

**Comment by JbIPS** [comment]
Is there any news on this? I tried to update to latest PM2 (2.1.5) and env vars are still not used
```
NODE_ENV="production" pm2 start server.js -- server_config.json
```
This doesn't start with the production flag :disappointed: . Is the JSON file mandatory to use environment? This looks a bit overkill to me.

**Comment by vmarchaud** [comment]
@JbIPS Test with the options `--update-env` ?

**Comment by JbIPS** [comment]
Same results. I tried:
* restarting the process
* Deleting the process and starting it again
* Killing the PM2 daemon before starting

And no change at all. I tried multiple env vars to test if there was a collision with NODE_ENV, but no.

**Comment by JbIPS** [comment]
Weirdly, this suddenly worked... Don't know, don't understand why :neutral_face:

**Comment by chovy** [comment]
bash environment is not reloaded on restart. I have to do `. ~/.bashrc && pm2 stop all && pm2 kill all && pm2 delete all && npm run start:production` to pickup new environment variables defined in `~/.bashrc`

**Comment by vmarchaud** [comment]
@chovy You first need to your shell to load variable defined inside `~/.bashrc` then you need to add `--update-env` when using `pm2 restart` to tell PM2 that you explicitly want to inject new env variable.

**Comment by chovy** [comment]
Thanks. I will give `--update-env` a try.

**Comment by Romick2005** [comment]
Finally make it:
`NODE_ENV="production" pm2 start server.js`
Magic was in quotes :)

**Comment by papakai** [comment]
Question: I've added
`env:{
    NODE_ENV: "production"
}`
to my app.

Will this then be automatically used when doing
`pm2 start <appname>`
`pm2 restart <appname>`

I'm asking because I saw the `--env <environmentname>` parameter in the docs.
Thanks for any response on that.

**Comment by vmarchaud** [comment]
`--env <envname>` is used to tell pm2 to use another environnement defined inside a process file :
```
{
  "apps" : [{
    "name"        : "worker",
    "script"      : "./worker.js",
    "watch"       : true,
    "env": {
      "NODE_ENV": "development"
    },
    "env_production" : {
       "NODE_ENV": "production"
    }
  },{
    "name"       : "api-app",
    "script"     : "./api.js",
    "instances"  : 4,
    "exec_mode"  : "cluster"
  }]
}
```
In this example, you will run `pm2 start ecosystem.json` and it will start your application with the default environment (in development so).
Then you use `pm2 start ecosystem.json --env production` and it will use the attribute `env_<name>` where name is `production` here, so it will start your app with `NODE_ENV=production`.

**Comment by papakai** [comment]
Ah, thanks a lot - that clarifies it. Maybe you can point out in the docs, that "env" will be taken as default, if no `--env` parameter is used.

**Comment by luokuning** [comment]
Thanks, `NODE_ENV=production pm2 restart --update-env 0` works for me.
