### ISSUE TITLE
Error: connect EACCESS

### ISSUE THREAD

**Issue by medatech** [Unitech/pm2#837]
When I install PM2 0.12.1 with the following and run pm2 list like this...

```
sudo npm install -g pm2
sudo pm2 startup ubuntu
pm2 list
```

I get the following error:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect EACCES
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
```

However, if I go back to an older version which I have been using in production 0.9.6, then running the following:

```
sudo npm install -g pm2@0.9.6
sudo pm2 startup ubuntu
pm2 list
```

Then it works fine.  If it's not a bug, then I'm unsure what I'm doing wrong.  The docs indicate this should be pretty straight forward.

Any help would be most appreciated!

**Comment by Yinear** [comment]
@Tjatse How can I fix this on Mac?
Mac don't have root,  and don't have a /opt path.
Thank you!

**Comment by Tjatse** [comment]
@Yinear try @soyuka's solution.
If you're doing this on Mac, you need no `sudo` to upgrade permission.
`/opt` path is just an example, `/path/to` is okay too.

**Comment by Yinear** [comment]
@Tjatse ,  while trying @soyuka's solution,  in the first step "npm i pm2 -g",  I got EACCES error asking me for root.
So I have to do chmod -R 777 on /Users/xxx/.npm  and /usr/local/lib/node_modules.
After that, I still get Error: EACCES, symlink '../lib/node_modules/pm2/bin/pm2' and maybe more EACCES errors.

I'm afraid if I did it right? Thank you!

**Comment by struCoder** [comment]
what i do:
+  sudo npm uninstall -g pm2
+  cd .npm/ && sudo rm -rf pm2*
+  cd ~ && sudo rm -rf .pm2
+  sudo npm install pm2 -g  

lastly. it was success

**Comment by no7dw** [comment]
thanks @medatech

**Comment by ORESoftware** [comment]
I get this same error on a Macbook Pro

**Comment by 59naga** [comment]
I'm too.

```coffee
# app.coffee
http= require 'http'
http.createServer (req,res)->
  res.writeHead 200, {'Content-Type':'text/plain'}
  res.end 'Hello World\n'
.listen 80,'127.0.0.1'

console.log 'Server running at http://127.0.0.1:1337/'
```

```bash
$ sudo pm2 kill
# [PM2] PM2 stopped

$ rm -rf ~/.npm/pm2
$ rm -rf ~/.pm2
$ sudo npm uninstall pm2 --global
# unbuild pm2@0.14.3

$ npm install pm2 --global
# pm2@0.14.3 /Users/koliseoa/.nodebrew/current/lib/node_modules/pm2

$ sudo pm2 start app.coffee
#│ app      │ 0  │ fork │ 66353 │ online │ 0       │ 0s     │ 7.723 MB   │ disabled │
```
```bash
$ pm2 list
# events.js:85
#       throw er; // Unhandled 'error' event
#             ^
# Error: connect EACCES
#     at exports._errnoException (util.js:746:11)
#     at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
```

But, __resolved at the following.__

```bash
$ sudo chmod -R 777 ~/.pm2
$ pm2 list
#│ hoo      │ 0  │ fork │ 66353 │ online │ 0       │ 2m     │ 8.988 MB   │ disabled │
```

In this case, permission of the folder was the cause.

**Comment by jhansen-tt** [comment]
You can also just do:
    sudo chown nobody:nogroup ~/.pm2/*

**Comment by tuoxie007** [comment]
@struCoder thanks，i resolved with your method.

**Comment by creativityjuice** [comment]
If you forgot to use the -u argument in `pm2 startup ubuntu -u YOURNODEJSUSER`, you still can change the user in your /etc/init.d/pm2-init.sh at line 21 : `USER=YOURNODEJSUSER`

**Comment by glskiba** [comment]
I tried most of the suggestions, but the only one that worked was jhansen-tt's (thanks!).  Make sure all the files in ~/user/.pm2 are owned by the user account!

**Comment by hmny** [comment]
had the same problem on Ubuntu Server. As other people mentioned, just run `pm2` commands as `SU` like `sudo pm2 list`

**Comment by MaffooBristol** [comment]
I had a really weird issue with EACCES that was unrelated to the above things. I was in my home directory on Centos `/home/matt`, then did `sudo su www`, then tried `pm2 start /path/to/my/app.js`. It threw up an error just because I was currently in a directory that I didn't have permission to access, even though i was trying to run the script that was situated somewhere I did have access to. Changing directory to my own home folder made the command work- kinda odd.

**Comment by xx4159** [comment]
I do **not** recommend to use `chmod 777`
you should run `pm2` **without** `sudo`

```sh
$ sudo pm2 start pm2.json
$ ps aux | grep PM2
# user        4318   0.1  0.0  2448152    860 s000  S+    6:09PM   0:00.00 grep PM2
# root        3515   0.0  0.2  3130616  58836   ??  Ss    5:47PM   0:01.03 PM2 v1.1.2: God Daemon 

$ pm2 list
‼️ # Error... (connect EACCES...)
$ sudo pm2 list
👍 # Working...

$ sudo pm2 kill

$ pm2 start pm2.json
$ ps aux | grep PM2
# user        4318   0.1  0.0  2448152    860 s000  S+    6:09PM   0:00.00 grep PM2
# user        3515   0.0  0.2  3130616  58836   ??  Ss    5:47PM   0:01.03 PM2 v1.1.2: God Daemon 

$ pm2 list
👍 # Working...
```

**Comment by LightGlobal** [comment]
@struCoder it is work for me, thanks

**Comment by rauleite** [comment]
My solution:
`sudo npm uninstall -g pm2`
`sudo rm -rf ~/.pm2`
`sudo yarn global add pm2@latest`

**Comment by isrmicha** [comment]
@struCoder  Thanks! Solved my problem

**Comment by Keyne** [comment]
I've ran into the sample problem and my situation was that I needed to ran pm2 as non-root and besides the fact that I was starting it with the correct user I wasn't under the user's home dir, instead I was in /root and pm2 was creating the .pm2 file under that directory. Changing to the correct dir solved my problem.

Ps: I've done the installation again just to make sure everything was setup correctly
