### ISSUE TITLE
PM2 0.12.1 not releasing a port after app is restarted

### ISSUE THREAD

**Issue by rmldsky** [Unitech/pm2#842]
Hi,
We have recently upgraded from 0.9.5 to 0.12.1 (big jump we know). What we've noticed is random and happens whenever we deploy a new app version, which just triggers _pm2 stop_/_pm2 start_ on that app. PM2 still holds a port when the app is not running (after stop, before start). App starts OK, app's PID gets the port, but it is unreachable.

To better understand what I am trying to explain please check this Gist of my command line:
https://gist.github.com/rmldsky/c5001e2f5160f6be028d

Please advice what can be wrong. Is this related to the change in 0.11.0 (TCP Sockets -> UNIX Sockets)? Should we modify our apps or do something else?

Thanks!

**Comment by LourduDarwin** [comment]
In a Node.js application managed by PM2, multiple ports are running, but occasionally some ports stop unexpectedly. When this happens, CPU utilization reaches 100%. Why does this occur, and how can it be resolved? Can anyone provide a solution?
