### ISSUE TITLE
pm2 doesn't log after shutdown

### ISSUE THREAD

**Issue by iliakan** [Unitech/pm2#856]
When `pm2 gracefulReload all` is executed, the processes receive a message `shutdown`.

In the process of shutdown, there's something to be logged.

But unfortunately, everything I try to log `process.on('message')` does not get to `~/.pm2/logs`.
The function I made to check it:

``` js
var fd = fs.openSync('/tmp/bla', 'w');
function log(str) {
  console.log(str);
  fs.writeSync(fd, str + "\n");
}
```

All records after receiving `shutdown` are printed to `fd`, but not to pm2 logs.

**Comment by jshkurti** [comment]
It should work now.

**Comment by iliakan** [comment]
It should, but it doesn't. Don't know how to reopen, just checked w/ 0.12.14.

**Comment by iliakan** [comment]
This is my code for clarity:
```js
process.on('message', function(msg) {
  if (msg == 'shutdown') { // PM2 sends this on graceful reload
    shutdown();
  }
});


var fd = require('fs').openSync('/tmp/bla', 'a');
function l(str) {
  console.log(str);
  require('fs').writeSync(fd, str + "\n");
}

function shutdown() {
  co(function*() {
    log.info("closing the app..."); // (!!!!!)
    yield* app.close();
    log.info("app closed");
  }).then(function() {
    l("STOP " + new Date()); // (*****)
    log.info("exiting");
    process.exit(0);
  }, function(err) {
    log.error(err);
  });

  var dieDelay = process.env.PM2_GRACEFUL_TIMEOUT || 4000;
  // I have 4000ms to close all connections
  setTimeout(function() {
    log.error("App is stopping for too long! Will be killed now!");
    // kill is accomplished by PM2
  }, dieDelay - 100);

}
```

The line `(!!!!!)` can be seen in pm2 logs. That's right.

The line `(*****)` actually writes to `/tmp/bla`, but not to any of pm2 logs.

**Comment by iliakan** [comment]
Guess, when all connections are closed, pm2 disconnects logging streams, or kind of.
So I can't log the fact that "connections are closed".

**Comment by jtokoph** [comment]
Any workarounds for this? I console.log as my first line in `process.on('message')` and it doesn't get picked up in pm2 logs.

**Comment by liukun** [comment]
The message can only be logged by other mechanisms such as write to file directly or socket to log services.

**Comment by pierre-b** [comment]
@iliakan , I just had same issue, and wrapping process.exit(0) with a setTimeout of few ms did the trick ;)

**Comment by Unitech** [comment]
[SIGINT handler](http://pm2.keymetrics.io/docs/usage/signals-clean-restart/) for graceful exit now works as expected (it prints every log):

To try it:

```
$ npm install pm2@next -g
$ pm2 update
```
