### ISSUE TITLE
Disable logs

### ISSUE THREAD

**Issue by janantala** [Unitech/pm2#866]
Is it possible to disable logs? I would like to run pm2 on read-only file system.

**Comment by panuhorsmalahti** [comment]
Disabling logs would be very useful on Windows, where /dev/null doesn't exist.

**Comment by kedare** [comment]
@panuhorsmalahti : Try that : http://stackoverflow.com/questions/313111/dev-null-in-windows

**Comment by nodkrot** [comment]
So whats the answer?

**Comment by cmal** [comment]
`/dev/null` not working on my Centos server.
