### ISSUE TITLE
Feature request: Don't follow symlinks when watching

### ISSUE THREAD

**Issue by matthewwithanm** [Unitech/PM2#870]
The master branch of chokidar now supports a `followSymlinks` option (as of [284148b][1]). It would be great if PM2 would expose access to this for its watch mode. This would be convenient for symlink-based deployment strategies: simply configure PM2 to watch the "current" symlink and restart when it's updated.

[1]: https://github.com/paulmillr/chokidar/commit/284148bb3d118ee31241d167fa41036dcc088b59

**Comment by soyuka** [comment]
@matthewwithanm Sorry for the big delay was really busy!

Hope that this PR'll fit your needs!
