### ISSUE TITLE
Starting different Servers by different declaration files disturbing watch

### ISSUE THREAD

**Issue by goser** [Unitech/PM2#876]
My app configurations:

    // app_1/app1.json
    {
        "apps":[
            {
                "name": "app1",
                "script" : "src/main.js",
                "watch": [ "src" ]
            }
        ]
    }

    // app_2/app2.json
    {
        "apps":[
            {
                "name": "app2",
                "script" : "src/main.js",
                "watch": [ "src" ]
            }
        ]
    }

Now I start app1 by "pm2 app1.json" from app_1 directory 
and app2 by "pm2 app2.json" from app2 directory. 

Both instances are running the way they should.

But one thing is strange:
When changing "app_1/src/main.js" app1 and app2 are restarting.
When changing "app_2/src/main.js" no server restarts.

Node is v.0.10.28

**Comment by Tjatse** [comment]
I can not reproduce this, if there still has problems with the latest ver, feel free to reopen it or fire a new one.
