### ISSUE TITLE
Make startup script use a json app declaration instead of dump

### ISSUE THREAD

**Issue by jfbelisle** [Unitech/pm2#878]
Hi,

I think it would be nice if we could specify a json app declaration for the startup script instead of the default dump. That way we can control which app starts at boot time.

Any idea on how I can achieve this ?

Thank you

**Comment by Tjatse** [comment]
Actually, the JSON declaration only exists before passed in (humanize the configurations), when you ran `pm2 start <file>`, the declaration is being transformed to PROCESS STYLE - like the dumped file, so, it's difficult to restore it.

**Comment by jfbelisle** [comment]
Ok, I understand. So my best bet would be to have all my process that I want at reboot and do a pm2 dump to generate my process file the way I want it and don't do any other pm2 save or dump to override it.
