### ISSUE TITLE
Spawning PM2 hangs with Jenkins slave

### ISSUE THREAD

**Issue by tokyowizard** [Unitech/PM2#887]
Hi!

I have a [Jenkins server](http://jenkins-ci.org/) that has Jenkins slaves running jobs in a [mesos cluster](https://mesosphere.com/).

When the slaves try to start PM2, they hang at spawning the PM2 daemon:

```
./node_modules/.bin/pm2 start index.js
[PM2] Spawning PM2 daemon
```

[This line](https://github.com/Unitech/PM2/blob/59f67937dc1e9459692b90d11ead4c47ac698bb6/lib/Satan.js#L332) is causing the Jenkins' slave to hang: 

I tried changing the line from:
```
    stdio      : ['ipc', out, err]
```

to:
```
    stdio      : "ignore"
```

That change got the Jenkins slave to spawn the daemon successfully:

```
$ ps auxw | grep PM2
jenkins  25911 92.3  5.9 674444 60844 ?        Rsl  04:28  28:57 PM2 v0.12.2: God Daemon
```

I think it's related to file descriptors as explained here: https://wiki.jenkins-ci.org/display/JENKINS/Spawning+processes+from+build
because something similar was tried before by adding "ignore": https://github.com/Unitech/PM2/issues/659#issuecomment-61445692

**Comment by Unitech** [comment]
Hi!

Interesting.
If file descriptors are managed inside the forked process ([here](https://github.com/Unitech/PM2/blob/59f67937dc1e9459692b90d11ead4c47ac698bb6/lib/Satan.js#L586)) instead of passing them via the spawn [here](https://github.com/Unitech/PM2/blob/59f67937dc1e9459692b90d11ead4c47ac698bb6/lib/Satan.js#L325) would it solve the problem?

@jshkurti @soyuka @Tjatse

**Comment by soyuka** [comment]
I installed jenkins, manually installed nvm to the `/var/lib/jenkins` home directory and tried the following build:
```
[ -s $HOME/.nvm/nvm.sh ] && . $HOME/.nvm/nvm.sh # This loads NVM
PATH=$PATH:/var/lib/jenkins/.nvm/v0.10.36/bin
node -v
npm i pm2 -g
pm2 start ~/server.js
curl -sf localhost:8020 > /dev/null #is alive?
pm2 desc 0
pm2 kill
```

It's working just fine. I also made some tests on pm2 file descriptors and they are closed as they should be when daemon has been launched.

node v0.10.36
pm2 v0.12.4


In my opinion, this is no longer an issue.
