### ISSUE TITLE
`pm2 startup` cannot generate startup scripts for multiple users

### ISSUE THREAD

**Issue by dantman** [Unitech/pm2#889]
When using `pm2 startup` (at least when using `pm2 startup ubuntu -u x`) the same init.d file is used every time.

This means that because `--run-as-user` has been removed you can no longer easily have scripts started by pm2 that run under different users, they all have to run as the same user.

**Comment by Deminetix** [comment]
+1

**Comment by PierreGambarotto** [comment]
With the PR #1202, `pm2 startup -u username …` adds the username to the init script name.
Hope this helps.

**Comment by DeveloperAlex** [comment]
I had the same problem on ubuntu 14.04.  Fixed it by running "sudo pm2 startup -u myusername".   Then "sudo pm2 save".  And "sudo shutdown -r now" - of course.

**Comment by Unitech** [comment]
Closing in favor of #2559 

To try the new startup system:

```bash
$ npm install Unitech/pm2#development -g
$ pm2 update
```

```bash
$ pm2 startup     # Then copy / paste the command displayed
$ pm2 unstartup
```
