### ISSUE TITLE
CentOS startup scripts break with non-bash default shells

### ISSUE THREAD

**Issue by Gillingham** [Unitech/pm2#890]
You end up with something like this:

```
/etc/init.d/pm2-init.sh status
Status for pm2:
PATH=(..your current $PATH here): Command not found.
┌──────────┬────┬──────┬───────┬────────┬───────────┬────────┬─────────────┬──────────┐
│ App name │ id │ mode │ PID   │ status │ restarted │ uptime │      memory │ watching │
├──────────┼────┼──────┼───────┼────────┼───────────┼────────┼─────────────┼──────────┤
```

For some of the servers I work on csh is the default shell, where "PATH=$PATH" is invalid syntax.
That path error can get pretty annoying and cause other people to freak out when they see errors.

One fix would be to add -s /bin/bash to the su line. That would probably be acceptable since pm2 is already relying on /bin/bash in the shebang line of the script itself.
I don't know how portable -s is on su though.

**Comment by Tjatse** [comment]
CentOS 7?

**Comment by Gillingham** [comment]
I saw this in 5, I somewhat assume it will be present on any version of CentOS/RHEL with non-default shells as the shell syntax likely hasn't changed.

**Comment by Gillingham** [comment]
Since this script already assumes bash, without saying it, would a pull request be accepted to change the su - line to execute the command with /bin/bash -c - to remove this error?

**Comment by soyuka** [comment]
Would [this kind of fix](https://github.com/Unitech/PM2/commit/85fb58ce881fdcde10d7b1119448b4da2179f2cd) work?

**Comment by Gillingham** [comment]
@soyuka -s is not entirely portable

```
super() {
    su - $USER -c "/bin/bash -c - PATH=$PATH; PM2_HOME=$PM2_HOME $*"
}
```
I *think* would be more likely to work on various platforms, especially since the script already has /bin/bash hardcoded in the shebang, it's not going to function without it anyways.

**Comment by Gillingham** [comment]
Double posting because I'm not sure github sends notifications for edits but @soyuka That the fix you mentioned won't work, because if the shell is something like tcsh that patch won't solve anything as it's still using bash specific syntax when setting the enviroment.

**Comment by soyuka** [comment]
> @soyuka -s is not entirely portable

Is it not available on centOS? 

I understand your issue about env variable declaration. Your fix will work on debian/ubuntu, feel free to PR about this.

**Comment by Unitech** [comment]
Closing in favor of #2559 

To try the new startup system:

```bash
$ npm install Unitech/pm2#development -g
$ pm2 update
```

```bash
$ pm2 startup     # Then copy / paste the command displayed
$ pm2 unstartup
```
