### ISSUE TITLE
How can I use events without pm2-interface?

### ISSUE THREAD

**Issue by uetkaje** [Unitech/pm2#900]
In the past, I could use events with pm2-interface like the following;

```
var ipm2 = require('pm2-interface')();
ipm2.on('ready', function () {
    ipm2.bus.on('process:online', function (data) {
        console.log("process:online");
        console.log(data);
    });

    ipm2.bus.on('process:exception', function (data) {
        console.log("process:exception");
        console.log(data);
    });

    ipm2.bus.on('process:exit', function(data) {
        console.log("process:exit");
        console.log(data);
    });
});
```

How can I use these three events with pm2? I can not see any explanation about events in the programmatic API section.

Any help would be appreciated.

**Comment by Tjatse** [comment]
Definitely yes.
```
var sub = axon.socket('sub-emitter');
sub.connect([socket path]); // [socket path] is '~/.pm2/pub.sock' by default.
sub.on('process:exit', function(e, d){
    if(d.process.name == 'MY_APP'){
      // enqueue alert or do something else.
    }
  });
```

**Comment by RSSGergelyMunkacsy** [comment]
Thank you your answer! I I extended your solution with the `resolveHome` function form pm2-gui, because if I use relative path, it doesn't work, but with it, it is work like a charm.

**Comment by Tjatse** [comment]
@RSSGergelyMunkacsy Glad to be of service :)

**Comment by pravee-n** [comment]
@Tjatse, the code you mentioned above doesn't seem to work for me. Any idea what I might be missing?
