### ISSUE TITLE
Detect unstable restarts?

### ISSUE THREAD

**Issue by Monsignor** [Unitech/PM2#902]
In my Node app, sometimes it's possible to get faulty data from the client which forces the server to restart.

Then, after it is rebooted by PM2, it runs a script to clean up any bad data and proceeds with normal operation.

However, if, for whatever reason, the clean-up script doesn't do the job (only happened once so far, but that's one time too many), PM2 keeps restarting the server over and over again. In this situation, there are 15 restarts made within 2-3 seconds and then it stops completely with the error:

"script had too many unstable restarts"

I realize the ideal solution is to make sure faulty data never happens, but in the meanwhile, is it possible for the Node server to detect when the "unstable restarts" error happens? Then I could notify the admin immediately or run whatever code I come up with to remedy the issue.

**Comment by Tjatse** [comment]
#900
