### ISSUE TITLE
pm2 start server.js does not launch application in windows 8

### ISSUE THREAD

**Issue by openlib** [Unitech/PM2#907]
**Environment:**
1. Windows 8.1 x64 Update 1
2. node -v = v0.11.14-nightly-20140819-pre   [Tried with v0.10.35]
3. npm -v = 1.4.21
4. pm2 -v = 0.12.3

**server.js:**

```
var express = require('express');

var app  = express();

app.use(express.compress());
app.use(express.bodyParser());
app.use(express.methodOverride());
app.use(express.static(__dirname + '/app' ));
app.use('/bower_components', express.static(__dirname + '/bower_components' ));

app.get('/*', function(req, res)
{
    res.sendfile(__dirname + '/app/index.html');
});

app.listen(8000);

console.log('Listening on port 8000');
```

```node server.js```: works but using pm2 does not work.

**C:\Users\User\Documents\Repositories\FrontEndWebTemplate>pm2 start server.js**
*[PM2] Process server.js launched*
```
│ App name │ id │ mode │ PID │ status │ restarted │ uptime │ memory │ watching │
```

 Use `pm2 info <id|name>` to get more details about an app

Does not work with pm2.

**Comment by Exsilium122** [comment]
The same here. Willing to help to test on windows 8.1 and Windows Server 2012 R2
