### ISSUE TITLE
pm2-init.sh doesn't work on startup under ubuntu 12.04 LTS

### ISSUE THREAD

**Issue by mkmelin** [Unitech/pm2#909]
The /etc/init.d/pm2-init.sh script doesn't work ubuntu 12.04 LTS for boot (pm2 gets called but there's just some error thrown). Running it manually later works. 

In the /etc/init.d/pm2-init.sh script there's a line
export PATH=$PATH:/usr/local/bin

... but apparently that does not work out. 

If I change it to this, things start working:
 export PATH=/bin:/usr/local/bin

Using pm2 version 0.12.3.

**Comment by asendia** [comment]
I don't know if it is relevant but I also need to rename the root user in 
USER=root
to my current username (USER=username) to get it works.

**Comment by lab101** [comment]
thx for the suggestion had the same problem running Ubuntu 14.10
added /usr/local/bin to 
export PATH=$PATH:/usr/bin:/usr/local/bin

I don't think removing $PATH is a good solution because it will change all the previous paths.

**Comment by natcl** [comment]
Had the same problem as lab101 under Ubuntu 14.04, any plans to fix this ?

Thanks !

**Comment by Unitech** [comment]
Closing in favor of #2559 

To try the new startup system:

```bash
$ npm install Unitech/pm2#development -g
$ pm2 update
```

```bash
$ pm2 startup     # Then copy / paste the command displayed
$ pm2 unstartup
```
