### ISSUE TITLE
NPM test failed

### ISSUE THREAD

**Issue by Tjatse** [Unitech/PM2#913]
test/bash/log-custom.sh
```bash
grep "2014" out-rel.log
```

It's 2015 now, BTW, we shouldn't use a fixed value like "2014" in our test cases.

**Comment by jshkurti** [comment]
Yeah we saw that ^^

Happy new year buddy ! :)

**Comment by Tjatse** [comment]
Aha, happy new year, in the lunar calendar, there is a month to a new year :p

**Comment by Unitech** [comment]
Haha funny, happy new year!!!!

**Comment by soyuka** [comment]
Happy new year! :D

**Comment by Unitech** [comment]
new year fixed via https://github.com/Unitech/PM2/commit/85d11d521e4b3e5e18b5beda39ea3d5570c6510a :)
