### ISSUE TITLE
6666/6667 ports

### ISSUE THREAD

**Issue by CodersBrothers** [Unitech/PM2#916]
It's normal that any person that want can do a telnet to port 6667 of my server and read all my logs? LOL. Not sounds crazy? PM2 Seems open this door to anyone.

**Comment by CodersBrothers** [comment]
How disable RPC?

**Comment by Tjatse** [comment]
6666 is the RPC port and 6667 is the EventBUS port.
Open your firewall, and do not ACCEPT the specific ports in iptables. no one can access your server.

**Comment by CodersBrothers** [comment]
Thanks.

But maybe will be cool that this RCP will be activate only if developer want. 
I use this to hack the app of my friend.

**Comment by Tjatse** [comment]
try  to set access permission like below:
```
-A INPUT -s 192.168.100.124 -p tcp --dport 6666 -j ACCEPT
```

Then your friend who has the ip address `192.168.100.124` can access RPC, the others are denied.

**Comment by Unitech** [comment]
This was possible on old version of PM2. Just upgrade it.
On Jan 3, 2015 9:41 PM, "Jun" <notifications@github.com> wrote:

try to set access permission like below:

-A INPUT -s 192.168.100.124 -p tcp --dport 6666 -j ACCEPT

Then your friend who has the ip address 192.168.100.124 can access RPC, the
others are denied.

—
Reply to this email directly or view it on GitHub
<https://github.com/Unitech/PM2/issues/916#issuecomment-68618452>.

**Comment by CodersBrothers** [comment]
Thanks. Do it. I create this script, i use bounce module as balancer:

```sh
#!/bin/bash

iptables -F
iptables -t nat -F
iptables -t filter -F
iptables -t mangle -F

iptables -P INPUT DROP
iptables -P OUTPUT ACCEPT
iptables -P FORWARD DROP

iptables -A INPUT -p icmp -j ACCEPT

# General
iptables -A INPUT -p tcp --dport 22 -j ACCEPT # SSH
iptables -A INPUT -p tcp --dport 80 -j ACCEPT # WEB
iptables -A INPUT -p tcp --dport 443 -j ACCEPT # HTTPS

# Opinook
iptables -A INPUT -s 127.0.0.0/8 -p tcp --dport 8001 -j ACCEPT # public
iptables -A INPUT -s 127.0.0.0/8 -p tcp --dport 8002 -j ACCEPT # api
iptables -A INPUT -s 127.0.0.0/8 -p tcp --dport 8003 -j ACCEPT # developers
iptables -A INPUT -s 127.0.0.0/8 -p tcp --dport 8004 -j ACCEPT # live

# Bit2Me
iptables -A INPUT -s 127.0.0.0/8 -p tcp --dport 8500 -j ACCEPT # api
iptables -A INPUT -s 127.0.0.0/8 -p tcp --dport 8501 -j ACCEPT # public
iptables -A INPUT -s 127.0.0.0/8 -p tcp --dport 8502 -j ACCEPT # developers

iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
```

Later I use iptables-persistent

**Comment by CodersBrothers** [comment]
nope. Seems this not works :S

**Comment by Tjatse** [comment]
What's the version of your PM2, As @Unitech mentioned above: TCP is no longer supported since v0.12

**Comment by CodersBrothers** [comment]
Let me some minutes, i block the server, i denied my access.... im restating... xD

**Comment by CodersBrothers** [comment]
The version of PM2 is 0.10.8

**Comment by CodersBrothers** [comment]
Seems that something of my before scripts block pm2, what ports need for work? When i try to run a simple pm2 -v with the last iptables config pm2 never respond

**Comment by Tjatse** [comment]
Uh, it's too old and not safety, TCP is not supported after v0.11, why do not you update to latest ver (v0.12.4), it's more powerful and stabler.

**Comment by CodersBrothers** [comment]
ok, let me doit.

So, I need put udp in -p property? or what?

**Comment by Unitech** [comment]
You should upgrade pm2. Else to solve this bug only allow access to these
ports from remote not on localhost

**Comment by Unitech** [comment]
Only block from remote access not on localhost, the beers im drinking are
quite strong :p

**Comment by CodersBrothers** [comment]
ooooh ok, was sounds rare block only localhost. I'm was writing response :P, ok I go to update

**Comment by Tjatse** [comment]
Haha...

**Comment by Tjatse** [comment]
@CodersBrothers If you wanna hack apps through RPC or observe the EventBUS, you can head over to  the following links:
- [pm2-interface](https://github.com/Unitech/PM2/blob/master/lib/Interactor/pm2-interface.js)
- Doable
  - [RPC](https://github.com/Tjatse/pm2-gui/blob/master/lib/pm.js#L86-L118)
  - [EventBUS](https://github.com/Tjatse/pm2-gui/blob/master/lib/pm.js#L25-L43)

**Comment by CodersBrothers** [comment]
Seems now works really cool, now I'm using the last iptables config, i don't really sure if PM2 lines are corrects, but works:

```
#PM2
iptables -A INPUT -s 127.0.0.0/8 -p tcp --dport 6666 -j ACCEPT
iptables -A INPUT -s 127.0.0.0/8 -p tcp --dport 6667 -j ACCEPT
```

**Comment by Tjatse** [comment]
Strongly recommend you updating your PM2 to the latest :D

**Comment by CodersBrothers** [comment]
Yes, i updated

**Comment by CodersBrothers** [comment]
Thanks for all! If this RPC port in 0.12.4 can be accessible, I really recomend explain this in readme, as "very important" or "security considerations", some people return logs with passwords or input/ouput rest server as logs or something like this. This can be very dangerous, take down all work, as my friend, i get the admin password only listening this port. If best solutions it's iptables, will be cool add some basic example in section of readme.

**Comment by Unitech** [comment]
Nope RPC ports are not anymore accessible as the communication between the CLI and the Daemon is done via unix sockets. Btw, before and by default I'm not sure that these ports were binded to all, if I remember well there were only binded for 127.0.0.1.

You scarred me with this security issue but finally everything is okay :)
