### ISSUE TITLE
Start CLI node processes?

### ISSUE THREAD

**Issue by fritx** [Unitech/pm2#917]
I'm new to pm2 and I know we start processes from declared script paths:

``` js
{
  "name": "my-app",
  "script" "path/to/my-app.js"
  // ...
}
```

But what if we start from cmd line, instead of script paths? Such as:

```
$ http-server ./
$ serve ./
```

Is it possible? Thank you!

**Comment by Unitech** [comment]
pm2 start /absolute/bin/path

**Comment by fritx** [comment]
Oh I see! thanks!
But it is inconvinient..
It'd be great if pm2 provides a shortcut for cmd directly

**Comment by Tjatse** [comment]
Do you mean to follow the symbol link?

**Comment by fritx** [comment]
Pardon?
I wonder if I can do something as easy as:

```
pm2 start --bin http-server
```

instead of

```
pm2 start /not/very/clearly/bin/http-server
```

**Comment by Tjatse** [comment]
That's **FOLLOW SYMLINKS**. LOL..

**Comment by fritx** [comment]
Oh I see! And thanks for adding this to progress..

**Comment by Tjatse** [comment]
Enhancement:
```
$ pm2 start exec
```
Start the first matching executables in PATH.

```
$ pm2 start /absolute/bin/exec
```
Start the specific executable.

**Comment by Unitech** [comment]
Yes this feature was on our backlog but we finally delayed it.

It's quite straightforward to implement, it would take place somewhere there:
- https://github.com/Unitech/PM2/blob/master/lib/Common.js#L79

And PM2 already use shelljs (https://github.com/Unitech/PM2/blob/master/package.json#L169) that handle the PATH environment variable

**Comment by fritx** [comment]
I tried, but it aborted before lib/Common.js#L79 mentioned above
I've added some lines at [lib/Common.js#L55](https://github.com/Unitech/PM2/blob/master/lib/Common.js#L55), and it works
Here is my commit: https://github.com/fritx/PM2/commit/dbac332f02c46eb22e619359869a1db90f5da7ab

I wonder what the related test would look like, any guides?
Since this is of low-priority, I'm happy to contribute for such a PR.
Thank you!

**Comment by Unitech** [comment]
Sure send us a PR ! (with some tests ;) 
thanks

**Comment by fritx** [comment]
hey guys.. any progress on this?

**Comment by fritx** [comment]
ok let me try `$ pm2 start /absolute/bin/exec` for now

**Comment by Unitech** [comment]
absolute path + binaries (env PATH) both work now. Please upgrade PM2
