### ISSUE TITLE
Cant display ilogs

### ISSUE THREAD

**Issue by nfour** [Unitech/PM2#919]
On all of my Centos 6 servers I can't use

```
pm2 ilogs
```

It results in

```
Waiting for pm2...
```

Forever. It has been happening since I started using PM2 4 months ago.

Anyone care to explain? These are fresh Centos 6 installations with the latest version of PM2 and node.

**Comment by soyuka** [comment]
ilogs is broken since pm2 0.11, please use `pm2 logs` for the moment (or `tail`).

**Comment by Tjatse** [comment]
@nfour You gotcha.

**Comment by nfour** [comment]
That's all I really need! Thanks @Tjatse

**Comment by Unitech** [comment]
We built a new way to interact with PM2, we would need to upgrade pm2-ilogs at some point

https://github.com/Unitech/PM2/blob/master/doc/PROGRAMMATIC.md#bus-system---event-monitoring

**Comment by jshkurti** [comment]
ilogs has been removed
