### ISSUE TITLE
pm2 startup not working on aws ec2 ubuntu server

### ISSUE THREAD

**Issue by rishiyadav31** [Unitech/pm2#920]
I used 'pm2 startup ubuntu' to setup init script and everything worked fine; but when system reboots, pm2 processes aren't restarting. I tried pm2 kill/resurrect, that's working.

**Comment by soyuka** [comment]
Did you `pm2 save` or `pm2 dump` before resurrecting?

**Comment by rishiyadav31** [comment]
Yes I did. When I manually do pm2 resurrect after reboot,it works
perfectly.

**Comment by soyuka** [comment]
I'm not familiar with EC2 instances. Could you please check the `pm2-init.sh` file and put it in a gist?

It should be located under `/etc/init.d/`.

**Comment by rishiyadav31** [comment]
https://gist.github.com/anonymous/bb2de06ccc48bd6f9f20

**Comment by soyuka** [comment]
From what I see,

pm2 was installed as root (`PM2=/usr/local/lib/node_modules/pm2/bin/pm2`) but you try to run pm2 as the `ubuntu` user. I don't know if `ubuntu` can run the pm2 located in `/usr/local`.

Did you install pm2 as root? If yes, changing `USER=ubuntu` by `USER=root` should do the trick.

**Comment by rishiyadav31** [comment]
No that didn't work. And I installed pm2 as ubuntu only.

**Comment by soyuka** [comment]
Could you give me the output of `which pm2`? I assume you can run pm2 from the ubuntu user manually with no errors? 
Output of the `~/.pm2/pm2.log`?

How did you install npm?

**Comment by lab101** [comment]
Could be the same as this issue https://github.com/Unitech/PM2/issues/909
After your machines reboots you could check if pm2 is running in the process list and verify the user its using.
ps -aux | grep "PM2"

**Comment by rishiyadav31** [comment]
I tried the solution given in issue #909, but still it's not working. Are there any logs that I can check to get more info on what's stopping pm2 from restarting at system reboot.

**Comment by Unitech** [comment]
Closing in favor of #2559 

To try the new startup system:

```bash
$ npm install Unitech/pm2#development -g
$ pm2 update
```

```bash
$ pm2 startup     # Then copy / paste the command displayed
$ pm2 unstartup
```
