### ISSUE TITLE
Failure for date reported in log when testing

### ISSUE THREAD

**Issue by CGavrila** [Unitech/PM2#922]
When running `npm test`, I now get the following error

```
grep "2014" out-rel.log
spec "Should have written year in log file according to format YYYY"
########   ✘ Should have written year in log file according to format YYYY
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

This is obviously because we are now in 2015, and this is what is found in the `out-rel.log` file.

The solution for this is to change all occurrences of `2014` to `2015` in the `/test/bash/log-custom.sh` file.

Creating a pull request for this small change seems like overkill, so I was hoping that one of the collaborators could quickly fix it as suggested above and do the same in approx. one year's time. :)

**Comment by soyuka** [comment]
#913
