### ISSUE TITLE
process doesn't restart successfully if killed

### ISSUE THREAD

**Issue by kidbrax** [Unitech/PM2#923]
We have a Node server running under PM2 in cluster mode that spawns 4 processes. If I go and manually kill one of the process, it seems to restart fine.  PM2 list shows it restarted once and appears healthy.  However, the node app will no longer serve any traffic and nothing is logged anywhere that I can see.

I am trying to be sure that an unhandled exception will not cause our node app to become unresponsive.

**Comment by Unitech** [comment]
Node version?

**Comment by kidbrax** [comment]
v0.10.33

**Comment by Unitech** [comment]
Cluster mode is not advised for production services with Node 0.10.X, it's written on the terminal when you launch it,

Upgrade to 0.11.x or stay in fork mode,
Cheers
