### ISSUE TITLE
Can't run with --node-args="--harmony" with koa project

### ISSUE THREAD

**Issue by thanhnv1986** [Unitech/PM2#927]
I can't run koa project with PM2, some body help me, my code very simple

```javascript
var koa = require('koa')();

koa.use(function* (next) {
    console.log("A");
    yield next;
    console.log("B");
});

koa.use(function* (next) {
    console.log("C");
    yield next;
    console.log("D");
});

koa.use(function* () {
    console.log("E");
    this.body = "hey guys";
    console.log("F");
});

koa.listen(3000);
```
Error log:
```
>PM2: 2015-01-08 11:32:36: Script /Users/thanhnv/Documents/Nodejs/TestKoaGenerator/koa.js had >too many unstable restarts (15). Stopped. "errored"
>koa-1 (err):     at exports.runInThisContext (vm.js:73:16)
>koa-1 (err):     at Module._compile (module.js:443:25)
>koa-1 (err):     at Object.Module._extensions..js (module.js:478:10)
>koa-1 (err):     at Module.load (module.js:355:32)
>koa-1 (err):     at Function.Module._load (module.js:310:12)
>koa-1 (err):     at Function.Module.runMain (module.js:501:10)
>koa-1 (err):     at startup (node.js:124:16)
>koa-1 (err):     at node.js:842:3
>koa-1 (err): /Users/thanhnv/Documents/Nodejs/TestKoaGenerator/koa.js:3
>koa-1 (err): koa.use(function* (next) {
>koa-1 (err):                 ^
>koa-1 (err): SyntaxError: Unexpected token *
>koa-1 (err):     at exports.runInThisContext (vm.js:73:16)
>koa-1 (err):     at Module._compile (module.js:443:25)
>koa-1 (err):     at Object.Module._extensions..js (module.js:478:10)
>koa-1 (err):     at Module.load (module.js:355:32)
>koa-1 (err):     at Function.Module._load (module.js:310:12)
>koa-1 (err):     at Function.Module.runMain (module.js:501:10)
koa-1 (err):     at startup (node.js:124:16)
koa-1 (err):     at node.js:842:3
```

**Comment by Tjatse** [comment]
It seems your node doesn't support ES 6 generator, open a new terminal window, typo:
```
$ which node
$ node -v
```

Makes sure version is greater than 0.11.

Do not use `nvm use x.y.z` to change your node ver.

**Comment by Tjatse** [comment]
Are you testing this on a Mac? 
Try to link your `node` executable to v0.11.*, e.g.:
```
$ nvm use v0.11.14
$ which node
```
output:
```
$ /Users/thanhnv/.nvm/v0.11.14/bin/node
```
open a new terminal window, and typing:
```
$ which node
```
Output like:
```
$ /usr/local/bin/node
```
typing:
```
$ mv /usr/local/bin/node /usr/local/bin/node_bak
$ ln -s /Users/thanhnv/.nvm/v0.11.14/bin/node /usr/local/bin/node
```

Do your job again, it should works.

Fallback:
```
$ rm -rf /usr/loca/bin/node
$ mv /usr/loca/bin/node_bak /usr/loca/bin/node
```

**Comment by thanhnv1986** [comment]
I's tried but still error, I ready use v0.11.14, run on MacOS YOSEMITE
if i run normal
```
node --harmony koa.js
```
everything ok, but I can't run with
```
pm2 start koa.js --node-args="--harmony"
````

**Comment by Tjatse** [comment]
Just uses `COMMAND + t` to open a new terminal window, and types:
```
$ node -v
```
Show me the output.

My test (global node v0.11.14):
![term](https://cloud.githubusercontent.com/assets/1418444/5659716/30af1d56-9752-11e4-9f54-36ff92e7245e.jpg)
![browser](https://cloud.githubusercontent.com/assets/1418444/5659718/3201f034-9752-11e4-9e0a-d31bb629ca17.jpg)

**Comment by thanhnv1986** [comment]
my screen, thank you.
![screen_shot_2015-01-07_at_4_45_44_pm](https://cloud.githubusercontent.com/assets/3871494/5660013/7f39afc2-974d-11e4-94db-d311391e4633.png)
![screen shot 2015-01-08 at 3 47 19 pm](https://cloud.githubusercontent.com/assets/3871494/5660023/aaac54ca-974d-11e4-98e1-4388dce71e84.png)

**Comment by Tjatse** [comment]
Totally new? There must be some lines like following:
```
Last login: Thu Jan  8 16:14:50 on ttys002
localhost:path tjatse$ 
```
How about:
1st. run `$ pm2 kill`
2nd. Quit your terminal.
3rd. Start your terminal again.
4th. `node -v`

The error indicates that you're using a `node` executable which doesn't support ES-6.

**Comment by thanhnv1986** [comment]
oh, after i run
```
pm2 kill
```
it running, thank you very much.
