### ISSUE TITLE
File watching worked in 0.12.1 but does not in newer versions with Vagrant/Virtualbox/NFS shared folders configurations

### ISSUE THREAD

**Issue by 43n79w** [Unitech/PM2#931]
Using Vagrant (1.7.2) with Virtualbox (4.3.20) on Mac OS X 10.10.1 and a Vagrant configuration which does the following:

- Uses Vagrant's build-in docker support to provision a virtual machine that mounts a NFS shared folder. This shared folder is exposed as a docker volume.
- Launches several docker containers, one of which runs PM2 to launch a Node.JS script. PM2 watches a sub-directory of the above docker volume.

In version 0.12.1 of PM2, I could edit a watched file on my Mac OS X host and PM2 would correctly restart the application. In (at least) 0.12.3 of PM2, this is no longer the case. If I SSH into the Virtualbox and touch the same file there, PM2 restarts the application.

I've debugged this for a couple of days and tried many different Vagrant/Virtualbox/Docker configurations thinking the issue lay there. But on a whim I tried installing an older version of PM2 that had been working in a similar project, and things started to work. I noticed that there were some file watching changes in 0.12.2. Perhaps some of these changes are causing this behaviour?

**Comment by Tjatse** [comment]
We updated dependencies ([chokidar](https://www.npmjs.com/package/chokidar)) around v0.12.1, can you help to figure out whether this problem is related to `chokidar` or not?
```javascript
var chokidar = require('chokidar');
var watcher = chokidar.watch('current directory', {
  ignored: /[\/\\]\.|node_modules/, 
  persistent: true,
  ignoreInitial : true
}).on('all', function(event, path) {
  console.log(event, path);
});
```

Appreciate!

**Comment by 43n79w** [comment]
Thanks @Tjatse. I can confirm that the issue appears to lie in chokidar. I ran the above test against chokidar `~0.10.1` which was the previous PM2 dependency and was able to trigger the logging message by writing from the host machine. But when I upgraded chokidar `~0.12.1` which is the new PM2 dependency, writes from the host machine would not trigger the logging message.

**Comment by Tjatse** [comment]
@43n79w Thats nice, and thanks a lot. Can you describe this on [chokidar issues](https://github.com/paulmillr/chokidar/issues)? and reference to this by using `Unitech/PM2#931`, maybe chokidar team could give us an advice. :p

**Comment by caseywebdev** [comment]
I ran into this issue in [my own project](https://github.com/caseywebdev/cogs) using chokidar w/ vagrant/parallels/boot2docker. The problem is that the [`atomic` file watching option](https://github.com/paulmillr/chokidar/blob/master/CHANGELOG.md#chokidar-0120-8-december-2014) is being defaulted to when, over NFS, your only option is file polling as inotify events will not be triggered. My solution was to add a command line option to opt into `usePolling` and now everything is working again.

**Comment by soyuka** [comment]
> is being defaulted to when
Is there missing a word? So, @caseywebdev what's your solution? Setting `usePolling` to `false`?

**Comment by Tjatse** [comment]
maybe we should expose all the `chokidar` options.

**Comment by soyuka** [comment]
Indeed it'd also fix #870 (followSymlink)

**Comment by caseywebdev** [comment]
Sorry, it defaults to `atomic` on Linux which is why you need to explicitly set `usePolling: true` to get chokidar working over NFS. You may also want to set `boot_options: %w[actimeo=2]` in your `Vagrantfile` sync settings so that NFS will update mtimes more often than the default (which is like 15s).

**Comment by reimerp** [comment]
Hi, I can confirm this bug, using Linux with local file systems only. PM2 Version 0.12.1 is working, 0.12.2 and 0.12.3 is continously restarting the app. Tried some debugging on pm2:watch but this seem not even involved...

**Comment by rarkins** [comment]
@soyuka what is the actual fix/resolution?

**Comment by soyuka** [comment]
You can now change chokidar options through the `watch_options` variable in the schema.

@caseywebdev wrote:
> I ran into this issue in my own project using chokidar w/ vagrant/parallels/boot2docker. The problem is that the atomic file watching option is being defaulted to when, over NFS, your only option is file polling as inotify events will not be triggered. My solution was to add a command line option to opt into usePolling and now everything is working again.

So, you can change the `atomic` parameter to `true` or `false` or change the `usePolling` parameter to fit your needs. 
If I understood this issue, it wasn't really pm2-related more chokidar-related. Try playing with those parameters and if you can't fix it please come back to us!

**Comment by yads** [comment]
It still doesn't seem to be working for me with the following options:

```
  "watch": true,
  "watch_options": {
    "usePolling": true,
    "useFsEvents": false,
    "atomic": false
  }
```

Am I missing something?

**Comment by soyuka** [comment]
What's your setup?

Are you using os x ? NFS ?

**Comment by yads** [comment]
We're using nfs to mount OSX folder to Linux.

**Comment by soyuka** [comment]
So, just tried this exact configuration "watching an nfs mounted directory from os x". 

I just left the default settings and it worked, it seems that `fsEvents` are doing just fine compared to the nodejs default file system events. 

My recommendation with your settings will be to:
1. Make sure that the optional dependency "fsevents" has been build
2. Don't use polling but keep fsEvents `useFsEvents: true`

I don't know why you'd need `atomic` here, the default setting seems to work fine. According to the chokidar Readme it appears that this setting is automatically set according to the other options.

If it doesn't work, you can also use `usePolling: true`. I just tried with both `fsEvents` vs `usePolling` and both are working here.

> Client OS X 10.10.3 + pm2 0.14.3 + node 0.12.4
NFS Server on OS X 10.9.5 

![](http://www.zupmage.eu/i/rwpWO9UJu3.png)

**Comment by yads** [comment]
Thanks for the investigation. I'll have to try it out with 0.12.4. We're currently using iojs 2.3.x so maybe that has some issues. I also haven't built fsevents so I'll take a look at that as well.
