### ISSUE TITLE
Installation of startup script kicks of pm2 daemon running as root

### ISSUE THREAD

**Issue by akloeber** [Unitech/pm2#933]
After creation of the startup script and its registration as a service as root via

```
# pm2 startup ubuntu -u <USER>
```

there is a pm2 instance running as root afterwards and a working directory is created at `/root/.pm2`.

This does not make sense in this case where the user is explicitely given. Either the daemon user should match the given user `<USER>` or the daemon should not be started at all if the startup command is only meant to register the service.

As a workaround `pm2 startup ubuntu -u <USER> && pm2 kill && rm -rf ~/.pm2` could be used but the pm2 daemon still runs for a short period.

**Environment:**
Ubuntu 14.04.1 LTS
pm2 0.12.3

**Comment by soyuka** [comment]
Usually if you init pm2 after installing it `pm2 -v` - or any other command - it'll create `~/.pm2` with basic files. As the startup script has to run as root, it might lead to a `/root/.pm2` which will not be used.
Indeed, the startup script logs into the `USER` account to launch the user pm2 instance: 
`su - USER -c 'pm2 resurrect'`.

I'll see if I can find a workaround.

**Comment by pkyeck** [comment]
:+1: very annoying indeed. but thanks the workaround - will be using it as long as there is no other way around this.

**Comment by Unitech** [comment]
Closing in favor of #2559 

To try the new startup system:

```bash
$ npm install Unitech/pm2#development -g
$ pm2 update
```

```bash
$ pm2 startup     # Then copy / paste the command displayed
$ pm2 unstartup
```
