### ISSUE TITLE
`pm2 stop` starts the god daemon

### ISSUE THREAD

**Issue by jussi-kalliokoski** [Unitech/PM2#937]
The following reduced test case running on a Ubuntu machine (AWS EC2): https://gist.github.com/jussi-kalliokoski/ccb2e0b7708bfebb8155

I get the following results:

(first shell)

```
$ npm start

> pm2-daemon-starting-on-stop@ start /home/jussi
> pm2 start --no-daemon -x --name $npm_package_name $npm_package_main

pm2 launched in no-daemon mode (you can add DEBUG="*" env variable to get more messages)
2015-01-13 11:11:15: [PM2][WORKER] Started with refreshing interval: 30000
2015-01-13 11:11:15: [[[[ PM2/God daemon launched ]]]]
2015-01-13 11:11:15: BUS system [READY] on port /home/jussi/.pm2/pub.sock
2015-01-13 11:11:15: RPC interface [READY] on port /home/jussi/.pm2/rpc.sock
2015-01-13 11:11:15: Starting execution sequence in -fork mode- for app name:pm2-daemon-starting-on-stop id:0
2015-01-13 11:11:15: App name:pm2-daemon-starting-on-stop id:0 online
2015-01-13 11:11:15: [PM2] Process index.js launched
2015-01-13 11:11:15: ┌─────────────────────────────┬────┬──────┬──────┬────────┬───────────┬────────┬────────────┬──────────┐
│ App name                    │ id │ mode │ PID  │ status │ restarted │ uptime │     memory │ watching │
├─────────────────────────────┼────┼──────┼──────┼────────┼───────────┼────────┼────────────┼──────────┤
│ pm2-daemon-starting-on-stop │ 0  │ fork │ 3502 │ online │         0 │ 0s     │ 8.176 MB   │ disabled │
└─────────────────────────────┴────┴──────┴──────┴────────┴───────────┴────────┴────────────┴──────────┘
2015-01-13 11:11:15:  Use `pm2 info <id|name>` to get more details about an app
2015-01-13 11:11:15: --no-daemon option enabled = do not exit pm2 CLI
2015-01-13 11:11:15: PM2 dameon PID = 3496
2015-01-13 11:11:15: PM2: Log file "/home/jussi/.pm2/pm2.log" does not exist.
```

(second shell)

```
$ ps ax | grep -i "node\|pm"
 3489 pts/1    Sl+    0:00 npm
 3495 pts/1    S+     0:00 sh -c pm2 start --no-daemon -x --name $npm_package_name $npm_package_main
 3496 pts/1    Sl+    0:00 node /home/jussi/node_modules/.bin/pm2 start --no-daemon -x --name pm2-daemon-starting-on-stop index.js
 3502 ?        Ssl    0:00 node /home/jussi/index.js
 3509 pts/2    S+     0:00 grep -i node\|pm
$ rm -rf ~/.pm2
$ npm stop; npm start

> pm2-daemon-starting-on-stop@ stop /home/jussi
> pm2 stop $npm_package_name || true

[PM2] Spawning PM2 daemon
[PM2] Success
[PM2] Stopping pm2-daemon-starting-on-stop
[PM2] [ERROR] Process pm2-daemon-starting-on-stop not found

> pm2-daemon-starting-on-stop@ start /home/jussi
> pm2 start --no-daemon -x --name $npm_package_name $npm_package_main

pm2 launched in no-daemon mode (you can add DEBUG="*" env variable to get more messages)
>> pm2 is already daemonized ! You should kill it before launching it in no-daemon mode
[PM2] Process index.js launched
┌─────────────────────────────┬────┬──────┬──────┬────────┬───────────┬────────┬────────────┬──────────┐
│ App name                    │ id │ mode │ PID  │ status │ restarted │ uptime │     memory │ watching │
├─────────────────────────────┼────┼──────┼──────┼────────┼───────────┼────────┼────────────┼──────────┤
│ pm2-daemon-starting-on-stop │ 0  │ fork │ 3543 │ online │         0 │ 0s     │ 8.172 MB   │ disabled │
└─────────────────────────────┴────┴──────┴──────┴────────┴───────────┴────────┴────────────┴──────────┘
 Use `pm2 info <id|name>` to get more details about an app
--no-daemon option enabled = do not exit pm2 CLI
PM2 dameon PID = 3528
PM2: 2015-01-13 11:12:08: [PM2][WORKER] Started with refreshing interval: 30000
PM2: 2015-01-13 11:12:08: [[[[ PM2/God daemon launched ]]]]
PM2: 2015-01-13 11:12:08: BUS system [READY] on port /home/jussi/.pm2/pub.sock
PM2: 2015-01-13 11:12:08: RPC interface [READY] on port /home/jussi/.pm2/rpc.sock
PM2: 2015-01-13 11:12:08: Starting execution sequence in -fork mode- for app name:pm2-daemon-starting-on-stop id:0
PM2: 2015-01-13 11:12:08: App name:pm2-daemon-starting-on-stop id:0 online
```

(third shell)
```
$ ps ax | grep -i "node\|pm"
 3489 pts/1    Sl+    0:00 npm
 3495 pts/1    S+     0:00 sh -c pm2 start --no-daemon -x --name $npm_package_name $npm_package_main
 3496 pts/1    Sl+    0:00 node /home/jussi/node_modules/.bin/pm2 start --no-daemon -x --name pm2-daemon-starting-on-stop index.js
 3502 ?        Ssl    0:00 node /home/jussi/index.js
 3528 ?        Ssl    0:00 PM2 v0.12.3: God Daemon
 3530 pts/2    Sl+    0:00 npm
 3536 pts/2    S+     0:00 sh -c pm2 start --no-daemon -x --name $npm_package_name $npm_package_main
 3537 pts/2    Sl+    0:00 node /home/jussi/node_modules/.bin/pm2 start --no-daemon -x --name pm2-daemon-starting-on-stop index.js
 3543 ?        Ssl    0:00 node /home/jussi/index.js
 3549 pts/2    S+     0:00 tail -f -n 20 /home/jussi/.pm2/pm2.log
 3639 pts/4    S+     0:00 grep -i node\|pm
```

So as you can see, when `pm2 stop` gets run after the `~/.pm2` folder gets removed, the stop command doesn't find the `pid` of the PM2 instance running in `--no-daemon` mode, but what happens next is the weird part: it starts a new useless daemon. Why is this?

**Comment by Tjatse** [comment]
'Cause `pm2 stop` will spawn the *Daemon/Satan* process.
I think it has no bearing on `rm -rf ~/.pm2`, e.g.:
```bash
$ npm stop
# start Satan/Daemon up, you can find a process which is named PM2 v0.12.3: God Daemon by using 
#     ps aux | grep PM2
$ npm start
# start a no-daemon process, but unfortunately, God Daemon is already running, you'll get a tip like following:
#     >> pm2 is already daemonized ! You should kill it before launching it in no-daemon mode
# and then your 'no-daemon process' will be ran as daemonic.
```

**Comment by Tjatse** [comment]
I am going to close this, if still have questions, please feel free to reopen it or file a new one :p

**Comment by jussi-kalliokoski** [comment]
Sorry for not getting back on this earlier x)

> I think it has no bearing on `rm -rf ~/.pm2`

Actually it does: if it finds the no-daemon process by the PID stored in `~/.pm2`, it doesn't start a daemon, instead it just stops the child process of the no-daemon PM2.

I'm having a hard time understanding the logic behind the choice of a `stop` command spawning a new daemon. Currently this leads to very nasty states in our setup when there's a non-clean shutdown (for example when the service is not running and then restart is called), e.g. we get ghost daemons and sometimes even ghost instances that prevent restarting the service without `kill`ing off the ghosts.

If `pm2 stop` is not the recommended way to stop a no-daemon service, what is? SIGTERM to the pm2 process just kills of the pm2 process and not the service itself, leaving the service ghost lying around and preventing a new instance from taking over (because ports). Currently our orchestration uses upstart, where we have `npm start` as the `start` script and `npm stop` as `pre-stop` (the npm scripts are defined as in my example), which works, but is kinda fragile for the aforementioned reasons.

**Comment by Tjatse** [comment]
Oops! I just thought you were confusing about **`pm2 stop` starts a daemonic process**, never mind.
Try to use `"stop": "pm2 kill"` instead of it.

**Comment by Tjatse** [comment]
- **Enhancement**

  `pm2 stop` should graceful stop no-daemon process.

- **Bug**

  `pm2 kill` can graceful stop no-daemon process but `tail` process still exist.

**Comment by jussi-kalliokoski** [comment]
> `Try to use "stop": "pm2 kill" instead of it.`

Tried that, but `pm2 kill` seems to have no bearing on a no-daemon pm2. :/

**Comment by Tjatse** [comment]
@jussi-kalliokoski 
If `"stop": "pm2 stop ..."`, execute `npm start` in first terminal, then do `npm stop` in second terminal, the session in first terminal will not quit and the `pm2-daemon-starting-on-stop` process still exists, but PM2 Daemon will be stopped.

processes:
```
$ ps aux | egrep "node|PM2"
> ... 0:00.36 node /usr/local/bin/pm2 start --no-daemon -x --name pm2-daemon-starting-on-stop index.js
> ... 0:00.00 egrep node|PM2
```

tail logs:
```
[timestamp]: App name:pm2-daemon-starting-on-stop id:0 exited
[timestamp]: 2015-01-22 17:49:27: Process with pid [PID] killed
```

If `"stop":"pm2 kill"`, do the same operations as above, you'll find **the session in first terminal will quit graceful and the `pm2-daemon-starting-on-stop` process does not exist**.

processes:
```
$ ps aux | egrep "node|PM2"
> ... 0:00.00 egrep node|PM2
```

tail logs:
```
[timestamp]: App name:pm2-daemon-starting-on-stop id:0 exited
[timestamp]: Process with pid [PID] killed
[timestamp]: PM2 is being killed via kill method
[timestamp]: RPC socket closed
[timestamp]: PUB socket closed
```

If you still wanna `rm -rf ~/.pm2`, of course it will fail.

**Comment by Tjatse** [comment]
Hi, @jussi-kalliokoski.
My test cases on Mac:
If `"stop": "pm2 stop ..."`, execute `npm start` in first terminal, then do `npm stop` in second terminal, the session in first terminal will not quit and the `pm2-daemon-starting-on-stop` process still exists, but PM2 Daemon will be killed.

processes:
```
$ ps aux | egrep "node|PM2"
> ... 0:00.36 node /usr/local/bin/pm2 start --no-daemon -x --name pm2-daemon-starting-on-stop index.js
> ... 0:00.00 egrep node|PM2
```

tail logs:
```
[timestamp]: App name:pm2-daemon-starting-on-stop id:0 exited
[timestamp]: 2015-01-22 17:49:27: Process with pid [PID] killed
```

If `"stop":"pm2 kill"`, do the same operations as above, you'll find **the session in first terminal will quit graceful and the `pm2-daemon-starting-on-stop` process does not exist**.

processes:
```
$ ps aux | egrep "node|PM2"
> ... 0:00.00 egrep node|PM2
```

tail logs:
```
[timestamp]: App name:pm2-daemon-starting-on-stop id:0 exited
[timestamp]: Process with pid [PID] killed
[timestamp]: PM2 is being killed via kill method
[timestamp]: RPC socket closed
[timestamp]: PUB socket closed
```

It seems not the way you want, does it?
If you still wanna `rm -rf ~/.pm2`, of course it will fail, `pm2 stop` will start the PM2 Daemon again if there is no RPC socket (path `~/.pm2/rpc.sock`).
