### ISSUE TITLE
when start pm2 by JSON it will failed if no log file exists

### ISSUE THREAD

**Issue by zhouseahe** [Unitech/PM2#939]
why don't pm2  create one if it doesn't exists .

**Comment by Tjatse** [comment]
It's totally doable, but no necessary.
I think it is far beyond the ability of PM2, the reality is more complex, e.g.:
```JSON
{
  "out_file": "/path/to/foo/bar/out.log"
}
```
We need to do:
```bash
mkdir /path                     # if /path does not exist.
mkdir /path/to                  # if /path/to does not exist.
mkdir /path/to/foo              # if /path/to/foo does not exist.
mkdir /path/to/foo/bar          # if /path/to/foo/bar does not exist.
```

Even if we could `mkdir` for you, how about the access permissions of log files / directories? maybe you want it to be `777`, but Tommy want `755`.

So, make sure your log directory is valid, then run your process by `pm2 start`. What do you say?

**Comment by elyas-bhy** [comment]
For creating the folders hierarchy, take a look at [mkdir -p](https://www.gnu.org/software/coreutils/manual/html_node/mkdir-invocation.html).
As for the permissions, you can either set a reasonable default, use the system default, or even load it from a config file.

**Comment by soyuka** [comment]
+1 @elyas-bhy and there is also a https://www.npmjs.com/package/mkdirp npm package if you need :).

@Tjatse agreed.

**Comment by Tjatse** [comment]
@elyas-bhy Thanks, `mkdir -p` is good, but my point is not how to create hierarchic directories, the access permissions of directories are bombs, and in order to run `mkdir`, sometimes we need upgrade permission. e.g.: 
```bash
$ sudo pm2 start ...
```
Thats not a good idea.

**Comment by soyuka** [comment]
@Tjatse I totally agree, this will not be an integrated feature.

**Comment by Tjatse** [comment]
@soyuka Yup, **Security Problems** will turn up, and that happened before - the TCP leak :p

**Comment by soyuka** [comment]
I'm closing this. Feel free to keep commenting but there is no issue there :).

**Comment by zhouseahe** [comment]
thx all ,  just want to create file , not the path

**Comment by soyuka** [comment]
File is created if directory has correct rights.
