### ISSUE TITLE
Startup script fails on OpenSuse: Can't find active process / dump file (with solution)

### ISSUE THREAD

**Issue by nikolasleblanc** [Unitech/pm2#943]
After launching a pm2 process:

```
pm2 start app.js
```

and running the startup script with my username:

```
sudo env PATH=$PATH:/usr/local/bin pm2 startup systemd -u <myusername>
```

I got this error:

```
-systemd- Using the command su -c "pm2 dump && pm2 kill && systemctl daemon-reload && systemctl enable pm2 && systemctl start pm2"
Command failed: [PM2] [WARN] No process found
```

Got around it by creating my own dump file:

```
pm2 dump
```

then running the startup script again:

```
sudo env PATH=$PATH:/usr/local/bin pm2 startup systemd -u <myusername>
```

Is this expected behaviour?

**Comment by jshkurti** [comment]
Yes it's excpected.
When you ```sudo```, you are running pm2 as root, so it's a new instance of pm2 and thus it doesn't find any processes launched yet ([PM2] [WARN] No process found).
You gotta do it whith the same user :)

**Comment by sboulkour** [comment]
Hi everyone !

I get the same error with RHEL 7 (using systemd), see my outputs below.

@jshkurti It doesn't makes sense to me. I mean how do you setup a startup script with a non-root user ? Also from various docs on-line (such as  https://www.digitalocean.com/community/tutorials/how-to-use-pm2-to-setup-a-node-js-production-environment-on-an-ubuntu-vps), it seems that this command works but for startup modes others that systemd ...

Also 'sudo -c' containing systemctl commands doesn't feel right here. My simple user doesn't have rights to run systemctl, which is to be expected.


with '-u nodejs'
```
[root@vm20 -----]# env PATH=$PATH:/usr/bin pm2 startup systemd -u nodejs
[PM2] Spawning PM2 daemon
[PM2] PM2 Successfully daemonized
[PM2] Generating system init script in /etc/systemd/system/pm2.service
[PM2] Making script booting at startup...
[PM2] -systemd- Using the command:
      su -c "pm2 dump && pm2 kill && systemctl daemon-reload && systemctl enable pm2 && systemctl start pm2"
Command failed: [PM2][WARN] No process found
Job for pm2.service failed. See 'systemctl status pm2.service' and 'journalctl -xn' for details.
----- Are you sure you use the right platform command line option ? centos / redhat, amazon, ubuntu, gentoo, systemd or darwin?
[root@vm20 -----]# 
```

without '-u nodejs'
```
[root@vm20 ansible]# env PATH=$PATH:/usr/bin pm2 startup systemd
[PM2] Spawning PM2 daemon
[PM2] PM2 Successfully daemonized
[PM2] Generating system init script in /etc/systemd/system/pm2.service
[PM2] Making script booting at startup...
[PM2] -systemd- Using the command:
      su -c "pm2 dump && pm2 kill && systemctl daemon-reload && systemctl enable pm2 && systemctl start pm2"
[PM2] Dumping processes
[PM2] Stopping PM2...
[PM2] All processes has been stopped and deleted
[PM2] PM2 stopped
[PM2] Done.
[root@vm20 ansible]#
```

**Comment by sboulkour** [comment]
@jshkurti any chance to have an update here ?

**Comment by Unitech** [comment]
OpenSuse use systemd and now fixed

https://github.com/Unitech/pm2/issues/2559

```
$ pm2 startup systemd
```
