### ISSUE TITLE
Not available to run pm2 on ubuntu

### ISSUE THREAD

**Issue by vorillaz** [Unitech/PM2#945]
Hello there I have a simple small app under a subdomain on my VM. 
Running `node /var/www/vhosts/subdomain.example.com/app.js` and hitting http://subdomain.example.com makes my app running.

Hitting on the exact same command using pm2 gives me This webpage is not available.
Any ideas?

**Comment by jshkurti** [comment]
What does ```pm2 logs``` say ?

**Comment by Unitech** [comment]
While we are still waiting to get more feedback about this, i'm closing it
