### ISSUE TITLE
Tests failed on CentOS 6.5

### ISSUE THREAD

**Issue by Jokero** [Unitech/PM2#950]
OS: CentOS release 6.5 (Final)
node: 0.11.14
pm2: 0.12.3

Logs: https://gist.github.com/Jokero/e17552c67929dc1d05ad

Tried to install pm2@latest and git://github.com/Unitech/pm2#development, but there is no difference

**Comment by jshkurti** [comment]
```Error: channel closed``` is a well-known cluster module bug ( https://github.com/joyent/node/issues/8792 ) which happens quite randomly.
Try launching tests again and tell us if it worked :)
