### ISSUE TITLE
Orphan process

### ISSUE THREAD

**Issue by crashbell** [Unitech/PM2#952]
After add/remove some process, I found out that there are 2 orphan processes which aren't tracked by PM2. I ran `top` and `pm2 list` to compare PIDs. I tried to `kill PID` but PM2 always restarted them automatically. How can I kill them without restarting PM2 (running on production)?

Using version: 0.12.3

**Comment by Unitech** [comment]
`pm2 update` can restart pm2 again with the previous processes (and you
could get rid of these orphan ones)

Btw orphan process, if there are, can't be restarted automatically by pm2.
Instead of top, use htop and list by thread tree to see if there are
detached from pm2 or not.

**Comment by crashbell** [comment]
@Unitech please see my screenshots: 
I have 3 master processes of `app.coffee` but only one PID I can find when running `pm2 list` (app name `http`, PID `23196`)
![screen shot 2015-01-20 at 2 53 09 pm](https://cloud.githubusercontent.com/assets/810139/5813699/5f53ebe4-a0b4-11e4-94b8-ccbad419bea1.png)
![screen shot 2015-01-20 at 2 53 31 pm](https://cloud.githubusercontent.com/assets/810139/5813700/5f57c5e8-a0b4-11e4-8de1-1a7df1335c3b.png)

**Comment by jshkurti** [comment]
These do not look like orphan processes since they're attached to PM2.
That's just the mysterious way Node.js handles processes.
Try ```pm2 kill``` and if the processes are still there that would be a bug :)

**Comment by kangjoonsoo** [comment]
That's exactly the same issue what I have.
`pm2 list` doesn't list orphan process but PM2 God Daemon reborns orphan process when I kill it.
Orphan process also has same PPID(PM2 God Daemon) and `pm2 restart [app_name]` command also restarts all processes including orphans.
This issue makes port conflict.

I'll try to make clear reproducing environment.

**Enviroment**
PM2 version:  0.12.3
Deployment tool: Capistrano

**Comment by crashbell** [comment]
I had to run `pm2 update` and PM2 didn't manage those processes anymore. And then I kill them manually. I have no idea how this issue happened.

**Comment by Unitech** [comment]
It may happen on pm2 upgrade or when using Node 0.10.x with cluster mode.
A recent commit has also been made to avoid restarting some processes. It's on the master branch but haven't been published yet.

So if you experience this, the `pm2 update` seems the preferred way to stop monitoring these processes. @crashbell if you get orphan processes one more time, please tell us

**Comment by crashbell** [comment]
thanks @Unitech 
I'll try to upgrade Node to the latest one and take a look on PM2. I'll let you know if I run into the problem again.

**Comment by macobo** [comment]
Just saying that we're seeing these errors regularly on 0.12.7

**Comment by zeluis9** [comment]
I am experiencing some issues like this one and I think they are related to pm2. All the processes somehow "detached" (I don't know how) from pm2 and are running standalone(I can see them in `ps aux | grep node`). If i kill them manually (`kill -SIGTERM <pid>`) they restart automatically (or automagically? :laughing:). I have already checked `/etc/init.d` , but no startup script is defined to my apps. `pm2 status` or `pm2 list` comes up with an empty list :crying_cat_face: 

Node version: 4.3.2 (latest)
PM2 version: 1.0.1 (latest)
OS: Ubuntu Server 14.04.4 LTS (latest with all the updates installed)
