### ISSUE TITLE
How to deploy without git?

### ISSUE THREAD

**Issue by kai1987** [Unitech/PM2#953]
Hello everyone, I want use PM2 to deploy my local source to server. I want to do this because
 1, git pull is very slow in china mainland (fuck GFW).  
 2, I have to encrypt my source code before deployment. 
Now I use capstrnal ,but I really want to try PM2 。Any ideas ？ thx.

**Comment by Tjatse** [comment]
> fuck GFW

哈哈!!!

deploy是基于git部署的，你可以尝试:
- 1. 使用gitstack在windows服务器或虚机上快速搭建一个本地的git服务器，将json配置文件里的repo替换成本地git仓库地址。
- 2. 翻墙。。。

**Comment by kai1987** [comment]
谢谢。
