### ISSUE TITLE
pm2 restart/reload fails

### ISSUE THREAD

**Issue by lovio** [Unitech/PM2#955]
- node `0.10.35`
- pm2  `0.12.3`

If I try `pm2 restart all`, all clusters will be restarted. But my service is not accessible.
There is a process called `cisco-sccp` ocuppied the service-port, such as `2000`.
I need to do these steps  in order to make my service accessible:
-  `pm2 delete all`
- `lsof -i :2000` to find the cisco-sccp's pid.
- kill `cisco-sccp`
- `pm2 start app.js -i 0`

**Comment by Tjatse** [comment]
PM2 日志能看到吗？是否提示*EADDRINUSE*，如果是的话说明你的服务器端口被别的进程占用了, `pm2 restart all` 肯定失败。
能尝试换一个别的非常用端口吗？比如8080之类的。

> cisco-sccp      2000/tcp   Cisco SCCP
> cisco-sccp      2000/udp   Cisco SCCp

**Comment by skipify** [comment]
node 0.10.34
pm2 0.12.3

first
      pm2 start app.js -i 0
Ok!!!
then:
   pm2 reload all
Does not work


    pm2 kill
    pm2 start app.js -i 0

Ok !!!

The whole process without error

**Comment by Unitech** [comment]
Do not use cluster mode with NodeJS 0.10.X
