### ISSUE TITLE
Windows start works only with -i specified

### ISSUE THREAD

**Issue by HalfdanJ** [Unitech/PM2#956]
Running `pm2 start app.js` does not return any errors, but does not start any instances. 

Running `pm2 start app.js -i 1` does start an instance, but i'm not sure its actually running. Calling `pm2 monit` does show it, but `pm2 logs` returns the error 
```
Log file "C:\Users\username\.pm2\logs\app-out-2.log" does not exists.`
```

Also having pm2 running makes the node.exe window constantly popup. 

I'm running Windows 7, and with the latest node js.

**Comment by Unitech** [comment]
@Atelier-Morales @jshkurti could you try and handle this?

**Comment by echiu64** [comment]
Also try setting PM2_HOME to c:\users\username\.pm2 (sub username for your username)
This pull should patch the issue with where child process log files go when PM2_HOME isn't set:
https://github.com/Unitech/PM2/pull/982

**Comment by jshkurti** [comment]
@HalfdanJ is this fixed with the last pm2 version ? :)

**Comment by HalfdanJ** [comment]
Yep
