### ISSUE TITLE
Status for node 0.10.x running pm2 on cluster mode

### ISSUE THREAD

**Issue by geekyme** [Unitech/PM2#957]
Hi guys, 

What's the status for the cluster mode option on latest pm2 + node 0.10.x? 
When I tried the command it appears that only 1 process is being started. 

<pre>
user@server:~$ pm2 start app -i max
[PM2] [WARN] Deprecated, we recommend using 0 instead of max to indicate maximum of instances.
[PM2] [WARN] You should not use the cluster_mode (-i) in production, it's still a beta feature. A front HTTP load balancer or interaction with NGINX will be developped in the future.
</pre>

![image](https://cloud.githubusercontent.com/assets/977460/5869689/f6403bf8-a2f7-11e4-8bd0-02a7fde02ef3.png)

**Comment by Tjatse** [comment]
`node v0.10.x` has too many bugs with [*cluster module*](http://nodejs.org/api/cluster.html), try to use node v0.11.x instead of it if you still wanna use cluster mode.

**Comment by jshkurti** [comment]
Node.js cluster module is still unstable (https://nodejs.org/docs/latest/api/cluster.html)
But as the warning says, ```-i max``` is deprecated, try ```-i 0``` instead :)

**Comment by geekyme** [comment]
I see. Are there other ways I can try to make node make use of my quad core CPUs ?

**Comment by jshkurti** [comment]
```-i 0``` works fine :)
The cluster module status is 'experimental' but it works nevertheless.
It is just not recommended using it in production for the moment but it still works fine most of the time.

**Comment by Unitech** [comment]
I definetely not recommend to use it with Node 0.10.x.
With Node 0.11.14+ & iojs it's much better

**Comment by geekyme** [comment]
I just tried it with node v0.11.15. It is not working for me

PM2: 2015-01-27 10:51:07: Error: spawn ENOENT
PM2:     at errnoException (child_process.js:1011:11)
PM2:     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
PM2: 2015-01-27 10:51:07: App name:app id:8 exited
PM2: 2015-01-27 10:51:07: Starting execution sequence in -cluster mode- for app name:app id:8
PM2: 2015-01-27 10:51:07: Error: spawn ENOENT
PM2:     at errnoException (child_process.js:1011:11)
PM2:     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
PM2: 2015-01-27 10:51:07: App name:app id:8 exited
PM2: 2015-01-27 10:51:07: Starting execution sequence in -cluster mode- for app name:app id:8
PM2: 2015-01-27 10:51:07: Error: spawn ENOENT
PM2:     at errnoException (child_process.js:1011:11)
PM2:     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
PM2: 2015-01-27 10:51:07: App name:app id:8 exited
PM2: 2015-01-27 10:51:07: Script /home/carousell/aizen/app.js had too many unstable restarts (15). Stopped. "errored"

**Comment by jshkurti** [comment]
We had some incompatibility issues with Node.js v0.11.15.
It is fixed now :)
```npm install git://github.com/Unitech/pm2#master -g``` and try again.

**Comment by geekyme** [comment]
ok all’s good now. pm2 is at 0.12.3 and all I needed to do was to pm2 kill, then restart all my apps. 

Works like a charm. Thanks so much.

**Comment by jshkurti** [comment]
You're welcome, thanks for the feedback.
We'll publish pm2 0.12.4 soon ;)

**Comment by pravin-mindstix** [comment]
Hi, 

I used    pm2 start app -i  command still it showing one process running as fork mode.

my node version is  
node -v
v0.12.0

**Comment by jorge-d** [comment]
@pravin-mindstix Which version pm2 ?

**Comment by pravin-mindstix** [comment]
i am using
pm2 -v
0.12.7

**Comment by jorge-d** [comment]
I just tested with `node v0.12.0` and `pm2 0.12.7` and everything seems to be working fine...
Could you do a simple test ? run `pm2 kill; pm2 start app.js -i 0` and tell me whether it starts in cluster of fork mode ?

**Comment by pravin-mindstix** [comment]
Ohh.. after pm2 kill;  its work for me  :)

i hit   pm2 start app.js -i 4  and its showing 4 cluster mode. :)

Thank you so much Jorge-d
