### ISSUE TITLE
PM2 not responding

### ISSUE THREAD

**Issue by alihalabyah** [Unitech/PM2#960]
Looks like PM2 is stuck at some point and won't respond to any command:

I'm trying to execute the following:

`pm2 ls` or even `pm2 kill`

But it keeps showing:

`[PM2] Spawning PM2 daemon`
`[PM2] Success`

**Comment by Tjatse** [comment]
Try to execute following cmds:
```bash
$ ps aux | grep PM2 | xargs kill -9
$ pm2 updatePM2
```

If this issue still exists, show me the pm2.log through
```bash
$ tail -n 100 ~/.pm2/pm2.log
```

**Comment by soyuka** [comment]
Closing, 15 days waiting.
