### ISSUE TITLE
too many open files, again.

### ISSUE THREAD

**Issue by chiarishow** [Unitech/PM2#962]
Hi,

after about 90-100 restarts, node gives me "too many open files" error. 

PM2 Version is 0.12.1 and my process is in fork mode because sometimes it doesn't free the server http port in cluster mode. 

Thank you.

**Comment by Unitech** [comment]
I started 10 processes in fork mode that auto exits (PM2 0.12.3 + Node 0.11.14) and run the command

`$ ps -aef | wc -l`

The open file descriptors does not increase at all

**Comment by chiarishow** [comment]
Ok I will try monitoring the open file descriptors using the last version. I will report back if I find any problem. Thank you!

**Comment by michaelBenin** [comment]
Running this has worked for me before with the same error:

    echo 'kern.maxfiles=20480' | sudo tee -a /etc/sysctl.conf && echo -e 'limit maxfiles 8192 20480\nlimit maxproc 1000 2000' | sudo tee -a /etc/launchd.conf && echo 'ulimit -n 4096' | sudo tee -a /etc/profile

**Comment by wmbutler** [comment]
Looking for a way to set the ulimit -n while running pm2. It's possible with node, but pm2 seems to ignore it:

Node
```
/bin/bash -c "ulimit -n 200000; node ./test.js"
stdout is 200000
```

PM2
```
/bin/bash -c "ulimit -n 200000; pm2 start ./test.js"
[PM2] Process ./test.js launched

PM2: 2015-03-30 14:48:51: Script /home/ubuntu/test.js had too many unstable restarts (15). Stopped. "errored"
test-4 (out): stdout is 1024
test-4 (out): stdout is 1024
test-4 (out): stdout is 1024
test-4 (out): stdout is 1024
test-4 (out): stdout is 1024
test-4 (out): stdout is 1024
test-4 (out): stdout is 1024
test-4 (out): stdout is 1024
test-4 (out): stdout is 1024
test-4 (out): stdout is 1024
```

Here is the test.js script
```
var exec = require('child_process').exec;
exec('ulimit -n', function (error, stdout, stderr) {
  // output is in stdout
  console.log('stdout is', stdout.toString());
});
```

**Comment by jshkurti** [comment]
You have to set it before the PM2 daemon is launched.
```/bin/bash -c "ulimit -n 200000; pm2 kill; pm2 start ./test.js"```

**Comment by wmbutler** [comment]
So I'd have to issue a:

`pm2 kill`

followed by that to ensure that the daemon was being launched for the first time. I discovered that the proper procedure for setting the ubuntu server is here http://posidev.com/blog/2009/06/04/set-ulimit-parameters-on-ubuntu/ and be sure to reboot the server once complete to force applications to respect it. Even pm2 respects it once the server has been rebooted.

**Comment by Unitech** [comment]
this has been fixed, please update PM2
