### ISSUE TITLE
Can't upload to Amazon s3

### ISSUE THREAD

**Issue by sean-hill** [Unitech/PM2#964]
Hey there,

I have this upload code using the `awssum-amazon-s3` module.

    var options = {
        BucketName    : Conf.amazon.image_bucket
        , ObjectName    : bucketPath
        , ContentLength : fileInfo.size
        , Body          : bodyStream
        , ContentType   : file.contentType
    };

    s3.PutObject(options, function(err, data) {
       // ...
    });

When starting my server with `NODE_ENV=production node server.js` the upload works just fine with node and amazon.

However when starting my server with `pm2` like `pm2 start processes.json` my app crashes right before the `PutObject` method call and `pm2` shoots out these logs:

	PM2: 2015-01-27 18:06:17: App name:Unbill API id:1 exited
	PM2: 2015-01-27 18:06:17: Process with pid 16546 killed
	PM2: 2015-01-27 18:06:17: Starting execution sequence in -fork mode- for app name:Unbill API id:1
	PM2: 2015-01-27 18:06:17: App name:Unbill API id:1 online

I don't believe there is an error with my node app because no `uncaughtException` event is fired. I have these lines in my `server.js`.

    process.on('uncaughtException', function(error, stack){
        console.log('Uncaught Error');
        console.log(error.stack);
    });

This is never called.

Here is my `processes.json` in case that's helpful.

	{
	    "apps" : [{
	        "name"        : "Unbill API",
	        "script"      : "server.js",
	        "watch" 	  : true,
	        "node_args"   : "--max-old-space-size=8192 --nouse-idle-notification",
	        "env": {
	            "NODE_ENV": "production"
	        }
	    }]
	}

I'm curious why `pm2` is restarting, or whatever it's doing when I do this amazon upload.

Thanks

**Comment by Unitech** [comment]
Could you just `pm2 start server.js` and see if it's working?
Also doing some raw console.log to log some messages

(The fork-mode do anything else than a process forking)

**Comment by sean-hill** [comment]
@Unitech `pm2 start server.js` has the same issue. I remove the logs from my post because I didn't think they were relevant, but that's how I figured out that at `s3.putObject` was where my app restarted using `pm2`. None the less, here's my full code sample with logs.

    exports.write = function (file, bucketPath, wrote) {

        console.log('Works 1');

        if (!file || !bucketPath) {
            return wrote('Invalid Fields');
        }

        var fileLocation = Conf.downloadsPath + '/' + file.name;

        console.log('Works 2');

        fs.stat(fileLocation, function(err, fileInfo) {

            if (err) {
                return wrote(err)
            }

            var bodyStream = fs.createReadStream( fileLocation );

            var options = {
                BucketName    : Conf.amazon.image_bucket
                , ObjectName    : bucketPath
                , ContentLength : fileInfo.size
                , Body          : bodyStream
                , ContentType   : file.contentType
            };

            console.log('Works 3');

            s3.PutObject(options, function(err, data) {

                console.log('DOESNT WORK, app crashed');

                if (err) {
                    return wrote(err);
                }
                else {
                    return wrote();
                }
            });

        });

    }

And the logs after running that

	Unbill API-1 (out): STATE: Production
	Unbill API-1 (out): Unbill API listening on port 3000
	Unbill API-1 (out): Mongoose Connected
	Unbill API-1 (out): Uploading avatar!
	Unbill API-1 (out): { file:
	Unbill API-1 (out):    { fieldname: 'file',
	Unbill API-1 (out):      originalname: 'cdv_photo_020.jpg',
	Unbill API-1 (out):      name: '7d1af69f9f34ae55b55373bf926b9e92.jpg',
	Unbill API-1 (out):      encoding: '7bit',
	Unbill API-1 (out):      mimetype: 'image/jpeg',
	Unbill API-1 (out):      path: 'downloads/7d1af69f9f34ae55b55373bf926b9e92.jpg',
	Unbill API-1 (out):      extension: 'jpg',
	Unbill API-1 (out):      size: 795616,
	Unbill API-1 (out):      truncated: false,
	Unbill API-1 (out):      buffer: null } }
	Unbill API-1 (out): Works 1
	Unbill API-1 (out): Works 2
	Unbill API-1 (out): Works 3
	PM2: 2015-01-27 19:24:09: App name:Unbill API id:1 exited
	PM2: 2015-01-27 19:24:09: Process with pid 19210 killed
	PM2: 2015-01-27 19:24:09: Starting execution sequence in -fork mode- for app name:Unbill API id:1
	PM2: 2015-01-27 19:24:09: App name:Unbill API id:1 online
	Unbill API-1 (out): STATE: Production
	Unbill API-1 (out): Unbill API listening on port 3000
	Unbill API-1 (out): Mongoose Connected

Thanks for the help!

**Comment by soyuka** [comment]
Are you sure that you can send a Stream as the bucket Body?

```
 var bodyStream = fs.createReadStream( fileLocation );
```

Any docs about putObject? I could only find the following: http://aws.amazon.com/fr/sdk-for-node-js/.

Thanks!

**Comment by sean-hill** [comment]
@soyuka I'm positive about the stream :) It works great on my local machine, no `pm2`, and with just `node server.js` on my production server, it's only when I run `pm2 start server.js` that this issue is happening. So weird.

**Comment by sean-hill** [comment]
The only thing I can think of is that `pm2` doesn't like writing large files to a remote server? But I can't see why that should affect `pm2` at all.

**Comment by soyuka** [comment]
https://github.com/chilts/awssum-amazon-s3#streaming indeed!

I don't think that pm2 affects the stream.

**Comment by sean-hill** [comment]
@soyuka, so what are you saying? My code looks nearly identical to the sample you just linked too.

**Comment by Unitech** [comment]
This is strange, if you:

```
var options = {
            BucketName    : Conf.amazon.image_bucket
            , ObjectName    : bucketPath
            , Body          : 'HEYYY!'
        };

        console.log('Works 3');

        s3.PutObject(options, function(err, data) {

            console.log('DOESNT WORK, app crashed');

            if (err) {
                return wrote(err);
            }
            else {
                return wrote();
            }
        });
```

 does it works ?

**Comment by sean-hill** [comment]
This time it got past the callback, but amazon threw an error, of course, but then `pm2` reset again as you can see in the logs.

	Unbill API-4 (out): Amazon write err: { Code: 'AwsSumCheck', Message: 'Provide a ContentLength' }
	PM2: 2015-01-27 22:15:45: App name:Unbill API id:4 exited
	PM2: 2015-01-27 22:15:45: Process with pid 24988 killed
	PM2: 2015-01-27 22:15:45: Starting execution sequence in -fork mode- for app name:Unbill API id:4
	PM2: 2015-01-27 22:15:45: App name:Unbill API id:4 online

**Comment by Tjatse** [comment]
@sean-hill `ContentLength` is missing.
```javascript
var options = {
  BucketName: Conf.amazon.image_bucket,
  ObjectName: bucketPath,
  Body: 'HEYYY!',
  ContentLength: '6'
};

console.log('Works 3');

s3.PutObject(options, function(err, data) {

  console.log('DOESNT WORK, app crashed');

  if (err) {
    return wrote(err);
  } else {
    return wrote();
  }
});
```

**Comment by sean-hill** [comment]
@Tjatse yes I know, I was just trying the example @Unitech asked for :)

**Comment by Tjatse** [comment]
@Unitech missed the `ContentLength` :p 
I would like to help you figure this out, but unfortunately, it's a big problem for me to register AWS account, I am in China (WTF).......

**Comment by soyuka** [comment]
@sean-hill Could you try with the example provided by @Tjatse? 

Thanks. I'm not familiar with EC2 instances but I could try to register one!

**Comment by jshkurti** [comment]
Which version of pm2 and node.js are you using ?

**Comment by sean-hill** [comment]
@soyuka, @Tjatse example gave the same results.

@jshkurti,
   $ pm2 -v
    0.12.3

    $ node -v
    v0.10.25

**Comment by sean-hill** [comment]
All right new news, it looks like it's not actually Amazon! :)

	// Uploads an avatar
	exports.avatar = function(req, res) {

		var file = req.files.file;
		file.contentType = file.mimetype;

		console.log('Uploading avatar :)');

		console.log(file);

		// AmazonS3.write(file, 'uploads/avatars/' + file.name, function(err){

		// 	if (err) {
		// 		console.log('Amazon write err:', err);
		// 	}

		// 	fs.unlink(Conf.downloadsPath + '/' + file.name);

		// 	console.log('4');
			
			return res.status(200).json({ fileName: file.name });

		//});

	};

I decided, just comment out the Amazon stuff, and see if the request even responds. Check out these logs.

	Unbill API-4 (out): Uploading avatar :)
	Unbill API-4 (out): { fieldname: 'file',
	Unbill API-4 (out):   originalname: 'cdv_photo_005.jpg',
	Unbill API-4 (out):   name: '6609af9d8ba5055280e9a6602981460e.jpg',
	Unbill API-4 (out):   encoding: '7bit',
	Unbill API-4 (out):   mimetype: 'image/jpeg',
	Unbill API-4 (out):   path: 'downloads/6609af9d8ba5055280e9a6602981460e.jpg',
	Unbill API-4 (out):   extension: 'jpg',
	Unbill API-4 (out):   size: 1360577,
	Unbill API-4 (out):   truncated: false,
	Unbill API-4 (out):   buffer: null,
	Unbill API-4 (out):   contentType: 'image/jpeg' }
	Unbill API-4 (out): Wed, 28 Jan 2015 15:12:26 GMT - POST /api/upload/avatar responded 200 in 39.459 ms - 127.0.0.1 - - Mozilla/5.0 (iPhone; CPU iPhone OS 10_10_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12B411 (2072514576)
	PM2: 2015-01-28 15:12:26: App name:Unbill API id:4 exited
	PM2: 2015-01-28 15:12:26: Process with pid 20647 killed
	PM2: 2015-01-28 15:12:26: Starting execution sequence in -fork mode- for app name:Unbill API id:4
	PM2: 2015-01-28 15:12:26: App name:Unbill API id:4 online
	Unbill API-4 (out): STATE: Production
	Unbill API-4 (out): Unbill API listening on port 3000
	Unbill API-4 (out): Mongoose Connected

It the upload request responds with a `200`, and then weird `pm2` thing happens.

**Comment by soyuka** [comment]
@sean-hill Could you try implementing [`onError`](https://www.npmjs.com/package/multer#onerror-) or some [`onFileUploadXXX`](https://www.npmjs.com/package/multer#onfileuploadcomplete-file-) listeners to log and see what is going wrong?

**Comment by sean-hill** [comment]
You betcha, @soyuka, stand by.

**Comment by sean-hill** [comment]
SO WEIRD...no errors for file upload.

Code:
    app.use(multer({ 
        dest: './downloads/' 
        , onError: function(err) {

        }
        , onFileUploadStart: function (file) {
            console.log(file.fieldname + ' is starting ...')
        }
        , onFileUploadData: function (file, data) {
            console.log(data.length + ' of ' + file.fieldname + ' arrived')
        }
        , onFileUploadComplete: function (file) {
            console.log(file.fieldname + ' uploaded to  ' + file.path)
        }
        , onError: function (error, next) {
            console.log('Upload file error:', error)
            next(error)
        }
        , onFileSizeLimit: function (file) {
              console.log('Failed file size limit: ', file.originalname)
              fs.unlink('./' + file.path) // delete the partially written file
        }
    }));

Logs:
	Unbill API-4 (out): STATE: Production
	Unbill API-4 (out): Unbill API listening on port 3000
	Unbill API-4 (out): Mongoose Connected
	Unbill API-4 (out): file is starting ...
	Unbill API-4 (out): 64870 of file arrived
	Unbill API-4 (out): 65536 of file arrived
	Unbill API-4 (out): 65536 of file arrived
	Unbill API-4 (out): 65536 of file arrived
	Unbill API-4 (out): 65536 of file arrived
	Unbill API-4 (out): 65536 of file arrived
	Unbill API-4 (out): 65536 of file arrived
	Unbill API-4 (out): 50700 of file arrived
	Unbill API-4 (out): file uploaded to  downloads/5a95b60615d1536cb4ba3723f53ec809.jpg
	Unbill API-4 (out): Uploading avatar :)
	Unbill API-4 (out): { fieldname: 'file',
	Unbill API-4 (out):   originalname: 'cdv_photo_006.jpg',
	Unbill API-4 (out):   name: '5a95b60615d1536cb4ba3723f53ec809.jpg',
	Unbill API-4 (out):   encoding: '7bit',
	Unbill API-4 (out):   mimetype: 'image/jpeg',
	Unbill API-4 (out):   path: 'downloads/5a95b60615d1536cb4ba3723f53ec809.jpg',
	Unbill API-4 (out):   extension: 'jpg',
	Unbill API-4 (out):   size: 508786,
	Unbill API-4 (out):   truncated: false,
	Unbill API-4 (out):   buffer: null,
	Unbill API-4 (out):   contentType: 'image/jpeg' }
	Unbill API-4 (out): Wed, 28 Jan 2015 15:28:38 GMT - POST /api/upload/avatar responded 200 in 35.192 ms - 127.0.0.1 - - Mozilla/5.0 (iPhone; CPU iPhone OS 10_10_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12B411 (2072514576)
	PM2: 2015-01-28 15:28:38: App name:Unbill API id:4 exited
	PM2: 2015-01-28 15:28:38: Process with pid 21220 killed
	PM2: 2015-01-28 15:28:38: Starting execution sequence in -fork mode- for app name:Unbill API id:4
	PM2: 2015-01-28 15:28:38: App name:Unbill API id:4 online
	Unbill API-4 (out): STATE: Production
	Unbill API-4 (out): Unbill API listening on port 3000
	Unbill API-4 (out): Mongoose Connected

**Comment by sean-hill** [comment]
One thing I just confirmed is that when a file to upload comes through with the request, that is when `pm2` restarts. For instance, go use something like the Postman extension for Chrome and post to `https://unbill.co/api/upload/avatar`, you'll see that it responds just fine, and my server doesn't restart. So it looks like it's something to do with file uploading and `multipart/form-data`.

**Comment by jshkurti** [comment]
Can you ```npm install git://github.com/Unitech/pm2#hotfix -g```, reproduce the bug, and show us the logs please ? :)

**Comment by soyuka** [comment]
I tried to reproduce with this basic repo: https://github.com/soyuka/testpm2964

Everything went fine while uploading, with or without pm2 (cluster or fork mode are both working).

**Comment by sean-hill** [comment]
@jshkurti I ran that and got this, just making sure it's okay.

	$ pm2 -v

	>>>> In-memory PM2 is out-of-date, do:
	>>>> $ pm2 updatePM2
	In memory PM2 version: 0.12.3
	Local PM2 version: 0.12.4

	0.12.4

**Comment by jshkurti** [comment]
Yep, just ```pm2 kill``` and start again :)

**Comment by sean-hill** [comment]
Hey @jshkurti here ya go.

	Unbill API-0 (out): file is starting ...
	Unbill API-0 (out): 21177 of file arrived
	Unbill API-0 (out): 65536 of file arrived
	Unbill API-0 (out): 65536 of file arrived
	Unbill API-0 (out): 65536 of file arrived
	Unbill API-0 (out): 65536 of file arrived
	Unbill API-0 (out): 65536 of file arrived
	Unbill API-0 (out): 65536 of file arrived
	Unbill API-0 (out): 65536 of file arrived
	Unbill API-0 (out): 65536 of file arrived
	Unbill API-0 (out): 65536 of file arrived
	Unbill API-0 (out): 65536 of file arrived
	Unbill API-0 (out): 65536 of file arrived
	Unbill API-0 (out): 65536 of file arrived
	Unbill API-0 (out): 65536 of file arrived
	Unbill API-0 (out): 65536 of file arrived
	Unbill API-0 (out): 65536 of file arrived
	Unbill API-0 (out): 65536 of file arrived
	Unbill API-0 (out): 65536 of file arrived
	Unbill API-0 (out): 65536 of file arrived
	Unbill API-0 (out): 65536 of file arrived
	Unbill API-0 (out): 65536 of file arrived
	Unbill API-0 (out): 28680 of file arrived
	Unbill API-0 (out): file uploaded to  downloads/7de488f7cccd41a359b11810906cb314.jpg
	Unbill API-0 (out): Uploading avatar :)
	Unbill API-0 (out): { fieldname: 'file',
	Unbill API-0 (out):   originalname: 'cdv_photo_011.jpg',
	Unbill API-0 (out):   name: '7de488f7cccd41a359b11810906cb314.jpg',
	Unbill API-0 (out):   encoding: '7bit',
	Unbill API-0 (out):   mimetype: 'image/jpeg',
	Unbill API-0 (out):   path: 'downloads/7de488f7cccd41a359b11810906cb314.jpg',
	Unbill API-0 (out):   extension: 'jpg',
	Unbill API-0 (out):   size: 1360577,
	Unbill API-0 (out):   truncated: false,
	Unbill API-0 (out):   buffer: null,
	Unbill API-0 (out):   contentType: 'image/jpeg' }
	Unbill API-0 (out): Wed, 28 Jan 2015 17:18:24 GMT - POST /api/upload/avatar responded 200 in 42.549 ms - 127.0.0.1 - - Mozilla/5.0 (iPhone; CPU iPhone OS 10_10_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12B411 (2072514576)
	PM2: 2015-01-28 17:18:24: App closed with code: 143
	PM2: 2015-01-28 17:18:24: App name:Unbill API id:0 exited
	PM2: 2015-01-28 17:18:24: Process with pid 25037 killed
	PM2: 2015-01-28 17:18:24: Starting execution sequence in -fork mode- for app name:Unbill API id:0
	PM2: 2015-01-28 17:18:24: App name:Unbill API id:0 online
	PM2: 2015-01-28 17:18:24: INFINITE LOOP IN GOD ?
	Unbill API-0 (out): STATE: Production
	Unbill API-0 (out): Unbill API listening on port 3000
	Unbill API-0 (out): Mongoose Connected
	PM2: 2015-01-28 17:18:30: INFINITE LOOP IN WORKER ?

**Comment by sean-hill** [comment]
And,

    PM2: 2015-01-28 17:18:30: INFINITE LOOP IN WORKER ?

Keeps firing every 30 seconds

**Comment by jshkurti** [comment]
Don't worry about that I just forgot the console.log() since it's the branch I use for live support :)
The important part here is :
```PM2: 2015-01-28 17:18:24: App closed with code: 143```

**Comment by sean-hill** [comment]
What does that indicate?

**Comment by jshkurti** [comment]
It means the child process died with code 143.
I don't know yet what does it mean but it's good to know for sure :)
#investigating

**Comment by soyuka** [comment]
Could you remove the `"watch"       : true,` from your `processes.json` and try again?

Thanks.

**Comment by sean-hill** [comment]
YAYAYAY! That was it! Everything works great with `"watch": true` removed!

**Comment by sean-hill** [comment]
Ohhhh, maybe because I add a file to `./downloads` that pm2 tries to restart?

**Comment by soyuka** [comment]
Indeed....
You need to ignore the directory you're uploading too, if you don't want pm2 to restart your process when a change happened.

**Comment by sean-hill** [comment]
@Unitech, @soyuka, @jshkurti, @Tjatse thanks for helping me narrow this down.

**Comment by danpe** [comment]
Thanks guys! I had the exact issue!! you saved my day! 👍👍👍

**Comment by diegoddox** [comment]
I'm facing the same issue today and I do have turn off the `watch` but I'm still not able to upload the file, only by running `node api/server.js` any idea of what may be?
`node -v: 6.9.1`
`pm2 -v: 2.1.5`

my process.json

```
{
  "apps" : [
    {
        "name" : "pfsserver",
        "script" : "./api/server.js",
        "watch" : false,
        "env": {
            "NODE_ENV": "development",
            "PORT": 8081
        },
        "ignore_watch" : ["node_modules", "./api/assets/profile"],
        "env_production" : {
            "NODE_ENV": "production"
        },
        "log_date_format": "YYYY-MM-DD HH:mm Z"
    }
  ]
}
```

**Comment by sarya-alsayed** [comment]
@diegoddox , i have the same issue , please help me , any idea , how do you solve this issue ??

**Comment by diegoddox** [comment]
@sarya-alsayed , As you can see in my comment above the module `multer` was working fine if I run the command `node api/server.js` so in my case the issue was with the path.
### example:
```
├── mysite.com/
|   └── process.json
|   └── api/
|       └── server.js
```
 Because I was running the `process.json` from outside the `mysite.com` like
`pm2 start mysite.com/process.json` and this is the same as `node mysite.com/api/server.js`
and by doing so it will not work, but by doing `node api/server.js` works fine so I run the command from the site folder `pm2 start process.json`

hope that help!

**Comment by sarya-alsayed** [comment]
@diegoddox  thanks very much, i update the path of uploads folder in storage of multer and it is working , so now i can run **pm2 start myApp.js**  anywhere ..
thanks again
