### ISSUE TITLE
Is PM2 + node.js 0.11.X ready for production usage?

### ISSUE THREAD

**Issue by MaximF** [Unitech/PM2#965]
In PM2 requirements it is mentioned, that Node.js 0.11.14 is recommended to use for cluster mode.
But Node.js 0.11.14 is a beta release.

I'm wondering how stable is it at the moment? Can we us that version of node.js + pm2 in production?

Thank you in advance!

**Comment by soyuka** [comment]
If you use fork mode + node 0.10.x it's (safe-)ready for production usage. 

If you really want to use the cluster mode use node 0.11.14, it'll be more stable than 0.10.x.

**Comment by jshkurti** [comment]
From our experience, Node v0.11.x versions are always more stable than v0.10.x ones.
The cluster module stability status on 0.10.x is "Stability: 1 - Experimental" whilst on 0.11.x it is "Stability: 2 - Unstable" which is slightly better.
Moreover, several bug fixes have been applied to the cluster module on 0.11.15 (http://blog.nodejs.org/2015/01/20/node-v0-11-15-unstable/).
So if you wanna still take the risk of using cluster mode in production, I'd say go for Node 0.11.15 and generally 0.11.x if there are new releases anytime soon ;)

**Comment by MaximF** [comment]
Thank you, @soyuka and @jshkurti!
We will move forward with node.js 0.11.15 and pm2 in a clusterization mode to see how that would work for us. :)

**Comment by smrutimandal** [comment]
Hi,

We are using node 4.2.3. Can you please confirm if it is safe to run pm2 in clustering mode in production?
