### ISSUE TITLE
PM2 cleared my process list sometimes

### ISSUE THREAD

**Issue by brilvio** [Unitech/PM2#967]
Hello,

I have two Beaglebones Black with Debian, and one of them have a strange behaving.

In the Beaglebone that I have this problem I tried pm2 interact with Keymetrics, appears that when the Beaglebone doesn't have internet connection the PM2 list is cleared. How do I remove this interaction? 
I tried pm2 interact stop but didn't worked.

**Comment by jshkurti** [comment]
```pm2 interact delete```

**Comment by brilvio** [comment]
Keymetrics responded via email thanks.
