### ISSUE TITLE
run-as-user, root process, workarounds

### ISSUE THREAD

**Issue by zxqfox** [Unitech/pm2#971]
Since run-as-user option was removed in 0.12 I want to ask: Is there any workaround for that?

How I should run and inspect all my `PM2: God Daemon`s and their processes? Should it be a Universe or Ring process to rule them all?

Or should I run and watch many `God`'s for each user and collect data manually?

Also, you can search for runAsUser, runAsGroup, run-as-user, etc. and you'll find that many places in docs still has that information, as well as there are opened issues about it. It's very confusing ;-(

**Comment by uetkaje** [comment]
+1

**Comment by vmarchaud** [comment]
You can set a common $PM2_HOME env var for all your users, and they will share the same daemon but the daemon will be launched under the first user that will launch it.

**Comment by Unitech** [comment]
Feature added in upcoming PM2. To try it:

(Make sure pm2 is run as root to manipulate uid and gid)

```bash
$ pm2 save
$ pm2 kill
$ npm install Unitech/pm2#development -g
$ sudo pm2 resurrect
$ sudo pm2 start app --uid <uid>
# Now pm2 ls display the user running the script
$ pm2 ls
```

Feedback is welcome
