### ISSUE TITLE
https socket.io + pm2 cluster = Connection closed before receiving a handshake response

### ISSUE THREAD

**Issue by geekyme** [Unitech/PM2#974]
My chat server is running an express + socket.io setup. They listen on https port 8443. I do not have an nginx to route to 8443 and that is ok. 

I use pm2 to run a cluster mode on 2 CPUs.

Now when a client attempts to connect to my chat server, he gets

<pre>
WebSocket connection to 'wss://chat.abctest.com:8443/socket.io/?EIO=3&transport=websocket&sid=f3bvw3rY1cRf1YkCAAAA' failed: Connection closed before receiving a handshake response
</pre>

There is nothing peculiar in the logs that indicates this failure. 

Now when I run pm2 in fork mode, the client no longer sees that error. 

Please help.

**Comment by soyuka** [comment]
node version ? pm2 version ?

**Comment by geekyme** [comment]
node v0.11.15, pm2 12.3

**Comment by geekyme** [comment]
i thought it was related to this problem and i tried including that library but it didnt work too. https://github.com/indutny/sticky-session

**Comment by soyuka** [comment]
#389

**Comment by geekyme** [comment]
ok will follow the above discussion
