### ISSUE TITLE
Save actual log into a file?

### ISSUE THREAD

**Issue by Monsignor** [Unitech/PM2#976]
My server is crashing from time to time so I need to access the logs in order to troubleshoot it.

When I type `pm2 logs` I can see what's being logged in real time (for example, data being sent through `socket.io` etc). However, this data isn't being saved anywhere on the server, it seems.

When I open the log located at `/root/.pm2/pm2.log` it doesn't show any of the data that I see in the console. It just repeats `entering in node wrap logic` over and over again indefinitely. The `logs` directory only contains errors, not all data that you can see in real time. This is helpful to an extent, but I really need to see the data that caused the error, not just the error message.

What I need is to be able to see the real log, that is, everything that I can see in real-time by typing `pm2 logs`, but for the whole last 24 hours or so. This is necessary so I could compare the server crash times with the logs and see what caused them.

Is there a solution for this that I am missing?

**Comment by jshkurti** [comment]
```pm2 logs > yourlogFile.txt &``` :)

**Comment by Monsignor** [comment]
Ouch.
