### ISSUE TITLE
want to pm2 restart and reload to change config

### ISSUE THREAD

**Issue by SeungHam** [Unitech/PM2#978]
pm2 start process.js -l log.1

and i need to change logfile name, but i can't change it.

do not change the log's filename after pm2 start app.js ??

how to do it??

**Comment by lovio** [comment]
Pm2 is not good at handling logs.
The best practice is to use [log4js](https://github.com/nomiddlename/log4js-node)
In my case, I set up a Logstash+ElasticSearch+Kibana Log System and pipe the logs to it.

**Comment by soyuka** [comment]
http://stackoverflow.com/questions/28203820/how-to-separate-pm2-out-logs-by-time-daily-or-by-log-size related.

+1 @lovio

**Comment by SeungHam** [comment]
I don't want to add process...

want to sepaterate logs by only pm2 used.

This method be enough add process(logrotate or log4js)...?

**Comment by soyuka** [comment]
@SeungHam did you read the [pm2 logs documentation](https://github.com/Unitech/PM2/blob/master/ADVANCED_README.md#logs-management) ?

**Comment by SeungHam** [comment]
yes, i read it but I thought there is another way to resolve

**Comment by jshkurti** [comment]
You can now install the module pm2-logrotate `pm2 install pm2-logrotate` which will automatically rotate logs for each application running with PM2 including PM2 logs itself.

See https://www.npmjs.com/package/pm2-logrotate#configure for more info.
