### ISSUE TITLE
Option for process-management file location besides $HOME/.pm2

### ISSUE THREAD

**Issue by lamberta** [Unitech/PM2#980]
Trying to run pm2 as a *non-login/non-home-dir* user in a FreeBSD rc.d script. It looks like pm2 requires a home directory to write `.pm2/` process-management files to:

~~~
~# su -m www_daemon -c "pm2 start test.js"

[PM2] Spawning PM2 daemon
fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: EACCES, permission denied '/root/.pm2/pm2.log'
    at Object.fs.openSync (fs.js:439:18)
...
~~~

Can this directory be set in a nice way? I don't see a flag for it, maybe `--working-dir` or something? I seem to be able to get around it by setting the `HOME` environmental variable when running:

~~~
~# env HOME="/tmp" su -m www_daemon -c "pm2 start test.js"
~~~

**Comment by soyuka** [comment]
The best way to do this is to set the `PM2_HOME` environment variable to the directory of your wish.

**Comment by zxqfox** [comment]
@soyuka !!! Thanks!

**Comment by lamberta** [comment]
Cool, thanks.
If anyone's interested, here's a [FreeBSD rc.d startup script](https://gist.github.com/lamberta/80a4f49ebb7b07a8f9dc) for PM2 I've been playing with.

**Comment by soyuka** [comment]
@lamberta that's nice, would you mind pull-requesting the FreeBSD startup script?

The cli startup functions is located here: https://github.com/Unitech/PM2/blob/master/lib/CLI.js#L348.
