### ISSUE TITLE
Second start/reload/gracefulreload doesn't work in cluster mode

### ISSUE THREAD

**Issue by theolternative** [Unitech/pm2#981]
I'm clearly doing something wrong: I'm using Ubuntu 12.04, NodeJS 0.11.16 and PM2 0.12.4 but the same thing happens with every other version I tried (i.e. Node 0.10.36).
In fork mode everything works fine but in cluster mode even with 1 instance I'm not able to connect to webpages served by my app running on port 15000

I follow these steps. I start pm2 like this

    pm2 start processes.json
If I check connections:

    netstat -taupen | grep  15000
I get this:

    tcp        0      0 0.0.0.0:15000           0.0.0.0:*               LISTEN      0          36505       15376/PM2 v0.12.4:

Now I gracefulReload my instance (but the same thing happens with  start and stop  or reload):

    pm2 gracefulReload all
If I try to request a webpage from my browser there's no way to receive a response. This is what netstat returns:

    tcp        0      0 0.0.0.0:15000           0.0.0.0:*               LISTEN      0          36505       15376/PM2 v0.12.4: 
    tcp        0      0 127.0.0.1:49454         127.0.0.1:15000         ESTABLISHED 33         36859       836/nginx: worker p
    tcp     1410      0 127.0.0.1:15000         127.0.0.1:49454         ESTABLISHED 0          36860       15644/node 

If I reload the page:

    tcp        0      0 0.0.0.0:15000           0.0.0.0:*               LISTEN      0          36505       15376/PM2 v0.12.4: 
    tcp        0      0 127.0.0.1:49455         127.0.0.1:15000         ESTABLISHED 33         37071       836/nginx: worker p
    tcp        0      0 127.0.0.1:49454         127.0.0.1:15000         FIN_WAIT2   0          0           -               
    tcp     1410      0 127.0.0.1:15000         127.0.0.1:49455         ESTABLISHED 0          36861       15644/node      
    tcp        0      0 127.0.0.1:49457         127.0.0.1:15000         ESTABLISHED 33         37075       836/nginx: worker p
    tcp     1849      0 127.0.0.1:15000         127.0.0.1:49456         ESTABLISHED 0          37072       15644/node      
    tcp     1410      0 127.0.0.1:15000         127.0.0.1:49457         ESTABLISHED 0          37074       15644/node      
    tcp     1411      0 127.0.0.1:15000         127.0.0.1:49454         CLOSE_WAIT  0          36860       15644/node      
    tcp        0      0 127.0.0.1:49456         127.0.0.1:15000         ESTABLISHED 33         37073       836/nginx: worker p

Please note that I was using *recluster* before and everything was working fine. I'm collecting open sockets like these:
	
    server = app.listen(15000);
    server.on('connection', function(socket) {
        sockets.push(socket);
    });

in order to close them when I receive the shutdown message:

    process.on('message', function(msg) {
        if( msg != 'shutdown' ) { return; )
        if( sockets.length ) {
            console.log('Closing connections...');
            server.close( function() {
                console.log('All connections closed');
                process.exit(0);
            });
            sockets.forEach(function(socket) {
                console.log('Closing socket');
                socket.destroy();
            });
            setTimeout(function() {
                console.log('Couldn\'t close all connections');
                process.exit(0);
            }, 1500);
        } else {
            console.log('No open connections. Really closing now.');
            process.exit(0);
        }

I have a simple processes.json like this:

    { "apps":[
        {
        "name"             : "pscmyarea",
        "cwd"              : "/home/theolternative/www/_psconline/myarea/production/current",
        "script"           : "server.js",
        "error_file"       : "/home/theolternative/www/_psconline/myarea/production/current/logs/stderr.log",
        "out_file"         : "/home/theolternative/www/_psconline/myarea/production/current/logs/stdout.log",
        "run_as_user"      : "root",
        "run_as_group"     : "root",
        "instances"        : 1,
        "min_uptime"       : 1000, 
        "max_restarts"     : 15,
        "cron_restart"     : "1 0 * * *",
        "watch"            : false,
        "ignoreWatch"      : ["node_modules"],
        "merge_logs"       : true,
        "exec_interpreter" : "node",
        "exec_mode"        : "cluster",
        "port"        	 : 15000,
        "env": {
            "NODE_ENV": "production"
        }
    }]
    }

I'm really stuck.

**Comment by jshkurti** [comment]
Hey,

Is this still happenning to you ?
Can you show us some logs ? Is there any error thrown ?

Thanks.

**Comment by theolternative** [comment]
Hi,
I'm not using PM2 right now since I had a schedule and I needed a working solution asap.
There were no errors thrown. I was using the latest version of PM2 so if there's no new update, the problem still persists.
Let me know if there's any way I can help

**Comment by matAtWork** [comment]
Similar issue here. PM2 v0.12.5, Node v0.10.36 (via nvm), Ubuntu 14.04

A simple Express app listening on a port, works fine in "fork", and initially in "cluster" mode, but following a `pm2 restart all` the listen is essentially lost - the browser spins endlessly. An lsof after the second restart indicates that indeed, no listening socket has been created following the restart.

One observation - when restarting, the killing of the old processes is quite slow - maybe 1 sec each - almost like they are refusing to die nicely (nothing in ps -ef tho).

`pm2 kill && pm2 start myapp.js -i 4` brings it all back to life.

Any ideas as to where to start looking?

**Comment by Unitech** [comment]
@jshkurti inspected the issue deeply with the same use case than @theolternative but he has not managed to reproduce the bug

@matAtWork just don't use cluster mode with 0.10.36, upgrade to 0.12 to use it

**Comment by matAtWork** [comment]
Sadly I have some modules that don't (yet) work with v0.12. 

I'm guessing this is some environmental thing - probably permissions. I say this because we have 2 machines (both installed 'by hand'), and one is fine, one isn't. The difference was one initally had node 0.10.25 installed on it (from the Ubuntu PPA) and 'sudo npm install -g pm2'. It works. The second machine was installed with 0.10.36 via NVM, and 'npm install -g pm2' (no sudo) - it fails on restarting.

The first machine was 'upgraded' to NVM, etc....it stopped behvaving - so this looks like some 'sudo' vs user installation issue (creation of scripts/sockets/Satanic IPC??)

**Comment by buxihuanni** [comment]
@Unitech Is there some progress on this? I can also reproduce this on pm2 2.4.1 node 0.10.36.
