### ISSUE TITLE
Private Key passphrase

### ISSUE THREAD

**Issue by marcoschicote** [Unitech/pm2#983]
Hi
I new to PM2 and I have a problem that should be pretty common but I could not find the solution.
I'm trying to deploy a node app to a ec2 instance. Code for the node app is on github on a private repo. I created a public/private key pair for the user I use during deployment to access github. As I created the pair using a passphrase, I can't automate the deployment process and need to type the passphrase every time. Can't I make this process smoother? For now, I'm using a passphrase free key, but I fear this is not ideal.

Thanks!

**Comment by soyuka** [comment]
Passphrase free key are just fine ;).

**Comment by fernandoneto** [comment]
you can add a file to `~/.ssh/` with the name `config` and add your information there
