### ISSUE TITLE
how to insert multiple port?

### ISSUE THREAD

**Issue by Ohen** [Unitech/PM2#984]
json declaration

I start same process but, it have different ports.

just to do cli :   
pm2 start app.js -- -p 8001
pm2 start app.js -- -p 8002
pm2 start app.js -- -p 8003

only this way? i admin josn file through a process. 

add question : 

when a process restart, i want to work another process.

how to do? else, did not this function?

**Comment by Unitech** [comment]
You can use the "args" parameter in JSON conf to pass differents parameter to each app.
https://github.com/Unitech/PM2/blob/development/ADVANCED_README.md#json-app-declaration
