### ISSUE TITLE
arguments sanity check (especially for -i, --instances)

### ISSUE THREAD

**Issue by simonjosefsson** [Unitech/PM2#993]
Hi, I played around a bit with pm2 and missed setting a value for number of instances

At least on WIndows, running `pm2 start app.js -i --name "app"` is suicide (**only run this in a VM!**)

![pm2](https://cloud.githubusercontent.com/assets/3242316/6037077/75698500-ac4f-11e4-885c-02cfa73d2c1a.png)

I tried closing the terminals but the whole point of pm2 is to start them again... facepalm. Had to hard-reboot my machine when it became unresponsive.

Is there a usecase for running more processes than cores? If not maybe put a cap at that number or like 2x number of cores. At least something that's less than infinity =)

**Comment by soyuka** [comment]
Did you take this fix into consideration?
https://github.com/Unitech/PM2/issues/584#issuecomment-72720060

**Comment by simonjosefsson** [comment]
No, I installed 0.12.4 from npm. Will try it again with that patch

**Comment by simonjosefsson** [comment]
@echiu64's patch did not affect this (but seems to solve terminals popping up and closing).
See my PR #994 for a suggested fix

**Comment by soyuka** [comment]
:+1:
