### ISSUE TITLE
Read module implementation

### ISSUE THREAD

**Issue by CodersBrothers** [Unitech/PM2#997]
I use Read module (https://github.com/isaacs/read) for run my server securely, because I don't need a config file, and I don't need argvs that will be show with ``` history ``` linux command. I use read that gives a like ssh login feature, you can add passwords as hidden.
I don't like export vars feature, because its sowed.

But the problem is that I can't use this feature with pm2. Will be cool that pm2 will have a way to make something like this.

**Comment by CodersBrothers** [comment]
I'm looking for Programmatic way, maybe this can be a temporal solution if this executions not are logged in terminal history. https://github.com/Unitech/PM2/blob/development/ADVANCED_README.md#using-pm2-programmatically

**Comment by soyuka** [comment]
Sadly I don't think that using `readline` with pm2 would work or could ever be implemented.

A solution is too launch your configuration script on npm `post-install` [doc](https://docs.npmjs.com/misc/scripts).

**Comment by Unitech** [comment]
closing for now
